* 昨日2020年8月21日の朝から始めた決算報告書の作成，本日午後，会計監査を受け無事終了，長かった一日
  :LOGBOOK:
  CLOCK: [2020-08-22 土 19:15]--[2020-08-22 土 19:49] =>  0:34
  :END:

:CATEGORIES: 宇出津

〉〉〉：Emacs： 2020-08-22（土曜日）19：15　 〉〉〉

　興能信用金庫での町内協力金の締切が8月14日で，その日に銀行の営業が終了した直後に始めるべきだったのですが，出来心もあって会計監査前日の昨日21日の早朝から始めました。昨日の9時30分には旧能登町役場を集合に，役員4人が集まる用事もあって，旧柳田村に行っていました。

　ちょっと考えられないほどミスが続き，本来，中止となり，鎮疫祭という7月5日のご神事のみとなった，宇出津あばれ祭りの決算報告書でした。

　あばれ祭りだけでも2016年，2017年には同じ決算報告書を報告書を作成し，監査を受けています。2017年はちょっと違ったかもしれないですが，よく憶えていません。少なくとも一度は，同じ会計監査を自分が作成した決算報告書で受けています。

　容易に気がつけなかったという問題もいくつかあったのですが，自分でも考えられないミスがあって，確認だけでも相当の時間を使ったことになります。11,500を12,000とご入力していたことも大きいのですが，なにかに取り憑かれていたのではと思うようなミスが連発し，直前で解決しました。

　そもそも2009年3月15日から一度も仕事をしておらず，同年10月頃から生活保護の生活を続けている私に，全国放送のテレビ番組にも何度か取り上げられたことのある宇出津あばれ祭りの会計を任せられ，昨年からは通帳の管理も任されています。

　いろいろと考えるところもあって，これまで触れてこなかったところもあるのですが，これが実際のところで，会計監査を終えて，一息ついたところでもあります。次の会計監査は，9月の秋祭り，初詣，宇出津八坂神社での七日詣り，そして4月の曳山祭が終わった後に，一括した決算報告書となります。

　ようやく収支が一致したのは午後の0時過ぎでした，しかし，会計監査のときのも誤字が3つ，記載漏れが１つ指摘されました。他の役員の人は，私の間違えに気づいていたはずになります。それらしいことも言われましたが，前とは違って厳しい注意は受けませんでした。

　Twitterでも投稿直後に誤変換や入力ミスに気がつくことが多いので，間違ったままになっていることは少ないと思っていたのですが，それも怪しくなってきまいた。具体的に，「松明制作」，「令和2年、「あばれ祭り祭」会計帳簿を監査」となっていました。

　昨日は，この件で，宇出津の城野町，天徳町，夕方近くには新村浜という町内を回りました。今日の午前中は，栄町も回っています。偶然とは思えないところはありますが，私が気がつくのに遅すぎたということははっきりしています。

〈〈〈：Emacs： 2020-08-22（土曜日）19：49 　〈〈〈

