* 小倉秀夫弁護士が被害者安藤文さん家族の生活と人生に与えた影響

** これまでとは違う能登町防災訓練と，小倉秀夫弁護士による弁護士の社会的危険性の再認識

*** 「無実の既決囚が再審により無罪判決を受ける機会を奪ってまで、遺族が望む「一番重い刑」を死刑としておく必然性はないですね。」という深澤諭史弁護士にリツイートされた小倉秀夫弁護士のツイート

:CATEGORIES: 小倉秀夫弁護士,深澤諭史弁護士,再審請求

- RT fukazawas（深澤諭史）｜chosakukenho（小倉秀夫） 日時：2020/10/04 09:36／2020/10/04 09:34 URL： https://twitter.com/fukazawas/status/1312552055349805056 https://twitter.com/chosakukenho/status/1312551655032803328

> RT @chosakukenho: 無実の既決囚が再審により無罪判決を受ける機会を奪ってまで、遺族が望む「一番重い刑」を死刑としておく必然性はないですね。既に死刑制度が廃止されている国々では、「一番重い刑」が死刑でなくとも回っていますし。 https://t.co/ZsqR3HTGsq  

　さきほど深澤諭史弁護士のタイムラインでトップに表示されていました。そういえば，昨日の朝に視聴したAbemaPrimeでリモート出演の深澤諭史弁護士が，終わりの方でリツイートの責任について言及していました。これはあとで確認をした上，別の項目で取り上げます。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-04 10:02／2020/10/04 09:59 URL： https://twitter.com/kk_hirono/status/1312558629841563648 https://twitter.com/s_hirono/status/1312557842017050624  

> 2020-10-04-095134_深澤諭史さんがリツイート￼小倉秀夫@chosakukenho·16分無実の既決囚が再審により無罪判決を受ける機会を奪ってまで、遺族が望む「一.jpg https://t.co/7aYS5YBCm0  

　Twitterでよくあると感じることですが，タイムラインにあるツイートを個別に開くと，タイムラインの表示よりリツイートの数が増えていることがあります。今回もそれを予想したのですが，個別に開いてもリツイートの数は１つで，それも深澤諭史弁護士のリツイートだと確認しました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-04 10:14／2020/10/04 10:05 URL： https://twitter.com/kk_hirono/status/1312561683286564865 https://twitter.com/s_hirono/status/1312559506115584001  

> 2020-10-04-100426_小倉秀夫@chosakukenho無実の既決囚が再審により無罪判決を受ける機会を奪ってまで、遺族が望む「一番重い刑」を死刑としておく必然性は.jpg https://t.co/A572qLJh7D  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-04 10:14／2020/10/04 10:05 URL： https://twitter.com/kk_hirono/status/1312561704329330688 https://twitter.com/s_hirono/status/1312559433646436353  

> 2020-10-04-100410_小倉秀夫@chosakukenho無実の既決囚が再審により無罪判決を受ける機会を奪ってまで、遺族が望む「一番重い刑」を死刑としておく必然性は.jpg https://t.co/Vt3N0sqebh  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-04 10:14／2020/10/04 10:05 URL： https://twitter.com/kk_hirono/status/1312561718787108865 https://twitter.com/s_hirono/status/1312559360699113472  

> 2020-10-04-100351_小倉秀夫@chosakukenho無実の既決囚が再審により無罪判決を受ける機会を奪ってまで、遺族が望む「一番重い刑」を死刑としておく必然性は.jpg https://t.co/FIwUiyZxl7  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-04 10:14／2020/10/04 10:04 URL： https://twitter.com/kk_hirono/status/1312561736654843904 https://twitter.com/s_hirono/status/1312559288125063168  

> 2020-10-04-100340_小倉秀夫@chosakukenho無実の既決囚が再審により無罪判決を受ける機会を奪ってまで、遺族が望む「一番重い刑」を死刑としておく必然性は.jpg https://t.co/jLY8FOydEo  

　小倉秀夫弁護士のTwitter新規アカウントが出来て，しばらくすると死刑廃止に関連したツイートを多く見かけるようになりました。一過性で，これまでの反応に比較してもさほど大きな動きとも感じていないのですが，日弁連が強引に死刑制度廃止の採択をしたようです。

　昨日のことだと思いますが，どこにいたのか思い出せないですが，出先でスマホの画面を操作したところ，iphoneの最近の大きなアップデートで表示されるようになったニュースの主要項目があって，そこに死刑囚の息子の記事があってので，読んでみました。

*** 深澤諭史弁護士の出演したAbemaPrimeでの，リツイートの刑事責任についての発言

*** スマホの画面で目にした「｢愛犬家連続殺人｣死刑囚息子が語る壮絶な人生 | テレビ | 東洋経済オンライン | 経済ニュースの新基準」という記事

:CATEGORIES: 再審請求,死刑囚

- TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020/10/03 14:58 URL： https://twitter.com/hirono_hideki/status/1312270901585403905  

> ｢愛犬家連続殺人｣死刑囚息子が語る壮絶な人生 | テレビ | 東洋経済オンライン | 経済ニュースの新基準 https://t.co/DLrqa4ekG1  

　上記のツイートは，出先でスマホからツイートしたはずですが，時刻が昨日10月3日の14時58分となっています。思い出したのですが，これは自宅前でした。

　荷物の運搬を手伝ってほしいと頼まれ，自宅前で車が迎えに来るのを待っていたのですが，スマホの画面を表示させたところ，見出しの１つとして，愛犬家連続殺人｣死刑囚息子が語る壮絶な人生という記事が目に入ったのです。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-04 11:02／2020/10/04 11:01 URL： https://twitter.com/kk_hirono/status/1312573672717049856 https://twitter.com/s_hirono/status/1312573535840202752  

> 2020-10-04_103843＿スマホの画面（iphone）.png https://t.co/iGj5HQeqeK  

　説明がややこしいかと思ったので，実際のスマホの画面のスクリーンショットを作成しました。ニュースの主要項目のことだと思いますが，「見出し」となっています。

　記事の本文には埼玉愛犬家連続殺人事件とありますが，この事件のことは大きな報道があったという印象がありながら，内容をほとんどしらないという，他の事件とは一線を画する，個人的にかなり変わった位置づけの事件でした。

　記事には月日まで出ていないですが，冒頭に「1993年に埼玉県で愛犬家ら4人が相次ぎ失踪、その2年後の1995年、ペットショップを経営する男女が逮捕された。」とあります。桶川ストーカー殺人事件と共通したものを感じたのですが，私は拘置所で生活をしていた時期になります。

　1995年は平成7年で，福井刑務所で服役中でしたが，テレビでこの埼玉愛犬家連続殺人事件の報道をみたという記憶はなく，オウム真理教事件はよくみたと記憶にあるので，なにか矛盾したものを感じます。

　たぶんですが，平成7年の秋頃には2級生になっていたかと思います。福井刑務所では2級生になると，自主選択といって，自由にテレビのチャンネルを変えることが出来ました。毎日ではないですが，週に3日ほど19時からのNHKニュースをみることもできました。

　新聞を読む時間が長かったのも金沢刑務所とは異なる福井刑務所の特徴でしたが，新聞で埼玉愛犬家連続殺人事件の記事を読んだという記憶もありません。

　昨日に，この「｢愛犬家連続殺人｣死刑囚息子が語る壮絶な人生」という記事を読んで初めて知ったのは，夫婦が共犯として逮捕されていたこと，さらに夫婦揃って死刑判決を受けていたこと，夫が獄中で病死し，妻が再審請求を繰り返していたことです。

　ずいぶん前のことになりますが，この埼玉愛犬家連続殺人事件は，同じ埼玉県ということもありますが，本庄保険金殺人事件と混同していた時期がありました。考えてみると桶川ストーカー殺人事件も埼玉県になります。

```
殺人を行おうとする者が、共謀していない者を現場に呼ぶだろうか、という疑問が湧く。出所後に中岡が出した手記には、演歌を口ずさみながら風間が、遺体を牛刀で切り刻む様子が描かれている。その歌は手記では「河内おとこ節」。だが中岡の供述調書では、「大阪情話」だ。歌手はどちらも中村美律子だが、曲調はまるで違う。

　電話で話す機会が訪れ、その疑問をぶつけると、中岡は答えた。

「博子が演歌を歌ってたなんて、ありゃあ嘘だからね。そういうふうに書かなきゃ、おもしろくないでしょ。ノンフィクションみたいにはなってるけど、あれは小説だから」

［source：］埼玉愛犬家連続殺人事件から25年　冤罪を訴える風間博子死刑囚からの手紙 (4/5) 〈dot.〉｜AERA dot. (アエラドット) https://dot.asahi.com/dot/2019122800007.html?page=4
```

　上記の引用部分も驚いたのですが，連続殺人が発覚し，逮捕の決め手となったのもこの中岡という人物のようです。前の部分になるのですが，そちらも引用します。

```
事件の犠牲者たちは、いずれも関根と関わりがあった。埼玉県警は当初から彼を疑っていたが、物証が見つからず翌年になっても捜査は進展しなかった。

　アフリカケンネルの名目上の役員であったのが、中岡（仮名）である。結婚したばかりの妻が詐欺事件で逮捕されたことで、1994年11月、中岡は自ら埼玉県警に連絡し、任意の事情聴取に応じた。殺人を犯したのは関根と風間であること、群馬県片品村にある中岡の自宅で死体の処理が行われた、と自分も犯行の一部に関わったことを供述した。彼の案内で片品村の山林から、多数の骨粉や犠牲者のものであったロレックスなどが見つかった。

　関根と風間は、年の明けた1995年1月5日に逮捕された。同じ日、中岡の妻は釈放された。

　1月8日に逮捕された中岡は、2人とは別に裁判を受け、死体損壊・遺棄罪で3年の懲役に服した。

［source：］埼玉愛犬家連続殺人事件から25年　冤罪を訴える風間博子死刑囚からの手紙 (3/5) 〈dot.〉｜AERA dot. (アエラドット) https://dot.asahi.com/dot/2019122800007.html?page=3
```

　「結婚したばかりの妻が詐欺事件で逮捕されたことで、1994年11月、中岡は自ら埼玉県警に連絡し、任意の事情聴取に応じた。」とありますが，これは実質的な別件逮捕であったと考えられ，それも本人ではなく妻を警察がターゲットに狙ったことになりそうです。

```
風間の再審請求弁護人、内山成樹弁護士は言う。

「私たちが風間さんが殺人に関与していないと確信している大きな理由は、風間さんが殺人の共犯だと言っていた張本人の中岡が、風間さんは死刑になってはいけないと法廷で証言していることです。今後も、再審を勝ち取るべく頑張ります」

　現在、東京高裁で審理されている第2次再審請求は、山上とのトラブルを風間が知らなかったことを裏付ける、取り調べ時の供述だ。

［source：］埼玉愛犬家連続殺人事件から25年　冤罪を訴える風間博子死刑囚からの手紙 (5/5) 〈dot.〉｜AERA dot. (アエラドット) https://dot.asahi.com/dot/2019122800007.html?page=5
```

　記事は5ページに分かれていますが，最後の5ページ目に「風間の再審請求弁護人、内山成樹弁護士は言う。」という弁護士の名前が出てきました。

　大きな事件の再審請求で，弁護士の名前が出てこないことは前にもあったと思っていたので，今回も同じなのかと考えていたのですが，これは意外でした。さらにこの弁護士の名前をGoogleで検索したところ，次も信じがたいような弁護士業界の内幕が垣間見えてきました。

*** 「埼玉愛犬家連続殺人事件から25年　冤罪を訴える風間博子死刑囚からの手紙」というネット記事に対する反応，主として弁護士，ジャーナリストらのツイートの記録

```
(py37_env) ➜  ~ kk2020-09_ajx-all-user-mysql-REGEXP_blogger.rb "愛犬家連続殺人"
SELECT * FROM tw_user_tweet WHERE  tweet REGEXP "愛犬家連続殺人"   ORDER BY tw_date ASC
hirono_hideki
奉納＼さらば弁護士鉄道・泥棒神社の物語（hirono_hideki）
ユーザ名称：奉納＼さらば弁護士鉄道・泥棒神社の物語 [screen_name]ユーザ名：hirono_hideki フォロー数：4278 フォロワー数：4294 ツイート数：197762
a_hosokawa
細川　敦史（a_hosokawa）
ユーザ名称：細川　敦史 [screen_name]ユーザ名：a_hosokawa フォロー数：730 フォロワー数：5156 ツイート数：12712
tk84yuki
🍙高橋ユキ🍙（tk84yuki）
ユーザ名称：🍙高橋ユキ🍙 [screen_name]ユーザ名：tk84yuki フォロー数：1169 フォロワー数：13574 ツイート数：35906
chemicalgroom
ゴルーグ２８号（chemicalgroom）
ユーザ名称：ゴルーグ２８号 [screen_name]ユーザ名：chemicalgroom フォロー数：80 フォロワー数：1610 ツイート数：74432
kk_hirono
刑事告発・非常上告＿金沢地方検察庁御中（kk_hirono）
ユーザ名称：刑事告発・非常上告＿金沢地方検察庁御中 [screen_name]ユーザ名：kk_hirono フォロー数：489 フォロワー数：564 ツイート数：118507
REGEXP：”愛犬家連続殺人”／データベース登録済みツイート：2020年10月04日12時13分の記録：ユーザ・投稿：5／18件
```

　上記のまとめ記事を作成してから気がついたのですが，対象とした記事の日付を未確認だったことで，確認をしたところ驚いたことに，2019年12月29日11時30分という昨年の記事でした。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜mikimobilephone（水野美紀） 日時：2020-10-04 12:27／2020/10/02 18:13 URL： https://twitter.com/kk_hirono/status/1312595154264449024 https://twitter.com/mikimobilephone/status/1311957500883800064  

> 10/4（日）20:00〜 フジテレビ系「実録ドラマ 3つの取調室 〜埼玉愛犬家連続殺人事件〜」の放送です！ ⠀ 誰が嘘をついて誰が本当の事を言っているのか… 刑事と犯人たちの攻防をテレビの前で目撃してください！ ⠀ #3つの取調室  #フジテレビ  #水野美紀  ⠀⠀ 【by staff】 https://t.co/ZszyEYp3tp  

 - 愛犬家連続殺人 - Twitter検索 / Twitter https://twitter.com/search?q=%E6%84%9B%E7%8A%AC%E5%AE%B6%E9%80%A3%E7%B6%9A%E6%AE%BA%E4%BA%BA&src=typed_query

　Twitterの検索から弁護士のツイートを探そうとしたのですが，昨年12月29日の記事がなぜ今頃，話題になっているのか理解が出来ました。そういえば昨日もテレビ放送のような話は見ていたのですが，すでに放送済みのものとばかり思い込んでいました。

　検索でトップに表示されたツイートを一つ読んだところ，10月4日，今夜の放送だとわかりました。すぐに番組予約を入れたのですが，昨夜に久しぶりに録画の操作をしたところ，10月3日で録画が止まっていて，たまったいたものを削除して，新たに予約を入れました。

　最初はNHKのドラマでした。タイトルが気になって予約を入れようと思ったのですが，予約を入れた直後に，民放で恐怖新聞のドラマがあることに気が付き，そちらにも予約を入れたところ，重複というメッセージが出ましたが，そのまま予約を入れておきました。

　テレビドラマの恐怖新聞は，前にTwitterのトレンドで知ったのですが，すぐに忘れてしまって，放送をみることもなかったものです。眠さもあったので事前に予約を入れたのですが，開始から番組を視聴していたものの，たぶん終わりの方で寝てしまい，気がつくと終わっていました。

　寝ていたのは短い時間だったと思うのですが，それまでみていた恐怖新聞のドラマがとても時間が長く感じられるものでした。ドラマの筋もわかりづらいところがあって，漫画の恐怖新聞とは全くの別物ということはよくわかりました。

　今，録画を確認したところ，気になって予約を入れた番組が，「【よるドラ】彼女が成仏できない理由（４）」でした。続く録画が「オトナの土ドラ・恐怖新聞　＃６」となっています。

　名前がはっきりしないのですが，たぶん黒木瞳という女優が，主人公らしい若い女性の母親役で，その母親が連続殺人事件の犯人だと告白した辺りまで，記憶にあるのですが，そのときもだいぶん眠かったのか，曖昧模糊としたところもあります。

　「愛犬家連続殺人 - Twitter検索 / Twitter」でスクロールダウンしながら弁護士のツイートを探したのですが，１つも見かけず，次から次に再読込が繰り返されるので，終わりも見えずやめにしました。しかし，これはかなり大きな反応ではないかと思われます。




*** 埼玉愛犬家連続殺人事件，風間博子死刑囚の再審請求弁護人，内山成樹弁護士が業務停止1年の懲戒処分になったという預貯金約5000万円や不動産の譲渡で強制執行を妨げ報酬3800万円の受領








