* 定額給付金で買った代引き手数料，送料込みで15万ちょっとの新しいパソコン，期待をいくらか超えるぐらいの告発状作成及び弁護士脳の記録の作業環境
  :LOGBOOK:
  CLOCK: [2020-07-13 月 20:57]
  :END:

:CATEGORIES: パソコン

〉〉〉：Emacs： 2020-07-13（月曜日）20：57　 〉〉〉

　注文したのが7月10日金曜日のお昼12時頃，配達が届いたのが昨日7月12日日曜日の午前10時40分頃でした。お昼過ぎにはUbuntuつまりLinuxのインストール作業を始めていたのですが，これまで経験がないほど失敗続きで，難航しました。

　今朝になってようやくうまくいかない原因に気がついたのですが，この原因で思わぬ不具合が続出し，ハードウェア構成が新しすぎるためLinuxののドライバが対応しきれていないのかと疑ったほどでした。失敗の原因はパーティションの選択にありました。

　最初にプリインストールされたWindows10の起動に躓いたいたのですが，パソコンでは原因は使ったことがなかったHDMI端子で，しばらく経ってからモニターの端子を抜いて挿し直すと，すぐにモニターにパソコンの画面が表示されました。最初から荒れ気味の船出でした。

　500GBのSSDと2TBのハードディスクがついたパソコンでした。Windows10でSSDのパーティションを縮小しLinuxをインストールする領域を作ったのですが，ハードディスクは，とりあえずのつもりで600GBをパーティション分割し，Windows10用にNTFSでフォーマットしました。

　Linuxで1番目のハードディスクはsdaになるのですが，そこに32GBのスワップ領域と残りをLinuxをインストールするパーティションとして割り当てたのです。これがまずかったのはそのサイズが1.6TBもあったことだと思います。

　これまで最高のスペックのパソコンなのにやたらとインストールに時間が掛かっていました。このインストール前にもWindows10でDVD-RにUbuntuのISOイメージの書き込みに連続して失敗し，6枚ほどディスクをダメにしました。これまで経験のない中途のエラーでした。

　以前にISOイメージを買い込んだUSBがあったのですが，最後にDVD-Rディスクをダメにした直後，見つからなかったものを見つけることが出来，それでUbuntuのインストールを始め，それで時間がかかったり，途中にエラーが出ていました。

　ようやくUbuntuのインストールが出来て，起動したあとも，起動や終了にずいぶんと時間がかかりおかしかったのですが，MySQLのすべてのデータベースのインポートが終了しないという問題が起きていました。コマンドを実行し，エラーが出ないもののプロンプトが返らないのです。

　朝になって，dfコマンドを実行したところ，SSDにインストールしたものと思い込んでいたUbuntuが実際にはハードディスクにインストールされ，それも1.6TBのパーティションをルートにしていたことに気が付きました。

　2020-07-13_084938＿.jpgというスマホの写真があるのですが，dfコマンドの結果を撮影したものです。そのあと2020-07-13_092303＿.jpgの写真には，Ubuntuのインストールが完了したというメッセージの表示があります。

　これもちょうど昼の12時頃には，ほとんどのインストール，設定作業を終えていました。大きなファイルのコピーも終わっていたように思います。135GBのファイルをネットワーク経由でコピーしたことになります。送りてのパソコンのスペックもあるので，それなりに時間は掛かっていました。

　午後もこまかい作業はありました。スクリプトの実行にエラーが出て，必要なライブラリー，モジュールのインストールなどしていました。夕方には前のパソコンの環境とほぼ同じように使えるようになり，新しいパソコンで更新したデータベースも古いパソコンのデータベースにコピーしました。

　思い切った買い物ではあったのですが，概ね期待以上の処理能力と安定感です。なにより意外だったのはパソコンの静音性で，ちょっとどうなのかと思うぐらいCPUや冷却ファンが高回転しません。言い換えればそれほど負荷を掛ける処理はしていないことになります。

　GPU付きのディスクトップパソコンは2回目になりますが，前回というのも平成16年辺りに，当時あった穴水町の自作パソコンショップで購入したものでGPUは中古品だと聞いていました。当時はGPUのことも余り理解していませんでした。

　Ubuntuで標準のシステムモニターには，CPUの16のコアの使用率が色分けで表示されています。これはWindows10のシステムモニターにはないものですが，Windows10にあったGPUの表示がないのは少し残念です。

　ブラウザを２つ立ち上げたままで，外でもアプリを立ち上げたまま前のパソコンだと不具合を起こさないためのぎりぎりという慣れた作業状態ですが，メモリの使用は5.1GB，CPUのコアはまばらに高いグラフで25％前後という安定感です。

　はるかに上には上の高スペックのパソコンはいくらでもあると思いますが，個人的には劇的変化で，メモリが16GBになったのも今回が初めて，たぶん触ったのも初めてかもしれません。出だしが暴風雨に巻き込まれるような状況だったので，なおさら手に入れた安定感を強く感じます。

〈〈〈：Linux Emacs： 2020-07-13（月曜日）21：59 　〈〈〈

