* 市役所支所に爆破予告文を郵送した疑い　岐阜県関市の市議会議員（67）逮捕　（メ〜テレ（名古屋テレビ））　-　Yahoo!ニュース
  :LOGBOOK:
  CLOCK: [2020-06-29 月 20:10]--[2020-06-29 月 20:31] =>  0:21
  :END:

:CATEGORIES: 業務妨害

〉〉〉：Emacs： 2020-06-29（月曜日）20：10　 〉〉〉

　10分ほど前になりますか，Twitterのトレンドで知ったニュースになります。

 - 市役所支所に爆破予告文を郵送した疑い　岐阜県関市の市議会議員（67）逮捕　（メ〜テレ（名古屋テレビ）） - Yahoo!ニュース https://news.yahoo.co.jp/articles/d367cc1661cd222e9a320f635ce4a0bc52e9f49c  

　このような爆破予告のニュースは，数年前，珠洲市市役所でもありました。金沢工業大学でもあったと記憶にありますが，逮捕に至らないことが多かったという印象で，逮捕されても若年層のいたずら目的がほとんどであったように思います。

 - » 爆破予告文 - Twitter検索 / Twitter https://t.co/f3jHaSQPcf

　最初，「岐阜県関市」としてTwitterのトレンドで見ていたものが，別のブラウザでは「爆破予告文」だけのトレンドになっていました。現在は再捜査要請書＿警察庁・石川県警察御中（@kk_hirono）でログインしているGoogle Chromeがそのブラウザになります。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜livedoornews（ライブドアニュース） 日時：2020-06-29 20:18／2020/06/29 19:06 URL： https://twitter.com/kk_hirono/status/1277562139587166216 https://twitter.com/livedoornews/status/1277543871161884673  

> 【防犯カメラから浮上】市役所に爆破予告文、関市の市議を逮捕 岐阜 https://t.co/ix7Z5mgxit  爆破予告文を市役所の事務所に郵送し、市職員に爆発物の捜索をさせ、業務を妨害した疑い。認否は明らかにしていない。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜nhk_news（NHKニュース） 日時：2020-06-29 20:18／2020/06/29 18:31 URL： https://twitter.com/kk_hirono/status/1277562175767244800 https://twitter.com/nhk_news/status/1277535257017737216  

> 市役所に爆破予告文送った疑い 関市議会議員を逮捕 岐阜 関 #nhk_news https://t.co/9zDFa1G1VN  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜bungu42（ぶんぐ） 日時：2020-06-29 20:19／2020/06/29 20:06 URL： https://twitter.com/kk_hirono/status/1277562329555582976 https://twitter.com/bungu42/status/1277559024443985920  

> 関市の市議・太田博勝容疑者(67)を逮捕 関市役所の上之保事務所に爆破予告文を郵送 現在5期目で議長を務めたことも 現職の市議でしかも議長も務めた事があるベテランが市役所に爆破予告文を送るとか世も末ですな。 何を拗らせた ...… https://t.co/QUjtPLjiqf  

　今日は午後から一度もテレビをつけていないのですが，NHKでテレビニュースになっているのかもしれません。市議会議員が5期目で，議長を務めたこともある，という情報が出ています。顔写真も出ていますが至って思慮深く真面目そうにみえる人物です。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜mainichi（毎日新聞） 日時：2020-06-29 20:23／2020/06/29 19:30 URL： https://twitter.com/kk_hirono/status/1277563333244104706 https://twitter.com/mainichi/status/1277549873479458817  

> 岐阜県警関署は、爆破予告文を関市役所の支所に郵送したとして、威力業務妨害の疑いで、関市の67歳市議を逮捕。認否は明らかにしていません。 https://t.co/2lV8Cwp5oW  

　上記の毎日新聞のツイートにもありますが，「認否は明らかにしていません。」という情報が目立っていて，それもかなり気になっています。

　岐阜県関市といえば，刃物の町で有名で，日本刀の神事もテレビで何度か見たことがありました。そのような歴史と伝統のある土地柄もあるようです。

〈〈〈：Linux Emacs： 2020-06-29（月曜日）20：30 　〈〈〈

* 女子大生殺人事件　「自分の名前がSNSで拡散されている」被害者が警察に相談　静岡・沼津市（静岡朝日テレビ）　-　Yahoo!ニュース
  :LOGBOOK:
  CLOCK: [2020-06-29 月 20:31]
  :END:

:CATEGORIES: 警察

〉〉〉：Emacs： 2020-06-29（月曜日）20：31　 〉〉〉

 - 604：2020-06-29_20:27:55 ＊ 市役所支所に爆破予告文を郵送した疑い　岐阜県関市の市議会議員（67）逮捕　（メ〜テレ（名古屋テレビ））　-　Yahoo!ニュース https://hirono-hideki.hatenadiary.jp/entry/2020/06/29/202753

　上記に取り上げた記事に，「アクセスランキング（東海）」の2位として見かけたニュースになります。1位も同じ事件のニュースのような見出しとなっています。

 - 女子大生殺人事件　「自分の名前がSNSで拡散されている」被害者が警察に相談　静岡・沼津市（静岡朝日テレビ） - Yahoo!ニュース https://news.yahoo.co.jp/articles/ea31185a97d9cd611f1b8353880c7b626f89bd07  

　この記事にも「警察は容疑者が容疑を認めているかどうか明らかにしていません。」とあります。

```
今年1月、警察に相談「SNSで名前が拡散されている」
　捜査関係者によりますと、女子大生は今年1月、自分の名前などをSNSで拡散されていると警察に相談していたということです。警察は、この相談と事件の関連も調べています。

［source：］女子大生殺人事件　「自分の名前がSNSで拡散されている」被害者が警察に相談　静岡・沼津市（静岡朝日テレビ） - Yahoo!ニュース https://news.yahoo.co.jp/articles/ea31185a97d9cd611f1b8353880c7b626f89bd07?page=2
```

　上記の引用部分も気になったところです。「今年1月、警察に相談「SNSで名前が拡散されている」」が小見出しのようになっており，記事の締めくくりのようにもなっています。

　今日も思い出して考えていたのですが，金沢西警察署刑事課強行主任は安藤健次郎さんや被害者安藤文さんについて，「安藤さんって誰ですか？」という明らかにとぼけたようなことを今のところ最後となっている電話で私に話していたことです。

```
沼津市西浦久連の女子大学生（19）が自宅近くの路上で刺殺された事件で、殺人未遂容疑で現行犯逮捕された三島市壱町田、大学生の男（20）が、女子大学生に一方的に好意を寄せていたとみられることが29日、捜査関係者への取材で分かった。沼津署は男が女子大学生と連絡が取れなくなったことへの逆恨みで犯行に及んだ可能性もあるとみて、2人の関係や動機を詳しく調べる。

　同署は同日午前、殺人容疑で男を静岡地検沼津支部に送致した。

　捜査関係者によると、男は女子大学生を刺したことを認めているとみられる。事件前に女子大学生から警察への相談はなかったという。凶器の刃物は現場で見つかり、同署が押収している。

［source：］容疑者、一方的に好意か　沼津・女子大生刺殺（＠S［アットエス］ by 静岡新聞SBS） - Yahoo!ニュース https://news.yahoo.co.jp/articles/e9b46fb1c70d962bb2dcaaa557df7add34100125
```

　被疑者は20歳の大学生の男となっていますが，実名は出ていません。よくみると「三島市壱町田」という住所は出ているようです。「逆恨みで犯行に及んだ可能性」という朝から深澤諭史弁護士のツイートで気になっていたワードも出ている記事になります。

 - 「助けてください、助けてください」　静かな集落に叫び声、何度も　沼津の女子大生殺害｜静岡新聞アットエス https://www.at-s.com/news/article/social/shizuoka/780435.html  

　あまり見たことがないような衝撃的で印象に残るニュース記事の見出しとなっています。恐怖で声が出せない被害者もいると聞きますが，この記事に込められたなにかを感じるところがあります。

　よくみると被害者の名前も「女子大学生（１９）」と匿名になっているようです。これも弁護士基準の適用事例となるのかもしれません。記事には27日土曜日の白昼の事件とあります。このところテレビを見ている時間が少なくなっていますが，テレビで報道は見ていない事件です。

* ＜竹かばん職人＞竹の鞄ＧＥＮ（浜松市天竜区）｜静岡新聞アットエス

:CATEGORIES: テレビ

 - 「助けてください、助けてください」　静かな集落に叫び声、何度も　沼津の女子大生殺害｜静岡新聞アットエス https://www.at-s.com/news/article/social/shizuoka/780435.html  

　上記の記事の「ニュースアクセスランキング」6位として見かけた記事になりますが，ちょうど昨夜，日曜日の夜のポツンと一軒家の放送でみたところでした。途中までは台所に行ったり集中をしていなかったのでわからなかったのですが，竹細工で静岡県というのも意外でした。

　ゴミ出しの時間と，買い物に行く時間が片道1時間と聞いたように思うのですが，それも驚きでした。初めの頃はテレビを余り見ていなかったので，場所がよくわからなかったのですが，買い物に片道1時間というのは，ポツンと一軒家でも特別と思いました。

```
　かばん作りは１１～１２月の新月の頃、真竹を山から切り出すことから始まる。「満月にたっぷりと蓄えた水や養分を、竹は新月で吐き出す。水や養分が少ない竹は害虫やカビが生えるリスクが低い」。最適なのは水脈に近い場所にある３～４年生の竹。水が豊富な地に育った竹は節間が長く、大きなかばん作りに使いやすいからだ。

［source：］＜竹かばん職人＞竹の鞄ＧＥＮ（浜松市天竜区）｜静岡新聞アットエス https://www.at-s.com/news/article/featured/culture_life/shigoto_zekkei/652195.html
```

　記事は2019年7月1日11時00分とあります。昨夜のポツンと一軒家も，再放送の再取材で，このところ新型コロナの影響と思われるパターンでした。

　昨夜（2020年6月28日日曜日）のポツンと一軒家は，番組の途中のCMで，「必殺仕事人２０２０」の番宣を見たのも印象的で，今夜９時ということでした。前年は２月あたりの放送であったように思いますが，年に一度となっていると思われる番組のことはすっかりと忘れていました。

* 「石川県警の防犯コールセンター」を名乗り「 空請求で　県内の女性５８８０万詐欺被害｜NNNニュース」と，親だましたテーマだった昨夜の必殺仕事人２０２０

:CATEGORIES: 石川県警察

　20時47分にテレビをつけ，すぐにNHKにチャンネルを変えたところこのニュースがありました。ネットで調べたところ，２つしかニュースが見つかっていません。Googleのニュースで見つかったのは次の日テレNEWS24ですが，文字列の範囲選択も出来ない設定となっています。

 - » 架空請求で　県内の女性５８８０万詐欺被害｜NNNニュース https://t.co/eWIZFJhy7n

 - » 石川県警察 - Google 検索 https://t.co/cFKy4d9K7a

　上記の検索で，「ニュース」を指定しています。この検索では同じ1ページ目に次の初めて知る石川県内ニュースを見つけました。気になる内容のニュースです。

```
羽咋署によると、忍さんが林道で軽貨物車を運転していて右の前後輪が側溝に落ちて、家族らに助けを求めた。駆け付けた容疑者が運転し、道路側に戻そうとして前方にいた忍さんに衝突した。

［source：］酒気帯びで息子ひいた疑い、石川　車側溝に落ち戻す途中、意識不明：東京新聞 TOKYO Web https://www.tokyo-np.co.jp/article/35494
```

 - » 石川県警察 - Google 検索 https://t.co/zuymFOmYZp すべて，24時間以内のオプション指定

```
警察によりますとことし２月、県内の７０代の女性の自宅に、警察を名乗る男から、「あなたの個人情報が複数の会社に登録されている」と電話があり、削除するための会社として教えられた番号に電話したところ「登録を削除します」と言われるとともに会員番号を教えられました。
その後、自然復興のボランティア団体を名乗る男から「子どもたちのためだ」として会員番号を教えて欲しいという電話があり、女性は男に会員番号を教えました。
すると、今度は個人情報を削除したとする会社から、「ボランティア団体が不法行為をした。会員番号を教えたあなたにも責任がある」と電話があり、保証金を支払うよう命じられ、女性は５月までに手渡しや振り込みであわせて５８８０万円をだまし取られました。

［source：］特殊詐欺で５８００万円余の被害｜NHK 石川県のニュース https://www3.nhk.or.jp/lnews/kanazawa/20200629/3020005310.html
```

　上記の引用は，20時45分からのNHKの石川県内ニュースでみたのとほぼ同じ内容なのですが，その内容というのが昨夜，テレビの必殺仕事人2020で観たのと，共通点がありました。全国的にも大きなニュースにはなっていないようです。少しテレビを付ける時間が遅れれば知らずに終わったかも。　

```
石川県警によりますと、能登地方に住む７０代の女性は今年２月、実在しない「防犯コールセンター」を名乗る男から個人情報が複数登録されていると電話を受けました。

　女性は、男の指示通り“個人情報を削除する手続き”を行い、この際ウソの会員番号を受けとります。

　その後、別の男が「この番号が不法行為を行うボランティア団体に渡った」といいがかりをつけ、女性から保証金名目で１０回にわけ、５８８０万円をだまし取ったということです。

　県警は大がかりな詐欺グループが存在していると見ています。５８８０万円は特殊詐欺では今年に入って最も高い被害額です。

［source：］きっかけは1本の電話…70代女性が5880万円騙し取られる 大規模な特殊詐欺グループが関与か（石川テレビ） - Yahoo!ニュース https://news.yahoo.co.jp/articles/5bdf4de8e4cc6ae198934f3b463764201796b712
```

　少しGoogleの検索方法を変えたことで見つけた記事ですが，この記事ではテレビのニュースにもなかった「石川県警によりますと、能登地方に住む」という情報があります。テレビのNHKとNHKのネットニュースでは，「子どもたちのためだ」というのがとりわけ印象的な報道でした。

 - » きっかけは1本の電話…70代女性が5880万円騙し取られる 大規模な特殊詐欺グループが関与か https://t.co/BmnHJV7NX2

　全国ニュースとして観ていないのが気になるところですが，前出の「日テレNEWS24」だと全国ニュースになるのかもしれません。深夜に放送が今もあるのだと思いますが，アディーレ法律事務所のニュースなど，他では見ないニュースをテレビで見かけたことがありました。

　騙されたのは能登地方の住む70代女性とありますが，70代と聞くとまだまだ判断力がしっかりしているという印象があります。５８８０万円という被害額も高額です。それも石川県警察を騙った詐欺であったとのことです。全国ニュースになっていないのが重ねて気になります。

* 史上最多1240万円、裁判費用クラウドファンディング　「大崎事件」を800人が支援（弁護士ドットコム）　-　Yahoo!ニュース

:CATEGORIES: 大崎事件,クラウドファンディング,鴨志田裕美弁護士,弁護士ドットコム,再審請求

```
これまで、裁判所が3回も再審開始を認める決定を出しているが、検察の抗告で覆されてきた。

第3次再審請求では、地裁・高裁の再審開始決定を最高裁が史上初めて取り消している（2019年6月）。検察の特別抗告を「理由がない」と退けつつ、職権による調査で「破棄自判」したものだ。

2020年にも、殺人であることを否定する医学鑑定などを新証拠として、第4次の再審請求をおこなっている。「事故なのに警察が見立てを誤った」（佐藤博史弁護士）と考えているという。

CFの成功について、弁護団事務局長の鴨志田祐美弁護士は、「800人からの1240万円が何を意味しているのか。最高裁とどちらが正義なのか、社会が答えを出してくれている」と力を込めた。

集まった支援金は、裁判費用のほか、再審制度の改正をめざす活動にも活用するという。

［source：］史上最多1240万円、裁判費用クラウドファンディング　「大崎事件」を800人が支援（弁護士ドットコム） - Yahoo!ニュース https://news.yahoo.co.jp/articles/2dd1f2d78d9416d695b441601dbf39633dc14b5d
```

　ブラウザのブックマークにしている鴨志田裕美弁護士のTwitterタイムラインで見つけた記事になります。久々の更新ツイートでもあったようです。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜kamo629782（かもん弓（鴨志田 祐美）） 日時：2020-06-29 23:43／2020/06/29 18:39 URL： https://twitter.com/kk_hirono/status/1277613583270993920 https://twitter.com/kamo629782/status/1277537223114539008  

> 「800人からの1240万円が何を意味しているのか。最高裁と(我々の)どちらが正義なのか、社会が答えを出してくれている」  https://t.co/pbcOYPmEon  

　やっているつもりでいたのですが，ツイートのまとめ記事の記録を行っていなかったようです。現在，処理の実行中です。鴨志田裕美弁護士のタイムラインでは，5時間前という表示のツイートで，その前のツイートが6月27日と表示されています。

 - 2020年06月29日23時44分の登録： ＼かもん弓（鴨志田 祐美）　@kamo629782＼「800人からの1240万円が何を意味しているのか。最高裁と(我々の)どちらが正義なのか、社会が答えを出してくれている http://hirono2014sk.blogspot.com/2020/06/kamo6297828001240.html

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-06-29 23:47／2020/06/29 23:42 URL： https://twitter.com/kk_hirono/status/1277614623529689088 https://twitter.com/s_hirono/status/1277613323400253448  

> 2020-06-29-220843_かもん弓（鴨志田祐美）@kamo629782·3時間「800人からの1240万円が何を意味しているのか。最高裁と（我々の）どちらが正義なのか、社会が答えを.jpg https://t.co/jcYqFGYa6U  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-06-29 23:47／2020/06/29 23:42 URL： https://twitter.com/kk_hirono/status/1277614641456111617 https://twitter.com/s_hirono/status/1277613396796403717  

> 2020-06-29-221101_史上最多1240万円、裁判費用クラウドファンディング　「大崎事件」を800人が支援（弁護士ドットコム）　-　Yahoo!ニュース.jpg https://t.co/mEEdKvD3eI  

　「史上最多1240万円、裁判費用クラウドファンディング　「大崎事件」を800人が支援」という記事の見出しですが，クラウドファンディングのホームページでは大勢の弁護士と思われる写真がありました。

　先日，調べて確認をしたところですが，この大崎事件では1千万円の赤字となった弁護士がいるとのことです。「史上最多1240万円、裁判費用クラウドファンディング」とありますが，一人の弁護士でも補填を賄うのが余裕のない金額となりそうです。

　そんなことを気にかけていたところ，「CFの成功について、弁護団事務局長の鴨志田祐美弁護士は、「800人からの1240万円が何を意味しているのか。最高裁とどちらが正義なのか、社会が答えを出してくれている」と力を込めた。」という記事が出てきました。

　他の弁護士らの反応も乏しいようです。クラウドファンディングが弁護士業界にプラスになったとは思えないところで，なにか別の事実を露呈する結果になったとも思えるところです。佐藤博史弁護士の名前も記事は出ています。ＰＣ遠隔操作事件で疑問の大きな著名弁護士です。

