* コマンドラインからメールで添付ファイルをgmailに送信する方法

:CATEGORIES: メール,コマンドライン

% mutt -a 添付ファイル -s "サブジェクト（件名）" -a 添付ファイル -- アカウント@gmail.com < メールの本文となるテキストファイル

　最終的に見つけたのが上記の方法です。10年以上前に同じことをやったと記憶にあるのですが，当時とはまったく違っていると思います。他にも方法があったのですが，nonameという空の添付ファイルが付くという問題がありました。次がそれになります。

% (uuencode 添付ファイル名 < 添付ファイル名; echo "メールの本文") |mailx -s "サブジェクト（件名" "アカウント@gmail.com"

　メールの本文をファイルとして指定するのは多少面倒ではありますが，スクリプトのテキストファイルだと，コードがそのまま本文になります。次のスクリプトを作成しました。自動化すれば，一度に沢山の処理ができます。

```
#!/bin/bash

FILE=$1
mutt -a "${FILE}" -s $FILE -a "${FILE}" -- アカウント@gmail.com < "${FILE}"
```

　以下は，昨夜，Googleで検索しながら参考にさせてもらったページです。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-08 09:44／2020/09/08 04:13 URL： https://twitter.com/kk_hirono/status/1303131996835602432 https://twitter.com/hirono_hideki/status/1303048742019280897  

> shell — Muttを使用して直接メールを送信する方法は？ https://t.co/uwKlzcjVoo  -iの代わりにstdinで本文をフィードします。  mutt -a file -s "Subject of Mail" -a file -- test@example.com &lt; bodyTextFile  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-08 09:44／2020/09/08 04:11 URL： https://twitter.com/kk_hirono/status/1303132015131205632 https://twitter.com/hirono_hideki/status/1303048360346021888  

> - Postfix+Dovecotによるメールサーバーの構築 - Akionux-wiki https://t.co/PoSCmWmRQN  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-08 09:44／2020/09/08 03:02 URL： https://twitter.com/kk_hirono/status/1303132042058592256 https://twitter.com/hirono_hideki/status/1303031010292985856  

> - uuencodeコマンドの使い方： UNIX/Linuxの部屋 https://t.co/HCpn4FKa7x  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-08 09:44／2020/09/08 02:58 URL： https://twitter.com/kk_hirono/status/1303132067643838465 https://twitter.com/hirono_hideki/status/1303029989881704448  

> - mailxコマンドで本文と日本語ファイル名の添付ファイルを同時に送信する方法 - Qiita https://t.co/GwIFEkvNJw  

* HyperEstraierという2007年に開発が止まっている全文検索エンジンのライブラリを使い，Mewのメールの本文を検索

:CATEGORIES: Emacs,メール

```
Hyper Estraier（はいぱー・えすとれいや）は、日本で開発された全文検索エンジンのライブラリである。ライセンスはLGPLで提供されている。

［source：］Hyper Estraier - Wikipedia https://ja.wikipedia.org/wiki/Hyper_Estraier
```

　今調べたのですが，「最新版	1.4.13 / 2007年12月24日」とあります。昨夜も，ずいぶん古そうなライブラリーなので半信半疑でインストールをしたのですが，コンパイルもすんなり短時間で終わりました。

```
Mewでメール本文を検索 HyperEstraier
Mewは基本機能として、grepによるメール検索ができるが、検索対象がSubjectやToなどのヘッダフィールドに限られており、メール本文を検索することができない。メール本文を検索するには、拡張機能のHyper Estraierを使うと良い。 (Mewのマニュアルにある、「日本語の全文検索をしたい場合は、"mg" をインストール」という話は古いので、mgは使わないこと。) Ubuntuの場合、hyperestraierパッケージをインストールすれば、依存するものもすべて入る、、、はずだったが、このパッケージは16.04(Xenial)を最後にその後は提供されなくなった。以後は自力で野良インストールするしかない。もう古いソフトなので、メンテしてくれる人がいなくなってしまったようだ。

［source：］Ubuntu Linux 20.04 設定メモ - Qiita https://qiita.com/j0306043/items/5666e67bcbfd099be7d5#mew%E3%81%A7%E3%83%A1%E3%83%BC%E3%83%AB%E6%9C%AC%E6%96%87%E3%82%92%E6%A4%9C%E7%B4%A2-hyperestraier
```

　上記のページを参考にインストールしました。

```
sudo apt install libc6-dev zlib1g-dev libqdbm-dev

tar zxvf hyperestraier-1.4.13.tar.gz 
cd hyperestraier-1.4.13/
./configure
make
make check
sudo make install
```

　次が，インストールに必要なパッケージがダウンロードできるページです。リンクを開くとダウンロードが始まりました。

```
ダウンロード
以下のパッケージをダウンロードしてください。

最新のソースパッケージ（バージョン1.4.13）

［source：］全文検索システム Hyper Estraier https://dbmx.net//hyperestraier/index.ja.html
```

　Mewは，メールの件名と本文を別に検索できるらしく，それもMewを活用しようと思った理由の1つです。ブログのタイトルに相当するのがメールのサブジェクト（件名）ですが，記事の本文と切り離し別々に検索できるのは，編集画面ならばある機能なのかもしれないですが，今のところ見たことがありません。

　このMewの検索は，マークを付けることでフォルダ移動などの振り分け，つまり整理整頓ができることになります。

* 表計算ソフトと，EmacsのメールリーダMewのドラフト（下書き保存）を連携，活用したこの後の告発状の作成方針

:CATEGORIES: メール,お知らせ

　試行錯誤でいろいろやっていたのですが，昨夜，ようやく目途というかかたちができたように思います。次が表計算ソフトの対象行をテキストとしてコピーしたものになります。

済	告発の事実	市場急配センター	被告発人安田繁克	松浦さんの愛人の息子として入社した被告発人安田繁克（平成元年9月？）	
	告発の事実	市場急配センター	被告発人安田繁克	松浦さんの愛人の息子として入社した被告発人安田繁克（平成元年9月？）	ほぼ同じ頃に入社した西口君と名古屋の元暴力団員S藤
	告発の事実	市場急配センター	被告発人安田繁克	松浦さんの愛人の息子として入社した被告発人安田繁克（平成元年9月？）	長く勘違いしていた，入社のきっかけとなった被告発人安田繁克の母親の愛人
済	告発の事実	市場急配センター	被告発人安田繁克	被告発人安田繁克と被告発人大網健二との接点（平成2年春か秋）	
	告発の事実	市場急配センター	被告発人安田繁克	被告発人安田繁克と被告発人大網健二との接点（平成2年春か秋）	宇出津のK村さんと姫のNさんという被告発人大網健二と市場急配センターの接点
	告発の事実	市場急配センター	被告発人安田繁克	被告発人安田繁克と被告発人大網健二との接点（平成2年春か秋）	被害者安藤文さんを市場急配センターに紹介したともされる，笹田君と峰田君
	告発の事実	市場急配センター	被告発人安田繁克	被告発人安田繁克と被告発人大網健二との接点（平成2年春か秋）	笹田君と被告発人大網健二の中古車販売を巡るトラブル
	告発の事実	市場急配センター	被告発人安田繁克	被告発人安田繁克と被告発人大網健二との接点（平成2年春か秋）	中古のBMW

　次がMewの+draftフォルダのサマリーになります。これもテキストとしてコピペをしています。

  09/07 To:hirono2012@ 告発の事実/市場急配センター/被|                         1    
  09/07 To:hirono2012@ ほぼ同じ頃に入社した西口君と名|                         3    
  09/07 To:hirono2012@ 長く勘違いしていた，入社のきっ|                         4    
  09/07 To:hirono2012@ 被害者安藤文さんを市場急配セン|                         5    
  09/07 To:hirono2012@ 笹田君と被告発人大網健二の中古|                         6    
  09/07 To:hirono2012@ 宇出津のK村さんと姫のNさんとい|   

　サマリーで下書きメールの内容を表示したものです。再編集には対象のメールを選択肢た状態でEとコマンドを打ちます。

```
To: アカウント@gmail.com
Subject: 告発の事実/市場急配センター/被告発人安田繁克/被告発人安田繁克と被告発人大網健二との接点（平成2年春か秋）/中古のBMW
From: 廣野秀樹 <アカウント@gmail.com>
Fcc: %Sent
X-Mailer: Mew version 6.8 on Emacs 26.3

/告発の事実/市場急配センター/被告発人安田繁克/被告発人安田繁克と被告発人大網健二との接点（平成2年春か秋）/中古のBMW

```

　言葉ではご説明もしきれないので，スクリーンショットを用意しました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-08 10:49／2020/09/08 10:47 URL： https://twitter.com/kk_hirono/status/1303148319846346757 https://twitter.com/s_hirono/status/1303147888038432768  

> 2020-09-08-104308_Mewのdraftフォルダ，下書きメールの表示.jpg https://t.co/QMfYJLth89  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-08 10:49／2020/09/08 10:47 URL： https://twitter.com/kk_hirono/status/1303148341463674880 https://twitter.com/s_hirono/status/1303147960989958144  

> 2020-09-08-104330_Mewのdraftフォルダ，下書きメールの編集.jpg https://t.co/zfjQ8sjsxk  

　表計算ソフトは，Windows10ではExcel，Linuxの環境ではLibreOfficeのCalcを使っていきます。ずいぶん前から漠然としたアイデアはあったのですが，行の挿入やセルのコピーが容易なので，使い始めてみると，予想以上に使えそうです。データ全体の見通しもよい気がします。

* 
