* 「ネット上の誹謗中傷が話題ですが，「悪口一つで２００万円３００万円当たり前」はもちろん真実ではありません。」という深澤諭史弁護士のツイート
  :LOGBOOK:
  CLOCK: [2020-08-03 月 07:34]--[2020-08-03 月 07:47] =>  0:13
  CLOCK: [2020-08-03 月 00:14]--[2020-08-03 月 00:53] =>  0:39
  :END:

:CATEGORIES: 深澤諭史弁護士,誹謗中傷,本人訴訟

〉〉〉：Emacs： 2020-08-03（月曜日）00：14　 〉〉〉

　まず，Twitterの仕様で意外な発見があったのですが，返信のツイートとコメント付きリツイートは別物であることが，この深澤諭史弁護士のツイートでの発見となりました。よく考えてみるとツイートのURLを含むか含まない違いですが，これまで混同をしていたようです。

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2020/07/31 17:45 URL： https://twitter.com/fukazawas/status/1289120028378279938  

> ネット上の誹謗中傷が話題ですが，「悪口一つで２００万円３００万円当たり前」はもちろん真実ではありません。  
> 一方で「訴えられても大丈夫。本人訴訟で争えば，判例にしたがって相場で５０万円以下で済む」も嘘です。  
> 近時の同種事件，被告だけ本人訴訟で５０万円切る判決は一件も見当たりません。  

　返信のツイートは２つあって，1つ目が深澤諭史弁護士本人の次のツイートになりますが，これも気になる内容のものとなっています。

- TW fukazawas（深澤諭史） 日時： 2020/07/31 17:45 URL： https://twitter.com/fukazawas/status/1289120030584500224  

> 誤字があったので修正。  
> 不法行為に基づく損害賠償請求事件で，損害額が，「判例」で決まるとか，出所は不明だが，そういう相談が多いんですよ・・・。  
> （・∀・；）  

　見比べると，7月31日17時45分のツイートに，同時刻の返信をしています。一瞬目を疑ったのですが，60秒以内ということなのでしょう。後のツイートに，「誤字があったので修正」とありますが，修正箇所が不明で，前のツイートを読み返しても誤字はなさそうです。

　私がTwitterを好み積極的に使っている理由の1つでもあるのですが，ブログやFacebookと違い，ツイートは編集ができないはずです。たまに見かけることもあるのですが，前のツイートを削除した上での再投稿になり，その旨を明示するのも例外を見たことがありません。

　コメント付きリツイートが6件となっているのですが，タイムラインに表示があるのは3件です。表示されないのは非公開設定のアカウントであったり，見たことも聞いたこともないですが，アカウントの設定で非表示を選択できるのではとも考えるところです。

　3件のコメント付きリツイートのうち2件は，深澤諭史弁護士のツイートの内容に懐疑的なものであり，これはとても珍しく感じました。

　1つは，だいぶん前からときどき見かけたアカウントで，プロフィールに弁護士という明示はなかったですが，法アニクラスタ，企業法務ブロガーなどとあり，プロフィールの名前を見直すと弁護団団員とあります。弁護士以外の弁護団団員は聞いたことがないのですが，あり得ないことでもなさそうです。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜bit_lawyer（ちょ） 日時：2020-08-03 00:34／2020/07/31 21:09 URL： https://twitter.com/kk_hirono/status/1289947601245093889 https://twitter.com/bit_lawyer/status/1289171441405923329  

> そうなんですか？50万以下ケースもありそうだけど。公表裁判例という限定ならわかりますが https://t.co/lN6ZkguDtW  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ahowota（QB被害者対策弁護団団員ronnor） 日時：2020-08-03 00:34／2020/07/31 18:37 URL： https://twitter.com/kk_hirono/status/1289947729863430144 https://twitter.com/ahowota/status/1289133115697315841  

> 「一件も見当たりません」という投稿は、リーガルリサーチによって裏付けられるべき。ブログ等に投稿された名誉毀損等について、被告らのみ本人訴訟、原告ら訴訟代理人ありの事案で、原告一人につき最大でも22万円の賠償しか認められなかった東京… https://t.co/KrlwTcZC1V  

　本人訴訟だと大きな不利益になる可能性を印象づけ，弁護士を代理人にすると大きな効果があると印象づけるのも深澤諭史弁護士に顕著にみられる特徴になります。

　そもそも名誉毀損の損害賠償で50万を超える認容額の方が滅多にみかけない気がします。そういえば，日付が変わっていますが，夕方の早い時間になるのか，読んでいた池田信夫氏のWikipediaにもそれらしい判決を見かけたように思いました。

```
ブログ記事をめぐる訴訟［編集］
上杉隆との名誉毀損裁判［編集］
池田のブログ記事の一部をめぐり、上杉隆から名誉毀損で削除を求められていた裁判で、2015年3月16日、東京地裁は池田と上杉の双方に50万円を支払うよう命じた［34］。一審では池田のブログ記事削除を命じられたが［34］、池田は控訴した［35］。

二審では一審で命じられた池田が上杉に支払う損害賠償が却下され、上杉によるブログ記事の削除請求が却下されたため［36］ 当該ブログ記事［37］［38］ は再度掲載されている。

弁護士・伊藤和子との名誉毀損裁判［編集］
2016年11月24日、弁護士でNPO法人「ヒューマンライツ・ナウ」の事務局長を務める伊藤和子から名誉毀損で損害賠償を求められた裁判で、約57万円の支払いを命じられる。国連特別報告者マオドが「日本の女子高生の13％が売春している」と虚偽情報［39］ を発信した事件について、池田はその情報源が伊藤であると断定し、「法廷内外で協力して伊藤を追放すべし」と述べたが、伊藤の関与が全く証明されず、名誉毀損であったと裁判所に認められたものである［40］。

［source：］池田信夫 - Wikipedia https://ja.wikipedia.org/wiki/%E6%B1%A0%E7%94%B0%E4%BF%A1%E5%A4%AB
```

　ちょっと記憶とは違ったのですが，上杉隆氏の方は，ちょうど50万円，それも双方に50万円の支払いを命じたとあります。2例目が，伊藤和子弁護士との裁判で，こちらは記事を読みながら金額を見た記憶がなかったのですが，約57万円の支払いを命じられたとあります。

　上杉隆氏は最近ほとんど名前をみかけないのですが，Twitterのフォロワー数を上杉軍30万などとツイートされているのを見かけた覚えがあり，かなりの著名人のようでした。著名人の方が失われるものを多く，損害額は多くに認定されそうですが，無名の一般人の方が高くなるとは考えにくいです。

　なかには一方的にやりすぎた名誉毀損や誹謗中傷というのはあると思いますが，そればかりではないと思います。しかしそれをごく自然でありがちなことのように印象づける訴求性が顕著なのも，深澤諭史弁護士ならではの特徴となります。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜xzbuR98XchTOgZ8（NOT PROFIT） 日時：2020-08-03 00:51／2020/07/31 17:56 URL： https://twitter.com/kk_hirono/status/1289952040685363200 https://twitter.com/xzbuR98XchTOgZ8/status/1289122646278332417  

> 弁護士費用考慮したら認容額が多少高額でも本人訴訟か選ぶメリットはありそう（そもそも誹謗中傷するなっていう話やけど） https://t.co/Tqa69ZbdVS  

　上記が3件目となっているコメント付きリツイートですが，今まで私にはなかった視点でなるほどと思いました。

〈〈〈：Emacs： 2020-08-03（月曜日）00：53 　〈〈〈

〉〉〉：Emacs： 2020-08-03（月曜日）07：34　 〉〉〉

 - 2020年08月03日07時28分の登録： REGEXP：”悪口一つで２００万円３００万円当たり前”／データベース登録済みツイート：2020年08月03日07時27分の記録：ユーザ・投稿：15／19件 http://hirono2014sk.blogspot.com/2020/08/regexp2020080307271519.html

```
アカウント名	ツイート数	リツイート数
深澤諭史（fukazawas）	1	0
Document35（document35）	0	1
TｰTAKA（TGN54）	0	1
中野 俊徳（kanonjilawfirm）	0	1
okumuraosaka（okumuraosaka）	0	1
非常上告-最高検察庁御中_ツイッター（s_hirono）	4	0
inマイdreams（bengobengostory）	0	1
リーチ一発ツモ裏１（luckymangan）	0	1
Pokomoko（Pokomoko5）	0	1
FANZAは直樹（depon2010）	0	1
おるぐり（allgreen76b）	0	1
⚖法律系Vtuberじゃこにゃー⚖（Jakotsunya）	0	1
地方在住弁護士@地方で悩む人を応援（chihoben）	0	1
刑事告発・非常上告＿金沢地方検察庁御中（kk_hirono）	2	0
奉納＼さらば弁護士鉄道・泥棒神社の物語（hirono_hideki）	1	0


［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”悪口一つで２００万円３００万円当たり前”／データベース登録済みツイート：2020年08月03日07時27分の記録：ユーザ・投稿：15／19件 http://hirono2014sk.blogspot.com/2020/08/regexp2020080307271519.html
```

　最低1件は，深澤諭史弁護士自身のリツイートがあるはずで，昨夜はそれをみて取り上げておくことにしたのですが，なぜかデータベースの情報が反映されていないらしく，ツイートが1件のみとなっています。

 - （15／19） TW s_hirono（非常上告-最高検察庁御中_ツイッター） 日時： 2020-08-03 00:05:00 +0900 URL： https://twitter.com/s_hirono/status/1289940513370431488

> 2020-08-03-000337_深澤諭史さんがリツイート深澤諭史@fukazawas·7月31日ネット上の誹謗中傷が話題ですが，「悪口一つで２００万円３００万円当たり前」は.jpg https://t.co/421rqbNafJ

　上記の19件中15件目のツイートがスクリーンショットの記録で，撮影日時が2020-08-03-000337，この時点で深澤諭史弁護士のタイムラインの固定されたツイートの真下，最新のツイートとして表示されています。

　同業の弁護士のリツイートが割と多いのだと確認しました。性犯罪の刑事弁護でスペシャリストのように評価されることもある大阪の奥村徹弁護士のリツイートもあります。名誉毀損のことは手がけた案件として見かけないですが，示談交渉等の専門家でもあるのでしょう。

　「悪口一つで２００万円３００万円当たり前」という話も，たまたま1人か2人が発言したという話はあるのかもしれないと思いますが，そんなに一般化されるような話とは思えないところです。不要な萎縮効果も与えそうな気がします。

〈〈〈：Emacs： 2020-08-03（月曜日）07：47 　〈〈〈

