* 大量不当懲戒請求のカンパ，嶋﨑量弁護士とは別，北周士弁護士と佐々木亮弁護士の振込口座が一緒になっていた，嶋﨑量弁護士と佐々木亮弁護士のツイートの記録
  :LOGBOOK:
  CLOCK: [2020-08-01 土 00:33]--[2020-08-01 土 12:36] => 12:03
  :END:

:CATEGORIES: 懲戒請求,北周士弁護士,嶋﨑量弁護士,佐々木亮弁護士,カンパ

〉〉〉：Emacs： 2020-08-01（土曜日）00：33　 〉〉〉

```
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb shima_chikara 'カンパ' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "shima_chikara") AND  tweet REGEXP "カンパ"  ORDER BY tw_date ASC
REGEXP：”カンパ”／嶋﨑量（弁護士）（@shima_chikara）の検索（2018-05-09〜2020-03-13／2020年08月01日00時18分の記録45件）
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb ssk_ryo 'カンパ' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "ssk_ryo") AND  tweet REGEXP "カンパ"  ORDER BY tw_date ASC
REGEXP：”カンパ”／ささきりょう（@ssk_ryo）の検索（2011-08-06〜2020-05-23／2020年08月01日00時26分の記録26件）
```

　面倒だったのですが，北周士弁護士とは違い，嶋﨑量弁護士と佐々木亮弁護士のツイートは，同じカンパをキーワードにしたTwitter検索から全てのツイートをデータベースに登録する作業を行い，そのデータベースに基づくまとめ記事を作成，投稿しました。

　何度かご紹介していると思いますが，まとめ記事の作成と投稿は，1つの自作コマンド（スクリプト）で実行しています。以前は，Twitter検索のソースからツイートのURLをスクレイピングの処理で一度に取得できたのですが，それが困難となって手作業となっています。

 - 2020年08月01日00時18分の登録： REGEXP：”カンパ”／嶋﨑量（弁護士）（@shima_chikara）の検索（2018-05-09〜2020-03-13／2020年08月01日00時18分の記録45件） http://hirono2014sk.blogspot.com/2020/08/regexpshimachikara2018-05-092020-03.html

　まずは嶋﨑量弁護士のツイートです。まとめ記事を時系列で見ながら，これはと思うツイートに絞ってリツイートをしていきたいと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:42／2018/05/09 17:53 URL： https://twitter.com/kk_hirono/status/1289224972850720768 https://twitter.com/shima_chikara/status/994138178842906624  

> 私もカンパしました（笑） https://t.co/y4eE6f1oLr  

　すでにリツイート済みですが，上記の1番目になる嶋﨑量弁護士のツイートは，次の北周士弁護士のツイートを引用リツイートしたものになります。嶋﨑量弁護士のツイートは2018年5月9日，北周士弁護士のツイートは同年4月27日となっています。

- TW noooooooorth（ノ ー ス ラ イ ム） 日時： 2018/04/27 17:19 URL： https://twitter.com/noooooooorth/status/989781133880582144  

> #不当懲戒 に対応するための費用のカンパをお願いするための口座を作成しました。本件では今後懲戒請求者等に対し民事・刑事上の責任を追及していく予定ですが相応の費用がかかります。少しでも皆さまのお力添えを頂けますと幸いです。 https://t.co/XvxFh3Gor9  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:46／2018/05/10 21:07 URL： https://twitter.com/kk_hirono/status/1289225972810539009 https://twitter.com/shima_chikara/status/994549570326556672  

> 「佐々木弁護士は･･･『請求に基づく弁護士会の調査を受けており、本業に物理的な支障が出ている。気味が悪く、精神的な苦痛も味わった』と話す。２人は全請求者に損賠賠償請求訴訟を起こし、虚偽告訴罪や業務妨害罪での刑事告訴も検討･･･カンパも募り、すでに５００万円近い提訴資金を集めた」  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:46／2018/05/10 21:05 URL： https://twitter.com/kk_hirono/status/1289226028162748416 https://twitter.com/shima_chikara/status/994549073595191297  

> 社会問題となりつつあるようですね。 ⇒　弁護士：大量「懲戒請求」返り討ち　賠償請求や刑事告訴も - 毎日新聞 https://t.co/5zzPz89U72  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:47／2018/05/12 11:10 URL： https://twitter.com/kk_hirono/status/1289226151269867523 https://twitter.com/shima_chikara/status/995124076791255041  

> #不当懲戒請求 への法的措置をとるか否かの主たる考慮要素は、既存の依頼者や活動への影響。そこを克服するのは、頼りになる同僚含む仲間であり、最後は「お金」。相当額の実費もかかるし、手間暇はお金で買えるので影響を最小限にできる。 それで、カンパに頼ることにしました（現在口座開設中）。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:47／2018/05/12 11:15 URL： https://twitter.com/kk_hirono/status/1289226203786694656 https://twitter.com/shima_chikara/status/995125385175052288  

> 全国にいる仲間の存在は大きい。私の懲戒請求書は肩書きで「日本労働弁護団事務局長」とあった。私は昨年11月まで日本労働弁護団（1700名）の事務局長の仕事を活動の中心にしていた。労働運動で志を同じくする弁護士が全国にいるのでご助力をお願いする予定。その際カンパを活用したい。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:48／2018/05/15 12:04 URL： https://twitter.com/kk_hirono/status/1289226425774432258 https://twitter.com/shima_chikara/status/996224737247350785  

> 現在、私に対し591件の懲戒請求があり、同種被害状況等から全体で960件の懲戒請求があるようです。 被告数600人・請求額1人30万円でも、郵券・印紙代だけで300万を超える実費が予想されます。カンパは、主にこの民事訴訟の実費（郵券・印紙代）として使用を予定しております。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:48／2018/05/15 12:06 URL： https://twitter.com/kk_hirono/status/1289226498709192704 https://twitter.com/shima_chikara/status/996225185022857216  

> 使用内容につきましては、TwitterやFacebook等で報告させていただきます。 カンパに余剰が生じた場合、同様の被害にあった弁護士のため活用させていただく予定で、引継先等も同様にご報告します。 皆さまのお力添えを頂戴できますと幸いです。何とぞよろしくお願い致します。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:48／2018/05/16 14:57 URL： https://twitter.com/kk_hirono/status/1289226557882372096 https://twitter.com/shima_chikara/status/996630661439021056  

> 昨日開始したカンパ、１日で１０６件８６万７６０９円集まりました。ありがとうございます！ 個別返信が追いつかず漏れている方、申し訳ありません。 金額もですが、100人以上が支援してくれていることが、力になります。 お金が集まれば取れ… https://t.co/kUR2CxW3Sc  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:49／2018/05/16 15:00 URL： https://twitter.com/kk_hirono/status/1289226642598924288 https://twitter.com/shima_chikara/status/996631568549535744  

> カンパ大喜利というより、昔のご依頼者や、お付合いのある組合関係者や研究者、あとは直接のご面識もない弁護士さんが多いです。Twitterでの告知をみていただいた方だろう。ありがとうございますm(__)m  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:49／2018/05/16 15:19 URL： https://twitter.com/kk_hirono/status/1289226722940919809 https://twitter.com/shima_chikara/status/996636298143137793  

> 一番強力なカンパは、アマテラスオオミカミ　様、これ最強。ツタンカーメン　様も多分強い。 アンパンマン　様も強いが、ジャムおじさんの助けがないと心細いか？乞うご期待。 とはいえ、タサキ　スシロー　様もいれば、チェゲバラ　様もいるから、メンバーは多彩。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:49／2018/05/17 19:56 URL： https://twitter.com/kk_hirono/status/1289226782143471616 https://twitter.com/shima_chikara/status/997068321563422721  

> 本日15時時点で187名から129万8152円ものカンパをいただきました。ありがとうございますm(__)m 引き続き、宜しくお願いします。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:50／2018/05/19 00:39 URL： https://twitter.com/kk_hirono/status/1289226847989796865 https://twitter.com/shima_chikara/status/997501904006533120  

> #高プロ強行採決 もピンチだし、#不当懲戒 で煩わしいが、今日は良いことも。 カンパを直接事務所に届け応援メッセージくれた方が二人。１人は遠路はるばるTwitterみてお仕事の合間に、もうお１人は担当する争議当事者。多くの方のカン… https://t.co/ko9JPVZglO  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:50／2018/05/21 23:03 URL： https://twitter.com/kk_hirono/status/1289226934514155520 https://twitter.com/shima_chikara/status/998564879714811904  

> 本日15時時点で、271人から201万8401円のカンパをいただきました。本当にありがとうございますm(__)m メンバーも多彩。ウヨクン　様とか、アベアキエイノリマス　さんとか。グンマチャンもありがとう。そして、沢山の法クラの皆… https://t.co/e4XhCpRKRg  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:50／2018/05/24 08:21 URL： https://twitter.com/kk_hirono/status/1289226999160901632 https://twitter.com/shima_chikara/status/999430264462848000  

> 本当にそのとおり。 ノースライム先生や私など被害を受けた弁護士の被害回復に向けた法的措置が、結果として、懲戒制度の健全化に向けた動きにも資するなら、やり甲斐もあるます。 弁護士や弁護士の活動に賛意を示す多くの方からのカンパは、これ… https://t.co/z98sTl3yTg  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:50／2018/05/30 23:36 URL： https://twitter.com/kk_hirono/status/1289227061274398720 https://twitter.com/shima_chikara/status/1001834654624722944  

> 本日30日時点で326人の方から251万7369円のカンパをいただきました。ありがとうございますm(__)m 昔のご依頼者とか、前の職場の関係者とか。長らくお目にかかっていない方々、個別にご挨拶できず申し訳ありません。 現依頼者や… https://t.co/oq99GlJxE7  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:51／2018/05/30 23:42 URL： https://twitter.com/kk_hirono/status/1289227122435710976 https://twitter.com/shima_chikara/status/1001836198376030208  

> 現在、カンパ募集はネット上だけやっているのですが、弁護士になる前の知人、長らくお目にかかっていない方からも沢山カンパをいただき、本当に嬉しいです。 あと、みんなTwitterみてくれてたんだな・・というが分かったのは驚きでした。感謝。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:51／2018/05/30 23:45 URL： https://twitter.com/kk_hirono/status/1289227248231256065 https://twitter.com/shima_chikara/status/1001837074805223424  

> 司法試験に受かる前後、司法修習生になるまで、伊藤塾で講師やゼミなど長らく担当していたのですが、そのときのゼミ生など沢山カンパをしてくれてます。 お会いする機会も無い方ばかりだし、そもそも匿名で当時のゼミ名などで送金して下さる方も多く、御礼もできないのですが、本当に感謝。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:52／2018/06/06 09:49 URL： https://twitter.com/kk_hirono/status/1289227455106965507 https://twitter.com/shima_chikara/status/1004163328627732480  

> 大量不当懲戒請求への法的措置のためカンパ募集したら「恐ろしいビジネスモデル」だとの理由で、新たに懲戒請求されました。 折角なので。原因となったカンパはまだまだ募集してますので、宜しくお願いしますm(__)m ◆みずほ銀行　横浜支店… https://t.co/z8w9sjnfJW  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:52／2018/06/06 10:56 URL： https://twitter.com/kk_hirono/status/1289227545188032513 https://twitter.com/shima_chikara/status/1004180074873085952  

> 本日時点で、336人から約254万円のカンパをいただきました。どうもありがとうございますm(__)m　 人数ベースで5分1くらいは、弁護士の方からのカンパと思われます。金額ベースだともっと割合は高くなります。 法クラの皆さまに感謝。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:53／2018/07/12 18:53 URL： https://twitter.com/kk_hirono/status/1289227625366347776 https://twitter.com/shima_chikara/status/1017346173521178624  

> 先ほどまで、佐々木・北弁護士と大量懲戒請求の弁護団会議。諸事情により提訴が予定より遅れてますが準備進めてます（カンパいただいた方、申し訳ありません）。 まずは、佐々木・北弁護士の提訴が先発となりますが、私の分も提訴します。強力な弁護団も助力いただいており、心強いです。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:53／2018/07/14 07:54 URL： https://twitter.com/kk_hirono/status/1289227668181798913 https://twitter.com/shima_chikara/status/1017905176353443841  

> カンパをお願いしてるときにお約束している通り、刑事もやります。 https://t.co/GXiYmuR5LQ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:53／2018/08/27 23:32 URL： https://twitter.com/kk_hirono/status/1289227759995117570 https://twitter.com/shima_chikara/status/1034086251463233536  

> これで、私宛計958件の扇動された懲戒請求が確定し、請求者も全て特定済み。 提訴できる環境がほぼ整ったので、カンパしていただいた皆さま、もう少しお待ちくださいm(__)m 訴状は、佐々木・北弁護士と協働でほぼ仕上げてるので、必要な事務手続を終えたら提訴予定。9月中には必ず第一段。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:53／2018/11/10 11:16 URL： https://twitter.com/kk_hirono/status/1289227817092227073 https://twitter.com/shima_chikara/status/1061080025795948545  

> 私への訴訟費用実費カンパは、現状で約300万円集まっております。提訴後、一旦報告させていただきます。 労働弁護団など所属団体で呼び掛けていないこともありますが、全く接点もなかった方含め、多数カンパをいただき、本当に感謝しておりますm(__)m  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:54／2018/11/30 11:31 URL： https://twitter.com/kk_hirono/status/1289227925896572929 https://twitter.com/shima_chikara/status/1068331701993037826  

> 本日、私への大量懲戒請求について、横浜地裁に１陣・３訴訟（被告６名✕３訴訟＝１８名）を提訴しました。 事件番号平成３０年（ワ）第４７４９号（５民）、同第４７８０号（８民）、同第４７８１号（９民） カンパいただいた皆さま、大変お待たせしましたm(__)m ＃大量懲戒請求  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:54／2019/02/15 16:42 URL： https://twitter.com/kk_hirono/status/1289228064279289857 https://twitter.com/shima_chikara/status/1096313751899320320  

> 被害回復のカンパもらった弁護士って、いないはずですよ。 カンパは懲戒請求者への訴訟費用目的です、私がいただいたのは。管理口座も個人名義でなく弁護団名義。 そこは、カンパしてくださった方に誤解与えるので指摘しときますね。 https://t.co/8oz4rZOWeC  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:55／2019/02/16 18:24 URL： https://twitter.com/kk_hirono/status/1289228304348672000 https://twitter.com/shima_chikara/status/1096701871480160256  

> 大量懲戒請求で「損害が無い」「訴訟で儲けている」とか言われると、日頃温厚で知られる私でも、少々ムッとしますね。 ちなみに、同業者から訴訟費用で多くのカンパをいただいた（感謝）。 同業者がカンパしてくれたのは、弁護士だからこそ、被害も訴訟実負担もよく理解しているから。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:56／2019/03/15 10:17 URL： https://twitter.com/kk_hirono/status/1289228428231598081 https://twitter.com/shima_chikara/status/1106363667040239616  

> 【訴訟費用カンパに関するご報告】 皆さまから、現在まで332万6310円のカンパをいただきました。 これまで、郵券・印紙代、提訴予告通知発送作業、被告住所調査費用、代理人弁護士（私、佐々木・北弁護士以外の弁護士）への弁護士費用として、165万6115円を支出させていただきました。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:56／2019/03/17 23:53 URL： https://twitter.com/kk_hirono/status/1289228494711296007 https://twitter.com/shima_chikara/status/1107294009314074625  

> 【訴訟費用カンパに関するご報告】 皆さまから、2019年3月15日時点で332万6310円のカンパをいただきました。ありがとうございます。これまで郵券印紙代、提訴予告通知発送作業、被告住所調査費、代理人弁護士（私、佐々木・北以外の… https://t.co/0C1xrC6zdp  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:57／2019/04/11 13:36 URL： https://twitter.com/kk_hirono/status/1289228588609224705 https://twitter.com/shima_chikara/status/1116198434820644864  

> 原告私の不当懲戒請求事件、横浜地裁で全額認容(33万)判決です。被告6名。欠席判決は2人で、残りは反論した上での判決。 人生初の(自分の)勝訴判決です。嬉しい！ カンパいただいた皆様、代理人の皆様に感謝。 #不当懲戒請求 #勝訴  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:57／2019/06/26 10:39 URL： https://twitter.com/kk_hirono/status/1289228690887282691 https://twitter.com/shima_chikara/status/1143695298390188035  

> @PxRAu990oSW6sIl カンパのお金で印鑑は作っておりません。所員弁護士の押印＆代印で処理しています。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:58／2019/06/30 20:41 URL： https://twitter.com/kk_hirono/status/1289228842259763200 https://twitter.com/shima_chikara/status/1145296410754949120  

> @PxRAu990oSW6sIl @LQ76130865 @sugibow ご心配ありがとうございます！ 神奈川県弁護士会とは、仲良く訴えられているので、協働歩調です（笑） 神奈川県弁護士会の会員からは、多数のカンパもいただいおり、とても感謝しています。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:58／2019/08/23 18:12 URL： https://twitter.com/kk_hirono/status/1289228907279863808 https://twitter.com/shima_chikara/status/1164827824215060483  

> 本日、原告私の訴訟で原告本人尋問の期日。裁判官に私の被害実態を聴いてもらいました。 不当懲戒請求訴訟で、弁護士本人の証人尋問は初（今後も不明）。 尋問されるのは初体験でしたが、代理人のサポートで乗切れました。カンパいただいた皆さま… https://t.co/Nv0jVRFpyB  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:58／2019/09/19 14:17 URL： https://twitter.com/kk_hirono/status/1289229012938584064 https://twitter.com/shima_chikara/status/1174553181184856065  

> 現在、1～18事件を提訴で、被告数合計168名。 なお、カンパ募集開始時以降も懲戒請求がなされ、現在は958件。 これとは別に、損害賠償請求をしたことへの報復的な懲戒請求は別途140件ほど、私や神奈川県弁護士会と日弁連を共同被告と… https://t.co/i6DefRuJN4  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 00:59／2019/09/20 19:10 URL： https://twitter.com/kk_hirono/status/1289229209299120129 https://twitter.com/shima_chikara/status/1174989323650781184  

> 【カンパの会計報告】 使用内訳は、ある程度全体解決の目途がたった時期にご報告させて下さい。こちらの動きが見えてしまうこともあり、今はこの程度で御容赦を。 なお、カンパの用途に、私の収入補填や出頭時の交通費は含まれておりません（今後もあり得ません）。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 01:00／2019/10/21 09:05 URL： https://twitter.com/kk_hirono/status/1289229340043915265 https://twitter.com/shima_chikara/status/1186070888728297472  

> @hamabou_33 @kumikokatase 現実に、960人を相手に訴訟提起することの負担が重いこと(労力だけでなく実費も)は、訴訟実務を知っていれば簡単に分かることですので、揶揄されても気になりません。 カンパ、弁護団の… https://t.co/0PXMXJeqaN  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 01:00／2019/10/30 17:10 URL： https://twitter.com/kk_hirono/status/1289229385740951552 https://twitter.com/shima_chikara/status/1189454580645416960  

> 本日、原告私の第25次訴訟を横浜地裁に提訴しました（1訴状・被告20名）。 これで提訴済みが合計248件です。 カンパのご支援、どうもありがとうございます。 ＃不当懲戒請訴訟  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 01:00／2020/01/01 12:01 URL： https://twitter.com/kk_hirono/status/1289229445379706881 https://twitter.com/shima_chikara/status/1212207115923677189  

> 明けましておめでとうございます！ 昨年は、多くの皆様にお世話になりました。とくに、大量不当懲戒請求の関係でカンパ含むご支援、ありがとうございました。 今年も、ライフワークの労働問題等を中心に、Twitterで発信していきます。 そ… https://t.co/YcgGWVGsPV  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 01:00／2020/02/21 23:18 URL： https://twitter.com/kk_hirono/status/1289229537927032833 https://twitter.com/shima_chikara/status/1230859281668296705  

> 素晴らしいサイトができました。 報告が途切れがちで恐縮ですが、着々と進展してます。 提訴・勝訴判決が積み重なる一方、私と神奈川県弁護士会を被告とするスラップ訴訟も全国で提訴されてます。 カンパのご支援、宜しくお願いします ⇒不当懲… https://t.co/iI94BpvXKI  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 01:06／2020/03/13 15:17 URL： https://twitter.com/kk_hirono/status/1289231032231669761 https://twitter.com/shima_chikara/status/1238348345778683904  

> 私と神奈川県弁護士会を被告とする損害賠償請求訴訟は、京都・名古屋・奈良（葛城支部）・高松で提起されていて、まだまだ増える様相も。 訴訟対応を依頼する弁護士さんへの費用支払も必要です。 カンパのご支援、継続的に募集中です。宜しくお願… https://t.co/8NjnBVzVBy  

不当懲戒請求問題弁護団 https://t.co/FsJIgdEl7u このページは，弁護士佐々木亮（東京弁護士会所属），弁護士北周士（東京弁護士会所属），弁護士嶋崎量（神奈川県弁護士会所属）に対して 平成29年中に大量に行われた不当な懲戒請求について，

不当懲戒請求問題弁護団 https://t.co/FsJIgdEl7u 和解によるメリット \n 以上の手順で和解がされた場合は，損害賠償請求訴訟を提起せず，刑事上の処罰も求めません。

不当懲戒請求問題弁護団 https://t.co/FsJIgdEl7u 申出方法 \n 和解の申出は，神奈川総合法律事務所の「相談申込みフォーム」（嶋崎弁護士 所属事務所）へお申し込み下さい。

不当懲戒請求問題弁護団 https://t.co/FsJIgdEl7u この申出は，原則として，3名の弁護士に対する和解を希望するご連絡であると判断します。

不当懲戒請求問題弁護団 https://t.co/FsJIgdEl7u 弁護団に対するカンパのお願い \n この弁護団の活動のために，カンパを受け付けております。

不当懲戒請求問題弁護団 https://t.co/FsJIgdEl7u カンパの振込先口座 \n 佐々木弁護士・北弁護士用

不当懲戒請求問題弁護団 https://t.co/FsJIgdEl7u 嶋﨑弁護士用 \n 銀行名：みずほ銀行 \n 支店名：横浜支店（店番357） \n 口座種類：普通 \n 口座番号：4012715 \n 口座名義：不当懲戒請求被害回復カンパ

不当懲戒請求問題弁護団 https://t.co/FsJIgdEl7u 佐々木弁護士・北弁護士用 \n 銀行名：みずほ銀行 \n 支店名：浜松町支店（店番148） \n 口座種類：普通 \n 口座番号：1665961 \n 口座名義：不当懲戒被害回復原告団

不当懲戒請求問題弁護団 https://t.co/FsJIgdEl7u 原告弁護士 \n  佐々木弁護士（@ssk_ryo） \n  \n  嶋﨑弁護士（@shima_chikara） \n  \n  北弁護士（@noooooooorth）

奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: REGEXP：”カンパ”／嶋﨑量（弁護士）（@shima_chikara）の検索（2018-05-09〜2020-03-13／2020年08月01日00時18分の記録45… https://t.co/EAu9TE6N3S

　なにかの間違いかと思ったのですが，カンパをキーワードに含む嶋﨑量弁護士のツイートの記録は，2020年3月13日のツイートで途切れていました。ちなみに本日は，2020年8月1日になります。

　重要と思える間違いがあっては，北周士弁護士，嶋﨑量弁護士，佐々木亮弁護士にもご迷惑が掛かりかねないというツイートは，スクリーンショットをあわせて記録しました。それを次にリツイートし，佐々木亮弁護士のツイートのまとめ記事に移ります。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-01 01:11／2020/08/01 01:06 URL： https://twitter.com/kk_hirono/status/1289232274047660033 https://twitter.com/s_hirono/status/1289231057577861122  

> 2020-08-01-010540_原告弁護士　佐々木弁護士（@ssk_ryo）　嶋﨑弁護士（@shima_chikara）　北弁護士（@noooooooorth）.jpg https://t.co/GRwTLn0Z5T  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-01 01:11／2020/08/01 01:06 URL： https://twitter.com/kk_hirono/status/1289232292511019008 https://twitter.com/s_hirono/status/1289230984798380032  

> 2020-08-01-010401_カンパの振込先口座佐々木弁護士・北弁護士用.jpg https://t.co/zezW88IOL4  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-01 01:11／2020/08/01 01:06 URL： https://twitter.com/kk_hirono/status/1289232304838029317 https://twitter.com/s_hirono/status/1289230911699968001  

> 2020-08-01-010303_この申出は，原則として，3名の弁護士に対する和解を希望するご連絡であると判断します。.jpg https://t.co/rnlMtYNjdU  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-01 01:11／2020/08/01 01:05 URL： https://twitter.com/kk_hirono/status/1289232320034009088 https://twitter.com/s_hirono/status/1289230838110892033  

> 2020-08-01-005519_嶋﨑量（弁護士）@shima_chikara被害回復のカンパもらった弁護士って、いないはずですよ。カンパは懲戒請求者への訴訟費用目的です、私.jpg https://t.co/INAr69wNWS  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:13／2011/08/06 12:38 URL： https://twitter.com/kk_hirono/status/1289232640923455491 https://twitter.com/ssk_ryo/status/99685703503454208  

> 厳しい状況だとは思うが、たった今、ビギナーズネット（ @beginners_net ）にわずかばかりのカンパをした。本当にわずかだけど（笑）。みなさんもフトコロに余裕があればカンパしてあげましょう（と、菅本先生にツイッターで宣伝してくださいと言われたので実行しました）。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:13／2011/08/06 12:42 URL： https://twitter.com/kk_hirono/status/1289232770128994305 https://twitter.com/ssk_ryo/status/99686688485416961  

> 菅本先生によると「カンパ先： ゆうちょ銀行　０２２１０－７－１１７６８４　口座名義：　ビギナーズネット　★他行からのお振込は、以下の店名・口座番号になります（口座名義は同じです）　店名（店番）：二二九（ニニキュウ）　口座番号：　０１１７６８４」・・・だそうです。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:14／2012/04/22 00:21 URL： https://twitter.com/kk_hirono/status/1289232885220651009 https://twitter.com/ssk_ryo/status/193721222385766403  

> 福島みずほ議員と、けっこう昔に、名刺交換したことがあるからか、国政報告とカンパのお願いが何回か届いたことがある。で、カンパの振込銀行はどこかな、と思ってみたら、みずほ銀行だったんだ。本当だよ。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:14／2018/04/27 18:36 URL： https://twitter.com/kk_hirono/status/1289232990598344706 https://twitter.com/ssk_ryo/status/989800473874972673  

> 不当な懲戒請求に対する費用のカンパを募ります。口座は写真のやつです。印紙や郵券、副本の作成費用（紙代、コピー代）に使用します。ぜひ、ご協力をお願いします。 #不当懲戒   https://t.co/2lzB1n8v9G  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:14／2018/04/28 11:21 URL： https://twitter.com/kk_hirono/status/1289233065978425347 https://twitter.com/ssk_ryo/status/990053368402927616  

> #不当懲戒　のカンパは下記口座へ。お力添えいただければ幸甚です。  みずほ銀行　浜松町支店　普通　１６６５９６１　不当懲戒被害回復原告団  ・印紙代、郵券代、副本作成費（紙代・コピー代）に使います ・懲戒請求者に対する通知や発信者… https://t.co/5gxeKj3c2x  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:16／2018/04/28 11:22 URL： https://twitter.com/kk_hirono/status/1289233429230362624 https://twitter.com/ssk_ryo/status/990053589660778496  

> いただいた金額の合計および使用内容につきましては適宜TwitterやFB等で報告させていただきます。 もし、非常に多くのカンパを頂戴した場合には、今後同様の被害にあった人のためのプール金とさせていただく予定です。引き継ぎ先等につきましても適宜ご報告致します。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:17／2018/05/07 10:26 URL： https://twitter.com/kk_hirono/status/1289233745992511491 https://twitter.com/ssk_ryo/status/993300891531792384  

> カンパ、本当にありがとうございます。ツイッターの通知が非常に多く、お礼が漏れている方もいると思われます。大変失礼しておりますが、ご容赦ください。引き続きよろしくお願いいたします。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:17／2018/05/23 19:40 URL： https://twitter.com/kk_hirono/status/1289233834672713729 https://twitter.com/ssk_ryo/status/999238687073288192  

> 今日は普段は相手方になるだろう先生からもカンパをいただいた。また、先日は、期日の後に、相手方の先生から心配いただいた。ありがたいことだ。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:18／2018/06/06 20:53 URL： https://twitter.com/kk_hirono/status/1289233965413363713 https://twitter.com/ssk_ryo/status/1004330447289978880  

> よくわかんないんだけど、弁護士がカンパを募ると品位を欠くとかって、どういう理屈なの？意味が分からん。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:18／2019/03/11 09:39 URL： https://twitter.com/kk_hirono/status/1289234027325448192 https://twitter.com/ssk_ryo/status/1104904721368641536  

> 余命なんとかが、私や北さんを何億円もの訴額で訴えると息巻いていた件、事件番号と係属部をあるスジから入手したので問い合わせたら、２月に取り下げで終了しておりました。訴訟を謄写したら、改めてお知らせします。しかし、大々的にカンパ集めてやった訴訟を期日指定前に取り下げるって。。。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:19／2019/03/11 11:00 URL： https://twitter.com/kk_hirono/status/1289234151414013953 https://twitter.com/ssk_ryo/status/1104925056562425856  

> 訴訟記録一式を謄写して、このあたりも確認したいところ。読者から多額のカンパを集めて、訴えるまでやったのに、そのあと、なぜか取下げという行動をとっている。極めて不可解である。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:19／2019/03/11 11:02 URL： https://twitter.com/kk_hirono/status/1289234271220056065 https://twitter.com/ssk_ryo/status/1104925653130854400  

> 訴えるので読者からカンパを集める（５万円×〇〇〇名？） ↓ 訴えて印紙を何百万円も納める ↓ 期日前に取り下げる ↓ 印紙代半額返る  なんなのだろう、これ・・。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:20／2019/04/12 18:33 URL： https://twitter.com/kk_hirono/status/1289234380045475840 https://twitter.com/ssk_ryo/status/1116635443913576450  

> 弁護士費用は認められませんでしたが、カンパくださった皆さま、応援してくださった皆さま、強力な呉越同舟弁護団の先生方、ありがとうございました。第一弾は完勝です。あと私の巻き添えになって申し訳ない北さん、嶋崎さん、ホントにごめんなさい。今日の結論でとりあえずホッとしました・・。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ssk_ryo（ささきりょう） 日時：2020-08-01 01:20／2019/11/23 11:10 URL： https://twitter.com/kk_hirono/status/1289234459724673024 https://twitter.com/ssk_ryo/status/1198061148458717185  

> 大体、６０名の提訴で５０万円くらい経費がかかります。もし、まだお力添えいただけるのであれば、引き続きカンパを募集しておりますので、よろしくお願いいたします。 #不当懲戒請求 #大量懲戒請求  https://t.co/PnbxmiaOH2  

　佐々木亮弁護士のカンパをキーワードにしたツイートは5月23日を最後にしているのですが，次の北周士弁護士のツイートを引用リツイートしたものになります。「カンパの総額は920万円になりました。」とあります。

- TW noooooooorth（ノ ー ス ラ イ ム） 日時： 2020/05/23 09:33 URL： https://twitter.com/noooooooorth/status/1263991501404528640  

> カンパの総額は920万円になりました。本当にありがとうございました！なお既に使い切っており現在は手出しで戦っております。カンパがなければ戦い切ることは到底できませんでしたね…。 https://t.co/EODipRdbuC  

　すでにリツイート済みのツイートになります。佐々木弁護士・北弁護士用が口座名義：不当懲戒被害回復原告団，嶋﨑弁護士用が口座名義：不当懲戒請求被害回復カンパとなっているのですが，これも不可解で，総額が増えそうではありますが，いろいろと誤解も与えそうです。

```
弁護団に対するカンパのお願い
この弁護団の活動のために，カンパを受け付けております。
カンパの利用用途
いただいたカンパは，訴訟提起の際の印紙代，郵便費用，副本等の作成費用（印刷費等），代理人の出廷費用，意見書依頼費用，発端となったブログの開設者に関する発信者情報開示請求の弁護士費用など，弁護団が活動していくための費用に使用させていただきます。

被害の回復のためにカンパをお願いするものではありません。事件が完全に終了した際に余剰を生じたときは，同種の被害を受けた弁護士に対する支援のため，あるいは，不当な懲戒請求の手続による負担を受けた弁護士会等への寄付をするなど，弁護団において協議のうえ使用させていただくことをご了解ください。

カンパの必要性
多数の懲戒請求者に対する提訴には多額の印紙代・郵便費用の予納が必要となります。また，主要な争点について研究者による意見書を依頼しました。そのため，2019年11月末時点で，いずれのカンパ口座も残金が少なくなりつつあります。これまでのご支援に感謝を申しあげるとともに，さらなるご支援を，可能な範囲でお願いいたします。

カンパの振込先口座
佐々木弁護士・北弁護士用
銀行名：みずほ銀行
支店名：浜松町支店（店番148）
口座種類：普通
口座番号：1665961
口座名義：不当懲戒被害回復原告団
嶋﨑弁護士用
銀行名：みずほ銀行
支店名：横浜支店（店番357）
口座種類：普通
口座番号：4012715
口座名義：不当懲戒請求被害回復カンパ
原告弁護士
 佐々木弁護士（@ssk_ryo）

 嶋﨑弁護士（@shima_chikara）

 北弁護士（@noooooooorth）

［source：］不当懲戒請求問題弁護団 https://futo-choukai-seikyu.net/
```

　上記にまとめて引用しましたが，「事件が完全に終了した際に余剰を生じたときは，同種の被害を受けた弁護士に対する支援のため，あるいは，不当な懲戒請求の手続による負担を受けた弁護士会等への寄付をするなど，弁護団において協議のうえ使用」とあります。

　弁護士会への寄付というのはまったく初めて目にしたのですが，寄付をした人への見返りが全く感じられないのもこのカンパ募集の特徴です。大崎事件のクラウドファンディングでは，心からの感謝のメッセージなどというものがありました。

　「被害の回復のためにカンパをお願いするものではありません。」ともこのホームページにはあるのですが，すでに数々の勝訴判決を受けているとツイートとしながら，賠償金を得たという報告は，3人の弁護士のツイートにも全く見当たらないものとなっています。

　つい最近は，最高裁での勝訴判決が続出しているというようなツイートを見ているのですが，民事裁判が確定すれば債務名義として強制執行も可能，任意に支払いがなければ画餅に帰すともいわれるところですが，回収の見込みを含めたそのあたりの説明も全く見られないところです。

　最高裁が勝訴判決と書いてしまいましたが，刑事事件の場合は書面審理のみが原則で，口頭弁論がなければ決定となり，口頭弁論が開かれた場合が判決となります。民事裁判の場合は情報も少なくわかりづらいのですが，上訴にお金の負担がかかるとも過去に勉強をしています。

　いずれにせよ，最高裁で勝訴が続いているとのことなので，お墨付きをもらったかたちにもなりそうですが，一つ間違うと出資法などの刑事事件として，警察や検察が捜査をする可能性もあるように思えてきました。

　ツイートで写真が公開されているのも銀行口座の表だけです。他の部分はモザイク処理をするにしても，振込の日付と金額は公開して不思議はないように思います。私も祭礼委員会の会計として決算報告書を作成し町内会長，氏子総代の監査を受け，宇出津の各町内各戸の回覧にすることをやってきました。

〈〈〈：Linux Emacs： 2020-08-01（土曜日）01：48 　〈〈〈

* 「アメブロを更新しました。 『刑事弁護の存在意義に思いを馳せる――被告高野隆の意見陳述』」という趙誠峰弁護士のツイート
  :LOGBOOK:
  CLOCK: [2020-08-01 土 12:36]--[2020-08-01 土 16:52] =>  4:16
  :END:

:CATEGORIES: 趙誠峰弁護士,高野隆弁護士,懲戒請求

〉〉〉：Emacs： 2020-08-01（土曜日）12：36　 〉〉〉

　朝はWindows10の一太郎で告発状の作成を開始しました。LibreOfficeの拡張機能で一太郎のビューアがあるという情報で，それをやってみたのですが，このコンピュータでは動作しませんなどというエラーが出ました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-01 12:44／2020/08/01 12:14 URL： https://twitter.com/kk_hirono/status/1289406686843686913 https://twitter.com/hirono_hideki/status/1289399191928635393  

> 刑事弁護の存在意義に思いを馳せる――被告高野隆の意見陳述 | 空気を読まずに生きる https://t.co/C7zCre9vF7  

　12時14分に投稿となっている上記のツイートは，記事を読み終えた直後の投稿になります。Linuxを起動し直してしばらくした頃で，ブックマークの趙誠峰弁護士のTwitterタイムラインを開いて見つけたツイートです。

 - 2020年08月01日12時25分の登録： REGEXP：”高野隆”／データベース登録済みツイートの検索：2020-07-28〜2020-08-01／2020年08月01日12時24分の記録：ユーザ・投稿：43／47件 http://hirono2014sk.blogspot.com/2020/08/regexp2020-07-282020-08.html

　上記のまとめ記事は7日以内で範囲指定しました。7日の指定ですが取得されたツイートは7月28日からなので5日分になりそうです。

```
アカウント名	ツイート数	リツイート数
りっぴぃ（rippy08）	2	0
河﨑健一郎（kappamark）	1	0
Yasuyuki KIMURA（弁護士ときどきランナー）（kmrysyk）	0	1
icchan（icchan41543407）	0	1
? ｛君はアレがエロく見えるのかね？平和の証に見えないならば教養が足りんよ。本を読みなさい。（un_co_the2nd）	0	1
マニアの受難＠日本酒沼（mt1q7q）	1	0
sym（TnktMcBg）	0	1
弁護士髙橋宗吾（sogo_takahashi）	0	1
ＤＤＤ（TheReadingTime）	0	1
今泉義竜（i_yoshitatsu）	1	0
CHO Seiho／趙誠峰（cho_seiho）	1	0
TｰTAKA（TGN54）	0	1
芳賀淳（jjjhaga）	0	1
ぎたべん（guitar_ben）	0	2
福岡真之介　弁護士（shin_fukuoka）	0	1
Masahiro Ito/伊藤雅浩?（redipsjp）	0	1
じーこ（jiko25jiko）	0	1
弁護士ソチ預り口（scazukari）	0	1
櫻井光政（okinahimeji）	0	1
ぽんぽん（ponponmonn）	0	1
弁護士 高野倉 勇樹（yuukitakanokura）	0	1
Smith目（iy0kahn）	0	1
弁護士 亀石倫子（MichikoKameishi）	1	0
dslaw（dshowgo）	0	1
リーチ一発ツモ裏１（luckymangan）	0	1
ぽぽひと@睡眠重視（popohito）	0	1
しゅん弁（shunlawyer）	0	1
okumuraosaka（okumuraosaka）	0	1
木下裕一（hirokazu41519）	0	1
山口一臣（kazu1961omi）	0	1
えきなんローヤー?（ekinan_lawyer）	0	1
ルート６６（元ルパン３世）（Route66_LP3）	0	1
銀冠（ginkanmuri_0202）	1	0
ユウヘイ・パパ（yuuheipapa）	0	1
いわぽん（yiwapon）	0	1
shou_yasuda（shou_yasuda）	0	1
坂本義夫（SakamotoYoshio）	0	1
しゃんきち弁護士（syankichilawyer）	0	3
法務ニュース（Sosho_Sokuho）	0	1
無彩の彩（y_muninare）	0	1
Kenji Takeuchi（KPf_M）	0	1
惇兄（tongu）	0	1
奉納＼さらば弁護士鉄道・泥棒神社の物語（hirono_hideki）	1	0


［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”高野隆”／データベース登録済みツイートの検索：2020-07-28〜2020-08-01／2020年08月01日12時24分の記録：ユーザ・投稿：43／47件 http://hirono2014sk.blogspot.com/2020/08/regexp2020-07-282020-08.html
```

 - （01／47） TW rippy08（りっぴぃ） 日時： 2020-07-28 21:24:00 +0900 URL： https://twitter.com/rippy08/status/1288087941126828033

> 新62期のときの7月集会の全体集会に高野隆先生が講師で来られていて、被害者参加について述べられていたのを今頃思い出すなど、、、

 - （02／47） TW kappamark（河﨑健一郎） 日時： 2020-07-31 11:55:00 +0900 URL： https://twitter.com/kappamark/status/1289031820856631297

> 高野先生、相変わらず圧倒的にかっこよい。深い人間性が滲み出るような文章。マルゼルブ卿・・・　／被告高野隆の陳述 - 刑事裁判を考える：高野隆＠ブログ https://t.co/Qvv6jOIyMI

 - （04／47） TW rippy08（りっぴぃ） 日時： 2020-07-31 12:19:00 +0900 URL： https://twitter.com/rippy08/status/1289038012567887874

> マルゼルブ、、、そんな人物のことは知りませんでしたが、圧倒されました。／被告高野隆の陳述 https://t.co/v48LcJzbXc

 - （07／47） TW mt1q7q（マニアの受難＠日本酒沼） 日時： 2020-07-31 12:42:00 +0900 URL： https://twitter.com/mt1q7q/status/1289043626639495168

> 読みながら何度もうなずいてしまう。
>
> 被告高野隆の陳述 - 刑事裁判を考える：高野隆＠ブログ https://t.co/JZJsCMZFjn

 - （11／47） TW i_yoshitatsu（今泉義竜） 日時： 2020-07-31 20:16:00 +0900 URL： https://twitter.com/i_yoshitatsu/status/1289158048636780576

> 「隆よ、影に廻って人の悪口を言うもんではない。悪口を言うならば堂々と本人の前で言うんだ」
> 被告高野隆の陳述 - 刑事裁判を考える：高野隆＠ブログ https://t.co/pOPumU5r1l

 - （12／47） TW cho_seiho（CHO Seiho／趙誠峰） 日時： 2020-07-31 21:58:00 +0900 URL： https://twitter.com/cho_seiho/status/1289183671199522816

> アメブロを更新しました。 『刑事弁護の存在意義に思いを馳せる――被告高野隆の意見陳述』
> https://t.co/MXLfPoukYT

 - （24／47） TW MichikoKameishi（弁護士 亀石倫子） 日時： 2020-08-01 09:31:00 +0900 URL： https://twitter.com/MichikoKameishi/status/1289357944614576128

> 高野隆弁護士が懲戒請求されたことについて、懲戒請求者の氏名を公表したうえで、その懲戒請求書と反論文を自身のブログに掲載したことについて、懲戒請求者から損害賠償等を求められている事件における、被告高野隆氏の意見陳述https://t.co/DWtZm2xvNc

 - （29／47） RT okumuraosaka（okumuraosaka）｜fuyuben（冬弁） 日時：2020-08-01 10:00:00 +0900／2020-08-01 09:53:00 +0900 URL： https://twitter.com/okumuraosaka/status/1289365381614727168 https://twitter.com/fuyuben/status/1289363534812340224
被告人と一緒に処刑された弁護人。。知りませんでした。怖すぎ。 \n \n 〉歴史上最も悲惨な例は、フランス革命のときにルイ16世の弁護人となったマルゼルブ卿の場合です。 \n \n 【被告高野隆の陳述】 \n https://t.co/ArZZcb2ydU

　元のツイートの冬弁というアカウントですが，2,3日前にも少し気になるツイートを見かけ印象に残っていたところでした。ツイートととして記録がなかったので確認したところ，リストに未登録のアカウントでした。

　奥村徹弁護士のリツイートになっているのは今気がついたところです。冬弁というアカウントは，だいぶん前にときどき見かけていたと思うのですが，いつの間にかほとんど見かけなくなって，つい最近になってまた見かけるようになったアカウントになります。

```
冬弁
@fuyuben
弁護士　/重点分野　労働（使用者側） 企業法務　ベンチャー支援　IT法務　支配権争い　/顧問業務　/気になる時事ネタにコメント　/好きなもの　BS海外ドキュメンタリー　コズミックフロント　/筋トレ超初心者　皇居ラン
2019年11月からTwitterを利用しています
1.1万 フォロー中
1.1万 フォロワー

［source：］冬弁さん (@fuyuben) / Twitter https://twitter.com/fuyuben?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1289363534812340224%7Ctwgr%5E&ref_url=http%3A%2F%2Fhirono2014sk.blogspot.com%2F2020%2F08%2Fregexp2020-07-282020-08.html
```

　プロフィールに弁護士とあります。フォロワー，フォローともに1.1万となっていますが，この割合は弁護士アカウントとしては珍しく感じました。1.1万というのもけっこうな数です。他の法クラのリツイートを余り見かけてこなかったのが不思議な気もします。

　タイムラインをみていると，気になるものや参考になりそうな情報があるのでリツイートします。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fuyuben（冬弁） 日時：2020-08-01 13:05／2020/08/01 12:39 URL： https://twitter.com/kk_hirono/status/1289411945414529025 https://twitter.com/fuyuben/status/1289405279247847425  

> 新型コロナの流行は当分続くと思いますので、誹謗中傷についても初動で徹底的に特定して摘発していく（民事・刑事）、新型コロナと同じアプローチが必要かと思います。増えすぎると手がつけられなくなるのも同じ。  【岩手初の感染者に中傷続く… https://t.co/gIFRgYJxY0  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fuyuben（冬弁） 日時：2020-08-01 13:05／2020/08/01 11:49 URL： https://twitter.com/kk_hirono/status/1289412018617769985 https://twitter.com/fuyuben/status/1289392822248906753  

> メモ。  被告の主張はこちら。 〉被告側は請求棄却を求め、争う方針を示した。男性が文書を作成した事実は争わないとしながらも「強要はなかった」などと反論  【「障害有無書かされ自殺」／自治会班長選びめぐり自殺男性の遺族提訴】 https://t.co/yrYluKGg2R  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fuyuben（冬弁） 日時：2020-08-01 13:06／2020/08/01 11:49 URL： https://twitter.com/kk_hirono/status/1289412110162653185 https://twitter.com/fuyuben/status/1289392823549046785  

> 原告の主張はこちら。  〉男性は同月２４日、自治会の会長、班長と地域の社会福祉協議会の関係者の計４人で面談。その際、障害があることや、金の計算ができないことや自転車に乗れることなどを列挙した文書の作成を約２時間にわたって強要され、  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fuyuben（冬弁） 日時：2020-08-01 13:06／2020/08/01 11:49 URL： https://twitter.com/kk_hirono/status/1289412125723463680 https://twitter.com/fuyuben/status/1289392824924819457  

> 〉班長決めの集まりを開く際には文書を他の住民に見せることを伝えられたという。男性は文書を作成した翌日の同月２５日、自宅で自殺した。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fuyuben（冬弁） 日時：2020-08-01 13:06／2020/08/01 09:53 URL： https://twitter.com/kk_hirono/status/1289412259324690434 https://twitter.com/fuyuben/status/1289363537572196352  

> 〉そして、その後ジャコバン政権の下でルイ16世の王妃マリ・アントワネットも処刑されましたが、それと共にマルゼルブも処刑されてしまいました。裁判すら受けずに、マルゼルブ本人だけではなくて彼の娘、娘婿、そして孫も処刑されています。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fuyuben（冬弁） 日時：2020-08-01 13:07／2020/07/31 21:46 URL： https://twitter.com/kk_hirono/status/1289412430938873856 https://twitter.com/fuyuben/status/1289180667901693952  

> こ、これは。 筆跡でなぜバレないと思ったのでしょうか。  ＞男性弁護士は昨年１２月と今年４月の２件で、いずれも法定相続人ではない親族から依頼を受け、本来は故人自身が書かないと効力がない自筆証書遺言を作成した。 【弁護士が遺言書偽造… https://t.co/dOsjcmi7n3  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fuyuben（冬弁） 日時：2020-08-01 13:08／2020/07/31 21:18 URL： https://twitter.com/kk_hirono/status/1289412616939425794 https://twitter.com/fuyuben/status/1289173657395159042  

> 弁護人はどんな主張をするのでしょうか。仮に、起訴されて有罪となった場合、執行猶予はつくのでしょうか。注目。  〉「安楽死」をめぐる裁判例は複数ある  【京都ALS嘱託殺人、これを「安楽死」と呼べるのか？　弁護士「責任厳しく問われる… https://t.co/UyimrsjqHe  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fuyuben（冬弁） 日時：2020-08-01 13:09／2020/07/31 07:47 URL： https://twitter.com/kk_hirono/status/1289413019219324939 https://twitter.com/fuyuben/status/1288969562843578368  

> もし、冤罪で死刑が執行されて、死後に再審で無罪が確定した場合の補償額は、刑事補償法4条3項に定めがありますね。  【無実の罪で13年間拘束の女性、補償金5997万円を地裁に請求へ　湖東病院患者死亡】 https://t.co/fOK2Wkg8gE  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fuyuben（冬弁） 日時：2020-08-01 13:11／2020/07/30 19:16 URL： https://twitter.com/kk_hirono/status/1289413374766247936 https://twitter.com/fuyuben/status/1288780517731516418  

> 「加害者」側に当番弁護士。法務省は被疑者段階で「加害者」認定するのか。。 ＞森雅子法相は冒頭のあいさつで「加害者側に当番弁護士制度があるように、被害者側の権利を保護するため弁護士の活動を充実させていきたい」 【弁護士の被害者支援、… https://t.co/RhTRmGJL4u  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fuyuben（冬弁） 日時：2020-08-01 13:11／2020/07/30 19:21 URL： https://twitter.com/kk_hirono/status/1289413451903725569 https://twitter.com/fuyuben/status/1288781633529630722  

> 森法務大臣には悪意はないのかもしれませんが、ゴーン氏の事件で、ゴーン氏は「司法の場で無罪を証明すべきだ」と記者会見でいってみたり、口が滑るにも程がある。刑訴法の学部試験の答案で書いたら一発不可では。  【森法相「ゴーン被告は無罪証… https://t.co/9vq3SkNm95  

　そろそろタイムラインを辿るのをやめようかと思っていたところで，森雅子法務大臣に関するツイートが出てきました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fuyuben（冬弁） 日時：2020-08-01 13:15／2020/07/29 10:18 URL： https://twitter.com/kk_hirono/status/1289414320850219008 https://twitter.com/fuyuben/status/1288282664852525056  

> 「実は、私たちのように被害者側の代理人をする弁護士はごく少数です。日弁連の中にあっては、『絶滅危惧種』と言っても過言ではありません。」（「死刑賛成弁護士」14頁）とありますが、「本当なんですかね？」と思い、ファクトチェックをしたい… https://t.co/Thmvs0fex7  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fuyuben（冬弁） 日時：2020-08-01 13:15／2020/07/29 19:03 URL： https://twitter.com/kk_hirono/status/1289414344363536385 https://twitter.com/fuyuben/status/1288414755812646915  

> アンケートはファクトチェックではないという指摘を受けましたので撤回します。Twitterのアンケートは、本人確認もできず、ランダムサンプリングでもなく、統計的に有意な数の回答も得ることは難しいことは百も承知ですが、厳密な言葉遣いができず、申し訳ありませんでした。以後気をつけます。  

　あるかと思ってタイムラインをさらに遡ると，死刑賛成弁護士に関するツイートがあり，アンケートを実施してあります。274票は多くないですが，被害者代理人をやったことがあるが21.5％，やったことがないが意欲はあるが10.2％となっています。

　今のところ被害者代理人の弁護士の報酬がどこから出るのかよく分かっていないのですが，お金を出して依頼する被害者もそれだけ多いということなのかと考え，参考になりました。

 - （34／47） TW ginkanmuri_0202（銀冠） 日時： 2020-08-01 10:19:00 +0900 URL： https://twitter.com/ginkanmuri_0202/status/1289370192661737472

> 「刑事弁護の存在意義に思いを馳せる――被告高野隆の意見陳述」
> ⇒ https://t.co/FGSJIp7Dql #アメブロ @ameba_officialさんから

　余り見かけないアカウントのツイートが記録されていました。プロフィールを確認すると弁護士とあり，いずれも見覚えはあるものです。

```
銀冠
@ginkanmuri_0202
やっとこさウォーズ初段になったヘッポコ振り飛車党員。プロレス・Ｋ－ＰＯＰガールズグループ画像ＲＴおじさん。レジスタンス弁護士会惑星エンドア支部所属。イウォークの権利委員会委員。めつわか下っ端。
惑星エンドア2014年3月からTwitterを利用しています
448 フォロー中
621 フォロワー

［source：］銀冠さん (@ginkanmuri_0202) / Twitter https://twitter.com/ginkanmuri_0202?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1289370192661737472%7Ctwgr%5E&ref_url=http%3A%2F%2Fhirono2014sk.blogspot.com%2F2020%2F08%2Fregexp2020-07-282020-08.html
```

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ginkanmuri_0202（銀冠） 日時：2020-08-01 13:24／2020/07/31 21:52 URL： https://twitter.com/kk_hirono/status/1289416734823165952 https://twitter.com/ginkanmuri_0202/status/1289182172838948866  

> もう二度とこんな思いしたくないから、困難案件は暫く受任をお断りしよう……  今後どこかの時期で引き受けることがあっても、相当警戒してやらないといけないな……  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ginkanmuri_0202（銀冠） 日時：2020-08-01 13:24／2020/07/31 21:57 URL： https://twitter.com/kk_hirono/status/1289416745749422080 https://twitter.com/ginkanmuri_0202/status/1289183466957938688  

> 困難案件を拾いまくっている弁護修習の指導担当の先生に「銀君が私の真似をしようなんて１０年早い。そんなのは基礎を固めてからにしなさい！」って言われた意味を痛感している。  いや、このメンタル案件は自分で拾ったんじゃなくて、姉弁が拾ってきたんですが……  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 13:25／2020/07/31 12:09 URL： https://twitter.com/kk_hirono/status/1289416898120056833 https://twitter.com/shima_chikara/status/1289035383108321280  

> 「『ブラック企業』という言葉を使わなくても、若者使い潰しの被害者を相談に繋げられるのでは」という疑問を呈されるのは、本当に嬉しいですね。 認知されていなかった若者使い潰しに対する被害者救済の取組が、社会に浸透している証でもあるし。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-08-01 13:25／2020/07/31 11:56 URL： https://twitter.com/kk_hirono/status/1289416957331030019 https://twitter.com/shima_chikara/status/1289032105783988224  

> 私や、実際に汗をかいた仲間の弁護士、ユニオン、NPOの皆さんが救済に取り組んでつながった依頼者・相談者などです。 このテーマ、社会施策学会から依頼されて報告して論文も書きました。これ。 https://t.co/J45MrC6VIt https://t.co/p6wdJYkhls  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ginkanmuri_0202（銀冠） 日時：2020-08-01 13:26／2020/07/31 19:32 URL： https://twitter.com/kk_hirono/status/1289417169327935488 https://twitter.com/ginkanmuri_0202/status/1289146867058487296  

> 相手方への攻撃性を伴う不当要求が、その為に動こうとしない代理人（姉弁と俺）への誹謗中傷と自傷・自殺の仄めかしにまで発展した案件。 虚偽と暴言に満ちた今日付メールを姉弁に見せたら、｢何処かで辞任するのは確定だとして、何とか穏便に手を引こう｣と仰ってた姉弁が｢もう辞める！｣となった。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ginkanmuri_0202（銀冠） 日時：2020-08-01 13:26／2020/07/31 19:33 URL： https://twitter.com/kk_hirono/status/1289417183966027777 https://twitter.com/ginkanmuri_0202/status/1289147102216335360  

> この件で、怒りが大爆発した（元）依頼者から懲戒請求されたら笑ってくれ（俺は全く笑えないが）  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ginkanmuri_0202（銀冠） 日時：2020-08-01 13:26／2020/07/31 19:36 URL： https://twitter.com/kk_hirono/status/1289417232552886273 https://twitter.com/ginkanmuri_0202/status/1289147972987441152  

> まぁ、辞任にあたってｋｓ……じゃなかった、法テラスに提出する資料の中に、今まで送られてきた異常なメールの数々と、それにも関わらずこちらが法的に出来る手続は進めてきたことを示す書面がセットになってるので、同じものを綱紀委員にも提出する羽目になるんでしょうね……  

　タイムラインに嶋﨑量弁護士のツイートが7件並んでいるのですが，昨日にリツイートをしているものと思っていたツイートが，リツイート済みとなっていませんでした。

 - （47／47） TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-08-01 12:14:00 +0900 URL： https://twitter.com/hirono_hideki/status/1289399191928635393

> 刑事弁護の存在意義に思いを馳せる――被告高野隆の意見陳述 | 空気を読まずに生きる https://t.co/C7zCre9vF7

　上記の47件中47件目が私のツイートとなっていました。この先はありません。今のところ。

〈〈〈：Linux Emacs： 2020-08-01（土曜日）13：30 　〈〈〈

* 一太郎のファイルをWord形式で保存，そのまま一太郎でも編集できて，LinuxのLibreOfficeでも編集可能
  :LOGBOOK:
  CLOCK: [2020-08-01 土 16:52]
  :END:

:CATEGORIES: パソコン

〉〉〉：Emacs： 2020-08-01（土曜日）16：52　 〉〉〉

　一太郎で，一太郎プロンプトを例題をみながら使っていたのですが，そこにWord形式のファイルを一太郎形式で保存するというのがありました。逆も出来るのかと試したところ，Word形式のファイルが保存されました。ただ，古いWord形式で拡張子をdocにする必要があるようです。

　メニューにもWord形式で保存や読み込みはあったのですが，そのままWord形式のファイルを一太郎で編集できるというのは意外でした。法クラのツイートをみていると互換性がないというものが多かったのですが，少なくとも基本的な読み書きはできるようです。

　段落のスタイルや連番もそのまま使えているようです。一太郎のブックマークをリンクにしたものもリンクが有効になっていました。

　法クラのツイートで，Macのパソコンで一太郎が読み込めないという不満をたびたび見かけてきたのですが，これはLinuxも同じらしく，ビューアも使えないようです。最終的なファイルの印刷などはPDFファイルに変換してやるつもりでいます。

　次が，ファイル形式をコンバートさせる一太郎のコマンドというか関数になります。単純な関数ですが，引数のパスがWSLになっているので，ややこしくなっています。

fl("\\wsl$\Ubuntu-20.04\home\a66\git\gh2020kk\2020-08-01_告発状.jtd","\\wsl$\Ubuntu-20.04\home\a66\git\gh2020kk\2020-08-01_告発状.doc")

　一太郎は期待以上に使えそうですし，なによりATOKでの日本語変換の効率化で時間の有効活用に期待をしています。

〈〈〈：Linux Emacs： 2020-08-01（土曜日）17：15 　〈〈〈

