* 金沢市粟崎町について

:CATEGORIES: 被告発人大網健二,被告発人浜口卓也

粟崎町 - Google マップ https://t.co/zJwdVvQA2e

　まず，Googleマップで調べたのですが，思いの外，粟崎町の範囲が狭いと感じていたところ，隣接している別の区域にも粟崎という地名があることに気が付きました。周辺をよく見ると，内灘町向粟崎などとなっています。それも内灘駅の近くになります。

字向粟崎 - Google マップ https://t.co/mhW7GAl9ZR

　Googleマップで向粟崎をみると，ずいぶんな飛び地となっていました。向粟崎という地名に見覚えはあるのですが，内灘町とは気づかずにいたかと思います。昭和59年に事故死した見知らぬ若者の葬式に行ったこと，平成13年12月31日に回転寿司に入ったぐらいしか粟崎には縁がありませんでした。

清湖大橋 - Google マップ https://t.co/xevcK3u9ti

　粟崎は能登から来ると金沢市の玄関口のような場所だったので車で通ることはよくありましたが，上記の清湖大橋ができてからはほとんど通らなくなっていました。たまに気まぐれで粟崎を通過する道を選ぶことはありましたが。

日産ディーゼルトラックス㈱ 金沢支店 営業サービス - Google マップ https://t.co/ewDUeecgsI

　上記の日産ディーゼルの場所が１つの目安になります。近くに近岡という大きな交差点があって，その交差点から粟崎に向かっていました。この周辺は，新しい広い道路や建物も沢山出来て，平成11年当時とも大きく様変わりをしています。

　金沢市粟崎の範囲が狭いので，金沢港に埋立地が出来て，そちらが新しい道路になったのかと考えたのですが，五郎島が海沿いにそのままあるようなので，地形自体は変わっていないようです。

五郎島町 - Google マップ https://t.co/spaAejzQw5

　五郎島には川と河口があったはずですが，Googleマップでは見当たらず，ちょうど金沢港大橋という新しい道路の下辺りになるのかとも思われます。河口の横は公園になっていて公衆トイレがあったとも記憶にあります。

　平成3年の7月から9月に，被告発人安田敏とちょくちょくセイゴ釣りに来ていたのが，この五郎島になります。当時すでに五郎島はサツマイモの産地として有名になっていたと思いますが，平成16年辺りには，イモ泥棒で立ち入りが出来なくなっているとテレビニュースでみました。

　昨夜かその前の夜のテレビニュースでも，イモ泥棒の対策で金沢西警察署と連携パトロールをしているとやっていました。相当厳しく見回りをしているようですが，石川県内でも不思議と，この五郎島だけは泥棒のニュースをよくみかけます。

　かほく市の名産であるルビーロマンの方がはるかに高額になりそうですが，泥棒対策のニュースもみたことがありません。

「世界一の葡萄（ぶどう）」―ルビーロマンと付加価値農業― https://t.co/4btIsv3mDu 笹川陽平2020年09月04日 16:14

　ルビーロマンが世界一の葡萄という話は聞いたことがなかったのですが，Googleの検索結果から開いてみると，昨日の記事でした。テレビでニュースになるのは決まって初セリの金額ですが，これがいつもとんでもない値段となっています。検索ではすぐに見つからなかったですが。

```
県が開発した高級ブドウ「ルビーロマン」の初競りが16日早朝、金沢市西念4丁目の中央卸売市場であり、過去最高の一房130万円の値が付いた。

　最高額がついたのは、3段階中2段階目のグレード「特秀」の中でも、30グラム以上の大粒がそろった「Gクラス」。金沢市と能登町に旅館を3店舗構える「百楽荘」が昨年の120万円に続き、今回も最高額で落札した。

［source：］石川）ルビーロマン初競り　過去最高130万円：朝日新聞デジタル https://www.asahi.com/articles/ASN7J7SKTN7JPISC001.html
```

```
2020/09/05 01：47
　加賀野菜のサツマイモ「五郎島金時」の盗難を防ぐため、生産者５０軒でつくるパトロール隊が４日、活動を開始した。同日は五郎島生産組合と金沢西署、金沢西防犯協会の約２０人が粟崎町５丁目の畑を巡回した。１０月末まで続ける。

［source：］五郎島金時盗難防げ　生産者がパトロール隊 - 石川県のニュース | 北國新聞社 https://www.hokkoku.co.jp/subpage/H20200905101.htm
```

* 
