* 深澤諭史弁護士が「ここの所長の爪のアカを煎じて飲むべし！」とツイートした先に見た，「信州大学法科大学院は、2009（平成21）年の司法試験において、初の合格者を出し、存続の危機を乗り切った。」
  :LOGBOOK:
  CLOCK: [2020-07-25 土 00:42]--[2020-07-25 土 01:25] =>  0:43
  :END:

:CATEGORIES: 司法制度改革,深澤諭史弁護士

〉〉〉：Emacs： 2020-07-25（土曜日）00：42　 〉〉〉

　これは司法試験に合格することの大きさと，それが本人以外の大学関係者の利害や生活にも多大の影響を与えうるということを現実感をともなって教えてくれた記事になります。ページにはロゴマークの横に「信州大学大学院　法曹法務研究科」とあります。

```
（１）改革の必要性
　信州大学法科大学院は、2009（平成21）年の司法試験において、初の合格者を出し、存続の危機を乗り切った。しかし、そのこと自体は、ようやく他の法科大学院と同じ土俵にのったにすぎなかった。法科大学院をめぐる状況からすれば、その後も合格者を継続的に出すことによって、能力ある入学生を確保しなければならない。そのために、信州大学法科大学院は、2010（平成22）年から2011（平成23）年にかけて、カリキュラム改編と2年コースの導入という二つの大きな制度改革をおこなった。以下では、その様子を概観しよう。


（２）カリキュラム改編による演習科目の導入
　合格者を出していくための努力の中で、当時のカリキュラムが司法試験合格に適合していないという問題が意識されるようになった。
　信州大学法科大学院は、司法改革の理念に忠実であったため、ほとんどの教員は、講義では受験に向けた指導をしてはならないと考えていた。また、カリキュラムも講義が中心であって、答案を「書く力」は学生が努力して獲得するものだという前提があった。
　しかし、最初の合格者の多くは、教員が参加する「自主勉強会」や弁護士会の協力による「ゼミ」によって書く力をつけた者であった。司法試験の合格のためには、答案を書く力が備わっていなければならず、その力を得るには、一定の訓練が必要なのである。とするならば、そのような能力の養成は、「自主勉強会」のような「課外活動」ではなく、正規のカリキュラムによってなされるべきではないか。
　この考えを強く主張し、カリキュラム改編を提言したのは、2009（平成21）年1月に赴任した三枝有教授（刑法）であった。彼は、他の法科大学院での教育歴をもち、そこで合格者も出していた。三枝教授は、他の法科大学院では、「演習科目」を多く設置して、「書く力」を養成している。信州大学法科大学院も、それにならってカリキュラム改編をするべきだと主張した。

［source：］さらなる格闘・・・改革期 https://www.shinshu-u.ac.jp/graduate/law/a12year/history/index5.html
```

　こちらもページタイトルが「さらなる格闘・・・改革期」とあるだけで，「信州大学大学院　法曹法務研究科」とはありません。

 - 信州大学法科大学院十二年史 https://www.shinshu-u.ac.jp/graduate/law/a12year/  

　ロゴマークと一緒にある「信州大学大学院　法曹法務研究科」というリンクを開いたところ，上記のページタイトルが「信州大学法科大学院十二年史」と，長い歴史と伝統を感じさせるページが開かれました。これも深澤諭史弁護士のリンクの選択となったのかもしれません。

　信州大学に法科大学院というの初めてみたとも，意外にも感じたところですが，信州大学はかなりの難関で学力が高いという情報を見たように思います。このあと確認しますが，能登町での事件のことになります。たぶん信州大学だったと思います。その事件でテレビでも紹介されていました。

能登町 信州大学 - Google 検索 https://t.co/g9g072MZQF

【能登・高１女子遺体】事故死の男子学生が通う信州大が会見「目立つ印象ではなかった」　昨年後期から成績落ち - 産経ニュース https://t.co/0VAB8Z39zH

死亡の元信州大生を書類送検へ　石川・高１女子殺害：朝日新聞デジタル https://t.co/AiAjC0HPOW

　間違いがないことを確認しましたが，それらしい記憶通り，信州大学は本部が長野県松本市とありました。信州大学は農業に特化した大学というイメージがあっただけに，「信州大学大学院　法曹法務研究科」や法科大学院というのはかなり意外です。ロースクールにもなるのでしょう。

　狂牛病というのを思い出しましたが，人が狂って怪物化していると思えてならないのが弁護士で，その具体的な代表格が深澤諭史弁護士になります。その弁護士脳にとって，我々一般社会は，畜産の農場に見えているのではないかという，深刻重大な危機感を感じ，これは避けれない大問題です。

　結果の大きさは，そのまま裁判の判決にも共通しそうですが，「信州大学法科大学院は、2009（平成21）年の司法試験において、初の合格者を出し、存続の危機を乗り切った。」という結果の左右の度合いは，はるかに想像を絶するものです。

```
　1990年代に、日本は「改革の時代」にはいる。最初に実現したのは、1994（平成6）年の「政治改革」であった。政治改革がめざした「政治のリーダーシップ」は1998（平成10）年の「中央省庁等改革基本法」を典型例とする行政改革を急ピッチで成し遂げ、同時に司法改革の推進力となったのである。
　司法改革を担ったのは、司法制度改革審議会である。1999（平成11）年に成立した司法制度改革審議会設置法2条は、司法制度改革審議会の役割をこう規定している。「二十一世紀の我が国社会において司法が果たすべき役割を明らかにし、国民がより利用しやすい司法制度の実現、国民の司法制度への関与、法曹の在り方とその機能の充実強化その他の司法制度の改革と基盤の整備に関し必要な基本的な施策について調査審議する」。ここに、国民が司法制度をより利用しやすくするために、国民自身が司法制度に関与し（裁判員制度）、また、国民の司法への参加を補助する「法曹」を充実強化する（法科大学院制度）という司法改革の二つの大きな制度改革のプランが、すでに示されている。
　司法制度改革審議会は、1999（平成11）年12月21日に「司法制度改革に向けて−論点整理−」を発表する。そこには、司法制度改革が「民法典の編さんから100年、日本国憲法制定から50年の今この時にあたって、司法に豊かな活力を吹き込むための根本的な制度改革」であり、また、「近代の幕開け以来、130年にわたってこの国が背負い続けてきた課題、すなわち、一国の法がこの国の血肉と化し、『この国のかたち』となるため」の改革であるとの認識が示されている。
　ところで、なぜ司法制度改革が必要なのであろうか。「論点整理」は、次のように述べる。「この国が豊かな創造性とエネルギーを取り戻すため」、「政治改革・行政改革・地方分権推進・規制緩和等の経済構造改革」がなされた。これらの改革によって、「国民一人ひとりが、統治客体意識から脱却し、自律的でかつ社会的責任を負った統治主体」となることがめざされている。しかし、そのような社会においては、ともすれば、国民の間でさまざまな紛争が起きる。その紛争を「公正かつ透明な法的ルールの下で適正かつ迅速に解決される仕組み」が整えられなければならない。また、政治改革・行政改革による「統治能力の資質の向上」が行き過ぎて基本的人権を損ねることのないようにしなければならない。そのために、司法の「制度的基盤の強化」と「人的基盤の強化」が喫緊の課題とされたのである。
　「論点整理」は、構造改革後に必要となる課題に対応するには、わが国の法曹人口が少なすぎると指摘する。しかし、問題は量だけではない。重要なのは、「21世紀の司法を支えるにふさわしい資質と能力（倫理面を含む）を備えた法曹をどのようにして養成するか」である。その役割を担うのに最も適しているのは大学であるとされた。こうして、「論点整理」は、次のように、法科大学院の設立を積極的に提言したのである。

［source：］司法改革と法科大学院 https://www.shinshu-u.ac.jp/graduate/law/a12year/history/index1.html
```

　上記に別の記事の長めの引用をしましたが，「「法律家に対する教育の在り方が一国の法制度の根幹を形成する」といわれるように、古典的教養と現代社会に関する広い視野をもち、かつ、「国民の社会生活上の医師」たる専門的職業人としての自覚と資質を備えた人材」とあります。

　深澤諭史弁護士は東京大学大学院の卒業だったと思いますが，「「国民の社会生活上の医師」たる専門的職業人」に当て嵌まるのかとなると，さらに重大，深刻なツイートの数々が思い出され，その代表格に盲腸というものがありました。

〈〈〈：Linux Emacs： 2020-07-25（土曜日）01：16 　〈〈〈

* ”俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみた”という深澤諭史弁護士のツイートの記録
  :LOGBOOK:
  CLOCK: [2020-07-25 土 01:25]
  :END:

:CATEGORIES: 深澤諭史弁護士

〉〉〉：Emacs： 2020-07-25（土曜日）01：25　 〉〉〉

```
➜  ~ dp -p |grep 盲腸
 - 2017年10月05日01時03分の登録： REGEXP：”盲腸”／深澤諭史弁護士（@fukazawas）のツイートの記録（2016-05-23 11:32〜2017-09-02 15:48／2017年10月05日01時03分・24件） http://hirono2014sk.blogspot.com/2017/10/regexpfukazawas2016-05-23-11322017-09.html
 - 2017年10月06日22時27分の登録： ％@fukazawas　深澤諭史％病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど， http://hirono2014sk.blogspot.com/2017/10/fukazawas_6.html
 - 2017年10月07日20時33分の登録： ％@fukazawas　深澤諭史％病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど http://hirono2014sk.blogspot.com/2017/10/fukazawas_63.html
 - 2017年10月07日20時48分の登録： ％@fukazawas　深澤諭史％盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。 http://hirono2014sk.blogspot.com/2017/10/fukazawas_40.html
 - 2017年10月26日07時52分の登録： REGEXP：”俺，医療には詳しいんで，それで盲腸手術なんか簡単”／データベース登録済みツイートの検索（2016-05-23〜2017-09-02／2017年10月26日07時52分の記録30件） http://hirono2014sk.blogspot.com/2017/10/regexp2016-05-232017-09-0220171026075230.html
 - 2017年11月05日05時04分の登録： REGEXP：”俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ”／データベース登録済みツイートの検索（2017年11月05日05時04分の記録31件） http://hirono2014sk.blogspot.com/2017/11/regexp20171105050431.html
 - 2017年11月23日18時31分の登録： REGEXP：”俺，医療には詳しいんで，それで盲腸手術なんか簡単”／データベース登録済みツイート：2017年11月23日18時31分の記録：ユーザ・投稿：16／43件 http://hirono2014sk.blogspot.com/2017/11/regexp2017112318311643.html
 - 2017年12月25日10時33分の登録： REGEXP：”俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？”／データベース登録済みツイート：2017年12月25日10時32分の記録：ユーザ・投稿：18／43件 http://hirono2014sk.blogspot.com/2017/12/regexp2017122510321843.html
 - 2018年01月15日20時20分の登録： REGEXP：”盲腸”／深澤諭史（@fukazawas）の検索（2017-01-23〜2017-11-03／2018年01月15日20時20分の記録17件） http://hirono2014sk.blogspot.com/2018/01/regexpfukazawas2017-01-232017-11.html
 - 2018年02月03日20時27分の登録： REGEXP：”病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？”／データベース登録済みツイート：2018年02月03日20時26分の記録：ユーザ・投稿：26／54件 http://hirono2014sk.blogspot.com/2018/02/regexp2018020320262654.html
 - 2018年04月10日01時49分の登録： REGEXP：”病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？”／データベース登録済みツイート：2018年04月10日01時48分の記録：ユーザ・投稿：29／59件 http://hirono2014sk.blogspot.com/2018/04/regexp2018041001482959.html
 - 2018年04月10日03時29分の登録： ％@o2441　弁護士大西洋一％病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗… — なんかできそうじゃん http://hirono2014sk.blogspot.com/2018/04/o2441.html
 - 2018年04月16日16時40分の登録： REGEXP：”盲腸”／深澤諭史（@fukazawas）の検索（2016-05-23〜2018-03-18／2018年04月16日16時40分の記録29件） http://hirono2014sk.blogspot.com/2018/04/regexpfukazawas2016-05-232018-03.html
 - 2018年04月16日17時00分の登録： ％@fukazawas　深澤諭史％病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下 http://hirono2014sk.blogspot.com/2018/04/fukazawas_80.html
 - 2018年06月12日12時55分の登録： REGEXP：”病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？”／データベース登録済みツイート：2018年06月12日12時54分の記録：ユーザ・投稿：29／64件 http://hirono2014sk.blogspot.com/2018/06/regexp2018061212542964.html
 - 2018年06月24日21時34分の登録： ＼DUKEまんごう　@nan5o＼盲腸で死んだんですよ。医療過誤ですから病院をとっちめてください」という相談には注意すべき。注意する理由がわからないうちは受任すべきでない http://hirono2014sk.blogspot.com/2018/06/dukenan5o_32.html
 - 2018年12月03日08時15分の登録： REGEXP：”俺，医療には詳しいんで，それで盲腸手術なんか簡単”／データベース登録済みツイート：2018年12月03日08時14分の記録：ユーザ・投稿：31／75件 http://hirono2014sk.blogspot.com/2018/12/regexp2018120308143175.html
 - 2019年03月22日22時38分の登録： REGEXP：”俺、医療には詳しいんで。盲腸なんか簡単でしょ？”／データベース登録済みツイート：2019年03月22日22時38分の記録：ユーザ・投稿：2／3件 http://hirono2014sk.blogspot.com/2019/03/regexp20190322223823.html
 - 2019年05月24日22時28分の登録： REGEXP：”俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？”／データベース登録済みツイート：2019年05月24日22時27分の記録：ユーザ・投稿：32／81件 http://hirono2014sk.blogspot.com/2019/05/regexp2019052422273281.html
 - 2019年05月26日10時55分の登録： ＼深澤諭史　@fukazawas　RT：　@fukazawas＼病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど http://hirono2014sk.blogspot.com/2019/05/fukazawasrtfukazawas_26.html
 - 2019年06月24日22時41分の登録： REGEXP：TEXT　”盲腸”／深澤諭史（@fukazawas）の検索（2016-05-23　11：32〜2019-05-27　22：16／2019年06月24日22時41分の記録33件） http://hirono2014sk.blogspot.com/2019/06/regexptextfukazawas2016-05-2311322019.html
 - 2019年06月25日17時51分の登録： REGEXP：”俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？”／データベース登録済みツイート：2019年06月25日17時50分の記録：ユーザ・投稿：33／89件 http://hirono2014sk.blogspot.com/2019/06/regexp2019062517503389.html
 - 2019年06月25日21時34分の登録： ＼浜ちゃん　@lawer_hamachan　RT：　@fukazawas＼病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみた http://hirono2014sk.blogspot.com/2019/06/lawerhamachanrtfukazawas.html
 - 2019年10月08日08時27分の登録： ％@lawkus　ystk％この場合は「病気でいえば盲腸みたいなものです。たしかに放っておけば大変なことになる病気で、本人も苦しいですが、プロから見たらありふれた事例で処 http://hirono2014sk.blogspot.com/2019/10/lawkusystk.html
 - 2019年10月14日16時38分の登録： REGEXP：”盲腸”／深澤諭史（@fukazawas）の検索（2016-05-23〜2019-05-27／2019年10月14日16時38分の記録33件） http://hirono2014sk.blogspot.com/2019/10/regexpfukazawas2016-05-232019-05.html
 - 2019年12月03日00時03分の登録： ＼ノースライム　@noooooooorth＼盲腸になった場合に自分で手術してみる人とか、身内の人が代わりに診察にくる人とかありえないと思うんですが、法律相談の場合、自分で http://hirono2014sk.blogspot.com/2019/12/noooooooorth.html
 - 2019年12月03日00時21分の登録： REGEXP：”盲腸になった場合に自分で手術してみる人とか”／データベース登録済みツイート：2019年12月03日00時21分の記録：ユーザ・投稿：9／10件 http://hirono2014sk.blogspot.com/2019/12/regexp201912030021910.html
 - 2019年12月19日21時50分の登録： REGEXP：”盲腸”／深澤諭史（@fukazawas）の検索（2016-05-23〜2019-05-27／2019年12月19日21時50分の記録33件） http://hirono2014sk.blogspot.com/2019/12/regexpfukazawas2016-05-232019-05.html
 - 2020年04月03日13時16分の登録： ＼深澤諭史　@fukazawas＼先生，それは「腹痛がするので，自宅で簡単な盲腸手術をしようと思います。手術道具と薬は，ドラッグストアで買えますか？ホムセンがいいでしょう http://hirono2014sk.blogspot.com/2020/04/fukazawas_88.html
 - 2020年06月23日16時24分の登録： REGEXP：”俺，医療には詳しいんで，それで盲腸手術なんか簡単”／深澤諭史（@fukazawas）の検索（2016-05-23〜2020-04-03／2020年06月23日16時23分の記録26件） http://hirono2014sk.blogspot.com/2020/06/regexpfukazawas2016-05-232020-04.html
 - 2020年07月25日01時19分の登録： REGEXP：”盲腸”／深澤諭史（@fukazawas）の検索（2016-05-23〜2020-04-03／2020年07月25日01時19分の記録35件） http://hirono2014sk.blogspot.com/2020/07/regexpfukazawas2016-05-232020-04.html
```

 - （34／35） RT fukazawas（深澤諭史）｜fukazawas（深澤諭史） 日時：2020-04-03 08:25:00 +0900／2016-05-23 11:32:00 +0900 URL： https://twitter.com/fukazawas/status/1245854941672947712 https://twitter.com/fukazawas/status/734572617651347459

> 病院には，「俺，医療には詳しいんで，それで盲腸手術なんか簡単なんでしょ？だから，自分でやってみたんすけれど，敗血症になったので，治して下さい。」っていう患者は滅多に来ないだろうが，法律事務所には似たような状況の人がしょっちゅう来る。

 - （35／35） TW fukazawas（深澤諭史） 日時：2020-04-03 10:34:00 +0900 URL： https://twitter.com/fukazawas/status/1245887480802369537

> 先生，それは「腹痛がするので，自宅で簡単な盲腸手術をしようと思います。手術道具と薬は，ドラッグストアで買えますか？ホムセンがいいでしょうか。おすすめを教えてください。」というような話です。悪い相手方に返り討ちにされないように，相談… https://t.co/wZWBLmW7lW

　あまり見覚えはないように感じたのですが，今年の4月3日も新バージョンのような盲腸を引き合いにした深澤諭史弁護士のツイートがあったようです。弁護士として高度医療に匹敵するような自信がみなぎるツイートとも感じるところですが，いつもの深澤諭史弁護士の語り口です。

　知能水準が高く頭の回転が早いのか疑問なのですが，回答へのプロセスが早く単純明快，絶対的なのも深澤諭史弁護士の特徴になります。これで依頼者とトラブルが起きないのも不思議なのですが，たまに攻撃的に依頼者を腐すツイートは見かけるものの，それで大きな問題にはなっていないようです。

　昭和40年代の後半から昭和50年代の前半，1970年代にもなりますが，少年の頃，漫画で読んでいた世界観以上のすさまじさと不思議さを常に深澤諭史弁護士のツイートや発言には感じています。東大一直線などもその１つですが，想像を絶する現実感と非現実感のはざまを感じさせられます。

　弁護士というだけでなにかと都合の良い社会の仕組みにはなっているのでしょう。それが弁護士鉄道の基盤，インフラでもあります。

〈〈〈：Linux Emacs： 2020-07-25（土曜日）01：47 　〈〈〈

- TW to_pamyu（とーしょくぱみゅぱみゅ） 日時： 2020/07/24 16:04 URL： https://twitter.com/to_pamyu/status/1286557824625958912  

> 初回接見のとき「あなたの言い分、こんなふうに報道されてますよ」と伝えると「ええ？！こんなこと言ってない！」となったので「ね？捜査機関には何言っても無駄だと分かるでしょう？」と説明して黙秘の戦術がとてもとりやすかった。ありがとう！警察の大本営発表を垂れ流すメディアたち！  


