* モトケンこと矢部善朗弁護士（京都弁護士会）に対する名誉毀損の刑事告訴，被害者安藤文さん及びその家族に与えた深刻な影響

** 記録のスクリーンショット作成直後に気がついた，「福岡の女性刺殺」というTwitterトレンド，15歳少年による21歳女性殺害事件
   :LOGBOOK:
   CLOCK: [2020-08-30 日 09:57]--[2020-08-30 日 10:38] =>  0:41
   :END:

:CATEGORIES: 少年法,モトケンこと矢部善朗弁護士（京都弁護士会）

〉〉〉：Emacs： 2020-08-30（日曜日）09：57　 〉〉〉

　別のことがきっかけで，モトケンこと矢部善朗弁護士（京都弁護士会）の過去のツイートを調べていたのですが，毎回，手間の掛かる検索で，ようやくスクリーンショットの記録が出来たと思ったところで目にしたのが，標題にあるTwitterのトレンドでした。

- TW s_hirono（非常上告-最高検察庁御中_ツイッター） 日時： 2020/08/30 09:52 URL： https://twitter.com/s_hirono/status/1299872643768709121  

> 2020-08-30-091004_モトケン@motoken_tw現実的対応としては、最寄りの警察に相談に行って刑事さんとお友達になるという手もあります。　RT　.jpg https://t.co/cf6Vc9M7aa  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-30 10:02／2020/08/30 09:53 URL： https://twitter.com/kk_hirono/status/1299875070181957632 https://twitter.com/s_hirono/status/1299872716497932289  

> 2020-08-30-091654_吉松弥里さんの母親は29日、朝日新聞の取材に「悲しいです。もう頭の中がパニックで」と声を絞り出した。福岡市の自宅で2人暮らし。「明るく、可愛.jpg https://t.co/Wugx12M4d4  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-30 10:02／2020/08/30 09:53 URL： https://twitter.com/kk_hirono/status/1299875093468688384 https://twitter.com/s_hirono/status/1299872789130694656  

> 2020-08-30-093345_しばらくして白っぽいTシャツを着た少年が、刃物を手に歩いてきて「不自然なほど無表情だった」。手に持った刃物を小さい布で覆うような仕草をしてい.jpg https://t.co/bwYkpqr1Uy  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-30 10:03／2020/08/30 09:10 URL： https://twitter.com/kk_hirono/status/1299875315213201409 https://twitter.com/hirono_hideki/status/1299862042162024448  

> 福岡の女性刺殺 - Twitter検索 / Twitter https://t.co/eDqr9roBsz  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜YahooNewsTopics（Yahoo!ニュース） 日時：2020-08-30 10:03／2020/08/30 08:59 
URL： https://twitter.com/kk_hirono/status/1299875355340095490 https://twitter.com/YahooNewsTopics/status/1299859190530277377  

> 【女性刺殺 施設から失踪後殺害か】 https://t.co/UPJLP4v4MB  福岡市中央区の商業施設で28日夜、女性が殺害された事件をめぐり、現行犯逮捕された少年が、事件の前日、少年院から移ってきた更生保護施設から無断でいなくなっていたことが、捜査関係者への取材でわかった。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜NEWS_JAPAN_S（NEWS JAPAN） 日時：2020-08-30 10:03／2020/08/30 08:43 URL： https://twitter.com/kk_hirono/status/1299875379314700288 https://twitter.com/NEWS_JAPAN_S/status/1299855240854814721  

> 【福岡】商業施設のトイレで21歳女性を殺害…逮捕の15歳少年、事件の前日 少年院から移った更生保護施設から失踪 ★2  ■少年、更正施設からの失踪後に殺害か　福岡の女性刺殺事件から一夜明け、臨時休館となった商業施設「MARK IS(マークイズ)　福岡ももち」=2…  https://t.co/d7ulCkMhfO  #ニュース https://t.co/SLyydpA0GF  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-30 10:03／2020/08/30 09:14 URL： https://twitter.com/kk_hirono/status/1299875401288671232 https://twitter.com/hirono_hideki/status/1299863069686771712  

> 被害者といた友人は泣いて謝罪　福岡刺殺、遺族の言葉は：朝日新聞デジタル https://t.co/5r483e2JGw  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-30 10:03／2020/08/30 09:15 URL： https://twitter.com/kk_hirono/status/1299875421173944320 https://twitter.com/hirono_hideki/status/1299863331914706944  

> 被害者といた友人は泣いて謝罪　福岡刺殺、遺族の言葉は：朝日新聞デジタル https://t.co/5r483e2JGw 吉松弥里さんの母親は29日、朝日新聞の取材に「悲しいです。もう頭の中がパニックで」と声を絞り出した。福岡市の自宅で2人暮らし。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-30 10:04／2020/08/30 09:27 URL： https://twitter.com/kk_hirono/status/1299875486676316160 https://twitter.com/hirono_hideki/status/1299866308549341184  

> 2020年08月30日09時27分の実行記録 twitterAPI-search-lawList-mydql-add.rb "少年法" ツイート数：20/1965 リツイート数：8/1965 トータル：5863 hirono_hideki 0／1件 kk_hirono 0／0件 s_hirono 0／0件  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜mainichi_kokura（毎日新聞小倉報道部） 日時：2020-08-30 10:04／2020/08/29 02:35 URL： https://twitter.com/kk_hirono/status/1299875527986094080 https://twitter.com/mainichi_kokura/status/1299400113211793409  

> 福岡市のマークイズ福岡ももちで起きた刺殺事件。現行犯逮捕されたのは15歳の少年でした。現場で何が起きていたのか。居合わせた人の証言を。  刃渡り18.5センチの包丁持った15歳逮捕　福岡の商業施設で女性刺され死亡 - 毎日新聞 https://t.co/qs1gOW8DGI  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-30 10:04／2020/08/30 09:48 URL： https://twitter.com/kk_hirono/status/1299875643803332609 https://twitter.com/hirono_hideki/status/1299871569284534273  

> 2020年08月30日08時37分の登録： ＼感熱紙(疑似太陽炉)　@thermalpaper00＼「会合に参加していても飲食できていたことの証明にはならない」という点に思い至らない想像力の無さが今の無様な状況を生 https://t.co/2x0v1uUPMK  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-30 10:04／2020/08/30 09:48 URL： https://twitter.com/kk_hirono/status/1299875679232618496 https://twitter.com/hirono_hideki/status/1299871648322002945  

> 2020年08月30日09時47分の登録： REGEXP：”少年．＊逮捕”／データベース登録済みツイートの検索：2020-08-28〜2020-08-29／2020年08月30日09時47分の記録：ユーザ・投稿：6／9件 https://t.co/bkmFcCigtG  

　はっきりとは憶えていませんが，一昨日，昨日は，一度も家のテレビをつけておらず，昨夜はTwitterの「恐怖新聞」というトレンドがきっかけで，0時30分少し前ぐらいにテレビをつけ，20分ぐらいつけたままにしていたと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-30 10:09／2020/08/30 00:30 URL： https://twitter.com/kk_hirono/status/1299876990980292608 https://twitter.com/hirono_hideki/status/1299731249456529414  

> (7) #恐怖新聞 - Twitter検索 / Twitter https://t.co/pvzKu2zH8o  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜modelpress（モデルプレス） 日時：2020-08-30 10:10／2020/08/30 00:22 URL： https://twitter.com/kk_hirono/status/1299877062111420417 https://twitter.com/modelpress/status/1299729075880124416  

> 白石聖『#恐怖新聞』連ドラ初主演＆初ホラーに挑む思い明かす  ゼクシィCMで話題になった #白石聖 の存在感が光る  ▼詳細・写真  https://t.co/Yqu9qocL8N  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜shiraishi_sei（白石聖） 日時：2020-08-30 10:10／2020/08/29 22:07 URL： https://twitter.com/kk_hirono/status/1299877163982712833 https://twitter.com/shiraishi_sei/status/1299695248008855552  

> 今夜11時40分から、 オトナの土ドラ #恐怖新聞🗞 第一話スタートです！是非ご覧ください！！ゾゾゾ〜 https://t.co/zzL93aIhlm  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜taiki__official（佐藤大樹 EXILE/FANTASTICS） 日時：2020-08-30 10:10／2020/08/29 20:29 URL： https://twitter.com/kk_hirono/status/1299877174808211456 https://twitter.com/taiki__official/status/1299670558603317248  

> いよいよ今夜‼️  ドラマ『恐怖新聞』 スタートです📺  ホラー好きな人も 苦手だよ🙀の方も 楽しめる作品です！  そして…観た人の 色んな考察が楽しみです！  真夏のホラーサスペンス #恐怖新聞 で考察や感想を 沢山呟いてくださーい👻 https://t.co/RCxwOysY9m  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-30 10:10／2020/08/30 00:37 URL： https://twitter.com/kk_hirono/status/1299877230340841474 https://twitter.com/hirono_hideki/status/1299732836388237312  

> [新]オトナの土ドラ・恐怖新聞　#1[字]     8/29 (土) 23:40 ～ 0:35 （55分） この時間帯の番組表      石川テレビ(Ch.8)     ドラマ - 国内ドラマ https://t.co/9gmvZv60T5  

　ちょうどドラマが終わったタイミングでテレビをつけていたようです。「恐怖新聞」はテレビアニメでも放送はなかったように思いますが，実写版というのは全く意外でした。このタイミングでと思い出したのが，岡口基一裁判官とも関わりのある漫画の得意な弁護士のブログです。

　「福岡の女性刺殺」というTwitterトレンドは，もう消えていますが，昨夜は思わぬところから，Twitterのトレンドでも見かけていなかったニュースを知り，そのことがきっかけで，モトケンこと矢部善朗弁護士（京都弁護士会）のことに繋がっています。

スガキヤが30店舗を閉鎖へ 中日新聞報道 / Twitter https://t.co/iUIvkMOTUt

　昨日から長く続くのが，上記のTwitterトレンドです。ジャスコ若宮店で，被告発人大網健二の家族とスガキヤのラーメンを食べたことなど思い出しました。平成3年7月です。

福岡刺殺、死亡女性は21歳のアルバイト（共同通信） - Yahoo!ニュース https://t.co/YCb8BIH0hE  \n 8/29(土) 8:24配信

女性の上半身中心に複数の傷　逮捕の少年と面識なし、福岡 ｜ 共同通信 https://t.co/q5sb1H84Bb 2020/8/29 12:51 (JST)

少年、更生保護施設から失踪後に現場へ　福岡の女性刺殺：朝日新聞デジタル https://t.co/3nvjgLyr4x  \n 会員記事 \n  \n 2020年8月30日 5時00分

女性刺され死亡、銃刀法違反容疑で自称15歳逮捕　福岡 - ライブドアニュース https://t.co/RpqOfwi2lq 28日午後7時半ごろ、福岡市中央区地行浜（じぎょうはま）2丁目の大型商業施設「MARK　IS（マークイズ）　福岡ももち」で、女性が男に刃物で刺されたと110番通報があった。

　最後に見つけた記事で，「28日午後7時半ごろ」という事件発生時刻がわかりましたが，他の記事は，28日夜などとなっていました。大型商業施設が夜遅くまで営業しているというイメージもなく，その辺りも気になっていたのですが，トレンドで事件を知ったのが30日朝というのも気になります。

　Twitterのトレンドのツイートで，久しぶりにみかけた少年法が問題とされた15歳少年による重大事件ですが，弁護士の反応というのはほとんど見ておらず，その辺りも気になっています。

〈〈〈：Emacs： 2020-08-30（日曜日）10：38 　〈〈〈

** 少年法をキーワードにした，主に法クラの弁護士らのツイートの記録，弁護士鉄道の歴史
   :LOGBOOK:
   CLOCK: [2020-08-30 日 10:40]--[2020-08-30 日 11:08] =>  0:28
   :END:

:CATEGORIES: 少年法

〉〉〉：Emacs： 2020-08-30（日曜日）10：40　 〉〉〉

```
(py37_env) a66@a66-XTe:~$ ajx-all-user-mysql-REGEXP_blogger_hirono2014sk.rb "少年法"
SELECT * FROM tw_user_tweet WHERE  tweet REGEXP "少年法"   ORDER BY tw_date ASC
motoken_tw
モトケン（motoken_tw）
ユーザ名称：モトケン [screen_name]ユーザ名：motoken_tw フォロー数：1858 フォロワー数：25420 ツイート数：134125
Hideo_Ogura
小倉秀夫（Hideo_Ogura）
ユーザ名称：小倉秀夫 [screen_name]ユーザ名：Hideo_Ogura フォロー数：73 フォロワー数：13703 ツイート数：167618
amneris84
Shoko Egawa（amneris84）
ユーザ名称：Shoko Egawa [screen_name]ユーザ名：amneris84 フォロー数：631 フォロワー数：293010 ツイート数：107738
sakamotomasayuk
坂本正幸（sakamotomasayuk）
ユーザ名称：坂本正幸 [screen_name]ユーザ名：sakamotomasayuk フォロー数：5663 フォロワー数：7025 ツイート数：235708
BarlKarth
高島章（BarlKarth）
ユーザ名称：高島章 [screen_name]ユーザ名：BarlKarth フォロー数：4359 フォロワー数：11430 ツイート数：60023
Bibendum65
塩タンメン（Bibendum65）
ユーザ名称：塩タンメン [screen_name]ユーザ名：Bibendum65 フォロー数：3601 フォロワー数：3187 ツイート数：380046
a_anzai
安西敦 Atsushi Anzai（a_anzai）
ユーザ名称：安西敦 Atsushi Anzai [screen_name]ユーザ名：a_anzai フォロー数：334 フォロワー数：2496 ツイート数：4726
TobenMedia
東京弁護士会（TobenMedia）
ユーザ名称：東京弁護士会 [screen_name]ユーザ名：TobenMedia フォロー数：0 フォロワー数：4232 ツイート数：2608
kotadon
```

　ちょうど処理が完了したところです。エラーが出ていないので投稿済みのはずです。→　REGEXP：”少年法”／データベース登録済みツイート：2020年08月30日10時38分の記録：ユーザ・投稿：99／608件

　10日からまだ2週間は経っていないと思いますが，同じ福岡県の田川市で，女子大生による気になるニュースを読んでいました。何がきっかけだったのか思い出せないのですが，ふとしたことでたまたま目にしたニュースでした。交通死亡事故ですが，逮捕はされていませんでした。

```
 - 2020年08月30日09時47分の登録： REGEXP：”少年法”／データベース登録済みツイートの検索：2020-08-23〜2020-08-30／2020年08月30日09時46分の記録：ユーザ・投稿：12／16件 http://hirono2014sk.blogspot.com/2020/08/regexp2020-08-232020-08.html
 - 2020年08月30日09時47分の登録： REGEXP：”少年．＊逮捕”／データベース登録済みツイートの検索：2020-08-28〜2020-08-29／2020年08月30日09時47分の記録：ユーザ・投稿：6／9件 http://hirono2014sk.blogspot.com/2020/08/regexp2020-08-282020-08-2920200830094769.html
 - 2020年08月30日10時41分の登録： REGEXP：”少年法”／データベース登録済みツイート：2020年08月30日10時38分の記録：ユーザ・投稿：99／608件 http://hirono2014sk.blogspot.com/2020/08/regexp20200830103899608.html
```

 - （01／16） TW hamachi_m（浜地雅一（衆議院議員.弁護士)） 日時： 2020-08-23 21:17:00 +0900 URL： https://twitter.com/hamachi_m/status/1297508328466046976

> 今日は宮崎県本部の夏季議員研修会にWEB参加しました。私からは憲法と少年法改正についてお話しさせて頂きました。 https://t.co/OSxKtbjwJo

　ほとんど見覚えのないアカウントですが，リストには登録済みのようです。「浜地雅一（衆議院議員.弁護士）」とあります。宮崎県とありますが，強姦事件の示談強要で弁護士が問題となり，弁護士会が懲戒請求を不処分にしたと記憶にあります。

 - （04／16） TW mayukotaniguchi（まゆこ） 日時： 2020-08-24 23:23:00 +0900 URL： https://twitter.com/mayukotaniguchi/status/1297902306319429632

> 少年法適用年齢引下げには超大反対、選挙権行使可能年齢引下げには賛成、飲酒喫煙年齢引下げには消極的に賛成、行為能力年齢引下げには消極的に反対。
> 一言に成人年齢って言っても示すところが多義的なのに、無理や…
>
> 続きは質問箱へ… https://t.co/Uw0tx3ioYt

 - （05／16） TW mayukotaniguchi（まゆこ） 日時： 2020-08-25 00:04:00 +0900 URL： https://twitter.com/mayukotaniguchi/status/1297912661443674112

> @MilesNeismith 少年法適用年齢引下げに反対しすぎて疲れたので、、、徒労感を感じているところです。

 - （06／16） TW Redips00（赤ネコ@弁護士兼マンガ家） 日時： 2020-08-25 16:10:00 +0900 URL： https://twitter.com/Redips00/status/1298155651311390720

> 少年法がまたも責められているようなので、うちの少年法を出してみる。
> https://t.co/VVvjgNHHZN 『法律擬人化！赤ネコ式六法全書』社会の歪みは弱い者のところから出る。厳罰を検討する前にまずは己を恥じてもいいんじ… https://t.co/ozD3ffbCDb

 - （07／16） TW KPf_M（Kenji Takeuchi） 日時： 2020-08-25 21:45:00 +0900 URL： https://twitter.com/KPf_M/status/1298239981522022401

> 「処罰より立ち直りに主眼を置く少年法の趣旨から後退していると言え、真に社会に有益なのか、懸念が拭えない。更生を重んじた丁寧な議論をさらに求めたい。」＞北海道新聞・社説（8/24）「少年法改正論議　厳罰化より更生重視で」 https://t.co/VEe1NAhx5L

 - （12／16） TW okumuraosaka（okumuraosaka） 日時： 2020-08-28 17:25:00 +0900 URL： https://twitter.com/okumuraosaka/status/1299261912983642112

> 少年法改正されてだいぶになるので 間違ってるよね・・児童福祉法違反は、家庭裁判所で審理されます。 これらの罪は、「児童」であることを認識していなくても成立します。 https://t.co/HbUqZlW2ae

 - （13／16） RT hiroaki_t（takahashi hiroaki）｜worldjourney（viajeros） 日時：2020-08-29 12:02:00 +0900／2020-08-29 08:53:00 +0900 URL： https://twitter.com/hiroaki_t/status/1299543014671409153 https://twitter.com/worldjourney/status/1299495296955592704
福岡の事件の被疑者が15歳だということで正義のヒーローの皆様が早速少年法にお怒りで「少年でも関係ねえ厳罰に処せ、親を引きずり出せ」とか言ってたりするんだけど、結局成人扱いなのか子ども扱いなのか

 - （14／16） TW KPf_M（Kenji Takeuchi） 日時： 2020-08-30 08:15:00 +0900 URL： https://twitter.com/KPf_M/status/1299848174773788672

> 「中山さんは弱い立場の人に寄り添い続けている。その人生の軌跡から、子どもを包み込む少年法の精神の大切さを教えられる。」＞余録：福岡の筑豊は炭鉱労働者の町だった… - 毎日新聞 https://t.co/aUmDviZIOv

　意外なところで，福岡の筑豊が出てきましたが，修羅の国とも呼ばれる福岡県で，特に治安が悪く危険という情報をネットで見かけてきました。特に目立ったのが筑豊に入るのか再確認が必要ですが，福岡県田川市でした。

 - （15／16） RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜EDxFaXiMEs0CGEJ（ドラえもんどら焼） 日時：2020-08-30 09:23:00 +0900／2020-08-29 22:13:00 +0900 URL： https://twitter.com/hirono_hideki/status/1299865282261917696 https://twitter.com/EDxFaXiMEs0CGEJ/status/1299696772319571970
本当にここ身近で怖いです。 \n よく行ってます。 \n もし、この日もここにいて刺されたらと思うとゾッとしますね。 \n 殺人したんですよ、 \n 少年法とか必要なんですかね～。 \n 21歳でまだこれからというのに、 \n 悪のルーレットを引き当てたみたいで、本… https://t.co/dMhIrfGZCc

 - （16／16） TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-08-30 09:27:00 +0900 URL： https://twitter.com/hirono_hideki/status/1299866308549341184

> 2020年08月30日09時27分の実行記録
> twitterAPI-search-lawList-mydql-add.rb ""少年法""
> ツイート数：20/1965 リツイート数：8/1965 トータル：5863
> hirono_hi… https://t.co/4dgqfKFsHv

　これもTwitterAPIで，私が一応のリミットとしている8500には到達しなかったもので，昨夜も同じことが2回ありました。注目度の高そうなニュースでした。

　次がデータベースに登録済みの全ツイートを対象にしたまとめ記事になります。

```
アカウント名	ツイート数	リツイート数
モトケン（motoken_tw）	35	1
小倉秀夫（Hideo_Ogura）	279	0
Shoko Egawa（amneris84）	7	0
坂本正幸（sakamotomasayuk）	8	0
高島章（弁護士）（BarlKarth）	76	0
仙猫カリン@鼻血ブー太郎（Bibendum65）	4	0
安西敦 Atsushi Anzai（a_anzai）	5	0
東京弁護士会（TobenMedia）	2	0
こたぴょん（kotadon）	21	0
午睡（ichbinschlaefig）	1	0
廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜（hirono_hideki）	5	3
弁護士 柴田幸正（yukimasashibata）	1	1
竹田圭吾（KeigoTakeda）	1	0
阿野寛之（pilori1616）	0	4
村松 謙（kmuramatsu）	4	0
hznf（_hznf_）	0	1
弁護士 市川 寛（imaloser15）	0	1
サイ太（uwaaaa）	1	0
弁護士 中村憲昭（nakanori930）	0	1
toujin（tou_jin）	0	5
Kamei, Gentaro（gk1024）	1	0
櫻井光政（okinahimeji）	2	0
やっしー（yassi___）	1	0
関西大学法学部　永田憲史（penology_nagata）	2	1
町村泰貴（matimura）	1	0
前田恒彦　－元特捜部主任検事のつぶやき－（maedatsunehiko）	1	0
弁護士 市川 寛（imarockcaster42）	0	1
おおはしひろき（hiroki0084）	0	1
ＫＢブラック（bengoshi_black）	1	1
深澤諭史（fukazawas）	3	9
TORU OKUMURA（okumuraosaka）	4	0
でゅーくまんごう(●―●)（nan5o）	1	0
弁護士中村晃基（福山）（koukitei）	4	1
赤ネコ漫画家弁護士＠LINEスタンプ！（Redips00）	2	0
弁護士　戸舘圭之（todateyoshiyuki）	2	4
中村剛（take-five）（take___five）	1	0
うちだ（仮名）（unknownBar）	0	1
弁護士　野田隼人（nodahayato）	2	0
たろう featuring TARO（kaito_regend）	1	0
k.a（feather03）	0	1
中村元弥（1961kumachin）	1	2
大山定伸（oyamalaw）	1	0
とらきち（torakiti0405）	1	0
木下裕一（hirokazu41519）	1	0
落合洋司 Yoji Ochiai（yjochi）	1	0
木村草太（SotaKimura）	1	0
黄金糞闘士うのじ（un_co_the2nd）	0	2
モフ（mofjd）	0	1
福岡県弁護士会【公式】（fben2016）	1	0
弁護士 千綿 俊一郎（s_chiwata）	0	1
向原総合法律事務所　弁護士向原（harrier0516osk）	1	0
Kenji Takeuchi（KPf_M）	6	4
寺町東子（teramachi_toko）	0	1
非常上告-最高検察庁御中_ツイッター（s_hirono）	15	0
嘘つき弁護士。（LiarLawyer800）	1	1
給費制実現活動弁護士（kyuhi_realize）	0	1
なかじ（h_nakaji）	0	1
えきなんローヤー?（ekinan_lawyer）	0	1
リーチ一発ツモ裏１（luckymangan）	0	1
微笑みのロイヤー（smile_spirits）	0	1
かもん弓（鴨志田 祐美）（kamo629782）	1	0
弁護士 太田啓子（katepanda2）	0	1
弁護士 吉峯耕平（「カンママル」撲滅委員会）（kyoshimine）	1	0
全司法労働組合（本部）（ZenshihoHombu）	1	0
弁護士 中原潤一（lawyernakahara）	1	0
自家製パンチェッタ（jikapan）	1	0
斎藤司（tsukassaito）	0	2
南野 森（Minamino S.）（sspmi）	0	1
中野昌宏 Masahiro Nakano（nakano0316）	0	1
本 秀紀（MotoBuch1228）	0	1
ぽぽひと@内閣調査室所属（popohito）	0	1
黒田法律事務所 弁護士黒田厚志（kurodalawoffice）	0	3
カール=レーフラー（hirohika777）	0	1
まっつん（kazuaki0606）	0	2
KURODA TAKASHI（kitaguni_b）	0	1
福山和人（kaz_fukuyama）	1	0
京都弁護士会　広報委員会（KBAsns）	1	0
弁護士 上瀧浩子（sanngatuusagino）	0	1
山口直也 Naoya Yamaguchi（nashyama）	1	0
漂う蛸（k1e8i1k5o2k2e29）	1	0
弁護士　志賀晃（SHIGA.Akira）（a_shiga34496）	1	0
国立研究開発個人原田知世研究機構（norinori1968）	0	1
安藤俊文（toshifumi_Ando）	0	1
y（yu_l09）	0	1
ケナー（tyousan09）	0	1
Issei Sakamoto（torres9agyi）	0	1
ゆーか（nyamu624）	0	1
₍ᐢꙬᐢ₎狸の金玉₍ᐢꙬᐢ₎（inonianomezak）	0	1
アリアンデルの猫（laparkadejapon）	0	1
櫻町直樹（n_sakuramachi）	1	0
浜地雅一（衆議院議員.弁護士)（hamachi_m）	1	0
COLORS＠73期（COLORS_I_am_you）	1	0
司法少年リオ（white_cosmos_）	0	1
まゆこ（mayukotaniguchi）	2	0
半田 望（Handalaw）	0	1
Yasuomi SAWA 澤康臣（yasuomisawa）	0	1
藤井誠二（seijifujii1965）	0	1
takahashi hiroaki（hiroaki_t）	0	1
刑事告発・非常上告＿金沢地方検察庁御中（kk_hirono）	1	1


［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”少年法”／データベース登録済みツイート：2020年08月30日10時38分の記録：ユーザ・投稿：99／608件 http://hirono2014sk.blogspot.com/2020/08/regexp20200830103899608.html
```

 - （001／608） TW motoken_tw（モトケン） 日時： 2010-09-17 12:24:00 +0900 URL： https://twitter.com/motoken_tw/status/24725771299

> へ！RT @okumuraosaka: 少年法改正前に、同一児童に強制わいせつ罪（176条後段）と児童淫行罪を繰り返したのは、地裁・家裁で実刑になっているのだが、弁護人は「併合の利益」のへの字も主張してない。

 - （002／608） TW Hideo_Ogura（小倉秀夫） 日時： 2010-11-15 10:38:00 +0900 URL： https://twitter.com/Hideo_Ogura/status/3985265836171264

> 普通に考えると、敢えて少年法の趣旨に反して少年の実名を掲載した雑誌社が、敢えて本名ではなく通称を掲載する理由ってないように思うんだけどね。RT @mserai: 母子殺害の件で記事にしてるソースを貼れと指摘されるんですか？

〈〈〈：Emacs： 2020-08-30（日曜日）11：08 　〈〈〈

