#+TODO: TODO EDITEING | DONE

* 「夫（それ）とくらべてハ私などハ、うん（運）がつよくなにほど死ぬるバ（場）へでゝもし（死）なれず」という乙女あての坂本龍馬の手紙で思い出した，被告発人長谷川紘之弁護士の夫々
  :LOGBOOK:
  CLOCK: [2020-07-10 金 00:18]--[2020-07-10 金 09:58] =>  9:40
  :END:

:CATEGORIES: 被告発人長谷川紘之弁護士

〉〉〉：Emacs： 2020-07-10（金曜日）00：18　 〉〉〉

　「夫々」という漢字を「それぞれ」と読める人はどれほどいるのかと疑問ですが，福井刑務所の受刑中では，意味を調べるのもかなり時間が掛かったような記憶があります。まるで暗号の解読です。

```
扨も／＼人間の一世（ひとよ）ハがてん（合点）の行ぬハ元よりの事、うん（運）のわるいものハふろ（風呂）よりいでんとして、きんたま（睾丸）をつめわりて死ぬるものもあり。夫（それ）とくらべてハ私などハ、うん（運）がつよくなにほど死ぬるバ（場）へでゝもし（死）なれず、じぶん（自分）でしのふと思ふても又いきねバならん事ニなり、今にてハ日本第一の人物勝憐（麟）太郎殿という人にでし（弟子）になり、日々兼而（かねて）思付所をせい（精）といたしおり申候。

［source：］坂本龍馬 手紙 文久三年三月二十日　坂本乙女あて https://www.aozora.gr.jp/cards/000908/files/51392_39891.html
```

　　坂本乙女は坂本龍馬の姉で，大柄で仁王様のような女傑として漫画に描かれていたという記憶があります。気が弱く優しい性格だった幼少期の坂本龍馬を，見守りながら育て上げたようにも描かれていたと記憶にあります。作者の思い入れが時に強すぎると感じることもある歴史の人物でもあります。　

```
「夫々」という日本語。一体なんと読むのでしょうか？
もちろん「ふふ」とか「おっとおっと」じゃありません。
これも音で聞けば皆さんおなじみの日本語、きっとあなたも声に出して言ったことがあるはずです♪　そこで、まずは意味を調べてみましょう。
小学館デジタル大辞泉によると、「夫々」の意味は次のとおりです。

「複数の物・人の、ひとつひとつ・ひとりひとり。おのおの。めいめい」

会話で使われるときには、
・夫々のやり方がある
・冠婚葬祭のマナーは地方によって夫々ちがう
といった使われ方が一般的です。
なんとなく想像ができたでしょうか？　では正解を見てみましょう、コチラです！

［source：］「夫々」読める？「ふふ」じゃなくて、絶対知ってるあの単語 https://cancam.jp/archives/732654
```

　「其々」とも書くとのことですが，こちらの方が戦前の大審院の判例などで見かけた憶えのある漢字になります。

　私は被害者安藤文さんの原告代理人となった被告発人長谷川紘之弁護士が，夫婦である意味の期待を持たせるために仕込んだ小細工のように考えたことがあったのですが，今，意外な坂本龍馬をきっかけに思い出したところ，いっそう弁護士窓外の危険性と悪質さを感じるところです。

〈〈〈：Linux Emacs： 2020-07-10（金曜日）00：32 　〈〈〈

* 昭和48年2月24日「森進一の母が自殺」という記事の背景と，昭和48年5月23日「吉田拓郎，逮捕　金沢事件」に共通する狂言
  :LOGBOOK:
  CLOCK: [2020-07-10 金 09:58]
  :END:

:CATEGORIES: 狂言

〉〉〉：Emacs： 2020-07-10（金曜日）09：58　 〉〉〉

```
森進一の母が自殺

お気に入り詳細を見る
昭和48年２／24午前４時30分、世田谷区深沢２丁目の森進一（25）の自宅で、コタツの中で母の尚子（47）がガス自殺をしているのを、慶応高校１年の次男（16）が発見した。尚子は10年前からバセドー氏病で、昨年８月にも入院していた。

出典
森進一…おふくろさん事件…妄想を言っていた女性はどう言う名前で、今は何をしてい... - Yahoo!知恵袋



中日新聞：1973.2.24.夕刊

［source：］【昭和】芸能人の事件・事故まとめ！ - NAVER まとめ https://matome.naver.jp/odai/2138984261143904801?&page=3
```

```
１９７３年　５月２３日

吉田拓郎、逮捕　金沢事件

出典
吉田拓郎 - Wikipedia

新六文銭のツアー中に拓郎が逮捕されるという事件が発生（通称：金沢事件）。
ファンの女子大生が4月18日の金沢公演の夜に拓郎に暴行されたと訴えたが、
結局女子大生の狂言であることがわかり不起訴となり6月2日に釈放された。

［source：］【昭和】芸能人の事件・事故まとめ！ - NAVER まとめ https://matome.naver.jp/odai/2138984261143904801?&page=3
```

　12ページに分かれているようですが，その3ページ目になります。時系列に並んでいるようですが，２つのニュースが続けて並んでいます。森進一の母親の自殺のことは昨日知ったばかりでしたが，吉田拓郎の事件のことはずっと前から知っていて，詳細なものも読んでいます。

　森進一の件は，中日新聞1973年2月24日夕刊が記事の切り抜きとして掲載されています。森進一の婚約不履行という裁判のことは触れられておらず，病苦からノイローゼとあります。

 - » 吉田拓郎　久保利 - Google 検索 https://t.co/p0wb7xLOa2

 - » 吉田拓郎×久保利英明弁護士（For Life１９７６創刊春号）: machikado https://t.co/H0OuQyz4dx

　以前読んだのと同じ記事かわからないですが，だいたい同じ内容になっていると思います。「だから弁護団がジェット機で小松まで 飛んで来たなんて話になると、ギョギョッてな感じになるんでしょ。」という辺りも記憶にあった内容です。

　ページ内検索をしたところ「狂言」はありませんでした。

　昨夜から時間を掛けて，森進一の女性の狂言とされた婚約不履行の裁判について調べたのですが，ネット上の情報はわずかなものであらたな判断材料は見つけることができませんでした。

〈〈〈：Linux Emacs： 2020-07-10（金曜日）10：36 　〈〈〈

