* WSL2のUbuntuでのspt,mysql-server,rubyのエラー，インストルのし直し

　電気とテレビをつけたまま寝ていて，目が覚めて時間を見るとちょうど4時でした。データベースの更新作業を実行したところエラーが出ていました。Rubyのスクリプトがエラーを出していたのですが，原因はMySQLにもありそうでした。

　そういえばしばらくaptのアップデートをしていなかったと思い始めたところ，mysql-serverのバージョンに問題があって先に進めませんでした。他のMySQL関連のパッケージより1つ古くなっているのです。

　MySQLを削除し，インストールし直すことにしたのですが，これもパッケージの依存関係などでなかなか削除ができませんでした。

```
sudo dpkg --force-all -r  dbconfig-mysql libmysqlclient-dev mysql-client mysql-client-core-8.0 mysql-common mysql-server  mysql-server-8.0 php-mysql php7.4-mysql ruby-mysql2

sudo dpkg -r mysql-server-8.0
```

　--force-allというオプションは，対象のパッケージが設定ファイルを持たないとエラーが出るようでした。それでオプションを外して，mysql-server-8.0を削除しました。あとは普通にパッケージのインストールのし直しです。

　MySQLを扱うスクリプトの実行をすると，やはりRubyでエラーが出ました。モジュールのファイルを読み込まないので，ｉrbを使ってモジュールを読み込むパスを調べようとしたところ，次のようなエラーがでました。

```
 cannot load such file -- /usr/lib/ruby/gems/2.7.0/gems/irb-1.2.4/exe/irb (LoadError)
```

　何の間違いがあったのか，複数の場所にRubyのライブリーがインストールされていて，Rubyの再インストールを繰り返しても結果が同じでした。問題のありそうなパスのディレクトリーを削除し，Rubyをインストールし直すことでようやく直りました。どちらも経験のないエラーでした。

　終わったのは7時10分頃でした。一時は，WSL2のUbuntuの入れ直しも考えたのですが，何が起こるかわからず，メンテナンスは大事だと思いました。

* ジャーナリストの江川紹子氏のタイムラインで知った，「事故のドライバー、無罪だったのに免許戻らず職失う…「行政の対応ひどい」弁護団がクラファン」
  :LOGBOOK:
  CLOCK: [2020-08-12 水 14:36]--[2020-08-12 水 17:38] =>  3:02
  :END:

:CATEGORIES: ジャーナリストの江川紹子氏,大西洋一弁護士,無罪,行政,弁護団,クラウドファンディング

〉〉〉：Emacs： 2020-08-12（水曜日）14：36　 〉〉〉

　最近になってちょくちょくした割合で見かけるようになった，ジャーナリストの江川紹子氏のタイムラインでの大西洋一弁護士のツイートです。Windows10の一太郎で告発状の作成をやっていたのですが，深澤諭史弁護士のタイムラインで記録の必要性を感じUbuntuに戻りました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜amneris84（Shoko Egawa） 日時：2020-08-12 14:39／2020/08/12 12:36 URL： https://twitter.com/kk_hirono/status/1293421868599226368 https://twitter.com/amneris84/status/1293390908621111296  

> これはひどいわ～ https://t.co/AlKz21VYtg  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜o2441（弁護士大西洋一） 日時：2020-08-12 14:40／2020/08/12 10:28 URL： https://twitter.com/kk_hirono/status/1293422017627086850 https://twitter.com/o2441/status/1293358684886638594  

> これは同感。無罪なんだから免許戻してよ。  「無罪確定でも免許戻らず」ドライバーの職失う…手弁当の弁護団、クラファン立ち上げ|弁護士ドットコムニュース https://t.co/WvPfmj31kE @bengo4topicsより  

事故のドライバー、無罪だったのに免許戻らず職失う…「行政の対応ひどい」弁護団がクラファン - 弁護士ドットコム https://t.co/XVhOXhYyjN 2020年08月12日 10時23分

若柳拓志の執筆記事一覧[PAGE1]|弁護士ドットコムニュース https://t.co/FEpwEjhaQr  \n 若柳拓志 \n 弁護士ドットコムニュース編集部。出版社（編集職）→現職。 \n 執筆記事 7件見つかりました 1 - 7件目

　時刻は14時51分です。弁護士ドットコムのアクセスランキング1位にあった次の記事を読んでいました。できれば後で単体で取り上げておきたいとも考えています。

 - 司法試験に落ち続けて二十年、八神さん「思いが叶わなかった人がいること、忘れないで」 - 弁護士ドットコム https://www.bengo4.com/c_23/n_11575/  

　若柳拓志という記者は，弁護士ドットコムでも初めて見たように思います。リンクになっていた執筆記事一覧も7つと少なめで，読んで見覚えのある見出しの記事はありませんでした。将棋に関する記事のタイトルは，どこかで見かけていたような気はします。

無罪のあと、ちゃんとしよう！プロジェクト（田中謙二（無罪のあと、ちゃんとしよう！プロジェクト代表） 2020/07/16 公開） - クラウドファンディング READYFOR (レディーフォー)… https://t.co/OQIBVN6Wpk

　先程は気が付かなかったのですが，クラウドファンディングのページがリンクになっていました。弁護士バッチをつけた5人の男性の顔写真に，「罪なき人へ，免許証を取り戻す。」とテロップがあります。

```
支援総額

795,000円
目標金額 2,000,000円

39%
残り
33日
74人 が支援しています

［source：］無罪のあと、ちゃんとしよう！プロジェクト（田中謙二（無罪のあと、ちゃんとしよう！プロジェクト代表） 2020/07/16 公開） - クラウドファンディング READYFOR (レディーフォー) https://readyfor.jp/projects/innocent-menkyo2020
```

　大崎事件でみていたのと同じクラウドファンディングのサイトだと思います。目標額が200万円と余り多くは感じられないですが，39％の残り期間（33日）で，74人の支持で支援総額795,000円とあります。

　昨日は，たまたま見かけた三重県津市の交通死亡事故の判決文を読んでいました。危険運転致死傷罪の成立を否定し，予備的訴因の過失運転致死傷罪だったと思いますが，そちらを刑罰の上限で懲役7年に処したという判決でした。

　事故を起こした時のベンツのスピードが146キロか147キロになっていました。どうして特定できたスピードだったのか不思議にも思ったのですが，制限速度60キロの一般道をそのスピードで走行し，事故発生の危険性は認めたものの被告人にそこ認識があったという証明は不十分となっていました。

　刑法の勉強をしていると，最も峻厳な，というような形容が出てきたと記憶にあるのですが，厳格な事実の証明を必要とするのも刑罰の原則とされています。

　今日は，ツイートの数も多くなく，ほぼ毎日タイムラインをチェックしているジャーナリストの江川紹子氏のTwitterタイムラインで，大西洋一弁護士のツイートの引用リツイートで，「これはひどいわ～」とされていたので，この発見は，必然性を感じた納得のものです。

　運転免許の価値は，トラック運転手として結婚をした昭和62年に一度に大きな免許停止を受けたという経験もあって，身にしみてよく分かっている方だと思います。交通事故の刑事裁判で無罪となって運転免許が戻るとなれば，期待も大きく膨らみそうです。

　しかし，行政処分と刑事裁判を同列に扱うということは，憲法が保障する刑事手続の厳格さとは相反するように思えます。完全無罪を18件としたのも昨日に見て取り上げた高野隆弁護士の言行録でした。その折も，私は似たようなことを感じ，言及したと思います。

　まだ記事は全部読んでいないのですが，このクラウドファンディングは行政訴訟になるのだと思われます。過労死や過労自殺での労働基準監督署と似ているとも思いましたが，記事には警察と見かけた気がするものの，公安委員会がより正確なのかもしれません。

　記事の続きを読んでいるうちに忘れるかもしれないので，先に少し書いておきますが，女性のトラック運転手の事故の裁判で忘れられないのは，最高裁の決定か判決です。福山通運の女性運転手となっていました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 15:30／2020/02/28 17:18 URL： https://twitter.com/kk_hirono/status/1293434560852574209 https://twitter.com/hirono_hideki/status/1233305406350344192  

> 勤務中の事故、会社に負担請求可　最高裁が初判断 ｜ 共同通信 https://t.co/UKj3PY3EMl 2020/2/28 14:57 (JST)2/28 15:09 (JST)updated 原告は運送大手、福山通運（広島県福山市）のドライバーだった女性。  

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「福山通運」の検索結果 - Twilog https://t.co/6idHYycBvp

　Twilogでの福山通運の検索結果は2件のみでしたが，すぐに情報を見つけることができてよかったです。ここで見つからずに探し回ることは，これまでにたびたび経験をしてきたところのなので，あとで探し出せる工夫を考えるようになりました。

```
(py37_env) a66@a66-XTe:/mnt/ubuntu/sql$ dp -p|grep 2020年02月28日|grep 最高裁
 - 2020年02月28日17時19分の登録： ＼そらまめ　@sollamame＼いわゆる逆求償の可否について本日13:30に最高裁判例が出ています。学説上は肯定する見解が多数派ですが、これまで最高裁で未解決の論点で、 http://hirono2014sk.blogspot.com/2020/02/sollamame1330.html
 - 2020年02月28日20時58分の登録： ＼溝延祐樹　@YukiMizonobe＼被害者側の選択肢が増える点で良い判決だと思う。\n\n勤務中の事故賠償金、従業員が会社に請求可能　最高裁が初判断  http://hirono2014sk.blogspot.com/2020/02/yukimizonobe_28.html
```

　このときも大西洋一弁護士のツイートで知ったのが最初かもしれないと思っていたのですが，違うような気もして気になっていました。記憶になかったのですが，「そらまめ」というずっと前からブロックされているアカウントが最初の発見だったようです。見覚えのある内容のツイートです。

　思い出せない法律用語があって，それも思い出せないじれったさがあったのですが，「逆求償」となっていました。会社の運転手が事故を起こし，会社が賠償金の全額を被害者に支払い，そのうち応分の支払いを運転手に求めるというのが通常の求償権なのでしょう。

　不真性連帯債務ではなかったかと思います。真正連帯債務というのもあったはずですが，これはネットでも見かけた覚えがなくかなり珍しいケースになるのか，よくわからないです。

```
　不真正連帯債務と解されているもので、良くある例は、以下の３つです。

　１　会社の役員の職務上の不法行為と会社の責任
　　　役員等がその職務を行うについて悪意又は重大な過失があったときは、当該役員等は、これによって第三者に生じた損害を賠償する責任を負いますが（会社法４２９条）、役員個人が、不法行為者として、第三者に生じた損害を賠償する責任を負う場合、役員等個人と会社の債務は、不真正連帯債務の関係に立つと解されています。

　２　使用者責任
　　　被用者がその事業の執行について第三者に加えた損害を賠償する責任を原則として負いますが（民法７１５条）、被用者個人が、不法行為者として、第三者に生じた損害を賠償する責任を負う場合、被用者個人と雇用者の債務は、不真正連帯債務の関係に立つと解されています。

　３　共同不法行為
　　　共同不法行為（民法７１９条）において、各共同不法行為者の負う損害賠償債務は、不真正連帯債務であると解されています。

［source：］真正連帯債務と不真正連帯債務 https://www.nishino-law.com/publics/index/68/detail=1/b_id=114/r_id=3823/
```

　拾い読みしたところですが，わかりやすく説明されています。やはり通常の連帯債務が真正連帯債務で，連帯債務と略されることがあるとあります。やはり使用者責任と不法行為が不真性連帯債務でした。

　1から3のうち1番目にある「会社の役員の職務上の不法行為と会社の責任」が最近になって知った大きな発見でした。これは金沢西警察署刑事課強行主任から最後の電話があった後の発見になると思います。まさに市場急配センターに当て嵌まる法律問題です。

　「役員個人が、不法行為者として、第三者に生じた損害を賠償する責任を負う場合、役員等個人と会社の債務は、不真正連帯債務の関係に立つと解されています。」というのも前回に輪をかけたような発見になります。

　西野法律事務所とありますが，その名前自体，初めて見たように思いました。西野という名前はけっこうありそうですが，代表者のフルネームが多いのも法律事務所の名前の特徴かと思います。3つぐらい名前をつなげたものもたまに見かけます。

　住所が「大阪府大阪市北区西天満」となっていますが，この住所で大きな責任問題になったらしい法律事務所のニュースを２ほど，同じ頃に見かけています。請求権の時効で，確か億単位の損害賠償請求が弁護士になされていたと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 16:02／2019/11/28 00:58 URL： https://twitter.com/kk_hirono/status/1293442696183349249 https://twitter.com/hirono_hideki/status/1199719195627286528  

> 男性の親族が０９年１２月、この弁護士を担当に、トラック運転手に損害賠償を求める契約を同法人と結んだ。だが、弁護士は１６年５月になって提訴。大阪地裁は１７年１１月、民法上の損害賠償請求権の時効（３年）を理由に請求を棄却し、その後判決… https://t.co/l8sfp4YAmv  

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「請求権」の検索結果 - Twilog https://t.co/9tehwmdc0W

　Twilogで１つ発見できたようですが，記事には大阪市北区とあるだけです。こちらの方が印象も薄く，記憶になかったニュースになるのかもしれません。もう一つの西天満とあった記事の内容が，より凄いと思う内容だった気がします。

```
交通事故の相手に損害賠償を求めるよう依頼したのに、弁護士が約６年半にわたって提訴せず賠償金を受け取れなかったとして、大阪府の男性（３４）と親族が大阪弁護士会の男性弁護士（５０）と所属する弁護士法人（大阪市北区）に計約２億８千万円の損害賠償を求めた訴訟が、大阪地裁で和解した。弁護士側が解決金計１億６７５０万円を支払う内容。１０月２８日付。

［source：］提訴依頼、弁護士が６年放置し時効に　１・６億円で和解：朝日新聞デジタル https://www.asahi.com/articles/ASMCH4D17MCHPTIL00V.html
```

弁護士　時効　請求権 - Google 検索 https://t.co/mUpDkAs8S7

　たぶん次の記事になると思うのですが，2019年12月3日とあります。遠藤隆史という名前が一緒にありますが，記事の執筆者の名前のようです。朝日新聞のニュース記事で，こういう名前を見たのは記憶にないのですが，ふだんは気にせず，見落としていたのかもしれません。

```
医療過誤をめぐり損害賠償を求める訴訟を弁護士が時効の期限までに起こさなかったため、賠償請求ができなくなったとして、大阪府の４０代男性が大阪弁護士会の男性弁護士に計約２億５千万円を求める訴えを大阪地裁に起こした。２日にあった第１回口頭弁論で、弁護士側は請求の棄却を求めたが、詳細な認否は留保した。

［source：］「弁護士、時効までに訴訟せず」　２．５億円求め提訴：朝日新聞デジタル https://www.asahi.com/articles/ASMD23RZLMD2PTIL005.html
```

　この記事の内容はさすがに凄いです。前に読んだときより物凄いと思いました。まるで虚構新聞なのか目を疑うところ，体調いかんでは白日夢の幻をみているのかとまさに自分の目を疑いたくなる内容です。しかし，西天満とは記事にないので，前に読んだのは違った記事になるのかもしれません。

提訴依頼、弁護士が６年放置し時効に　１・６億円で和解：朝日新聞デジタル https://t.co/f0tNAP1993  \n 米田優人 2019年11月16日 6時00分

　先に見つけていた記事は，同じ2019年の11月16日でした。よりインパクトのある記事が12月3日なっていたので，思っていたより時期に開きがあります。3日ぐらいの間に立て続けて見ていたという感覚でした。執筆者と思われる名前も違った名前となっています。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 16:23／2019/11/28 00:54 URL： https://twitter.com/kk_hirono/status/1293448110400663552 https://twitter.com/hirono_hideki/status/1199718030936199168  

> 提訴依頼、弁護士が６年放置し時効に　１・６億円で和解：朝日新聞デジタル https://t.co/B46uJL37YO 米田優人 2019年11月16日06時00分　←　10日以上前の記事だったらしい。全く知らなかったし、知らないままだった可能性が大。  

　先に見つけていた記事は，同じ2019年の11月16日でした。よりインパクトのある記事が12月3日なっていたので，思っていたより時期に開きがあります。3日ぐらいの間に立て続けて見ていたという感覚でした。執筆者と思われる名前も違った名前となっています。

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「放置 時効」の検索結果 - Twilog https://t.co/iNiiKPvqLp

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「弁護士 放置」の検索結果 - Twilog https://t.co/EuiTVYnN95

　「「弁護士、時効までに訴訟せず」　２．５億円求め提訴」という見出しのニュース記事は，Twilogで見つかりませんでした。正直，納得がいかず，狐につままれた気分ですが，ほぼ記憶どおりのニュース記事が2件発見できて本当に良かったです。

```
アカウント名	ツイート数	リツイート数
岡ロ基ー（okaguchikii）	1	0
奉納＼さらば弁護士鉄道・泥棒神社の物語（hirono_hideki）	1	0


［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”弁護士が６年放置し時効”／データベース登録済みツイート：2019年11月28日00時55分の記録：ユーザ・投稿：2／2件 http://hirono2014sk.blogspot.com/2019/11/regexp20191128005522.html
```

　最近ツイートをみかけない岡口基一裁判官の転載アカウントだと思い，タイムラインを開いたのですが，先月7月の中頃から更新が止まっているようです。Facebookの投稿の転載自体をやっていない可能性はありますが，そのうち仙台で大きな動きがあるのかもしれません。

```
岡ロ基ー
@okaguchikii
こちら”岡ロ基ー”です。岡口基一判事のなりすまし。岡口判事のFB投稿をひたすらツイート（稀に，誤写，元投稿の補正，ツイートの削除等有り）。いいねとリツイートで岡口判事を応援しよう！岡口ロスの解消が目的ゆえに，ファンもアンチも大歓迎！岡口判事の許可無し。岡口判事へのDM伝達不可。完全なる手動更新。ツイートの大幅遅延有り。
amazon.co.jp/-/e/B004MHD36A…2018年9月からTwitterを利用しています
0 フォロー中
1.5万 フォロワー


［source：］(6) 岡ロ基ーさん (@okaguchikii) / Twitter https://twitter.com/okaguchikii
```

　上記にプロフィールを引用しましたが，「こちら”岡ロ基ー”です。岡口基一判事のなりすまし。岡口判事のFB投稿をひたすらツイート（稀に，誤写，元投稿の補正，ツイートの削除等有り）。いいねとリツイートで岡口判事を応援しよう！」とあります。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜okaguchikii（岡ロ基ー） 日時：2020-08-12 16:34／2020/07/16 23:55 URL： https://twitter.com/kk_hirono/status/1293450737616224256 https://twitter.com/okaguchikii/status/1283777320453455876  

> 問題が発生しました。やりなおしてください  このリクエストは、コンピュータによる自動的なものと判断されました。アカウントをスパムやその他の迷惑行為から保護するために、現在この操作は実行できません。しばらくしてからやりなおしてください。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜okaguchikii（岡ロ基ー） 日時：2020-08-12 16:34／2020/07/16 23:53 URL： https://twitter.com/kk_hirono/status/1293450755513319424 https://twitter.com/okaguchikii/status/1283776829799542785  

> この猿芝居を批判的に報じないマスコミを俺が批判していた件 ようやくマスコミも批判的に報じるようになりましたね（笑） https://t.co/x1Isjk99Vj https://t.co/4forvOlIy6  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜okaguchikii（岡ロ基ー） 日時：2020-08-12 16:34／2020/07/16 23:52 URL： https://twitter.com/kk_hirono/status/1293450770432405504 https://twitter.com/okaguchikii/status/1283776531030925312  

> 30代の男性裁判官が新型コロナウイルスに感染 最高裁事務総局に所属・東京都在住 https://t.co/6XfgGY7usY  

　直近の3つ目の「30代の男性裁判官が新型コロナウイルスに感染」というツイートの内容が見覚えのあるもので，同じタイムラインで見ていたように思うのですが，よく見ると直近の3つのツイートが全て7月16日になっていて，その日以来更新は止まっていたようです。

(1) 岡口 基一 | Facebook https://t.co/wYxWyaZ37k もしも願いが叶うなら、吐息を白いブリーフに変えて、逢えない日には部屋中に風間杜夫

　岡口基一裁判官のFacebookアカウントですが，4時間前，4時間前，7時間前，8時間前という投稿が並んでいました。今日は8月12日の水曜日で平日になりそうです。一昨日の10日は何も知らずに銀行に行き，シャッターが閉まっていたので驚きました。スマホで調べると山の日となっていました。

```
優子さんは、交通事故で相手に重傷を負わせたとして、自動車運転処罰法違反（過失傷害）の罪に問われたものの、「過失があったとは認められない」として無罪が確定。免許取消処分の理由がなくなったとして、免許を事故前の状態に戻すよう警察側に要請した。

ところが、警察側は「免許取消処分は変更しない」と回答。事故から3年以上経過しているが、いまだ事故前の状態に戻っていない。優子さんは免許取消処分の無効確認を求め、このほど福岡県を相手に行政訴訟を起こした。

［source：］事故のドライバー、無罪だったのに免許戻らず職失う…「行政の対応ひどい」弁護団がクラファン - 弁護士ドットコム https://www.bengo4.com/c_2/n_11580/
```

　やはり「警察側は「免許取消処分は変更しない」と回答。」とあるのですが，警察署が回答するはずもなく，公安委員会になりそうです。運転免許センターのことで公安委員会のことも知ってはいましたが，交通以外にも警察を監督するような立場と役割があると前に読んだ憶えがあります。

公安委員会 - Wikipedia https://t.co/Lq3cXFansI 公安委員会（こうあんいいんかい）とは、警察の民主的運営と政治的中立性を確保するため、警察を管理する行政委員会。

公安委員会 - Wikipedia https://t.co/Lq3cXFansI 運転免許証の発行主体[編集] \n 運転免許証は各都道府県公安委員会が交付するが、実際の業務は各都道府県警察交通部に委任されている。

公安委員会 - Wikipedia https://t.co/Lq3cXFansI 警察法第79条に基づいて、警察職員の職務執行について苦情がある場合は、各都道府県の公安委員会に対し、署名または捺印の上、文書により苦情の申出をすることができる

公安委員会 - Wikipedia https://t.co/Lq3cXFansI 職務執行において違法、不当な行為をしたり、なすべきことをしなかったことによって、何らかの不利益を受けたとして個別具体的にその是正を求める不服 \n 警察… https://t.co/ar3JRhXbUj

事故のドライバー、無罪だったのに免許戻らず職失う…「行政の対応ひどい」弁護団がクラファン - 弁護士ドットコム https://t.co/XVhOXhYyjN 世間の注目が裁判にどう影響するのかと思われるかもしれませんが、裁判所も世間の反応を見ていると思います。

事故のドライバー、無罪だったのに免許戻らず職失う…「行政の対応ひどい」弁護団がクラファン - 弁護士ドットコム https://t.co/XVhOXhYyjN たしかに、裁判所といえども、誰もが「おかしい」と考えていることを、「いや、それでいいんだ」とは簡単に言えないだろう。

事故のドライバー、無罪だったのに免許戻らず職失う…「行政の対応ひどい」弁護団がクラファン - 弁護士ドットコム https://t.co/XVhOXhYyjN ●弁護団は手弁当で活動、「本当にそれでいいのか？」

事故のドライバー、無罪だったのに免許戻らず職失う…「行政の対応ひどい」弁護団がクラファン - 弁護士ドットコム https://t.co/XVhOXhYyjN 本来であれば、訴訟でかかる費用は当事者が負担しますが、優子さんの行政訴… https://t.co/HEr5Sc3oyh

事故のドライバー、無罪だったのに免許戻らず職失う…「行政の対応ひどい」弁護団がクラファン - 弁護士ドットコム https://t.co/XVhOXhYyjN 今回の問題を契機に、まずは『無罪になれば免許取消し処分を自動的に見直す… https://t.co/wAekwyrWf6

事故のドライバー、無罪だったのに免許戻らず職失う…「行政の対応ひどい」弁護団がクラファン - 弁護士ドットコム https://t.co/XVhOXhYyjN 行政訴訟はこの目標への第一歩であり、社会的意義があります。だからこそ、… https://t.co/9fQTThrpmG

事故のドライバー、無罪だったのに免許戻らず職失う…「行政の対応ひどい」弁護団がクラファン - 弁護士ドットコム https://t.co/XVhOXhYyjN そこで考えたのが、クラウドファンディングの活用だ。きっかけは、日本で初… https://t.co/HEK3w6GY0V

　昨日の午前中も取り上げた憶えのある亀石倫子弁護士の名前が出てきました。亀石倫子弁護士とクラウドファンディングは，最初ぴんと来なかったのですが，クラウドファンディングの意義がそれほど強調されてはいなかったと思うものの，入れ墨の彫師の医療行為問題のことかと思います。

事故のドライバー、無罪だったのに免許戻らず職失う…「行政の対応ひどい」弁護団がクラファン - 弁護士ドットコム https://t.co/XVhOXhYyjN 亀石弁護士は、クラウドファンディングで費用を集めたいわゆる「タトゥー裁… https://t.co/W17eazNHVb

　一行下に事例紹介があるのに気が付きませんでした。同じ頃にはGPSの違法捜査の裁判があり，それが亀石倫子弁護士の大きな功績ともされていました。ただ被告人本人は，刑事裁判が長引いた他に利益がないようにも感じられたケースでした。減刑にはなっていないような感想でした。

事故のドライバー、無罪だったのに免許戻らず職失う…「行政の対応ひどい」弁護団がクラファン https://t.co/XVhOXhYyjN 自分たちの現状を良しとしてしまっては、「どれほど社会的意義のある訴訟でも、お金がないならやら… https://t.co/YwMzzt19tz

　この弁護士の手弁当というのは，いまでこそ見かける機会が少ないと思っていたのですが，最近になって増えつつある傾向を感じました。まだネットがいまほど普及していなかった20年以上前にも，冤罪に関する本でよく出てきたと思う手弁当です。弁護士以外では見ることがない気もします。

事故のドライバー、無罪だったのに免許戻らず職失う…「行政の対応ひどい」弁護団がクラファン - 弁護士ドットコム https://t.co/XVhOXhYyjN 「みなさんの力を少しずつでも分けてもらえれば、大きな力になり、それが社… https://t.co/XfNobYTGJ8

　行政処分としての運転免許取り消しには，刑事責任とはことなる目的や意味合いがあるように思われます。罰金と過料の違いというのも参考になりそうです。余り調べている時間もないですが，過料の場合は行政罰となっていたように思います。これは調べて確認します。

過料 - Google 検索 https://t.co/cMDDo7rFmw

過料と科料 https://t.co/PqilcrQV2f

　またGoogleの検索結果の，2番目に西野法律事務所の記事が出てきたのですが，さきほどのことはわからないものの，この記事のページタイトルには，「過料と科料」とあるだけで，西野法律事務所とはありません。

```
　次に、過料について説明します。
　「過料」は、大きく分けて「秩序罰としての過料」「執行罰としての過料」「懲戒罰としての過料」があります。

　「秩序罰としての過料」というのは、民事上の義務違反に対するもの、民事訴訟上の義務違反に対するもの、行政上の義務違反に対するもの、地方公共団体の条例・規則違反に対するものがあります。

［source：］過料と科料 https://www.nishino-law.com/publics/index/28/detail=1/b_id=54/r_id=78/
```

　上記の引用部分に，「「秩序罰としての過料」「執行罰としての過料」「懲戒罰としての過料」」とあり，行政罰はないですが，その先に「、行政上の義務違反に対するもの、地方公共団体の条例・規則違反に対するものがあります。」とあります。

```
行政処分とは
行政処分（免許取り消し、免許停止など）は、道路交通の安全確保を目的とした、公安委員会による行政法上の処分です。交通事故の内容や責任の重さに応じて運転免許に違反点数を加算するもので、点数が一定の基準に達すると、「免許取り消し」や「免許停止」などの処分を受けることになります。

［source：］人身事故の罰金・点数まとめ | もしも交通事故を起こしてしまったら？|【初心者必見】編集部が語る自動車購入ノウハウ【MOTA】 https://autoc-one.jp/knowhow/3425559/
```

　ずいぶん細かく詳しい説明があるようです。ページの下の方には統計の表のようなものも目立ちました。弁護士が書いているのかと気になったのですが，そうでもなさそうです。

　「行政処分（免許取り消し、免許停止など）は、道路交通の安全確保を目的とした、公安委員会による行政法上の処分です。」とあるので，思った以上に，刑事罰，刑事処分との線引きははっきりしていそうです。弁護士でなかったら弁護士に非弁ともされそうな情報源ではあります。

〈〈〈：Emacs： 2020-08-12（水曜日）17：38 　〈〈〈

* 「人質司法を実現し続けているのが現状。起訴前勾留での保釈があればどれだけ冤罪が防げたことか。」というモトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインでみたツイート
  :LOGBOOK:
  CLOCK: [2020-08-12 水 18:21]--[2020-08-12 水 18:55] =>  0:34
  :END:

:CATEGORIES: モトケンこと矢部善朗弁護士（京都弁護士会）,人質司法,櫻井光政弁護士,冤罪,大窪和久弁護士

〉〉〉：Emacs： 2020-08-12（水曜日）18：21　 〉〉〉

　モトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインで，モトケンこと矢部善朗弁護士（京都弁護士会）の返信ツイートとして表示をみた大窪和久弁護士のツイートになります。

　半月に1回ぐらい，法クラのタイムラインでリツイートを見かけるアカウントですが，そういえば，長いことタイムラインを開いていなかったと思い，開いてプロフィールをみたところ，櫻井光政弁護士が所長をする桜丘法律事務所の弁護士で，すっかり忘れていたことに気が付きました。

@motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@motoken_tw）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW motoken_tw（モトケン） 日時：2020/08/12 09:12 URL： https://twitter.com/motoken_tw/status/1293339422734184448  

> @okuboka ＞起訴前保釈  
>   
> 運用次第では虚偽自白を量産する恐れがあります。  
> 裁判官が客観証拠に基づく証拠隠滅の現実的可能性の有無程度を考慮してくれればいいのですが。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜okuboka（大窪和久） 日時：2020-08-12 18:25／2020/08/12 08:36 URL： https://twitter.com/kk_hirono/status/1293478752073027590 https://twitter.com/okuboka/status/1293330601810878465  

> 起訴前勾留は自白を「確保」する人質司法の核になるところなので、法務省は一貫して起訴前勾留での保釈制度の設置には反対しています。裁判所も逃亡や証拠隠しの「おそれ」があれば安易に身柄をとって人質司法を実現し続けているのが現状。起訴前勾留での保釈があればどれだけ冤罪が防げたことか。  

```
大窪和久
@okuboka
大窪和久／OKUBO Katsuhisa 渋谷にある桜丘法律事務所の弁護士（第二東京弁護士会所属）。インターネット関係及び刑事事件等取扱。二弁消費者問題対策委員会・公設事務所運営等支援委員会所属。元公設事務所所長（奄美・紋別）。 word派。 連絡はＳＮＳで受付 http：//facebook.com/okuboka
東京都渋谷区okubo-lawyer.jp2009年12月からTwitterを利用しています
940 フォロー中
3,014 フォロワー

［source：］(7) 大窪和久さん (@okuboka) / Twitter https://twitter.com/okuboka
```

　上記にTwitterアカウントのプロフィールを引用しました。ヘッダ画像の写真ですが，左右にある街路樹の間に細身の人物の銅像があります。誰の銅像なのかも気になったのですが，昔のマッシュルームカットの髪型に見えます。

　次が7月31日付で固定されたツイートになっています。

```
大窪和久
@okuboka
大窪和久／OKUBO Katsuhisa 渋谷にある桜丘法律事務所の弁護士（第二東京弁護士会所属）。インターネット関係及び刑事事件等取扱。二弁消費者問題対策委員会・公設事務所運営等支援委員会所属。元公設事務所所長（奄美・紋別）。 word派。 連絡はＳＮＳで受付 http：//facebook.com/okuboka
東京都渋谷区okubo-lawyer.jp2009年12月からTwitterを利用しています
940 フォロー中
3,014 フォロワー

［source：］(7) 大窪和久さん (@okuboka) / Twitter https://twitter.com/okuboka
```
▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜okuboka（大窪和久） 日時：2020-08-12 18:29／2020/07/31 12:03 URL： https://twitter.com/kk_hirono/status/1293479690573713414 https://twitter.com/okuboka/status/1289033970118619138  

> 東京ミネルヴァ法律事務所破産被害対策全国弁護団が立ち上がりました。明日よりホットラインも開設されます。詳細はURL先まで  https://t.co/D6TnmWQLaW  

　リンクにある東京ミネルヴァ法律事務所破産被害対策全国弁護団のホームページを数日ぶりに開いて確認したのですが，少なくとも全部で9名という弁護団の数に変わりはありませんでした。

　ずいぶん前から見かけているプロフィールの顔写真ですが，これはずっと変わっていないように思います。高橋雄一郎弁護士のアカウントと同じ頃に見かけるようになったとも思うのですが，高橋雄一郎弁護士のプロフィールの顔写真は，ずいぶん違ったものに変わっていました。

　プロフィールの顔写真をみるととても誠実で真面目そうな人柄にみえるだけに，そのツイートの内容も深く考えさせられるものがありました。今回も，「あればどれだけ冤罪が防げたことか」となっています。

　自分の体験以外は，二次的なマスコミなどの報道でしか，刑事事件，刑事裁判，冤罪とされる問題には触れる機会がなく，それこそ宇宙旅行の話を聞いているような，未知との遭遇が数多くあります。刑事弁護の第一線で職務をしれいればこその経験や知識もあるのでしょう。

　数は多くないと思うのですが，これまでのツイートの記録を見ておきたいと思います。冤罪と警察の関係を考える上でも，架け橋となるような資料だと思います。

　犯罪の影に女あり，というのは昔よくみかけた言葉です。時代も変わったのかたまたまなのか今は見かけませんが，冤罪の影に弁護士あり，という弁護士の暗躍，放置，無関心が冤罪発生のメカニズムに組み込まれているようにも思え，そうと判断される事例も増えつつあります。

　冤罪に取り組み正統派の弁護士には，迷惑な話かもしれません。

　思いの外数がありました。再捜査要請書＿警察庁・石川県警察御中（@kk_hirono）のツイートは，連投モードにはいりますが，これだけあると制限が掛かるリスクもあります。

```
(py37_env) a66@a66-XTe:~$ dp -p |grep okuboka
 - 2017年09月25日20時49分の登録： ＼大窪和久  @okuboka＼日本の法テラスに対し、契約弁護士はプロボノで仕事をさせられているのかとの質問。これに対し、マーケットよりは「若干低めの費用」 http://hirono2014sk.blogspot.com/2017/09/okuboka.html
 - 2017年10月04日20時59分の登録： ＼アリー　@defe647　RT：　@okuboka＼武井咲さんの結婚に日弁連がコメントを入れるか入れないかはもうどちらでも良いですが、継続してカネをかけることには http://hirono2014sk.blogspot.com/2017/10/defe647rtokuboka.html
 - 2017年10月04日21時05分の登録： ＼大窪和久　@okuboka＼締め出されたので仕方なくリベラルを売り物にしていると批判されて然るべき政党だと思います。 / 立憲民主、合流相次ぐ　50人以上の見方も （共 http://hirono2014sk.blogspot.com/2017/10/okuboka-50.html
 - 2017年10月11日21時30分の登録： ＼大窪和久　@okuboka　RT：　@bengo4topics＼（承前）本店以外の85事務所も対象に。計187人の弁護士に影響が及ぶようです。  http://hirono2014sk.blogspot.com/2017/10/okubokartbengo4topics85187.html
 - 2017年10月18日10時58分の登録： ＼大窪和久　@okuboka＼弁護士法人が破綻した場合、社員弁護士には無限責任を負わされることのほかに社員の出資金もゼロになるという二重のリスクがありますね http://hirono2014sk.blogspot.com/2017/10/okuboka.html
 - 2017年10月21日00時43分の登録： ＼大窪和久　@okuboka＼法テラス本部曰く法テラスは単価が若干安いだけでプロボノではないとのことなので、認識にギャップが http://hirono2014sk.blogspot.com/2017/10/okuboka_21.html
 - 2017年10月22日20時18分の登録： ＼大窪和久　@okuboka＼あそこは町長が法律事務所の設立を法テラスにお願いしたにも関わらず断りましたからね。あげく公設事務所の設置という形で http://hirono2014sk.blogspot.com/2017/10/okuboka_22.html
 - 2017年11月01日19時12分の登録： ＼大窪和久　@okuboka＼東弁にアディーレの後始末をする義務は本来無いので的外れな記事ですが、依頼者目線からはこう見えるのでしょう　アディーレ業務停止で東京弁護士会が http://hirono2014sk.blogspot.com/2017/11/okuboka.html
 - 2017年11月02日00時45分の登録： ＼大窪和久　@okuboka＼まだ中国に比べて優位点があるとすれば一応は基本的人権を守る憲法があるくらいだと思います。ただその憲法も骨抜きですし来年くらいには変わってしま http://hirono2014sk.blogspot.com/2017/11/okuboka_2.html
 - 2017年11月08日04時18分の登録： ＼大窪和久　@okuboka＼今の弁護士が一般的に鉄のメンタルを持っているとは全く思いませんが、過去は過酷な司法試験の試練にさらされていた結果メンタルが強い人しか残らなか http://hirono2014sk.blogspot.com/2017/11/okuboka_8.html
 - 2017年12月02日17時14分の登録： ＼大窪和久　@okuboka＼このことを警察官はおろか検察官でもよく分かっていない人がいるのが困る http://hirono2014sk.blogspot.com/2017/12/okuboka.html
 - 2017年12月05日11時39分の登録： ％@okuboka　大窪和久％地方だと犯罪の実名報道の弊害は本当に顕著で、不起訴の結果に終わらせた方でも新聞に名前が書かれたのでここでは村八分にされると言って他の地域に引 http://hirono2014sk.blogspot.com/2017/12/okuboka_5.html
 - 2017年12月14日13時10分の登録： ＼大窪和久　@okuboka＼懲戒権を国に与えることがどれだけ弁護士の活動にとって弊害があるかと考えると、やはり弁護士自治は守らねばならないと思う。価格決定権の一部を法務 http://hirono2014sk.blogspot.com/2017/12/okuboka_14.html
 - 2017年12月24日03時43分の登録： ＼大窪和久　@okuboka＼一番気になっているのは現在依頼者との間だけで負う守秘義務を事件関係者全員(無論相手方は当然含む)に及ばす点。 http://hirono2014sk.blogspot.com/2017/12/okuboka_24.html
 - 2017年12月26日21時17分の登録： ＼大窪和久　@okuboka＼刑事裁判の判決をどこまでインターネットで公開するかはプライバシーとの兼ね合いがありますが、裁判の公開の原則からすると広く認められてしかるべき http://hirono2014sk.blogspot.com/2017/12/okuboka_26.html
 - 2018年01月10日21時19分の登録： ＼大窪和久　@okuboka＼先日伊藤塾で行いました明日の法律家講座の講演内容をマガジン９にて記事にしていただきました。　弁護士過疎地域での業務と課題～自分の経験から皆さ http://hirono2014sk.blogspot.com/2018/01/okuboka.html
 - 2018年02月09日23時15分の登録： ％@okuboka　大窪和久％先日伊藤塾で行いました明日の法律家講座の講演内容をマガジン９にて記事にしていただきました。　弁護士過疎地域での業務と課題～自分の経験から皆さま方に伝えたいこと　講師：大窪和久氏 http://hirono2014sk.blogspot.com/2018/02/okuboka.html
 - 2018年02月09日23時20分の登録： ＼大窪和久　@okuboka＼\n\n会長選挙期間中どんどんＦＡＸが届くので、票を入れる気自体が無くなっています。受け手にコストをかけさせる通信方法をつかっている時点でどうか http://hirono2014sk.blogspot.com/2018/02/okuboka_9.html
 - 2018年02月15日07時00分の登録： ＼大窪和久　@okuboka＼\n\n年収330万円でインハウスを雇おうとしている会社が批判されてますが、少し前ならそれより安い金額で新人を雇用する法律事務所が普通にあったわ http://hirono2014sk.blogspot.com/2018/02/okuboka-330.html
 - 2018年02月17日20時39分の登録： ＼大窪和久　@okuboka＼親族事件関係以外は驚くほどのスピードで地方の支部の民事事件減ってますしね。東京はまだ若い人が流入しており景気も上がっているので東京にずっとい http://hirono2014sk.blogspot.com/2018/02/okuboka_17.html
 - 2018年02月18日20時20分の登録： ＼大窪和久　@okuboka＼法的手続のハードルの高さが結果このようなサイトの存在を許しているわけですね。根が深い問題 海賊版サイトは「漫画の万引」　単行本売り上げ、落ち http://hirono2014sk.blogspot.com/2018/02/okuboka_18.html
 - 2018年02月19日18時21分の登録： ＼大窪和久　@okuboka＼ここに書いてあることは職人たる弁護士にも全て当てはまりますね。特に「誰に評価されなくとも、きちんとした仕事をすること」は本当に大事。この漫画 http://hirono2014sk.blogspot.com/2018/02/okuboka_19.html
 - 2018年03月11日17時30分の登録： ＼大窪和久　@okuboka＼いまや役人は嘘つかないと思ってるのは裁判官くらいでは http://hirono2014sk.blogspot.com/2018/03/okuboka.html
 - 2018年03月12日21時50分の登録： ＼大窪和久　@okuboka＼検察庁でも公文書書き換えは日常茶判事だったのでしょうか。そう言えば証拠については大阪地検特捜部が改ざんしていましたね。 若狭勝氏、官僚の文書 http://hirono2014sk.blogspot.com/2018/03/okuboka_12.html
 - 2018年04月16日01時01分の登録： ＼大窪和久　@okuboka＼ロクでもないことばかりやったあげく、この期に及んで消費税率まで上げようとする安倍首相の葬儀には誰も行かないんじゃないかって近所のコンビニの店 http://hirono2014sk.blogspot.com/2018/04/okuboka.html
 - 2018年04月24日10時46分の登録： ＃大窪和久　@okuboka＃のツイート／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年04月24日10時46分 http://hirono2014sk.blogspot.com/2018/04/okuboka201804241046.html
 - 2018年04月25日09時35分の登録： ＃大窪和久　@okuboka＃のツイート／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年04月25日09時35分 http://hirono2014sk.blogspot.com/2018/04/okuboka201804250935.html
 - 2018年05月08日23時44分の登録： ＃大窪和久　@okuboka＃のツイート／2018-04-11_0916〜2018-05-08_2039／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年05月08日23時44分 http://hirono2014sk.blogspot.com/2018/05/okuboka2018-04-1109162018-05.html
 - 2018年05月12日23時08分の登録： ＃大窪和久　@okuboka＃のツイート／2018-04-14_1051〜2018-05-12_2249／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年05月12日23時08分 http://hirono2014sk.blogspot.com/2018/05/okuboka2018-04-1410512018-05.html
 - 2018年05月29日21時50分の登録： ＃大窪和久　@okuboka＃のツイート／2018-05-12_1742〜2018-05-29_1218／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年05月29日21時50分 http://hirono2014sk.blogspot.com/2018/05/okuboka2018-05-1217422018-05.html
 - 2018年06月10日01時50分の登録： ＼大窪和久　@okuboka＼第三者委員会メンツ丸潰れ 葛飾・中３自殺：区長「いじめに該当」　第三者委報告覆す - 毎日新聞 http://hirono2014sk.blogspot.com/2018/06/okuboka.html
 - 2018年06月10日01時50分の登録： ＃大窪和久　@okuboka＃のツイート／2018-05-23_0825〜2018-06-09_1129／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年06月10日01時50分 http://hirono2014sk.blogspot.com/2018/06/okuboka2018-05-2308252018-06.html
 - 2018年07月04日20時50分の登録： ＼大窪和久　@okuboka＼弁護士のストレスフルな環境に耐えられず他業種に移って成功している人の話などを聞く。確かにこの仕事ストレス強度が高くないと続けていけないので、 http://hirono2014sk.blogspot.com/2018/07/okuboka.html
 - 2018年07月04日20時50分の登録： ＃大窪和久　@okuboka＃のツイート／2018-06-13_1250〜2018-07-04_1806／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年07月04日20時50分 http://hirono2014sk.blogspot.com/2018/07/okuboka2018-06-1312502018-07.html
 - 2018年07月13日16時14分の登録： ＼大窪和久　@okuboka＼弁護士は逮捕された「犯罪者」の味方をする悪党ではないかという話は地方時代いろいろな形で言われましたね…。 http://hirono2014sk.blogspot.com/2018/07/okuboka_13.html
 - 2018年07月13日16時14分の登録： ＃大窪和久　@okuboka＃のツイート／2018-06-26_1838〜2018-07-13_1422／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年07月13日16時14分 http://hirono2014sk.blogspot.com/2018/07/okuboka2018-06-2618382018-07.html
 - 2018年09月18日20時20分の登録： ＼大窪和久　@okuboka＼ネットの発達により結果不起訴でも逮捕されたというだけで拡散されてしまい、事実上の制裁を受けることは明らかにおかしい。逮捕段階で実名報道をする http://hirono2014sk.blogspot.com/2018/09/okuboka.html
 - 2018年09月18日20時20分の登録： ＃大窪和久　@okuboka＃のツイート／2018-08-31_1118〜2018-09-18_1959／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年09月18日20時20分 http://hirono2014sk.blogspot.com/2018/09/okuboka2018-08-3111182018-09.html
 - 2018年10月16日12時02分の登録： ＼大窪和久　@okuboka＼素人さんで請求に応じなければ職場等に連絡するという内容の通知書を送ってしまう例はありがちですが、弁護士が代理人としてそれをやるのは明らかにＮ http://hirono2014sk.blogspot.com/2018/10/okuboka.html
 - 2018年10月16日12時02分の登録： ＃大窪和久　@okuboka＃のツイート／2018-09-17_0244〜2018-10-16_1156／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年10月16日12時02分 http://hirono2014sk.blogspot.com/2018/10/okuboka2018-09-1702442018-10.html
 - 2018年10月16日23時45分の登録： ＼大窪和久　@okuboka＼検察が刑事訴訟の反対当事者である弁護人を潰すために捜査する危険は潜在的にあるとも思いますので http://hirono2014sk.blogspot.com/2018/10/okuboka_16.html
 - 2018年10月16日23時45分の登録： ＃大窪和久　@okuboka＃のツイート／2018-09-17_2208〜2018-10-16_1852／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年10月16日23時45分 http://hirono2014sk.blogspot.com/2018/10/okuboka2018-09-1722082018-10.html
 - 2018年11月01日16時00分の登録： ＼大窪和久　@okuboka＼同じ案件で各種無料相談を繰り返し利用されている方にこのような方は多いですね。。 http://hirono2014sk.blogspot.com/2018/11/okuboka.html
 - 2018年11月01日16時00分の登録： ＃大窪和久　@okuboka＃のツイート／2018-10-11_1745〜2018-11-01_1537／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年11月01日16時00分 http://hirono2014sk.blogspot.com/2018/11/okuboka2018-10-1117452018-11.html
 - 2018年11月02日06時09分の登録： ＼大窪和久　@okuboka＼同じ案件で各種無料相談を繰り返し利用されている方にこのような方は多いですね。。 http://hirono2014sk.blogspot.com/2018/11/okuboka_2.html
 - 2018年11月02日06時09分の登録： ＃大窪和久　@okuboka＃のツイート／2018-10-11_2200〜2018-11-01_2103／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年11月02日06時09分 http://hirono2014sk.blogspot.com/2018/11/okuboka2018-10-1122002018-11.html
 - 2018年12月01日12時55分の登録： ＼大窪和久　@okuboka＼罪名にもよりますけど、今年もウチの事務所の弁護士が受けた刑事事件の多くが勾留請求却下となってますね。私が受けた事件でも身元引受人がいないもの http://hirono2014sk.blogspot.com/2018/12/okuboka.html
 - 2018年12月01日12時56分の登録： ＃大窪和久　@okuboka＃のツイート／2018-11-06_0717〜2018-12-01_1121／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月01日12時56分 http://hirono2014sk.blogspot.com/2018/12/okuboka2018-11-0607172018-12.html
 - 2018年12月23日15時01分の登録： ＃大窪和久　@okuboka＃のツイート／2018-11-28_1330〜2018-12-22_1319／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月23日15時01分 http://hirono2014sk.blogspot.com/2018/12/okuboka2018-11-2813302018-12.html
 - 2018年12月24日12時37分の登録： ＃大窪和久　@okuboka＃のツイート／2018-11-28_1331〜2018-12-23_1625／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月24日12時37分 http://hirono2014sk.blogspot.com/2018/12/okuboka2018-11-2813312018-12.html
 - 2018年12月25日20時38分の登録： ＃大窪和久　@okuboka＃のツイート／2018-11-30_2217〜2018-12-25_1847／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月25日20時38分 http://hirono2014sk.blogspot.com/2018/12/okuboka2018-11-3022172018-12.html
 - 2018年12月26日19時45分の登録： ＃大窪和久　@okuboka＃のツイート／2018-12-03_0952〜2018-12-26_1501／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月26日19時45分 http://hirono2014sk.blogspot.com/2018/12/okuboka2018-12-0309522018-12.html
 - 2018年12月29日20時35分の登録： ＃大窪和久　@okuboka＃のツイート／2018-12-05_1451〜2018-12-29_1155／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月29日20時35分 http://hirono2014sk.blogspot.com/2018/12/okuboka2018-12-0514512018-12.html
 - 2018年12月30日20時52分の登録： ＃大窪和久　@okuboka＃のツイート／2018-12-06_0830〜2018-12-30_1701／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月30日20時52分 http://hirono2014sk.blogspot.com/2018/12/okuboka2018-12-0608302018-12.html
 - 2019年01月03日02時42分の登録： ＼大窪和久　@okuboka＼裏金を使ってでも入りたいという人が今でもいる医学部と、定員割れでそっぽを向かれている法科大学院を比べてしまうと、当業界の斜陽ぶりを実感せざる http://hirono2014sk.blogspot.com/2019/01/okuboka.html
 - 2019年01月03日02時42分の登録： ＃大窪和久　@okuboka＃のツイート／2018-12-10_1048〜2019-01-02_2049／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年01月03日02時42分 http://hirono2014sk.blogspot.com/2019/01/okuboka2018-12-1010482019-01.html
 - 2019年01月05日00時20分の登録： ＃大窪和久　@okuboka＃のツイート／2018-12-11_1220〜2019-01-04_1451／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年01月05日00時20分 http://hirono2014sk.blogspot.com/2019/01/okuboka2018-12-1112202019-01.html
 - 2019年01月06日19時27分の登録： ＃大窪和久　@okuboka＃のツイート／2018-12-13_1313〜2019-01-06_1554／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年01月06日19時27分 http://hirono2014sk.blogspot.com/2019/01/okuboka2018-12-1313132019-01.html
 - 2019年01月07日00時38分の登録： ＃大窪和久　@okuboka＃のツイート／2018-12-13_1313〜2019-01-06_1554／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年01月07日00時38分 http://hirono2014sk.blogspot.com/2019/01/okuboka2018-12-1313132019-01_7.html
 - 2019年01月10日16時28分の登録： ＃大窪和久　@okuboka＃のツイート／2018-12-20_1046〜2019-01-10_1558／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年01月10日16時28分 http://hirono2014sk.blogspot.com/2019/01/okuboka2018-12-2010462019-01.html
 - 2019年01月11日23時56分の登録： ＃大窪和久　@okuboka＃のツイート／2018-12-21_0835〜2019-01-11_1946／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年01月11日23時56分 http://hirono2014sk.blogspot.com/2019/01/okuboka2018-12-2108352019-01.html
 - 2019年01月16日22時21分の登録： ＃大窪和久　@okuboka＃のツイート／2018-12-26_1501〜2019-01-16_1953／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年01月16日22時21分 http://hirono2014sk.blogspot.com/2019/01/okuboka2018-12-2615012019-01.html
 - 2019年01月30日02時29分の登録： ＃大窪和久　@okuboka＃のツイート／2019-01-08_1914〜2019-01-29_1629／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年01月30日02時29分 http://hirono2014sk.blogspot.com/2019/01/okuboka2019-01-0819142019-01.html
 - 2019年02月02日02時15分の登録： ＃大窪和久　@okuboka＃のツイート／2019-01-11_1630〜2019-02-01_2106／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月02日02時15分 http://hirono2014sk.blogspot.com/2019/02/okuboka2019-01-1116302019-02.html
 - 2019年02月02日02時15分の登録： ＼大窪和久　@okuboka＼https://twitter.com/mansakukanada/status/1091243310818050048 http://hirono2014sk.blogspot.com/2019/02/okubokahttpstwittercommansakukanadastat.html
 - 2019年02月02日02時27分の登録： ＼大窪和久　@okuboka＼犯罪容疑がかかった場合の「酔って覚えてない」主張については思うことはあるもののツイッターでは書かないようにしよう(事件の接見時相談時には当然 http://hirono2014sk.blogspot.com/2019/02/okuboka.html
 - 2019年02月02日02時35分の登録： ＼大窪和久　@okuboka＼イチケイのカラス、裁判員事件の評議で部長が冤罪をつくることは無辜の処罰だけでなく真犯人を取り逃がすという意味でもあると話されていて、なるほど http://hirono2014sk.blogspot.com/2019/02/okuboka_2.html
 - 2019年02月06日10時15分の登録： ＼大窪和久　@okuboka＼悪寒しかしないね・・・ それなら対立候補に挙がった北海道局長の方が得がたい人材だった。。。 http://hirono2014sk.blogspot.com/2019/02/okuboka_6.html
 - 2019年02月06日10時15分の登録： ＃大窪和久　@okuboka＃のツイート／2019-01-15_1156〜2019-02-06_0951／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月06日10時15分 http://hirono2014sk.blogspot.com/2019/02/okuboka2019-01-1511562019-02.html
 - 2019年02月06日10時16分の登録： ＼大窪和久　@okuboka＼公務員の人件費減らして人材が流出した夕張と同じ政策をするつもりなのか… 北海道知事選、出馬表明の鈴木氏「給与30％削減」 - 毎日新聞 http://hirono2014sk.blogspot.com/2019/02/okuboka-30.html
 - 2019年02月20日17時42分の登録： ＃大窪和久　@okuboka＃のツイート／2019-01-24_1712〜2019-02-20_1501／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月20日17時42分 http://hirono2014sk.blogspot.com/2019/02/okuboka2019-01-2417122019-02.html
 - 2019年02月20日17時43分の登録： ＼大窪和久　@okuboka＼弁護士事務所の生産性をみるみる奪っているのは電話なのですが、少なくとも街弁では無くすことは不可能だろうな。それでも少しでも電話依存を減らさな http://hirono2014sk.blogspot.com/2019/02/okuboka_20.html
 - 2019年02月21日20時00分の登録： ＃大窪和久　@okuboka＃のツイート／2019-01-28_0842〜2019-02-21_1835／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月21日20時00分 http://hirono2014sk.blogspot.com/2019/02/okuboka2019-01-2808422019-02.html
 - 2019年02月21日20時00分の登録： ＼大窪和久　@okuboka＼鑑定資料を残さない手法は、弁護側の鑑定可能性を潰しておく最も効果的な方法なので、裁判所がそれでも鑑定の信用性を認めてくれるならば捜査側も鑑定 http://hirono2014sk.blogspot.com/2019/02/okuboka_21.html
 - 2019年03月04日23時29分の登録： ＼大窪和久　@okuboka＼無限責任を負わせたり、新人から出資金をガメたりと経営者視点からはやれることは多い(非推奨w)大窪和久さんが追加\n http://hirono2014sk.blogspot.com/2019/03/okubokaw.html
 - 2019年03月07日03時17分の登録： ＼大窪和久　@okuboka＼今週になって2件保釈請求が通る(うち一件は公判前)。報道されている件とは保釈金の金額をみても圧倒的に違いますが一人の人の身柄を解放させる点で http://hirono2014sk.blogspot.com/2019/03/okuboka2.html
 - 2019年03月08日04時10分の登録： ＼大窪和久　@okuboka＼イチケイのカラス最終回、SNSで書いたことは刑事裁判が終わっても付いて回るのだろうなぁ…と。\nこれで終わってしまうのは残念 http://hirono2014sk.blogspot.com/2019/03/okubokasns.html
 - 2019年03月28日18時17分の登録： ＼大窪和久　@okuboka＼旭川の無令状GPS捜査の事件、有罪だったもののGPS捜査の証拠排除はした様子。それでいてどういう理屈で有罪になったのか興味はあるので判決は確 http://hirono2014sk.blogspot.com/2019/03/okubokagpsgps.html
 - 2019年03月29日14時14分の登録： ＼大窪和久　@okuboka＼無罪判決に対するネット上の炎上をみるに、有罪であっても無罪であっても刑事事件の実名報道（加害者被害者共に）はするべきではないなとの思いを強く http://hirono2014sk.blogspot.com/2019/03/okuboka.html
 - 2019年04月05日01時23分の登録： ＼大窪和久　@okuboka＼裁判資料の押収にまで裁判所が令状を出したという知らせに言葉を失う。弁護権の侵害でしょう http://hirono2014sk.blogspot.com/2019/04/okuboka.html
 - 2019年04月06日00時43分の登録： ＼大窪和久　@okuboka＼以前ロシアの法律事務所に訪問した時に、捜査機関が法律事務所を捜索差押して裁判記録を持っていくことが珍しく無い為紙の記録を事務所に置かないとい http://hirono2014sk.blogspot.com/2019/04/okuboka_6.html
 - 2019年04月13日00時21分の登録： ＼大窪和久　@okuboka＼それ以外の活動はともかくとして国選刑事弁護に関してはなんで悪い人間の見方をするのだと言われることは数知れず。一番理解を得ることが難しい分野な http://hirono2014sk.blogspot.com/2019/04/okuboka_13.html
 - 2019年04月13日20時17分の登録： ＼大窪和久　@okuboka＼今後性犯罪の国選弁護人についた弁護士についてはSNSで情報を晒された後(傍聴に行けば弁護士が誰かは容易に特定できる)、懲戒請求を多数受けるな http://hirono2014sk.blogspot.com/2019/04/okubokasns.html
 - 2019年04月13日22時29分の登録： ＼小倉秀夫　@Hideo_Ogura＼被害者と同じくらいの年齢のお嬢様をお持ちの場合、同じ目に遭わせるぞと脅迫されることになるでしょうね。RT @okuboka: 今後性 http://hirono2014sk.blogspot.com/2019/04/hideoogurart-okuboka.html
 - 2019年04月18日04時34分の登録： ＼大窪和久　@okuboka＼離婚事件をしているとこの結婚のおかげで両当事者の寿命が下がっただろうなというケースに良くあたるので、結婚すれば寿命が長くなるという言説につい http://hirono2014sk.blogspot.com/2019/04/okuboka_18.html
 - 2019年04月19日13時17分の登録： ＼大窪和久　@okuboka＼刑事弁護人がツイッターの場であっても無罪推定原則を口にするのを躊躇うようになるようではもう刑事弁護の現場を離れた方がいいでしょうね http://hirono2014sk.blogspot.com/2019/04/okuboka_19.html
 - 2019年04月19日23時53分の登録： ＼大窪和久　@okuboka＼刑事弁護人がツイッターの場であっても無罪推定原則を口にするのを躊躇うようになるようではもう刑事弁護の現場を離れた方がいいでしょうね http://hirono2014sk.blogspot.com/2019/04/okuboka_25.html
 - 2019年05月06日19時56分の登録： ＼大窪和久　@okuboka＼＼弁護士 吉峯耕平（「カンママル」撲滅委員会）　@kyoshimine＼相談件数と受任件数が見込まれないと法テラスが切り捨てた場所については http://hirono2014sk.blogspot.com/2019/05/okuboka-kyoshimine.html
 - 2019年05月06日23時45分の登録： ＼大窪和久　@okuboka＼相談件数と受任件数が見込まれないと法テラスが切り捨てた場所については弁護士が身銭を切って事務所を作らない限り切り捨てられたままになります。\n http://hirono2014sk.blogspot.com/2019/05/okuboka.html
 - 2019年05月10日00時22分の登録： ＼大窪和久　@okuboka＼岡崎の性犯罪無罪判決読みました。控訴されている事件なので最終的な結果は分かりませんが、もっと早く裁判例としてウエストロー等に掲載されていれば http://hirono2014sk.blogspot.com/2019/05/okuboka_10.html
 - 2019年05月10日00時29分の登録： ＼大窪和久　@okuboka＼少なくとも判断の資料として入れられないと裁判官に判断されるような供述調書を作成してしまった捜査側にはかなり問題があると私は思います。 http://hirono2014sk.blogspot.com/2019/05/okuboka_86.html
 - 2019年05月21日00時07分の登録： ％@okuboka　大窪和久％性行為が原則違法であり同意を得て初めて適法化する、同意が得られたと誤信して行為に及んだ場合でも処罰しうるようにするという考え方から現行法を改 http://hirono2014sk.blogspot.com/2019/05/okuboka_21.html
 - 2019年06月05日16時14分の登録： REGEXP：”@okuboka”／データベース登録済みツイート：2019年06月05日16時11分の記録：ユーザ・投稿：87／228件 http://hirono2014sk.blogspot.com/2019/06/regexpokuboka20190605161187228.html
 - 2019年06月10日01時29分の登録： ＼大窪和久　@okuboka＼着手金タダでという方と信頼関係結ぶのは難しいのでそのような方は受けないことにしています http://hirono2014sk.blogspot.com/2019/06/okuboka.html
 - 2019年06月22日03時53分の登録： ＃大窪和久　@okuboka＃のツイート／2019-05-28_0910〜2019-06-21_1155／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年06月22日03時53分 http://hirono2014sk.blogspot.com/2019/06/okuboka2019-05-2809102019-06.html
 - 2019年06月27日00時01分の登録： ＼大窪和久　@okuboka＼いわぽんさんがリツイート＞　大窪和久（@okuboka）：　イチケイのカラス４巻に、「刑事弁護人と無力感はセットだからな」「弁護士は無力感 http://hirono2014sk.blogspot.com/2019/06/okubokaokuboka.html
 - 2019年07月01日08時33分の登録： ＼大窪和久　@okuboka＼っていて一番辛かったのは弁護士会でも被告人被疑者でも被害者でもなく、「犯罪者の味方やって金をもらえるんだから弁護士はいい商売ですよね」という http://hirono2014sk.blogspot.com/2019/07/okuboka.html
 - 2019年07月15日23時19分の登録： ＃大窪和久　@okuboka＃のツイート／2019-06-20_1914〜2019-07-15_1433／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年07月15日23時19分 http://hirono2014sk.blogspot.com/2019/07/okuboka2019-06-2019142019-07.html
 - 2019年07月20日01時15分の登録： ＼大窪和久　@okuboka＼国選弁護の費用なんて一般人はおろか検察官にすら安いとは思われていないのだから、安いと言われて納得するのは刑事やってる同業者くらいしかいないと http://hirono2014sk.blogspot.com/2019/07/okuboka_20.html
 - 2019年07月20日01時15分の登録： ＼大窪和久　@okuboka＼この金額でも多すぎる、そもそも金を貰って犯罪者の弁護をすること自体誤りという反応が多数になるのでは…\n引用ツイート\n http://hirono2014sk.blogspot.com/2019/07/okuboka_92.html
 - 2019年07月24日13時22分の登録： ＼大窪和久　@okuboka＼民事司法IT化で主に地方会から「ITの使えない「弁護士」を切り捨てるのか」という反対意見が上がってきており、日弁連が最大の抵抗勢力になってる http://hirono2014sk.blogspot.com/2019/07/okubokaitit.html
 - 2019年07月24日13時22分の登録： ＼弁護士 遠藤温子　@Atsuko_law＼返信先: \n@okuboka\n さん、 \n@popohito\nさん\n使うことを学ぼうとすらしない弁護士は切り捨てて父のでは？ http://hirono2014sk.blogspot.com/2019/07/atsukolaw-okuboka-popohito.html
 - 2019年07月28日17時53分の登録： ＼大窪和久　@okuboka＼死にたい人は周りに迷惑をかけずに死ねというメッセージが広まることで、既に追い込まれている人に最後の一押しをすることは多いでしょう。 http://hirono2014sk.blogspot.com/2019/07/okuboka_28.html
 - 2019年08月01日20時14分の登録： ＃大窪和久　@okuboka＃のツイート／2019-07-08_1301〜2019-08-01_1724／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年08月01日20時14分 http://hirono2014sk.blogspot.com/2019/08/okuboka2019-07-0813012019-08.html
 - 2019年08月01日20時29分の登録： https://twitter.com/okuboka/with_replies http://hirono2014sk.blogspot.com/2019/08/httpstwittercomokubokawithreplies.html
 - 2019年08月13日03時01分の登録： ＃大窪和久　@okuboka＃のツイート／2019-07-21_1341〜2019-08-12_2138／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年08月13日03時01分 http://hirono2014sk.blogspot.com/2019/08/okuboka2019-07-2113412019-08.html
 - 2019年08月13日03時03分の登録： ＼大窪和久　@okuboka＼民事判決データベース、テキストベースで全判決が出てくるようになれば判例分析も飛躍的に向上できるので是非実現してもらいたい http://hirono2014sk.blogspot.com/2019/08/okuboka.html
 - 2019年10月12日00時26分の登録： ＼大窪和久　@okuboka＼早い時期に運休を決められるようになったのは大きな進歩だと思います。今後も台風等災害の際には早い時期の告知をお願いしたい / 首都圏JR、12 http://hirono2014sk.blogspot.com/2019/10/okuboka-jr12.html
 - 2019年10月16日13時27分の登録： ＼大窪和久　@okuboka＼50歳の弁護士に対する法クラの辛辣な意見を読んでわが身を鑑みる44歳の秋 http://hirono2014sk.blogspot.com/2019/10/okuboka5044.html
 - 2019年11月02日20時33分の登録： ＼大窪和久　@okuboka＼もう過疎地の公営病院ですら統廃合が進められている中で、自治体が新たにそれより優先度の低いインフラにお金を出すのはますます難しくなってますよね http://hirono2014sk.blogspot.com/2019/11/okuboka.html
 - 2019年11月07日00時07分の登録： ＼大窪和久　@okuboka＼深澤諭史さんがリツイート大窪和久@okuboka·2h覚醒剤の情状弁護については神山ゼミでもよく取り上げられますが、毎度立ち直りの為の社会資 http://hirono2014sk.blogspot.com/2019/11/okubokaokuboka2h.html
 - 2019年11月09日00時07分の登録： ＼大窪和久　@okuboka＼覚醒剤の情状弁護については神山ゼミでもよく取り上げられますが、毎度立ち直りの為の社会資源が乏しい(地方だと尚更ない)で行き詰っています。\n事 http://hirono2014sk.blogspot.com/2019/11/okuboka_9.html
 - 2019年11月27日22時56分の登録： ＼大窪和久　@okuboka＼やっていないけど保釈されたいので認めるというケースは暗数では非常に多いと思います。それだけ否認をしていると裁判所は保釈を認めないということ。 http://hirono2014sk.blogspot.com/2019/11/okuboka_27.html
 - 2019年11月27日23時00分の登録： ＼奉納＼さらば弁護士鉄道・泥棒神社の物語　@hirono_hideki＼返信先: \n@okuboka\nさん\n単純に、刑事事件、刑事裁判における弁護士報酬禁止法を制定すれば http://hirono2014sk.blogspot.com/2019/11/hironohideki-okuboka.html
 - 2019年11月27日23時10分の登録： ＼大窪和久　@okuboka＼地方の弁護士が裁判官や他の弁護士と談合しているということは全くありませんが、裁判官や弁護士の考え方や視点などについては予測可能性がある程度立 http://hirono2014sk.blogspot.com/2019/11/okuboka_10.html
 - 2019年12月18日21時23分の登録： ＼大窪和久　@okuboka＼事件毎にプロジェクトをつくり、事件終了までに想定されるタスクを全部仮に入れて、具体化したものについて期限を設定して整理してます。準備書面の起 http://hirono2014sk.blogspot.com/2019/12/okuboka.html
 - 2019年12月22日08時20分の登録： ＼大窪和久　@okuboka＼司法のIT化の足を引っ張らないこと(議論を先導することまでは期待してません)  \n  #これからの日弁連に期待すること http://hirono2014sk.blogspot.com/2019/12/okubokait-n.html
 - 2020年01月08日22時52分の登録： ＼大窪和久　@okuboka＼大窪和久\n@okuboka\n·\n8時間\n特捜が無意味な捜査や令状請求をするのも、裁判所が令状の自動販売機になっているのも刑事弁護に関わる弁護 http://hirono2014sk.blogspot.com/2020/01/okuboka-okuboka-8.html
 - 2020年01月13日03時11分の登録： ＼大窪和久　@okuboka＼70日間も黙秘権行使している人に弁護士の立ち合いすら認めずに平均四時間も取調しているのは普通に拷問ですが、当然そんな問題意識は検察にはカケラ http://hirono2014sk.blogspot.com/2020/01/okuboka70.html
 - 2020年01月19日04時39分の登録： ＼大窪和久　@okuboka＼国費の無駄遣いという点で言うと、黙秘権を行使している被疑者を拘束して数十日間も1日当たり数時間も検察官に取り調べさせていることは莫大な国費の http://hirono2014sk.blogspot.com/2020/01/okuboka1.html
 - 2020年01月22日00時29分の登録： ＼大窪和久　@okuboka＼「弁護人が立ち会うことを認めた場合，被疑者から十分な供述が得られなくなることで，事案の真相が解明されなくなる 」と自白を取るのに弁護人が邪魔 http://hirono2014sk.blogspot.com/2020/01/okuboka.html
 - 2020年01月22日14時45分の登録： ＼大窪和久　@okuboka＼自白を取るのに弁護人が邪魔だという国家権力のホンネを全世界にアピールしている法務省 http://hirono2014sk.blogspot.com/2020/01/okuboka_22.html
 - 2020年01月30日12時05分の登録： ＼大窪和久　@okuboka＼その為検察の嫌がらせとしか思われない捜査活動も野放しになっています。\n\n弘中弁護士「鍵ぶっ壊して…」事務所捜索を  http://hirono2014sk.blogspot.com/2020/01/okuboka_30.html
 - 2020年03月03日19時26分の登録： ＼大窪和久　@okuboka＼必ずそのように考えていらっしゃると思います http://hirono2014sk.blogspot.com/2020/03/okuboka.html
 - 2020年03月11日02時17分の登録： ＼大窪和久　@okuboka＼検察庁から、刑事記録のデータについてネットワークに繋がっているＰＣ、スマートフォンには一切入れるなと言う申し入れが弁護士会にあったという情報 http://hirono2014sk.blogspot.com/2020/03/okuboka_11.html
 - 2020年03月11日02時19分の登録： ＼荒木　樹　@Tacky1971＼返信先: \n@okuboka\nさん, \n@yiwapon\nさん\nコピー料金が高いし、カラーがないので、タブレットで撮影してますが。\n\n今 http://hirono2014sk.blogspot.com/2020/03/tacky1971-okuboka-yiwapon.html
 - 2020年03月11日22時27分の登録： ＼大窪和久　@okuboka＼ソフトバンクで社会貢献したいなら、むしろ期間限定で通信費を安くしたりした方が喜ぶ人は多かろうと思う http://hirono2014sk.blogspot.com/2020/03/okuboka_28.html
 - 2020年04月18日11時39分の登録： ＼大窪和久　@okuboka＼三密でないなら問題ないと総理がいうのなら安心ですね。緊急事態宣言終わったら旅行に行ってガンガン経済を回せます\n\n首相 妻の大分旅行は問題ない http://hirono2014sk.blogspot.com/2020/04/okuboka.html
 - 2020年04月29日21時21分の登録： ＼大窪和久　@okuboka＼多重債務の相談が増えてきた感じがします。事業者の場合、管財費用の確保等本当に資金が尽きてからですと破産すらままならないことが多いので、あらか http://hirono2014sk.blogspot.com/2020/04/okuboka_29.html
 - 2020年05月17日20時24分の登録： ＼大窪和久　@okuboka＼自治がなくなった際の懲戒関係等は法務省がやることになると思いますが、その場合法テラスのように日増しに懲戒関係も悪化するのではないかと懸念して http://hirono2014sk.blogspot.com/2020/05/okuboka.html
 - 2020年06月15日21時49分の登録： ＃大窪和久　@okuboka＃のツイート／2020-05-10_0913〜2020-06-15_2029／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2020年06月15日21時48分 http://hirono2014sk.blogspot.com/2020/06/okuboka2020-05-1009132020-06.html
```

　大丈夫そうです，編集中のテキストファイルで，392行目から522行目になっています。130件ということになりそうです。TwitterAPIでの投稿に失敗したツイートもあるかもしれません。あまりに数が多いので，自分の記憶がどしたのかと思ったのですが，6月15日で止まっていました。

〈〈〈：Emacs： 2020-08-12（水曜日）18：55 　〈〈〈

* テレビで大聖寺川の鹿島の森，北白川という匿名弁護士アカウントのツイートを記録しながら探した七五三の写真，思いを馳せる被害者安藤文さんの21年と弁護士泥棒神社の物語（１）

:CATEGORIES: 被害者安藤文さん

　かなりの数のツイートを記録しましたが，それをリツイートでご紹介することから始めたいと思います。8月12日ということで先祖の霊が帰るというお盆に入っているのかとも考えるのですが，偶然とは思えない成り行きと展開でした。潮津神社のこともあります。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:56／2020/08/12 21:41 URL： https://twitter.com/kk_hirono/status/1293546792311635968 https://twitter.com/hirono_hideki/status/1293527910301593601  

> パッション - Google 検索 https://t.co/hiOhwUZ8IA  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:56／2020/08/12 21:38 URL： https://twitter.com/kk_hirono/status/1293546812477861888 https://twitter.com/hirono_hideki/status/1293527234699882498  

> 2020年08月12日20時20分の登録： ＼北白川　@GUv4i6＼こんなしちめんどくさいしごと娘にはさせたくないと思うが、じゃあ、他の仕事何がいいかって、大概の仕事は同じくしちめんどくさいぞ…まあ病まずに、これ https://t.co/FyZs5t3vcD  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:56／2020/08/12 21:38 URL： https://twitter.com/kk_hirono/status/1293546832711180288 https://twitter.com/hirono_hideki/status/1293527208326131712  

> 2020年08月12日20時19分の登録： ＼北白川　@GUv4i6＼起訴前保釈うらやましいが、日本でやるとしても、弁護人とか保釈金貸す業者とかいろいろ整備必要だろな。 一日中裁判所にいる弁護士が必要になる気がする https://t.co/qSf8PoMBTp  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:56／2020/08/12 21:38 URL： https://twitter.com/kk_hirono/status/1293546846267138053 https://twitter.com/hirono_hideki/status/1293527181960740864  

> 2020年08月12日20時17分の登録： ＼北白川　@GUv4i6＼検察統計で計算できたはず。 平成３０年だと全国の検察送致件数（交通事故案件除く）が１０８８８５で，全国の釈放数（交通事故案件除く）が７５２９だか https://t.co/mRyrU6Kd0l  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:56／2020/08/12 21:38 URL： https://twitter.com/kk_hirono/status/1293546859605028864 https://twitter.com/hirono_hideki/status/1293527155498835968  

> 2020年08月12日20時17分の登録： ＼北白川　@GUv4i6＼仙台家裁はいろいろいいなあって思うことが多いんだよなあ。所長があの本書いている人だったとかだからなのかな https://t.co/hjevgCcQpE  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:56／2020/08/12 21:37 URL： https://twitter.com/kk_hirono/status/1293546871936319488 https://twitter.com/hirono_hideki/status/1293527129120899074  

> 2020年08月12日20時16分の登録： ＼北白川　@GUv4i6＼司法試験の時の記憶がほぼない。マイドームとかいうふざけた名前だった記憶しか無い。 https://t.co/jsSEZyz7hF  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:56／2020/08/12 21:37 URL： https://twitter.com/kk_hirono/status/1293546882661195776 https://twitter.com/hirono_hideki/status/1293527102789005312  

> 2020年08月12日19時32分の登録： ＼北白川　@GUv4i6＼まあ，ただ，起訴前保釈うらやましすっていうと，検察官の友だちからすかさず「アメリカは無令状逮捕の範囲広いし，現に無令状で逮捕されまくってるぞ」と https://t.co/nEjbkDDGpZ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:56／2020/08/12 21:37 URL： https://twitter.com/kk_hirono/status/1293546893033652226 https://twitter.com/hirono_hideki/status/1293527076440403968  

> 2020年08月12日19時32分の登録： ＼ぎたべん　@guitar_ben＼「日本は令状主義で良かった！裁判官が適切に判断してくれるもんね！」…なんて思えるかバカヤローー！！！ https://t.co/7sIxvSdHDf  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:56／2020/08/12 21:37 URL： https://twitter.com/kk_hirono/status/1293546902324051968 https://twitter.com/hirono_hideki/status/1293527050070835200  

> 2020年08月12日19時31分の登録： ＼りっぴぃ　@rippy08＼性犯罪にせよその他類型の犯罪にせよ，「犯罪を許さない」ことと，行為者（と疑われた人）を厳罰に処すること，必罰主義とはまた別だと思うのですが， https://t.co/UrEB5NTfxi  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:56／2020/08/12 21:37 URL： https://twitter.com/kk_hirono/status/1293546913287921665 https://twitter.com/hirono_hideki/status/1293527023734779906  

> 2020年08月12日18時11分の登録： ＼モトケン　@motoken_tw＼＞起訴前保釈  運用次第では虚偽自白を量産する恐れがあります。 裁判官が客観証拠に基づく証拠隠滅の現実的可能性の有無程度を考慮してくれ https://t.co/FlmwZSM31c  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:56／2020/08/12 21:37 URL： https://twitter.com/kk_hirono/status/1293546925292023809 https://twitter.com/hirono_hideki/status/1293526997302308865  

> 2020年08月12日18時10分の登録： ＼大窪和久　@okuboka＼起訴前勾留は自白を「確保」する人質司法の核になるところなので、法務省は一貫して起訴前勾留での保釈制度の設置には反対しています。裁判所も逃亡や https://t.co/ifyUVHaYx7  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:56／2020/08/12 21:37 URL： https://twitter.com/kk_hirono/status/1293546936092393472 https://twitter.com/hirono_hideki/status/1293526970945294337  

> 2020年08月12日18時08分の登録： ＼モトケン　@motoken_tw＼性風俗産業は男性の本能に基づくニーズがあるので、禁止しただけでは反社が専売的地位で営業を独占するだけなので、従業員の安全性や待遇が悪化 https://t.co/kzvXuQcfeL  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:56／2020/08/12 21:37 URL： https://twitter.com/kk_hirono/status/1293546945680560134 https://twitter.com/hirono_hideki/status/1293526944579895296  

> 2020年08月12日18時08分の登録： ＼モトケン　@motoken_tw＼風俗嬢のことを考えているようで何も考えていないじょいたまちゃん。 再掲 https://t.co/sPrqrU7QCZ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:56／2020/08/12 21:37 URL： https://twitter.com/kk_hirono/status/1293546956086628352 https://twitter.com/hirono_hideki/status/1293526918189334528  

> 2020年08月12日18時06分の登録： ＼モトケン　@motoken_tw＼女性に生理があるように男性にも生理がある。射精といいますけどね。 女性の生理は本人にとって憂鬱なことにとどまるが、男性の生理が暴発する https://t.co/SCVvsvZrOk  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:56／2020/08/12 21:36 URL： https://twitter.com/kk_hirono/status/1293546968384299008 https://twitter.com/hirono_hideki/status/1293526891761000451  

> 2020年08月12日17時56分の登録： ＼古家野 彰平　@shoheikoyanolaw＼司法試験委員のあくどさを呪うのも  今はやめとけ  今はただ自分が受かることだけ考えればいい  今日の試験は負けられない https://t.co/kR0iXQ9KPy  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:56／2020/08/12 21:36 URL： https://twitter.com/kk_hirono/status/1293546980585533445 https://twitter.com/hirono_hideki/status/1293526865357889537  

> 2020年08月12日17時55分の登録： ＼サイ太　@uwaaaa＼「日本も即日保釈制度を作れ」みたいなことを言っている弁護士，性犯罪になると真逆なことを言う人が一定数含まれそう https://t.co/A7xpmEqO9C  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:56／2020/08/12 21:36 URL： https://twitter.com/kk_hirono/status/1293546994162495489 https://twitter.com/hirono_hideki/status/1293526838988247040  

> 2020年08月12日17時55分の登録： ＼弁護士 浦川ゆーすけ　@yurakawa92＼みんなマジでこれ読んで。  まんが 弁護士が教えるウソを見抜く方法   深澤 諭史 https://t.co/vk9pjbz4fe.j https://t.co/0eiIdph7If  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:56／2020/08/12 21:36 URL： https://twitter.com/kk_hirono/status/1293547005810061312 https://twitter.com/hirono_hideki/status/1293526812601905154  

> 2020年08月12日17時50分の登録： ＼ピピピーッ　@O59K2dPQH59QEJx＼相談者やばそう、事件の筋悪い→手間かかるのミエミエやし高い見積出すしかない。  相談者「払います！（しかも、高い金払ったの https://t.co/KKJ2GenNVh  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:56／2020/08/12 21:36 URL： https://twitter.com/kk_hirono/status/1293547019106045952 https://twitter.com/hirono_hideki/status/1293526786219753472  

> 2020年08月12日17時49分の登録： ＼ルート６６（元ルパン３世）　@Route66_LP3＼よもや合格者数ではなく司法試験の受験者が3000人台になる時代が来るとは… https://t.co/3ghBybZmQ8  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:56／2020/08/12 21:36 URL： https://twitter.com/kk_hirono/status/1293547030334251009 https://twitter.com/hirono_hideki/status/1293526759808225286  

> 2020年08月12日17時49分の登録： ＼深澤諭史　@fukazawas＼いや、ほんと疑問というか不思議なのは、受験生、新人弁護士を経済的に追い込みまくる政策を支持しながら、「苦しいっていうな！」って言い出すと https://t.co/zzepuMKvey  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:57／2020/08/12 21:36 URL： https://twitter.com/kk_hirono/status/1293547045559521281 https://twitter.com/hirono_hideki/status/1293526733405040642  

> 2020年08月12日17時46分の登録： ＼白石　資朗　@shiraishilo＼法科大学院関係者「弁護士が経済的に辛いだなんていう、弁護士会のネガティブキャンペーンのせい。」 https://t.co/GCthiUXsY5  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜chemicalgroom（ゴルーグ２８号） 日時：2020-08-12 22:57／2020/06/21 15:56 URL： https://twitter.com/kk_hirono/status/1293547068061966347 https://twitter.com/chemicalgroom/status/1274597147841716226  

> 「黒川弘務さん、みそぎでヌードやらないかなぁ。篠山紀信撮影ならバカ売れだろうなぁ」とか考えているので多分今日はとても疲れている気がします。帰ろう。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜freeryota（ryota） 日時：2020-08-12 22:57／2020/08/07 07:36 URL： https://twitter.com/kk_hirono/status/1293547083127873537 https://twitter.com/freeryota/status/1291503436102434816  

> 何これ、おもろすぎ。 https://t.co/5f7zl1g22r  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:57／2020/08/12 20:12 URL： https://twitter.com/kk_hirono/status/1293547096985935874 https://twitter.com/hirono_hideki/status/1293505693874450433  

> 櫻田山神社 - Wikiwand https://t.co/sWwt7lFD8a 約1500年前に創建されたとされ[1]、県内でも有数の歴史を持つ。社格は村社。  お笑いタレントである狩野英孝の実家としても知られており、彼の持ちネ… https://t.co/OTALPGTaOI  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:57／2020/08/12 20:12 URL： https://twitter.com/kk_hirono/status/1293547109103239170 https://twitter.com/hirono_hideki/status/1293505614665007107  

> 櫻田山神社 - Wikiwand https://t.co/sWwt7lFD8a 櫻田山神社（さくらださんじんじゃ）は、宮城県栗原市栗駒桜田にある神社。正式名称は山神社（さんじんじゃ）であるが、地区名の桜田を冠した「櫻田山神社」で一般に呼ばれる。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:57／2020/08/12 20:08 URL： https://twitter.com/kk_hirono/status/1293547131727310849 https://twitter.com/hirono_hideki/status/1293504585693200385  

> 狩野英孝 - Wikiwand https://t.co/rmQBOxzlTP 宮城県築館高等学校を卒業。高校時代は弓道部に所属し、国民体育大会の宮城県代表選手に選抜されるほどの腕前だった。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:57／2020/08/12 20:07 URL： https://twitter.com/kk_hirono/status/1293547145572753412 https://twitter.com/hirono_hideki/status/1293504376753934339  

> 狩野英孝 - Wikiwand https://t.co/rmQBOxzlTP 宮城県泉市（現：仙台市泉区）生まれ。同県栗原郡栗駒町（現：栗原市）育ち。幼少期を泉市、黒川郡富谷町（現：富谷市）などで過ごしたが、父が神職の資格を取得… https://t.co/oMfqfoRNcG  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:57／2020/08/12 20:07 URL： https://twitter.com/kk_hirono/status/1293547160210829319 https://twitter.com/hirono_hideki/status/1293504254255042560  

> 狩野英孝 - Wikiwand https://t.co/rmQBOxzlTP 宮城県栗原郡栗駒町出身[3]。日本映画学校（現在の日本映画大学）俳優科卒業、東京都神社庁主催神職養成講習会修了。マセキ芸能社所属。また櫻田山神社で神職も務めている。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:57／2020/08/12 20:06 URL： https://twitter.com/kk_hirono/status/1293547177038381062 https://twitter.com/hirono_hideki/status/1293504034255409152  

> 狩野英孝 - Wikiwand https://t.co/rmQBOxzlTP 狩野 英孝（かの えいこう、1982年（昭和57年）2月22日[1] - ）は日本の男性お笑いタレント（ピン芸人）、シンガーソングライター、声優、神職、YouTuberである。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:57／2020/08/12 19:46 URL： https://twitter.com/kk_hirono/status/1293547192238579714 https://twitter.com/hirono_hideki/status/1293499148751101954  

> 鹿島の森 - Google 検索 https://t.co/Nue29VWF86  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:57／2020/08/12 19:45 URL： https://twitter.com/kk_hirono/status/1293547208906702849 https://twitter.com/hirono_hideki/status/1293498764011778049  

> 絶好調W【夏を乗り切る！スタミナ＆涼感グルメ】 - Gガイド.テレビ王国 https://t.co/76bVHiqLe2 石川と福井の県境。  その昔、神々が奪い合った伝説の森…  そこには未知との遭遇が待っていた！  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:57／2020/08/12 19:44 URL： https://twitter.com/kk_hirono/status/1293547237100777473 https://twitter.com/hirono_hideki/status/1293498626417729536  

> Twitterでの会話について https://t.co/EzRuKjdZOa 新しいツイートを作成する際、そのツイートに返信できるユーザーを選ぶことができます。初期設定では、ツイート作成ボックスの地球アイコンの横に、[すべてのア… https://t.co/tzh6NfgpN3  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:57／2020/08/12 19:43 URL： https://twitter.com/kk_hirono/status/1293547250220580864 https://twitter.com/hirono_hideki/status/1293498373794721793  

> 絶好調W【夏を乗り切る！スタミナ＆涼感グルメ】     8/12 (水) 19:00 ～ 19:58 （58分） この時間帯の番組表      ＭＲＯ(Ch.6)     バラエティー - 旅バラエティ , 情報／ワイドショー -… https://t.co/81wPdPFrBs  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜oricon（ORICON NEWS（オリコンニュース）） 日時：2020-08-12 22:57／2020/08/12 16:02 URL： https://twitter.com/kk_hirono/status/1293547278980923395 https://twitter.com/oricon/status/1293442615006830592  

> 元欅坂46・今泉佑唯、新型コロナウイルス感染 https://t.co/88a2FJrvMS   #今泉佑唯 @yuuui_imaizumi  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:58／2020/08/12 19:28 URL： https://twitter.com/kk_hirono/status/1293547301206519810 https://twitter.com/hirono_hideki/status/1293494530314969091  

> - 779：2020-08-12_19:28:15 ＊ 「人質司法を実現し続けているのが現状。起訴前勾留での保釈があればどれだけ冤罪が防げたことか。」というモトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインでみたツイート https://t.co/Xnqw5JojED  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:58／2020/08/12 17:45 URL： https://twitter.com/kk_hirono/status/1293547316746391564 https://twitter.com/hirono_hideki/status/1293468680949362690  

> 2020年08月12日17時44分の登録： ＼白石　資朗　@shiraishilo＼発足当時を見れば明らかなとおり（合格者１０００人見込みのところ６０００人を超える定員）、彼らにとっては「入学金と授業料を取れるか」 https://t.co/wf4F01CTqJ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜o2441（弁護士大西洋一） 日時：2020-08-12 22:58／2020/08/12 17:20 URL： https://twitter.com/kk_hirono/status/1293547333049651200 https://twitter.com/o2441/status/1293462294408568833  

> 恐ろしい合格率になりそう・・。 https://t.co/XmPP89946p  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:58／2020/08/12 17:39 URL： https://twitter.com/kk_hirono/status/1293547369984700418 https://twitter.com/hirono_hideki/status/1293467148568784896  

> - 778：2020-08-12_17:39:26 ＊ ジャーナリストの江川紹子氏のタイムラインで知った，「事故のドライバー、無罪だったのに免許戻らず職失う…「行政の対応ひどい」弁護団がクラファン」 https://t.co/zRHahmSfze  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ibbZEuXH3AkukTh（司法試験八神（八振）） 日時：2020-08-12 22:58／2020/05/02 20:44 URL： https://twitter.com/kk_hirono/status/1293547392604594178 https://twitter.com/ibbZEuXH3AkukTh/status/1256550187108990978  

> 司法試験に20年以上挑戦し続けたが合格できなかった。  もう一度生まれ変わったら何したい？ そう聞かれても、私は「また司法試験に挑戦したい」 と答えるであろう。 たとえ再び失敗しても前のめりで倒れたい。 周囲から馬鹿にされても それが20年続けて形作った私なりの美学である。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜iijyanka（いいじゃんか） 日時：2020-08-12 22:58／2020/08/12 13:44 URL： https://twitter.com/kk_hirono/status/1293547418353426433 https://twitter.com/iijyanka/status/1293408014997704704  

> @o2441 @bengo4topics 「不起訴」は無罪とは別物。 推定無罪の原則は大事なんだが、交通事故が多過ぎて司法が捌ききれない&amp;検察が起訴手続きをこなせないから不起訴にしてる面もある 不起訴で免許差し戻してたら大パニック… https://t.co/NHeSd05hbo  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:58／2020/08/12 14:25 URL： https://twitter.com/kk_hirono/status/1293547437273931776 https://twitter.com/hirono_hideki/status/1293418335229505536  

> 事故のドライバー、無罪だったのに免許戻らず職失う…「行政の対応ひどい」弁護団がクラファン - 弁護士ドットコム https://t.co/Bk4iUrH4Yw  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:58／2020/08/12 14:03 URL： https://twitter.com/kk_hirono/status/1293547477883219968 https://twitter.com/hirono_hideki/status/1293412695236988929  

> 2020年08月12日13時15分の登録： ＼奥村徹弁護士　@okumuraosaka＼当たり前の事だが、捜査機関の立証に必要なことしか調書に取ってない。略式の事件だと端的にわかる。 https://t.co/9YKX2eKZiC  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:58／2020/08/12 14:03 URL： https://twitter.com/kk_hirono/status/1293547493200822273 https://twitter.com/hirono_hideki/status/1293412668787720193  

> 2020年08月12日13時13分の登録： ＼深澤諭史　@fukazawas＼あるあるあるあるある。児童ポルノ事件だとその傾向が強い。 \n （＾ω＾）自首したりするときは、このポイントで上申書巻くと有効ですお。 https://t.co/kxgh8bLvZP  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:58／2020/08/12 14:02 URL： https://twitter.com/kk_hirono/status/1293547513706737666 https://twitter.com/hirono_hideki/status/1293412642464231424  

> 2020年08月12日08時53分の登録： ＼すか?　@suka_t＼そおゆうとこだぞ事案パート2 https://t.co/LcKlJyHJ0Z  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:58／2020/08/12 14:02 URL： https://twitter.com/kk_hirono/status/1293547534443409408 https://twitter.com/hirono_hideki/status/1293412616111394816  

> 2020年08月12日08時51分の登録： ＼深澤諭史　@fukazawas＼たとえどんなに・・、不運、不幸、コロナに問題漏洩、合格者数減に見舞われようと・・。 \n オレは決して諦めない・・！ \n 捩じ伏せる・ https://t.co/NjkHkTHq04  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:59／2020/08/12 14:02 URL： https://twitter.com/kk_hirono/status/1293547568446599168 https://twitter.com/hirono_hideki/status/1293412589666328577  

> 2020年08月12日04時05分の登録： 2020-08-11の投稿一覧＼検察・石川県警察宛記録資料＼奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中：20件 https://t.co/rMJ8UJZVN7  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:59／2020/08/12 13:48 URL： https://twitter.com/kk_hirono/status/1293547590336667650 https://twitter.com/hirono_hideki/status/1293408975354961924  

> - 777：2020-08-12_13:48:17 (イ). 平成4年1月上旬，市場急配センター2階の事務所の台所付近，被害者安藤文さんの方に私の体を押しやった被告発人浜口卓也 https://t.co/hIf3OU0cRB  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:59／2020/08/12 13:48 URL： https://twitter.com/kk_hirono/status/1293547612776198149 https://twitter.com/hirono_hideki/status/1293408880383287296  

> - 776：2020-08-12_13:47:54 (ア). 被告発人浜口卓也が，私と被害者安藤文さんとの関係を最初に知っていると思ったのは平成3年12月21日の夕方 https://t.co/R87Dumkl84  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:59／2020/08/12 11:17 URL： https://twitter.com/kk_hirono/status/1293547628538368001 https://twitter.com/hirono_hideki/status/1293370964504276993  

> - 775：2020-08-12_11:17:14 (キ). 被告発人安田繁克が話し始めた被害者安藤文さんとの関係，交際を否定 https://t.co/xIYDVe1KDB  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:59／2020/08/12 10:49 URL： https://twitter.com/kk_hirono/status/1293547643046592512 https://twitter.com/hirono_hideki/status/1293363974319165440  

> - 774：2020-08-12_10:49:27 (カ). 山三青果の運行から戻りしばらく1階休憩室にいた被告発人多田敏明 https://t.co/oRV8uyQLpK  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:59／2020/08/12 09:37 URL： https://twitter.com/kk_hirono/status/1293547664303206400 https://twitter.com/hirono_hideki/status/1293345790102970368  

> - 773：2020-08-12_09:37:12 ＊ python3で起こっていたgoogle-api-python-clientのエラーが解決 https://t.co/IfU15BXgHm  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:59／2020/08/12 09:34 URL： https://twitter.com/kk_hirono/status/1293547681051111426 https://twitter.com/hirono_hideki/status/1293345114685706240  

> PythonでNo module named 'apiclient.discovery' エラーへの対応 - ヘンゼルのパンくず https://t.co/yNJoXIwhrw  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:59／2020/08/12 09:29 URL： https://twitter.com/kk_hirono/status/1293547703255760896 https://twitter.com/hirono_hideki/status/1293343722491375616  

> - 772：2020-08-12_09:29:01 ＊ WSL2のUbuntuでのspt,mysql-server,rubyのエラー，インストルのし直し https://t.co/odwvVUJibm  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜nikkei（日本経済新聞 電子版） 日時：2020-08-12 22:59／2020/08/12 07:34 URL： https://twitter.com/kk_hirono/status/1293547735698743296 https://twitter.com/nikkei/status/1293314821786611714  

> 鉄道から不動産に軸足を移し東京・渋谷に集中投資してきた東急。テレワークでオフィス離れが進み戦略見直しを迫られています。惣菜宅配や郊外型ビジネスなど新常態に対応します。 #新型コロナ https://t.co/0GfCoPAX9Y  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜nikkei（日本経済新聞 電子版） 日時：2020-08-12 22:59／2020/08/12 02:09 URL： https://twitter.com/kk_hirono/status/1293547752257855488 https://twitter.com/nikkei/status/1293233177922662400  

> 東急、渋谷依存に試練　テレワークでオフィス離れ加速 https://t.co/SjUmdHpuwo  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 22:59／2020/08/12 07:09 URL： https://twitter.com/kk_hirono/status/1293547773438988288 https://twitter.com/hirono_hideki/status/1293308593261821952  

> - 2020年08月12日04時03分の登録： ツイートの記録資料：＼法務検察・石川県警察宛＼／深澤諭史（@fukazawas）／”2020年08月11日”：60件 https://t.co/jfE8vTXxZC  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 23:00／2020/08/12 07:09 URL： https://twitter.com/kk_hirono/status/1293547786982440964 https://twitter.com/hirono_hideki/status/1293308566816739329  

> - 2020年08月12日04時03分の登録： ツイートの記録資料：＼法務検察・石川県警察宛＼／モトケン（@motoken_tw）／”2020年08月11日”：49件 https://t.co/Vw77QOf4AX  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 23:00／2020/08/12 06:51 URL： https://twitter.com/kk_hirono/status/1293547806351699969 https://twitter.com/hirono_hideki/status/1293304046585966592  

> `rubygems-update requires Ruby version &gt;= 2.3.0` のエラーが出るとき - Qiita https://t.co/13tHEDk4Vp  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 23:00／2020/08/12 04:51 URL： https://twitter.com/kk_hirono/status/1293547824831897602 https://twitter.com/hirono_hideki/status/1293273867251720194  

> WSL2の初歩メモ - Qiita https://t.co/MNCERExOxO  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 23:00／2020/08/11 20:01 URL： https://twitter.com/kk_hirono/status/1293547838081650688 https://twitter.com/hirono_hideki/status/1293140587105771521  

> 2020年08月11日20時01分の登録： ＼Shoko Egawa　@amneris84＼介護の現場はホッとしていることでしょう。　→ドーナツ死裁判、准看護師の無罪確定へ　高検が上告断念：朝日新聞デジタル https://t.co/IonYEb885s  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜o2441（弁護士大西洋一） 日時：2020-08-12 23:00／2020/08/11 19:59 URL： https://twitter.com/kk_hirono/status/1293547865675948032 https://twitter.com/o2441/status/1293140007633395717  

> へー、かわいそう。 　 【レバノン爆発】カルロス・ゴーン被告の自宅は完全破壊と報道　ホームレス状態に｜ニフティニュース https://t.co/IdBd89XWpL  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-12 23:00／2020/08/11 20:00 URL： https://twitter.com/kk_hirono/status/1293547885649223680 https://twitter.com/hirono_hideki/status/1293140179692081163  

> iPhoneでATOKを使う方法。iOS 8から標準のキーボードとして利用できる！ | iPhone | できるネット https://t.co/XbDEHWUDUp  

　次にスクリーンショットの記録になります。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:01／2020/08/12 22:47 URL： https://twitter.com/kk_hirono/status/1293548131263451138 https://twitter.com/s_hirono/status/1293544710653411328  

> 2020-08-12-224625_イケメン弁護士（PRO）@ikemen_lawyer·4時間返信先：　@sakamotomasayukさん着実に目標の７，８割合格に近づいて.jpg https://t.co/JzG7ddezdh  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:01／2020/08/12 22:47 URL： https://twitter.com/kk_hirono/status/1293548142697168896 https://twitter.com/s_hirono/status/1293544637806698496  

> 2020-08-12-223520_弁護士樋詰哲朗@hizumelawブロックされています@hizumelawさんのフォローやツイートの表示はできません。詳細はこちら.jpg https://t.co/mCEJezg3QR  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:01／2020/08/12 22:47 URL： https://twitter.com/kk_hirono/status/1293548155942797313 https://twitter.com/s_hirono/status/1293544564926513153  

> 2020-08-12-223019_弁護士　市川　寛@imarockcaster42·8月11日真実を訴えるＶが嘘つきＡの弁護人にいじめられるのはひどいと思いますけど、刑事裁判.jpg https://t.co/rqXQ9Jt63t  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:01／2020/08/12 22:46 URL： https://twitter.com/kk_hirono/status/1293548168567590913 https://twitter.com/s_hirono/status/1293544491878477826  

> 2020-08-12-222930_モトケン@motoken_tw·4時間わお、弓月先生からいいねをもらったぞ　＊＼（＾o＾）／＊「甘い生活」には何人も巨乳キャラが登場するんだ.jpg https://t.co/8gJNQyafcN  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:01／2020/08/12 22:46 URL： https://twitter.com/kk_hirono/status/1293548185273548800 https://twitter.com/s_hirono/status/1293544419115675650  

> 2020-08-12-222832_モトケン@motoken_tw矢部善朗。元検事の弁護士（京都弁護士会）です。　アイコン（作者は　Y_Coronaさん）は単なる趣味（＾＾；　.jpg https://t.co/NyTdaXUaKA  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:01／2020/08/12 22:26 URL： https://twitter.com/kk_hirono/status/1293548199169241090 https://twitter.com/s_hirono/status/1293539467353939971  

> 2020-08-12-222458_弁護士　大山定伸@oyamalawS51大阪市生野区生まれ。大阪市立巽小学校卒。愛媛県愛光学園中学・高校卒（36期）。早稲田大学法学部卒。早.jpg https://t.co/qoYTPKjY2l  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:01／2020/08/12 22:26 URL： https://twitter.com/kk_hirono/status/1293548210623897601 https://twitter.com/s_hirono/status/1293539394675027969  

> 2020-08-12-222350_つまらむさんがリツイートサイ太@uwaaaa·11時間「日本も即日保釈制度を作れ」みたいなことを言っている弁護士，性犯罪になると真逆なことを.jpg https://t.co/aARML1sDlL  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:01／2020/08/12 22:26 URL： https://twitter.com/kk_hirono/status/1293548224318328833 https://twitter.com/s_hirono/status/1293539321660633088  

> 2020-08-12-222200_つまらむさんがリツイート要　友紀子傘SWASH@kanameyukiko·4時間風俗のこと知らない人が、風俗嬢の平均月収34万〜37万と聞い.jpg https://t.co/28bLT5pnuM  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:01／2020/08/12 22:26 URL： https://twitter.com/kk_hirono/status/1293548242026676225 https://twitter.com/s_hirono/status/1293539248612601856  

> 2020-08-12-221424_つまらむ@km0bakeそら、医師にくらべたら低いわな。。。午後6：10　·　2020年8月12日·Twitter　for　Android.jpg https://t.co/vPG1moh1HD  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:01／2020/08/12 22:25 URL： https://twitter.com/kk_hirono/status/1293548258740985856 https://twitter.com/s_hirono/status/1293539175812063232  

> 2020-08-12-221340_つまらむ@km0bake·3時間ジャンプは「性犯罪は許さない」というコメントを出すべきで、出さないから許さない。と暴れ回ってる人たちがいるの.jpg https://t.co/zpO6ZCAyT2  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:01／2020/08/12 22:25 URL： https://twitter.com/kk_hirono/status/1293548274863861760 https://twitter.com/s_hirono/status/1293539103099637761  

> 2020-08-12-221132_つまらむ@km0bake·3時間犯罪が許されないから、逮捕段階で、いまだ確定してないのに、連載を打ち切ったんでしょうに。確定してないのに、有.jpg https://t.co/4XRdTgaYMy  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:02／2020/08/12 22:25 URL： https://twitter.com/kk_hirono/status/1293548291624378368 https://twitter.com/s_hirono/status/1293539030424891393  

> 2020-08-12-220058_弁護士　亀石倫子さんがリツイート高橋雄一郎@kamatatylaw·15時間周庭女史は逮捕されたが２６０万円の保釈金を払って釈放された。人権.jpg https://t.co/v5o0MXKVFd  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:02／2020/08/12 22:00 URL： https://twitter.com/kk_hirono/status/1293548304647639041 https://twitter.com/s_hirono/status/1293532857961390083  

> 2020-08-12-215642_イケメン弁護士（PRO）@ikemen_lawyer·8月7日転職受容のプロセス①否認　自分の事務所がやばいはずはない、そのうち改善されるは.jpg https://t.co/BzJBDpJHKr  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:02／2020/08/12 22:00 URL： https://twitter.com/kk_hirono/status/1293548318719500290 https://twitter.com/s_hirono/status/1293532784758124546  

> 2020-08-12-215444_イケメン弁護士（PRO）さんがリツイート深澤諭史@fukazawas·4時間いや、ほんと疑問というか不思議なのは、受験生、新人弁護士を経済的.jpg https://t.co/OpCB1AVo3T  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:02／2020/08/12 22:00 URL： https://twitter.com/kk_hirono/status/1293548331612790785 https://twitter.com/s_hirono/status/1293532711651426305  

> 2020-08-12-215417_イケメン弁護士（PRO）@ikemen_lawyer都内のキラキラ弁護士。69期。4年目企業法務。31歳。ガッキーが好きです。とても太りまし.jpg https://t.co/MFx7JJZZXx  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:02／2020/08/12 21:59 URL： https://twitter.com/kk_hirono/status/1293548344157954049 https://twitter.com/s_hirono/status/1293532638821539841  

> 2020-08-12-215339_えきなんローヤー🕊さんがリツイート白石　資朗@shiraishilo·4時間発足当時を見れば明らかなとおり（合格者１０００人見込みのところ６.jpg https://t.co/4XMmIpUWYV  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:02／2020/08/12 21:59 URL： https://twitter.com/kk_hirono/status/1293548357252571137 https://twitter.com/s_hirono/status/1293532565752619008  

> 2020-08-12-215305_えきなんローヤー🕊さんがリツイート弁護士大西洋一@o2441·2時間事務所の支店も人数も増えたので、弁護士業務以上に経営関連の雑務が結構あっ.jpg https://t.co/p1d5mj8Ng3  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:02／2020/08/12 21:59 URL： https://twitter.com/kk_hirono/status/1293548372524068865 https://twitter.com/s_hirono/status/1293532492989751297  

> 2020-08-12-215138_えきなんローヤー🕊さんがリツイートgimu13@gimu13·2時間検察官の15分遅刻で文句言うくらい刑事裁判に関心があるなら、国選報酬を上.jpg https://t.co/hHvbjevLRE  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:02／2020/08/12 21:58 URL： https://twitter.com/kk_hirono/status/1293548386541424640 https://twitter.com/s_hirono/status/1293532420239552518  

> 2020-08-12-214958_えきなんローヤー🕊さん　（@ekinan_lawyer）　／　Twitter.jpg https://t.co/amVshwnZw5  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:02／2020/08/12 21:58 URL： https://twitter.com/kk_hirono/status/1293548418300690434 https://twitter.com/s_hirono/status/1293532347413884930  

> 2020-08-12-214903_ツイッターのリプを制限する仕様により、デマツイートに批判をぶら下げて対抗することが困難になった。表現の自由市場の前提となる対抗言論は難しくな.jpg https://t.co/rzVGrUIcP6  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:02／2020/08/12 21:58 URL： https://twitter.com/kk_hirono/status/1293548432313815040 https://twitter.com/s_hirono/status/1293532274281943045  

> 2020-08-12-214711_深澤諭史さんがリツイート山口貴士　aka無駄に感じが悪いヤマベン@otakulawyer·2時間ツイッターのリプを制限する仕様により、デマツ.jpg https://t.co/mCIy2Ip2cs  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:02／2020/08/12 21:58 URL： https://twitter.com/kk_hirono/status/1293548445823721472 https://twitter.com/s_hirono/status/1293532201418596352  

> 2020-08-12-214619_Shin　Horiさん　（@ShinHori1）　／　Twitter.jpg https://t.co/9Wp41EBx7N  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:02／2020/08/12 21:57 URL： https://twitter.com/kk_hirono/status/1293548464240902144 https://twitter.com/s_hirono/status/1293532128685068288  

> 2020-08-12-214336_深澤諭史@fukazawas·11分モスバーガー、昨年290万食売り上げた「海老天七味マヨ」復活販売　｜　RBB　TODAY　https：／.jpg https://t.co/8Nt5aIbLA4  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:02／2020/08/12 21:57 URL： https://twitter.com/kk_hirono/status/1293548480502276101 https://twitter.com/s_hirono/status/1293532055792361472  

> 2020-08-12-214121_パッション　-　Google　検索.jpg https://t.co/XX3V8H4f9W  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:02／2020/08/12 21:57 URL： https://twitter.com/kk_hirono/status/1293548494792228866 https://twitter.com/s_hirono/status/1293531982958215169  

> 2020-08-12-214010_深澤諭史さんがリツイート泥濘大魔王サイケ@k_sawmen·13時間周庭氏保釈の件で弁護士がざわついてるのをネトウヨっぽい人が「なに言ってる.jpg https://t.co/vXrkabw0q3  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:02／2020/08/12 21:56 URL： https://twitter.com/kk_hirono/status/1293548509078011910 https://twitter.com/s_hirono/status/1293531910040244224  

> 2020-08-12-213831_北白川@GUv4i6こんなしちめんどくさいしごと娘にはさせたくないと思うが、じゃあ、他の仕事何がいいかって、大概の仕事は同じくしちめんどくさ.jpg https://t.co/1twMLxHbQN  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:02／2020/08/12 21:42 URL： https://twitter.com/kk_hirono/status/1293548523493892097 https://twitter.com/s_hirono/status/1293528314036940802  

> 2020-08-12-213227_”七五三”　（from：GUv4i6）　-　Twitter検索　／　Twitter.jpg https://t.co/iY4JjLUd3z  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:02／2020/08/12 21:42 URL： https://twitter.com/kk_hirono/status/1293548535799939072 https://twitter.com/s_hirono/status/1293528241383174144  

> 2020-08-12-213122_北白川@GUv4i6昨日、無事、七五三を終えたので今日は、すみっこぐらしみたら帰りますね.jpg https://t.co/zxHFawF5l8  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:03／2020/08/12 21:42 URL： https://twitter.com/kk_hirono/status/1293548549477605376 https://twitter.com/s_hirono/status/1293528167345397761  

> 2020-08-12-213038_北白川@GUv4i6·2019年11月24日昨日、無事、七五三を終えたので今日は、すみっこぐらしみたら帰りますね.jpg https://t.co/wShXeYvQ7q  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:03／2020/08/12 21:41 URL： https://twitter.com/kk_hirono/status/1293548560848310272 https://twitter.com/s_hirono/status/1293528094582530049  

> 2020-08-12-212929_北白川@GUv4i6·1月2日あんきものお豆腐をソテーしてみました.jpg https://t.co/p49g6TmET6  
* テレビで大聖寺川の鹿島の森，北白川という匿名弁護士アカウントのツイートを記録しながら探した七五三の写真，思いを馳せる被害者安藤文さんの21年と弁護士泥棒神社の物語（２）

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:03／2020/08/12 21:41 URL： https://twitter.com/kk_hirono/status/1293548574551060482 https://twitter.com/s_hirono/status/1293528021819781121  

> 2020-08-12-212841_北白川@GUv4i6諍い　強情も時によしとは考えさせられる。ちょっと和解率高いことは少し悩みではあるんよ、俺.jpg https://t.co/lOw3g4qVor  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:03／2020/08/12 21:41 URL： https://twitter.com/kk_hirono/status/1293548588501356544 https://twitter.com/s_hirono/status/1293527948574601217  

> 2020-08-12-212803_北白川@GUv4i6よっしゃ明日からむちゃくちゃ稼いでまた海外いくねん！午後10：21　·　2020年1月5日·Twitter　for　iP.jpg https://t.co/WSGQFZvIU3  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:03／2020/08/12 21:40 URL： https://twitter.com/kk_hirono/status/1293548604511010816 https://twitter.com/s_hirono/status/1293527875832799243  

> 2020-08-12-212734_北白川@GUv4i6法務省にしてはおもしろいことする午後0：08　·　2020年1月7日·Twitter　for　iPhone.jpg https://t.co/eN7vNm31Gv  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:03／2020/08/12 21:40 URL： https://twitter.com/kk_hirono/status/1293548619518193666 https://twitter.com/s_hirono/status/1293527802596061185  

> 2020-08-12-212656_北白川@GUv4i610年ぶりぐらいにたべた午後7：22　·　2020年1月8日·Twitter　for　iPhone.jpg https://t.co/uiL4RUFUSS  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:03／2020/08/12 21:40 URL： https://twitter.com/kk_hirono/status/1293548639495663616 https://twitter.com/s_hirono/status/1293527729699053568  

> 2020-08-12-212622_北白川@GUv4i6おー、やるやん、めっちゃうまそう。最近娘ちゃんが魚好きになって、うちの食卓が最高.jpg https://t.co/8Gh81oASTe  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:03／2020/08/12 21:40 URL： https://twitter.com/kk_hirono/status/1293548659989049345 https://twitter.com/s_hirono/status/1293527656001163265  

> 2020-08-12-212547_北白川@GUv4i6なんや、公判黙秘してんのか午後4：57　·　2020年1月11日·Twitter　for　iPhone.jpg https://t.co/Kg9Z8zz8sl  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:03／2020/08/12 21:39 URL： https://twitter.com/kk_hirono/status/1293548672769126400 https://twitter.com/s_hirono/status/1293527582562893824  

> 2020-08-12-212520_北白川@GUv4i6きたたのしみ午前10：21　·　2020年1月12日·Twitter　for　iPhone.jpg https://t.co/TreEWxr4Ck  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:03／2020/08/12 21:39 URL： https://twitter.com/kk_hirono/status/1293548693153411072 https://twitter.com/s_hirono/status/1293527509846224896  

> 2020-08-12-212446_北白川@GUv4i6なまはげのおくりもの午後10：17　·　2020年1月12日·Twitter　for　iPhone.jpg https://t.co/BdBa3FCgpG  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:03／2020/08/12 21:39 URL： https://twitter.com/kk_hirono/status/1293548705233043456 https://twitter.com/s_hirono/status/1293527437305774081  

> 2020-08-12-212419_北白川@GUv4i6妻氏、でかけた….jpg https://t.co/hti8QDFCSI  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:03／2020/08/12 21:38 URL： https://twitter.com/kk_hirono/status/1293548717010636800 https://twitter.com/s_hirono/status/1293527364459040769  

> 2020-08-12-212342_北白川@GUv4i6やはり「森」はこう午前9：07　·　2020年1月16日·Twitter　for　iPhone.jpg https://t.co/dTDtgBLMcp  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:03／2020/08/12 21:38 URL： https://twitter.com/kk_hirono/status/1293548731216744449 https://twitter.com/s_hirono/status/1293527291620810758  

> 2020-08-12-212306_北白川@GUv4i6今日は疲れた。お腹いっぱい。娘ちゃんもかなり滑られるようになったし、きてよかった。.jpg https://t.co/LUhIjx57JU  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:03／2020/08/12 21:38 URL： https://twitter.com/kk_hirono/status/1293548745771032576 https://twitter.com/s_hirono/status/1293527218828611585  

> 2020-08-12-212237_北白川@GUv4i6いえー！午後8：50　·　2020年1月19日·Twitter　for　iPhone.jpg https://t.co/8e2xCour9H  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:03／2020/08/12 21:37 URL： https://twitter.com/kk_hirono/status/1293548758819463169 https://twitter.com/s_hirono/status/1293527145793220609  

> 2020-08-12-212203_北白川@GUv4i6おお、今日は快晴.jpg https://t.co/3HDYigItpc  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:03／2020/08/12 21:37 URL： https://twitter.com/kk_hirono/status/1293548774518714373 https://twitter.com/s_hirono/status/1293527073269538816  

> 2020-08-12-212116_北白川@GUv4i6·1月22日今度、否認で保釈請求するときはこれを疎明資料にいれようかな.jpg https://t.co/F0aaqShJ8N  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:03／2020/08/12 21:37 URL： https://twitter.com/kk_hirono/status/1293548788489936896 https://twitter.com/s_hirono/status/1293527000137601028  

> 2020-08-12-212033_北白川@GUv4i6これが若狭か（定期.jpg https://t.co/Cuw4BHC6ED  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:04／2020/08/12 21:37 URL： https://twitter.com/kk_hirono/status/1293548801588785154 https://twitter.com/s_hirono/status/1293526927559426048  

> 2020-08-12-211926_北白川@GUv4i6お魚おいしいね.jpg https://t.co/ObyLgPI7QD  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:04／2020/08/12 21:36 URL： https://twitter.com/kk_hirono/status/1293548813899034625 https://twitter.com/s_hirono/status/1293526854662418437  

> 2020-08-12-211845_北白川@GUv4i6おお、そなたは美しい.jpg https://t.co/7nmSvAqWX2  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:04／2020/08/12 21:36 URL： https://twitter.com/kk_hirono/status/1293548828298158080 https://twitter.com/s_hirono/status/1293526782004441092  

> 2020-08-12-211806_北白川@GUv4i6足湯して帰りまーす午後9：09　·　2020年1月23日·Twitter　for　iPhone.jpg https://t.co/vqGDBqKqDo  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:04／2020/08/12 21:36 URL： https://twitter.com/kk_hirono/status/1293548843460472832 https://twitter.com/s_hirono/status/1293526709317169154  

> 2020-08-12-211719_北白川@GUv4i6しかし、最近、アトム好きやな、君は。最終回のアルマゲドン展開に落ち込むなよ。.jpg https://t.co/pVfS4g0l20  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:04／2020/08/12 21:35 URL： https://twitter.com/kk_hirono/status/1293548857591304198 https://twitter.com/s_hirono/status/1293526636361478144  

> 2020-08-12-211630_北白川@GUv4i6俺の中に流れる愛知県民の血が騒ぐぜ.jpg https://t.co/UqBHHZV0U1  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:04／2020/08/12 21:22 URL： https://twitter.com/kk_hirono/status/1293548872283824129 https://twitter.com/s_hirono/status/1293523320416043008  

> 2020-08-12-211539_北白川@GUv4i6ジャフバ、チラチラでてくんなし！午後2：54　·　2020年1月30日·Twitter　for　iPhone.jpg https://t.co/pvI4HneYM1  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:04／2020/08/12 21:22 URL： https://twitter.com/kk_hirono/status/1293548885965590531 https://twitter.com/s_hirono/status/1293523247351308293  

> 2020-08-12-211501_北白川@GUv4i6妻氏作成のおいしい汁.jpg https://t.co/RbPxj7TDgi  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:04／2020/08/12 21:22 URL： https://twitter.com/kk_hirono/status/1293548901320945664 https://twitter.com/s_hirono/status/1293523174433280000  

> 2020-08-12-211437_北白川@GUv4i6だから、今、大事なもの読んでるんだからチラチラでてくんな！ジャフバ！.jpg https://t.co/n5IlJtsb9a  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:04／2020/08/12 21:21 URL： https://twitter.com/kk_hirono/status/1293548913723547648 https://twitter.com/s_hirono/status/1293523101381038081  

> 2020-08-12-211405_北白川@GUv4i6·2月1日白熊食べて頭を冷やそう.jpg https://t.co/Bcj5FtWwdT  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:04／2020/08/12 21:21 URL： https://twitter.com/kk_hirono/status/1293548927996715010 https://twitter.com/s_hirono/status/1293523028639285248  

> 2020-08-12-211335_北白川@GUv4i6この本いいぞ〜.jpg https://t.co/y1MrH2w8Zp  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:04／2020/08/12 21:21 URL： https://twitter.com/kk_hirono/status/1293548939317096448 https://twitter.com/s_hirono/status/1293522956035821569  

> 2020-08-12-211302_北白川@GUv4i6グアムのときはこんなんやったな笑.jpg https://t.co/0BTP8xFmvx  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:04／2020/08/12 21:21 URL： https://twitter.com/kk_hirono/status/1293548951531003909 https://twitter.com/s_hirono/status/1293522882895572998  

> 2020-08-12-211218_北白川@GUv4i6ケース３の鳥取の方のご報告が素晴らしいのだが，どうやって協力医をみつけたのか非常に気になる（すくなくとも僕の地方では鑑定.jpg https://t.co/XyXtq3hP0W  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:04／2020/08/12 21:20 URL： https://twitter.com/kk_hirono/status/1293548965837774848 https://twitter.com/s_hirono/status/1293522810048925697  

> 2020-08-12-211135_北白川@GUv4i6欲しかったから買った.jpg https://t.co/2V97wOaRUI  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:04／2020/08/12 21:20 URL： https://twitter.com/kk_hirono/status/1293548978819104768 https://twitter.com/s_hirono/status/1293522736686358528  

> 2020-08-12-211107_北白川@GUv4i6訴因が気になるので受験時代の復習からはじめるか.jpg https://t.co/zj2RLoDmbW  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:04／2020/08/12 21:20 URL： https://twitter.com/kk_hirono/status/1293548994111500289 https://twitter.com/s_hirono/status/1293522663911038977  

> 2020-08-12-211030_北白川@GUv4i6あの夜だけが.jpg https://t.co/1jtqSMpuCw  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:04／2020/08/12 21:19 URL： https://twitter.com/kk_hirono/status/1293549010121236481 https://twitter.com/s_hirono/status/1293522591022424064  

> 2020-08-12-210935_北白川@GUv4i6お、お雛様飾ったんか.jpg https://t.co/EKRa4fHhdz  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:04／2020/08/12 21:19 URL： https://twitter.com/kk_hirono/status/1293549023802974208 https://twitter.com/s_hirono/status/1293522518179864576  

> 2020-08-12-210847_北白川@GUv4i6あ、どうも、当職です。午後9：02　·　2020年2月15日·Twitter　for　iPhone.jpg https://t.co/qPXrRyenYX  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:04／2020/08/12 21:19 URL： https://twitter.com/kk_hirono/status/1293549038290128898 https://twitter.com/s_hirono/status/1293522444934758407  

> 2020-08-12-210814_北白川@GUv4i6実家ナウ産まれてた午後10：25　·　2020年2月15日·Twitter　for　iPhone.jpg https://t.co/sZqdQa6ExO  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:05／2020/08/12 21:19 URL： https://twitter.com/kk_hirono/status/1293549052320079873 https://twitter.com/s_hirono/status/1293522371857412096  

> 2020-08-12-210723_北白川@GUv4i6午後8：42　·　2020年2月23日·Twitter　for　iPhone.jpg https://t.co/gCuQEnNZGU  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:05／2020/08/12 21:18 URL： https://twitter.com/kk_hirono/status/1293549064353529856 https://twitter.com/s_hirono/status/1293522297588862976  

> 2020-08-12-210617_北白川@GUv4i6さすがに暇そうだし買ってってあげようか。迷惑かな笑.jpg https://t.co/9pp58G9YQF  

* テレビで大聖寺川の鹿島の森，北白川という匿名弁護士アカウントのツイートを記録しながら探した七五三の写真，思いを馳せる被害者安藤文さんの21年と弁護士泥棒神社の物語（２）

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:05／2020/08/12 21:18 URL： https://twitter.com/kk_hirono/status/1293549077599154177 https://twitter.com/s_hirono/status/1293522224779898881  

> 2020-08-12-210512_北白川@GUv4i6蟹に興奮する娘.jpg https://t.co/npEr6XTRFJ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:05／2020/08/12 21:18 URL： https://twitter.com/kk_hirono/status/1293549094175047682 https://twitter.com/s_hirono/status/1293522151790632960  

> 2020-08-12-210441_北白川@GUv4i6よしいくぜ午前11：25　·　2020年3月22日·Twitter　for　iPhone.jpg https://t.co/A2gsgckazp  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:05／2020/08/12 21:17 URL： https://twitter.com/kk_hirono/status/1293549108137844741 https://twitter.com/s_hirono/status/1293522079115907072  

> 2020-08-12-210248_北白川@GUv4i6タイヤ新しくなた.jpg https://t.co/UyGE7QdcdW  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:05／2020/08/12 21:17 URL： https://twitter.com/kk_hirono/status/1293549121026965504 https://twitter.com/s_hirono/status/1293522006411886593  

> 2020-08-12-210157_北白川@GUv4i6接見研修器具.jpg https://t.co/B7gVzSD6Ro  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:05／2020/08/12 21:17 URL： https://twitter.com/kk_hirono/status/1293549136327790594 https://twitter.com/s_hirono/status/1293521933552689153  

> 2020-08-12-210118_北白川@GUv4i6刑事弁護の伝説ー神々のトライフォースー的なやつ.jpg https://t.co/dfXC6rbyET  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:05／2020/08/12 21:16 URL： https://twitter.com/kk_hirono/status/1293549151888711682 https://twitter.com/s_hirono/status/1293521860450062336  

> 2020-08-12-210041_北白川@GUv4i6読書.jpg https://t.co/80oyxQmGI5  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:05／2020/08/12 21:16 URL： https://twitter.com/kk_hirono/status/1293549166128332804 https://twitter.com/s_hirono/status/1293521787318177794  

> 2020-08-12-210003_北白川@GUv4i6当職、敬虔なタカシアン午前11：04　·　2020年4月20日·Twitter　for　iPhone.jpg https://t.co/mRYiwgVtZQ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:05／2020/08/12 21:16 URL： https://twitter.com/kk_hirono/status/1293549182502887424 https://twitter.com/s_hirono/status/1293521714265985025  

> 2020-08-12-205917_北白川@GUv4i6今日撮った写真なんかカモメがかっこよかった.jpg https://t.co/km7jxzEfDD  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:05／2020/08/12 21:16 URL： https://twitter.com/kk_hirono/status/1293549196390195200 https://twitter.com/s_hirono/status/1293521641557774337  

> 2020-08-12-205826_北白川@GUv4i6娘が「日本で一番偉いのはだれ？」とか聞くようになったので、この本を毎晩2人で少しずつ読み始めました。今のところ娘は楽しい.jpg https://t.co/WPXzI2jZGm  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:05／2020/08/12 21:15 URL： https://twitter.com/kk_hirono/status/1293549209115717632 https://twitter.com/s_hirono/status/1293521568614592513  

> 2020-08-12-205742_北白川@GUv4i6誰だよ笑午後10：52　·　2020年4月26日·Twitter　for　iPhone.jpg https://t.co/5F7Jnk8evp  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:05／2020/08/12 21:01 URL： https://twitter.com/kk_hirono/status/1293549222394884096 https://twitter.com/s_hirono/status/1293518057093046278  

> 2020-08-12-205611_北白川@GUv4i6·5月1日きた以前の笹倉先生の伝聞の説明は好きだったから今号も楽しみ.jpg https://t.co/YghAcpVI6s  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:05／2020/08/12 21:01 URL： https://twitter.com/kk_hirono/status/1293549236886200323 https://twitter.com/s_hirono/status/1293517984317583361  

> 2020-08-12-205520_北白川@GUv4i6·5月1日難解な法律概念みるといっつもおもうけどすごい折り込みだよね.jpg https://t.co/2z3tnql2kU  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:05／2020/08/12 21:01 URL： https://twitter.com/kk_hirono/status/1293549263872385027 https://twitter.com/s_hirono/status/1293517911609315329  

> 2020-08-12-205447_北白川@GUv4i6·5月1日自粛ごはん金曜日バージョン.jpg https://t.co/sIOJlSLuvj  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:05／2020/08/12 21:00 URL： https://twitter.com/kk_hirono/status/1293549286458707968 https://twitter.com/s_hirono/status/1293517838775279620  

> 2020-08-12-205401_北白川@GUv4i6·5月2日ワイ「ガンジーってなにやった人だったかな？」ムッスメ「あの人何にもしてないよ」.jpg https://t.co/uenbKZzwDX  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:06／2020/08/12 21:00 URL： https://twitter.com/kk_hirono/status/1293549300643794950 https://twitter.com/s_hirono/status/1293517765962117120  

> 2020-08-12-205328_北白川@GUv4i6·5月2日わたしたちは、刑務所の門を広げ、花婿が花嫁の部屋に入るように入っていかなくてはならない。.jpg https://t.co/wtdUPww8mA  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:06／2020/08/12 21:00 URL： https://twitter.com/kk_hirono/status/1293549394520715265 https://twitter.com/s_hirono/status/1293517693149044736  

> 2020-08-12-205215_北白川@GUv4i6·5月3日憲法記念日によせて.jpg https://t.co/X36PzYKuL5  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:06／2020/08/12 21:00 URL： https://twitter.com/kk_hirono/status/1293549410106761216 https://twitter.com/s_hirono/status/1293517620289781761  

> 2020-08-12-205132_北白川@GUv4i6·5月4日とにかく邪魔しにくる、おれは井田総論を読みたいんだ。.jpg https://t.co/zjllldKXzi  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:06／2020/08/12 20:59 URL： https://twitter.com/kk_hirono/status/1293549423880855553 https://twitter.com/s_hirono/status/1293517547531198470  

> 2020-08-12-204947_北白川@GUv4i6·5月17日娘とサンフランシスコなう（大嘘.jpg https://t.co/k9NFHtbTc2  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:06／2020/08/12 20:59 URL： https://twitter.com/kk_hirono/status/1293549437839486976 https://twitter.com/s_hirono/status/1293517474453843968  

> 2020-08-12-204918_北白川@GUv4i6·5月17日椅子とビールもってくればよかったぜ。.jpg https://t.co/U41PUx8XtW  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:06／2020/08/12 20:59 URL： https://twitter.com/kk_hirono/status/1293549456348966912 https://twitter.com/s_hirono/status/1293517401665896448  

> 2020-08-12-204815_北白川@GUv4i6·5月22日ファイブになってから買ってなかったので買った.jpg https://t.co/UviaN0uzTc  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:06／2020/08/12 20:58 URL： https://twitter.com/kk_hirono/status/1293549471221964806 https://twitter.com/s_hirono/status/1293517328563363840  

> 2020-08-12-204634_北白川@GUv4i6·5月30日虹捕まえたぜ.jpg https://t.co/3hOvXvnPoh  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:06／2020/08/12 20:58 URL： https://twitter.com/kk_hirono/status/1293549485985894400 https://twitter.com/s_hirono/status/1293517255477665792  

> 2020-08-12-204558_北白川@GUv4i6·5月30日夏のはじまり.jpg https://t.co/auW0gpDLsJ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:06／2020/08/12 20:58 URL： https://twitter.com/kk_hirono/status/1293549502884745216 https://twitter.com/s_hirono/status/1293517182626717697  

> 2020-08-12-204440_北白川@GUv4i6·6月7日天気いいしBBQ前の仕事に洗車する.jpg https://t.co/Ey8ZX474UA  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:06／2020/08/12 20:58 URL： https://twitter.com/kk_hirono/status/1293549518873440261 https://twitter.com/s_hirono/status/1293517109712936961  

> 2020-08-12-204350_北白川@GUv4i6·6月7日なんとなく娘が少しずつギャル化してる気がして心配になる父であった.jpg https://t.co/v9nhSVcENo  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:06／2020/08/12 20:57 URL： https://twitter.com/kk_hirono/status/1293549534203633664 https://twitter.com/s_hirono/status/1293517034332934145  

> 2020-08-12-204305_北白川@GUv4i6·6月13日というわけで最初の目的地、実家である。あいかわらずのどかである。今日は仕事のため妻も子も連れてきていないので.jpg https://t.co/MOAMJvKilc  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:06／2020/08/12 20:57 URL： https://twitter.com/kk_hirono/status/1293549547512188928 https://twitter.com/s_hirono/status/1293516961444270082  

> 2020-08-12-204243_北白川@GUv4i6·6月13日というわけで最初の目的地、実家である。あいかわらずのどかである。今日は仕事のため妻も子も連れてきていないので.jpg https://t.co/v31gznrHb0  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:07／2020/08/12 20:57 URL： https://twitter.com/kk_hirono/status/1293549561525358592 https://twitter.com/s_hirono/status/1293516888362778625  

> 2020-08-12-204130_北白川@GUv4i6·6月15日我が名はアシタカ！ストレッチャーから自力で移動できぬ者でも第三者に指示して証拠隠滅する具体的な可能性ありとし.jpg https://t.co/2Itku9cULY  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:07／2020/08/12 20:56 URL： https://twitter.com/kk_hirono/status/1293549578826862593 https://twitter.com/s_hirono/status/1293516815193108481  

> 2020-08-12-204047_北白川@GUv4i6·6月19日.jpg https://t.co/C0kZpWCKBq  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:07／2020/08/12 20:56 URL： https://twitter.com/kk_hirono/status/1293549592106029056 https://twitter.com/s_hirono/status/1293516742312914947  

> 2020-08-12-204002_北白川@GUv4i6·6月20日迷子記念食事会.jpg https://t.co/3HPWl3ruLE  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:07／2020/08/12 20:56 URL： https://twitter.com/kk_hirono/status/1293549605360041985 https://twitter.com/s_hirono/status/1293516669420150784  

> 2020-08-12-203911_北白川@GUv4i6元来、禊とはヌードなので思考的には正しい気がする者.jpg https://t.co/e1uuV0qMED  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:07／2020/08/12 20:43 URL： https://twitter.com/kk_hirono/status/1293549621818437632 https://twitter.com/s_hirono/status/1293513396218781696  

> 2020-08-12-203830_スゴい発想ですねwww午後3：57　·　2020年6月21日·Twitter　for　Android.jpg https://t.co/CLzqFzvhOC  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:07／2020/08/12 20:43 URL： https://twitter.com/kk_hirono/status/1293549636112662528 https://twitter.com/s_hirono/status/1293513323288248320  

> 2020-08-12-203706_北白川@GUv4i6·6月21日元来、禊とはヌードなので思考的には正しい気がする者.jpg https://t.co/15jjuwfoac  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:07／2020/08/12 20:42 URL： https://twitter.com/kk_hirono/status/1293549652491419650 https://twitter.com/s_hirono/status/1293513250059907072  

> 2020-08-12-203415_北白川@GUv4i6·6月26日今日は久々の出張なので、マエストロの新作映画を楽しみながら.jpg https://t.co/XhVp97LTUh  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:07／2020/08/12 20:42 URL： https://twitter.com/kk_hirono/status/1293549668492693506 https://twitter.com/s_hirono/status/1293513177221615616  

> 2020-08-12-203258_北白川@GUv4i6·6月27日すみっこ付添人弁護士なう.jpg https://t.co/kAMse3fpJi  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:07／2020/08/12 20:42 URL： https://twitter.com/kk_hirono/status/1293549685546737664 https://twitter.com/s_hirono/status/1293513104219713537  

> 2020-08-12-203227_北白川@GUv4i6·6月27日もう剣も天秤も投げ捨てて「ええからおまえら2人ともちょっとそこ座れ！」とブチギレ系の仲裁を始める正義の女神テ.jpg https://t.co/ngczNNvsNF  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:07／2020/08/12 20:41 URL： https://twitter.com/kk_hirono/status/1293549702525280256 https://twitter.com/s_hirono/status/1293513031431806977  

> 2020-08-12-203129_北白川@GUv4i6·7月4日というわけで映画みよ.jpg https://t.co/14fwMDuoE4  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:07／2020/08/12 20:41 URL： https://twitter.com/kk_hirono/status/1293549718920822787 https://twitter.com/s_hirono/status/1293512958627086336  

> 2020-08-12-203034_北白川@GUv4i6·7月4日よし、つぎはこれみんぞ.jpg https://t.co/ikcEmGZRh6  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:07／2020/08/12 20:41 URL： https://twitter.com/kk_hirono/status/1293549732879466497 https://twitter.com/s_hirono/status/1293512884593364992  

> 2020-08-12-203006_北白川@GUv4i6·7月5日これはいい映画だあ.jpg https://t.co/SkhHzAYB0B  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:07／2020/08/12 20:41 URL： https://twitter.com/kk_hirono/status/1293549746716516352 https://twitter.com/s_hirono/status/1293512811742560257  

> 2020-08-12-202936_北白川@GUv4i6·7月10日さあ、パパとママの合同誕生会はじまりはじまり.jpg https://t.co/nMiKd6B3rG  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:07／2020/08/12 20:40 URL： https://twitter.com/kk_hirono/status/1293549761794994176 https://twitter.com/s_hirono/status/1293512739042676736  

> 2020-08-12-202802_北白川@GUv4i6·7月25日鳥「ようきたの、ワレ」.jpg https://t.co/Imy3Ba9PSD  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:07／2020/08/12 20:40 URL： https://twitter.com/kk_hirono/status/1293549778391797766 https://twitter.com/s_hirono/status/1293512666120482817  

> 2020-08-12-202623_”娘ちゃん”　（from：GUv4i6）　-　Twitter検索　／　Twitter.jpg https://t.co/E3O67Mpa34  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:07／2020/08/12 20:40 URL： https://twitter.com/kk_hirono/status/1293549793650737153 https://twitter.com/s_hirono/status/1293512593487720448  

> 2020-08-12-202553_”娘ちゃん”　（from：GUv4i6）　-　Twitter検索　／　Twitter.jpg https://t.co/Dt0CKRBhkf  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:08／2020/08/12 20:39 URL： https://twitter.com/kk_hirono/status/1293549807579983874 https://twitter.com/s_hirono/status/1293512520632696832  

> 2020-08-12-202502_”娘ちゃん”　（from：GUv4i6）　-　Twitter検索　／　Twitter.jpg https://t.co/ihG5O160fe  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:08／2020/08/12 20:39 URL： https://twitter.com/kk_hirono/status/1293549824323678208 https://twitter.com/s_hirono/status/1293512447899262976  

> 2020-08-12-202424_”娘ちゃん”　（from：GUv4i6）　-　Twitter検索　／　Twitter.jpg https://t.co/RR3Vo87Upi  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:08／2020/08/12 20:39 URL： https://twitter.com/kk_hirono/status/1293549853163655168 https://twitter.com/s_hirono/status/1293512374683447302  

> 2020-08-12-202017_北白川@GUv4i6·20時間こんなしちめんどくさいしごと娘にはさせたくないと思うが、じゃあ、他の仕事何がいいかって、大概の仕事は同じくしち.jpg https://t.co/1Y3MET6rBa  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:08／2020/08/12 20:38 URL： https://twitter.com/kk_hirono/status/1293549876865687552 https://twitter.com/s_hirono/status/1293512301744545792  

> 2020-08-12-201917_北白川@GUv4i6·12時間起訴前保釈うらやましいが、日本でやるとしても、弁護人とか保釈金貸す業者とかいろいろ整備必要だろな。一日中裁判所.jpg https://t.co/dzpva9UKLx  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:08／2020/08/12 20:38 URL： https://twitter.com/kk_hirono/status/1293549899187810304 https://twitter.com/s_hirono/status/1293512229011128320  

> 2020-08-12-201746_北白川@GUv4i6·11時間仙台家裁はいろいろいいなあって思うことが多いんだよなあ。所長があの本書いている人だったとかだからなのかな.jpg https://t.co/hLhngvXzJ0  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:08／2020/08/12 20:15 URL： https://twitter.com/kk_hirono/status/1293549914757062657 https://twitter.com/s_hirono/status/1293506420667609093  

> 2020-08-12-201506_固定されたツイート北白川@GUv4i6·4月4日謙虚に生きる２０２０知る者は言わず言う者は知らず自分への戒めである.jpg https://t.co/xJmYFbtkum  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:08／2020/08/12 20:15 URL： https://twitter.com/kk_hirono/status/1293549933648216066 https://twitter.com/s_hirono/status/1293506347732885504  

> 2020-08-12-201332_櫻田山（イケメン）神社　-　Google　マップ.jpg https://t.co/RlZW0hmubR  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:08／2020/08/12 19:34 URL： https://twitter.com/kk_hirono/status/1293549964325347328 https://twitter.com/s_hirono/status/1293496187392159744  

> 2020-08-12-193258_北白川@GUv4i6まあ，ただ，起訴前保釈うらやましすっていうと，検察官の友だちからすかさず「アメリカは無令状逮捕の範囲広いし，現に無令状で.jpg https://t.co/8q45gXdr7z  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:08／2020/08/12 19:34 URL： https://twitter.com/kk_hirono/status/1293549989273034752 https://twitter.com/s_hirono/status/1293496114763579392  

> 2020-08-12-193002_深澤諭史さんがリツイートりっぴぃ@rippy08·48分性犯罪にせよその他類型の犯罪にせよ，「犯罪を許さない」ことと，行為者（と疑われた人）.jpg https://t.co/P5bWYy6iZE  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:08／2020/08/12 19:34 URL： https://twitter.com/kk_hirono/status/1293550008780771328 https://twitter.com/s_hirono/status/1293496041703055361  

> 2020-08-12-181647_東京ミネルヴァ法律事務所破産被害対策全国弁護団　-　被害対策全国弁護団について.jpg https://t.co/VR6FUxnQSg  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:08／2020/08/12 19:34 URL： https://twitter.com/kk_hirono/status/1293550023657975810 https://twitter.com/s_hirono/status/1293495968680173568  

> 2020-08-12-181219_大窪和久@okuboka起訴前勾留は自白を「確保」する人質司法の核になるところなので、法務省は一貫して起訴前勾留での保釈制度の設置には反対し.jpg https://t.co/ofgwPsKPLR  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:08／2020/08/12 19:33 URL： https://twitter.com/kk_hirono/status/1293550040133206016 https://twitter.com/s_hirono/status/1293495895615406080  

> 2020-08-12-181128_モトケン@motoken_tw·8時間＞起訴前保釈運用次第では虚偽自白を量産する恐れがあります。裁判官が客観証拠に基づく証拠隠滅の現実的可能.jpg https://t.co/nr3flK2E4r  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:09／2020/08/12 19:33 URL： https://twitter.com/kk_hirono/status/1293550056327360513 https://twitter.com/s_hirono/status/1293495822961655809  

> 2020-08-12-180554_モトケン@motoken_tw·33分女性に生理があるように男性にも生理がある。射精といいますけどね。女性の生理は本人にとって憂鬱なことにと.jpg https://t.co/fl7sbMszcU  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:09／2020/08/12 19:33 URL： https://twitter.com/kk_hirono/status/1293550081715519488 https://twitter.com/s_hirono/status/1293495750270128128  

> 2020-08-12-180426_深澤諭史さんがリツイート深澤諭史@fukazawas·8月5日たまに、こういう、弁護士全体を逆恨みしているみたいな人には遭遇しますね。相談者.jpg https://t.co/dfrH0aLuEe  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:09／2020/08/12 18:04 URL： https://twitter.com/kk_hirono/status/1293550097817432065 https://twitter.com/s_hirono/status/1293473337541160960  

> 2020-08-12-131548_Windows10.jpg https://t.co/RWgW7bBe2g  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:09／2020/08/12 18:03 URL： https://twitter.com/kk_hirono/status/1293550111138578432 https://twitter.com/s_hirono/status/1293473264593825792  

> 2020-08-12-130721_Windows10.jpg https://t.co/k5xRTHf50J  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:09／2020/08/12 18:03 URL： https://twitter.com/kk_hirono/status/1293550123952123905 https://twitter.com/s_hirono/status/1293473191608774657  

> 2020-08-12-130422_Windows10.jpg https://t.co/JamP6Q5TjS  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:09／2020/08/12 18:03 URL： https://twitter.com/kk_hirono/status/1293550140867846144 https://twitter.com/s_hirono/status/1293473118501998592  

> 2020-08-12-130339_Windows10.jpg https://t.co/xnVQDZvBIE  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:09／2020/08/12 18:03 URL： https://twitter.com/kk_hirono/status/1293550152926375936 https://twitter.com/s_hirono/status/1293473045533716481  

> 2020-08-12-130037_Windows10.jpg https://t.co/549pIXmQ8M  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:09／2020/08/12 18:02 URL： https://twitter.com/kk_hirono/status/1293550167988170753 https://twitter.com/s_hirono/status/1293472972179558400  

> 2020-08-11-225212_Windows10.jpg https://t.co/CVkNT79gBm  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:09／2020/08/12 17:58 URL： https://twitter.com/kk_hirono/status/1293550197453119490 https://twitter.com/s_hirono/status/1293471872873451523  

> 2020-08-12-175728_深澤諭史さんがリツイートすか潮吹きクジラ@suka_t·21時間そおゆうとこだぞ事案パート2.jpg https://t.co/BVfl7uEVEj  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:09／2020/08/12 17:58 URL： https://twitter.com/kk_hirono/status/1293550212338704389 https://twitter.com/s_hirono/status/1293471800110661634  

> 2020-08-12-175637_深澤諭史さんがリツイート古家野　彰平@shoheikoyanolaw·7時間司法試験委員のあくどさを呪うのも　今はやめとけ　今はただ自分が受.jpg https://t.co/50OS8MjPYj  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:09／2020/08/12 17:57 URL： https://twitter.com/kk_hirono/status/1293550241958907904 https://twitter.com/s_hirono/status/1293471726811021312  

> 2020-08-12-175219_深澤諭史さんがリツイートピピピーッ@O59K2dPQH59QEJx·56分話になるかという視点は大事。たとえば、訴訟の終盤に決定的に不利な書.jpg https://t.co/ycPLBLVmdI  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:09／2020/08/12 17:45 URL： https://twitter.com/kk_hirono/status/1293550261634363393 https://twitter.com/s_hirono/status/1293468717435641856  

> 2020-08-12-174450_深澤諭史さんがリツイート白石　資朗@shiraishilo·6分発足当時を見れば明らかなとおり（合格者１０００人見込みのところ６０００人を超.jpg https://t.co/X2tknr6KuD  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:09／2020/08/12 17:45 URL： https://twitter.com/kk_hirono/status/1293550278906490880 https://twitter.com/s_hirono/status/1293468644622516224  

> 2020-08-12-161233_「弁護士、時効までに訴訟せず」　２．５億円求め提訴：朝日新聞デジタル.jpg https://t.co/0EJ5UxROuY  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:09／2020/08/12 17:45 URL： https://twitter.com/kk_hirono/status/1293550298196131841 https://twitter.com/s_hirono/status/1293468571838738432  

> 2020-08-12-145743_無罪のあと、ちゃんとしよう！プロジェクト（田中謙二（無罪のあと、ちゃんとしよう！プロジェクト代表）　2020／07／16　公開）　-　クラウ.jpg https://t.co/XYJ3B38zOn  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:10／2020/08/11 19:31 URL： https://twitter.com/kk_hirono/status/1293550321243795457 https://twitter.com/s_hirono/status/1293132810115407875  

> 2020-08-11-191234_深澤諭史@fukazawas·4時間（；・∀・）今年出した単著３冊、Amazonの在庫が軒並み全滅。。。うち一冊は1ヶ月待ち。。。嬉しさより.jpg https://t.co/Cb7BwtgujH  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:10／2020/08/11 19:30 URL： https://twitter.com/kk_hirono/status/1293550340881575936 https://twitter.com/s_hirono/status/1293132737117790208  

> 2020-08-11-191205_深澤諭史@fukazawas·4時間成年被後見人の親族が「成年後見人がついたせいで，被後見人の財産が自由に使えなくなった！酷い！」っていって.jpg https://t.co/33Suqzj6VK  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:10／2020/08/11 19:30 URL： https://twitter.com/kk_hirono/status/1293550356836659202 https://twitter.com/s_hirono/status/1293132664405295104  

> 2020-08-11-191047_深澤諭史さんがリツイートふて寝べん@hirune_b·4時間被害者支援をされている先生方の一部がどういう世界を望んでいるのかが分からないんで.jpg https://t.co/R7PIuPOQjk  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:10／2020/08/11 19:30 URL： https://twitter.com/kk_hirono/status/1293550375492935681 https://twitter.com/s_hirono/status/1293132591705423873  

> 2020-08-11-132035_Shin　Horiさんがリツイートふて寝べん@hirune_b·7月29日以前に法教育で高校を訪ねた際、「黙秘権や国選弁護士を付ける権利は、.jpg https://t.co/4APk4rX733  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:10／2020/08/11 19:29 URL： https://twitter.com/kk_hirono/status/1293550393251618817 https://twitter.com/s_hirono/status/1293132518695133185  

> 2020-08-11-123042_深澤諭史さんがリツイートなべきょう＠過眠症@wata_nabekyo_ko·9時間まったく同感なのです。別に弁護士は離婚をけしかけたりしない.jpg https://t.co/c1ZE0LXu0w  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:10／2020/08/11 19:29 URL： https://twitter.com/kk_hirono/status/1293550419017207808 https://twitter.com/s_hirono/status/1293132445819129863  

> 2020-08-11-122835_深澤諭史@fukazawas·46分「ネットｄｅ真実　法律情報版」に騙されないためには，その情報提供の仕方，文言が，感情的でないかは，一つの.jpg https://t.co/NRnku5wU3l  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:10／2020/08/11 19:29 URL： https://twitter.com/kk_hirono/status/1293550433500196864 https://twitter.com/s_hirono/status/1293132372980817920  

> 2020-08-11-122527_深澤諭史さんがリツイートShin　Hori@ShinHori1·3時間＃日本沈没この漫画版のセリフは、ほぼ原作そのまま。1970年代、東南ア.jpg https://t.co/HWXc43U2iW  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:10／2020/08/11 19:29 URL： https://twitter.com/kk_hirono/status/1293550453221810176 https://twitter.com/s_hirono/status/1293132300205486082  

> 2020-08-11-121712_弁護士　亀石倫子さんがリツイート￼郷原信郎【「深層」カルロス・ゴーンとの対話　起訴されれば９９％超が有罪となる国で】·8月4日【アナザースト.jpg https://t.co/cFXelJc8K0  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:10／2020/08/11 19:28 URL： https://twitter.com/kk_hirono/status/1293550477427146753 https://twitter.com/s_hirono/status/1293132227476254730  

> 2020-08-11-093706_嶋﨑量（弁護士）さんがリツイートささきりょう@ssk_ryo·2時間著名刑事弁護士の反対尋問について考えたこと（AV事業者との裁判）｜伊藤和.jpg https://t.co/NykmTQ5zGK  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:10／2020/08/11 19:28 URL： https://twitter.com/kk_hirono/status/1293550500206575617 https://twitter.com/s_hirono/status/1293132154948317184  

> 2020-08-11-093648_AV事業者側の代理人についているのは、カルロス・ゴーンの弁護人などを務めた高野隆弁護士、および同じ事務所の弁護士です。高野弁護士は著名で優秀.jpg https://t.co/0UTpft9zjO  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-12 23:10／2020/08/11 19:28 URL： https://twitter.com/kk_hirono/status/1293550534733905920 https://twitter.com/s_hirono/status/1293132082223304704  

> 2020-08-11-063337_深澤諭史@fukazawas（；・∀・）もう、大勢の人が指摘していますが、こういうメッセージ出すときは、絶対に、弁護士に相談してからがいいで.jpg https://t.co/jLbK1m3FVR  

　上記のスクリーンショット分で144件となっていました。これだけ連投が多いのも初めてかもしれません。テレビを付けて，みたい番組がなかったので，ずいぶん久しぶりにローカル番組にチャンネルを変えました。前回みたときは，ぶるぞんちえみが出演していたように思います。

　石川県に50年以上住んできて，鹿島の森というのを初めて知りました。石川県では能登地方の中能登町に鹿島というアルプラザ鹿島もある商業地があるのですが，大聖寺川の河口で福井県と石川県の県境に鹿島の森があると知りました。

　この鹿島の森の場面では，ゲストで出演しているのが日曜日のお昼のアッコにおまかせ！という番組で，たぶんレギュラー出演している関西の芸人と思っていました。森から出てきた湖畔のような場面でした。

アッコにおまかせ! - Wikipedia https://t.co/4K019VmRxJ!

ますだおかだ - Wikipedia https://t.co/EtTPdnyher

ますだおかだ ｜松竹芸能株式会社 https://t.co/BLXGj5jShl

　名前をみてもわかるかどうか心もとなかったのですが，どうも二人の漫才コンビらしくこれは初めて知ったような気がします。いわゆるピン芸人と思っていました。

　大聖寺川沿いのお店で，洋風のお菓子を食べている場面で，ようやく狩野英孝だとわかったのですが，テレビで姿をみたのもずいぶん久しぶりだと思いました。数年前，女性問題でもよくテレビの芸能ニュースになっていましたが，宮城県北部の神社が実家ということも印象に残っていました。

　テレビの番組では，石川県の福井県境に近い富士ドライブインの映像が出てきたのですが，この食堂は，長距離トラック運転手の仕事で，妻子と店に入って食事をした思い出としては，他にもあったはずなのですが，最後の方にアルバムの写真のように記憶に残る食堂でした。

　そのお店の紹介で，最初に出てきたのが「とり野菜」，石川県のソウルフードとしてケンミンショーでも紹介されていましたが，市販のものはかなり多くの水を使うという説明書きになっています。

　この「とり野菜の」の本場というか発祥は，石川県でも河北郡の七塚町か高松町辺り，この2町と宇ノ気町が合併し現在はかほく市となっています。その高松町辺りの国道沿いの店に入って，一度，とり野菜を食べたのですが，店の人が水を使わずにその場で調理していたのが印象的でした。

　今回もそれと同じとり野菜の作り方を紹介していたのですが，自家製の味噌のように紹介されていました。加賀市で味噌というのは聞いたことがなかったのですが，加賀市の橋立港，金沢市の大野町，かほく市というのは北前船の歴史で共通があり，大野町は醤油が有名です。

　この前，山中温泉殺人事件のこともあり，潮津町から大聖寺は10キロ近く離れていると知りました。潮津神社は前妻と結婚式を昭和61年3月に挙げた神社でもありましたが，前妻の家の近くで，かなり大きな神社でした。小さい娘だった頃は，七五三のお祝いなどしていたのかと思いを巡らせました。

　ちょうどそのタイミングで見かけたのが，北白川というTwitterアカウントのツイートで，娘ちゃんというツイートを思い出すとともに，七五三の写真を見たように思い出しました。きっかけがどこのタイムラインであったのか思い出せなくなっています。

　Twitterのタイムラインでメディアを選択し，タイムラインを最後まで読み込んだのですが，七五三の写真は見つかりませんでした。そこで七五三というキーワードが頭に浮かび，そのままTwitter検索を実行したところ写真のツイートが出てきたのです。

　Twitter検索の精度がここまで悪いのかと思いながら，まるでコックリさんの怪奇現象のようにも思えました。Twitterの扱う情報量は想像を超えて膨大なはずで，エラーがご操作がでないのばむしろ不思議と考えることもありました。

　私の告発事件は，21歳で健康な体を私の暴力行為によって失った被害者安藤文さんと，被害者安藤文さんを娘とする父親の安藤健次郎さんの人生を紡ぐ物語でもあります。そこに介在した弁護士の狂った欲望，泥棒根性を私は家内安全と子孫繁栄を祈願とする奉納として記録作成しております。

@GUv4i6 ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@GUv4i6）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW GUv4i6（北白川） 日時：2019/11/24 10:11 URL： https://twitter.com/GUv4i6/status/1198408697782792192  

> 昨日、無事、七五三を終えたので今日は、すみっこぐらしみたら帰りますね https://t.co/L3aptLE1Ds  

　大きな回り道をしてようやく探し出した北白川という弁護士アカウントの七五三のツイートですが，今年の2月頃のツイートとばかり思っていました。七五三というのは3つの年齢で年に3回あるという思いがあり，最初の3歳が初春の2月という漠然としたイメージがありました。

　ツイートは昨年2019年の11月24日で，今，そういえば七五三というのは11月頃とテレビでみたことを思い出しました。ようやく探し出した写真をみて，イメージとして脳裡に残っているものとは違った印象があり，今見たものは小奇麗な飲食店の店内に見えます。

　イメージとして脳裡にあったのは，寺院の通路のような情景で，小さい頃にどこかでみた風景とも重なるものがあり，それに近いと思ったのは，もう8,9年前になると思いますが，小中学生の遠足以来に行ったと思う，現在は輪島市となっている門前町の總持寺祖院の通路でした。

〈〈〈：Linux Emacs： 2020-08-12（水曜日）23：53 　〈〈〈

