* 「検事も逆恨みを買うから大変ですね。盗撮とのことですが，性犯罪，ストーカー系は，そうなる割合を高く感じます。」という深澤諭史弁護士のツイート
  :LOGBOOK:
  CLOCK: [2020-08-19 水 17:33]--[2020-08-19 水 17:38] =>  0:05
  :END:

:CATEGORIES: 深澤諭史弁護士,ストーカー

〉〉〉：Emacs： 2020-08-19（水曜日）17：33　 〉〉〉

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2020/08/19 16:19 URL： https://twitter.com/fukazawas/status/1295983800787144705  

> 元担当検事らに「死刑」「復讐しにいく」…地検ＨＰの意見・要望欄に : 社会 : ニュース : 読売新聞オンライン https://t.co/vpEKb2degC   
> 検事も逆恨みを買うから大変ですね。盗撮とのことですが，性犯罪，ストーカー系は，そうなる割合を高く感じます。  

```
2020/08/19 15：17
　検事らを脅迫したとして、脅迫罪に問われた三重県亀山市、アルバイト従業員の男（２８）に対し、津地裁は１８日、懲役１年２月（求刑・懲役２年６月）の実刑判決を言い渡した。四宮知彦裁判官は「あまり類をみない悪質性の高い類型の脅迫事件であり、刑事責任は相応に重いというべきである」などと量刑理由を述べた。

［source：］元担当検事らに「死刑」「復讐しにいく」…地検ＨＰの意見・要望欄に ： 社会 ： ニュース ： 読売新聞オンライン https://www.yomiuri.co.jp/national/20200819-OYT1T50136/
```

　弁護士が原因で検事が恨みを買う，というケースもけっこうありそうな気がします。あるいは，弁護士が示唆するかたちで検事を悪者に印象づけるということもありそうです。このツイートは，これまでの深澤諭史弁護士の物の見方，考えがよく現れています。

〈〈〈：Emacs： 2020-08-19（水曜日）17：38 　〈〈〈

* 南満州鉄道あじあ号と，深澤諭史弁護士と被告発人弁護士らについて考える弁護士鉄道の歴史と将来
  :LOGBOOK:
  CLOCK: [2020-08-19 水 19:50]
  CLOCK: [2020-08-19 水 17:47]--[2020-08-19 水 18:40] =>  0:53
  :END:

:CATEGORIES: 深澤諭史弁護士,被告発人木梨松嗣弁護士

〉〉〉：Emacs： 2020-08-19（水曜日）17：47　 〉〉〉

　昨夜になりますが，ふと思うところがあって，YouTubeで宇出津のあばれ祭りの動画を視聴し，次の動画の一覧から阿波おどり，そして南満州鉄道のあじあ号の記録映像の動画が出てきました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:50／2020/08/18 20:58 URL： https://twitter.com/kk_hirono/status/1296006731990880256 https://twitter.com/hirono_hideki/status/1295691530527629312  

> 4k あばれ祭り2019キリコ最終日 Abare festival - YouTube https://t.co/AzjqJyigFy  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:51／2020/08/18 21:45 URL： https://twitter.com/kk_hirono/status/1296006741902073856 https://twitter.com/hirono_hideki/status/1295703322788208640  

> 【散策物語】 あばれ祭り「キリコ編」2019　～石川県能登町～　"The Abare Festival 2019 of Kiriko Part" - YouTube https://t.co/xGFDajdk4X  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:51／2020/08/18 21:51 URL： https://twitter.com/kk_hirono/status/1296006753981587457 https://twitter.com/hirono_hideki/status/1295704757714030598  

> 阿波おどりファン必見！みんなが観たかった、みんなで踊る阿波おどり！阿波おどり振興協会・総踊り2018！ Awaodori in Tokushima Japan - YouTube https://t.co/NdA7dM8793  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:51／2020/08/18 22:10 URL： https://twitter.com/kk_hirono/status/1296006768183500801 https://twitter.com/hirono_hideki/status/1295709704451047424  

> 阿波おどりファン必見！総踊り4Kフルバージョン！踊り子さんの笑顔がすてき！徳島市阿波おどり2017初日総踊り！！ Awaodori in Tokushima Japan - YouTube https://t.co/2uQVyejgvz  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:51／2020/08/18 22:21 URL： https://twitter.com/kk_hirono/status/1296006783262048257 https://twitter.com/hirono_hideki/status/1295712372645076992  

> 南滿洲鐵道 特急亞細亞號（ あじあ号）特快列車之旅 日本紀錄片 - YouTube https://t.co/3Ccwt9XVdn  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:51／2020/08/19 00:14 URL： https://twitter.com/kk_hirono/status/1296006886848778241 https://twitter.com/hirono_hideki/status/1295740850392035328  

> 『2020年08月18日のつぶやき』MakeMyDay｜https://t.co/6EnWPmAZj1  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:51／2020/08/19 08:08 URL： https://twitter.com/kk_hirono/status/1296006986857775107 https://twitter.com/hirono_hideki/status/1295860235148484608  

> 2020年08月18日20時18分の登録： ＼深澤諭史　@fukazawas＼提訴には時間かかるので、通知とほぼ同時に提訴をするという迅速進行。 手間はかかるけれどもなぁ・・・。 https://t.co/YlaEWkcKXB  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:52／2020/08/19 08:08 URL： https://twitter.com/kk_hirono/status/1296006995384758272 https://twitter.com/hirono_hideki/status/1295860261547470848  

> 2020年08月18日20時26分の登録： REGEXP：”モラ夫”／深澤諭史（@fukazawas）の検索（2017-04-14〜2020-06-27／2020年08月18日20時26分の記録18件） https://t.co/tPzt09KTAD  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:52／2020/08/19 08:09 URL： https://twitter.com/kk_hirono/status/1296007003605622787 https://twitter.com/hirono_hideki/status/1295860288160280577  

> 2020年08月19日08時06分の登録： ツイートの記録資料：＼法務検察・石川県警察宛＼／モトケン（@motoken_tw）／”2020年08月18日”：34件 https://t.co/wBXJBpYyQi  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:52／2020/08/19 08:09 URL： https://twitter.com/kk_hirono/status/1296007013718085632 https://twitter.com/hirono_hideki/status/1295860314542505984  

> 2020年08月19日08時07分の登録： ツイートの記録資料：＼法務検察・石川県警察宛＼／深澤諭史（@fukazawas）／”2020年08月18日”：55件 https://t.co/gUR0FVXM5U  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:52／2020/08/19 08:48 URL： https://twitter.com/kk_hirono/status/1296007030994395136 https://twitter.com/hirono_hideki/status/1295870201230012416  

> 南滿洲鐵道 特急亞細亞號（ あじあ号）特快列車之旅 日本紀錄片 - YouTube https://t.co/3Ccwt9GjON  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:52／2020/08/19 09:02 URL： https://twitter.com/kk_hirono/status/1296007044168785920 https://twitter.com/hirono_hideki/status/1295873761812463616  

> 娘々祭り - Google 検索 https://t.co/BjofN9ddyO  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:52／2020/08/19 09:05 URL： https://twitter.com/kk_hirono/status/1296007057158443008 https://twitter.com/hirono_hideki/status/1295874391843041280  

> 満洲祭り　夏目芙美子 - YouTube https://t.co/NyTsBMSXmd  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:52／2020/08/19 09:06 URL： https://twitter.com/kk_hirono/status/1296007072920682496 https://twitter.com/hirono_hideki/status/1295874807481868288  

> 「々」はなんて読む？　“文字”をもっと知るための雑学3つ - ねとらぼ https://t.co/x5l5kxPKsE  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:52／2020/08/19 09:07 URL： https://twitter.com/kk_hirono/status/1296007090746478593 https://twitter.com/hirono_hideki/status/1295875108913856512  

> 娘娘饅頭 - 加賀市のお土産・名菓なら｜娘娘万頭の山中石川屋 https://t.co/FRFvF3qrJd  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:52／2020/08/19 09:16 URL： https://twitter.com/kk_hirono/status/1296007099214729216 https://twitter.com/hirono_hideki/status/1295877162419884032  

> 満州写真館　大石橋娘娘祭 https://t.co/GzNhIWMPP3  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜nhk_news（NHKニュース） 日時：2020-08-19 17:52／2020/08/18 19:26 URL： https://twitter.com/kk_hirono/status/1296007146291699712 https://twitter.com/nhk_news/status/1295668270977048582  

> コロナ重症者数が増加傾向 大阪は東京の2倍以上 その理由とは #nhk_news https://t.co/8si8oB0Y0f  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:52／2020/08/19 10:02 URL： https://twitter.com/kk_hirono/status/1296007164960493569 https://twitter.com/hirono_hideki/status/1295888854495330304  

> 南満州鉄道パシナ型蒸気機関車 - Wikiwand https://t.co/0edjbkTBRs 南満州鉄道が設計製造した蒸気機関車。その流線型のフォルムから満鉄もしくは満州国のあじあ号の看板となり新幹線の土台ともなったが同時に中国などの国々から侵略のプロパガンダと見なされた負の面もある。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:52／2020/08/19 10:06 URL： https://twitter.com/kk_hirono/status/1296007204319817728 https://twitter.com/hirono_hideki/status/1295889797718740992  

> あじあ (列車) - Wikiwand https://t.co/eKITe8IvmD  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:52／2020/08/19 10:51 URL： https://twitter.com/kk_hirono/status/1296007222669881344 https://twitter.com/hirono_hideki/status/1295901148012875776  

> 2020年08月19日10時50分の実行記録 APIのリミットに達するので8500で処理と中断しました。 twitterAPI-search-lawList-mydql-add.rb "満州" ツイート数：4/1957 リツイート数：7/1957 トータル：8500 hirono_hideki 2／0件 kk_hirono 0／0件 s_hirono 0／0件  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜BloombergJapan（ブルームバーグニュース日本語版） 日時：2020-08-19 17:53／2020/08/19 09:17 URL： https://twitter.com/kk_hirono/status/1296007261261713408 https://twitter.com/BloombergJapan/status/1295877593896562689  

> 出前館、ウーバーイーツの買収検討報道は事実無根 https://t.co/ioyuG167Xi  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:53／2020/08/19 10:55 URL： https://twitter.com/kk_hirono/status/1296007276822634496 https://twitter.com/hirono_hideki/status/1295902167081971713  

> アカシア - Google 検索 https://t.co/wtcTg1fbnQ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:53／2020/08/19 10:56 URL： https://twitter.com/kk_hirono/status/1296007287270563840 https://twitter.com/hirono_hideki/status/1295902472498581504  

> アカシア　並木 - Google 検索 https://t.co/hgejhdCjLY  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:53／2020/08/19 10:58 URL： https://twitter.com/kk_hirono/status/1296007295592144899 https://twitter.com/hirono_hideki/status/1295902879950106624  

> ライラック　並木 - Google 検索 https://t.co/7alqiRpKT0  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:53／2020/08/19 11:13 URL： https://twitter.com/kk_hirono/status/1296007323379351553 https://twitter.com/hirono_hideki/status/1295906585219235840  

> 2020年08月19日11時07分の実行記録 twitterAPI-search-lawList-mydql-add.rb "法を身近に 泣き寝入りなくす" ツイート数：14/1958 リツイート数：10/1958 トータル：110 hirono_hideki 1／0件 kk_hirono 6／1件 s_hirono 0／0件  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:53／2020/08/19 11:14 URL： https://twitter.com/kk_hirono/status/1296007367453102081 https://twitter.com/hirono_hideki/status/1295907000392413184  

> 2020年08月19日08時08分の登録： 2020-08-18の投稿一覧＼検察・石川県警察宛記録資料＼奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中：38件 https://t.co/crS2OhG0ys  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:53／2020/08/19 11:14 URL： https://twitter.com/kk_hirono/status/1296007375451693056 https://twitter.com/hirono_hideki/status/1295907026703249408  

> 2020年08月19日08時17分の登録： ＼深澤諭史　@fukazawas＼今年出した単著３冊，いずれもＡｍａｚｏｎで品切れ・・・。一部はプレミア・・・。 うれしいという気持ちよりも，申し訳ないという気持ちが・・ https://t.co/TovWBAHMl7  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:53／2020/08/19 11:14 URL： https://twitter.com/kk_hirono/status/1296007388424617986 https://twitter.com/hirono_hideki/status/1295907053072814080  

> 2020年08月19日08時35分の登録： ＼モトケン　@motoken_tw＼行為が、被害者がこれまで積み重ねた努力と費やした時間に対する加害だということを理解してもらえればそれで結構です。 https://t.co/O1PFOufpIZ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:53／2020/08/19 11:14 URL： https://twitter.com/kk_hirono/status/1296007401682825216 https://twitter.com/hirono_hideki/status/1295907079450849280  

> 2020年08月19日10時54分の登録： REGEXP：”満州”／データベース登録済みツイート：2020年08月19日10時53分の記録：ユーザ・投稿：33／52件 https://t.co/OJMlTE5MSD  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:53／2020/08/19 11:15 URL： https://twitter.com/kk_hirono/status/1296007430896144385 https://twitter.com/hirono_hideki/status/1295907105820438528  

> 2020年08月19日11時01分の登録： ＼滝沢亮 Ryo Takizawa　@Ryo_Sanjo＼修習の同期、闇に舞い降りた天才です！  法を身近に、泣き寝入りなくす　弁護士費用を立て替え：日本経済新聞 https://t.co/HvOc37RWqX  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:53／2020/08/19 11:15 URL： https://twitter.com/kk_hirono/status/1296007449166544896 https://twitter.com/hirono_hideki/status/1295907132177432576  

> 2020年08月19日11時03分の登録： ＼法テラ弁　@9L1ZTxR8630irXW＼1回も返済してないのに、過払金請求できませんか？と法律相談に来た人は知ってます。 https://t.co/ioQa5qWecd  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:53／2020/08/19 11:15 URL： https://twitter.com/kk_hirono/status/1296007464358297600 https://twitter.com/hirono_hideki/status/1295907158542831616  

> 2020年08月19日11時07分の登録： ＼深澤諭史　@fukazawas＼（・∀・）まかり間違ってもそういう人の相談、事件は受けたくないので、そう言ってもらえると助かりますね。 https://t.co/MUXBifmYFL  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:53／2020/08/19 11:15 URL： https://twitter.com/kk_hirono/status/1296007482389590016 https://twitter.com/hirono_hideki/status/1295907184929169410  

> 2020年08月19日11時08分の登録： ＼大窪和久　@okuboka＼確実にやって成果がでるのでなければ法律相談に金を払いたくないという方については相談を受けようがないですので… https://t.co/I0d3vYHymF  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:54／2020/08/19 11:15 URL： https://twitter.com/kk_hirono/status/1296007498638323713 https://twitter.com/hirono_hideki/status/1295907211319709696  

> 2020年08月19日11時14分の登録： REGEXP：”法を身近に．＊泣き寝入りなくす”／データベース登録済みツイート：2020年08月19日11時13分の記録：ユーザ・投稿：11／24件 https://t.co/SNvTm89B6k  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:54／2020/08/19 11:46 URL： https://twitter.com/kk_hirono/status/1296007534919131136 https://twitter.com/hirono_hideki/status/1295915049618305024  

> rsyncしても一部ファイルが同期されない | TECHSCORE BLOG https://t.co/oxWvvsPaQX  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:54／2020/08/19 12:51 URL： https://twitter.com/kk_hirono/status/1296007549062242304 https://twitter.com/hirono_hideki/status/1295931365465001985  

> 女子大生「LINEの返信」で事故か　42歳会社員死亡　福岡（フジテレビ系（FNN）） - Yahoo!ニュース https://t.co/I2QOvQH2fN  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜mamemamemamec2（まめちゃん） 日時：2020-08-19 17:54／2020/08/19 12:03 URL： https://twitter.com/kk_hirono/status/1296007585863053312 https://twitter.com/mamemamemamec2/status/1295919344396800000  

> 統合失調症の人が知り合いにいるんだけど、本当に初めは何を言っているのか分からなくて黙って聞いてると真剣に自分が狙われていると詳細に説明してくれる。しかし内容が馬鹿げているから初めは冗談なのかと思うと顔は真剣なので、マジか？って本当に驚いた。この人がとうとう統合失調症に？って  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:54／2020/08/19 13:48 URL： https://twitter.com/kk_hirono/status/1296007601021304833 https://twitter.com/hirono_hideki/status/1295945831908929536  

> - 806：2020-08-19_13:48:57 ア.平成4年1月21日の夜中2時頃に被害者安藤文さんの自宅に掛けた電話 https://t.co/d4RH5UkQF7  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:54／2020/08/19 13:54 URL： https://twitter.com/kk_hirono/status/1296007615311298560 https://twitter.com/hirono_hideki/status/1295947314402476039  

> - 807：2020-08-19_13:54:53 (ア). 夜中2時頃の電話の目撃者は，被告発人東渡好信の紹介で入社した七尾のMさん https://t.co/bs1KDvjiA3  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:54／2020/08/19 15:15 URL： https://twitter.com/kk_hirono/status/1296007630670843906 https://twitter.com/hirono_hideki/status/1295967522592681984  

> - 808：2020-08-19_15:15:10 (イ). 夜中2時頃の電話に，すぐに出た被害者安藤文さん，「殺せ，明日会社行ったら殺されてやるわい」と返す https://t.co/DxsiOi1KB4  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:54／2020/08/19 15:15 URL： https://twitter.com/kk_hirono/status/1296007647028637696 https://twitter.com/hirono_hideki/status/1295967680898293760  

> - 809：2020-08-19_15:15:47 (ウ). 平成4年1月22日，手に大きなハサミを持つ私に，二階の窓からにらみつけ，呼んだらすぐに降りてくる勢いをみせた被害者安藤文さん https://t.co/m2lgfYHLij  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:54／2020/08/19 16:11 URL： https://twitter.com/kk_hirono/status/1296007675264696321 https://twitter.com/hirono_hideki/status/1295981597817049088  

> - 810：2020-08-19_16:11:05 ア.平成4年1月21日の夕方，大型ウィング車3016号での，被害者安藤文さんとの会見 https://t.co/6OPEYMDIBc  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:54／2020/08/19 16:39 URL： https://twitter.com/kk_hirono/status/1296007703181967360 https://twitter.com/hirono_hideki/status/1295988785109377025  

> (7) 展示物火災死亡事件 元大学生ら無罪主張 東京地裁 / Twitter https://t.co/mdGdkLHymA  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-19 17:54／2020/08/19 17:39 URL： https://twitter.com/kk_hirono/status/1296007725223051264 https://twitter.com/hirono_hideki/status/1296003753405902848  

> - 811：2020-08-19_17:39:00 ＊ 「検事も逆恨みを買うから大変ですね。盗撮とのことですが，性犯罪，ストーカー系は，そうなる割合を高く感じます。」という深澤諭史弁護士のツイート https://t.co/vAZxkMOVev  

　昨夜からの奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)でのツイート・リツイートを全て，再捜査要請書＿警察庁・石川県警察御中（@kk_hirono）でリツイートしました。44件です。

　Windows10の一太郎で告発状の作成をしましたが，8月15日以来だと確認しました。はてなブログで，記事の見出しの先頭に「ア」とか「（ア）」とあるのが，それになります。カッコ付きでないものが見出しレベルの4，カッコ付きのものが見出しレベルの５になります。

　昨夜はいつの間にか横になったまま寝ていて，目が覚めたのが夜中の3時頃でした。今，スマホで撮影した写真で確認したのですが，3時10分に，マッサージ器のテレビショッピングの画面を撮影した写真が1つありました。

　朝起きてから，パソコンでブラウザをみると「南滿洲鐵道 特急亞細亞號（ あじあ号）特快列車之旅 日本紀錄片」というYouTube動画が開かれていて，不思議に思ったのですが，再生を始めると途中まで視聴していたことを思い出しました。

　このYouTubeの動画を視聴しながら少し横になったところでそのまま眠っていたようです。動画のツイートの時刻をみると，午後10時21分となっています。再生時間が52分32秒の動画です。再生から10分から20分の間で寝ていたようです。

　記憶がぼんやりしているので，それも夢のようなのですが，朝に動画を最初から視聴しながら，完全に見ていないと思ったのが「娘々祭り」でした。これは見るのも聞くのも初めてでしたが，娘々饅頭というのは，石川県の山中温泉の名物だと，テレビを観て知っていました。

　「娘々祭り」は「にゃんにゃんまつり」と読むそうです。昭和から平成になる前後，若い女の子を集めたおニャン子クラブが出てきて，社会現象になっていましたが，男女の性行為を「にゃんにゃん」という隠語のようなものもあった気がします。

　満州についてはいくつか本を読んで，知っていることもあります。満州は満州族とも呼ばれる女真族で，中国の最後の王朝となった清朝が，女真族の愛新覚羅ヌルハチによる建国となっているかと思います。本では，女真族の女性は自分の尿で顔を洗う風習があると読んだこともありました。

　満州といえば，日本の関東軍の駐留からソ連軍の侵攻により大きな悲劇にもなったと聞きます。2日ほど前にも深澤諭史弁護士のタイムラインで，満州がツイートにあるものを見かけていました。深澤諭史弁護士がリツイートしたツイートの引用リツイートだったかもしれません。

　今なら深澤諭史弁護士のTwitterタイムラインからも探し出せそうです。

　見つけることができたのですが，見かけない一般の匿名アカウントのツイートの引用リツイートのようなものとして見たと思っていたのが，モトケンこと矢部善朗弁護士（京都弁護士会）とも関わりのある匿名弁護士のツイートでした。それも8月15日のツイートでした。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜obpmb3fN93mQI9i（大阪名物パチパチ弁護士） 日時：2020-08-19 18:33／2020/08/15 07:18 URL： https://twitter.com/kk_hirono/status/1296017432801193985 https://twitter.com/obpmb3fN93mQI9i/status/1294397954816536576  

> 終戦記念日やし、なぜ日本が戦争することになったのか、一言で述べる。  現預金が足りんかったからや。  やし、満州や中国、東南アジアの利権を求め、他国と衝突し、どうしようもなくなったんや。  みんな頑張って働いて税金納めて財政赤字を減らし経済を安定させることが、戦争回避の方法やと思うわ。  

　深澤諭史弁護士のリツイートの方も探してみます。

```
➜  ~ tu fukazawas 200 2 |grep -B 1 '満州'
RT fukazawas（深澤諭史）｜obpmb3fN93mQI9i（大阪名物パチパチ弁護士） 日時：2020-08-15 09:16／2020-08-15 07:18 URL： https://twitter.com/fukazawas/status/1294427591101657088 https://twitter.com/obpmb3fN93mQI9i/status/1294397954816536576
> 終戦記念日やし、なぜ日本が戦争することになったのか、一言で述べる。 \n  \n 現預金が足りんかったからや。 \n  \n やし、満州や中国、東南アジアの利権を求め、他国と衝突し、どうしようもなくなったんや。 \n  \n みんな頑張って働いて税金納めて財政赤字を減らし経済を安定させることが、戦争回避の方法やと思うわ。
```

　この深澤諭史弁護士のリツイートにある現預金ですが，最近，深澤諭史弁護士のタイムラインでよく見かけていたワードで，健全な精神が宿る，というような組み合わせになっていたと思います。

〈〈〈：Emacs： 2020-08-19（水曜日）18：40 　〈〈〈

〉〉〉：Emacs： 2020-08-19（水曜日）19：50　 〉〉〉

@k_sawmen ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@k_sawmen）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW k_sawmen（泥濘大魔王サイケ） 日時：2020/08/15 08:04 URL： https://twitter.com/k_sawmen/status/1294409710804692992  

> ツイッターの弁護士は、司法試験受験生には甘く、弁護士には厳しい傾向あると思う。これは、受験生は何の地位もない弱者であるのに対し、弁護士になると国家資格持ちの強者になることからかと思われるが、いささか極端な例も見受けられる。  

@kamatatylaw ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@kamatatylaw）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW kamatatylaw（高橋雄一郎） 日時：2020/08/15 07:37 URL： https://twitter.com/kamatatylaw/status/1294402792468041729  

> 弁護士は嫌われることに慣れなければいけないよ。紛争の渦中に入り込んで相手方の憎悪を一身に浴び，事案によってはクライアントにも譲歩させなければならないので両方から憎悪を浴びる。罵声を浴び暴言を吐かれ人格攻撃にさらされ報酬をもらう。人から好かれたいなんて甘い考えは忘れるべきだよ。  

　宇出津新港で買い物をして戻り，パソコンの画面に戻ったところで，深澤諭史弁護士のタイムラインで，満州のリツイートの下に，2つ並んだリツイートの内容が気になり，それもリツイートを試みました。いずれもだいぶん前からブロックされているアカウントです。

　泥濘大魔王サイケというプロフィールの名前のアカウントは，最初に見たのも深澤諭史弁護士のタイムラインだったと思いますが，泥濘が泥棒に見ていました。「ぬかるみ」と読めることは，だいぶん後になって調べて知ったことです。

　泥濘大魔王サイケというプロフィールの名前のアカウントは，泥棒という漢字ではないと知った頃から，これは中国の遼寧省と同じ漢字のように思っていたのですが，今変換すると違っていたようです。遼寧省がどこにあるのか確認していませんが，満州の旅順辺りというイメージがあります。

遼寧省 - Google マップ https://t.co/JGYaFFqvjn

　どんぴしゃ以上に，当たっていたようですが，中国の漢字で表記されているようです。遼寧省の隣になりますが，通化市というこれは見覚えのある地名があって，その隣に白山市が見えます。石川県の白山市と同じ漢字になりますが，これは初めての発見になりそうです。

遼寧省地図 - 旅行のとも、ZenTech https://t.co/YPQAkooh9b

　日本語の漢字で表記した中国の地図がなかなか見つからなかったのですが，上記のページで，遼寧省の北隣が聞いたことのある吉林省だとわかりました。少なくとも，この遼寧省と吉林省が旧満州になるようです。今朝見た動画では満州里まで満州鉄道の支線があったようです。

　もう一つの深澤諭史弁護士のリツイートの高橋雄一郎弁護士も，ツイートを読んでいると考え方が，戦前の旧日本軍の青年将校に似ているように感じていました。深澤諭史弁護士と並ぶ，弁護士鉄道の牽引車のようでもあります。他にも北周士弁護士などがそうそうと並んでいます。

　人間の顔をつけた機関車トーマスというアニメのようでもありますが，今日初めてあじあ号に，パシナという別の言葉があったことを知りました。あじあ号を牽引する蒸気機関車の部分が，そのパシナになるようです。古いのか新しいのかよくわからない初めて知る言葉でした。

　満州国といえば，山形県鶴岡市出身の軍人，石原莞爾のことも思い出します。mozcで変換候補が出ず，検索結果のコピペを単語入力に入れたところ，読みに自動で「いしわらかんじ」と出てきたので，ちょっと驚きました。検索結果の要約を見ると，それが正しい名前の読みのようです。

　石原莞爾のことは漫画で知りました。平成に入った頃と思います。自信はないですがヤングジャンプの可能性が高いと考えています。漫画のタイトルは全く記憶にないのですが，同じ頃，同じような週刊誌で，新選組の清川八郎と芹沢鴨のことを知りました。どちらもずいぶんエグく描かれていました。

　石原莞爾は東條英機と対立したことでも知られていますが，その週刊誌を読んだのと同じ頃，レンタルビデオ店で借りてきた東京裁判のドキュメンタリー記録を観たところ，処刑される寸前までの映像があって，それが堂々といさぎよく，とても印象に残っています。

　東京裁判の法廷の映像もあり，大川周明に後ろからハゲ頭をこづかれる場面があって，振り返ってにっこり笑ったのも印象的で，その法廷を見守る母や娘の様子というのも目に焼き付いていて，大切に思う身内が死刑になる刑事裁判を傍聴する家族の姿と今でも重なるところがあります。

　東條英機は心臓を狙った自殺未遂をしており，その時の映像もあったと記憶します。丘の上にある小さな一軒家のようでした。陸軍大将でありながら質素な暮らしをし，家族を大切にしたという話です。

　その東條英機の家族も，東條英機がA級戦犯となったこともあり，怨嗟の的となったり，誹謗中傷を受け続けてきたと聞きます。

```
2020年08月19日20時38分の実行記録
twitterAPI-search-lawList-mydql-add.rb "東條英機"
ツイート数：0/1958 リツイート数：0/1958 トータル：74
hirono_hideki 0／0件
kk_hirono 0／0件
s_hirono 0／0件
```

　1秒もあったのか瞬間に処理が終わりましたが，再捜査要請書＿警察庁・石川県警察御中（@kk_hirono）のツイートが該当しておらず，気になるところはあります。まとめ記事も出来上がっていますが，深澤諭史弁護士に該当はなかったようです。

```
2020年08月19日20時43分の実行記録
twitterAPI-search-lawList-mydql-add.rb "東条英機"
ツイート数：5/1958 リツイート数：3/1958 トータル：2212
hirono_hideki 0／0件
kk_hirono 0／0件
s_hirono 0／0件
```

　近年は，東條英機として名前を見かけることが多いように思っていたのですが，昭和の時代に見ていたのと同じ東条英機で検索したところ，結果がかなり増えました。

　思えば，憲兵隊を悪用し拷問で弾圧をしたともされるのが，東條英機で，その割には憶測のような話しか見ていないので，実際どうなのかという思いは前からありました。2つのまとめ記事も出来上がっています。

```
 - 2020年08月19日17時01分の登録： ＼野田隼人　@nodahayato＼弁護人にのみ通知することで良いか…。被告人において聞き込んだ噂から偶然名寄せができた結果として、同一の被害者が短期間に異なる機会に異な http://hirono2014sk.blogspot.com/2020/08/nodahayato.html
 - 2020年08月19日17時02分の登録： ＼深澤諭史　@fukazawas＼検事も逆恨みを買うから大変ですね。盗撮とのことですが，性犯罪，ストーカー系は，そうなる割合を高く感じます。 http://hirono2014sk.blogspot.com/2020/08/fukazawas_47.html
 - 2020年08月19日17時05分の登録： ＼匿名裁判官　@courts_jp＼質問箱にたくさんご質問いただき，ありがとうございます。 ただ，個別の事案に関するご質問については，お答えをすることができません。私に個 http://hirono2014sk.blogspot.com/2020/08/courtsjp.html
 - 2020年08月19日17時26分の登録： ＼サイ太　@uwaaaa＼性犯罪に限って特別扱いをする理由ってあるの？　普通の犯罪だとしても名前とか出されるのには抵抗感あるように思うけど。 http://hirono2014sk.blogspot.com/2020/08/uwaaaa_19.html
 - 2020年08月19日17時28分の登録： ＼弁護士落合洋司?高輪ゲートウェイ駅徒歩5分?泉岳寺駅徒歩1分　@yjochi＼なかなか厳しそう。 ↓ 安倍首相、慶応病院で7時間半の真実…吐瀉物に鮮血、ステロイド効かず http://hirono2014sk.blogspot.com/2020/08/51yjochi-7.html
 - 2020年08月19日17時29分の登録： ＼弁護士落合洋司?高輪ゲートウェイ駅徒歩5分?泉岳寺駅徒歩1分　@yjochi＼知人が東京地検で副部長になったので、電話でお祝い言おうと電話したら、出てきた事務官が「用件 http://hirono2014sk.blogspot.com/2020/08/51yjochi_19.html
 - 2020年08月19日18時39分の登録： REGEXP：”現預金”／深澤諭史（@fukazawas）の検索（2020-08-14〜2020-08-16／2020年08月19日18時39分の記録3件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2020-08-142020-08.html
 - 2020年08月19日20時39分の登録： REGEXP：”東條英機”／データベース登録済みツイート：2020年08月19日20時39分の記録：ユーザ・投稿：5／6件 http://hirono2014sk.blogspot.com/2020/08/regexp20200819203956.html
 - 2020年08月19日20時45分の登録： REGEXP：”東条英機”／データベース登録済みツイート：2020年08月19日20時45分の記録：ユーザ・投稿：10／13件 http://hirono2014sk.blogspot.com/2020/08/regexp2020081920451013.html
```

　所定のディレクトリで，「grep 登録 2020-08-19_reference.org」というコマンドを実行し，前回ツイート済みのものを確認しました。

　そういえば，夕方に宇出津新港に買い物に行ったタイミングで，アルプのテレビで，意外にも感じるニュースを見かけていました。2回見たようにも思うので，午後に家のテレビでも見ていたような気もします。買い物から戻ってからはまだテレビをつけていません。

金沢　食　満足 - Google 検索 https://t.co/6j5oebghIL

　どうもテレビの石川県内ニュースの他，ネットではまだ情報が出ていないようですが，全国の旅行者のアンケートで，食に関する満足度が，金沢が1位で，それも3年連続というような話でした。

　今日は他にも珍しいことがあって，どんたく宇出津店で冷凍のキンキがあったのです。特大が7,8と残っていたと思いますが，特大でないものが1つだけ残っていて，迷ってそれを買ってきました。特大が1,980円，それでないのが980円となっていたと思います。

　アメリカ産とあったのがちょっと残念にも思い，買うかどうかの迷いにもなったのですが，裏のラベルには吉次ともあり，宮城県塩釜市とありました。キンキは，根室市花咲港，塩釜港，仙台市の繁華街と1回ずつしか店で食べた憶えがないのですが，最も美味しいと思った焼き魚でした。

　ネットで調べると，北海道では，昔は獲れ過ぎで，捨てるような価値のない魚だったという話です。昔と今の価値の違いについても考えさせる話です。

　同じくアメリカ産でしたが，すごく小さなキンキは，Aコープ能都店で開きにしたものや，開きにした干物が売られていることがありましたが，売れ残りが多く，半額になったものをそれぞれ買ってきた食べたことがありました。

　3週間ほど前になるのか，輪島の冷凍のカレイの干物がどんたく宇出津店で半額で売られていたので，買ってきて食べたのですが，期待以上に美味しかったです。そのあと普通のカレイの干物を買ってきて同じように焼いて食べたのですが，焼き過ぎもあったのか味は今ひとつでした。

　話に聞くと，宇出津病院で北海道に旅行に行ったときに，パサパサの美味しくないカニが料理に出てきたということですが，それでも美味しいカニを食べたことのない人は，うまいうまいと満足しながら食べていたという話でした。弁護士鉄道の商売にもありそうな話です。

　個人的に金沢市内の外食で，特別美味しいと思ったものを食べたことはなかったのですが，金沢刑務所での正月のおせちの折り詰めは，他に口にしたことがないほど美味しかったと印象にあります。それもあり平成13年は，12月31日に満期で出所させられたことが残念でした。

　12月に入るまで，12月21日辺りが満期日だと思いこんでいたことは，ネットでも書いていると思います。満期日の翌日が出所となっています。未決囚から受刑者とされた時点で，口頭で満期日のことは知らされていましたし，他にも刑務官から満期日を知らされることはありました。

　同じようにネットで公開した記事にも書いているはずですが，福井刑務所の出所とのとき，事前に連絡のない被告発人大網健二，その兄の関係者OSN，同級生の関係者KYNが，OSNが鳶職の仕事で使っているワゴン車で迎えに来ました。

　福井刑務所のときは，数日前に刑務官から手渡されていた和倉温泉までの鉄道の切符もそのばで返しています。なぜ和倉温泉までなのかずっと気になっていました。急行も同じだったと思いますが，七尾駅の次が和倉温泉駅になるのかと思います。

　能都町が能登町になった平成17年，同じ頃に鉄道の蛸島線が廃線になりましたが，それまでは宇出津駅を通過して珠洲市の蛸島駅が終着駅となっていました。廃線になるころには今は聞かない第三セクターなどになっていて，はっきりとはわからないですが，のと鉄道だったかもしれません。

　のと鉄道は二両編成だったと思います。鉄道をよく利用したのは昭和56年頃までですが，当時はまだ国鉄で，5両編成が当たり前になっていたと思います。普通車の運転免許を取得したのは昭和58年7月20日頃と，自動二輪で1年間の免許取り消し処分になっていたので，半年以上遅れていました。

　誕生日が同じ11月26日の被告発人大網健二は，18歳の誕生日を迎えた昭和58年のうちに普通免許を取得していたらしく，正月に私が名古屋から戻ったときは，すでに家の大網自動車工場の代車であった，トヨタのコロナという車種の車を自分で運転し，乗り回していました。

　なかでも昭和59年の2月頃，珠洲実業高校を卒業したばかりの同級生の女子2人を後部席に乗せ，4人で，輪島市の曽々木海岸から珠洲市の大谷の方に行ったのは，特に印象的で，輪島市と珠洲市の境にあるトンネルがオレンジ色の見たことのない灯りで，まるで銀河鉄道999の世界のようでした。

　他に銀河鉄道999のアニメの世界に迷い込んだように感じたのは，花咲港からの戻りで青森行のフェリー乗り場に向かった室蘭市内で，これもオレンジ色の電灯があったと記憶にあります。もう一つは昭和58年4月当時，小林運送で住み込みの長距離助手をしていた当時の，金沢中央卸売市場前です。

　平成9年には，小林運送は廃業し，建物自体が消滅していたと思います。小林運送の建物は，市場急配センターの事務所の50メートルほど，金沢中央卸売市場から離れた左斜めでした。昭和58年当時は，金沢中央卸売市場の裏側まで一直線の細い道路があり，周囲は田園風景でした。

　今は記憶にしかない風景ですが，早朝に金沢中央卸売市場での荷降ろしの仕事が終わってからは，大型トラックの洗車をさせられていました。小さな小川と橋があった記憶ですが，その少しのところに左に入る道があって，その右の右側が金沢市場輸送の駐車場となっていました。目と鼻の先です。

　この小林運送は，平成4年になってからの豊橋の仕事でも再び関係性が出てくるのですが，小林運送の経営難を救済するため専務になったという人物が，被告発人松平日出男との取引相手になったようです。平成4年3月の「相撲でも見いや」というときに，市場急配センターの事務所で専務を見ています。

　満州鉄道のあじあ号ですが，昭和50年代に漫画で見て知ったのが最初です。たぶん週刊少年ジャンプですが，長期連載ではない特集で見たという記憶です。実話のような個別の連載で同じ頃に見て知ったと思うのが，藤山寛美という芸人です。他に野球選手もいたと思います。

　今，Googleでの検索で藤山寛美という漢字を見て，意外な漢字の並びとも思ったのですが，娘の人もずいぶん前になりますがテレビで話題となっていて，最後に記憶にあるのが，当時はまだ不治の病とも聞いていた癌のことでした。10年以上は前ではないかと思います。

```
藤山 直美（ふじやま なおみ、1958年12月28日 - ）は、日本の女優。本名、稲垣 直子（いながきなおこ）。

大阪府大阪市生まれ、京都府［1］京都市山科区出身。京都女子高等学校卒業。父は喜劇役者の藤山寛美、甥は俳優の藤山扇治郎。

［source：］藤山直美 - Wikipedia https://ja.wikipedia.org/wiki/%E8%97%A4%E5%B1%B1%E7%9B%B4%E7%BE%8E
```

　生まれと出身が違うというのは，Wikipediaでも初めて見たように思いました。現在61歳という年齢も意外ですが，終わりがないので癌は克服されたようです。

```
『おしん』でヒロインの老後を演じた乙羽信子のようなケースを除くと、史上最年長の朝ドラヒロイン（放送開始当時47歳。それまでの最年長は1989年上半期・青春家族に主演したいしだあゆみ＝当時41歳）である。このドラマ出演を機に、『第57回NHK紅白歌合戦』の審査員を務める。

［source：］藤山直美 - Wikipedia https://ja.wikipedia.org/wiki/%E8%97%A4%E5%B1%B1%E7%9B%B4%E7%BE%8E
```

　あの伝説的な連続テレビ小説おしん，ずいぶん話題になっていると知りながら，当時ちょっとだけしか視聴していなかったドラマですが，その主人公の老後を演じていたとは初めて知りました。子役の時しか視聴した記憶がないのですが，そのあと田中裕子が演じていたという情報はネットで知りました。

　おしん，と言えば山形県の最上川だったと思います。平成11年に再び金沢刑務所の拘置所での生活が始まった後，官本で，おしんの本の奉公編というのを一冊だけ読むことが出来たのですが，その本の表紙の挿絵で赤子を背負う少女の姿がとりわけ印象的で，衝撃を覚えたほどです。

　だっことかおんぶという今は見かけない言葉ですが，昭和の時代は幼児に排便の仕方を教えるオマルとともに，宇出津の町中でも普通に見かけたものでした。奉公という言葉は，松下幸之助の本を官本で読んだことでも強く印象に残っています。これが奉納という弁護士に対するテーマにも繋がっています。

　ここ数年は全く見かけないですが，数年前まではネットでも滅私奉公という言葉を見かけていたように思います。久しぶりに思い出しました。捧げると奉納の違いは未だにわからないですが，捧げるというのは平成11年8月8日に金沢中警察署で，取り囲まれた警察官に，挑発的に言われた言葉です。

　「2012年初演の『ええから加減』で大阪の女漫才師役を好演し、共演の高畑淳子とともに第38回菊田一夫演劇賞演劇大賞を受賞[4]。」という意外な関係性のエピソードもWikipediaには出てきましたが，癌の病気のことは情報が見当たりません。


乳がんから復帰！藤山直美「完治したといったら大ペテン師になる」 (1/2ページ) - 芸能社会 - https://t.co/FzP9XTV21T（サンスポ） https://t.co/Cky048PIun 昨年２月に初期の乳がんを公表し、翌３月に摘出手術を受け療養していた女優、藤山直美（５９）が７日、東京都内で行われた１０月から上演の


　上記の記事で自分の記憶に間違いがなかったことは確認が出来ましたが，2018年8月8日の記事となっており，本文の昨年2月だと，2017年2月になります。これだと思っていたよりずいぶんと最近の話になります。

　実は，このような癌の告知のニュースを見るたびに，悪徳医師に騙され大金をむしり取られ，本人は死地からの生還と喜んでいるのではないかと想像するところがあるのですが，それも弁護士鉄道の水先案内をやってくれた，世紀の大犯罪人被告発人木梨松嗣弁護士のことがあるからです。

　この被告発人木梨松嗣弁護士に対しては，狂い死ぬのもお構いなしの刑事裁判と，無期懲役刑としての人生の最後，終焉が相応しく，それ以外はないと考えています。

　@kanazawabengosi もう一度，金沢弁護士会のTwitterアカウントのメンションを含めて投稿します。＞　この被告発人木梨松嗣弁護士に対しては，狂い死ぬのもお構いなしの刑事裁判と，無期懲役刑としての人生の最後，終焉が相応しく，それ以外はないと考えています。

　南満州鉄道というのも気になっているのですが。本やドラマでは満鉄と省略され，満鉄総裁というのもよく見かけてきました。港の大連から確か731部隊でも知られるハルピンまで，鉄道が繋がっていたとYouTubeの動画で初めて知ったあじあ号になります。

南満州鉄道 - Wikipedia https://t.co/aJg7I8XLen 南満洲鉄道（みなみまんしゅうてつどう）は、日露戦争終結後、1905年（明治38年）に締結されたポーツマス条約によって、ロシア帝国から大日本帝国に譲渡された東清鉄道南満州支線（長春・旅順間鉄道）のこと[1]

　やはり南満州鉄道が満鉄の正式名称だったようです。満州といえば冬場に水が凍らないのが珍しいとされた極寒の地域になります。北部という印象が強烈に強かっただけに，南満州というのは，意外かつ新鮮に響いた言葉です。

　「1906年（明治39年）11月に設立された半官半民の国策会社である[1]。」とも上記のWikipediaにはあります。弁護士脳が弁護士音頭の弁護士踊りでもやらかしそうなのが，最近は余り見かけなくはなっている「国策」という言葉で，「国策捜査」というのもありました。

```
満鉄の方が関東軍よりも歴史が古く、老舗意識が濃厚で関東軍を一段下にみる風潮があり、第一次世界大戦後の反軍的雰囲気のなかでは軍に対して非協力的姿勢が顕著であった［17］。ただし、そのなかでも満鉄調査課長の佐田弘治郎やロシア班主任の宮崎正義は関東軍との連携を模索していた［17］。宮崎が関東軍参謀の石原莞爾と出会うのは、1930年秋の旅順のヤマトホテルにおいてであった［17］。

［source：］南満州鉄道 - Wikipedia https://ja.wikipedia.org/wiki/%E5%8D%97%E6%BA%80%E5%B7%9E%E9%89%84%E9%81%93
```

　上記の引用部分に，石原莞爾の名前が出てきました。「ただし、そのなかでも満鉄調査課長の佐田弘治郎やロシア班主任の宮崎正義は関東軍との連携を模索していた［17］。宮崎が関東軍参謀の石原莞爾と出会うのは、1930年秋の旅順のヤマトホテルにおいてであった［17］。」とあります。

石原莞爾 - Wikipedia https://t.co/2qGsQ3AtGz 石原 莞爾（いしわら かんじ[注 1]、1889年1月18日 （戸籍の上では17日）- 1949年8月15日）は、日本の陸軍軍人。最終階級は陸軍中将。栄典は正四位[1]・勲一等[2]・功三級[1]、「世界最終戦論」など軍事思想家としても知られる。

　石原莞爾の命日が8月15日というのも意外でありながら何か背負った宿命のようなものも感じないではありません。同じくずっと気になってきたところですが，被害者安藤文さんの生誕も昭和45年8月15日と知り，1945年の終戦記念日とも似ています。

　初めてみたWikipediaではないと思いますが，「幼少期の莞爾と二郎」，「青年期の莞爾と二郎」という写真が出てきました。まだ確認はしていませんが，実の兄弟のようです。

```
昭和3年（1928年）に関東軍作戦主任参謀として満州に赴任した。自身の最終戦争論を基にして、関東軍による満蒙領有計画を立案する。

昭和6年（1931年）満州事変を起こした［6］後に23万の張学良軍を相手に、わずか1万数千の関東軍で日本本土の3倍もの面積を持つ満州の占領を実現した。

［source：］石原莞爾 - Wikipedia https://ja.wikipedia.org/wiki/%E7%9F%B3%E5%8E%9F%E8%8E%9E%E7%88%BE
```

　わかりやすいWikipediaの記述です，弁護士脳の歴史的反応の資料とするため，まとめ記事を作成，記録をして起きたおと思います。

```
2020年08月19日22時57分の実行記録
twitterAPI-search-lawList-mydql-add.rb "石原莞爾"
ツイート数：0/1958 リツイート数：0/1958 トータル：6
hirono_hideki 0／0件
kk_hirono 0／0件
s_hirono 0／0件
```

　こちらも私のアカウントでのTwitterAPIの検索結果がゼロでした。再捜査要請書＿警察庁・石川県警察御中（@kk_hirono）では直前にツイートをしているはずで，通常はこれが検索結果に反映され，データベースの記録のも取り込まれています。

　ちょっと見たことのないエラーが，スクリプトの処理で発生しました。ブログへの投稿自体は成功しているっぽいです。

```
(py37_env) a66@a66-XTe:~$ ajx-all-user-mysql-REGEXP_blogger_hirono2014sk.rb "石原莞爾"
SELECT * FROM tw_user_tweet WHERE  tweet REGEXP "石原莞爾"   ORDER BY tw_date ASC
makotoakishige
makoto.a（makotoakishige）
ユーザ名称：makoto.a [screen_name]ユーザ名：makotoakishige フォロー数：855 フォロワー数：589 ツイート数：22077
ishiitakaaki
石井孝明（Ishii Takaaki）（ishiitakaaki）
ユーザ名称：石井孝明（Ishii Takaaki） [screen_name]ユーザ名：ishiitakaaki フォロー数：9255 フォロワー数：106089 ツイート数：193410
LiarLawyer800
嘘つき弁護士。（LiarLawyer800）
ユーザ名称：嘘つき弁護士。 [screen_name]ユーザ名：LiarLawyer800 フォロー数：2519 フォロワー数：3061 ツイート数：148116
vivaSPQR
婚活弁護士お兄さん（vivaSPQR）
ユーザ名称：婚活弁護士お兄さん [screen_name]ユーザ名：vivaSPQR フォロー数：2974 フォロワー数：1453 ツイート数：56943
REGEXP：”石原莞爾”／データベース登録済みツイート：2020年08月19日22時59分の記録：ユーザ・投稿：4／4件
Traceback (most recent call last):
  File "/home/a66/h-local-bin/arg-bpost_ajx.py", line 89, in <module>
    f = open(filename)
IOError: [Errno 2] No such file or directory: './tmp.txt'
rm: 'tmp.txt' を削除できません: そのようなファイルやディレクトリはありません
```

 - 2020年08月19日22時59分の登録： REGEXP：”国策”／データベース登録済みツイート：2020年08月19日22時56分の記録：ユーザ・投稿：67／244件 http://hirono2014sk.blogspot.com/2020/08/regexp20200819225667244.html

　戦没者をここまでかと愚弄する深澤諭史弁護士のツイートやリツイートは，数多に見かけてきました。

```
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb fukazawas '国策' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "fukazawas") AND  tweet REGEXP "国策"  ORDER BY tw_date ASC
REGEXP：”国策”／深澤諭史（@fukazawas）の検索（2014-09-14〜2020-01-01／2020年08月19日23時10分の記録16件）
```

 - 2020年08月19日23時10分の登録： REGEXP：”国策”／深澤諭史（@fukazawas）の検索（2014-09-14〜2020-01-01／2020年08月19日23時10分の記録16件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2014-09-142020-01.html

　時刻は23時12分です。そのままテレビはつけていません。戦没者の霊魂とそれを愚弄してきた深澤諭史弁護士の今後に思いを馳せるだけでも，お腹一杯です。

 - （01／16） TW fukazawas（深澤諭史） 日時：2014-09-14 10:54:00 +0900 URL： https://twitter.com/fukazawas/status/510969716098093056

> 「耳障りは良いが抽象的な宣伝文句で始めて，倫理的で情緒的な看板で消極意見を迫害する」って，平成の司法改革に限らず，日本の国策遂行でよく使われる手口ですね。
>
> ＊先の戦争→自存自衛とアジア解放のためだ！反対する奴は非国民！
> ＊司法改革→社会の隅々に法の光を！反対する奴は既得権者！

　見覚えのない深澤諭史弁護士のツイートですが，記録したまとめ記事の初っ端に弁護士脳のお花畑として強烈なのが出てきました。

 - （02／16） TW fukazawas（深澤諭史） 日時：2015-03-12 13:00:00 +0900 URL： https://twitter.com/fukazawas/status/575868903961710595

> 昔：帝国臣民に生まれながら，国策に反対する奴は非国民！
>
> 今：ロー制度下で弁護士になっておきながら，制度に反対する弁護士は淘汰されてしまえ！
>
> #太平ロー戦争

　昭和の終わりには中国残留孤児の問題もありました。テレビのニュースにはほとんど無関心でしたが，驕り高ぶった日本人に迫害を受けたとされる日本人の子供を，救って育てたという中国人に対して魂を震わされるような畏敬の念がありました。リスペクトを要求する弁護士とは対極です。

 - （03／16） RT fukazawas（深澤諭史）｜harrier0516osk（弁護士法人向原・川上総合法律事務所　向原） 日時：2016-05-16 09:29:00 +0900／2016-05-16 09:29:00 +0900 URL： https://twitter.com/fukazawas/status/732005046896861184 https://twitter.com/harrier0516osk/status/732004925463396353

> 国策とはそういうもの。
> やりたい、といえば推進されるもの。 https://t.co/dTpCLzTwGT

 - （04／16） RT fukazawas（深澤諭史）｜harrier0516osk（弁護士法人向原・川上総合法律事務所　向原） 日時：2016-05-16 09:29:00 +0900／2016-05-16 09:28:00 +0900 URL： https://twitter.com/fukazawas/status/732005034179710976 https://twitter.com/harrier0516osk/status/732004762460164096

> まだそういう認識でないのがすごい
> 国策とはやったもん勝ち https://t.co/S4LWjcyAnF

　これまで表現には隠忍自重をしてきた，福岡市天神に法律事務所を構えるという向原栄大朗弁護士ですが，深澤諭史弁護士との関係性は，ずっと前から，福岡市出身でその漫画の舞台ともしていたとも記憶にある，東大一直線の東大通と多分田吾作との関係性そのものです。

```
多分田吾作（たわけ・たごさく）
5巻で初登場。ネーミングは名古屋弁でバカ・アホを意味する「たわけ」。病気で寝たきりの母と二人暮らしで、好物はトマト。
試験でカンニングをした罰として全教科0点になったことにより、東大通は800点の座を初めて奪われたと思い（本当は800位）愕然。中学編では火花を散らす（？）ライバルとなる。
だが東大通を優秀館高校に入れるため、多分にも優秀館受験を依頼。意気投合した2人は高校編で迷コンビとなり、東大通さえもずっこけさせるアホぶりを発揮。一方、所々で東大通へのツッコミ役もこなす。
東大通に匹敵するアホではあるが、中学時代には現役のノートで勉強しただけでテストの順位が500位にまで上がるなど、極端に頭が悪いわけではない。
父親が校長を務める知識ヶ丘学園に編入後は、制服も知識ヶ丘のものに変更になる。
父親のコネ・裏金によって切裂医大に合格する。
小林が大変気に入っているキャラクターで、その後の小林作品にも『メンぱっちん』などに出演。『いろはにほう作』も多分の発展形だという。

［source：］東大一直線と東大快進撃の登場人物 - Wikipedia https://ja.wikipedia.org/wiki/%E6%9D%B1%E5%A4%A7%E4%B8%80%E7%9B%B4%E7%B7%9A%E3%81%A8%E6%9D%B1%E5%A4%A7%E5%BF%AB%E9%80%B2%E6%92%83%E3%81%AE%E7%99%BB%E5%A0%B4%E4%BA%BA%E7%89%A9
```

 - （05／16） RT fukazawas（深澤諭史）｜harrier0516osk（弁護士法人向原・川上総合法律事務所　向原） 日時：2016-05-18 13:18:00 +0900／2016-05-18 10:23:00 +0900 URL： https://twitter.com/fukazawas/status/732787493326721025 https://twitter.com/harrier0516osk/status/732743256220438528

> 市場原理からすると、法科大学院は淘汰されるでしょう。が、そこには国策があるから、自然淘汰されません。
> それが、単なる民間の一零細事業主に過ぎない弁護士との、一番大きな違いではないかと考えています https://t.co/MCLFx9SwvJ

 - （06／16） RT fukazawas（深澤諭史）｜harrier0516osk（弁護士法人向原・川上総合法律事務所　向原） 日時：2016-09-18 10:57:00 +0900／2016-09-18 10:50:00 +0900 URL： https://twitter.com/fukazawas/status/777325676357570560 https://twitter.com/harrier0516osk/status/777323851466223616

> 法科大学院制度の功績はとても大きいと思います。
> 国策というのはこうやって動くのだなということと、自治を誇る弁護士業界でさえも、国策によって、このようにいとも簡単にブッ壊されるのだなということがよくわかって、勉強になります。 https://t.co/zK4BjFA76y

 - （07／16） RT fukazawas（深澤諭史）｜shima_chikara（嶋﨑量（弁護士）） 日時：2016-09-19 15:12:00 +0900／2016-09-18 08:39:00 +0900 URL： https://twitter.com/fukazawas/status/777752288026763265 https://twitter.com/shima_chikara/status/777290979195834368

> 技能実習生も外国人介護士看護士も、騙しと搾取ばかり。
> 日本の外国人労働政策は、人権侵害誘発システム。
> こんなシステムを国策にして、アジア各国に敬意を払われたいとか、商売できるとか、本気で思ってるのか？人権感覚もゼロなら、長期的に見て経済センスもゼロ。

 - （09／16） RT fukazawas（深澤諭史）｜NOSUKE0607（清水 潔） 日時：2017-01-04 20:51:00 +0900／2017-01-03 19:17:00 +0900 URL： https://twitter.com/fukazawas/status/816613123754856448 https://twitter.com/NOSUKE0607/status/816227090475282433

> 「神道は戦前、国策に協力というよりは、共犯者になり戦争をすすめてきました」「戦前の愚　来る返さぬ」八王子の浅川金刀比羅神社宮司さんの主張。
> 一口に神社と言ってもこんな神社から、改憲の書名集めをする神社まである。我々はもっと神社を知… https://t.co/xaUy0miPbj

　本日と思うところですが，深澤諭史弁護士のタイムラインで，気になる清水潔氏のツイートのリツイートを見かけていました。同じく戦時中に関するツイートで，お菓子のメーカーを痛烈に批判するものでした。正義感なのかもしれないですが，桶川ストーカー殺人事件では，大いに疑問があります。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜NOSUKE0607（清水 潔） 日時：2020-08-19 23:37／2020/08/18 14:12 URL： https://twitter.com/kk_hirono/status/1296093822292602880 https://twitter.com/NOSUKE0607/status/1295589323073437700  

> 日本軍による中国各地への空襲については不思議な話がある。この有名なお菓子メーカーは空爆が大好きだったらしく、他国の悲劇を商売に利用していたのだ。特にこの「爆弾チョコレート」はあまりに恐ろしい。 https://t.co/BOguebIemF  
　奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)ではかなり前からブロックされているジャーナリストの清水潔氏ですが，再捜査要請書＿警察庁・石川県警察御中（@kk_hirono）では今のところずっとリツイートが出来ています。

　ジャーナリストの清水潔氏は，南京事件に関する本も出しているようです。本の宣伝になるかもしれないのは，深澤諭史弁護士と同じですが，軽薄な妄執と，狂気じみた欲望が原動力と思える深澤諭史弁護士とは異なり，少なくとも検証はされていそうな本なので，多少は気になっています。

　踏み込んで調べたこともない南京事件ですが，近代史では物凄い数の日本軍による虐殺があったという説と，その虐殺の数は物理的にもありえないという説を見かけています。この南京事件もまとめ記事を作成しておきたいと思います。言うまでもなく現地を見ていないので，確証は無理です。

```
2020年08月19日23時47分の実行記録
twitterAPI-search-lawList-mydql-add.rb "南京事件"
ツイート数：3/1958 リツイート数：5/1958 トータル：4966
hirono_hideki 0／0件
kk_hirono 2／0件
s_hirono 0／0件
```

　TwitterAPIのリミットと設定した8500には到達していないですが，トータル：4966は観測の範囲とおさまりました。今回は，直前の再捜査要請書＿警察庁・石川県警察御中（@kk_hirono）のツイートも検索の該当に反映されています。

 - （10／16） RT fukazawas（深澤諭史）｜poorpartner（三毛猫B【行政法クラ】） 日時：2017-07-27 13:04:00 +0900／2017-07-27 09:23:00 +0900 URL： https://twitter.com/fukazawas/status/890422596113637376 https://twitter.com/poorpartner/status/890367044859842560

> 補助金適正化法違反と詐欺で籠池夫婦逮捕へって…
>
> ブツも軒並み持ってっててさ…
> この人らも逃亡はせんだろうに。顔割れてるし。
>
> 国策捜査と言われても仕方ないな。
>
> 検察ってまあ弱いもんには強く、強いもんには弱いからな

 - （11／16） RT fukazawas（深澤諭史）｜guitar_ben（ぎたべん） 日時：2017-08-16 11:14:00 +0900／2017-08-16 10:02:00 +0900 URL： https://twitter.com/fukazawas/status/897642655055847427 https://twitter.com/guitar_ben/status/897624501097304064

> 「国策に従っただけだから被害者だ」的な言い方してるが、原発事故後の電力会社みたいだな。
>
> 東京新聞:法科大学院の撤退止まらず　国立、有名私大で募集停止:教育ニュース:教育(TOKYO Web) https://t.co/phRpk633wU

 - （12／16） RT fukazawas（深澤諭史）｜kd_ixi（標識派） 日時：2017-10-09 10:54:00 +0900／2017-10-09 07:44:00 +0900 URL： https://twitter.com/fukazawas/status/917206581007196161 https://twitter.com/kd_ixi/status/917158855095746560

> 裁判所が強制執行を充実させないのも、法テラスが契約弁護士の心を折りにくるのも、いずれも「なるべく利用を減らしたい」という国策に基づいているんだと最近思うようになった。 https://t.co/kIgmuC8gqv

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜kd_ixi（エンリケ航海玉子） 日時：2020-08-19 23:54／2017/10/09 07:44 URL： https://twitter.com/kk_hirono/status/1296098152953479168 https://twitter.com/kd_ixi/status/917158855095746560  

> 裁判所が強制執行を充実させないのも、法テラスが契約弁護士の心を折りにくるのも、いずれも「なるべく利用を減らしたい」という国策に基づいているんだと最近思うようになった。 https://t.co/kIgmuC8gqv  

　これまでTwitterで見たことのない現象だと思ったのですが，どうもデータベースに登録されていたプロフィールの名前が過去のもので「標識派」となっており，最新の情報として読み込んだ埋め込みツイートの情報が，「エンリケ航海玉子」となっているようです。

 - （13／16） RT fukazawas（深澤諭史）｜mas__yamazaki（山崎 雅弘） 日時：2018-02-08 18:07:00 +0900／2018-02-08 16:44:00 +0900 URL： https://twitter.com/fukazawas/status/961526945094672385 https://twitter.com/mas__yamazaki/status/961505884269522946

> 自国優越思想の文脈で、特定のプロジェクトを国策として持て囃してしまうと、失敗が明白になっても誰もそれを直視できず、面子と威信を守る為に中止を決断できなくなる。昭和史の中では既視感ありすぎの話だが、「失敗を反省する」概念や「謙虚に他… https://t.co/szFjLcPX3l

 - （15／16） TW fukazawas（深澤諭史） 日時：2019-11-05 09:24:00 +0900 URL： https://twitter.com/fukazawas/status/1191511584012554240

> （＾ω＾）国策で立派な，多様性のある質と量とともに豊かな法曹を養成するお！
> （・∀・）そのためにどうするんですか？
> （＾ω＾）高額な学費を費やさないと司法試験を受験できないようにし，バイト禁止で無給で研修させ，食っていけると心配す… https://t.co/ps6GBD8X7F

 - （16／16） RT fukazawas（深澤諭史）｜shima_chikara（嶋﨑量（弁護士）） 日時：2020-01-01 09:26:00 +0900／2019-12-31 23:12:00 +0900 URL： https://twitter.com/fukazawas/status/1212168139598790656 https://twitter.com/shima_chikara/status/1212013692646121474

> ゴーン氏が述べるとおり、日本の刑事司法は、正に人質司法で問題がある。
> とはいえ、司法制度を愚弄したこんな逃亡劇を肯定しようなどとは、全く思えない。ゴーン氏の疑惑には国策捜査の疑いがあろうと、こんな形でゴーン氏を訴追から免れさせては… https://t.co/BNcX7XjAuf

　深澤諭史弁護士の「国策」をキーワードに含んだツイートは，記録されたものが16件と意外に少なくは感じましたが，さすがと思われる内容のものがリツイートもされていました。弁護士脳の集積地のようなものです。

　深澤諭史弁護士にしてみれば，全ての批判や問題の投げかけは，弁護士に対する逆恨みや誹謗中傷と脳内変換されることでしょう。修正は不可能とも思われるので，弁護士鉄道の爆破が必要不可欠と長年，思料されてきた所以です。

〈〈〈：Linux Emacs： 2020-08-20（木曜日）00：04 　〈〈〈

