* 確認された小倉秀夫弁護士のTwitterタイムライン，新規投稿は未確認
  :LOGBOOK:
  CLOCK: [2020-07-11 土 20:51]
  :END:

:CATEGORIES: 小倉秀夫弁護士

〉〉〉：Emacs： 2020-07-11（土曜日）20：51　 〉〉〉

　昨日の7月10日は，久しぶりにずいぶん体調が悪くなり，午後から寝ている時間が多かったのですが，よく寝たつもりでも時間が進んでおらず，パソコンに不具合が出ているのかと疑うこともありました。夕方も早い時間に寝たのですが，かなり長い時間寝ていたと思います。

　明け方に寝汗をかいて体が冷えたのが原因のようでした。そのあとも寝汗をかいていたのですが，タオルで拭いていました。今朝もそうだったように思いますが，朝起きたときは，まだ少し体調が優れなかったものの，昨日とは逆にしばらく時間た経つと回復しました。

　前日に森進一の母親の自殺という深刻に考えさせられる話を知ったのも体調不良の一因だったと思います。他に銀行に行った時に電話が掛かり，図書館に取り寄せていた本を取りに行ったのですが，雨にもうたれていました。記憶が低いとは思わなかったのですが，悪寒気味でした。

　咳のような症状はなかったのですが，急速に悪化するという新型コロナウィルスのこともあり，少なからず心配もしたのですが，一日で回復し体調が戻ったのは幸いでした。昨日は，食欲もなく昼食，夕食を食べずに寝ていました。最初によく寝たと思って起きた時間が13時20分ぐらいでした。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-07-11 21:12／2020/07/11 21:09 URL： https://twitter.com/kk_hirono/status/1281924302011424769 https://twitter.com/s_hirono/status/1281923626246131712  

> 2020-07-11-204806_小倉秀夫（@Hideo_Ogura）さんの返信があるツイート　／　Twitter.jpg https://t.co/6Obznau8O0  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-07-11 21:12／2020/07/11 20:35 URL： https://twitter.com/kk_hirono/status/1281924442428325889 https://twitter.com/s_hirono/status/1281914987770859523  

> 2020-07-11-075602_（1）　小倉秀夫（@Hideo_Ogura）さんの返信があるツイート　／　Twitter.jpg https://t.co/1rxzXCCG6d  

　今朝の7時56分がスクリーンショットの記録だと確認しました。三浦義隆弁護士のツイートのリツイートがタイムラインのトップになっていますが，以前は違ったものでした。

 - 2019年12月12日19時27分の登録： ＃小倉秀夫　@Hideo_Ogura＃のツイート／2019-05-31_0815〜2019-06-08_0709／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年12月12日19時27分 http://hirono2014sk.blogspot.com/2019/12/hideoogura2019-05-3108152019-06.html

 - 2019年06月24日07時38分の登録： @Hideo_Ogura（小倉秀夫）のツイート　”．＊”　3203／3203：2018-10-15　01：27〜2019-06-08　07：09　2019年06月24日07時38分の記録 http://hirono2014sk.blogspot.com/2019/06/hideoogura320332032018-10-1501272019-06_24.html

　ちょっと違ったものでした。昨年2019年6月24日の記録となっていますが，内容が2018-10-15　01：27〜2019-06-08　07：09の範囲です。ちょうど小倉秀夫弁護士のTwitterアカウントの更新が止まった時期が，この2019年6月24日頃だったと思います。

奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: ＃小倉秀夫　@Hideo_Ogura＃のツイート／2019-05-31_0815〜2019-06-08_0709／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年12月12日19時27分 http://hirono2014sk.blogspot.com/2019/12/hideoogura2019-05-3108152019-06.html#p2

2件目 ￼戻る （リツイート）： Hideo_Ogura（小倉秀夫）｜lawkus（ystk） 日時：2019-06-08 07:07／2019-06-07 21:37 URL： https://twitter.com/Hideo_Ogura/status/1137118978134855680 https://twitter.com/lawkus/status/1136975415564574720
{% tweet 1137118978134855680 %}
> 【お知らせ】 \n 「近頃は微物検査があるから痴漢冤罪は起こり得ない」とのツイートが一部出回っていますが、完全に嘘です。 \n 「微物検査した上で何も出なかったけど有罪」という判決は最近も普通に出てますし。 \n こんなデタラメを真に受けて確かめもせず拡散した人々は己の愚かさを心から恥じてほしい。

　原因がわかったのですが，小倉秀夫弁護士のTwitterタイムラインでトップに表示されていたツイートが，アカウントの非公開設定になっていました。たまたまトップにあったツイートだから異変に気がつくことが出来たのだと思いますが，誤解を与えそうな現象です。

〈〈〈：Linux Emacs： 2020-07-11（土曜日）21：45 　〈〈〈

