* 「「ドクター・キリコになりたい」　京都ＡＬＳ女性嘱託殺人　逮捕の医師、ツイッターに繰り返し投稿か　 | 京都新聞 」という市川寛弁護士のツイート
  :LOGBOOK:
  CLOCK: [2020-07-28 火 11:34]--[2020-07-28 火 15:11] =>  3:37
  :END:

:CATEGORIES: 市川寛弁護士

〉〉〉：Emacs： 2020-07-28（火曜日）11：34　 〉〉〉

 - 2020年07月28日09時58分の登録： ＼弁護士 市川 寛　@imarockcaster42＼「ドクター・キリコになりたい」　京都ＡＬＳ女性嘱託殺人　逮捕の医師、ツイッターに繰り返し投稿か　 | 京都新聞 http://hirono2014sk.blogspot.com/2020/07/imarockcaster42_28.html

　週刊少年チャンピオンの連載と記憶しているブラックジャックですが，これも昭和40年代の終わりから連載が始まったように記憶にあります。連載は長く続いていたように思うのですが，週刊少年チャンピオンをほとんど読まなくなったとも記憶にあるので，いつまで続いたのはわかりません。

　週刊少年チャンピオンを読まなくなった頃，宇出津の千間書店の漫画の単行本の棚に，同じ手塚治虫の漫画で「火の鳥」を見かけるようになったと記憶にあるのですが，手にして開くか，手にすることもなかったのかという記憶しかないものの，割と強く印象に残っていました。

火の鳥 (漫画) - Wikipedia https://t.co/4iTVdmpXCn

　比較的最近になって情報を見かけるようになった手塚治虫の火の鳥ですが，きっかけは深澤諭史弁護士のリツイートにもなっていたと思うアッサジであったように思います。

　市川寛弁護士のツイートにある記事を読むと，ドクター・キリコがブラックジャックの登場人物のように書かれていました。キリコというのは，子供のような大人のような女の子で，ブラックジャックの手術の助手をしていた登場人物のことかと思っていました。

　調べたところ，その女の子はキリコではなくピノコだったのですが，双子の姉の腫瘍から生まれた話など，これまで全く知らなかったことがわかりやすい情報としてまとめられていました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-28 11:56／2020/07/28 10:04 URL： https://twitter.com/kk_hirono/status/1287945091403755520 https://twitter.com/hirono_hideki/status/1287916730778415104  

> ブラックジャックピノコにモデル!誕生秘話･正体は双子姉の病気腫瘍 https://t.co/egw9J27PMU  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜asahi_nagoya（朝日新聞名古屋編集局） 日時：2020-07-28 11:57／2020/07/27 19:08 URL： https://twitter.com/kk_hirono/status/1287945279245754369 https://twitter.com/asahi_nagoya/status/1287691231879819264  

> 男性3人に車突っ込み1人死亡、無差別殺害図る？　豊橋 https://t.co/pQloB1Fm7O  27日午後2時半ごろ、愛知県豊橋市の路上で、除草作業中の男性3人に、男が運転する車が突っ込んだ。3人は病院に搬送されたが、1人が死亡した。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜tv_asahi_news（テレ朝news） 日時：2020-07-28 11:58／2020/07/27 18:19 URL： https://twitter.com/kk_hirono/status/1287945409915101184 https://twitter.com/tv_asahi_news/status/1287678885153234982  

> 【速報】路上の男性3人に殺意を持って車で突っ込み男性1人死亡、2人搬送　愛知・豊橋市 https://t.co/thR32iDcU8  

「神になりたかった」路上の男性3人に車で突っ込んだ男が逮捕 愛知県豊橋市 / Twitter https://t.co/4FOLN9D2rM

　Twitterのトレンドに「「神になりたかった」路上の男性3人に車で突っ込んだ男が逮捕 愛知県豊橋市」とあり，昨夜も見ていたニュースでしたが，愛知県とは記憶にあったものの，豊橋市というのは，このトレンドで初めて知ったように思いました。被告発人安田敏の白菜散乱も思い出します。

　豊橋市といえば，以前は，豊橋刑務所が交通刑務所という話を聞くことがあったのですが，他にもっと有名だった市原刑務所を含め，近年，交通刑務所という話をまったく見かけていないように思いました。

　キリコは，ガラス細工の工芸品としてテレビで見かけることもありますが，私の生まれ育った能登では，神様を先導する灯籠が巨大化したものとして，とても身近な言葉になります。ドクター・キリコの記憶がなかったのは不思議にも感じるのですが，見たことがなかったのか確信は持てません。

```
「切籠（キリコ）」または「奉燈（ほうとう）」と呼ばれる高さ数メートル〜十数メートルの巨大な切子灯籠を使うことを特徴とするものである。地域によって御明かし（おあかし）とも呼ばれる。主として7月から10月に掛けて夏祭り・秋祭りとして、現在も能登の約137の地区（不定期を含む）で行われており、疫病退散を願って始まったとされるものが多い。

1997年（平成9年）12月4日に「能登のキリコ祭り」として、国の「記録作成等の措置を講ずべき無形の民俗文化財」に選択され［1］、2015年（平成27年）4月24日に文化庁が【日本遺産】最初の18件の一つとして「灯り舞う半島 能登 ～熱狂のキリコ祭り～」の名称で認定した［2］。

［source：］能登キリコ祭り - Wikipedia https://ja.wikipedia.org/wiki/%E8%83%BD%E7%99%BB%E3%82%AD%E3%83%AA%E3%82%B3%E7%A5%AD%E3%82%8A
```

　ちょっと忘れていたような気もするのですが，「国の「記録作成等の措置を講ずべき無形の民俗文化財」に選択」というのが，弁護士ツイートの記録作成に大きな影響を与えたと思います。弁護士鉄道の記録です。

　前にも調べたことがあるように思うのですが，ブラックジャックの連載の時期を調べておきたいと思います。調べたようには思うのですが，内容が記憶に残っていない感覚です。

```
『ブラック・ジャック』（BLACK JACK）は、手塚治虫による日本の漫画作品。『週刊少年チャンピオン』（秋田書店）にて1973年11月19日号から1978年9月18日号にかけて連載したのち、1979年1月15日号から1983年10月14日号にかけて不定期連載された。全242話。略称はB・J。

［source：］ブラック・ジャック - Wikipedia https://ja.wikipedia.org/wiki/%E3%83%96%E3%83%A9%E3%83%83%E3%82%AF%E3%83%BB%E3%82%B8%E3%83%A3%E3%83%83%E3%82%AF
```

　昭和48年から連載が始まったとあります。昭和53年まで5年ほどの連載だったらしく，これは意外に早く終わっていたように感じました。「1979年1月15日号から1983年10月14日号にかけて不定期連載」というのは知らなかったと思いますし，不定期連載とは初めて見た気がします。

　ブラック・ジャックが正しいようですが，ブラックジャックというトランプのゲームがあったことを思い出しました。ゲームの内容が思い出せないですが，そもそもジャックの意味をしらないことに気が付きました。電波ジャックというのは昔，テレビで見かけたような気はします。

```
電波ジャック（でんぱジャック）とは、電気通信における正規の伝送路を乗っ取り、正規の受信者に向けて独自の内容を送信することをいう。

なお、「電波ジャック」はハイジャックに由来する日本独自の表現であり、英語では「Broadcast signal intrusion（放送信号割り込み）」又は、「Broadcast pirating」と呼ぶ。

［source：］電波ジャック - Wikipedia https://ja.wikipedia.org/wiki/%E9%9B%BB%E6%B3%A2%E3%82%B8%E3%83%A3%E3%83%83%E3%82%AF
```

　昭和の時代は身近でもあったハイジャックという言葉をいつのまにかすっかり忘れていたことに気が付きました。ジャックというのは乗っ取るという意味があるようです。他にも意味はあるのかもしれないので調べて確認しておきます。

ジャック(じゃっく)とは - コトバンク https://t.co/ZPUYdDEE2P

　乗っ取るという意味は書かれていなかったのですが，トランプの絵札とあるので10の次のJのことのようです。ジャックと呼んでいた記憶はあまりないのですが，トランプは平成以降，ほとんど見たこともないように思います。これも昭和の時代は身近なものでした。

　もう4週間ほど前になりますか，数年前から何度か時間を掛けて探していた，手塚治虫の短編漫画をようやく見つけ出すことが出来ました。漢字2文字だったとも思うのですが，不思議と記憶に薄かったタイトルで，実は今も思い出すことが出来ず，不思議に思っています。

〈〈〈：Linux Emacs： 2020-07-28（火曜日）12：44 　〈〈〈

* 宮城県名取市から思い出した，平成3年4月頃，被告発人安田敏が輪島屋鮮冷の運転手として金沢市場輸送に来た頃の状況
  :LOGBOOK:
  CLOCK: [2020-07-28 火 15:11]--[2020-07-28 火 20:37] =>  5:26
  :END:

:CATEGORIES: 被告発人安田敏,金沢市場輸送

〉〉〉：Emacs： 2020-07-28（火曜日）15：11　 〉〉〉

　福島県と宮城県の県境は，宮城県が岩沼市で，国道4号線と国道6号線が交わった辺りが宮城県と記憶にあるのですが，その付近に自衛隊の駐屯地があって，岩沼市ではなかったような記憶があります。ちょうど平成3年の4月頃に爆弾の荷物を運びました。

石川製作所　爆弾 - Google 検索 https://t.co/k86px1AbRF

防衛関連株は大波乱、代表格の石川製作所に信用規制が発動され週末要因も影響 | 株式投資情報　総合　日本インタビュ新聞 https://t.co/dGCyO0aRu4 2017/4/14 11:48:18株式投資ニュース

　石川製作所の場所が思い出せないのですが，金沢市場輸送にいた頃から爆弾や魚雷をちょくちょく積みに行き，福島県と群馬県の大きな火薬工場，自衛隊の基地や駐屯地に運ぶようになりました。自衛隊は少なかったかもしれません。

　他にもあったように思うのですが，今思い出せるのは青森県八戸市の航空自衛隊の基地，そして福島県との県境に近い自衛隊で基地ではなく駐屯地となっていたように思います。宮城県の自衛隊ということで検索すれば情報がすぐに見つかりそうです。

自衛隊 岩沼市 - Google 検索 https://t.co/EMSK0rKSN4 宮城県柴田郡柴田町大字船岡 字, 大沼端１−１

自衛隊 岩沼市 - Google 検索 https://t.co/gSSFZZh2g8]] 宮城県岩沼市下野郷北長沼

　ページタイトルがGoogleの検索ワードになっていました。岩沼市とあるのが陸上自衛隊岩沼訓練場，柴田郡柴田町と住所があるのが，陸上自衛隊船岡駐屯地となっています。

　国道4号線より山の方に入ったという記憶があるので，この船岡駐屯地に間違いはなさそうですが，平成3年当時は違った名称になっていたような気もします。

　船岡駐屯地というのは聞き覚えがないのですが，さきほど漢字2文字のように思い出しかけていた手塚治虫の短編漫画ですが，さきほど思い出したのは「ガラスの脳」になります。これも似たような感覚で，以前に見聞きをしたような感覚が乏しかったのです。

石川製作所 - Google 検索 https://t.co/EEzwKibXak]] 石川県白山市福留町２００

　石川製作所を調べると，白山市福留町とありました。この福留町というのは，逆に記憶というか脳にこびりついたような感覚の地名になります。この検索をする前，石川製作所は当時の石川郡野々市町，現在の野々市市の可能性が高いように考えていました。白山市は当時の松任市になります。

　福留町は，トラックで走行中，たびたび標識を見かけていたように思うのですが，埼玉県の辺りにも似たような地名があったり，似たような福増町という地名も見ていたような記憶があって，今の記憶のままだと白山市のどのあたりになるのか正直わかりません。

　長距離以外の市内配達などの仕事では，地図を所持することも地図をみることもほとんどなかったと思うのですが，国道8号線で手取川を渡る付近というのは，思いの外，海に近いのだと思いました。国道8号線は陸橋になるのか，手取川の橋や川を見たという記憶はない気がします。

　手前に斜めに入る旧道のような道路があって，そこでは手取川の大きな橋を渡り，橋を渡ってすぐ左手にあるのが手取フィッシュランドでした。2年ほど前にはテレビで中継を見たことがありました。最近はテレビCMも見かけなくなっていますが，そのままあると思います。

　自衛隊や爆弾というのは国防に関わる問題でもあり，あまり具体的にするのを避けていたのですが，福島県の火薬工場は日本工機，群馬県にあるのは中国化薬でした。前に調べたとき，中国化薬の本社は広島県とかの中国地方にあるらしく，それで中国化薬という名前になっているようです。

日本工機 - Google 検索 https://t.co/zBFASCQDWI]] 日本工機（株） 白河製造所

　白河製造所というのは初めてみたように思います。住所が福島県西白河郡西郷村となっています。白河市なのかと思っていました。栃木県との県境に近いと確認しました。国道4号線から少し日本海の方向に入ったというのは記憶どおりのようです。

　同じ頃に初めて山形市の市場に筍を運んだという記憶があるのですが，照明の暗い感じが印象に残る市場で，それとよく似た印象を受けたのが，平成4年3月30日の深夜から翌31日の未明の時間に，これも初めて行った静岡県浜松市の市場になります。

　他に，横浜の市場と徳島市の市場も照明が暗さが気になったことで印象に残っています。

　宮城県の自衛隊の駐屯地では，同じ荷物を積んできた輪島屋鮮冷の大型車と一緒になりました。運転手のこともいくらか記憶に残っているのですが，荷物を積み込んだ前日にも会っているという記憶があって，金沢市場輸送の会社前であったように思います。

　金沢市場輸送の軽油の給油機は，たしか後ろがブロック塀になっていて，ブロック塀の先はパチンコオークラの駐車場の一部になっていました。その辺りで会ったという気がするのですが，同じ頃に，輪島屋鮮冷の4トン保冷車に乗ってきた被告発人安田敏とも会っています。

　被告発人安田敏のときは，荷物の積み替えだったと思います。船凍イカとも思うのですが記憶がぼやけています。被告発人安田敏からはいきなり自宅アパートに電話があって，そのときに金沢市場輸送に入社するような話となっていました。

　輪島屋鮮冷が金沢市場輸送の仕事をするようになったのは，その平成3年の春頃と思うのですが，１つ別の記憶があって，当時の松任市の海の方の出荷場で，輪島屋鮮冷の大型車の運転手と一緒になったことがありました。年は若かったと思います。

　スイカなのか大根なのか記憶がはっきりしないのですが，ちょうどそのあたりの出荷場で，一度大根を積み込んだ仕事の記憶ははっきりしています。それが京都市の市場行きの運行だったとも思うのですが，異例の珍しい仕事でした。

〈〈〈：Linux Emacs： 2020-07-28（火曜日）16：43 　〈〈〈

* 「ドーナツ食べた入所者死亡 准看護師に逆転無罪 東京高裁 」のNEWS７のニュースがきっかけで知った，冤罪で国民救援会が支援する大仙市事件
  :LOGBOOK:
  CLOCK: [2020-07-28 火 20:37]
  :END:

:CATEGORIES: 冤罪,再審請求

〉〉〉：Emacs： 2020-07-28（火曜日）20：37　 〉〉〉

 -  ドーナツ食べた入所者死亡 准看護師に逆転無罪 東京高裁 | NHKニュース https://www3.nhk.or.jp/news/html/20200728/k10012536621000.html

　上記の事件のテレビニュース，NHKのNEWS７ですが，映像に3,4種類の幟旗の1つに「国民救済」と見えて，それをキーワードにTwitter検索を行っていました。いくつかツイートを見るうち，国民救済会と確信したのでGoogle検索をしたところ以前にも何度か見ているホームページが出ました。

```
再審・冤罪事件 　
●秋田・大仙市事件
●山形・明倫中裁判
●宮城・仙台北陵クリニック筋弛緩剤冤罪事件
●栃木・今市事件
●東京・三鷹事件
●東京・痴漢えん罪西武池袋線小林事件
●東京・小石川事件
●東京・乳腺外科医師冤罪事件
●長野・冤罪あずさ３５号窃盗事件
●長野・あずみの里「業務上過失致死」事件
●福井・福井女子中学生殺人事件
●静岡・袴田事件
●静岡・天竜林業高校成績改ざん事件
●愛知・豊川幼児殺人事件
●三重・名張毒ぶどう酒事件
●滋賀・日野町事件
●京都・長生園不明金事件
●京都・タイムスイッチ事件
●兵庫・えん罪神戸質店事件
●兵庫・花田郵便局強盗事件
●岡山・山陽本線痴漢冤罪事件
●高知・高知白バイ事件
●鹿児島・大崎事件
●米・ムミア事件

［source：］国民救援会の支援事件 - 日本国民救援会 http://www.kyuenkai.org/index.php?%B9%F1%CC%B1%B5%DF%B1%E7%B2%F1%A4%CE%BB%D9%B1%E7%BB%F6%B7%EF
```

　目視で数えて上から1番目に「秋田・大仙市事件」とあります。このコピペで気がついたのですが，2番目が「山形・明倫中裁判」，3番目が「宮城・仙台北陵クリニック筋弛緩剤冤罪事件」となっていて，秋田，山形，宮城という東北の事件が上から並んでいるようです。

　どうも時系列ではなく，事件の場所を北から南に

　時刻は20時51分です。テレビのNHK，ニュースいしわか８４５で意外なニュースが２つ続きました。心神喪失で無罪判決になったことも余り憶えていなかった警察官をサバイバルナイフで刺傷した事件の控訴審で，逆転の有罪判決が出たというニュースでした。

　それでも懲役3年の執行猶予で，被告人は医療の看護措置が続いているというような話でした。弁護士が上告する方向で被告人と話をするとコメントしているというのも印象的で，弁護士の名前はなかったですが，実名の検事のコメントが珍しく長いものとなっていました。

　次にあったのが，能登町の定額給付金詐欺で起訴というニュースでした。被疑者森進一の同姓同名と出ていたのですが，テレビで見たのは初めてで，ネットで調べてもわずかな情報でした。同姓同名のことは地元の人の話を聞いて，そのあとネットで検索していました。

　どちらも全国ニュースにはなっていないと思われ，石川県内ニュースとしてもネットではまだ情報が出ていないかもしれません。これまでの経験で翌日以降になれば，ネットで情報が見つかることはあります。

　なお，地元の情報で，能登町の同姓同名の被害者は，その年齢で森進一のデビュー前ということは確実でした。被害者が特定されそうな情報なので，積極的な報道はされないのかとも考え，ツイートも控えていました。

　昨日の7月27日は，久しぶりに能登町役場新庁舎に行って，用事を済ませてきました。宇出津の町内に来月の回覧板にいれる書面を入れてきた用事で，最終的な修正は別に作成をしていました。これが気がかりで，何かと集中しきれず，一息ついたところです。

森進一　能登町　起訴 - Google 検索 https://t.co/8BMRP6ek8l

　24時間以内でオプション指定をすると，それと思われる情報がなく，全く無関係のものが4件表示されています。

【石川】能登町の給付金詐取　県外の同姓同名者も標的 オンライン申請 未遂に　　　：北陸中日新聞Web https://t.co/kAClTntXJQ 2020年7月21日 05時00分 (7月21日 10時54分更新)

　上記の記事は，Google検索の期間指定なし，「森進一　能登町　起訴」の4番目に出てきたものです。ずいぶん目立つ名前の同姓同名で，それも自分の銀行口座に振り込ませていたというのですから発覚し逮捕されないのが不思議なのですが，現実の事件になります。

　全国ニュースとしてはほとんど見ていないと思いますし，いまテレビでみていて「ドーナッツ裁判　循環に逆転無罪」とやっているNHKのNEWS９でも，取り上げることはなさそうなニュースです。ほとんど思い出すことのなかった事件ですが，本日起訴という石川県内ニュースでした。

　次がGoogle検索でけっこう結果が出たようです。

森進一　能登町　起訴 - Google 検索 https://t.co/8BMRP6ek8l

　24時間以内でオプション指定をすると，それと思われる情報がなく，全く無関係のものが4件表示されています。

【石川】能登町の給付金詐取　県外の同姓同名者も標的 オンライン申請 未遂に　　　：北陸中日新聞Web https://t.co/kAClTntXJQ 2020年7月21日 05時00分 (7月21日 10時54分更新)

　上記の記事は，Google検索の期間指定なし，「森進一　能登町　起訴」の4番目に出てきたものです。ずいぶん目立つ名前の同姓同名で，それも自分の銀行口座に振り込ませていたというのですから発覚し逮捕されないのが不思議なのですが，現実の事件になります。

　全国ニュースとしてはほとんど見ていないと思いますし，いまテレビでみていて「ドーナッツ裁判　循環に逆転無罪」とやっているNHKのNEWS９でも，取り上げることはなさそうなニュースです。ほとんど思い出すことのなかった事件ですが，本日起訴という石川県内ニュースでした。

　次がGoogle検索でけっこう結果が出たようです。

名古屋高裁金沢支部　逆転 - Google 検索 https://t.co/yI80JAnw5Y

警官２人刺傷、逆転有罪　「心神耗弱」、高裁金沢支部：東京新聞 TOKYO Web https://t.co/MBfrqcOB5R ２０１７年８月、交通違反に関する事務手続きのため自宅を訪れた警察官２人をナイフで襲い、重傷を負わせたとして殺人未遂などの罪に問われた金沢市の

警官２人刺傷、逆転有罪　「心神耗弱」、高裁金沢支部：東京新聞 TOKYO Web https://t.co/MBfrqcOB5R 一審金沢地裁は１９年３月の判決で、被告は犯行時は心神喪失状態だったと判断していた。

警官２人刺傷、逆転有罪　「心神耗弱」、高裁金沢支部：山陽新聞デジタル｜さんデジ https://t.co/887j8Cuyvi 被告がナイフを隠し、口頭で退去を求めた点に着目。ナイフで襲うことの危険性などを認識していたとして「心神… https://t.co/ZEIgeKpuCR

山陰中央新報社｜警官２人刺傷、逆転有罪　「心神耗弱」、高裁金沢支部 https://t.co/QqQPpwz4TO 控訴審判決で、名古屋高裁金沢支部（高山光明裁判長）は２８日、無罪とした一審金沢地裁の裁判員裁判判決を破棄、懲役３年、執行猶予５年を言い渡した。

警官2人刺傷、逆転有罪　「心神耗弱」、高裁金沢支部（共同通信） - Yahoo!ニュース https://t.co/J2H2Gj8n7C

警官2人刺傷　重傷負わせた被告に逆転有罪　高裁金沢支部 - 毎日新聞 https://t.co/0pr6BVSdpD 一方で、犯行は「統合失調症の影響による強い不安や恐怖の中で行われた」として執行猶予を付けた。

警官2人刺傷　重傷負わせた被告に逆転有罪　高裁金沢支部 - 毎日新聞 https://t.co/0pr6BVSdpD 検察側は1審で、「限定的な責任能力があった」として懲役8年を求刑していた。

警官2人刺傷　重傷負わせた被告に逆転有罪　高裁金沢支部 - 毎日新聞 https://t.co/0pr6BVSdpD 弁護人は「被告と相談した上で上告するかどうか検討する」と話した。名古屋高検の中村孝次席検事は「責任能力に関する主… https://t.co/6q9G22c70x

警官2人刺傷、逆転有罪 「心神耗弱」、高裁金沢支部 https://t.co/CX0fOGhz4s 高山裁判長は判決理由で、被告がナイフを隠し、口頭で退去を求めた点に着目。ナイフで襲うことの危険性などを認識していたとして「心神耗弱状態にとどまっていた」と認定した。

警官２人刺傷、逆転有罪　「心神耗弱」、高裁金沢支部｜静岡新聞アットエス https://t.co/gOaZJEfJXU

警官２人刺傷、逆転有罪　「心神耗弱」、高裁金沢支部：中日新聞Web https://t.co/WPhjTllo1Y

　大仙市事件について書き始めていたのでした。大仙市というのは割と最近見かけるようになった地名で，平成4年4月1日まで私が長距離トラック運転手をしていた頃は，見たことのない市町村名でした。さきほど確認したところ，平成17年に出来たようです。

　大仙市事件とみてもどのような事件なのか皆目見当がつかなかったのですが，国民救援会のホームページでリンクを開くとすぐに思い出す。とても印象的な事件でした。夕方のテレビで特集を見たことが強く印象的な事件でした。

　かなり気になる事件だったので前にも調べた憶えがあるのですが，冤罪を主張する事件とは，今回初めて知ったように思いました。国民救援会のホームページの個別記事では，確かに冤罪の可能性が高そうな事件ですが，他の事件とは異なり，アピールがほとんどないという印象を受けました。

　連絡先が冤罪を訴える受刑者が服役する山形刑務所ということも記事に掲載があったのですが，山形刑務所は初犯刑務所で短期刑務所とばかり思っていました。福井刑務所の受刑中，職業訓練の募集としてチラシもみていた山形刑務所になります。

　Googleで調べたところ初犯刑務所に間違いはなかったですが，長期の服役囚も収容とのことでした。初犯刑務所の福井刑務所と再犯刑務所の金沢刑務所に共通したのは，短期刑務所で，刑務官に残刑期が8年以内と説明を受けていました。未決通算などを差し引いた日数になります。

　初犯で長期というのは今回始めてみたのですが，最近は刑務所に関する情報をほとんど見かけないとも思っていました。テレビもネットも同じですが，たまたまのタイミングで目にしていない可能性は十分にあるものです。ただやはり全般的に社会の関心は薄そうに感じています。

　時刻は21時53分です。NHKのNEWS９はスポーツコーナーですが，このままニュースの放送はなさそうです。番組表はみていないのですが，北陸朝日放送の報道ステーションにチャンネルを変更します。21時55分からの放送と思います。

　時刻はまだ21時54分ですが，チャンネルを変更すると報道ステーションが始まっていました。大阪の新型コロナウィルス感染拡大，5人以上の飲み会自粛のニュースから始まったようです。

大仙市 - Wikipedia https://t.co/Iwlb4Chxtd 2005年（平成17年）3月22日に、大曲仙北地域の8市町村が合併し誕生した市である。

　周辺の市町村の合併のようですが，消滅したのは大曲市になるようです。国道13号線で山形市から秋田市に向かうと，湯沢市，横手市の次に大仙市があります。秋田市との隣接は確認していませんが，大仙市と秋田市の間に大きな市町村はGoogleマップに見えません。

　この国道13号線で，山形市と秋田市の間というのは，けっこうな回数通行したことがあり，国道46号線で岩手県盛岡市に向かったり，逆に盛岡市から国道13号線に出ることもありました。

　大仙市事件とありますが，私がテレビで報道をみた印象と記憶では，秋田県内でも男鹿半島の付け根，八郎潟と秋田市内の間という記憶，あるいは能代市から大館市の間という記憶もあったように思います。とにかく比較的海に近いというイメージになっていました。

　大仙市事件というのも珍しく感じてならないのですが，事件名に地名がつくのは多いものの，大仙市という市名がついたものは，他に見ていないと思います。国民救援会の支援にはなっていないらしいと知った，北海道恵庭市の事件も，恵庭OL殺害事件などと，市名はなかったと思います。

大仙市事件 - Google 検索 https://t.co/RYvJHmYfxD

　Googleの検索で大仙市事件とあるのは，日本国民救援会のホームページだけのようです。Wikipediaには秋田園児殺害事件とあって，要約に「2006年10月23日，秋田県大仙市で4歳の男児保育園児が他殺体となって発見」とあります。

　2006年というのは平成18年で，10月というのは月始めに，工場の機会で指先をつぶすという怪我をし，休業中に金沢地方検察庁に出向いて遠塚さんと話をし，その場で告訴状を提出した時期になると思います。怪我をしたとき工場で社員の笑顔を見たのもとても印象に残っています。

　この秋田県大仙市の事件のテレビの特集のような報道は，当時の羽咋市のアパートの小さなテレビではなく，宇出津の家のテレビで見たような記憶ともなっています。土日のテレビの番組で，報道特集やそのような感じの週末の番組だったと思います。

```
実母は、一審（秋田地方裁判所）で殺人罪で懲役14年の実刑判決を受けた。判決直後は控訴しない考えを示していたが、判決から8日後、仙台高等裁判所に控訴手続きを取った。

2007年8月27日、秋田刑務所を通して、控訴を取り下げる文書を秋田地裁に提出していたことが判明した（懲役14年の刑が確定）。

［source：］秋田園児殺害事件 - Wikipedia https://ja.wikipedia.org/wiki/%E7%A7%8B%E7%94%B0%E5%9C%92%E5%85%90%E6%AE%BA%E5%AE%B3%E4%BA%8B%E4%BB%B6
```

　上記のWikipediaでは，交際相手の判決が見当たらず，冤罪を訴えているのはこの当時43歳という交際相手になります。実母は殺人罪で懲役14年の判決，2007年8月27日に控訴取り下げの文書を秋田地裁に提出とあります。情報量が少なく，読みやすくはあります。

秋田大仙市発　我が子を惨殺した鬼母がハマった「出会い系サイト」 | FRIDAYデジタル https://t.co/rf6yZxERa2 なんともやりきれないこの事件。その後、美香に対しては懲役14年、畠山に対しては懲役16年の刑が確定している。

　上記のFRIDAYデジタルの記事はさきほど読み終えていたものになります。実母が懲役14年，交際相手が懲役16年とあります。減刑狙いで巻き込み型という冤罪の典型的パターンと思われますが，山中温泉殺人事件に共通するパターンでありながら，弁護士の積極性が見られない発見の特徴です。

```
■物的証拠なし
　畠山さんの犯行を示す客観的・物的証拠は一切ありません。犯行時刻とされる時間帯は１０月下旬といってもまだ暗くはなく、犯行現場とされる駐車場は事件当時大変混雑しており、車内で幼児をその頭皮が剥落するほど殴打すれば、通行人などが当然気づくと思われるのに、目撃者はいません。
　Ｓや畠山さんがＲ君を殴打したのであれば、畠山さんの車に血痕などの痕跡が残るはずですが、警察のルミノール検査などの結果では一切見つかっていません。他にも、殴打したとされる缶やＳの供述でＲ君の頭の血を拭いたとされるタオルなどの物的証拠も発見されていません。

■犯行は不可能
　Ｓの供述によれば、畠山さんの軽自動車の中でＳと畠山さんが交互に失神させるまでＲ君に暴行したことになっています。そのような残虐な行為が白昼、混雑している駐車場の車内でおこなわれたということ自体、信じがたいことですが、国民救援会が暴行の再現実験をおこなったところ、「自白」のような暴行は不可能であることが確認されました。

■作られた「自白」
　警察は畠山さんをホテルに３日間にわたって軟禁状態にして取り調べ、怒鳴ったり暴行を加えるなどして「自白」を強要しました。
　一方、Ｓは親しい男性や友人に、畠山さんの関与はまったく述べず、自分がＲ君に暴行し殺したと告白しています。畠山さんは事件に全く関係なく、「自白」は警察が作り上げたものです。

　現在、再審弁護団を結成し、再審申し立てを準備しています。

［source：］大仙市事件 - 日本国民救援会 http://www.kyuenkai.org/index.php?%C2%E7%C0%E7%BB%D4%BB%F6%B7%EF
```

　上記の引用部分に，「物的証拠なし」，「犯行は不可能」，「作られた「自白」」，「　現在、再審弁護団を結成し、再審申し立てを準備しています。」とあるのですが，他にもちょくちょく見かけてきた日本国民救援会の支援事件とは異なり，初めて再審請求を見かけ，それも準備となっています。

　「Ｓは親しい男性や友人に、畠山さんの関与はまったく述べず、自分がＲ君に暴行し殺したと告白しています。」とあるSは，共犯者とされたと思われる実母ですが，弁護士らが最大限に膨らませて警察批判に利用しようとしたのが，そもそもの冤罪の始まり，弁護士鉄道のスタートに思えてきました。

　事件名の特定が難しい事件の一つでもあり，それが大仙市事件という殺人事件ともわからない事件名となっているのですが，この辺りも弁護士らの下心，都合に合わせた隠蔽体質が垣間見えるように思いました。秋田県には他に，弁護士殺害事件があります。

　今夜はGoogleマップで山形刑務所の場所も確認したのですが，国道13号線から近く，仙台市内に向かう国道286号線の分岐点の少し先となっていました。前にも一度は調べたと思うのですが，不思議と記憶には残っていませんでした。

　さらに意外だったのが山形刑務所の収容者の数で600人を超えていました。このあと調べて確認をしておきたいですが，以前にみた金沢刑務所の収容者数より多いように思います。福井刑務所では入所した平成6年当時，新入教育で220人ぐらいと収容者数を聞いた憶えがあります。

山形刑務所 - Wikipedia https://t.co/KGyFh5F5II 収容定員[編集] \n 605人 \n 舎房棟　工場棟新築済みで増員 現在　1300名以上

　さきほど見たときは気が付かなかったのですが，「舎房棟　工場棟新築済みで増員 現在　1300名以上」とあります。山形市内の規模の小ささというのは，鳥取市，山口市などと並んで県庁所在地としては，特別に感じるものがありました。見通しが良かったのも山形市の特徴です。

金沢刑務所 - Wikipedia https://t.co/Kfhat268gp 収容定員[編集] \n 732人

福井刑務所 - Wikipedia https://t.co/hOlmlHwInr 収容定員[編集] \n ○○○人

　私が金沢刑務所に服役したのは，2週間の新入教育を終えて平成12年の11月に入った頃から満期出所日が平成13年12月31日でした。この秋頃，平成13年の9月頃になりますが，全国的に刑務所の過剰収容が社会問題のピークとなっていました。それでも732人はかなり増えています。

　時刻は23時06分です。報道ステーションが終わり，すぐにチャンネルをテレビ金沢のニュースzeroに変えました。報道ステーションに石川県内のニュースはなかったと思います。

　ここ最近，本当に刑務所に関する話をテレビで見かけていないと思います。しばらく前は受刑者の高齢化や高齢受刑者の介護のことが社会問題として報道されていました。この刑務所の問題は定期的にテレビで見かけていたのですが，たまたまになるのか最近はさっぱり見かけません。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-28 23:14／2019/08/02 21:36 URL： https://twitter.com/kk_hirono/status/1288115579820232704 https://twitter.com/hirono_hideki/status/1157268966416379906  

> 金曜プレミアム・今日、刑務所を出ます～やり直したいオンナたち～  2019年8月2日（金）  20時00分～21時49分  の放送内容 https://t.co/sxfDAXGBpD 　すっかり忘れていたが、さきほどから視聴。墓参りの場面から。  

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「刑務所」の検索結果 - Twilog https://t.co/ewvkYHoxya

　Twilogで確認したのですが，テレビで刑務所の話題を見かけたのは2019年8月2日の「金曜プレミアム・今日、刑務所を出ます～やり直したいオンナたち～」という番組が最後だったようです。この番組は終わりの方で途中から見たようにも思います。

　2007年の8月の終わりに懲役14年の判決確定であれば，未決通算を含め満期でも刑務所を出所している可能性がありそうです。この実母が共犯者でないと主張したという共犯者が懲役16年で山形刑務所に服役，これが大きな冤罪問題になっていないのがとても不思議で，また一つの発見となりました。

　現地での取材による映像を多く見たとも記憶にある名前は知らなかった大仙市事件ですが，それは事件が発覚した当時の報道で，裁判に関する報道はテレビで見ていなかったとも思います。共犯者が無関係と言っているのに，再審請求が準備中というのも奇怪な弁護士現象になります。

〈〈〈：Linux Emacs： 2020-07-28（火曜日）23：30 　〈〈〈

