* 深澤諭史弁護士の「弁護士全体を逆恨み」，と広島の原爆投下を描いた漫画「はだしのゲン」
  :LOGBOOK:
  CLOCK: [2020-08-06 木 09:43]--[2020-08-06 木 11:57] =>  2:14
  :END:

:CATEGORIES: 深澤諭史弁護士,漫画,弁護士

〉〉〉：Emacs： 2020-08-06（木曜日）09：43　 〉〉〉

　さきほどTwitterのタイムラインに「はだしのゲン」を見つけ，いくつかツイートを読んだ後，作者について調べてみました。2012年12月に亡くなっていたことをしったのですが，顔写真を見ても，見覚えがあるとは思えませんでした。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 09:46／2020/08/06 09:37 URL： https://twitter.com/kk_hirono/status/1291173819491799044 https://twitter.com/hirono_hideki/status/1291171540667596803  

> 漫画家の中沢啓治さん死去　「はだしのゲン」作者: 日本経済新聞 https://t.co/XNwI96X1oh  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 09:46／2020/08/06 09:31 URL： https://twitter.com/kk_hirono/status/1291173892472614912 https://twitter.com/hirono_hideki/status/1291170091216842757  

> はだしのゲン - Twitter検索 / Twitter https://t.co/ItXkKZ8MR3  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 09:47／2020/08/06 08:20 URL： https://twitter.com/kk_hirono/status/1291173925859348481 https://twitter.com/hirono_hideki/status/1291152229177540609  

> 2020年08月06日08時19分の登録： REGEXP：”逆恨み”／深澤諭史（@fukazawas）の検索（2014-09-22〜2020-08-05／2020年08月06日08時19分の記録55件） https://t.co/aPdVQASQOg  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 09:47／2020/08/06 08:20 URL： https://twitter.com/kk_hirono/status/1291173941017546754 https://twitter.com/hirono_hideki/status/1291152202766008322  

> 2020年08月06日08時17分の登録： REGEXP：”逆恨み”／データベース登録済みツイート：2020年08月06日08時11分の記録：ユーザ・投稿：154／430件 https://t.co/z3XUcfI96L  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 09:47／2020/08/06 08:20 URL： https://twitter.com/kk_hirono/status/1291174046734987269 https://twitter.com/hirono_hideki/status/1291152176430030848  

> 2020年08月06日07時58分の登録： REGEXP：”井戸謙一”／データベース登録済みツイート：2020年08月06日07時56分の記録：ユーザ・投稿：49／171件 https://t.co/auvk5Ycpso  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 09:47／2020/08/06 08:20 URL： https://twitter.com/kk_hirono/status/1291174056323153920 https://twitter.com/hirono_hideki/status/1291152150089801728  

> 2020年08月06日07時52分の登録： ＼郷原信郎【「深層」カルロス・ゴーンとの対話　起訴されれば９９％超が有罪となる国で】　@nobuogohara＼ツイートで私が吉村知事自身の発言を引用して批判しているのに https://t.co/1Ti8V0SIdB  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 09:47／2020/08/06 08:20 URL： https://twitter.com/kk_hirono/status/1291174069522567174 https://twitter.com/hirono_hideki/status/1291152123619692544  

> 2020年08月06日07時50分の登録： ＼Shoko Egawa　@amneris84＼自治体が法的根拠がないままに、それぞれの緊急事態宣言を出さざるを得ない状況になっているのに、国はどうするつもりだろう。その https://t.co/SjiMn7PdAk  

```
1966年に母を原爆症で亡くしたことを契機に、原爆をテーマにした作品の執筆を決意。68年、「黒い雨にうたれて」を発表し、73年に「はだしのゲン」の連載を週刊少年ジャンプで開始した。「はだしのゲン」は英語やロシア語など翻訳中を含めて18カ国語に訳され、総発行部数は1千万部を超える。

［source：］漫画家の中沢啓治さん死去　「はだしのゲン」作者： 日本経済新聞 https://r.nikkei.com/article/DGXNASDG25016_V21C12A2CC0000?s=5
```

　上記の記事に「はだしのゲン」の週刊少年ジャンプの連載が昭和48年から始まったとあるのですが，私の記憶では昭和50年4月に辺田の浜から宇出津の小棚木に引っ越した後のことになります。

　一つの傾向ですが，辺田の浜に住んでいる頃は，週刊少年チャンピオンと週刊少年マガジンをよく読んでいて，宇出津の小棚木に来てからは週刊少年ジャンプを読むことが多かったと思います。

　辺田の浜に住んでいる頃に，週刊少年ジャンプの連載として印象にあるのは「トイレット博士」でした。その漫画の内容が徐々に変化し，メタクソ団として活動をするようになった時期が，小棚木に来てからのことで，同じジャンプの「はだしのゲン」の連載と重なります。

　メタクソ団の活動は，そのしばらくあとと思うのですが，これも週刊少年ジャンプの連載で「東大一直線」の展開に重なるところがありました。主人公の東大通が東大つまり東京大学に合格，入学，活躍という展開です。この活躍の頃に週刊少年ジャンプは読まなくなりました。

　「トイレット博士」と「東大一直線」は，そのまま深澤諭史弁護士の弁護士としての活躍に重なるところがあると常々考えてきました。昨日も思っていたのですが，漫画家が思い描いた人生を自ら演じるあるいは実践するという感じです。それが現実問題という検討課題でもあります。

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2020/08/05 16:14 URL： https://twitter.com/fukazawas/status/1290908992433041408  

> たまに、こういう、弁護士全体を逆恨みしているみたいな人には遭遇しますね。相談者にもいますし、ネットにはもっといっぱいいます。  
> 属性は統一できないが、クレーマー、ストーカー、DV加害者、モラハラ加害者は弁護士全般への憎悪が強い傾向を… https://t.co/CkxRVLYHNS  

　今確認すると昨日の16時14分が投稿時刻となっていますが，けっこう衝撃的なツイートでした。弁護士による悪夢，それが本件告発事件の実質的な内容でもあるのですが，走馬灯となって各場面が目まぐるしく思い出されました。

　これは今に始まったことではなく，最近は見かけていないですが，深澤諭史弁護士のツイートには「はだしのゲン」に対する格別な思い入れもあるらしく，披瀝がありました。だいたいは町内会長の話となっていました。

　そんなに数はないと思うので，深澤諭史弁護士に限らず，「はだしのゲン」をキーワードに含み記録したデータを次にご紹介します。

```
(py37_env) a66@a66-XTe:~$ dp -p|grep はだしのゲン
 - 2017年11月11日21時09分の登録： ＼いわぽん　@yiwapon　RT：　@fukazawas＼「はだしのゲンの町内会長」現象として，数年前から予言しています。 \n （・∀・） http://hirono2014sk.blogspot.com/2017/11/yiwaponrtfukazawas.html
 - 2018年01月31日11時54分の登録： REGEXP：”はだしのゲンの町内会長”／データベース登録済みツイート：2018年01月31日11時53分の記録：ユーザ・投稿：13／32件 http://hirono2014sk.blogspot.com/2018/01/regexp2018013111531332.html
 - 2018年03月15日10時12分の登録： ＼深澤諭史　@fukazawas＼テレビを付けていたら，はだしのゲンが実写化されて，町内会長の登場シーンかな？っておもったら，ただのニュースだった。 紛らわしいな（・∀・ http://hirono2014sk.blogspot.com/2018/03/fukazawas_25.html
 - 2018年06月02日05時41分の登録： REGEXP：”弁護士の魅力を伝えるためにはだしのゲンの雑コラ作り”／データベース登録済みツイート：2018年06月02日05時40分の記録：ユーザ・投稿：33／33件 http://hirono2014sk.blogspot.com/2018/06/regexp2018060205403333.html
 - 2018年12月09日11時24分の登録： REGEXP：”はだしのゲン”／深澤諭史（@fukazawas）の検索（2015-06-05〜2018-12-09／2018年12月09日11時23分の記録44件） http://hirono2014sk.blogspot.com/2018/12/regexpfukazawas2015-06-052018-12.html
 - 2019年03月02日23時13分の登録： ＼リーチ一発ツモ裏１　@luckymangan＼「実は」反対なんて言ってる輩ははだしのゲンの町内会長だろ。本当に反対の人はハナから反対と言ってる。 http://hirono2014sk.blogspot.com/2019/03/luckymangan.html
 - 2019年07月28日17時56分の登録： ＼弁護士7286　@jmjhjmwtad＼Twitter のイキリ弁護士のイキリ芸、はだしのゲン1巻のゲンと弟の「八百余州の乞食ーデンデン」みたいな乞食芸なんで、売上が殆 http://hirono2014sk.blogspot.com/2019/07/7286jmjhjmwtadtwitter-1.html
 - 2019年08月19日16時06分の登録： REGEXP：”はだしのゲンの町内会長”／データベース登録済みツイート：2019年08月19日16時05分の記録：ユーザ・投稿：15／47件 http://hirono2014sk.blogspot.com/2019/08/regexp2019081916051547.html
 - 2019年10月05日16時38分の登録： ％@fukazawas　深澤諭史％ＲＴ\n全てが終わった後に，はだしのゲンの町内会長みたいなのがたくさん現れることを予想している。\nまあ，すでに準備を始めている人もいますが。\n(･∀･) http://hirono2014sk.blogspot.com/2019/10/fukazawasnnn.html
 - 2019年10月05日16時39分の登録： ％@fukazawas　深澤諭史％法科大学院制度についても，同じようなことが起こりそうだな。\n\nいや，もう起こりつつあるか。未来のはだしのゲンの町内会長みたいなのが一杯出てきそうだ。 http://hirono2014sk.blogspot.com/2019/10/fukazawasnn.html
 - 2019年10月05日16時39分の登録： ％@fukazawas　深澤諭史％大昔に「はだしのゲン」を読んだとき「昔の日本には，こんな時代があったのか。もう二度と無いだろうし，あってはならないけれど，酷い時代もあっ http://hirono2014sk.blogspot.com/2019/10/fukazawas_26.html
 - 2019年10月05日16時39分の登録： ％@fukazawas　深澤諭史％＞ＲＴｓ\nロー制度は，いまでもそうだけれども，今後ますます，はだしのゲンの町内会長みたいなのが大量発生すると思う http://hirono2014sk.blogspot.com/2019/10/fukazawasn.html
 - 2019年10月05日16時40分の登録： ％@fukazawas　深澤諭史％>RTs\n以前，予言？したとおり，本当に，はだしのゲンの町内会長現象が起きているのかもしれない。 http://hirono2014sk.blogspot.com/2019/10/fukazawasrtsn.html
 - 2019年10月05日16時40分の登録： ％@fukazawas　深澤諭史％司法改革の戦犯が誰かなんて，あんまり興味は無いなぁ・・。\nＡ級戦犯より，むしろ，はだしのゲンの町内会長みたいな人がちらほらと。\n（・∀・） http://hirono2014sk.blogspot.com/2019/10/fukazawasnn_5.html
 - 2019年10月05日16時41分の登録： ％@fukazawas　深澤諭史％（；＾ω＾）（利権・ポストはもらったが）俺も大変だったお\n（・∀・）お前は，はだしのゲンの町内会長か http://hirono2014sk.blogspot.com/2019/10/fukazawasn_5.html
 - 2019年10月05日16時41分の登録： ％@fukazawas　深澤諭史％「はだしのゲンの町内会長」現象として，数年前から予言しています。\n（・∀・）https:// http://hirono2014sk.blogspot.com/2019/10/fukazawasnhttps.html
 - 2019年10月05日16時41分の登録： ％@fukazawas　深澤諭史％（＃＾ω＾）（俺様の賃金はもちろん保障されているが）赤字だから利権じゃないんだお！\n（・∀・）お前らは，はだしのゲンの町内会長か。#司法改革コント http://hirono2014sk.blogspot.com/2019/10/fukazawasn_92.html
 - 2019年10月05日16時42分の登録： ％@fukazawas　深澤諭史％まさに「はだしのゲンの町内会長」みたいですね。 http://hirono2014sk.blogspot.com/2019/10/fukazawas_15.html
 - 2019年10月05日16時42分の登録： ％@fukazawas　深澤諭史％はだしのゲンの町内会長現象として予言しています。\n（・∀・）\n（；＾ω＾）（利権・ポストはゲットしたけれども）実は，私は，昔から反対 http://hirono2014sk.blogspot.com/2019/10/fukazawasnn_66.html
 - 2019年10月05日16時42分の登録： ％@fukazawas　深澤諭史％昔，「はだしのゲン」を読んだとき，そこに出てくる町内会長の変節ぶりが，いかにも漫画的な表現だなぁって，おもったけれども。\nまさか，平成の世に，同じ光景を目の当たりにするとは。\n（・∀・；） http://hirono2014sk.blogspot.com/2019/10/fukazawasnn_24.html
 - 2019年10月05日16時43分の登録： ％@fukazawas　深澤諭史％オウム真理教の件については、はだしのゲンの町内会長みたいな立場ですよね、テレビって。\n選挙に出て敗北して…、と、その「前」があったでしょう？\n忘れたとは言わせない。\n（・∀・） http://hirono2014sk.blogspot.com/2019/10/fukazawasnnn_5.html
 - 2019年10月05日16時43分の登録： ％@fukazawas　深澤諭史％美しい国の伝統「はだしのゲンの町内会長現象」  http://hirono2014sk.blogspot.com/2019/10/fukazawas_9.html
 - 2020年03月31日22時39分の登録： ＼7286　@jmjhjmwtad＼しかし、同業者からリアルはだしのゲン町内会長が出るとは。後で「私は自粛には反対だったんだ」みたいなこと言い出すかもね。 http://hirono2014sk.blogspot.com/2020/03/7286jmjhjmwtad_31.html
 - 2020年04月11日23時55分の登録： REGEXP：”はだしのゲン”／深澤諭史（@fukazawas）の検索（2015-06-05〜2019-10-14／2020年04月11日23時55分の記録49件） http://hirono2014sk.blogspot.com/2020/04/regexpfukazawas2015-06-052019-10.html
 - 2020年05月10日14時59分の登録： ＼弁護士足立敬太 @アレクサ 六甲おろしかけて　@keita_adachi＼はだしのゲンは日本人の恐ろしさをよく表現した漫画だったね。 子供ながら怖い怖いと思いながら読ん http://hirono2014sk.blogspot.com/2020/05/keitaadachi.html
```

　深澤諭史弁護士のツイートには，逆恨みにも関連して「病院」，「治療」というキーワードがしばしば出てくるのですが，上記のデータベースの検索結果を見ながら思い出したニュースがありました。昨夜の「ニュースいしかわ８４５」だったと思います。

　民事裁判の控訴審のニュースでしたが，そういえば病院名が出ていなかったような気がしました。これで３回目か４回目になるのですが，いずれもテレビの石川県内ニュースとしてのみみてきたものです。

金沢地方裁判所　控訴 - Google 検索 https://t.co/kal5BDypEh

身体拘束後に死亡　控訴審始まる｜NHK 石川県のニュース https://t.co/pQVu13dw6z

　Googleの検索は，「金沢地方裁判所　控訴」をキーワードに，２４時間以内のオプション指定をしました。該当があったのは１ページめのみの確認ですが，１番目の１件だけです。「NHK石川のニュース」とあります。

```
４年前、石川県内の病院の精神科に入院した４０歳の男性が、体をベッドに拘束されたあと、エコノミークラス症候群を発症して死亡したのは、必要性がない身体拘束が原因だとして、両親が賠償を求めた裁判の２審の審理が名古屋高等裁判所金沢支部で始まり、原告の両親は訴えを退けた１審判決を強く批判しました。

［source：］身体拘束後に死亡　控訴審始まる｜NHK 石川県のニュース https://www3.nhk.or.jp/lnews/kanazawa/20200806/3020005663.html
```

　昨夜テレビで見たのと同じ内容と思いましたが，「石川県内の病院の精神科」とあるだけで病院名はありません。前の裁判のニュースは病院名が出ていましたし，映像もあったかもしれません。

　上記の記事には動画のニュースが付いているのですが，アナウンサーが余り見ない顔で，スタジオの背景が淡い赤茶色に見えるのも見覚えのないものです。記事は本日８月６日で８時４０分とあります。朝に放送されたテレビニュースになるのかもしれません。

　録画していた番組で確認したのですが，アナウンサーは記事にある動画と同じ人のようです。船岡久嗣と名前がでています。スタジオの背景の模様も同じにみえますが，テレビの方が水色に見えます。ニュースいしかわ８４５では，ニュース項目の一覧も出ていません。

　病院の名前で検索したのですが，裁判に関する情報は出てきませんでした。Googleマップで病院名を調べると普通に情報が出てきたので，病院名が間違っていないことは確認しました。・・・と，ここで，間違いに気がついたのですが，「24時間以内」のオプションを付けたままでした。

```
秋山晴康｜2020年3月3日7：27PM

精神科病院へ入院中の大畠一也さんが亡くなったのは病院の不当な身体拘束が原因であるとして、両親が病院を経営する社会福祉法人金沢市民生協会（石川県野々市市、片岡正子理事長）に約８６３０万円の損害賠償を求めた訴訟の判決で、金沢地裁（押野純裁判長）は１月31日、原告の訴えを棄却した（事件の詳細は、本誌１月31日号に掲載）。２０１６年12月、一也さん（当時40歳）は入院先の「ときわ病院」のベッドで６日間身体拘束を受けたうえ、下肢深部静脈血栓による肺動脈血栓塞栓症、すなわちいわゆるエコノミークラス症候群で死亡した。

［source：］「身体拘束され死亡」　遺族が病院提訴も棄却　金沢地裁 ｜ 週刊金曜日オンライン http://www.kinyobi.co.jp/kinyobinews/2020/03/03/antena-661/
```

　週刊金曜日という雑誌は，だいぶん前から情報を見かけていますが，全国紙なのかは不明です。石川県だけなら北國新聞社の「アクタス」になりますが，そういうことはないはずです。週刊金曜日オンラインとあるので，やはり出版もされているのでしょう。宇出津の書店にはなさそうですが。

提訴：「不当拘束」　遺族が精神科病院を - 毎日新聞 https://t.co/sLniXvJPCl

　上記の記事にある「運営する社会福祉法人「金沢市民生協会」」というのは覚えになく，聞いた覚えがないのですが，「ときわ病院」については，以前に時間を掛けて調べました。

　金沢市の卯辰山にあった医療施設が始まりらしく，それがハンセン病の隔離の問題とも重なるものに感じられました。「ときわ病院」の所在地となっている場所は，以前，よく通っていると思うので，病院の建物は見ていたような気もするのですが，そこに精神病院があるとは知らなかったです。

　NHK石川の記事の動画と，昨夜のニュースいしかわ８４５の放送内容は同じだと思います。テーブルの向かって左側3人がご遺族のようですが，右手に二人，弁護士と思われる人物がいて，どちらも弁護士バッチが見えないのが気になりました。

　この「ときわ病院」の訴訟ですが，被告発人木梨松嗣弁護士，被告発人小島裕史裁判長に共通した犯罪性とも関連があると考えていました。そのうちすっかり忘れていたのですが，昨夜のテレビで思い出すことができました。

　NHKのニュースいしかわ８４５ですが，最近はだいたい3,4日に1回のペースで視聴をしていると思います。見ない方が多いので，見落とし，見逃しの可能性もあったわけです。いちおう毎回録画予約をしているのですが，普通に再生することはありません。

　昨日は7月31日に気になるニュースを見つけ，レコーダーの録画一覧を見たのですが，ちょうど7月31日で録画が途切れていました。ディスク容量がいっぱいになったためで，削除で容量をあけました。

　そのついでになったのですが，だいぶん前に録画したまま視聴していなかった番組があり，多少，石川県のかほく市とも関わりがあるのですが，オウム真理教の井上嘉浩元死刑囚の番組でした。井上嘉浩元死刑囚の父親とかほく市の住職の話がメインの番組でした。

　他の石川県内の番組でも，かほく市の住職と井上嘉浩元死刑囚の関係はみていたのですが，京都の仏教系の学校の同窓生で，住職の方が５つ年上，京都からかほく市に来て住職になったということは，その番組で初めて知りました。

　時刻は11時23分です。深澤諭史弁護士のタイムラインの更新を確認したところ，気になるリツイートがあったのですが，少し下に下げると，19時間前として自身のツイートのリツイートが出てきました。「弁護士全体を逆恨み」という本項でメインのツイートです。

@popohito ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@popohito）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW popohito（ぽぽひと@睡眠重視） 日時：2020/08/06 09:05 URL： https://twitter.com/popohito/status/1291163338379005957  

> こういうのは「主語がでかい」って突っ込まれないのかね。 https://t.co/luTK0Q7ylR  

　深澤諭史弁護士のタイムラインでよく見かけるアカウントですが，ブロックされているのか覚えておらず，リツイートを試みたところブロックされていることを確認しました。この「主語がでかい」というツイートは，次のツイートを引用リツイートしたもので，そちらの画像が目立っています。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜nippon_no_tsuki（かしたん） 日時：2020-08-06 11:28／2020/08/06 06:44 URL： https://twitter.com/kk_hirono/status/1291199412689965056 https://twitter.com/nippon_no_tsuki/status/1291127873651105792  

> 広島市民の願いはこれです。  京都や沖縄や県外から来て、原爆とは関係ない話を拡声器で喋って騒いで欲しい訳がない。 https://t.co/ppFecg81VE  

　「弁護士全体を逆恨み」の下にあるのも気になる内容のツイートでした。みかけないプロフィールの名前で，一般のアカウントと思ったのですが，プロフィールに弁護士とありました。

　リストには未登録でした。プロフィールの内容は以前に見かけていたような気がしていたのですが，似たような内容というのはあるかもしれません。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜5ByiYMhnN2468ho（少数意見のひとりごと） 
日時：2020-08-06 11:32／2020/08/05 20:54 URL： https://twitter.com/kk_hirono/status/1291200542954250241 https://twitter.com/5ByiYMhnN2468ho/status/1290979444614549506  

> 地雷依頼者の見分け方　②調子のいいことを言う　初対面で「素晴らしい先生に出会った」とか，調子のいいことをいう人は要注意。あなたが素晴らしい弁護士であるからではなく，もともと，弁護士に対する期待値が高いから調子のいいことを言う。しかし，期待が裏切られると，クレーマーに変身する。  

```
少数意見のひとりごと
@5ByiYMhnN2468ho
自然をこよなく愛する田舎の弁護士。自分の意見は，どちらかというと，少数派という自覚はありますが，論理的におかしいことはおかしいと言いたくなる。クソリプへの有効な反論は、スルーと気づいた。
2020年5月からTwitterを利用しています
484 フォロー中
207 フォロワー

［source：］(5) 少数意見のひとりごとさん (@5ByiYMhnN2468ho) / Twitter https://twitter.com/5ByiYMhnN2468ho
```

　アカウントのヘッダ画像に朱色の吊橋が出てきたのですが，これは見たことがあると思いました。わりと最近で，見かけた回数は1,2回と思います。宇出津の遠島山公園にあるしらさぎ橋とも似ているので印象に残っていました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 
日時：2020-08-06 11:42／2020/08/06 11:35 URL： https://twitter.com/kk_hirono/status/1291202916200534016

 https://twitter.com/s_hirono/status/1291201174083796992  

> 2020-08-06-113406_少数意見のひとりごとさん　（@5ByiYMhnN2468ho）　／　Twitter.jpg https://t.co/gks8LMX4r7  

```
地雷依頼者の見分け方　③事案の緊急性を強調する。事案について，いかに緊急であるかを強調する。しかし，実際は，事案が緊急であるわけではなく，相談者にとって緊急なだけ。すなわち，相談者のキャパの小ささが，事案を緊急に感じさせている。キャパの小ささは，そのまま弁護士に対するクレームへ。
```

　上記の内容のツイートのリツイートができず，速攻でブロックされたのかと思ったのですが，その様子はなく，自分のアカウントの方で投稿制限が掛かったようにも思え，結局，ページの再読込をすると，「このアカウントは存在しません」と出ました。

〈〈〈：Emacs： 2020-08-06（木曜日）11：57 　〈〈〈

* 「げんしばくだんがおちると　ひるがよるになって　ひとはおばけになる」という深澤諭史弁護士のリツイートに感じた弁護士爆弾の危険性

:CATEGORIES: 深澤諭史弁護士

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-06 20:55／2020/08/06 20:53 URL： https://twitter.com/kk_hirono/status/1291342113934696454 https://twitter.com/s_hirono/status/1291341615110348801  

> 2020-08-06-202852_深澤諭史さんがリツイートBuzzFeed　Japan　News@BFJNews·10時間「げんしばくだんがおちると　ひるがよるになって　ひと.jpg https://t.co/Mgpo3r7rBl  

　Windows10で作業をしているとき見かけたのですが，すぐにWindows10を終了し，起動したUbuntuで記録の作成を行いました。それが上記の2020-08-06-202852として記録されているスクリーンショットになります。

(py37_env) a66@a66-XTe:~$ tu fukazawas 4
RT fukazawas（深澤諭史）｜fukazawas（深澤諭史） 日時：2020-08-06 20:56／2020-08-06 18:00 URL： https://twitter.com/fukazawas/status/1291342422425735168 https://twitter.com/fukazawas/status/1291297969287831552
> 財産の調べ方と強制執行：ネット上の表現トラブル（とその誤解）Ｑ＆Ａを更新２５ - 弁護士 深澤諭史のブログ https://t.co/iBYvnFS759  \n 差し押さえは大変だし、肝心なことはなかなか言えないという話。

RT fukazawas（深澤諭史）｜fukazawas（深澤諭史） 日時：2020-08-06 20:56／2020-08-06 10:08 URL： https://twitter.com/fukazawas/status/1291342318268645378 https://twitter.com/fukazawas/status/1291179302365601792
> 恐ろしいほど，最初の電話での態度って，その人の本質が出ますよね。良くも悪くも。 \n 「敷居」の高低の問題というより，「防犯フェンス」の問題ですね。 https://t.co/Hf6lSC9Mll

RT fukazawas（深澤諭史）｜fukazawas（深澤諭史） 日時：2020-08-06 20:56／2020-08-06 19:48 URL： https://twitter.com/fukazawas/status/1291342258327805952 https://twitter.com/fukazawas/status/1291325280875720704
> 弁護士ドットコムコミュニティ「受任に慎重さを要する人たち」非常に，興味深い。 \n 弁護士限定匿名掲示板というだけあって，率直な話が聞ける。 \n （・∀・）（＾ω＾）

RT fukazawas（深澤諭史）｜BFJNews（BuzzFeed Japan News） 日時：2020-08-06 20:13／2020-08-06 10:15 URL： https://twitter.com/fukazawas/status/1291331481667690496 https://twitter.com/BFJNews/status/1291180944699908096
> 「げんしばくだんがおちると　ひるがよるになって　ひとはおばけになる」 \n  \n これは、原爆を経験した小学生が書いた詩。残された言葉たちを読み継いできた朗読劇が、いま問いかけるものとは。（籏智広太 @togemaru_k） \n  \n 【New】「… https://t.co/cP7FNQ1hDS

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜BFJNews（BuzzFeed Japan News） 日時：2020-08-06 21:01／2020/08/06 10:15 URL： https://twitter.com/kk_hirono/status/1291343705387855874 https://twitter.com/BFJNews/status/1291180944699908096  

> 「げんしばくだんがおちると　ひるがよるになって　ひとはおばけになる」  これは、原爆を経験した小学生が書いた詩。残された言葉たちを読み継いできた朗読劇が、いま問いかけるものとは。（籏智広太 @togemaru_k）  【New】「… https://t.co/cP7FNQ1hDS  

　深澤諭史弁護士のタイムラインにはTwitterカードとして泣いている子供の写真が掲載されていました。原爆が広島に透過された昭和20年当時の写真なのかは不明ですが，訴求性の高い写真で，心打たれるものがありました。

　これが深澤諭史弁護士のタイムライン，リツイートでみたことの衝撃を記録しないわけにはいきません。これまで数々の先の大戦に対する深澤諭史弁護士のツイート，その軽薄さと短慮には目を見張るものがあり，何かが取り憑いているのではと真剣に考えさせられるところです。

　弁護士資格を持ってしゃぶり尽くそうという，狂った欲望を強く，強く感じてきたのが深澤諭史弁護士にTwitterタイムラインになりますが，他に専念するためもあり，ストレートに表現することは自重をしてきましたし，気に入らないことはすべて誹謗中傷とするのも弁護士頭の特徴です。

　しかし，深澤諭史弁護士のリツイートのリンクにある記事を読んで，これは黙っていられないという衝動に駆られました。今まで溜め込んできたものの爆発もあったとは思いますが，たちまち頭に浮かんだのが深澤諭史弁護士の社会的危険性を表現する「弁護士爆弾」という言葉です。

　こういう弁護士のツイート，リツイートを見かけると頭に浮かんで鳴り響くのが，次の曲で，歌詞が「弁護士バッド　狂った欲望　狂気の印」と聞こえてきます。

黄金バット　オープニング - YouTube https://t.co/vVmjhrsTfV

　これまでけっこうな期間，隠忍自重をしてきたことになりますが，まさに深澤諭史弁護士の「弁護士一代深澤稼業」だと思いました。全ては自己愛と自分の利益への我田引水，そこに尽きると思います。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中） 日時：2020-08-06 21:24／2020/05/28 23:05 URL： https://twitter.com/kk_hirono/status/1291349446152749056 https://twitter.com/kk_hirono/status/1266007623670751232  

> あらためて法律のプロ，専門家という以前に，弁護士商売，弁護士一代深澤稼業という言葉以外に思い浮かぶものはない，歴史的にも貴重な資料の発見と思います。まさに社会を汚染する弁護士病の蔓延，拡散です。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中） 日時：2020-08-06 21:24／2019/11/20 22:34 URL： https://twitter.com/kk_hirono/status/1291349472358801413 https://twitter.com/kk_hirono/status/1197146081416503296  

> 深澤諭史弁護士は、自身に不都合あるいは不利益と感じるネット上の反応について、単純に中傷などと決めつけておりますが、これも弁護士業界の消費者被害として、深刻重大なものを感じており、まさに弁護士脳の社会汚染としての公害であると捉えております。弁護士一代深澤稼業です。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中） 日時：2020-08-06 21:24／2019/08/12 21:39 URL： https://twitter.com/kk_hirono/status/1291349504478724096 https://twitter.com/kk_hirono/status/1160893453120655361  

> 「弁護士一代深澤稼業」というのも、深澤諭史弁護士のツイートをみながらしばしば頭に浮かんできた言葉の一つです。それも表現の1つかと思います。非弁に強いこだわりで弁護士会での活動もしているという深澤諭史弁護士なので、正規版にも見えますが、その辺りを含めた印象です。  

刑事告発・非常上告＿金沢地方検察庁御中(@kk_hirono)/「深澤稼業」の検索結果 - Twilog https://t.co/zZ9mxJEzLZ

　深澤諭史弁護士の固執は弁護士という職業，資格への執着に尽きると思いますが，ここまで自分の職業に執着し，自己都合の良さだけに拘泥するというのも他のは見ないもので，弁護士としての執筆や表現力の高さというのもあるのかもしれないですが，超絶に凄まじい欲望の爆発です。

　前にも書いたことですが，深澤諭史弁護士の出身の東京大学法科大学院と所属の第二東京弁護士会には，深澤諭史弁護士に対する製造物責任と社会に対する安全配慮義務違反を問いたいところで，深澤諭史弁護士の反応次第では，いつでも必要とされる権利を行使する用意があるつもりです。

〈〈〈：Linux Emacs： 2020-08-06（木曜日）21：34 　〈〈〈

* 「げんしばくだんがおちると　ひるがよるになって　ひとはおばけになる」という深澤諭史弁護士のリツイートで，改めて考えたハウス食品のテレビCM「おうちで食べよう。」のこと

:CATEGORIES: 深澤諭史弁護士

　ある意味，深澤諭史弁護士には感謝の念もあるのですが，弁護士の凄まじき独善税，異常性，危険性を思い知らせてくれていました。これは現在進行系でもあります。

- RT fukazawas（深澤諭史）｜BFJNews（BuzzFeed Japan News） 日時：2020/08/06 20:13／2020/08/06 10:15 URL： https://twitter.com/fukazawas/status/1291331481667690496 https://twitter.com/BFJNews/status/1291180944699908096

> RT @BFJNews: 「げんしばくだんがおちると　ひるがよるになって　ひとはおばけになる」  
>   
> これは、原爆を経験した小学生が書いた詩。残された言葉たちを読み継いできた朗読劇が、いま問いかけるものとは。（籏智広太 @togemaru_k）  
>   
> 【New】「おとうちゃん どうして…  

　率直に，この世の中にこれほどの大馬鹿者がいるのかと，日々の更新で思い知らされてくれるのが深澤諭史弁護士であり，そのTwitterタイムラインになります。これは法務検察，石川県警察に対しても喫緊も問題性として伝えないわけにはいきません。改めて思い知らされました。

　スマホでの写真撮影をしているもののまだ確認はしていないところですが，10日か2週間ほど前からテレビで，印象深いハウス食品のテレビCMが再開されました。前と全く同じかどうかも確認はできなかったのですが，TwitterやGoogleで検索をしました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 21:54／2020/08/06 20:26 URL： https://twitter.com/kk_hirono/status/1291357061024890883 https://twitter.com/hirono_hideki/status/1291334954723323906  

> 「おとうちゃん どうして…」子どもたちの残した原爆の詩が、いま問いかけるもの https://t.co/ktLFjarUSJ 「げんしばくだんがおちると　ひるがよるになって　ひとはおばけになる」（小学3年、坂本はつみ）  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 21:54／2020/08/06 20:33 URL： https://twitter.com/kk_hirono/status/1291357073108643842 https://twitter.com/hirono_hideki/status/1291336630020608000  

> (1) ハウス食品　CM - Twitter検索 / Twitter https://t.co/FYZqmZxtdD トレンドではない検索。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜MaroYonebayashi（米林宏昌） 日時：2020-08-06 21:54／2020/08/04 08:09 URL： https://twitter.com/kk_hirono/status/1291357088556277766 https://twitter.com/MaroYonebayashi/status/1290424509095264257  

> 2003年に作画を担当したハウスのCMが突然流れててビックリ。　 曲を変えてやってたのね。  https://t.co/zqykNSuzNc  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 21:55／2020/08/06 20:34 URL： https://twitter.com/kk_hirono/status/1291357104083628033 https://twitter.com/hirono_hideki/status/1291336738334359553  

> ハウス食品グループ企業広告　おうちで食べよう。 | ハウス食品グループ本社 https://t.co/1y1eMnJeg3  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜70_90_hougaku（70〜90年代邦楽 ご紹介bot） 日時：2020-08-06 21:55／2020/08/02 20:09 URL： https://twitter.com/kk_hirono/status/1291357132525170689 https://twitter.com/70_90_hougaku/status/1289880942970990595  

> No.222：♪ギンギラギンにさりげなく/近藤真彦 1981年にリリースされた近藤真彦さんの4枚目のシングル。 ハウス食品「ククレカレー」と富士フイルム「フジカラー写ルンです」のCMソングとしても起用された大ヒット楽曲であります(… https://t.co/0hEsL0yk0A  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜morino_wakaba（ハルカゼ） 日時：2020-08-06 21:55／2020/08/03 12:22 URL： https://twitter.com/kk_hirono/status/1291357190213652480 https://twitter.com/morino_wakaba/status/1290125849971187712  

> ハウス食品「おうちで食べよう」のCM、 そうそう こうだったよね～と、見るたびほっこり。 母が作ってくれた夏服に下駄！ ゴザを敷いてままごと。 ウチにいた犬とブチの入り方まで似てる～😭  未曾有の夏が来ました。 できるだけ心安らぐ… https://t.co/Qa8100SKA2  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜RUNA60931938（RUNA） 日時：2020-08-06 21:55／2020/08/04 14:07 URL： https://twitter.com/kk_hirono/status/1291357230269308928 https://twitter.com/RUNA60931938/status/1290514653617909762  

> ハウス食品「おうちで食べよう」シリーズCM「庭の千草」vrが普通に流れててびびった  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜yamada_azumi（山田安曇） 日時：2020-08-06 21:55／2017/12/12 22:32 URL： https://twitter.com/kk_hirono/status/1291357244127244289 https://twitter.com/yamada_azumi/status/940575081498951680  

> いい歌だなあ、と思ってなんの曲だっけと記憶をたぐるとこの曲だってことがよくある。ハウス食品のCMとか "The Last Rose of Summer : Flute 庭の千草  - フルート演奏" を YouTube で見る - https://t.co/enNPJIPbeD  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜DRAKO1964（DRAKO） 日時：2020-08-06 21:55／2018/03/12 21:00 URL： https://twitter.com/kk_hirono/status/1291357272552009728 https://twitter.com/DRAKO1964/status/973166858265247744  

> インドネシア出身の歌姫、シェリナ・ムナフさんがバックの歌「庭の千草」を担当したハウス食品の TV-CM「おうちで食べよう」シリーズ。(^_^)v↓ https://t.co/hmEmhZNkaW  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 21:55／2020/08/06 20:42 URL： https://twitter.com/kk_hirono/status/1291357293464784897 https://twitter.com/hirono_hideki/status/1291338870039048193  

> インドネシアの歌手・Sherinaが歌う「庭の千草」はテレビＣＭ・ハウス食品のおうちで食べよう。 : exblog ガドガド https://t.co/xVbLOcEXPY 2017年 02月 20日  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 21:55／2020/08/06 21:35 URL： https://twitter.com/kk_hirono/status/1291357321675673600 https://twitter.com/hirono_hideki/status/1291352185414930437  

> - 742：2020-08-06_21:35:19 ＊ 「げんしばくだんがおちると　ひるがよるになって　ひとはおばけになる」という深澤諭史弁護士のリツイートに感じた弁護士爆弾の危険性 https://t.co/nFv15U7aW2  

　意外にGoogleの検索の情報は乏しく，声が違っているようにも感じたのですが，以前に見たインドネシア人歌手の歌声なのかも確認が出来ませんでした。私にはこの庭の千草という曲の歌詞が前から，「深澤諭史弁護士の・・・」と聞こえてしまいます。

　Twilogで調べてみますが，庭の千草という曲のことを知ったのは，ハウス食品のテレビがきっかけだったと思います。一時，ネットでの情報が途絶えて，弁護士商売の介入なのかと想像をしていたのですが，つい最近になってテレビCMで復活を見たのは本当にありがたいことでした。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 22:03／2017/01/03 12:36 URL： https://twitter.com/kk_hirono/status/1291359248819998721 https://twitter.com/hirono_hideki/status/816125934172573697  

> House(ハウス食品) 新CM「おうちで食べよう 」シリーズ編のCM曲はシェリナ・ムナフ『庭の千草』 https://t.co/1UyC7e69LP  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 22:03／2017/01/04 10:36 URL： https://twitter.com/kk_hirono/status/1291359325047283720 https://twitter.com/hirono_hideki/status/816458369233866752  

> 2017年01月03日16時29分26秒の記録＿ストーカーをキーワードにした弁護士アカウントのの作業と庭の千草 https://t.co/edYlqHJrxF  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 22:04／2017/01/04 10:37 URL： https://twitter.com/kk_hirono/status/1291359392701362176 https://twitter.com/hirono_hideki/status/816458391555973120  

> 2017年01月03日16時54分54秒の記録＿ストーカの弁護士アカウントのツイート検索をブログ投稿する作業と庭の千草 https://t.co/UTJ5KSvcEH  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 22:04／2017/02/28 23:07 URL： https://twitter.com/kk_hirono/status/1291359514206171137 https://twitter.com/hirono_hideki/status/836578630641848324  

> 庭の千草 ／アイルランド民謡 編曲：名田綾子 https://t.co/qmHkuwRNaS  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 22:04／2017/04/09 20:14 URL： https://twitter.com/kk_hirono/status/1291359596527853571 https://twitter.com/hirono_hideki/status/851030454492844035  

> ハウス食品グループのＣＭの「庭の千草」。昨日、昼に見た連続テレビ小説で、田んぼで合唱する場面があった。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 22:05／2017/06/27 23:11 URL： https://twitter.com/kk_hirono/status/1291359666702708736 https://twitter.com/hirono_hideki/status/879703684866875392  

> zen-on piano solo 「庭の千草」 全音 絶対ハズさない！心に届く聴かせる名曲 https://t.co/uZVYHjC1Lz  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 22:05／2017/07/13 00:08 URL： https://twitter.com/kk_hirono/status/1291359701582651392 https://twitter.com/hirono_hideki/status/885153854320496641  

> Shaylee - 庭の千草 - The last rose of summer ( Japanese and Alphabet lyrics) https://t.co/Gk4MGWZpAe  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 22:05／2017/08/05 22:37 URL： https://twitter.com/kk_hirono/status/1291359733815730176 https://twitter.com/hirono_hideki/status/893828313873096704  

> 庭の千草 関屋敏子 https://t.co/TnTVvK1MdZ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 22:05／2017/12/12 22:29 URL： https://twitter.com/kk_hirono/status/1291359814870683650 https://twitter.com/hirono_hideki/status/940574345016963072  

> 庭の千草のメロディが流れている。報道ステーション。「女たちの飲ん兵衛横丁」という。鐵の町釜石で愛され続けてきたとも。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 22:06／2018/05/17 23:12 URL： https://twitter.com/kk_hirono/status/1291359891165048833 https://twitter.com/hirono_hideki/status/997117704803729408  

> バーモンドカレーのＣＭは、「庭の千草」を思い出す。ＣＭで知ってすごく懐かしい気がしたが、実際には過去に聞いた覚えのない曲だった。同じ頃、海蔵院末観音堂へ。竹林も発見。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 22:06／2019/02/07 23:56 URL： https://twitter.com/kk_hirono/status/1291359937344319488 https://twitter.com/hirono_hideki/status/1093524020044025856  

> Shaylee - 庭の千草 (Niwa no chigusa) 歌詞付/ アイルランド民謡 The last rose of summer(Japanease) - YouTube https://t.co/7sn4eK54Mg  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 22:06／2019/02/08 00:16 URL： https://twitter.com/kk_hirono/status/1291359976305246209 https://twitter.com/hirono_hideki/status/1093528980139868162  

> Shaylee - 庭の千草(アイルランド民謡) / The last rose of summer (Japanese lyrics) - YouTube https://t.co/qruWU51tJD  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 22:06／2019/02/08 00:22 URL： https://twitter.com/kk_hirono/status/1291360012468498432 https://twitter.com/hirono_hideki/status/1093530382228586497  

> 関屋敏子 Toshiko Sekiya - 庭の千草 The last rose of summer (1934) - YouTube https://t.co/gFaI0hWvRQ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 22:06／2019/02/08 00:29 URL： https://twitter.com/kk_hirono/status/1291360045519663104 https://twitter.com/hirono_hideki/status/1093532088089731073  

> THE NORMAN CANDLER ORCHESTRA - THE LAST ROSE OF SUMMER　　庭の千草 - YouTube https://t.co/iSvcG30LA8  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 22:06／2019/02/08 00:40 URL： https://twitter.com/kk_hirono/status/1291360085151584257 https://twitter.com/hirono_hideki/status/1093534947724255232  

> House(ハウス食品) 新CM「おうちで食べよう 」シリーズ編のCM曲はシェリナ・ムナフ『庭の千草』 - CMの曲名 https://t.co/9slFrSX8VZ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 22:07／2019/12/29 20:29 URL： https://twitter.com/kk_hirono/status/1291360128982061062 https://twitter.com/hirono_hideki/status/1211247842993426432  

> ままごと : あなざ～まいんど https://t.co/cVzMrPqnHP ‘庭の千草’　という曲もこのＣＭにすごくマッチしてる。 　　　　　少し調べてみました。 　　　　　歌ってるのは、インドネシア生まれで現在は日本を拠点に… https://t.co/EseM6G4SuR  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 22:07／2019/12/29 20:31 URL： https://twitter.com/kk_hirono/status/1291360167326441473 https://twitter.com/hirono_hideki/status/1211248459715510272  

> 唱歌　庭の千草 - YouTube https://t.co/aQkeFkM08N 『小学唱歌集 第三編』明治17年（1884年）3月発行 作詞 里見義　原曲はアイルランド民謡 The Last Rose of Summer  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 22:07／2019/12/29 20:35 URL： https://twitter.com/kk_hirono/status/1291360222234083328 https://twitter.com/hirono_hideki/status/1211249268494721024  

> 庭の千草　歌詞の意味 https://t.co/tb3TYQn0pF 先立たれ一人残されても　白菊のように力強く生きていきたい  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-06 22:07／2019/12/29 21:16 URL： https://twitter.com/kk_hirono/status/1291360290055962624 https://twitter.com/hirono_hideki/status/1211259715407077377  

> 庭の千草 - YouTube https://t.co/VlYFDnWUOd  

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「庭の千草」の検索結果 - Twilog https://t.co/rr3EPRYAVE

　白菊という花のことがよくわからなかったのですが，過去のリンクを見ると，昭和40年代によく目にした花で，最近になってまた見かける機会が増えた花だと思いました。花と言っても草に近いようです。

```
歌詞（原文に近い仮名表記）
庭の千草も　むしのねも
かれてさびしく　なりにけり
あゝしらぎく　嗚呼白菊
ひとりおくれて　さきにけり

露もたわむや　菊の花
しもにおごるや　きくの花
あゝあはれあはれ　あゝ白菊
人のみさおも　かくてこそ

［source：］庭の千草　歌詞の意味 http://www.worldfolksong.com/songbook/ireland/niwano-chigusa.html
```

```
「露もたわむ」については、先立たれ一人残されて涙に暮れる様子が目に浮かぶ。

「しもにおごる」は古い漢文に由来する表現で、漢字では「霜に傲る」と表記される。

「傲る」とは、霜に負けずに力強く咲く菊の花の様子を表しており、ここでは悲しみに対して力強く生きていこうとする人物の気丈な様子が暗示されていると考えられる。

なお、寒さに耐える菊を表す「傲霜（ごうそう）」という言葉もある。

［source：］庭の千草　歌詞の意味 http://www.worldfolksong.com/songbook/ireland/niwano-chigusa.html
```

```
「あはれ」は、寂しさや悲しさを表す古語の感動詞。「みさお（操）」は、不変の意思・節操、伴侶への貞節などの意味がある。

庭に咲いた周りの草花（庭の千草）が皆枯れてしまった中、秋冬の厳しい寒さを一人耐え忍ぶ菊の花のように、人間も強く生きていきたいものだというメッセージが込められているように感じられる。

原曲のアイルランド民謡『夏の名残のバラ（夏の最後のバラ）』の歌詞に通じるものがあるが、原曲では、愛する人に先立たれて一人残される悲しみがより強調されている。両曲の歌詞を比較してみると面白い発見があるかもしれない。

［source：］庭の千草　歌詞の意味 http://www.worldfolksong.com/songbook/ireland/niwano-chigusa.html
```

　上記に引用をしましたが，「「あはれ」は、寂しさや悲しさを表す古語の感動詞。「みさお（操）」は、不変の意思・節操、伴侶への貞節などの意味がある。」などとあります。

```
昭和42年4月1日～昭和43年3月23日　よみうりテレビ系で放映。
戦前、紙芝居大人気を呼んだヒーローが高らかな笑いもそのままにアニメとなってやってきた。世界征服を企む謎の生命体、ナゾーが次々に送り込んでくる超兵器や怪獣をアトランティス大陸の守護神黄金バットが粉砕する。

［source：］黄金バット　オープニング - YouTube https://www.youtube.com/watch?v=jzeR2Te60hc
```

　「昭和42年4月1日～昭和43年3月23日　よみうりテレビ系で放映。」と上記の引用にありますが，昭和39年11月26日生まれの私には，実際にみているのか記憶が微妙な境界線が，このテレビ放送の黄金バッドになります。再放送などあまりなかった時代が続くので記憶は間違いないはずです。

　最近は特にことある場面で，この黄金バットのテーマ曲があたまに浮かび，鳴り響いていました。バットとバッドの違いもありますが，物心ついた頃の記憶が，現在の弁護士不信，危険性のハザードに結びついています。

　「黄金バット　オープニング」という上記のYouTube動画は何度みてもカラーで映像がきれいすぎるのですが，昭和50年の4月以降に宇出津の小棚木の家に引っ越すまで，私の家のテレビは白黒テレビでした。カラーになってからもそれほど画質に改善はなかったと思います。

響けチンドン！あなたの心に～絆その１２チンドン芸能社(東京) - YouTube https://t.co/PZ0WulJkiJ

《戦時歌謡》暁に祈る（"Akatsuki Ni Inoru"）with Eng/Sub - YouTube https://t.co/IVtn56ga0j

出征兵士を送る歌 - YouTube https://t.co/xtCFZ89W7P

父よあなたは強かった　霧島昇・伊藤久男・松原操・二葉あき子 - YouTube https://t.co/HZTW0jiwGJ

【軍歌】軍歌聞き比べ　出征兵士を送る歌　林伊佐緒　伊藤久男 - YouTube https://t.co/nCF8CTA1d9

出征兵士を送る歌 - YouTube https://t.co/Bhplr8qao1

出征兵士を送る歌 - YouTube https://t.co/3CLEaz8ruK

月月火水木金金 - YouTube https://t.co/ICdQdNnrto

【ドリフの軍歌】月月火水木金金 - YouTube https://t.co/GPGhdIpYns

《軍歌》軍艦マーチ（"Gunkan māchi "～March "Man-of-War"～）with Eng/Sub - YouTube https://t.co/Vxwr8LoQT7

日本軍歌「出征兵士を送る歌」（歌詞付き） - YouTube https://t.co/bDcVth8qHL

ああ紅の血は燃ゆる - YouTube https://t.co/a5Z64sOEpf

何をすさぶか　小夜嵐 - Google 検索 https://t.co/IEUXAioGQv

あゝ紅の血は燃ゆる - YouTube https://t.co/GNZwoRYAjz

鶴田浩二 あゝ紅の血は燃ゆる 歌詞&amp;動画視聴 - 歌ネット https://t.co/80b9BUY73U

鶴田浩二　神風特攻　軍歌　ラバウル航空隊　紅の血は燃ゆる　夢飛行 - YouTube https://t.co/g72mKJ1iCu

《軍歌》歩兵の本領("Hohei no Honryō"- Specialty of Infantry)with Eng/Sub - YouTube https://t.co/sOd6orJygK

歩兵の本領 - YouTube https://t.co/7pUXudUbiu

步兵の本領 - YouTube https://t.co/JKOM1r8dFK

父よあなたは強かった - YouTube https://t.co/MYMRcr3QJK

海軍小唄（ズンドコ節） - YouTube https://t.co/WL6WoIhUFh

ダンチョネ節 - YouTube https://t.co/mpII7lWvWp

可愛いスーちゃん - YouTube https://t.co/s6qbhn9HaY

可愛いスーチャン - YouTube https://t.co/HPWUr5hZnx

南洋航路 - YouTube https://t.co/3yBu5alDQN

ラバウル小唄 - ばんくガールズ - YouTube https://t.co/2mubHfV4sS

ドンパン節 - YouTube https://t.co/MBlDJNeXp3

どんぱん節 - YouTube https://t.co/ikv28n7Orb

どんぱん節 「秋田県民謡」 - YouTube https://t.co/dvq2w7vV2x

どんぱん節（はげ頭） - 平馬 秋田民謡 - YouTube https://t.co/qG5wMLDUgP

必殺仕事人 Ⅰ エンディング 「浜千鳥情話」 Full　金沢明子 - YouTube https://t.co/iZHNKYndfs

宮さん宮さん(トンヤレ節) - YouTube https://t.co/4GqB58vFUG

出征兵士を送る歌 - YouTube https://t.co/5y0qLSCXJI 2,170,640 回視聴•2013/08/14 \n ￼ \n 5964 \n ￼ \n 532 \n ￼ \n 共有 \n ￼ \n 保存 \n ￼

月月火水木金金 - YouTube https://t.co/jmnq1swCAV

グッド・ナイト・ベイビー　ザ・キングトーンズ　ＵＰＣ‐０１０３ - YouTube https://t.co/xe7mbH2oZA

グッド・ナイト・ベイビー　ザ・キングトーンズ　ＵＰＣ‐０１０３ - YouTube https://t.co/xe7mbH2oZA 4,200,755 回視聴•2012/01/16 \n ￼ \n 8905 \n ￼ \n 639 \n ￼ \n 共有 \n ￼ \n 保存 \n ￼

鉄道唱歌 (明治・大正・昭和初期の唱歌） - YouTube https://t.co/RHBkvrmNcH

どんぱん節 Folk Song of Japan 平野繁松 - YouTube https://t.co/b27WGy0FRI

どんぱん節 - YouTube https://t.co/XlTIueSvo4

ドンパン節 - YouTube https://t.co/WZb9dry40F

ドンパン節／あや - YouTube https://t.co/DNRIJ3RnFo

ドンパン節 - YouTube https://t.co/6OpWQ8zrJf

平成２９年角館町観桜会舞台⑧ドンパン節 - YouTube https://t.co/sPWj1UCGta

東京音頭 - YouTube https://t.co/KmwlTcK8R2

ドンパン節　日本民謡同好会　第53回 南御堂盆おどり　2015.08.27 - YouTube https://t.co/taxDaOY7a8

鶴見音頭・ドンパン節　青木 遥　緑・納涼盆踊り大会　2016.07.22 - YouTube https://t.co/mBrCKCukMN

2019年東京丸の内盆踊り②　ドンパン節 - YouTube https://t.co/Rhp33mDEsz  \n ￼￼ \n 0:02 / 7:15￼￼￼￼ \n 2019年東京丸の内盆踊り②　ドンパン節 \n 350 回視聴•2019/08/09 \n ￼ \n 1 \n ￼ \n 0 \n ￼ \n 共有 \n ￼ \n 保存 \n ￼

〈〈〈：Linux Emacs： 2020-08-07（金曜日）08：13 　〈〈〈

