* 神奈川県小田原市の村松謙弁護士（神奈川県弁護士会）と，神奈川県横浜市で活動中の可能性のある匿名弁護士うの字

** 2020年9月1日9時14分から同年同月3日午前8時3分までの弁護士鉄道の歴史における，うの字のツイートの記録

 - 2020年09月03日09時42分の登録： TWEET：”2020-09-01 09:14〜2020-09-03 08:03”／うのじ（@un_co_the2nd）の検索（2020年09月03日09時42分の記録38件） http://hirono2014sk.blogspot.com/2020/09/tweet2020-09-01-09142020-09-03.html

 - （01／38） RT un_co_the2nd（うのじ）｜ichigo_ba（スヤスヤいちご） 日時：2020-09-01 09:14:00 +0900／2020-09-01 08:23:00 +0900 URL： https://twitter.com/un_co_the2nd/status/1300587899155443712 https://twitter.com/ichigo_ba/status/1300574992812310528

> 一審無罪も「弁護側」が有罪主張へ 前橋の女子高生死傷事故｜上毛新聞ニュース https://t.co/PAUeO4Z6lu
> どういうことだってばよ

 - （02／38） RT un_co_the2nd（うのじ）｜o2441（弁護士大西洋一） 日時：2020-09-01 09:26:00 +0900／2020-09-01 09:25:00 +0900 URL： https://twitter.com/un_co_the2nd/status/1300590851567923200 https://twitter.com/o2441/status/1300590510491328512

> 「どこでも仕事できることを実証する」目的なら淡路島で勤務させる必要ないよね。あと、経営陣は東京に残るんだろうなと思って記事読んだら、異動は営業と人事だった。やっぱり。
>
> パソナ、本社機能を淡路島に移転　社員１０００人を異動(産経新… https://t.co/vqqf66WgHY

 - （03／38） TW un_co_the2nd（うのじ） 日時：2020-09-01 09:44:00 +0900 URL： https://twitter.com/un_co_the2nd/status/1300595438479839233

> 共同親権になれば自由に子供と接触できるという幻想はどっから湧いてくるんだろうか

 - （05／38） TW un_co_the2nd（うのじ） 日時：2020-09-01 11:31:00 +0900 URL： https://twitter.com/un_co_the2nd/status/1300622395066130434

> 責任能力のほうで無罪になったっぽい書き方なんだが、責任能力無罪だったらなおさら無責にならんくね？

 - （07／38） TW un_co_the2nd（うのじ） 日時：2020-09-01 11:35:00 +0900 URL： https://twitter.com/un_co_the2nd/status/1300623271751163905

> 一審国選てことは本人は資力なし、家族が控訴審で私選選任、という読みはアタリだと思う

 - （08／38） TW un_co_the2nd（うのじ） 日時：2020-09-01 11:37:00 +0900 URL： https://twitter.com/un_co_the2nd/status/1300623890612326402

> 家族が選任したとしても、被告人の不利になる弁護活動はしちゃいかんし。
> 記事がどこまで正確なのかわかんないけど、一審無罪なのに有罪弁論するよって部分がマジだったら裁判所は特別代理人選任申立を検察官に促すべきじゃないかなー…

 - （15／38） TW un_co_the2nd（うのじ） 日時：2020-09-01 14:20:00 +0900 URL： https://twitter.com/un_co_the2nd/status/1300664717640306689

> 冤罪独白！小6女児へのわいせつで逮捕された男性が語る、真実と勾留56日間 (2019年2月28日) - エキサイトニュース https://t.co/tDQm2zXupI

 - （20／38） TW un_co_the2nd（うのじ） 日時：2020-09-01 18:31:00 +0900 URL： https://twitter.com/un_co_the2nd/status/1300728066088398854

> 殺された被害者をネタに暴行強迫要件についてデマ流してる奴、自分こそが二次被害を生んでる張本人って自覚ないよね

 - （22／38） TW un_co_the2nd（うのじ） 日時：2020-09-01 18:55:00 +0900 URL： https://twitter.com/un_co_the2nd/status/1300734123183546371

> 暴行強迫要件に関する、死ぬほど抵抗しないといけないっていうデマは共通敵を作るというアジテーションの基礎に適ってるんで、仮に暴行強迫要件がなくなっても代わりを見つけて吹聴するんだろうなって思ってますよ

 - （24／38） TW un_co_the2nd（うのじ） 日時：2020-09-02 06:53:00 +0900 URL： https://twitter.com/un_co_the2nd/status/1300914645914451968

> 道徳的なヒトビトが、自分こそが犯罪者予備軍であると考えないのが不思議でならない。道徳は他人ではなく己を律するためのものなのに。

　ちょっと思い出したのですが，「ヒトビト」といううの字の文字使いは，言霊を感じさせるもので，マレビト信仰のことを思い出しました。弁護士の原点の一つがこのうの字にあるとみています。

 - （25／38） TW un_co_the2nd（うのじ） 日時：2020-09-02 08:48:00 +0900 URL： https://twitter.com/un_co_the2nd/status/1300943766203711489

> 少年法がらみは調べものしないし論理も破綻してるのが勢いよく湧いてるからミュートワード設定しとこ…

 - （26／38） TW un_co_the2nd（うのじ） 日時：2020-09-02 10:09:00 +0900 URL： https://twitter.com/un_co_the2nd/status/1300964111660888064

> 「娘も罪に問われるべき」って何言ってんだ。娘が「あいつを殺して」とまで言ったならちょっと揺らぐけど、そんな事情は記述がない。10歳なら自分の嘘でまさか親がおじさん殺すまで予見しないだろ…(たぶん)
> そもそも両親が収監されたで十分な… https://t.co/sI0KsvqA1T

 - （28／38） TW un_co_the2nd（うのじ） 日時：2020-09-02 12:50:00 +0900 URL： https://twitter.com/un_co_the2nd/status/1301004490590412800

> せっせと抵抗しないと同意だとデマ広げてる人、何がしたいんですか。
> そもそもあの事件、犯行が実際にわいせつ目的だったかすら怪しいでしょ

　福岡市の大型商業施設女子トイレでの事件のことと思います。15歳少年による女性殺害事件で，被害者は21歳だったかもしれません。テレビでは未だに一度もみていないニュースです。

 - （29／38） TW un_co_the2nd（うのじ） 日時：2020-09-02 12:52:00 +0900 URL： https://twitter.com/un_co_the2nd/status/1301004933815181314

> 捜査機関には、それなりにストーリーが成立する供述らしきものをマスコミに公開する動機があるんですよ
> 記事には支離滅裂な供述をしてるというような記述があるものもあったのに…

 - （30／38） TW un_co_the2nd（うのじ） 日時：2020-09-02 12:55:00 +0900 URL： https://twitter.com/un_co_the2nd/status/1301005865655218176

> 被害者の発見場所がトイレだったから、捜査機関としては猥褻目的だったというふうに誘導したほうがやりやすい、くらい想像できんかね

 - （31／38） TW un_co_the2nd（うのじ） 日時：2020-09-02 12:58:00 +0900 URL： https://twitter.com/un_co_the2nd/status/1301006571191689217

> 捜査機関側からのリークが多すぎるのと、被疑者の年齢や漏れてきてる生育環境からすると、誘導等のリスクがかなりあると思うんで、ただでさえアレな捜査機関のリーク情報を鵜呑みにするのはとてもまずい事案だと思うのよね

　盤石の弁護士鉄道の基盤，レールを想起させるうの字のツイートで，安定の警察批判，警察不信を煽りまくり，爆走しているかのようです。

 - （33／38） TW un_co_the2nd（うのじ） 日時：2020-09-02 13:50:00 +0900 URL： https://twitter.com/un_co_the2nd/status/1301019649866256385

> 人が亡くなってる事件でレイプされるときに抵抗しないと無罪になっちゃうから云々とかやってるの、?の目には貞操守るために死ねって言ってるように見えるんですよね。その人が亡くなったことより強制性交等罪の有罪無罪が優先しちゃうのかよと。

　福岡の事件は，女子トイレが殺害場所になったという他は，追尾をしていたぐらいしか具体的な情報が出ていなかったはずなのですが，うの字以外にも話を膨らませ，意味付けを行っている弁護士のツイートが散見されました。

 - （34／38） TW un_co_the2nd（うのじ） 日時：2020-09-02 16:30:00 +0900 URL： https://twitter.com/un_co_the2nd/status/1301060019396304897

> 「上司殺してえ〜」
> だと嫌悪感ないのに、
> 「幼女犯してえ〜」
> だと嫌悪感があるんだとしたら、それは表出されたのが犯罪願望だからではないですよね

　ここ最近，モトケンこと矢部善朗弁護士（京都弁護士会）のツイート，タイムラインでも「小児性愛」なるキーワードが目立っています。

 - （35／38） TW un_co_the2nd（うのじ） 日時：2020-09-02 16:37:00 +0900 URL： https://twitter.com/un_co_the2nd/status/1301061720144658432

> 小学4年生〜高校生までの間に学校に放火しようと考えなかった日はないんで、犯罪願望がダメとか言われてもなあ

　木造校舎の学校は少ないはずなので，放火は困難だろうと考えていたのですが，このうの字のツイートをみてしばらくたってから，秋田港でイカ釣り漁船の爆発炎上のニュースがあり，ちょっと考えられないような勢いで船が燃えていました。

秋田港で漁船爆発か　複数の船が燃える【動画】｜秋田魁新報電子版 https://t.co/fPZvYWrDwp 秋田市消防本部によると、３日午前１０時１０分ごろ、秋田市の秋田港でイカ釣り漁船とみられる船が爆発したと１１９番があった。

　いくつか記事を読んだのですが，まだイカ釣り漁船の爆発炎上の原因が分かっていないようです。係留されていた漁船が火災で漂流を始めたともテレビで解説がありました。地元にも同じようなイカ釣り漁船がいますが，物凄い可燃物らしく，気になっています。

 - （36／38） TW un_co_the2nd（うのじ） 日時：2020-09-02 21:58:00 +0900 URL： https://twitter.com/un_co_the2nd/status/1301142506386501632

> 犯罪願望なんて許されないって言ってる勢は、学校に火つけたろとか担任刺したろとかクラスのあいつを吊るしてやろうとか考えることなく生きてきたんですね…恵まれてますね…

 - （38／38） TW un_co_the2nd（うのじ） 日時：2020-09-03 08:03:00 +0900 URL： https://twitter.com/un_co_the2nd/status/1301294643074617344

> ボコボコにされなければ、死ぬほど抵抗しなければ強姦と認められないっていうデマカセは、貞操のために死ねって言下に述べてるとしか思えない
> なぜフェミニストを名乗る人々や女性の権利擁護を訴える人がこのデマカセを撒き続けるんだろ
> 男女問わず、意に反して性交を強いられたら即通報して下さい

　フェミニストと聞いて思い出すのは，伊藤和子弁護士と太田啓子弁護士です。検索のためのまとめ記事を作成しました。

 - 2020年09月04日13時30分の登録： @KazukoIto_Law（Kazuko　Ito　伊藤和子　香港に自由を！周庭さんなどへの弾圧に抗議します！）のツイート　”．＊”　3227／3227：2020-04-07_0018〜2020-09-04_1231　2020年09月04日13時30分の記録 http://hirono2014sk.blogspot.com/2020/09/kazukoitolawkazukoito322732272020-04.html

　まず伊藤和子弁護士です。「福岡」をキーワードにページ内検索を行ったところ，該当したツイートは次の1件のみです。3227件中の検索です。

RT KazukoIto_Law（Kazuko Ito 伊藤和子　香港に自由を！周庭さんなどへの弾圧に抗議します！）｜asahi_seibu（朝日新聞福岡報道センター） 日時：2020-08-28 08:37／2020-08-26 19:06 URL： https://twitter.com/KazukoIto_Law/status/1299128834306924546 https://twitter.com/asahi_seibu/status/1298562384055767041
> 福山雅治さん、長崎から平和発信へ　「被爆樹木」通じて：朝日新聞デジタル https://t.co/kyK3cOErZY #戦後７５年特集

　次に「少年」でやってみます。

RT KazukoIto_Law（Kazuko Ito 伊藤和子　香港に自由を！周庭さんなどへの弾圧に抗議します！）｜8bit_HORIJUN（堀 潤　J U N H O R I） 日時：2020-06-23 07:10／2020-06-23 06:50 URL： https://twitter.com/KazukoIto_Law/status/1275189387458834432 https://twitter.com/8bit_HORIJUN/status/1275184412842287106
> きょうは沖縄慰霊の日。当時何があったのか。聞いて欲しい。元沖縄県知事大田昌秀さん、生前の証言。 \n →「2個の手榴弾を渡されて、半袖半ズボンで戦場に送られた」沖縄戦少年兵の実態を証言(堀潤) - Y!ニュース https://t.co/G7fmmnvj4n

RT KazukoIto_Law（Kazuko Ito 伊藤和子　香港に自由を！周庭さんなどへの弾圧に抗議します！）｜MPD_ikusei（警視庁少年育成課） 日時：2020-07-05 08:21／2020-04-01 11:17 URL： https://twitter.com/KazukoIto_Law/status/1279555866258051072 https://twitter.com/MPD_ikusei/status/1245173306048671744
> 毎年４月は「AV出演強要・「JKビジネス」等被害防止月間」です。 \n AV出演強要、JKビジネス等の各種トラブルに関する相談ができる場所があります。 \n ひとりで悩まないでください。 https://t.co/6Wd5a0m05O

　次に太田啓子弁護士です。

 - 2020年09月04日13時34分の登録： @katepanda2（弁護士　太田啓子　「これからの男の子たちへ」（大月書店））のツイート　”．＊”　3192／3192：2020-07-10_1309〜2020-09-04_0923　2020年09月04日13時32分の記録 http://hirono2014sk.blogspot.com/2020/09/katepanda2319231922020-07-1013092020-09.html

RT katepanda2（弁護士 太田啓子　「これからの男の子たちへ」（大月書店））｜YahooNewsTopics（Yahoo!ニュース） 日時：2020-07-22 08:57／2020-07-22 08:56 URL： https://twitter.com/katepanda2/status/1285725643305623553 https://twitter.com/YahooNewsTopics/status/1285725310483337216
> 【傾斜マンション JR九州ら謝罪】 \n https://t.co/8OOR6i5Lva \n \n 福岡市東区のマンションで傾きが生じ、基礎となるくいが固い地盤に未到達だったことが判明した問題で、販売したJR九州ら3社のトップがマンションを訪れ、住民に謝罪。くい8本が固い地盤に届いていなかった。

RT katepanda2（弁護士 太田啓子　「これからの男の子たちへ」（大月書店））｜akabishi2（akabishi2） 日時：2020-08-04 17:23／2020-08-01 20:17 URL： https://twitter.com/katepanda2/status/1290563929244971008 https://twitter.com/akabishi2/status/1289520513736351745
> ７月は結局大田原市だけとは。 \n 特に都教委は画期的だった。 \n \n とはいえ、育鵬社使用中の、 \n 横浜武蔵村山大阪東大阪泉佐野金沢小松加賀呉防府岩国松山四国中央新居浜上島町小笠原石垣与那国、 \n 府県教委では埼玉千葉宮城大阪山口香川愛媛福岡、 \n 横浜市立の一貫校と大阪の特別支援… \n \n 以上がこれからです💦 https://t.co/BL6eLBL2zH

RT katepanda2（弁護士 太田啓子　「これからの男の子たちへ」（大月書店））｜akabishi2（akabishi2） 日時：2020-08-04 17:23／2020-08-04 17:06 URL： https://twitter.com/katepanda2/status/1290563983183814657 https://twitter.com/akabishi2/status/1290559607677435904
> 横浜はついに育鵬社を一掃（道徳は東書）。 \n \n 武蔵村山大阪東大阪泉佐野金沢小松加賀呉防府岩国松山四国中央新居浜上島町小笠原石垣与那国、 \n 府県教委では埼玉千葉宮城大阪山口香川愛媛福岡、 \n 大阪の特別支援。 \n \n ちなみに武蔵村山は今年は遅くて18日（火）だって。

RT katepanda2（弁護士 太田啓子　「これからの男の子たちへ」（大月書店））｜nhk_1945yasuko（やすこ＠ひろしまタイムライン） 日時：2020-08-04 23:21／2020-07-31 10:29 URL： https://twitter.com/katepanda2/status/1290654216000884746 https://twitter.com/nhk_1945yasuko/status/1289010289665552392
> 26歳主婦,結婚2年目,初めての妊娠中 \n 女子学習院卒,東京大久保生まれ→結婚で京都左京区→廣島の緑井(夫の実家)に疎開中。軍医の夫つぐおは福岡の折尾に出征。絵を描くことや刺繍が好き、甘いものも好き。宝物は7歳から続ける日記。毎日を丁寧に。日々の記録をつづっています。 \n #ひろしまタイムライン

　次に「少年」です。

RT katepanda2（弁護士 太田啓子　「これからの男の子たちへ」（大月書店））｜nhk_1945yasuko（やすこ＠ひろしまタイムライン） 日時：2020-08-06 09:21／2020-08-06 09:17 URL： https://twitter.com/katepanda2/status/1291167498554036224 https://twitter.com/nhk_1945yasuko/status/1291166487726743556
> 【1945年8月6日】 \n \n トラックには人、人、人。二十名ほどでしょうか。 \n …中に一人だけ、傷のなさそうな少年がいたけれど、すぐに気が狂ったように暴れて死んでしまった。 \n 廣島でいま　なにがおこってるの…？ \n \n #ひろしまタイムライン　#広島 \n #もし75年前にSNSがあったら

　全部で54件の該当があるのですが，ツイートが古いものから並んでいるので，検索では不都合です。福岡の少年の事件は8月28日の発生であったと思います。近接したものを掲載します。

RT katepanda2（弁護士 太田啓子　「これからの男の子たちへ」（大月書店））｜sodium（しお（汐街コナ）@既刊「死ぬ辞め」「ずっとやめ」発売中） 日時：2020-08-27 22:37／2020-08-23 19:46 URL： https://twitter.com/katepanda2/status/1298977888297873413 https://twitter.com/sodium/status/1297485424684724224
> なんでフェミニストが少年誌の表現にあれこれ言うというと、こういうことです。 \n 「子供のスカートめくりくらい許される」…これは「性犯罪の肯定」です。 \n こういう価値観の大人が、そういう価値観の作品を描き、その価値観が少年たちに受け継がれてゆく。 \n それを止めてくれって言ってるのです。

RT katepanda2（弁護士 太田啓子　「これからの男の子たちへ」（大月書店））｜free_andpeace（はし@子どもの権利） 日時：2020-09-02 16:27／2020-08-31 22:19 URL： https://twitter.com/katepanda2/status/1301059207207071745 https://twitter.com/free_andpeace/status/1300422882036654081
> 「県警によると、少年は複雑な環境で育ち、家族と離れて暮らしていた。」あぁ、やはりか･･･。大切にされていなければ、人を大切にはできない。何かできなかったものか。 \n /逮捕少年は中3　福岡女性刺殺(時事通信) \n https://t.co/oeMK7noU8R

RT katepanda2（弁護士 太田啓子　「これからの男の子たちへ」（大月書店））｜rainbowfoster（レインボーフォスターケア（RFC）） 日時：2020-09-02 01:16／2020-09-01 09:00 URL： https://twitter.com/katepanda2/status/1300829892011991042 https://twitter.com/rainbowfoster/status/1300584328615714822
> 「わいせつ目的、抵抗され刺した」少年が供述　福岡刺殺：朝日新聞デジタル \n \n 性犯罪が起きたら、被害者が「あなた、ちゃんと抵抗しましたか？抵抗してないよね？本当に無理強いなの？」とか聞かれるよね…。こんな結果になることもあるのに。 \n \n どんなに怖かっただろう…。 https://t.co/9nuZ0ANSqc

RT katepanda2（弁護士 太田啓子　「これからの男の子たちへ」（大月書店））｜mhmakino（牧野雅子 ／ Masako Makino） 日時：2020-09-01 08:20／2020-09-01 08:11 URL： https://twitter.com/katepanda2/status/1300574322562494464 https://twitter.com/mhmakino/status/1300572009005371393
> 抵抗され（たので）殺された。 \n \n 「わいせつ目的、抵抗され刺した」少年が供述　福岡刺殺：朝日新聞デジタル https://t.co/yLqpL7P95v

　54からカウントダウンする方法で検索したことで，効率よく見つけ出すことが出来ました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜rainbowfoster（レインボーフォスターケア（RFC）） 日時：2020-09-04 13:57／2020/09/01 09:00 URL： https://twitter.com/kk_hirono/status/1301746248068677633 https://twitter.com/rainbowfoster/status/1300584328615714822  

> 「わいせつ目的、抵抗され刺した」少年が供述　福岡刺殺：朝日新聞デジタル  性犯罪が起きたら、被害者が「あなた、ちゃんと抵抗しましたか？抵抗してないよね？本当に無理強いなの？」とか聞かれるよね…。こんな結果になることもあるのに。  どんなに怖かっただろう…。 https://t.co/9nuZ0ANSqc  

　テキストのみのツイートでは，太田啓子弁護士本人のツイートと思いながら読んでいたのですが，実際はリツイートでした。132件の引用ツイートと表示されていますが，返信ツイートというのはないようです。

 - 引用ツイート / Twitter https://twitter.com/rainbowfoster/status/1300584328615714822/retweets/with_comments  

　取得したページタイトルが「引用ツイート / Twitter」となっていて意外ですが，タイムラインに法クラや弁護士とおぼしきアカウントのツイートは見当たりませんでした。

* 「【ご報告】私のツイッター上での発言がいずれも弁護士としての品位を失うべき非行には当たらないことが日弁連にも認められました。」という喜久山大貴弁護士（京都弁護士会）の固定されたツイート

** 「当たり前だろ。ヨコチン氏はこのような濫用的な懲戒請求をしたことを恥じ、喜久山先生に詫びるべきだ。」という三浦義隆弁護士のツイート，喜久山大貴弁護士に対する懲戒請求の件

:CATEGORIES: 三浦義隆弁護士,懲戒請求,喜久山大貴弁護士

@lawkus ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@lawkus）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW lawkus（ystk） 日時：2020/09/03 10:38 URL： https://twitter.com/lawkus/status/1301333722973663232  

> 当たり前だろ。ヨコチン氏はこのような濫用的な懲戒請求をしたことを恥じ、喜久山先生に詫びるべきだ。  
> もっとも不当懲戒請求として不法行為にまであたるかというと、そこは微妙な気はするが。 https://t.co/YCM1jxCIIY  

@yokotindeka_DJ ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@yokotindeka_DJ）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW yokotindeka_DJ（ヨコチン刑事㊙️実況） 日時：2020/09/03 01:28 URL： https://twitter.com/yokotindeka_DJ/status/1301195403312783360  

> 京都新聞の新聞紙です  
>   
> 弁護士が、弁護士の肩書を付してミニブログ（ツイッター）において、ある神社たちの出した意見広告を指して「犬のうんこ拾う紙にちょうどいい」と評することは、品位を害したとは言えないとする事例。  
>   
> （京都弁護士会） https://t.co/69gBsQhbIL https://t.co/kjnzuRE42z  

　画像として添付されている書面は，京都弁護士会事務長上山浩子のハンコ付きで，2020年1月20日となっています。今日になって知ったことですが，ヨコチン氏は日弁連に不服申立ての手続きはしておらず，喜久山大貴弁護士の固定ツイートは，別の懲戒請求の可能性が高いとのことです。

　昨日に，三浦義隆弁護士のタイムラインでツイートを見かけたのが始まりと思うのですが，具体的な時間のことはよく憶えていません。それでもスクリーンショットの記録はしていると思います。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-04 14:59／2020/09/03 22:38 URL： https://twitter.com/kk_hirono/status/1301761831376093184 https://twitter.com/s_hirono/status/1301514854298251267  

> 2020-09-03-191806_ystk@lawkus当たり前だろ。ヨコチン氏はこのような濫用的な懲戒請求をしたことを恥じ、喜久山先生に詫びるべきだ。もっとも不当懲戒請求と.jpg https://t.co/mKtQGOrMvA  

　夕方の早い時間にツイートを見ていたという記憶だったのですが，19時18分というのはほとんど暗くなった時間で夜です。三浦義隆弁護士のツイートを確認すると，「日時：2020/09/03 10:38」ということで午前中のツイートとなっていました。

 - 2020年09月03日19時18分の登録： ＼ystk　@lawkus＼当たり前だろ。ヨコチン氏はこのような濫用的な懲戒請求をしたことを恥じ、喜久山先生に詫びるべきだ。 もっとも不当懲戒請求として不法行為にまであた http://hirono2014sk.blogspot.com/2020/09/ystklawkus_11.html

　ツイートのまとめ記事としての記録もほぼ同時刻だったと確認しました。

　ヨコチン氏のツイートも「日時：2020/09/03 01:28」となっていて，そのツイートに三浦義隆弁護士が直接，反応をしたようです。弁護士の品位，弁護士の懲戒請求のあり方としても，考えさせられるところの問題です。

　発端となる喜久山大貴弁護士のツイートを直にみていただけに，三浦義隆弁護士の謝罪すべき，濫用的懲戒請求というのはかなりの疑問があります。

 - 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： @lawkus（ystk）のツイート　”ヨコチン”　4／3222：2020-05-02_0532〜2020-09-04_1413　2020年09月04日15時08分の記録　：embed http://hirono2014sk.blogspot.com/2020/09/lawkusystk432222020-05-0205322020-09.html

　次に，もともとの喜久山大貴弁護士の発言について調べました。

** 京都弁護士会が，「よって，本件行為は品位を失うべき非行にはあたらず」とした，喜久山大貴弁護士の天皇陛下御即位，京都新聞広告を「犬のうんこを拾う紙」発言と，他の弁護士らの反応の記録

```
(py37_env) a66@a66-XTe:~$ dp -p|grep 犬のうんこ
 - 2019年05月02日00時08分の登録： ＼喜久山大貴　@kikuyamahiroki＼犬のうんこ拾う紙にちょうどいい http://hirono2014sk.blogspot.com/2019/05/kikuyamahiroki.html
 - 2019年05月02日00時23分の登録： ＼鳩屋　@haya_rt＼そう言うこと言うと自由法曹団のチラシやパンフも犬のうんこ拾う紙に使われて誰も意見なんか聞いてくれなくなる。  http://hirono2014sk.blogspot.com/2019/05/hayart.html
 - 2019年05月02日10時54分の登録： 犬のうんこ発言について。皇室にも神社仏閣にも特段の権威を認めないので、ただの紙なんだから犬のうんこ処理に使ったり引越しの時に皿包んだり芋焼くのに使ってなんの問題もないと思 http://hirono2014sk.blogspot.com/2019/05/blog-post_2.html
 - 2019年05月02日11時42分の登録： ＼喜久山大貴　@kikuyamahiroki＼なぜ「犬のうんこ拾う紙」とすら言えない気がするのかを考えることが、この国の人々が自由や平等を獲得するのに大切なこと（適当） http://hirono2014sk.blogspot.com/2019/05/kikuyamahiroki_71.html
 - 2019年05月02日11時42分の登録： ＼喜久山大貴　@kikuyamahiroki＼人を犬のうんこ呼ばわりとは失礼な。\n報告しとこ。 http://hirono2014sk.blogspot.com/2019/05/kikuyamahiroki_89.html
 - 2019年05月02日12時30分の登録： ＼喜久山大貴　@kikuyamahiroki＼何もすり替わってません。天皇即位を奉祝する記事広告を掲載した新聞紙では犬のうんこを拾ってはいけない理由をどうぞ述べてみてくだ http://hirono2014sk.blogspot.com/2019/05/kikuyamahiroki_47.html
 - 2019年05月02日12時30分の登録： ＼橋本太地（弁護士・あなたのみかた法律事務所）　@kojin_syugi＼返信先: @kikuyamahirokiさん\n誰も「この新聞紙では犬のうんこを拾ってはいけない」 http://hirono2014sk.blogspot.com/2019/05/kojinsyugi-kikuyamahiroki.html
 - 2019年05月02日22時49分の登録： ＼暇弁(暇とは言ってない)　@himaben1st＼「犬のうんこ」発言、無粋だとは思うがそこまで寄ってたかって袋叩きにしないといかんか？懲戒請求は尚更。 http://hirono2014sk.blogspot.com/2019/05/himaben1st_23.html
 - 2019年06月16日09時32分の登録： ＼asty_md　@asty_md＼水戸家裁下妻支部で「犬のうんこですら肥料になるのに、君たちは何の役にも立たない産業廃棄物以下じゃないか」と発言したとされた裁判官につい http://hirono2014sk.blogspot.com/2019/06/astymdastymd.html
```

　そもそもこの喜久山大貴弁護士に対しては，明石花火大会歩道橋事故の警備で，警察を根こぎ愚弄していたのが，なにより強烈に印象的でした。喜久山大貴弁護士のTwitterが公開設定に戻っていたことは知っていましたが，再び注目したのは昨日。

　昨日は祭礼員会の役員として，珠洲警察署能登庁舎の所長，石川県警察珠洲警察署の署長室に挨拶回りに行っていました。過去に石崎奉燈祭では見物の若い女性の死亡事故も起こっており，刑事裁判として有罪判決が出たとも聞いています。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜kikuyamahiroki（喜久山大貴） 日時：2020-09-04 15:42／2020/09/02 21:12 URL： https://twitter.com/kk_hirono/status/1301772646414086144 https://twitter.com/kikuyamahiroki/status/1301130812134313984  

> 【ご報告】私のツイッター上での発言がいずれも弁護士としての品位を失うべき非行には当たらないことが日弁連にも認められました。京都の綱紀委員会の判断に懲戒請求者側から異議申出がなされていましたが、無事棄却されました。  

　次に，スクリーンショットの記録になりますが，Twilogで古いものからリツイートをしていきます。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜1961kumachin（中村元弥） 日時：2020-09-04 15:45／2020/09/04 12:03 URL： https://twitter.com/kk_hirono/status/1301773364239818752 https://twitter.com/1961kumachin/status/1301717400899842050  

> 起訴状匿名問題も動き出した  性犯罪の被害者、匿名で起訴状に記載を検討　森法相：朝日新聞デジタル https://t.co/JRZZrYdvdx  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-04 15:45／2019/05/02 13:18 URL： https://twitter.com/kk_hirono/status/1301773404165472259 https://twitter.com/s_hirono/status/1123804017682014211  

> 2019-05-02-000907_喜久山大貴さんのツイート：　”犬のうんこ拾う紙にちょうどいい…　”.jpg https://t.co/XrIaFkvUBB  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-04 15:45／2019/05/02 13:20 URL： https://twitter.com/kk_hirono/status/1301773452261482496 https://twitter.com/s_hirono/status/1123804383441977344  

> 2019-05-02-105210_モトケンさんがリツイート＞　うの字（@un_co_the2nd）：　犬のうんこ発言について。皇室にも神社仏閣にも特段の権威を認めないので、ただの紙なんだ.jpg https://t.co/TMPmmBHbDR  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-04 15:45／2019/05/02 13:21 URL： https://twitter.com/kk_hirono/status/1301773481730650112 https://twitter.com/s_hirono/status/1123804676716212225  

> 2019-05-02-114535_喜久山大貴さんがリツイート＞　うの字（@un_co_the2nd）：　犬のうんこ発言について。皇室にも神社仏閣にも特段の権威を認めないので、ただの紙なん.jpg https://t.co/ahX0Eg80c0  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-04 15:46／2019/05/05 08:12 URL： https://twitter.com/kk_hirono/status/1301773524881690630 https://twitter.com/s_hirono/status/1124814089576783873  

> 2019-05-04-221032_弁護士神原元さんがリツイート＞　喜久山大貴（@kikuyamahiroki）：　犬のうんこ拾う紙にちょうどいい.jpg https://t.co/wMlceMgVuS  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-04 15:46／2019/05/05 08:12 URL： https://twitter.com/kk_hirono/status/1301773552857673728 https://twitter.com/s_hirono/status/1124814164520652800  

> 2019-05-04-221100_喜久山大貴さんのツイート：　”犬のうんこ拾う紙にちょうどいい…　”.jpg https://t.co/STCqBgC8Lc  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-04 15:46／2019/05/06 13:29 URL： https://twitter.com/kk_hirono/status/1301773588148576256 https://twitter.com/s_hirono/status/1125256120572891137  

> 2019-05-05-232731_喜久山大貴さんのツイート：　”犬のうんこ拾う紙にちょうどいい…　”.jpg https://t.co/FYFbGD2UXF  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-04 15:46／2019/06/16 10:54 URL： https://twitter.com/kk_hirono/status/1301773669388021760 https://twitter.com/s_hirono/status/1140075043449294848  

> 2019-06-16-093240_asty_mdさんのツイート：　”水戸家裁下妻支部で「犬のうんこですら肥料になるのに、君たちは何の役にも立たない産業廃棄物以下じゃないか」と発言したとされ.jpg https://t.co/J3xJvervaO  

非常上告-最高検察庁御中_ツイッター(@s_hirono)/「犬のうんこ」の検索結果 - Twilog https://t.co/48VdLhcN6S

### 2019年5月5日に記録されていた喜久山大貴弁護士の「犬のうんこ拾う紙にちょうどいい」というツイート，天皇陛下即位をお祝いする京都新聞に向けたもので，懲戒請求もされていた様子 Last update 2020-05-22_1718 - 告発＼金沢地方検察庁＼最高検察庁＼法務省＼石川県警察 https://t.co/UGBeobOVW8

```
2019-05-05-232731_喜久山大貴さんのツイート：　”犬のうんこ拾う紙にちょうどいい…　”.jpg http://hirono2014sk.blogspot.com/2019/05/2019050815482019-05-04-1338072019-05-08.html#20190505232731
2019-05-05-233639_喜久山大貴（@kikuyamahiroki）：　裁判官には皇居かどこかにお呼ばれして天皇とテニスをする機会があって、昔それに参加したという話を自慢のよう.jpg http://hirono2014sk.blogspot.com/2019/05/2019050815482019-05-04-1338072019-05-08.html#20190505233639
2019-05-05-233942_喜久山大貴さんのツイート：　”警察がいつもやってることやん…　”.jpg http://hirono2014sk.blogspot.com/2019/05/2019050815482019-05-04-1338072019-05-08.html#20190505233942
```

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜jmjhjmwtad（7286） 日時：2020-09-04 15:56／2019/05/07 23:56 URL： https://twitter.com/kk_hirono/status/1301776103871193088 https://twitter.com/jmjhjmwtad/status/1125776428266475520  

> 私は、京都弁護士会は、喜久山大貴弁護士と思想が近い弁護士が主流派を占めるイメージを持っています。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜jmjhjmwtad（7286） 日時：2020-09-04 15:56／2019/05/09 16:45 URL： https://twitter.com/kk_hirono/status/1301776112884674560 https://twitter.com/jmjhjmwtad/status/1126392780870172672  

> @nodahayato 単なる京都に対する偏見ですね。 すいません。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ShminLo（及川智志） 日時：2020-09-04 15:57／2020/09/04 12:47 URL： https://twitter.com/kk_hirono/status/1301776329256230914 https://twitter.com/ShminLo/status/1301728578896183297  

> 荒会長、まだ冒頭の挨拶をしています。長いなあ。と思っていたら、会場から開会宣言をする前に発言を求める声あり。荒会長これを許さず、冒頭手続きを進めました。しかし、議長・副会長の選任に進もうとしたら、ついに「復代理」を認めるべきではない、と会場から発言あり。最初から波乱含みです！  

@un_co_the2nd ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@un_co_the2nd）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW un_co_the2nd（うのじ） 日時：2019/05/02 09:55 URL： https://twitter.com/un_co_the2nd/status/1123752839292043265?phpMyAdmin=cfc2644bd9c947213a0141747c2608b0  

> 犬のうんこ発言について。皇室にも神社仏閣にも特段の権威を認めないので、ただの紙なんだから犬のうんこ処理に使ったり引越しの時に皿包んだり芋焼くのに使ってなんの問題もないと思うが、わざわざ言ってしまうあたり「権威を認めた上での逆張りっすね( ´_ゝ`)」て反応したくならないこともない  

** 警察に関連した喜久山大貴弁護士（京都弁護士会）のツイートの記録










