* 「弁護士として言うべきことを言ったまで。」，補足として「女性はいくらでも嘘をつける・・・性犯罪に冤罪はありえないと言うのなら別ですが。」というモトケンこと矢部善朗弁護士（京都弁護士会）のツイート

:CATEGORIES: モトケンこと矢部善朗弁護士（京都弁護士会）

　「女性はいくらでも嘘をつける」というのは，数日前からネットで見かけていた言葉ですが，モトケンこと矢部善朗弁護士（京都弁護士会）の言及があったとは意外でした。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜tomopop21（ナカジマ） 日時：2020-10-01 20:09／2020/10/01 09:17 URL： https://twitter.com/kk_hirono/status/1311624215846506497 https://twitter.com/tomopop21/status/1311460107234885632  

> この社会的脈絡で、弁護士という立場で、その内容のツイートをされますか、あなたは。 https://t.co/gDINWLummY  

　上記のツイートは，次のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートを公式引用したものです。

@motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@motoken_tw）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW motoken_tw（モトケン） 日時：2020/10/01 09:14 URL： https://twitter.com/motoken_tw/status/1311459416193990656  

> 自民党の杉田水脈議員が「女性はいくらでもうそをつける」と発言したとして強く批判されているようだが、女性であれ男性であれ、被害者であれ加害者であれ目撃者であり、意図的に嘘をついていないとしても、その供述をなんの裏付けもなしに全面的に信用してはいけない、というのは法律家の基本です。  

- TW motoken_tw（モトケン） 日時： 2020/10/01 09:18 URL： https://twitter.com/motoken_tw/status/1311460448584171520  

> @tomopop21 弁護士として言うべきことを言ったまで。  

- TW motoken_tw（モトケン） 日時： 2020/10/01 09:29 URL： https://twitter.com/motoken_tw/status/1311463204648710144  

> @tomopop21 補足説明しますと  
>   
> 女性はいくらでも嘘をつける  
> 　　↓  
> 何言ってるんだ、そんなことあるか（怒  
> 　　↓  
> 女性の性犯罪被害者の言うことを微塵も疑うなんてとんでもない。  
>   
> というような非論理的な決めつけをする人が出てくると困るな、ということです。  
> 性犯罪に冤罪はありえないと言うのなら別ですが。  

* 「これで「弁護士」なら辞めて欲しいです」というツイートに対し，「速攻でブロックされましたw　反論される覚悟もなしに批判したのでしょうか？　批判というか誹謗中傷の類ですが(^^;」というモトケンのツイート

:CATEGORIES: モトケンこと矢部善朗弁護士（京都弁護士会）,誹謗中傷,ブロック

- TW motoken_tw（モトケン） 日時： 2020/09/27 11:29 URL： https://twitter.com/motoken_tw/status/1310043804582338560  

> さて、これから本論です。  
> ロックの根拠になったツイートは以下の二つです。  
> 削除前に撮ったスクショを貼り付けますが、それを理由にまたロックされるかも知れません。  
> 続いて、ツイッターの規約に反しないことを論証しますが、ツイッター社の担当者の知的能力で理解できるか不安ですw  
> （続く https://t.co/X2xnOLjd2I  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜sunflower2691（🍀伊予末摘花🍀） 日時：2020-10-01 20:19／2020/10/01 00:56 URL： https://twitter.com/kk_hirono/status/1311626671724716035 https://twitter.com/sunflower2691/status/1311334150255697921  

> @motoken_tw これで「弁護士」なら辞めて欲しいです  

- TW motoken_tw（モトケン） 日時： 2020/10/01 07:38 URL： https://twitter.com/motoken_tw/status/1311435399064031232  

> こういう人は、困ったことが起こって弁護士に法律相談をしたときに、弁護士が「法律的にはこうなりますよ。」と言って自分の意に沿わぬ見解を述べたときにも同じようなことを言うのだろうな。 https://t.co/9mNdZTmtRe  

- TW motoken_tw（モトケン） 日時： 2020/10/01 09:16 URL： https://twitter.com/motoken_tw/status/1311459953106771968  

> 速攻でブロックされましたw  
> 反論される覚悟もなしに批判したのでしょうか？  
> 批判というか誹謗中傷の類ですが(^^;  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-01 20:21／2020/10/01 20:20 URL： https://twitter.com/kk_hirono/status/1311627228589899777 https://twitter.com/s_hirono/status/1311627060545118211  

> 2020-10-01-201413_速攻でブロックされましたw反論される覚悟もなしに批判したのでしょうか？批判というか誹謗中傷の類ですが（＾＾；.jpg https://t.co/EFY9XJBuKC  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-01 20:21／2020/10/01 20:06 URL： https://twitter.com/kk_hirono/status/1311627250341679104 https://twitter.com/s_hirono/status/1311623582695395329  

> 2020-10-01-200300_モトケン@motoken_tw·10時間弁護士として言うべきことを言ったまで。.jpg https://t.co/KprleoM0Xj  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-01 20:21／2020/10/01 20:20 URL： https://twitter.com/kk_hirono/status/1311627375218581504 https://twitter.com/s_hirono/status/1311627133014269953  

> 2020-10-01-201501_モトケン@motoken_tw返信先：　@motoken_twさん速攻でブロックされましたw反論される覚悟もなしに批判したのでしょうか？批判.jpg https://t.co/mvUa1qa24L  

* 





