* 「現実的対応としては、最寄りの警察に相談に行って刑事さんとお友達になるという手もあります」という2012年3月20日のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートの記録

:CATEGORIES: モトケンこと矢部善朗弁護士（京都弁護士会）

@motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@motoken_tw）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW motoken_tw（モトケン） 日時：2012/03/20 10:10 URL： https://twitter.com/motoken_tw/status/181910450001281024  

> 現実的対応としては、最寄りの警察に相談に行って刑事さんとお友達になるという手もあります。 RT @sunatsu846: @lieesyuemay @motoken_tw 相手方がオペレーションコドモタチという子供達を救うというボランティア団体なので、その活動内容と言論のギャップ  

```
(py37_env) ➜  ~ dp -p|grep 相談に行って刑事さんとお友達
 - 2018年02月08日07時54分の登録： ％@motoken_tw　モトケン％現実的対応としては、最寄りの警察に相談に行って刑事さんとお友達になるという手もあります。 RT http://hirono2014sk.blogspot.com/2018/02/motokentw-rt_8.html
 - 2020年10月18日09時38分の登録： REGEXP：”最寄りの警察に相談に行って刑事さんとお友達”／データベース登録済みツイート：2020年10月18日09時37分の記録：ユーザ・投稿：3／4件 http://kk2020-09.blogspot.com/2020/10/regexp20201018093734.html
 - 2020年10月18日09時43分の登録： REGEXP：”最寄りの警察に相談に行って刑事さんとお友達”／データベース登録済みツイート：2020年10月18日09時43分の記録：ユーザ・投稿：4／15件 http://kk2020-09.blogspot.com/2020/10/regexp202010180943415.html
```

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-18 09:56／2020/10/18 09:54 URL： https://twitter.com/kk_hirono/status/1317630594918969344 https://twitter.com/s_hirono/status/1317630221588131840  

> 2020-10-18-095308_モトケン@motoken_twブロックされています@motoken_twさんのフォローやツイートの表示はできません。詳細はこちら.jpg https://t.co/fZU71lMKTL  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-18 09:56／2020/10/18 09:54 URL： https://twitter.com/kk_hirono/status/1317630622110679040 https://twitter.com/s_hirono/status/1317630148959633408  

> 2020-10-18-095231_モトケン@motoken_tw現実的対応としては、最寄りの警察に相談に行って刑事さんとお友達になるという手もあります。　RT　@sunats.jpg https://t.co/zNMz5T0Sqr  

* 「どういう糸（意図）があって、「＞ＲＴ」というわかりづらい言及をやって、Twilog（ツイログ）の登録もされていないのでしょうか？　深澤諭史弁護士さん。」という2015年12月19日の返信ツイート

:CATEGORIES: 深澤諭史弁護士,非弁

 - （0023／8695） TW hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜） 日時： 2015-12-19 21:17:00 +0900 URL： https://twitter.com/hirono_hideki/status/678187482060488704

> .@fukazawas どういう糸（意図）があって、「＞ＲＴ」というわかりづらい言及をやって、Twilog（ツイログ）の登録もされていないのでしょうか？　深澤諭史弁護士さん。

　昨日，次の深澤諭史弁護士のツイートがきっかけで，「深澤諭史」をキーワードにしたまとめ記事を作成しました。たぶん初めてではないと思いますが，深澤諭史弁護士本人のツイートは余り含まれなかったのか，予想より少ない数で8695件でした。

- TW fukazawas（深澤諭史） 日時： 2020/10/17 09:53 URL： https://twitter.com/fukazawas/status/1317267419560251392  

> Ｔｗｉｔｔｅｒを「深澤論史」でエゴサーチしてみたら，面白かった。  
> （・∀・）（＾ω＾）  

　すぐには気が付かなかったのですが，名前の漢字一文字が違っていました。諭と論の違いのようです。一文字でも検索結果がずいぶん変わっていましたが，これがきっかけとなって，思わぬ発見に至りました。

　ちょうどその前からまったく別の調べ物をしていたのですが，そちらとも近接した意外な発見がありました。時間的には，けっこうな間があったのですが，同じキーワードを含むツイートとしては，2つ前になっていました。

 - （0021／8695） TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2015-11-30 11:39:00 +0900 URL： https://twitter.com/hirono_hideki/status/671156511838593024

> ＞ＲＴ&#10;自由競争とか，市場原理とか，無邪気にいっている先生，特に佐藤幸治先生とかには，百回くらい読んで頂きたい記事ですね。&#10;(＃･∀･)／（深澤諭史） - 日暮れて途遠し_2011... https://t.co/2kV8CDuShe

　このツイートにある深澤諭史弁護士のツイートについては，昨日，まとめ記事を作成済みと思います。歴代の深澤諭史弁護士のツイートのなかでも，最も考えさせられ，被害者安藤文さん家族，安藤健次郎さんの生活，将来についても深刻重大な脅威を感じたものです。

　今，このツイートを探すのに，別の発見がいくつかあったのですが，やはり，この脳機能障害障害の少女の家族に関連した深澤諭史弁護士のツイートが，弁護士脳汚染，危険生物という問題意識の始まりとなっていたようです。昨日も変異のようなものかと考えていました。

 - 1018：2020-10-17_21:41:07 ＊ 脳機能障害を負った少女の一家から示談不成立と5千万円以上着服した弁護士のニュースに対する、2015年7月22日の深澤諭史弁護士の反応の記録（2020年10月17日） https://hirono-hideki.hatenadiary.jp/entry/2020/10/17/214104

　昨日は，「＞ＲＴ　味方になれば、依頼者をあり得ない報酬であり得ない処理をしてあり得ない状態に陥らせ、」が指すツイートも調べていました。以前はよく見かけた深澤諭史弁護士のスタイルですが，直前すなわち一つ前のリツイートを指すものと考えます。

　たしか，スクリーンショットの記録で見つけることが出来たと思うのですが，非弁に関するもので，＞ＲＴを使った深澤諭史弁護士の批判の矛先も，非弁にあるものと判断しました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-18 10:52／2015/07/22 19:09 URL： https://twitter.com/kk_hirono/status/1317644783670624257 https://twitter.com/s_hirono/status/623796928011067392  

> ＞ＲＴ 自由競争とか，市場原理とか，無邪気にいっている先生，特に佐藤幸治先生とかには，百回くらい読んで頂きたい記事ですね。 (＃･∀･)／（深澤諭史） https://t.co/qq41q2RXZP  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-18 10:52／2015/07/22 19:21 URL： https://twitter.com/kk_hirono/status/1317644812930093056 https://twitter.com/s_hirono/status/623800146728370176  

> 2015-07-22-192154_自由競争とか，市場原理とか，無邪気にいっている先生，特に佐藤幸治先生とかには，百回くらい読んで頂きたい記事ですね。.jpg http://t.co/Yjv22BMfLb  

非常上告-最高検察庁御中_ツイッター(@s_hirono)/「自由競争とか，市場原理とか，無邪気にいっている先生」の検索結果 - Twilog https://t.co/G7mytpvnxX

　勘違いして別のツイートを調べていました。今調べるべきは，「＞ＲＴ　味方になれば、依頼者をあり得ない報酬」です。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-18 10:55／2020/10/17 17:28 URL： https://twitter.com/kk_hirono/status/1317645378078961666 https://twitter.com/s_hirono/status/1317382056477818880  

> 2020-10-17-160845_深澤諭史@fukazawas＞ＲＴ味方になれば、依頼者をあり得ない報酬であり得ない処理をしてあり得ない状態に陥らせ、敵になれば、ただただ紛争.jpg https://t.co/UdQIFg6zkg  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-18 10:55／2015/12/19 21:07 URL： https://twitter.com/kk_hirono/status/1317645408798011392 https://twitter.com/s_hirono/status/678184942753341441  

> 2015-12-19-210740_深澤諭史さんはTwitterを使っています：　”＞ＲＴ　味方になれば、依頼者をあり得ない報酬であり得ない処理をしてあり得ない状態に陥らせ、　.jpg https://t.co/5JiiI5OWNG  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-18 10:55／2015/12/19 21:07 URL： https://twitter.com/kk_hirono/status/1317645449730248704 https://twitter.com/s_hirono/status/678184862231101441  

> 2015-12-19-210721_深澤諭史さんはTwitterを使っています：　”＞ＲＴ　味方になれば、依頼者をあり得ない報酬であり得ない処理をしてあり得ない状態に陥らせ、　.jpg https://t.co/xqnn9evFCj  

非常上告-最高検察庁御中_ツイッター(@s_hirono)/「＞ＲＴ 味方になれば、依頼者をあり得ない報酬」の検索結果 - Twilog https://t.co/af4w6ksZ5J

　これも失敗で，深澤諭史弁護士が＞ＲＴを付けた対象のツイートは出ていません。昨日は発見したと思うのですが，たぶん2015-12-19という日付での検索であったように思います。そこに深澤諭史弁護士のタイムラインのスクリーンショットの記録があったはずです。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-18 10:59／2015/12/19 21:08 URL： https://twitter.com/kk_hirono/status/1317646433550364673 https://twitter.com/s_hirono/status/678185189974011905  

> 2015-12-19-210839_味方になれば、依頼者をあり得ない報酬であり得ない処理をしてあり得ない状態に陥らせ、.jpg https://t.co/fKzfvJAkis  

　これも失敗で，深澤諭史弁護士が＞ＲＴを付けた対象のツイートは出ていません。昨日は発見したと思うのですが，たぶん2015-12-19という日付での検索であったように思います。そこに深澤諭史弁護士のタイムラインのスクリーンショットの記録があったはずです。

非常上告-最高検察庁御中_ツイッター(@s_hirono)/「2015-12-19」の検索結果 - Twilog https://t.co/xnRHXtIVnw

　ようやく見つけることができましたが，スクリーンショットにあるツイートです。「スーパーの店長には万引きが大好きな人が多いようですね。」というツイートが，「弁護士には非弁が大好物な人が多いようですね。」というツイートを公式引用しています。

"店長" (from：Qu2_law) - Twitter検索 / Twitter https://twitter.com/search?q=%22%E5%BA%97%E9%95%B7%22%20(from%3AQu2_law)&src=typed_query

@Qu2_law ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@Qu2_law）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW Qu2_law（きゅきゅ） 日時：2016/03/08 20:02 URL： https://twitter.com/Qu2_law/status/707159656020357120  

> 昔、先月食った時と味が違うぞ！手抜きしただろ！ってクレーム言うお客さんいたなぁ。  
> 僕、店長に「同じ製法で作ってます」って言ってきてと言われ対応。  
>   
> 最終的に「レトルトなんで変わらないです」という真実を突きつけて試合は終了しました。  

　検索結果は上記の1件のみで，「スーパーの店長には万引きが大好きな人が多いようですね。」という内容のツイートは見つかりませんでした。かなり長く見かけることのなかったアカウントと思いますが，ブロックされていました。

　TwitterのQu2_lawというアカウント名にlawがあったので，法クラの弁護士かロースクール関係かと思ったのですが，タイムラインのツイートをみていると，現在，司法修習生で検察で起案をしているようなツイートがありました。

```
 - 2020年10月18日11時16分の登録： ＃きゅきゅ　@Qu2_law＃のツイート／2020-07-22_1723〜2020-10-17_1516／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2020年10月18日11時16分 http://kk2020-09.blogspot.com/2020/10/qu2law2020-07-2217232020-10.html
 - 2020年10月18日11時18分の登録： ＼きゅきゅ　@Qu2_law＼P教官たちがラーメン次席盛りってつけるくない？笑ときゃっきゃっと作問してたかと思うと途中微笑ましく思ったけど、文量キツすぎて途中から殺意にか http://kk2020-09.blogspot.com/2020/10/qu2lawp.html
 - 2020年10月18日11時18分の登録： ＼きゅきゅ　@Qu2_law＼検察起案だけ起案時間2時間プラスしろよ。 http://kk2020-09.blogspot.com/2020/10/qu2law2.html
 - 2020年10月18日11時18分の登録： ＼きゅきゅ　@Qu2_law＼明日は検察起案だから今から頑張って検察講義案全部暗記するぞ(ง •̀_•́)ง http://kk2020-09.blogspot.com/2020/10/qu2law.html
 - 2020年10月18日11時19分の登録： ＼きゅきゅ　@Qu2_law＼紐になって、趣味で週2で弁護士したい人生だった。 http://kk2020-09.blogspot.com/2020/10/qu2law2_18.html
 - 2020年10月18日11時21分の登録： ＼きゅきゅ　@Qu2_law＼弁護士であることをBIOに載せたり、弁護士である旨をツイートしてますが、弁護士法74条、77条の2の規定はご存知ですか。 http://kk2020-09.blogspot.com/2020/10/qu2lawbio74772.html
```

　「弁護士には非弁が大好物な人が多いようですね。」というツイートの＠honshiochoというアカウントは，アカウント自体が存在しなくなっているようです。

　本当に何度でも反芻して噛みしめる味わい深さのある深澤諭史弁護士のツイートで，これを弁護士とは似て非なる非弁に限定しているというのも，深刻な問題性を感じます。

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2015/12/19 16:37 URL： https://twitter.com/fukazawas/status/678116968398905344  

> ＞ＲＴ  
> 味方になれば、依頼者をあり得ない報酬であり得ない処理をしてあり得ない状態に陥らせ、  
> 敵になれば、ただただ紛争を複雑化させる以外のことを何もしない  
>   
> こんなのをしょっちゅう見れば敏感にもなりますね（・∀・；）  

　この「しょっちゅう」というのも深澤諭史弁護士のツイートに特徴的な用法が感じられます。最近は余り見かけていないとも思いますが，そんなに沢山あることなのか，素朴に疑問です。

* 

