* 「判決文見ると，「あっ（察し）。確かに勝訴判決ですね（誰の，とは言っていない）」ということは，あるあるですね。裁判所は助けなかったのか（汗）」という深澤諭史弁護士のツイート
  :LOGBOOK:
  CLOCK: [2020-07-12 日 08:53]--[2020-07-12 日 09:25] =>  0:32
  :END:

:CATEGORIES: 深澤諭史弁護士

〉〉〉：Emacs： 2020-07-12（日曜日）08：53　 〉〉〉

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2020/07/11 21:59 URL： https://twitter.com/fukazawas/status/1281936097409302529  

> 「本人訴訟で勝訴判決取りました。でも，相手方が従わないので，強制執行してください！」  
> って話って，結構な確率で，判決文見ると，「あっ（察し）。確かに勝訴判決ですね（誰の，とは言っていない）」ということは，あるあるですね。  
> 裁判所は助けなかったのか（汗）  

　昨夜見かけた深澤諭史弁護士のツイートですが，具体性のあるなかなか気になる内容です。とっさに思い浮かんだのは「仮執行宣言」のことで，私にはそれ以外，思い当たるものがありませんでした。

　仮執行宣言は請求の趣旨になっていたと思います。裁判で求める結果，刑事裁判の主文に相当するという勉強をした記憶があります。刑事裁判の主文は，死刑とか懲役何年という結果になりますが，ほとんど見かけることのないものに訴訟費用の負担があり，被告人の負担にしないがほとんどとのことです。

　民事裁判の仮執行宣言もほとんどネットで話題を見たことがなく，深澤諭史弁護士のツイートでもそれという答えにはなっていません。昨夜，調べたところ，弁護士が仮執行宣言の求めを訴状に記載しなかった例があるようです。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-07-12 09:04／2020/07/12 08:54 URL： https://twitter.com/kk_hirono/status/1282103548923150336 https://twitter.com/s_hirono/status/1282101039861084160  

> 2020-07-11-234243_深澤諭史@fukazawas·1時間「本人訴訟で勝訴判決取りました。でも，相手方が従わないので，強制執行してください！」って話って，結構な確率で，判決文見.jpg https://t.co/rrZrglPhrc  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-12 09:11／2020/07/11 23:46 URL： https://twitter.com/kk_hirono/status/1282105248178290690 https://twitter.com/hirono_hideki/status/1281963138028408832  

> 仮執行宣言しなかったのは何故？！ https://t.co/Zz0FjxPSaD この弁護士は裁判所に提出する控訴状の「請求の趣旨」の欄に「仮執行宣言」の主張をしていませんでした。つまり、このままではたとえ控訴審で勝訴したとしても… https://t.co/QYJDtfcpTI  

　よく考えてみると，仮執行宣言の効果は判決確定までと私には解釈されるので，相手方の上訴が必至であったり，どちらにころぶかわからないような法律上の難しい論点を含む場合は，あえて仮執行宣言を求めない場合もありそうに思えてきました。

　平成７，８年当時のことになりますが，民事裁判の勉強で理解が難しかったのは，上訴に伴う金銭的負担のことで，これは刑事裁判とはまったく違うものでした。予納金のようなものを納める必要があったように思います。あるいは供託に近いのかもしれません。必要があれば調べ直す必要を考えています。

　ここでもまったく深澤諭史弁護士らしいいくらか漫画っぽくもある言い回しとなっていますが，「察し」と「あるある」があります。まるで一種のコレクションのようですが，深澤諭史弁護士の他にも法クラのツイートにはよくみられる現象になります。

　ここでは簡単なご紹介にとどめておきますが，代表的な共通フレーズに「そういうとこだぞ」あるいは「そういうところだぞ」というものがありました。ここ最近は余り見かけなくなったような気もします。

〈〈〈：Linux Emacs： 2020-07-12（日曜日）09：24 　〈〈〈

* 「そういうとこだぞ」あるいは「そういうところだぞ」という共通フレーズ，法クラの弁護士らのツイートの記録
  :LOGBOOK:
  CLOCK: [2020-07-12 日 09:25]
  :END:

:CATEGORIES: 法クラ

〉〉〉：Emacs： 2020-07-12（日曜日）09：25　 〉〉〉

```
[8446]  % dp -p|grep -E '(そういうところだぞ|そういうとこだぞ)'
 - 2018年02月15日22時16分の登録： ＼ほうたろう　@lawyerhotaro＼あはは、仮想通貨で大損こいてCC被害者弁護団の費用を高いって言ってる人、そういうとこだぞｗ http://hirono2014sk.blogspot.com/2018/02/lawyerhotarocc.html
 - 2018年06月23日14時12分の登録： ＼コントラムンディ　@un_co_the2nd＼連れ去り、で検索すると、bioの段階で「そういうとこだぞ」ってなるアカウントがいっぱい出てくる http://hirono2014sk.blogspot.com/2018/06/uncothe2ndbio.html
 - 2019年02月03日14時12分の登録： ＼チョココロネ　@un_co_the2nd＼・弁護士の報酬になる←なら任意に払え\n・養育費欲しいほど金がないなら親権よこせ←そういうとこだぞ http://hirono2014sk.blogspot.com/2019/02/uncothe2nd.html
 - 2019年02月17日22時37分の登録： ％@noooooooorth　ノースライム(50倍)％itterの観測範囲内に過ぎないが離婚やら親権やら養育費やらに絡む部分にはてきめんに「そういうとこだぞ」という人が多い気がする。 http://hirono2014sk.blogspot.com/2019/02/noooooooorth50itter.html
 - 2019年02月17日22時40分の登録： ％@himaben1st　暇弁(暇とは言ってない)％そういうとこだぞ？ http://hirono2014sk.blogspot.com/2019/02/himaben1st_17.html
 - 2019年04月16日21時58分の登録： ＼仙猫カリン　@Bibendum65＼相手の都合を考えずに自分中心で物事を進めようとする。\nそういうとこだぞ案件（定期） http://hirono2014sk.blogspot.com/2019/04/bibendum65_16.html
 - 2019年04月17日09時22分の登録： ＼暇弁(暇とは言ってない)　@himaben1st＼この引用ツイートのリプが地獄絵図すぎて、「そういうとこだぞ？」の一言しか浮かんでこない。 http://hirono2014sk.blogspot.com/2019/04/himaben1st_58.html
 - 2019年04月17日09時29分の登録： ＼うの字　@un_co_the2nd＼そういうとこだぞホイホイすぎて草\n\n「夫婦で話し合ってできるのに弁護士が介入する必要はない」って言ってくる人、相手方の言い分聞かなく http://hirono2014sk.blogspot.com/2019/04/uncothe2nd_90.html
 - 2019年05月03日22時46分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼なんかもう、「そういうところだぞ」という感想しか持てないな。 http://hirono2014sk.blogspot.com/2019/05/popohito_3.html
 - 2019年05月05日21時47分の登録： ＼深澤諭史　@fukazawas＼まさに、「そういうとこだぞ」という話ですね。（・∀・；） http://hirono2014sk.blogspot.com/2019/05/fukazawas_49.html
 - 2019年06月03日03時27分の登録： ＼暇弁(暇とは言ってない)　@himaben1st＼返信先: @fukazawasさん\nまさに「そういうとこだぞ？」案件です。\n\n http://hirono2014sk.blogspot.com/2019/06/himaben1st-fukazawas.html
 - 2019年06月03日03時28分の登録： ＼深澤諭史　@fukazawas＼まさに\nそういうとこだぞ？\nって話ですね（・∀・；） http://hirono2014sk.blogspot.com/2019/06/fukazawas_3.html
 - 2019年06月07日21時07分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼べんごしは しんけんについてつぶやいた。\n\nそういうところだぞが  あらわれた！\n\n #法クラクエスト http://hirono2014sk.blogspot.com/2019/06/popohito_72.html
 - 2019年06月21日08時49分の登録： ＼D弁　@dben82716007＼なんか暴れ回ってるB垢見たけど、これがいわゆる、そういうとこだぞ、案件なわけですね\n\n（そんなんでは支持を得られないヨ） http://hirono2014sk.blogspot.com/2019/06/ddben82716007b.html
 - 2019年06月26日07時46分の登録： ＼魚占い　@sakanauranai＼そういうとこだぞ は、どうやってこれまでの◯十年間、社会生活を過ごしてきたのか。 http://hirono2014sk.blogspot.com/2019/06/sakanauranai_26.html
 - 2019年06月26日09時08分の登録： REGEXP：”そういうとこだぞ”／データベース登録済みツイート：2019年06月26日09時07分の記録：ユーザ・投稿：30／191件 http://hirono2014sk.blogspot.com/2019/06/regexp20190626090730191.html
 - 2019年06月26日09時13分の登録： ％@un_co_the2nd　うの字％連れ去り、で検索すると、bioの段階で「そういうとこだぞ」ってなるアカウントがいっぱい出てくる http://hirono2014sk.blogspot.com/2019/06/uncothe2ndbio.html
 - 2019年06月26日09時13分の登録： ％@lawkus　ystk％「そういうとこだぞ」という人を呼び寄せそうなツイート。  http://hirono2014sk.blogspot.com/2019/06/lawkusystk.html
 - 2019年07月12日19時52分の登録： ＼深澤諭史　@fukazawas＼（；・∀・）ＤＶの話題になると，「そういうとこだぞ」リプライが沢山ぶら下がる現象って，もう名前はついていましたよね。 http://hirono2014sk.blogspot.com/2019/07/fukazawas_98.html
 - 2019年08月15日11時42分の登録： REGEXP：”そういうとこだぞ”／データベース登録済みツイート：2019年08月15日11時41分の記録：ユーザ・投稿：38／214件 http://hirono2014sk.blogspot.com/2019/08/regexp20190815114138214.html
 - 2019年08月26日19時09分の登録： ＼深澤諭史　@fukazawas＼他人の労働について敬意を払えない者と，円満な家庭生活を築くのは難しいですよね。\n「そういうとこだぞ」といわれてしまいかねないですね。 http://hirono2014sk.blogspot.com/2019/08/fukazawas_66.html
 - 2019年08月28日19時01分の登録： ＼暇弁(暇とは言ってない)　@himaben1st＼そういうとこだぞマンがまた釣れた http://hirono2014sk.blogspot.com/2019/08/himaben1st_28.html
 - 2019年09月04日11時40分の登録： ＼うの字　@un_co_the2nd＼クツー無理なのってこの人のこういうとこが大いにある\n\n「そういうとこだぞ」なんだよな\n対立煽る商売は楽しいか？ http://hirono2014sk.blogspot.com/2019/09/uncothe2nd_4.html
 - 2019年09月21日17時08分の登録： ＼うの字　@un_co_the2nd＼そうだんで自分の思い通りのヨイショが得られなかったからって受付の人に八つ当たりすんなよ\nそういうとこだぞ http://hirono2014sk.blogspot.com/2019/09/uncothe2nd_21.html
 - 2019年09月25日16時05分の登録： ％@noooooooorth　ノースライム％Twitterの観測範囲内に過ぎないが離婚やら親権やら養育費やらに絡む部分にはてきめんに「そういうとこだぞ」という人が多い気がする。 http://hirono2014sk.blogspot.com/2019/09/noooooooorthtwitter.html
 - 2019年10月22日12時34分の登録： ＼深澤諭史　@fukazawas＼いわゆる「そういうとこだぞ」事案（・∀・；） http://hirono2014sk.blogspot.com/2019/10/fukazawas_22.html
 - 2019年10月22日12時56分の登録： ＼芝原章吾　@shogoshibahara＼こういうときに使うんだろうな。「ほら、そういうとこだぞ…。」というフレーズは。 http://hirono2014sk.blogspot.com/2019/10/shogoshibahara_22.html
 - 2019年12月21日19時53分の登録： ＼深澤諭史　@fukazawas＼「あっ（察し」「そういうとこだぞ」って感想しか持たれないと思う（・∀・；） http://hirono2014sk.blogspot.com/2019/12/fukazawas_0.html
 - 2020年01月11日17時02分の登録： REGEXP：”そういうとこだぞ”／データベース登録済みツイート：2020年01月11日16時59分の記録：ユーザ・投稿：61／285件 http://hirono2014sk.blogspot.com/2020/01/regexp20200111165961285.html
 - 2020年01月11日17時02分の登録： REGEXP：”そういうところだぞ”／データベース登録済みツイート：2020年01月11日17時02分の記録：ユーザ・投稿：10／13件 http://hirono2014sk.blogspot.com/2020/01/regexp2020011117021013.html
 - 2020年01月12日12時15分の登録： ＼深澤諭史　@fukazawas＼いわゆる「そういうところだぞ？」現象（・∀・；） http://hirono2014sk.blogspot.com/2020/01/fukazawas_12.html
 - 2020年02月06日19時45分の登録： ＼深澤諭史　@fukazawas＼完全に　「そういうところだぞ」　案件ですね。。　（・∀・；）　 http://hirono2014sk.blogspot.com/2020/02/fukazawas.html
 - 2020年02月07日08時00分の登録： REGEXP：”（そういうところ？やぞ｜そういうところだぞ｜そういうとこだぞ）”／深澤諭史（@fukazawas）の検索（2018-11-22〜2020-02-06／2020年02月07日08時00分の記録31件） http://hirono2014sk.blogspot.com/2020/02/regexpfukazawas2018-11-222020-02.html
 - 2020年03月02日14時19分の登録： ％@o2441　弁護士大西洋一％「そういうとこだぞ案件」だね。 http://hirono2014sk.blogspot.com/2020/03/o2441.html
 - 2020年03月02日14時20分の登録： ％@sakanauranai　魚占い％なんでこう「そういうとこだぞ」を地で行くようなことをするのかねぇ http://hirono2014sk.blogspot.com/2020/03/sakanauranai.html
 - 2020年03月10日00時12分の登録： ＼なべきょう＠過眠症　@wata_nabekyo_ko＼馬鹿にしきっている元配偶者本人じゃなくて弁護士を装うところもまた、「そういうとこだぞ」なんですよね。 http://hirono2014sk.blogspot.com/2020/03/watanabekyoko_10.html
 - 2020年03月10日00時12分の登録： ＼ふて寝べん　@hirune_b＼あの偽弁護士アカ、「女性」を名乗っているところがまた「そういうとこだぞ」なんだよな。 http://hirono2014sk.blogspot.com/2020/03/hiruneb.html
 - 2020年03月18日21時23分の登録： ＼深澤諭史　@fukazawas＼なんで「さぞかし，この人と共同生活を送るのは怖かっただろうな」「そういうとこだぞ」って，頼んでもいないのに第三者をして信じさせてしまうの http://hirono2014sk.blogspot.com/2020/03/fukazawas_47.html
 - 2020年03月20日11時09分の登録： ＼リーチ一発ツモ裏１　@luckymangan＼元のツイートとこのツイートに、いわゆる「そういうとこだぞ」な人が反応しだした… http://hirono2014sk.blogspot.com/2020/03/luckymangan_20.html
 - 2020年03月23日21時56分の登録： ＼ＫＢブラック（アルコールやめられない）　@battamon_black＼時々いますが、ある種『そういうとこだぞ』というか… http://hirono2014sk.blogspot.com/2020/03/battamonblack_23.html
 - 2020年03月23日22時15分の登録： ＼深澤諭史　@fukazawas＼（；・∀・）まさに「そういうとこだぞ」ってツイートを見た。 http://hirono2014sk.blogspot.com/2020/03/fukazawas_43.html
 - 2020年04月18日20時08分の登録： ％@luckymangan　リーチ一発ツモ裏１％元のツイートとこのツイートに、いわゆる「そういうとこだぞ」な人が反応しだした… http://hirono2014sk.blogspot.com/2020/04/luckymangan_18.html
 - 2020年06月12日13時53分の登録： ＼ノ ー ス ラ イ ム　@noooooooorth＼こういう投稿をすると「そういうとこだぞ」というリプライが飛んできまくるのでミュートがはかどる。 http://hirono2014sk.blogspot.com/2020/06/noooooooorth_12.html
 - 2020年06月22日07時58分の登録： ＼深澤諭史　@fukazawas＼弁護士ドットコムコミュニティ、「そういうとこだぞ」な人への対応とか、アレな相談者の見分け方とか、そういう分野が盛り上がっているなぁ・・・ http://hirono2014sk.blogspot.com/2020/06/fukazawas_64.html
 - 2020年06月22日07時59分の登録： REGEXP：”そういうとこだぞ”／深澤諭史（@fukazawas）の検索（2018-11-22〜2020-06-21／2020年06月22日07時59分の記録34件） http://hirono2014sk.blogspot.com/2020/06/regexpfukazawas2018-11-222020-06.html
 - 2020年06月28日04時41分の登録： REGEXP：”そういうとこだぞ”／深澤諭史（@fukazawas）の検索（2018-11-22〜2020-06-21／2020年06月28日04時41分の記録34件） http://hirono2014sk.blogspot.com/2020/06/regexpfukazawas2018-11-222020-06_28.html
```

〈〈〈：Linux Emacs： 2020-07-12（日曜日）09：36 　〈〈〈

* 




