* 「特定されたくない某先生は，Tweetで嘘ついてないなら3択くらいまで一瞬で絞れるので，」という野田隼人弁護士のツイートの深澤諭史弁護士のリツイート

:CATEGORIES: 野田隼人弁護士,深澤諭史弁護士

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-06-30 00:26／2020/06/30 00:25 URL： https://twitter.com/kk_hirono/status/1277624565523288065 https://twitter.com/s_hirono/status/1277624275982151680  

> 2020-06-30-002222_深澤諭史さんがリツイート野田隼人@nodahayato·2時間特定されたくない某先生は，Tweetで嘘ついてないなら3択くらいまで一瞬で絞れるので，あとは.jpg https://t.co/cAEhMuPGiE  

 - 2020年06月29日21時47分の登録： ＼野田隼人　@nodahayato＼特定されたくない某先生は，Tweetで嘘ついてないなら3択くらいまで一瞬で絞れるので，あとはちょっとした聴き取りで特定できると思うのだ http://hirono2014sk.blogspot.com/2020/06/nodahayatotweet3.html

　正確なことは確認の作業が必要になりますが，日付が変わり昨日となった6月29日，弁護士であることを確認した林宏弥というアカウントで，福井の弁護士ということで法クラで話題となっていました。最初に見たのは一昨日の6月28日になりそうと思っています。

　野田隼人弁護士は滋賀弁護士会の所属で，福井県は隣になります。その地理的な短さというのは長距離トラック運転手の仕事で実感しています。野田隼人弁護士は高島市ということで，私の記憶にあるのは今津町になりますが，いっそう福井県に近いところになります。

　深澤諭史弁護士のタイムラインをみていると，直接，林宏弥というTwitterアカウントに触れることは避けているような印象を受けています。それを踏まえて野田隼人弁護士のツイートをリツイートしているのは気になるところと思いました。

@nodahayato ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@nodahayato）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW nodahayato（野田隼人） 日時：2020/06/29 21:39 URL： https://twitter.com/nodahayato/status/1277582432242302977  

> どうも反応されるとやりたい欲が出てくるんですけどね。  


　上記の野田隼人弁護士のツイートも深澤諭史弁護士のタイムラインにリツイートされています。林宏弥という匿名の弁護士アカウントを批判したいという気持ちがそこにあるように感じています。

 - 2020年06月30日00時02分の登録： ツイートの記録資料：＼法務検察・石川県警察宛＼／深澤諭史（@fukazawas）／”2020年06月29日”：59件 http://hirono2014sk.blogspot.com/2020/06/fukazawas2020062959.html

　毎日欠かさず行っているモトケンこと矢部善朗弁護士（京都弁護士会）と深澤諭史弁護士のツイートの記録ですが，上記の深澤諭史弁護士のツイートの日付単位のまとめ記事にも，記録があるものと思います。

 - （58／59） RT fukazawas（深澤諭史）｜nodahayato（野田隼人） 日時：2020-06-29 22:14:00 +0900／2020-06-29 21:39:00 +0900 URL： https://twitter.com/fukazawas/status/1277591333142532097 https://twitter.com/nodahayato/status/1277582432242302977

> どうも反応されるとやりたい欲が出てくるんですけどね。

 - （57／59） RT fukazawas（深澤諭史）｜nodahayato（野田隼人） 日時：2020-06-29 22:14:00 +0900／2020-06-29 21:34:00 +0900 URL： https://twitter.com/fukazawas/status/1277591310023589888 https://twitter.com/nodahayato/status/1277581088903147523

> 特定されたくない某先生は，Tweetで嘘ついてないなら3択くらいまで一瞬で絞れるので，あとはちょっとした聴き取りで特定できると思うのだが，しかし，まあ，そんなことをしても仕方ないのでしない。

* ツイッター投稿削除認めず　過去の逮捕歴、東京高裁　-　産経ニュース
  :LOGBOOK:
  CLOCK: [2020-06-30 火 09:51]--[2020-06-30 火 11:02] =>  1:11
  :END:

:CATEGORIES: SNS,プライバシー

〉〉〉：Emacs： 2020-06-30（火曜日）09：51　 〉〉〉

```
昨年１０月の１審判決は、ツイッターはグーグルのような情報流通基盤にはなっていないとして削除の要件を緩和。「逮捕から期間が経過し、公表の公共性は相当減少している」と請求を認めた。

　１審判決によると、男性は２４年、建造物侵入容疑で逮捕され、罰金刑を受けた。実名報道された記事を引用したツイートが複数投稿され、就職活動に支障が出ていた。

［source：］ツイッター投稿削除認めず　過去の逮捕歴、東京高裁 - 産経ニュース https://www.sankei.com/affairs/news/200629/afr2006290009-n1.html
```

　記事には「2020.6.29 11:46社会裁判」とあります。昨日の午前中の記事ですが，初めて知りました。きっかけはテレビのとくダネ！で，全く違ったニュースの紹介に新聞の記事が出てきて，その紙面に「ツイッター投稿削除認めず」などと見て，すぐにGoogleで検索しました。

　とくダネ！にチャンネルを変えたのは9時30分頃かと思います。テレビを消す前にチャンネルを石川テレビに変えたのですが，そのタイミングで，小さな枠にゴットハンドの医師の姿がありました。名前を思い出せないのですが，前回見たときは新型コロナの闘病体験のお話でした。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜1961kumachin（中村元弥） 日時：2020-06-30 10:04／2020/06/29 16:16 URL： https://twitter.com/kk_hirono/status/1277769852212539392 https://twitter.com/1961kumachin/status/1277501287714586624  

> 大崎事件についての記者会見のNHKニュース　 https://t.co/JAICRfHWUW  

 - » とくダネ！ 医師 - Google 検索 https://t.co/jfFyFkrXu7

 - » とくダネ！【番組出演の加藤友朗医師が感染…語る後遺症▽今週承認へ抗原検査とは】[字]｜番組情報｜TNC　テレビ西日本 https://t.co/2WeW9VYPul

 - » 価格.com - 「加藤友朗」に関連する情報 | テレビ紹介情報 https://t.co/zYG2vxGkMD

　前は「その他のツイート」などと表示があったように思うのですが，今確認をしたところ，ツイートの投稿直後に説明の表示がないまま無作為のようなツイートが並んでいました。中村元弥弁護士の大崎事件のツイートもそこに出てきたものです。

　昨日の夕方何をしていたのか思い出せないのですが，NHKのNEWS７を見ていたのか思い出せません。ニュースの項目は見たように思います。夕方は早い時間に宇出津新港の買い物から戻っていました。職業安定所にも行っており，そちらが宇出津新港へ行った目的でした。

　NEWS７の途中でテレビを消し，次にテレビをつけたのが20時47分でした。そこで石川県警察の振込詐欺事件のニュースをみて，エントリーに取り上げました。NEWS９の終わり頃には報道ステーションにチャンネルを変え，23時を過ぎてからはzeroに変えて，その次の番組もつけていました。

　大崎事件を取り上げたニュースは，テレビで見ていません。録画の確認をしたのですが，６つの主要項目以外も大崎事件はありませんでした。主要項目に入っていたいものに養育費不払い問題があって，森まさこ法務大臣の姿がありました。

　1,2ヶ月前にも朝のNHKの番組で大崎事件が取り上げられたというのをツイートで見ていたことがありました。

*  大崎事件　NHK - Twitter検索 / Twitter

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜amneris84（Shoko Egawa） 日時：2020-06-30 10:34／2020/03/30 06:23 URL： https://twitter.com/kk_hirono/status/1277777431605080065 https://twitter.com/amneris84/status/1244374564932444160  

> 起きてる人、NHKをつけてみて〜。大崎事件やってる  

 - » (1) 大崎事件　NHK - Twitter検索 / Twitter https://t.co/BLmUhvFwO5

　いくらか記憶が残っていたのですが，ジャーナリストの江川紹子氏のツイートと確認しました。3月30日のツイートになっており，この日が第4次再審請求の提出日でした。

　Twitterの検索は，ローマ字の大文字と小文字を区別しないだけではなく，半角文字と全角文字も区別をしないようです。しかし，「大崎事件　NHK」の検索結果は意外に少ない数で，ページスクロールの読み込みが終わりました。

* 「第3次再審請求を認め、裁判のやり直しを決定した。共犯とされた原口さんの元夫・中村善三さん（故人）の再審請求も認めた。報道各社が同日報じた。」

:CATEGORIES: 大崎事件

　大崎事件の被害者の名前も最近になって実名を知ったと思っていたのですが，「共犯とされた原口さんの元夫・中村善三さん（故人）」という実名は初めてみました。故人の再審請求を認めたというのは日野町事件と同じになります。

　この「共犯とされた原口さんの元夫・中村善三さん（故人）」の再審請求を認めたという情報は，前に少し見かけていたとも思うのですが，不思議と扱いの小さなものでした。

　この原口アヤ子さんの元夫というのは，原口アヤ子さんに再審請求を一緒にやろうと言われて，断り，それが原因で離婚したという情報が出ています。本人の死亡後に再審請求がされたのか，再審請求の途上で亡くなったのかは不明ですが，自殺であったような。確認します。

```
鹿児島県大崎町で1979年に男性（当時42）の遺体が発見された「大崎事件」で、鹿児島地裁は2017年6月28日、殺人罪などで服役した原口アヤ子さん（90）の第3次再審請求を認め、裁判のやり直しを決定した。共犯とされた原口さんの元夫・中村善三さん（故人）の再審請求も認めた。報道各社が同日報じた。

［source：］38年前の大崎事件、再審決定　服役した90歳女性の請求認める： J-CAST ニュース https://www.j-cast.com/2017/06/28301856.html
```

　記事に「今回の第3次再審請求は15年7月に申し立てていた。」という記述がありました。

* 大崎事件の共犯者とされた3人の男性の死亡時期，自殺者2人，3人とも知的障害があり，警察がそれを最大限利用し自白させたという説
  :LOGBOOK:
  CLOCK: [2020-06-30 火 11:02]--[2020-06-30 火 11:19] =>  0:17
  :END:

:CATEGORIES: 大崎事件,警察,知的障害

〉〉〉：Emacs： 2020-06-30（火曜日）11：02　 〉〉〉

```
警察は、当初から近親者の犯行と見て捜査を開始し、10月18日、同一敷地内に住む長兄の中村善三さん（当時52歳。服役後93年病死）と次兄の中村喜作さん（当時50歳。服役後87年自殺）を逮捕。当初はこの「二人犯行説」に拠った調書が作られました。しかし、犯行当日とされる日は親戚の結婚式があり、二人とも酒に酔ってすぐに就寝したことから、邦夫さんが送り届けられたことに気付かないという不自然さがありました。

警察は、死亡した邦夫さんにとっては義理の姉に当たる、善三さんの妻であったアヤ子さん（当時52歳、中村姓、後に離婚し原口姓）を受取人とする郵便局の簡易保険が邦夫さんにかけられていたことを知ると、アヤ子さんを主犯とする「三人犯行説」に事件の構図を書き換えます。

警察のストーリーによる犯行の動機は、保険金目当てのほかに「酒癖の悪い義理の弟をやっかいに思った」というものでした（保険金に関しては、再三の勧誘にいやいや加入したことが分かり、後の検察の主張からは外されました）。

27日に喜作さんの息子の中村善則さん（当時25歳。服役後01年自殺）を死体遺棄を手伝ったとして逮捕し、新たなストーリーに沿った善三さん、喜作さん、善則さんの自白調書を取ります。アヤ子さんの指示で善三さん、喜作さんが絞殺し、善則さんと三人で死体遺棄をしたというものです。

［source：］冤罪ファイル　その8　「大崎事件」 - 「蟷螂の斧となろうとも」 by 元外資系証券マン http://fugathegameplayer.blog51.fc2.com/blog-entry-510.html
```

　調べるとすぐに見つかった記事ですが，よく知るアカウントのブログ記事でした。実名，顔写真ともに公開をされていましたが，なかでも気になったのが金沢市出身という情報でした。

　「長兄の中村善三さん（当時52歳。服役後93年病死）」，「次兄の中村喜作さん（当時50歳。服役後87年自殺）」，「喜作さんの息子の中村善則さん（当時25歳。服役後01年自殺）」と記事にあります。

　中村姓となっているので実名に間違いないと思いますが，このような関係者の実名記載をみたのも初めてと思いますし，なぜ今日のこのタイミングで発見になったのかも不思議なところです。

```
この事件の不運なことは、死体遺棄のような状況があったために関係者全員が「殺人事件」だと思い込んでしまったことです。その予断は死体解剖した検死医にもありました。もし、検死医が予断を持たずに頸椎前面の皮下出血に注目して切開していたら、死因は絞殺ではなく事故死になっていたはずです（このことは再審請求審で解明されます）。

また、内部の人間の犯行と判断されたため、アヤ子さん、善三さん、喜作さん、善則さんは、それぞれが自分以外の人を犯人と疑うことになり、警察の構図に迎合する供述も生まれたのでした。

更に不幸なことは、共謀したとされる男三人は、知的障害があり、被暗示性が強く、脅しや強制に弱いという特徴がありました。警察はそれを最大限に利用して自白をさせたのです。

アヤ子さんは、懲役10年を服役し、刑期満了で出所後、再審を勝ち取るため闘っています。

［source：］冤罪ファイル　その8　「大崎事件」 - 「蟷螂の斧となろうとも」 by 元外資系証券マン http://fugathegameplayer.blog51.fc2.com/blog-entry-510.html
```

　ちょっとわかりづらいのですが，記事の下にある「2013/03/05 Tue. 07:00」が記事の投稿日時と思われます。7年ちょっと前の記事ですが，もっと最近のものかと思いながら記事を読んでいました。飛ばし読みをしましたが，追記もあるようです。

　この記事を見つけたきっかけは，Twitter検索で見た次の渡辺輝人弁護士のツイートでした。

〈〈〈：Emacs： 2020-06-30（火曜日）11：19 　〈〈〈

* 「ご遺体に手で首を絞めた跡がなく、そのことについて当初から警察で写真撮影しており、かつ、隠ぺいされていた訳ですね。」という大崎事件の渡辺輝人弁護士のツイート
  :LOGBOOK:
  CLOCK: [2020-06-30 火 11:19]--[2020-06-30 火 11:55] =>  0:36
  :END:

:CATEGORIES: 大崎事件,渡辺輝人弁護士,警察

〉〉〉：Emacs： 2020-06-30（火曜日）11：19　 〉〉〉

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜nabeteru1Q78（渡辺輝人） 日時：2020-06-30 11:20／2017/06/28 17:20 URL： https://twitter.com/kk_hirono/status/1277789021301702656 https://twitter.com/nabeteru1Q78/status/879977791260721156  

> 首を絞めて殺したとされる事件で、ご遺体に手で首を絞めた跡がなく、そのことについて当初から警察で写真撮影しており、かつ、隠ぺいされていた訳ですね。 / “大崎事件 ９０歳女性の再審認める決定 鹿児島地裁 | NHKニュース” https://t.co/DVupUDch3B  

　次のTwitter検索で見つけたツイートになります。以前にも見かけていたように思いますが，以前に見かけていたときはそれほど注目することはなかったように思います。

 - » 大崎事件　NHK - Twitter検索 / Twitter https://t.co/BLmUhvFwO5

　渡辺輝人弁護士のツイートにある「“大崎事件 ９０歳女性の再審認める決定 鹿児島地裁 | NHKニュース”」という記事はリンク切れでした。リンク切れの記事でも見出しの部分を検索すると，その記事の情報が見つかることが多いのですが，今回は少し違っていました。

 - » 大崎事件 ９０歳女性の再審認める決定 鹿児島地裁 | NHKニュース - Google 検索 https://t.co/JqxetuS5ai

　次が検索結果のトップに表示された記事で，「共犯者とされた原口さんの元夫についても再審開始を認めた。」という情報を見つけて，他の検索につながりました。

 - 【大崎事件】３８年前の殺人、被害者義姉９０歳女性の再審認める　鹿児島地裁決定「共犯者の自白、誘導で変遷の疑い」（1/2ページ） - 産経WEST https://www.sankei.com/west/news/170628/wst1706280043-n1.html  

　現在の大崎事件第4次再審請求でも，被害者の死因を事故死と主張しているわけで，医学的な根拠も散見されるのですが，以前見かけたと記憶にある情報では，被害者の遺体の腐敗がひどく死因の特定が出来なかったというものがあったと思うのです。

　これは大崎事件の大きな特徴で，その割に問題視されないのが不思議なのですが，最後に生存が確認されてから3日ほどで死因の特定が出来ないほど遺体の腐敗が進行していたというのです。牛小屋の堆肥に埋まっていたのが原因とのことです。

　急激に遺体の腐敗が進むことを知って堆肥に埋めたのであれば，悪質な計画殺人ともされそうですが，骨まで溶けるのかは不明で，被疑者が住む同じ敷地の牛小屋に遺体を隠したというのも，計画殺人としては疑問のあるところでもあります。

　また，つい最近になって事件現場の番地を含めた住所を知ることとなり，Googleマップで調べたところ，それまでの想像とは違って，人里は離れておらず，集落の中に敷地の周りを木に囲まれた家があったという感じでした。

　この家の周りを神社のように樹木で囲むというのは富山県でよく見かけた風景で，前から気になっていたのですが，最近見たテレビ番組で，立山からの強い風を防ぐ生活の知恵という話でした。

　通常の刑事裁判では，一人否認を貫いていたという原口アヤ子さんも，割と早くに判決が確定し服役となっていたようです。その弁護人が鹿児島県で実力のある大物弁護士だったということも，公開された第4次再審請求で初めて知りました。私選弁護人です。

　再審請求は同じ理由で出来ないのが基本となっているので，別の理由で再審請求をする他ないというのは理解が出来るのですが，大崎事件の刑事裁判，そして再審請求の経過をみていると，いろいろと気になる変遷が多々あります。

　渡辺輝人弁護士のツイートにあるように，「首を絞めて殺したとされる事件で、ご遺体に手で首を絞めた跡がなく」というのが証明されたのであれば，刑事裁判の鉄則で無罪は理解できるのですが，それほど確かな根拠を見たという記憶はなく，参照のNHKの記事を確認したかったのです。

〈〈〈：Linux Emacs： 2020-06-30（火曜日）11：55 　〈〈〈

* 「大崎事件再審へ　映画監督の周防正行さんネットで支援金集める　｜　NHKニュース」という2020年6月29日15時05分の記事と，法クラの弁護士らの反応の記録
  :LOGBOOK:
  CLOCK: [2020-06-30 火 11:55]--[2020-06-30 火 14:56] =>  3:01
  :END:

:CATEGORIES: 大崎事件

〉〉〉：Emacs： 2020-06-30（火曜日）11：55　 〉〉〉

```
2020年6月29日 15時05分

41年前、鹿児島県大崎町で起きた殺人事件で、93歳の女性が無実を訴えているいわゆる「大崎事件」の再審請求を支援しようと、映画監督の周防正行さんがクラウドファンディングで1240万円余りの支援金を集めました。

原口アヤ子さん（93）は、昭和54年、鹿児島県大崎町で義理の弟を殺害した罪などで懲役10年の刑が確定し服役しましたが、一貫して無実を訴えています。

3度目の再審請求では、去年、最高裁判所が再審を認めるとした地裁と高裁の判断を覆す異例の決定をして、再審が認められませんでした。

4度目の再審請求を支援しようと、ことし3月から今月にかけてクラウドファンディングで支援金を集めた、映画監督の周防正行さんが29日、東京 霞が関で会見を開き、全国の805人から1240万7000円が寄せられ、目標金額を大幅に上回ったことを明らかにしました。

［source：］大崎事件再審へ 映画監督の周防正行さんネットで支援金集める | NHKニュース https://www3.nhk.or.jp/news/html/20200629/k10012487751000.html
```

 - 2020年06月20日15時23分の登録： REGEXP：”大崎事件”／データベース登録済みツイートの検索：2020-06-20〜2020-06-20／2020年06月20日15時22分の記録：ユーザ・投稿：1／1件 http://hirono2014sk.blogspot.com/2020/06/regexp2020-06-202020-06-2020200620152211.html
 - 2020年06月20日16時37分の登録： Shoko　Egawa（@amneris84）／「大崎事件」の検索結果　-　Twilog：2020年06月20日16時36分　49件 http://hirono2014sk.blogspot.com/2020/06/shokoegawaamneris84-twilog20200620163649.html
 - 2020年06月20日17時27分の登録： REGEXP：”大崎事件”／Shoko Egawa（@amneris84）の検索（2012-12-22〜2020-03-30／2020年06月20日17時27分の記録49件） http://hirono2014sk.blogspot.com/2020/06/regexpshoko-egawaamneris842012-12.html
 - 2020年06月22日02時58分の登録： REGEXP：”大崎事件”／データベース登録済みツイートの検索：2020-06-19〜2020-06-21／2020年06月22日02時58分の記録：ユーザ・投稿：7／82件 http://hirono2014sk.blogspot.com/2020/06/regexp2020-06-192020-06_22.html
 - 2020年06月29日22時27分の登録： REGEXP：”大崎事件”／データベース登録済みツイートの検索：2020-06-22〜2020-06-29／2020年06月29日22時26分の記録：ユーザ・投稿：13／15件 http://hirono2014sk.blogspot.com/2020/06/regexp2020-06-222020-06.html
 - 2020年06月30日07時13分の登録： REGEXP：”大崎事件”／奉納＼さらば弁護士鉄道・泥棒神社の物語（@hirono_hideki）の検索（2020-06-16〜2020-06-29／2020年06月30日07時13分の記録15件） http://hirono2014sk.blogspot.com/2020/06/regexphironohideki2020-06-162020-06.html

　ちょっと忘れていたのですが，今朝の7時13分にも記録を作成済みだったようです。2020-06-16〜2020-06-29という幅の広い期間の指定で15件という結果でした。内容を確認していませんが，私のアカウントのツイートが多いのかもしれません。

```
2020年06月30日12時03分の実行記録
twitterAPI-search-lawList-mydql-add.rb "大崎事件"
ツイート数：43/1891 リツイート数：11/1891 トータル：381
hirono_hideki 10／1件　kk_hirono 21／4件　s_hirono 1／0件
```

　今から，「ajx-all-user-mysql-REGEXP_blogger_hirono2014sk.rb "大崎事件" "2020-06-29 12:03/2020-06-30 12:03"」というコマンドを時間計測付きで実行します。

```
[7802]  % time ajx-all-user-mysql-REGEXP_blogger_hirono2014sk.rb "大崎事件" "2020-06-29 12:03/2020-06-30 12:03"
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '2020-06-29 12:03' AND '2020-06-30 12:03' AND  tweet REGEXP "大崎事件"  ORDER BY tw_date ASC
nhk_news
NHKニュース（nhk_news）
ユーザ名称：NHKニュース [screen_name]ユーザ名：nhk_news フォロー数：19 フォロワー数：3014770 ツイート数：456643
eeyy888777
びーちゃん（eeyy888777）
ユーザ名称：びーちゃん [screen_name]ユーザ名：eeyy888777 フォロー数：530 フォロワー数：1226 ツイート数：29071
1961kumachin
中村元弥（1961kumachin）
ユーザ名称：中村元弥 [screen_name]ユーザ名：1961kumachin フォロー数：1545 フォロワー数：8741 ツイート数：178256
hiromomosetsu
白山次郎（hiromomosetsu）
ユーザ名称：白山次郎 [screen_name]ユーザ名：hiromomosetsu フォロー数：142 フォロワー数：1192 ツイート数：5888
h_nakaji
なかじ（h_nakaji）
ユーザ名称：なかじ [screen_name]ユーザ名：h_nakaji フォロー数：1070 フォロワー数：2333 ツイート数：46189
bengo4topics
弁護士ドットコムニュース（bengo4topics）
ユーザ名称：弁護士ドットコムニュース [screen_name]ユーザ名：bengo4topics フォロー数：2173 フォロワー数：35229 ツイート数：32750
asahi
朝日新聞(asahi shimbun）（asahi）
ユーザ名称：朝日新聞(asahi shimbun） [screen_name]ユーザ名：asahi フォロー数：313 フォロワー数：1274210 ツイート数：310013
daisuke29801
江木大輔（daisuke29801）
ユーザ名称：江木大輔 [screen_name]ユーザ名：daisuke29801 フォロー数：727 フォロワー数：584 ツイート数：26977
hosakanobuto
保坂展人（hosakanobuto）
ユーザ名称：保坂展人 [screen_name]ユーザ名：hosakanobuto フォロー数：21436 フォロワー数：92493 ツイート数：32962
SATOMasako
佐藤正子（SATOMasako）
ユーザ名称：佐藤正子 [screen_name]ユーザ名：SATOMasako フォロー数：2869 フォロワー数：7629 ツイート数：204341
hirono_hideki
奉納＼さらば弁護士鉄道・泥棒神社の物語（hirono_hideki）
ユーザ名称：奉納＼さらば弁護士鉄道・泥棒神社の物語 [screen_name]ユーザ名：hirono_hideki フォロー数：4290 フォロワー数：4310 ツイート数：190251
Pokomoko5
Pokomoko（Pokomoko5）
ユーザ名称：Pokomoko [screen_name]ユーザ名：Pokomoko5 フォロー数：2722 フォロワー数：838 ツイート数：89470
itoyukilaw
弁護士 伊藤祐貴（itoyukilaw）
ユーザ名称：弁護士 伊藤祐貴 [screen_name]ユーザ名：itoyukilaw フォロー数：252 フォロワー数：985 ツイート数：1614
kk_hirono
刑事告発・非常上告＿金沢地方検察庁御中（kk_hirono）
ユーザ名称：刑事告発・非常上告＿金沢地方検察庁御中 [screen_name]ユーザ名：kk_hirono フォロー数：493 フォロワー数：565 ツイート数：105949
s_hirono
非常上告-最高検察庁御中_ツイッター（s_hirono）
ユーザ名称：非常上告-最高検察庁御中_ツイッター [screen_name]ユーザ名：s_hirono フォロー数：4 フォロワー数：80 ツイート数：72043
REGEXP：”大崎事件”／データベース登録済みツイートの検索：2020-06-29〜2020-06-30／2020年06月30日12時06分の記録：ユーザ・投稿：15／48件

real    0m53.177s
user    0m1.470s
sys     0m0.364s
```

　今頃になって気がついたのですが，スクリプトの表示で「 [screen_name]ユーザ名：s_hirono」というのは分かりづらく，変数の値を表示させるつもりで変数名screen_nameをそのまま表示しているのかと勘違いしました。

 - 2020年06月30日12時06分の登録： REGEXP：”大崎事件”／データベース登録済みツイートの検索：2020-06-29〜2020-06-30／2020年06月30日12時06分の記録：ユーザ・投稿：15／48件 http://hirono2014sk.blogspot.com/2020/06/regexp2020-06-292020-06.html

　上記のまとめ記事は24時間以内指定になります。ユーザが15でツイートが48ですが，たぶん私のツイートがかなりあると思います。

　私の3つのアカウントのツイートが29件，リツイートが5件でした。48件中の34件が私のツイートになります。この3つのアカウントのツイートを除外する仕様変更も考えてみます。逆に今日の朝は，私の３つのアカウントのみのツイートをまとめるスクリプトを新規作成しました。

 - （03／48） TW 1961kumachin（中村元弥） 日時： 2020-06-29 16:16:00 +0900 URL： https://twitter.com/1961kumachin/status/1277501287714586624

> 大崎事件についての記者会見のNHKニュース　 https://t.co/JAICRfHWUW

 - （10／48） TW hosakanobuto（保坂展人） 日時： 2020-06-29 20:34:00 +0900 URL： https://twitter.com/hosakanobuto/status/1277566224465932288

> 大崎事件再審　クラウドファンディングに1240万円　https://t.co/SrNSosAd3E 鹿児島県大崎町で1979年に男性（当時42）の遺体が見つかった「大崎事件」の再審請求で、弁護活動の費用を募るクラウドファンディング… https://t.co/xlNILLPb3l

　共謀罪反対で大きく目立った印象のある保坂展人氏のツイートです。

　なにか意見やコメントらしいものを付けたツイートは見当たりませんでした。最近は，意識的に大崎事件のことを避けている弁護士が多いようにも感じています。

〈〈〈：Linux Emacs： 2020-06-30（火曜日）12：38 　〈〈〈

* 「コロナ禍と大崎事件　中島邦之｜【西日本新聞ニュース】」という記事にある，名誉回復を目指す弁護団の活動資金はほぼ手出し。他の仕事ができず事務所が昨年、1千万円の赤字だった弁護士

:CATEGORIES: 大崎事件

```
再審無罪に向け、弁護団の活動資金を募る。3月24日のプロジェクト開始から、わずか10日間で当初の目標額500万円を突破した。

　周防監督は痴漢冤罪（えんざい）事件を題材にした映画「それでもボクはやってない」で知られ、法務省の法制審議会特別部会委員を務めるなど日本の刑事司法の問題点を訴えてきた。アヤ子さんの長女と弁護団が第4次再審請求を申し立てた3月30日には、鹿児島市に駆けつけ、集会で「この事件のことを、とにかく多くの人に知ってほしい」と訴えた。

　大崎事件は25年前の第1次請求後、過去3回も再審開始決定が出た。そのたびに検察官が抗告し、上級審で覆されてきた。特に、昨年6月の最高裁決定は、地裁と高裁がともに認めた開始決定を取り消した初のケースとみられる。その証拠評価や事実認定のおかしさは、私も検証取材の中で痛感した。高齢のアヤ子さんの生のあるうちの名誉回復を目指す弁護団の活動資金はほぼ手出し。他の仕事ができず事務所が昨年、1千万円の赤字だった弁護士もいる。

　CFは1千万円を次の目標に定め、6月16日まで寄付を募る。「アヤ子さんの再審無罪と再審制度の法改正を実現するためさらなるご支援を」と周防監督は呼び掛ける。

　最初の目標額達成後、寄付の集まりは鈍っているようだ。いや、違う。感染が拡大し多くの人の収入が減り生活が脅かされる中で、500人が803万円（23日現在）を寄せたことは、真実究明への期待の大きさとみるべきだろう。

［source：］コロナ禍と大崎事件　中島邦之｜【西日本新聞ニュース】 https://www.nishinippon.co.jp/item/n/603202/
```

　初めTwilogで検索したのですが，見つからず，Googleの検索で記事を見つけました。先日も調べに掛かるとすぐに見つけることが出来たのですが，本当なのかと記憶に自信が持てなくなっていた情報でもありました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-06-30 14:20／2020/06/30 13:39 URL： https://twitter.com/kk_hirono/status/1277834321185763328 https://twitter.com/s_hirono/status/1277823932859420673  

> 2020-06-30-124215_名誉回復を目指す弁護団の活動資金はほぼ手出し。他の仕事ができず事務所が昨年、1千万円の赤字だった弁護士もいる。.jpg https://t.co/dL8MCkjbJJ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-06-30 14:20／2020/06/21 10:47 URL： https://twitter.com/kk_hirono/status/1277834355541340162 https://twitter.com/s_hirono/status/1274519170986545153  

> 2020-06-21-104537_高齢のアヤ子さんの生のあるうちの名誉回復を目指す弁護団の活動資金はほぼ手出し。他の仕事ができず事務所が昨年、1千万円の赤字だった弁護士もいる.jpg https://t.co/AERapHg20Y  

 - » 非常上告-最高検察庁御中_ツイッター(@s_hirono)/「千万円の赤字」の検索結果 - Twilog https://t.co/f7cnZOjuur

　6月21日にスクリーンショットの記録が作成されていました。目を疑う内容だったので間違いのないように記録しました。長年よくみてきた弁護士の手弁当になるものと思われますが，一人の弁護士の負担として具体的な金額を見たのも初めてかと思います。

　この項目の見出しを作成した後，中断をしていたのですが，そのなかでまた１つの考えさせれる発見があり，それが東京都台東区の入谷に繋がりました。これも先日，「投げ込み寺」を調べた時の発見でした。

〈〈〈：Linux Emacs： 2020-06-30（火曜日）14：27 　〈〈〈

* 凍結されたという横須賀の弁護士のTwitterアカウントのことから調べた「恐れ入谷の鬼子母神」，そこで見た朝顔という花の写真
  :LOGBOOK:
  CLOCK: [2020-06-30 火 14:56]
  :END:

:CATEGORIES: Twitter

〉〉〉：Emacs： 2020-06-30（火曜日）14：56　 〉〉〉

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-06-30 14:58／2020/06/30 14:21 URL： https://twitter.com/kk_hirono/status/1277843826128769024 https://twitter.com/s_hirono/status/1277834673339555840  

> 2020-06-30-134537_えきなんローヤーさんがリツイート高橋雄一郎@kamatatylaw·1時間共同親権に強い横須賀の先生のアカが凍結されている。なにかあったのだろうか。.jpg https://t.co/6y8BhEjqMW  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-06-30 14:58／2020/06/30 14:21 URL： https://twitter.com/kk_hirono/status/1277843893417984000 https://twitter.com/s_hirono/status/1277834746534391814  

> 2020-06-30-135134_リーチ一発ツモ裏１@luckymangan·2019年7月7日共同親権の横須賀先生。断絶派の弁護士にデマ流されたと仰るが、「親権争い自体が酷いことで、敗者.jpg https://t.co/50w6mihCmH  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-06-30 14:58／2020/06/30 14:22 URL： https://twitter.com/kk_hirono/status/1277843913542299649 https://twitter.com/s_hirono/status/1277834819754356737  

> 2020-06-30-135529_凍結されたアカウントによるツイートです。詳細はこちら.jpg https://t.co/etgaFrXJk1  

　時刻は14時58分です。13時55分のスクリーンショットとして記録されたものをみて思い出したのですが，きっかけはえきなんローヤーのタイムラインでみた高橋雄一郎弁護士のツイートのリツイートでした。考えていたのですが思い出せずにいました。

　横須賀の杉山程彦ですが，Twitterアカウントで思い出したのがヘッダ画像の宗教画のような鬼子母神でした。本当に鬼子母神なのかと確信が持てなかったのですが，非常上告-最高検察庁御中_ツイッター（@s_hirono）でスクリーンショットを調べました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-06-30 15:05／2017/09/01 21:03 URL： https://twitter.com/kk_hirono/status/1277845598062837760 https://twitter.com/s_hirono/status/903589102045368320  

> 2017-09-01-210319_弁護士杉山程彦4　＞　お釈迦様　かつて、鬼子母神から子どもを奪い、鬼子母神に自分のした愚かさを諭したように、今こそ全国の弁護士と裁判官の子を.jpg https://t.co/QYwPntqGbb  

 - » 非常上告-最高検察庁御中_ツイッター(@s_hirono)/「杉山程彦」の検索結果 - Twilog https://t.co/4iLZ6rQ0iQ

　最初にスクリーンショットとして記録されていたのが，「2017-09-01-210319_弁護士杉山程彦4　＞　お釈迦様　かつて、鬼子母神から子どもを奪い、鬼子母神に自分のした愚かさを諭したように、今こそ全国の弁護士と裁判官の子を.jpg」になります。

　これはファイル名ですが，ヘッダ画像は最高裁裁判官の国民審査のようです。プロフィールの内容かと思ったのですが，画像を拡大すると，固定されたツイートの内容に鬼子母神があることがわかりました。

　鬼子母神のヘッダ画像の記録が最初に出るのは次のツイートでした。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-06-30 15:08／2019/01/26 18:53 URL： https://twitter.com/kk_hirono/status/1277846497241923585 https://twitter.com/s_hirono/status/1089098968565395457  

> 2019-01-26-181830_弁護士杉山程彦5東慶應三丁目（@r34CXRsvHnOj2GB）さん　｜　Twitter.jpg https://t.co/6HetTGsiHk  

　「恐れ入谷の鬼子母神」という言葉を思い出すと同時に，先日，Googleマップで目にした上野駅の近くの入谷という地名のことが気になりました。

　平成元年から平成4年頃のことになりますが，上野駅の近くに首都高速の終点インターのようなところがあって，それが入谷インターではなかったかとGoogleマップを見た時に思い出したのです。

```
入谷出入口（いりやでいりぐち）は、東京都台東区にある首都高速道路1号上野線の出入口である。

［source：］入谷出入口 - Wikipedia https://ja.wikipedia.org/wiki/%E5%85%A5%E8%B0%B7%E5%87%BA%E5%85%A5%E5%8F%A3
```

　調べてみたのですが，現在も首都高速の終点のような出入り口となっているのかもしれません。上野線とあります。ずっと前に延伸されてただのインターになっているものと考えていました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-06-30 15:24／2020/06/30 13:48 URL： https://twitter.com/kk_hirono/status/1277850510440067072 https://twitter.com/hirono_hideki/status/1277826262635954176  

> ひき逃げ　自称弁護士・（神奈川県弁護士会所属）小柳茂秀容疑者（５５）を逮捕　その後、再逮捕（弁護士法違反・偽計等）された報道も無く・・・会長・剱持京助　ご挨拶(^－^)　　　 - 冷静に新潟県を見つめる会　弁護士改革！真実の追究 https://t.co/pW8wbPZFML  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-06-30 15:24／2020/06/30 14:04 URL： https://twitter.com/kk_hirono/status/1277850565309902849 https://twitter.com/hirono_hideki/status/1277830378552614913  

> おそれ入谷の鬼子母神 - Google 検索 https://t.co/bXtWmdY0kw  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-06-30 15:24／2020/06/30 14:08 URL： https://twitter.com/kk_hirono/status/1277850578622676998 https://twitter.com/hirono_hideki/status/1277831409298620416  

> 入谷鬼子母神（真源寺） | 東京とりっぷ https://t.co/lmRmvgUoMM  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-06-30 15:25／2020/06/30 14:09 URL： https://twitter.com/kk_hirono/status/1277850605269078017 https://twitter.com/hirono_hideki/status/1277831661795766272  

> 朝顔 - Google 検索 https://t.co/JdmeFboAF6  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-06-30 15:25／2020/06/30 14:14 URL： https://twitter.com/kk_hirono/status/1277850672453435392 https://twitter.com/hirono_hideki/status/1277832900931534850  

> 鬼子母神堂 | 東京とりっぷ https://t.co/yWwUeqRa6x  

　杉山程彦弁護士の名前が思い出せず，「横須賀　弁護士」などとGoogleで検索したところ，ひき逃げ容疑で逮捕されたという自称弁護士のニュースが出てきました。弁護士が車で黙秘すると言ったそうですが，それで自称弁護士とされたようです。

 - » 入谷鬼子母神（真源寺） | 東京とりっぷ https://t.co/yeob3NTRHo 入谷鬼子母神は朝顔市でも有名

　上記の記事に朝顔の写真をみたのですが，余り見たことのない花だと思いながら，ちょうど昨日の夕方に見た花に似ていると思いました。どこで見たのか思い出すのに少し時間が掛かったのですが，3週間ほど前に死亡事故のあった宇出津第一トンネルでした。

　宇出津新港のどんたく宇出津店から買い物をして帰るのに，宇出津第一トンネルの前に来たところで，後ろにスピードを落とした車がいることに気が付き，死亡事故のことも思い出して，トンネルの手間でバイクを停車させたのですが，その時に花があることに気がついたのです。

　アジサイの花と思ったのですが，それにしては花が小さいように思っていました。しかし，数日前にも合鹿で小さいアジサイの花を見かけていました。

　アジサイの花に気がついたのは，日曜日につくモールに行った帰り道でした。羽生の交差点の角にアジサイの花を見て，今がアジサイの時期であることに気がついたのです。このときもしばらく気がつくまでに時間が掛かりました。

　昨年は，秋の紅葉を見にアジサイ寺とも呼ばれる平等寺に行った時に，アジサイの花を見て，遅い時期に大変珍しいと思っていました。8月に入るとアジサイの花を見かけることはなかったように思います。

　上町の母親の病院に行くとき，やなぎだ植物公園の手前から合鹿の集落に入ったのですが，そこで例年，時期になるとよくアジサイの花を見かけていたからです。今年は例年になくアジサイの花が小さく，数もずいぶん少なく感じました。

 - 2020-06-24_145736＿能登町合鹿，紫陽花の花.jpg https://t.co/QSPCWGJPrJ

 - 2018-06-26_192339＿母親の入院する上町の病院へ・宇出津昭和町・大乗寺・アジサイ.jpg https://t.co/WxWWb1vJvg

 - 2018-07-02_175318＿宇出津上田町の大黒宮とアジサイ.jpg https://t.co/g8G6gRq0Sw

 - 2018-07-04_101317＿宇出津昭和町大乗寺、アジサイ.jpg https://t.co/WNw2SZFMKn

 - 2019-11-18_131011＿平等寺　アジサイ.jpg https://t.co/N2zYsfRqLU

　% locate アジサイ| xargs -I % cp % ./ \n を実行してから， \n % for i in `ls *.jpg`; do hsk "$i"; sleep 3; done \n とやって，写真付きツイートを投稿しました

　最近は面倒になって写真ファイルに撮影日時以外の名前をつけることは少なくなっているのですが，面倒でもやっておけば検索で役立ちます。合鹿のアジサイの写真がありませんでした。写真はあるはずですが，名前がないようです。

　宇出津の昭和町の大乗寺に紫陽花があることもすっかり忘れていました。最近はポケモンGOをめったにやらなくなったこともあり，昭和町の大乗寺の前も余り通らなくなっています。

　ネコヤナギと思われる写真がTwitterへの投稿に失敗していて，サイズが5.5MBでした。「% mogrify -resize 2048 2019-11-18_133716＿平等寺のネコヤナギ？.jpg」を実行すると1.6MBになりました。

 - 2019-11-18_133716＿平等寺のネコヤナギ？.jpg https://t.co/cIFckHQtI8

　このとき，ネコヤナギという木があることを知ったのですが，子供の頃のテレビアニメの天才バカボンの歌に，「柳の下にネコがいる　だからネコヤナギ」というのはずっと記憶にありました。これもダジャレのようなもので実在する植物とは思っていませんでした。

 - » ネコヤナギ - Google 検索 https://t.co/KF28ErpemN

　いちおうの確認のため調べたつもりだったのですが，ネコヤナギというのは全然違う見たことのない植物のようです。猫じゃらしというのに似ている気がしますが，小さなきりたんぽのようでもあります。綿毛のようですが，海ムカデにも似ています。

　海ムカデも海毛虫が正式名のようでした。子どものころは海でよく見かけたのですが，今は長い時間，魚釣りをしていても数年に一度ぐらいしか見かけなくなっていました。

　時刻は17時05分です。ネコヤナギだと思っていた枯れ木の名前を調べていたのですが，断念することにしました。使ったのは時間です。疲れも感じました。

〈〈〈：Linux Emacs： 2020-06-30（火曜日）17：47 　〈〈〈






