* ログインシェルをzshに変更

　数日前から使い始めたzshですが，これまでに何度か使ってきたところ長続きせず，しばらくするとbashに戻っていました。bashと併用して使ってきたのが，高機能だが少し癖のあるfishシェルになります。

　zshをbashから起動して使っているうちは気が付かなかったのですが，コマンドサーチパスが設定されておらず，bashの設定をかなりの数，そのままコピペしたのですが，問題なく使えるようです。ログインシェルの変更は，平成10年からUNIXを使ってきた今回が初めてかもしれないです。

　今回，bashからzshに変更した一番の理由は，端末間のコマンド履歴の共有です。ターミナルでもタブで複数の端末を開き，kateのテキストエディタやファイルブラウザでも同じウィンドウ内にターミナルを開いて使っています。なお，端末の履歴の同期には設定が必要になっています。

* APIで昨日は10件の取得しかできなかったのに，今日は101件という全件の取得が出来たBloggerの新規ブログ

　原因は，Bloggerのブログの設定で，初期設定がアメリカ時刻となっていたものを日本時間に変更したことかと考えられます。Googleは有料化されたサービスも多いらしいので，無料だと10件までにされたのかという想像も思い巡らしていました。

　データ型を再度，確認したいと思ったのですが，pythonを対話型のインタプリタで起動し，コードを打ち込んだところエラーが起こっていました。環境が変わったとは考えられず，一応bashでも試してみましたが，結果が同じで，昨日出来ていたことが出来なくなっています。

　ちょっと思い出したのですが，昨日使っていたのはpythonコマンドではなく，ipythonコマンドだったようです。これで実行するとうまくいきました。

* 「Blogger API v3」で取得したデータの構造

　ipythonコマンドを使って実行しています。けっこう長い前処理がありますが，そちらは省略しています。

In [9]: request = posts.list(blogId=BLOG_ID,)
   ...: 

In [10]: posts_doc = request.execute()
    ...: 

In [11]: len(posts_doc['items'] )
Out[11]: 10

In [12]: posts_doc['items'] [0]
Out[12]: 
{'kind': 'blogger#post',
 'id': '889888888899999999075889',
 'blog': {'id': '11433355534455555555'},
 'published': '2020-09-21T09:53:00+09:00',
 'updated': '2020-09-21T09:53:08+09:00',
 'url': 'http://kk2020-09.blogspot.com/2020/09/regexp2020-09-192020-09.html',
 'selfLink': 'https://blogger.googleapis.com/v3/blogs/1143335553445555555/posts/881111111111133332229',
 'title': 'REGEXP：”総本山”／データベース登録済みツイートの検索：2020-09-19〜2020-09-20／2020年09月21日09時52分の記録：ユーザ・投稿：4／10件',
 'content':  '<div style="font-size: 8pt; color: #FF0040; margin-bottom: 25px;">\n<script type=\'text/javascript\'>\n    document.write("&nbsp;-&nbsp;" + document.title + " " + location.href + "");\n（以下省略）

　idなどは内容を変更しています。posts_doc = request.execute()で取得した，posts_docはdict型で，itemsをキーにした値が，要素が10の配列で，配列の中には1つの投稿記事のデータが入っています。どうも一度に10件ずつ取得する仕様となっていたようです。

　今頃気がついたのですが，「while request != None:」という繰り返し処理の中に，「if 'items' in posts_doc and not (posts_doc['items'] is None):」の処理が入っていました。

* 《参考資料》深澤諭史弁護士のTLで見た「日本の警察は、今年3月から防犯カメラやSNSの画像を顔認証システムで照合していた 」に「画像提供する民間側が損害賠償のリスク背負ってないからじゃねーかな」というツイート

:CATEGORIES: うの字,深澤諭史弁護士,警察

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-21 13:36／2020/09/20 19:29 URL： https://twitter.com/kk_hirono/status/1307901527827202048 https://twitter.com/s_hirono/status/1307627836723789826  

> 2020-09-20-171223_深澤諭史さんがリツイート￼うのじ@un_co_the2nd·1時間法律の根拠もなしにこういうことするのって、画像提供する民間側が損害賠償のリ.jpg https://t.co/WbZOboDoWK  

 - 2020年09月20日17時12分の登録： ＼うのじ　@un_co_the2nd＼法律の根拠もなしにこういうことするのって、画像提供する民間側が損害賠償のリスク背負ってないからじゃねーかな…日本の警察は、今年3月か http://kk2020-09.blogspot.com/2020/09/uncothe2nd3.html
 - 2020年09月20日19時23分の登録： REGEXP：”日本の警察は、今年3月から防犯カメラやSNSの画像を”／データベース登録済みツイート：2020年09月20日19時22分の記録：ユーザ・投稿：30／32件 http://kk2020-09.blogspot.com/2020/09/regexp3sns2020092019223032.html

　他にもうの字と深澤諭史弁護士に関連して記録資料を作成しています。

 - 2020年09月20日21時21分の登録： REGEXP：”ネット世論操作”／データベース登録済みツイート：2020年09月20日21時21分の記録：ユーザ・投稿：1／2件 http://kk2020-09.blogspot.com/2020/09/regexp20200920212112.html
 - 2020年09月20日21時33分の登録： REGEXP：”顔認証システム”／データベース登録済みツイート：2020年09月20日21時32分の記録：ユーザ・投稿：39／45件 http://kk2020-09.blogspot.com/2020/09/regexp2020092021323945.html
 - 2020年09月20日21時39分の登録： ＼うのじ　@un_co_the2nd＼じょいたまとかいう垢は釣り垢だから触らないけど、それに対する反応がちょっと気になったのさ http://kk2020-09.blogspot.com/2020/09/uncothe2nd.html
 - 2020年09月20日21時56分の登録： REGEXP：”@un_co_the2nd”／データベース登録済みツイートの検索：2020-09-08〜2020-09-20／2020年09月20日21時54分の記録：ユーザ・投稿：36／97件 http://kk2020-09.blogspot.com/2020/09/regexpuncothe2nd2020-09-082020-09.html
 - 2020年09月20日22時05分の登録： @sakamotomasayuk（坂本正幸）のツイート　”@un_co_the2nd”　10／3228：2020-08-16_1226〜2020-09-20_2037　2020年09月20日22時04分の記録　：embed http://kk2020-09.blogspot.com/2020/09/sakamotomasayukuncothe2nd1032282020-08.html
 - 2020年09月20日22時35分の登録： REGEXP：”非弁”／深澤諭史（@fukazawas）の検索（2012-09-08〜2020-09-20／2020年09月20日22時35分の記録2043件） http://kk2020-09.blogspot.com/2020/09/regexpfukazawas2012-09-082020-09.html
 - 2020年09月20日22時39分の登録： REGEXP：”弁護士”／深澤諭史（@fukazawas）の検索（2012-09-10〜2020-09-20／2020年09月20日22時38分の記録9615件） http://kk2020-09.blogspot.com/2020/09/regexpfukazawas2012-09-102020-09.html
 - 2020年09月20日22時43分の登録： REGEXP：”司法．＊改革”／深澤諭史（@fukazawas）の検索（2012-11-05〜2020-09-09／2020年09月20日22時43分の記録910件） http://kk2020-09.blogspot.com/2020/09/regexpfukazawas2012-11-052020-09.html
 - 2020年09月20日22時48分の登録： REGEXP：”司法．＊改革”／うのじ（@un_co_the2nd）の検索（2016-08-31〜2018-05-23／2020年09月20日22時48分の記録4件） http://kk2020-09.blogspot.com/2020/09/regexpuncothe2nd2016-08-312018-05.html
 - 2020年09月20日22時48分の登録： REGEXP：”警察”／うのじ（@un_co_the2nd）の検索（2016-02-04〜2020-09-20／2020年09月20日22時48分の記録163件） http://kk2020-09.blogspot.com/2020/09/regexpuncothe2nd2016-02-042020-09.html
 - 2020年09月20日22時49分の登録： REGEXP：”ヒャッハー”／うのじ（@un_co_the2nd）の検索（2017-05-16〜2020-03-22／2020年09月20日22時49分の記録11件） http://kk2020-09.blogspot.com/2020/09/regexpuncothe2nd2017-05-162020-03.html
 - 2020年09月20日22時51分の登録： REGEXP：”裁判員制度”／うのじ（@un_co_the2nd）の検索（2017-05-27〜2020-01-15／2020年09月20日22時51分の記録31件） http://kk2020-09.blogspot.com/2020/09/regexpuncothe2nd2017-05-272020-01.html
 - 2020年09月20日22時52分の登録： REGEXP：”死刑”／うのじ（@un_co_the2nd）の検索（2016-02-04〜2020-02-27／2020年09月20日22時52分の記録55件） http://kk2020-09.blogspot.com/2020/09/regexpuncothe2nd2016-02-042020-02.html
 - 2020年09月20日22時52分の登録： REGEXP：”被告人”／うのじ（@un_co_the2nd）の検索（2016-10-08〜2020-09-01／2020年09月20日22時52分の記録65件） http://kk2020-09.blogspot.com/2020/09/regexpuncothe2nd2016-10-082020-09.html
 - 2020年09月20日22時54分の登録： TWEET：”2016-01-08 15:46〜2020-09-20 19:43”／うのじ（@un_co_the2nd）の検索（2020年09月20日22時53分の記録6460件） http://kk2020-09.blogspot.com/2020/09/tweet2016-01-08-15462020-09-20.html
 - 2020年09月20日22時57分の登録： REGEXP：”うの字”／データベース登録済みツイート：2020年09月20日22時56分の記録：ユーザ・投稿：25／177件 http://kk2020-09.blogspot.com/2020/09/regexp20200920225625177.html
 - 2020年09月20日22時59分の登録： REGEXP：”うのじ”／データベース登録済みツイート：2020年09月20日22時58分の記録：ユーザ・投稿：16／56件 http://kk2020-09.blogspot.com/2020/09/regexp2020092022581656.html

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2020/09/20 15:42 URL： https://twitter.com/fukazawas/status/1307570871695888384  

> RT @un_co_the2nd: 法律の根拠もなしにこういうことするのって、画像提供する民間側が損害賠償のリスク背負ってないからじゃねーかな…  
>   
> 日本の警察は、今年3月から防犯カメラやSNSの画像を顔認証システムで照合していた | 一田和樹 https://t.co/71PScOqkvt  
@un_co_the2nd ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@un_co_the2nd）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW un_co_the2nd（うのじ） 日時：2020/09/20 15:38 URL： https://twitter.com/un_co_the2nd/status/1307569748062822402  

> 法律の根拠もなしにこういうことするのって、画像提供する民間側が損害賠償のリスク背負ってないからじゃねーかな…  
>   
> 日本の警察は、今年3月から防犯カメラやSNSの画像を顔認証システムで照合していた | 一田和樹 https://t.co/71PScOqkvt

* 




