* 珍しく問題性のあるツイートを見かけなかった2020年8月25日の深澤諭史弁護士のタイムライン
  :LOGBOOK:
  CLOCK: [2020-08-26 水 09:09]--[2020-08-26 水 09:15] =>  0:06
  :END:

:CATEGORIES: 深澤諭史弁護士

〉〉〉：Emacs： 2020-08-26（水曜日）09：09　 〉〉〉

　昨日は，頼まれたSSDのフォーマット，Windows10のアップデートのこともあって，深澤諭史弁護士だけではなく法クラのツイートを見ることが少なかったのですが，深澤諭史弁護士のタイムラインで社会的問題性を感じなかったのは久しぶりかもしれません。

 - 2020年08月26日03時51分の登録： ツイートの記録資料：＼法務検察・石川県警察宛＼／深澤諭史（@fukazawas）／”2020年08月25日”：35件 http://hirono2014sk.blogspot.com/2020/08/fukazawas2020082535.html

　夜中に一度目が覚めた時の記録です。

 - 2020年08月26日03時53分の登録： 2020-08-25の投稿一覧＼検察・石川県警察宛記録資料＼奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中：5件 http://hirono2014sk.blogspot.com/2020/08/2020-08-255.html

　今日もこの後，LinuxのUbuntuからWindows10に移って，ワープロソフト一太郎で告発状の作成に取り掛かる予定です。

〈〈〈：Emacs： 2020-08-26（水曜日）09：15 　〈〈〈

* 「安倍さん、今こそ感染者に対するいわれなき誹謗・中傷に対して強いメッセージを発信するべきタイミングだと思うんだ。」という深澤諭史弁護士のリツイート
  :LOGBOOK:
  CLOCK: [2020-08-26 水 10:07]--[2020-08-26 水 10:09] =>  0:02
  :END:

:CATEGORIES: 深澤諭史弁護士,中村元弥弁護士

〉〉〉：Emacs： 2020-08-26（水曜日）10：07　 〉〉〉

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜1961kumachin（中村元弥） 日時：2020-08-26 10:07／2020/08/25 21:17 URL： https://twitter.com/kk_hirono/status/1298426841363972098 https://twitter.com/1961kumachin/status/1298233015466827778  

> 安倍さん、今こそ感染者に対するいわれなき誹謗・中傷に対して強いメッセージを発信するべきタイミングだと思うんだ。自分のご病気を題材にされても良いし。そうすれば少しは安倍さんを見直すんだがなあ。  

RT fukazawas（深澤諭史）｜1961kumachin（中村元弥） 日時：2020-08-26 00:25／2020-08-25 21:17 URL： https://twitter.com/fukazawas/status/1298280282278092802 https://twitter.com/1961kumachin/status/1298233015466827778
> 安倍さん、今こそ感染者に対するいわれなき誹謗・中傷に対して強いメッセージを発信するべきタイミングだと思うんだ。自分のご病気を題材にされても良いし。そうすれば少しは安倍さんを見直すんだがなあ。

　そろそろ更新がありそうですが，深澤諭史弁護士のタイムラインで，今現在最新ツイートとなっているようです。

〈〈〈：Emacs： 2020-08-26（水曜日）10：09 　〈〈〈

