* 「加害者の家族を苦しめているのは、被害者ではなく、「社会」の人々です。」という10月9日のツイートを含むここ一週間のジャーナリストの江川紹子氏のツイート

:CATEGORIES: ジャーナリストの江川紹子氏

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜amneris84（Shoko Egawa） 日時：2020-10-13 11:04／2020/10/09 09:55 URL： https://twitter.com/kk_hirono/status/1315835716723564544 https://twitter.com/amneris84/status/1314368871898382336  

> 事実確認もないまま、共犯者であるかのような非難にさらされる日々。終わりなき社会的制裁に、加害者の家族も苦しんでいる。「危険なのは塀の中より社会である」と　→「正直逮捕してもらいたかった」池袋暴走事故の批判に苦しむ加害者家族 #ldnews https://t.co/5StI233Smt  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜amneris84（Shoko Egawa） 日時：2020-10-13 11:04／2020/10/09 10:48 URL： https://twitter.com/kk_hirono/status/1315835748499681280 https://twitter.com/amneris84/status/1314382289816571904  

> @AnnoyingCure 加害者の家族を苦しめているのは、被害者ではなく、「社会」の人々です。  

　今朝，3日ぶりぐらいにUbuntuを起動したのですが，それまではずっとWindows10でやっていました。2,3日集中してPowerShellのプログラムに取り組み，目的の機能を実現するスクリプトファイルを作成しました。

　次がここ最近のジャーナリストの江川紹子氏のツイートの記録です。

```
 - 2020年09月30日03時06分の登録： ＼Shoko Egawa　@amneris84＼今朝の朝日新聞への投書。検察の取り調べを受けた経験者の違和感。弁護士の立ち会いを求める声は切実だ。 http://kk2020-09.blogspot.com/2020/09/shoko-egawaamneris84_30.html
 - 2020年09月30日03時27分の登録： ＼Shoko Egawa　@amneris84＼朝日ガーと憤ってた方、時事通信もトーンはやや控えめながらも、同様の事実関係を書いてます。→橋本五輪相、女性蔑視発言「党は適 http://kk2020-09.blogspot.com/2020/09/shoko-egawaamneris84_91.html
 - 2020年09月30日03時28分の登録： ＼Shoko Egawa　@amneris84＼横審こそが、横綱の地位を貶め、人々の横綱への敬意を失わしめているのではないかと、何年も苦々しい思いをしながら見ていた。もう http://kk2020-09.blogspot.com/2020/09/shoko-egawaamneris84_39.html
 - 2020年09月30日03時28分の登録： ＼Shoko Egawa　@amneris84＼杉田議員は発言を否定しているが、読売新聞も、参加者の証言から「発言していた」と報道　→「女性はいくらでもウソつける」…自民 http://kk2020-09.blogspot.com/2020/09/shoko-egawaamneris84_58.html
 - 2020年09月30日03時34分の登録： ＼Shoko Egawa　@amneris84＼こちらの方が見やすいかな？　→安倍政権と「百田尚樹現象」の共通点　支持と批判が同居｜NEWSポストセブン http://kk2020-09.blogspot.com/2020/09/shoko-egawaamneris84news.html
 - 2020年09月30日03時34分の登録： ＼Shoko Egawa　@amneris84＼あたしは嘘つき、と言ってるのだろうか…… →杉田議員、女性はいくらでもうそ　自民党の合同会議で蔑視発言（共同通信） http://kk2020-09.blogspot.com/2020/09/shoko-egawaamneris84_77.html
 - 2020年09月30日03時35分の登録： ＼Shoko Egawa　@amneris84＼記事によると、文科省が厳罰化に向けて法改正を検討しているそうだが、ならばなぜ、同省がデータを集めて公表しないんだろう…とい http://kk2020-09.blogspot.com/2020/09/shoko-egawaamneris84_2.html
 - 2020年09月30日03時35分の登録： ＼Shoko Egawa　@amneris84＼「プライバシーへの配慮」を理由に被害者数を非公表としたのは、石川、広島、徳島、愛媛の各県と名古屋市の５教委。その判断が理解 http://kk2020-09.blogspot.com/2020/09/shoko-egawaamneris84_8.html
 - 2020年10月05日07時32分の登録： ＼Shoko Egawa　@amneris84＼しかし、９月4日の出来事を、１ヶ月の今日になって発表したというのはなぜかしらん。そもそも、厚労省の抗議がいつだったか、とい http://kk2020-09.blogspot.com/2020/10/shoko-egawaamneris844.html
 - 2020年10月09日11時12分の登録： ＼Shoko Egawa　@amneris84＼事実確認もないまま、共犯者であるかのような非難にさらされる日々。終わりなき社会的制裁に、加害者の家族も苦しんでいる。「危険 http://kk2020-09.blogspot.com/2020/10/shoko-egawaamneris84.html
 - 2020年10月12日22時38分の登録： ＼Shoko Egawa　@amneris84＼upされました〜。→【日本学術会議“任命拒否”】は安倍前首相が仕掛けた“時限爆弾”？　江川紹子の考察 http://kk2020-09.blogspot.com/2020/10/shoko-egawaamneris84up.html
```

　さきほど，過去7日間を指定して「江川紹子」をキーワードに含む弁護士らのツイートのまとめ記事を作成したのですが，ざっと目を通したところ，「日本学術会議任命拒否」関連の反応が多く，池袋の暴走死亡事故や被害者家族に関するものは見当たりませんでした。

 - 2020年10月13日10時14分の登録： REGEXP：”江川紹子”／データベース登録済みツイートの検索：2020-10-07〜2020-10-13／2020年10月13日10時13分の記録：ユーザ・投稿：23／34件 http://kk2020-09.blogspot.com/2020/10/regexp2020-10-072020-10_13.html

　今日も午後から用事ができたので，再開するつもりだった告発状の作成は一日順延になります。

* 
