* 法務省：性犯罪に関する刑事法検討会　第３回会議（令和２年７月９日）後藤貞人氏提出資料　刑事弁護人の立場から見た各論点への懸念　（後藤貞人弁護士）
  :LOGBOOK:
  CLOCK: [2020-07-23 木 09:21]
  :END:

:CATEGORIES: 後藤貞人弁護士,法務省,性犯罪

〉〉〉：Emacs： 2020-07-23（木曜日）09：21　 〉〉〉

　今日は，パソコンで個人的ではない用事をする予定なので，あまり作業ができないと思います。一昨日の夕方に連絡があったのですが，昨日は手を付けずに済ませてしまいました。早く終わるかもしれないのですが，4月辺りからのブランクもあるのでやってみないとわかりません。

　後藤貞人弁護士のことは，昨日にツイートで見かけ，PDFファイルもダウンロードしていたのですが，さきほど初めて内容に目を通しました。また長い文書になるのかと，用事のこともあるので読み進めることをためらったのですが，これまで見たことがないほど簡潔なものでした。

　PDFファイルですが，パワーポイントで作成したようなプレゼンテーションの資料といった感じです。このところ改行も少ない読みづらく，長い判決文をいくつか読んできただけに安堵感もありました。

　ネットで後藤貞人弁護士の名前を見かけたのも久しぶりでしたが，その前日ぐらいに平野母子殺害事件のことで取り上げたところでした。後藤貞人弁護士と高野隆弁護士は，刑事弁護界の偉人，レジェンドや神様とも称される存在です。いや，称されてきた，というのがマッチかもしれません。

　とりわけ高野隆弁護士は，このところ失点が続いているという印象があります。カルロス・ゴーン氏を仮装させて東京拘置所から出したのもありますが，乳腺外科医わいせつ事件の逆転有罪判決は7月13日，その後の対応を含め，刑事弁護に対する期待と信頼に，大きな影を落とした気がします。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-23 09:37／2020/07/22 23:40 URL： https://twitter.com/kk_hirono/status/1286098170510848000 https://twitter.com/hirono_hideki/status/1285947918596206593  

> 2020年07月22日23時39分の登録： ＼奥村徹弁護士　@okumuraosaka＼後藤貞人氏提出資料　刑事弁護人の立場から見た各論点への懸念 https://t.co/2FVHA5RtMO  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-07-23 09:39／2020/07/22 23:40 URL： https://twitter.com/kk_hirono/status/1286098636825272321 https://twitter.com/s_hirono/status/1285947818117455872  

> 2020-07-22-233949_サイ太さんがリツイートokumuraosaka@okumuraosaka·8時間後藤貞人氏提出資料　刑事弁護人の立場から見た各論点への懸念　.jpg https://t.co/68cX0qLIgg  

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「後藤貞人」の検索結果 - Twilog https://t.co/hwPbnmMkgV

非常上告-最高検察庁御中_ツイッター(@s_hirono)/「後藤貞人」の検索結果 - Twilog https://t.co/ZlTy9bZrfY

　奥村徹弁護士のツイートのことは記憶にあったのですが，最初，刑裁サイ太のタイムラインで，その奥村徹弁護士のツイートを見かけていたようです。スクリーンショットの記録で確認ができました。やることや考え事が多いと忘れることも多くなります。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜okumuraosaka（okumuraosaka） 日時：2020-07-23 09:44／2020/07/22 15:26 URL： https://twitter.com/kk_hirono/status/1286099856214224896 https://twitter.com/okumuraosaka/status/1285823399898439681  

> 後藤貞人氏提出資料　刑事弁護人の立場から見た各論点への懸念　https://t.co/AZKsR9u5Dc  

弁護士 亀石倫子（@MichikoKameishi）さんの返信があるツイート / Twitter https://t.co/ovLW4rphFw

　今日は，上記の亀石倫子弁護士のタイムラインでリツイートされていた奥村徹弁護士のツイートにあるリンクを開きました。昨日開いたリンクは，直接PDFファイルが開いたのですが，今回は次の法務省のホームページが開き，そのなかにPDFファイルのリンクがありました。

法務省：性犯罪に関する刑事法検討会　第３回会議（令和２年７月９日） https://t.co/pK9lO8QF6o

　「弱冠１４歳の少女がありもしない強姦被害等をでっち上げるまでして告訴すること自体非常に考えにくいことであって、もしそのような稀有なことがあるとすればよほどの特殊な事情がなければならないと考えられるところ，本件全証拠を子細に検討しても、」などとあります。

　再審無罪となった大阪の少女強姦事件のことと思いますが，国家賠償での大敗のことは触れられておらず，なんであれ結果が出れば，このように使えるのかと参考になったところでもあります。しかし，この事件の内容や国賠のことを知る人は，違和感が大きいように思えます。

　なんであれ，無罪という結果が大事ということであれば，なっとくの刑事弁護スピリッツではあります。漫画のような。

〈〈〈：Linux Emacs： 2020-07-23（木曜日）09：53 　〈〈〈

