* 深澤諭史弁護士の「発信者情報開示に係る意見照会書が届いた方へ（まとめと解説）」に非常によくまとめられていた，弁護士に対する疑問と不信感
  :LOGBOOK:
  CLOCK: [2020-08-18 火 09:42]--[2020-08-18 火 13:20] =>  3:38
  :END:

:CATEGORIES: 深澤諭史弁護士

〉〉〉：Emacs： 2020-08-18（火曜日）09：42　 〉〉〉

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2020/08/17 12:10 URL： https://twitter.com/fukazawas/status/1295196251470749696  

> 発信者情報開示に係る意見照会書が届いた方へ（まとめと解説） : 弁護士 深澤諭史のブログ https://t.co/NG2SQYbXzr  
> 相談がすごい多い、ネットのデマで自爆寸前な人もちらほらいるので、まとめました。  

　昨夜の遅い時間に上記のツイートのリンクを開き，読んだのですが，ツイートは昼の早い時間に見かけていました。今確認すると午後0時10分の投稿となっています。記事の日時はまだ確認していないのですが，ずいぶん古い記事の紹介というのも深澤諭史弁護士のツイートではよくあることです。

　深澤諭史弁護士が嫌がり，不当と考えるであろう全文引用を下記に行います。これは弁護士会や消費者庁のようなところに，苦情の申し出や適正の調査を求めるほどの問題性を含むものと考えますので，全趣旨を伝えるために全文の引用といたします。

　なお，コマンドを使って行頭に引用符をつけました。このあといくつか再捜査要請書＿警察庁・石川県警察御中（@kk_hirono）にツイートをしますが，深澤諭史弁護士のブログ記事の引用文になります。

(py37_env) a66@a66-XTe:~$ xsel -b |sed 's/^/> /'
```
> 最初にまとめをおいておきます。
> まず，落ち着きましょう。
> これが来たからといってあなたの投稿が違法であると確定したわけではありません。開示になると決まったわけでもありません。
> 「言葉」だけで決まる問題ではありません。私が投稿者を担当した事件でも，ここには書けないような汚い悪口でも非開示なったケースは複数あります。
> 仮にあなたの投稿が違法であるとしても，相手の言い分が全て通るわけでもなければ，いいなりになる必要があるわけではありません。
> 最近は，ＳＬＡＰＰ訴訟（恫喝訴訟）のようなケースも増えていますので，あなたが悪いと確定した訳ではありません。ただし，ＳＬＡＰＰと決めつけて自分で対処すると痛い目に遭いかねません。ＳＬＡＰＰだからこそ，巧妙であったりします。
> 刑事事件になる可能性もありますが，それはよっぽど悪質なものに限られます（ただし，最近は，そのハードルは下がっているので注意は必要です。）。
> 回答期限は延長してもらえるケースがほとんどです。「弁護士に相談している」といえば，なおさらです。まずは延長してもらって落ち着いて考えましょう。
> 弁護士にはすぐに相談に行きましょう。ギリギリですとうまくいきません。最悪なのが延長してもらってその期限も目前の段階でいくケースです。
> 不安なあなたはデマに弱くなっています。それは仕方の無いことですが，「ネットｄｅ真実」に目覚めて罠にはまらないでください。
> ネットで都合の良い情報をかき集めるのはよしましょう。
> 自分で回答書を作成するなら，「プラス」より「マイナス」に気をつけましょう。最近，これを発信者に不利な証拠に使う・使われるケースが増えています。
> 「示談は不利」はデマです。不利な示談はありますが，示談が不利な訳ではありません。
> 「金額は判例で決まる」はデマです。そんな都合のいい判例はありません。似たような悪口なのに１件当たり３０倍以上の差がついたことがあります（ただし３０倍になったのは本人訴訟なので一般化できません。）。
> 「本人訴訟で，せいぜい２０万３０万円で済む」というのもデマです。これはあり得ないわけではないですが，発信者情報開示請求を経由したネット上の表現トラブルで，かつ，被告本人訴訟に絞ると最近のものでは５０万円以下はほぼ見当たらず，平均値は１００万円程度です（個別判断ですので，この数字は絶対視すべきではないですが。）。
> 「裁判所は判例に従って公平に判断するから本人訴訟で大丈夫」もデマです。もしそうなら，前記の様な大差がつくわけありません。すこし訴訟法を勉強すれば分かりますが，「公平に判断する」から本人訴訟にリスクがあるのです。本人訴訟するなとはいいませんが，弁護士であっても自分の事件は弁護士を頼むことが普通です。
> 「名誉毀損と違ってプライバシー侵害は安心」はデマです。確かにプライバシー侵害は犯罪になりませんが，ネット上のプライバシー侵害は名誉毀損につながりやすいので分離はできないですし，賠償金はプライバシー侵害の方が高くなるケースもあり得ます。
> 「裁判外請求だから開示はあり得ない」もデマです。プロバイダと権利によっては開示されますので先例が重要です。
> 「自分に都合の良い情報→ネットｄｅ真実に目覚めた！」「自分に都合の悪い情報→工作員の仕業だ！」という思考に陥らないようにしましょう。完全にカルトと同じ心理状況で，判断を誤ったり騙されたりして危険です。
> この種事件の限りませんが，とにかく，狼狽して相手の言い分通りに応じることが１番に，そしてネット上の都合の良いだけのデマを信じ込むのが２番目に不利益なことです。まずは落ち着きましょう。
> 最近，「発信情報開示に係る意見照会書がとどいた」という相談が，特に個人の方から殺到しています。
> 基本的に，個人の方の相談ですので，初回無料の電話相談を実施していますが（念のため，都合等により承れないこともあります。） ，皆さん，かなり不安が大きい，ネットのデマに乗せられている，ということも多く，相談にたどり着けない人も多いのではないかと思います。
> 
> この問題については，ネット投稿者の責任についてのまとめＱ＆Ａ（＋ネット上の誤解）において，請求者（被害者であるとは限らないので，こういう言い方をしています。）と投稿者の双方の立場で，特にネット上の誤解・デマを中心に解説しました。
> また，弁護士向けの専門書として，これらの問題，経験を踏まえて「インターネット権利侵害 削除請求・発信者情報開示請求“後”の法的対応Ｑ＆Ａ」という本も出させて頂きました。
> 
> ただ，前者は長文ですし，後者はあくまで弁護士向けの書籍です。
> そこで，ひとまず落ち着くのが大事ということで，冒頭にまとめました。不安が強いと，不利な内容で和解（示談）してしまったり，「ネットｄｅ真実の法律情報に目覚めました！」みたいにデマと心中する羽目になります。
> 
> 冒頭にあるとおり，とにかく落ち着くこと，そして，これはどんな事件でもそうですが，紛争の渦中にあること，しかもそうなった直後というのは，一番判断力が低下しています。ネットのデマの餌食になりやすい，そのことを頭に入れておくだけでも，大分リスクは軽減出来ます。
> 
> ［source：］発信者情報開示に係る意見照会書が届いた方へ（まとめと解説） ： 弁護士 深澤諭史のブログ http://xn--zqs94lv37b.club/archives/23406240.html
```

　従来，深澤諭史弁護士のツイートやブログ記事で見かけてきた説明や表現がほとんどですが，これほどまとめられたものは今回が初めてかもしれません。いろいろと刺激を受けて思い出すこともありました。告発状の本文になりますが，そちらを優先したいと思います。

　「完全にカルトと同じ心理状況で，判断を誤ったり騙されたりして危険です。」という点が，最も印象的で，真新しく感じました。このブログ記事に対する感想と発見が，そのまま弁護士及び弁護士商売のカルト性の象徴になります。

　深澤諭史弁護士の記事には，言葉の持つ意味についても考えさせられ，これまでツイートで見かけたような言葉を含め，改めてまとめ記事を作成，記録しました。今朝になってからも継続しましたが，次の流れとなりました。

```
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb fukazawas 'ゲーム' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "fukazawas") AND  tweet REGEXP "ゲーム"  ORDER BY tw_date ASC
REGEXP：”ゲーム”／深澤諭史（@fukazawas）の検索（2013-02-07〜2020-07-07／2020年08月18日02時44分の記録161件）
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb fukazawas '心中' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "fukazawas") AND  tweet REGEXP "心中"  ORDER BY tw_date ASC
REGEXP：”心中”／深澤諭史（@fukazawas）の検索（2016-09-22〜2020-07-07／2020年08月18日02時50分の記録16件）
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb fukazawas '不安' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "fukazawas") AND  tweet REGEXP "不安"  ORDER BY tw_date ASC
REGEXP：”不安”／深澤諭史（@fukazawas）の検索（2013-05-22〜2020-08-17／2020年08月18日02時51分の記録224件）
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb fukazawas '判断' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "fukazawas") AND  tweet REGEXP "判断"  ORDER BY tw_date ASC
REGEXP：”判断”／深澤諭史（@fukazawas）の検索（2012-09-07〜2020-08-13／2020年08月18日02時51分の記録487件）
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb fukazawas 'デマ' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "fukazawas") AND  tweet REGEXP "デマ"  ORDER BY tw_date ASC
REGEXP：”デマ”／深澤諭史（@fukazawas）の検索（2013-09-19〜2020-08-17／2020年08月18日02時52分の記録268件）
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb fukazawas '渦中' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "fukazawas") AND  tweet REGEXP "渦中"  ORDER BY tw_date ASC
none
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb fukazawas '示談' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "fukazawas") AND  tweet REGEXP "示談"  ORDER BY tw_date ASC
REGEXP：”示談”／深澤諭史（@fukazawas）の検索（2013-04-15〜2020-06-10／2020年08月18日02時53分の記録140件）
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb fukazawas '経験' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "fukazawas") AND  tweet REGEXP "経験"  ORDER BY tw_date ASC
REGEXP：”経験”／深澤諭史（@fukazawas）の検索（2012-12-07〜2020-07-30／2020年08月18日02時53分の記録481件）
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb fukazawas '被害者' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "fukazawas") AND  tweet REGEXP "被害者"  ORDER BY tw_date ASC
REGEXP：”被害者”／深澤諭史（@fukazawas）の検索（2012-09-26〜2020-08-13／2020年08月18日02時53分の記録630件）
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb fukazawas '無料' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "fukazawas") AND  tweet REGEXP "無料"  ORDER BY tw_date ASC
REGEXP：”無料”／深澤諭史（@fukazawas）の検索（2012-12-14〜2020-08-16／2020年08月18日02時54分の記録392件）
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb fukazawas '専門書' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "fukazawas") AND  tweet REGEXP "専門書"  ORDER BY tw_date ASC
REGEXP：”専門書”／深澤諭史（@fukazawas）の検索（2016-08-20〜2020-03-15／2020年08月18日02時54分の記録9件）
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb fukazawas '成仏' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "fukazawas") AND  tweet REGEXP "成仏"  ORDER BY tw_date ASC
REGEXP：”成仏”／深澤諭史（@fukazawas）の検索（2012-12-15〜2020-08-16／2020年08月18日09時35分の記録730件）
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb fukazawas '発信者情報開示' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "fukazawas") AND  tweet REGEXP "発信者情報開示"  ORDER BY tw_date ASC
REGEXP：”発信者情報開示”／深澤諭史（@fukazawas）の検索（2012-12-23〜2020-08-17／2020年08月18日09時36分の記録189件）
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb fukazawas 'カルト' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "fukazawas") AND  tweet REGEXP "カルト"  ORDER BY tw_date ASC
REGEXP：”カルト”／深澤諭史（@fukazawas）の検索（2014-02-08〜2020-04-25／2020年08月18日10時02分の記録32件）
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb fukazawas 'カルト' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "fukazawas") AND  tweet REGEXP "カルト"  ORDER BY tw_date ASC
REGEXP：”カルト”／深澤諭史（@fukazawas）の検索（2014-02-08〜2020-04-25／2020年08月18日10時02分の記録32件）
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb fukazawas 'デマ' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "fukazawas") AND  tweet REGEXP "デマ"  ORDER BY tw_date ASC
REGEXP：”デマ”／深澤諭史（@fukazawas）の検索（2013-09-19〜2020-08-17／2020年08月18日10時09分の記録268件）
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb fukazawas 'ウソ' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "fukazawas") AND  tweet REGEXP "ウソ"  ORDER BY tw_date ASC
REGEXP：”ウソ”／深澤諭史（@fukazawas）の検索（2015-07-22〜2020-08-16／2020年08月18日10時10分の記録120件）
```

　次が投稿済みの記事の一覧になります。深澤諭史弁護士とは無関係のものを含みますが，連続した流れになります。前後関係が憶えにないですが，俳優の山下智久さんの問題をTwitterのトレンドで知り，これも弁護士の社会的影響について考えさせられるところでした。

```
 - 2020年08月17日20時34分の登録： ＼深澤諭史　@fukazawas＼非弁なサービスを見ながらいつも思うのは （・∀・）「素晴らしいサービスですねー！完璧ですよ！非弁で犯罪だってところだけを除けば〜！！！」 http://hirono2014sk.blogspot.com/2020/08/fukazawas_91.html
 - 2020年08月17日20時35分の登録： ＼北白川　@GUv4i6＼「闘う相手は，悪い奴らだけでなく，その弁護人もいる」  俺もつい熱くなって検事にぶち切れるときあるけど，お互い敵味方みたいな思考はいけないよね。 http://hirono2014sk.blogspot.com/2020/08/guv4i6_25.html
 - 2020年08月17日21時27分の登録： ＼嶋﨑量（弁護士）　@shima_chikara＼Yahoo!ニューストップ、きました！ ありがとうございます。 子ども達のためにも学校を変えたいと願う先生方に届いて欲し http://hirono2014sk.blogspot.com/2020/08/shimachikarayahoo.html
 - 2020年08月17日21時36分の登録： ＼えきなんローヤー?　@ekinan_lawyer＼ツイッターやってる修習生は、そこそこオンライン環境を整えているので。  阿鼻叫喚になっている修習生は、TL上に観測され http://hirono2014sk.blogspot.com/2020/08/ekinanlawyer-tl.html
 - 2020年08月17日21時37分の登録： ＼中村元弥　@1961kumachin＼お爺ちゃんはただの店番っと  76歳弁護士を除名処分 過払い金未返還など 第二東京弁護士会 | NHKニュース http://hirono2014sk.blogspot.com/2020/08/1961kumachin-76-nhk.html
 - 2020年08月17日23時05分の登録： ＼すてぃっち　@TAS6284＼某先生、最近色んなアカウントに自分から絡みにいって、噛み付かれて、無駄な議論をしてるけど、精神的にヤバい時期なのではなかろうか… http://hirono2014sk.blogspot.com/2020/08/tas6284.html
 - 2020年08月17日23時06分の登録： ＼えきなんローヤー?　@ekinan_lawyer＼今日、73期修習生に、研修所所長の講話がチームズでされたっぽい。  画像流出しなければ良いのだが… http://hirono2014sk.blogspot.com/2020/08/ekinanlawyer73.html
 - 2020年08月17日23時08分の登録： ＼弁護士 亀石倫子　@MichikoKameishi＼中学時代の後輩であるミルクボーイ駒場さんのSNSに「死ね」「殺すぞ」「返信しろ」といったメッセージを複数回送った男に http://hirono2014sk.blogspot.com/2020/08/michikokameishisns.html
 - 2020年08月17日23時16分の登録： ＼野田隼人　@nodahayato＼ネットワーク的な関係性を基本とするTwitterで馬鹿に絡んでもそいつのプレゼンスをあげるだけなので、原則的にはミュートなりブロックな http://hirono2014sk.blogspot.com/2020/08/nodahayatotwitter.html
 - 2020年08月17日23時20分の登録： ＼えきなんローヤー?　@ekinan_lawyer＼明日からA班はオンライン修習か…  接続とか、うまくいく方が奇跡。 http://hirono2014sk.blogspot.com/2020/08/ekinanlawyera.html
 - 2020年08月17日23時22分の登録： ＼霞 司郎?️　@kasumi_shiro＼裁判官ツイッタラーなんていないよね。 たまにいても、すぐ止めてしまう。 http://hirono2014sk.blogspot.com/2020/08/kasumishiro_17.html
 - 2020年08月17日23時41分の登録： ＼豚野郎　@butayar0＼月刊懲戒８月号，都市部の先生の事件放置型が目立つが，事件数が多くなりすぎて，管理できなかったのだろうか。都市部は弁護士密度が高くて顧客獲得競 http://hirono2014sk.blogspot.com/2020/08/butayar0.html
 - 2020年08月17日23時43分の登録： ＼えきなんローヤー?　@ekinan_lawyer＼基本は、絡んできたらブロックでしょう。絡まれること自体が、面倒なんだからさ。  中の人が面白そうなアカウントとか、面倒 http://hirono2014sk.blogspot.com/2020/08/ekinanlawyer_17.html
 - 2020年08月17日23時58分の登録： ＼ystk　@lawkus＼名誉毀損では警察はなかなか動いてくれないから被害者としては事実上民事一択になったりするけど、民事で負けても金払うつもりも詫びるつもりもない、押 http://hirono2014sk.blogspot.com/2020/08/ystklawkus_17.html
 - 2020年08月18日00時01分の登録： ＼弁護士樋詰哲朗　@hizumelaw＼クラウドベースの事件管理システムのLEALA、firmee、LegalWinがあるけど、どれが使い勝手がよいのだろうか。各種書類作 http://hirono2014sk.blogspot.com/2020/08/hizumelawlealafirmeelegalwin.html
 - 2020年08月18日00時02分の登録： ＼弁護士樋詰哲朗　@hizumelaw＼irmeeが一番かなと思いました。 しかし、弊所では紆余曲折あって、結局、事務局に管理してもらうのが一番早いという結論になりました http://hirono2014sk.blogspot.com/2020/08/hizumelawirmee.html
 - 2020年08月18日00時02分の登録： ツイートの記録資料：＼法務検察・石川県警察宛＼／モトケン（@motoken_tw）／”2020年08月17日”：42件 http://hirono2014sk.blogspot.com/2020/08/motokentw2020081742.html
 - 2020年08月18日00時02分の登録： ツイートの記録資料：＼法務検察・石川県警察宛＼／深澤諭史（@fukazawas）／”2020年08月17日”：68件 http://hirono2014sk.blogspot.com/2020/08/fukazawas2020081768.html
 - 2020年08月18日00時04分の登録： 2020-08-17の投稿一覧＼検察・石川県警察宛記録資料＼奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中：36件 http://hirono2014sk.blogspot.com/2020/08/2020-08-1736.html
 - 2020年08月18日00時14分の登録： REGEXP：”事務局”／深澤諭史（@fukazawas）の検索（2013-08-12〜2020-08-06／2020年08月18日00時14分の記録79件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2013-08-122020-08.html
 - 2020年08月18日01時23分の登録： REGEXP：”山下智久”／データベース登録済みツイート：2020年08月18日01時23分の記録：ユーザ・投稿：10／23件 http://hirono2014sk.blogspot.com/2020/08/regexp2020081801231023.html
 - 2020年08月18日01時34分の登録： REGEXP：”事務局”／データベース登録済みツイート：2020年08月18日01時24分の記録：ユーザ・投稿：265／832件 http://hirono2014sk.blogspot.com/2020/08/regexp202008180124265832.html
 - 2020年08月18日02時26分の登録： REGEXP：”山口達也”／データベース登録済みツイート：2020年08月18日02時22分の記録：ユーザ・投稿：82／224件 http://hirono2014sk.blogspot.com/2020/08/regexp20200818022282224.html
 - 2020年08月18日02時44分の登録： REGEXP：”ゲーム”／深澤諭史（@fukazawas）の検索（2013-02-07〜2020-07-07／2020年08月18日02時44分の記録161件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2013-02-072020-07.html
 - 2020年08月18日02時51分の登録： REGEXP：”心中”／深澤諭史（@fukazawas）の検索（2016-09-22〜2020-07-07／2020年08月18日02時50分の記録16件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2016-09-222020-07.html
 - 2020年08月18日02時51分の登録： REGEXP：”不安”／深澤諭史（@fukazawas）の検索（2013-05-22〜2020-08-17／2020年08月18日02時51分の記録224件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2013-05-222020-08.html
 - 2020年08月18日02時51分の登録： REGEXP：”判断”／深澤諭史（@fukazawas）の検索（2012-09-07〜2020-08-13／2020年08月18日02時51分の記録487件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2012-09-072020-08.html
 - 2020年08月18日02時52分の登録： REGEXP：”デマ”／深澤諭史（@fukazawas）の検索（2013-09-19〜2020-08-17／2020年08月18日02時52分の記録268件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2013-09-192020-08.html
 - 2020年08月18日02時53分の登録： REGEXP：”示談”／深澤諭史（@fukazawas）の検索（2013-04-15〜2020-06-10／2020年08月18日02時53分の記録140件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2013-04-152020-06.html
 - 2020年08月18日02時53分の登録： REGEXP：”経験”／深澤諭史（@fukazawas）の検索（2012-12-07〜2020-07-30／2020年08月18日02時53分の記録481件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2012-12-072020-07.html
 - 2020年08月18日02時54分の登録： REGEXP：”被害者”／深澤諭史（@fukazawas）の検索（2012-09-26〜2020-08-13／2020年08月18日02時53分の記録630件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2012-09-262020-08_18.html
 - 2020年08月18日02時54分の登録： REGEXP：”無料”／深澤諭史（@fukazawas）の検索（2012-12-14〜2020-08-16／2020年08月18日02時54分の記録392件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2012-12-142020-08_18.html
 - 2020年08月18日02時54分の登録： REGEXP：”専門書”／深澤諭史（@fukazawas）の検索（2016-08-20〜2020-03-15／2020年08月18日02時54分の記録9件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2016-08-202020-03.html
 - 2020年08月18日09時33分の登録： ＼なべきょう＠過眠症　@wata_nabekyo_ko＼以前は、ホームレスの被疑者被告人の支援についてたまにお問い合わせが来ていました。おそらくゼロベースから、よく当職に http://hirono2014sk.blogspot.com/2020/08/watanabekyoko_18.html
 - 2020年08月18日09時35分の登録： REGEXP：”成仏”／深澤諭史（@fukazawas）の検索（2012-12-15〜2020-08-16／2020年08月18日09時35分の記録730件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2012-12-152020-08_18.html
 - 2020年08月18日09時36分の登録： REGEXP：”発信者情報開示”／深澤諭史（@fukazawas）の検索（2012-12-23〜2020-08-17／2020年08月18日09時36分の記録189件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2012-12-232020-08.html
 - 2020年08月18日10時02分の登録： REGEXP：”カルト”／深澤諭史（@fukazawas）の検索（2014-02-08〜2020-04-25／2020年08月18日10時02分の記録32件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2014-02-082020-04.html
 - 2020年08月18日10時09分の登録： REGEXP：”デマ”／深澤諭史（@fukazawas）の検索（2013-09-19〜2020-08-17／2020年08月18日10時09分の記録268件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2013-09-192020-08_18.html
 - 2020年08月18日10時10分の登録： REGEXP：”ウソ”／深澤諭史（@fukazawas）の検索（2015-07-22〜2020-08-16／2020年08月18日10時10分の記録120件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2015-07-222020-08.html
```

　カルト的弁護士商法としか思えない深澤諭史弁護士のツイートやブログ記事になります。とにかく触発され，「事務局」という言葉が頭に浮かんできて，まとめ記事を作成し，深澤諭史弁護士個人と登録全ユーザーの事務局の間に，「山下智久」というキーワードが挟まっている格好です。

 - （01／79） TW fukazawas（深澤諭史） 日時：2013-08-12 15:07:00 +0900 URL： https://twitter.com/fukazawas/status/366803114935853059

> 法の光教団が想定した淘汰とは，弁護士が経済的に行き詰まったら，残務処理をすべて綺麗にして，アソシエイト，事務局の解雇もつつがなく行い，綺麗に片付いた自室で，「法の光神万歳！」っていいながら切腹する，というものだったんでしょうね（笑） RT

　最近は法クラのツイートでも見かけなくなった「法の光」というワードですが，「クソテラス」も同じです。どちらも法テラスを揶揄したものと思われます。

 - （02／79） TW fukazawas（深澤諭史） 日時：2013-12-11 13:52:00 +0900 URL： https://twitter.com/fukazawas/status/410633108174544898

> ＊正しい弁護士の淘汰のされ方＊
> １．残務処理をきちんとする
> ２．預かり金は全部返す。
> ３．事務局の解雇もつつがなく
> ４．事務所も綺麗に引き払う
> ５．法の光神様万歳！理念万歳！成仏！と呪文を唱えながら切腹する。
>
> ５はもちろん皮肉です。

 - （05／79） TW fukazawas（深澤諭史） 日時：2014-05-21 21:51:00 +0900 URL： https://twitter.com/fukazawas/status/469098224674811904

> たびたび法クラでは既出の話題ですが。
>
> 弁護士は，自分が脅されたり，暴言を吐かれたりしても，それも仕事だと思ったりする事はありますが（でも許さない。）， 事務局が脅されたり暴言を吐かれたりした場合には，絶対に許しませんし，妥協しません。
>
> 事務局を守るのは弁護士の義務なので。

　上記が，「事務局」をワードにした深澤諭史弁護士のツイートで，強く印象に残り，余韻を引くように考えさせられた問題です。2014年5月21日のツイートと確認しましたが，宇都宮市で元自衛隊幹部が爆発自殺の事件を起こしたのもその頃ではなかったかと思います。それも弁護士絡みでした。

　このあと調べて確認をしますが，事務局というのは，弁護士の法律事務所の事務と，弁護士会の事務局があるのではと見ています。事務員の数が何人いるのかわからないですが，深澤諭史弁護士の発言は当時から過激性があり，事務員の生命身体に危険を発生させているのではと想像していました。

＜宇都宮公園爆発「栗原敏勝容疑者」と絡んだ「4名の女性弁護士」＞「横山幸子弁護士」「根元智子弁護士」「柾 智子 (まさき)弁護士」「和地郁枝（わち）弁護士」栃木県弁護士会元会長や元検事のヤメ検弁護士も！？ - 栃木県介護被害者会（介護事件事故・高齢者虐待・告発） https://t.co/fzTaIuU8i1

　すごく長いページタイトルだったので，ツイートは出来ないかと思ったのですが，残り1文字となっていました。そういえば最近見ていない奥村徹弁護士のブログですが，あちらは到底，ツイートなどできない文字の長さとなっていました。メールアドレスや電話番号も入っていたかもしれません。

　時間のこともあるので，部分的にしか読んでいないのですが，上告断念申立書という書面の写しがあって，そこに「本人訴訟が故に，読みもしないで全て却下し，ゴミ箱に投げ捨てた。」とあります。最高裁なのかと思ったら東京高裁となっていました。

　この宇都宮市の爆発事件のこともちょくちょくと思い出していたのですが，娘が精神的な病と診断され，宗教に救いを求めるようになったというのは，忘れていたことです。その少し前に，それらしいことがあったように思い出していたのですが，例のごとく確認の持てる記憶ではありませんでした。

　さきほどの深澤諭史弁護士のまとめ記事に，「クレーマー」と「ストーカー」が抜けていたことは，しばらく前に思い出していたのですが，この「本人訴訟」というのも深澤諭史弁護士ならではの特別なキーワードになります。

```
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb fukazawas 'クレーマー' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "fukazawas") AND  tweet REGEXP "クレーマー"  ORDER BY tw_date ASC
REGEXP：”クレーマー”／深澤諭史（@fukazawas）の検索（2015-02-04〜2020-08-17／2020年08月18日10時59分の記録75件）
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb fukazawas 'ストーカー' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "fukazawas") AND  tweet REGEXP "ストーカー"  ORDER BY tw_date ASC
REGEXP：”ストーカー”／深澤諭史（@fukazawas）の検索（2015-05-18〜2020-08-05／2020年08月18日11時00分の記録229件）
➜  ~ ajx-user-mysql-REGEXP_blogger_hirono2014sk.rb fukazawas '本人訴訟' '1000-01-01/3000-01-01'
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1000-01-01' AND '3000-01-01' AND (user LIKE "fukazawas") AND  tweet REGEXP "本人訴訟"  ORDER BY tw_date ASC
REGEXP：”本人訴訟”／深澤諭史（@fukazawas）の検索（2012-12-22〜2020-08-17／2020年08月18日11時00分の記録371件）
```

　たまたま抜けた3つになりますが，コマンドの実行結果に並んだ言葉をみると，「クレーマー」，「ストーカー」，「本人訴訟」というのは，深澤諭史弁護士の特徴をあらわす，三大キーワードに思えてきました。弁護士脳の謎に迫れる納得のツイートが散りばめられていると思います。

```
 - 2020年08月18日11時00分の登録： REGEXP：”クレーマー”／深澤諭史（@fukazawas）の検索（2015-02-04〜2020-08-17／2020年08月18日10時59分の記録75件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2015-02-042020-08.html
 - 2020年08月18日11時00分の登録： REGEXP：”ストーカー”／深澤諭史（@fukazawas）の検索（2015-05-18〜2020-08-05／2020年08月18日11時00分の記録229件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2015-05-182020-08_18.html
 - 2020年08月18日11時00分の登録： REGEXP：”本人訴訟”／深澤諭史（@fukazawas）の検索（2012-12-22〜2020-08-17／2020年08月18日11時00分の記録371件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2012-12-222020-08.html
```

＜宇都宮城址公園爆発事件＞栗原敏勝容疑者 爆破自宅のその後・・・・。栗原敏勝容疑者、奥さんとの訴訟に絡んだ原告側「横山幸子弁護士」は現在、栃木小１女児殺害事件での原告側弁護士。 - 栃木県介護被害者会（介護事件事故・高齢者虐待・告発） https://t.co/jbwknK2em6

　栃木県弁護士会の懲戒請求に対する決定書というのがありました。こちらは写真なのかもしれません。「「横山幸子弁護士」は現在、栃木小１女児殺害事件での原告側弁護士」というのはずっと前に情報を見ていたのですが，いつの間にか4人の女性弁護士になっていました。

　探しているのは事件の発生時期になります。

```
宇都宮市連続爆発事件（うつのみやし れんぞくばくはつじけん）とは、2016年10月23日に栃木県宇都宮市内の近接した3ヵ所で連続して起こった爆発事件。

［source：］宇都宮市連続爆発事件 - Wikipedia https://ja.wikipedia.org/wiki/%E5%AE%87%E9%83%BD%E5%AE%AE%E5%B8%82%E9%80%A3%E7%B6%9A%E7%88%86%E7%99%BA%E4%BA%8B%E4%BB%B6
```

　2016年10月23日の事件と確認しました。ずいぶん前という感覚で2014年あたりを想定していました。もう一つ，最近も作成，記録しているものですが，深澤諭史弁護士のツイートに「逆恨み」というキーワードがあります。弁護士の問題性というのは綺麗サッパリ一片も感じさせません。

 - 2020年08月18日11時15分の登録： REGEXP：”逆恨み”／深澤諭史（@fukazawas）の検索（2014-09-22〜2020-08-08／2020年08月18日11時15分の記録56件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2014-09-222020-08_18.html

　事務局のまとめの続きに戻ります。

 - （06／79） TW fukazawas（深澤諭史） 日時：2014-10-28 16:55:00 +0900 URL： https://twitter.com/fukazawas/status/527005698559705088

> そういう人からの依頼は絶対に受けません(･∀･＃) RT @Noooooooorth なお経験上弁護士に対しては低姿勢なのに事務局に対しては異常に高圧的な人間は「先生」と呼ばれている人間に多い。権威主義的なんだろうか。

 - （08／79） TW fukazawas（深澤諭史） 日時：2015-09-01 16:34:00 +0900 URL： https://twitter.com/fukazawas/status/638615827567149056

> 法律事務所における，「事務局に横柄・無礼」「事務局に話は伝えず，何が何でも弁護士とだけ話そうとする」人についても，同じ事がいえるな。
> 相談者や相手方本人の両方においていえる。
>
> https://t.co/W2TmbTdJwh

　最近は見かけないですが，弁護士が事務員に対応させ，いい加減な処理をしているという話は，一時期，わりと見かけていました。一昨日あたりも，弁護士会の対応を讃える深澤諭史弁護士のツイートを見かけた，東京ミネルヴァ法律事務所の問題ですが，弁護士以外の発言を全く見ていません。

　テレビでも短いニュースを１つ見ただけでしたが，弁護士に対する不信や反感というのは，骨髄に染み渡るもので広く社会に浸透しているとも考えられ，そのうち大規模な地滑り現象が発生するのではないかと考えたり，それが深澤諭史弁護士を後先のない発言に駆り立てているのかと考えたりします。

 - （12／79） TW fukazawas（深澤諭史） 日時：2016-02-27 11:33:00 +0900 URL： https://twitter.com/fukazawas/status/703407556325081090

> 弁護士が脅迫をうけるって、結構大変な問題なんですよね。
> 実際問題、殴られたりしなくても、事務所の前で大声を上げられたり、脅迫電話を何回もかけられたりするだけでも、相当に精神には来るし、仕事の支障にもなりかねない。なにより、事務局に恐怖を覚えさせるのは申し訳ない。

　これも見覚えのあるツイートになりますが，本当の体験談であれば，そのうちもっと大きなことになって，テレビニュースで深澤諭史弁護士を見ることもあるのではないかと考えることがありました。作り話のような気もするので，微妙です。いずれも相手が見ていれば，火に油を注ぐことになりそうです。

 - （13／79） TW fukazawas（深澤諭史） 日時：2016-02-27 11:46:00 +0900 URL： https://twitter.com/fukazawas/status/703410790473162752

> ①一度はっきりと拒絶する　②①をしたら同じことは２、３回も繰り返さない。繰り返すと「期待」を持たせてしまう　③脅迫が手段となった要求には、些細でも一切応じない。つまり、脅迫に成果を与えない。
> というのが基本でしょうか。厳正対処は、自分のためだけでなく事務局のためでもあります。

 - （17／79） TW fukazawas（深澤諭史） 日時：2016-05-25 17:21:00 +0900 URL： https://twitter.com/fukazawas/status/735385186272169985

> https://t.co/BgZXjwleTN
> 世の中，万が一にも勘違いする人がいると思うから，念のため。
> これ，別に，お高くとまっているとか，そういうことじゃないですよ。
> 事務局や他の弁護士，事務所全体を危険から守るためです。

 - （16／79） RT fukazawas（深澤諭史）｜nodahayato（弁護士　野田隼人） 日時：2016-05-25 17:19:00 +0900／2016-05-25 17:18:00 +0900 URL： https://twitter.com/fukazawas/status/735384864959156224 https://twitter.com/nodahayato/status/735384482128232449

> 弊所に電話をしてきて，事務局に対して社会人としてあり得ない対応があった場合，私の判断で相談等を謝絶します。

　このようなツイートを深澤諭史弁護士のタイムラインでたくさん見てきたので，弁護士脳の社会的危険性を強く考えるようになりました。警察の仕事も増えることでしょう。

 - （20／79） TW fukazawas（深澤諭史） 日時：2016-06-12 10:09:00 +0900 URL： https://twitter.com/fukazawas/status/741799504802811904

> 「都合のよい答えをもらえないと怒鳴り出す相談者，弁護士の前では従順な態度をとっていたのに，事務局には横柄な態度をとる相談者・・。」

　この相談者という本人が，このツイートを見たらどう考えるのかと，想像せずにはいられません。

 - （60／79） TW fukazawas（深澤諭史） 日時：2018-05-11 12:10:00 +0900 URL： https://twitter.com/fukazawas/status/994776764781088768

> なぜか，うちにも嫌がらせ電話がきましたけれども，私でなくて，うちの大事な大事な事務局に暴言をぶつけた方には，もちろん，責任を取って頂く所存です。
> 電話は匿名だって勘違いしてないでしょうね？

　続けて同じような内容のツイートをみていると，深澤諭史弁護士はありもしない架空の話をしているのではないかと思えてきました。

 - （61／79） TW fukazawas（深澤諭史） 日時：2018-06-19 09:33:00 +0900 URL： https://twitter.com/fukazawas/status/1008870295745191936

> 法律相談に関する業務妨害としては，さほど経験は多くないけれども，相談中に怒鳴る，机を叩くなど，粗暴な振る舞いを弁護士や事務局にする，相談後に脅迫電話をする，ネットに中傷を投稿する（なぜか会ってもいない事務所の他の弁護士についても投… https://t.co/Bm4fb6Byee

　何度かGoogleで深澤諭史弁護士の名前で検索をしましたが，深澤諭史弁護士を名指しで批判する記事は見たことがありません。ただ一つ，検索のトップの方に気になる内容の記事がいつも表示されていました。今もあるのかわかりません。

深澤諭史弁護士 - Google 検索 https://t.co/zoQuigDvwX

　上記の検索の8ページ目の6番目にようやくみつけました。いちおう10ページ目までは確認するつもりでいました。以前は1ページ目の上の方に表示があったので，削除されたのかと考えていたタイミングでの発見です。次の記事になります。

```
> ネットの表現の自由に関するインタビュー記事「ネット：そのつぶやきは法律違反？　注意点を深澤弁護士に聞く」があったので読んでみました。

> で、深澤諭史弁護士のことを知りませんでしたので事務所名でググってみたところ、http：//刑事弁護士.jp/とか、http：//出会い系詐欺.jp/とか、http：//債権回収弁護士.net/とか、似たような紋切り型のホームページが大量にヒットしました。

> いったい、どんだけあるのかと思ってJPRS WHOISで調べてみると、ほとんどSPAMとしか思えないほどの異常な営業活動っぷりにドン引きです。まだ名前だけでホームページが無いものもあるようなので、これからドンドン増えていくのでしょう。

［source：］［悪徳商法？支店］： 深澤諭史弁護士（服部啓法律事務所）の異常に頑張る宣伝活動 https://beyond.cocolog-nifty.com/akutoku/2014/07/post-6462.html
```

 2014年7月3日となっています。URLをみてココログのブログらしいと初めてわかりました。ページの体裁が，最近はみかけなくなっているWikiに似ています。

　検索結果の8ページ目だとなかなかひと目にはつかないと思いますが，そこに至るまでも深澤諭史弁護士に批判的な記事は見かけませんでした。Googleのページの下に検索候補の表示があって，そこに「深澤諭史弁護士　評判」というのがありました。

```
深澤諭史 on Twitter： "自動車保険は，ほんと，弁護士の評判を ...twitter.com › fukazawas › status
2018/08/31 - 自動車保険は，ほんと，弁護士の評判を聞いて決めた方がいいですよ。 不合理な払い渋りをする損保だと，人身事故のとき，被害者の被害感情を煽って，本当なら付くはずの無かった前科が付くことになります。 罰金とか ...


［source：］深澤諭史 評判 - Google 検索 https://www.google.co.jp/search?sxsrf=ALeKk001eEJzLhJs5rgieYPuczw8wQqvkg:1597718449608&q=%E6%B7%B1%E6%BE%A4%E8%AB%AD%E5%8F%B2+%E8%A9%95%E5%88%A4&sa=X&ved=2ahUKEwiP_I6F3aPrAhWVwosBHbmlDGU4RhDVAigAegQICxAB&biw=1920&bih=921
```

　なぜか検索結果の1番目が，自動車保険の深澤諭史弁護士のツイートになっていました。「深澤諭史 on Twitter： "自動車保険は，ほんと，弁護士の評判を ...」とあるもので，これは目的をもって検索した人の探したものとは，ずれているような気がします。

　このようにネットの表面上に深澤諭史弁護士を問題視し，批判する情報が，上記に紹介した1つの例外を除いて，殆どないことは，少なくとも通常の観測の範囲としては明らかと思います。しかし，これは逆に，弁護士という業界内部の信頼を破壊するという地下変動を推測させるものと考えます。

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2018/09/01 09:22 URL： https://twitter.com/fukazawas/status/1035684391823929344  

> 自動車保険は，ほんと，弁護士の評判を聞いて決めた方がいいですよ。  
> 不合理な払い渋りをする損保だと，人身事故のとき，被害者の被害感情を煽って，本当なら付くはずの無かった前科が付くことになります。  
> 罰金とか執行猶予付懲役刑とか。  
> （・∀・；）  

　時刻は12時01分です。気がつくと昼になっていました。そういえば，ここ数日，ジャーナリストの江川紹子氏のタイムラインを開いていないと思い，ブックマークから開いたところ，タイムラインにちょっと気になる社会問題のツイートがありました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜amneris84（Shoko Egawa） 日時：2020-08-18 12:02／2020/08/17 11:11 URL： https://twitter.com/kk_hirono/status/1295556733339721730 https://twitter.com/amneris84/status/1295181384827322368  

> コロナに次に殺されるのは「大学」。大学教員の大量失業が始まった https://t.co/pL0UyO3cRa  〈大学の本質的価値はオンラインで提供できない〉のだけど、と  

　大学の死活問題のようですが，深澤諭史弁護士がよく批判の矛先を向けるのも法科大学院のロースクールになります。テレビのニュースではみていないのですが，新型コロナウィルスの影響で，司法試験の受験者の数が記録的に少なかった。同確率はどうなるのかと法クラで話題となっていました。

　そのロースクールを批判する深澤諭史弁護士自身が，東京大学法科大学院の出身とのことなので，出身大学との関係が良いものとは考えられないところです。深澤諭史弁護士は伊藤塾のテキストで司法試験の勉強をしたともツイートをしていたと思いますし，伊藤塾や伊藤真弁護士は評価しているようです。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜amneris84（Shoko Egawa） 日時：2020-08-18 12:10／2020/08/16 10:33 URL： https://twitter.com/kk_hirono/status/1295558543123181568 https://twitter.com/amneris84/status/1294809354231623680  

> 昨夜のNスペでもやっていた、民間人の戦争犠牲者への補償問題。　→常夏通信：その51　74年目の東京大空襲(37)　同じ敗戦国のドイツは民間人にも補償 - 毎日新聞 https://t.co/RrMjdcfxPk  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜amneris84（Shoko Egawa） 日時：2020-08-18 12:10／2020/08/15 22:28 URL： https://twitter.com/kk_hirono/status/1295558620835266566 https://twitter.com/amneris84/status/1294626929220284416  

> 民間の犠牲には冷たい日本という国…。国家も、民間も。寄せられた誹謗中傷の手紙に慄然とする。この時代にSNSが普及していたら、もっとひどかったかもしれない。 https://t.co/jv0B8gqArr  

　ネットのテレビ欄で，22時頃から始まるときと21時頃から始まるときがある北陸朝日放送の情報番組が，21時頃からの放送と知り，テレビをつけ，すぐにリモコンでチャンネル変更したのですが，テレビがついたタイミングで目に飛び込んだなんだかわからない映像が気になり，NHKに戻しました。

　どういう番組かわからないまま，いきなり視聴を始めることになったのですが，それが戦後補償の特集番組でした。不思議とTwitterでもトレンドになっておらず，弁護士のタイムラインでも見かけることがなかったと思います。

```
2020年08月18日12時22分の実行記録
APIのリミットに達するので8500で処理と中断しました。
twitterAPI-search-lawList-mydql-add.rb "戦後補償"
ツイート数：12/1956 リツイート数：36/1956 トータル：8500
hirono_hideki 0／0件
kk_hirono 1／2件
s_hirono 0／0件
```

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜a_ranking_news（書籍ランキング速報） 日時：2020-08-18 12:36／2020/08/16 19:12 URL： https://twitter.com/kk_hirono/status/1295565326877224960 https://twitter.com/a_ranking_news/status/1294939963465691136  

> (8/16) honto 本の通販ストアランキング &gt; 法学・法律 &gt; 司法・裁判・訴訟法ランキング2位:深澤 諭史 （著）『まんが弁護士が教えるウソを見抜く方法』 https://t.co/CqSbGxblbA  

 - 2020年08月18日12時28分の登録： REGEXP：”戦後補償”／データベース登録済みツイート：2020年08月18日12時27分の記録：ユーザ・投稿：21／29件 http://hirono2014sk.blogspot.com/2020/08/regexp2020081812272129.html

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜rkayama（香山リカ） 日時：2020-08-18 12:58／2020/08/16 13:35 URL： https://twitter.com/kk_hirono/status/1295570671813066753 https://twitter.com/rkayama/status/1294855230824226816  

> 昨日のNスペ『忘れられた戦後補償』が話題です。番組中、下の私のツイートにあるように、補償を求めて声をあげる戦争被害者に心ないハガキが届きました。すぐ下は水俣病、新潟水俣病患者へのハガキの一例です。被害者を「金ほしさ」「ニセモノ」と愚弄する。ネトウヨとまったく同じです。 https://t.co/vDgBQkOXgq https://t.co/M7RlHgQHGs  

 - （06／29） RT butayar0（豚野郎）｜rkayama（香山リカ） 日時：2020-08-16 13:48:00 +0900／2020-08-16 13:35:00 +0900 URL： https://twitter.com/butayar0/status/1294858651694329856 https://twitter.com/rkayama/status/1294855230824226816

 - （15／29） TW sanngatuusagino（弁護士 上瀧浩子） 日時： 2020-08-16 19:23:00 +0900 URL： https://twitter.com/sanngatuusagino/status/1294942760680611840

> 「忘れられた戦後補償」観てる。
>
> 「国民」を利用するだけ利用して、使い捨てする国家。今も変わらない。

　深澤諭史弁護士の事務局に戻ります。

 - （62／79） TW fukazawas（深澤諭史） 日時：2018-06-29 13:14:00 +0900 URL： https://twitter.com/fukazawas/status/1012549784660348929

> 二弁の事務局に，えらい迷惑かけてしまった。
> 申し訳ない（Ｔ∀Ｔ）

 - （64／79） TW fukazawas（深澤諭史） 日時：2018-11-15 17:21:00 +0900 URL： https://twitter.com/fukazawas/status/1062983883724009473

> （・∀・）あ，肌色のイラストがＴＬに・・・。もう１７時過ぎたのか。
> （；＾ω＾）事務局に残業させちゃだめだお。

 - （65／79） TW fukazawas（深澤諭史） 日時：2018-11-24 08:25:00 +0900 URL： https://twitter.com/fukazawas/status/1066110562570952704

> 別に私は休日夜間働くことに抵抗はないのだけれども、事務局を休日出勤、夜間残業させるわけにはいかないので、それで、休日夜間の相談は対応が難しい。
> （・∀・）

 - （66／79） TW fukazawas（深澤諭史） 日時：2018-12-02 10:12:00 +0900 URL： https://twitter.com/fukazawas/status/1069036593573355520

> 同事務所のほか弁護士や、事務局にまで嫌がらせしてきたりとかもありましたね。
> 今後は厳正対処したほうがいいかなぁ。
> （・∀・；） https://t.co/jHlyC4TQS7

 - （68／79） TW fukazawas（深澤諭史） 日時：2018-12-25 11:23:00 +0900 URL： https://twitter.com/fukazawas/status/1077389325875130368

> https://t.co/gXR5a6m5XE
> ほんこれ。
> こっちは予定入れると、他の予定入れられないし、事務局まで休日出勤させる必要も出てくることがわかっていない。
> （・∀・）

 - （69／79） TW fukazawas（深澤諭史） 日時：2019-01-16 13:28:00 +0900 URL： https://twitter.com/fukazawas/status/1085393258077999106

> @take___five なお、いきなり音声入力を始めると、事務局に「ついにうちの先生、成仏する前におかしくなっちゃったか・・・。帰りに弁護士会に相談に行こう。」となりますので、お気をつけを。
> （・∀・）

 - （71／79） TW fukazawas（深澤諭史） 日時：2019-11-11 12:40:00 +0900 URL： https://twitter.com/fukazawas/status/1193735205976035329

> 散々放置した挙句、切羽詰まっているだけというケースも多い。
> すぐに電話しないと逆ギレしたり、事務局に粗暴な言葉を投げかけるので、正直、関わりたくない類型です（・∀・；） https://t.co/YbNi95WgOq

 - （72／79） TW fukazawas（深澤諭史） 日時：2019-12-11 12:42:00 +0900 URL： https://twitter.com/fukazawas/status/1204607267384918017

> 事務所側で事務局を連れてランチ！
> 非常にリーズナブル、良心的な価格で、しかもハイクオリティ！
> （・∀・）（＾ω＾） https://t.co/B0rUX3iPhx

 - （73／79） TW fukazawas（深澤諭史） 日時：2019-12-24 15:12:00 +0900 URL： https://twitter.com/fukazawas/status/1209356040229097472

> 飲食店で店員に横柄な態度とる人は、本当に地雷な人が多いから、要注意。
> 同じく、法律事務所で事務局に横柄な人も。
> 後者については、弁護士はものすごく怒ることが多い。
> （・∀・）

 - （77／79） TW fukazawas（深澤諭史） 日時：2020-06-21 17:16:00 +0900 URL： https://twitter.com/fukazawas/status/1274617256719208448

> （・∀・）法律事務所に電話するとき、事務局にタメ口な人も大嫌いである。 https://t.co/Ih1vhUDdiF

- （78／79） TW fukazawas（深澤諭史） 日時：2020-07-12 10:18:00 +0900 URL： https://twitter.com/fukazawas/status/1282122250007670784

> 日弁連の会務のとき，日弁連事務局に，やたら大柄な態度で接して人がいたことを思い出した。
> （・∀・；） https://t.co/e1GKz26yoT

 - （79／79） TW fukazawas（深澤諭史） 日時：2020-08-06 11:21:00 +0900 URL： https://twitter.com/fukazawas/status/1291197762847952897

> たぶん，ほぼ全ての弁護士が同意するであろうことは，「事務局への態度が横柄な人」は，絶対に受任してはならない，相談も極力回避するべき，という点ですね。
> （・∀・；） https://t.co/MAYYNyHgXD

　今の時代，電話で唐突に横柄な態度をとる人というのは多くない気がします。弁護士の対応に対する不満が窓口である事務員に向けられているような気もしてきたのですが，相手の立場を含め，それを一切，気にすることのないのが深澤諭史弁護士のツイートに共通した特徴とも思われます。

　昨夜の20時ぐらいの時点で用意は出来ていたのですが，そのあと夕食と片付け，そのあとに銭湯とバタバタと時間が過ぎていました。これまでに同じことを何度かやっていると思うのですが，毎回，探し出すのにけっこう手間が掛かってしまいます。脳機能障害の少女のことです。

〈〈〈：Linux Emacs： 2020-08-18（火曜日）13：19 　〈〈〈

* 深澤諭史弁護士の2015年7月22日のツイートで深く考えさせられてきた懲役11年の脳機能障害少女一家の弁護士横領・詐欺事件，他に岡山の懲役14年，福岡でも懲役14年の事件
  :LOGBOOK:
  CLOCK: [2020-08-18 火 13:20]--[2020-08-18 火 19:03] =>  5:43
  :END:

:CATEGORIES: 深澤諭史弁護士

〉〉〉：Emacs： 2020-08-18（火曜日）13：20　 〉〉〉

　ふとした思いつきですが，今回，見出しタイトル後回しで記述を始めたいと思います。いろいろと組み合わせで関係性が伝わるように，という方向性で進めます。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-18 13:26／2015/07/22 19:12 URL： https://twitter.com/kk_hirono/status/1295577775194030080 https://twitter.com/hirono_hideki/status/623797702887895040  

> 脳機能障害を負った少女の一家から着服 「示談不成立」とウソ - ライブドアニュース http://t.co/GixhNUe2aN  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-18 13:26／2015/07/22 19:32 URL： https://twitter.com/kk_hirono/status/1295577798896058370 https://twitter.com/hirono_hideki/status/623802831691190272  

> ブログ更新： さっきのと同一人物ですか……。開いた口が塞がらないよ……。 脳機能障害を負った少女の一家から着服 「示談不成立」とウソ #ldnews http://t.co/mKQvyPNi1T／（深澤諭史弁護士のリツイート） http://t.co/RKB7JTh8R2  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-18 13:26／2016/05/18 09:28 URL： https://twitter.com/kk_hirono/status/1295577906719014913 https://twitter.com/hirono_hideki/status/732729413842964480  

> 脳機能障害を負った少女の一家から示談不成立と5千万円以上着服した弁護士のニュースに対する、深澤諭史弁護士の司法制度改革批判... https://t.co/H6RMnsnG1M  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-18 13:27／2016/05/28 19:20 URL： https://twitter.com/kk_hirono/status/1295577940785115142 https://twitter.com/hirono_hideki/status/736502510299451393  

> 引用：脳機能障害を負った少女の一家から着服 「示談不成立」とウソ - ライブドアニュース　（提供社の都合により、削除されました。） https://t.co/FTpNCeZhOs  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-18 13:27／2016/11/06 08:02 URL： https://twitter.com/kk_hirono/status/1295577978106073089 https://twitter.com/hirono_hideki/status/795038538161070081  

> 奉納＼弁護士妖怪大泥棒神社・金沢地方検察庁御中: 脳機能障害少女家族の弁護士被害に対する、深澤諭史弁護士の反応の記録 - Google フォト  https://t.co/xDj51EEl7m  

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「脳機能障害」の検索結果 - Twilog https://t.co/JL79wQXG0U

奉納＼弁護士妖怪大泥棒神社・金沢地方検察庁御中: 脳機能障害少女家族の弁護士被害に対する、深澤諭史弁護士の反応の記録 - Google フォト https://t.co/al7NHYTStM

　今は投稿をしていないBloggerのブログで，2016年11月6日日曜日の記事として記録されています。事実上の放置状態なのでブログが削除される可能性もないとは限らないと考えていたところ，画像のリンクはTwitterのようで，安心しました。以下に引用していきます。

［1／18］ ツイートID：795028678237298688
投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-11-06 07:23 ツイート： https://twitter.com/s_hirono/status/795028678237298688
2015-07-22-192154_自由競争とか，市場原理とか，無邪気にいっている先生，特に佐藤幸治先生とかには，百回くらい読んで頂きたい記事ですね。.jpg https://t.co/L0jDLxasQ0

［2／18］ ツイートID：795028695270363136
投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-11-06 07:23 ツイート： https://twitter.com/s_hirono/status/795028695270363136
2015-07-22-192255_深澤諭史@fukazawas＞ＲＴ自由競争とか，市場原理とか，無邪気にいっている先生，特に佐藤幸治先生とかには，百回くらい読んで頂きたい記.jpg https://t.co/FJw6NCsrQh

［3／18］ ツイートID：795028712295047168
投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-11-06 07:23 ツイート： https://twitter.com/s_hirono/status/795028712295047168
2015-07-22-193820_横領・詐欺、計4。9億円に　大阪地検が弁護士を追起訴：日本経済新聞　2015／7／22　2：05.jpg https://t.co/c06klh2tQ7

　日本経済新聞の記事に，横領・詐欺の被害額が4.9億円とあります。この前になると思いますが，福岡と岡山の弁護士の事件の方が被害額が大きく，岡山の方は9億円となっていたように思います。その全てをテレビのニュース，報道では見ていません。

　4.9億円というのもずいぶん大きな被害金額ですが，これは記憶にありませんでした。この日本経済新聞の記事自体が余り印象にはなかったもので，他に脳機能障害の少女という見出しの記事のことが鮮烈に印象に残っています。

　久保田昇という弁護士の名前を確認しましたが，その後，刑事裁判での判決のことなど何も見ることはなかった気がします。やってみないとわからないですが，Googleで検索をしてみます。

【衝撃事件の核心】５億円ネコババ弁護士の〝裏の顔〟　脳障害少女の家族も食い物に　はぎ取られた「弱者の味方」の仮面（1/4ページ） - 産経WEST https://t.co/sBRWZup0ZE 一連の捜査で、交通事故で脳障害を負った１０代の少女一家が受け取るはずだった示談金約５４００万円まで着服する無慈悲ぶりも

【衝撃事件の核心】５億円ネコババ弁護士の〝裏の顔〟　脳障害少女の家族も食い物に　はぎ取られた「弱者の味方」の仮面（2/4ページ） - 産経WEST https://t.co/6UuFXSMNlR 「法のプロ信用」背信 \n  \n 　こうした背信行為の中でも、特に目を引くのが交通事故で脳障害を負った少女一家の被害だった。

【衝撃事件の核心】５億円ネコババ弁護士の〝裏の顔〟　脳障害少女の家族も食い物に　はぎ取られた「弱者の味方」の仮面（2/4ページ） - 産経WEST https://t.co/6UuFXSMNlR 自転車で帰宅途中、自宅近くの交差点で出合い頭にトラックと衝突。一時は意識不明の重体となり、脳機能障害が残った。

【衝撃事件の核心】５億円ネコババ弁護士の〝裏の顔〟　脳障害少女の家族も食い物に　はぎ取られた「弱者の味方」の仮面（3/4ページ） - 産経WEST https://t.co/6scjSIv9lM 本来の示談金は約９２００万円だったが、振り込まれたのは一部に過ぎなかった。被告が着服した総額は約５４００万円に上った。

【衝撃事件の核心】５億円ネコババ弁護士の〝裏の顔〟　脳障害少女の家族も食い物に　はぎ取られた「弱者の味方」の仮面（3/4ページ） - 産経WEST https://t.co/6scjSIv9lM 障害者向けの作業所に就職した長女は、記憶力の低下や激しい感情の起伏もあり、事故以前の生活に戻ることはできない。

【衝撃事件の核心】５億円ネコババ弁護士の〝裏の顔〟　脳障害少女の家族も食い物に　はぎ取られた「弱者の味方」の仮面（3/4ページ） - 産経WEST https://t.co/6scjSIv9lM 女性の預金計約４２００万円を着服したとして、東京弁護士会の元副会長が業務上横領罪に問われ、懲役５年の実刑判決を受けた。

【衝撃事件の核心】５億円ネコババ弁護士の〝裏の顔〟　脳障害少女の家族も食い物に　はぎ取られた「弱者の味方」の仮面（4/4ページ） - 産経WEST https://t.co/8py9i5UdG2 調査を始めた２２年６月から２６年末までの４年半で、全国で少なくとも６２件、約１１億２０００万円に上った。

【衝撃事件の核心】５億円ネコババ弁護士の〝裏の顔〟　脳障害少女の家族も食い物に　はぎ取られた「弱者の味方」の仮面（4/4ページ） - 産経WEST https://t.co/8py9i5UdG2 別の会員の弁護士も裁判所の判決文や決定書を偽造していた疑いが浮上し、大阪地検が本格捜査に乗り出している。

【衝撃事件の核心】５億円ネコババ弁護士の〝裏の顔〟　脳障害少女の家族も食い物に　はぎ取られた「弱者の味方」の仮面（4/4ページ） - 産経WEST https://t.co/8py9i5UdG2 示談金を横領された少女一家は、交通事故から９年を経た今春、地検の捜査が入るまで弁護士の不正を疑ったことは一切なかった。

【衝撃事件の核心】５億円ネコババ弁護士の〝裏の顔〟　脳障害少女の家族も食い物に　はぎ取られた「弱者の味方」の仮面（4/4ページ） - 産経WEST https://t.co/8py9i5UdG2 もっとも、弁護士の不正を監視すべき立場の弁護士会でも、被告の不正情報はつかめていなかったという。

【衝撃事件の核心】５億円ネコババ弁護士の〝裏の顔〟　脳障害少女の家族も食い物に　はぎ取られた「弱者の味方」の仮面（4/4ページhttps://t.co/8py9i5UdG2 『弁護士自治』の原則があり、相当程度の不正を確認できなければ、積極的に介入することはできない」。弁護士会の関係者はこう嘆くのだが…。

　「５億円ネコババ弁護士の〝裏の顔〟　脳障害少女の家族も食い物に」という4ページに分かれた記事は，途中で読んだ内容だと思いました。確認すると2015年7月30日とあります。

　「調査を始めた２２年６月から２６年末までの４年半で、全国で少なくとも６２件、約１１億２０００万円に上った。」という部分が，前回読んだとき特に気になり，調べたような気もするのですが，その後のことは憶えていません。岡山と福岡の事件が含まれておらず，2つだけで11億は軽く超えます。

　求刑懲役13年の判決が懲役11年で，2016年3月28日とあります。これはたぶん全く知らずにいたと思います。被害金額は5億円と少なめですが，懲役11年というのは，岡山の事件と福岡の事件に共通したものであったと記憶にあります。3つということはまずなかったはずです。

　それでは次に，福岡の事件を調べてみます。前回調べたときも情報が見つかりづらく，検索に難儀したような憶えがあります。弁護士に関する情報が少ないのも特徴だったと思います。大阪の事件や岡山の事件のように，公開された弁護士の顔写真も見た憶えがありません。只調べ方では出るかもしれません。

福岡　弁護士　横領 - Google 検索 https://t.co/aUEUwchakL

高橋浩文元弁護士の詐欺横領被害者が福岡県弁護士会を提訴した1回目の裁判 – 弁護士自治を考える会 https://t.co/z1WWkAzfT3

高橋浩文元弁護士の詐欺横領被害者が福岡県弁護士会を提訴した1回目の裁判 – 弁護士自治を考える会 https://t.co/z1WWkAzfT3 「弁護士会が指導監督を怠った」という原告側の主張に対し、弁護士会側は請求棄却を求め、争う姿勢を示した。

高橋浩文元弁護士の詐欺横領被害者が福岡県弁護士会を提訴した1回目の裁判 – 弁護士自治を考える会 https://t.co/z1WWkAzfT3 計４億６９２０万円を詐取したなどとして、１２年に同地裁で懲役１４年の判決を受けて服役中。同５月には自己破産が確定した。

1億7000万円詐欺容疑で弁護士逮捕　福岡地検　　:日本経済新聞 https://t.co/mKSdWdd7qB 2012/5/10付

裁判費詐取事件：弁護士会責任なし　請求を棄却　福岡地裁 - 毎日新聞 https://t.co/KXEgnqViHD 倉沢守春裁判長は「弁護士会の指導監督が必要といえる具体的事情はなかった」として請求を棄却した

裁判費詐取事件：弁護士会責任なし　請求を棄却　福岡地裁 - 毎日新聞 https://t.co/KXEgnqViHD 倉沢裁判長は「弁護士の職務の独立性や守秘義務などがあり、弁護士会が指導監督できるのは明らかに違法な弁護活動などの場合に限られる」と指摘。

高橋浩文弁護士 - Google 検索 https://t.co/CiwnwZmyTK 画像検索

　やはりGoogleの検索で情報が見つかりにくい事件です。私の記憶では被害額は7億円ぐらいで，それも検察が立件できた分だけというようなニュースを読んだように思います。大阪の事件は5億円で，この福岡の事件は計４億６９２０万円となっていますが，懲役14年となっていました。

　岡山の弁護士の事件も同じ懲役刑だったように思います。岡山の方が被害者の数も金額も多かったと思いますが，なぜ量刑が同じなのかと気になっていました。何か作為が感じられるほど，情報が乏しく見つかりにくい福岡の弁護士の事件で，顔写真もやはり見つかりませんでした。

　求刑が懲役15年で判決が懲役14年，2012年10月11日と確認できました。被害額は約4億6千万円と少なめで計算しますが，この後調べる岡山の弁護士の事件の被害額を合わせれば，2つだけで11億円は軽く突破すると思います。

岡山　弁護士　横領 - Google 検索 https://t.co/etAgzlwz24

弁護士による約１６億２４００万円の横領／岡山 | 高松総合法律事務所 https://t.co/NAxNhiAJ7S 2013年6月8日 　カテゴリ：弁護士 \n ￼ \n 　岡山弁護士会に所属していた元弁護士が約１６億２４００万円を横領した事件に関して、その元弁護士の破産手続の債権者集会があったようです。（毎日新聞のサイト）

横領の元弁護士に懲役１４年判決　岡山地裁「強い非難に値する」（山陽新聞より） | 会計ニュース・コレクター（小石川経理研究所） https://t.co/jdXdqyexf1 民事訴訟の賠償金など９億円超を着服した岡山市の元弁護士に懲役14年の有罪判決が下されたという記事。

横領の元弁護士に懲役１４年判決　岡山地裁「強い非難に値する」（山陽新聞より） | 会計ニュース・コレクター（小石川経理研究所） https://t.co/jdXdqyexf1 中田幹人裁判長は「被害者の多くは交通事故の遺族や重度の後遺障害を負った人々。その状況を知りながら生活に不可欠な賠償金、保険金を横領し

横領の元弁護士に懲役１４年判決　岡山地裁「強い非難に値する」（山陽新聞より） | 会計ニュース・コレクター（小石川経理研究所） https://t.co/jdXdqyexf1 申告した個人や金融機関は約２００人・団体で、申告の総額は約１６億３０００万円に上るが、債権者に配当できる資産は現在で約４４００万円。

岡山弁護士巨額横領事件 - Wikipedia https://t.co/I9WHVuAwGY 被害者の多くは交通事故の遺族や重度の後遺障害を負った人々。その状況を知りながら生活に不可欠な賠償金、保険金を横領し、さらなる窮地に追い込んだ」として被告人に懲役14年（求刑懲役15年）が言い渡された

　岡山の弁護士の事件は，求刑懲役15年の判決が懲役14年，2013年8月28日の岡山地裁だと確認しました。16億円という被害額は今回初めて見たように思います。これも検察が立件できたのが9億円ということのようです。

　福岡の判決が2012年10月11日，岡山の判決が2013年8月28日ですが，4億6千万円と9億円という被害額に大きな開きがあるのに，求刑も懲役15年，判決も懲役14年と同じだったようです。この違いはなんなのかと気になるところです。

```
➜  ~ dp -p | grep 2015-07-22
 - 2017年10月09日14時17分の登録： REGEXP：”無邪気”／深澤諭史弁護士（@fukazawas）のツイートの記録（2015-07-22〜2017-02-20／2017年10月09日14時17分・8件） http://hirono2014sk.blogspot.com/2017/10/regexpfukazawas2015-07-222017-02.html
 - 2017年10月09日15時22分の登録： ％@s_hirono　非常上告-最高検察庁御中_ツイッター％2015-07-22-192255_深澤諭史@fukazawas＞ＲＴ自由競争とか，市場原理とか，無邪気にいっている先生，特に佐藤幸治先生とか http://hirono2014sk.blogspot.com/2017/10/shirono-2015-07-22-192255fukazawas.html
 - 2017年10月09日15時24分の登録： ％@s_hirono　非常上告-最高検察庁御中_ツイッター％2015-07-22-192154_自由競争とか，市場原理とか，無邪気にいっている先生，特に佐藤幸治先生 http://hirono2014sk.blogspot.com/2017/10/shirono-2015-07-22-192154.html
 - 2018年05月22日07時16分の登録： TWEET：”2015-07-22 10:39〜2015-07-22 23:19”／深澤諭史（@fukazawas）の検索（2018年05月22日07時16分の記録15件） http://hirono2014sk.blogspot.com/2018/05/tweet2015-07-22-10392015-07-22.html
 - 2019年06月21日14時27分の登録： TWEET：”2015-07-22 10:39〜2015-07-22 23:19”／深澤諭史（@fukazawas）の検索（2019年06月21日14時26分の記録23件） http://hirono2014sk.blogspot.com/2019/06/tweet2015-07-22-10392015-07-22.html
 - 2020年07月01日00時51分の登録： TWEET：”2015-07-22 19:09〜2015-07-22 19:21”／データベース登録済みツイート2020年07月01日00時51分の記録：ユーザ・投稿：1／2件） http://hirono2014sk.blogspot.com/2020/07/tweet2015-07-22-19092015-07-22.html
 - 2020年07月01日00時51分の登録： TWEET：”2015-07-22 10:39〜2015-07-22 23:19”／深澤諭史（@fukazawas）の検索（2020年07月01日00時51分の記録27件） http://hirono2014sk.blogspot.com/2020/07/tweet2015-07-22-10392015-07-22.html
 - 2020年08月18日10時10分の登録： REGEXP：”ウソ”／深澤諭史（@fukazawas）の検索（2015-07-22〜2020-08-16／2020年08月18日10時10分の記録120件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2015-07-222020-08.html
```

　「TWEET：”2015-07-22 10:39〜2015-07-22 23:19”／深澤諭史（@fukazawas）」というまとめ記事の中に，求めるツイートがあったように思います。

 - （02／27） TW fukazawas（深澤諭史） 日時：2015-07-22 11:53:00 +0900 URL： https://twitter.com/fukazawas/status/623687293891575808

> 国選弁護報酬の問題は，報酬が低いことだけではなくて，全力で手抜きを応援する一方，被疑者被告人のために頑張る弁護人の足を全力で引っ張る報酬体系であること。
>
> 自由競争，市場原理の原則には反するかも知れないが，それでも，国選をしている皆さんは全力を尽くしていると思います・・。

　深澤諭史弁護士の基本書のような内容のツイートです。自由競争，市場原理を司法制度改革が悪の根源のように位置づけ，これは当時の小倉秀夫弁護士のツイートのもよく見られたことです。

 - （03／27） TW fukazawas（深澤諭史） 日時：2015-07-22 12:06:00 +0900 URL： https://twitter.com/fukazawas/status/623690676648083456

> 法科大学院の大先生が
> 「法曹養成改革の理念が実現したら，お金のない人や勤め人でも，地方出身者も，多種多様で優秀な人が法曹になる世の中が来る！」
> と言った。
>
> それを聞いて１人の老弁護士が言った。
> 「なるほど。やっとわしが受験生だった頃に戻れるんじゃな！」
>
> #司法改革ジョーク

 - （14／27） TW fukazawas（深澤諭史） 日時：2015-07-22 18:32:00 +0900 URL： https://twitter.com/fukazawas/status/623787729877274625

> @Jakotsunya
> まさに，弁護士会でも，その点が問題にされていますね。
> 真面目にやっている弁護士が，集客で，不誠実な弁護士や事件屋に勝てない，仕事を取られている，と。
> (･∀･；)

　次の深澤諭史弁護士のリツイートです。この直後のツイートで，深澤諭史弁護士は，当時よく使っていた「＞RT」というような記号で，直前のリツイートに対する言及だということを示していることがうかがわれます。

 - （15／27） RT fukazawas（深澤諭史）｜yukihirosasamo（ささもたん@赤腹魔王） 日時：2015-07-22 18:48:00 +0900／2015-07-22 18:46:00 +0900 URL： https://twitter.com/fukazawas/status/623791767637225472 https://twitter.com/yukihirosasamo/status/623791245568012288

> さっきのと同一人物ですか……。開いた口が塞がらないよ……。
> 脳機能障害を負った少女の一家から着服 「示談不成立」とウソ #ldnews http://t.co/BW3bqtjmAW target="_blank">http://t.co/BW3bqtjmAW

 - （16／27） TW fukazawas（深澤諭史） 日時：2015-07-22 18:49:00 +0900 URL： https://twitter.com/fukazawas/status/623791961539919873

> ＞ＲＴ
> 自由競争とか，市場原理とか，無邪気にいっている先生，特に佐藤幸治先生とかには，百回くらい読んで頂きたい記事ですね。
> (＃･∀･)

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2015/07/22 18:49 URL： https://twitter.com/fukazawas/status/623791961539919873  

> ＞ＲＴ  
> 自由競争とか，市場原理とか，無邪気にいっている先生，特に佐藤幸治先生とかには，百回くらい読んで頂きたい記事ですね。  
> (＃･∀･)  

　これは深澤諭史弁護士という弁護士の価値観，生き様のすべてが魂のごとく込められたツイートだと思います。脳機能障害の少女の一家の悲劇も，司法制度改革による不満をぶつける理由付けにしかなっていません。ここに深澤諭史弁護士の弁護士としての成功の秘訣があるのかもしれないですが。

　この深澤諭史弁護士のツイートは2015年7月22日，知るのか知らないのかわかりませんが，福岡と岡山で懲役14年という詐欺や横領の事件が起きているわけで，失われた弁護士に対する信頼が，弁護士の需要を減らしていたとも考えられるところではあります。他にも色々あったと思います。

　もともと弁護士の増員というのは，一部の弁護士が暴対法で勢力が弱まった暴力団に取って代わり，しのぎを拡大させるべく舵取りをしたような話を見かけたこともありました。最近はすっかり名前も見かけなくなった久保利英明弁護士のことです。

```
――自分の稼ぎを増やすために「事件を作る」ような弁護士が現れるという声もあります。

弁護士が増えれば見解を比較することも可能になる。法律問題かどうかすら知る機会が得られないよりは、遙かにマシだ。今の人数では、そもそも弁護士にたどり着くこと自体が難しい。

――弁護士の適正人口はどのくらいだとお考えでしょうか。

国民にとっては多ければ多いほどいい。多くて困る国民はいないはず。裁判官や検察官の数は国家予算の関係で増やせないというのなら、弁護士から先に 増やせば悪徳業者に泣かされている人が訴訟を起こせる機会が増えるし、訴訟件数が増えれば、裁判官や検察官も増やさざるを得なくなる。

［source：］弁護士のニーズは｢供給｣によって増大する | 続・弁護士という民族 | 東洋経済オンライン | 経済ニュースの新基準 https://toyokeizai.net/articles/-/72088?page=2
```

　コピペをしてから，ずっと前に見覚えのある「続・弁護士という民族 | 東洋経済オンライン」の記事だとわかりました。たまに記事の日付をみないまま終わることもあるのですが，ここで気がついて確認すると，2015年6月9日となっています。

```
7割合格」の時代が来れば、希望を見出せる
――弁護士を増やすと競争が起き、競争に敗れた弁護士が窮乏化して悪事を働く、結果被害を受けるのは国民だという説もありますが。

懲戒処分を受ける弁護士は主に、競争に敗れた高齢者層だ。そういう弁護士こそ淘汰されなければいけない。どんなに窮乏しようが、悪事を働かないのがプロのプロたるゆえんだ。

――そこで司法試験合格者数を3000人にせよという運動を展開されていると。

弁護士は増やすべきなのに、その予備軍である法科大学院の志望者数は年々減っている。入学者数は2300人弱しかいない。私が司法 試験を受験した頃は合格者500人のところ大体2～3万人の受験者がいた。

司法試験の合格者数を減らせと言っている人たちは、多額の授業料で負債を背負っ ても合格出来るかどうかわからないだの、合格しても就職先がないだの、食えずに困窮するだの言って、弁護士全体のイメージを下げている。そんな希望のない 職業を目指す人が減るのは当然。

［source：］弁護士のニーズは｢供給｣によって増大する | 続・弁護士という民族 | 東洋経済オンライン | 経済ニュースの新基準 https://toyokeizai.net/articles/-/72088?page=2
```

　この久保利英明弁護士も深澤諭史弁護士が理想とした時代の弁護士なのかもしれません。他によく似た弁護士で河合というような弁護士がいました。テレビで，裁判所に熊本の阿蘇山が大爆発をし，愛媛の原発に大きな被害をもたらす可能性を認めさせ，派手な色の服を来ている姿をみました。

山口組分裂についての質疑応答の全文 - ログミーBiz https://t.co/TWvl8sdWzw 「ヤクザの仕事は弁護士に取られた」山口組分裂について専門家が質疑応答 \n 【山口組分裂について】溝口敦氏＆久保利英明弁護士 記者会見 #2/2

　ヤクザや総会屋と対立をしてきたという久保利英明弁護士ですが，世渡り上手で危険な橋を渡るタイプとも思えないところがあります。私が最初に久保利英明弁護士に注目したのは，たまたまテレビで見た，すき家の第三者委員会の会見でした。

久保利 英明弁護士｜すき屋第三者委員会委員長 | Hashigozakura https://t.co/rueoesVf2j

　上記のページには，久保利英明弁護士らの記者会見の様子，NHKと画面左下にみえるテレビの映像の写真がありますが，2014年7月31日の記事となっています。2012年ぐらいのことかと思っていたので，2014年というのはけっこう意外に感じました。

　このあとにテレビで見たのが「まむしの善三」という元検察幹部の弁護士でしたが，ずいぶん不信と不興を買った様子でした。久保利英明弁護士のすき家の会見も，この弁護士らのお墨付きをもらうより，巨額と想像される弁護士費用を，そのまま従業員に還元させれば，感謝もされそうと思っていました。

　テレビのデジタル化で，顔の毛穴まで人に見られてしまう，という不安がテレビで紹介される時代がありましたが，情報のデジタル化が進み物事の見通しがよくなるほどに，弁護士の問題性というのもくっきり浮き出るようになり，それが様々な方面で，影響を及ぼすようになってきたと思います。

　弁護士が目を向けようとしない社会の断片というのも，光と影のコントラストのように浮かび出るものを感じます。深澤諭史弁護士は，本が在庫切れとか，部門の売上げランキングで2位になったと今日もツイートをしていましたが，それだけ反響があるのに，リツイートの数が極端に少ないことが多いです。

　昔は，私も本の著者の名前を見ても，その人物の人なりなど想像を及ぼすことなく本を買ったものですが，やはり売れる本には条件もあって，深澤諭史弁護士の本には売れるだけの理由があるというのも事実なのだと思います。読みやすくて面白いのかもしれません。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜lyiase（Lyiase） 日時：2020-08-18 16:14／2020/08/18 10:51 URL： https://twitter.com/kk_hirono/status/1295620016902086661 https://twitter.com/lyiase/status/1295538745458823171  

> この事実をちゃんとアメリカ軍が記録していて、我が国が記録していないこと自体が、我が国が負けた最大の原因を物語って居るような気がする。 https://t.co/fUp6tUCSbx  

　今，深澤諭史弁護士のタイムラインで，深澤諭史弁護士のリツイートとして見かけたツイートをリツイートしましたが，そこに引用リツイートされているNHKニュースのツイートの動画ニュースの映像と内容が衝撃的です。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜nhk_news（NHKニュース） 日時：2020-08-18 16:17／2020/08/17 22:00 URL： https://twitter.com/kk_hirono/status/1295620763202936833 https://twitter.com/nhk_news/status/1295344723880747008  

> もし突然命を奪われ、その事実が語り継がれることなく誰が犠牲になったのかわからなかったら。75年前、福岡県で満員電車がアメリカ軍に銃撃されました。しかし多くの犠牲者の名前は今もわかっていません。犠牲者の「生きた証」を取り戻す、地元の市職員が調査を続けています。https://t.co/Kgdl0EaWI8 https://t.co/RKnjNexBnn  

- TW a_ranking_news（書籍ランキング速報） 日時： 2020/08/16 19:12 URL： https://twitter.com/a_ranking_news/status/1294939963465691136  

> (8/16) honto 本の通販ストアランキング &gt; 法学・法律 &gt; 司法・裁判・訴訟法ランキング2位:深澤 諭史 （著）『まんが弁護士が教えるウソを見抜く方法』  
> https://t.co/CqSbGxblbA  

- TW fukazawas（深澤諭史） 日時： 2020/08/18 10:06 URL： https://twitter.com/fukazawas/status/1295527563880566784  

> インターネット権利侵害 削除請求・発信者情報開示請求“後"の法的対応Q&amp;A  
> https://t.co/URf4Gzf8Ax  
> ひょっとして，完全に通常の在庫がなくなってしまったのか・・・。  
> 結構印刷したのに・・・。  
> 定価オーバーで出品されているし・・。  
> なお，楽天ブックスには，まだ在庫がある模様・・。  

　時刻は16時32分です。本当は安藤健次郎さんや被害者安藤文さんのこととも絡めて，関連性を示したかったのですが，深澤諭史弁護士だけでお腹いっぱいになりました。また，深澤諭史弁護士のことで時間と労力を費やしました。深澤諭史弁護士疲れです。

　しかし，大阪の脳機能障害の少女一家を食い物にした弁護士の事件で懲役11年の判決が出ていたことを知ったというのも収穫ですし，その大阪の裁判が懲役11年で，少し被害金額が少ない福岡の弁護士の事件の方が懲役14年だったというのも，本当に謎です。

　最初に懲役11年という判決を見たとき，脳機能障害の少女一家の無念を裁判所が反映させたのかと思ったのですが，数年前に出ていた同種事案の福岡の弁護士の懲役14年より，3年も軽くしていたことになり，求刑自体も懲役12年というものでした。3つに共通したのは求刑より1年の減刑です。

　深澤諭史弁護士のタイムラインでリツイートを見かけた次のツイートにリンクがある日本経済新聞の記事も気になっているところです。有料記事が「弁護士で最高経営責任者（CEO）の南谷」という部分で途切れ，昔やったことのある冒険物のテレビゲームのことを思い出しました。

　記事の有料化は時代の流れとしてしかたがないのかもしれず，昔は無料が当たり前で，社会が回っていたことの方が，どうして出来たのかと思うところがあります。広告収入と聞くことはありましたが，そういえば最近は以前ほど広告を見かけていないように思います。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜atehosho_atela（「アテラ」事務局） 日時：2020-08-18 16:45／2020/08/18 12:17 URL： https://twitter.com/kk_hirono/status/1295627861093572608 https://twitter.com/atehosho_atela/status/1295560413631807488  

> 日本経済新聞のGame Changerに取り上げて頂きました！！！ 法を身近に、泣き寝入りなくす　弁護士費用を立て替え: 日本経済新聞 https://t.co/8EiyLueYQA  #ATE保証 #アテラ #日本リーガルネットワーク  

　ちょうど昨日の今頃の時間，夕方の早い時間だったように思いますが，ギャラクシーの英単語を調べていました。「日本経済新聞のGame Changer」という部分ですが，よく見ると日本経済新聞のもののようです。先程は弁護士費用の建て替えサービスの名前にゲームがあるのかと勘違いしました。

　Googleの翻訳を使うと，ゲームチェンジャーとカタカナが出てきました。ゲームについて調べると，「勝負事，遊び」とありました。

　深澤諭史弁護士のTwitterタイムラインというのも思えば，ゲームの世界のようです。最近は時間を無駄にしてしまったと思いながら，弁護士パラダイスの欲望と妄執の世界に，囚われているような感覚にもあります。しかし，一方で，弁護士鉄道の歴史を記録に出来たという達成感もあります。

〈〈〈：Linux Emacs： 2020-08-18（火曜日）16：58 　〈〈〈

* 深澤諭史弁護士がツイートで「法を身近に、泣き寝入りなくす　弁護士費用を立て替え: 日本経済新聞」という記事，調べるとアテラと南谷泰史弁護士，金沢弁護士会に挨拶代わりのツイート
  :LOGBOOK:
  CLOCK: [2020-08-18 火 19:03]
  :END:

:CATEGORIES: 深澤諭史弁護士

〉〉〉：Emacs： 2020-08-18（火曜日）19：03　 〉〉〉

　時刻は19時04分です。テレビをつけたところですが，たぶん昨日は24時間一度もつけず，今日も初めてつけました。家にいてテレビをつけなかった時間では過去最高記録になりそうですが，記録を狙ったことではありません。いろいろと集中したいことがあって，自然とそうなりました。

```
 - 803：2020-08-18_13:19:43 ＊ 深澤諭史弁護士の「発信者情報開示に係る意見照会書が届いた方へ（まとめと解説）」に非常によくまとめられていた，弁護士に対する疑問と不信感 https://hirono-hideki.hatenadiary.jp/entry/2020/08/18/131938
 - 804：2020-08-18_17:06:54 ＊ 深澤諭史弁護士の2015年7月22日のツイートで深く考えさせられてきた懲役11年の脳機能障害少女一家の弁護士横領・詐欺事件，他に岡山の懲役14年，福岡でも懲役14年の事件 https://hirono-hideki.hatenadiary.jp/entry/2020/08/18/170650
```

　本日作成した2つのエントリーですが，自分としては弁護士鉄道の歴史の記録として，けっこう大仕事をしたつもりでいます。すぐにでもWindows10に移って，一太郎で告発状の作成を再開したいところだったのですが，迷いながら取り上げることに決めたのがこのエントリーです。

　深澤諭史弁護士のタイムラインでは，深澤諭史弁護士本人のツイートを1件，リツイートを1件確認していますが，どちらも同じ標題に関連したツイートになります。

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2020/08/18 13:29 URL： https://twitter.com/fukazawas/status/1295578501882343424  

> 法を身近に、泣き寝入りなくす　弁護士費用を立て替え: 日本経済新聞 https://t.co/D6E92zq67h  

- TW atehosho_atela（「アテラ」事務局） 日時： 2020/08/18 12:17 URL： https://twitter.com/atehosho_atela/status/1295560413631807488  

> 日本経済新聞のGame Changerに取り上げて頂きました！！！  
> 法を身近に、泣き寝入りなくす　弁護士費用を立て替え: 日本経済新聞 https://t.co/8EiyLueYQA   
> #ATE保証 #アテラ #日本リーガルネットワーク  

```
2020年8月18日 11：00 ［有料会員限定記事］

全て表示
インターネット上で誹謗（ひぼう）中傷され、損害賠償を求めたい。元請け業者が難癖をつけて建築工事の代金を支払ってくれない――。日本リーガルネットワーク（東京・中央）にこうした相談が続々と寄せられている。単なる法律の相談ではない。弁護士に支払う着手金などを立て替えてもらえないかという内容だ。

「泣き寝入りする人をなくし、アンフェア（不公正）の解消につなげたい」。弁護士で最高経営責任者（CEO）の南谷

［source：］法を身近に、泣き寝入りなくす　弁護士費用を立て替え： 日本経済新聞 https://r.nikkei.com/article/DGXMZO62585750T10C20A8TL3000?disablepcview=&s=4
```

　有料記事で，公開部分が弁護士の上の名前の南谷で途切れたのも，機械的処理の結果なのかとも考えながら気になったところで，この依頼者にとってはいいとこ尽くしのような法律サービスについて，調べてみました。

　経営のことは経験もなくさっぱりわからないので，なおさら気になって調べたという動機もあります。まるで国や行政の財源や支援がなければ成り立たないようなサービスに思えたのですが，勝訴の見込みがそれだけ高い依頼を選別しているのかなど，色々と思いを巡らしました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-18 19:22／2020/08/18 13:19 URL： https://twitter.com/kk_hirono/status/1295667290348720129 https://twitter.com/hirono_hideki/status/1295576115537276929  

> - 803：2020-08-18_13:19:43 ＊ 深澤諭史弁護士の「発信者情報開示に係る意見照会書が届いた方へ（まとめと解説）」に非常によくまとめられていた，弁護士に対する疑問と不信感 https://t.co/E1txsijBu7  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜livedoornews（ライブドアニュース） 日時：2020-08-18 19:22／2020/08/18 12:40 URL： https://twitter.com/kk_hirono/status/1295667304110239745 https://twitter.com/livedoornews/status/1295566210692558848  

> 1000RT：【家出】道路を歩いていたペンギン、パトロール中の警察官が保護 英 https://t.co/kY7tsYGub8  飼われている農場を逃げ出して約1.6kmの距離をヨチヨチと歩いてきたとみられ、無事に飼い主の元へと返されたという。 https://t.co/ej2m1Lmfgy  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-18 19:22／2020/08/18 17:07 URL： https://twitter.com/kk_hirono/status/1295667343041781763 https://twitter.com/hirono_hideki/status/1295633285981208576  

> - 804：2020-08-18_17:06:54 ＊ 深澤諭史弁護士の2015年7月22日のツイートで深く考えさせられてきた懲役11年の脳機能障害少女一家の弁護士横領・詐欺事件，他に岡山の懲役14年，福岡でも懲役14年の事件 https://t.co/vcS6GWhKfH  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-18 19:22／2020/08/18 17:56 URL： https://twitter.com/kk_hirono/status/1295667358887944195 https://twitter.com/hirono_hideki/status/1295645670569701376  

> 袴田事件を再審無罪へ。最高裁に立ち向かう、弁護団に応援を。（袴田さん支援クラブ（代表：猪野待子） 2020/08/18 公開） - クラウドファンディング READYFOR (レディーフォー) https://t.co/tPJw5XpvUA  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-18 19:22／2020/08/18 18:04 URL： https://twitter.com/kk_hirono/status/1295667387857920000 https://twitter.com/hirono_hideki/status/1295647801217445888  

> 冤罪事件弁護の泰斗、西嶋勝彦 | 袴田さん支援クラブ https://t.co/8Tsob4mszU  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-18 19:22／2020/08/18 18:46 URL： https://twitter.com/kk_hirono/status/1295667396020035584 https://twitter.com/hirono_hideki/status/1295658238671646720  

> 南谷泰史 | 鎧橋総合法律事務所 https://t.co/4G8OsDHsOB  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ishikawa_tvnews（【石川テレビ】石川さんLive News it! 💙） 日時：2020-08-18 19:22／2020/08/18 00:04 URL： https://twitter.com/kk_hirono/status/1295667426407747584 https://twitter.com/ishikawa_tvnews/status/1295375907092234244  

> 本日感染が確認された20代女性警察官について県警本部が詳細を明らかにしました。 ・白山警察署 留置管理課の護送業務 ・同じ課の警察官等が自宅待機に ・他の署から応援要請などはせず、署内で勤務を調整 ・留置者に体調不良者は現時点でなし ・消毒作業済 とのことです。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜nhk_news（NHKニュース） 日時：2020-08-18 19:22／2020/08/18 11:29 URL： https://twitter.com/kk_hirono/status/1295667438567096320 https://twitter.com/nhk_news/status/1295548458494046209  

> もし突然命を奪われ、その事実が語り継がれることなく誰が犠牲になったのかわからなかったら。75年前、福岡県で満員電車がアメリカ軍に銃撃されました。しかし多くの犠牲者の名前は今もわかっていません。犠牲者の「生きた証」を取り戻す、地元の市職員が調査を続けています。https://t.co/Kgdl0EaWI8 https://t.co/72j2CpJsUU  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-08-18 19:22／2020/08/18 18:48 URL： https://twitter.com/kk_hirono/status/1295667453825961984 https://twitter.com/hirono_hideki/status/1295658835273609216  

> 弁護士　南谷 泰史【開拓者たち】 | Attorney's MAGAZINE Online https://t.co/p6aBksvP1h  

　一仕事終えた感で開いた深澤諭史弁護士のタイムラインでは，イギリスでペンギンが保護されたというニュースのツイートが最初に目に入りました。

　南谷泰史弁護士ですが，調べながら情報を見ていくと，以前に読んだことがあるように思われる記事もありました。しかし，一方で，Twitter検索などのまとめ記事を作成したところ，アテラをキーワードにしたものを含め，異様に思えるほど結果の少ないものでした。

　事実上，深澤諭史弁護士のご紹介で知ったようなものですが，弁護士の新規事業の開拓としてこの先どうなっていくのかも気になるところです。弁護士としては報酬をもらえないリスクも高く，冷静な判断や対処が出来るものなのかという試金石もありそうな感じで，新規開拓分野という感じです。

　勘違いをした依頼者も出てきてトラブルのリスクも高まりそうなので，そのリスクを排除するという趣旨の深澤諭史弁護士のツイートとも齟齬があるように感じました。どこかに本音と建前が入り混じっているのかもしれません。

```
 - 2020年08月18日11時00分の登録： REGEXP：”クレーマー”／深澤諭史（@fukazawas）の検索（2015-02-04〜2020-08-17／2020年08月18日10時59分の記録75件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2015-02-042020-08.html
 - 2020年08月18日11時00分の登録： REGEXP：”ストーカー”／深澤諭史（@fukazawas）の検索（2015-05-18〜2020-08-05／2020年08月18日11時00分の記録229件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2015-05-182020-08_18.html
 - 2020年08月18日11時00分の登録： REGEXP：”本人訴訟”／深澤諭史（@fukazawas）の検索（2012-12-22〜2020-08-17／2020年08月18日11時00分の記録371件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2012-12-222020-08.html
 - 2020年08月18日11時15分の登録： REGEXP：”逆恨み”／深澤諭史（@fukazawas）の検索（2014-09-22〜2020-08-08／2020年08月18日11時15分の記録56件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2014-09-222020-08_18.html
 - 2020年08月18日12時28分の登録： REGEXP：”戦後補償”／データベース登録済みツイート：2020年08月18日12時27分の記録：ユーザ・投稿：21／29件 http://hirono2014sk.blogspot.com/2020/08/regexp2020081812272129.html
 - 2020年08月18日12時33分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼四大の若手ってけっこう、その辺の町弁よりずっと人権活動やってたりするよね。「あなたの体と家族のほうが大事では？」って思ったりもする http://hirono2014sk.blogspot.com/2020/08/ksawmen_18.html
 - 2020年08月18日12時54分の登録： ＼佐藤倫子　@sato__michiko＼法律家は人さまの事件を扱う仕事です。人さまの事件だから冷静でいられます。どんな人でも当事者になると冷静な判断ができないと分かって http://hirono2014sk.blogspot.com/2020/08/satomichiko.html
 - 2020年08月18日18時44分の登録： REGEXP：”アテラ”／データベース登録済みツイート：2020年08月18日18時44分の記録：ユーザ・投稿：2／5件 http://hirono2014sk.blogspot.com/2020/08/regexp20200818184425.html
 - 2020年08月18日18時53分の登録： REGEXP：”南谷．＊泰史”／データベース登録済みツイート：2020年08月18日18時53分の記録：ユーザ・投稿：2／3件 http://hirono2014sk.blogspot.com/2020/08/regexp20200818185323.html
 - 2020年08月18日18時56分の登録： ＼深澤諭史　@fukazawas＼本当に及川先生、いろいろ活動なさっているなぁ・・・。 思想は異なる（選挙の時は対立候補を応援しました。）けれども、あの熱意と選挙前後の会 http://hirono2014sk.blogspot.com/2020/08/fukazawas_97.html
 - 2020年08月18日18時57分の登録： ＼深澤諭史　@fukazawas＼提訴には時間かかるので、通知とほぼ同時に提訴をするという迅速進行。 手間はかかるけれどもなぁ・・・。 http://hirono2014sk.blogspot.com/2020/08/fukazawas_77.html```

　著書の売れ行きも上々で，絶好調のぶっ飛ばし感も強い深澤諭史弁護士が，「法を身近に、泣き寝入りなくす　弁護士費用を立て替え: 日本経済新聞」という慈善事業を紹介したかに見えたのも，非常に気になるところです。まあ，普段より無料法律相談もちらつかせはあります。

　「アテラ」という情報誌のタイトルのような言葉も気になっています。何か似たようなタイトルの情報誌があったと思うのですが思い出せず，テラの部分は，お寺や法テラスを想起させるところがあります。なにより，笑顔が弾ける南谷泰史弁護士のサムネイルの写真が，自身と余裕を感じさせます。

```
「アテラ」事務局
@atehosho_atela
フォローされています
日本初のトラブル発生後でも契約できる弁護士費用保証・立替サービス「アテラ」。クイックマネーサポート（オプションサービス）をご利用いただけば、状況によっては、生活費や治療費のご提供も可能。弁護士費用（着手金）の立替も行い、敗訴の場合、立替したお金や提供した資金は返済不要！
泣き寝入りのない社会を目指します！
legal-security.jp2020年6月からTwitterを利用しています
277 フォロー中
54 フォロワー

［source：］ 「アテラ」事務局さん (@atehosho_atela) / Twitter https://twitter.com/atehosho_atela
```

　コピペをしたところ，「フォローされています」とあったので，いくつか溜まっていた通知を確認したところフォローされましたとありました。この再捜査要請書＿警察庁・石川県警察御中（@kk_hirono）のアカウントは，尋常でないツイートの頻度で，余り変動がないのも不思議ではあります。

@hizumelaw ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@hizumelaw）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW hizumelaw（弁護士樋詰哲朗） 日時：2020/05/08 21:00 URL： https://twitter.com/hizumelaw/status/1258728395354943491  

> クラウドベースの事件管理システムのLEALA、firmee、LegalWinがあるけど、どれが使い勝手がよいのだろうか。各種書類作成支援はあると便利だけど、意外と面倒なイメージがある。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜yotajirosan（Ｂ54なぶさん） 日時：2020-08-18 19:50／2020/08/17 19:28 URL： https://twitter.com/kk_hirono/status/1295674444224983041 https://twitter.com/yotajirosan/status/1295306557505146880  

> @hizumelaw 何をつかってますか。firmeeにしようかとも思ってるんですが，Legalwinの値段が魅力的すぎて 書類作成支援よりも，顧客管理とメモの紐付け，できれば立替金とか請求書とかのお金関係がセットだとありがたいんですけど，なかなかないですよね。各ソフトのシェアもよくわからないですし迷います  

@hizumelaw ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@hizumelaw）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW hizumelaw（弁護士樋詰哲朗） 日時：2020/08/17 21:21 URL： https://twitter.com/hizumelaw/status/1295334926993125378  

> @yotajirosan firmeeが一番かなと思いました。  
> しかし、弊所では紆余曲折あって、結局、事務局に管理してもらうのが一番早いという結論になりました。身も蓋もなくてスミマセン。  

　今，樋詰哲朗弁護士（金沢弁護士会）のツイートを再確認して気がついたのですが，新たな発見とばかり思っていたツイートは，5月8日のツイートで，そのツイートに8月17日に返信があって，返信に応えた樋詰哲朗弁護士（金沢弁護士会）のツイートが22時間前となっています。

　たしか最後にTwitterで話題として見かけた蓮舫議員のツイートで，クラウドの技術が国や行政の機関にも採用されつつあるということを初めて知ったのですが，それ以来の最新のクラウドの技術で，それを弁護士が積極利用をしていると知ったところでした。22時間以内となりそうです。

　樋詰哲朗弁護士（金沢弁護士会）が5月8日で紹介しているネットのサービスは3つあるうちネットで調べて２つの情報を読むことが出来たのですが，料金が月額で2千円程度のようです。私が平成9年5月頃から平成10年の12月頃まで利用した判例のCDロムのサービスは月額17,500円でした。

　今夜は火曜日なのにNHKでうたコンの放送がないようです。久しぶりに歌番組をみたかったので残念です。テレビを消しました。

　今日は，かなり久しぶりに金沢弁護士会のTwitterアカウントを検索から探して開いたのですが，更新も6月から停まっていて，ツイートのリツイートも少なくなっていました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜kanazawabengosi（金沢弁護士会） 日時：2020-08-18 20:03／2020/06/01 10:28 URL： https://twitter.com/kk_hirono/status/1295677704209985537 https://twitter.com/kanazawabengosi/status/1267266652950806528  

> 金沢弁護士会業務再開のお知らせです。 https://t.co/MVDgUC0iYw  

　上記が最新のツイートですが，私が再捜査要請書＿警察庁・石川県警察御中（@kk_hirono）でリツイートをして2件から3件になったところです。6月でも1日なので最初の一日目でした。金沢弁護士会に対する世間の関心の低さもうかがえるところです。

```
金沢弁護士会
@kanazawabengosi
2020年4月からTwitterを利用しています
5 フォロー中
16 フォロワー
フォローしている人にフォロワーはいません

［source：］金沢弁護士会さん (@kanazawabengosi) / Twitter https://twitter.com/kanazawabengosi
```

　さきほども気がついていなかったと思うのですが，金沢弁護士会のTwitterアカウントは，フォロー中が5，フォロワーが16となっています。弁護士会に対する関心の低さが浮き彫りとなっているようですが，妥当性のチェックが入らないことで，楽ちんな運用もできそうです。

@kanazawabengosi @niben_net - 797：2020-08-15_23:16:46 ＊ 日本弁護士連合会（日弁連）@JFBAsns，第二東京弁護士会@niben_netに伝える，「戦没者に感謝って意味わからんよな。飢え死にしてくれてありがと… https://t.co/jNKDgNrwLS

　挨拶代わりのメンション付きのツイートを@kanazawabengosiの金沢弁護士会に送っておきました。確か4人の，副会長の一人，樋詰哲朗弁護士（金沢弁護士会）には，そうそうとだいぶん前からTwitterでたぶん三冠の，ブロックを受けています。

〈〈〈：Linux Emacs： 2020-08-18（火曜日）20：11 　〈〈〈

* 






