* 2020年7月4日の集中豪雨災害がきっかけで知った熊本県芦北町を舞台にした「放課後ていぼう日誌」
  :LOGBOOK:
  CLOCK: [2020-07-05 日 09:23]--[2020-07-05 日 16:32] =>  7:09
  :END:

:CATEGORIES: 金沢市場輸送

〉〉〉：Emacs： 2020-07-05（日曜日）09：23　 〉〉〉

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜KCCmagpii（ゆずめろん） 日時：2020-07-05 09:25／2020/07/04 12:20 URL： https://twitter.com/kk_hirono/status/1279572017583292416 https://twitter.com/KCCmagpii/status/1279253630743281664  

> 芦北町ってていぼう日誌のところだよね… https://t.co/exUT6ayH7Y  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-05 09:25／2020/07/05 08:49 URL： https://twitter.com/kk_hirono/status/1279572029570605057 https://twitter.com/hirono_hideki/status/1279562941814108161  

> ていぼう日誌 - Google 検索 https://t.co/J4svJt6oa5  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-05 09:25／2020/07/05 08:49 URL： https://twitter.com/kk_hirono/status/1279572046087741441 https://twitter.com/hirono_hideki/status/1279563053722263552  

> TVアニメ「放課後ていぼう日誌」公式サイト https://t.co/gsKRCOhVYq  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-05 09:25／2020/07/05 09:01 URL： https://twitter.com/kk_hirono/status/1279572074915180544 https://twitter.com/hirono_hideki/status/1279566138767101952  

> 放課後ていぼう日誌 - Wikiwand https://t.co/9GPs7mIszr 『放課後ていぼう日誌』（ほうかごていぼうにっし）は、小坂泰之による日本の漫画。『月刊ヤングチャンピオン烈』（秋田書店）にて、2017年No.3から連載中。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜yuki843003（高橋 幸美） 日時：2020-07-05 09:25／2020/07/04 21:21 URL： https://twitter.com/kk_hirono/status/1279572120322715649 https://twitter.com/yuki843003/status/1279389951734370304  

> うちの会社が官邸のSNSを毎日更新しているんだよ。 って5年前にまつりが言ってたよ。 #高橋まつり #電通 https://t.co/WAESHGSKi3  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-05 09:25／2020/07/05 09:07 URL： https://twitter.com/kk_hirono/status/1279572133836804097 https://twitter.com/hirono_hideki/status/1279567582928842752  

> (8) TVアニメ「放課後ていぼう日誌」PV - YouTube https://t.co/slXMTOTmZx  

　この熊本県芦北町には強く印象に残る思い出があってずっと前から度々思い出し気になっていたのですが，昨日7月4日の朝，Twitterのトレンドで初めに見たのが「球磨川氾濫」というワードでした。

　「放課後ていぼう日誌」を調べてみると，「『月刊ヤングチャンピオン烈』（秋田書店）」の連載ということが分かったのですが，今でも漫画の月刊誌があるとも知らず，チャンピオンを見たのも久しぶりのことで，なにより今でも秋田書店があることに驚いたという不思議さです。

〈〈〈：Linux Emacs： 2020-07-05（日曜日）09：30 　〈〈〈

* 160年ぶり　鎮疫祭　きょう　宇出津「あばれ祭」神事：北陸中日新聞Web，宇出津の八坂神社
  :LOGBOOK:
  CLOCK: [2020-07-05 日 16:32]
  :END:

:CATEGORIES: 宇出津

〉〉〉：Emacs： 2020-07-05（日曜日）16：32　 〉〉〉

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-05 16:33／2020/07/05 12:44 URL： https://twitter.com/kk_hirono/status/1279679763133521920 https://twitter.com/hirono_hideki/status/1279622231039995905  

> 160年ぶり 鎮疫祭 きょう 宇出津「あばれ祭」神事：北陸中日新聞Web https://t.co/XrvRsOvGZ9 神事は午前十時から。一般参拝者も入場できるが、多数の場合は入場制限を行う。終了後は、宇出津のコンセールのとで祈禱（きとう）札を配布する。  

　午前中は，祭礼委員として，この八坂神社の神事に行っていました。先週の土曜日に連絡があったように思いますが，「160年ぶり 鎮疫祭」というのは知らなかったように思います。ツイートにリンクのある北陸中日新聞の記事でも，多数の場合は入場制限とあります。

　笹はらい，という神事があって，そこでなぜあばれ祭りの置き松明の場所に大きな鍋があるのか理解が出来ました。記事に写真が掲載されていますが，見たことのない大きな鍋で，それもかなり古そうにみえます。鍋というより洗濯機のない時代の洗濯で使いそうな盥に見えます。

　変換候補に盥という漢字が出てきたのですが，Googleの画像検索で調べてみると，木製の風呂桶のようなものがあったり，台所で皿洗いに使っているような桶もみえます。

　今朝は熊本県芦北町について書き始めたところであったのですが，これもタライなどの日用品と関係がありました。昭和63年1月のことです。

　家に戻ってから「笹はらい」という神事について調べてみたのですが，「笹払い」と「笹祓い」でGoogle検索し，神戸の湊川神社では「湯立神事」とも呼ばれるようです。この神戸市の湊川神社についても，平成3年秋のことで思い出すことがありました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-05 16:50／2020/07/05 11:55 URL： https://twitter.com/kk_hirono/status/1279684142205026307 https://twitter.com/hirono_hideki/status/1279609855016185858  

> 湊川神社初午祭のユニークな湯立神事！巫女が笹束で釜から湯を振りケガレを祓う！｜オマツリジャパン｜毎日、祭日 https://t.co/oH8xDU7tW7 湊川神社へは、最寄りのJR神戸駅から徒歩4分程で行くことができます。都会の中に自然の広がる美しい境内が目印です！  

　神戸市の湊川神社も数年前に場所をGoogleマップで調べたことがあったと思うのですが，JR神戸駅から徒歩4分程というのは意外でした。自分の家から宇出津の八坂神社でも徒歩だと10分程かかりそうです。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-05 16:54／2020/07/05 11:51 URL： https://twitter.com/kk_hirono/status/1279685183143161861 https://twitter.com/hirono_hideki/status/1279608729432780800  

> 七夕神事～星祭と「笹の祓（はらえ）」｜【京都市公式】京都観光Navi https://t.co/SQebEyj4Xx  

　竹林に浴衣の女性の写真がありますが，竹と笹の関係についても今日は考える機会となりました。「七夕神事～星祭と「笹の祓（はらえ）」｜【京都市公式】京都観光Navi」とありますが，今もう一度リンクを開いてみると，京都の貴船神社とありました。

 - » 貴布禰總本宮 貴船神社 から 嵐山 - Google マップ https://t.co/cZBJEuIFYh

　京都の竹林の有名な場所をGoogleで調べると，嵐山と出てきました。嵐山とははっきり記憶にはなかったのですが，テレビの番組で何度か見たことがあり，だいたいの場所も出ていたと思ったのですが，同じくテレビで見た貴船神社とは，場所が離れているように思い，調べてみました。

〈〈〈：Linux Emacs： 2020-07-06（月曜日）07：25 　〈〈〈
 


