* 「弁護士っていうだけで、逆恨みの感情をぶつける」という深澤諭史弁護士のツイートと，「＃私たちの社会に風俗産業は要らない」というハッシュタグ

:CATEGORIES: 深澤諭史弁護士,村松謙弁護士

　深澤諭史弁護士のツイートは昨夜のうちにみかけていたのですが，もう1つのハッシュタグは，村松謙弁護士のタイムラインで見かけたのが始まりです。そのあとに見たうの字のタイムラインでも関連のありそうなツイートを見かけました。

@km0bake ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@km0bake）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW km0bake（つまらむ） 日時：2020/08/07 19:39 URL： https://twitter.com/km0bake/status/1291685487703289858  

> やっぱり、セックスワーカーの人たちに累積的抑圧経験を与えてるよね。。。こういうタグ使う人たち。。。 https://t.co/UVJgc60NhC  

　この少し上にも気になるツイートがあって，村松謙弁護士と市川寛弁護士の会話となっているようです。どちらもブロックされているアカウントになるかと思いますが，確認は1回だけにしておきます。

- TW km0bake（つまらむ） 日時： 2020/08/07 19:28 URL： https://twitter.com/km0bake/status/1291682563199623170  

> うちの事務所に女性初の検事正だった弁護士がいる。昨日は、女性初の刑事弁護教官だった先生と打ち合わせ。  
> ほんとつい最近なんだもんなぁ。。。  

@imarockcaster42 ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@imarockcaster42）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW imarockcaster42（弁護士 市川 寛） 日時：2020/08/07 20:00 URL： https://twitter.com/imarockcaster42/status/1291690761310756866  

> @km0bake その女性初の検事正の先生は、たぶん、私の高校の遠い先輩です。小田原支部にいたときにお会いしました。違っていたらすみません（汗  

- TW km0bake（つまらむ） 日時： 2020/08/07 20:19 URL： https://twitter.com/km0bake/status/1291695537947684866  

> @imarockcaster42 あたりです。  

　次が，「セックスワーカーの人たちに累積的抑圧経験を与えてるよね」という村松謙弁護士のツイートが，コメント付きリツイートしたツイートになります。余り見かけないアカウントなのでブロックはされてないかと思います。初見ではなさそうでした。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜kannekolaw（かんねこ@あなたの顧問弁護士(弁護士・社会福祉士　石橋靖己)） 日時：2020-08-09 09:11／2020/08/06 19:27 URL： https://twitter.com/kk_hirono/status/1292252007852515328 https://twitter.com/kannekolaw/status/1291319867203706880  

> #私たちの社会に風俗産業は要らない　というとんでもないハッシュタグを見た。誰かにとって要らなくても他の誰かが必要としている。それが仕事ってもんだ。自分の正義感だけで特定の産業をぶっ壊してよいという感覚を持ってるなら、そんな感覚こそ私たちの社会に要らないよ。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜kannekolaw（かんねこ@あなたの顧問弁護士(弁護士・社会福祉士　石橋靖己)） 日時：2020-08-09 09:11／2020/08/07 20:18 URL： https://twitter.com/kk_hirono/status/1292252040865824769 https://twitter.com/kannekolaw/status/1291695311509786626  

> ↓のTweetのとおり、このタグを最初に使った勝部さんの感覚に対しては以前も激しく疑問を持ったことがある。たぶん、私とは価値観が180度違うのであろう。  https://t.co/1W04WBeaZn https://t.co/8BEHCmd3OZ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜kannekolaw（かんねこ@あなたの顧問弁護士(弁護士・社会福祉士　石橋靖己)） 日時：2020-08-09 09:11／2020/05/06 21:38 URL： https://twitter.com/kk_hirono/status/1292252085606440960 https://twitter.com/kannekolaw/status/1258013332205735936  

> 目眩がした。なぜ岡村隆史がそこまでしなくてはならんの？👇  “岡村氏に勧めたい責任の取り方としては、今後数年間、ご自身のギャラの何割かを「イコール・ペイ(男女の賃金格差解消)」の活動や「セクハラ・マタハラ撲滅」の活動等に寄付するこ… https://t.co/imLlBrxIGK  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜kannekolaw（かんねこ@あなたの顧問弁護士(弁護士・社会福祉士　石橋靖己)） 日時：2020-08-09 09:11／2020/08/08 04:26 URL： https://twitter.com/kk_hirono/status/1292252119634857984 https://twitter.com/kannekolaw/status/1291818060731432960  

> 多少伸びてきたので，少し前に書いたこのnoteを貼っておきます。 性産業全廃論者に対する反論をまとめたもの。 https://t.co/LzzVWpa88I  


　次にうの字のタイムラインを再確認しておきます。

@un_co_the2nd ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@un_co_the2nd）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW un_co_the2nd（🐕💩） 日時：2020/08/08 15:26 URL： https://twitter.com/un_co_the2nd/status/1291984223415332864  

> 「私たちの社会(藤田何某と局部()とその取り巻きで構成した社会)」が無人島に引き篭もればいいだけだと思うのだよね https://t.co/epnwsYYYH2  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜Red_storehouse（紅蔵） 日時：2020-08-09 09:16／2020/08/07 20:47 URL： https://twitter.com/kk_hirono/status/1292253376093097985 https://twitter.com/Red_storehouse/status/1291702601923194880  

> 藤田孝則と局部元気による、自己満足ハッシュタグかwwwww #私たちの社会に風俗産業は要らない  

　2つ目はうの字のツイートがコメント付きリツイートしたツイートになります。ツイートと見直して気がついたのですが，局部元気とあるのは勝部元気という人のことのようです。藤田孝則という名前に誤りがあるのか，あるいは別人ということも気が付きました。

　藤田孝典という人物のことかと思い，Twitter検索をしたのですが，そのアカウントで#私たちの社会に風俗産業は要らない　，というハッシュタグを含むツイートは該当なしでした。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fujitatakanori（藤田孝典） 日時：2020-08-09 09:24／2020/08/08 23:56 URL： https://twitter.com/kk_hirono/status/1292255341132972033 https://twitter.com/fujitatakanori/status/1292112499731361792  

> 今日は20代の性被害女性が「性被害を受けても被害を受けた側にも非がある。被害を受けないように注意しなきゃダメ。」と言われて絶望したという話を聞く。 20代女性に「若い女が安心して生きる場所は日本にはないから、早く歳を取っておばあさ… https://t.co/TCK3CL0afN  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜KTB_genki（勝部元気 Katsube Genki） 日時：2020-08-09 09:24／2020/08/08 20:14 URL： https://twitter.com/kk_hirono/status/1292255352830885888 https://twitter.com/KTB_genki/status/1292056573313839105  

> 性的搾取する男性側に矛先を向けたはずなのに、搾取されている女性を盾にして、「女性たちがどうなっても良いのか！？」と叫び、自分たち男性側の支配権を守ろうとする。「撃つなよ！この人質がどうなっても良いのか！？」と構図が近いことから悪質… https://t.co/m3Bst8LobT  

　さきほどタイムラインのトップにあり，固定されたツイートと思っていたのが，上記の「今日は20代の性被害女性」という藤田孝典氏のツイートだったのですが，リツイートされた勝部元気氏のツイートがリツイートで一番上に置き換わっていました。

　この勝部元気という人ですが，名前に見覚えがあって，一時期何度かテレビのサンジャポことサンダージャポンという番組の出演者として見ていたような気がします。最近はみていない番組ですが，あと30分程すると始まるらしいと時間を確認しました。

勝部元気 サンジャポ - Google 検索 https://t.co/OpyAO6AXJp

　名前はテレビで見ているように思ったのですが，ネットに出ている顔写真をみていると，テレビで見たことのある人ではなさそうな気がしてきました。他の著名人と混同して勘違いしていたのかもしれません。

```
　これを受けて、先日2020年6月9日には自民党の誹謗中傷対策プロジェクトチームが提言を政府に提出しました。情報開示のハードルを下げる等の施策は、早急に進めて欲しい気持ちがある一方で、懸念もあります。

　前回の記事「木村花さんの死にも懲りない、批判と誹謗中傷の違いが分からない人たち」で触れたように、言葉の本来の意味を都合のいいように歪曲させる「言葉のカスタマイズ」が噴出する社会においては、適切な「批判」や「非難」が「誹謗中傷」とされ、逆に「誹謗中傷」が適切な「批判」や「非難」と見なされてしまうことが頻出しているのです。

　また、プロジェクトチームの座長を務める三原じゅん子参議院議員は、「批判と誹謗中傷の違いを皆さんにまず理解していただく」と述べていますが、その二つはどう区別するのでしょうか？　実際には、その境界線は曖昧であり、たとえ同じ言葉でも、TPOにより批判・非難の言葉が誹謗中傷の言葉になったり、その逆もあるからです。

　もしその区別を明確化できなければ、公権力による恣意的な解釈を許すことになりかねません。公権力や権力者と親しい人物に対する批判が誹謗中傷として捉えられて、言論封殺に繋がる可能性も十分あり得ることでしょう。これは絶対に防がなければならないことです。

［source：］伊藤詩織さんや木村花さんのケースから考える批判と誹謗中傷の境界線 - 勝部元気｜論座 - 朝日新聞社の言論サイト https://webronza.asahi.com/culture/articles/2020061500003.html
```

```
お笑い芸人の岡村隆史氏が、ラジオ番組「ナインティナイン岡村隆史のオールナイトニッポン」(2020年4月23日放送)で、以下のような発言をし、大きな批判が起こりました。

　「コロナが収束したら、もの凄く絶対おもしろいことある(中略)苦しい状態がずっと続きますから(中略)美人さんがお嬢やります(中略)稼がないと苦しいですから(中略)だから今、我慢しましょう」

　まるで女性の貧困化を期待し、望まずしてセックスワーカーになった女性への性的搾取を扇動するような発言であり、批判が殺到したのは当然です。この発言の何が問題かは、藤田孝典氏をはじめ、多くの論者が適切な批判を加えているため、ここでは岡村氏の「謝罪」と「責任」について指摘をしたいと思います。



［source：］「コロナ風俗嬢」発言の岡村隆史氏に、正しい“謝罪”と責任を取る機会を - 勝部元気｜論座 - 朝日新聞社の言論サイト https://webronza.asahi.com/culture/articles/2020050500001.html
```

　2つ目の記事は，さきほど見かけていたもので，今回の　#私たちの社会に風俗産業は要らない　というハッシュタグの始まりかと思っていたのですが，いま記事を見直すと5月5日のツイートとなっていました。

　この岡村隆志氏の風俗嬢の発言問題は，Twitterで見かけ，記事など読んでいましたが，藤田孝典氏が始まりで問題を大きくさせたようです。それも正しい事実にも続いていないという指摘がラジオ番組のリスナーから多数あったのも印象的な現象でした。

　この藤田孝典氏については，その前にも注目したことがあったのですが，貧困問題や生活保護というところで関わりの深い活動をされているようです。貧困ビジネスで搾取をしているという具体的な情報も多数見かけていました。

```
　仕事をしながら同番組を聴いていたという藤田氏が、ヤフーニュースやツイートで批判し、拡散させた。
　それによって、岡村に対する批判の嵐が吹き荒れるのかと思いきや、事態は思いもよらぬ展開となる。
　なんと、矛先は岡村にではなく、藤田氏に向かい、岡村のファンや、様々な方面から、「あんたこそ人のこと言えんのか！」「相手を社会的に抹殺する必要はあるのか」「売名のために岡村さんを利用するな」「藤田は貧困ビジネスをやっている」など、まさに、藤田氏の方がカウンターパンチを食らうはめになったのである。
　藤田氏を批判したのは、匿名のツイッタラーだけでなく、さいたま市議会議員(無所属)の吉田一郎氏や漫画家のろくでなし子といった著名人もいた。
　ろくでなし子は、藤田氏が、「生活保護の不正横領をしている」旨のツイートをしたが、それに対して藤田氏が、「事実はありましたか。確認しましたか。 名誉毀損の訴訟も検討します」などとリツイートすると、ろくでなし子は「何も怖くありませんのでご自由に」などと応戦し、なんともグダグダな状況になっていた。
　現時点(2020.5.5)においても、まだ完全に消火しきれていない状況が続いている。

［source：］藤田孝典は貧困ビジネスなのか？ - 生活保護の闇現場 http://eastnishibori.blog.fc2.com/blog-entry-18.html
```

　上記の引用に「ろくでなし子は、藤田氏が、「生活保護の不正横領をしている」旨のツイートをしたが、それに対して藤田氏が、「事実はありましたか。確認しましたか。 名誉毀損の訴訟も検討します」などとリツイートすると、ろくでなし子は「何も怖くありませんのでご自由」などと応戦」とあります。

　これは初めて知ったし意外でした。ろくでなし子という名前がここで出てきたのも意外なのですが，かねてより共通したものを感じていたのもこの両者だったからです。それは弁護士との良好な関係です。

　弁護士の中というか，法クラのツイートでは藤田孝典氏対して批判的なものを見かけているのですが，藤田孝典氏のツイートとして見かけた情報には，好意的に頼りにしていると伝わるものがありました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fujitatakanori（藤田孝典） 日時：2020-08-09 09:54／2020/04/23 22:40 URL： https://twitter.com/kk_hirono/status/1292263009469964297 https://twitter.com/fujitatakanori/status/1253317847385731074  

> 仲間の弁護士がLINEを利用した相談会をします。気軽に弁護士を活用してください。  障害のある方や家族のためのLINE法律相談 https://t.co/jS082dU8DP  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fujitatakanori（藤田孝典） 日時：2020-08-09 09:54／2020/04/21 11:30 URL： https://twitter.com/kk_hirono/status/1292263069268103169 https://twitter.com/fujitatakanori/status/1252424365779501059  

> あまりに相談が多いため、埼玉の有志の弁護士が緊急で相談ダイヤルを設置しました。 こちらにも相談ください。  コロナ災害・緊急電話相談ダイヤル・埼玉総合法律事務所の弁護士が対応・048-862-0360 https://t.co/AaViMWnXFf  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fujitatakanori（藤田孝典） 日時：2020-08-09 09:55／2020/04/24 22:31 URL： https://twitter.com/kk_hirono/status/1292263117666230273 https://twitter.com/fujitatakanori/status/1253678070289981441  

> 猪股正弁護士 リーマンショックでは、派遣社員など非正規の人が中心だったが、今回は正社員やフリーランス、個人事業者、中小企業などすべての働く人に幅広く影響が及んでいる  コロナ相談に5000件、弁護士らが危機感「数カ月で大量の失業、… https://t.co/Dt1gR40jl0  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fujitatakanori（藤田孝典） 日時：2020-08-09 09:55／2020/05/05 11:56 URL： https://twitter.com/kk_hirono/status/1292263155851120642 https://twitter.com/fujitatakanori/status/1257504306762153985  

> 一部ですでに実現した政策もありますが、仲間の研究者、弁護士、労働組合、NPOなどと共同で31の政策提言をしています。 新型コロナによる経済危機が発生しているなか、着実に人々の生存、暮らしを守る政策が必要です。  提言：生存する権利… https://t.co/Z9ybo6MoTR  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fujitatakanori（藤田孝典） 日時：2020-08-09 09:55／2020/04/25 21:07 URL： https://twitter.com/kk_hirono/status/1292263183281827840 https://twitter.com/fujitatakanori/status/1254019160528392192  

> 新型コロナ労働・生活総合相談ホットラインを実施。労働問題や生活支援に取り組むＮＰＯや弁護士などが対応。気軽に相談ください。 ５月２日（土）、３日（日）　いずれも１３時～２０時 ０１２０－３３３－７７４　外国人専用（英語、日本語可）… https://t.co/zyuEDZba00  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fujitatakanori（藤田孝典） 日時：2020-08-09 09:55／2020/04/23 16:18 URL： https://twitter.com/kk_hirono/status/1292263231654748160 https://twitter.com/fujitatakanori/status/1253221572455788546  

> 月末なので家賃、各種公共料金などの滞納も起こる。支払い猶予の交渉は可能。国交省も追い出さないように通知している。酷い場合は弁護士へ仲介するので相談ください。  家賃を払えないときは無理して払わないでください。諦めて住居を出ることも… https://t.co/1Wmm8JlqwO  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fujitatakanori（藤田孝典） 日時：2020-08-09 09:55／2020/04/10 11:27 URL： https://twitter.com/kk_hirono/status/1292263264018038784 https://twitter.com/fujitatakanori/status/1248437500793589763  

> 【拡散希望】4月18日、19日、両日とも午前10時から午後10時まで、全国一斉で弁護士らが電話相談会を開催する。番号は 0120-157930 で無料。気軽に相談してほしい。  4月18日、19日に大規模ないのちとくらしを守るなん… https://t.co/sZuKM6jzzB  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fujitatakanori（藤田孝典） 日時：2020-08-09 09:55／2020/05/03 16:24 URL： https://twitter.com/kk_hirono/status/1292263300080627712 https://twitter.com/fujitatakanori/status/1256847149142171649  

> GWの連休明けに緊急で生活保護申請に付き添う弁護士が増えています。 生活保護制度はなかなか馴染みがない福祉制度ですが、こういう困った時に活用できるものです。 一人で役所に行くことが不安な方、事情がある方は相談ください。 埼玉048… https://t.co/EDfVWmQiyu  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fujitatakanori（藤田孝典） 日時：2020-08-09 09:56／2020/03/29 00:20 URL： https://twitter.com/kk_hirono/status/1292263330590072832 https://twitter.com/fujitatakanori/status/1243920947574267905  

> 日本労働弁護団は、全国で4月5日から「新型コロナウイルス労働問題　全国一斉相談ホットライン」を開設。弁護士が無料相談（通話費用は要負担） 4月5日（日）午前10時～午後5時。新型コロナウイルス関連の労働問題について対応する。 【電… https://t.co/MGHXmDFxSt  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fujitatakanori（藤田孝典） 日時：2020-08-09 09:56／2020/04/07 14:34 URL： https://twitter.com/kk_hirono/status/1292263373514530817 https://twitter.com/fujitatakanori/status/1247397320884244485  

> 福祉事務所で生活保護が受けられなかった場合、第三者の法律家に意見を聞いて、状況によっては仲間の弁護士、司法書士らが窓口に同行支援も可能。こちらも活用を。  首都圏生活保護支援法律家ネットワーク 常設　０４８－８６６－５０４０　平日… https://t.co/YQ7WyVfCVC  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fujitatakanori（藤田孝典） 日時：2020-08-09 09:56／2020/04/18 16:54 URL： https://twitter.com/kk_hirono/status/1292263400169332736 https://twitter.com/fujitatakanori/status/1251418798155939842  

> 東京新聞:＜新型コロナ＞収入がない　休業補償は　弁護士ら無料電話相談　１８、１９日全国一斉:埼玉(TOKYO Web) https://t.co/z1CeeHb8kf 全国一斉電話相談会＝フリーダイヤル（０１２０）１５７９３０＝は十八、十九日の午前十時〜午後十時に開設。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fujitatakanori（藤田孝典） 日時：2020-08-09 09:56／2020/05/04 17:33 URL： https://twitter.com/kk_hirono/status/1292263436550696963 https://twitter.com/fujitatakanori/status/1257226742348972032  

> 失業手当の要件も緩和し、仕事のない人に幅広く支給すべきです。国は国民の生活を保障する義務があります。困窮による孤立や自殺を防ぐため、国に対策を要求していくことが大切です。  国は困窮による孤立や自殺を防げ　生活保護問題対策全国会議… https://t.co/PZdC34MEKT  

弁護士 (from:fujitatakanori) - Twitter検索 / Twitter https://t.co/x9KCck9tIK

　藤田孝典氏のツイートに「仲間の弁護士」というのは記憶になかったのですが，この「仲間の弁護士」という言葉自体がとても珍しく斬新に感じました。勢いも感じます。

　ちょっと検索を「仲間の弁護士」に変えてみたのですが，それだけでもけっこうな数が出てきたようです。ただTwitter検索は曖昧検索なので，「ブラック企業対策プロジェクト共同代表仲間の棗一郎弁護士(日本労働弁護団幹事長)と札幌に来ています。」なども含まれています。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜fujitatakanori（藤田孝典） 日時：2020-08-09 10:01／2016/09/02 17:18 URL： https://twitter.com/kk_hirono/status/1292264745777557504 https://twitter.com/fujitatakanori/status/771623299805687808  

> ブラック企業対策プロジェクト共同代表仲間の棗一郎弁護士(日本労働弁護団幹事長)と札幌に来ています。二人で拙著『貧困世代』(講談社現代新書)を参照しながら、若者の貧困と労働問題について語ります。会場へお越しください。 https://t.co/dFY975izYd  

　この「ブラック企業対策プロジェクト」というのは，佐々木亮弁護士や嶋﨑量弁護士らの団体名と似ています。棗一郎弁護士という名前もどこかで見かけていたような気がしますが，法クラのツイートではなかったように思います。

ブラック企業対策プロジェクト https://t.co/wMb0TxdaRg

　Googleの検索からリンクを開くと，見たことのないページが表示されました。これは佐々木亮弁護士や嶋﨑量弁護士の団体とは異なるのかもしれません。

```
共同代表

今野晴貴

『ブラック企業　日本を食いつぶす妖怪』の著者
『しごとダイアリー２』監修
労働相談を中心に若者の格差・労働問題に取り組むNPO法人POSSEの代表
NPO法人POSSEホームページ

藤田孝典

『ひとりも殺させない　それでも生活保護を否定しますか』の著者
埼玉県内で野宿生活状態にある方、生活に困っている方を相談支援する団体NPO法人ほっとプラスの代表理事
NPO法人ほっとプラスのホームページ

［source：］About Us | ブラック企業対策プロジェクト http://bktp.org/about-us
```

　二人の人物の顔写真とプロフィールだけで，弁護士の名前は他のタブにあるページを含め見当たらないと思っていたのですが，下にProject Members （50音順）という項目があって，佐々木亮弁護士や嶋﨑量弁護士の名前が並んでいます。

　共同代表として顔写真が藤田孝典氏と並んでいる，今野晴貴という人の名前は，以前見かけていたと思うのですが，著書の紹介がプロフィールにあって，そのタイトル名に驚きました。『ブラック企業　日本を食いつぶす妖怪』とあります。

　「Project Members （50音順）」に戸舘圭之弁護士の名前があるのも意外だったのですが，それより気になったのは「新里宏二（弁護士）」とあることです。最近になってよく見かけるようになった弁護士の名前に似ており，多分当たっていると思いますが，当たりだと仙台の弁護士です。

```
被害対策弁護団によると、同事務所が抱えていた依頼は約２万件に上るとされ、過払い金の多くが依頼者に返還されていないとみられる。新里宏二団長は「まずは被害実態を把握して、可能な救済を図っていきたい」と話した。
　電話相談会は８月１、２、８、９、１５、２２、２９日に開催され、午前１０時～午後４時まで対応する。電話番号は０５７０（０５６）５６０。

［source：］被害対策弁護団を結成　流用疑惑の東京ミネルヴァ：時事ドットコム https://www.jiji.com/jc/article?k=2020073101075&g=soc
```

```
過払い金返還請求などを手掛けた弁護士法人「東京ミネルヴァ法律事務所」（東京都港区）が負債５１億円を抱えて破綻したことを受け、弁護士１１５人が被害対策全国弁護団（新里宏二団長）を結成した。８月の毎週末に電話相談を受け付ける。消費者金融業者などから返還された過払い金を依頼者に渡さず別使途に流用していた疑いがあり、被害実態の把握を進める。

［source：］東京ミネルヴァ法律事務所の破綻で弁護団結成　依頼者から電話相談受付 - SankeiBiz（サンケイビズ）：自分を磨く経済情報サイト http://www.sankeibiz.jp/workstyle/news/200731/cpd2007311807003-n1.htm
```

```
ハンセン病家族訴訟で損害賠償を命じた熊本地裁判決を国が受け入れる方針を示したことについて、旧優生保護法下の強制不妊手術を巡る全国被害弁護団の共同代表の新里宏二弁護士は「政府の対応を注目してきた。筆舌に尽くしがたい被害が家族にもあった中で、国が控訴を断念するのは当然と言える」と指摘した。

［source：］「当然」と強制不妊弁護団　ハンセン病訴訟控訴断念に： 日本経済新聞 https://r.nikkei.com/article/DGXMZO47145540Z00C19A7CN8000?s=1
```

```
救済法の意義や課題を、超党派議員連盟の事務局長として立法作業を担った福島瑞穂参院議員（社民）と、全国被害弁護団共同代表で日本弁護士連合会副会長などを歴任した新里宏二弁護士（仙台弁護士会）に聞いた。

［source：］旧優生保護法を問う：強制不妊救済法成立　福島瑞穂参院議員、新里宏二弁護士に聞く - 毎日新聞 https://mainichi.jp/articles/20190425/ddm/010/040/010000c
```

　記事は読んでいませんが，福島瑞穂弁護士と新里宏二弁護士の名前が一緒に，それも毎日新聞の記事のタイトルに出てくるとは意外です。それも強制不妊救済法成立から並んでいます。

　テレビでみかけることのあるニュースですが，旧優生保護法の強制不妊の問題はハンセン病の隔離施設での問題となっていたと思います。その家族の救済については法律の制定ではなく，政府の補償という解決になったとテレビで見たことが印象的でした。

　これはB型肝炎訴訟の法律との違いを大きく感じる解決策でした。B型肝炎訴訟の法律制定こそ弁護士らが獲得した利権であり，このような法律を成立させてくれる政府こそ，弁護士らが支持する政府あるいは政権政党というイメージが根強くありました。

```
今回成立した「旧優生保護法に基づく優生手術等を受けた者に対する一時金の支給等に関する法律」では、被害者に一律320万円が支払われる。

一時金の請求期間は5年間で、専門家によって受給権があるかの調査が行われ、認定が必要となる。

現在、20人ほどの被害者が国を相手に訴訟を起こしている。一連の訴訟の最初の判決は5月末に出る予定。

［source：］旧優生保護法の救済法が成立、強制不妊手術の被害者に一時金 - BBCニュース https://www.bbc.com/japanese/48047996
```

```
国家賠償請求訴訟［編集］
2018年1月30日、旧優生保護法による強制不妊手術を受けた宮城県在住の60代女性が、個人の尊厳や自己決定権を保障する日本国憲法に違反するとして、国家賠償を求めて仙台地方裁判所に提訴した［6］。

この原告女性の代理人弁護士を始めとする184人の弁護士によって、2018年5月27日、全国優生保護法被害弁護団が結成された［7］。2019年5月15日時点で、全国規模の一斉電話相談を5回実施するなど、被害者の救済に向けた全国的活動を行っている［8］［9］。

2019年3月5日時点で、同様の国家賠償請求訴訟が、札幌・仙台・東京・静岡・大阪・神戸・熊本の7地方裁判所に提起されている。原告は、60代から80代までの男女20人にのぼる［10］。

［source：］旧優生保護法に基づく優生手術等を受けた者に対する一時金の支給等に関する法律 - Wikipedia https://ja.wikipedia.org/wiki/%E6%97%A7%E5%84%AA%E7%94%9F%E4%BF%9D%E8%AD%B7%E6%B3%95%E3%81%AB%E5%9F%BA%E3%81%A5%E3%81%8F%E5%84%AA%E7%94%9F%E6%89%8B%E8%A1%93%E7%AD%89%E3%82%92%E5%8F%97%E3%81%91%E3%81%9F%E8%80%85%E3%81%AB%E5%AF%BE%E3%81%99%E3%82%8B%E4%B8%80%E6%99%82%E9%87%91%E3%81%AE%E6%94%AF%E7%B5%A6%E7%AD%89%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8B%E6%B3%95%E5%BE%8B
```

　「弁護士」でページ内検索しました。2018年1月30日というのは意外に最近ですが，宮城県在住の60代女性が国家賠償を求めて仙台地方裁判所に提訴したことが始まりになるようです。

B型肝炎「給付金」特措法改正が成立。当面の期限を5年延長。 | 全国B型肝炎訴訟東京弁護団 給付金相談 医療費助成改善等 https://t.co/Ff1HMAjBIm

本日、平成28年（2016年）5月13日（金）、参議院本会議において、「特定B型肝炎ウイルス感染者給付金等の支給に関する特別措置法の一部を改正する法律案」（閣法第二七号）が可決されました。総数228名中、賛成228名、反対0名と、… https://t.co/OLqh3gRElt

```
(訴訟手当金の支給)

第七条　特定B型肝炎ウイルス感染者又はその相続人が、確定判決等に係る訴訟又は和解若しくは調停に関し、特定B型肝炎ウイルス感染者であることを確認するための検査に要する費用として厚生労働省令で定めるものを支出したとき又は弁護士若しくは弁護士法人に報酬を支払うべきときは、支払基金は、特定B型肝炎ウイルス感染者給付金の支給を請求する者に対し、その者の請求に基づき、訴訟手当金を支給する。

２　訴訟手当金の額は、前項に規定する厚生労働省令で定める費用に係るものにあっては当該検査に通常要する費用を考慮して厚生労働省令で定める額とし、弁護士又は弁護士法人に支払うべき報酬に係るものにあっては当該者に支給される特定B型肝炎ウイルス感染者給付金の額に百分の四を乗じて得た額とする。

３　第三条第二項及び第三項の規定は訴訟手当金の支給について、第五条の規定は訴訟手当金の支給の請求について準用する。

(追加給付金の支給)

［source：］・特定Ｂ型肝炎ウイルス感染者給付金等の支給に関する特別措置法(◆平成23年12月16日法律第126号) https://www.mhlw.go.jp/web/t_doc?dataId=81ab2495&dataType=0&pageNo=1
```

　「特定Ｂ型肝炎ウイルス感染者給付金等の支給に関する特別措置法」という名称も初めて見たと思ったのですが，「(訴訟手当金の支給)」というのが肝となっているようです。これが弁護士広告や果ては，東京ミネルヴァ法律事務所の破産につながったレールにも見えます。

　件のハッシュタグをみて，深澤諭史弁護士のツイートの内容を思い出しながら頭に浮かんできたのが，「弁護士産業」という言葉で，これは産業廃棄物という意味合いを多分に含む，社会問題と考えます。

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2020/08/08 20:08 URL： https://twitter.com/fukazawas/status/1292055117156372482  

> 弁護士って、仕事柄、相手方から恨まれるというのは想定していたけれども、世の中には、「弁護士っていうだけで、逆恨みの感情をぶつける」人たちが結構たくさんいるってあたり、本当に勉強になりました。  
> （・∀・）（＾ω＾） https://t.co/KvWvJQLCeE  

　世の中で弁護士を悪く言うやつは，逆恨みと決めつけている内容です。弁護士に対する宗教的な信仰を強く感じる深澤諭史弁護士のツイートです。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-09 10:58／2020/08/08 22:13 URL： https://twitter.com/kk_hirono/status/1292279052619849728 https://twitter.com/s_hirono/status/1292086569038274560  

> 2020-08-08-220919_深澤諭史@fukazawas·2時間弁護士って、仕事柄、相手方から恨まれるというのは想定していたけれども、世の中には、「弁護士っていうだけで.jpg https://t.co/3ZK199cWGv  

　そういえば，最近は見かけなくなった感情論という言葉ですが，モトケンこと矢部善朗弁護士（京都弁護士会）が相手をねじ伏せるのに使う技のように思えた時期もありました。素人は感情論，弁護士は法律家で理路整然という自信が根底にあるのでしょう。

〈〈〈：Linux Emacs： 2020-08-09（日曜日）11：08 　〈〈〈

