* 昨日の朝，知ったところの「農業アイドル自殺訴訟」で場外乱闘　タレント弁護士がちらつかせた”月9出演”話(デイリー新潮)」という佐藤大和弁護士，望月宣武弁護士の問題

** それらしき予兆は，深澤諭史弁護士のタイムラインでの深澤諭史弁護士の意味深なツイート

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-09-08 11:18 URL： https://twitter.com/hirono_hideki/status/1303155737321811968
> 2020年09月08日11時01分の登録： ＼深澤諭史　@fukazawas＼とんでもないニュースを見た・・・。 証拠はあるが，信じたくない・・・。 https://t.co/9IYilaokMh

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2020/09/08 10:21 URL： https://twitter.com/fukazawas/status/1303141447227437056  

> とんでもないニュースを見た・・・。  
> 証拠はあるが，信じたくない・・・。  

** 「こ、これは・・。長いので誰か要約してほしい。」という大西洋一弁護士のツイートで最初に発見したのが，「FRIDAYの記事と日本エンターテイナーライツ協会の釈明について」という記事

RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜o2441（弁護士大西洋一） 日時：2020-09-08 11:48／2020-09-08 07:44 URL： https://twitter.com/hirono_hideki/status/1303163353645285376 https://twitter.com/o2441/status/1303101961223327744
> こ、これは・・。長いので誰か要約してほしい。
> 
> FRIDAYの記事と日本エンターテイナーライツ協会の釈明について https://t.co/v3Gm6qZZNZ

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-09-08 11:50 URL： https://twitter.com/hirono_hideki/status/1303163677068025861
> FRIDAYの記事と日本エンターテイナーライツ協会の釈明について https://t.co/XA86oyU5lw

RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜fuyu3710（相澤冬樹　共著【私は真実が知りたい】発売中） 日時：2020-09-08 11:50／2020-09-08 08:46 URL： https://twitter.com/hirono_hideki/status/1303163733384986626 https://twitter.com/fuyu3710/status/1303117545197563906
> 日本ジャーナリスト会議（JCJ）のJCJ賞を赤木雅子さんと連名で受賞することになりました。9月5日に開かれた選考会で決まったと7日夕方ご連絡を頂きました。ありがとうございます。この記事は共同通信が昨夜配信し、大阪日日新聞が急きょ掲載を決めました。#私は真実が知りたい #赤木さんはあなたです https://t.co/cWWaTM9ozB

RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜Custom24_Taaant（タント） 日時：2020-09-08 12:42／2020-09-07 17:30 URL： https://twitter.com/hirono_hideki/status/1303176955446005760 https://twitter.com/Custom24_Taaant/status/1302887009392848897
> 「農業アイドル自殺訴訟」で場外乱闘　タレント弁護士がちらつかせた“月9出演”話(デイリー新潮)
> 
> #農業アイドル自殺訴訟
> #Yahooニュース
> https://t.co/q5jNhbRAKs

RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜dailyshincho（デイリー新潮） 日時：2020-09-08 12:43／2020-09-07 17:29 URL： https://twitter.com/hirono_hideki/status/1303177192902336513 https://twitter.com/dailyshincho/status/1302886742073266176
> 「農業アイドル自殺訴訟」で場外乱闘　タレント弁護士がちらつかせた“月9出演”話
> https://t.co/c8oYmVX9FR
> …怖くなったので、念のために面会の様子を録音しておくことにしたのです
> #農業アイドル #大本萌景 さん #佐藤大和 弁護士 #月9 #自死 #デイリー新潮

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-09-08 12:45 URL： https://twitter.com/hirono_hideki/status/1303177566543519746
> 「農業アイドル自殺訴訟」で場外乱闘　タレント弁護士がちらつかせた“月9出演”話 | デイリー新潮 https://t.co/zz2ptxvW2r それから半年以上の時間を経て、彼女が録音していた音声データがYouTubeで“暴露”されたのだ。一体、何があったのか――。

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-09-08 12:45 URL： https://twitter.com/hirono_hideki/status/1303177696541724672
> 2020年09月08日12時42分の実行記録
> twitterAPI-search-lawList-mydql-add.rb "佐藤大和"
> ツイート数：4/1969 リツイート数：4/1969 トータル：166
> hirono_hideki 0／0件
> kk_hirono 0／0件
> s_hirono 0／0件

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-09-08 12:56 URL： https://twitter.com/hirono_hideki/status/1303180340446388225
> 「農業アイドル自殺訴訟」で場外乱闘　タレント弁護士がちらつかせた“月9出演”話 | デイリー新潮 https://t.co/VQ4vo7d5Eb 佐藤弁護士からすれば、“寝返った”ということになるのだろうが、身から出た錆であろう。
> 
> 　被告側代理人の渥美陽子弁護士は、語気を強めてこう指摘する。

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-09-08 12:58 URL： https://twitter.com/hirono_hideki/status/1303180908929773569
> 農業生産法人hプロジェクト株式会社 https://t.co/C1yP2GTEHj

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-09-08 12:59 URL： https://twitter.com/hirono_hideki/status/1303181209518833670
> 2020年09月08日12時48分の実行記録
> twitterAPI-search-lawList-mydql-add.rb "タレント弁護士がちらつかせた"
> ツイート数：5/1969 リツイート数：7/1969 トータル：142
> hirono_hideki 1／2件
> kk_hirono 0／0件
> s_hirono 0／0件

** ”農業アイドル 訴訟”というTwitterAPI検索，2020年09月08日19時50分の実行記録トータル185

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-09-08 19:56 URL： https://twitter.com/hirono_hideki/status/1303286179425525761
> 2020年09月08日19時50分の実行記録
> twitterAPI-search-lawList-mydql-add.rb "農業アイドル 訴訟"
> ツイート数：6/1969 リツイート数：7/1969 トータル：185
> hirono_hideki 2／2件
> kk_hirono 0／0件
> s_hirono 0／0件

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-09-08 20:23 URL： https://twitter.com/hirono_hideki/status/1303292768815517696
> 2020年09月08日20時21分の実行記録
> twitterAPI-search-lawList-mydql-add.rb "愛媛ご当地アイドル"
> ツイート数：1/1969 リツイート数：2/1969 トータル：37
> hirono_hideki 0／0件
> kk_hirono 0／0件
> s_hirono 0／0件

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-09-08 20:25 URL： https://twitter.com/hirono_hideki/status/1303293440902324229
> 2020年09月08日20時23分の登録： REGEXP：”愛媛ご当地アイドル”／データベース登録済みツイート：2020年09月08日20時23分の記録：ユーザ・投稿：6／6件 https://t.co/m9AzTz1rmH

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-09-08 20:25 URL： https://twitter.com/hirono_hideki/status/1303293335377829888
> 2020年09月08日19時57分の登録： REGEXP：”農業アイドル．＊訴訟”／データベース登録済みツイート：2020年09月08日19時57分の記録：ユーザ・投稿：10／14件 https://t.co/bCJlbSGQR5

** 「ううむ。。。こんなことで場外乱闘」という佐々木亮弁護士のツイートで知った，「元愛の葉Girlsメンバーに取引を持ちかける遺族弁護団の音声録音【月9】 - YouTube」

:CATEGORIES: 佐々木亮弁護士,嶋﨑量弁護士,佐藤大和弁護士,望月宣武弁護士

TW s_hirono（非常上告-最高検察庁御中_ツイッター） 日時： 2020-09-09 00:21 URL： https://twitter.com/s_hirono/status/1303352867936378882
> 2020-09-08-201843_嶋﨑量（弁護士）さんがリツイート￼ささきりょう@ssk_ryo·8時間ううむ。。。こんなことで場外乱闘するような事案ではないと思うので、いろ.jpg https://t.co/9LLqSlxAij

TW s_hirono（非常上告-最高検察庁御中_ツイッター） 日時： 2020-09-09 00:22 URL： https://twitter.com/s_hirono/status/1303352941009543171
> 2020-09-08-202157_【愛媛ご当地アイドル自殺訴訟】陳述書のサインを得ようと元愛の葉Girlsメンバーに取引を持ちかける遺族弁護団の音声録音【月9】3,577　回.jpg https://t.co/QQDJrXBAzY

　嶋﨑量弁護士のタイムラインでの佐々木亮弁護士のツイートのスクリーンショットの記録が昨夜20時21分となっています。YouTubeで音声動画が出ているらしい情報は見かけていましたが，GoogleやYouTubeで検索をしても見つけられずにいました。

** デイリー新潮の「「農業アイドル自殺訴訟」で場外乱闘　タレント弁護士がちらつかせた“月9出演”話」というネット記事に関する，法クラ弁護士らの反応と記録

```
佐藤弁護士からすれば、“寝返った”ということになるのだろうが、身から出た錆であろう。

　被告側代理人の渥美陽子弁護士は、語気を強めてこう指摘する。

「訴訟の関係者が、弁護士に陳述書のサインをお願いされて断った場合、普通の人は、弁護士が関与しているのだから、陳述書の内容が勝手に裁判に出されることはないと思うでしょう。それを弁護士が表紙だけ差し替えて無断で裁判に提出するということは、弁護士に対する信頼を裏切る行為だと思います。また、音声データで明らかになっていますが、佐藤弁護士は橋川さんからの陳述書を取りたいがために、『月9』話を持ちかけています。『月9』出演といった利益供与をちらつかせてサインを迫るような手法も含めて、弁護士倫理上問題ある行為と考えます」

［source：］「農業アイドル自殺訴訟」で場外乱闘　タレント弁護士がちらつかせた“月9出演”話 | デイリー新潮 https://www.dailyshincho.jp/article/2020/09071703/?all=1&page=4
```

　記事は，「2020年9月7日掲載」となっています。今のところ9月8日の朝より前のツイートは見かけていないのですが，このあと作成済みの記録から確認作業を行います。弁護士鉄道の検証問題です。

　週刊新潮の記事の転載と思っていたのですが，昨日の午後，図書館でみたところ最新号と思われる週刊新潮にそれらしい記事は見当たりませんでした。週刊誌は週刊新潮と週刊文春のみが置いてあります。

 - 2020年09月08日12時46分の登録： REGEXP：”佐藤大和”／データベース登録済みツイートの検索：2020-09-03〜2020-09-08／2020年09月08日12時46分の記録：ユーザ・投稿：4／6件 http://hirono2014sk.blogspot.com/2020/09/regexp2020-09-032020-09-0820200908124646.html
 - 2020年09月08日13時00分の登録： REGEXP：”タレント弁護士がちらつかせた”／データベース登録済みツイート：2020年09月08日13時00分の記録：ユーザ・投稿：10／13件 http://hirono2014sk.blogspot.com/2020/09/regexp2020090813001013.html
 - 2020年09月08日19時57分の登録： REGEXP：”農業アイドル．＊訴訟”／データベース登録済みツイート：2020年09月08日19時57分の記録：ユーザ・投稿：10／14件 http://hirono2014sk.blogspot.com/2020/09/regexp2020090819571014.html
 - 2020年09月08日20時23分の登録： REGEXP：”愛媛ご当地アイドル”／データベース登録済みツイート：2020年09月08日20時23分の記録：ユーザ・投稿：6／6件 http://hirono2014sk.blogspot.com/2020/09/regexp20200908202366.html

 - （01／13） RT ashiharashuichi（芦原修一?）｜KanaiYoshiie（kanai yoshiie） 日時：2020-09-07 19:10:00 +0900／2020-09-07 18:56:00 +0900 URL： https://twitter.com/ashiharashuichi/status/1302912041552814083 https://twitter.com/KanaiYoshiie/status/1302908543771705345
弁護士より国会議員向きだなwwwww \n \n 「農業アイドル自殺訴訟」で場外乱闘　タレント弁護士がちらつかせた“月9出演”話 https://t.co/h7KvYTXutX #デイリー新潮

　最初の記録が，9月7日18時56分のツイートの同日19時10分のリツイートとなっていました。おそくともこの時点で，デイリー新潮のネット記事は公開されていたようです。

 - （02／13） TW ichifuna_law（弁護士 髙橋裕樹（アトム市川船橋法律事務所代表）） 日時： 2020-09-07 23:40:00 +0900 URL： https://twitter.com/ichifuna_law/status/1302980029781913602

> 今後懲戒請求とかになっていくかもしれませんね、このトラブルは
>
> 「農業アイドル自殺訴訟」で場外乱闘　タレント弁護士がちらつかせた“月9出演”話(デイリー新潮)
> #Yahooニュース
> https://t.co/NPZwtNcvpe

　見かけていなかったツイートになります。こちらは弁護士本人のツイートですが，9月7日23時40分ということで，デイリー新潮の記事の公開から開きがあるようです。

 - （04／13） TW okumuraosaka（okumuraosaka） 日時： 2020-09-08 00:09:00 +0900 URL： https://twitter.com/okumuraosaka/status/1302987317817171968

> 「農業アイドル自殺訴訟」で場外乱闘　タレント弁護士がちらつかせた“月9出演”話(デイリー新潮)
> #Yahooニュース
> https://t.co/TB1qpxmmPi

 - （05／13） RT un_co_the2nd（うのじ）｜okumuraosaka（okumuraosaka） 日時：2020-09-08 01:12:00 +0900／2020-09-08 00:09:00 +0900 URL： https://twitter.com/un_co_the2nd/status/1303003278649614349 https://twitter.com/okumuraosaka/status/1302987317817171968
「農業アイドル自殺訴訟」で場外乱闘　タレント弁護士がちらつかせた“月9出演”話(デイリー新潮) \n #Yahooニュース \n https://t.co/TB1qpxmmPi

 - （06／13） TW keita_adachi（弁護士足立敬太 @アレクサ 六甲おろしかけて） 日時： 2020-09-08 07:01:00 +0900 URL： https://twitter.com/keita_adachi/status/1303090925602615296

> 「農業アイドル自殺訴訟」で場外乱闘　タレント弁護士がちらつかせた“月9出演”話(デイリー新潮)
> #Yahooニュース
> https://t.co/uYriyLSJ2Q

 - （09／13） TW TSUYOSHIFUKAI（深井 剛志） 日時： 2020-09-08 11:59:00 +0900 URL： https://twitter.com/TSUYOSHIFUKAI/status/1303165957423001601

> こんなことになっていたのか。
>
> 「農業アイドル自殺訴訟」で場外乱闘　タレント弁護士がちらつかせた“月9出演”話(デイリー新潮)
> #Yahooニュース
> https://t.co/JjtL9KTe5W

 - （13／13） TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-09-08 12:59:00 +0900 URL： https://twitter.com/hirono_hideki/status/1303181209518833670

> 2020年09月08日12時48分の実行記録
> twitterAPI-search-lawList-mydql-add.rb ""タレント弁護士がちらつかせた""
> ツイート数：5/1969 リツイート数：7/1969 トータル：142… https://t.co/O97wgwjfsJ

　個人的に愛媛と聞いて思い出す1つが，「アパッチ野球軍」という古いアニメになるのですが，荒唐無稽でありながら妙にリアリティを感じる作画でした。どうもこの愛媛の弁護団に重なるところがあるのですが，想像を超えた展開となりつつあり，静観の向きが同業者には強いようです。

アパッチ野球軍 OP 【ｽﾃﾚｵ】 - YouTube https://t.co/kMArXqPM2G

　この愛媛の弁護団については，佐藤大和弁護士，望月宣武弁護士，そして福岡の向原栄大朗弁護士がテレビのニュースに繰り返し出ていました。弁護士鉄道の歴史としても華々しいスタートを切った損害賠償請求の提訴であったと思います。

 - 2020年09月09日08時16分の登録： REGEXP：”佐藤大和”／データベース登録済みツイートの検索：2020-09-08〜2020-09-08／2020年09月09日08時16分の記録：ユーザ・投稿：5／11件 http://hirono2014sk.blogspot.com/2020/09/regexp2020-09-082020-09.html
 - 2020年09月09日08時19分の登録： REGEXP：”佐藤．＊弁護士”／データベース登録済みツイートの検索：2020-09-08〜2020-09-09／2020年09月09日08時19分の記録：ユーザ・投稿：4／6件 http://hirono2014sk.blogspot.com/2020/09/regexp2020-09-082020-09-0920200909081946.html
 - 2020年09月09日08時23分の登録： REGEXP：”望月．＊弁護士”／データベース登録済みツイートの検索：2020-09-08〜2020-09-09／2020年09月09日08時23分の記録：ユーザ・投稿：4／5件 http://hirono2014sk.blogspot.com/2020/09/regexp2020-09-082020-09-0920200909082345.html

　向原栄大朗弁護士のタイムラインに関連したと思われるツイートは見当たりませんでした。

 - 2020年09月09日08時06分の登録： ＼向原総合法律事務所　弁護士向原　@harrier0516osk＼もともと法テラスのいうことはなんでも聞いてきて、会員が法テラスに言いたいことは何一つ伝えてないあるいは通 http://hirono2014sk.blogspot.com/2020/09/harrier0516osk_9.html

 - 2020年09月08日19時51分の登録： ＼佐藤大和『図解版ずるい暗記術 』重版決定！　@yamato_lawyer＼風が強いですね。 今日は法科大学院の学生さんからの勉強相談￼当時の自分の勉強法を思い出しながら http://hirono2014sk.blogspot.com/2020/09/yamatolawyer.html
 - 2020年09月08日19時53分の登録： ＼望月宣武 Hiromu MOCHIZUKI　@166mochizuki＼無難に多数派工作に成功し、議案を通せたと、執行部は安堵していることでしょう。  しかし、短期的に http://hirono2014sk.blogspot.com/2020/09/hiromu-mochizuki166mochizuki_8.html

　佐藤大和弁護士と望月宣武弁護士のタイムラインも同じです。佐藤大和弁護士と仲良しの北周士弁護士のタイムラインも普段とまったく変わりなく，どこ吹く風という感じでした。

 - 2020年09月08日19時56分の登録： ＼『信仰の』ノースライム　@noooooooorth＼【弁護士から経営者になるってどんなこと】Holmesの笹原さんに対するインタビューをまとめました。ぜひご覧ください。 http://hirono2014sk.blogspot.com/2020/09/noooooooorthholmes.html

```
アカウント名	ツイート数	リツイート数
cloud_110（cloud_110）	0	1
奉納＼さらば弁護士鉄道・泥棒神社の物語（hirono_hideki）	3	1
弁護士足立敬太 @アレクサ 六甲おろしかけて（keita_adachi）	0	2
アカギ（akagishigelu）	1	0
新藤圭介（keisukeshinto）	0	3


［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”佐藤大和”／データベース登録済みツイートの検索：2020-09-08〜2020-09-08／2020年09月09日08時16分の記録：ユーザ・投稿：5／11件 http://hirono2014sk.blogspot.com/2020/09/regexp2020-09-082020-09.html
```

 - （02／11） RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜dailyshincho（デイリー新潮） 日時：2020-09-08 12:43:00 +0900／2020-09-07 17:29:00 +0900 URL： https://twitter.com/hirono_hideki/status/1303177192902336513 https://twitter.com/dailyshincho/status/1302886742073266176
「農業アイドル自殺訴訟」で場外乱闘　タレント弁護士がちらつかせた“月9出演”話 \n https://t.co/c8oYmVX9FR \n …怖くなったので、念のために面会の様子を録音しておくことにしたのです \n #農業アイドル #大本萌景 さん… https://t.co/kIvQPPF7vC

　自分のリツイートだと気がついたのですが，次のデイリー新潮のツイートは，佐藤大和弁護士のハッシュタグまで入っていました。「#佐藤大和 弁護士」というのは，より広くという効果がありそうです。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜dailyshincho（デイリー新潮） 日時：2020-09-09 10:21／2020/09/07 17:29 URL： https://twitter.com/kk_hirono/status/1303503863836598272 https://twitter.com/dailyshincho/status/1302886742073266176  

> 「農業アイドル自殺訴訟」で場外乱闘　タレント弁護士がちらつかせた“月9出演”話 https://t.co/c8oYmVX9FR …怖くなったので、念のために面会の様子を録音しておくことにしたのです #農業アイドル #大本萌景 さん #佐藤大和 弁護士 #月9 #自死 #デイリー新潮  

** 2020年8月28日付けだと気がついた，「FRIDAYの記事と日本エンターテイナーライツ協会の釈明について」という記事

:CATEGORIES: 佐藤大和弁護士,望月宣武弁護士

```
平素より弊社を応援いただき，誠にありがとうございます。

愛の葉Girlsに所属されていた大本萌景さんの自死に関しては，2018年10月12日，萌景さんのご遺族から，弊社らに対し，合計9268万円余りの賠償を求める訴訟が提起されております（以下「本件訴訟」といいます。）。

2020年8月21日に写真週刊誌FRIDAYに本件訴訟に関する記事が掲載されました（以下「本件記事」といいます。）。本件記事は「愛媛ご当地アイドル自殺事件　注目裁判の現在」とのタイトルで，本件訴訟の現状を紹介するものでした。

本件記事においては，遺族弁護団が2019年11月25日に「聴取報告書」と題する，当社の元マネージャーや元所属アイドルらから聞き取った供述を記載したとされる書面（本人の署名捺印がないもの）を裁判所に提出したのに対し，被告である当社が，同一の元マネージャー及び元所属アイドルらの署名捺印がある陳述書を提出したうえ，当該陳述書において，元マネージャー及び元所属アイドルらが，聴取報告書に記載されている内容を全否定するという「異常事態」が発生していることが記載されました。

そして，本件記事においては，当社が提出した陳述書の中で，元所属アイドルの橋川美紀さんが，遺族弁護団の一人から「月９のエキストラでもいいから出られるチャンスがあるんだよ。愛の葉Girlsも全国に行きたいんだよね」という話をされたと述べていることが記載されました。さらに，本件記事においては，この証言を裏付ける証拠として，遺族弁護団の一人である佐藤大和弁護士が，グループLINEに送信した「橋川さんの月９のエキストラ出演の件ですが，先方（フジテレビ）に伝えて前向きに検討して頂いております」とのメッセージの写真が掲載されました。

［source：］FRIDAYの記事と日本エンターテイナーライツ協会の釈明について http://ehime-hpro.com/index20200828.html
```

　さきほど，「日本エンターテイナーライツ協会」についてもまとめ記事を作成したのですが，これも乏しい内容でした。同じ記事を読んでも昨日は余りピンと来ていなかったのですが，8月21日に「写真週刊誌FRIDAYに本件訴訟に関する記事が掲載されました」とのことです。

 - 2018-11-04_162452＿テレビの画面・そこまで言って委員会NP【女性論客が委員会占拠！?男社会に物申す！！】　パワハラ・セクハラ　愛媛のご当地アイドル自殺.jpg  http://hirono2014sk.blogspot.com/2018/11/2018110420072018-11-041540532018-11.html#20181104162452

 - 2019-01-01-205436_望月宣武Hiromu MOCHIZUKIさんのツイート_ _愛媛アイドル自殺訴訟、第1回口頭弁論期日の日時と法廷が決まりました。ご支援よろしくお願いいたし_.jpg  http://hirono2014sk.blogspot.com/2019/01/2019010418152018-12-31-1223592019-01-04.html#20190101205436

 - 2019-01-08_212254＿テレビの画面・訳あり人の駆け込み寺～明日は我が身～・密着！法律事務所　愛媛の１６歳のアイドルが自殺した事件.jpg  http://hirono2014sk.blogspot.com/2019/01/2019010917332019-01-060020562019-01.html#20190108212254

 - 2019-02-18_142950＿テレビの画面・ミヤネ屋・裁判速報　愛媛１６歳アイドル自殺　主張対立　野村修也弁護士.jpg  http://hirono2014sk.blogspot.com/2019/03/2019030719392019-02-171011592019-02.html#20190218142950

 - 2019-04-24-235727_ystkさんがリツイート＞　望月宣武HiromuMOCHIZUKI（@166mochizuki）：　愛媛ご当地アイドル自殺訴訟の経過報告を公表しました。.jpg  http://hirono2014sk.blogspot.com/2019/05/2019050413492019-04-21-1905172019-04-30.html#20190424235727

 - 2018-10-15_122924＿テレビの画面・バイキング・ご当地アイドル”自殺”遺族が事務所を提訴　両者の間で食い違う主張.jpg  http://hirono2014sk.blogspot.com/2018/10/2018102012382018-10-120729412018-10.html#20181015122924

 - 2018-10-16_124332＿テレビの画面・バイキング・16歳ご当地アイドル自殺・・・背景に何が？　独自取材！ファン語る事務所との関係.jpg  http://hirono2014sk.blogspot.com/2018/10/2018102012502018-10-160339492018-10.html#20181016124332

　「2018-10-15_122924＿テレビの画面・バイキング・ご当地アイドル”自殺”遺族が事務所を提訴」と記録があるので，やがて2年という民事裁判になっているようです。昨日に読んだ記事の中でも，佐藤大和弁護士が陳述書の署名のことで3回，愛媛に足を運んでいるなどとありました。

　個人的に，報道された事実関係の範囲で，勝訴の見込みがあるとは思えない提訴だったのですが，弁護団として愛媛への交通費と時間の負担だけでも相当なものがありそうだと想像し，それでも経営を維持していける弁護士という稼業に凄まじいものを感じている次第です。

　無理がたたれば，社会的な信用も失い，場合によっては責任の追求もあって火だるまの業火モードに突入しそうです。今のところ反応は乏しいですが，嵐の前の静けさという言葉があるように，裁判の帰趨次第では，弁護士業界に嵐を巻き起こして来るのかもしれません。

 - 2020年09月09日10時24分の登録： REGEXP：”日本エンターテイナーライツ”／データベース登録済みツイート：2020年09月09日10時23分の記録：ユーザ・投稿：21／41件 http://hirono2014sk.blogspot.com/2020/09/regexp2020090910232141.html

 - 2020年09月09日10時24分の登録： REGEXP：”日本エンターテイナーライツ”／データベース登録済みツイートの検索：2020-09-08〜2020-09-09／2020年09月09日10時24分の記録：ユーザ・投稿：13／16件 http://hirono2014sk.blogspot.com/2020/09/regexp2020-09-082020-09_70.html

　逆に，このまま沈静化するようであれば，弁護士は後先考えずに気楽なやりたい放題が出来るという風潮を加速化しそうに思えます。かなり根拠が薄いと思われる話で，法外な請求（「合計9268万円余りの賠償を求める訴訟が提起」）という印象が当初より否めませんでした。

148件目 » 2018-10-11_175704＿テレビの画面・自殺　アイドルLINEに「ブン殴る」　遺族ら事務所のパワハラ訴え　望月宣武弁護士.jpg

[link:] 2018-10-11_175704＿テレビの画面・自殺　アイドルLINEに「ブン殴る」　遺族ら事務所のパワハラ訴え　望月宣武弁護士.jpg <http://hirono2014sk.blogspot.com/2018/10/2018101511092018-10-090006382018-10.html#20181011223941#20181011175704>

154件目 » 2018-10-11_175811＿テレビの画面・自殺　アイドルLINEに「ブン殴る」　遺族ら事務所のパワハラ訴え　河西邦剛弁護士.jpg

[link:] 2018-10-11_175811＿テレビの画面・自殺　アイドルLINEに「ブン殴る」　遺族ら事務所のパワハラ訴え　河西邦剛弁護士.jpg <http://hirono2014sk.blogspot.com/2018/10/2018101511092018-10-090006382018-10.html#20181011223941#20181011175811>

　NHKのテレビニュースを探しているのですが，今のところ見つかっていません。

 - 2019-02-20-235711_yuriさんのツイート：　”弁護士殺害２審　県にも賠償命令｜NHK　秋田県のニュース　　https：／／t。co／i4RnRgdfwy”.jpg  http://hirono2014sk.blogspot.com/2019/02/2019022112272019-02-10-1155022019-02-21.html#20190220235711

　どうも愛媛の農業アイドル自殺の問題は，NHKのニュースが見つかりそうもない感じです。

アイドル自殺　NHK　愛媛 - Google 検索 https://t.co/0DUWFW6In4

　Googleでもみつからない感じです。

FRIDAY　弁護士 - Google 検索 https://t.co/5dzUxJKdTg

FRIDAY　弁護士　愛媛 - Google 検索 https://t.co/FWKoBmOR65

愛媛ご当地アイドル自殺事件 注目裁判の現在 - Google 検索 https://t.co/OnMuG7PfaU

```
松山市を拠点にしたアイドルグループ「愛（え）の葉（は）Girls」のメンバーで、昨年3月に自殺した大本萌景（ほのか）さん（当時16歳）の遺族が、当時の所属会社「Hプロジェクト」によるパワハラや過酷な労働環境で精神的に追い詰められ、自殺したとして同社の佐々木貴浩・代表取締役らに計約9200万円の損害賠償を求めた民事訴訟は18日、東京地裁（三木素子裁判長）で第1回口頭弁論があった。代表取締役らは争う姿勢を示した。

　訴状によると、大本さんは2015年から同社に所属。イベントなどで平均して10時間以上拘束されたうえ、代表取締役から「辞めるのであれば1億円支払え」などの発言があり、昨年3月21日に自宅で自殺した、としている。遺族は昨年10月、松山地裁に提訴したが、双方の代理人が東京にいることなどから東京地裁に裁判が移された。

［source：］注目裁判・話題の会見：愛媛アイドル自殺初弁論　遺族側「辞めるなら1億円と言われた」、事務所側「社員とは兄妹のように親密」 - 毎日新聞 https://mainichi.jp/articles/20190218/k00/00m/040/297000c
```

　「遺族は昨年10月、松山地裁に提訴したが、双方の代理人が東京にいることなどから東京地裁に裁判が移された。」とあります。どちらに転んでも，弁護士の仕事になるのだと，弁護士のためにある裁判制度なのかと思わせるのに，象徴的です。

```
リーガルファンディングのホームページには、12月12日の時点で、369名が賛同して支援金を拠出、その金額が187万7777円に到達したことを告げている。

裁判を起こし、正当な権利を要求、金銭や謝罪を求めるにもカネが要る。「法の世界もカネ次第」であるのは、冷徹な事実である。そこに、「国民的共感」を背景に、法定費用を調達する手段が生まれるのは望ましく、意義も意味もある。

だが、その第一号が本件であるのは、話題性を優先させたものではないか、という感もある。実際、反響は大きく、hプロは公判が始まる前から猛烈なバッシングにさらされた。佐々木社長は、そこが納得いかない、という。

［source：］アイドル自殺事件で救済に立ち上がったリーガルファンディングとは何か（伊藤 博敏） | 現代ビジネス | 講談社（1/2） https://gendai.ismedia.jp/articles/-/58948
```

** 「アイドル自殺事件で救済に立ち上がったリーガルファンディングとは何か」という2018年12月23日付けの記事，「187万円集めた」とも，愛媛の農業アイドル自殺の問題

```
2020年09月09日11時50分の実行記録
twitterAPI-search-lawList-mydql-add.rb "リーガルファンディング"
ツイート数：4/1969 リツイート数：3/1969 トータル：273
hirono_hideki 1／2件
kk_hirono 3／0件
s_hirono 0／0件
```

```
(py37_env) a66@a66-XTe:~% dp -p|grep リーガルファンディング
 - 2019年03月19日10時16分の登録： ＼ノースライム・ピウス　@noooooooorth＼破産者等の情報を大量にインターネットで公開するサイト「破産者マップ」をなくしましょう。 | リーガルファンディング http://hirono2014sk.blogspot.com/2019/03/noooooooorth_19.html
 - 2019年08月29日22時17分の登録： ％@naotarou1981　とりなお％リーガルファンディングはまだ駆け出しだし，信頼で成り立っている（金が集まっている）部分もあるだろうから，理屈的にどうかっていう切り http://hirono2014sk.blogspot.com/2019/08/naotarou1981.html
 - 2019年11月02日13時36分の登録： ＼酒井将　@sakaisusumu_vb＼ベリーベスト法律事務所は、訴訟をしたいが活動資金が足りないという問題を抱えている被害者を募金で支援する、リーガルファンディングを http://hirono2014sk.blogspot.com/2019/11/sakaisusumuvb.html
```

```
(py37_env) a66@a66-XTe:~% ajx-all-user-mysql-REGEXP_blogger_hirono2014sk.rb "リーガルファンディング"
SELECT * FROM tw_user_tweet WHERE  tweet REGEXP "リーガルファンディング"   ORDER BY tw_date ASC
hirono_hideki
奉納＼さらば弁護士鉄道・泥棒神社の物語（hirono_hideki）
ユーザ名称：奉納＼さらば弁護士鉄道・泥棒神社の物語 [screen_name]ユーザ名：hirono_hideki フォロー数：4278 フォロワー数：4299 ツイート数：195944
noooooooorth
『信仰の』ノースライム（noooooooorth）
ユーザ名称：『信仰の』ノースライム [screen_name]ユーザ名：noooooooorth フォロー数：357 フォロワー数：19244 ツイート数：46396
kota_takagi
弁護士 高木 小太郎（kota_takagi）
ユーザ名称：弁護士 高木 小太郎 [screen_name]ユーザ名：kota_takagi フォロー数：299 フォロワー数：910 ツイート数：2100
keita_adachi
弁護士足立敬太 @アレクサ 六甲おろしかけて（keita_adachi）
ユーザ名称：弁護士足立敬太 @アレクサ 六甲おろしかけて [screen_name]ユーザ名：keita_adachi フォロー数：3330 フォロワー数：3639 ツイート数：212334
naotarou1981
とりなお（naotarou1981）
ユーザ名称：とりなお [screen_name]ユーザ名：naotarou1981 フォロー数：465 フォロワー数：1749 ツイート数：62129
gachinavi
ガチナビゾンビ＠負債５１０万（gachinavi）
ユーザ名称：ガチナビゾンビ＠負債５１０万 [screen_name]ユーザ名：gachinavi フォロー数：577 フォロワー数：579 ツイート数：44484
s_hirono
非常上告-最高検察庁御中_ツイッター（s_hirono）
ユーザ名称：非常上告-最高検察庁御中_ツイッター [screen_name]ユーザ名：s_hirono フォロー数：4 フォロワー数：81 ツイート数：73673
sakaisusumu_vb
酒井将（sakaisusumu_vb）
ユーザ名称：酒井将 [screen_name]ユーザ名：sakaisusumu_vb フォロー数：1834 フォロワー数：1459 ツイート数：315
kk_hirono
刑事告発・非常上告＿金沢地方検察庁御中（kk_hirono）
ユーザ名称：刑事告発・非常上告＿金沢地方検察庁御中 [screen_name]ユーザ名：kk_hirono フォロー数：491 フォロワー数：569 ツイート数：116399
PWyVw4xpW1SHM0I
村田連邦🙂（PWyVw4xpW1SHM0I）
ユーザ名称：村田連邦🙂 [screen_name]ユーザ名：PWyVw4xpW1SHM0I フォロー数：503 フォロワー数：395 ツイート数：17965
REGEXP：”リーガルファンディング”／データベース登録済みツイート：2020年09月09日11時51分の記録：ユーザ・投稿：10／18件
```

 - 2020年09月09日11時52分の登録： REGEXP：”リーガルファンディング”／データベース登録済みツイート：2020年09月09日11時51分の記録：ユーザ・投稿：10／18件 http://hirono2014sk.blogspot.com/2020/09/regexp2020090911511018.html

 - （01／18） RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜DuoSonic5190（☆かぱたん☆） 日時：2018-10-12 06:09:00 +0900／2018-10-11 11:15:00 +0900 URL： https://twitter.com/hirono_hideki/status/1050493617402339328 https://twitter.com/DuoSonic5190/status/1050208353928994816
石川県鳳珠郡能登町宇出津

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜166mochizuki（望月宣武 Hiromu MOCHIZUKI） 日時：2020-09-09 11:57／2018/10/03 23:23 URL： https://twitter.com/kk_hirono/status/1303527812788137984 https://twitter.com/166mochizuki/status/1047492279252840450  

> 子供を亡くした遺族の代理人を務めるのは3回目。感情振り回されるほどにもらい泣きするし、こちらも崩れそうになるけど、冷静に裁判で勝ち切るのが仕事。来週は2つの遺族事件で山場。何が何でも勝つ。勝つと決めた事件は勝つ。  

 - （05／18） TW keita_adachi（弁護士あだちけいた の子） 日時： 2019-08-08 16:03:00 +0900 URL： https://twitter.com/keita_adachi/status/1159359443118653440

> さすがにこういう実例をみると、リーガルファンディング、かなり危険だな。
> この事案も弁護士倫理上どうなんだろうという感がするし、某手続に発展しそう。 https://t.co/J25tHsGvsd

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜wjdpdptgda（たまご） 日時：2020-09-09 11:59／2019/08/08 08:39 URL： https://twitter.com/kk_hirono/status/1303528329526427648 https://twitter.com/wjdpdptgda/status/1159247697565458432  

> リーガルファンディングって凄いなぁ。  ・訴訟の当事者が自己の判断で訴えを取り下げることは「勝手」 ・取下げに支援者の許可も同意も必要ない ・全額返金する必要もない ・以上の内容を弁護士が胸を張って語る https://t.co/nZDDubR0Mi  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜wjdpdptgda（たまご） 日時：2020-09-09 11:59／2019/08/08 14:57 URL： https://twitter.com/kk_hirono/status/1303528510976192513 https://twitter.com/wjdpdptgda/status/1159342766574297088  

> 弁護士らしきアカウントが「こんなの当たり前なんだけど」とか引用RTで言ってたんだけど…  弁護士の間では当たり前でも、一般人からしたら勝手に訴え取り下げて、なのにお金だけ持っていかれたら納得いかないってことなのに。  そんな変な仕組みだと思われてるってことに気づかないんだろうか…  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜wjdpdptgda（たまご） 日時：2020-09-09 12:00／2019/08/08 17:05 URL： https://twitter.com/kk_hirono/status/1303528567259635712 https://twitter.com/wjdpdptgda/status/1159375117761126400  

> この人も「何が問題なのかサッパリ分からない」か… 望月弁護士といい、弁護士先生って支援者がどんな気持ちでこういった声を上げてるのかが全くわからない人が多いの…？ https://t.co/9r39t84N8w  

 - （06／18） TW naotarou1981（とりなお） 日時： 2019-08-08 16:20:00 +0900 URL： https://twitter.com/naotarou1981/status/1159363749897048064

> リーガルファンディングはまだ駆け出しだし，信頼で成り立っている（金が集まっている）部分もあるだろうから，理屈的にどうかっていう切り詰めた話だけではなくて周囲がどう見るかについてきちんと配慮しないと全体としてコケて今後の同業者に悪影響を与えかねないと思っている。

 - （07／18） TW keita_adachi（弁護士足立敬太 @アレクサ 六甲おろしかけて） 日時： 2019-08-08 16:44:00 +0900 URL： https://twitter.com/keita_adachi/status/1159369756077510656

> そんなの「勝手」と言い切ってしまうのは、リーガルファンディング黎明期でその対応は今後の目を摘み取りかねない気がします。一番大切な信用を失ってる感がします。 https://t.co/BpJdYXJpP1

 - （08／18） TW gachinavi（若手ガチナビ（商売の仕方模索中）） 日時： 2019-08-08 18:50:00 +0900 URL： https://twitter.com/gachinavi/status/1159401377040179204

> リーガルファンディングの件、そりゃ原告が訴えを取り下げるのは手続上は自由だけどさ、それを「当たり前だろ」って切り捨てるのはちょっとどうかと思う。余命の訴え下げで散々詐欺が疑われるとか言ってたのと何が違うのか、少なくとも運営者はちゃんと説明すべきなんじゃないの。

 - （12／18） RT PWyVw4xpW1SHM0I（村田連邦?）｜T233122006（T2） 日時：2020-09-08 16:02:00 +0900／2019-08-04 16:54:00 +0900 URL： https://twitter.com/PWyVw4xpW1SHM0I/status/1303227079484350464 https://twitter.com/T233122006/status/1157922860465131521
@166mochizuki 「支援者は金だけ出して黙ってろ」ということですか？ \n \n #リーガルファンディング \n #望月宣武 \n #大本萌景 https://t.co/tRpeIrG5SV

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜T233122006（T2） 日時：2020-09-09 12:04／2019/08/04 12:08 URL： https://twitter.com/kk_hirono/status/1303529571954827265 https://twitter.com/T233122006/status/1157850823658917888  

> @166mochizuki なぜ急に取り下げられたんですか？ 4月25日の報告を最後に、なにも報告をされてこなかったのに、急に取り下げになっており困惑しております。 支援者にも分かるように取り下げになられた経緯をご説明ください。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜T233122006（T2） 日時：2020-09-09 12:04／2019/08/04 16:54 URL： https://twitter.com/kk_hirono/status/1303529697339416576 https://twitter.com/T233122006/status/1157922860465131521  

> @166mochizuki 「支援者は金だけ出して黙ってろ」ということですか？  #リーガルファンディング #望月宣武 #大本萌景 https://t.co/tRpeIrG5SV  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜QNews24（news24） 日時：2020-09-09 12:05／2020/09/07 20:50 URL： https://twitter.com/kk_hirono/status/1303529970648530945 https://twitter.com/QNews24/status/1302937250255183872  

> @t_inaba135 問題が山積している裁判ですが、募金（リーガルファンディング）でやっているのに証拠なく訴え、不自然な取り下げ訴訟があり、後から証拠を出すために元メンバーたちに無理やり面会して証言取ろうとする、断られて聴取報告書にして当人に無断で提出って、書き出しますと結構恐ろしいです。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜dpawgtmgdpaw（ᒐƕ (普通浮上)） 日時：2020-09-09 12:06／2020/09/08 07:16 URL： https://twitter.com/kk_hirono/status/1303530143034437633 https://twitter.com/dpawgtmgdpaw/status/1303094759964041217  

> ４ 原告：前事務所 被告：遺族、芸能人の権利を守る日本エンターテイナーライツ協会、遺族代理人弁護士５名、一般社団法人リーガルファンディング 約3600万円の損害賠償請求 https://t.co/gZZIeoOjzV  (当然ながら)被害者不在の裁判。 果たして、自殺したアイドルの子の名誉を守ろうとしているのは？  

```
弊社は、本日付で下記の民事訴訟を東京地方裁判所に提起致します。

記

原告　Hプロジェクト株式会社及び佐々木貴浩

被告　大本萌景さんのご両親

芸能人の権利を守る日本エンターテイナーライツ協会

大本萌景さんのご両親の訴訟代理人弁護士５名

一般社団法人リーガルファンディング

弊社は、２０１８年１０月１２日に、大本萌景さんのご遺族から、大本萌景さんが自ら命を絶ったことについての全責任は、弊社、弊社代表取締役及び弊社従業員２名にあるとして突然提訴されました（この訴訟を第１訴訟といいます。）。

第１訴訟の提訴に際し、日本エンターテイナーライツ協会の共同代表理事であり、第１訴訟の原告訴訟代理人である５名の弁護士は東京及び松山で大々的な記者会見を行い、うちの１名の弁護士は、ご遺族と共に自らテレビ出演を行うなど、通常では考えられない大規模な広報活動が行われました。

記者会見においては、弊社代表取締役が、大本萌景さんに「１億円支払え」と脅迫したり、大本萌景さんにほとんど休みを取らせることもなく、午前４時３０分から午前２時まで働かせるといった過重労働を強いたり、弊社従業員が大本萌景さんに暴力的なパワーハラスメントを行っていたかのような発言が行われ、これらは事実無根であるにもかかわらず、あたかも真実であるかのように世間に流布されてしまいました 。

その結果、弊社、弊社代表取締役及び弊社従業員やその家族は、ＳＮＳ等を通じた苛烈かつ大量の攻撃を受けることになりました。弊社には、嫌がらせで刃物が送付されてくることすらあり、関係者らは身の危険を感じながら日々を過ごさなければなりませんでした。

また、弊社は農業振興を目的とする会社であり、自社での野菜の栽培・販売や農業振興・町おこしに関する催事等を本業として おりましたが、「１６歳のアイドルを過重労働、パワハラ、１億円発言により自殺に追い込んだ悪徳芸能事務所」というレッテルを貼られそのような会社から野菜を購入することはできないと言われ、多くの取引先を失いました。

弊社は、大本萌景さんの死を悼み、アイドルとして輝いていた彼女の尊厳を守りたいという思いから、多くを発信せずに耐えておりましたが、このような謂れのない訴えと、メディアを最大限に利用した一方的な広報活動により、事実無根の悪評を拡散され、人生が変わり果ててしまう者が、今後二度と現れてはならないと考え、本日の提訴に至りました。

［source：］ｈプロジェクト株式会社 http://ehime-hpro.com/index20191011.html
```

　2019年10月11日付となっていますが，被告に，大本萌景さんのご両親，芸能人の権利を守る日本エンターテイナーライツ協会，大本萌景さんのご両親の訴訟代理人弁護士５名，一般社団法人リーガルファンディング，とあります。

　訴訟代理人弁護士５名，という弁護士が気になりますが，確実視されるのが山口貴士弁護士と望月宣武弁護士で，テレビの報道をみたところ他に可能性のあるのが，向原栄大朗弁護士と河西邦剛弁護士になるかと思います。

　ホームページで，共同代表に5人の弁護士の名前があって，1つ抜けがあったのが安井飛鳥弁護士でした。昨日か今日も少し名前を見かけていましたが，そういえばという気がしますた。先日，ブロックされていることを記述したときは，頭なかった事実関係ではあります。

** 日本エンターテイナーライツ協会，共同代表理事，望月宣武弁護士，向原栄大朗弁護士,安井飛鳥弁護士,河西邦剛弁護士,佐藤大和弁護士の5名と確認

:CATEGORIES: 望月宣武弁護士，向原栄大朗弁護士,安井飛鳥弁護士,河西邦剛弁護士,佐藤大和弁護士

```
名称
「芸能人の権利を守る　日本エンターテイナーライツ協会」
所在地
東京都文京区音羽2-2-2　アベニュー音羽ビル2階（レイ法律事務所内）
広報窓口
レイ法律事務所　佐藤大和
共同代表理事
望月宣武（日本羅針盤法律事務所、弁護士、東京弁護士会所属）　
向原栄大朗（向原総合法律事務所、弁護士、福岡県弁護士会所属）
安井飛鳥（法律事務所くらふと、弁護士、社会福祉士、精神保健福祉士、千葉県弁護士会所属）
河西邦剛（レイ法律事務所、弁護士、東京弁護士会所属）
佐藤大和（レイ法律事務所、弁護士、東京弁護士会所属）
理事
田畑淳（溝の口法律事務所、弁護士、神奈川県弁護士会所属）
中村剛（中村総合法律事務所、弁護士、東京弁護士会）
高田沙代子（ケレス法律事務所、弁護士、東京弁護士会）
パートナー
しほり（音楽家、株式会社メディック・アーツ代表取締役）
今野悠夫（俳優、俳優互助団体０９代表）
桑原みずき（女優、ダンサー、ツルノヒトコエ）

［source：］芸能人の権利を守る 日本エンターテイナーライツ協会 https://era-japan.org/#desc5
```

　今回，意外に感じたのは，「田畑淳（溝の口法律事務所、弁護士、神奈川県弁護士会所属）」と「中村剛（中村総合法律事務所、弁護士、東京弁護士会）」の名前です。田畑淳弁護士は，深澤諭史弁護士,野田隼人弁護士らとの共著もありました。

　「高田沙代子（ケレス法律事務所、弁護士、東京弁護士会）」は見たことのない名前ですが，匿名でTwitterをやっている可能性などありそうな気がしました。

 - 高田沙代子弁護士。民事裁判の記者会見なのに被告を「刑事の犯罪者」扱い？ビハイア裁判。 - 元ビハイアの大山莉加さんから遺言の公開してほしいと依頼されたので公開します https://niwareiko207.blog.fc2.com/blog-entry-352.html  

　高田沙代子を右クリックで検索したところ，意外な情報が出てきました。

** Twilogで，2017年3月1日のリツイートが1件しか出てこなかった，日本エンターテイナーライツの理事，高田沙代子弁護士

:CATEGORIES: 高田沙代子弁護士

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「高田沙代子」の検索結果 - Twilog https://t.co/y6Rbgxzi2V

- RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜CEEKJPNEWS（CEEK.JP NEWSbot/test） 日時：2017/03/01 11:27／2017/02/28 21:48 URL： https://twitter.com/hirono_hideki/status/836764841368944643 https://twitter.com/CEEKJPNEWS/status/836558725779337218

> RT @CEEKJPNEWS: [社会] 「たった14年後に犯人が塀の外に」小金井刺傷の被害者 （朝日新聞）: 判決後、記者会見で冨田真由さんの思いを述べる代理人の柴田崇弁護士（左）と高田沙代子弁護士＝東京都立川市 [PR]… https://t.co/Tbc9XNU2eZ  

```
　判決後、記者会見した冨田さんの代理人弁護士によると、冨田さんはこの日は出廷せず、控室で判決内容を聞いた。「（求刑の）１７年でも短いと思っていたのに」とだけ言い、沈黙したという。

［source：］「たった１４年後に犯人が塀の外に」小金井刺傷の被害者：朝日新聞デジタル https://www.asahi.com/articles/ASK2X6QBCK2XUTIL01C.html?utm_source=dlvr.it&utm_medium=twitter
```

```
判決後、記者会見で冨田真由さんの思いを述べる代理人の柴田崇弁護士（左）と高田沙代子弁護士＝東京都立川市

［source：］「たった１４年後に犯人が塀の外に」小金井刺傷の被害者：朝日新聞デジタル https://www.asahi.com/articles/ASK2X6QBCK2XUTIL01C.html?utm_source=dlvr.it&utm_medium=twitter
```

```
また、プレゼントを返すのが遅れたことを岩崎被告が動機としたことに触れ、「当時の事務所に『返してほしい』と預けたのに返してもらえなかった。残念でなりません」とコメント。「通報した方や精神科の先生が証人として話してくれ、皆さんの必死な思いで助けていただいたと改めて感じさせられた。本当にありがとうございました」と感謝の思いも記した。

［source：］「たった１４年後に犯人が塀の外に」小金井刺傷の被害者：朝日新聞デジタル https://www.asahi.com/articles/ASK2X6QBCK2XUTIL01C.html?utm_source=dlvr.it&utm_medium=twitter
```

　記事に掲載された写真に，「判決後、記者会見で冨田真由さんの思いを述べる代理人の柴田崇弁護士（左）と高田沙代子弁護士＝東京都立川市」とありますが，柴田崇弁護士の方が印象に残っていた感じです。こちらもTwilogで確認してみます。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-09 14:02／2017/03/01 15:26 URL： https://twitter.com/kk_hirono/status/1303559292004360198 https://twitter.com/hirono_hideki/status/836824849540595712  

> 冨田さんの代理人をつとめる柴田崇弁護士が12月16日、東京・霞が関の司法記者クラブで記者会見を開いた。 https://t.co/Rml6aQ6HJV  

　判決後、記者会見で冨田真由さんの思いを述べる代理人の柴田崇弁護士（左）と高田沙代子弁護士＝東京都立川市

　記事に掲載された写真に，「判決後、記者会見で冨田真由さんの思いを述べる代理人の柴田崇弁護士（左）と高田沙代子弁護士＝東京都立川市」とありますが，柴田崇弁護士の方が印象に残っていた感じです。こちらもTwilogで確認してみます。

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「柴田崇弁護士」の検索結果 - Twilog https://t.co/fbY8S3av1j

　前に，崇という名前が気になって調べたことがありました。NHKの平将門の大河ドラマで見ていた俳優の名前がずっと印象に残っていたのですが，たしか山口崇という名前の俳優でした。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-09 14:05／2017/03/01 10:48 URL： https://twitter.com/kk_hirono/status/1303560079854063617 https://twitter.com/hirono_hideki/status/836754910079246336  

> 山口崇 - Wikipedia https://t.co/ah7GKaXa9i  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-09 14:05／2018/03/09 19:23 URL： https://twitter.com/kk_hirono/status/1303560111864963072 https://twitter.com/hirono_hideki/status/972055309979074561  

> 風と雲と虹と - Wikipedia https://t.co/LcDYJCBMzP 平太郎貞盛[6] （左衛門少志→左兵衛少尉兼検非違使尉→左馬大允）：山口崇  昭和５１年の放送とあるので、中学生ではなく小学校６年生だったと確認。火の用心をやっていた頃。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-09 14:05／2018/03/09 19:28 URL： https://twitter.com/kk_hirono/status/1303560153053052928 https://twitter.com/hirono_hideki/status/972056613593886720  

> 山口崇 - Wikipedia https://t.co/ufh44tco9Y なんとなく故人のイメージだったが、８１歳でご健在という情報。テレビドラマは２０１３年が最新の出演らしい。白い巨塔の俳優とイメージが似ていたと記憶に残っているが、ぼんやりとした記憶。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-09 14:05／2018/03/09 19:33 URL： https://twitter.com/kk_hirono/status/1303560198267699201 https://twitter.com/hirono_hideki/status/972057852931002369  

> 俳優　山口崇 - Google 検索 https://t.co/8JgUUmBYy8 大岡越前のキーワードと写真。大岡越前は平将門と同じ加藤剛だったので、共演していたらしい。  

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「山口崇」の検索結果 - Twilog https://t.co/UsbGCaTAYz

　柴田崇弁護士の名前があるツイートと同じ2017年3月1日に，「山口崇 - Wikipedia http://ow.ly/g4ak309ssTB 」というツイートがありました。崇という名前が気になったこともあり，高田沙代子弁護士については調べることもなく，本日まで名前を気にすることもなかったようです。

　崇という名前は，そう珍しくないと思いますが，「祟（たたり）」との違いが気になりました。微妙に異なる漢字だと思っていたのですが，今，日本語変換をしてみたところ，同じ漢字のようです。

 - 崇 | 漢字一字 | 漢字ペディア https://www.kanjipedia.jp/kanji/0003778700  

　あまり見かけないと思いますが，「崇める」という漢字の読み方もあるようです。崇敬というのは，氏子崇敬者や氏子崇拝者として見ることがあると思いますが，同じ漢字とは考えていませんでした。ただ，上記のページに「たたり」という読み方は見当たりません。

 - 「祟」と「崇」　似て非なる字｜ライフコラム｜NIKKEI STYLE https://style.nikkei.com/article/DGXZZO06311920V20C10A4000000/  

　祟り，は崇と微妙に漢字が違っているようです。記憶どおりになりますが，出るに示すを重ねて祟りというのは，新発見のように思えてきました。

```
祟り(たたり)とは、神仏や霊魂などの超自然的存在が人間に災いを与えること、また、その時に働く力そのものをいう。人間社会の法則や論理では制御不能な出来事が起こった際に、それを強大な霊力の発現であると考える解釈・説明［1］。


月岡芳年「不知藪八幡之実怪」。迷い込んだ水戸黄門（右）の前に老人の妖怪があらわれる
類似の概念として呪(のろ)いがある。祟りは神仏・妖怪による懲罰など、災いの発生が何らかの形で予見できたか、あるいは発生後に「起こっても仕方がない」と考えうる場合にいう（「無理が祟って」などの表現もこの範疇である）。これに対し呪いは、何らかの主体による「呪う」行為によって成立するものであり、発生を予見できるとは限らない。何者かに「呪われ」た結果であり、かつそうなることが予見できたというケースはあり得るので、両概念の意味する範囲は一部重なるといえる。

［source：］祟り - Wikipedia https://ja.wikipedia.org/wiki/%E7%A5%9F%E3%82%8A
```

　調べてみると，意外なことに祟りと呪いの違いが出てきました。高田沙代子弁護士と柴田崇弁護士が関与をしたという小金井ストーカー事件も並外れた情念が感じられた事件になりますが，一時は心肺停止という報道があったと記憶にあり，回復が奇跡のような事件でした。

　個人的に小金井ストーカー事件は，弁護士の救いなき攻撃性を強く感じた事件の１つでもありました。

```
日本の神は本来、祟るものであり、タタリの語は神の顕現を表す「立ち有り（タツとアリの複合形）」が転訛したものという折口信夫の主張が定説となっている［1］。流行り病い、飢饉、天災、その他の災厄そのものが神の顕現であり、それを畏れ鎮めて封印し、祀り上げたものが神社祭祀の始まりとの説が

［source：］祟り - Wikipedia https://ja.wikipedia.org/wiki/%E7%A5%9F%E3%82%8A
```

　折口信夫は有名な民俗学者で，これまでにも度々名前を見かけてきましたが，余りよく知らない人物でもあります。

```
柳田が民俗現象を比較検討することによって合理的説明をつけ、日本文化の起源に遡ろうとした帰納的傾向を所持していたのに対し、折口はあらかじめマレビトやヨリシロという独創的概念に日本文化の起源があると想定し、そこから諸現象を説明しようとした演繹的な性格を持っていたとされる。なお『遠野物語』に折口の跋文がある（現：角川ソフィア文庫）。

［source：］折口信夫 - Wikipedia https://ja.wikipedia.org/wiki/%E6%8A%98%E5%8F%A3%E4%BF%A1%E5%A4%AB
```

```
1925年5月処女歌集『海やまのあひだ』を刊行。1927年6月國學院の学生らを伴い能登半島に採訪旅行し、藤井春洋の生家を訪う。1928年4月慶應義塾大学文学部教授となり芸能史を開講する。

［source：］折口信夫 - Wikipedia https://ja.wikipedia.org/wiki/%E6%8A%98%E5%8F%A3%E4%BF%A1%E5%A4%AB
```

```
石川県羽咋郡一ノ宮村（現在の羽咋市）に藤井升義の四男として生まれる。生家は漢方の眼薬を伝える古い家柄であった。

石川県立金沢第一中学校（現・石川県立金沢泉丘高等学校）を経て、1925年、國學院大學予科に入学し、折口信夫に師事。折口主宰の短歌結社「鳥船社」に入り、新派短歌を作る。1928年、同性愛者であった折口と同居開始。実質的な愛人としてである。

［source：］折口春洋 - Wikipedia https://ja.wikipedia.org/wiki/%E6%8A%98%E5%8F%A3%E6%98%A5%E6%B4%8B
```

　折口信夫が同性愛者だったというのも知らなかったですが，おそらくは大正から昭和の初めの時代の日本にも同性愛者はいたということを初めて知ったように思います。

　初めて名前を知る人物と思いますが，石川県羽咋郡一ノ宮村とあるのは，能登一ノ宮ともいわれる気多大社の場所になると思います。

奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: REGEXP：”小金井ストーカー”／データベース登録済みツイート：2020年09月09日14時26分の記録：ユーザ・投稿：22／36件 https://t.co/H09RkGlmrD

 - （25／36） TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2018-03-09 19:19:00 +0900 URL： https://twitter.com/hirono_hideki/status/972054243354886145

> @amneris84 崇という漢字を調べたのは、この小金井ストーカー事件に関与した新発田崇弁護士だったらしい。「たたり」と読むとは思わなかった。中学生の頃、平将門のNHK大河ドラマがあって、平貞盛役の俳優の名前が、同じ漢字だった。平将門が怨霊のイメージが強いので、その辺りも含め。

　ちょっと勘違いしたのですが，次のジャーナリストの江川紹子氏のツイートへの私の返信ツイートだったようです。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜amneris84（Shoko Egawa） 日時：2020-09-09 14:56／2017/03/01 10:09 URL： https://twitter.com/kk_hirono/status/1303572923769257984 https://twitter.com/amneris84/status/836745101674065921  

> 毎日新聞は、小金井市のストーカーによる殺未事件の判決を、被害者の視点のみで伝える。なぜ、代理人の写真をこんなに大きく載せるのか不明。被害者の発言を伝えるのはいいが、司法を被害者感情だけで評価するよう誘導している紙面作りはいただけない。 https://t.co/GNMAzglr3y  

　新聞紙の折り目もあると思いますが，高田沙代子弁護士がけっこう怖い感じの写真になっているジャーナリストの江川紹子氏のツイートの新聞紙の写真になります。

　昨夜になるのか，深澤諭史弁護士のタイムラインがきっかけで，久しぶりに恐怖新聞をもじった弁護士による他の弁護士を社会風刺した挿絵の再発見になりました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 15:03／2020/09/09 15:01 URL： https://twitter.com/kk_hirono/status/1303574614564458496 https://twitter.com/s_hirono/status/1303574121331081216  

> 2020-09-09-145843_Shoko　Egawa@amneris84毎日新聞は、小金井市のストーカーによる殺未事件の判決を、被害者の視点のみで伝える。なぜ、代理人の写.jpg https://t.co/9mgKWkSpvQ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 15:03／2020/09/09 00:22 URL： https://twitter.com/kk_hirono/status/1303574736895574016 https://twitter.com/s_hirono/status/1303353086962839553  

> 2020-09-08-211405_WebLOG弁護士中村真　アナタに届け、ボクの上告理由.jpg https://t.co/hildCzYrPh  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 15:03／2020/09/09 00:22 URL： https://twitter.com/kk_hirono/status/1303574766935183360 https://twitter.com/s_hirono/status/1303353013994622976  

> 2020-09-08-211156_深澤諭史@fukazawas·2時間【副会長日記】「ああああ」弁護士会　.jpg https://t.co/MSX7BqJQln  

　弁護士による社会現象という意味で共通性もあるように思います。本当に被害者の利益になっているのかも疑問で，さらなる不幸せに弁護士鉄道の牽引するレールは向かっているようにも思えてなりません。愛媛の農業アイドル自殺の問題もしかりで，弁護士鉄道の燃料にされているかに思えます。

```
送達場所の上申をしていないどころか
事件に全く関与していないのに
いきなり上告理由書が送られてくるというのは
正直あまりない経験です。
とりあえずタダでもらえてトクしたって
喜んでいいんだよね？

私に送られてきたということから見て
おそらく、日本の司法制度と民主政治を牽引する役割を担える
ごく限られた優秀な弁護士や
それに類する法曹関係者にだけ送られていることは間違いありません。
（うちの所属弁護士は全員
「ごく限られた優秀な弁護士」と認めて頂けたようです。）

書面の所々に超弩級巨大フォントでの強調（「無効」や「大発見」など）があったり、
色分け、傍線＆傍点や数種類のカッコが多用されてたりという
ひときわ変わった体裁だったので、
驚いた弁護士の方も多かったようです。
しかし、余り知られてないことですが、
これこそが上告事件での最高裁指定の書式なんですよね。
（わからないけど、たぶんそんな気がします。）

超弩級巨大フォントを使うことにより、
その単語だけが頭にすり込まれ、
その間の文章や全体の文意はほとんど記憶に残らないという
本当によく考えられた文章だと思いました。


ところが、気になったのがその送付のコスト。


私クラスの「ごく限られた優秀な弁護士」はさほど多くありません。
（全国で2万8000人くらい？）
でもその数分だけこれだけきれいに印刷した書面を
送付書を付けて送りつけるというのは
膨大な手間と費用がかかるのではないでしょうか。
（よく見たらそこそこいい紙使ってたので、
ウラ紙にしようとしたら、残念、両面印刷でした。）
一説によると、裁判官にも送られているとか。
太っ腹！

しかも、送付書には送付先の弁護士個人名（差し込み印刷？）と
送付して頂いた先生の職印での押印つき。
この送付作業だけでアジアに工場を一つ作ってもいいくらい。
といったら言い過ぎか。
（ほら僕ってば昔からちょっと大げさなとこあるじゃない？）


結局、上告理由書(抜粋)を送って頂いた趣旨は
よくわからなかったのですが、
豊富な資金力を持った弁護士が
花の都大東京にいるらしいということはよくわかりました。

［source：］WebLOG弁護士中村真　アナタに届け、ボクの上告理由 http://nakamuramakoto.blog112.fc2.com/blog-entry-226.html
```

```
選挙区ごとの選挙民と定数配分が均衡を失していると
一票の価値に差が出てしまい、
これが２倍以上になると
「実質、複数投票制を認めたのと同じ」になるから
「1：2未満の格差のみが憲法上許容されると解すべき」
って書かないといけないよって
受験時代にナントカ塾の教材で習った記憶があるよ。

そういえば、
伊藤真弁護士も「一票の格差」弁護団の一人なんだよね。
まぁ、この法曹界で輝ける「真」は
俺一人でも別にいいんだけどね。

受験時代は（教材使ってたクセに）「アンチイトマコ」を気取ってて、
そのくせ浦安の口述会場で生イトマコに出会ったときには
駆け寄って握手したのは本当にいい思い出。



そういえば、「一票の格差」弁護団には
他にも超ビッグネームの先生が参加されていたような…。

［source：］WebLOG弁護士中村真　アナタに届け、ボクの上告理由 http://nakamuramakoto.blog112.fc2.com/blog-entry-226.html
```

　これまでに何度か繰り返し読んでいる記事ですが，伊藤真弁護士の名前が出てきて，ちょっと意外でした。漫画のような漫画以上の成功者が，伊藤真弁護士であったり，久保利英明弁護士というイメージも強いです。現実問題として外せない弁護士鉄道の歴史と未来といえるでしょう。

　漫画に二人の会話があって，背後に久保利英明弁護士らしい人物の姿があり，会話に「そういえば，こないだ新幹線で読んだビジネス雑誌で，どこかの弁護士が「弁護士を十万人まで増やさんならん」て書いてましてな。」とあります。皮肉というか風刺なのでしょう。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 15:16／2020/09/09 15:16 URL： https://twitter.com/kk_hirono/status/1303578090589700096 https://twitter.com/s_hirono/status/1303577943302533122  

> 2020-09-09-151302_伊藤真弁護士も「一票の格差」弁護団の一人なんだよね。まぁ、この法曹界で輝ける「真」は俺一人でも別にいいんだけどね。受験時代は（教材使ってたク.jpg https://t.co/vallWfmzeY  

 - 東京銀座の女性弁護士事務所 | ケレス法律事務所 (企業法務, 一般民事, 不良債権回収, 犯罪被害者支援) http://www.ceres-law.com/  

　さきほどジャーナリストの江川紹子氏のツイートの新聞記事とは別人のような高田沙代子弁護士の腰の辺りから上の顔写真があります。服装もじつに清潔な感じです。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 15:27／2020/09/09 15:24 URL： https://twitter.com/kk_hirono/status/1303580679276392448 https://twitter.com/s_hirono/status/1303580015171305472  

> 2020-09-09-152405_代表弁護士　高田沙代子　（TAKADA　SAYOKO）所属　東京弁護士会出身地　神奈川県横浜市.jpg https://t.co/1M7bslONLR  

　さきほども東京銀座の法律という情報は見かけていたのですが，このホームページをみると所属の弁護士は高田沙代子弁護士，お一人のようです。よほど実力や甲斐性がなければ，維持のできない経営とも想像されます。

```
2020年4月14日付官報でレアーナ法律事務所の玉里友香弁護士（第一東京）の懲戒処分の公告がありました。

登録番号39962とまだベテランとも言えない女性弁護士が初めての懲戒処分が業務停止2月、こういう処分はあまりありません。正確な処分内容は日弁連広報誌「自由と正義」8月号までお待ちください、推測ではいえませんが、だいたいアレでしょう。

［source：］「レアーナ」(玉里友香弁護士）「ケレス」「ウラノス」！？ワンフロアに３つの法律事務所、どういう意味があるのか？ – 弁護士自治を考える会 https://jlfmt.com/2020/04/15/42042/
```

　Googleでケレスを調べると，準惑星と出てきました。ローマ神話やギリシア神話のイメージがあったのですが，それらしい情報もかいまみれます。

```
玉里弁護士は、上記のように業務外では派手な活躍をなさっている中で、非弁提携の噂が絶えない弁護士であった。筆者に寄せられている情報では、非弁ＮＰＯ関係者や特殊詐欺の返金とか、情報商材の購入代金の返金などの依頼者を弁護士に送り込む「送り屋」と深い接点があり、実質的に「名義貸し」を行っているとの内容であった。今回の懲戒処分の内容は現時点ではわからないが、初回の懲戒処分で業務停止を受けるという事は相当な問題であったであろうことは想像に難くない。

この玉里弁護士の現在の登録先は以下のとおりである。

［source：］よくも悪くも有名な玉里友香弁護士（第一東京）に業務停止２月の懲戒処分　ところで銀座の事務所には３つの法律事務所が存在していますが、これはどういう事なんですかね？ – 鎌倉九郎 https://kamakurasite.com/2020/04/15/%E3%82%88%E3%81%8F%E3%82%82%E6%82%AA%E3%81%8F%E3%82%82%E6%9C%89%E5%90%8D%E3%81%AA%E7%8E%89%E4%BA%95%E5%8F%8B%E9%A6%99%E5%BC%81%E8%AD%B7%E5%A3%AB%EF%BC%88%E7%AC%AC%E4%B8%80%E6%9D%B1%E4%BA%AC%EF%BC%89/
```

　「非弁ＮＰＯ関係者や特殊詐欺の返金とか、情報商材の購入代金の返金などの依頼者を弁護士に送り込む「送り屋」と深い接点があり、実質的に「名義貸し」を行っているとの内容であった。」とありますが，「送り屋」というのは，当たり屋にも似た語感があります。

```
この３名の弁護士が一緒に業務をやっているとは断定できないが、レアーナはともかくとしてウラノスとケレスはギリシャ・ローマ神話の神々の名前で天体の名前でもあることから、何らかの関係性はあるのであろうと思われる。

［source：］よくも悪くも有名な玉里友香弁護士（第一東京）に業務停止２月の懲戒処分　ところで銀座の事務所には３つの法律事務所が存在していますが、これはどういう事なんですかね？ – 鎌倉九郎 https://kamakurasite.com/2020/04/15/%E3%82%88%E3%81%8F%E3%82%82%E6%82%AA%E3%81%8F%E3%82%82%E6%9C%89%E5%90%8D%E3%81%AA%E7%8E%89%E4%BA%95%E5%8F%8B%E9%A6%99%E5%BC%81%E8%AD%B7%E5%A3%AB%EF%BC%88%E7%AC%AC%E4%B8%80%E6%9D%B1%E4%BA%AC%EF%BC%89/
```

　「レアーナはともかくとしてウラノスとケレスはギリシャ・ローマ神話の神々の名前で天体の名前でもあることから、何らかの関係性はあるのであろうと思われる。」とあります。ウラノスはまだ調べていなかったのですが，レアーナは，花王のシャンプーの情報ばかりでした。

 - 玉里友香 - 唐澤貴洋Wiki https://krsw-wiki.org/wiki/%E7%8E%89%E9%87%8C%E5%8F%8B%E9%A6%99  

　弁護士に限らず名前はどこかでみたように思っていたのですが，掲載されている顔写真は初めて目にするもので，まるで弁護士ドラマの女優そのものか，それをしのぐ非現実的存在感を感じました。

　玉里友香という名前はTwilogにありませんでした。初めての発見となる弁護士のようです。

** 初めて知ったと思われる玉里友香弁護士，東京銀座のフロアにレアーナ法律事務所，高田沙代子弁護士のケレス法律事務所，まだ調べていないウラノス法律事務所があるという，ケレスは準惑星とも

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「玉里友香」の検索結果 - Twilog https://t.co/sO2RfHeolC ツイートが見つかりませんでした

ウラノス法律事務所の退職代行サービスの特徴と費用をご紹介 | JobReset｜退職代行紹介メディア https://t.co/OntIooXjC6 名称ウラノス法律事務所 \n 弁護士藤崎雅弘 \n 所属弁護士会第一東京弁護士会　登録番号　48146

ウラノス法律事務所の退職代行サービスの特徴と費用をご紹介 | JobReset｜退職代行紹介メディア https://t.co/OntIooXjC6

　先にウラノス法律事務所を調べたところ，退職代行と男性弁護士の名前と顔写真が出てきて，同じ名前の法律事務所があるのかと思ったのですが，別に見つけた情報によると，三人の女性弁護士というのは私の早とちりで，一人は男性弁護士だったようです。名前も同じでした。

```
ウラノス

《天の意》ギリシャ神話で、世界の最初の支配者。女神ガイアの夫。神々の祖で、ゼウスの祖父。テミスはギリシャ神話で、法の女神。ウラノスとガイアの娘で、ゼウスの二度目の妻。

 

ガイヤ法律事務所、テミス(法を司る神）法律事務所はこのギリシャ神話からいただいたのでしょう。

ケレス

ケレース（Ceres）は、ローマ神話に登場する豊穣神、地母神、地下神。長母音を省略してケレスとも表記される。英語表記ではシリーズ、シアリーズとも呼称される。

 

ケレスもギリシャ神話からのようです。

 

レアーナ

いろいろネットで検索したがシャンプーの名称とか石鹸のたぐいしか出てこない。玉里友香弁護士は過去ビューテイ・メダリストだということで、美容関係の名前にしたのか？それとも石鹸の業界の顧問でもしたことでもあるのか？

［source：］「レアーナ」(玉里友香弁護士）「ケレス」「ウラノス」！？ワンフロアに３つの法律事務所、どういう意味があるのか？ – 弁護士自治を考える会 https://jlfmt.com/2020/04/15/42042/
```

　ゼウスという神の名前は，昭和50年代によく見かけていたと記憶にあるのですが，ウラノスはゼウスの祖父で，「テミスはギリシャ神話で、法の女神。ウラノスとガイアの娘で、ゼウスの二度目の妻。」とあります。

　テミスは裁判所にある女神像として名前を聞きますが，平成7年から平成9年頃には別の名前の女神として名前をよく見かけていたと思います。ちょっと思い出せないですが，Googleで検索すればすぐに見つかる情報と思います。

```
ユースティティア (Jūstitia あるいは Iūstitia［1］) とは、ローマ神話に登場する女神［2］。

名前はラテン語で「正義」を意味し、英語ではジャスティス (Lady Justice) と知られる［3］。英語で正義を意味する「Justice」はユースティティアが語源である［4］。

正義の女神であることから、裁判所などでは、天秤と剣を手にし目隠しをしたユースティティア（あるいはテミス）の像 (Statue of Lady Justice または Statue of Jusctice) を飾る習慣がある［3］。ユースティティアの像は日本の最高裁判所にもある［5］。ただし最高裁判所など目隠しされていないものもある。

ギリシア神話のホーラ（ホーライ）の一人ディケーや、その母で掟の女神であるテミスと同一視される［6］。また、アストライアーとも同一視され、おとめ座の女神とされる。

［source：］ユースティティア - Wikipedia https://ja.wikipedia.org/wiki/%E3%83%A6%E3%83%BC%E3%82%B9%E3%83%86%E3%82%A3%E3%83%86%E3%82%A3%E3%82%A2
```

　英語のジャスティスの語源がユースティティアにあるというのは初めて知ったように思います。名前がまったく違う気がするのですが，テミスと同一視されるとあります。　

泥棒　神様 - Google 検索 https://t.co/3ASCIUfGPV

```
ヘルメースは早朝に生まれ、昼にゆりかごから抜け出すと、まもなくアポローンの飼っていた雄牛50頭を盗んだ［1］。ヘルメースは自身の足跡を偽装し、さらに証拠の品を燃やして雄牛たちを後ろ向きに歩かせ、牛舎から出た形跡をなくしてしまった［1］。翌日、牛たちがいないことに気付いたアポローンは不思議な足跡に戸惑うが、占いによりヘルメースが犯人だと知る［3］。激怒したアポローンはヘルメースを見つけ、牛を返すように迫るが、ヘルメースは「生まれたばかりの自分にできる訳がない」とうそぶき、ゼウスの前に引き立てられても「嘘のつき方も知らない」と言った［1］。それを見たゼウスはヘルメースに泥棒と嘘の才能があることを見抜き、ヘルメースに対してアポローンに牛を返すように勧めた［1］。ヘルメースは牛を返すがアポローンは納得いかず、ヘルメースは生まれた直後（牛を盗んだ帰りとも）に洞穴で捕らえた亀の甲羅に羊の腸を張って作った竪琴を奏でた［1］。それが欲しくなったアポローンは牛と竪琴を交換してヘルメースを許し、さらにヘルメースが葦笛をこしらえると、アポローンは友好の証として自身の持つケーリュケイオンの杖をヘルメースに贈った（牛はヘルメースが全て殺したため、交換したのはケーリュケイオンだけとする説も。なお、殺した牛の腸を竪琴の材料に使ったとも）［1］。このときアポローンとお互いに必要な物を交換したことからヘルメースは商売の神と呼ばれ、生まれた直後に各地を飛び回ったことから旅の神にもなった。

ヘルメースはヘーラーの息子ではなかったが、アレースと入れ替わってその母乳を飲んでいたため、ヘーラーはそれが分かった後もヘルメースに対して情が移り、彼を我が子同然に可愛がった［1］。

［source：］ヘルメース - Wikipedia https://ja.wikipedia.org/wiki/%E3%83%98%E3%83%AB%E3%83%A1%E3%83%BC%E3%82%B9
```

　「ヘルメースは早朝に生まれ、昼にゆりかごから抜け出すと、まもなくアポローンの飼っていた雄牛50頭を盗んだ[1]。」とあります。アポローンがアポロンと同じであれば，ディオニュソスが対のように思い出されます。

アポロンとディオニュソス : ニーチェ初期における《悲劇的なるもの》 https://t.co/u4oceqXhSM

　弁護士が陶酔の呪術師のようにも思えてきました。彼らの語る真実が何かを含め。

```
(py37_env) a66@a66-XTe:~% dp -p|grep 真実|grep ネット
 - 2018年07月03日14時11分の登録： ＼モトケン　@motoken_tw＼こういう人たちは詩織氏の話を100％真実であると前提して考えているみたいなんだけど、ほとんどの法律家はネット情報だけでそこまで全面的に http://hirono2014sk.blogspot.com/2018/07/motokentw100.html
 - 2018年08月08日03時46分の登録： ＼深澤諭史　@fukazawas＼ですね（・∀・；） 死刑について論じると，「ネットで真実に目覚めた」方々から，こういう反応がありますね・・。 こういう人達が，何とかブロ http://hirono2014sk.blogspot.com/2018/08/fukazawas_8.html
 - 2019年05月14日21時24分の登録： ＼深澤諭史　@fukazawas＼もはや常識ですが、真実でも名誉毀損は成立し得ます。 #ネット表現の法務 http://hirono2014sk.blogspot.com/2019/05/fukazawas_45.html
 - 2019年08月05日17時57分の登録： ＼リーチ一発ツモ裏１　@luckymangan＼令和のご時世に、ネットで真実！を専門家に見せつけるドヤ顔素人の図を見られてほっこり笑ってる…いや笑えないわ… http://hirono2014sk.blogspot.com/2019/08/luckymangan_5.html
 - 2019年08月05日19時41分の登録： ＼リーチ一発ツモ裏１　@luckymangan＼令和のご時世に、ネットで真実！を専門家に見せつけるドヤ顔素人の図を見られてほっこり笑ってる…いや笑えないわ… http://hirono2014sk.blogspot.com/2019/08/luckymangan_6.html
 - 2019年08月20日19時52分の登録： ＼弁護士 上瀧浩子　@sanngatuusagino＼あいちトリエンナーレに脅迫かけるような人は、ネットで「真実に目覚め」てそういう情報を信じて自分の考えを濃縮したんです http://hirono2014sk.blogspot.com/2019/08/sanngatuusagino_20.html
 - 2019年10月08日11時15分の登録： ＼深澤諭史　@fukazawas＼破産，廃業周りって，ネットde真実が本当に多いな。\n下手すりゃ命に関わるのでやめてほしい。インチキ医療並みの危険度。\n（・∀・；） http://hirono2014sk.blogspot.com/2019/10/fukazawasde_8.html
 - 2019年10月08日11時29分の登録： ＼深澤諭史　@fukazawas＼（；・∀・）この３倍，５倍酷い案件でも免責通りますよね・・・。\n（＾ω＾）「ネットde真実」の前に，弁護士に相談だお！ http://hirono2014sk.blogspot.com/2019/10/fukazawas-de.html
 - 2020年03月14日19時31分の登録： ＼深澤諭史　@fukazawas＼法的請求を受ける側，被告側で本人訴訟すると，ネットde真実に目覚めて都合の良い法律情報デマと心中するのって，大病にかかった人が，カルトや http://hirono2014sk.blogspot.com/2020/03/fukazawasde.html
 - 2020年04月02日21時31分の登録： ＼深澤諭史　@fukazawas＼「こういう事件では、弁護士なんかつけなくても訴訟は大丈夫！みんなでネットｄｅ真実に目覚めよう！」みたいな話はTwitterでもたまに聞く http://hirono2014sk.blogspot.com/2020/04/fukazawastwitter.html
 - 2020年04月02日21時35分の登録： REGEXP：”ネットｄｅ真実”／データベース登録済みツイート：2020年04月02日21時34分の記録：ユーザ・投稿：3／4件 http://hirono2014sk.blogspot.com/2020/04/regexp20200402213434.html
 - 2020年04月03日13時14分の登録： ＼深澤諭史　@fukazawas＼少額訴訟という制度は「ネットｄｅ真実に目覚めたが，この制度を使えば，本人訴訟で簡単に，正しい俺の言い分が通るはずだ」というものではありま http://hirono2014sk.blogspot.com/2020/04/fukazawas_90.html
 - 2020年04月15日11時00分の登録： REGEXP：”ネットｄｅ真実”／データベース登録済みツイート：2020年04月15日10時59分の記録：ユーザ・投稿：7／15件 http://hirono2014sk.blogspot.com/2020/04/regexp202004151059715.html
 - 2020年04月15日11時00分の登録： REGEXP：”ネットde真実”／データベース登録済みツイート：2020年04月15日11時00分の記録：ユーザ・投稿：10／33件 http://hirono2014sk.blogspot.com/2020/04/regexpde2020041511001033.html
 - 2020年04月15日11時01分の登録： REGEXP：”（ネットｄｅ真実｜ネットde真実）”／深澤諭史（@fukazawas）の検索（2017-07-20〜2020-04-13／2020年04月15日11時01分の記録27件） http://hirono2014sk.blogspot.com/2020/04/regexpdefukazawas2017-07-202020-04.html
 - 2020年05月09日18時52分の登録： ＼深澤諭史　@fukazawas＼法律トラブルで、同じ立場に置かれた当事者同士で「情報交換」して、ネットｄｅ真実すなわち都合の良いだけのデマをかき集め、自分達に不都合な情 http://hirono2014sk.blogspot.com/2020/05/fukazawas_9.html
 - 2020年05月11日15時44分の登録： ＼深澤諭史　@fukazawas＼「ネットｄｅ真実」よりも「専門家で現実」 : 弁護士 深澤諭史のブログ http://hirono2014sk.blogspot.com/2020/05/fukazawas_11.html
 - 2020年05月14日05時25分の登録： REGEXP：”ネットｄｅ真実”／データベース登録済みツイート：2020年05月14日05時24分の記録：ユーザ・投稿：14／42件 http://hirono2014sk.blogspot.com/2020/05/regexp2020051405241442.html
 - 2020年05月18日13時47分の登録： REGEXP：”ネットｄｅ真実”／データベース登録済みツイート：2020年05月18日13時46分の記録：ユーザ・投稿：14／44件 http://hirono2014sk.blogspot.com/2020/05/regexp2020051813461444.html
 - 2020年05月20日21時42分の登録： ＼深澤諭史　@fukazawas＼最近沢山検索でアクセスされているので，紹介・・。 本人訴訟あるある，本人訴訟のネットｄｅ真実系のデマとかも，なるべく網羅しています・・。 http://hirono2014sk.blogspot.com/2020/05/fukazawas_31.html
 - 2020年06月06日21時10分の登録： ＼深澤諭史　@fukazawas＼別に本人訴訟やっちゃダメとは言わないし、本人訴訟が適切な事例もあるけれども、「判例で決まるから大丈夫！ネットｄｅ真実の法律情報！弁護士は http://hirono2014sk.blogspot.com/2020/06/fukazawas_10.html
 - 2020年06月18日21時52分の登録： ＼深澤諭史　@fukazawas＼ネット上の表現トラブルを扱っていると、ネットｄｅ真実に目覚めて、違法投稿して責任追及されて、相手に弁護士がついているのに、それでもネット http://hirono2014sk.blogspot.com/2020/06/fukazawas_56.html
 - 2020年06月19日16時41分の登録： ＼深澤諭史　@fukazawas＼専門家に相談すると都合の悪い話もあるかもしれないので怖いってのがあるかもしれないですね。 ネットなら，有利な情報はネットｄｅ真実！，不利 http://hirono2014sk.blogspot.com/2020/06/fukazawas_19.html
 - 2020年06月23日17時11分の登録： REGEXP：”ネット．＊真実”／深澤諭史（@fukazawas）の検索（2014-10-29〜2020-06-20／2020年06月23日17時11分の記録73件） http://hirono2014sk.blogspot.com/2020/06/regexpfukazawas2014-10-292020-06.html
 - 2020年07月16日16時13分の登録： ＼深澤諭史　@fukazawas＼逆にすぐに相談しないとまずい案件に限って、「ネットｄｅ真実」の法律情報を探すことに時間を費消して、最後に差し押さえ食らってから相談に来る http://hirono2014sk.blogspot.com/2020/07/fukazawas_88.html
 - 2020年08月11日12時28分の登録： ＼深澤諭史　@fukazawas＼「ネットｄｅ真実 法律情報版」に騙されないためには，その情報提供の仕方，文言が，感情的でないかは，一つのメルクマールですね。 やたら感情 http://hirono2014sk.blogspot.com/2020/08/fukazawas_11.html
 - 2020年08月11日13時57分の登録： REGEXP：”ネットｄｅ真実”／データベース登録済みツイート：2020年08月11日13時56分の記録：ユーザ・投稿：15／66件 http://hirono2014sk.blogspot.com/2020/08/regexp2020081113561566.html
 - 2020年08月11日13時59分の登録： REGEXP：”「ネットｄｅ真実」よりも「専門家で現実」”／データベース登録済みツイート：2020年08月11日13時59分の記録：ユーザ・投稿：4／12件 http://hirono2014sk.blogspot.com/2020/08/regexp202008111359412.html
```

玉里友香 弁護士 - Google 検索 https://t.co/Nk0P18l0Ar

中傷サイトの削除依頼 発信者情報の特定 検索結果削除 関連検索キーワード削除 損害賠償請求等 : ＭＩＫＡＴＡ法律事務所 https://t.co/3VnXjy4tze

　よくわからない記事なのですが，玉里友香弁護士という顔写真があります。ちょっとした表紙で乳首が見えそうな，見せることも出来そうな服装ですが，これほど弁護士らしく見えない，弁護士らしいいでたちの弁護士というのも珍しく思います。

　スクリーンショットを撮るために，別のブラウザでページを開いたのですが，豆腐という現象が発生しました。文字のフォントの読み込みが出来ず，四角い豆腐のような枠に置き換わった現象で，10年ほど前まではEmacsでよくみた現象です。これはとても珍しく，偶然とも思えません。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 16:45／2020/09/09 16:44 URL： https://twitter.com/kk_hirono/status/1303600308786880512 https://twitter.com/s_hirono/status/1303600132139573248  

> 2020-09-09-164110_弁護士情報玉里　友香　弁護士プロフィールはこちら　←　豆腐という現象の発生.jpg https://t.co/M8hn4LBFbR  

emacsをインストールしたが、日本語が豆腐状になる - https://t.co/fiYjd7lDN6 https://t.co/LaQmqJknRx

```
弁護士玉里友香
東京地方裁判所平成26年(ヨ)第218号14/2/21
http：//qb5.2ch.net/test/read.cgi/saku2ch/1392964047/
東京地方裁判所平成26年(ヨ)第369号同日
http：//engawa.2ch.net/test/read.cgi/accuse/1392964836/
正本一週間放置で2ちゃんねるが管理機能喪失、全裸コラージュを大量にはられる事態に
ほら、弁護士バッチも本物でございますhttp：//i.imgur.com/l9Lxf9fl.jpg

［source：］2014年パカベン総決算 ： krswcorssのblog http://blog.livedoor.jp/krswcorss/archives/1028752530.html
```

　玉里友香弁護士のGoogle検索で出てきたページですが，馬鹿弁護士を意味するバカベンなのかと思ったものが，パカベンとなっているようです。ドカベンという野球漫画が昭和50年代にあったことを思い出しましたが，バカベン見たことがなかったように思います。

　パカベンというのは，IPアドレス開示と関係があるようにも思えてきました。2014年から玉里友香弁護士の名前は，ネットの一部で話題となっていたようですが，今日まで名前も顔も知らずにいました。ケレス法律事務所の高田沙代子弁護士からの繋がりで目にすることになりました。

```

インターネット上の電子掲示板にて誹謗中傷などの行為があった場合、被害者および当事者はIPアドレス開示や書き込み削除を申請したり、インターネットに接続しているプロバイダへの個人情報請求を行い、最終的に名誉毀損などで刑事告発したり、民事訴訟を起こすことが可能である。
この一連の「開示」作業を得意とする弁護士に付けられた通称の一つ。
「パカッという開示の擬音＋弁護士」から作られた造語である。

［source：］パカ弁 (ぱかべん)とは【ピクシブ百科事典】 https://dic.pixiv.net/a/%E3%83%91%E3%82%AB%E5%BC%81
```
　唐澤貴洋弁護士が仏像になったような画像と，同じく野球のバッターがボーリングのピンになったような画像があります。最近は名前を見かけることも少なくなった唐澤貴洋弁護士ですが，唐澤真教なるものも以前は見かけ，若者に影響を与え，人生や生活を左右したとも考えられます。

弁護士紹介 | 法律事務所Steadiness https://t.co/J0o29vilB1 唐澤貴洋KARASAWA Takahiro \n ￼ \n 【登録・所属】 \n 第一東京弁護士会

　「『そのツイート炎上します！100万回の殺害予告を受けた弁護士が教える危機管理』（カンゼン社、2019年）」という著書の紹介もありますが，率直に，儲けるための打算のマーケティングを展開してきたのではという疑念が払拭できない弁護士です。

```
ワイエヌ銀座ビル（中央区銀座）は、1990年1月竣工、鉄骨鉄筋コンクリート造地上10階建の賃貸オフィスビルです。
基準階面積は20.96坪で、少し特徴的な間取りです。
大江戸線・汐留駅から徒歩5分です。
オフィスビルが立ち並ぶオフィス街に立地しています。

［source：］ワイ・エヌ銀座ビル（中央区銀座）の賃貸情報｜オフィサイト https://www.offisite.jp/buildings/29120/%E3%83%AF%E3%82%A4%E3%83%BB%E3%82%A8%E3%83%8C%E9%8A%80%E5%BA%A7%E3%83%93%E3%83%AB
```

```
「1m2（平米）は『1m2』とも書き、1辺が1mの正方形面積になります。1畳というのは畳1枚分の広さ、1坪はだいたい畳2枚分の広さになります」(石井さん、以下同)

［source：］1坪は何平米？1平米はどれぐらいの広さ？ ちょうどよい広さの目安は？ | 住まいのお役立ち記事 https://suumo.jp/article/oyakudachi/oyaku/sumai_nyumon/other/tsubo_heibei/
```

　20.96坪というのは，調べたところ畳42枚分の広さになるようです。20.96坪と聞くと狭く感じたのですが，畳42枚分となると広く思えてきました。3つで割ると14枚になります。法律事務所として書類の保管や面談室の確保が出来るのかという疑問もあります。

```
■広さ

開業マニュアル等には、事務所の広さは、弁護士一人当たり１５坪程度必要とよく記載されています。

しかし、デッドスペースの少ない物件であれば、１０坪程度でも問題ないように思います。

 

最初の開業場所も移転先もどちらも１０坪程度ですが、支障をきたしたことはありません。

事務員を一人雇用したとしても余裕があります。

 

１５坪というのは、しっかりしたエントランスを設け、かつ、事件記録等がかなり溜まった状態にも耐えうることを想定しているのではないかと思います。

 

ですが、そうすると開業当初は、スペースを持て余すことになります。

将来を見越して使っていないスペースに賃料を払という選択肢は、開業資金の少ない私にはありませんでした。

［source：］弁護士の独立開業と物件選び③ | 弁護士の独立開業　マチ弁モデルの再構築 https://ameblo.jp/musakolaw/entry-12249401200.html
```

```
退職代行「ウラノス法律事務所」は、東京都中央区銀座に拠点を構える弁護士事務所です。代表の藤崎 雅弘弁護士は、刑事事件の解決に強く、巷では「告訴マン」の異名を取っているとのこと。刑事事件だけでなく、労働事件の解決でも満足のできる結果、納得のできる結果が得られると評判です。

［source：］【最新2020年】退職代行「ウラノス法律事務所」の口コミと評判！費用やサービスの内容を徹底解説| 資金調達プロ https://shikin-pro.com/guide/14761
```

```
退職代行「ウラノス法律事務所」の費用は、パート・アルバイトは43,200円(税込)で、正社員 54,000円(税込)です。このほか、成功報酬で依頼をした場合、経済的利益の20%を費用として支払う仕組みです。このほか、未払給料・残業代・退職金 等の請求は「着手金無料」となっています。

［source：］【最新2020年】退職代行「ウラノス法律事務所」の口コミと評判！費用やサービスの内容を徹底解説| 資金調達プロ https://shikin-pro.com/guide/14761
```

　深澤諭史弁護士が問題視などしていた退職代行サービスは記憶にあるのですが，弁護士が退職代行を専門のようにしているのは，初めてみたかもしれません。

　すんなりいけば，電話1本で「パート・アルバイトは43,200円(税込)で、正社員 54,000円(税込)です。」という収入になるのかと考えられますが，さすが東京のど真ん中という気がします。Googleマップで見たところ，住所が銀座でも汐留料金所に近いようです。

 - 2020年09月09日17時48分の登録： REGEXP：”退職代行”／深澤諭史（@fukazawas）の検索（2018-06-20〜2020-06-26／2020年09月09日17時48分の記録87件） http://hirono2014sk.blogspot.com/2020/09/regexpfukazawas2018-06-202020-06.html

 - （01／87） TW fukazawas（深澤諭史） 日時：2018-06-20 13:33:00 +0900 URL： https://twitter.com/fukazawas/status/1009293243593285634

> 可能性としては，
> 退職代行業者による退職の意思表示→非弁行為→無権代理→無効→退職にならない。
> なので，
> 会社：退職扱いすると不当解雇類似の法律関係になりバックペイのリスク
> 従業員：退職扱いになっていないので，無断欠勤からの懲戒解… https://t.co/Gn5Z2LTGVs

 - （02／87） TW fukazawas（深澤諭史） 日時：2018-06-20 15:44:00 +0900 URL： https://twitter.com/fukazawas/status/1009326069998948352

> 最近，非弁業者の代理・代行は無効扱いすべき，というのが浸透してきたから，退職代行業者に頼むのは，本当にリスクしかない。
> 代理しなきゃ非弁にならない，代行だから大丈夫！という人は，弁護士法７２条本文を声に出して読んでみてね。
> （・∀・）ｂ

　最近は見かけなくなった，深澤諭史弁護士の非弁と無効の組み合わせですが，法律行為の無効というのはさかのぼって効力を失うとなっていたように思います。それだけ影響が大きいはずですが，探しても具体的な判例など見つかりませんでした。

 - （03／87） TW fukazawas（深澤諭史） 日時：2018-06-21 09:11:00 +0900 URL： https://twitter.com/fukazawas/status/1009589711294291968

> 退職代行業者に依頼した場合，退職の意思表示とはいえ，勤務先に対する犯罪行為を依頼するわけだから，有効無効以前に，懲戒事由にもなりかねないですね。
> （・∀・；）

　本当に，弁護士フィールド全開，といった感じの深澤諭史弁護士らしいツイートで，弁護士が全知全能の神であるかのようです。

 - （87／87） TW fukazawas（深澤諭史） 日時：2020-06-26 12:23:00 +0900 URL： https://twitter.com/fukazawas/status/1276355292897263617

> 退職代行業者で「即日退職可能」は悪質なデマ - 弁護士 深澤諭史のブログ https://t.co/VDZVQZ7Qqp

 - （84／87） TW fukazawas（深澤諭史） 日時：2020-05-02 20:52:00 +0900 URL： https://twitter.com/fukazawas/status/1256552209916981248

> 退職代行は「判例がないからグレーだ」というのは間違い - 弁護士 深澤諭史のブログ https://t.co/D240W8A3TD　

　上記の「退職代行は「判例がないからグレーだ」というのは間違い - 弁護士 深澤諭史のブログ」というツイートは，ツイートもブログ記事も見落としがあったようです。退職代行を弁護士のツイートで見かけるようになったのは1年ほど前でしょうか。その前にテレビで見ていたかもしれませんが。

```
はっきりいって間違いです。
そもそも、判例になるのは、争われて、明確に判断が下されて、しかも実際問題として公刊物に掲載された、というような事案です。
しかも、そうそう都合よく、同じ事案が見つかるというものではありません（そんなことなら、法律家はみんな失業です。）。
大学の試験問題ですら、裁判例そのまま出るというものではありません。

こういう場合は、類似の案件や、逐条解説書（１条１項毎に法律条文の意味や解釈などを解説した書籍。コンメンタールともいわれる。）などから支配的な見解を調べて、判断をするということが必要になります。

代行に関しては、債権回収の代行、あるいは債権受領の代行について、すでにそれらが非弁行為であるという裁判例があります。

また、非弁行為の成立には、法律事件に関する法律事務であることが必要です。
この点について、法律事件とは、紛争の可能性があるか又は新しく法律関係を変動させる事案をいい、法律事務とは、代理以外にも法律関係を変動させたり明確化、保全する行為が含まれる、と解釈されています。
そうすると、退職代行は、具体的な内容次第ですが、一般に宣伝されているような内容・行為であれば、非弁行為に該当する可能性が極めて高いといえます。

［source：］退職代行は「判例がないからグレーだ」というのは間違い ： 弁護士 深澤諭史のブログ http://xn--zqs94lv37b.club/archives/16819523.html
```

　フィールドというのは，分野という意味があったように思いますが，数日前，アニソンと呼ばれるアニメソングのランキングの番組があって，ちょうど最後の1位の前ぐらいに気がついたのですが，久しぶりに「残酷な天使のテーゼ」を聴きながら，弁護士フィールドが頭に浮かんでいました。

　深澤諭史弁護士には非弁フロンティアのようなものもあったかと思います。もとい，第二東京弁護士会のなんとかフロンティアという広報誌のようなものに，深澤諭史弁護士が非弁問題を，怪談のように紹介したものでした。

```
 - 2020年09月09日10時24分の登録： REGEXP：”日本エンターテイナーライツ”／データベース登録済みツイート：2020年09月09日10時23分の記録：ユーザ・投稿：21／41件 http://hirono2014sk.blogspot.com/2020/09/regexp2020090910232141.html
 - 2020年09月09日10時24分の登録： REGEXP：”日本エンターテイナーライツ”／データベース登録済みツイートの検索：2020-09-08〜2020-09-09／2020年09月09日10時24分の記録：ユーザ・投稿：13／16件 http://hirono2014sk.blogspot.com/2020/09/regexp2020-09-082020-09_70.html
 - 2020年09月09日11時52分の登録： REGEXP：”リーガルファンディング”／データベース登録済みツイート：2020年09月09日11時51分の記録：ユーザ・投稿：10／18件 http://hirono2014sk.blogspot.com/2020/09/regexp2020090911511018.html
 - 2020年09月09日12時30分の登録： ＼浜 ち ゃ ん　@lawer_hamachan＼残債ありどうしよう（－）から０になるのみならず過払い金が返ってくる（＋）に転じるわけだから過払い案件は感謝されるよなぁと http://hirono2014sk.blogspot.com/2020/09/lawerhamachan.html
 - 2020年09月09日12時30分の登録： ＼うのじ　@un_co_the2nd＼このとても極めて真っ当なツイートにぶら下がってる大麻推進派（という呼び名でいいの？）のリプを見て、大麻は少なくとも心に悪そうだと思い http://hirono2014sk.blogspot.com/2020/09/uncothe2nd_9.html
 - 2020年09月09日12時33分の登録： ＼田丁木寸　@matimura＼大量懲戒請求事件で本人応訴の被告に対し、裁判所が「求釈明書兼回答書」を送ったら、「そもそも釈明すべきことなど何もありません。本件の裁判長の http://hirono2014sk.blogspot.com/2020/09/matimura.html
 - 2020年09月09日12時33分の登録： ＼深澤諭史　@fukazawas＼「酷薄なことを言っているリーダーを支持すると，自分が一体となって，強くなった気分が味わえる」というのが，大きい気がします。 （・∀・；） http://hirono2014sk.blogspot.com/2020/09/fukazawas_9.html
 - 2020年09月09日12時33分の登録： ＼向原総合法律事務所　弁護士向原　@harrier0516osk＼福祉（や生活保護）を叩いてる人は、そうした利益供与については全然ダンマリなので不思議やなぁと思っています http://hirono2014sk.blogspot.com/2020/09/harrier0516osk_1.html
 - 2020年09月09日12時35分の登録： ＼深澤諭史　@fukazawas＼非弁，広告，外弁，研修，さすがに多重会務だな・・・。 クオリティが落ちて迷惑かけるので，ちょっと，考えないと。 （・∀・；） http://hirono2014sk.blogspot.com/2020/09/fukazawas_78.html
 - 2020年09月09日12時36分の登録： ＼Document35　@document35＼公益活動を語る弁護士ほど過払バブルのとき荒稼ぎするべきだったんじゃないだろうか。過払回収だって、どうせ誰かがやらなければな http://hirono2014sk.blogspot.com/2020/09/document35document35.html
 - 2020年09月09日13時28分の登録： ＼深澤諭史　@fukazawas＼法律相談、事件受任、顧問契約、専門書出版、一般向け書籍出版、テレビ出演、全部につながりました（・∀・）v http://hirono2014sk.blogspot.com/2020/09/fukazawasv.html
 - 2020年09月09日13時29分の登録： ＼プリンセスN　@princessbea1215＼弁護士ドットコムの冊子、やっと届いたんだけど、ツイッターって受任に繋がるのか。どうせバレてるし、もう実名に変えようかな。 http://hirono2014sk.blogspot.com/2020/09/nprincessbea1215.html
 - 2020年09月09日14時27分の登録： REGEXP：”小金井ストーカー”／データベース登録済みツイート：2020年09月09日14時26分の記録：ユーザ・投稿：22／36件 http://hirono2014sk.blogspot.com/2020/09/regexp2020090914262236.html
 - 2020年09月09日15時54分の登録： REGEXP：”ケレス”／データベース登録済みツイート：2020年09月09日15時54分の記録：ユーザ・投稿：1／6件 http://hirono2014sk.blogspot.com/2020/09/regexp20200909155416.html
 - 2020年09月09日15時55分の登録： REGEXP：”レアーナ”／データベース登録済みツイート：2020年09月09日15時55分の記録：ユーザ・投稿：1／3件 http://hirono2014sk.blogspot.com/2020/09/regexp20200909155513.html
 - 2020年09月09日15時56分の登録： REGEXP：”ウラノス”／データベース登録済みツイート：2020年09月09日15時56分の記録：ユーザ・投稿：1／3件 http://hirono2014sk.blogspot.com/2020/09/regexp20200909155613.html
 - 2020年09月09日15時58分の登録： REGEXP：”玉里友香”／データベース登録済みツイート：2020年09月09日15時57分の記録：ユーザ・投稿：1／6件 http://hirono2014sk.blogspot.com/2020/09/regexp20200909155716.html
 - 2020年09月09日16時04分の登録： REGEXP：”高田沙代子”／データベース登録済みツイート：2020年09月09日16時04分の記録：ユーザ・投稿：3／17件 http://hirono2014sk.blogspot.com/2020/09/regexp202009091604317.html
 - 2020年09月09日16時07分の登録： REGEXP：”藤崎雅弘”／データベース登録済みツイート：2020年09月09日16時06分の記録：ユーザ・投稿：1／1件 http://hirono2014sk.blogspot.com/2020/09/regexp20200909160611.html
 - 2020年09月09日17時48分の登録： REGEXP：”退職代行”／深澤諭史（@fukazawas）の検索（2018-06-20〜2020-06-26／2020年09月09日17時48分の記録87件） http://hirono2014sk.blogspot.com/2020/09/regexpfukazawas2018-06-202020-06.html
 - 2020年09月09日17時56分の登録： REGEXP：”無効”／深澤諭史（@fukazawas）の検索（2013-07-04〜2020-06-17／2020年09月09日17時55分の記録163件） http://hirono2014sk.blogspot.com/2020/09/regexpfukazawas2013-07-042020-06.html
 - 2020年09月09日18時08分の登録： REGEXP：”フロンティア”／深澤諭史（@fukazawas）の検索（2014-04-22〜2020-05-28／2020年09月09日18時08分の記録88件） http://hirono2014sk.blogspot.com/2020/09/regexpfukazawas2014-04-222020-05.html
```

 - （01／88） TW fukazawas（深澤諭史） 日時：2014-04-22 17:05:00 +0900 URL： https://twitter.com/fukazawas/status/458516959873597440

> 法曹志願者激減の原因について
> 「多大な時間的・金銭的負担の末に取得する資格であるにもかかわらず、その資格で「飯を食う」ことができない。これほど資格の魅力を損なう話はない。資格の魅力が低くなればなるほど、その資格を目指す人間は減る。」
> 二弁フロンティア２０１２年１２月号２５頁。

 - （10／88） TW fukazawas（深澤諭史） 日時：2015-11-21 12:07:00 +0900 URL： https://twitter.com/fukazawas/status/667902108788625410

> ☆Ｖｏｌ．４☆
> 【特集１】非弁提携か成仏か。それが問題だ。ある新人弁護士の告白。
> 【特集２】非弁提携業者を直撃！提携先はどうやって見つけている！？
> ◯コラム　非弁と非弁提携の違い
>
> #非弁フロンティア

 - （45／88） RT fukazawas（深澤諭史）｜kid_ant8（きど@はてなブログ） 日時：2017-10-06 12:50:00 +0900／2017-09-30 10:53:00 +0900 URL： https://twitter.com/fukazawas/status/916148644679577600 https://twitter.com/kid_ant8/status/913944862004613120

> 二弁フロンティアの「本当に怖い非弁提携」、面白かった

　「本当に怖い非弁提携」が深澤諭史弁護士の執筆記事のタイトルで，おどろおどろしい表現もありました。真夏の夜の怪談ってな感じで。弁護士に狂わされる人生の方が，社会危機として深刻な問題であることを，弁護士パラダイスの深澤諭史弁護士の軽薄さで思いを強くしました。

 - （46／88） RT fukazawas（深澤諭史）｜tatoo_guy（多頭飼い） 日時：2017-10-06 12:51:00 +0900／2017-09-26 21:17:00 +0900 URL： https://twitter.com/fukazawas/status/916148790389751808 https://twitter.com/tatoo_guy/status/912652457372557312

> とても手が込んでいる二弁フロンティア来月号の特集 #非弁フロンティア https://t.co/zUPf4InQHO

　ここで「二弁フロンティア来月号の特集 #非弁フロンティア」の表紙が，画像か写真で出てきました。業務提携というのはどこの業界でもありそうですが，弁護士の独占フィールドで，弁護士が一方的な被害者とも印象づけています。

 - （47／88） RT fukazawas（深澤諭史）｜ina_min（イナミン） 日時：2017-10-12 22:19:00 +0900／2017-10-12 18:29:00 +0900 URL： https://twitter.com/fukazawas/status/918466175083745281 https://twitter.com/ina_min/status/918408383216021506

> ようやく，評判の「非弁フロンティア」を拝読できた。率直にいってガクブルであります。

 - （48／88） RT fukazawas（深澤諭史）｜jjjhaga（芳賀淳） 日時：2017-10-21 13:07:00 +0900／2017-10-17 10:25:00 +0900 URL： https://twitter.com/fukazawas/status/921588743923908608 https://twitter.com/jjjhaga/status/920098465044054016

> 私は東弁だけど「非弁フロンティア・二弁フロンティアの一部」を取り寄せて読んだ。これは独立を考える若手の弁護士は必読でしょう。「苦しい仕事がない今だけ」というのは非弁提携には通用しない(足抜けできない)、契約書でがんじがらめ。とのこ… https://t.co/CggUBWPvLt

 - （49／88） TW fukazawas（深澤諭史） 日時：2017-10-24 10:54:00 +0900 URL： https://twitter.com/fukazawas/status/922642478573920257

> 二弁フロンティア「非弁フロンティア 本当に怖い非弁提携」が、誰でもネットで読めるようになりました！
> https://t.co/REs7bztURC

 - （60／88） RT fukazawas（深澤諭史）｜ekinan_lawyer（えきなんローヤー） 日時：2017-10-28 19:59:00 +0900／2017-10-28 18:13:00 +0900 URL： https://twitter.com/fukazawas/status/924229105620365313 https://twitter.com/ekinan_lawyer/status/924202331247218688

> 非弁フロンティア曰く、「不適切勧誘、不適切処理、そして、経費流用（横領）で弁護士を食いものにすれば、まだまだペイできるというのが実情のようです」、と。
>
> 弁護士志望の修習生、必読の記事だよ。１０頁ぐらいで短いことだし。

　あらためて，玉里友香弁護士が，非弁提携で業務停止2ヶ月の懲戒処分を受けたという情報がネットにあるのですが，まとめ記事の検索結果を見ても，他の弁護士は知らないか，だんまりを決め込んでいるようです。

 - （61／88） RT fukazawas（深澤諭史）｜ekinan_lawyer（えきなんローヤー） 日時：2017-10-28 19:59:00 +0900／2017-10-28 18:08:00 +0900 URL： https://twitter.com/fukazawas/status/924229096183230464 https://twitter.com/ekinan_lawyer/status/924201287947665408

> 非弁フロンティア、今更ながら読んだ。
>
> 私自身は、こんな手口には騙されない自信あるけど、引っかかる若手弁護士はいるんだろうな …

 - （62／88） RT fukazawas（深澤諭史）｜civil_law1（民法(親族相続)くん） 日時：2017-10-30 23:06:00 +0900／2017-10-30 13:12:00 +0900 URL： https://twitter.com/fukazawas/status/925001059931582464 https://twitter.com/civil_law1/status/924851410805563392

> 一月遅れではありますが、深澤先生の非弁フロンティアをば…。
> この再現率…www https://t.co/qc24HLptAB

 - （65／88） TW fukazawas（深澤諭史） 日時：2017-12-19 15:24:00 +0900 URL： https://twitter.com/fukazawas/status/943004148538028032

> 同意見です。
> 「非弁フロンティア」でも研修でも繰り返し繰り返し言っていることですが，一人で抱え込むと，非弁提携業者にますます抱え込まれます。
> 少しでも早く相談を！ https://t.co/nMIW1tVkfx

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜o2441（弁護士大西洋一） 日時：2020-09-09 18:28／2017/12/18 23:31 URL： https://twitter.com/kk_hirono/status/1303626437480513536 https://twitter.com/o2441/status/942764238623428609  

> 自由と正義の懲戒事例を見て思ったけど、今、非弁に脅されてたり、無知から非弁提携始めてしまったけど関係が切れずに困ってたり、着服してまだバレてないけどバレるのは時間の問題だって弁護士いる？一人で悩まず相談に来てよ。秘密は守るし匿名相談でもいいよ。今からできるベストを尽くそうよ。  

 - （70／88） RT fukazawas（深澤諭史）｜kurobeco（くろべこ） 日時：2018-01-24 17:49:00 +0900／2018-01-24 17:48:00 +0900 URL： https://twitter.com/fukazawas/status/956086532540018688 https://twitter.com/kurobeco/status/956086283280896000

> @fukazawas 普段のツイートと非弁フロンティアに書かれていたことが簡潔に復習できました！

 - （73／88） RT fukazawas（深澤諭史）｜O59K2dPQH59QEJx（ピピピーッ） 日時：2018-03-18 09:51:00 +0900／2018-03-18 09:50:00 +0900 URL： https://twitter.com/fukazawas/status/975172725311352832 https://twitter.com/O59K2dPQH59QEJx/status/975172579429302272

> 「砂漠にはまだ見ぬフロンティアがある」と嘯き、夢を求める人達を砂漠に連れ出し、そして乾き出したその人達に水を売って儲ける。
> ロー推進派は悪徳な砂漠の商人だよ。 https://t.co/H3tdMyX0eB

 - （77／88） TW fukazawas（深澤諭史） 日時：2018-07-25 12:41:00 +0900 URL： https://twitter.com/fukazawas/status/1021963676725563392

> 正直、この二弁フロンティアの論考は、法曹養成について語るなら、必読だと思う。
> （・∀・） https://t.co/GYeYJAJ575

 - （78／88） TW fukazawas（深澤諭史） 日時：2018-10-26 12:59:00 +0900 URL： https://twitter.com/fukazawas/status/1055670226493202432

> （・∀・）お，今月号の二弁フロンティアに，私の記事が。
> （＾ω＾）普通の常議員会報告だお。

 - （80／88） TW fukazawas（深澤諭史） 日時：2019-02-28 17:05:00 +0900 URL： https://twitter.com/fukazawas/status/1101030657973641216

> 二弁フロンティア２０１９年３月号、e裁判レポートは、全法曹必読ですね。
> 最初に歴史やこれまでの経緯を簡単に説明し、現状どこまできているのか、とかが解説されています。
> 連載で、次回以降、模擬裁判とかの情報も出てくると思います。
> （・∀・）（＾ω＾）

 - （85／88） TW fukazawas（深澤諭史） 日時：2019-07-25 16:35:00 +0900 URL： https://twitter.com/fukazawas/status/1154294092647395328

> 二弁フロンティア特集
> 「人はなぜ記憶を誤るのか　刑事弁護に必要な心理学の基礎（後編）」
> 凄い読み応えあった。是非（・∀・）

　上記の深澤諭史弁護士のツイートは見落としかもしれません。

 - （86／88） TW fukazawas（深澤諭史） 日時：2019-07-25 16:40:00 +0900 URL： https://twitter.com/fukazawas/status/1154295222701969408

> （・∀・）自画自賛するようですが，本当に，二弁フロンティアのレベルは高い。
> （＾ω＾）素晴らしい記事が多すぎるお。

　たしかに深澤諭史弁護士を必要とする需要に応える依頼者というのは存在するのかもと想像しますが，社会全体の利益を見通すと，深刻重大な危機感を躊躇なしに痛感させる生の迫力があります。

弁護士ビル２号館 から ワイ・エヌ銀座ビル - Google マップ https://t.co/RdiXWSoUpy  \n ￼ \n 8 分 \n 1.7 km \n 都道405号 経由 \n 最速ルート（通常の交通量） \n ￼詳細 \n ￼ \n 8 分 \n 2.0 km \n 第一京浜/国道15号 経由 \n 多少の交通量（通常どおり） \n ￼ \n 22 分 \n 18:40 - 19:02 \n ￼  ￼日比谷線  ￼

#### 深澤諭史弁護士が所属していると思われる東京都港区西新橋弁護士ビル2号館，服部啓法律事務所 : 金沢地方検察庁御中 https://t.co/EHzyGD56y4

　自分のブログですが，リンクを開いたのは久しぶりで，半年近く前は，いつまで経ってもページの読み込みができず，もうダメなのかと思っていたのが，すぐに記事の表示となりました。

　なんとかフィールド全開，というのは，エヴァンゲリオンのパチスロ機の演出の１つだったと思います。

エヴァンゲリオン セリフ at フィールド 全開 - Google 検索 https://t.co/EkuVrIIpbb

　サジェスというのか入力の補完候補が出てきました。

```
「ATフィールド、全開！！」このセリフは、エヴァでは欠かすことのできない言葉です。
私もこの言葉なくしてエヴァは語れないと思っています。
今回はエヴァ用語である「ATフィールド」について解説していきたいと思います

［source：］ATフィールドの意味とは？エヴァが展開し中和したシーンを解説 | あゆレビ -are you review?- https://i-revue.com/evangelion-atfield/
```

* 「凍った豆腐で殴る行為が傷害罪になるかどうかは、判例がないから今の所グレー」という，退職代行を非弁とする判例がないから，という文脈で例え話の深澤諭史弁護士のツイート

```
はっきりいって間違いです。
そもそも、判例になるのは、争われて、明確に判断が下されて、しかも実際問題として公刊物に掲載された、というような事案です。
しかも、そうそう都合よく、同じ事案が見つかるというものではありません（そんなことなら、法律家はみんな失業です。）。
大学の試験問題ですら、裁判例そのまま出るというものではありません。

こういう場合は、類似の案件や、逐条解説書（１条１項毎に法律条文の意味や解釈などを解説した書籍。コンメンタールともいわれる。）などから支配的な見解を調べて、判断をするということが必要になります。

代行に関しては、債権回収の代行、あるいは債権受領の代行について、すでにそれらが非弁行為であるという裁判例があります。

また、非弁行為の成立には、法律事件に関する法律事務であることが必要です。
この点について、法律事件とは、紛争の可能性があるか又は新しく法律関係を変動させる事案をいい、法律事務とは、代理以外にも法律関係を変動させたり明確化、保全する行為が含まれる、と解釈されています。
そうすると、退職代行は、具体的な内容次第ですが、一般に宣伝されているような内容・行為であれば、非弁行為に該当する可能性が極めて高いといえます。

［source：］退職代行は「判例がないからグレーだ」というのは間違い ： 弁護士 深澤諭史のブログ http://xn--zqs94lv37b.club/archives/16819523.html
```

　上記のブログ記事の冒頭で，埋め込みツイートとして紹介されているもので，次のツイートです。

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2019/05/03 09:25 URL： https://twitter.com/fukazawas/status/1124107642769690624  

> 「退職代行については、非弁とする判例がないから、今の所グレー」という言説は、法律実務を理解していない見解だと思う。  
> 例えば「凍った豆腐で殴る行為が傷害罪になるかどうかは、判例がないから今の所グレー」というようなもの。  
> （・∀・；）  

　大音響で成立する暴行罪という判例はあったと思いますし，傷害罪は暴行罪の結果的加重犯でもあるので，当然に傷害罪が成立するはずですが，これは流石に基本的な論理に疑問を感じた深澤諭史弁護士のツイートです。

大音量の音楽による精神的傷害に傷害罪を認めた事案（奈良騒音おばさん事件） : 最新法律情報室 https://t.co/5lOW6lU8aS

　前にテレビの情報番組で見たことのある騒音問題かと思いますが，判例となっていたようです。それでも下級審の判例なので，判例としては参考以上の意味がないはずです。深澤諭史弁護士の場合は，下級審の判例以前に，示す積極的な見解を感じさせるものでもあります。

* 野田隼人弁護士や喜久山大貴弁護士がリツイートした，「「正解病」が検察を蝕む：なぜ小説『ナリ検』を執筆したのか」という市川寛弁護士のツイート

:CATEGORIES: 野田隼人弁護士,喜久山大貴弁護士,市川寛弁護士,検察

@imarockcaster42 ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@imarockcaster42）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW imarockcaster42（弁護士 市川 寛） 日時：2020/09/04 11:13 URL： https://twitter.com/imarockcaster42/status/1301704976750669825  

> 「正解病」が検察を蝕む：なぜ小説『ナリ検』を執筆したのか（市川寛） https://t.co/7ZbCknETx6  拙著の意図などをお話しました。よろしければお読みください  

@imarockcaster42 ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@imarockcaster42）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW imarockcaster42（弁護士 市川 寛） 日時：2020/09/04 11:13 URL： https://twitter.com/imarockcaster42/status/1301704977975398400  

> 多くの人は失敗の原因を見つめ、それを踏まえて次の施策を考えることで進歩するのではと思いますが、今日び、場面によっては、例えば失敗の証拠を廃棄することによって失敗を否定し、「この国がかつて行ったことには何ら間違いはない」とまで強弁する「正解病」がはびこりつつあるのではと危惧します  

```
返信できるアカウント
@imarockcaster42さんがフォローしているか@ツイートしたアカウントが返信できます。

［source：］弁護士 市川 寛さんはTwitterを使っています 「多くの人は失敗の原因を見つめ、それを踏まえて次の施策を考えることで進歩するのではと思いますが、今日び、場面によっては、例えば失敗の証拠を廃棄することによって失敗を否定し、「この国がかつて行ったことには何ら間違いはない」とまで強弁する「正解病」がはびこりつつあるのではと危惧します」 / Twitter https://twitter.com/imarockcaster42/status/1301704977975398400
```

```
2020年09月09日20時27分の実行記録
twitterAPI-search-lawList-mydql-add.rb "正解病"
ツイート数：4/1969 リツイート数：5/1969 トータル：504
hirono_hideki 1／0件
kk_hirono 0／0件
s_hirono 0／0件
```
```

アカウント名	ツイート数	リツイート数
弁護士 市川 寛（imarockcaster42）	2	0
芳賀淳（jjjhaga）	0	1
黒田法律事務所 弁護士黒田厚志（kurodalawoffice）	0	1
喜久山大貴（kikuyamahiroki）	0	1
野田隼人（nodahayato）	0	1
弁護士 伊藤祐貴＠上野御徒町（itoyukilaw）	1	0
奉納＼さらば弁護士鉄道・泥棒神社の物語（hirono_hideki）	1	0


［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”正解病”／データベース登録済みツイート：2020年09月09日20時30分の記録：ユーザ・投稿：7／8件 http://hirono2014sk.blogspot.com/2020/09/regexp20200909203078.html
```

* 「「決定的な証拠あります」と言われて録音聞くと次の一つ以上に当てはまる。」という2018年10月29日のツイートの，深澤諭史弁護士のリツイート

:CATEGORIES: 深澤諭史弁護士

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜which0623（W h i c h (今は社会的距離を保ってね)） 日時：2020-09-09 20:36／2018/10/29 21:42 URL： https://twitter.com/kk_hirono/status/1303658443497119745 https://twitter.com/which0623/status/1056889025569550342  

> 「決定的な証拠あります」と言われて録音聞くと次の一つ以上に当てはまる。 ①言葉が聞き取れない。 ②誰が話しているか分からない。 ③話が証明されるべき事実と無関係。 ④むしろこちらが致命的なことを言っている。 ⑤こちらが無茶言って相手が黙ったのを決定的と思っている。  #弁護士あるある  

- RT fukazawas（深澤諭史）｜which0623（W h i c h (今は社会的距離を保ってね)） 日時：2020/09/09 20:24／2018/10/29 21:42 URL： https://twitter.com/fukazawas/status/1303655501872259072 https://twitter.com/which0623/status/1056889025569550342

> RT @which0623: 「決定的な証拠あります」と言われて録音聞くと次の一つ以上に当てはまる。  
> ①言葉が聞き取れない。  
> ②誰が話しているか分からない。  
> ③話が証明されるべき事実と無関係。  
> ④むしろこちらが致命的なことを言っている。  
> ⑤こちらが無茶言って相手が黙ったのを決定的と思っている。  
>   
> #弁護士あるある  

　何分の一かはそういう事例がないと否定は出来ない弁護士商売ですが，それを全てと語り，深澤諭史弁護士がリツイートしているところに図り知れぬ，異常性と危機感を弁護士商売，弁護士業界に向けて感じる参考資料です。それも何のタイミングなのか2018年10月のツイート。

* 「病院から説明をうけることになったボス。仕事を告げた瞬間、職業を赤文字でカルテに記載されました。#弁護士あるある 」という深澤諭史弁護士のリツイート

:CATEGORIES: 深澤諭史弁護士,病院

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 20:45／2020/09/09 20:43 URL： https://twitter.com/kk_hirono/status/1303660802965229581 https://twitter.com/s_hirono/status/1303660320263561217  

> 2020-09-09-204313_深澤諭史さんがリツイート￼icchan@icchan41543407·2018年10月29日家族が入院したということで、病院から説明をうける.jpg https://t.co/gAonqGRPG0  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 20:45／2020/09/09 20:35 URL： https://twitter.com/kk_hirono/status/1303660824955777024 https://twitter.com/s_hirono/status/1303658340065579008  

> 2020-09-09-203417_深澤諭史さんがリツイート￼W　h　i　c　h　（今は社会的距離を保ってね）@which0623·2018年10月29日「決定的な証拠あります.jpg https://t.co/3JLk66beHr  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 20:45／2020/09/09 20:35 URL： https://twitter.com/kk_hirono/status/1303660841602957313 https://twitter.com/s_hirono/status/1303658266468081665  

> 2020-09-09-202514_弁護士　市川　寛@imarockcaster42多くの人は失敗の原因を見つめ、それを踏まえて次の施策を考えることで進歩するのではと思いますが.jpg https://t.co/hGfFcy4OUB  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 20:45／2020/09/09 20:35 URL： https://twitter.com/kk_hirono/status/1303660868400340993 https://twitter.com/s_hirono/status/1303658193545867264  

> 2020-09-09-201327_野田隼人さんがリツイート￼弁護士　市川　寛@imarockcaster42·9月4日「正解病」が検察を蝕む：なぜ小説『ナリ検』を執筆したのか.jpg https://t.co/73iavDz1Gl  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 20:45／2020/09/09 20:34 URL： https://twitter.com/kk_hirono/status/1303660881901830151 https://twitter.com/s_hirono/status/1303658120456011776  

> 2020-09-09-193505_野田隼人@nodahayato·1時間自治体のお客さんにばべるんと平先生を売り込んでみた。.jpg https://t.co/YDT4pOBPnV  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 20:45／2020/09/09 20:34 URL： https://twitter.com/kk_hirono/status/1303660904836341766 https://twitter.com/s_hirono/status/1303658047613489152  

> 2020-09-09-190814_深澤諭史@fukazawas「退職代行については、非弁とする判例がないから、今の所グレー」という言説は、法律実務を理解していない見解だと思う.jpg https://t.co/R7fUqyQR4s  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 20:45／2020/09/09 19:07 URL： https://twitter.com/kk_hirono/status/1303660918681657345 https://twitter.com/s_hirono/status/1303636011084201989  

> 2020-09-09-185819_喜久山大貴@kikuyamahiroki返信先：　@koto_tsumuさんいずれの場合も自分の氏名を捜査機関に告げる必要はありません。.jpg https://t.co/t8KRfok00J  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 20:46／2020/09/09 19:06 URL： https://twitter.com/kk_hirono/status/1303660940005486592 https://twitter.com/s_hirono/status/1303635938547920896  

> 2020-09-09-185646_喜久山大貴@kikuyamahiroki逮捕されたら弁護士が来るまで黙秘が鉄則。もうちょい頑張れそうなら、自分の名前も言わない、スマホの暗証.jpg https://t.co/NdkAVwNgA2  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 20:46／2020/09/09 19:06 URL： https://twitter.com/kk_hirono/status/1303660963573317632 https://twitter.com/s_hirono/status/1303635865655148545  

> 2020-09-09-185223_深澤諭史さんがリツイート￼仲町六絵_新刊告知用@karakusashuzai·3時間こういう手口を察知したら、証拠を残した上で逃げます。そし.jpg https://t.co/muTfTKcc2W  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 20:46／2020/09/09 19:06 URL： https://twitter.com/kk_hirono/status/1303660981143232519 https://twitter.com/s_hirono/status/1303635792992976896  

> 2020-09-09-185028_ーフォローしている人にフォロワーはいません3￼深澤諭史11。7万　件のツイートフォロー新しいツイートを表示￼￼フォロー深澤諭史@fukaza.jpg https://t.co/PB4AojyPMT  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 20:46／2020/09/09 19:05 URL： https://twitter.com/kk_hirono/status/1303660997979242496 https://twitter.com/s_hirono/status/1303635720435712002  

> 2020-09-09-184931_深澤諭史さんがリツイート￼りっぴぃ@rippy08·2時間こんなに忙しいのに売り上げ全然ないのなんで（パクツイですが本当に・・・本当にね・・.jpg https://t.co/knXxugjqQS  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 20:46／2020/09/09 19:05 URL： https://twitter.com/kk_hirono/status/1303661013766557696 https://twitter.com/s_hirono/status/1303635647924559874  

> 2020-09-09-180231_例えば「凍った豆腐で殴る行為が傷害罪になるかどうかは、判例がないから今の所グレー」というようなもの。（・∀・；）.jpg https://t.co/gVQd92n3Fb  

@icchan41543407 ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@icchan41543407）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW icchan41543407（icchan） 日時：2018/10/29 22:36 URL： https://twitter.com/icchan41543407/status/1056902623285006336  

> 家族が入院したということで、病院から説明をうけることになったボス。仕事を告げた瞬間、職業を赤文字でカルテに記載されました。  
> #弁護士あるある https://t.co/FIrCoZy7on  

　頂きました，弁護士ブロックという感じです。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 20:53／2020/09/09 20:52 URL： https://twitter.com/kk_hirono/status/1303662828306354176 https://twitter.com/s_hirono/status/1303662586630529025  

> 2020-09-09-205040_icchan　@icchan41543407　ブロックされています　@icchan41543407さんのフォローやツイートの表示はできません。詳細はこちら.jpg https://t.co/U7osFjEcJC  

- RT fukazawas（深澤諭史）｜icchan41543407（icchan） 日時：2020/09/09 20:24／2018/10/29 22:36 URL： https://twitter.com/fukazawas/status/1303655430770499586 https://twitter.com/icchan41543407/status/1056902623285006336

> RT @icchan41543407: 家族が入院したということで、病院から説明をうけることになったボス。仕事を告げた瞬間、職業を赤文字でカルテに記載されました。  
> #弁護士あるある https://t.co/FIrCoZy7on  

```
icchan
@icchan41543407
国内の蒼黒両方好き。言動危険、定期忘れても守秘義務必須。
日本のどっか2012年4月からTwitterを利用しています
1,091 フォロー中
1,096 フォロワー

［source：］icchanさん (@icchan41543407) / Twitter https://twitter.com/icchan41543407
```

　これまで余り注目してこなかった匿名の弁護士の可能性の高いアカウントですが，プロフィールに「国内の蒼黒両方好き。言動危険、定期忘れても守秘義務必須。」とあるのは印象深くあります。

```
(py37_env) a66@a66-XTe:~% dp -p|grep icchan41543407
 - 2017年10月06日00時37分の登録： ％@icchan41543407　icchan％人権大会に運営で関わった経験があるボス、あまりに多忙なので事務は「(弁護士の)人権(蹂躙)大会じゃね？」と言っておりました http://hirono2014sk.blogspot.com/2017/10/icchan41543407icchan.html
 - 2017年11月22日16時44分の登録： ＼icchan　@icchan41543407＼実際は、法テラスの存在が目の前の弁護士ほど見えてないから、何かあると弁護士に直接来ちゃうんだよね…＞ＲＴ\n今のところ、法テ http://hirono2014sk.blogspot.com/2017/11/icchanicchan41543407.html
 - 2018年02月06日20時00分の登録： ＼icchan　@icchan41543407＼被害にあった方が相談にみえたことがありますが、ご本人が懲戒請求者として名前を出すのをためらわれてしまって。対象者は故人です http://hirono2014sk.blogspot.com/2018/02/icchanicchan41543407.html
 - 2018年10月31日13時45分の登録： ＼icchan　@icchan41543407＼家族が入院したということで、病院から説明をうけることになったボス。仕事を告げた瞬間、職業を赤文字でカルテに記載されました。 http://hirono2014sk.blogspot.com/2018/10/icchanicchan41543407.html
 - 2018年10月31日13時45分の登録： ＃icchan　@icchan41543407＃のツイート／2018-10-23_2327〜2018-10-31_0849／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年10月31日13時45分 http://hirono2014sk.blogspot.com/2018/10/icchanicchan415434072018-10-2323272018.html
 - 2018年12月04日10時28分の登録： ＼icchan　@icchan41543407＼ 返信先: @fukazawasさん\n\n篠田先生は名前と顔をだして呟いてはるから、いろいろ飛んでくるのでしょうね…　ボスは http://hirono2014sk.blogspot.com/2018/12/icchanicchan41543407-fukazawas.html
 - 2018年12月04日10時28分の登録： ＃icchan　@icchan41543407＃のツイート／2018-11-28_1051〜2018-12-04_1015／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月04日10時28分 http://hirono2014sk.blogspot.com/2018/12/icchanicchan415434072018-11-2810512018.html
 - 2019年12月30日11時56分の登録： ＼icchan　@icchan41543407＼被告人本人は閲覧までですものね(条文を確認しなおしました…)\n\nこれ、弁護人に検察から懲戒請求がとびそう(あがが http://hirono2014sk.blogspot.com/2019/12/icchanicchan41543407.html
 - 2020年04月08日12時10分の登録： ＼icchan　@icchan41543407＼あるいは専門外について思慮が及ばない人があ～だこ～だおっしゃりたいのでしょうね。\n\n…法律系でもそういうのは珍しくないかと http://hirono2014sk.blogspot.com/2020/04/icchanicchan41543407.html
```

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:01／2020/09/09 21:00 URL： https://twitter.com/kk_hirono/status/1303664843694551040 https://twitter.com/s_hirono/status/1303664671979757568  

> 2020-09-09-210039_icchan@icchan41543407国内の蒼黒両方好き。言動危険、定期忘れても守秘義務必須。日本のどっか2012年4月からTwitte.jpg https://t.co/ybrAb8Oh7e  

* 「普通の弁護士なら絶対に断言しないことを、断言する弁護士がいてそういう弁護士は営業上手として稼ぎまくっていたりする。」という深澤諭史弁護士のタイムラインで見かけたツイート，リツイートはない。

:CATEGORIES: 深澤諭史弁護士,都行志弁護士

@Miyako_Koji ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@Miyako_Koji）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW Miyako_Koji（弁護士 都 行志） 日時：2020/09/08 18:44 URL： https://twitter.com/Miyako_Koji/status/1303267955816321025  

> 普通の弁護士なら絶対に断言しないことを、断言する弁護士がいてそういう弁護士は営業上手として稼ぎまくっていたりする。断言口調の方が仕事が取れることは確か。それでも多くの弁護士は職業人の良心から、断言できないこと断言してはいけないことは断言しない。この一線を踏み越えるかどうかは大きい  

　> 普通の弁護士なら絶対に断言しないことを、断言する弁護士がいてそういう弁護士は営業上手として稼ぎまくっていたりする。断言口調の方が仕事が取れることは確か。それでも多くの弁護士は職業人の良心から、断言できないこと断言してはいけないことは断言しない。この一線を踏み越えるかどうかは

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜yurubenn（ゆる弁） 日時：2020-09-09 21:11／2020/09/08 22:56 URL： https://twitter.com/kk_hirono/status/1303667308871577602 https://twitter.com/yurubenn/status/1303331333200949248  

> @Miyako_Koji しまった、断言できないことの間違いだった！  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜norihikosatow1（佐藤憲彦（人工透析中の身体障害者1級社会保険労務士）） 日時：2020-09-09 21:11／2020/09/08 19:03 URL： https://twitter.com/kk_hirono/status/1303667414584799233 https://twitter.com/norihikosatow1/status/1303272758785134592  

> @Miyako_Koji 私たち社会保険労務士も弁護士の先生ほどプレッシャーあるわけじゃありませんが、私もあまり断定口調はできませんね。 万が一をどうしても考えますので。 断定口調できる心臓の方は尊敬しますよ。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜f3QuTT8s7lQnWvJ（忍冬は冬に負けない） 日時：2020-09-09 21:12／2020/09/09 17:54 URL： https://twitter.com/kk_hirono/status/1303667527847829504 https://twitter.com/f3QuTT8s7lQnWvJ/status/1303617645757960192  

> @Miyako_Koji 大半はいい弁護士さんです。 私がお世話になっている弁護士さんはとてもいい方です。 　 しかし、既にそのような方がおられるのが、とても残念です。 極一部と思いたいですが、ツイッターでもおられるのが怖いところです。  私の友人はネットで知り合った弁護士に騙されました。 皆様もお気をつけて。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜f3QuTT8s7lQnWvJ（忍冬は冬に負けない） 日時：2020-09-09 21:12／2020/09/09 17:54 URL： https://twitter.com/kk_hirono/status/1303667527847829504 https://twitter.com/f3QuTT8s7lQnWvJ/status/1303617645757960192  

> @Miyako_Koji 大半はいい弁護士さんです。 私がお世話になっている弁護士さんはとてもいい方です。 　 しかし、既にそのような方がおられるのが、とても残念です。 極一部と思いたいですが、ツイッターでもおられるのが怖いところです。  私の友人はネットで知り合った弁護士に騙されました。 皆様もお気をつけて。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜omorichan0922（Omorichan56🏉） 日時：2020-09-09 21:12／2020/09/09 20:10 URL： https://twitter.com/kk_hirono/status/1303667684140224512 https://twitter.com/omorichan0922/status/1303651902710710272  

> @Miyako_Koji 大事な一線やと思います。 けどね、貴方はどうか知らないけど、就く側によって主張が180度変わるでしょ。それが仕事やと思うけど、理解も信用も出来ない。 違いますか？  

- TW motokeso（モトケソ） 日時： 2020/09/09 10:10 URL： https://twitter.com/motokeso/status/1303500952398249989  

> @Miyako_Koji @yomimate 少し違う話題ですみません。  
> 難関である司法試験を勝ち抜いた立派な弁護士先生方からすると、このような弁護士の発言は職業人の良心には引っかからない当然のものなのでしょうか？ https://t.co/PpR1syTJIh  

　2,3日前から更新が止まっていると，数時間前にも確認していたモトケンこと矢部善朗弁護士（京都弁護士会）のTwitterタイムラインですが，11時間前として都行志弁護士のツイートへの返信ツイートが確認されました。

* 見たことのないTwitterの異変と思った最中，完全に欲望の暴走，狂った異常性を確信したモトケンこと矢部善朗弁護士（京都弁護士会）の一連のツイート

:CATEGORIES: モトケンこと矢部善朗弁護士（京都弁護士会）

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜tebasakitoriri（須賀原洋行 講談社まんが学術文庫カミュ『異邦人』カフカ『変身』発売中） 日時：2020-09-09 21:53／2020/09/05 03:31 URL： https://twitter.com/kk_hirono/status/1303677822569820160 https://twitter.com/tebasakitoriri/status/1301951147255578624  

> こういうアカウント作ると、モトケンさん @motoken_tw に訴えられないか…… https://t.co/7SV5vc2fmd  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜gokkunsan（名前が決まらない） 日時：2020-09-09 21:53／2020/09/05 09:12 URL： https://twitter.com/kk_hirono/status/1303677834024554496 https://twitter.com/gokkunsan/status/1302036801763254273  

> @motoken_tw @tebasakitoriri こんなアカウントが… モトケンさんのアイコンって、モトケンさんが作った(誰かに依頼して作ってもらった？)ものなんですよね？  そうであれば、著作権を元にアイコンとして勝手に使用するのをやめるように言えそうに思いますが…  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-09 21:53／2020/09/09 21:35 URL： https://twitter.com/kk_hirono/status/1303677853188325378 https://twitter.com/hirono_hideki/status/1303673423395135489  

> 2020年09月09日20時31分の登録： REGEXP：”正解病”／データベース登録済みツイート：2020年09月09日20時30分の記録：ユーザ・投稿：7／8件 https://t.co/1KhF8u7fPx  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-09 21:53／2020/09/09 21:35 URL： https://twitter.com/kk_hirono/status/1303677864986828801 https://twitter.com/hirono_hideki/status/1303673449756254208  

> 2020年09月09日21時04分の登録： ＼関東のどこかで細々経営の若手弁護士　@hdm1987＼相互フォローでもないし、勝手なこっちの印象のみだったけど、某弁護士には結構ガッカリした。 https://t.co/C37MukJj1S  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-09 21:53／2020/09/09 21:35 URL： https://twitter.com/kk_hirono/status/1303677882812653569 https://twitter.com/hirono_hideki/status/1303673476218150912  

> 2020年09月09日21時06分の登録： ＼弁護士 都 行志　@Miyako_Koji＼普通の弁護士なら絶対に断言しないことを、断言する弁護士がいてそういう弁護士は営業上手として稼ぎまくっていたりする。断言口調の https://t.co/pnI8Dkzh81  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-09 21:53／2020/09/09 21:35 URL： https://twitter.com/kk_hirono/status/1303677895915704320 https://twitter.com/hirono_hideki/status/1303673502591938561  

> 2020年09月09日21時16分の登録： ＼モトケソ　@motokeso＼このゾウさん、惜しかったな… https://t.co/CxGXyQcOaj  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-09 21:53／2020/09/09 21:36 URL： https://twitter.com/kk_hirono/status/1303677908846702592 https://twitter.com/hirono_hideki/status/1303673528978292738  

> 2020年09月09日21時17分の登録： ＼モトケソ　@motokeso＼刑事責任能力なしで無罪。 精神病患者はいくら人を◯しても無罪。 https://t.co/kFi9Z3GHBi  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-09 21:53／2020/09/09 21:36 URL： https://twitter.com/kk_hirono/status/1303677919370252288 https://twitter.com/hirono_hideki/status/1303673555352133632  

> 2020年09月09日21時20分の登録： ＼モトケソ　@motokeso＼白人店主の店が襲撃されても知らんぷりなのに、犯罪歴があって警官の警告を無視した黒人が撃たれたら抗議ですか？ 大坂なおみさん。 白人差別も大 https://t.co/xhMyoajnhi  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-09 21:53／2020/09/09 21:36 URL： https://twitter.com/kk_hirono/status/1303677930875183105 https://twitter.com/hirono_hideki/status/1303673581788782592  

> 2020年09月09日21時23分の登録： ＼モトケソ　@motokeso＼少し違う話題ですみません。 難関である司法試験を勝ち抜いた立派な弁護士先生方からすると、このような弁護士の発言は職業人の良心には引っかから https://t.co/3yx2IPJVNY  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-09 21:53／2020/09/09 21:36 URL： https://twitter.com/kk_hirono/status/1303677945647570944 https://twitter.com/hirono_hideki/status/1303673608187699202  

> 2020年09月09日21時28分の登録： ＼モトケソ　@motokeso＼そういえば、「この夏には東京はニューヨークのように感染爆発する！」とか言ってた評論家(笑)たちはどこに消えたんだ？？言いっぱなしか？無責任 https://t.co/PZChFRf2WV  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-09 21:53／2020/09/09 21:36 URL： https://twitter.com/kk_hirono/status/1303677961300705285 https://twitter.com/hirono_hideki/status/1303673634590842881  

> 2020年09月09日21時28分の登録： ＼モトケソ　@motokeso＼だからどうした。はしご酒してたんだろうが。 https://t.co/aIqg12Ni2U  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-09 21:53／2020/09/09 21:36 URL： https://twitter.com/kk_hirono/status/1303677973728428032 https://twitter.com/hirono_hideki/status/1303673660952047621  

> 2020年09月09日21時30分の登録： ＼モトケソ　@motokeso＼返信先:  @YahooNewsTopics さん だからどうした。はしご酒してたんだろうが。 https://t.co/HeVCMgdw3S  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-09 21:53／2020/09/09 21:45 URL： https://twitter.com/kk_hirono/status/1303677999540133888 https://twitter.com/hirono_hideki/status/1303675992972562433  

> 2020年09月09日21時44分の登録： ＼モトケソ　@motokeso＼返信先:  @nebukuro1030 さん そんなもん知ってますよ。バズったら通知きまくる奴でしょ。 それ、いいねでも通知きますよね。  https://t.co/mgAP2bE4Bq  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-09 21:53／2020/09/09 21:45 URL： https://twitter.com/kk_hirono/status/1303678007832227840 https://twitter.com/hirono_hideki/status/1303676019325284353  

> 2020年09月09日21時45分の登録： ＼モトケソ　@motokeso＼え、引用RTやめろ？何ですかそれ…何の権利があって言ってるのですか？ もし私が勝手にあなたのツイートのスクショを撮って貼り付けたとかで文句 https://t.co/CA5qsc7cst  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:55／2020/09/09 21:25 URL： https://twitter.com/kk_hirono/status/1303678333205372928 https://twitter.com/s_hirono/status/1303670915050295296  

> 2020-09-09-210516_深澤諭史さんがリツイート￼Hiro　粒クリ×プレシードベンチャー@Hiro_MD_MBA·6時間これは医者もそうですね.jpg https://t.co/zFdLWVpxcx  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:55／2020/09/09 21:25 URL： https://twitter.com/kk_hirono/status/1303678343972151296 https://twitter.com/s_hirono/status/1303670988018561024  

> 2020-09-09-210535_弁護士　都　行志@Miyako_Koji普通の弁護士なら絶対に断言しないことを、断言する弁護士がいてそういう弁護士は営業上手として稼ぎまくっ.jpg https://t.co/pd0e7nfZSD  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:55／2020/09/09 21:26 URL： https://twitter.com/kk_hirono/status/1303678359285587969 https://twitter.com/s_hirono/status/1303671060869464064  

> 2020-09-09-211532_モトケソ@motokeso返信先：　@Miyako_Kojiさん,　@yomimateさん少し違う話題ですみません。難関である司法試験を勝ち.jpg https://t.co/4ymMXdXjhL  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:55／2020/09/09 21:26 URL： https://twitter.com/kk_hirono/status/1303678374578065409 https://twitter.com/s_hirono/status/1303671133686755330  

> 2020-09-09-211616_￼モトケソ@motokeso·10分このゾウさん、惜しかったな….jpg https://t.co/AiBxZD3Qow  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:55／2020/09/09 21:26 URL： https://twitter.com/kk_hirono/status/1303678385856471042 https://twitter.com/s_hirono/status/1303671206504062979  

> 2020-09-09-211706_モトケソ@motokeso·3時間刑事責任能力なしで無罪。精神病患者はいくら人を◯しても無罪。.jpg https://t.co/B8mALhrUn5  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:55／2020/09/09 21:27 URL： https://twitter.com/kk_hirono/status/1303678401543196672 https://twitter.com/s_hirono/status/1303671279212404736  

> 2020-09-09-211807_モトケソ@motokeso返信先：　@nhk_newsさんまぁ、この女性は本当に被害者だとしても、他の悪い奴らがいくらでも被害者になりすます.jpg https://t.co/wf83n3JmSt  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:55／2020/09/09 21:27 URL： https://twitter.com/kk_hirono/status/1303678418282659840 https://twitter.com/s_hirono/status/1303671352193241088  

> 2020-09-09-211834_モトケソ@motokeso返信先：　@3kan_nnさん？私より前のリプでもあなたは宛先に入ってたけど何も言ってないのに、なぜ急に言うように.jpg https://t.co/kNmnE1ozlv  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:55／2020/09/09 21:27 URL： https://twitter.com/kk_hirono/status/1303678431683473411 https://twitter.com/s_hirono/status/1303671425027330051  

> 2020-09-09-211934_モトケソ@motokeso返信先：　@Sankei_newsさん性犯罪者への対処として、去勢　or　GPS埋め込み必須を早く実現してくれ。午.jpg https://t.co/jTBqNAUx2o  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:55／2020/09/09 21:28 URL： https://twitter.com/kk_hirono/status/1303678444325150721 https://twitter.com/s_hirono/status/1303671497756520448  

> 2020-09-09-212037_モトケソ@motokeso白人店主の店が襲撃されても知らんぷりなのに、犯罪歴があって警官の警告を無視した黒人が撃たれたら抗議ですか？大坂なお.jpg https://t.co/HRBjr0JF8I  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:55／2020/09/09 21:28 URL： https://twitter.com/kk_hirono/status/1303678456501137414 https://twitter.com/s_hirono/status/1303671570590625797  

> 2020-09-09-212314_￼モトケソ@motokeso·11時間少し違う話題ですみません。難関である司法試験を勝ち抜いた立派な弁護士先生方からすると、このような弁護士.jpg https://t.co/tuT15R6hH6  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:55／2020/09/09 21:28 URL： https://twitter.com/kk_hirono/status/1303678469356748802 https://twitter.com/s_hirono/status/1303671643407970305  

> 2020-09-09-212334_モトケソ@motokeso·12時間誤魔化すんじゃないよ…私の指摘は、あなたの「1人で何票でも入れる事が出来るので、民意なんか全く反映しませ.jpg https://t.co/9G9jnZq0ya  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:55／2020/09/09 21:28 URL： https://twitter.com/kk_hirono/status/1303678485005697024 https://twitter.com/s_hirono/status/1303671716497907712  

> 2020-09-09-212403_モトケソ@motokeso·9月8日アンタは古谷に踊らされてるんやで。.jpg https://t.co/ONszttKQQ9  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:55／2020/09/09 21:29 URL： https://twitter.com/kk_hirono/status/1303678496565125122 https://twitter.com/s_hirono/status/1303671789994651649  

> 2020-09-09-212422_モトケソ@motokeso·9月8日アンタ、古谷の思うツボだよ。.jpg https://t.co/9fKaci8CA7  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:55／2020/09/09 21:29 URL： https://twitter.com/kk_hirono/status/1303678511849193474 https://twitter.com/s_hirono/status/1303671863093071873  

> 2020-09-09-212445_モトケソ@motokeso·9月8日貪欲ですね。テレビで共演した時から、完全にロックオン。.jpg https://t.co/5XBAh9ivIX  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:55／2020/09/09 21:29 URL： https://twitter.com/kk_hirono/status/1303678524058812416 https://twitter.com/s_hirono/status/1303671935746727936  

> 2020-09-09-212517_モトケソ@motokeso·9月8日小6の小島瑠璃子さんへ。.jpg https://t.co/M01vLNicrG  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:55／2020/09/09 21:30 URL： https://twitter.com/kk_hirono/status/1303678539296776192 https://twitter.com/s_hirono/status/1303672008413077504  

> 2020-09-09-212529_モトケソ@motokeso返信先：　@Haruka_Hanasakiさん,　@tsuisokuさん貪欲ですね。テレビで共演した時から、完全に.jpg https://t.co/PEiMpXEAhN  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:56／2020/09/09 21:31 URL： https://twitter.com/kk_hirono/status/1303678552458452992 https://twitter.com/s_hirono/status/1303672342699106304  

> 2020-09-09-212621_モトケソ@motokeso返信先：　@gokkunsanさんこのアイコンは、その人が作ったりしたものでは全くないのですよ。関係ない作者様がい.jpg https://t.co/5evX43zxAy  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:56／2020/09/09 21:31 URL： https://twitter.com/kk_hirono/status/1303678566840836097 https://twitter.com/s_hirono/status/1303672415252176896  

> 2020-09-09-212947_モトケソ@motokeso返信先：　@YahooNewsTopicsさんだからどうした。はしご酒してたんだろうが。午後10：42　·　202.jpg https://t.co/CSv5HZoC9S  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:56／2020/09/09 21:31 URL： https://twitter.com/kk_hirono/status/1303678578639294464 https://twitter.com/s_hirono/status/1303672487922655233  

> 2020-09-09-213111_モトケソ@motokeso·8月14日女性の方が量が少なかったら少なかったで「差別するな！」っていいそう….jpg https://t.co/eCZmVfoVfr  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:56／2020/09/09 21:35 URL： https://twitter.com/kk_hirono/status/1303678597857648640 https://twitter.com/s_hirono/status/1303673296106352644  

> 2020-09-09-213411_％@motokeso　モトケソ％モトケソ@motokeso·7月27日そりゃ嫌だろう。マスコミは、そういう「人の気持ち」が本当にわからないの.jpg https://t.co/1n89IPbuOR  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:56／2020/09/09 21:35 URL： https://twitter.com/kk_hirono/status/1303678611782660098 https://twitter.com/s_hirono/status/1303673368600670208  

> 2020-09-09-213423_モトケソ@motokeso·7月18日三浦春馬さんの自殺の原因を、まだ何の確証もないのに誹謗中傷にしたがってる奴らってなんなの？誹謗中傷を原.jpg https://t.co/9XRXzOz0Dh  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:56／2020/09/09 21:35 URL： https://twitter.com/kk_hirono/status/1303678625149931520 https://twitter.com/s_hirono/status/1303673441489281027  

> 2020-09-09-213450_モトケソ@motokeso息抜きツイート用　元鍵盤ハーモニカ奏者日本2020年4月からTwitterを利用しています47　フォロー中20　フ.jpg https://t.co/T17xSCNZDD  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:56／2020/09/09 21:43 URL： https://twitter.com/kk_hirono/status/1303678637741236230 https://twitter.com/s_hirono/status/1303675515677503488  

> 2020-09-09-213926_モトケソ@motokeso·9月8日返信先：　@DMGuerrillaさん,　@takeshi_tsurunoさん,　@TomoMachiさ.jpg https://t.co/Iat97I8gte  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:56／2020/09/09 21:44 URL： https://twitter.com/kk_hirono/status/1303678651758596096 https://twitter.com/s_hirono/status/1303675588754907136  

> 2020-09-09-214005_モトケソ@motokeso·9月7日まぁ、急に逃げたら怪しむわな。ちょっとやり過ぎだとは思うけど。.jpg https://t.co/5ehFOOA8O4  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:56／2020/09/09 21:44 URL： https://twitter.com/kk_hirono/status/1303678666245693440 https://twitter.com/s_hirono/status/1303675661509226496  

> 2020-09-09-214030_モトケソ@motokeso·9月6日これだから野球脳は。.jpg https://t.co/Ymp7MBgOe5  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:56／2020/09/09 21:44 URL： https://twitter.com/kk_hirono/status/1303678681374625793 https://twitter.com/s_hirono/status/1303675734452441089  

> 2020-09-09-214053_モトケソ@motokeso·9月5日大澤昇平さんにも謝られたほうがよろしいかと.jpg https://t.co/DPwu4TjTsW  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:56／2020/09/09 21:45 URL： https://twitter.com/kk_hirono/status/1303678694611775488 https://twitter.com/s_hirono/status/1303675807454224384  

> 2020-09-09-214117_モトケソ@motokeso·9月4日こういう風に「緊急事態宣言しないと感染爆発するぞ！」と言ってた人々も、すっかり沈黙。当たらなくても責任は.jpg https://t.co/4uiPcIPWaJ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:56／2020/09/09 21:45 URL： https://twitter.com/kk_hirono/status/1303678709220519937 https://twitter.com/s_hirono/status/1303675880468705280  

> 2020-09-09-214136_モトケソ@motokeso·9月4日GoToどころか、こうやって「緊急事態宣言出さないと感染爆発するぞ！」ってドヤ顔で言ってた奴らの予想も大.jpg https://t.co/dkvaCZptDm  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:56／2020/09/09 21:45 URL： https://twitter.com/kk_hirono/status/1303678723426672641 https://twitter.com/s_hirono/status/1303675953265008641  

> 2020-09-09-214157_2128405￼モトケソ@motokeso·9月4日単純に、本来左に寄せておくべき方を右に、右に寄せておくべき方を左に寄せてしまうとこうなる.jpg https://t.co/LNfJGKsGmy  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:56／2020/09/09 21:46 URL： https://twitter.com/kk_hirono/status/1303678736647122945 https://twitter.com/s_hirono/status/1303676025927208960  

> 2020-09-09-214229_モトケソ@motokeso·9月4日自分…滑り倒してるで。大丈夫か？.jpg https://t.co/4X9QWFy1rn  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:56／2020/09/09 21:46 URL： https://twitter.com/kk_hirono/status/1303678749515214848 https://twitter.com/s_hirono/status/1303676098509561856  

> 2020-09-09-214250_モトケソ@motokeso·9月3日返信先：　@kohei_uRu_さん,　@HaraYassaさん不倫されて奥様とお子様たちが傷つくことは.jpg https://t.co/h8XxRPK3Fi  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:56／2020/09/09 21:46 URL： https://twitter.com/kk_hirono/status/1303678777935814656 https://twitter.com/s_hirono/status/1303676171213705218  

> 2020-09-09-214305_モトケソ@motokeso·9月3日東出は叩きまくってたのに、原泰久には擁護コメントが多いのを見ると、多くの人が行為の是非よりも「ソイツが自.jpg https://t.co/Fqt8MX9AJ6  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:56／2020/09/09 21:46 URL： https://twitter.com/kk_hirono/status/1303678787138191360 https://twitter.com/s_hirono/status/1303676243921924098  

> 2020-09-09-214331_モトケソ@motokeso·9月3日「わたし…ムカつきます！」.jpg https://t.co/GNKYqMc63E  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 21:57／2020/09/09 21:47 URL： https://twitter.com/kk_hirono/status/1303678803210727425 https://twitter.com/s_hirono/status/1303676316634345473  

> 2020-09-09-214345_モトケソ@motokeso·9月3日返信先：　@KnPDWtcsy4uM4CVさん,　@realdea28955056さん,　@YahooN.jpg https://t.co/tRTwNGV25V  

　何か事情があって，3日ほど更新がなく，このまま小倉秀夫弁護士のように事実上の消滅となる可能性もあると考えていたモトケンこと矢部善朗弁護士（京都弁護士会）のTwitterタイムラインになりますが，いきなり思わぬ発見が連続しました。

　一応の記録と考えていたスクリーンショットになりますが，モトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインは，更新が滞っていたはずなのです。次の記録があります。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 22:01／2020/09/09 09:40 URL： https://twitter.com/kk_hirono/status/1303679863849541633 https://twitter.com/s_hirono/status/1303493407986257920  

> 2020-09-09-082047_モトケン（@motoken_tw）さんの返信があるツイート　／　Twitter.jpg https://t.co/gFyTaxDNsy  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 22:01／2020/09/09 00:23 URL： https://twitter.com/kk_hirono/status/1303679896648953857 https://twitter.com/s_hirono/status/1303353232593317888  

> 2020-09-09-002040_モトケン@motoken_tw·9月5日連ツイを全部読みましょう。.jpg https://t.co/VbbAINMtnR  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 22:01／2020/09/07 21:32 URL： https://twitter.com/kk_hirono/status/1303679927456129024 https://twitter.com/s_hirono/status/1302947929011810304  

> 2020-09-07-195803_モトケン@motoken_tw·9月5日連ツイを全部読みましょう。.jpg https://t.co/BMTZjRrrgc  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 22:01／2020/09/07 11:05 URL： https://twitter.com/kk_hirono/status/1303679958158438400 https://twitter.com/s_hirono/status/1302790008445624320  

> 2020-09-06-220828_モトケン@motoken_tw矢部善朗。元検事の弁護士（京都弁護士会）です。　アイコン（作者は　Y_Coronaさん）は単なる趣味（＾＾；　.jpg https://t.co/Zb8W6xMI8k  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 22:01／2020/09/06 08:07 URL： https://twitter.com/kk_hirono/status/1303679989661876224 https://twitter.com/s_hirono/status/1302382944250519552  

> 2020-09-05-220547_モトケン@motoken_tw返信先：　@xY1213Hxさん連ツイ全部嫁。同じことを言うのに疲れた。.jpg https://t.co/Zjg1Jle8y7  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 22:01／2020/09/04 23:44 URL： https://twitter.com/kk_hirono/status/1303680017818292225 https://twitter.com/s_hirono/status/1301893782426664960  

> 2020-09-04-232041_モトケン@motoken_tw＞同性愛は同意のある性愛を想定可能でありその限りにおいて加害性は無いが、同性愛も同意のない性的行為が想定可能で.jpg https://t.co/6n8UG6yMPT  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 22:02／2020/09/03 09:00 URL： https://twitter.com/kk_hirono/status/1303680089385656320 https://twitter.com/s_hirono/status/1301309019156410369  

> 2020-09-03-083453_モトケン@motoken_tw·45分欲望や感情を理性で制御するというのは人間だけに許された特権である、と思うのだがその特権を放棄している人.jpg https://t.co/9GoRGXdUQW  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 22:02／2020/09/03 09:00 URL： https://twitter.com/kk_hirono/status/1303680117244194816 https://twitter.com/s_hirono/status/1301308946498482177  

> 2020-09-02-222927_モトケン@motoken_tw·14時間「小児に手を出したことがない（自分の欲望を理性で制御している）小児性愛者を社会から排除しろ」と公言し.jpg https://t.co/1n4tzMaMjP  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 22:02／2020/09/03 08:59 URL： https://twitter.com/kk_hirono/status/1303680142640775168 https://twitter.com/s_hirono/status/1301308874071265280  

> 2020-09-02-222700_モトケン@motoken_tw·3時間この人、かなり危ない人ですね。危ない人だということは十分周知されたと思いますので、今後は無視するのがよ.jpg https://t.co/IC7Ymx3Oy9  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 22:02／2020/09/03 08:58 URL： https://twitter.com/kk_hirono/status/1303680174374793218 https://twitter.com/s_hirono/status/1301308583435329538  

> 2020-09-02-195608_感熱紙（疑似太陽炉）さんがリツイートモトケン@motoken_tw·4時間この人、なんでこんなにいきり立ってるんですかね？.jpg https://t.co/wn0znxkmus  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 22:02／2020/09/02 13:25 URL： https://twitter.com/kk_hirono/status/1303680241483669504 https://twitter.com/s_hirono/status/1301013358250921984  

> 2020-09-02-113741_モトケン@motoken_tw·36分返信先：　@ene_100_t_Anさんそりゃ、根拠のない主張や批判や誹謗中傷は聞く気になりませんね。.jpg https://t.co/1y5BRKpyCb  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 22:02／2020/09/01 16:15 URL： https://twitter.com/kk_hirono/status/1303680269497462785 https://twitter.com/s_hirono/status/1300693629850193920  

> 2020-09-01-133802_モトケン@motoken_tw·20分返信先：　@soyao0さん,　@choco_papico_1さん男性の性行為の３パターン１　魅力的な.jpg https://t.co/uzJqVcAp6B  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 22:02／2020/09/01 16:13 URL： https://twitter.com/kk_hirono/status/1303680292801056769 https://twitter.com/s_hirono/status/1300693339142930434  

> 2020-09-01-093048_モトケン@motoken_tw·9分「合意の上で性行為をしたい」＝「合意なしに性交するとレイプになる」→レイプにならないよう→合意を得よう結.jpg https://t.co/WoYBuzS7bg  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 22:03／2020/09/01 16:13 URL： https://twitter.com/kk_hirono/status/1303680321783619584 https://twitter.com/s_hirono/status/1300693266153664512  

> 2020-09-01-091552_モトケン@motoken_tw·27分そういう思い込みの決めつけをしていて、リアルの社会生活で困ってませんか？もし困ってるのなら、あなたこそ.jpg https://t.co/VRHQgPVHvg  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 22:03／2020/08/31 22:14 URL： https://twitter.com/kk_hirono/status/1303680356042682368 https://twitter.com/s_hirono/status/1300421686886428672  

> 2020-08-31-135824_モトケンさんがリツイート感熱紙（疑似太陽炉）@thermalpaper00·2時間自身の性的嗜好を口に出すことも別に犯罪行為でも何でもないけ.jpg https://t.co/9Rt1CnmfuN  

* 「高松市で6歳と3歳の姉妹が車内に放置され、熱中症とみられる症状で死亡した。」に対し，「だからどうした。はしご酒してたんだろうが。」というモトケンこと矢部善朗弁護士（京都弁護士会）のツイート

:CATEGORIES: モトケンこと矢部善朗弁護士（京都弁護士会）

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜YahooNewsTopics（Yahoo!ニュース） 日時：2020-09-09 22:07／2020/09/07 22:35 URL： https://twitter.com/kk_hirono/status/1303681411803611138 https://twitter.com/YahooNewsTopics/status/1302963645953970176  

> 【放置死 車内で心臓マッサージ】 https://t.co/ew11RtnGR9  高松市で6歳と3歳の姉妹が車内に放置され、熱中症とみられる症状で死亡した。この事件で保護責任者遺棄致死容疑で逮捕された母親が、車の後部座席でぐったりする娘に心臓マッサージをしている姿が目撃されていた。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜YahooNewsTopics（Yahoo!ニュース） 日時：2020-09-09 22:07／2020/09/07 22:35 URL： https://twitter.com/kk_hirono/status/1303681411803611138 https://twitter.com/YahooNewsTopics/status/1302963645953970176  

> 【放置死 車内で心臓マッサージ】 https://t.co/ew11RtnGR9  高松市で6歳と3歳の姉妹が車内に放置され、熱中症とみられる症状で死亡した。この事件で保護責任者遺棄致死容疑で逮捕された母親が、車の後部座席でぐったりする娘に心臓マッサージをしている姿が目撃されていた。  

　さすがにここまで狂った異常性とは考えていなかったモトケンこと矢部善朗弁護士（京都弁護士会）のツイートで，やはり弁護士妖怪モトケン大王だと感じました。

* 「京アニ放火殺人事件で、京都地検は9日」に対して，「刑事責任能力なしで無罪。精神病患者はいくら人を◯しても無罪。」というモトケンこと矢部善朗弁護士（京都弁護士会）のツイート

:CATEGORIES: モトケンこと矢部善朗弁護士（京都弁護士会）,精神鑑定

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜YahooNewsTopics（Yahoo!ニュース） 日時：2020-09-09 22:11／2020/09/09 17:42 URL： https://twitter.com/kk_hirono/status/1303682525504577536 https://twitter.com/YahooNewsTopics/status/1303614686743556096  

> 【京アニ容疑者 鑑定留置を延長】 https://t.co/n2SQN7Cmzx  京アニ放火殺人事件で、京都地検は9日、殺人などの容疑で逮捕された容疑者の鑑定留置期限を12月11日まで約3カ月間延長すると明らかにした。刑事責任能力を調べるため、医師による精神鑑定が続くことになる。  

@motokeso ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@motokeso）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW motokeso（モトケソ） 日時：2020/09/09 18:00 URL： https://twitter.com/motokeso/status/1303619184694145024  

> @YahooNewsTopics 刑事責任能力なしで無罪。  
> 精神病患者はいくら人を◯しても無罪。  

　ここまで狂った弁護士が京都弁護士会，日弁連には放置されているのかと思ったのが，まずの感想です。京都弁護士会　広報委員会　@KBAsns 日本弁護士連合会（日弁連）@JFBAsns

* 再び2020年9月5日で更新が止まっていると確認したモトケンこと矢部善朗弁護士（京都弁護士会）のTwitterタイムラインのツイート

:CATEGORIES: モトケンこと矢部善朗弁護士（京都弁護士会）

```
(py37_env) a66@a66-XTe:~% tun motoken_tw 10
TW motoken_tw（モトケン） 日時： 2020-09-05 16:19 URL： https://twitter.com/motoken_tw/status/1302144271730966530
> @fubyulas 幼児には欲情しません。
> あなた、するんですか？あなたがするから私にそういう質問をしたんでしょ？

TW motoken_tw（モトケン） 日時： 2020-09-05 16:20 URL： https://twitter.com/motoken_tw/status/1302144479919398913
> @T4jC6R2bR83Dn3x ネタ垢です（ｷｯﾊﾟﾘ

TW motoken_tw（モトケン） 日時： 2020-09-05 16:25 URL： https://twitter.com/motoken_tw/status/1302145818745425922
> @godspeedtetsuma ｢社会倫理に反するという問題｣は、まさに社会倫理という規範に反するかどうかという規範的評価の問題なのだが、この人、何を言ってるんだろう？

TW motoken_tw（モトケン） 日時： 2020-09-05 16:26 URL： https://twitter.com/motoken_tw/status/1302145966607224834
> @syakkurigaderu 反論ではない、ということについて了解。

TW motoken_tw（モトケン） 日時： 2020-09-05 16:26 URL： https://twitter.com/motoken_tw/status/1302146177689817088
> @T4jC6R2bR83Dn3x 今のところの評価としては、違うんじゃないですか。

TW motoken_tw（モトケン） 日時： 2020-09-05 16:27 URL： https://twitter.com/motoken_tw/status/1302146350847389696
> @fubyulas ＞あなたがするから私にそういう質問をしたんでしょ？

TW motoken_tw（モトケン） 日時： 2020-09-05 16:33 URL： https://twitter.com/motoken_tw/status/1302147942627721216
> @xY1213Hx 連ツイ全部嫁。
> 同じことを言うのに疲れた。

TW motoken_tw（モトケン） 日時： 2020-09-05 16:35 URL： https://twitter.com/motoken_tw/status/1302148396040376322
> @fubyulas 欲情の点は私の誤読。撤回します。

TW motoken_tw（モトケン） 日時： 2020-09-05 16:39 URL： https://twitter.com/motoken_tw/status/1302149257051299840
> @fubyulas ＞「『幼い』に価値を感じて欲情することを恥じずに公言できる世の中になっている」
> 
> この点については、そういう世の中にはなっていないと思います。
> 再掲
> https://t.co/jQ0OaAaoGL
> https://t.co/nZE66nTPmp

TW motoken_tw（モトケン） 日時： 2020-09-05 16:46 URL： https://twitter.com/motoken_tw/status/1302150988237742083
> @P3rZI1SXporVAJt @joytamachan 連ツイを全部読みましょう。
```

- TW s_hirono（非常上告-最高検察庁御中_ツイッター） 日時： 2020/09/09 21:31 URL： https://twitter.com/s_hirono/status/1303672415252176896  

> 2020-09-09-212947_モトケソ@motokeso返信先：　@YahooNewsTopicsさんだからどうした。はしご酒してたんだろうが。午後10：42　·　202.jpg https://t.co/CSv5HZoC9S  

　どう見ても2020年9月7日午後10時42分として，記録されているモトケンこと矢部善朗弁護士（京都弁護士会）のツイートですが，とても不思議な現象としてTwitterに出ているようです。

 - 2020年09月09日22時21分の登録： ＃モトケン　@motoken_tw＃のツイート／2020-09-02_1442〜2020-09-05_1646／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2020年09月09日22時21分 http://hirono2014sk.blogspot.com/2020/09/motokentw2020-09-0214422020-09.html

 - ツイート： motoken_tw（モトケン） 日時： 2020-09-05 16:46 URL： https://twitter.com/motoken_tw/status/1302150988237742083

> @P3rZI1SXporVAJt @joytamachan 連ツイを全部読みましょう

```
記録作成等の措置を講ずるべき弁護士・ジャーナリスト関連のツイート
基準となる注目のツイートを含む最新199件のツイート
2020-08-11 00：01から199件：最新2020-09-09 21：05という範囲（29日21時間4分）の取得
基準となる注目ツイートの位置と内容タイムラインの該当箇所に移動

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： ＼モトケソ　@motokeso＼返信先： @YahooNewsTopics さん だからどうした。はしご酒してたんだろうが。 http://hirono2014sk.blogspot.com/2020/09/motokeso-yahoonewstopics.html
```

　やはり9月5日以降として，9月7日に存在が確認され，スクリーンショットで記録したモトケンこと矢部善朗弁護士（京都弁護士会）の驚愕のツイートになります。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 22:35／2020/09/09 22:33 URL： https://twitter.com/kk_hirono/status/1303688420116455424 https://twitter.com/s_hirono/status/1303688077223686145  

> 2020-09-09-223307_モトケソ@motokeso返信先：　@YahooNewsTopicsさんだからどうした。はしご酒してたんだろうが。.jpg https://t.co/WpdSo6w7AI  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 22:35／2020/09/09 22:33 URL： https://twitter.com/kk_hirono/status/1303688436667174916 https://twitter.com/s_hirono/status/1303688004322557953  

> 2020-09-09-223250_モトケソ@motokeso·9月7日だからどうした。はしご酒してたんだろうが。.jpg https://t.co/yyCSdY3NLa  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 22:35／2020/09/09 22:19 URL： https://twitter.com/kk_hirono/status/1303688456636309505 https://twitter.com/s_hirono/status/1303684393936928769  

> 2020-09-09-221731_モトケン@motoken_tw·9月5日連ツイを全部読みましょう。.jpg https://t.co/lrx419Ta2F  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 22:35／2020/09/09 22:18 URL： https://twitter.com/kk_hirono/status/1303688485878919168 https://twitter.com/s_hirono/status/1303684321178316800  

> 2020-09-09-214453_モトケソ@motokeso·9月3日え、引用RTやめろ？何ですかそれ…何の権利があって言ってるのですか？もし私が勝手にあなたのツイートのスク.jpg https://t.co/oYsMDTPnmJ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-09 22:35／2020/09/09 22:18 URL： https://twitter.com/kk_hirono/status/1303688525385089024 https://twitter.com/s_hirono/status/1303684247866179587  

> 2020-09-09-214423_モトケソ@motokeso·9月3日返信先：　@nebukuro1030さんそんなもん知ってますよ。バズったら通知きまくる奴でしょ。それ、い.jpg https://t.co/iTcbNgLkCY  

