#+TODO: TODO EDITEING | DONE
* 「最近，法曹養成・弁護士業界で起きていることは，平成の司法改革の終わりを告げるものではないと思います。」という深澤諭史弁護士のツイート
  :LOGBOOK:
  CLOCK: [2020-07-08 水 09:25]--[2020-07-08 水 09:50] =>  0:25
  :END:

:CATEGORIES: 深澤諭史弁護士

〉〉〉：Emacs： 2020-07-08（水曜日）09：25　 〉〉〉

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2020/07/08 07:59 URL： https://twitter.com/fukazawas/status/1280637572742475776  

> 最近，法曹養成・弁護士業界で起きていることは，平成の司法改革の終わりを告げるものではないと思います。  
> 終わりの始まりですらないとも思います。  
> でも，始まりの終わりかもしれません。  
> （・∀・；）  

　いろいろと考えさせられるところのある深澤諭史弁護士のツイートですが，「でも，始まりの終わりかもしれません。」というのがいまひとつ理解ができません。思い描く，あるべき理想郷，「弁護士パラダイス」の世界観を前提にしているのでしょう。

　最近もぽつぽつと見かけているように思うのですが，深澤諭史弁護士にはなんとか黙示録というハッシュタグがあります。昭和50年代の終わり頃だと記憶するのですが，「地獄の黙示録」とかいう映画の宣伝をやたらと目にしたという記憶があります。内容は全く知りません。

〈〈〈：Linux Emacs： 2020-07-08（水曜日）09：38 　〈〈〈

* 平成の司法制度改革の終わりを告げるという，深澤諭史弁護士の「司法黙示録」という主にハッシュタグ付きツイートの記録資料　＃司法黙示録
  :LOGBOOK:
  CLOCK: [2020-07-08 水 13:02]--[2020-07-08 水 17:29] =>  4:27
  CLOCK: [2020-07-08 水 09:50]
  :END:

:CATEGORIES: 深澤諭史弁護士,司法制度改革

〉〉〉：Emacs： 2020-07-08（水曜日）09：50　 〉〉〉

```
➜  ~ dp -p |grep 司法制度改革
 - 2014年11月15日23時28分の登録： 司法制度改革で弁護士の不祥事が、という人が弁護士にいるけど、主観的に稼げ\nなくなったら不正を働くような人たちがそろっていた業界だったというのだろう\nか？／坂本正幸弁護士 http://hirono2014sk.blogspot.com/2014/11/blog-post_65.html
 - 2014年12月06日07時41分の登録： 深澤諭史弁護士がリツイートしていた主に司法制度改革に関するツイート\n＿2014年12月4日のまとめ／深澤諭史弁護士 http://hirono2014sk.blogspot.com/2014/12/2014124.html
 - 2017年08月04日01時48分の登録： mackckckck（弁護士ワック）の”この姿が標準モデルであるべきだし、司法制度改革前の弁護士はそうだったはずである。”というツイートの記録 http://hirono2014sk.blogspot.com/2017/08/mackckckck.html
 - 2017年08月04日01時57分の登録： mackckckck（弁護士ワック）の”弁護士会がポスト司法制度改革として如何なる弁護士自治を目指すのか。 ”というツイートの記録 http://hirono2014sk.blogspot.com/2017/08/mackckckck_4.html
 - 2017年10月08日09時02分の登録： ％@fukazawas　深澤諭史％（患者が）成仏理論(･∀･llll) #もし司法制度改革を医療界でやったら http://hirono2014sk.blogspot.com/2017/10/fukazawasllll.html
 - 2017年10月08日09時08分の登録： ％@fukazawas　深澤諭史％くじ引きで選ばれた一般人が参加して執刀することになる。 そのために，執刀前準備手続きを，本体の手術時間の何十倍もかけてする。 #もし司法制度改革を医療界でやったら http://hirono2014sk.blogspot.com/2017/10/fukazawas_92.html
 - 2017年10月12日06時52分の登録： ＼いわぽん　@yiwapon＼アディーレの件で引き継ぎ等がうまく行かずに混乱も生ずるかもしれないが、それもまた司法制度改革の成果 http://hirono2014sk.blogspot.com/2017/10/yiwapon_12.html
 - 2017年10月12日10時15分の登録： ＼深澤諭史　@fukazawas　RT：　@yiwapon＼アディーレの件で引き継ぎ等がうまく行かずに混乱も生ずるかもしれないが、それもまた司法制度改革の成果 http://hirono2014sk.blogspot.com/2017/10/fukazawasrtyiwapon_12.html
 - 2017年10月14日23時38分の登録： ＼弁護士渡邉恭子（なべきょう）＠過眠症　@wata_nabekyo_ko＼そういう弁護士に依頼しちゃって損する人が出るのも司法制度改革のうちだと捉えれば別に自由競争の範囲のうちだということなのだろう http://hirono2014sk.blogspot.com/2017/10/watanabekyoko.html
 - 2017年10月17日10時00分の登録： ＼のりあ　@Nolia__＼自由市場，競争原理を持ち込んだ司法制度改革の成果だねってなるし，それでも弁護士は社会正義の実現のため動くべきと言われると http://hirono2014sk.blogspot.com/2017/10/nolia_17.html
 - 2017年10月19日18時08分の登録： ＼とらきち　@torakiti0405＼これが平成の司法制度改革の結果なんだよなぁ。。。自由競争させて、消費者に自由に選ばせて、競争の結果で不利益 http://hirono2014sk.blogspot.com/2017/10/torakiti0405_19.html
 - 2017年10月30日09時20分の登録： データベース登録タグ：”##もし司法制度改革を医療界でやったら／2017年10月30日09時20分の記録15件）<br /> http://hirono2014sk.blogspot.com/2017/10/20171030092015.html
 - 2017年10月30日09時27分の登録： タグ：＼法務検察・石川県警察宛資料＼”##もし司法制度改革を医療界でやったら”／2017年10月30日09時27分の記録：15件）<br /> http://hirono2014sk.blogspot.com/2017/10/20171030092715.html
 - 2017年10月30日09時49分の登録： タグ：＼法務検察・石川県警察宛資料＼”##もし司法制度改革を医療界でやったら”／2017年10月30日09時49分の記録：34件）<br /> http://hirono2014sk.blogspot.com/2017/10/20171030094934.html
 - 2017年10月30日10時12分の登録： タグ：＼法務検察・石川県警察宛資料＼”##もし司法制度改革を医療界でやったら”／2017年10月30日10時11分の記録：37件<br /> http://hirono2014sk.blogspot.com/2017/10/20171030101137.html
 - 2017年11月13日09時43分の登録： ＼裁判員制度はいらないインコ　@nosaibaninko＼今度は司法制度改革そのものを題材にしてみようかとも思っています。こちらもまだ改良の余地ありですけど。お時間あると http://hirono2014sk.blogspot.com/2017/11/nosaibaninko.html
 - 2017年11月24日21時34分の登録： ＼霞 司郎㌥　@kasumi_shiro＼労働審判は、平成の司法制度改革で、ほぼ唯一成功したものと言われているなあ… http://hirono2014sk.blogspot.com/2017/11/kasumishiro_24.html
 - 2017年12月05日21時34分の登録： ＼Which　@which0623＼えっ司法制度改革やってたときの日弁連って法曹一元が実現するって思ってたの？？？ http://hirono2014sk.blogspot.com/2017/12/whichwhich0623.html
 - 2018年01月07日21時43分の登録： ＼向原総合法律事務所　弁護士向原　@harrier0516osk＼本当に拡大してる人は法曹人口増やせとか言わない。\n司法制度改革では「旧来型訴訟担当者」とか「国際的課題解 http://hirono2014sk.blogspot.com/2018/01/harrier0516osk_63.html
 - 2018年02月04日10時01分の登録： ＼村松 謙　@kmuramatsu＼但木先生、法教育協力的だし、良い人なんだが。。。＞論点：司法制度改革の今 - 毎日新聞 http://hirono2014sk.blogspot.com/2018/02/kmuramatsu_54.html
 - 2018年02月05日22時08分の登録： ＼とりろーる　@triroll33＼コインチェック弁護団は乱立してますが、ジャパンライフ弁護団は乱立してないわけですよ。 これが司法制度改革の結果なのかもしれませんね。 http://hirono2014sk.blogspot.com/2018/02/triroll33.html
 - 2018年02月10日01時22分の登録： ＼ぺぷち　@Alicandros＼\n\n教育なんて将来の人材を左右する点において自治の根幹なのに、法曹養成制度を国の司法制度改革にされるがままに放置しながら弁護士自治を語ら http://hirono2014sk.blogspot.com/2018/02/alicandros.html
 - 2018年02月12日03時56分の登録： ＼ぺぷち　@Alicandros＼自治の根幹なのに、法曹養成制度を国の司法制度改革にされるがままに放置しながら弁護士自治を語られてもねぇ http://hirono2014sk.blogspot.com/2018/02/alicandros_12.html
 - 2018年02月22日19時28分の登録： ＼とりろーる　@triroll33＼\n\n司法制度改革で多様な弁護士が誕生する理想世界を夢に描いていたとして、その多様な弁護士像を実現するには会費が高すぎるとは考えなかった http://hirono2014sk.blogspot.com/2018/02/triroll33_22.html
 - 2018年03月04日00時24分の登録： ＼弁護士わっく　@mackckckck＼確かに。 司法制度改革が望んだ姿ですよね。 司法制度改革推進論者はさぞかし喜んでいることでしょうね。 あーあ。 http://hirono2014sk.blogspot.com/2018/03/mackckckck_76.html
 - 2018年03月11日17時32分の登録： ＼いわぽん　@yiwapon＼朝日新聞嫌いな人は多いんだな。かくいう当職も司法制度改革絡みではさんざんクソ主張をし続けているからどうかと思って嫌々読んでいるが。 http://hirono2014sk.blogspot.com/2018/03/yiwapon_11.html
 - 2018年04月07日18時14分の登録： REGEXP：”司法制度改革”／深澤諭史（@fukazawas）の検索（2012-11-20〜2018-04-03／2018年04月07日18時14分の記録212件） http://hirono2014sk.blogspot.com/2018/04/regexpfukazawas2012-11-202018-04.html
 - 2018年04月26日14時45分の登録： ＼ながしま　@incubatorN0712＼\n\n今日の大学院では、司法制度改革と法教育の関係を話して議論しました。\n1件の返信 2件のリツイート 3 いいね\n http://hirono2014sk.blogspot.com/2018/04/incubatorn0712-1-2-3.html
 - 2018年06月07日18時03分の登録： ＼向原総合法律事務所　弁護士向原　@harrier0516osk＼司法制度改革って、医学界でいえば「不治の病だったものが撲滅された」的な何らかのエピソードを創出できたんで http://hirono2014sk.blogspot.com/2018/06/harrier0516osk_7.html
 - 2018年09月17日11時03分の登録： ＼中村剛（take-five）　@take___five＼司法制度改革の弁護士増員で淘汰されたのは、腕の悪い弁護士ではなく、経営のことを全く考えない弁護士、経営について何 http://hirono2014sk.blogspot.com/2018/09/take-fivetakefive_17.html
 - 2018年09月23日09時28分の登録： ＼たろう teacher　@tomo_law_＼まあ、司法制度改革とロースクール創設は、権力者側が弁護士自治を崩壊させるための政策だ という「陰謀論」に従えば、司法制度改 http://hirono2014sk.blogspot.com/2018/09/teachertomolaw_23.html
 - 2018年09月29日22時53分の登録： ＼及川智志　@ShminLo＼ツイッターへの投稿について東京高裁から懲戒を申し立てられている岡口基一裁判官が共同通信に寄稿。「司法制度改革で弁護士余剰時代が到来し、弁護士 http://hirono2014sk.blogspot.com/2018/09/shminlo.html
 - 2019年02月03日21時40分の登録： ＼おちゃべん　@pigbengoshi＼まあ、司法制度改革も世間知らずのアホな学者が噛んでいだと思うと脱力感よね、 http://hirono2014sk.blogspot.com/2019/02/pigbengoshi.html
 - 2019年02月05日23時53分の登録： ＼弁護士7286　@jmjhjmwtad＼司法制度改革の本質は、自分たちをバカにして授業に出なかった学生（司法試験受験生）たちへの学者による復讐。だから、学者は異常に弁護 http://hirono2014sk.blogspot.com/2019/02/7286jmjhjmwtad.html
 - 2019年02月05日23時53分の登録： ＼リーチ一発ツモ裏１　@luckymangan＼司法制度改革の何が凄いかって、弁護士の数だけ増やして困窮させる現状なら、司法試験の合格者増やしてそれ以外の制度変えなくてよ http://hirono2014sk.blogspot.com/2019/02/luckymangan.html
 - 2019年02月06日14時28分の登録： ＼てらやさん☆　@terayasan＼すごいなー　司法制度改革を実行した人たちが目標とした合格率に着々と近づいているなー　実現力だなー http://hirono2014sk.blogspot.com/2019/02/terayasan.html
 - 2019年02月07日00時13分の登録： ＼でまっちー　@demacchiee＼覚えていますか。司法制度改革とロー導入の意義。多様な人材を法曹にするためじゃなかったんですか。\n\n今年のロー入学者1600何人の特性 http://hirono2014sk.blogspot.com/2019/02/demacchiee-1600.html
 - 2019年02月19日10時36分の登録： ＼弁護士 中村憲昭　@nakanori930＼深澤諭史さんがリツイート＞　弁護士中村憲昭（@nakanori930）：　司法制度改革の失敗を糊塗しつつ法科大学院を延命さ http://hirono2014sk.blogspot.com/2019/02/nakanori930nakanori930.html
 - 2019年02月22日15時42分の登録： ＼ＫＢブラック　@bengoshi_black＼競争の結果の淘汰という司法制度改革が目指した成果？ http://hirono2014sk.blogspot.com/2019/02/bengoshiblack_22.html
 - 2019年02月24日22時19分の登録： ＼リーチ一発ツモ裏１　@luckymangan＼「倫理観が薄っぺらいけれども、一応弁護士なので、その肩書き・名前は便利に使える存在」って、平成の司法制度改革が目指した目的 http://hirono2014sk.blogspot.com/2019/02/luckymangan_24.html
 - 2019年03月01日03時36分の登録： ＼ルート６６（元ルパン３世）　@Route66_LP3＼リスク管理のプロ集団であれば、司法制度改革はこんなことになってないのでは… http://hirono2014sk.blogspot.com/2019/03/route66lp3.html
 - 2019年03月02日20時19分の登録： ＼坂本正幸　@sakamotomasayuk＼司法制度改革で弁護士会が求めたものは法曹一元\n裁判官は弁護士から\nみんな最初は弁護士になるんだ、という制度だったことを認識し http://hirono2014sk.blogspot.com/2019/03/sakamotomasayuk_61.html
 - 2019年03月06日13時28分の登録： ＼オタ弁さん　@otalawyer＼20xx年。法科大学院は姿を消し、新たな司法制度改革として新々司法試験が導入された。受験資格は特に定められておらず誰でも受験できた。試 http://hirono2014sk.blogspot.com/2019/03/otalawyer20xx.html
 - 2019年04月12日20時05分の登録： REGEXP：”司法制度改革．＊崩壊”／データベース登録済みツイート：2019年04月12日20時04分の記録：ユーザ・投稿：4／4件 http://hirono2014sk.blogspot.com/2019/04/regexp20190412200444.html
 - 2019年05月06日14時30分の登録： ＼深澤諭史　@fukazawas＼（＾ω＾）実は司法制度改革審議会（佐藤幸治座長）では、司法修習の貸与制の他に提案してた制度があったんだお。\n（＊・∀・）え？給費制維持！ http://hirono2014sk.blogspot.com/2019/05/fukazawas_13.html
 - 2019年05月09日22時20分の登録： ＼ピピピーッ　@O59K2dPQH59QEJx＼ロースクールを卒業して弁護士にならない小室さんを批判する人は、ピロシに司法制度改革の理念を教えてもらうべき。 http://hirono2014sk.blogspot.com/2019/05/o59k2dpqh59qejx_9.html
 - 2019年06月07日20時37分の登録： ＼浜木綿弁右衛門　@leplusallez＼法寺マンセー系司法制度改革最右翼\n憲法ポエム系\nモノ言う系\n前の事務総長\n大阪の大御所\n名古屋の人\n\nもう当職はでぽん先生に入 http://hirono2014sk.blogspot.com/2019/06/leplusallez_7.html
 - 2019年06月17日00時39分の登録： ＼坂本正幸　@sakamotomasayuk＼司法制度改革のために新人弁護士が食えなくなった、ベテランはなぜ俺に仕事を回さない、と恨み言を言い続けている人がまともなことを http://hirono2014sk.blogspot.com/2019/06/sakamotomasayuk_17.html
 - 2019年06月19日00時52分の登録： ％@uwaaaa　サイ太％司法制度改革によって弁護士が急増すること，弁護士特約の普及によって交通事故訴訟が急増することは，容易に予想されうる事態なのであって，実際に急増し http://hirono2014sk.blogspot.com/2019/06/uwaaaa_70.html
 - 2019年07月01日08時31分の登録： ＼えきなんローヤー?　@ekinan_lawyer＼司法制度改革で「成仏」とか偉い人が言い、流布されてるような現状。\n\nそして、「谷間世代」なんて、名実共に屈辱なわけでさ http://hirono2014sk.blogspot.com/2019/07/ekinanlawyer.html
 - 2019年07月07日13時55分の登録： ＼深澤諭史　@fukazawas＼司法制度改革審議会意見書では、制度を生かすものは人である、ということを高らかに謳っているけれども、人一人がどういう行動をするのだろうか、 http://hirono2014sk.blogspot.com/2019/07/fukazawas_7.html
 - 2019年07月31日23時22分の登録： ＼坂本正幸　@sakamotomasayuk＼裁判官不信\nがスタートなので、それ以降どうなるかは考えていなかった\nというのが司法制度改革でこれが入った理由と現状 http://hirono2014sk.blogspot.com/2019/07/sakamotomasayuk_71.html
 - 2019年08月01日02時30分の登録： ＼深澤諭史　@fukazawas＼成仏 - Wikipedia\n法律家の間では、司法制度改革に伴い若い弁護士が経済的に困窮したり廃業したりする現象を成仏と表現することが広 http://hirono2014sk.blogspot.com/2019/08/fukazawas-wikipedia.html
 - 2019年08月17日17時53分の登録： ＼裁判員制度はいらないインコ　@nosaibaninko＼返信先: \n@fukazawas\nさん\n司法制度改革、「これでは優秀な人材が集まりませんよ」と言われた某最高裁長 http://hirono2014sk.blogspot.com/2019/08/nosaibaninko-fukazawas.html
 - 2019年08月20日20時14分の登録： ＼サイ太　@uwaaaa＼司法制度改革が産み出した狂気こと「虎ノ門法経塾 」のことについては未来永劫語り継いでいきたいと思います。\n\n塾生の活動 | 虎ノ門法経塾  http://hirono2014sk.blogspot.com/2019/08/uwaaaa_20.html
 - 2019年10月10日07時38分の登録： ＼えきなんローヤー?　@ekinan_lawyer＼しっかし、司法制度改革の甘い罠にすでに引っかかってるんだよなー。ローに入学するあたりが。\n\n諸行無常やな… http://hirono2014sk.blogspot.com/2019/10/ekinanlawyer.html
 - 2019年11月06日11時03分の登録： ＼ごしべんせんせー　@mackckckck＼稼ぐ弁護士は良い弁護士、稼げない弁護士は悪い弁護士、これが司法制度改革の定理。\n\n市民には質の良し悪しは判断できないのに、質の http://hirono2014sk.blogspot.com/2019/11/mackckckck_6.html
 - 2019年11月28日18時17分の登録： ＼平　裕介　@YusukeTaira＼司法制度改革の総括（一部の方々でする）では、かえって弁護士費用が割高になりましたというコメントは出ないでしょうね。そもそも関心がなさ http://hirono2014sk.blogspot.com/2019/11/yusuketaira_28.html
 - 2019年11月28日20時25分の登録： ＼弁護士7286　@jmjhjmwtad＼司法制度改革って、あれ単に弁護士が儲けすぎやろ、っていうものに過ぎなかったんやろね。んで、弁護士が儲けすぎやろっていう感覚は、今 http://hirono2014sk.blogspot.com/2019/11/7286jmjhjmwtad_6.html
 - 2019年11月29日09時57分の登録： ＼中村剛（take-five）　@take___five＼弁護士費用を安くするために司法制度改革が行われたのかは知らないけど、昔ながらの旧弁護士報酬基準ってかなり安く、あ http://hirono2014sk.blogspot.com/2019/11/take-fivetakefive_29.html
 - 2019年12月19日21時55分の登録： REGEXP：”司法制度改革”／深澤諭史（@fukazawas）の検索（2012-11-20〜2019-08-17／2019年12月19日21時55分の記録225件） http://hirono2014sk.blogspot.com/2019/12/regexpfukazawas2012-11-202019-08.html
 - 2020年01月23日01時27分の登録： ＼モトケン　@motoken_tw＼この話は、私が司法制度改革の問題として、一部を変えた場合にその影響が全体に及ぶ、と言ってることと全く同じ。\n引用ツイート\n http://hirono2014sk.blogspot.com/2020/01/motokentw_23.html
 - 2020年02月16日20時06分の登録： ＼モトケン　@motoken_tw＼司法制度改革以前から多様な人材は確保されてるよ。\n例えば、私と同期の（誰か来たようだ。。 http://hirono2014sk.blogspot.com/2020/02/motokentw_20.html
 - 2020年06月14日20時52分の登録： ＼戸舘圭之/弁護士/袴田事件弁護団　@todateyoshiyuki＼法テラス特措法、いまあがってる批判の声を突き詰めていけば、高山俊吉先生はじめとする司法制度改革反対派 http://hirono2014sk.blogspot.com/2020/06/todateyoshiyuki.html
 - 2020年06月25日09時50分の登録： ＼7286　@jmjhjmwtad＼素人を腹話術人形にして、自分に利益誘導したい悪い大人がいるということ。司法制度改革で散々見られたパターン。 http://hirono2014sk.blogspot.com/2020/06/7286jmjhjmwtad_25.html
 - 2020年06月26日09時32分の登録： ＼Document35　@document35＼弁護士と自由競争が話題になると司法制度改革による増員に言及されるけど、あれは「競争を促進しよう論」ではなく、「需要が増える http://hirono2014sk.blogspot.com/2020/06/document35document35_26.html
```

　コピペしたあとになって気がついたのですが，「司法制度改革」で検索を実行していたようです。「dp -p |grep 司法制度改革 |wc -l」というコマンドの実行結果は66件。1件のデータ内に改行を含ませていないのでそのまま該当データの件数になります。

```
➜  ~ dp -p |grep 司法黙示録
 - 2019年03月01日13時15分の登録： ＼深澤諭史　@fukazawas＼「日本弁護士連合会臨時総会。まもなく、開始です・・・・！」\n#司法黙示録\n#日弁連臨時総会\n\n0件の返信 0件のリツイート 0 いいね\n http://hirono2014sk.blogspot.com/2019/03/fukazawas-0-0-0.html
 - 2019年09月10日16時13分の登録： オープンだ・・！受験生達を招いての狂乱の宴。\n合格発表の幕が上がる・・！\n\n#司法黙示録 http://hirono2014sk.blogspot.com/2019/09/blog-post_68.html
 - 2020年01月08日13時45分の登録： ＼深澤諭史　@fukazawas＼オープンだっ・・・・！！！\n日弁連の将来を決める2年に一度の大勝負、日弁連会長選挙・・・！！ #司法黙示録 http://hirono2014sk.blogspot.com/2020/01/fukazawas-2.html
 - 2020年03月11日16時27分の登録： ＼深澤諭史　@fukazawas＼再投票日当日・・・。場は、異常に煮詰まっていた・・・。\nやがて誘う・・・。候補者たちを、人智及ばぬ裁きの場へと・・・・！！\n#司法黙示録 http://hirono2014sk.blogspot.com/2020/03/fukazawas_31.html
 - 2020年05月21日10時34分の登録： ＼深澤諭史　@fukazawas＼嘘丸出しの答弁でも・・・ 人は・・・ そこにポストや利権があればついてくる・・・! #司法黙示録 http://hirono2014sk.blogspot.com/2020/05/fukazawas_21.html
 - 2020年05月21日10時35分の登録： ＼深澤諭史　@fukazawas＼ねじ曲げられねえんだっ・・！！ 自分が死ぬことと・・・， 検察庁法に定められた定年はよっ・・・！！！！ #司法黙示録 http://hirono2014sk.blogspot.com/2020/05/fukazawas_41.html
 - 2020年06月28日23時15分の登録： ＼深澤諭史　@fukazawas＼弁護士に対して、長文ＤＭで、黙らせようとする考えが、そもそも論外なのだ！ #司法黙示録 http://hirono2014sk.blogspot.com/2020/06/fukazawas_28.html
 - 2020年07月08日09時45分の登録： REGEXP：”司法黙示録”／深澤諭史（@fukazawas）の検索（2014-01-24〜2020-06-30／2020年07月08日09時45分の記録354件） http://hirono2014sk.blogspot.com/2020/07/regexpfukazawas2014-01-242020-06_8.html
```

　すでに2,3度，「司法黙示録」をキーワードにまとめ記事を作成していると思っていたのですが，結果にはさきほど作成したばかりの「（2014-01-24〜2020-06-30／2020年07月08日09時45分の記録354件）」しか見当たらないようです。

-30／2020年07月08日09時45分の記録354件） http://hirono2014sk.blogspot.com/2020/07/regexpfukazawas2014-01-242020-06_8.html

　最近，パソコンの処理能力不足のためなのか，まとめ記事の埋め込みツイートのデザインが表示されないことが多くなっています。Firefoxに変えるとすぐに表示されることもあるのですが，JavaScriptの処理に軽いバグや負担が掛かっているのかと想像したりしています。

　Firefoxで同じページを開くと，同じく埋め込みツイートが表示されなかったのですが，急にパソコンの動きが重く，マウスの動きも不安定になって，Google Chromeを終了させると，すぐにFirefoxで埋め込みツイートが表示されました。やはり処理能力不足のようです。

 - （002／382） TW fukazawas（深澤諭史） 日時： 2014-01-24 09:28:00 +0900 URL： https://twitter.com/fukazawas/status/426511734338105344

> 多様な法曹志願者に，受験資格を与える我々が悪党なわけがない。
> 我々は，皆さんに，司法試験合格という未曾有の大チャンスを与えているのです。
> 数百万の負債を抱えることなど，このチャンスに比べれば安いもの。ロー制度は非常にリーズナブル，良心的制度でございます。 #司法黙示録 

 - （009／382） TW fukazawas（深澤諭史） 日時： 2014-02-08 23:28:00 +0900 URL： https://twitter.com/fukazawas/status/432158895516037120

> もはや破綻しているのに…。まだ，そんなことを…！生来の詐欺師っ…！筋金入りだ…！起こせるぜ…！カルトな宗教っ…！
> #司法黙示録 #法の光教団 

　#法の光教団 というハッシュタグは余り見覚えのないものですが，法の光というのは法テラスを揶揄する言い回しなのかもしれません。割とよく見かけた時期があり，それらしい内容のツイートもありました。他に，法寺，とする法クラのツイートがあります。成仏と対なのでしょう。

 - （010／382） TW fukazawas（深澤諭史） 日時： 2014-04-03 17:29:00 +0900 URL： https://twitter.com/fukazawas/status/451637604715229184

> 見ての通りだ，見ての通り，法科大学院制度を続けると，法曹志望者も学生も，法曹界も，痛む！
>
> だが，わしは痛まない！
>
> #司法黙示録 

 - （018／382） TW fukazawas（深澤諭史） 日時： 2014-04-07 23:41:00 +0900 URL： https://twitter.com/fukazawas/status/453180864998813696

> 勾留満期まで，黙秘しておけばええんちゃう？
>
> #司法黙示録 

　これはちょっと見覚えのなかった深澤諭史弁護士のツイートになりますが，勾留での取調べを皮肉り，それに黙秘権を使っているようです。2014年4月7日のツイートとなっているので，大分の件や，名古屋の喫茶店女性店員死体遺棄事件より前になるのかもしれません。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜yoshikawayusaku（吉川　雄策） 日時：2020-07-08 10:30／2017/11/16 18:20 URL： https://twitter.com/kk_hirono/status/1280675661191852033 https://twitter.com/yoshikawayusaku/status/931089458434162688  

> 大分県別府市の女性殺害事件で、 36歳長男を殺人の疑いで再逮捕  民家で住人の山野佐知子さんが死亡しているのが見つかった事件で、大分県警はが再逮捕。した。認否については「黙秘します」と供述しています。尾形記者の取材。https://t.co/3MM58Rx2JJ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜TOS_hodo（TOS報道部） 日時：2020-07-08 10:30／2017/11/22 19:33 URL： https://twitter.com/kk_hirono/status/1280675695203463168 https://twitter.com/TOS_hodo/status/933282185917775872  

> 転落女性のバッグ隠した罪　被告の男は黙秘: 　平成29年7月、大分市都町のビルで転落死していた女性の手提げバッグなどを隠して放置したとされる男の初公判が22日に大分地裁で開かれ男は起訴内容について黙秘しました。… https://t.co/Ztbw38tttZ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜YahooNewsTopics（Yahoo!ニュース） 日時：2020-07-08 10:31／2019/01/25 13:27 URL： https://twitter.com/kk_hirono/status/1280675728317546496 https://twitter.com/YahooNewsTopics/status/1088654508408750080  

> 【娘の最後話して 黙秘権に苦悩】 https://t.co/q85VpzlafS  2017年、大分市の女性が遺体で見つかった事件で、死亡直前まで一緒にいた男性が裁判などで経緯を説明しないため精神的苦痛を受けたとして両親が提訴。「娘の最後を話してほしい」。  

〈〈〈：Linux Emacs： 2020-07-08（水曜日）10：31 　〈〈〈

〉〉〉：Emacs： 2020-07-08（水曜日）13：02　 〉〉〉

- RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜yuki_k1（YUKI　Keiichi） 日時：2018/07/01 00:39／2018/06/26 19:22 URL： https://twitter.com/hirono_hideki/status/1013084620252827651 https://twitter.com/yuki_k1/status/1011555204225888256

> RT @yuki_k1: 被疑者・被告人の「黙秘権」は強力な権力を用いて捜査する警察・検察への数少ない防御手段であって、「被害者の知る権利」という副次的な価値を根拠に疑問を呈するのはちょっとな～。  
> ／なぜ名古屋の漫画喫茶店スタッフは死んだのか。被告が「黙る」ことで分からなくなる…  

@hirono_hideki ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@hirono_hideki）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-08 14:23／2018/11/15 09:52 URL： https://twitter.com/kk_hirono/status/1280734327735676928 https://twitter.com/hirono_hideki/status/1062871033110118400  

> “依頼者は５か月の間、全てを黙秘で通しており、今更、供述に転じる見込みなど、ないと断じて良い。 では、令状担当裁判官は、何を考えて、「被疑者取調未了」が勾留延長を正当化すると考えたのだろうか。” / “黙秘と勾留延長|名古屋市中…” https://t.co/vW5Uq4i27Q  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-08 14:23／2018/11/15 10:07 URL： https://twitter.com/kk_hirono/status/1280734354763739138 https://twitter.com/hirono_hideki/status/1062874713301573632  

> 1件のコメント https://t.co/PHT1G0kFbT “『黙秘の壁 名古屋・漫画喫茶従業員はなぜ死んだのか』への批判を巡って。 高橋正人弁護士との対話(藤井誠二) - 個人 - Yahoo!ニュース” https://t.co/yqb7NQ6KDm  

　> ／なぜ名古屋の漫画喫茶店スタッフは死んだのか。被告が「黙る」ことで分からなくなる…

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-08 14:27／2019/07/29 23:22 URL： https://twitter.com/kk_hirono/status/1280735273974812673 https://twitter.com/hirono_hideki/status/1155846079423733762  

> 『黙秘の壁 名古屋・漫画喫茶従業員はなぜ死んだのか』への批判を巡って。 松原拓郎弁護士との対話(藤井誠二) - 個人 - Yahoo!ニュース https://t.co/ew4QZmdqwH 　ブロックされている野田政仁弁護士の名前も出てきたが、率直に読む気にならない。  

　@hirono_hideki 野田政仁弁護士となっているのは，野田隼人弁護士の間違い。

　時刻は16時51分になります。さきほど宇出津新港の買い物から戻ったのですが，買い忘れがあったので今日，2回，同じ宇出津新港に行くことになりました。かなり珍しいことです，午後は晴れ間もあって雨の心配はない感じですが，昼前に向かったときは小雨が降っていました。

 - 2020年07月08日09時45分の登録： REGEXP：”司法黙示録”／深澤諭史（@fukazawas）の検索（2014-01-24〜2020-06-30／2020年07月08日09時45分の記録354件） http://hirono2014sk.blogspot.com/2020/07/regexpfukazawas2014-01-242020-06_8.html

　354件のツイートというのは数が多すぎます。最近のものから目を通し，これはというものを掲載してご紹介したいと思います。１つの弁護士現象の実態，現実です。

 - （353／354） TW fukazawas（深澤諭史） 日時： 2020-06-28 19:11:00 +0900 URL： https://twitter.com/fukazawas/status/1277182928758300673

> 弁護士に対して、長文ＤＭで、黙らせようとする考えが、そもそも論外なのだ！
> #司法黙示録 https://t.co/WZPkBQosmb

 - （349／354） TW fukazawas（深澤諭史） 日時： 2020-06-13 13:17:00 +0900 URL： https://twitter.com/fukazawas/status/1271657886691688448

> これ以上法テラスの範囲を拡大だと！？ふざけるな！
> 「ククク・・・。日弁連の要望により法テラスの適用範囲を拡大する法案を提出する我々野党が悪党な訳がない。」
> 「我々は、日弁連の要望に従っただけです。法テラスは非常にリーズナブル、良心的制度でございます・・！」
> #司法黙示録 

 - （348／354） TW fukazawas（深澤諭史） 日時： 2020-06-13 13:15:00 +0900 URL： https://twitter.com/fukazawas/status/1271657429013417984

> 成仏だろうが・・・！
> これ以上、日弁連の要望で、法テラスの適用範囲を拡大したら・・・！
> 俺たちはみんな成仏だろうが・・・！！
> #司法黙示録 

 - （346／354） TW fukazawas（深澤諭史） 日時： 2020-05-22 14:35:00 +0900 URL： https://twitter.com/fukazawas/status/1263705124146278402

> ひどい・・ひどすぎる・・！こんな話があるかっ・・！
> 努力の果て，やっとの思いで官邸と仲良しになれたのに・・
> 麻雀っ・・！あの賭け麻雀がもぎとってしまった・・！
> せっかく手にした彼の希望・・！検事総長の椅子をっ・・！
> #司法黙示録 

 - （345／354） TW fukazawas（深澤諭史） 日時： 2020-05-21 10:11:00 +0900 URL： https://twitter.com/fukazawas/status/1263276228640772098

> まだだよ・・。まだ定年になっていない。
> まだまだ退職しない・・！検事総長の椅子が見えるまで。
> 定年を超えていく・・！野党共が完全に諦めるまで・・。
> 検事総長になった後は，証拠も残さない・・！！
> #司法黙示録 

 - （344／354） TW fukazawas（深澤諭史） 日時： 2020-05-21 10:09:00 +0900 URL： https://twitter.com/fukazawas/status/1263275779359567872

> 魂の乗った法解釈・・。
> そういう解釈を議事録も作らずに閣議決定だけでひっくり返すこと。
> それはまるで，法律の心を喰らうようだ・・。
> この世じゃ，法律の心が一番うまいんだ・・
> #司法黙示録 

 - （343／354） TW fukazawas（深澤諭史） 日時： 2020-05-21 10:08:00 +0900 URL： https://twitter.com/fukazawas/status/1263275393773010944

> 嘘丸出しの答弁でも・・・
> 人は・・・
> そこにポストや利権があればついてくる・・・!
> #司法黙示録 

 - （337／354） TW fukazawas（深澤諭史） 日時： 2020-05-10 11:18:00 +0900 URL： https://twitter.com/fukazawas/status/1259306860835815425

> 政府「法律なんか誰が守るか！あれは私と私のお友達が、下々を支配するために使う道具なんずよ！
> なんで、私たちがこんなものを守らないといけないざんすか！訳のわかない制度ざんすよ！法律は！」
> #司法黙示録
> #検察庁法改正案に抗議します 

 - （329／354） TW fukazawas（深澤諭史） 日時： 2020-01-08 12:07:00 +0900 URL： https://twitter.com/fukazawas/status/1214745494305431552

> オープンだっ・・・・！！！
> 日弁連の将来を決める2年に一度の大勝負、日弁連会長選挙・・・！！ #司法黙示録 

 - （326／354） TW fukazawas（深澤諭史） 日時： 2019-12-10 16:52:00 +0900 URL： https://twitter.com/fukazawas/status/1204307818108473344

> 修習生君は，これまで気持ちよく修習をしてきた。
> 常に新しいことを学び，順調に帆をあげているよう・・。
> 修習先でごちそうになる食事もうまかったろう・・。
> しかし，ここからは違う，変わるよ何もかも。
>
> ここから先の実務は地獄の淵を通る・・！
> ＨＥＬＬ　ＥＤＧＥ　ＲＯＡＤ
> #司法黙示録 

 - （315／354） TW fukazawas（深澤諭史） 日時： 2019-07-14 12:52:00 +0900 URL： https://twitter.com/fukazawas/status/1150251589342384129

> ハンセン氏病事件について，控訴はしない・・・しない・・・が・・・。
> それは，国の責任を認めたものではない・・・！
> そのことを，国民諸君は，どうか忘れないで頂きたい・・！
> つまり，我々がその気になれば，他の患者は一切救済しないことも可能だろう・・ということ・・！
> #司法黙示録 

　深澤諭史弁護士のツイートに「ハンセン病」が出てきたところで打ち切りたいと思います。きりがないので。

〈〈〈：Linux Emacs： 2020-07-08（水曜日）17：14 　〈〈〈

* 川沿いの国道41号線が崩落したという岐阜県下呂市のニュース，ずっと名古屋から長野県松本市に向かう国道19号線沿いと勘違いしていた件
  :LOGBOOK:
  CLOCK: [2020-07-08 水 17:29]
  :END:

:CATEGORIES: 中西運輸商,金沢市場輸送

〉〉〉：Emacs： 2020-07-08（水曜日）17：29　 〉〉〉

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜akichanenjoy（【公式】あなたに良いことが起きるTw） 日時：2020-07-08 17:32／2020/07/08 08:37 URL： https://twitter.com/kk_hirono/status/1280781827066572801 https://twitter.com/akichanenjoy/status/1280647115161526272  

> これがこう  #飛騨川氾濫 #記録的大雨 #特別警報  #避難勧告 #これがこう https://t.co/qpgBGaerG2  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜akichanenjoy（【公式】あなたに良いことが起きるTw） 日時：2020-07-08 17:32／2020/07/08 11:17 URL： https://twitter.com/kk_hirono/status/1280781882225876992 https://twitter.com/akichanenjoy/status/1280687433013579777  

> この大雨特別警報の中橋を渡る 名鉄3500系が幻想的だわ。 かっこいい。  #飛騨川氾濫 #記録的大雨 #特別警報  #避難勧告 #これがこう  #名鉄 https://t.co/e3nuatyF8V  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜taiyamann10（クソノヤマ） 日時：2020-07-08 17:33／2020/07/08 10:08 URL： https://twitter.com/kk_hirono/status/1280781919878176774 https://twitter.com/taiyamann10/status/1280670122533720064  

> 国道41号なくなりました https://t.co/CSvgJA5Mlv  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-08 17:33／2020/07/08 14:38 URL： https://twitter.com/kk_hirono/status/1280781943848632320 https://twitter.com/hirono_hideki/status/1280737998015885312  

> 岐阜 飛騨川付近 国道41号線えぐられる | NHKニュース https://t.co/Wd0qjdTeh2  

　飛騨という岐阜県の地名は有名ですが，飛騨川というのは聞いたことがなかったように思います。Googleマップで下呂市の場所を確認すると，高山市にずいぶん近いので驚きました。高山市というのは富山県や富山市にも近かったようなイメージがあります。

 - » 富山市、富山県 から 岐阜県高山市 - Google マップ https://t.co/iOtrksPXnO 国道1号線経由　1時間46分　82.6Km

　岐阜県飛騨市というのも聞いたことがないと思ったのですが，別に調べた神岡町が飛騨市になっていました。３つ地名の選択を迫られたのですが，真ん中の神岡町東雲を選択したところ，高山市まで47分，36.3Kmと経路が表示されています。Googleマップです。

　神岡町は，安房峠，長野県松本市，長野県諏訪市の経由で東京に行くのによく通行した時期があったのですが，ずいぶん歴史を感じる独特な雰囲気がある土地で，近年になって昭和40年代と記憶するイタイイタイ病の発生源だったとネットで知りました。

　一度，富山の方から国道41号線を名古屋方面に向かい，夕方の早い時間だったと記憶にあるのですが，前方左手に高山市の市街地らしい場所を見たことが，割と強く記憶に焼き付いています。他にも1,2回は通行したことがあったかもしれませんが，基本，通る道ではなかったです。

　金沢市場輸送では岐阜県内での荷降ろしというのも滅多になかったです。中西運輸商でも少なかったですが，トナミ運輸の定期便で，広島県の福山市から長野市と上越市という路線があって，それをしばらくの間，何度かやったことがありました。

　下呂温泉は有名ですが，国道の広い道路から右手に，川沿いにある温泉街の風景を何度か見たという記憶がありました。ただ，福山市からの定期便では松本市も明け方の薄明るくなってきた時間帯に通行していたので，下呂温泉の風景を見ることはなさそうとは考えていました。

　国道19号線で松本市から名古屋市方面に向かって通行したことも何度かあったのですが，大きな川の川沿いに大型トラックの通行が多い国道があったという記憶です。Googleマップでみると，それが有名は木曽川になるようです。

　昭和59年当時，富山県と新潟県の県境は親不知の国道8号線のみで迂回路がなく，一度，鮮魚を積んで新潟に向かうのに，東名高速で名古屋から中央道と大きく迂回したことがあったのですが，予想を超えてずいぶん時間が掛かったことがありました。

　国道19号線も国道41号線も二桁の国道で，交通の大動脈になると思います。その川沿いの道路が水流で抉られ崩落したという現場を見たのは，衝撃でした。

　Twitterのトレンドでは，昔，長距離トラック運転手の仕事で見たのと同じような下呂温泉の写真が出ているのですが，その下呂温泉とよく似た雰囲気だと思ったのが，香川県の池田町でした。現在は香川県三好市となっているようです。

　この池田町は，高校野球の甲子園大会でいちやく有名になったことがあります。野球には余り関心がないので，まだ知らない方と思いますが，伝説や漫画のような活躍をしたのが池田町の高校でした。たぶん池田高校ではと思います。

 - » 池田高校 甲子園全成績 https://t.co/AEJ9WBYusM

　Googleの検索で，これはという見出しの記事が見つからなかったのですが，上記のページに，昭和49年春準優勝，昭和54年夏準優勝，昭和57年夏優勝，昭和58年春優勝，昭和61年春優勝と。2年ぐらいの活躍で優勝1回，準優勝1回ぐらいだと思っていので，ずいぶん違っていたようです。

 - » 徳島県立池田高等学校 - Wikipedia https://t.co/gjPUA0PpXh 蔦文也元監督が率いる池田高校野球部は、春夏の甲子園大会で優勝3回、準優勝を2回した。全部員11人だけで戦い抜き準優勝を果たした「さわやかイレブン」や、

　ほんとうに2年間ぐらいの活躍と思っていたので，「春夏の甲子園大会で優勝3回、準優勝を2回」というのは驚きです。星稜・箕島戦があった頃までは，割と熱心に高校野球を見ていたのですが，その後はほとんど無関心になっていました。ただ大きな話題になっていたことはわかっていました。

　個人的には，その高校野球での池田高校の活躍や知名度より，池田町の現地の雰囲気が印象に残るものでした。

 - » 池田町マチ - Google マップ https://t.co/Htiak7tZDc 徳島県三好市

　Googleマップでみると，この池田町の中心部も大きな川の川沿いとなっていて，吉野川とあります。国道192号線と，国道32号線が交差しているようです。国道32号線のようですが高知市に向かうのに通行したような記憶がありました。

　それとは別に，徳島県徳島市から愛媛県松山市に向かうときも国道192号線を通行していたようです。平成4年3月にも通行していたようですが，途中で高速道路に乗り，新居浜市の辺りでパーキングエリアに入ったような記憶です。そこで被告発人梅野博之と電話で話した記憶もあります。

　前に何か調べた時に，三好市が出てきて，広島県の三次市との違いに戸惑ったことがあったのですが，何か警察の問題があったように思います。

 - » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「三好市」の検索結果 - Twilog https://t.co/J0Yl9DTuIm ツイートが見つかりませんでした

 - » 徳島・三好署が誤認逮捕謝罪 １９日間勾留された専門学校生宅訪れ｜徳島ニュース｜徳島新聞 https://t.co/cpeWB4k9vU 2017/9/11

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜flurry（flurry） 日時：2020-07-08 18:46／2017/09/10 22:44 URL： https://twitter.com/kk_hirono/status/1280800522954399747 https://twitter.com/flurry/status/906876124294033408  

> サイトに書き込まれていた名前をそのまま犯人だと判断して誤認逮捕。しかも4万円の容疑で19日間勾留。あまりに酷くねえかこれ……＞徳島・三好署が誤認逮捕　詐欺容疑の専門学校生 成り済まし被害 https://t.co/ANrZU0lHz9  

 - » 奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「三好」の検索結果 - Twilog https://t.co/lVnXtEZCok

　昨年あたりも，愛媛県で女性の誤認逮捕が問題になっていて，繰り返しテレビでみたのですが，終わりの方には弁護士が出てきていたような記憶があります。愛媛の農業アイドルの自殺問題も話を見かけなくなっていますが，弁護士が弁護士を訴えるとか，訴えたような話もあったかと思います。

〈〈〈：Linux Emacs： 2020-07-08（水曜日）18：57 　〈〈〈

