* 神奈川県小田原市の村松謙弁護士（神奈川県弁護士会）と，神奈川県横浜市で活動中の可能性のある匿名弁護士うの字

** 村松謙弁護士の経歴，「弁護士１７名が在籍する小田原市で創業４７年の弁護士事務所」と京都大学卒業

```

むらまつ　　 けん
村　松　謙
2005年10月	弁護士登録。小田原三の丸法律事務所に入所
【 略　歴 】	京都大学卒業
日弁連市民のための法教育委員会委員
『教室から学ぶ法教育』〔現代人文社〕を執筆（共著）
法と教育学会監事
箱根町情報公開・個人情報保護審査委員
小田原短期大学非常勤講師（日本国憲法）
藤沢市立看護専門学校非常勤講師

［source：］弁護士１７名が在籍する小田原市で創業４７年の弁護士事務所 http://www.odawarasannomaru-lawoffice.com/lawyers.html
```

　たぶん前にも読んでいると思うのですが，今回，村松謙弁護士のプロフィールに京都大学卒業とあるのを見て，ずいぶん意外に感じました。2005年10月に弁護士登録と小田原三の丸法律事務所への入所とあります。

　弁護士１７名が在籍する，というのは比較的大所帯になるのかと思いますが，小倉秀夫弁護士の弁護士としての立場や環境に似てものを感じてきました。そちらも確認をしておきます。

```
小倉　秀夫
Hideo Ogura
1968年生・東京都
経歴
1991　司法試験合格
1992　早稲田大学法学部卒業
1994　司法修習終了（46期）
1994　弁護士登録（東京弁護士会）
2000　中央大学法学部兼任講師
2001　当法律事務所パートナー
知的所有権研究会事務局長
民事訴訟法学会、情報ネットワーク法学会会員

［source：］小倉　秀夫｜スタッフ紹介｜事務所紹介｜東京平河法律事務所 http://www.tokyo-hirakawa.gr.jp/office/lawyer/staff19.html
```

 - スタッフ紹介｜事務所紹介｜東京平河法律事務所 http://www.tokyo-hirakawa.gr.jp/office/staff.html  

　何名とはかいてありませんが，数えると，弁護士8名，これは全員が男性の名前のようですが，小倉秀夫弁護士以外に名前を見かける弁護士はいません。司法書士が1名で，こちらはただ一人の女性のようです。他に弁理士が2名とあります。

** 村松 謙弁護士（弁護士法人小田原三の丸法律事務所） - 神奈川県小田原市 - 弁護士ドットコム

```
著書・論文
2010年 3月
教室から学ぶ法教育　子どもと育む法的思考
一部執筆
2009年
村松謙・熊本秀子「法教育における教師と弁護士の連携のあり方を考える」
共同発表
2010年
野嵜雄太・村松謙「法教育の基礎－遊びのルールづくりを通して、ルールの機能・役割を学ぶ授業－」
共同発表

［source：］村松 謙弁護士（弁護士法人小田原三の丸法律事務所） - 神奈川県小田原市 - 弁護士ドットコム https://www.bengo4.com/kanagawa/a_14206/l_120294/
```

　ずいぶん久しぶりに見たと思う履歴書サイズの顔写真が開いたページの冒頭に出てきました。最初にTwitterにみた村松謙弁護士の顔写真になるのかもしれないですが，10年近く前にもなりそうです。

　Twitterのプロフィールで確認をしたところ，「2009年9月からTwitterを利用しています」となっていました。現在のTwitterのアカウントは@km0bakeとなっていますが，前は違ったものだったと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 10:37／2020/09/03 10:36 URL： https://twitter.com/kk_hirono/status/1301333408413409281 https://twitter.com/s_hirono/status/1301333263898693632  

> 2016-05-25-132231_弁護士　村松　謙@kmuramatsuな　に　こ　れ＞群馬県警、誤認逮捕8日後に釈放　道交法違反容疑　｜　2016／5／24　-　共同通信.jpg https://t.co/KIAmUx7oRu  

　一つパソコン内でみつけたものを非常上告-最高検察庁御中_ツイッター（@s_hirono）に画像つきツイートをしました。2016年5月ということですが，Twitterのアイコンが丸くなる前のようです。弁護士ドットコムと同じ村松謙弁護士の顔写真です。

　やはりTwitterのアカウント名も@kmuramatsuとなっています。TwitterAPIではスクリーンネームというので，個人的にはそちらの方が馴染みがあるのですが，ユーザ名ともいうのかもしれません。はっきりしていることは，「弁護士　村松　謙」のところがプロフィールの名前ということです。

** Twilogで確認した2010年5月6日から始まる村松謙弁護士関連のツイート

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-03 10:57／2010/05/06 20:03 URL： https://twitter.com/kk_hirono/status/1301338597086261248 https://twitter.com/hirono_hideki/status/13481020079  

> RT @kmuramatsu    回数や時間をかくのがめんどくさいので、お金はいいです。。。 RT @narushisu2004: 被告人国選も被疑者国選と同じように、接見回数を報酬算定の基礎にして欲しいよ。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-03 10:58／2010/06/03 13:17 URL： https://twitter.com/kk_hirono/status/1301338651314462720 https://twitter.com/hirono_hideki/status/15301646411  

> このPDF読みました。昨日の弁護士刺殺事件に対するものです。RT @kmuramatsu: 会長談話がでましたね。ＰＤＦですが。http://www.elint.co.jp/yokoben/info/statement/20100602kaityodanwa.pdf  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-03 10:58／2010/08/18 23:42 URL： https://twitter.com/kk_hirono/status/1301338832692944897 https://twitter.com/hirono_hideki/status/21495424301  

> 弁護士2名からアンフォロー（リムーブとも）されたらしい。何故のタイミング？？？ @MinakoTYO @kmuramatsu  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-03 10:59／2010/08/18 23:45 URL： https://twitter.com/kk_hirono/status/1301338876695330816 https://twitter.com/hirono_hideki/status/21495657995  

> 今まで何故フォローされていたのかも不思議。 RT @hirono_hideki: 弁護士2名からアンフォロー（リムーブとも）されたらしい。何故のタイミング？？？ @MinakoTYO @kmuramatsu  

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「@kmuramatsu」の検索結果 - Twilog https://t.co/WpUpZbLt2M

　現在の村松謙弁護士のTwitterアカウントからブロックされるようになったのは，半年ほど前かと思います。過去には村松謙弁護士にフォローされていたことがあったようにありますが，記憶にはなく，思い出すという感覚もありません。

** 「2017年にまとめつくってた。。。＞強姦被害者は「死ぬほど抵抗しないと同意と見なされる」系都市伝説について。 - Togetter」という村松謙弁護士の本日未明のツイート

強姦被害者は「死ぬほど抵抗しないと同意と見なされる」系都市伝説について。 - Togetter https://t.co/YuEsIiNZ21  \n おなじみの弁護士ローカス先生と \n そうは見えないかも知れませんが、弁護士のうのじ先生がコメント。

　さきほど見たときは気が付かなかった，村松謙弁護士の三浦義隆弁護士とうの字の紹介文を引用しました。以下がまとめられているツイートになります。

@lawkus ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@lawkus）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW lawkus（ystk） 日時：2017/11/20 20:33 URL： https://twitter.com/lawkus/status/932572497282609153  

> 「死に物狂いで抵抗しなかったから同意があった。よって無罪」という判決が山ほどある旨のツイートが回ってきた。これよく聞く都市伝説だけど、被害者が強く抵抗していないことを一つの要素として考慮した無罪判決がしばしば見られること自体は事実だからややこしいんだよな。  

- TW lawkus（ystk） 日時： 2017/11/20 20:35 URL： https://twitter.com/lawkus/status/932573232992940032  

> 裁判所は多数の事実を総合的に考慮して判決の結論を決めるけど、無罪判決を書くなら無罪方向の事実は、軽重はともかく全部拾って判決文に記載する。結論を決める上で個々の事実がどれだけ重視されたかは明確には記載されない場合が多い。  

- TW lawkus（ystk） 日時： 2017/11/20 20:40 URL： https://twitter.com/lawkus/status/932574272907649026  

> なので、個々の判決文はそれだけ見ると、「考慮要素は羅列されているが個々の要素の重みが分からないので判断過程がよくわからない」ということが多い。そこを多少なりとも理解するには、多数の判例を読んで共通の傾向を析出する必要があったりする。率直に言って素人には無理。  

- TW lawkus（ystk） 日時： 2017/11/20 20:43 URL： https://twitter.com/lawkus/status/932575112049684480  

> だから、素人が生半可に判決文なんか読むと、「強く抵抗しなかった。よって同意があった。よって無罪」式の乱暴な読み方をしてしまうことがあるが、これはもう仕方ないという気がする。裁判所も敢えて判断基準をブラックボックス化して裁量を保っている面がないとはいえないし。  

- TW un_co_the2nd（うのじ） 日時： 2017/11/22 04:37 URL： https://twitter.com/un_co_the2nd/status/933056737589919744  

> 供述の信用性の判断に関わる事実認定では、広いうる限りの事情を拾う。とくに無罪判決書く＝検察官控訴だから、裁判官は何でもかんでも書いてしまったりする。  
> 抵抗の程度は、他の認定可能な客観的事実と被害者の供述の整合性がないときに、付け加えて言及する程度の位置付けなのに、「死ぬほど抵抗  

- TW un_co_the2nd（うのじ） 日時： 2017/11/22 04:38 URL： https://twitter.com/un_co_the2nd/status/933056964858298369  

> しないと同意ありとみなされる」とかいう都市伝説を流布する奴がいるのは困ったものだ…  

- TW un_co_the2nd（うのじ） 日時： 2017/11/22 04:44 URL： https://twitter.com/un_co_the2nd/status/933058601563721729  

> 兎にも角にも、強姦・強制わいせつ被告事件で「死ぬほど抵抗しなかった」を理由に無罪になったケースはないです。  
> 無罪になるのは、犯罪となるべき事実の認定ができない場合（その最たる証拠となる被害者供述について、裏付けとなる客観的事実が認定できないことも当然含めて）で、それがすべて。  

- TW un_co_the2nd（うのじ） 日時： 2017/11/22 04:51 URL： https://twitter.com/un_co_the2nd/status/933060346394288128  

> ぶっちゃけ、死に物狂いで抵抗しなかったら無罪ってんなら、我々ってばめっちゃ商売しやすいっすわ。被疑者被告人が、その死に物狂いの抵抗とやらで怪我してなきゃ無罪じゃん。  

- TW mofjd（モフ） 日時： 2017/11/22 04:52 URL： https://twitter.com/mofjd/status/933060685872762880  

> @un_co_the2nd 死ぬほど抵抗しなければならないという話が広まると、死ぬほど抵抗したがために殺されてしまう事例が出るのではないかと心配にもなります。  

- TW un_co_the2nd（うのじ） 日時： 2017/11/22 04:53 URL： https://twitter.com/un_co_the2nd/status/933060888667418624  

> @mofjd です。抵抗されたために激昂し、重傷を負わせたり殺したりっていうマッドな奴がいないとも限りません。  

- TW un_co_the2nd（うのじ） 日時： 2017/11/22 08:43 URL： https://twitter.com/un_co_the2nd/status/933118814648090624  

> 裁判所・裁判官って、ある事実があるならばある要件を満たす認定が可能、という類型のものについて、ある要件を満たさない理由としてある事実がないことに言及しなきゃいけない病にかかってるよね。  

@un_co_the2nd ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@un_co_the2nd）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW un_co_the2nd（うのじ） 日時：2017/11/22 08:46 URL： https://twitter.com/un_co_the2nd/status/933119412625747974  

> それが判決理由中の要らん記載となり、妙な都市伝説を生む  

　うの字に再注目をしだしたのは，つい最近のことで9月1日からと本日確認をしました。そのタイミングで，村松謙弁護士が2017年11月のTogetterのまとめ記事をツイートで紹介し，そのほとんどがローカスこと三浦義隆弁護士とうの字のツイートの紹介になっていました。

　一度，再確認のために村松謙弁護士のタイムラインを開き直したところ，そのタイミングでも村松謙弁護士がリツイートをしたうの字のツイートを見かけていて，その辺りを含め，弁護士鉄道の歴史資料としてスクリーンショットの記録を行っています。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:47／2020/09/03 09:00 URL： https://twitter.com/kk_hirono/status/1301350993582387200 https://twitter.com/s_hirono/status/1301309091898257408  

> 2020-09-03-083757_ystk@lawkus·9時間安倍ちゃんがあのだいぶやばい奥さんを好きなようにさせておいた（少なくともそう見える）点は、政治家としての功績と.jpg https://t.co/GFW7WhdP4m  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:47／2020/09/03 09:00 URL： https://twitter.com/kk_hirono/status/1301351049479946241 https://twitter.com/s_hirono/status/1301309164459667457  

> 2020-09-03-084031_つまらむ@km0bake·7時間2017年にまとめつくってた。。。＞強姦被害者は「死ぬほど抵抗しないと同意と見なされる」系都市伝説について。.jpg https://t.co/qxRVmTaaiY  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:47／2020/09/03 09:01 URL： https://twitter.com/kk_hirono/status/1301351081650188288 https://twitter.com/s_hirono/status/1301309237209882625  

> 2020-09-03-084239_強姦被害者は「死ぬほど抵抗しないと同意と見なされる」系都市伝説について。　-　Togetter.jpg https://t.co/H7IREhxPmX  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:47／2020/09/03 09:01 URL： https://twitter.com/kk_hirono/status/1301351099748610049 https://twitter.com/s_hirono/status/1301309310178217984  

> 2020-09-03-085047_｛君はアレがエロく見えるのかね？平和の証に見えないならば教養が足りんよ。本を読みなさい。　@un_co_the2nd供述の信用性の判断に関わ.jpg https://t.co/91KUqIYhj4  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:47／2020/09/03 09:01 URL： https://twitter.com/kk_hirono/status/1301351113317261312 https://twitter.com/s_hirono/status/1301309382903226368  

> 2020-09-03-085303_ぶっちゃけ、死に物狂いで抵抗しなかったら無罪ってんなら、我々ってばめっちゃ商売しやすいっすわ。被疑者被告人が、その死に物狂いの抵抗とやらで怪.jpg https://t.co/re2Tt5MTbE  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:47／2020/09/03 09:11 URL： https://twitter.com/kk_hirono/status/1301351144753561600 https://twitter.com/s_hirono/status/1301311832703995904  

> 2020-09-03-085820_うのじ@un_co_the2nd·55分ボコボコにされなければ、死ぬほど抵抗しなければ強姦と認められないっていうデマカセは、貞操のために死ね.jpg https://t.co/uvHmJdZvbp  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:47／2020/09/03 09:11 URL： https://twitter.com/kk_hirono/status/1301351176017829888 https://twitter.com/s_hirono/status/1301311905290547206  

> 2020-09-03-090153_性犯罪については参考になる弁護士アカウント・奥村先生・らめーん先生だと思ってる。特に、被害者側の支援したい人たちはらめーん先生のを参考にする.jpg https://t.co/QirbDPO7Ni  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:47／2020/09/03 09:12 URL： https://twitter.com/kk_hirono/status/1301351195743719424 https://twitter.com/s_hirono/status/1301311978070106112  

> 2020-09-03-090257_うのじ@un_co_the2nd·11時間犯罪願望なんて許されないって言ってる勢は、学校に火つけたろとか担任刺したろとかクラスのあいつを吊る.jpg https://t.co/dI5AxS3y0x  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:48／2020/09/03 09:12 URL： https://twitter.com/kk_hirono/status/1301351212504113152 https://twitter.com/s_hirono/status/1301312050832916482  

> 2020-09-03-090442_うのじ@un_co_the2nd·16時間「上司殺してえ〜」だと嫌悪感ないのに、「幼女犯してえ〜」だと嫌悪感があるんだとしたら、それは表出さ.jpg https://t.co/xw2oze9oNN  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:48／2020/09/03 09:12 URL： https://twitter.com/kk_hirono/status/1301351235421745152 https://twitter.com/s_hirono/status/1301312123629264896  

> 2020-09-03-090528_うのじ@un_co_the2nd·16時間小学4年生〜高校生までの間に学校に放火しようと考えなかった日はないんで、犯罪願望がダメとか言われて.jpg https://t.co/LIUiXkBCnR  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:48／2020/09/03 09:12 URL： https://twitter.com/kk_hirono/status/1301351257618096128 https://twitter.com/s_hirono/status/1301312196362735617  

> 2020-09-03-090814_うのじさんがリツイート坂本正幸@sakamotomasayuk·18時間まあこのレベルの役職まで来てる政治家の配偶者ってことはむちゃくちゃ地.jpg https://t.co/XjZRC7eT1z  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:48／2020/09/03 09:13 URL： https://twitter.com/kk_hirono/status/1301351278878978049 https://twitter.com/s_hirono/status/1301312269091917824  

> 2020-09-03-090928_うのじさんがリツイート高橋雄一郎@kamatatylaw·18時間湯婆婆「フン。淡路島というのかい？贅沢な名だねぇ。今からおまえの名前はパソ.jpg https://t.co/86r9Pb8M2t  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:48／2020/09/03 09:13 URL： https://twitter.com/kk_hirono/status/1301351297547866113 https://twitter.com/s_hirono/status/1301312341607215107  

> 2020-09-03-091044_うのじさんがリツイート泥濘大魔王サイケ@k_sawmen·21時間「ナンパしてセックスに誘ったらとくに拒否しなかったのでOKと思った」みたい.jpg https://t.co/JrfT9NDvqi  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:48／2020/09/03 09:45 URL： https://twitter.com/kk_hirono/status/1301351317420478464 https://twitter.com/s_hirono/status/1301320433845690368  

> 2020-09-03-091157_うのじさんがリツイート小動物を愛するしんさん@aphros67·20時間マクロン「表現の自由には憎悪を唱えないようにする義務もあるが、風刺は.jpg https://t.co/iHHf9FNCHD  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:48／2020/09/03 09:46 URL： https://twitter.com/kk_hirono/status/1301351364577034240 https://twitter.com/s_hirono/status/1301320506545586176  

> 2020-09-03-092204_うのじ@un_co_the2nd·19時間人が亡くなってる事件でレイプされるときに抵抗しないと無罪になっちゃうから云々とかやってるの、うんち.jpg https://t.co/wVVq5dPxV6  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:48／2020/09/03 09:46 URL： https://twitter.com/kk_hirono/status/1301351421757939712 https://twitter.com/s_hirono/status/1301320579274829829  

> 2020-09-03-092344_うのじ@un_co_the2nd·20時間被害者の発見場所がトイレだったから、捜査機関としては猥褻目的だったというふうに誘導したほうがやりや.jpg https://t.co/YEDR2MQ75d  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:48／2020/09/03 09:46 URL： https://twitter.com/kk_hirono/status/1301351450598014976 https://twitter.com/s_hirono/status/1301320651861422080  

> 2020-09-03-092458_うのじ@un_co_the2nd·20時間せっせと抵抗しないと同意だとデマ広げてる人、何がしたいんですか。そもそもあの事件、犯行が実際にわい.jpg https://t.co/go4OOUKM1o  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:49／2020/09/03 09:46 URL： https://twitter.com/kk_hirono/status/1301351473503059968 https://twitter.com/s_hirono/status/1301320724620087297  

> 2020-09-03-092653_うのじさんがリツイートつまらむ@km0bake·21時間金沢は今回からってこと？うへえ.jpg https://t.co/QmklZ9xm5e  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:49／2020/09/03 09:47 URL： https://twitter.com/kk_hirono/status/1301351506654814209 https://twitter.com/s_hirono/status/1301320797382873089  

> 2020-09-03-092804_うのじ@un_co_the2nd·23時間「娘も罪に問われるべき」って何言ってんだ。娘が「あいつを殺して」とまで言ったならちょっと揺らぐけど.jpg https://t.co/UWA4d8czYO  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:49／2020/09/03 09:47 URL： https://twitter.com/kk_hirono/status/1301351530088378374 https://twitter.com/s_hirono/status/1301320870049099777  

> 2020-09-03-092911_うのじ@un_co_the2nd·9月2日少年法がらみは調べものしないし論理も破綻してるのが勢いよく湧いてるからミュートワード設定しとこ….jpg https://t.co/StFeDGIWqQ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:49／2020/09/03 09:47 URL： https://twitter.com/kk_hirono/status/1301351546827862021 https://twitter.com/s_hirono/status/1301320942774231040  

> 2020-09-03-092953_うのじさんがリツイートモトケン@motoken_tw·8月31日この連ツイを批判（または非難または罵倒）している人のほとんどは、連ツイをまと.jpg https://t.co/Yyg82507Jp  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:49／2020/09/03 09:48 URL： https://twitter.com/kk_hirono/status/1301351590406709249 https://twitter.com/s_hirono/status/1301321015461462017  

> 2020-09-03-094514_深澤諭史さんがリツイート心の貧困@mental_poverty·2時間真面目に勉強したいので、その「抵抗しなかったから無罪の判決」とやらを具.jpg https://t.co/QQfedZtejD  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:49／2020/09/03 09:58 URL： https://twitter.com/kk_hirono/status/1301351617749422081 https://twitter.com/s_hirono/status/1301323606815776768  

> 2020-09-03-095509_深澤諭史@fukazawas·3分（；・∀・）クレーマー対応事件とかやっているけれども，この世の中には，残念なことに一定数，取引相手を「脅か.jpg https://t.co/f86jvGSskm  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:49／2020/09/03 09:58 URL： https://twitter.com/kk_hirono/status/1301351634795069440 https://twitter.com/s_hirono/status/1301323679553302528  

> 2020-09-03-095616_つまらむさんがリツイートうのじ@un_co_the2nd·1分LGBTの権利擁護に熱心だったと💩は記憶してる弁護士ですら、ロリペドはキモいの.jpg https://t.co/t43qOeVnvS  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:49／2020/09/03 09:58 URL： https://twitter.com/kk_hirono/status/1301351663895109633 https://twitter.com/s_hirono/status/1301323752118996992  

> 2020-09-03-095728_とりなお@naotarou1981そのツイートが共感を得られると思ってたのなら認識をだいぶ改めたほうがよさそう。.jpg https://t.co/fHCQD2AoFt  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:49／2020/09/03 10:27 URL： https://twitter.com/kk_hirono/status/1301351687118962688 https://twitter.com/s_hirono/status/1301330886705647617  

> 2020-09-03-102650_村松　謙弁護士（弁護士法人小田原三の丸法律事務所）　-　神奈川県小田原市　-　弁護士ドットコム.jpg https://t.co/GxSxnQaUbI  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-03 11:50／2020/09/03 11:37 URL： https://twitter.com/kk_hirono/status/1301351722699218950 https://twitter.com/s_hirono/status/1301348550802984960  

> 2020-09-03-112710_おなじみの弁護士ローカス先生とそうは見えないかも知れませんが、弁護士のうのじ先生がコメント。　.jpg https://t.co/40aBf1kIIj  

　朝，村松謙弁護士のタイムラインを見る前に，三浦義隆弁護士のタイムラインをみていました。久しぶりにけっこう気になる内容のツイートがあったのですが，三浦義隆弁護士とうの字の組み合わせを村松謙弁護士が2017年にやっていて，それを2020年9月3日にツイートしたというのは，不思議な縁です。

　三浦義隆弁護士といえば，警察官を法律の素人して罵倒していたのも忘れられないツイートです。

