* 「「自殺ない社会、作っていただけるようお願い」　官房長官　7月以降、増加に転じ - 毎日新聞」に，「（；・∀・）あの・・・，私が苦労して納めた税金・・・・。」という深澤諭史弁護士のツイート

:CATEGORIES: 深澤諭史弁護士

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2020/09/29 09:04 URL： https://twitter.com/fukazawas/status/1310732028531281921  

> 「自殺ない社会、作っていただけるようお願い」　官房長官　7月以降、増加に転じ - 毎日新聞 https://t.co/8yaunbsHFD   
> （；・∀・）あの・・・，私が苦労して納めた税金・・・・。  

　記事に2度目を通したのですが，国の予算や税金に関することは書いてないように思います。現政権に対する強い不信感が根底にあっての深澤諭史弁護士の発言なのかと推察しますが，資料として全文を引用しておきます。

```
加藤勝信官房長官は28日の記者会見で、著名人を含む自殺の増加について「いろいろ悩みがある方が孤立することがないよう、温かく寄り添いながら見守っていただけるような社会を一緒に構築してほしい。それぞれが自殺のない社会を作っていただけるようにお願いしたい」と呼びかけた。

　加藤氏は「7月以降、自殺者数の増加の兆しが見られ、多くの方が自ら尊い命を絶っているという現実を我々はしっかりと受けとめなければいけない」として「政府としても相談窓口の設置等にしっかり取り組みたい」と述べた。

　新型コロナウイルスと自殺リスクの関係については「ステイホームとなると、なかなか他の人と接触しにくい状況もあり、うつなどになりがちだという指摘もある。政府としてはSNSを含め、相談窓口をさまざま用意しており、活用してほしい」と話した。

　警察庁と厚生労働省によると、今年の自殺者数は前年比で7月から増加に転じた。8月は1849人（速報値）に上り、前年の同じ時期より246人増えた。

　著名人では、今年7月に俳優の三浦春馬さん（30）が、今月は女優の芦名星さん（36）、竹内結子さん（40）がそれぞれ自宅で亡くなり、いずれも自殺とみられている。【佐藤慶】

［source：］「自殺ない社会、作っていただけるようお願い」　官房長官　7月以降、増加に転じ - 毎日新聞 https://mainichi.jp/articles/20200928/k00/00m/010/130000c
```

　なお，念頭にあるのは弁護士の社会的経済的責任と，弁護士の違法行為に対する国もしくは自治体の求償権になります。

* 「ネット上の表現トラブルについて，一般向けに必要な情報は，一揃い・・・無料で全部読めますので，ひとまず，ここを読んでおけば，デマと心中は避けられると思います。」という深澤諭史弁護士のツイート

:CATEGORIES: 深澤諭史弁護士

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2020/09/28 22:29 URL： https://twitter.com/fukazawas/status/1310572285669986305  

> ネット上の表現トラブルについて，一般向けに必要な情報は，一揃い，ここに集めておきました。  
> 無料で全部読めますので，ひとまず，ここを読んでおけば，デマと心中は避けられると思います。  
> （・∀・）  
> https://t.co/IJeHY85kps https://t.co/z6CB1kOds6  

```
＊初版：令和２年３月２８日。最終更新日：令和２年９月２７日

目次
はじめに
Ｑ１．発信者情報開示請求ってなんですか？
Ｑ２．発信者情報開示に係る意見照会書ってなんですか？
Ｑ３．裁判外だったら拒否すれば，開示されませんよね？
Ｑ４．必ず意見照会はくるのですか？
Ｑ５．投稿者ですが，開示・非開示になったら連絡はもらえますか？
Ｑ６．開示請求が来てから，どれくらいのタイミングで結論が出ますか？
Ｑ７．開示判決について，プロバイダは控訴してくれますか？
Ｑ８．名誉権侵害（名誉毀損）ではなくて，名誉感情とか，プライバシー，著作権侵害だったら，開示の可能性は低いですよね？
Ｑ９．意見照会ですが，延期してもらえるのですか？
Ｑ１０．発信者情報開示請求を検討していますが，弁護士費用の方が高くついてしまわないでしょうか。
Ｑ１１．慰謝料は判例で決まって，相場は○○ですよね？
Ｑ１２．発信者情報開示請求に使った弁護士費用は発信者に請求できる／できない，と聞きましたが，本当のところは？
Ｑ１３．発信者としては裁判前に示談しない方が安く済むよね？
Ｑ１４．立証責任は請求者（被害を受けたと主張する者）にあるから，全部否認すれば，大丈夫ですよね？
Ｑ１５．ネット上の情報は，書き込まれた人／書き込んだ人が，書き込んだ人／書き込まれた人をだまして，自分が有利になるように工作しているのですよね？
Ｑ１６．ネットで「○○という判決だったよ！」とか聞いたのですが，本当ですか。
Ｑ１７．相手の弁護士は東京の法律事務所のようですが，私は地方在住です。裁判はどこでやることになるのですか？
Ｑ１８．投稿者で開示されてしまい，賠償請求の内容証明郵便が来ました。示談は不利ですので，判決に従いますとだけ返事しようかと思いますが，それでいいのでしょうか。
Ｑ１９．Ｑ１８について，いくらにすればいいか，よくわからないので，裁判にしてもらって本人訴訟で対応しようと思いますが，どうでしょうか。
Ｑ２０．開示請求をして無事に開示されましたが，契約者は自分は投稿者ではないといっています／自分は投稿していないのですが，回線の契約者ということで開示されました。
Ｑ２１．原告に立証責任がある。だから釈明を求めまくれば大丈夫ですよね？
Ｑ２２．支払いの判決が出ても破産すれば大丈夫ですよね！
Ｑ２３．意見照会ってどうやって来るのですか？内容証明郵便？
Ｑ２４．被害者（請求者）ですが，複数名から投稿されたので，賠償請求訴訟ではまとめて訴訟をしようと思います／投稿者ですが，他にも投稿者がいるようで，その場合，他の投稿者にも私の住所氏名は知られてしまうのでしょうか。
Ｑ２５．請求者「事業上の損害は請求できますか？」被請求者「事業上の損害も請求されるのですか？」
Ｑ２６．この単語だったらいくらとか，「アホバカ」レベルなら○○万円とか，聞くのですが，本当でしょうか。あと，判例で賠償額は決まるとか聞きますが。
Q２７．今、発信者情報開示請求の制度について、政府が改正を検討していると聞きましたが、どのような影響はあるのですか？簡単に開示されるようになると聞きましたが。
Ｑ２８．ネット上の体験談、武勇伝で、「真実性や公共の利害関係性、公益性が認められて非開示になったぞ！」ってよく聞きますが、本当でしょうか。
Ｑ２９．最近は、裁判所は簡単に発信者情報開示請求を認めると聞きましたが、本当でしょうか。
Ｑ３０．請求を受けた側の対応が悪い，ということで，慰謝料は増額になるの？
Ｑ３１．被告側で本人訴訟は否認するのが大事，気をつけないと否認ではない，つまり自白と扱われるので注意！と聞いたけれども，本当？
Ｑ３２．発信者情報開示請求をする弁護士は仕事のない底辺弁護士だ，ビジネスにしようとしている，と聞きましたが，本当ですか？
Ｑ３３．尋問で裁判所に呼び出されることはあるのですか？
Ｑ３４．開示費用について，最近は発信者の負担にしない裁判例が多いが，被告本人訴訟の場合は，発信者負担になるケースが多い傾向だと聞きました。これは，控訴で逆転するのでしょうか。
Ｑ３５．発信者情報開示請求が簡略化すると聞きましたが，「法の不遡及」だから，過去の投稿は関係ないですよね？
Ｑ３６．和解と示談って，どう違うの？
Ｑ３７．賠償請求訴訟になったら，お互いの住所はわかるの？
Ｑ３８．ログの保管期限はどれくらいあるのですか？保存期間を延ばすことはできますか？
Ｑ３９．発信者情報開示請求をする場合，発信者に意見照会があるとのことですが，これは，（裁判外での請求ではなくて）開示請求訴訟をした場合もそうなりますか？
Ｑ４０．請求者（被害者）です。発信者情報開示請求を検討・実行しています。事件進捗について、いろいろとネットに書き込んで報告をしたいのですが。逆に、発信者・投稿者の立場から留意することはありますか？
Ｑ４１．訴訟の大部分は本人訴訟ですよね？判決は判例に従って決まると聞いたので「ネットｄｅ真実」の法律情報を集めて挑みたいと思うのですが。
Ｑ４２．匿名掲示板の投稿について，名誉毀損に当たるかどうか，同定可能性（本当にその人についての投稿であるのか）は，前後の投稿も考慮して判断されると聞きましたが，本当でしょうか。
Ｑ４３．現在，電話番号を発信者情報開示請求で開示される情報に省令改正で加える，という話があります。これで開示は簡単になるのでしょうか。
Ｑ４４．創作に関するトラブルです。創作物について「パクリ」ということは名誉毀損になりますか？
Ｑ４５．傍聴とか事件が知られてしまうのですか？相手方が有名人で心配なのですが。 
Ｑ４６．「発信者情報開示に係る意見照会」に対して，開示に同意すると慰謝料が上がると聞いたのですが，本当でしょうか。また，逆に下がるとも聞いたのですが本当でしょうか。
Ｑ４７．発信者（投稿者）です。プロバイダが裁判を起こされた，ということで，発信者情報開示請求に関する意見照会が届いて，拒否で連絡をしました。しばらく時間がかかると聞いているのですが，進捗などは教えてくれるのでしょうか。
Ｑ４８．Ｑ４７について，プロバイダが，プロバイダの弁護士に支払った弁護士費用は請求されるのでしょうか。
Ｑ４９．「この人，○○したんじゃないの？」の様な，疑問形での投稿について，発信者情報開示請求は認められるでしょうか。
Ｑ５０．遅延損害金って何ですか？名誉毀損は普通は認められないって聞いたのですが。
Ｑ５１．投稿者（発信者）ですが，発信者情報開示請求がされ，開示がされました。内容証明郵便で金銭を請求されたので，「裁判判決に従います」とだけ書いて返事をしました。もう半年くらいになりますが，諦めたと考えていいでしょうか。
Ｑ５２．投稿の賠償金については「仮差し押さえ」できるの？／「賠償金を払わないと仮差し押さえするぞ」といわれたんだけれども。
Ｑ５３．「発信者情報開示に係る意見照会書」に対して，開示に同意で回答すると，その後の権利侵害を争えないって本当？
Ｑ５４．請求者側：投稿者を見つけ出し，賠償請求訴訟を経て，判決が確定しました。しかし，払おうとしないし，差し押さえるべき財産も見当たりません。財産開示とかいう制度があるみたいですが。／発信者側：判決が確定しましたが，払いたくありません。どういう差し押さえのリスクがあるでしょうか。
Ｑ５５．コロナ禍の影響で，裁判が遅れています。これは，原告と被告，どちらに有利でしょうか。
Ｑ５６．仮処分だと発信者情報開示は簡単に認められるのですか？一方の言い分しか聞かないから簡単だと聞きましたが。
Ｑ５７．家族が契約している回線で書き込んだら，誰がどんな責任を負うことになるのですか？契約者は？投稿者は？立証責任は原告（請求者）にあるからシラをきれば大丈夫？
Ｑ５８．発信者情報開示請求をやるぞ！といわれているのですが，これについての発信者情報開示請求に係る意見照会書は，いつ頃届くのでしょうか。
Ｑ５９．企業に関する投稿についてです。暴言やパワハラ，不祥事などについての投稿なのですが，それについての証拠がありません。こういうケースでは，どのように判断されるのでしょうか。
Ｑ６０．発信者情報開示請求に係る意見照会書が届きました。開示に同意しようかと思いますが，メリットを教えてください。逆に，しないほうがいいのでしょうか。迷っています。
Ｑ６１．誹謗中傷って刑事告訴できるの？／されたらどうなるの？
Ｑ６２．発信者情報開示請求について，最近は，裁判外請求をしないので，最初からいきなり訴訟するケースが増えていると聞きましたが。
Ｑ６３．現在，発信者情報開示請求訴訟は止まっていると聞きましたが（だから，訴訟結果に関する情報はデマだと聞きましたが。）。
Ｑ６４．開示の判決が出てから，どれくらいで発信者情報は開示されるのでしょうか。
Ｑ６５．多数の人から中傷投稿をされているので，大量の投稿について開示請求をしようと思います／自分の投稿について開示請求を受けましたが，どうやら「大量開示」の様です。留意点は？
Ｑ６６．未成年者が書き込んだ場合はどうなるのでしょうか？

［source：］ネット投稿者の責任についてのまとめＱ＆Ａ（＋ネット上の誤解）｜深澤諭史｜note https://note.com/fukazawas/n/n87d77b861e9c
```

　上記に目次の部分を引用しましたが，66項目あります。記事は2020年9月19日ですが，内容は以前のブログで同じようなものを見ていたと思います。

* 「Ｑ６１．誹謗中傷って刑事告訴できるの？／されたらどうなるの？」という深澤諭史弁護士のnoteの記事

:CATEGORIES: 深澤諭史弁護士

　66項目ある目次から１つリンクを開いたのが，この「Ｑ６１．誹謗中傷って刑事告訴できるの？／されたらどうなるの？」になりますが，他は見ていないものの，かなり長文でした。

```
名誉毀損とは，事実（嘘を含む。）を摘示して，社会的評価を低下させる表現を行うことをいいます。
いわゆる悪口であれば直ちに名誉毀損になる，ということではありません。自分が読んでどう思うか，というのではなくて，一般読者が読んでどう思うか，がポイントです。これは，法律相談の時でもよく強調するのですが，読まされる被害ではなくて，読まれる被害がポイントということです。
もっとも，実際に刑事告訴したとして，そして名誉毀損罪が成立しているとして，捜査機関が動くとは限りません。
実は，警察への相談の中でも，名誉毀損というものは非常に多いそうです。ということで，捜査機関は，それなりの悪質性がないと，なかなか動いてはくれない，というのが実情です。
もっとも，最近は，誹謗中傷問題への注目が高まるにつれ，捜査機関の動きもよくなりつつあります。ですから，難しいとはいえ，決して不可能ではないともいえます。

［source：］ネット投稿者の責任についてのまとめＱ＆Ａ（＋ネット上の誤解）｜深澤諭史｜note https://note.com/fukazawas/n/n87d77b861e9c#9mspw
```

　名誉毀損で警察が動くのも動かないのも弁護士次第とも聞こえてくるささやき感があります。デマとセットになっているのも従来の深澤諭史弁護士らしさです。

```
誹謗中傷と刑事告訴の問題については，かなりネット上ではデマが多いです。
悪質性はもちろんのこと，悪質性のベクトル，つまりは方向も刑事処分になるかどうかでは，大きな影響があります。
ですから，かなり悪質であっても刑事事件にならない，さほど悪質ではないけれどもなる，ということがあります。
これは，投稿のテーマなどの事情が影響しますので，個別に弁護士に相談をするといいでしょう。
また，少し別の話になりますが，最近は，安易に「刑事告訴！即刻告訴！」と高圧的に内容証明郵便で予告するが，実際はしない，驚かして高額な和解に誘導しようとしているのではないか，と疑われるケースもあります。
このあたりは，内容証明郵便の文面を見れば分かることもありますので，あまり慌てず，早めに弁護士に相談に行くべきです。

［source：］ネット投稿者の責任についてのまとめＱ＆Ａ（＋ネット上の誤解）｜深澤諭史｜note https://note.com/fukazawas/n/n87d77b861e9c#9mspw
```

* 
