* LibreOfficeのWriteで悩みの種だったナビゲータのウィンドウへのドッキング方法

```
To dock or undock the Navigator or the Styles window, hold down the Ctrl key and double-click on a gray area in the window. Alternatively, press Ctrl+Shift+F10.

ウィンドウのサイズを変更するには、ウィンドウのエッジやコーナーをドラッグします。

［source：］ウィンドウのドッキングやサイズ変更をする https://help.libreoffice.org/latest/ja/text/swriter/guide/resize_navigator.html
```

　英語で書いてありますが，「Ctrl+Shift+F10」を実行すると，ナビゲータがウィンドウ内にドッキングしました。

* LibreOfficeのワープロソフトWriteで，Microsoft365と同じdocx形式の保存が出来ると知った。

　Wordで作成したdocxのファイルがLinuxのLibreOfficeで開けることは知っていたのですが，保存は古い形式のdocの拡張子でしか保存できないという思い込みがずっと長くありました。

　今日は午前2時18分にスマホの時計のアラームを設定し，午前4時の予定で小木港に行き，東一文字堤防でアジ釣りをしてきました。昨日の夕方に予定が入って8時から8時半には帰る予定でしたが，少し早いぐらいに切り上げました。

　メールで添付するWordの文書をLibreOfficeで作成していたところ，docxで保存できることに気がついたのです。Amazonギフト券についての資料の作成でした。これをポイントと混同したため，面倒なことになって午後の時間を費やしました。

　ipythonで計算式を表示させ，それをLibreOfficeにセレクションでコピペしたところ，色付けが反映されていて驚きました。他にも書式を含めたコピペができそうです。

　アジ釣りは最初に1匹，カマスが釣れました。その後はアジだけでしたが，サイズが小さく大きいものでも20センチはなかったと思います。

　オキアミの付け餌を忘れた上，サビキのアジ釣りの横でアオリイカ釣りのエギングを始めたところ，2投目で，糸が絡んでしまい，慌ててPEを切ったところ，エギのついたラインを切ってしまったようで，3号のエギを失ってしまいました。

　時間のロスにもなりましたが，3号のエギを失ったのは痛かったです。釣具店で3号のエギを１つ買っていたのですが1,100円ほどの値段でした。向かい風やある程度，水深のあるところでは，重めの3号のエギを使います。

　以前は，堤防の先端周りで20メートル以上水深があると3.5号のエギを使っていたのですが，負荷が大きく，シャクっただけでPEが切れることがあったので，そのような深場ではエギングをやらなくなっています。

　午前10時から予定が入っていたのですが，本当は翌日で，台風の影響で一日早まっていたのです。始まりからNHKのNEWS９をみていますが，スポーツコーナーのサッカーになっていて，台風のニュースはなかったような気がします。

　意外だったのは伊藤詩織さんが，世界で影響力を与えた100人に選ばれたというニュースでした。ここ数日，テレビはほとんどつけておらず，ニュースもほとんど見ていませんでした。気になったのは石川県での新型コロナウィルスのニュースで，20時47分ぐらいにテレビをつけました。

* UbuntuでVSCodeのマルチカーソールを使うため，KDEシステム設定のAlt＋左クリックを無効化

　これも数日前から悩みの種だったのですが，ようやく解決できました。ショートカットの設定ではなく，ウィンドウ操作→ウィンドウの挙動で，修飾キーAltの左クリックを，「何もしない」に設定することで解決できました。

* 

