* 「岡口判事を戒告　懲戒、異例の２度目―ＦＢに不適切投稿・最高裁」というネットニュースと，法クラの弁護士らの反応
  :LOGBOOK:
  CLOCK: [2020-08-27 木 09:48]--[2020-08-27 木 10:04] =>  0:16
  :END:

:CATEGORIES: 岡口基一裁判官

〉〉〉：Emacs： 2020-08-27（木曜日）09：48　 〉〉〉

 - 2020年08月27日07時18分の登録： REGEXP：”岡口”／データベース登録済みツイートの検索：2020-08-26〜2020-08-27／2020年08月27日07時15分の記録：ユーザ・投稿：57／68件 http://hirono2014sk.blogspot.com/2020/08/regexp2020-08-262020-08.html
 - 2020年08月27日08時20分の登録： REGEXP：”岡口”／データベース登録済みツイートの検索：2020-08-26〜2020-08-27／2020年08月27日08時18分の記録：ユーザ・投稿：65／82件 http://hirono2014sk.blogspot.com/2020/08/regexp2020-08-262020-08_27.html

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜pinpinkiri（小川一） 日時：2020-08-27 09:49／2020/08/27 06:00 URL： https://twitter.com/kk_hirono/status/1298784765890322432 https://twitter.com/pinpinkiri/status/1298726968079212544  

> フェイスブックへの投稿をめぐる仙台高裁の岡口基一裁判官の分限裁判で最高裁大法廷は戒告の懲戒処分とする決定を出しました。岡口氏は2018年10月にも投稿で戒告とされています。２度の懲戒処分を受けた裁判官は過去２人しかおらず異例です。SNS時代のふるまいを考えさせます。https://t.co/vXUYrkU2Om  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜pinpinkiri（小川一） 日時：2020-08-27 09:49／2020/08/27 06:00 URL： https://twitter.com/kk_hirono/status/1298784765890322432 https://twitter.com/pinpinkiri/status/1298726968079212544  

> フェイスブックへの投稿をめぐる仙台高裁の岡口基一裁判官の分限裁判で最高裁大法廷は戒告の懲戒処分とする決定を出しました。岡口氏は2018年10月にも投稿で戒告とされています。２度の懲戒処分を受けた裁判官は過去２人しかおらず異例です。SNS時代のふるまいを考えさせます。https://t.co/vXUYrkU2Om  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜matimura（田丁木寸） 日時：2020-08-27 09:52／2020/08/27 07:26 URL： https://twitter.com/kk_hirono/status/1298785483284082695 https://twitter.com/matimura/status/1298748739994042368  

> 岡口裁判官に再び戒告処分 FB投稿めぐり最高裁大法廷：朝日新聞デジタル https://t.co/iOWb8D4sfP ありゃ、今回は岡口判事が抵抗しなかったのか、少なくとも沈黙を守ったのか、分限裁判が始まったことすら知らなかった。  

　最高裁で分限裁判，懲戒処分で戒告などとなっているのですが，国会議員が岡口基一裁判官を罷免させる弾劾裁判を開くのか決めるというニュースも前からあったように思います。分限裁判の意味が理解できていないことに気が付きました。

```
裁判官の免職と懲戒を決定するために開かれる裁判

心身の故障または本人の希望により免職を決定する場合や、裁判官として相応しくない行為をしたなどの理由で懲戒処分を下す必要のあるとき、裁判所で行われる審理のことだ。裁判官分限法に基づき開かれる。

分限とは、身分を意味する言葉で、一般には、免職のほか休職や降格といった身分の異動が含まれる。しかし、裁判官の身分は手厚く保障されることから、懲戒には、戒告または1万円以下の過料しかない。

地方裁判所、家庭裁判所および簡易裁判所の裁判官が分限裁判にかけられる場合、高等裁判所において、５人の裁判官による合議体で審判が行われる。また、高等裁判所の裁判官については、最高裁判所の大法廷で開かれることになる。分限裁判とは、裁判所で裁判官を裁くことだと言える。

［source：］分限裁判(ぶんげんさいばん)の意味や定義 Weblio辞書 https://www.weblio.jp/content/%E5%88%86%E9%99%90%E8%A3%81%E5%88%A4
```

　やはり国会議員とはまったく別の手続きのようです。

 - 岡口基一裁判官、弾劾裁判への訴え検討の訴追委を批判 「軽々に裁判官を呼び出すのは三権分立に反する」 | ハフポスト https://t.co/Tzzt3nKPdV

　やはり訴追委こと国会の裁判官訴追委員会のことでした。本当は昨年2019年の6月25日辺りに，大きな判断を出すという話があったようですが，その後は情報を見かけなくなっています。

仙台高裁、岡口裁判官の懲戒申し立て　「ＦＢで遺族侮辱」―異例の２度目：時事ドットコム https://t.co/xo9ZP8DI5X 裁判官訴追委も罷免を求めて弾劾裁判所に訴追するか否かを審議しており、１９年３月には岡口判事に出頭を求め、投稿の経緯などを聴取している。

〈〈〈：Emacs： 2020-08-27（木曜日）10：04 　〈〈〈

