* 「【アナザーストーリーズ「わたしはやっていない　村木厚子　無罪までの４５４日」】」というNHKBSプレミアムの放送を紹介する郷原信郎弁護士のツイート
  :LOGBOOK:
  CLOCK: [2020-08-04 火 08:53]--[2020-08-04 火 10:21] =>  1:28
  :END:

:CATEGORIES: 郷原信郎弁護士

〉〉〉：Emacs： 2020-08-04（火曜日）08：53　 〉〉〉

　昨夜，深澤諭史弁護士のタイムラインを最初に見かけていました。まとめ記事も作成しているのですが，反応は少なかったようです。生成されたページタイトルを確認しただけで，まだ開いて内容はみていません。

 - 2020年08月03日22時01分の登録： REGEXP：”村木厚子．＊無罪までの454日”／データベース登録済みツイート：2020年08月03日22時00分の記録：ユーザ・投稿：10／11件 http://hirono2014sk.blogspot.com/2020/08/regexp4542020080322001011.html

```
2020年08月04日09時38分の実行記録
twitterAPI-search-lawList-mydql-add.rb "村木厚子"
ツイート数：9/1932 リツイート数：16/1932 トータル：559
hirono_hideki 3／0件
kk_hirono 3／0件
s_hirono 0／0件
```

　キーワードをよりヒット率の高い「村木厚子」に変更しましたが，トータルで559件という結果です。「REGEXP：”村木厚子”／データベース登録済みツイート：2020年08月04日09時39分の記録：ユーザ・投稿：133／219件」とでましたが，期間指定をしていませんでした。

 - 2020年08月04日09時45分の登録： REGEXP：”村木厚子”／データベース登録済みツイート：2020年08月04日09時39分の記録：ユーザ・投稿：133／219件 http://hirono2014sk.blogspot.com/2020/08/regexp202008040939133219.html

　今日は，いよいよ告発状の本文作成に取り掛かるつもりでいます。NHKBSは受信契約をしておらず，視聴は出来ないと思いますが，過去に連続テレビ小説まれ，のスピンオフ2作が，BSでの放送の後，地上波で放送されたのを視聴したことがありました。

　昨夜見た番組のホームページ，今朝見たホームページの動画にも郷原信郎弁護士の姿がありました。昨夜のホームページには大きな画像で弘中惇一郎弁護士の写真があったと思います。もともと弘中惇一郎弁護士の功績の１つに数えられるのが村木厚子さんの冤罪事件だったはずです。

　今朝は，郷原信郎弁護士のタイムラインで次のツイートをみました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜nobuogohara（郷原信郎【「深層」カルロス・ゴーンとの対話　起訴されれば９９％超が有罪となる国で】） 日時：2020-08-04 09:55／2020/08/04 06:31 URL： https://twitter.com/kk_hirono/status/1290451192561139714 https://twitter.com/nobuogohara/status/1290400014955552768  

> 【アナザーストーリーズ「わたしはやっていない　村木厚子　無罪までの４５４日」】 https://t.co/EIk8MJWKfB 本日（８月４日）21:00～、NHKBSプレミアムで放映されます。私もロングインタビューに応じ、これま… https://t.co/Yycm3aKt2A  

　リツイートしたところ，リツイートの数が317件そして319件になりました。いいねが514となっています。郷原信郎弁護士のフォロワー数を確認すると10.5万となっていました。右肩上がりで増えています。

 - （001／219） TW amneris84（Shoko Egawa） 日時： 2010-03-22 11:26:00 +0900 URL： https://twitter.com/amneris84/status/10851052304

> 濃い！ RT @tjimbo 弘中惇一郎弁護士の戦歴の一部です。ロス疑惑の三浦和義、薬害エイズの安部英、鈴木宗男、加藤紘一、村上正邦、矢野絢也、武井保雄（武富士会長）、野村沙知代、叶姉妹、堀江貴文、そして厚生省の村木厚子元局長。@takapon_jp #marugeki

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜amneris84（Shoko Egawa） 日時：2020-08-04 10:00／2010/03/22 11:26 URL： https://twitter.com/kk_hirono/status/1290452477985329152 https://twitter.com/amneris84/status/10851052304  

> 濃い！ RT @tjimbo 弘中惇一郎弁護士の戦歴の一部です。ロス疑惑の三浦和義、薬害エイズの安部英、鈴木宗男、加藤紘一、村上正邦、矢野絢也、武井保雄（武富士会長）、野村沙知代、叶姉妹、堀江貴文、そして厚生省の村木厚子元局長。@takapon_jp #marugeki  

```
神保哲生
@tjimbo
ジャーナリストの神保哲生です。ネット放送局『ビデオニュース・ドットコム』を主宰してます。
Tokyovideonews.com2009年6月からTwitterを利用しています
821 フォロー中
11.7万 フォロワー

［source：］神保哲生さん (@tjimbo) / Twitter https://twitter.com/tjimbo
```

　データベースに最初に記録されていたのは2010年3月22日のジャーナリストの江川紹子氏のツイートで，非公式RT，他のツイートの文字列を引用したものですが，それが神保哲生氏のアカウントとなっていました。ＰＣ遠隔操作事件の頃に動画ニュースとしてよくみかけたいた人物です。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜tjimbo（神保哲生） 日時：2020-08-04 10:03／2020/08/01 22:03 URL： https://twitter.com/kk_hirono/status/1290453368146624512 https://twitter.com/tjimbo/status/1289547353997766659  

> 郷原さん、ありがとうございました。 https://t.co/JXMAxfx2mE  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜nobuogohara（郷原信郎【「深層」カルロス・ゴーンとの対話　起訴されれば９９％超が有罪となる国で】） 日時：2020-08-04 10:03／2020/08/01 21:16 URL： https://twitter.com/kk_hirono/status/1290453393509617669 https://twitter.com/nobuogohara/status/1289535488735363072  

> 【是非、御視聴を‼】冒頭40分、私が出演し、菅原一秀衆院議員の公選法違反の検審申立について話しています。これを見れば、この国の「正義」が如何に危ういかが端的にわかります。《５金映画スペシャル＋α 「法外の正義」どころか日本はまず「… https://t.co/C8xQ4O7nAQ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜tjimbo（神保哲生） 日時：2020-08-04 10:04／2020/08/01 21:57 URL： https://twitter.com/kk_hirono/status/1290453625735729164 https://twitter.com/tjimbo/status/1289545825027145735  

> 市川さん、ありがとうございまさした。 https://t.co/bhLWZ2Lx0E  

　「このツイートはありません」と表示されています。再捜査要請書＿警察庁・石川県警察御中（@kk_hirono）がブロックされているアカウントで，市川さんで心当たりのあるのは市川寛弁護士です。

@imarockcaster42 ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@imarockcaster42）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW imarockcaster42（弁護士 市川 寛） 日時：2020/07/29 16:49 URL： https://twitter.com/imarockcaster42/status/1288381111999975424  

> 私が番組に出たときの章もあります（汗 https://t.co/6ZExpzqIZK  

　神保哲生氏の「市川さん，ありがとうございました。」のツイートの次にリツイートとして表示されていたものと同じだと思いますが，市川寛弁護士が引用リツイートしていたツイートが次になります。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜kobunsha_non（光文社 ノンフィクション編集部） 日時：2020-08-04 10:10／2020/07/29 16:21 URL： https://twitter.com/kk_hirono/status/1290454945150439424 https://twitter.com/kobunsha_non/status/1288374100201623552  

> ジャーナリストの神保哲生さん、社会学者の宮台真司さんによるニュース番組「マル激トーク・オン・ディマンド」から新しい書籍が出ました！12冊目のマル激本は『暴走する検察  歪んだ正義と日本の劣化』。こちらから立ち読みできます！https://t.co/j6xqU4iOy8  

　「暴走する検察  歪んだ正義と日本の劣化」というのは，ものすごくわかりやすいテーマとなっています。宮台真司という人の名前も見覚えがあるのですが，ＰＣ遠隔操作事件の動画に出ていたと記憶にあります。その動画も似たような，警察，検察批判でした。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-08-04 10:14／2020/08/04 10:13 URL： https://twitter.com/kk_hirono/status/1290456025494179843 https://twitter.com/s_hirono/status/1290455748909191170  

> 2020-08-03-213000_「わたしはやっていない　村木厚子　無罪までの454日」　-　アナザーストーリーズ　運命の分岐点　-　NHK.jpg https://t.co/lHYO0xF1lk  

　昨夜，記録としてスクリーンショットを作成しておいたのですが，弘中惇一郎弁護士と郷原信郎弁護士の組み合わせというのは，けっこう珍しく感じました。弘中惇一郎弁護士と佐藤博史弁護士の組み合わせというのは，割と最近，今年に入ってからだと思いますが，どこかで見たような気もします。

```
山口県生まれ。その後、東京代々木へ転居［1］。幼稚園と小学校は成城学園。小学校6年の夏に父親の転勤で広島市東区牛田に移り住む。私立修道高校を経て［2］、1968年東京大学法学部卒業。弁護士の佐藤博史は高校・大学の三年後輩にあたる。

クロロキン、クロラムフェニコール、日化工クロム職業病裁判（六価クロム）など多くの薬害事件を担当したほか、マクリーン事件などを担当。ロス疑惑の銃撃事件で三浦和義の無罪［3］、薬害エイズ事件における安部英の一審無罪［4］、障害者郵便制度悪用事件で村木厚子の無罪を勝ち取り、逆に大阪地検特捜部主任検事証拠改ざん事件を見抜く［5］。

カルロス・ゴーン被告が保釈を勝ち取れたのは弘中の弁護団選任が功を奏した、と海外で報じられた［6］。しかし、その保釈中のゴーンがレバノンに無断出国したことについては弘中は不関与を表明した［7］。

また、茶道上田宗箇流の門人でもある［要出典］。

［source：］弘中惇一郎 - Wikipedia https://ja.wikipedia.org/wiki/%E5%BC%98%E4%B8%AD%E6%83%87%E4%B8%80%E9%83%8E
```

　上記の引用部分で，広島の修道高校のことを確認しましたが，「村木厚子の無罪を勝ち取り、逆に大阪地検特捜部主任検事証拠改ざん事件を見抜く」とあるのはおそらく誤りで，前田恒彦元特捜部主任検事が弘中惇一郎弁護士が気がついていなかったと発言していたと思います。

〈〈〈：Emacs： 2020-08-04（火曜日）10：21 　〈〈〈

* はじめに
** (1).	告発状本文の作成開始
*** ア.	準備の完了と今後の予定