* 一昨日の夜から読み続けていた「仙台地方裁判所　昭和６０年（ワ）８３２号　判決」という松山事件の国賠請求棄却判決，終わり近くに思い出した石巻の有頭エビ
  :LOGBOOK:
  CLOCK: [2020-07-17 金 11:12]--[2020-07-17 金 14:42] =>  3:30
  :END:

:CATEGORIES: 国賠請求,再審,再審請求

〉〉〉：Emacs： 2020-07-17（金曜日）11：12　 〉〉〉

　たぶんネットで書くのは初めてになるかと思います。ささいといえば些細なことですが，割と強く印象に残っていた思い出で，ちょくちょくと思い出していました。それが有頭エビになります。

　仙台市の方から石巻市に入ったあたり，道路が二又になる突き当りのような敷地であったとも記憶にあるのですが，昔で言う庄屋のような大きな家でした。会社の看板は出ていなかったと思いますが，海産物の工場か大きな冷蔵庫に商品を入れているような家でした。

　古風な大きな家で，それ自体が珍しくもあったのですが，長距離トラック運転手の仕事で荷物を持っていったその石巻市の家で，おばあさんだったと思うのですが，揚げたてのような有頭エビをくれたのです。たまたま作っていた料理ができたタイミングだったとも思います。

　仙台市の方から来ると，石巻市のは入り口でしたが，石巻市での仕事のほとんどは日和大橋の向こう側でした。この有料道路の日和大橋を使わないと，石巻市内を大きく迂回することになり，そのときには石巻市内の中心部のようなところを通過しましたが，所持金を使いたくないときぐらいの通行でした。

　石巻市の水産業は，ほとんどが日和大橋を降りた先でした。降りるところに料金所があって，独特の強烈な匂いが周囲一帯に立ち込めていました。加工用の小魚の運搬で，道路が黒光りしていたのも印象に残っています。他に見ることのないそこだけの光景でした。

　日和大橋の料金所を出て，少し先の交差点を右折すると，突き当りに広い道路があって，その道路の海沿いが魚市場となっていました。当時，東日本最大とも聞いた石巻の魚市場でした。バラックを巨大化したような建物でしたが，長く続く建物でした。

　魚市場の二階の一部は，食堂になっていて大漁旗がいっぱいになっていました。テレビをみていると今はあちこちに海産物の土産物センターがあるようですが，当時それらしい鮮魚の直売所のようなもののを見かけるのは，新潟県の米山付近の国道8号線沿いぐらいでした。

　あるいは観光バスで団体客が来ていたのかと想像する，当時の石巻の魚市場の食堂ですが，そこで大きな有頭の海老フライを食べたのも印象でした。もうずいぶん前から珍しくなくなっていると思いますが，当時は見たことも聞いたこともない大きな海老フライで，誰かに話を聞いて知ったものでした。

石巻市 - Google マップ https://t.co/Rd6gcxR8Bm

　Googleマップで確認したところ，日和大橋が河口になる大きな川は，旧北上川となっていました。他にも有名な最上川かと思っていたのですが違っていました。この大きな川の川沿いにも大きな漁船が停泊し，川が漁港のようになっているという珍しい風景がありました。

　どれぐらい間があったのか記憶にないですが，宇出津の実家でも母親が冷蔵庫の冷凍庫に，有頭のエビを入れていたことがあります。小さな発泡スチロールの容器に入っていました。油で揚げたものを食べたと思うのですが，母親はめったに揚げ物を作らず，作るのも嫌がっていました。

　宇出津の実家で，いつのまにか新しくなっていた白い冷蔵庫でした。その冷凍庫に。小さな発泡スチロールの容器に入った有頭エビがあったこと，周辺の記憶がぼやけてしまっているのですが，印象的に記憶に残っています。

〈〈〈：Linux Emacs： 2020-07-17（金曜日）11：55 　〈〈〈

* 昨夜のうちに246ページまで読み進めていた「死刑捏造: 松山事件・尊厳かけた戦いの末に」という図書館の本

:CATEGORIES: 再審

　難読でもあった「仙台地方裁判所　昭和６０年（ワ）８３２号　判決」を読み終えて，肩の荷がおりた思いがあります。「死刑捏造: 松山事件・尊厳かけた戦いの末に」も319ページまでなので，あとは気持ちに余裕を持って，今日中に読み終えることができそうです。

　熊本の女性の話や，ハンセン病の藤本事件のことも昨夜，読んでいた部分に出てきました。仙台の拘置所では同じ敷地内に未決と死刑囚が生活をしていたように理解される記述がありましたが，40人の死刑執行を身近で見送ったとのことです。

　「仙台地方裁判所　昭和６０年（ワ）８３２号　判決」ではまるっきりの真犯人扱いで断罪したような印象も受けたので，同時に異なる視点や立場での見解を読めたのも，変わった経験というか，不思議にも思える体験になります。

　母親が辻立ちをしていたという仙台市青葉区一番町は，検察庁や裁判所に近い場所で，人の多い仙台駅前よりその場所を選んだのは，検察庁や裁判所の職員に直接，訴えかける目的があったとのことです。

　仙台市で最大の繁華街が何番町であるかは知っていました。トラックステーションからタクシーで飲みに行ったことも一度あったのですが，山の方向という以外は，仙台市内のどの辺りになるのか分かっていませんでした。仕事では行くことのない場所とも考えていました。

　アーケード街の入り口というような話も本にあったのですが，仙台市内のアーケードでの暴走事件というのは，一連の類似の犯罪のなかでも最初に見たもので，印象に残っています。テレビでニュースになっていましたが，被害者が少なかったのか，他の事件ほど報道が大きくはなかったとも思います。

　運送会社の運転手が会社に対する不満を募らせたというのが，アーケード街暴走の動機になっていたと記憶にあります。そのだいぶん後になりますが，愛媛県の松山市内でも似たような事件があり，そちらは母親を同乗させていたとも記憶にあります。

```
仙台アーケード街トラック暴走事件（せんだいアーケードがいトラックぼうそうじけん）とは、2005年（平成17年）4月2日に仙台市青葉区の商店街「中央通り」（アーケード街）にトラックが侵入、暴走し、歩行者7人が死傷した無差別殺人事件。

［source：］仙台アーケード街トラック暴走事件 - Wikipedia https://ja.wikipedia.org/wiki/%E4%BB%99%E5%8F%B0%E3%82%A2%E3%83%BC%E3%82%B1%E3%83%BC%E3%83%89%E8%A1%97%E3%83%88%E3%83%A9%E3%83%83%E3%82%AF%E6%9A%B4%E8%B5%B0%E4%BA%8B%E4%BB%B6
```

　調べたところ，記憶と時期は概ね一致していましたが，死者が3人出ていることや，その場で灯油をかぶり焼身自殺を図ったことなどは，記憶にありませんでした。死者は出ていない可能性があるとも考えていました。

```
2005年12月、宮城県仙台市青葉区内のアーケード街にワゴン車で進入し、買い物客7人を次々にはねたとして傷害の罪に問われていた53歳の男に対する判決公判が19日、仙台地裁で開かれた。裁判所は懲役3年の実刑を命じている。

事件は2005年12月25日夕方に発生した。仙台市青葉区一番町3丁目付近のアーケード街「マーブルロードおおまち」にワゴン車が進入。速度を上げながら約90mに渡って暴走し、買い物客を次々にはねた。この事故で子供を含む男女7人が打撲などの軽傷を負い、運転していた52歳（当時）の男は業務上過失傷害や道路交通法違反（ひき逃げ）の現行犯で逮捕された。

［source：］仙台で起きた2度目のアーケード暴走は懲役3年の実刑 | レスポンス（Response.jp） https://response.jp/article/2007/03/24/92922.html
```

　同じ年の4月と12月に2回，宮城県仙台市青葉区内のアーケード街で暴走事件があったというのも知らなかったように思います。12月の事件は死者は出ておらず，懲役3年の実刑という軽く感じる量刑となっています。

国道48号 - Google マップ https://t.co/UuMPMHbxHN

　昨日，国道47号線と間違って記述したと思う国道48号線ですが，今，Googleマップで再確認すると仙台駅や，仙台地方裁判所のすぐ近くを通過していることに気が付きました。未来都市にも見えるような場所があったことは印象に残っていて，仙台市内の中心部とは思っていました。

　この国道48号線は仙台市内に入るといつの間にか国道45線に変わり，そのまま多賀城市内の商店街を通過したとも記憶にあります。最初に塩釜市に行った頃，通った道路でしたが，その後は，給油所もある別の広い道路で塩釜市に向かっていました。

　石川県でも国道8号線のルートが変わっていることをGoogleマップでみているのですが，30年ほど前とは国道45号線のルートも変わっている可能性があります。塩釜市内をストリートビューで見ても，ほとんど以前の面影が残っていない気がしました。

　仙台市内の国道4号線から塩釜市内に向かうとき，陸橋になっていたのかも記憶にないですが，右手の広い道路に入ると，しばらくして左側に大きな駐車場のパチンコ店が２店と，それに隣接して大きな入浴施設がありました。今だとスーパー銭湯になるのかもしれません。

　左手にそのパチンコ店らの敷地があって，少し先に右手にガソリンスタンドがあって，いつもそこで給油をしていました。一光のカードを使っていましたが，特に大型車が集まるような大きなガソリンスタンドではありませんでした。

　国道４号線には，福島県から宮城県に入った岩沼市の辺りにも一光のカードの使えるガソリンスタンドがあって，仙台市に向かって左手でしたが，そちらはかなり大きなガソリンスタンドでした。少し手前で国道６号線が合流していたとも思います。

　岩沼市の先が名取市で仙台市の手前だったと思いますが，仙台市に向かって国道４号線から左折し，しばらく走った先に中越運送の定期便の荷降ろしをする運送会社がありました。福島県郡山市との２箇所おろしで，郡山市の方は中越運送になっていたと記憶にあります。

　名取市の運送会社の方が大きかったのですが，東北自動車道をどのインターで降りたのかを含め，余り思い出せなくなっています。なお，仙台市内に向かって左手というのは，海とは反対の山側になります。

　仙台市内の国道4号線は，広い道路でしたが，仙台南有料道路の入り口を越えてから広くなっていたような気もします。もうしばらく行くと，左手に第一貨物の大きなターミナルがありました。トナミ運輸の定期便は，この第一貨物で荷降ろしをしていました。

　駅のプラットフォームを大きくしたような第一貨物のターミナルで，ビルのような建物は記憶にないのですが，その敷地は，当時自分がみた運送会社で最大のものであったかもしれません。国道4号線からも目立つ建物でした。

〈〈〈：Linux Emacs： 2020-07-17（金曜日）14：19 　〈〈〈

* 第一貨物と同じく仙台市の運送会社として記憶と印象にあった三八五物流，「のらくろ」という古い漫画，昭和60年春の優水化成の東北での仕事
  :LOGBOOK:
  CLOCK: [2020-07-17 金 14:42]
  :END:

:CATEGORIES: 中西運輸商

〉〉〉：Emacs： 2020-07-17（金曜日）14：42　 〉〉〉

```
沿革［編集］
青森県下の三戸、八戸および五戸などを地盤とする地場零細の運送業者多数は、1940年（昭和15年）（八戸地区での少数社への統合整理）と1942年（昭和17年）の二次にわたって戦時統制により統合され、1942年の統合で地域一帯を版図とする南部貨物自動車が成立した。

戦後の統制緩和で1947年（昭和22年）に南部貨物自動車は6ブロックに分割され、うち3ブロックは速やかに独立した企業となったが、残り3ブロックは当面独立採算の営業所として発足した。このうち、八戸市地域の営業所として三八五営業所が業務を開始し、同営業所は1949年に改めて独立した企業の三八五貨物自動車運送として発足した。

［source：］三八五流通 - Wikipedia https://ja.wikipedia.org/wiki/%E4%B8%89%E5%85%AB%E4%BA%94%E6%B5%81%E9%80%9A
```

　ずいぶん古い時代の雰囲気をもつ運送会社で，小さい頃にみることのあった「のらくろ」という漫画にイメージが重なることがありました。調べたところ昭和22年に青森県八戸市から発足したとありました。

　国道4号線で，青森県と岩手県の県境には，漢数字で一戸から九戸のような地名が集まっていたと記憶にあります。青森市から石巻市に向かうとき，ほとんど八甲田山の有料道路を使っていたので，それだと十和田市の近くで国道4号線に出るので，通過することはなかったとも思います。

　昭和60年も冬が長く残雪が多かったと思います。その雪解けを待って工事が始まると聞きましたが，中西運輸商では当時の石川県羽咋郡押水町の優水化成から，東北への建築資材の仕事が集中しました。優水化成は魚箱の発泡スチロールもありましたが，断熱材の製品もありました。

二戸市 - Google マップ https://t.co/wc1Uzml80y

　Googleマップで確認すると二戸市が岩手県となっていました。金田一温泉というテレビで見たことのあるようなばしょがあって，「いわて銀河鉄道」というこれは初めて見るものがその付近にありました。

　県境付近の岩手県と記憶にあるので，この二戸市になるのかと思いますが，ほぼ国道4号線，青森から岩手に向かうとみ左手に荷降ろしの建材店がありました。裕福そうな自宅兼会社として記憶にあるのですが，たまたまトイレを借りたところ，それが初めて見る温水器付きだったのです。

　テレビで大きな話題を見るようになってしばらくした頃でしたが，現物を見たのは初めてで，それもずいぶんと田舎だったので驚きが大きく，よく憶えています。周囲に家はなく，あっても少なかったと思います。

　ここ2,3日の間に本で知ったことになると思いますが，松山事件の元死刑囚の自宅も割と大きな製材店で比較的裕福だったという話でした。「仙台地方裁判所 昭和６０年（ワ）８３２号 判決」では初めの方に家族構成があって，9人兄弟の次男となっていたかに思います。

　松山事件の取調べや捜査をしたのも古川警察署と知りました。もともと長距離トラック運転手の仕事で印象に残る宮城県古川市だったのですが，古い時代の貨物や駅舎に重なるイメージがあって，これはよく似た名称の茨城県古河市ともいくらか混同があるかもしれません。

　あの国道4号線沿いにあった宮城県古川市が，宮城県大崎市に変わっていたと知ったのも，松山事件を調べたことがきっかけであったように思います。宮城県の松山事件と福島県の松川事件の混同というのも，私に限ったことではなく，よくある勘違いと本で読みました。実際のつながりもある事件です。

```
泉市（いずみし）は、1971年（昭和46年）から1988年（昭和63年）まで宮城県に存在した市。

現在は仙台市泉区となっている。

［source：］泉市 - Wikipedia https://ja.wikipedia.org/wiki/%E6%B3%89%E5%B8%82
```

　上記の宮城県泉市も記憶と印象にあったものですが，昭和63年に仙台市泉区になったとあります。その泉市の上に古川市があったと記憶にあるのですが，荷物を運ぶのに通過したという記憶は薄いのに，その場所を通行していたという記憶は，割合鮮明に残っています。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-17 15:18／2017/10/19 11:54 URL： https://twitter.com/kk_hirono/status/1284009632139055105 https://twitter.com/hirono_hideki/status/920845586709979136  

> 宮城県大崎市という。宮崎県かと思った。なんとなく南国というイメージもあるが、以前、宮城県に大崎市というのはなかったはずかと思う。どの辺りなのか見当もつかない。昔になるが宮城県は定期便でよく行っていた。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-17 15:19／2017/10/19 12:02 URL： https://twitter.com/kk_hirono/status/1284009730537472001 https://twitter.com/hirono_hideki/status/920847506195464192  

> 大崎市 - Wikipedia https://t.co/U3eJJDKIQB  　古川市から鳴子町まで含まれるらしい。山形、秋田の県境にもなっている。東北道の古河インターは、石巻から出発して、塩釜に立ち寄らない時に利用していた。仙台市内も通行しなくてよかった。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-17 15:19／2017/10/19 12:08 URL： https://twitter.com/kk_hirono/status/1284009769217298432 https://twitter.com/hirono_hideki/status/920849142770892800  

> 「参拝したのにご利益ない」神社に放火と裁判で | NNNニュース https://t.co/BZ1M7PFVSh 　「大崎市」で検索していると出てきたニュース。テレビで見た交通トラブルのニュースは見つからない。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-17 15:20／2017/10/19 07:55 URL： https://twitter.com/kk_hirono/status/1284009963879190533 https://twitter.com/hirono_hideki/status/920785560142168064  

> ＼奉納＼さらば弁護士鉄道・泥棒神社の物語　@hirono_hideki＼報道ステーションの栃木女児殺害事件の控訴審の報道。今村核弁護士 https://t.co/E2YM89sZPJ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-17 15:20／2017/10/19 08:59 URL： https://twitter.com/kk_hirono/status/1284010087825068033 https://twitter.com/hirono_hideki/status/920801547100962816  

> なぜ栃木女児殺害事件の裁判で「Nシステム」を証拠として使うことが異例の事態なのか 前田恒彦 2016/3/2 - 来栖宥子★午後のアダージォ https://t.co/dlHtGBmGya  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-17 15:21／2017/10/19 10:00 URL： https://twitter.com/kk_hirono/status/1284010251457454080 https://twitter.com/hirono_hideki/status/920816798127226880  

> 「女性ヤメ検弁護士」が起こした刃傷事件　取り調べに完黙 | デイリー新潮 https://t.co/e5ByDXpLtH  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-17 15:21／2017/10/19 11:30 URL： https://twitter.com/kk_hirono/status/1284010383322185729 https://twitter.com/hirono_hideki/status/920839433481416704  

> 奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: ＼サイ太　@uwaaaa＼185人の弁護士が雁首そろえていながらすぐに対応できないあたり、アディーレさんの実力が伺い知れますよね。 https://t.co/zccUTnhwGN  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-17 15:22／2017/10/19 11:51 URL： https://twitter.com/kk_hirono/status/1284010600394133504 https://twitter.com/hirono_hideki/status/920844719462088704  

> 49歳と21歳の母娘。中国自動車上り線で、落ちていたタイヤに乗り上げ走行不能に、路肩に退避していたところに、同じくタイヤに乗り上げたトレーラーが横転し、死亡したというニュース。最初、車の傷が少ない不思議な死亡事故だと思った。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-17 15:23／2017/10/19 13:07 URL： https://twitter.com/kk_hirono/status/1284010851297460224 https://twitter.com/hirono_hideki/status/920863859493060608  

> ＼清水 潔　@NOSUKE0607＼「レイプ行為を告発された山口敬之・元TBSワシントン支局長（51）。その山口氏が保守派の論客として頭角を現すきっかけとなった「週刊文春」の記事に、捏造疑惑 https://t.co/JD0X6dsd16  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-17 15:23／2017/10/19 13:07 URL： https://twitter.com/kk_hirono/status/1284010896742735872 https://twitter.com/hirono_hideki/status/920863890291900416  

> ＼有田芳生　@aritayoshifu＼筆者とはもちろん伊藤詩織さん。本格的なノンフィクションを読み終えました。総括的な感想は改めて書きます。日常では知ることのない、 https://t.co/EcmrYKOS4W  

　奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「大崎市」の検索結果 - Twilog https://t.co/8vxvPF7QAE

　2017年10月19日は154件のツイートとなっています。Twilogの大崎市の検索で出たのは，この2017年10月19日だけで，そのあとは数日前の7月6日しか記録にありません。松山事件を調べての発見と思っていたのですが，それらしい松山事件のツイートは見当たりませんでした。

　本当に，つい最近になって注目することになった松山事件ですが，それまで余り注目する機会がなかったのも事実かと思います。その辺りを踏まえ，経過を調べ，道筋を確認しておきたいと思います。弁護士鉄道東北線です。

〈〈〈：Linux Emacs： 2020-07-17（金曜日）15：34 　〈〈〈

