* Windows10，ワープロソフト一太郎での告発状書面の作成を決定，午後は宇出津新港の職業安定所
  :LOGBOOK:
  CLOCK: [2020-07-30 木 19:52]
  :END:

:CATEGORIES: パソコン

〉〉〉：Emacs： 2020-07-30（木曜日）19：52　 〉〉〉

　午前中，Windows10を起動し，ワープロソフト一太郎で，マクロの作成をやっていました。思いの外，簡単でわかりやすくもあったのですが，呼び出すシステムコマンドのpythonスクリプトで，思わぬミスを連発し，こけつまろびずで手間取っていました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中） 日時：2020-07-30 19:59／2020/07/30 11:54 URL： https://twitter.com/kk_hirono/status/1288791394149003264 https://twitter.com/kk_hirono/status/1288669369090732032  

> 〒920-0912金沢市大手町6番15号  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中） 日時：2020-07-30 19:59／2020/07/30 12:27 URL： https://twitter.com/kk_hirono/status/1288791403300966401 https://twitter.com/kk_hirono/status/1288677667487637507  

> &lt;function lazy_load_stub_paste at 0x000001CDFBFCE700&gt;  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中） 日時：2020-07-30 19:59／2020/07/30 13:30 URL： https://twitter.com/kk_hirono/status/1288791426055118848 https://twitter.com/kk_hirono/status/1288693404382068738  

> 一太郎で告発状を作成しようか思案中，マクロからカレント行のテキストをツイートできるようになった。  

　11次54分のツイートで，スクリプトの実行自体は成功しています。12時27分のツイートはエラーの内容ですが，エラーが解決できたのが13時30分のツイートです。なぜか（）を付けておらず，プロパティの値を読み込んでいたもので，メソッドの実行で解決しました。

　どうも値を参照するプロパティと処理を実行するメソッドの名前が同じだったようです。これはpython特有なのかと思いますが，メソッドの実行は引数がなくてもしっかり明示する必要があるらしいと，勉強になりました。

　もともと一太郎2019は，日本語変換のATOKが欲しかったのですが，購入金額が余り変わらなかったこともあり，ATOKを同梱する一太郎2019をダウンロード版として購入，インストールしました。ずっと前に登録した会員割引となっています。

　ワープロソフト一太郎は，平成9年4月に定価で53万円だったノートパソコンを金沢市のパソコンの館で43万円で買ってきてからずっと使い，平成15年に金沢地方裁判所に行ったついでに，金沢市高柳の百満ボルトでバージョンアップ版を購入したことを憶えています。

　平成18年辺りに当時はあったATOKのLinux版をダウンロードで購入したのですが，Windowsパソコンでは一太郎をバージョンアップしないままWindows8の頃には，一太郎を使わなくなっていたように思います。

　昨年の2019年で，9月にOffice365をインストールするより，一月ほど前だったと思うのですが，日本語変換の効率化のためATOKが欲しくなって，値段が余り変わらなかったこともあって一太郎2019をダウンロード版で購入したのです。

　その一太郎2019も，インストールした頃は試しにちょっと使ってみたのですが，必要な文書はOffice365のWordで作成していました。Office365のビジネスで，つい最近，Microsoft365に変わったと知ったところですが，個人ではないライセンスで購入していました。

　一太郎2019は個人で購入したもので，会員の割引というのも平成9年から続くものかと思います。少なくとも平成11年8月12日の金沢中警察署の逮捕までは，ワープロソフト一太郎を使って文書や，金沢地方裁判所に提出した再審請求の書面を作成していました。

　2016年と2017年も同じ祭礼委員会の仕事で，WordやExcelを使っていたのですが，昨年の2019年に再び同じ祭礼委員会の仕事で再びWordやExcelを使うようになって，ずいぶん進化して使いやすくなったものだと思っていました。しかし，それでも微妙な不満はありました。

　一太郎のマクロは，JSマクロなどとなっていましたが，Linuxの環境でネットで調べると情報が乏しく，Windows10の環境で一太郎を起動したヘルプで，ようやくマクロの使い方や，使える関数名がわかりました。不思議なほどネットの情報は少ない感じです。

　探し方が悪かったのかもしれないですが，一太郎のマクロは，情報を探し出すのに難儀しました。システムコマンドとして読み出すpythonスクリプトの方で躓きがあったのですが，半日仕事より短い時間で，やりたかった段落のテキストのTwitter投稿が出来るようになりました。

　Windows10でのpythonもずいぶん使いやすくなったと実感しています。その気になって頑張れば，大抵のことは実現できそうです。

〈〈〈：Linux Emacs： 2020-07-30（木曜日）20：41 　〈〈〈

