* 「こういう店は店名を晒されるべきだと思う。別にネット上で袋叩きにしたり電凸したりする必要はない。」という深澤諭史弁護士のリツイート，三浦義隆弁護士のツイート

:CATEGORIES: 深澤諭史弁護士,三浦義隆弁護士

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2020/09/29 10:09 URL： https://twitter.com/fukazawas/status/1310748382286106624  

> RT @lawkus: こういう店は店名を晒されるべきだと思う。別にネット上で袋叩きにしたり電凸したりする必要はない。潜在的顧客が調べればわかるよう、こういうことをする店だという情報が残ればよい。そうした情報には公益性がある。 https://t.co/bXIVxpb90Z  

- RT fukazawas（深澤諭史）｜lawkus（ystk） 日時：2020/09/29 10:09／2020/09/29 10:05 URL： https://twitter.com/fukazawas/status/1310748382286106624 https://twitter.com/lawkus/status/1310747545942069248

> RT @lawkus: こういう店は店名を晒されるべきだと思う。別にネット上で袋叩きにしたり電凸したりする必要はない。潜在的顧客が調べればわかるよう、こういうことをする店だという情報が残ればよい。そうした情報には公益性がある。 https://t.co/bXIVxpb90Z  

@lawkus ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@lawkus）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW lawkus（ystk） 日時：2020/09/29 10:05 URL： https://twitter.com/lawkus/status/1310747545942069248  

> こういう店は店名を晒されるべきだと思う。別にネット上で袋叩きにしたり電凸したりする必要はない。潜在的顧客が調べればわかるよう、こういうことをする店だという情報が残ればよい。そうした情報には公益性がある。 https://t.co/bXIVxpb90Z  

　ちょうど24時間ほど前に見た憶えがあったのですが，三浦義隆弁護士のツイートが昨日9月29日の午前10時5分，深澤諭史弁護士のリツイートが午前10時9分となっていました。9月30日午前10時46分現在でリツイートは144件と，昨日とほとんど変わりがないように思います。

　昨日は12時30分の予定で小木港に向かい，夜の10時まで東一文字堤防でアオリイカのエギングとアジ釣りをしていました。家に戻ったのは23時頃になっていたと思いますが，戻ってからもテレビをつけることがなく，今朝もまだテレビはつけていません。

　このところテレビをみている時間が少ないのですが，三浦義隆弁護士が問題にした番組は，たまたま視聴をしていました。最初，日曜の夜のMr.サンデーかと思ったのですが，引用ツイートのテレビ画面の写真で，お昼のバイキングの放送だったことを思い出しました。

　「こういうことをする店だという情報が残ればよい。そうした情報には公益性がある。」というのが，弁護士的価値観，弁護士正義なのだとしみじみ噛み締めました。犯罪の実名報道などでは強くそれを否定するのも三浦義隆弁護士のポリシーなのだと感じてきました。

　話題性のありそうなツイートなので，もっとリツイートの数が増えるのかと思っていたのですが，そうでもなかったようです。2017年の5月だったと思いますが，三浦義隆弁護士のブログ記事がずいぶんアクセス数を上げたという時期もありました。痴漢えん罪関係だったと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-30 10:58／2020/09/29 11:43 URL： https://twitter.com/kk_hirono/status/1311123106526670848 https://twitter.com/s_hirono/status/1310772092451741697  

> 2020-09-29-111945_深澤諭史さんがリツイート￼ystk@lawkus·1時間こういう店は店名を晒されるべきだと思う。別にネット上で袋叩きにしたり電凸したりする必.jpg https://t.co/nZ8g5jjlHD  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-30 10:58／2020/09/29 11:43 URL： https://twitter.com/kk_hirono/status/1311123133651247105 https://twitter.com/s_hirono/status/1310772165067730944  

> 2020-09-29-112300_ystk@lawkusこういう店は店名を晒されるべきだと思う。別にネット上で袋叩きにしたり電凸したりする必要はない。潜在的顧客が調べればわか.jpg https://t.co/HqvIIebKHP  

* 「「警察官は法律の素人です・・・などと書いた看板を警察署近辺に設置する活動を、弁護士会がやるべきだと思う」という2017年12月13日のローカスこと三浦義隆弁護士のツイート，リツイートが7,857

:CATEGORIES: 三浦義隆弁護士,警察

@lawkus ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@lawkus）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW lawkus（ystk） 日時：2017/12/13 20:38 URL： https://twitter.com/lawkus/status/940908871001845761  

> 「警察官は法律の素人です」  
> 「"認めれば不起訴にしてやる" "認めれば執行猶予がある" "黙秘すれば認めたのと同じになる" "詳しくは言えないが動かぬ証拠を押さえてるから自白してしまえ" などは全て詐欺です」  
> などと書いた看板を警察署近辺に設置する活動を、弁護士会がやるべきだと思う  

　ローカスこと三浦義隆弁護士がネットで最も注目されたのが2017年5月という記憶でした。ブログのアクセス数が記録的という話でしたが，ツイートもそれなりの反応があったものと考え調べたところ，意外な結果でした。簡易な方法ですが，次のコマンドでファイルをコピーしています。

>|bash|
locate 2017-05 |grep ystk | xargs -I % cp % ./
||<

```
~ ❯❯❯ cd w
~/w ❯❯❯ ls
 2017-05-10-024439_深澤諭史さんがリツイート＞　ystk＞　まあ過度に好戦的なネット民は十中八九反論よりも治療が必要な感じではある。.jpg
 2017-05-10-024504_深澤諭史さんがリツイート＞　ystk＞　まあ過度に好戦的なネット民は十中八九反論よりも治療が必要な感じではある。.jpg
 2017-05-12-002856_弁護士　村松　謙さんがリツイート＞　ystk＞　　俺はDV加害者について書いただけなのに、不思議なことに自称連れ去り被害者の方々から攻撃的.jpg
 2017-05-12-010145_弁護士　村松　謙さんがリツイート＞　ystk＞　離婚事件と労働事件を扱っていて常日頃感じていることを書いた。.jpg
'2017-05-14-090924_ystkさんがれいな@底なし沼の魔女をリツイートしました＞　ひどいデマだな。デマは恥だがRT伸びるってか。いや恥とも思ってないのか。.jpg'
'2017-05-14-090957_ystkさんがれいな@底なし沼の魔女をリツイートしました＞　ひどいデマだな。デマは恥だがRT伸びるってか。いや恥とも思ってないのか。.jpg'
'2017-05-14-091012_ystkさんがれいな@底なし沼の魔女をリツイートしました＞　ひどいデマだな。デマは恥だがRT伸びるってか。いや恥とも思ってないのか。.jpg'
 2017-05-14-234559_弁護士　村松　謙さんがリツイート＞　ystkさんがスガノアキヒコ％石油王に俺はなる！をリツイートしました＞　とてつもない馬鹿だなこいつ。最初.jpg
 2017-05-15-082831_髑髏島の泥濘大魔王さんがリツイート＞ystk＞　逃げれば逃げ切れずに勾留までされる可能性が大だから、むしろそっちの方が弁護士費用は嵩むんだけ.jpg
 2017-05-15-165950_深澤諭史＞深澤諭史さんがystkをリツイートしました＞　ここにかけないようなかなりぶっちゃけたこと，警察とかから，いわれたことありますし（汗.jpg
 2017-05-27-001927_ystkさんが受験生サンシャイン吉岡をリツイートしました＞　大丈夫？そんなにつらいの？なんなら話聞くよ？30分540000円だけど（´・ω・.jpg
~/w ❯❯❯ 
```

"アクセス数" (from：lawkus) - Twitter検索 / Twitter https://twitter.com/search?lang=ja&q=%22%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%E6%95%B0%22%20(from%3Alawkus)&src=typed_query

- TW lawkus（ystk） 日時： 2017/04/22 16:02 URL： https://twitter.com/lawkus/status/855678218304602112  

> ブログ、一昨日昨日と更新しなかったにもかかわらず今日アクセス数が急増してた。1日平均1500PVくらいなのに今日は現時点で5000PV以上。借金玉さんが言及してくれたおかげっぽい。借金玉さんありがとうございます。 https://t.co/VIjkckPFoB  

"アクセス" (from：lawkus) - Twitter検索 / Twitter https://twitter.com/search?q=%22%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%22%20(from%3Alawkus)&src=typed_query

- TW lawkus（ystk） 日時： 2017/05/14 19:42 URL： https://twitter.com/lawkus/status/863706112125566977  

> 続編。  
> 痴漢を疑われた場合の弁護士アクセス手段をいくつか挙げておこう - 弁護士三浦義隆のブログ  
> https://t.co/aIWoCEqQ6O  

- TW lawkus（ystk） 日時： 2017/05/22 10:48 URL： https://twitter.com/lawkus/status/866470680073609216  

> フジテレビに出てもブログのPVは微増程度だった。毎日新聞のウェブ版記事がヤフートップに載ったときは一目瞭然に跳ね上がったが。毎日紙面版とか東京FMとかabemaTVがあまり影響ないのはわかるが、地上波でもここまで影響小さいというのは少し意外。TV観る層とネット民の断絶を感じた。  

- TW lawkus（ystk） 日時： 2017/05/22 12:02 URL： https://twitter.com/lawkus/status/866489533839187968  

> オンエア見てなかったんだけど録画で確認してびっくり。単にインタビュー受けただけならわざわざ名前でググったりしないよなとも思うけど、この切り口で紹介されてもほとんどブログのアクセス増えないってすごくない？放送された10時台のPV、微増はしてるけど600程度だよ。マジで断絶深いな。 https://t.co/uYgebqVZqQ  

"記録" (from：lawkus) until：2017-05-31 since：2017-04-01 - Twitter検索 / Twitter https://twitter.com/search?lang=ja&q=%22%E8%A8%98%E9%8C%B2%22%20(from%3Alawkus)%20until%3A2017-05-31%20since%3A2017-04-01&src=typed_query

　思った情報がみつからないですが，「痴漢を疑われた場合の弁護士アクセス手段をいくつか挙げておこう」という辺りの話題性だったと確認できました。テレビ出演の件は忘れていましたが，これも意外な発見となりました。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-30 11:33／2020/09/30 11:31 URL： https://twitter.com/kk_hirono/status/1311132086087028737 https://twitter.com/s_hirono/status/1311131637791354881  

> 2020-09-30-113101_”記録”　（from：lawkus）　until：2017-05-31　since：2017-04-01　-　Twitter検索　／　Twi.jpg https://t.co/fR1RQngZtW  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-30 11:33／2020/09/30 11:31 URL： https://twitter.com/kk_hirono/status/1311132109201797120 https://twitter.com/s_hirono/status/1311131564856602624  

> 2020-09-30-110923_ystk@lawkus·2017年12月13日「警察官は法律の素人です」「”認めれば不起訴にしてやる”　”認めれば執行猶予がある”　”黙秘す.jpg https://t.co/JT6ckMfTRa  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-30 11:33／2020/09/30 10:40 URL： https://twitter.com/kk_hirono/status/1311132130064257026 https://twitter.com/s_hirono/status/1311118679115886592  

> 2020-09-30-104007_ystk@lawkusこういう店は店名を晒されるべきだと思う。別にネット上で袋叩きにしたり電凸したりする必要はない。潜在的顧客が調べればわか.jpg https://t.co/ZDum4uV3Ua  

　今，一通り2017年5月12日付の三浦義隆弁護士の「痴漢を疑われても逃げるべきではない理由」という記事を読んだのですが（脚注はまだ），リツイートの数が1万8千という三浦義隆弁護士のツイートを見つけました。

　惑星のような印象的なアイコンの弁護士アカウントが関係していたようですが，これも不思議と記憶にありませんでした。弁護士といえば，惑星というイメージができた要因の１つです。よく見ると，惑星は惑わす星とも読めるようです。今まで気が付きませんでした。

(from：lawkus) min_retweets：1000 - Twitter検索 / Twitter https://twitter.com/search?q=(from%3Alawkus)%20min_retweets%3A1000&src=typed_query

　Twitterの検索オプションで，リツイートの数が一定以上という指定が出来ることを思い出し，少し調べてから実行をしました。そこで見つけたのが再掲になりますが，標題のローカスこと三浦義隆弁護士のツイートです。

- TW lawkus（ystk） 日時： 2017/12/13 20:38 URL： https://twitter.com/lawkus/status/940908871001845761  

> 「警察官は法律の素人です」  
> 「"認めれば不起訴にしてやる" "認めれば執行猶予がある" "黙秘すれば認めたのと同じになる" "詳しくは言えないが動かぬ証拠を押さえてるから自白してしまえ" などは全て詐欺です」  
> などと書いた看板を警察署近辺に設置する活動を、弁護士会がやるべきだと思う  

　弁護士はここまで警察を愚弄しているのかと目を瞠る思いがあったローカスこと三浦義隆弁護士のツイートで，これが弁護士だ，ということで，これは石川県警察の全警察官にも肝に銘じてもらいた弁護士鉄道の記録資料になります。

* @lawkusというローカスこと三浦義隆弁護士のTwitterアカウントのユーザ名と「素人」をキーワードに含む弁護士鉄道の記録資料

:CATEGORIES: 三浦義隆弁護士

```
~/w ❯❯❯ dp -p|grep lawkus |grep 素人
 - 2017年10月20日22時37分の登録： ＼ystk　@lawkus＼正面から反論して議論になっちゃったりすると収拾付かなくなるから反論は下策。素人と議論しても無意味だし http://hirono2014sk.blogspot.com/2017/10/ystklawkus_20.html
 - 2017年10月23日06時09分の登録： ＼ystk　@lawkus＼そりゃ法曹相手に素人が誘導尋問しようとしても成功するわけないわな。 http://hirono2014sk.blogspot.com/2017/10/ystklawkus_23.html
 - 2017年10月23日06時13分の登録： ＼弁護士あだちけいた㌠　@keita_adachi　RT：　@lawkus＼そりゃ法曹相手に素人が誘導尋問しようとしても成功するわけないわな。 http://hirono2014sk.blogspot.com/2017/10/keitaadachirtlawkus.html
 - 2017年10月26日18時44分の登録： REGEXP：”素人”／ystk（@lawkus）の検索（2010-02-02 21:45〜2017-10-23 00:24／2017年10月26日18時44分の記録170件） http://hirono2014sk.blogspot.com/2017/10/regexpystklawkus2010-02-02-21452017-10.html
 - 2017年10月26日18時46分の登録： ％@lawkus　ystk％最近モトケン先生が苛立っているご様子。まあようやく検察にも、裁判所や弁護士や官僚や政治家と同様に「素人の的外れな批判」が盛んに http://hirono2014sk.blogspot.com/2017/10/lawkusystk_26.html
 - 2017年11月21日05時16分の登録： ＼ystk　@lawkus＼素人が生半可に判決文なんか読むと、「強く抵抗しなかった。よって同意があった。よって無罪」式の乱暴な読み方をしてしまうことがあるが、これはもう仕 http://hirono2014sk.blogspot.com/2017/11/ystklawkus_63.html
 - 2017年11月22日21時57分の登録： ＼ystk　@lawkus＼どうしてツイッタラーは素人のくせにプロに独自見解を披露しようと思ってしまうのか http://hirono2014sk.blogspot.com/2017/11/ystklawkus_13.html
 - 2017年11月22日21時58分の登録： ＼モトケン　@motoken_tw　RT：　@lawkus＼どうしてツイッタラーは素人のくせにプロに独自見解を披露しようと思ってしまうのか http://hirono2014sk.blogspot.com/2017/11/motokentwrtlawkus.html
 - 2017年11月24日21時31分の登録： ＼ystk　@lawkus＼素人丸出しの言い分。元士業といっても弁護士以外だろう。俺が代理人で申立てた労働審判、9割以上は労働審判までで解決してるし、たいてい申立から1〜 http://hirono2014sk.blogspot.com/2017/11/ystklawkus91.html
 - 2017年11月30日21時30分の登録： ＼ystk　@lawkus＼素人が適当なこと書くなというのにまったくどいつもこいつも…(´・ω・｀) http://hirono2014sk.blogspot.com/2017/11/ystklawkus_18.html
 - 2017年12月04日23時39分の登録： ＼ystk　@lawkus＼同業者なら畏敬するレベルの奥村先生の高い専門性も素人はしばしば理解できないのだから、この世界では玄人と素人の情報の非対称性が本当に大きいなと思 http://hirono2014sk.blogspot.com/2017/12/ystklawkus_81.html
 - 2017年12月13日23時17分の登録： ＼ystk　@lawkus＼「警察官は法律の素人です」 「認めれば不起訴にしてやる 認めれば執行猶予がある 黙秘すれば認めたのと同じになる 詳しくは言えないが動かぬ証拠を http://hirono2014sk.blogspot.com/2017/12/ystklawkus_22.html
 - 2017年12月23日09時25分の登録： ＼ystk　@lawkus＼おっ。twitter名物、プロに講釈してくださる素人さんだ。しかも間違ってるし超カコイイ。 http://hirono2014sk.blogspot.com/2017/12/ystklawkustwitter_23.html
 - 2017年12月27日15時43分の登録： ＼ystk　@lawkus＼「弁護人にもやったと話し」とわざわざ書いてるのに、こういうこと言ってくる素人がいるからなあ。そりゃ、弁護人にやったと言ってる場合に冤罪の危険が http://hirono2014sk.blogspot.com/2017/12/ystklawkus_68.html
 - 2018年01月14日21時00分の登録： ＼ystk　@lawkus＼トラブルを抱えて不満なのに法律問題ではないということはかなり多い。そこの判断ができるのは法曹だけで、その素人との知識の差こそが我々の飯の種。だ http://hirono2014sk.blogspot.com/2018/01/ystklawkus_14.html
 - 2018年03月28日08時02分の登録： ＼ystk　@lawkus＼心証が灰色のときは白と扱う決まり（疑わしきは被告人の利益に）もない。この点、半端に黙秘権とか無罪推定とかいうキーワードを知ってる素人ほど誤解し http://hirono2014sk.blogspot.com/2018/03/ystklawkus_28.html
 - 2018年04月19日15時57分の登録： ＼ystk　@lawkus＼その点、福田事務次官は旧司法試験合格しているらしいが修習行かずに入省しちゃってるのでやっぱり素人。 http://hirono2014sk.blogspot.com/2018/04/ystklawkus_35.html
 - 2018年05月31日16時38分の登録： ＼ystk　@lawkus＼やはり情況証拠からの事実認定は素人には無理だなと思いながら見ていた。 http://hirono2014sk.blogspot.com/2018/05/ystklawkus_31.html
 - 2018年06月16日18時38分の登録： ＼ystk　@lawkus＼反証できるなら社会的地位は低下しないから名誉毀損にならないなどという珍説は今初めて聞いた。俺が繰り返し述べている「素人による法律論は常に間違い http://hirono2014sk.blogspot.com/2018/06/ystklawkus_16.html
 - 2018年06月19日04時20分の登録： ＼ystk　@lawkus＼\n\n警察に聞いたというのはつまり素人に聞いたということ。\n\nystkさんが追加\n http://hirono2014sk.blogspot.com/2018/06/ystklawkus-ystk.html
 - 2018年11月27日21時02分の登録： ＼ystk　@lawkus＼代理人弁護士の意図がある程度想像つく感じはある。素人が軽々に代理人が無能なのではとか論評するようなものでもないと思う。\n0件の返信 3件のリツ http://hirono2014sk.blogspot.com/2018/11/ystklawkus-0-3.html
 - 2019年01月12日08時35分の登録： REGEXP：”素人”／ystk（@lawkus）の検索（2010-02-02〜2019-01-10／2019年01月12日08時35分の記録226件） http://hirono2014sk.blogspot.com/2019/01/regexpystklawkus2010-02-022019-01.html
 - 2019年01月12日08時36分の登録： REGEXP：”警察．＊素人”／ystk（@lawkus）の検索（2017-06-07〜2018-08-13／2019年01月12日08時36分の記録4件） http://hirono2014sk.blogspot.com/2019/01/regexpystklawkus2017-06-072018-08.html
 - 2019年01月13日10時32分の登録： ＼ystk　@lawkus＼解説しよう。素人がボクサーに喧嘩を売ったがなぜか「ボクシングのルールでやろう」と申し入れてしまったのが話題の大量懲戒請求事件だ。 http://hirono2014sk.blogspot.com/2019/01/ystklawkus_13.html
 - 2019年02月06日00時41分の登録： ＼ystk　@lawkus＼村松謙さんがリツイート＞　ystk（@lawkus）：　素人が捜査段階で被疑者を犯人と決めつけてるの見るとドン引きするけど、冷静に考えてみる http://hirono2014sk.blogspot.com/2019/02/ystklawkusystklawkus.html
 - 2019年02月22日22時10分の登録： ＼ystk　@lawkus＼一般論として、弁護士が素人に内容証明を出すなどして損害賠償請求をする場合、初手は多少吹っかけ気味でも問題ない場合と初手から落とし所に近いライン http://hirono2014sk.blogspot.com/2019/02/ystklawkus_83.html
 - 2019年02月28日11時45分の登録： ＼ystk　@lawkus＼素人の「弁護士は仕事のため安易に破産を勧めるから破産せず踏ん張った方がいい」とかいう陰謀論レベルの話を安易に信じるくらい安易な人なら、安易に専 http://hirono2014sk.blogspot.com/2019/02/ystklawkus_13.html
 - 2019年03月15日06時40分の登録： ＼ystk　@lawkus＼「性交中だいたい寝てる様子だったけどときどき目を開けたり声も出したりしたことがある」くらいの状態なら素人目に見ても抗拒不能だろうから、話題の判 http://hirono2014sk.blogspot.com/2019/03/ystklawkus_15.html
 - 2019年03月15日20時39分の登録： ＼ystk　@lawkus＼放送中止せざるを得ない)という趣旨のツイートを見た。素人さんの発想は独創的でよろしおすなあという感想。 http://hirono2014sk.blogspot.com/2019/03/ystklawkus_59.html
 - 2019年04月08日03時29分の登録： ＼ystk　@lawkus＼ゴーン氏の妻が現時点で被疑者ですらなく、移動の自由を制限されるべき理由がないことくらい素人でもさすがにわかるはず。たまたま夫に対する捜査の巻添 http://hirono2014sk.blogspot.com/2019/04/ystklawkus_8.html
 - 2019年04月13日12時04分の登録： ＼ystk　@lawkus＼法を学んだことがない素人でも、記事本文に二重の危険云々と書いてあるのを読めるなら、「同じロジック」に基づいて有罪判決に対する控訴禁止論など成り http://hirono2014sk.blogspot.com/2019/04/ystklawkus_13.html
 - 2019年05月27日19時22分の登録： ＼ystk　@lawkus＼深澤諭史さんがリツイート＞　ystk（@lawkus）：　弁護士つかまえて法の何たるかを解いてくださる素人さんかっこいい。例によって「法治国 http://hirono2014sk.blogspot.com/2019/05/ystklawkusystklawkus_27.html
 - 2019年06月05日15時00分の登録： ＼ystk　@lawkus＼【悲報】元自称憲法学者の素人竹田氏、特殊刑法学にまで手を出してしまう http://hirono2014sk.blogspot.com/2019/06/ystklawkus_58.html
 - 2019年06月07日22時28分の登録： ＼ystk　@lawkus＼これって大麻を違法どころか犯罪とする理由としては全く足りてないので、EARL先生も医療に関しては立派な専門家でも、まあ素人考えの域を出ないなと http://hirono2014sk.blogspot.com/2019/06/ystklawkusearl.html
 - 2019年06月26日17時27分の登録： ＼ystk　@lawkus＼同サイトによれば、露木幸彦氏は素人レベルの知識に基づきこれまで離婚協議書作成900件を達成しているそうなので、既に多数の顧客に誤った説明をし、 http://hirono2014sk.blogspot.com/2019/06/ystklawkus900.html
 - 2019年06月26日17時28分の登録： ＼ystk　@lawkus＼【注意喚起】自称「離婚に特化した」行政書士の露木幸彦氏が、「離婚協議書に包括的清算条項を入れれば後に養育費増額請求ができなくなる」という素人レ http://hirono2014sk.blogspot.com/2019/06/ystklawkus_61.html
 - 2019年07月04日20時31分の登録： ＼ystk　@lawkus＼「書類送検」に何か特別の(有罪になりそうという方向の)意味を見出したがる素人の誤解は本当によく見るので、少しでも解消したいな。微力だが久々にブ http://hirono2014sk.blogspot.com/2019/07/ystklawkus_4.html
 - 2019年12月06日00時08分の登録： ＼ystk　@lawkus＼またもへもへがデタラメ言ってるのか。\nもへもへに限らず素人にはよく見られる誤解なので、俺のブログでも貼っておきますね。情況（状況）証拠だけで有 http://hirono2014sk.blogspot.com/2019/12/ystklawkus_6.html
 - 2019年12月13日11時58分の登録： ＼ystk　@lawkus＼前にも書いたけど、弁護士と素人の知識の格差こそがまさに独占資格たる弁護士資格の根拠であり、我々の飯のタネです。弁護士から見たら誤っている話を持 http://hirono2014sk.blogspot.com/2019/12/ystklawkus_13.html
 - 2020年01月02日02時16分の登録： ＼ystk　@lawkus＼これ「勝ち取られたのに、」までが完全に誤りだから素人の戯言以上のものではないのだが、玉井克哉先生がこれをRTしているのはどういうつもりなのであ http://hirono2014sk.blogspot.com/2020/01/ystklawkusrt.html
 - 2020年01月04日20時51分の登録： ＼ystk　@lawkus＼「日本の裁判官は買収されないから日本の司法は問題ない」的なことを述べる素人をここ数日で大勢見たが、じゃあ買収されず皆平等に保釈は一切認めず無罪 http://hirono2014sk.blogspot.com/2020/01/ystklawkus_19.html
 - 2020年03月11日02時25分の登録： ＼ystk　@lawkus＼↓適当なことをふかしてイキる素人の例 http://hirono2014sk.blogspot.com/2020/03/ystklawkus_46.html
 - 2020年04月04日01時43分の登録： ＼ystk　@lawkus＼20年以上30年未満の弁護士経験があるが素人並の経験知しか身につかなかった自己紹介はいたたまれないからやめてほしい、 http://hirono2014sk.blogspot.com/2020/04/ystklawkus2030.html
~/w ❯❯❯ 
```

　意外だったのはこれです。→　 - 2017年12月04日23時39分の登録： ＼ystk　@lawkus＼同業者なら畏敬するレベルの奥村先生の高い専門性も素人はしばしば理解できないのだから、この世界では玄人と素人の情報の非対称性が本当に大きいなと思 http://hirono2014sk.blogspot.com/2017/12/ystklawkus_81.html

奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: ＼ystk　@lawkus＼同業者なら畏敬するレベルの奥村先生の高い専門性も素人はしばしば理解できないのだから、この世界では玄人と素人の情報の非対称性が本当に大きいなと思 https://t.co/MdLq8YrOig

4件目 ツイート： lawkus（ystk） 日時： 2017-12-04 22:02 URL： https://twitter.com/lawkus/status/937668402285502464 
> 同業者なら畏敬するレベルの奥村先生の高い専門性も素人はしばしば理解できないのだから、この世界では玄人と素人の情報の非対称性が本当に大きいなと思う。その非対称性こそ我々のメシの種なわけだが。

6件目 （リツイート）： lawkus（ystk）｜okumuraosaka（児童ポルノ/わいせつ/青少年淫行弁護人） 日時：2017-12-04 21:55／2017-12-04 20:57 URL： https://twitter.com/lawkus/status/937666562844016640 https://twitter.com/okumuraosaka/status/937652158916313088 
> 専門分野分かりにくいかな。首突っ込むというか、弁護人として責任持ってやってるわけで https://t.co/4yLxLnpkCN

7件目 （リツイート）： lawkus（ystk）｜nodahayato（弁護士　野田隼人） 日時：2017-12-04 21:55／2017-12-04 19:13 URL： https://twitter.com/lawkus/status/937666548633821185 https://twitter.com/nodahayato/status/937626009314168832 
> 奥村先生って性犯罪関連の事件にやけに首突っ込んだり、コメントされたりしてますが、専門分野なのでしょうか？そういう専門分野もあるのですね？ — 最高裁判所 刑事判例集の性犯罪や児童ポルノ関係を10年分くらい眺めてみてください。 https://t.co/IUyMQFXdIc

　モトケンこと矢部善朗弁護士（京都弁護士会）が奥村徹弁護士のことを尊敬するとかリスペクトするというツイートをしていたのは，強く印象に残っていて忘れることもなかったのですが，三浦義隆弁護士の畏敬は神に近い存在をイメージさせるものでありながら，記憶にありませんでした。

```
~/w ❯❯❯ dp -p|grep motoken_tw |grep 奥村
 - 2018年03月02日17時52分の登録： ＼モトケン　@motoken_tw＼さすが奥村先生。 http://hirono2014sk.blogspot.com/2018/03/motokentw_75.html
 - 2018年05月06日17時16分の登録： REGEXP：”（奥村徹弁護士｜奥村弁護士｜奥村先生）”／モトケン（@motoken_tw）の検索（2010-10-29〜2018-04-26／2018年05月06日17時16分の記録13件） http://hirono2014sk.blogspot.com/2018/05/regexpmotokentw2010-10-292018-04.html
~/w ❯❯❯ 
```

@motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@motoken_tw）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW motoken_tw（モトケン） 日時：2016/11/23 18:59 URL： https://twitter.com/motoken_tw/status/801364416948269056  

> こういうことをさらっと言える奥村先生の凄さがわからないから、悪徳弁護士とか言っちゃう人がいるんだな。逮捕前弁護のノウハウ、つまり逮捕回避のノウハウをたくさんお持ちだということなんだが。 https://t.co/Zl5TC31dUp  

　これも意外に感じた発見ですが，実際に読んでいなかったツイートで，自作のプログラムの処理で機械的にデータベースに登録されたツイートという可能性もありそうです。

　さきほど思い出したのですが，モトケンこと矢部善朗弁護士（京都弁護士会）が奥村徹弁護士を尊敬するあるいはリスペクトすると言ったツイートは，質問に対する回答のようなもので，奥村徹弁護士の名前は含まれていなかったと思います。何かのトリガーになったような気もします。

```
~/w ❯❯❯ dp -p|grep motoken_tw |grep 尊敬
 - 2017年10月02日20時34分の登録： REGEXP：”尊敬”／モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）のツイートの記録（2011-08-06 00:16〜2017-08-12 17:47／2017年10月02日20時34分・19件） http://hirono2014sk.blogspot.com/2017/10/regexpmotokentw2011-08-06-00162017-08.html
 - 2018年02月01日05時47分の登録： ＼モトケン　@motoken_tw＼誰だよ「びろーん」の名付け親は、と思ったが、確か、尊敬する高島先生だったよね？違ったかな？ http://hirono2014sk.blogspot.com/2018/02/motokentw.html
 - 2019年10月14日12時42分の登録： REGEXP：”尊敬”／モトケン（@motoken_tw）の検索（2010-03-26〜2019-05-31／2019年10月14日12時42分の記録40件） http://hirono2014sk.blogspot.com/2019/10/regexpmotokentw2010-03-262019-05.html
 - 2020年02月24日19時14分の登録： ＼モトケン　@motoken_tw＼実名報道です。私は心から尊敬する。＞東京高検の黒川検事長の定年延長問題　検事正の乱「国民からの信頼が損なわれる」 (1/2) 〈週刊朝 http://hirono2014sk.blogspot.com/2020/02/motokentw-12.html
~/w ❯❯❯ 
```

@motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@motoken_tw）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW motoken_tw（モトケン） 日時：2014/05/22 11:01 URL： https://twitter.com/motoken_tw/status/469296978627952640  

> 佐藤弁護士を批判ないし非難するツイートも流れてくるが、私は佐藤弁護士を尊敬する。  
> 佐藤弁護士は、被告人の主張を弁護していたのではなく、被告人を弁護しているのだと思う。  
> さらに言えば、被告人の人生を弁護している。  

　PC遠隔操作事件も今は知らない人は，忘れている人も多そうです。考えてみると，確か8年ぐらいの刑期となっていたと思うので，刑務所からすでに出所している可能性もありそうです。服役に関しては情報を見ておらず，思い出したのも久しぶりです。

　「尊敬」で奥村徹弁護士に関連した，それらしいモトケンこと矢部善朗弁護士（京都弁護士会）のツイートは見当たりませんでした。

```
~/w ❯❯❯ dp -p|grep motoken_tw |grep リスペクト
 - 2019年10月14日15時08分の登録： REGEXP：”リスペクト”／モトケン（@motoken_tw）の検索（2017-09-14〜2017-09-14／2019年10月14日15時08分の記録2件） http://hirono2014sk.blogspot.com/2019/10/regexpmotokentw2017-09-142017-09.html
~/w ❯❯❯ 
```

　リスペクトは2件ともリツイートで，奥村徹弁護士とは無関係でした。

　少し諦めかけていたのですが，それらしいツイートを発見しました。2017年10月2日のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートですが，データベースのまとめ記事には含まれていなかったはずです。

- TW motoken_tw（モトケン） 日時： 2017/10/02 19:01 URL： https://twitter.com/motoken_tw/status/914792379579817984  

> @nioumasashi 私が尊敬する弁護士さんですよ。  

　見つからなかったのが不思議なツイートですが，これがきっかけで大きな発見がありました。すっかり忘れていたのですが，これも質問に対してモトケンこと矢部善朗弁護士（京都弁護士会）が，私をストーカーアカウントだと認諾したツイートになります。





