* 令和2年10月30日，宇出津新港の職業安定所に行ったことと，夕方からWSL2のMySQLのトラブル

　午前中，11時を過ぎてから向かったのですが雨が降り出していて，着いたと思ったら求職（就労）活動カードを忘れていたことに気が付き自宅に戻りました。職安を出た頃には雨もあがり，そのあと雨が降ることもなかったように思います。

　金沢地方検察庁に提出する告訴状を作成していることなど説明し，今就職できないことに理解が得られたという感じでした。

　午後もちょっと用事で出掛けたのですが，戻ってからWSL2のMySQLのトラブルが発生し，修復にずいぶんと時間がかかりました。不手際が重なって，データを全て失ったのですが，今朝になって別のパソコンから持ってきたもので，ほとんど復旧しました。

　MySQLの再インストールを行うため完全削除を行ったのですが，古い情報のままやったためか，aptが壊れてしまい，削除も再インストールも出来なくなりました。一時はWSL２の再インストールも考えたのですが，時間は掛かったもののなんとか解決できました。

* WSL2のUbuntuで，MySQLの完全削除と再インストール

完全削除
```
sudo apt-get remove --purge mysql-server* mysql-common
```

再インストール
```
sudo apt-get clean && sudo apt-get autoremove
sudo apt install mysql-server-8.0

sudo apt install libmysqlclient-dev
sudo gem install mysql2
```

　Rubyのmysql2が一緒に削除されていました。RubyからMySQLを操作するドライバーです。たぶん，mysql-serverだけでもmysql-server-8.0が入ると思います。依存関係でクライアントも入るようです。

* Windows10のWSL2で，操作性が劇的に改善された仮想端末konsoleとブラウザchromiumのインストール

　昼過ぎだったと思いますが，ふとした思いつきでkonsoleをインストールしました。WSL2にGUIでイントールして使っていたのはkateとEmacsぐらいでした。chromeもWSLの頃にインストールしましたが，使い物にならなかったように思います。

　WSLでFirefoxをインストールしても不安定で不具合があったように思います。aptでインストールしたものですが，今回はaptではなく，snapでインストールしました。「snap find chrome」とやって探したchromiumです。

　仮想端末konsoleとブラウザchromiumはどちらも通常のLinux環境と同じように，セレクションとクリップボードの使い分けが出来，xsel -oとxsel -bで別の値が取得できます。

　前からなんとかできないものかと調べたこともあったのですが，WSL2のコンソールだと，文字列の範囲選択の状態で右クリックでコピー，選択解除後の右クリックで貼り付けとなっているようです。少しは慣れてきたのですが，それでも面倒でした。

　Linuxだと範囲選択をしただけでセレクションに入り，そのあとのマウスの中ボタンクリックで貼り付けとなります。これはとても効率の良い作業になります。

 - Chromium - Wikipedia https://t.co/yvD6iPynMj

　上記のページに「Google Chromeはこのソースコードを引き抜いて開発されたものである[9]。」とありました。Google Chromeの方が本家のイメージがあったのですが，実際は逆だったようです。


