* 深澤諭史弁護士のリツイートで見た「アッサジ」，「某寺使ってあげたり国選やったり手弁当で人助けしたりするワシらは聖人やな」という2018年10月5日のツイート

:CATEGORIES: 深澤諭史弁護士,法テラス,国選弁護人,漫画

　「深澤諭史弁護士のリツイートで見た「アッサジ」，」という見出しの一部だけ作成していたのですが，昨日の持ち越しになります。これは改めて記録作成の措置を講じておきたいと考えていました。

　昨日は手塚治虫の火の鳥をWikipediaで調べて，手塚治虫が自分の人生をかけて手掛けた作品で，自分が死ぬときを物語の完結と設定していたと知りました。これは昭和11年生まれで私には生存の確認も出来ない安藤健次郎さんの人生，生涯とも重なる気がしました。

　火の鳥という漫画はまだ一度も読んでいないと思うのですが強いテーマ性は感じていました。一昨日になるのか手塚治虫氏のご長女のTwitterアカウントをブラック・ジャックのピノコのモデルという話から見ることになったのですが，火の鳥のような画像と鳳凰とありました。

　宇出津小学校の高学年と記憶にあるのですが，「三目とおる」というような手塚治虫の漫画がありました。記憶のままに書いたのでタイトルに間違いがあるかもしれません。以前，アッサジについて調べたところ出てきたのがこの手塚治虫の漫画だったのです。

　直接タイムラインを開くことはなかったアカウントのツイートだと思うので，最初に見たのは深澤諭史弁護士のタイムラインで深澤諭史弁護士にリツイートされたツイートだったと思われます。衝撃が走る内容のツイートでした。

@k999941457035 ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@k999941457035）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW k999941457035（K 9 9 9 9 9） 日時：2018/10/05 19:49 URL： https://twitter.com/k999941457035/status/1048163224758059008  

> 貸与世代で借金あるのに某寺使ってあげたり国選やったり手弁当で人助けしたりするワシらは聖人やな。自らの身体を動物に食べさせてあげたアッサジレベルやわ。  

```
(py37_env) a66@a66-XTe:~$ dp -p|grep アッサジ
 - 2019年03月19日09時10分の登録： ％@k999941457035　K - 9 9 9 9％ワシらは聖人やな。自らの身体を動物に食べさせてあげたアッサジレベルやわ。 http://hirono2014sk.blogspot.com/2019/03/k999941457035k-9-9-9-9.html
 - 2019年03月19日09時27分の登録： REGEXP：”アッサジ”／データベース登録済みツイート：2019年03月19日09時27分の記録：ユーザ・投稿：5／9件 http://hirono2014sk.blogspot.com/2019/03/regexp20190319092759.html
 - 2019年03月19日09時40分の登録： ＞@fukazawas　深澤諭史＞RT　@k999941457035：　手弁当で人助けしたりするワシらは聖人やな。自らの身体を動物に食べさせてあげたアッサジレベルやわ。 http://hirono2014sk.blogspot.com/2019/03/fukazawasrtk999941457035.html
 - 2019年05月25日09時57分の登録： REGEXP：”アッサジ”／データベース登録済みツイート：2019年05月25日09時56分の記録：ユーザ・投稿：6／12件 http://hirono2014sk.blogspot.com/2019/05/regexp201905250956612.html
```

　さきほど上記のまとめ記事を１つGoogle Chromeのブラウザで開いたのですが，埋め込みツイートが表示されず，これは最近よくある現象なのですが，下の方をみると私の奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)のアカウントのツイートの埋め込みが表示されていました。

　これは元のツイートが削除された可能性もあると思い個別に開いたところブロックされていることを示すメッセージが出てツイートが表示されず，Firefoxでまとめ記事を開いたところ元のツイートも埋め込みが表示され，個別にもツイートが削除されていないことを確認しました。

　これは次のスクリーンショットとして記録をしています。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-07-29 10:54／2020/07/29 10:28 URL： https://twitter.com/kk_hirono/status/1288291831332012032 https://twitter.com/s_hirono/status/1288285192033951744  

> 2020-07-29-102541_＞　貸与世代で借金あるのに某寺使ってあげたり国選やったり手弁当で人助けしたりするワシらは聖人やな。自らの身体を動物に食べさせてあげたアッサジ.jpg https://t.co/XQuDzCj5gW  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-07-29 10:54／2020/07/29 10:28 URL： https://twitter.com/kk_hirono/status/1288291844116246529 https://twitter.com/s_hirono/status/1288285264582868992  

> 2020-07-29-102625_＞　アッサジ　-　Google　検索　https：／／t。co／7fjTPCuczd.jpg https://t.co/i4p83n9eKe  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-07-29 10:54／2020/07/29 10:28 URL： https://twitter.com/kk_hirono/status/1288291863179362304 https://twitter.com/s_hirono/status/1288285337282740226  

> 2020-07-29-102645_＞　貸与世代で借金あるのに某寺使ってあげたり国選やったり手弁当で人助けしたりするワシらは聖人やな。自らの身体を動物に食べさせてあげたアッサジ.jpg https://t.co/a4ZJJVeALc  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-07-29 10:54／2020/07/29 10:29 URL： https://twitter.com/kk_hirono/status/1288291876500471808 https://twitter.com/s_hirono/status/1288285410250985472  

> 2020-07-29-102708_＞　貸与世代で借金あるのに某寺使ってあげたり国選やったり手弁当で人助けしたりするワシらは聖人やな。自らの身体を動物に食べさせてあげたアッサジ.jpg https://t.co/NIYXfXP793  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-07-29 10:54／2020/07/29 10:47 URL： https://twitter.com/kk_hirono/status/1288291892157800448 https://twitter.com/s_hirono/status/1288289955798630401  

> 2020-07-29-102818_K　9　9　9　9　9@k999941457035貸与世代で借金あるのに某寺使ってあげたり国選やったり手弁当で人助けしたりするワシらは聖人や.jpg https://t.co/v4BqF3Axx0  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-07-29 10:55／2020/07/29 10:47 URL： https://twitter.com/kk_hirono/status/1288291914790273024 https://twitter.com/s_hirono/status/1288290028242612224  

> 2020-07-29-102843_K　9　9　9　9　9@k999941457035貸与世代で借金あるのに某寺使ってあげたり国選やったり手弁当で人助けしたりするワシらは聖人や.jpg https://t.co/6KlrNAjhFb  

　このスクリーンショットはスクリプトという独自のプログラムで作成しています。最近作ったものですがブラウザがFirefoxの場合は，sc-firefox，同じくGoogle Chromeの場合は，sc-googlechromeというスクリプトを実行しています。

　Linuxの場合はいわゆるコピペ以外に，範囲選択したテキストがセレクションとして利用できるのですが，これにファイル名に使えない特殊文字の全角変換，決めた範囲での文字数のカットなどの処理をして，スクリーンショットのファイルを自動で作成しています。

　某寺というのも法テラスのことと思いますが，最近は見かけていないと思いTwilogで調べてみました。なお，最近でもちょくちょく見かけるのは法寺になります。法クラらしさを感じる風情があります。これと密接なのが成仏理論で，弁護士としての宗教性とも考えています。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-07-29 11:06／2015/08/20 21:21 URL： https://twitter.com/kk_hirono/status/1288294706367959040 https://twitter.com/s_hirono/status/634339491751157760  

> 某寺事件は、とりあえず申立書を送って事件番号付けてから交渉を開始するという生活の知恵。／（深澤諭史弁護士のリツイート） https://t.co/jAp2MLAQfk  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-07-29 11:06／2015/08/21 11:10 URL： https://twitter.com/kk_hirono/status/1288294805521330176 https://twitter.com/s_hirono/status/634548021800206336  

> 調停を某寺でやるときは、期日回数ごとの加算を導入すべき。ていうか、国選の期日報酬と同じで頼む。／（”うんこバースト”うの字） https://t.co/tiagiSv3AA  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-07-29 11:07／2018/08/23 08:48 URL： https://twitter.com/kk_hirono/status/1288294939030298624 https://twitter.com/s_hirono/status/1032414321337200641  

> 2018-08-22-204800_深澤諭史のリツイート（向原総合法律事務所　弁護士向原　@harrier0516osk）：某寺に国家予算ブチ込んで、実働する弁護士にはその予.jpg https://t.co/HP1yeLES4x  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-07-29 11:07／2018/10/06 20:14 URL： https://twitter.com/kk_hirono/status/1288294994244022272 https://twitter.com/s_hirono/status/1048532052847427584  

> 2018-10-06-161824_深澤諭史のリツイート（K9999　@k999941457035）：貸与世代で借金あるのに某寺使ってあげたり国選やったり手弁当で人助けしたり.jpg https://t.co/GM3AWNrgO3  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-07-29 11:07／2019/03/18 17:47 URL： https://twitter.com/kk_hirono/status/1288295141841633280 https://twitter.com/s_hirono/status/1107564162870177794  

> 2019-03-18-134308_深澤諭史さんがリツイート＞　暇弁（暇とは言ってない）（@himaben1st）：　某寺の闇は唯々「報酬が安すぎて赤字」なのに「余計な手続が多すぎる」こと.jpg https://t.co/z7WJPW9H1o  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-07-29 11:08／2019/03/19 10:51 URL： https://twitter.com/kk_hirono/status/1288295208363257857 https://twitter.com/s_hirono/status/1107821860308152322  

> 2019-03-19-091012_K　-　9　9　9　9さんのツイート：　”貸与世代で借金あるのに某寺使ってあげたり国選やったり手弁当で人助けしたりするワシらは聖人やな。自らの身体を動物に.jpg https://t.co/ytSsgkPHvY  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-07-29 11:08／2019/03/24 22:22 URL： https://twitter.com/kk_hirono/status/1288295289581789184 https://twitter.com/s_hirono/status/1109807719152640001  

> 2019-03-24-211306_江藤隆之さんのツイート：　”タイムラインに某寺というワードが流れてきてよく意味がわからないのですが，なんとなく某寺で修行していると成仏できそうな気がします.jpg https://t.co/a2tYE8MKWp  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-07-29 11:08／2019/06/07 23:05 URL： https://twitter.com/kk_hirono/status/1288295401905250306 https://twitter.com/s_hirono/status/1136997561376468992  

> 2019-06-07-214530_とらきちさんのツイート：　”某寺ふざけんなよ、自分たちの処理が遅れてたのを、依頼者に対して、俺が書類出してないと嘘をついてきやがった。”.jpg https://t.co/IEPx8LCeX6  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-07-29 11:09／2020/06/22 02:36 URL： https://twitter.com/kk_hirono/status/1288295492862926848 https://twitter.com/s_hirono/status/1274758220989427713  

> 2020-06-21-155547_深澤諭史さんがリツイートD弁@dben82716007·2時間弁護士は職務の自由と独立を重んじるとされてるのに、某寺では契約内容を自由にできないのよね….jpg https://t.co/lavuoP1Knl  

非常上告-最高検察庁御中_ツイッター(@s_hirono)/「某寺」の検索結果 - Twilog https://t.co/3txb9kHpv0

　検索結果のすべてのツイートをリツイートしたわけではないですが，7割ぐらいはリツイートしたかもしれません。最近は滅多にみかけなくなった「とらきち」というアカウントのツイートが記録されていて，ツイートの内容でやはり弁護士らしいと確認しました。

@torakiti0405 ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@torakiti0405）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW torakiti0405（とらきち） 日時：2020/06/27 21:00 URL： https://twitter.com/torakiti0405/status/1276847873645150210?phpMyAdmin=cfc2644bd9c947213a0141747c2608b0  

> 刑事事件で警察が言う事とも似てますね。相手を精神的に支配するのに弁護士がいると邪魔という点で共通点があるのでしょうね。 https://t.co/Wt2vt3E5tw  

　Twitterで「とらきち」とアカウントの検索をしたのですが，見つからず，Firefoxのブックマークでも見つからなかったので，データベースの記録から調べました。最後に記録されていたのが次のまとめ記事になります。

 - 2020年06月27日23時23分の登録： ＼とらきち　@torakiti0405＼刑事事件で警察が言う事とも似てますね。相手を精神的に支配するのに弁護士がいると邪魔という点で共通点があるのでしょうね。 http://hirono2014sk.blogspot.com/2020/06/torakiti0405.html

　このとらきちというアカウントも，強い宗教性を感じるところがあります。Twitterのプロフィールの写真がそれを物語るのですが，おそらく日光東照宮にある眠り猫かと思われます。三猿と同じ木彫りの彫刻と思われます。

　ヘッダ画像が古風な木の橋となっていますが，これは以前テレビで，時代劇の水戸黄門の出演者がグループで日光を散策するという番組の場面で見たように思います。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-07-29 11:27／2020/07/29 11:19 URL： https://twitter.com/kk_hirono/status/1288300057234534400 https://twitter.com/s_hirono/status/1288298022728687616  

> 2020-07-29-111828_とらきち@torakiti0405刑事事件で警察が言う事とも似てますね。相手を精神的に支配するのに弁護士がいると邪魔という点で共通点があるの.jpg https://t.co/bg06dbM48d  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-07-29 11:27／2020/07/29 11:19 URL： https://twitter.com/kk_hirono/status/1288300089752997889 https://twitter.com/s_hirono/status/1288298095369846784  

> 2020-07-29-111847_とらきち@torakiti0405刑事事件で警察が言う事とも似てますね。相手を精神的に支配するのに弁護士がいると邪魔という点で共通点があるの.jpg https://t.co/0KVME2cRzr  

〈〈〈：Linux Emacs： 2020-07-29（水曜日）11：29 　〈〈〈

* 深澤諭史弁護士のリツイートで見た「アッサジ」，「某寺使ってあげたり国選やったり手弁当で人助けしたりするワシらは聖人やな」というツイート，手塚治虫の漫画との関連性
  :LOGBOOK:
  CLOCK: [2020-07-29 水 11:31]--[2020-07-29 水 15:32] =>  4:01
  :END:

:CATEGORIES: 深澤諭史弁護士,漫画

〉〉〉：Emacs： 2020-07-29（水曜日）11：31　 〉〉〉

　まず，過去のTwilogから調べてみたいと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-29 11:33／2018/10/06 16:20 URL： https://twitter.com/kk_hirono/status/1288301603934466048 https://twitter.com/hirono_hideki/status/1048473094006833152  

> アッサジ - Google 検索 https://t.co/7fjTPCuczd  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-29 11:33／2018/10/06 16:24 URL： https://twitter.com/kk_hirono/status/1288301625354776576 https://twitter.com/hirono_hideki/status/1048474111549222912  

> アッサジ：キャラクター名鑑：https://t.co/sVpNm4Tsjl(JP) 手塚治虫 公式サイト https://t.co/mcwvA8L5Zg  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-29 11:33／2018/10/06 16:27 URL： https://twitter.com/kk_hirono/status/1288301655440519170 https://twitter.com/hirono_hideki/status/1048474745786707968  

> 手塚治虫のブッダで、アッサジは自分が獣に食われるのを知っ... - Yahoo!知恵袋 https://t.co/IdQxluN0Gm  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-29 11:33／2018/10/06 16:34 URL： https://twitter.com/kk_hirono/status/1288301690777563137 https://twitter.com/hirono_hideki/status/1048476560506806272  

> 医者になって初めて分かったアッサジが自殺ではなかった理由。 | 診察室 延長戦 https://t.co/Xf7CmriFvX  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-29 11:34／2019/03/19 11:45 URL： https://twitter.com/kk_hirono/status/1288301757110476800 https://twitter.com/hirono_hideki/status/1107835546200530945  

> 2019年03月19日09時10分の登録： ％@k999941457035　K - 9 9 9 9％ワシらは聖人やな。自らの身体を動物に食べさせてあげたアッサジレベルやわ。 https://t.co/NhVnInbPoZ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-29 11:34／2019/03/19 11:46 URL： https://twitter.com/kk_hirono/status/1288301784658714624 https://twitter.com/hirono_hideki/status/1107835625208602624  

> 2019年03月19日09時27分の登録： REGEXP：”アッサジ”／データベース登録済みツイート：2019年03月19日09時27分の記録：ユーザ・投稿：5／9件 https://t.co/5zmVEJ1oWG  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-29 11:34／2019/03/19 11:46 URL： https://twitter.com/kk_hirono/status/1288301811539955713 https://twitter.com/hirono_hideki/status/1107835651506864128  

> 2019年03月19日09時40分の登録： ＞@fukazawas　深澤諭史＞RT　@k999941457035：　手弁当で人助けしたりするワシらは聖人やな。自らの身体を動物に食べさせてあげたアッサジレベルやわ。 https://t.co/NeMNCrPWvD  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-29 11:34／2019/06/29 14:01 URL： https://twitter.com/kk_hirono/status/1288301840757473280 https://twitter.com/hirono_hideki/status/1144833202508275713  

> @i_tkst 2019年03月19日09時40分の登録： ＞@fukazawas　深澤諭史＞RT　@k999941457035：　手弁当で人助けしたりするワシらは聖人やな。自らの身体を動物に食べさせてあげたアッサジレベルやわ。 https://t.co/NeMNCrPWvD  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-29 11:34／2020/01/04 00:01 URL： https://twitter.com/kk_hirono/status/1288301879814832129 https://twitter.com/hirono_hideki/status/1213113035407032320  

> 35：2020-01-03_22:14:59 ＊ アッサジのK 9 9 9 9アカウントのタイムラインで知った伊藤祐貴弁護士の中止未遂の成立否定：札幌地判令和元年11月29日裁判所HPというブログ記事 https://t.co/4XniTIqWBF  

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「アッサジ」の検索結果 - Twilog https://t.co/qsEBWYSsJj

　9件になりますが，Twilogの検索結果のツイートを全てリツイートしました。2018年10月6日から始まっていて，元のツイートを確認すると2018/10/05 19:49という投稿時刻でした。

　さらにさきほど見かけたスクリーンショットの記録を確認したところ，2018-10-06-161824が深澤諭史弁護士のタイムラインでスクリーンショットを記録した時刻となっていました。それも最上部の最新のツイート（リツイート）として記録されています。

- TW s_hirono（非常上告-最高検察庁御中_ツイッター） 日時： 2018/10/06 20:14 URL： https://twitter.com/s_hirono/status/1048532052847427584  

> 2018-10-06-161824_深澤諭史のリツイート（K9999　@k999941457035）：貸与世代で借金あるのに某寺使ってあげたり国選やったり手弁当で人助けしたり.jpg https://t.co/GM3AWNrgO3  

　元のツイートのK9999というアカウントは，司法修習の貸与世代のようです。数年前に貸与制はなくなっていましたが，テレビでニュースを見ることはなく，法クラの弁護士ら以外は，ほとんど無関心な日常という感じでした。

　深澤諭史弁護士の司法修習の期は，前からすぐに忘れてしまうのですが，たぶん62期だったように思います。貸与制に移行する前だったと思います。これは調べて確認した憶えがあります。

司法修習生に対する修習資金の貸与制の概要 | 裁判所 https://t.co/X2PcQuBuvN 司法修習生に対する修習資金の貸与制の概要（70期以前）

　貸与制の最後が70期だという情報はすぐに見つかったのですが，始まりがまだ確認できません。63期かあるいは64期だったとは思います。今，もっとも新しい司法修習の期として見かけるのは73期になります。現在司法修習を受けているのが74期かもしれませんが，余り見かけません。

```
　司法修習生の給費制は、１９４７（昭和２２）年以来、６０年以上存続して、法曹養成制度を支え、かつ、弁護士の公益活動を支えてきたといってよい。ところが、２０１１（平成２３）年１１月、司法制度改革における司法修習生の増加、それに伴う財政的負担等を理由として、裁判所法改正により給費制は廃止され、新第６５期から第７０期までの司法修習生（いわゆる「谷間世代」）は最高裁判所から貸付けを受ける貸与制の下で修習を行うこととなった。

［source：］貸与制下で司法修習を受けた者の不公平・不平等の是正措置を求める会長声明 | 奈良弁護士会 http://www.naben.or.jp/news/seimei/5374/
```

　見つけづらかった情報ですが，上記の奈良弁護士会のホームページによると，「新第６５期から第７０期までの司法修習生（いわゆる「谷間世代」）は最高裁判所から貸付けを受ける貸与制の下で修習を行うこととなった。」とあります。

　終わったのも遅く感じたのですが，始まりも2,3年遅めでした。5年間続いたようです。一年ほど前までは法クラのツイートで，貸与制の返還，支払い免除のような話題をまだ見かけていたような気もするのですが，最近は法クラのツイートで全く見かけておらず，不思議にも思います。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜big_lawfirm（企業法務系弁護士その1） 日時：2020-07-29 12:08／2019/03/09 09:50 URL： https://twitter.com/kk_hirono/status/1288310374010241024 https://twitter.com/big_lawfirm/status/1104182625663516673  

> ちなみに私の奨学金による借金は844万2000円(ただしローの成績でこのうち105万円は免除)で、修習の貸与金300万円を加えると1040万円(有利子は360万円)くらいから弁護士人生が始まっています。借金なんか気にしてたら弁護士… https://t.co/j6oDrqzLr8  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜Mr_Bluegoat（tochi0428） 日時：2020-07-29 12:09／2018/04/09 17:01 URL： https://twitter.com/kk_hirono/status/1288310624737361920 https://twitter.com/Mr_Bluegoat/status/983253678566985729  

> 先週、同期が亡くなった。無論悲しいのだが、気になってたのは修習貸与金。調べたら免除されるとのことで良かった。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜niessun23（にーみん） 日時：2020-07-29 12:09／2016/12/19 12:28 URL： https://twitter.com/kk_hirono/status/1288310707541270528 https://twitter.com/niessun23/status/810688275006504960  

> ＞これ貸与のみで頑張ってきた勢には、一部免除とか何もないんかな？？  司法修習生に「給費制」復活へ…貸与と併用で（読売新聞） - Yahoo!ニュース https://t.co/E08UCnHCPX #Yahooニュース  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜nowfield1986（コンさん） 日時：2020-07-29 12:10／2020/02/01 17:40 URL： https://twitter.com/kk_hirono/status/1288310799711100928 https://twitter.com/nowfield1986/status/1223526614262140929  

> 司法修習貸与金の約300万円、毎年30万ずつ返還せよとの通知が来た。屈辱を毎年味わうよりは、経済合理性を無視して一括返済したい気もするが、あとから免除になる可能性が完全には否定できない(そのぐらいのクソ制度)ために、毎年嫌な気分に… https://t.co/qQwu6pH4wK  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜simuken2016（健🍣P　弁護士兼マンガ家😷） 日時：2020-07-29 12:10／2020/06/28 11:55 URL： https://twitter.com/kk_hirono/status/1288310851762413568 https://twitter.com/simuken2016/status/1277073192561991683  

> 弁護士は社会正義を実現しているから、 修習貸与金も奨学金も全部免除した方がいいよ🕵️‍♂️  　免除しないと利益活動に勤しみ、またミネる弁護士が出てくるよ。  　今回を機に法改正で貸与金も奨学金も全部免除した方がいいよ🕵️‍♂️  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜matimura（田丁木寸） 日時：2020-07-29 12:10／2020/06/16 17:40 URL： https://twitter.com/kk_hirono/status/1288310904673546240 https://twitter.com/matimura/status/1272811254596263937  

> 緊急声明～修習資金の貸与を受けた元司法修習生に対する貸与金返還の一律猶予を求める～ https://t.co/8hnHmOa9ob せめて猶予は必要不可欠。この機会に免除ができれば良いのに。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜yamanaka_osaka（弁護士　山中理司） 日時：2020-07-29 12:10／2020/06/30 15:36 URL： https://twitter.com/kk_hirono/status/1288310970935209985 https://twitter.com/yamanaka_osaka/status/1277853492456026112  

> 修習資金貸与金の返還を一律に免除するために必要な法的措置，及びこれに関する国会答弁 https://t.co/QPlGnFih0p  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜LawyerNT（弁護士 谷口直大） 日時：2020-07-29 12:11／2017/07/22 04:54 URL： https://twitter.com/kk_hirono/status/1288311040699056129 https://twitter.com/LawyerNT/status/888487431787261956  

> 司法修習生の貸与世代の救済は、心情的には十分共感するけれども、弁護士会が会費免除などといった手段ですべきものではない。 国政上の失政は、国政において手当てされなければならない。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜kd_ixi（エンリケ航海玉子） 日時：2020-07-29 12:11／2018/03/02 20:05 URL： https://twitter.com/kk_hirono/status/1288311112560078848 https://twitter.com/kd_ixi/status/969529040557113344  

> 修習を終えて6年目で年収（所得）1075万円に至っていなければ、まだ高度プロフェッショナルにはなれていないということで、貸与金返還免除でいいんじゃないか。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜Route66_LP3（ルート６６（元ルパン３世）） 日時：2020-07-29 12:11／2018/02/14 21:32 URL： https://twitter.com/kk_hirono/status/1288311225172889600 https://twitter.com/Route66_LP3/status/963752878199287808  

> ちなみに修習の貸与も本人死亡は返還免除事由だったはず…  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜battamon_black（Ｋ　Ｂ　ブ　ラ　ッ　ク） 日時：2020-07-29 12:12／2017/08/10 22:04 URL： https://twitter.com/kk_hirono/status/1288311382920687617 https://twitter.com/battamon_black/status/895631821664210946  

> 今、司法修習委員会委員長のインタビューを読んでいるけど、貸与制世代の間で借りた人と借りていない人との不公平が出るので償還免除は難しいという意見があるらしい  もうこれ以上やる気はないんだろうな…  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜rayuca1018（おけいはん☆） 日時：2020-07-29 12:12／2019/10/22 19:45 URL： https://twitter.com/kk_hirono/status/1288311479721050113 https://twitter.com/rayuca1018/status/1186594324852559874  

> 恩赦とかするぐらいなら、奨学金とか修習時代に貸与制だった弁護士の借金を免除してあげたらいいのに。  

修習　貸与　免除 - Twitter検索 / Twitter https://t.co/4uIOr7etxk

　ブロックされているアカウントのツイートは表示されないのですが，やはりたまたま見かけなかっただけではなく，「修習　貸与　免除」というキーワードを含むツイートの数自体が少なかったようです。なお，このTwitterの検索はあいまい検索です。

　2年だった司法修習が1年になって20年ぐらい経つように思います。その1年分の貸与金が300万円だったようです。このわかりやすい金額は，法クラの間では当たり前過ぎて省略されていたのかもしれないですが，全くではなかったと思うものの，見る機会は少なかったと思います。

　しかし，よく考えてみると，これは国の貸付の限度額が300万円ということで，借りない人もいたようなことを思い出しました。そもそもは給付制で，国から司法修習に給与に相当する手当が支払われていたものが不支給となり，貸与性が始まったものと考えます。

　なにぶん，新聞には記事の解説があったのかもしれないですが，テレビでは一度も司法修習の問題を見たことがなかったので，断片的にときたま見かける情報ばかりで，まとまりがありませんでした。

　時刻は12時42分です。昼食の途中でもあるのですが，深澤諭史弁護士のタイムラインをみていました。気になるツイートがいくつかありましたが，日常茶飯のことではあります。人を刺激するツイートが目立つ傾向にもあるのですが，弁護士経営にプラスになっているのか疑問はあります。

　午前中もつらつらと考えていたのですが，弁護士は周囲に刺激を与えることで浮力を保ち，世の中を漂い彷徨っているのかと思えてきました。１つ最近見かけなくなって気になっていた問題があったのですが，それを先程深澤諭史弁護士のタイムラインで見かけました。

@kumaemon9 ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@kumaemon9）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW kumaemon9（くまえもん） 日時：2020/07/28 22:43 URL： https://twitter.com/kumaemon9/status/1288107933377499138  

> 余命三年ブログを数か月ぶりに覗いてみたら、最高裁への上告がことごとく棄却され「最高裁よお前もか」という見出しのシリーズが出来上がっていてさすがに吹いた。期待していた安倍総理の指揮権発動はなかったんだねぇ…。  

- RT fukazawas（深澤諭史）｜kumaemon9（くまえもん） 日時：2020/07/29 11:00／2020/07/28 22:43 URL： https://twitter.com/fukazawas/status/1288293308440043520 https://twitter.com/kumaemon9/status/1288107933377499138

> RT @kumaemon9: 余命三年ブログを数か月ぶりに覗いてみたら、最高裁への上告がことごとく棄却され「最高裁よお前もか」という見出しのシリーズが出来上がっていてさすがに吹いた。期待していた安倍総理の指揮権発動はなかったんだねぇ…。  

　余命三年ブログが弁護士に対する大量懲戒請求の問題に発展したと聞くのですが，謎の部分が大きく感じる問題でもありました。現実問題として相当の数，弁護士らが賠償請求の裁判を起こし，裁判所にも大きな負担を掛けたものと想像されます。

　嶋﨑量弁護士，佐々木亮弁護士,北周士弁護士に代表される弁護士大量懲戒請求の問題ですが，とても不思議な世界観を感じています。嶋﨑量弁護士と佐々木亮弁護士は成仏などと発言，ツイートするタイプではないと思いますが，いずれも漫画の世界の住人に思えてしまいます。

　自分らを一方的な被害者として民事裁判も起こしたのでしょう。総額で億を超える賠償額という話も出ています。思考を現実化するのが弁護士の本分とすれば，それも漫画家がストーリーを組み立て漫画を描くのと似ているのかもしれません。

大量懲戒請求 - Twitter検索 / Twitter https://t.co/kOFsj3b3Sk

　予想以上に情報は乏しく感じました。「余命読者による（不当）大量懲戒請求事件は今どうなっているのだろう？　三宅雪子さんが生きていれば聞けたんだが．．．」という内容のツイートがあって，なるほどと思いました。

アッサジ　手塚治虫 - Google 検索 https://t.co/SW3IVLbuVD

```
ブッダ修行の旅の途中に出会ったのが「アッサジ」というお荷物です。ご覧のとおり愚鈍さが強調されたキャラクターで、手塚治虫の創作した人物で、経典には出てきません。
彼は、神からのお告げで、10年後に死ぬことを知っています。それは、彼の父親が多くのケモノを殺したことの報いであるという理由です。
結局、アッサジはその予言通り、10年後に腹を空かせた狼とその子どもに食べられて死にます。

［source：］「これでいいのだ」｜金谷どうはん｜note https://note.com/kanaya_douhan/n/nfb5ea4798a91
```

　Twilogでの過去の記録とは別に，Googleで最初から調べ直したのですが，上記に引用した「彼は、神からのお告げで、10年後に死ぬことを知っています。それは、彼の父親が多くのケモノを殺したことの報いであるという理由です」というのは初めて見たように思います。

　続いて「結局、アッサジはその予言通り、10年後に腹を空かせた狼とその子どもに食べられて死にます。」とあるのですが，これは自分で知っていた宿命を受け容れたようにも読めます。漫画の絵が画像として掲載されているのですが，アッサジの額にはバッテンの絆創膏があります。

　手塚治虫のブッダという漫画も，書店で見かけるなどして存在はしっていたのですが，その本に出てくるのがアッサジだと確認しました。「手塚治虫氏は、聖人としてのブッダではなく、人間としての「ゴータマ・シッダルタ」を描きたかったのだと思います。」とも紹介されています。

　この「手塚治虫氏は、聖人としてのブッダではなく、人間としての「ゴータマ・シッダルタ」を描きたかったのだと思います。」という部分は，Googleの検索結果の要約で見かけ，それで開いたページになります。

　確認しましたが検索結果にあるタイトルも「「これでいいのだ」｜金谷どうはん｜note」で，開いたページのページタイトルと同じです。

　「これでいいのだ」が記事のタイトルで，目次があって，見出しが４つあります。「手塚治虫の描く「ブッダ」」，「ブッダ」を軽々と超越する「アッサジ」」，「バカボンのパパは、ブッダである」，「「この世は美しい。人の命は甘美なものだ」」と続きます。

　漫画のコマにブッダが横になる場面がありますが，小学生の高学年の頃，機織り工場の慰安旅行に同行したとき，小松市のハニベ岩窟院で，地獄の世界を描いた地下のような通路から地上に出たとき，広場に仏様が横になる大きな像を見たことが印象的でした。

ハニベ岩窟院 - Google 検索 https://t.co/oBu4t5gcyl

　肩から上の大きな顔の銅像があるのですが，その胸の辺りがハニベ岩窟院の入り口となっているようです。前にも調べているのですが，このとても目立つ写真は初めて見たように思いました。

　数は少なく2枚ほどでしたが，横になったブッダと思われる銅像はあるものの石のような石像で，台の部分が石像と同じぐらい大きくなっています。昭和50年頃，自分の目でみたと記憶にある横になった像は，金色色に近いイメージが残っていて，台はなかったと思います。

drecom_r_okaのブログ : ハニベ岩窟院当主逮捕 https://t.co/SV7Be6g9aY 写真はトレードマークの仏頭。金がなくて頭しか作れなかったとか。 \n 変態地獄めぐりの詳細についてはたとえばココを見て。

　2004年11月5日12時07分とあるブログ記事です。先程から気になっていた大仏の頭の写真が記事の頭に掲載されています。この事件は，たまたまテレビか新聞で知ったという記憶があります。記事の内容は以前にも読んでいたような気がします。

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「ハニベ岩窟院当主逮捕」の検索結果 - Twilog https://t.co/rfJ1Ylghqy ツイートが見つかりませんでした

　あるかと思ったのですが，「ハニベ岩窟院当主逮捕」という記事タイトルでのツイートは見つかりませんでした。

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「ハニベ」の検索結果 - Twilog https://t.co/XGMA4x0PrG ツイートが見つかりませんでした

　岩窟院の漢字が違っているのかと思ったのですが，奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)では「ハニベ」でも該当するツイートがありませんでした。今までも多少はTwilogの検索に疑問を感じたことはあったのですが，今回が一番大きいです。

刑事告発・非常上告＿金沢地方検察庁御中(@kk_hirono)/「ハニベ岩窟院」の検索結果 - Twilog https://t.co/WEfoj7TsNW

　再捜査要請書＿警察庁・石川県警察御中（@kk_hirono）のTwilogで調べてみると，今度は意外に数が多く数えると11件のツイートがありました。記事のリンクがあって開いてみると，異様なインパクトのある大仏の頭の写真が出てきました。

　今日，初めて目にしたように思っていた大きな大仏の頭の写真ですが，過去に見ていたことは間違いなさそうと確認をしました。ハニベ岩窟院の場所も気になっていて，前にGoogleマップで調べているはずと思っていたのですが，ツイートに辰口町の近くとありました。

　今回もハニベ岩窟院の場所は，能美市辰口町とは反対側の，加賀市との境付近をイメージしていたように思います。

いしかわ動物園 から ハニベ巌窟院 - Google マップ https://t.co/h7tsR0pElH

　地図でみるとかなり近くに見えたのですが，経路検索をするといしかわ動物園からハニベ岩窟院は6キロという距離でした。平成10年，関係者KYNの配管工事の仕事でたびたび通って作業をしていたいしかわ動物園になります。完成後に行ったことはないですが，テレビで見ています。

　まだ内装の仕事が始まる前に行かなくなりました。建物の基礎はほぼ出来上がっていたと思います。同じ頃に別の現場として通っていた，辰口庁舎も同じぐらいの進捗状況でした。

　広い道路の方に大きな部屋があって，その部屋で作業をしていたときですが，大雨が長い時間降り続いていました。夕方暗くなってから金沢市内に戻ると，東力の辺りで田んぼが冠水し，川沿いには浸水で通行できなくなった道路もありました。

　浅野川が氾濫し大きな被害が出た大雨ではなかったと思います。ただこの日の大雨が原因で，翌年平成11年の3月から7月頃にかけ，いくつか災害復旧工事の現場で仕事をすることになったようです。よく通ったのが金沢市山科と山中温泉になります。

　山中温泉では，もう少しで河川が氾濫し山中温泉の町が水没するところだったと聞かされました。しかし，その作業をした川というのは，Googleマップで存在が確認できていない川になります。

　山中温泉殺人事件の殺害現場となった川というのも，私が仕事で通った川の近くになるはずなのですが，・・・と書いたところで，平成11年当時には道幅が広く拡張されていた可能性が頭に浮かんできました。

　山中温泉殺人事件の裁判記録などでは，現場の川のある道に入るには鋭角で何度も切り返しが必要になる旨の記載があったからです。しかし，それとは別に違うと思ったのは，私が仕事に行っていた川は，谷川も橋もありませんでした。

　ただ，よく思い出せないのが道路の突き当たりになる現場で，重機で掘り起こすような作業をしながらその手伝いをしていたことです。川沿いの道路でも別の作業をしていました。

　もしかすると，道路の突き当りの手前で，川は道路の下を通って山の左上方向に上流があったかもしれません。民家があった山中温泉のはずれから，2,3キロもあったのかと思うのが，道路の突き当りになります。だいぶん下の方に，熊出没注意という看板が出ていました。

　突き当りの100メートル以内かと思うのですが，かすかな記憶ではあるものの，道路から川を渡って向こう岸に行けるところがありました。その辺りは川幅も狭く，あるいは3メートル程度だったかもしれません。

　長靴を履いたまま川を渡ったという記憶もないのですが，簡単に渡れたと思います。道路では土埃も出そうなので，川の向こう側に渡り，弁当を食べたような記憶があるのです。

山中温泉東町 - Google マップ https://t.co/OODWq71FIC

　上記の山中温泉東町が山中温泉殺人事件の殺害現場となっていたのですが，昭和47年5月11日が殺害となっている事件なので，判決書などに記載された番地が，現在は無効となっているらしく，それ以上の特定は出来ませんでした。

　Googleマップでみても，山中温泉東町に大聖寺川以外の河川は見当たりません。Googleマップで見ると右手，車で金沢から山中温泉に入ると，温泉街の左手になるのですが，大聖寺川を渡った先が，山になっていました。私が仕事に通ったのも，この山の川になります。

　山裾には山中温泉のホテルや旅館がありました。昭和62年の6月に金沢市場輸送の一拍の慰安会で行ったのも，その辺りのホテルでした。ちょうど山中温泉東町の辺りと思っていたのですが，先日，当時のホテル名が検索で見つかり，もう少し大聖寺川の上流，山中温泉の奥の方でした。

〈〈〈：Linux Emacs： 2020-07-29（水曜日）15：21 　〈〈〈

* 昭和62年の6月に金沢市場輸送の一拍の慰安会で行った山中温泉のキャッスルバーデンホテル
  :LOGBOOK:
  CLOCK: [2020-07-29 水 15:32]
  :END:

:CATEGORIES: 金沢市場輸送,山中温泉殺人事件,被告発人梅野博之

〉〉〉：Emacs： 2020-07-29（水曜日）15：32　 〉〉〉

　金沢市場輸送では，希望者だけが加賀温泉に一拍の慰安会に行くと聞いていました。それも麻雀が目的という話も聞いていたのですが，山中温泉のときは，麻雀をする様子は見ておらず，とても広い大部屋が１つで雑魚寝をしたような場面しか記憶にありません。

　他に借りた部屋があって，そこで麻雀が行われていたことは十分可能性がありますが，当時はまだ麻雀好きの社員はいなかったかもしれず，希望者だけが加賀温泉に一拍の慰安会に行くという話も，二口町の新事務所に移転してから聞いた話でした。

　その移転が昭和63年の7月の初めとして記憶にあるのですが，そのちょうど1年ほど前に山中温泉に行ったことになります。金沢中央卸売市場の北國銀行中央市場支店の前からマイクロバスに乗り込んで山中温泉に向かったこと，妻が忘れ物を届けた場面が記憶にあります。

　元石川県警察の警察官で白バイ隊員であったというKKさんのことも強く印象に残っています。マイクロバスの中で酒を飲んでいるのを見たという記憶はないのですが，相当ご機嫌に酔っ払った様子で，片山津インターを降りて少しすると，窓から小便をしようと行動に出ました。

　それこそ被疑者確保のように制止された場面がかすかに記憶に残るのですが，他に印象的だったのはホテルに着いてから早い時間に大部屋の布団で爆睡をしていたことです。夕食のことは記憶にないのですが，KKさんが酒を飲み続けたという場面も記憶にはありません。

　あれが自然なKKさんの行動だったのか，今考えてみると疑問に思うところもあるのですが，当時は疑うことなどありませんでした。そのKKさんと一緒に行動するようになったのは，平成元年の12月以降になります。

　私は続けて2度目となった金沢港でのイワシの運搬の仕事で，KKさんは元請けとなった市場急配センターの社員として，現場監督や水揚げ運搬の記録係のような仕事をしていたようです。いつもラビット号とも呼ばれた，うさぎの小さい絵のあるポンコツのワゴン車に乗っていました。

　何度も書いてきたことで，年々記憶は薄れて正確なことは書けなくなりつつあるとも思うのですが，基本，イワシの運搬の仕事は12月から翌年2月一杯で，金沢市場輸送では2台のダンプのみが水揚げの少なくなった仕事を続けていました。

　始まりもダンプの方が早く，私たち平ボディ車がイワシの運搬に参加したのは，12月でも中頃か20日すぎだったと思います。これまでに何度も書いてきたことですが，原料のイワシが切れてミール工場の機械を停止させると，次の起動に数十万円の費用が掛かるという話でした。

　30万円か50万円，あるいは100万以上だったのかもしれないですが，この金額を思い出せなくなっています。この金額のことはたびたび聞かされ，イワシの水揚げが出来る間は，ぶっ通しで続けるというのが大前提の仕事となっていました。

　そのイワシも金沢港の堤防の先でとれることもあれば，新潟県の佐渡沖や京都府の舞鶴沖までイワシを求めて探し回ることがあると聞いていました。蛸島丸の船団には探査船がいて，その探査船がイワシを探しているという話でした。

　船団が遠くの海に行くと，次の帰港までどれぐらいの時間がかかるかわかるので，時間にゆとりがありました。その間に家に帰ったり，遊びに出掛けたりしていましたが，そんなときいつも一緒に行動し，いつもおごってもらっていたのが同じ平ボディ車の運転手，竹林になります。

　これは平成元年12月からの2度目のイワシのシーズンになりますが，昭和63年12月からの1度目のイワシのシーズンは，同じように大西さんに毎日のようにおごってもらっていました。なぜそんなにおごってくれるのか，不思議に思うことはありました。

　KKさんと一緒に食事に行くことも少なくなかったと思うのですが，おごってもらったような記憶は残っていません。KKさんは当時，27歳かあるいは28歳と話していました。

　今計算すると，平成2年の2月頃だと私は25歳になるので，28歳と聞いたと思うKKさんとは３つしか違わないのですが，5歳は年上という感覚で付き合っていました。

　潜水服のことも思い出したのですが，ときどき思い出して忘れることがないのは，彼の自宅で彼の妻に追い返されたことです。玄関先で奥から妻の声を聞いていたのですが，遠くで全身の姿を見かけたような憶えはかすかにあるものの，顔というのは見ておらず，想像もつきません。

　ここで久しぶりに思い出したのが，被告発人安田敏の妻のことです。正確にはまだ入籍前の時期だったと思うのですが，平成3年の5月頃から彼女の奇妙な行動が目立ちました。一緒の部屋にいてもベッドの上で寝たままタオルケットのようなものをかぶり，徹底して顔を見せなかったのです。

　重要な事実関係の１つであるので，この続きは独立した項目として記録にしておきたいと思います。ここでは山中温泉キャッスルバーデンホテルのことを記述しているのでした。

　これも過去の裁判記録等には詳しい記述があると思いますが，「ちょんこう」などとという名古屋の宿泊客とトラブルになったことが記述されていると思います。

　最初に手を出したのが大西さんの息子だったと思うのですが，あとで七尾市のSが暴行を受けたような様子で泣いていました。しかし，殴られたような様子はなかったとも思います。それにずいぶんと大げさな泣き方で，人格そのものにも疑問を持ちました。

　当時，過酷で厳しい仕事で知られていた佐川急便で市内配達の仕事をしていたという七尾市のSで，今でも顔や声はなんとなく印象に残っています。当時の金沢市場輸送の社長だった竹沢俊寿と夫人に，自分の結婚式に出席してもらったという話が印象的でした。

　七尾市は花嫁のれん，という風習があるらしくテレビのドラマにもなっていましたが，同じ石川県でも結婚式に対する考えが他とは違っていたのかもしれません。少なくとも他に竹沢俊寿夫妻に結婚式に出席してもらったという話を聞くことはありませんでした。

　本当は会社の上司や，小さな会社であれば社長に結婚式に出てもらうのは，むしろ常識なのかもしれません。被告発人大網健二の結婚式にも本陣不動産株式会社の社長や上司が出席していました。被告発人大網健二は，結婚式の費用も会社に借金をしたと話していました。

　被告発人大網健二の結婚式は平成2年の春だったと思います。以前は春か秋かわからなかったと思うのですが，今は春のように思えます。しかし，これを春とすると，被告発人安田敏と再会して片町に飲みに行ったのが，同じ平成2年の秋になりそうなのです。

　小立野の金沢大学病院前の飲み屋の前で酔いつぶれた被告発人安田敏と別れ，その次に電話で連絡があったのが平成3年の4月になります。前に会ったときと1年ほど間があるような感覚でいたのですが，今考えると半年前の秋でも，それほど違ってはいない気もします。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-29 16:58／2010/05/14 05:10 URL： https://twitter.com/kk_hirono/status/1288383465402974214 https://twitter.com/hirono_hideki/status/13932209222  

> いやこれは昭和62年かもしれません。ずいぶん前のことなので思い出すのも大変ですが、はっきりしていることは昭和62年の4月に、私はN運送から戻りすぐに新車の10トン保冷車に乗務しました。もう一つ記憶に残っているのは、6月に会社で山中温泉のキャッスルバーデンホテルに行ったことです。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-29 16:58／2010/08/08 23:18 URL： https://twitter.com/kk_hirono/status/1288383487095930883 https://twitter.com/hirono_hideki/status/20631273758  

> はっきり覚えていることは、昭和62年の6月頃に、金沢市場輸送の慰安会が山中温泉のキャッスルバーデンホテルであったこと。被告発人・被告訴人UHKの姿はあったと思うけど、○下はまだいなかったような気がする。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-07-29 16:59／2020/07/20 11:38 URL： https://twitter.com/kk_hirono/status/1288383518918074368 https://twitter.com/hirono_hideki/status/1285041357480845312  

> 金沢市中央卸売市場 から 北陸キャッスルバーデンホテル - Google マップ https://t.co/5eFrM792Yv  

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「キャッスルバーデン」の検索結果 - Twilog https://t.co/wuT1o8qpRb

金沢市中央卸売市場 から 北陸キャッスルバーデンホテル - Google マップ https://t.co/i4OjdfxTXW

　今になって気がついたのですが，キャッスルバーデンホテルは，北陸がついて北陸キャッスルバーデンホテルとなっていました。行ったときから変わった名前のホテルと思っていたのですが，その後，テレビCMで，画面に「山乃湯」と見たような憶えがあるのです。　

　7月20日のツイートと確認しましたが，このGoogleマップで北陸キャッスルバーデンホテルを見つけたときも，Googleでの検索は，「山中温泉　山乃湯」であったように思います。

　とにかく石川県で昭和の時代というのは，加賀温泉のホテルや旅館のCMが多くありました。山中温泉，山代温泉，片山津温泉で，山乃湯というのもどこかで見かけていたような記憶があったのです。バブル景気の終焉で，温泉は大打撃を受け，CMも少なくなったと聞きます。

　細かいことですが，山中温泉のキャッスルバーデンホテルでは，大浴場の脱衣場に，何をしているのかよくわからない2,3人の若い女性がいました。なぜ，そこにいるのか不思議だったのでよく憶えています。

　これは金沢市場輸送の会社が全額負担をした一拍の慰安会だったと思います。その次にあったのが平成2年の同じく6月で，片山津温泉の「ホテル長山」でした。あるいは「ホテルながやま」だったかもしれないですが，以前はよくテレビCMを見かけていました。

　いずれも6月でも終わりの方だったと思います。その少し前までは，筍と金沢港のスルメイカの仕事で忙しく，運転手がまとまって休むことは無理があったからです。そのように話を聞いていましたし，実際，仕事の多い時期でした。

　名前が１つ思い出せなかったのですが，「grep -r コンパニオン ./*」という検索では結果が出ませんでした。その前に少し思い出しかけていたので，その名前で検索すると間違っていないと確認できました。

こおろぎ橋 から 北陸キャッスルバーデンホテル - Google マップ https://t.co/cpgCiII9pB

　徒歩11分，750ｍとあります。このこおろぎ橋は，山中温泉の名所として聞くことがあったのですが，実際に現地で見たことがあるとも思います。キャッスルバーデンホテルでは，徒歩で外を散策するようなことはなかったはずです。

あやとりはし - Google マップ https://t.co/mIv863KIM7 大聖寺川に架かる全長約95mの徒歩専用の橋。糸遊びのあやとりのようなS字型のモダンなデザインで、桜公園や鶴仙渓への散策路がある。

　最近は，この「あやとりはし」というのをテレビで見かけていて，鶴仙渓とあるのも上記のページで思い出しました。山中温泉で観光をしたという記憶はないのですが，仕事だったのか行ったような気もします。

　Googleマップで，山中温泉の周辺をみていると，四十九院川というのがあることに気が付きました。この四十九院という地名は，山中温泉殺人事件でたびたび出てくるのですが，「蒔絵職人・霜上則男の冤罪―山中温泉殺人事件」を読んで知ったのが最初かもしれません。

九谷ダム - Google マップ https://t.co/1lUiOQfVep

　大聖寺川の上流に湖があって九谷ダムがあることに気が付きました。広い川のようにみえる少し離れたところに富士写湖と見えます。この辺りは前も調べたことがあったのですが，九谷ダムというのは気が付きませんでした。

　山中温泉の奥の山になるのですが，大きな湖があって，その先にダムと聞いて向かった現場がありました。一日だけの仕事で行ったような気もするのですが，それも平成11年の6月か7月頃のことです。

　この前は，九谷焼について調べたのですが，範囲が広くて山中温泉との関係は確認出来ませんでした。別に山中漆器という言葉を聞くこともあったので，九谷焼とは別になるのかと考えたのですが，山中温泉の奥地に九谷ダムが出てきたのは，意外な発見です。

　ただ，その山中温泉の奥地にあるダムと聞いた場所に仕事に行った時の状況，仕事の内容もわずかにしか思い出せず，魔法にでもかけられて記憶を失ったような気分になることもあります。

　ダムをみたという記憶はないのですが，ダムの現場だと聞いて向かったことと，大きな現場に着いたという記憶はなんとなく記憶に残っています。

　Googleマップの航空写真を拡大してみると，ダムの下が谷間のような形状になっていると確認しました。私の記憶にある場面は，大きな川のような湖の対岸に，現場があったのですが，橋を渡って対岸に行ったような記憶はありません。

　ストリートビューに切り替えて見ていると，県民の森１２ｋｍ，九谷ダム２ｋｍという道路標識がありました。右手に大きな川のような湖を見た道路は，けっこう広かったと記憶にあるのですが，道幅が狭く感じます。センターラインも見当たらない感じです。

石川県県民の森 - Google マップ https://t.co/MzPOjCDMHl

　石川県県民の森というのは，どこかで一度は聞いたような気もするのですが，山中温泉の奥地とは全く知らなかったと思います。県道１５３号線とありますが，福井県の方に出る道路なのかと思っていたところ，再び山中温泉の方に戻る道路となっているようです。

　石川県民として生まれ育っているので，なぜ山中温泉の奥地に石川県県民の森があるのか，気になるところがあります。

　山中温泉からは国道364号線で福井県丸岡町に出る道路があるのですが，これは初めて知った国道です。国道365号線というのは，よく憶えているのですが，下道で金沢から名古屋方面に向かうときは必ず通行した主要な国道でした。

　どうも国道8号線で，大聖寺検問所とある交差点が，国道364号線の始まりとなっているようです。大聖寺検問所というのは，津幡の検問所と違って記憶になく，国道8号線は熊坂に台貫場があったかもしれないと思えてきました。

加賀タンパク - Google マップ https://t.co/PQOmhcZEXI 〒921-8001 石川県金沢市高畠３丁目２３１

　昭和59年，金沢市場輸送の4トン保冷車の仕事でよく行ったのが，上記の加賀タンパクになるのですが，ふと思い出して調べてみたのです，期待したのは，この金沢市高畠3丁目の会社ではなく，山城とも聞いていた，加賀市大聖寺の近くの油揚げ工場でした。

　さきほど見つけた国道364号線に間違いないと思いますが，国道8号線を左折して山中温泉に向かい，3分から5分程走った右手に，その工場がありました。いつも夜の遅めの時間にしか行くことがなく，無人のまま油揚げの荷物を積み込んでいたように思います。

　同じ油揚げの仕事は，京都府の向日市だったと思うのですが，そこにも卸先の工場があって，他のトラックへの積替えだったのか，夜中に無人のまま油揚げの荷物を降ろしていたことが記憶にあります。油まみれのプラスチックケースでした。

　この金沢市場輸送の油揚げの仕事については，新潟県の青海町，富山県の滑川市についても書いていると思います。最終的な卸先は，大阪府の生田区だったかもしれません。明るくなった頃に着いたという記憶も少ないのですが，夜明け頃だったような気もします。

　大阪や神戸では帰り荷も小口で冷蔵庫まわりなど面倒な仕事が多かったのですが，昭和59年，給料は4トン保冷車の長距離で，総額20万円，手取で16万円ほどでした。運行費は別に出ていましたが，鮮魚も多く，荷物の破損や延着は自腹で弁償と言われ，責任の思い仕事でもありました。

　市場急配センターの市内配達も何年か後のことになりますが，給料は総額で20万円となっていたように思います。仕事の内容がまるで違っていましたが，大きな経験値を積むことは出来たと思っています。それが昭和61年8月に二度目の入社をした後の，信頼や高評価にもつながりました。

　金沢でも鮮魚を積んで下道を走るのは金沢市場輸送だけと言われていました。鮮魚を積んで初めて東京築地市場に行ったときも，碓氷バイパスから国道18号線を走行していた記憶があります。昼だと大きな駐車場の釜飯の看板の店が見える辺りでした。夜だと交通量も多く風景も変わります。

　初めて鮮魚を積んで東京築地市場に行ったのは，1月中で冬だったと思うのですが，スルメイカのシーズンになると初夏ですが，安房峠から松本市，塩尻市と国道を走り，諏訪南インターから中央道の高速に乗って，首都高速に入っていました。

　当時でも全線高速の指示が出ることはあったのですが，名古屋周りの東名高速で東京に向かっていました。中西運輸商にいるとき，昭和60年と思いますが，関越トンネルが開通し，そのあとは関越道から東京に向かうようになりました。

　中西運輸商でも，一度，湯沢インターが終点で，国道17号線の三国峠を走ったことがありました。雪が多い時期で，湯沢インター付近の灯りが印象に残っています。中西運輸商では高速道路の利用に制限がなかったので，わからないまま通行した三国峠でした。

関越トンネル - Wikipedia https://t.co/8BNbMlJIim 1985年10月2日、現在の下り線トンネルが開通した。当初は片側1車線（暫定2車線）の対面通行であった。これにより、関越道の練馬IC - 長岡J… https://t.co/GTdXASllkb

　1985年10月2日の開通というのは，ほぼ記憶通りと確認できたのですが，「1991年10月22日に上り線トンネルが開通し、全区間が4車線となった。」というのは記憶にないので，また不思議な気分になりました。

　中西運輸商では，広島，九州，金沢市場輸送では東北と九州で，東京は筍とスルメイカの時期を別にすれば，月に2回ほどの運行だったのですが，市場急配センターでの長距離の仕事が本格化したのもその平成3年10月で，それもそれまでになく関東に仕事が集中していました。

　関越トンネルが，平成3年10月22日に全区間4車線になったと聞いてもピンとこないのが正直なところです。全長約10キロ，日本一長いトンネルとは聞いていた関越トンネルになります。4車線になれば，事故や通行止めのリスクも減るわけで，もっと印象に残っていても良さそうです。

　運がよかったのか，関越トンネルの通行止めに遭うことは1度だけしかなかったのですが，想像を遥かに超えて大変な思いをしました。平成4年の2月の終わり頃と思うのですが，日付がなかなか確認できずにいます。栃木県葛生町で石灰を積んで，石川県七尾市に向かっていました。

　関越トンネルの通行止めに遭遇して国道17号線に出てからは，ほとんど仮眠をした記憶もないのですが，七尾市に着いたのが夕方に近いような時間で，16時を過ぎていたかもしれません。渋滞が解消されたのも午後になっていたように思います。

　他の運転手には，高速道路で何日か通行止めが続き，売店の食べ物も全て売り切れていた，という悲惨な話を聞くこともありました。大雪で交通網が完全に麻痺したという話だったかもしれません。テレビなどでニュースを見ていたような記憶もあります。

　まだ，山中温泉のキャッスルバーデンホテルを項目名に記述をしていたことを確認しました。余り項目を細かくするのもどうかと思うところがあって，情報をまとめておいた方がよさそうに思えることもあるのですが，いまだ試行錯誤を脱しきれていない感はあります。

　時刻は19時49分です。外には一度も出ていないのですが，雨は降っていない様子でした。今日は水曜日なのでポイント3倍の薬のアオキへ，宇出津新港に買い物に行くつもりでいたのですが，やめにしました。

　雨は降っていないと思うのですが，陽射しはなかったので日照不足が気になります。しばらく前，どんたく宇出津店で98円ほどで売っていたのと同じようなジャガイモが，一昨日ほど前，Aコープ能都店で398円になっていたので，久しぶりにカレーライスを作るつもりだったのをやめにしました。

　14時過ぎにテレビを消してからまだつけていないのですが，Twitterのトレンドをみると，岩手県で初の感染者とニュースがありました。NHKニュースのツイートをみると，岩手県で2人の感染確認とあります。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ciaolivia（伊吹早織 Saori Ibuki） 日時：2020-07-29 20:01／2020/07/29 19:08 URL： https://twitter.com/kk_hirono/status/1288429417060945921 https://twitter.com/ciaolivia/status/1288416135960883200  

> 岩手県で初のコロナ感染者確認の速報が来たので、5/15の知事の言葉を改めて。  「第1号になっても県はその人を責めません。感染者は出ていいので、コロナかもと思ったら相談して。陽性は悪ではない」  「感染未確認でいつづけることは目標… https://t.co/l2Et0qr1OL  

　時刻は20時04分です。今日は珍しく深澤諭史弁護士のタイムラインで，更新の頻度が少なくなっています。しかし，上から２つ，疑問に思うツイートが深澤諭史弁護士のリツイートとして並んでいます。

@uwaaaa ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@uwaaaa）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW uwaaaa（サイ太） 日時：2020/07/29 13:13 URL： https://twitter.com/uwaaaa/status/1288326727043657730  

> 野党が不甲斐ないから内閣支持率が発足以来最低になったじゃないか（怒） https://t.co/OBVHeYoNeV  

@luckymangan ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@luckymangan）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW luckymangan（リーチ一発ツモ裏１） 日時：2020/07/29 12:37 URL： https://twitter.com/luckymangan/status/1288317692085071872  

> 何処ぞの土下座像については、15〜20年前なら、「韓国の妄想w実現不能な妄想の表現くらいは、せめて認めてやらないとなw」と嘲笑する余裕はあったんだけど、現在ではそんな余裕がなくなったことに我が国の現状が反映されてると思う  

　2つ目は，ブロックされているのかわからないアカウントと思ったのですが，ブロックされていることを確認しました。

(py37_env) a66@a66-XTe:~/git/gh2020kk$ tu fukazawas 2
RT fukazawas（深澤諭史）｜uwaaaa（サイ太） 日時：2020-07-29 19:12／2020-07-29 13:13 URL： https://twitter.com/fukazawas/status/1288417141381672961 https://twitter.com/uwaaaa/status/1288326727043657730
> 野党が不甲斐ないから内閣支持率が発足以来最低になったじゃないか（怒） https://t.co/OBVHeYoNeV

RT fukazawas（深澤諭史）｜luckymangan（リーチ一発ツモ裏１） 日時：2020-07-29 19:07／2020-07-29 12:37 URL： https://twitter.com/fukazawas/status/1288415817466392582 https://twitter.com/luckymangan/status/1288317692085071872
> 何処ぞの土下座像については、15〜20年前なら、「韓国の妄想w実現不能な妄想の表現くらいは、せめて認めてやらないとなw」と嘲笑する余裕はあったんだけど、現在ではそんな余裕がなくなったことに我が国の現状が反映されてると思う

〈〈〈：Linux Emacs： 2020-07-29（水曜日）20：15 　〈〈〈

