* 「法科大学院に入学する前に司法試験受験を認めれば、受験生はもっと喜ぶと思いますが、いかがでしょうか？」という深澤諭史弁護士のツイートと，ブログ記事の紹介

:CATEGORIES: 司法制度改革,法科大学院

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2020/09/09 13:09 URL： https://twitter.com/fukazawas/status/1303546002914250752  

> 法科大学院在学中の司法試験受験を認める制度改革 - 弁護士 深澤諭史のブログ https://t.co/f7XD1MwDmb   
> 修了前なんてケチくさいこといわずに、法科大学院に入学する前に司法試験受験を認めれば、受験生はもっと喜ぶと思いますが、いかがでしょうか？  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-10 03:57／2020/09/10 03:54 URL： https://twitter.com/kk_hirono/status/1303769471778041856 https://twitter.com/s_hirono/status/1303768779030016001  

> 2020-09-10-035155_深澤諭史@fukazawas法科大学院在学中の司法試験受験を認める制度改革　-　弁護士　深澤諭史のブログ　http：／／弁護士。club／a.jpg https://t.co/zvBaazDLFD  

* 2020年9月10日午前3時過ぎに気がついた，「モトケソ」というモトケンこと矢部善朗弁護士（京都弁護士会）とアイコンが同じ別のTwitterアカウント

:CATEGORIES: モトケンこと矢部善朗弁護士（京都弁護士会）

　横になったまま眠っていて，テレビもつけたままで，起きたのが3時過ぎという時間でした。モトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインだと思ってみていたものが別のアカウント気がついたのは，起きて少ししてからのことだったと思います。

　次の2つのツイートが，時間の分かれ目になっています。

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-09-09 22:36 URL： https://twitter.com/hirono_hideki/status/1303688783481638912
> - 903：2020-09-09_22:36:31 ＊ 再び2020年9月5日で更新が止まっていると確認したモトケンこと矢部善朗弁護士（京都弁護士会）のTwitterタイムラインのツイート https://t.co/eI1ZVOUzpY

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-09-10 03:31 URL： https://twitter.com/hirono_hideki/status/1303762908547960832
> 2020年09月10日03時24分の登録： ツイートの記録資料：＼法務検察・石川県警察宛＼／深澤諭史（@fukazawas）／”2020年09月09日”：75件 https://t.co/R7Fdyu5ozV

　次が，別アカウントと気がついた後の，処理になります。

TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2020-09-10 04:18 URL： https://twitter.com/hirono_hideki/status/1303774793427120128
> 2020年09月10日04時17分の実行記録
> twitterAPI-search-lawList-mydql-add.rb "モトケソ"
> ツイート数：49/1969 リツイート数：43/1969 トータル：95
> hirono_hideki 9／0件
> kk_hirono 2／43件
> s_hirono 38／0件

```
REGEXP（サーチ）： "モトケソ"　該当：93件　取得ツイートの投稿日時の範囲：（2020-09-09 21：26〜2020-09-10 04：18）

SELECT * FROM tw_user_tweet WHERE tweet REGEXP "モトケソ" ORDER BY tw_date ASC

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”モトケソ”／データベース登録済みツイート：2020年09月10日04時21分の記録：ユーザ・投稿：3／93件 http://hirono2014sk.blogspot.com/2020/09/regexp202009100421393.html
```

```
アカウント名	ツイート数	リツイート数
非常上告-最高検察庁御中_ツイッター（s_hirono）	38	0
奉納＼さらば弁護士鉄道・泥棒神社の物語（hirono_hideki）	10	0
刑事告発・非常上告＿金沢地方検察庁御中（kk_hirono）	2	43


［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： REGEXP：”モトケソ”／データベース登録済みツイート：2020年09月10日04時21分の記録：ユーザ・投稿：3／93件 http://hirono2014sk.blogspot.com/2020/09/regexp202009100421393.html
```

　自作スクリプトの処理ですが，「取得ツイートの投稿日時の範囲：（2020-09-09 21：26〜2020-09-10 04：18）」という部分で，時間的に最初のツイートと最後のツイートの範囲が確認できます。気がつくまでは気が付かなかったので，これは参考になりました。

@motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@motoken_tw）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW motoken_tw（モトケン） 日時：2020/09/05 16:46 URL： https://twitter.com/motoken_tw/status/1302150988237742083  

> @P3rZI1SXporVAJt @joytamachan 連ツイを全部読みましょう。  

　モトケンこと矢部善朗弁護士（京都弁護士会）のTwitterアカウントは，上記の9月5日16時46分のツイートを最後に更新が止まったままです。

```
 - 2020年09月10日04時21分の登録： REGEXP：”モトケソ”／データベース登録済みツイート：2020年09月10日04時21分の記録：ユーザ・投稿：3／93件 http://hirono2014sk.blogspot.com/2020/09/regexp202009100421393.html
 - 2020年09月10日04時30分の登録： @motoken_tw（モトケン）のツイート　”．＊”　3200／3200：2020-06-16_0022〜2020-09-05_1646　2020年09月10日04時30分の記録 http://hirono2014sk.blogspot.com/2020/09/motokentw320032002020-06-1600222020-09.html
```

　「3200／3200」となったのは初めてかもしれません。理論上は200のオフセットが16回の取得で3200になるはずなのですが，そうなった試しはありませんでした。

　私の3つのアカウントで試したのですが，いずれも3200を超えていました。これも珍しいことです。オフセットの繰り返しは17回にしてあります。以前，仕様変更で増えていることを期待し変更してみたところ16回を超えて取得できたので，そのままにしています。

 - 2020年09月10日10時33分の登録： @hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）のツイート　”．＊”　3229／3229：2020-07-29_0033〜2020-09-10_1030　2020年09月10日10時33分の記録 http://hirono2014sk.blogspot.com/2020/09/hironohideki322932292020-07-2900332020.html
 - 2020年09月10日10時34分の登録： @kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）のツイート　”．＊”　3219／3219：2020-08-18_1018〜2020-09-10_1030　2020年09月10日10時34分の記録 http://hirono2014sk.blogspot.com/2020/09/kkhirono321932192020-08-1810182020-09.html
 - 2020年09月10日10時35分の登録： @s_hirono（非常上告-最高検察庁御中_ツイッター）のツイート　”．＊”　3218／3218：2020-05-19_2011〜2020-09-10_0942　2020年09月10日10時35分の記録 http://hirono2014sk.blogspot.com/2020/09/shirono-321832182020-05-1920112020-09.html

　しかし，謎はなぜモトケンこと矢部善朗弁護士（京都弁護士会）の@motoken_twとは異なるアカウントのページが開けたのかということです。

 - （01／93） TW s_hirono（非常上告-最高検察庁御中_ツイッター） 日時： 2020-09-09 21:26:00 +0900 URL： https://twitter.com/s_hirono/status/1303671060869464064

> 2020-09-09-211532_モトケソ@motokeso返信先：　@Miyako_Kojiさん,　@yomimateさん少し違う話題ですみません。難関である司法試験を勝ち.jpg https://t.co/4ymMXdXjhL

　上記の21時15分のスクリーンショットが最初の記録となっています。今ここで気がついたのですが，返信先に法クラの弁護士のアカウントのメンションがあります。

 - 弁護士 都 行志さん (@Miyako_Koji) / Twitter https://twitter.com/Miyako_Koji  

 - 弁護士 小林航太さん (@yomimate) / Twitter https://twitter.com/yomimate  

　今，タイムラインで気がついたのですが，モトケンこと矢部善朗弁護士（京都弁護士会）の別アカウントではなく，他人が勝手に作ったものの可能性が出てきました。その旨を指摘するツイートです。

- TW tebasakitoriri（須賀原洋行 講談社まんが学術文庫カミュ『異邦人』カフカ『変身』発売中） 日時： 2020/09/05 03:31 URL： https://twitter.com/tebasakitoriri/status/1301951147255578624  

> こういうアカウント作ると、モトケンさん @motoken_tw に訴えられないか…… https://t.co/7SV5vc2fmd  

- TW gokkunsan（名前が決まらない） 日時： 2020/09/05 09:12 URL： https://twitter.com/gokkunsan/status/1302036801763254273  

> @motoken_tw @tebasakitoriri こんなアカウントが…  
> モトケンさんのアイコンって、モトケンさんが作った(誰かに依頼して作ってもらった？)ものなんですよね？  
>   
> そうであれば、著作権を元にアイコンとして勝手に使用するのをやめるように言えそうに思いますが…  

@motokeso ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@motokeso）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW motokeso（モトケソ） 日時：2020/09/08 11:21 URL： https://twitter.com/motokeso/status/1303156388126797824  

> @gokkunsan このアイコンは、その人が作ったりしたものでは全くないのですよ。関係ない作者様がいて、勝手に使わせていただいてるだけです。 https://t.co/mx1gy8oaqr  

```
TW motokeso（モトケソ） 日時： 2020-06-18 20：37 URL： https：//twitter.com/motokeso/status/1273580570212106240
> @No_RightTurn_JP @mainichi 何罪で？

［source：］奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中： @motokeso（モトケソ）のツイート　”．＊”　505／505：2020-06-18_2037〜2020-09-10_0228　2020年09月10日03時34分の記録 http://hirono2014sk.blogspot.com/2020/09/motokeso5055052020-06-1820372020-09.html
```

　上記がモトケソというアカウントの最初のツイートとなっています。6月18日とあるのでだいぶん前ですが，昨夜の9月9日まで気が付きませんでした。ただ，ヘッダ画像のアザラシの写真は，過去に見たように思いました。

　岡口基一裁判官のなりすましアカウントにも本人の自作自演の疑惑がちらほらと見られたのですが，モトケンこと矢部善朗弁護士（京都弁護士会）のツイートを検索しても「モトケソ」は該当がありませんでした。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-10 11:00／2020/09/10 10:54 URL： https://twitter.com/kk_hirono/status/1303875924438388737 https://twitter.com/s_hirono/status/1303874572798758912  

> 2020-09-10-105419_モトケソ@motokesoブロックされています@motokesoさんのフォローやツイートの表示はできません。詳細はこちら.jpg https://t.co/ivF1cCA4Mh  

　モトケンこと矢部善朗弁護士（京都弁護士会）本人のツイートと誤解を与えたことは明らかです。モトケンこと矢部善朗弁護士（京都弁護士会）本人が気づいていない可能性は否定できませんが，もう5日ほど更新が止まったままで，事実上の沈黙とも想定される対応です。

* 「陳述書の量／厚木弁護士ｃｈ・神奈川県 - YouTube」に複雑な事件で20枚程度におさめるべきという，増えると裁判官が嫌い，流し読みをされる可能性も出るという解説

　2,3日前からブラウザのタブでページを開いたままにしていました。ある動画の視聴後，YouTubeの自動再生がオンになっていて始まったのがこの動画です。

陳述書の量／厚木弁護士ｃｈ・神奈川県 - YouTube https://t.co/eDBCrPWzL0

　不思議なことに，平成5年辺りから法律の勉強を始め民事裁判の経験もあるのですが，陳述書というものは，これまでほとんど知らなかったと思います。

- RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜motoken_tw（モトケン） 日時：2011/02/20 06:33／2011/02/19 18:28 URL： https://twitter.com/hirono_hideki/status/39075221474508800 https://twitter.com/motoken_tw/status/38892622097416192

> RT @motoken_tw: .@nakanori930 私は、供述調書も代理人作成の陳述書も記者が書く記事も、人が他人の話を聞いてそれを聞いた人間がまとめるという成立過程において同じだという事実を指摘しているだけです。そしてそのような伝聞過程そのものに誤謬が混入する可能性があることを確認しているだけです。  

　Twilogで最も古い「陳述書」を含むツイートが，2011年2月20日のリツイートで，モトケンこと矢部善朗弁護士（京都弁護士会）のツイートをリツイートしたものでした。ブロックをされていなかった期間ということになります。

　冒頭のYouTubeの動画では，代理人の弁護士が作成し署名捺印などするのが準備書面で，陳述書は依頼者本人の作成で，依頼者本人の署名捺印と解説がありました。捺印は正確ではないかもしれません。押印などもあったかと思いますし，確認はしていません。

- TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2014/02/16 14:15 URL： https://twitter.com/hirono_hideki/status/434918998460084224  

> 遠隔操作事件、謎深まる片山被告の冒頭陳述書 : サイバー護身術 : セキュリティー : ネット＆デジタル : YOMIURI ONLINE（読売新聞） http://t.co/iZGrMh8916  

　記録が残っていますが，冒頭陳述書というのは初めて聞いたように思いました。刑事裁判ではまれに弁護人の冒頭陳述を聞くことはあったと思いますが，冒頭陳述書という言葉は見聞きした憶えがありません。

- RT hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）｜take___five（中村剛（take-five）） 日時：2018/01/01 00:06／2017/12/21 11:23 URL： https://twitter.com/hirono_hideki/status/947484089526894592 https://twitter.com/take___five/status/943668247248826369

> RT @take___five: 中村=岡口本で、「陳述書なんてほとんど証拠価値ない」とあったけど、同じく一方当事者が書いた作文に過ぎない検面調書や員面調書にそれなりの証拠価値が認められてるの何でだろうとか思う。民事で「公開法廷での尋問の証言より、前の陳述書の方が信用できる」なんてあり得ない事態だと思うけど。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-10 11:47／2018/08/16 18:22 URL： https://twitter.com/kk_hirono/status/1303887865810567169 https://twitter.com/hirono_hideki/status/1030021930185715712  

> 陳述書（東京高等裁判所分限事件調査委員会） - 分限裁判の記録　岡口基一 https://t.co/qv4GzQhN3u  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-10 11:48／2020/07/10 10:21 URL： https://twitter.com/kk_hirono/status/1303888049974116352 https://twitter.com/hirono_hideki/status/1281398095545167872  

> 2020年07月10日01時23分の登録： ＼ピピピーッ　@O59K2dPQH59QEJx＼次回期日が迫った事件で、この時間帯に、相手方本人直筆の陳述書がFAXで大量に届くと、相手方代理人が気の毒になる。 https://t.co/YZAX5qBcGE  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-10 11:49／2020/09/08 20:22 URL： https://twitter.com/kk_hirono/status/1303888179498369025 https://twitter.com/hirono_hideki/status/1303292596215623680  

> - 【愛媛ご当地アイドル自殺訴訟】陳述書のサインを得ようと元愛の葉Girlsメンバーに取引を持ちかける遺族弁護団の音声録音【月9】 - YouTube https://t.co/vs5RHKXTRI  

　それなりに陳述書を見かけてきたようですが，つい先日までは印象に薄く，陳述書を検索で調べた形跡もありませんでした。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-10 11:52／2020/09/08 20:39 URL： https://twitter.com/kk_hirono/status/1303889121874554880 https://twitter.com/hirono_hideki/status/1303296897960964096  

> - 陳述書の量／厚木弁護士ｃｈ・神奈川県 - YouTube https://t.co/2Oco3xL0g8  

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2020年09月08日 - Twilog https://t.co/WzF8t53Xtm

　自動再生される前の動画もツイートをしているものと思っていたのですが，失念したのか見当たらず，とても大きな発見と感じていただけに不思議なことです。

 - 【愛媛ご当地アイドル自殺訴訟】陳述書のサインを得ようと元愛の葉Girlsメンバーに取引を持ちかける遺族弁護団の音声録音【月9】 - YouTube https://www.youtube.com/watch?v=_30fFGTLbws&feature=youtu.be  

　再生回数は4,505回視聴となっていて，8日に視聴したときから増えていない感じです。あれだけテレビで放送があった問題なのに，最近になってFRAIDY，デイリー新潮でも取り上げながら，関心が高まることはなさそうな感じです。

　関与した弁護士に対する関心が低まったとすれば，それが世間の反応なのかもしれません。時間を割いて調べたり，視聴する価値がないと多くに判断されたのかもしれないということです。

　陳述書ですが，20枚でも多いというのが意外でした。判決書だと80枚ぐらいになると読むのに朝から夕方までぐらいの時間が掛かります。集中力を徹底すればいくらか短縮はできそうですが，気を抜くとさらに時間が掛かります。その判決書も重複部分が多いです。

```
１　様式
　　Ａ４版（縦置き）横書きとする（片面のみ使用。Ａ３判の袋とじもしない。）。
　　文字サイズは１２ポイント，１行文字数は３７字，１ページの行数は２６行。
　　余白は，上端３５㎜，下端２７㎜，左側３０㎜，右端１５～２０㎜とする。
　　左端は，綴じしろ，２箇所でステープラー（ホッチキス）止め
　　上端は受付印用のスペースとなる。

［source：］裁判文書（裁判所提出書類）の標準的な書式，表記法 http://www5d.biglobe.ne.jp/Jusl/Bunsyo/Suujihyouki2.html
```

　「１行文字数は３７字，１ページの行数は２６行」とあります。平成9年から11年当時は，一太郎で裁判所に提出する書面を1ページ45行には設定していたと思います。一行の文字数も50文字に近かった気がします。

　最近になってこのような様式に文字数や余白のサイズを合わせるようになったのですが，以前は用紙代と印刷代がかさむと考え，一ページあたりの文字数を多く設定していました。

* 《参考資料》昭和50年代初めのスーパーカーブームと週刊少年ジャンプの連載「サーキットの狼」，その当時のBMW

:CATEGORIES: 参考資料

```
1970年代の日本におけるスーパーカーブーム［編集］
日本では、かつて1976年頃から1978年頃にかけて、池沢さとしの漫画『サーキットの狼』などの影響で、スーパーカーの爆発的なブームが起きた。スーパーカーは一般大衆には入手が困難なことから、特に自動車が好きな人達から見ると羨望の的となった。代表的な存在として君臨したのがランボルギーニ・カウンタックであり、他にもフェラーリ・512BB、ポルシェ・ターボ、ロータス・ヨーロッパ、ランチア・ストラトスなどが特に人気のあった車種である。当時のブームにおいて知名度を得たスーパーカー群は、21世紀初頭の現在でも根強い人気がある。

ブーム当時の日本では、車の購買層ではない低年齢層へのプロモーションとして、コカ・コーラ、ファンタ等の清涼飲料水の王冠の裏に車が描かれていたり、カード型の書籍やプラモデル（スケールモデル）、ミニカー、ラジコンが数多く発売された。その中でとりわけ人気を誇ったのがスーパーカー消しゴムと呼ばれる塩化ビニール製のミニチュアで、消しゴムという商品名ゆえ学校に持ち込んで遊ぶ子供も多くいた。スーパーカーブームにより自動車に関する情報が低年齢層に浸透することとなり、並行する形でモータースポーツ（F1、ル・マン24時間レース、世界ラリー選手権など）に対するブームも巻き起こった。

［source：］スーパーカー - Wikipedia https://ja.wikipedia.org/wiki/%E3%82%B9%E3%83%BC%E3%83%91%E3%83%BC%E3%82%AB%E3%83%BC#1970%E5%B9%B4%E4%BB%A3%E3%81%AE%E6%97%A5%E6%9C%AC%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E3%82%B9%E3%83%BC%E3%83%91%E3%83%BC%E3%82%AB%E3%83%BC%E3%83%96%E3%83%BC%E3%83%A0
```

```
『サーキットの狼』（サーキットのおおかみ）は、漫画家の池沢さとしが1975年（昭和50年）から1979年（昭和54年）にかけて「週刊少年ジャンプ」（集英社）に連載した漫画作品。続編に『サーキットの狼II モデナの剣』、『21世紀の狼』がある。実写映画が1977年に製作・公開された。

［source：］サーキットの狼 - Wikipedia https://ja.wikipedia.org/wiki/%E3%82%B5%E3%83%BC%E3%82%AD%E3%83%83%E3%83%88%E3%81%AE%E7%8B%BC
```

　記憶では，小学校6年生の昭和51年頃にスーパーカーブームが始まり，1年ほど後に週刊少年ジャンプの「サーキットの狼」の連載が始まったと思っていたのですが，スーパーカーブームが昭和51年から53年，サーキットの狼の連載が昭和50年から昭和54年とあります
 - Transformers 3 dark of the moon 2017 hindi 720p hd | エアロ https://www.pinterest.jp/pin/862439397363884994/

* 《参考資料》日野レンジャー　4代目（1989年〜2001年）

```
4代目（1989年-2001年）［編集］

クルージングレンジャーGD
教習車
1989年7月登場。通称クルージングレンジャー。コマーシャルにはアメリカの女優ダイアン・レインが出演した。エンジンは平成元年排出ガス規制適合のH07Dを搭載。ヘッドライトは異型2灯を採用した（一部の輸出向けは角型4灯を継続）。キャッチコピーは「人と街に響きあう」。フロントグリルがガンメタリック色に戻り、フェンガーニッシュも同じ色である。

［source：］日野・レンジャー - Wikipedia https://ja.wikipedia.org/wiki/%E6%97%A5%E9%87%8E%E3%83%BB%E3%83%AC%E3%83%B3%E3%82%B8%E3%83%A3%E3%83%BC#4%E4%BB%A3%E7%9B%AE%EF%BC%881989%E5%B9%B4-2001%E5%B9%B4%EF%BC%89
```

* 《参考資料》被告発人安田敏の平成3年当時の花里のアパートと，金沢市涌波周辺

花里町 - Google マップ https://t.co/mFk1m3QXAH

告訴事件と関連のある金沢市内の場所 - Google マイマップ https://t.co/RyqK5YMjzM 被告訴人YSNが住んでいた金沢市花里町

告訴事件と関連のある金沢市内の場所 - Google マイマップ https://t.co/xrJsldoCKL Google マップからの詳細情報 \n 〒920-0944 石川県金沢市三口新町１丁目５−１ \n https://t.co/DOnkn1vxsl

　涌波ではなく金沢市三口新町１丁目となっていますが，この辺りにウェルマート涌波店がありました。前の大通りは犀川大通りとなっていますが，余り聞いたことのない道路の名前です。平成3年当時も金沢市内の中心部，片町のスクランブル交差点からは末町に向かって一本道の道路でした。

　ずいぶん前に作成したGoogleのマイマップですが， 被告訴人YSNとあるのは，被告発人安田敏のことです。

* 《参考資料》堂野さんを送った寺中町の大体の場所と，同じ寺中町の中西運輸商の事務所，それと近くの金沢西警察署

告訴事件と関連のある金沢市内の場所 - Google マイマップ https://t.co/S69heWPr4f  \n 「令和2年9月10日追加」という新規レイヤー \n 1. 石川県　金沢西警察署 \n 2. 中西運輸商の事務所があった場所 \n 3. 堂野さんを送った辺り

　ちょっと見づらいかもしれないので，次が改行を入れたものです。

告訴事件と関連のある金沢市内の場所 - Google マイマップ https://t.co/S69heWPr4f 
「令和2年9月10日追加」という新規レイヤー
1. 石川県　金沢西警察署
2. 中西運輸商の事務所があった場所
3. 堂野さんを送った辺り

中西ビル - Google マップ https://t.co/GPQNvygdER

　場所の間違いに気が付き修正をしていたのですが，中西運輸商の事務所があった建物は中西ビルという名前で，Googleマップのストリートビューで見ると，建物がそのまま残っているようです。トタンの部分が赤茶色なのは記憶と違った感じではあります。

　すぐ近くの交差点になっている広い道路に海側幹線とありますが，平成11年頃には工事も始まっていなかったと思います。

* 





