* Linux（Ubuntu）で，C＃のCoreTweetのコンパイルと実行を出来るようした，dotnetとmono

　dotnetの方は，「dotnet add package CoreTweet --version 1.0.0.483」とやるだけで，情報さえ見つかれば，そのまま実行するだけで簡単でした。dotnetはインストールも簡単だったと思います。

　しかし，dotnetは，「dotnet new console -o twitterTl」などとアプリのようなものを作った上で，ディレクトリに入り，C#のコードを書いたcsのファイルを編集し，「dotnet run」という実行方法しか情報が見当たりませんでした。

　monoは，「mcs Program.cs」などとやることでexeファイルが作成され，「mono Program.exe」と実行することが出来，プログラムのコンパイルとして自然体です。

　Visual Studioだと簡単にインストールできたCoreTweetですが，monoだと情報が見つからず，試行錯誤の連続でした。Javaでもクラスパスを指定するコンパイルの方法があったので，その方向で調べたところうまくいきました。

　ファイルは別に入手したものになりますが，NET45のものを使いました。「mcs -reference:./CoreTweet.dll Program.cs」でコンパイルは成功したのですが，実行時にエラーが出たので，同じディレクトリにNewtonsoft.Json.dllを置きました。

　「nuget install CoreTweet」の実行で「CoreTweet.1.0.0.483  Newtonsoft.Json.9.0.1」の２つのディレクトリが出来，そのなかにCoreTweet.dllとNewtonsoft.Json.dllがあります。

* Linux（Ubuntu）のPowerShell Coreで，指定したディレクトリー内で再帰的に正規表現に一致したファイルを，カレントディレクトリーにコピー

:CATEGORIES: PowerShell Core,正規表現

```
PS (19:09:35) > Get-ChildItem -Path ~/ -Recurse | Where-Object { $_.name -match  "^200[1-3]-..-...*\.jpg$" }| % { $n = $_.name; if (Test-Path ./$n) { echo "ここに，${n}はあります。" } else { cp $_.FullName ./$n} }
ここに，2002-11-02_152511＿別冊ジュリスト，シッカロール.jpgはあります。
ここに，2002-11-02_152511＿別冊ジュリスト，シッカロール.jpgはあります。
ここに，2002-12-29_163215＿告発事件一件記録（写真資料・撮影日時）.jpgはあります。
ここに，2002-11-02_152511＿別冊ジュリスト，シッカロール.jpgはあります。
ここに，2002-12-29_163215＿告発事件一件記録（写真資料・撮影日時）.jpgはあります。
PS Pictures/w (19:10:48) > ls
2002-11-02_152511＿別冊ジュリスト，シッカロール.jpg  2002-12-29_163215＿告発事件一件記録（写真資料・撮影日時）.jpg
```

　これまではfindコマンドのexecオプションや，locateコマンドとxargsとの組み合わせで行ってきた処理ですが，複数の同名ファイルがあると，ワーニングのようなメッセージが出ていたので条件式を付けました。

* 


