* 「そういう国の9歳の女児との性行為を我々が虐待と考えるためには法律以外の根拠が必要になるが、あなたは何を根拠に虐待と考えるんですか？」等というモトケンこと矢部善朗弁護士（京都弁護士会）の一連ツイート

:CATEGORIES: モトケンこと矢部善朗弁護士（京都弁護士会）,性犯罪

@motoken_tw ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@motoken_tw）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW motoken_tw（モトケン） 日時：2020/10/05 17:12 URL： https://twitter.com/motoken_tw/status/1313029346710355968  

> @joytamachan 現時点において、9歳の女児との性行為が法的に許容されている国においては、国家政策的には虐待とは考えられていないことを意味すると思われる。  
> そういう国の9歳の女児との性行為を我々が虐待と考えるためには法律以外の根拠が必要になるが、あなたは何を根拠に虐待と考えるんですか？  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜joytamachan（じょいたまちゃん） 日時：2020-10-05 21:18／2020/10/05 12:25 URL： https://twitter.com/kk_hirono/status/1313091097409712130 https://twitter.com/joytamachan/status/1312957103829479427  

> 甘いですね。現代においても「9歳女児との性交が法的に許されている国においては当該行為は性的虐待には当たらない」と主張する日本人はいくらでもいます。 https://t.co/OCnjOKtv5o  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜joytamachan（じょいたまちゃん） 日時：2020-10-05 21:18／2020/10/05 13:41 URL： https://twitter.com/kk_hirono/status/1313091132285284354 https://twitter.com/joytamachan/status/1312976280778764291  

> @motoken_tw その前にあなたは「現代の"9歳女児との性交が法的に許されている国"における当該行為は性的虐待に当たる」と考えているんですか？　現代日本に生きるあなた自身の考えをお聞かせください。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜joytamachan（じょいたまちゃん） 日時：2020-10-05 21:18／2020/10/05 17:43 URL： https://twitter.com/kk_hirono/status/1313091165491666944 https://twitter.com/joytamachan/status/1313037078276399105  

> @motoken_tw 下記ツイートで述べています。 https://t.co/RrMH88pSCd  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜qqquppi（qqquppi） 日時：2020-10-05 21:18／2020/10/05 18:53 URL： https://twitter.com/kk_hirono/status/1313091200778342400 https://twitter.com/qqquppi/status/1313054691253579776  

> @motoken_tw @joytamachan おっしゃっている虐待は「それをする人間は屑である」の意味を含む「虐待」でしょうか？  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜qqquppi（qqquppi） 日時：2020-10-05 21:18／2020/10/05 19:51 URL： https://twitter.com/kk_hirono/status/1313091239634296834 https://twitter.com/qqquppi/status/1313069394780536833  

> @motoken_tw @joytamachan ならば、おっしゃる虐待には「それをする人物は蔑む（あるいは、改心を求める）に値する」の意味は含まれるでしょうか？  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜JIivJTStnKDHMe0（くいだおれ） 日時：2020-10-05 21:18／2020/10/05 20:10 URL： https://twitter.com/kk_hirono/status/1313091268549861377 https://twitter.com/JIivJTStnKDHMe0/status/1313074049522704385  

> @motoken_tw @qqquppi @joytamachan 横から失礼します。 児童が『悲惨』『危険』『かわいそう』な境遇にあることを指して『虐待』状況におかれている、と言えるかと だから当然に 配偶者や社会が虐待をしていた。と言えるかは別の話だと思います。  じょいたまちゃんさんは わざとごっちゃにしようとしていませんか？  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-05 21:20／2020/10/05 21:17 URL： https://twitter.com/kk_hirono/status/1313091617172070400 https://twitter.com/s_hirono/status/1313090991428005888  

> 2020-10-05-211713_モトケン@motoken_tw返信先：　@joytamachanさん現時点において、9歳の女児との性行為が法的に許容されている国においては、.jpg https://t.co/WKTpWovpt1  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-05 21:20／2020/10/05 21:09 URL： https://twitter.com/kk_hirono/status/1313091629792718849 https://twitter.com/s_hirono/status/1313089002984009728  

> 2020-10-05-204756_モトケン@motoken_tw真っ当な議論とは全く別の観点で楽しめるなw.jpg https://t.co/cC4okU0yE0  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-05 21:20／2020/10/05 21:09 URL： https://twitter.com/kk_hirono/status/1313091641926807552 https://twitter.com/s_hirono/status/1313088930212794369  

> 2020-10-05-204645_モトケン@motoken_tw·8時間すでに何人もの人が指摘しているけど、この問題は当時は虐待とは考えられていなかったとしても、現代において.jpg https://t.co/dTMT18n44Z  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-05 21:20／2020/10/05 21:09 URL： https://twitter.com/kk_hirono/status/1313091661434560512 https://twitter.com/s_hirono/status/1313088857462595584  

> 2020-10-05-203455_モトケン@motoken_tw·2時間考え方としては反対する理由はないですけど、女児の性的な自己決定能力は幾つになったらあると言えるかが明ら.jpg https://t.co/MCDViLxO4x  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-05 21:20／2020/10/05 21:08 URL： https://twitter.com/kk_hirono/status/1313091678148857863 https://twitter.com/s_hirono/status/1313088784573947904  

> 2020-10-05-203123_モトケン@motoken_tw·6分返信先：　@JIivJTStnKDHMe0さん,　@qqquppiさん,　@joytamachanさんじ.jpg https://t.co/C6hOy7znvz  

```
 - 2020年10月05日20時31分の登録： ＼モトケン　@motoken_tw＼じょいたまちゃんは「分析」ということが苦手です。つまり、論理的思考が苦手です。 http://kk2020-09.blogspot.com/2020/10/motokentw_5.html
 - 2020年10月05日20時35分の登録： ＼モトケン　@motoken_tw＼重大な身体的ダメージの具体的内容も問題になりますが、私は女児にとって性行為が苦痛であるならば虐待と言っていいと思います。 http://kk2020-09.blogspot.com/2020/10/motokentw_16.html
 - 2020年10月05日20時46分の登録： ＼モトケン　@motoken_tw＼すでに何人もの人が指摘しているけど、この問題は当時は虐待とは考えられていなかったとしても、現代においては例外なく性的虐待であって許され http://kk2020-09.blogspot.com/2020/10/motokentw_19.html
 - 2020年10月05日20時47分の登録： ＼モトケン　@motoken_tw＼真っ当な議論とは全く別の観点で楽しめるなw http://kk2020-09.blogspot.com/2020/10/motokentww_5.html
 - 2020年10月05日21時13分の登録： ＼モトケン　@motoken_tw＼そういう国の9歳の女児との性行為を我々が虐待と考えるためには法律以外の根拠が必要になるが、あなたは何を根拠に虐待と考えるんですか？ http://kk2020-09.blogspot.com/2020/10/motokentw9_5.html
```

　例外があるとは考え難いのですが，強姦罪から強制性交等罪とかになった刑法の条文では，確か13歳未満との性交は，同意の有無に関わりなく犯罪の成立を構成要件としていたはずかと思います。このあと確認をしておきますが，モトケンこと矢部善朗弁護士（京都弁護士会）の理屈は不可解です。

```
強制性交等罪（きょうせいせいこうとうざい）とは、暴行又は脅迫を用いて13歳以上の人に性交、肛門性交又は口腔性交（以下「性交等」）をし、または、13歳未満の人間に性交等をする犯罪である。刑法177条に定められている。睡眠・飲酒酩酊・薬物・昏睡・精神障害、知的障害という心神喪失や抗拒不能という心理的・物理的に抵抗ができない状態で性交した場合は罪名は準強制性交等罪となるが罪刑の重さは同じ5年以上の有期懲役であり、性犯罪の中で最も重い犯罪。かつては被害者が女性の場合のみ適応される強姦罪（ごうかんざい）であった。改正刑法案が2017年（平成29年）6月16日に可決成立［1］、同年6月23日に公布、7月13日施行され、これにより強姦罪は廃止され継承類型としての本罪が改正施行された。本罪では、男性が被害者の場合を含めた、性別不問の規定となり、また非親告罪となっている。

［source：］強制性交等罪 - Wikipedia https://ja.wikipedia.org/wiki/%E5%BC%B7%E5%88%B6%E6%80%A7%E4%BA%A4%E7%AD%89%E7%BD%AA
```

　ざっと上記のWikipediaに目を通したところ，13歳未満の性交の同意の有無は問題にされていないようですが，本来，暴行又は脅迫の有無を構成要件に必要とする条文のはずなので，13歳未満との性交は，13歳未満との認識がなかったという場合以外に犯罪の成立は免れないように情報を見てきました。

　錯誤による9歳女児に対する性犯罪を助長しているように見える他ない，モトケンこと矢部善朗弁護士（京都弁護士会）の一連のツイートです。

* 
