* 「（；・∀・）もう、大勢の人が指摘していますが、こういうメッセージ出すときは、絶対に、弁護士に相談してからがいいですよ・・・。」という深澤諭史弁護士のツイート
  :LOGBOOK:
  CLOCK: [2020-08-11 火 06:35]--[2020-08-11 火 09:31] =>  2:56
  :END:

:CATEGORIES: 深澤諭史弁護士,弁護士相談

〉〉〉：Emacs： 2020-08-11（火曜日）06：35　 〉〉〉

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2020/08/10 21:37 URL： https://twitter.com/fukazawas/status/1292802231423520773  

> （；・∀・）もう、大勢の人が指摘していますが、こういうメッセージ出すときは、絶対に、弁護士に相談してからがいいですよ・・・。  
> （；；＾ω＾）ですお・・・。 https://t.co/7eap6f9P6d  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜jump_henshubu（少年ジャンプ編集部） 日時：2020-08-11 06:37／2020/08/10 17:00 URL： https://twitter.com/kk_hirono/status/1292938190001602560 https://twitter.com/jump_henshubu/status/1292732640886321152  

> 『アクタージュ act-age』連載終了に関するお知らせ https://t.co/hCsKndrH2r https://t.co/qZeSFhCUGy  

　今見ると，深澤諭史弁護士の引用リツイートした少年ジャンプ編集部のツイートは，リツイートが13.3万，いいねが12.2万となっていました。これだけの反応があれば，引用リツイートした深澤諭史弁護士のツイートは読まれる可能性がかぎりなく低そうです。

　以前も似たような深澤諭史弁護士の反応を見たことがあったのですが，その時は高岡市のTwitterアカウントのツイートで，リツイートの数などから読まれている可能性がありそうに思えました。行政書士の法律相談に対する深澤諭史弁護士の意見だったと思います。

　深澤諭史弁護士の「弁護士」に対するこだわりは並外れていると昨夜も思っていたのですが，その特徴を探り分析すべく，いくつかツイートで見かけてきた印象的なワードでまとめ記事を作成していたところ，ふと弁護士でやってみたところ，記録的な数のまとめ記事が作成されました。

```
 - 2020年08月10日23時52分の登録： REGEXP：”成仏”／深澤諭史（@fukazawas）の検索（2012-12-15〜2020-08-10／2020年08月10日23時51分の記録728件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2012-12-152020-08.html
 - 2020年08月10日23時55分の登録： REGEXP：”高橋宏志”／深澤諭史（@fukazawas）の検索（2014-07-03〜2020-08-10／2020年08月10日23時55分の記録67件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2014-07-032020-08.html
 - 2020年08月10日23時56分の登録： REGEXP：”相談”／深澤諭史（@fukazawas）の検索（2012-09-26〜2020-08-10／2020年08月10日23時55分の記録1544件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2012-09-262020-08.html
 - 2020年08月10日23時56分の登録： REGEXP：”無料”／深澤諭史（@fukazawas）の検索（2012-12-14〜2020-08-10／2020年08月10日23時56分の記録391件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2012-12-142020-08.html
 - 2020年08月10日23時59分の登録： REGEXP：”弁護士”／深澤諭史（@fukazawas）の検索（2012-09-10〜2020-08-10／2020年08月10日23時57分の記録9482件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2012-09-102020-08.html
```

　深澤諭史弁護士のTwitterアカウントは本日2020年8月11日，11.6万ツイートとなっています。そのうち少なくとも9482件が弁護士をワードに含むツイートで，ツイートの全件記録を初めたのは2,3年前だと思うので，その実数はさらに多いものになると思います。

　少年ジャンプ編集部というのは，少年時代，唱和50年代の前半によく見かけたと思います。他に経験がないのですが，懸賞に当たって，漫画のマスコットの犬の人形が家に送られてきました。その漫画の情報は見かけず，タイトルも思い出せないのですが，時代の流れと変化を感じます。

　私の個人的な感想ですが，前々より漫画そのものと思っていた深澤諭史弁護士が，少年ジャンプ編集部にあてた引用ツイートの御意見は，どこまで本当なのかと目を疑う，まさに漫画のような話です。

　少年ジャンプ編集部のツイートは，PDFファイルを画像に変換したものにみえますが，リンクを開くとテキスト文として掲載がありました。深澤諭史弁護士の反応を社会現象，弁護士現象として考える上で，次に全文を引用させていただきたいと思います。

```
去る8月8日、『アクタージュ act-age』の原作担当であるマツキタツヤ氏が逮捕されました。

編集部ではこの事態を非常に重く受けとめて、事実確認のうえ、作画担当の宇佐崎しろ先生と話し合いを持ちました。その結果、『アクタージュ act-age』の連載をこのまま継続することはできないと判断いたしました。
8月11日（火）発売の「週刊少年ジャンプ36・37合併号」の掲載をもって、連載終了といたします。

これまで多くの読者の皆様に応援していただいた作品をこのような形で終了することになり、編集部としても非常に残念でなりません。しかしながら、事件の内容と、「週刊少年ジャンプ」の社会的責任の大きさを深刻に受け止め、このような決断に至りました。
ご心配、ご迷惑をおかけしましたこと、心よりお詫び申し上げます。

編集部はもとより、宇佐崎先生は断腸の思いをなさっていますが、先生をサポートし、また作品を作っていけるよう励んでまいります。
なお、コミックス等の関連刊行物やイベント等各種企画につきましては、関係各所とも協議のうえ、決まり次第お知らせいたします。


2020年8月10日
週刊少年ジャンプ編集部

［source：］『アクタージュ act-age』連載終了に関するお知らせ｜集英社『週刊少年ジャンプ』公式サイト https://www.shonenjump.com/j/2020/08/10/200810_oshirase001.html
```

　「社会的責任の大きさを深刻に受け止め、このような決断に至りました。」という部分に込められたものを感じますが，深澤諭史弁護士には弁護士として救いの妙案，指南があるかの提示をほのめかすものを感じました。

　テレビのニュースを見ていると，確か少女に対する，わいせつ事件のようでしたが，服の上から体を触ったとか，概ね認めているという話になっていたと思います。調べれば出てくるでしょうが，ネットでは今のところ余り情報をみていません。

　服の上から体を触って逮捕というのは余り聞かないのですが，事実関係はわからないものの，仮にへたに弁護士を頼りにしたことで逮捕に至ったとすれば，その悪影響の深刻さがうかがえます。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜EktDFDEOZSJjmoY（ハードボイルド弁護士） 日時：2020-08-11 07:09／2020/08/10 21:21 URL： https://twitter.com/kk_hirono/status/1292946321817530368 https://twitter.com/EktDFDEOZSJjmoY/status/1292798214756659208  

> ジャンプの人気漫画家が捕まった！ 漫画は打ち切り！ 被害者は、直接の犯罪被害者だけではない！ 作品に関わった多くの人までも巻き込まれた！ マツキタツヤではなく、巻き込み竜巻や！  

マツキタツヤ　弁護士 - Twitter検索 / Twitter https://t.co/p47ZtubJO9

　Twitter検索の結果は1件のみでしたが，プロフィールの名前とプロフィールに弁護士とあるアカウントでした。見かけないと思ったのですが，初見の可能性が高そうです。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜EktDFDEOZSJjmoY（ハードボイルド弁護士） 日時：2020-08-11 07:13／2020/08/05 20:12 URL： https://twitter.com/kk_hirono/status/1292947133629263874 https://twitter.com/EktDFDEOZSJjmoY/status/1290968896510373895  

> 東出は、当初、弁護士をつけなかった！ 弁護士をつけないことで、相手に誠意が伝わると勘違いする人がいるが、それは間違いだ！ 浮気では、相手は感情的になるから、弁護士を入れて冷静に話した方が絶対に良い！  

　「弁護士をつけないことで、相手に誠意が伝わる」というのは首肯しうるもので，以前はぼんやりとそう考えていたのですが，深澤諭史弁護士の荒唐無稽な弁護士ツイートなどを見ていると，大きな説得力を感じるとともに，弁護士迷惑・危険対策の必要性も強く感じるようになりました。

　あらためて，「（；・∀・）もう、大勢の人が指摘していますが」という切り出しから，深澤諭史弁護士の週刊少年ジャンプ編集部に向けたツイートが始まっているのも鮮烈です。深澤諭史弁護士のタイムラインにもそんな指摘はなかった気がします。その手のリツイートは多い傾向が前からあります。

 - 2020年08月10日21時49分の登録： ＼深澤諭史　@fukazawas＼（；・∀・）もう、大勢の人が指摘していますが、こういうメッセージ出すときは、絶対に、弁護士に相談してからがいいですよ・・・。 （；；＾ω http://hirono2014sk.blogspot.com/2020/08/fukazawas_79.html

　確認したところ，一つ見落としがあったようです。確かに１つ，週刊少年ジャンプ編集部のコメントに言及したツイートの深澤諭史弁護士のリツイートが，深澤諭史弁護士のタイムラインにありました。

RT fukazawas（深澤諭史）｜Simon_Sin（Simon_Sin） 日時：2020-08-10 19:30／2020-08-10 18:38 URL： https://twitter.com/fukazawas/status/1292770395716632576 https://twitter.com/Simon_Sin/status/1292757247034941441
> 残念とかじゃなくて被害者の子（たち？）に対するお詫びとか心配とか配慮とかそういうのはなくていいのか？大人だろ？ https://t.co/NQnQQ1Efpt

　この「残念とかじゃなくて被害者の子（たち？）に対するお詫びとか心配とか配慮とかそういうのはなくていいのか？大人だろ？」というツイートの内容を前提に，深澤諭史弁護士のツイートの内容を考えると，弁護士にまかせることで配慮の行き届いた対応が出来た，となるのか。

　これもテレビで，パソコンで作業しながら耳に入った言葉でしたが，「そしてなにより大切な」という言葉が聞こえてきて，印象に残るものとなっていました。

ジャンプ　謝罪 - Google 検索 https://t.co/tfPYqTI1U4

　上記の検索結果の1ページにある記事をすべて開いて探したのですが，「なにより大切な」という文言は見つかりませんでした。気になったのは，いずれも強制わいせつで逮捕などとだけあることです。テレビのニュースでは，服の上からとなっていたように思います。

　強制わいせつ罪は要件がきつめになっているはずなので，服の上から触って成立するのか疑問です。

少年ジャンプ漫画の原作者逮捕 女子中学生にわいせつ行為疑い | NHKニュース https://t.co/dCTAjMYIjs

　逮捕された人物の名前で調べていたのですが，「路上で10代少女の胸を触った」とだけあるものが多く，上記のNHKニュースの内容が今のところ最も詳細で具体性があります。テレビの報道とも似た内容ですが，服の上からとは書かれておらず，体を触ったとあります。

　時刻は7時48分です。ちょうど1分ほどの間に，気になっていたニュースの報道が２つありました。少年ジャンプ漫画の原作者逮と，それに続いたのがポルシェの事故でした。映像はなく，「100キロ以上は出していた」という被疑者の言葉だけ紹介されていました。

　あの事故の映像をみれば，「100キロ以上は出していた」という言葉と現実との違いの大きさが際立ちます。ネットでは250キロ，200キロ近くという声がありましたが，他に走行している車が止まっているように見えたので，200キロ以上が実態に近い気がしました。

　ZIPという番組なのでテレビ金沢の日テレですが，これほど簡潔な報道は驚きでした。これだけ実際の事故と報道のされ方にギャップを感じたのも初めてかもしれません。

　「少年ジャンプ漫画の原作者逮捕」も防犯カメラの映像が決め手になったような話で，ポルシェの死亡事故と共通して感じたのは，弁護士いらず，の時代の到来ということです。昨日調べたポルシェの事故に対する法クラの弁護士らの反応もゼロに近いものがありました。

〈〈〈：Emacs： 2020-08-11（火曜日）09：31 　〈〈〈

* 昨日に知った，川崎市の首都高速湾岸線のポルシェの追突夫婦死亡事故，8月2日の事故と知る
  :LOGBOOK:
  CLOCK: [2020-08-11 火 10:08]--[2020-08-11 火 13:51] =>  3:43
  :END:

:CATEGORIES: 死亡事故

〉〉〉：Emacs： 2020-08-11（火曜日）10：08　 〉〉〉

```
2020年8月2日の午前8時15分頃、神奈川県川崎市川崎区東扇島の首都高速道路・湾岸線西行き(横浜方面)となる東扇島入口の先にて、オレンジカラーとブラックのポルシェ911GT2RS(Porsche 911 GT2 RS)とトヨタbBが大破し、bBに乗っていた内山仁さん(70)と妻の美由紀さんの2人が死亡し、911GT2RSの助手席に乗っていたドライバーの息子が打撲、そして911GT2RSのドライバーが無傷という、とんでもない事故が発生しました。

［source：］これがもし本当なら酷い…首都高・湾岸線にてポルシェ911GT2RSでクラッシュし2名の命を奪った彦田嘉之 容疑者。相手車のドラレコを盗み証拠隠蔽との情報も【動画有】 | Creative Trend https://creative311.com/?p=97842
```

ポルシェ事故ドラレコ奪う - Google 検索 https://t.co/KDVNgH8DV0

　Firefoxで検索をしていたのですが，再捜査要請書＿警察庁・石川県警察御中（@kk_hirono）でログインしているGoogle Chromeで開き直そうと，いつものようにyyでURLを取得しようとしたところ，反応しませんでした。拡張でキーバインドをしているものです。

　Google ChromeでGoogleを開き，Firefoxの検索のコピペで，「ポルシェ　事故」と入れると，いくつかの入力補助に「ポルシェ事故ドラレコ奪う」というのが出てきました。

　その検索からリンクを開いたのが上記の引用の記事で，事故の発生時刻が午前8時15分と初めて知りました。昼前にはテレビのニュースになっていたと考えられますが，当日は何をしていたのかニュースをみた記憶はありません。全国ニュースではなかったのかもしれません。

　8月2日に撮影した写真を見ると，夜に千葉県のポツンと一軒家の放送があり，日曜日だったことがわかりました。この日はテレビを見る気になれず，少なくとも午前中から昼過ぎはテレビをつけることがなかったと思います。

【出しすぎちゃった…】首都高ポルシェ事故のドラレコ映像【閲覧注意】 - YouTube https://t.co/lWdHZAmzDr

　これまで同じ映像というか動画を何度か見ていると思うのですが，上記のYouTubeの動画をみて，トラックが右に車線変更していることがわかりました。そのドラレコがトラックに車載されたものということもちょっと前に情報を見かけ知ったところでした。

　いわれてみれば，ドラレコの撮影位置が高く，乗用車なら違っていると思ったのですが，他のことに気を取られていたためか深く考えることはなかったようです。

　ネットでは最初の方に，トラックの車線変更を批判する声があったらしくそれを不当とする意見を見かけていたのですが，そこで思い出していたのが東名高速あおり運転夫婦死亡事故のトラックの責任問題です。

　このYouTubeの動画も最初に見たときは気が付かなかったのですが，3車線で真ん中をドラレコ車載のトラックが走行していて，追い越し車線に進路変更したところ，追い越し車線にいたポルシェが真ん中の車線に入り，それまでトラックの後ろで見えなかったｄBに激突したようです。

　真ん中の車線を走行していたトラックもdBお追い越すのに，右のバックミラーで追い越し車線の確認はしたのだと思いますが，ポルシェの走行スピードが速すぎて目に入らなかったのかもしれません。

　私自身，一度だけ似たような経験をしているのですが，夜中に八王子から首都高速に入る手前の3車線で，後ろから来た乗用車が瞬間で抜き去っていきました。目にも止まらぬ速さとはこのことかと思ったのですが，抜かれたことに気がついたときは，かなり前方を走っていました。

　大型トラックの運転をしていた経験ですが，右の確認に時間をかけるのも危険です。前方と左手の状況の変化も注視を怠るわけにはいきません。乗用車なら少し視線を変えるだけで入る視界も，特にスピードが出ている場合，大型トラックだと左のバックミラーだけが頼りになります。

　今朝になってポルシェの事故を調べ直し，逮捕容疑が過失運転致死となっているのに違和感を覚えたのですが，トラックのドラレコの映像で，警察が危険運転致死傷罪に問うほどの悪質性はないと判断したのかと思いました。それでも尋常でないスピードなので，起訴は違ってくる可能性もありそうです。

　昨日は，このポルシェの事故で250キロという話も見たのですが，今日は150キロというものを見かけました。昭和の終わり頃の大型トラックでも140キロのメーターを振り切って走行することがありましたが，他の車を追い抜く時のスピードがまるっきり違っています。

三重　危険運転　弁護士 - Google 検索 https://t.co/7jtEp7729H

三重県よろずや:判決全文登載: 危険運転認めず,ベンツ5人死傷,懲役7年 - livedoor Blog（ブログ） https://t.co/mPqFhgoaR8

　やはり三重県の事故だったと確認したのですが，この刑事裁判もテレビニュースで見かけたものでした。検索の方法がよくないのか見つかる情報は乏しい感じです。

089558_hanrei.pdf https://t.co/qQY5XEF5a8

　PDFファイルになっている判決文を読み出したのですが，15ページで最後のページは裁判官一人の名前だけでした。正確に読み取れているのか自信がないですが，4人が死亡し，1人が加療期間不明とあるようです。主位的訴因を認定しなかった理由とあります。これが危険運転なのでしょう。

　時刻は11時34分です。判決文を読み終えました。被害車両はタクシーで運転手1名，乗客3名が死亡，乗客1名が瀕死の重傷とのことでした。判決文の一番始めに「令和2年6月16日宣告」とあります。この日付と宣告というのは初めて見たと思います。

　被告人の職業，生活態度，家族構成について，この判決文には一切言及がなかったように思います。犯人性を争うわけでもないという事情が，ほかの刑事裁判の被告人とは違うのかもしれないですが，ずいぶんプライバシーを尊重された気もして，どこのだれなのか全くわかりませんでした。

　よくみると，判決の主文に「訴訟費用は被告人の負担とする。」という珍しく感じるものを見たのですが，費用の具体的金額はなかったと思います。この刑事裁判の被告人の負担は，ネットでも具体的な金額の情報をみたことがなく，謎のベールに包まれた感があります。

被害者の母と婚約者怒り…146キロで走行し5人死傷した事故で被告に“過失運転”致死傷罪を適用（東海テレビ） - Yahoo!ニュース https://t.co/6i28PWFx4F

被害者の母と婚約者怒り…146キロで走行し5人死傷した事故で被告に“過失運転”致死傷罪を適用（東海テレビ） - Yahoo!ニュース https://t.co/kgpo92ydf4 検察側は被告が過去8回事故を起こしていたことを指… https://t.co/Jz319aKCcO

被害者の母と婚約者怒り…146キロで走行し5人死傷した事故で被告に“過失運転”致死傷罪を適用（東海テレビhttps://t.co/kgpo92ydf4 朗さんの母親: \n 「危険運転致死傷罪にしてもらって、最高の刑を与えてもらわんこと… https://t.co/XImAC7TpDk

　上記のページのアクセスランキング国内に，次の記事がありました。3ページに分かれているようですが，1ページ目を読み終えたところで，亀石倫子弁護士の顔写真があり，1ページにはまだ名前が出ていなかったと思います。

回し蹴りで虐待死、児童を2人突落とし……なぜ死刑にならないの？　3つの事件から見る裁判の仕組み（文春オンライン） - Yahoo!ニュース https://t.co/IZMhdEcX3m 亀石倫子さん　←写真

回し蹴りで虐待死、児童を2人突落とし……なぜ死刑にならないの？　3つの事件から見る裁判の仕組み（文春オンライン） - Yahoo!ニュース https://t.co/WfEgX62hXE text:Atsuko Komine

回し蹴りで虐待死、児童を2人突落とし……なぜ死刑にならないの？　3つの事件から見る裁判の仕組み（文春オンライン） - Yahoo!ニュース https://t.co/WfEgX62hXE 【ケース3】非常に悪質な殺人なのになぜ死刑… https://t.co/0isemz6rNg

　本文に亀石倫子弁護士の名前がなかったのですが，最後に「text:Atsuko Komine」とあったので，亀石倫子弁護士が執筆した記事らしいとわかりました。3件目の事件は，テレビの情報番組で見たことを思い出したのですが，すっかり忘れていましたし，裁判のことは知らなかったと思います。

```
35歳の女性が養女にした女性に保険金をかけ、知人男性と共謀して殺害、遺棄した。実行犯は知人男性で、女性は殺人を共謀した。殺人を共謀した者も実行犯と同様の重罪です。

　一審は裁判員裁判でした。最高裁まで争われ、被告人（当時）は一貫して無罪を主張し、実行犯の「殺人を依頼された」という供述の真偽が最大の争点でした。判決では殺人の共謀があったと認められ、求刑が23年でしたから量刑も重かったといえます。

　この女性は何度も姓を変えて詐欺を繰り返し、不審な死に方をした養父や母親にも保険金をかけていたことが報道されていました。そのため、懲役23年を軽いと見る人もいたでしょう。しかし、「日ごろから怪しげなことをしていた」「この人ならやりかねない」といった感情が量刑に影響を及ぼすことがあってはいけません。裁判ではあくまでも法廷に出された証拠のみで判断します。

　凶悪な犯罪、社会の関心が高い重大犯罪、死刑か無期懲役かを決める難しい裁判に一般市民が参加するようになって10年が経ちました。裁判員に選ばれていなくても、どうして死刑になったのか、どうして有期刑なのかという視点で事件を考えることは社会の一員として意味のある、とても大事なことだと思っています。

text：Atsuko Komine

［source：］回し蹴りで虐待死、児童を2人突落とし……なぜ死刑にならないの？　3つの事件から見る裁判の仕組み（文春オンライン） - Yahoo!ニュース https://news.yahoo.co.jp/articles/65164805114f696aed2ac9eb11c5803314a7bce3?page=3
```

　上記に引用を貼り付けるのに，もう一度記事に目を向けたところ，裁判員制度に向けた記事なのだと気が付きました。「8/11(火) 6:01配信」となっていて年がないですが，今朝の6時1分に配信された記事の可能性が高いです。

　朝に，亀石倫子弁護士と趙誠峰弁護士のTwitterアカウントは更新を確認したと思うのですが，どちらも更新は数日前で止まっていたと思います。文春オンラインとあるので，週刊文春の最新号で掲載されている可能性が高そうです。なぜこのタイミングなのかと考えます。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜sososakacity（ｓｏｓ大阪） 日時：2020-08-11 12:10／2020/05/18 17:51 URL： https://twitter.com/kk_hirono/status/1293022055592423425 https://twitter.com/sososakacity/status/1262304810872651778  

> こんなアホ議員が「維新」というだけでトップ当選して 辰巳孝太郎や亀石倫子が落選する大阪 在阪メディアと吉本の責任が大きいな https://t.co/BukvaoyB0P ＃梅村みずほ議員に抗議します  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜ChooselifePj（Choose Life Project） 日時：2020-08-11 12:11／2020/06/10 12:36 URL： https://twitter.com/kk_hirono/status/1293022109493604353 https://twitter.com/ChooselifePj/status/1270560354926395394  

> [告知] 本日10日17:00〜 #国会を止めるな💥立憲デモクラシーを守るために何をすべきか、何ができるのかを考えます。  [司会] 小島慶子 [出演] 山口二郎 / 長谷部恭男 / 石川健治 / 亀石倫子 / 望月衣塑子 [共催… https://t.co/fIRlnFee6y  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜reiwawakamono（れいわ新選組若者勝手連#消費税廃止） 日時：2020-08-11 12:11／2020/01/21 10:24 URL： https://twitter.com/kk_hirono/status/1293022139398856705 https://twitter.com/reiwawakamono/status/1219430622445228032  

> 山本太郎代表、23日かられいわの中国四国地方での遊説が始まりますが、26日は立憲民主党鹿児島県連の「立憲鹿児島フェス2020」に講師として参加されるそうです。亀石倫子弁護士も参加されるとのこと。↓ https://t.co/mOsS51sIHH  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜tomoshiokuda（奥田知志（NPO抱樸/牧師）） 日時：2020-08-11 12:11／2020/07/25 20:44 URL： https://twitter.com/kk_hirono/status/1293022217282842624 https://twitter.com/tomoshiokuda/status/1286990774312136704  

> 亀石「ヤクザの弁護もする。実はヤクザの中には経済的に困窮している人もいて、やめたいけど行き場がなくやめられない人が結構いる。ヤクザをいくら排除しても半グレなど違うところにいくだけ。更生の道を示さなければ」 亀石倫子（弁護士）× 奥… https://t.co/Uhvp3WvTO7  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜aokiaoki1111（青木美希） 日時：2020-08-11 12:11／2020/05/12 17:07 URL： https://twitter.com/kk_hirono/status/1293022239718137856 https://twitter.com/aokiaoki1111/status/1260119422150144000  

> 本日午後９時から 《緊急開催決定‼》強行採決間近…… #検察庁法改正案に抗議します　 【出演】山添拓、原口一博（国民民主党）、亀石倫子（弁護士）、落合洋司（弁護士）、望月衣塑子、青木理（22:00頃から15～30分程出演） 進行は… https://t.co/xyz2Al7Hjy  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜yuji_masataka（正高佑志   医療大麻のお医者さん） 日時：2020-08-11 12:12／2020/02/25 13:28 URL： https://twitter.com/kk_hirono/status/1293022327496560640 https://twitter.com/yuji_masataka/status/1232160396062019585  

> 弁護士の亀石倫子先生と意見交換。  写真撮ったら婚活サイトの広告みたいになりました。 https://t.co/t5SRf2ihmP  

(1) 亀石倫子 - Twitter検索 / Twitter https://t.co/P5hLfORaS7

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜MichikoKameishi（弁護士 亀石倫子） 日時：2020-08-11 12:12／2020/08/01 09:31 URL： https://twitter.com/kk_hirono/status/1293022524645638145 https://twitter.com/MichikoKameishi/status/1289357944614576128  

> 高野隆弁護士が懲戒請求されたことについて、懲戒請求者の氏名を公表したうえで、その懲戒請求書と反論文を自身のブログに掲載したことについて、懲戒請求者から損害賠償等を求められている事件における、被告高野隆氏の意見陳述https://t.co/DWtZm2xvNc  

　亀石倫子弁護士本人のツイートは，8月1日に止まっていますが，そのあとに3件のリツイートがあります。

```
(py37_env) a66@a66-XTe:/mnt/ubuntu/sql$ tu MichikoKameishi 3
RT MichikoKameishi（弁護士 亀石倫子）｜ChooselifePj（Choose Life Project） 日時：2020-08-08 20:22／2020-08-08 12:04 URL： https://twitter.com/MichikoKameishi/status/1292058612450254849 https://twitter.com/ChooselifePj/status/1291933339100700672
> [告知]8月12日20時から配信📽コロナ禍の、せめてもの抵抗。映画「8日で死んだ怪獣の12日の物語」「ソワレ」から考える、いま「映画」をつくるわたしたちの願いと自由とは。 #コロナ禍の映画  \n  \n [出演]岩井俊二@sindyeye… https://t.co/dABJle1xfa

TW MichikoKameishi（弁護士 亀石倫子） 日時： 2020-08-07 21:55 URL： https://twitter.com/MichikoKameishi/status/1291719706446045184
> @peace77mk ありがとうございます！

RT MichikoKameishi（弁護士 亀石倫子）｜kamba_ryosuke（神庭亮介） 日時：2020-08-04 20:58／2020-08-04 20:36 URL： https://twitter.com/MichikoKameishi/status/1290618081186680832 https://twitter.com/kamba_ryosuke/status/1290612459863080963
> 「だまされないように。買うだけ無駄です。新型コロナウイルス感染に有効であるという証明はまだされていません」 \n  \n 甲状腺機能の異常といった副作用の指摘も。 \n  \n 「イソジンなどのうがい薬でコロナ感染予防」は本当？ 大阪府が発表→医療者らか… https://t.co/6qZ9jkUVxM
```

　亀石倫子弁護士のTwitterアカウントのタイムラインでは，3件目が郷原信郎弁護士のツイートのリツイートとなっていたのですが，TwitterAPIで取得したツイートは違っているようです。

RT MichikoKameishi（弁護士 亀石倫子）｜nobuogohara（郷原信郎【「深層」カルロス・ゴーンとの対話　起訴されれば９９％超が有罪となる国で】） 日時：2020-08-04 07:13／2020-08-04 06:31 URL： https://twitter.com/MichikoKameishi/status/1290410522140012546 https://twitter.com/nobuogohara/status/1290400014955552768
> 【アナザーストーリーズ「わたしはやっていない　村木厚子　無罪までの４５４日」】 \n https://t.co/EIk8MJWKfB \n 本日（８月４日）21:00～、NHKBSプレミアムで放映されます。私もロングインタビューに応じ、これま… https://t.co/Yycm3aKt2A

　原因がわかりました。開いていたタイムラインが「ツイート」で，「ツイートと返信」ではなかったので，返信のツイートが1件表示されておらず，それで4件目の郷原信郎弁護士のツイートを3件目と数えてしまいました。

　時刻は13時50分です。Windows10の一太郎で告発状の作成の続きをするつもりでいたのですが，また深澤諭史弁護士のタイムラインで気になるツイートを見かけてしまい，いろいろと迷っています。

〈〈〈：Emacs： 2020-08-11（火曜日）13：51 　〈〈〈

