* 「「この政権、とんでもないところに手を出してきた」　学術会議任命見送られた松宮教授｜政治｜地域のニュース｜京都新聞」という記事から調べた深澤諭史弁護士と共謀罪

- 987：2020-10-02_15:28:27 ＊＊ 《参考資料》「「この政権、とんでもないところに手を出してきた」　学術会議任命見送られた松宮教授｜政治｜地域のニュース｜京都新聞
」という記事 https://hirono-hideki.hatenadiary.jp/entry/2020/10/02/152825

** 《参考資料》深澤諭史弁護士と共謀罪

:CATEGORIES: 深澤諭史弁護士,共謀罪

　深澤諭史弁護士のTwitterのタイムラインで共謀罪というワードは余り見た憶えがなかったのですが，調べてみるといくつかありました。そのあとでデータベースのまとめ記事を作成したのですが，そちらの方がだいぶん多い数でした。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-03 10:31／2020/10/02 13:51 URL： https://twitter.com/kk_hirono/status/1312203589406785536 https://twitter.com/s_hirono/status/1311891561681018882  

> 2020-10-02-134513_”共謀罪”　（from：fukazawas）　-　Twitter検索　／　Twitter.jpg https://t.co/eJd4ziuVSc  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-03 10:31／2020/10/02 13:51 URL： https://twitter.com/kk_hirono/status/1312203601998041092 https://twitter.com/s_hirono/status/1311891634175406086  

> 2020-10-02-134522_”共謀罪”　（from：fukazawas）　-　Twitter検索　／　Twitter.jpg https://t.co/Ah77QFhCKI  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-03 10:31／2020/10/02 13:52 URL： https://twitter.com/kk_hirono/status/1312203618221608961 https://twitter.com/s_hirono/status/1311891706879463424  

> 2020-10-02-134530_”共謀罪”　（from：fukazawas）　-　Twitter検索　／　Twitter.jpg https://t.co/SYl24qYr9H  

　ざっと数えて9件のツイートだったと思います。まとめ記事の方は100件を越えていたように思いますが，まだページを開いていないので内容は未確認です。一定数のリツイートが含まれているものと考えられますが，ツイートの数も50件はありそうだと予想します。

 - 2020年10月02日13時44分の登録： REGEXP：”共謀罪”／深澤諭史（@fukazawas）の検索（2015-11-19〜2019-07-22／2020年10月02日13時44分の記録117件） http://kk2020-09.blogspot.com/2020/10/regexpfukazawas2015-11-192019-07.html

　数え違いがあるかもしれないですが，確かにツイートは9件でした。その他108件がリツイートということになります。確かにリツイートが多いという印象でした。

　9件の共謀罪を含む深澤諭史弁護士のツイートで，とりわけ目立ったものはないのですが，やや地味めでありながら，政治不信，政権不信を煽るような匂いが次のツイートからはたちこめているように感じました。

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2017/01/06 15:16 URL： https://twitter.com/fukazawas/status/817253566326808576  

> 共謀罪「一般人は対象外」＝菅官房長官（時事通信） - Yahoo!ニュース https://t.co/QKo3Iuz2Oo #Yahooニュース  
>   
> 相変わらず，自分たちの支持者のインテリジェンスをよくよく理解していますね（褒め言葉）  

　今，貼り付けをして気がついたのですが，深澤諭史弁護士のツイートで取り上げた記事の見出しには，菅官房長官とあります。より直接的な深澤諭史弁護士の表現には，「肉屋を支持する豚」というのがありました。

** 《参考資料》「肉屋を支持する豚」という深澤諭史弁護士のツイート

:CATEGORIES: 深澤諭史弁護士

```
(py37_env) ➜  ~ dp -p|grep 肉屋
 - 2018年04月12日12時20分の登録： ＼深澤諭史　@fukazawas＼雇用者でもないのに，残業代ゼロ法案支持するって，まるで「肉屋を支持する豚」じゃないか・・。 （；；；・∀・） http://hirono2014sk.blogspot.com/2018/04/fukazawas_41.html
 - 2018年06月17日09時07分の登録： REGEXP：”肉屋を支持する豚”／データベース登録済みツイート：2018年06月17日09時07分の記録：ユーザ・投稿：19／33件 http://hirono2014sk.blogspot.com/2018/06/regexp2018061709071933.html
 - 2019年06月03日09時31分の登録： REGEXP：”豚に支持される肉屋の店長”／データベース登録済みツイート：2019年06月03日09時31分の記録：ユーザ・投稿：7／8件 http://hirono2014sk.blogspot.com/2019/06/regexp20190603093178.html
 - 2019年06月26日07時58分の登録： @fukazawas（深澤諭史）のツイート　”肉屋”　2／3236：2019-05-03　16：02〜2019-06-25　23：10　2019年06月26日07時58分の記録 http://hirono2014sk.blogspot.com/2019/06/fukazawas232362019-05-0316022019-06.html
 - 2019年08月11日15時17分の登録： REGEXP：”肉屋”／深澤諭史（@fukazawas）の検索（2016-03-04〜2019-06-03／2019年08月11日15時16分の記録14件） http://hirono2014sk.blogspot.com/2019/08/regexpfukazawas2016-03-042019-06.html
 - 2019年11月16日12時03分の登録： REGEXP：”肉屋”／深澤諭史（@fukazawas）の検索（2016-03-04〜2019-06-03／2019年11月16日12時03分の記録14件） http://hirono2014sk.blogspot.com/2019/11/regexpfukazawas2016-03-042019-06.html
 - 2020年04月18日11時45分の登録： ＼仙猫カリン　@Bibendum65＼安倍信者の自民党議員\n自分たちが他宗教の信徒より軽んじられてることに（ようやく）気づきオコである\n\n自分は肉屋ではなく豚だったことに http://hirono2014sk.blogspot.com/2020/04/bibendum65_18.html
 - 2020年05月10日00時25分の登録： REGEXP：”肉屋”／深澤諭史（@fukazawas）の検索（2016-03-04〜2019-06-03／2020年05月10日00時24分の記録14件） http://hirono2014sk.blogspot.com/2020/05/regexpfukazawas2016-03-042019-06.html
 - 2020年06月20日14時45分の登録： ＼深澤諭史　@fukazawas＼（；・∀・）「肉屋を支持する豚」の問題と言うより，豚から支持される肉屋の有能さが際立つ件。 （；＾ω＾）逆に豚の愛護団体は，豚からそっぽ http://hirono2014sk.blogspot.com/2020/06/fukazawas_84.html
 - 2020年07月24日21時48分の登録： REGEXP：”肉屋”／深澤諭史（@fukazawas）の検索（2016-03-04〜2020-06-20／2020年07月24日21時48分の記録15件） http://hirono2014sk.blogspot.com/2020/07/regexpfukazawas2016-03-042020-06.html
 - 2020年08月14日21時13分の登録： REGEXP：”肉屋”／深澤諭史（@fukazawas）の検索（2016-03-04〜2020-06-20／2020年08月14日21時13分の記録15件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2016-03-042020-06.html
 - 2020年08月28日21時27分の登録： REGEXP：”肉屋．＊支持”／深澤諭史（@fukazawas）の検索（2016-07-08〜2020-06-20／2020年08月28日21時27分の記録10件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2016-07-082020-06.html
(py37_env) ➜  ~ 
```

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hifik（ほらっちょMonkey） 日時：2020-10-03 10:53／2016/07/07 07:55 URL： https://twitter.com/kk_hirono/status/1312209234881175552 https://twitter.com/hifik/status/750825565502906368  

> 日本人は本当に「肉屋を支持する豚」が多いんだな…  

　時系列の並びでリツイートが先に出てきたようです。深澤諭史弁護士の独自の造語の一つかと思っていたのですが，これは違っていたようです。全体としてのまとめ記事も作成しておきたいと思います。

 - 2020年10月03日11時03分の登録： REGEXP：”肉屋を支持する豚”／データベース登録済みツイート：2020年10月03日11時02分の記録：ユーザ・投稿：24／55件 http://kk2020-09.blogspot.com/2020/10/regexp2020100311022455.html

　よく見かけたという記憶だったのですが，意外に深澤諭史弁護士本人のツイートで「肉屋を支持する豚」というのは数が少なかったようです。

 - （09／15） TW fukazawas（深澤諭史） 日時：2018-04-12 11:31:00 +0900 URL： https://twitter.com/fukazawas/status/984257634332102657

> 雇用者でもないのに，残業代ゼロ法案支持するって，まるで「肉屋を支持する豚」じゃないか・・。 （；；；・∀・）

 - （11／15） TW fukazawas（深澤諭史） 日時：2018-08-07 10:12:00 +0900 URL： https://twitter.com/fukazawas/status/1026637088274309120

> ＞ＲＴ
> ほんこれ。
> 「肉屋を支持する豚」なんて揶揄されるけれども。なぜ，どうしてか，よく考える必要がある問題だと思います。
> （・∀・；）

 - 非常上告-最高検察庁御中_ツイッター(@s_hirono)/「ほんこれ。」の検索結果 - Twilog https://twilog.org/s_hirono/search?word=%E3%81%BB%E3%82%93%E3%81%93%E3%82%8C%E3%80%82&ao=a  

 - 非常上告-最高検察庁御中_ツイッター(@s_hirono)/2018年08月07日 - Twilog https://twilog.org/s_hirono/date-180807  

- TW s_hirono（非常上告-最高検察庁御中_ツイッター） 日時： 2018/08/07 00:10 URL： https://twitter.com/s_hirono/status/1026485608661757952  

> 2017-10-02-181205_モトケン　　＞　ど素人が安田弁護士を批判するのはまあ仕方がないとして、マスコミはもうちっと刑事弁護を勉強したほうがいいんでないかな。.jpg https://t.co/7SYditWTlz  

- TW s_hirono（非常上告-最高検察庁御中_ツイッター） 日時： 2018/08/07 00:10 URL： https://twitter.com/s_hirono/status/1026485577376382976  

> 2017-10-02-151444_モトケン　＞　返信先：@takeshi_kine　＞　弁護士家業というのはね、依頼者が直視したくない現実を直視させた上で現実的かつ最善の解決.jpg https://t.co/KAwfB9xqX3  

- TW s_hirono（非常上告-最高検察庁御中_ツイッター） 日時： 2018/08/07 00:09 URL： https://twitter.com/s_hirono/status/1026485545700974592  

> 2017-10-02-151339_サイ太　＞　認知機能が不十分な高齢者・障害者の相談って，そもそもの聴取自体が極めて困難だったりするんだけど（そして扶助案件ではそういう事案に.jpg https://t.co/a8fzN8I43F  

- TW s_hirono（非常上告-最高検察庁御中_ツイッター） 日時： 2018/08/07 00:09 URL： https://twitter.com/s_hirono/status/1026485480743825408  

> 2017-10-01-040458_弁護士　浜ちゃん　＞　１期日の出頭で７桁（最初の数字は１ではない）の日当をとっていた県外の先生の話を聞いたことがある者.jpg https://t.co/HaM3jrzMdq  

- TW s_hirono（非常上告-最高検察庁御中_ツイッター） 日時： 2018/08/07 00:09 URL： https://twitter.com/s_hirono/status/1026485449643061253  

> 2017-10-01-035810_弁護士　野田隼人　　＞　返信先：@luckymangan　＞　ヤメ検を中心に数十人把握。.jpg https://t.co/9Lb3J8LMwK  

- TW s_hirono（非常上告-最高検察庁御中_ツイッター） 日時： 2018/08/07 00:09 URL： https://twitter.com/s_hirono/status/1026485317468020736  

> 2017-10-01-031852_弁護士　浜ちゃんさんがリツイート　　＞　サイ太　＞　Twitterが凍結祭りだけど、未だに非常上告が凍結されないんですが.jpg https://t.co/tEXfuKE98U  

- TW s_hirono（非常上告-最高検察庁御中_ツイッター） 日時： 2018/08/07 00:08 URL： https://twitter.com/s_hirono/status/1026485254448590848  

> 2017-10-01-023005_とらきち　＞　離島に午前午後がっつり１０人くらい尋問したって７桁はすごすぎる…某A事務所も出張日当高かったけどそれと一桁違う.jpg https://t.co/Gch4dvpcsk  

　深澤諭史弁護士の「ほんこれ」の指すツイート（たぶんリツイート）を探していたのですが，スクリーンショットの映り込みも発見できませんでした。しかし，この2018年8月7日というのは色々とあったようで，思い出したことや，つい最近の発見もありますが，上記に列挙しました。

 - 2018年08月08日02時33分の登録： ツイートの記録資料：＼法務検察・石川県警察宛＼／深澤諭史（@fukazawas）／”2018年08月07日”：96件 http://hirono2014sk.blogspot.com/2018/08/fukazawas2018080796.html

▶（21／96） RT fukazawas（深澤諭史）｜un_co_the2nd（うの字） 日時：2018-08-07 10:11:00 +0900／2018-08-07 10:08:00 +0900 URL： <https://twitter.com/fukazawas/status/1026636958326374400> <https://twitter.com/un_co_the2nd/status/1026636273329393664>
{% tweet 1026636958326374400 %}
> 大阪市の公立校に入れたら子供の人生がそこで詰みかねない…教員を生徒の点数で競わせるとロクなことにならないってこれまでも事例いっぱい出てるんだが。 \n でも、「競争原理」「自己責任」の掛け声って、とある層にはひびくんだよなぁ…。どういうわけか、それで一番被害を被る層に…

▶（22／96） TW fukazawas（深澤諭史） 日時：2018-08-07 10:12:00 +0900 URL： <https://twitter.com/fukazawas/status/1026637088274309120>
{% tweet 1026637088274309120 %}
> ＞ＲＴ \n ほんこれ。 \n 「肉屋を支持する豚」なんて揶揄されるけれども。なぜ，どうしてか，よく考える必要がある問題だと思います。 \n （・∀・；）

　深澤諭史弁護士が「ほんこれ」で指し示したのは，「「競争原理」「自己責任」の掛け声って、とある層にはひびくんだよなぁ…。どういうわけか、それで一番被害を被る層に…」などといううの字のツイートだったようです。

@un_co_the2nd ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@un_co_the2nd）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW un_co_the2nd（うのじ） 日時：2018/08/07 10:08 URL： https://twitter.com/un_co_the2nd/status/1026636273329393664?ref 

> 大阪市の公立校に入れたら子供の人生がそこで詰みかねない…教員を生徒の点数で競わせるとロクなことにならないってこれまでも事例いっぱい出てるんだが。  
> でも、「競争原理」「自己責任」の掛け声って、とある層にはひびくんだよなぁ…。どういうわけか、それで一番被害を被る層に…  

　うの字のツイートのリツイートの前が，深澤諭史弁護士本人の過去のツイートのリツイートとなっていますが，似たような話でロースクール（法科大学院）のバージョンとなっているようです。リツイートのツイートには深澤諭史弁護士本人の別のツイートも公式引用されています。

▶（20／96） RT fukazawas（深澤諭史）｜fukazawas（深澤諭史） 日時：2018-08-07 10:11:00 +0900／2018-08-05 16:11:00 +0900 URL： <https://twitter.com/fukazawas/status/1026636863308685312> <https://twitter.com/fukazawas/status/1026002640864337920>
{% tweet 1026636863308685312 %}
> いいか、ロー関係者の法科大学院制度への思い…。それを真に理解しないと何も始まらないんだぜ。 \n 『理解していますよ！素晴らしい司法改革の理念、それへの気持ちが強すぎて、若手法曹の意見や、他のやり方を受け容れる柔軟性を失ってるんでしょう… https://t.co/p4D28hzPYI

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2018/08/05 16:11 URL： https://twitter.com/fukazawas/status/1026002640864337920  

> いいか、ロー関係者の法科大学院制度への思い…。それを真に理解しないと何も始まらないんだぜ。  
> 『理解していますよ！素晴らしい司法改革の理念、それへの気持ちが強すぎて、若手法曹の意見や、他のやり方を受け容れる柔軟性を失ってるんでしょう！』  
> …。  
> 『違うっていうんですか‥？』  
> #司法発見伝 https://t.co/y5hHFkxZyN  

- TW fukazawas（深澤諭史） 日時： 2018/08/05 16:02 URL： https://twitter.com/fukazawas/status/1026000529963409408  

> で、お前は法科大学院と、その制度の改善にどういう対策を？  
> 『受験生や現役法曹の意見を取り入れて、何が求められているかを把握して貰って意識改革を促そうと思っています。更に実務にも受験にも役に立つカリキュラムの導入を…。』  
> ハハッ、まるで話にならんな。大丈夫か？オマエ。  
> #司法発見伝  

　そういえば，深澤諭史弁護士のプロフィールには経歴に，東京大学法科大学院を卒業した後，司法試験に合格し弁護士になったと書いてあったと思いますが，深澤諭史弁護士が東京大学法科大学院について言及したツイートは見たことがないように思えてきました。

"東京大学法科大学院" (from：fukazawas) - Twitter検索 / Twitter https://twitter.com/search?lang=ja&q=%22%E6%9D%B1%E4%BA%AC%E5%A4%A7%E5%AD%A6%E6%B3%95%E7%A7%91%E5%A4%A7%E5%AD%A6%E9%99%A2%22%20(from%3Afukazawas)&src=typed_query

　調べてみると2件のツイートがありました。2013年と2017年です。

- TW fukazawas（深澤諭史） 日時： 2013/09/22 08:30 URL： https://twitter.com/fukazawas/status/381561056939634688  

> お、ついに紙媒体が。関係者乙です(･∀･)　"@hounavi_books: 【新刊】 東京大学法科大学院ローレビュー Vol.8 / 編集：東京大学法科大学院ローレビュー編集委員会［ 商 ... http://t.co/DcRmRvDZf2 (amazon)"  

- TW fukazawas（深澤諭史） 日時： 2017/01/31 12:51 URL： https://twitter.com/fukazawas/status/826276685146312704  

> 東京大学法科大学院ローレビュー大9巻  
> 弁護士の民事訴訟におけるパフォーマンス評価： 法曹の質の実証的研究（太田勝造）  
> 「過払金請求などの簡単すぎたり」  
> ふーん、簡単だったんですね。。。  
> (･∀･)  

** 弁護士家業と弁護士稼業から弁護士列車と弁護士鉄道

:CATEGORIES: 深澤諭史弁護士,モトケンこと矢部善朗弁護士（京都弁護士会）

```
> 2017-10-02-151444_モトケン　＞　返信先：@takeshi_kine　＞　弁護士家業というのはね、依頼者が直視したくない現実を直視させた上で現実的かつ最善の解決.jpg https：//t.co/KAwfB9xqX3


［source：］＊＊ 《参考資料》「肉屋を支持する豚」という深澤諭史弁護士のツイート - 告発＼金沢地方検察庁＼最高検察庁＼法務省＼石川県警察御中2020 https://hirono-hideki.hatenadiary.jp/entry/2020/10/03/115203
```

　前回投稿分での発見になります。家業を発見したのは上記の引用部分です。家業を継ぐという言葉はみかけますが，弁護士家業というのは珍しく感じました。なになにかぎょうといえば，弁護士稼業ではと思ったからです。しかし，調べてみると他に家業を使う弁護士がいたようです。

 - 2020年10月03日11時58分の登録： REGEXP：”家業”／データベース登録済みツイート：2020年10月03日11時58分の記録：ユーザ・投稿：11／15件 http://kk2020-09.blogspot.com/2020/10/regexp2020100311581115.html

 - 2020年10月03日12時00分の登録： REGEXP：”稼業”／データベース登録済みツイート：2020年10月03日11時59分の記録：ユーザ・投稿：27／47件 http://kk2020-09.blogspot.com/2020/10/regexp2020100311592747.html

 - （01／15） TW Hideo_Ogura（小倉秀夫） 日時： 2012-08-24 03:00:00 +0900 URL： https://twitter.com/Hideo_Ogura/status/238697194172080129

> 相手を一方的に断罪できる地位を手に入れて神様気分の匿名家業。

　これは見覚えのない小倉秀夫弁護士のツイートですが，2012年8月24日のツイートです。それも午前3時の投稿時刻が表示されたものです。内容もなんですが，草木も眠る丑三つ時，牛の刻詣りというのを思い出しました。

```
小倉秀夫
@Hideo_Ogura
弁護士、明治大学法学部兼任講師、ペギっ子、SCANDAL MANIA
Katsushika Tokyo Japanben.li/text_pr/Profil…2008年10月からTwitterを利用しています
73 フォロー中
1.3万 フォロワー

［source：］小倉秀夫（@Hideo_Ogura）さんの返信があるツイート / Twitter https://twitter.com/Hideo_Ogura/with_replies
```

　ちょっと意外に感じたのですが，ロックされたまま更新のない小倉秀夫弁護士のTwitterアカウントのプロフィールに，明治大学法学部兼任講師とありました。更新がないのかちょくちょくと開いていたのですが，プロフィールに変更があったとは考え難く，今気がついたのも不思議です。

　小倉秀夫弁護士本人のツイートは2019年6月8日で止まっていますた，そのあとに2件ほどリツイートがあって，NHKのチコちゃんがアイコンになっていたように思うのですが，そのリツイートが消えて，ローカスこと三浦義隆弁護士のツイートが最上位になっていました。

　前にも同じ現象をみて，そのときは小倉秀夫弁護士のタイムラインに更新があったのかと早とちりをしたのですが，どうもリツイートしたツイートのアカウントが凍結されたらしく，しばらくして凍結の解除後に同じように表示されていました。

　小倉秀夫弁護士がリツイートをしたローカスこと三浦義隆弁護士のツイートが最上位でとても目立つかたちとなったのですが，ツイートの内容を読んでみると，これも新規の発見のような資料性の高いものです。

@lawkus ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@lawkus）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW lawkus（ystk） 日時：2019/06/07 21:37 URL： https://twitter.com/lawkus/status/1136975415564574720  

> 【お知らせ】  
> 「近頃は微物検査があるから痴漢冤罪は起こり得ない」とのツイートが一部出回っていますが、完全に嘘です。  
> 「微物検査した上で何も出なかったけど有罪」という判決は最近も普通に出てますし。  
> こんなデタラメを真に受けて確かめもせず拡散した人々は己の愚かさを心から恥じてほしい。  

　弁護士家業の個性を強く感じるのもローカスこと三浦義隆弁護士の際立つ特徴ですが，こんなかたちで出てくるとは想像もしていませんでした。とても広告性の高いツイートだと思います。広告といえば，さきほど深澤諭史弁護士のタイムラインでも見かけたものがあります。

- TW fukazawas（深澤諭史） 日時： 2020/10/03 10:13 URL： https://twitter.com/fukazawas/status/1312199144224681984  

> よーし！！！できた！！全部で１６９枚！！！！｜深澤諭史 @fukazawas #note https://t.co/N01YH4eDl4  

　ツイートにあるリンクは深澤諭史弁護士のnoteのつぶやきで，バーナー広告のような画像が貼り付けてあって，「効果的な弁護士広告のための心得」，続いて副題のようなもので「基本的概念，ルールから，コンテンツ作成のコツ　業者選定，そして問い合わせ対応まで」とあります。

　このあと別に取り上げる予定ですが，今朝は，たぶん昨夜放送のあったAbemaPrimeで，深澤諭史弁護士のリモート出演を視聴しました。他にも深澤諭史弁護士がリツイートをした弁護士ドットコムの記事でストーカーに関する記事を１つ読んでいます。

 - （05／15） TW motoken_tw（モトケン） 日時： 2017-10-02 14:43:00 +0900 URL： https://twitter.com/motoken_tw/status/914727468363165696

> @takeshi_kine 弁護士家業というのはね、依頼者が直視したくない現実を直視させた上で現実的かつ最善の解決を模索する仕事なんだよ。情緒に流されて黙ってたのでは依頼者の利益を守れない。感情論で同情した気になっているあなたこそ黙ってろ。

　モトケンこと矢部善朗弁護士（京都弁護士会）のブログで，最初に気になったのが，このモトケンこと矢部善朗弁護士（京都弁護士会）の発言としての「感情論」でした。モトケンこと矢部善朗弁護士（京都弁護士会）の独自の世界観と価値観を象徴する「感情論」です。

　どうもモトケンこと矢部善朗弁護士（京都弁護士会）返信したツイートに，「弁護士稼業に専念していろ。」という言葉があったようです。余り見覚えのないアカウントですが，括弧書きでモトケンとあります。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜takeshi_kine（木根渕猛[モトケン]） 日時：2020-10-03 12:45／2017/10/02 14:38 URL： https://twitter.com/kk_hirono/status/1312237237766033410 https://twitter.com/takeshi_kine/status/914726294000082944  

> @motoken_tw 現実には、家族の帰国を切望する年老いた肉親が日本に多数居るということを考えろ！という事ですよ。残念ながら、拉致被害者問題は現状のままでしょう。利口ぶる態度が気に食わない。黙って、弁護士稼業に専念していろ。  

　アカウントのプロフィールをみると，数年前に見覚えがありました。記憶に少しあるのは終わりの方の「現在釣り漁師居酒屋親父」ですが，「免疫学研究者、実験書分担執筆多数。大学・製薬会社研究員、バイオ専門学校講師を経て独立し研究所設立」などから始まっています。

　プロフィールにあるリンクのホームページを開くと「カヤック漁師居酒屋」と出てきました。佐渡ヶ島かと思ったのですが，どうも新潟市内のようです。釣り場で一緒になった新潟市出身の人に話を聞いたのですが，新潟市内の近辺の海は砂浜ばかりという話でした。大きな堤防は別にあるようですが。

　モトケンというのは，モトケンこと矢部善朗弁護士（京都弁護士会）の元検事ではなく，元研究者や元研究員という意味なのかもしれません。

 - （04／47） TW hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時： 2015-01-20 10:58:00 +0900 URL： https://twitter.com/hirono_hideki/status/557356350003765248

> 屋台弁護士 - Wikipedia http://t.co/NMTYazP6xu ←これがありなら、「泥棒神社の弁護士稼業」というタイトルのドラマがあってもよさそう。

　屋台弁護士というのは記憶にありませんでした。子供の頃，辺田の浜のキリコ祭りのとき，神目神社の下にキリコが止まり，その横に夜店が一つあったことを憶えています。子供向けのこまかい玩具を販売していたと憶えていますが，当時はそれだけ子供の数も多かったことになります。

　店の人の顔などは記憶にないですが，その雰囲気は強く印象に残っていて，地方を渡り歩く，さすらいの稼業という感じでした。夜店と言っても，夜には畳んでいなくなっていたように思います。お祭りの屋台のことを皆，夜店と呼んでいたように思います。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-10-03 13:09／2015/01/20 10:52 URL： https://twitter.com/kk_hirono/status/1312243237466193920 https://twitter.com/hirono_hideki/status/557355022183583744  

> お湯を沸かしながら珍しく午前中に新聞のテレビ欄を眺めていたら。14時頃から「屋台弁護士」というのがあった。再とあり、最近は余り見かけない俳優が主人公になっていたので、けっこう古いドラマかと思われる。気になるタイトル。屋台といえばまず福岡の博多を思い出す。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-10-03 13:09／2015/01/20 10:55 URL： https://twitter.com/kk_hirono/status/1312243463459491841 https://twitter.com/hirono_hideki/status/557355648766451712  

> 屋台弁護士 - Wikipedia http://t.co/A08DqjZkZP 2005年から2009年まで放送されたテレビドラマシリーズ。全3回。主演は中村雅俊。←　こんなドラマのタイトル見たのも今日が初めて。お祭り弁護士、というのは見ている。  

　お祭り弁護士は，1作か2作みていますが，思い出すのは1作だけで，徳島の阿波踊りと青森のねぶた祭が舞台になっていたと思います。徳島と青森に結びつきがあったはずですが思い出せません。今思えば，昭和の時代の映画，トラック野郎シリーズのような雰囲気がありました。

 - （06／47） TW lawkus（ystk） 日時： 2016-12-08 05:09:00 +0900 URL： https://twitter.com/lawkus/status/806591485147684864

> いくら金積まれても違法不当な弁護活動はしないという姿勢を保ち続けるためにも、ある程度金を稼ぎ続けることは大事。ダークサイドに落ちるのは簡単な稼業だけに。

 - （07／47） RT fukazawas（深澤諭史）｜lawkus（ystk） 日時：2016-12-08 09:43:00 +0900／2016-12-08 05:09:00 +0900 URL： https://twitter.com/fukazawas/status/806660346547032064 https://twitter.com/lawkus/status/806591485147684864

> いくら金積まれても違法不当な弁護活動はしないという姿勢を保ち続けるためにも、ある程度金を稼ぎ続けることは大事。ダークサイドに落ちるのは簡単な稼業だけに。

　最近，秋田県湯沢市出身の菅さんが首相になり，就職列車のテレビ報道もあったことから，ときどき「あゝ上野駅」のメロディが頭に浮かぶのですが，決まって歌詞のところどころが弁護士に置き換わります。「弁護士列車に揺られて揺れて」，「（弁護士の名前）の心の駅だ。」ってな感じです。

　「（弁護士の名前）の思いを乗せて」というのもありました。元のあゝ上野駅の歌詞は，記憶のままですが，「どこかに故郷のかおりを乗せて」だったと思います。サラリーマンの町として今でもちょこちょこテレビで見かけるのが新橋駅ですが，深澤諭史弁護士の事務所に近いようです。

　深澤諭史弁護士の法律事務所は建物の名前が，弁護士ビル2号館となっていて，1号館もあるのかと調べたところ情報が見当たりませんでした。コスモポリタンと聞いたような気もするのですが，銀河鉄道999のアニメで出てくる都市と，深澤諭史弁護士が弁護士稼業にかける情熱も重なります。

コスモポリタン - Google 検索 https://t.co/rsc0o5eMGG

　検索結果の1ページ目をみたところ，銀河鉄道999のことは出てきませんでした。なぜかコスモポリタンとして記録にあります。

銀河鉄道　コスモポリタン - Google 検索 https://t.co/y2G7wqo1Ee

夢のEF58牽引銀河鉄道999号｜旅せよコスモポリタン★レールウェイレビュー https://t.co/qmn6NLU1QA

　アニメの銀河鉄道999ではなく，大井川鉄道のことが写真付きで出てきました。コスモポリタンも記事ではなく，ブログのタイトルの一部となっていることに，記事に目を通してから気が付きました。

銀河鉄道999 (アニメ) - Wikipedia https://t.co/06jjYtQJ0P

　上記のページでページ内検索をしたのですが，「コスモ」でも該当は０でした。銀河鉄道999は，YouTubeで視聴したものもありますが，鉄郎の母親が狩猟のターゲットとして殺され，メーテルと出会った旅の出発の場所が，星の都市の名前としてコスモポリタンだと思っていました。

　銀河鉄道999は機械の体を手に入れるための宇宙の旅のパスポートだったと思っていますが，これが弁護士資格で稼ぎまくるという弁護士一代の稼業にそのまま重なります。弁護士鉄道によって狂わされた人生を数々みてきた現実の事実，物語との重なりもあります。

　コスモポリタンというのは，世界人や国際人という意味があると知りました。ポリタンというのは人類のことのように聞いた憶えがあるので，コスモが世界を意味するのかと考えます。宇宙というイメージがコスモにはあったのですが，調べることもなかったと思います。

コスモ - Wikipedia https://t.co/dzJXLwSNZt コスモ (ラテン語: cosmo)。英語ではコズモ、形容詞はコズミック (cosmic)。 \n  \n 宇宙を意味するラテン語接頭辞。

　やはりこれまでのイメージ通り，コスモは宇宙を意味する言葉でした。そういえば最近，テレビでコスモ石油のCMをみていないような気がしました。違った石油会社のCMかもしれないですが，「心も満タンに」というのもありました。

　いろいろとみていると，弁護士が神秘の生命体のように思えてきました。

** 


