* 「思い込み」と「思い込む」をキーワードに含む深澤諭史弁護士のツイートの記録

:CATEGORIES: 深澤諭史弁護士

 - 2020年10月16日19時52分の登録： REGEXP：”（思い込み｜思い込む）”／深澤諭史（@fukazawas）の検索（2013-11-18〜2020-10-16／2020年10月16日19時51分の記録42件） http://kk2020-09.blogspot.com/2020/10/regexpfukazawas2013-11-182020-10.html

 - （01／42） TW fukazawas（深澤諭史） 日時：2013-11-18 22:02:00 +0900 URL： https://twitter.com/fukazawas/status/402421486876520448

> 奨学金問題にしろ，生活保護にしろ，やれ自己責任だの借りたら返すだの，酷薄な意見が目立ちます。
> これは，別に日本の社会が冷たくなったのではなくて，今の政策の中で
> 「自分たちは，迫害される弱者ではないから大丈夫。」
> と思い込みたいだけだと思います。冷たいんでなくて怖いのでしょう。

 - （02／42） TW fukazawas（深澤諭史） 日時：2014-11-02 23:13:00 +0900 URL： https://twitter.com/fukazawas/status/528912756150263811

> 弁護士会の「仕組み」について、知らなかったら、
> 「たぶんこうだろう」
> 「こうに違いない」
> 「ネット de 真実に目覚めた！これに違いない！」
> とか思い込みで発言する前に、手近な弁護士に聞いてみよう！

 - （05／42） TW fukazawas（深澤諭史） 日時：2016-07-07 12:01:00 +0900 URL： https://twitter.com/fukazawas/status/750887379938848768

> 「ストーカー病」加害者治療の必要性 | 医療プレミア特集 | 中村好見 | 毎日新聞「医療プレミア」 https://t.co/hmt6grNq9z
> 「加害者には「被害者感情」「激しい思い込み」「愛憎の入り交じったしつこさ」「飛躍した衝動性」など、驚くほどの共通性がみられました」

 - （06／42） TW fukazawas（深澤諭史） 日時：2016-07-07 12:10:00 +0900 URL： https://twitter.com/fukazawas/status/750889690232819713

> この共通性ってのはＤＶ案件でもやや共通するのだけれども，被害拡大や再犯原因にもなっていると思う。
> 被害者感情：アイツが俺の思い通りになれば，こんな事にならなかった。だから俺は悪くない。悪くないからやっていない！
> 激しい思い込み：被害者も捜査機関も裁判所もグルで陰謀団に決まってる！

 - （07／42） RT fukazawas（深澤諭史）｜fukazawas（深澤諭史） 日時：2016-07-08 12:43:00 +0900／2016-07-07 12:01:00 +0900 URL： https://twitter.com/fukazawas/status/751260320069332992 https://twitter.com/fukazawas/status/750887379938848768

> 「ストーカー病」加害者治療の必要性 | 医療プレミア特集 | 中村好見 | 毎日新聞「医療プレミア」 https://t.co/hmt6grNq9z
> 「加害者には「被害者感情」「激しい思い込み」「愛憎の入り交じったしつこさ」「飛躍した衝動性」など、驚くほどの共通性がみられました」

 - （09／42） RT fukazawas（深澤諭史）｜lawkus（ystk） 日時：2016-11-04 21:21:00 +0900／2016-11-04 21:17:00 +0900 URL： https://twitter.com/fukazawas/status/794514965885353984 https://twitter.com/lawkus/status/794513823164080128

> 某論点について某立場に立ってネット上で盛んに発言している当事者の人々、明らかに思い込みが強く攻撃性の高い人が多いので「あっ（察し）」という感じになるよね。これだけ伏せても弁護士はかなりの確率で何の話かわかるような気がする。

 - （10／42） TW fukazawas（深澤諭史） 日時：2017-02-09 10:42:00 +0900 URL： https://twitter.com/fukazawas/status/829505674639839232

> 「自由競争」っていうと，売り手が，買い手の利益を最大化する方向でだけで，売り手同士だけで血を流して競争する，と勝手に思い込む人もおおい。
> けれども，自由競争原理の下では，売り手同士だけではなくて，買い手同士，下手すれば，売り手買い手の競争もあるということは，看過されがち。

 - （11／42） RT fukazawas（深澤諭史）｜yorisoibengoshi（弁護士篠田奈保子） 日時：2017-03-02 08:07:00 +0900／2017-03-01 16:14:00 +0900 URL： https://twitter.com/fukazawas/status/837076797543981056 https://twitter.com/yorisoibengoshi/status/836836933456265216

> 思い込みが強くて、認知の歪みが酷くて、攻撃力や破壊力がハンパなくってという人達が残念ながら社会には一定数おりまして。モラルという武器を与えられると、さらにその攻撃力や破壊力が増強されて、特に弱い立場の人たちが、スタンダードな状況ではない人たちが、本当に大変になると危惧するのです。

 - （15／42） RT fukazawas（深澤諭史）｜lawkus（ystk） 日時：2017-05-17 08:25:00 +0900／2017-05-16 23:06:00 +0900 URL： https://twitter.com/fukazawas/status/864622959478005760 https://twitter.com/lawkus/status/864482070097125376

> 「痴漢冤罪について逃げるしかないとか言ってるクラスタは放射脳とかネトウヨとかと同じ」という俺の数日前のツイートは完全に正しかったと実感してる。俺に絡んでくるお馬鹿さんたち、揃いも揃って悲観的な思い込みに支配されており、何とかなるよという現実的な話は頭から拒むので、本当にそっくり。

 - （17／42） RT fukazawas（深澤諭史）｜motoken_tw（モトケン） 日時：2017-07-09 13:30:00 +0900／2017-07-09 13:29:00 +0900 URL： https://twitter.com/fukazawas/status/883906270746427392 https://twitter.com/motoken_tw/status/883905955540357121

> @Dynamite_Tommy ならんよ！そういうことを言うからそういうゲームだと思い込む馬鹿が（弁護士の中にも）出てくる（可能性がある）。

 - （19／42） RT fukazawas（深澤諭史）｜noooooooorth（ノースライム） 日時：2017-08-12 09:40:00 +0900／2017-08-12 08:23:00 +0900 URL： https://twitter.com/fukazawas/status/896169596612337664 https://twitter.com/noooooooorth/status/896150029986967553

> もちろん低価格戦略が有効な場合もあるのだが、自分がしている低価格戦略が有効であるのかどうかについては思い込みではなく検討しておく必要があると思われる。大規模に集客している事務所の戦略は低価格戦略ではなく「一見低価格に見える戦略」で… https://t.co/ro4D2PNoSJ

 - （21／42） RT fukazawas（深澤諭史）｜un_co_the2nd（うの痔） 日時：2017-09-21 11:53:00 +0900／2017-09-21 11:52:00 +0900 URL： https://twitter.com/fukazawas/status/910698470163456001 https://twitter.com/un_co_the2nd/status/910698168936914944

> 「弁護士は高い」という思い込みのせいかな…300万円の損失を防ぐために30万払うのを嫌がる人の心理はまあわかるとしても、自分の「弁護士に依頼しない」という選択の結果300万損したのを、依頼もしてない弁護士のせいにする人までいるからなぁ

 - （24／42） RT fukazawas（深澤諭史）｜nodahayato（弁護士　野田隼人） 日時：2017-11-20 07:13:00 +0900／2017-11-19 22:14:00 +0900 URL： https://twitter.com/fukazawas/status/932371185827901445 https://twitter.com/nodahayato/status/932235720751583232

> 裁判所の判決がおかしいという話になる場合の大部分は、報道段階で何かが勝手に付加されたり捨象されたりという情報伝達過程のエラーである。そのエラーに気づかずに思い込みであれこれ言うのは法律家としてはアレな感じ。

 - （27／42） RT fukazawas（深澤諭史）｜kiwi250r（飛鳥＠3/11Aqours幕張昼） 日時：2018-01-21 23:32:00 +0900／2018-01-21 23:31:00 +0900 URL： https://twitter.com/fukazawas/status/955085772461285377 https://twitter.com/kiwi250r/status/955085523382550530

> 弁護士会への不満や理想をTwitterでつぶやくのは個人の自由だし別にかまわないと思うのだけれど浅学や思い込みに基づくデマや不正確な情報を公衆に撒き散らすのは百害あって一利なしなのでやめたほうがいいと思いますよ。

 - （29／42） TW fukazawas（深澤諭史） 日時：2019-01-02 15:07:00 +0900 URL： https://twitter.com/fukazawas/status/1080344787037782016

> 類型的、構造的に、本人訴訟の罠、思い込みにハマりやすい訴訟だと思う。
> （・∀・；） https://t.co/zbJGEUei5z

 - （31／42） TW fukazawas（深澤諭史） 日時：2019-02-03 08:10:00 +0900 URL： https://twitter.com/fukazawas/status/1091836219779047424

> 憲法学者が専門外の法分野、法律実務や業界について理解不十分なままに、自分の思い込みと想像の赴くまま、改革を進めた事例って知っています？
> 平成の司法改革っていうんですけれども。
> （・∀・）

 - （32／42） TW fukazawas（深澤諭史） 日時：2019-02-03 10:25:00 +0900 URL： https://twitter.com/fukazawas/status/1091870260741922817

> 陰謀論は麻薬みたいなものだから、心地良い（そして、私もフィクションとしては大好き）けれども、事態は悪化するだけなんですよね。
> そして、そのペースで思い込みをパートナーにぶつけ続けるから、関係が破綻してしまう、と。どっちにとっても不… https://t.co/Utaup9mmeN

 - （33／42） TW fukazawas（深澤諭史） 日時：2019-06-08 11:13:00 +0900 URL： https://twitter.com/fukazawas/status/1137180852360581120

> なんか、弁護士が懲戒制度について議論していると、すごい不完全な知識と思い込みに基づき、変なリプライ飛ばす方々が現れる・・。
> こういう方々が、余命ブログとかに騙されちゃうんだろうなぁ・・。
> 自分たちは違うって思っているかもだけれども… https://t.co/MmcEJ9Lz0P

 - （34／42） TW fukazawas（深澤諭史） 日時：2019-06-23 14:37:00 +0900 URL： https://twitter.com/fukazawas/status/1142668027407683586

> あるある。
> 少なくとも「そういう思い込みをして逆恨みをする人」大勢を相手にする時点で、相当大変だってば（・∀・；） https://t.co/PLcDmD5Gpz

 - （35／42） TW fukazawas（深澤諭史） 日時：2020-03-18 19:57:00 +0900 URL： https://twitter.com/fukazawas/status/1240230794527772672

> 「弁護士どもが金目当てで〇〇してる！」という思い込み - 弁護士 深澤諭史のブログ https://t.co/GAmKCQcCcz

 - （36／42） TW fukazawas（深澤諭史） 日時：2020-04-13 17:26:00 +0900 URL： https://twitter.com/fukazawas/status/1249614954329595907

> 「弁護士どもが金目当てで〇〇してる！」という思い込み - 弁護士 深澤諭史のブログ https://t.co/GAmKCQcCcz

 - （37／42） TW fukazawas（深澤諭史） 日時：2020-04-13 17:43:00 +0900 URL： https://twitter.com/fukazawas/status/1249619289121779717

> （；・∀・）自分たちが理解できない、気に食わない仕事をする弁護士を、仕事にあぶれている弁護士が金目当てでやっているって思い込むのは、その意見の信用性を著しく下げることに、早く気がついて欲しい。 https://t.co/cqkPO0SaXQ

 - （38／42） TW fukazawas（深澤諭史） 日時：2020-05-08 19:38:00 +0900 URL： https://twitter.com/fukazawas/status/1258707871409168385

> 「弁護士どもが金目当てで〇〇してる！」という思い込み - 弁護士 深澤諭史のブログ https://t.co/GAmKCQcCcz

 - （39／42） RT fukazawas（深澤諭史）｜harrier0516osk（向原総合法律事務所　弁護士向原） 日時：2020-05-14 11:07:00 +0900／2020-05-14 11:06:00 +0900 URL： https://twitter.com/fukazawas/status/1260753559580078080 https://twitter.com/harrier0516osk/status/1260753243396685825

> @fukazawas １億円持っている人からいただく100万円と、10万円しか持たない人からいただく10万円の価値の違いじゃないかなと思っています。
> お金と弁護士の問題は難しいですよね。
> 困難案件ほど揶揄されるのは、思い込みに基づ… https://t.co/vFoxPEAsDu

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2020/05/14 10:53 URL： https://twitter.com/fukazawas/status/1260749937471438848  

> 無料、赤字、困難案件ほど、「仕事のない弁護士の金儲け」と揶揄される謎現象。  
> （・∀・；） https://t.co/do6zLrVP4k  

 - （40／42） TW fukazawas（深澤諭史） 日時：2020-05-29 09:11:00 +0900 URL： https://twitter.com/fukazawas/status/1266160300887142400

> ブログにもＱＡ書いたが，ネット上の表現トラブルについて，請求（被害）者側は勇ましい願望の混じった武勇伝を誤信し，発信者側は，気休めのデマと心中するという，どうしようもない状態に陥っているよう。お互いに都合の良い事実は真実で，不都合な事実は「工作」だって思い込む迷路（・∀・；）

 - （41／42） TW fukazawas（深澤諭史） 日時：2020-07-01 22:23:00 +0900 URL： https://twitter.com/fukazawas/status/1278318366952833024

> 「弁護士どもが金目当てで〇〇してる！」という思い込み - 弁護士 深澤諭史のブログ https://t.co/GAmKCQcCcz

 - （42／42） TW fukazawas（深澤諭史） 日時：2020-10-16 16:24:00 +0900 URL： https://twitter.com/fukazawas/status/1317003448248795136

> 法的紛争で，相手方は相手方代理人弁護士に騙されているとか，こういう事件を担当する弁護士はダメな弁護士とか，そう思いたがる人がいますが，はっきりと，正直にいって，自爆につながる有害な発想です。そういう案件は，そう思い込む人に… https://t.co/umJo6OAUMz

* 埼玉愛犬家連続殺人事件，風間博子死刑囚の再審請求弁護人，内山成樹弁護士が業務停止1年の懲戒処分になったという預貯金約5000万円や不動産の譲渡で強制執行を妨げ報酬3800万円の受領

```
処分理由の要旨：裁判所の強制執行を妨害

処分が効力を生じた年月日：2017年7月10日

【処分変更】
処分種別：業務停止9月

変更理由：上記における詐害信託取消訴訟事件において、一部和解が成立。同弁護士は支払義務を負担し、同訴訟の一審判決を直ちに任意に履行し、原告（懲戒請求者）の利益を保全。これを受けて懲戒請求者から、同弁護士の懲戒を望まない旨の上申書が日弁連懲戒委員会宛てに提出されたため。

処分が効力を生じた年月日：2018年1月19日

［source：］【弁護士】内山成樹　東京：業務停止1年※処分変更有り：【公式】データ・マックス　NETIB-NEWS https://www.data-max.co.jp/article/20119
```

　上記は，Googleで検索をして，今初めて知った情報になります。

```
懲　戒　処　分　の　公　告

東京弁護士会がなした懲戒の処分について同会から以下のとおり通知を受けたので懲戒処分の公告公表に関する規定第３条第１号の規定
により公告する


１　懲戒を受けた弁護士

氏　名　　　　　　　　  　内山成樹

登録番号　　　　　　　　　17126

事務所　　　　　　　　　　東京都港区新橋３

　　　　　　　　　　　　　　田村町法律事務所　　　　
　　　　

２　処分の内容　　　　　業務停止1年
　　　　　　　業務停止9月に変更（30年1月19日）

　　

３　処分の理由の要旨

被懲戒者は、懲戒請求者が申し立てた子Aらの引渡しを求める間接強制申立事件等において懲戒請求者の夫の代理人であったが、Bが上記事件につき間接強制決定がなされた2014年3月31日以降もAらを引き渡すことを拒否し続け、上記決定に基づく間接強制金の支払義務を負っていたところ、同年10月頃、Bに対し懲戒請求者に対する強制執行を困難ならしめる目的で、Bが所有する資産を信託譲渡するスキームを提案し、同年12月20日、自宅土地建物、預貯金5000万円等のBの資産のほぼ全ていついて、受益者を被懲戒者及びAらとしてBから信託譲渡を受けた。

被懲戒者の上記行為は、弁護士法第５６条第１項に定める弁護士としての品位を失うべき非行に該当する。
４　処分が効力を生じた年月日

2017年7月10日　2017年10月1日　日本弁護士連合会

裁決の公告　　　2018年2月5日付官報

業務停止1年から業務停止9か月に変更

［source：］内山成樹弁護士（東京）懲戒処分の要旨 – 弁護士自治を考える会 https://jlfmt.com/2017/10/20/31494/
```

　上記の引用は，裁判所の決定や判決に相当するものと思われますが，再度読み直すと，「懲　戒　処　分　の　公　告」とありました。同じページには，報酬額を約3800万円受け取った旨，記載があるのですが，「懲戒処分の公告」には，見当たらない金額です。

```
← 京都弁護士会が「戒告」処分、島崎哲郎弁護士　京都新聞10月20日吉祥寺で車暴走、８５歳男を過失運転傷害容疑で逮捕/ヤメ裁弁護士 →
内山成樹弁護士（東京）懲戒処分の要旨
投稿日 ： 2017年10月20日 | カテゴリー ： 弁護士懲戒処分の要旨
TwitterFacebookHatenaLine共有

弁護士の懲戒処分を公開しています。

日弁連広報誌「自由と正義」2017年10月号に掲載された弁護士の懲戒処分の公告,
内山成樹弁護士の懲戒処分の要旨

 

脱原発全国弁護団の弁護士としても活躍

http：//www.datsugenpatsu.org/bengodan/news/14-08-29/

「前進」に掲載されたご活躍

 http：//www.zenshin.org/zh/f-kiji/2016/04/f27370401.html



懲戒処分について報道がありました。

 

内山成樹弁護士（東京）業務停止1年


東京弁護士会は10日、同会所属の内山成樹（しげき）弁護士（70）を業務停止1年の懲戒処分とした。

発表では、内山弁護士は千葉家裁から2013年4月に娘2人を別居中の妻に引き渡すよう命じられたのを拒み、1日あたり20万円～40万円の間接強制金の支払を命じられた依頼者の男性に、資産の譲渡を提案。14年2月に預貯金約5000万円の譲渡を提案、14年12月に預貯金約5000万円や不動産の譲渡を受け、裁判所の強制執行を防げたとしている。内山弁護士は同会の調査に『娘2人の養育費を確保するためだった』と述べたが、譲渡された資産から弁護士報酬として約3800万円を受け取っていたという

以上　読売新聞

［source：］内山成樹弁護士（東京）懲戒処分の要旨 – 弁護士自治を考える会 https://jlfmt.com/2017/10/20/31494/
```

　弁護士報酬約3800万円は，読売新聞の記事の内容のようです。理解が十分ではないものの，5000万円の資産隠しで，弁護士が約3800万円の報酬を得たと読めます。他の弁護士の横領などに比べれば，ましな方なのかもしれないですが，同業者の関心もすこぶる低く，問題視していないようです。

　これが刑事事件にならなかったのも不思議でならないです。報酬額の大きさをみれば，まさに主犯格で，報酬額は問題にされていなかったように思いますが，過去には安田好弘弁護士が，似たような強制執行妨害で起訴され，大きな問題になっていました。

```
裁判官5人中4人の多数意見。田原睦夫裁判官（弁護士出身）は「共謀の成立や犯意の認識に合理的な疑いがあり、被告は無罪」との反対意見を付けた。弁護士法は禁錮刑以上が確定した場合は弁護士資格を失うと定めており、罰金刑の場合は弁護士を続けられる。

二審判決によると、安田弁護士は不動産会社の社長（有罪確定）らに対し、所有ビルの賃料の差し押さえを逃れるため、賃料振込先を別口座にするよう指南。住宅金融債権管理機構（現整理回収機構）の債権回収を免れるのをほう助した。

［source：］安田弁護士の有罪確定へ　強制執行妨害ほう助　　：日本経済新聞 https://www.nikkei.com/article/DGXNASDG0801C_Y1A201C1CR0000/
```

　一審で無罪判決が出ていたのも記憶になかったですが，幇助犯として有罪判決になっていたのはさらに意外です。幇助犯の成立自体が珍しく感じますし，それも顧問弁護士という立場でのことです。

　全国の大勢の弁護士が安田好弘弁護士を支援したと記憶していますが，これは富山氷見強姦冤罪事件の国賠訴訟ともよく似ていました。記事は2011年12月8日とありますが，弁護士業界がそっぽを向かれ斜陽する分水嶺となったような気もします。一方で国策捜査というような話もあったかと思います。

* 「12人の国選弁護人に支払われた弁護士報酬は計4億5200万円」というオウム真理教事件、教祖の刑事裁判

オウム真理教事件 国選 報酬 - Google 検索 https://t.co/bRJsGH02RW

参考資料／刑事裁判／国選弁護人／「12人の国選弁護人に支払われた弁護士報酬は計4億5200万円」と知ったオウム真理教事件、教祖の刑事裁判と、ひな祭り - 告発＼金沢地方検察庁＼最高検察庁＼法務省＼石川県警察御中 https://t.co/aZDVWckAng

　Googleの検索結果の3番目に出てきたのが自分のブログ記事ですが，見出しと本文の内容が一致していないようです。2019年3月4日の記事となっていますが，ずっと前に使わなくなっていたorg-modeのヘッダが使われているのも意外でした。

```
２月２７日に東京地裁で死刑判決を受けたオウム真理教の麻原彰晃（松本智津夫）の国選弁護人に対し、総額約４億５２００万円の報酬が支払われたことが分かった。
最初、これを読んだとき、「さすがはオウム真理教。信者から強引に金をかき集めてるから、金持ちやのう」なんて呑気に思っていたら、なんと、これ、全額、国費からの支出、すなわち我々の税金からの支出なのだ。どひゃ～っ！麻原の弁護士は全員、国選弁護士だったのだ。もちろん、１人の被告に対する国選弁護報酬としては過去最高だ。

地下鉄サリン事件などで起訴された麻原は、当初依頼していた弁護人を、予定されていた初公判の前日に突然、解任した。このため初公判は延期を余儀なくされたのだが、もちろんこれは裁判を長引かせようとする麻原の卑劣な作戦だった。そのため地裁は再発阻止のため、被告からは解任できない国選弁護人を付けることを決めた。そして、これに応じたのが１２人の国選弁護士だ。普通、弁護士なんて１人か２人のような気がするけど、１２人もの大型国選弁護団が編成されたうえ、初公判から判決までに７年１０カ月、２５７回の公判を要したため、報酬額も膨れ上がったのだ。

［source：］人質帰国 http://www2.netwave.or.jp/~boris/Hitorigoto/Hitorigoto347.htm
```

　上記の引用は検索結果の5番目になりますが，ページタイトルが「人質帰国」と取得されていますが，実際のページ上では最上部に，「麻原彰晃の弁護士報酬　〜　こんなバカげた制度はやめろ　〜」とあります。初めて見るページですが，2004年4月4日という日付があります。

　どうも以前に，はじめて知った時のページは，検索で見当たらないようです。Twilogの方には痕跡が残っているかと思います。なにかでたまたま見つけたのですが，それで初めて「12人の国選弁護人に支払われた弁護士報酬は計4億5200万円」というオウム真理教事件のことを知りました。

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「12人の国選弁護人」の検索結果 - Twilog https://t.co/2RzLgrhgeE

　以下は，2019年3月4日記載となっている自分のブログ記事になります。

```
控訴審については深澤諭史弁護士のブログ記事がきっかけで、記事を読んで思い出したのが落合洋司弁護士（東京弁護士会）の過去のブログ記事で高検の検事を廃棄物処理場などと揶揄していたものです。探すと記事が見つかりました。後でエントリーを作成します。［fn：3］

　「12人の国選弁護人に支払われた弁護士報酬は計4億5200万円」という件は一審のようです。12人という弁護人の中には安田好弘弁護士がいるようですが、私は控訴審の弁護人とばかり思っていました。オウム真理教事件の教祖の刑事裁判のことです。

　オウム真理教の教祖の控訴審は、弁護人が期限内に控訴趣意書を提出しなかったことで棄却となり、当時問題になっていましたが、その弁護人が安田好弘弁護士という話と、仙台の余り名前は見ない弁護士という話があったかと思います。

　詳細はこのあと作成済みのエントリーで新規項目として記述をしたいと思いますが、国選弁護人が12人もいて、その報酬が4億5200万円ということも私は知らず、これまでの国選弁護人制度に関する認識が根本からひっくり返った気分になりました。［fn：4］

　刑事裁判で複数の国選弁護人が付いたという話も余り聞いたことはなく、最初に知って意外に思ったのが栃木小1女児殺害事件でした。それも控訴審であったと思います。この事件で思い出すのは、ひな祭りのことです。それでエントリー名に付け加えておきました。［fn：5］

［source：］告発に至る経緯／珠洲警察署／提出書面／平成4年傷害・準強姦被告事件につき、市場急配センターの殺人未遂事件として再捜査の要望書 - 告発＼金沢地方検察庁＼最高検察庁＼法務省＼石川県警察御中 https://hirono-hideki.hatenablog.com/entry/2019/03/01/192941#12%E4%BA%BA%E3%81%AE%E5%9B%BD%E9%81%B8%E5%BC%81%E8%AD%B7%E4%BA%BA%E3%81%AB%E6%94%AF%E6%89%95%E3%82%8F%E3%82%8C%E3%81%9F%E5%BC%81%E8%AD%B7%E5%A3%AB%E5%A0%B1%E9%85%AC%E3%81%AF%E8%A8%884%E5%84%845200%E4%B8%87%E5%86%86%E3%81%A8%E7%9F%A5%E3%81%A3%E3%81%9F%E3%82%AA%E3%82%A6%E3%83%A0%E7%9C%9F%E7%90%86%E6%95%99%E4%BA%8B%E4%BB%B6%E6%95%99%E7%A5%96%E3%81%AE%E5%88%91%E4%BA%8B%E8%A3%81%E5%88%A4%E3%81%A8%E3%81%B2%E3%81%AA%E7%A5%AD%E3%82%8A%E6%9C%AC%E6%96%87
```

　一審の12人の国選弁護人の中に，安田好弘弁護士がいたようなことが記述されていますが，これは記憶になかったもので，残念ながらこの記事にはソースが示されていないようです。仙台の弁護士のこともありますが，これも同じです。

　少し思い出したのは，控訴審だったと思いますが，オウム真理教事件の教祖の裁判で，問題視され，あるいは懲戒請求を受けたともいうのが仙台の弁護士だったように思います。

　仙台の弁護士については，今年2020年になってから注目度が高まっています。1つは日弁連の会長となった荒中弁護士，そして松山事件のことがあります。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜skd7（やん） 日時：2020-10-17 11:00／2020/10/17 10:49 URL： https://twitter.com/kk_hirono/status/1317284440083636224 https://twitter.com/skd7/status/1317281629090369536  

> めぞん一刻：ノラ・ジョーンズとコラボ　MV公開　ブルーノートの希望で実現 - MANTANWEB（まんたんウェブ） https://t.co/5DWkH1QXpr  

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2019年03月04日 - Twilog https://t.co/7GnvI0Bu3I

　どうも他に，オウム真理教事件の教祖の裁判に関するツイートは見つかりませんでした。当日2019年03月04日としてよく見かけたのが，岡口基一裁判官に関するツイートですが，情報をみかけないのでしばらく忘れていました。たぶんいまも仙台高裁の裁判官に違いはないと思います。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-10-17 11:04／2019/03/03 10:10 URL： https://twitter.com/kk_hirono/status/1317285228004560896 https://twitter.com/hirono_hideki/status/1102013389901983745  

> » 【社会】"過去最高" オウム・麻原裁判、国選弁護人の報酬は計４億５２００万円 https://t.co/cmIyHZvCDI  

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「オウム 国選」の検索結果 - Twilog https://t.co/tnUiLEQMuf

　Twilogの検索ワードを変更したところ一発で出てきましたが，2019年3月3日のツイートでした。ひな祭りです。

```
５ちゃんねる ★スマホ版★ ■掲示板に戻る■ 全部 1- 最新50 
■ このスレッドは過去ログ倉庫に格納されています
【社会】"過去最高" オウム・麻原裁判、国選弁護人の報酬は計４億５２００万円
1 ：☆ばぐ太☆φ ★：04/04/19 12：38 ID：???
★麻原裁判、国選弁護人の報酬は計４億５２００万円

・東京地裁で２月２７日に死刑判決を受けた麻原彰晃こと松本智津夫
　被告（４９）（控訴中）の国選弁護人に対する報酬が、総額
　約４億５２００万円に上ったことが、１９日分かった。

　同日までに国選弁護人だった１２人（後に１１人）に全額支払われた。
　同地裁によると、１人の被告に対する国選弁護報酬としては過去最高
　となった。

　松本被告は、起訴された事件数が１３あり、公判回数は２５７回、初公判
　から判決までに７年１０か月を要した。
　４人の国選弁護人が付き、週４日開廷の集中審理を実施した埼玉・本庄
　保険金殺人事件の金融業八木茂被告（５４）（控訴中）の場合は、９０回の
　公判で約４７００万円だった。

　http：//news.fs.biglobe.ne.jp/social/ym20040419i403.html

［source：］【社会】"過去最高" オウム・麻原裁判、国選弁護人の報酬は計４億５２００万円 https://news5.5ch.net/test/read.cgi/newsplus/1082345887/
```

　これが最初に目にした記事だと思いますが，「４人の国選弁護人が付き、週４日開廷の集中審理を実施した埼玉・本庄保険金殺人事件の金融業八木茂被告（５４）（控訴中）の場合は、９０回の公判で約４７００万円だった。」というのは記憶になかったです。

　さきほど，久しぶりにみる弁護士の記事があったのですが，そこに本庄保険金殺人事件を担当したように書いてありました。この事件は，高野隆弁護士が担当したような情報を過去に見かけたような記憶があったので，気になってはいたのです。

　「オウム真理教事件 国選 報酬」のGoogle検索の7番目の検索結果でした。次のページです。

```
法テラス埼玉開所の頃の話を聞かせてください。
　当時、埼玉には法テラスを「法務省の手先」「弁護士自治の敵」と考え、反対する弁護士が多くいました。一方で、国選弁護の手続は、法テラスが裁判所から引き継ぐことになり、被疑者国選も始まることが決まっていた。法テラスに反対して国選契約を拒否する弁護士が数多く出たら、埼玉の国選刑事弁護は回らなくなります。
　そのような状況の中で、私は開業と同時に、スタッフ弁護士になることに決めました。「村木は弁護士としての魂を権力に売った」と、批判されていました。
　よく覚えているのは開所披露パーティのことです。
　私は刑事弁護人として、検察庁と激しく対立することがしばしばでした。「本庄連続保険金殺人事件」の弁護人を務めていたところ、相被告人の弁護人を務める高野隆先生とともに、「接見禁止決定を潜脱する違法な弁護活動」だとして、さいたま地検から懲戒請求されたことすらあります（後に懲戒しないとの決定）。
　法テラス埼玉の開所式には、弁護士会や裁判所だけでなく、地検からも検事正以下来賓が来ていました。私も挨拶をすることになり、壇上で話しました。
　「『村木は魂を権力に売った』と言われているが、私はいま目の前にいる次席検事から、刑事弁護人として「違法な弁護活動をした」として、懲戒請求されたことがあります。これでも弁護士としての魂を売ったと言えるのでしょうか。」と静かに語りました。場内は爆笑（笑）。

［source：］私にとっての刑事弁護：被害者の最大・最高の理解者であること（埼玉・村木一郎弁護士）｜法テラス https://www.houterasu.or.jp/houterasu_gaiyou/saiyo/staff_bengoshi/motto-wakaru/keijibenngo/jokinmuraki.html
```

　先を急いでいたので，少ししか目を通していなかったのですが，「本庄連続保険金殺人事件」の弁護人を務めていたところ」のすぐあとに，続けて「相被告人の弁護人を務める高野隆先生とともに、」という記載がありました。

　この本庄連続保険金殺人事件は主犯と愛人とかの対立もあった刑事裁判で，その愛人のような女性が手記を出していたと，最近知りました。

　この村木一郎弁護士を見たのも久しぶりですが，前に対立候補の政治家の大失言もあって，新潟の選挙区で当選した女性弁護士の夫というのもよく憶えています。さく良という女性弁護士でしたが，上の名前が思い出せず，最近は名前も見かけていません。Twitterのアカウントもあったような気がします。

```
　私が東京で弁護士登録をした当時、刑事弁護で名前を知られている弁護士は、本当に限られていました。東京なら石田省三郎先生と丸山輝久先生、大阪なら下村忠利先生などです。当時20年目くらいのベテランの方々です。
　私は42期ですが、司法修習生の時に、まだ若手だった35期の神山啓史弁護士と知り合いました。神山先生とは、それ以来「何かあれば聞きに行く」という関係ですし、事件以外の人生の様々な局面でもアドバイスをもらってきました。
　弁護士になって4年目に入ったとき、埼玉に登録を移しました。埼玉には、34期の高野隆弁護士がいました。本庄事件では相被告人をそれぞれ弁護していましたが、一緒に事件を担当させてもらったこともあります。
　当時、刑事弁護は証拠の開示も不十分、保釈もなかなか通らないという暗黒の時代でした。高野・神山両先生は、刑事裁判をよくするために、刑事訴訟法に沿った裁判を実現するために、果敢に根気強く闘っていた。この2人がいなければ、今の刑事弁護シーンは、全く違うものになっていたと思います。
　高野先生に、「最高裁への特別抗告は、1000件やれば1件くらい良いことがある」と言われたことがあります。当時、第一回公判前の保釈請求は、検察官の意見書を閲覧できませんでした。不思議なことに、電話をすると口頭で教えてくれるのに、弁護人が自分で読むのはダメだと言うのです。高野先生は、保釈請求却下に対する特別抗告の中で、この点を刑事訴訟法に違反していると主張しました。最高裁は、特別抗告自体は棄却したものの、理由の中で、閲覧させない処分は「不相当」と書いていました。それは最高裁から全国の裁判所に通知されたようです。次に行ったら「どうぞどうぞ」と裁判官から検察官意見書を見せられたのが、印象に残っています。
　神山先生は常々、「どんなにダメな裁判官でも訴訟指揮には従うこと。訴訟指揮に従わないなら、それは弁護士ではない」と言います。特別抗告もそうですが、限られたツールの中で、法律のプロとして、法律の枠の中で、制度改善のために闘うこと。
いくら改善されたからと言って、まだまだ改善すべき点の多い刑事裁判なので、この先もそういった気概を持って刑事訴訟法を駆使して闘う弁護士は必要です。

［source：］私にとっての刑事弁護：被害者の最大・最高の理解者であること（埼玉・村木一郎弁護士）｜法テラス https://www.houterasu.or.jp/houterasu_gaiyou/saiyo/staff_bengoshi/motto-wakaru/keijibenngo/jokinmuraki.html
```

　ページを閉じようとしたのですが，下の方に軽く目を通すと，「私は42期ですが、司法修習生の時に、まだ若手だった35期の神山啓史弁護士と知り合いました」などという部分が目に入りました。過去に読んでいる記事と思っていたのですが，この部分の神山啓史弁護士との関係は記憶になかった気がします。

```
第一審・東京地裁
初公判
当初、第一審の初公判日程は1995年（平成7年）10月26日に設定されたものの、麻原は初公判前日の10月25日に私選弁護人の横山昭二を解任［91］。東京地方裁判所は期日を取り消し、渡辺脩、安田好弘ほか国選弁護団を選任したが、初公判は延期を余儀なくされた。国選弁護団は弁護士会から依頼があったので引き受けただけであるが、「何故麻原を弁護するのか」とバッシングを受けた［92］。

1996年（平成8年）4月24日、第一審の初公判（阿部文洋裁判長）が開かれ、1996年（平成8年）4月24日に東京地方裁判所で初公判が行われたが、48席の一般傍聴席に対して、日本の刑事裁判史上最多の12,292人が傍聴を希望して、傍聴券の抽選場所の日比谷公園には長蛇の列ができた［web 22］［93］。日本テレビはこの時点から、「麻原-」から「松本-」と本名で報道するようになった。その後、民放全局・産経新聞・中日新聞（東京新聞）などを除くほとんどの新聞社も本名で報道するようになった。NHKは結審まで「麻原-」を使用していた。

裁判では初公判で阿部は「全世界がこの事件に注目している。判決は5年以内に出したい」と述べ、事件ごとの並行審理を提案したが、弁護団側が拒否したため、一事件ずつの審理となった。また、弁護団が月4回の開廷ペースに反発。審理をボイコットなどで長期裁判の様相を見せ［94］、一時は第一審の結審までに30年はかかるという噂も流れた［95］［注 9］。

弁護側は検察側が申請した被害調書や共犯者の供述調書などの1万5687点の証拠に対し1万5472点と約98.62%に不同意。そのために171人の検察側の証人を直接出廷させて証言させることになったが、検察側の尋問時間が計206時間であったのに対し、弁護側の尋問時間は1053時間 （検察側の5倍） に及んだ。弁護士の証人尋問では「職場のどのプリンターで印刷したものか（地下鉄サリン事件で、営団地下鉄の職員が、都内の地下鉄のダイヤの表について）」「サリンを見たことあるのか（サリン患者に関する医師のカルテについて）」などの尋問があった。これらにより実質的な証拠調べが遅れたと日刊ゲンダイは報じている［96］。

1997年（平成9年）12月、検察側は松本・地下鉄両サリン事件の重軽症者を約4000人から18人に減らす訴因変更を行い、2000年（平成12年）10月に薬物密造など4事件の起訴を取下げて案件を13事件に絞り込んだ。

安田好弘の証言
1995年10月26日に予定されていた初公判が横山昭二弁護人の突然の解任で取り消しになった後、弁護士会より国選弁護人就任を依頼された弁護士安田好弘は、4日後に初めて麻原に接見。麻原は開口一番「あなたをお待ちしていました。あなたの名前は聞いていました」といったという。その後、月に5-10回の頻度で接見を続ける。1995年暮れ、麻原は安田に向かい、「どうすれば、私の真実を明らかにできますか」と問うたのに対し、安田は「法廷でみんなが見ている前で、空中浮揚をやってはどうでしょうか」と提案する。「法廷でやってみせれば、僕たち弁護人も納得するし、検察官、裁判官は腰を抜かして逃げてくと思うよ」と話すと、麻原は、「やってみます」と言い、1996年4月の初公判に向けて、警視庁の留置場や東京拘置所中で、『空中浮揚』の修行を重ねていたという。また、「当時麻原の好物は検察発表により高級品のメロンと報道されていたが、麻原は「本当の好物はバナナ」と話した（後述）。

麻原は接見中に、「2003年に、アメリカが日本や世界に向けて最終の宗教戦争を引き起こす」と言い出したことがあり、「自分は時間と空間を超えることができる。2003年の広島に飛んだところ、焼け野原になっていた。通りがかりの人に聞くとアメリカが原爆を落としたと広島弁で話した。これは、予言ではない、現実に行って見聞してきたことだ」と安田に向かって話した。また、接見中に停電があり、真っ暗となった際に麻原は何も気づかずに話し続けたことから、目が見えないのは本当だと思ったという［web 23］。

［source：］麻原彰晃 - Wikipedia https://ja.wikipedia.org/wiki/%E9%BA%BB%E5%8E%9F%E5%BD%B0%E6%99%83#%E7%AC%AC%E4%B8%80%E5%AF%A9%E3%83%BB%E6%9D%B1%E4%BA%AC%E5%9C%B0%E8%A3%81
```

　調べ方を変えたところ，オウム真理教事件の教祖の一審の刑事裁判で，安田好弘弁護士の活動が具体的にわかりました。控訴審で酵素趣意書の提出を先延ばしし，それが大きな問題になっていたことは知っていましたが，一審のことはまるで知らずにいました。

　過去のネットでも記述があると思いますが，被告発人木梨松嗣弁護士が私の母親経由で郵送で差し入れた刑事裁判の一件記録には，その一番上，表紙の次だったと思うのですが，判例解説のコピーがあって，それが新宿バス放火事件だったのです。

　安田好弘弁護士の名前を最初に知ったのは思い出せないですが，最初の頃に新宿バス放火事件を知りました。

　前にも書いていると思いますが，被告人は山口県の岩国市辺りの出身で，男の子をそちらの施設に預けながら東京で働き，事件を起こし，安田好弘弁護士の尽力で死刑判決を免れたものの，そのあと自殺をしたという話も印象的でした。

```
控訴審・東京高裁
第一審を担当した国選弁護団は終了後に全員が辞任。12人の国選弁護人に支払われた弁護士報酬は計4億5200万円になった［110］。松井武と仙台在住の松下明夫の2人の弁護団が後を引き継いだ。東京高等裁判所は控訴趣意書の提出期限を2005年（平成17年）1月11日と定めた［111］。弁護団は1審判決後、松本に計36回接見したものの、弁護団の問いかけに無反応で意味不明な声を漏らし意思疎通が不可能であるとして、公判停止を申し立てた［112］。一方、東京高裁裁判長の須田賢は、2004年12月10日に麻原と面会し、「控訴趣意書は弁護士に作ってもらってもよい」「提出期限を延ばすつもりはなく、棄却もありえる」と説明した［113］。

2005年（平成17年）1月6日、東京高裁は麻原の精神鑑定を求める特別抗告を棄却しつつ、控訴趣意書の提出期限を同年8月31日まで延長することを決めた［114］。

同年8月19日、東京高裁は弁護団に対して精神鑑定の実施を伝えた［web 27］。弁護団によれば、このとき東京高裁は「鑑定形式による鑑定人の意見が出るまでは控訴棄却はしない」と明言したとされる［115］。提出期限の8月31日、弁護側は控訴趣意書の「骨子」を持参したが、高裁の鑑定への立ち会いや公開法廷での鑑定人尋問などに関する申し入れが拒否されたことを理由に提出を拒んだ［115］。9月3日、東京高裁は控訴趣意書を「直ちに提出することを強く求める」文書を弁護団に送付した［web 28］。2005年（平成17年）9月、東京高裁は麻原の精神鑑定を西山詮に依頼した［116］。

2004年（平成16年）10月以降、弁護団は独自に精神科医に依頼して鑑定を実施した［117］。中島節夫・中谷陽二・野田正彰・秋元波留夫・加賀乙彦など、計7人の精神科医はいずれも訴訟能力を否定または疑問視している［118］［119］［120］。一方、高裁の依頼を受けて鑑定を行った西山は「拘禁反応はあるが拘禁精神病の水準には達しておらず訴訟を続ける能力を失っていない」とし、高裁は2006年2月にこの鑑定書を受けとった［116］。

高裁はこの鑑定書への反論意見書の提出を2006年3月15日までとした［web 29］。弁護側は提出期限の1ヶ月延長を高裁に申し立てたが［web 30］、認められず［web 31］、結局期日通りに意見書を提出した［web 32］。

弁護団は2006年（平成18年）3月28日に控訴趣意書を提出することを表明していたが、東京高裁（須田賢裁判長）はその前日の2006年3月27日付で控訴棄却を決定した［116］。この控訴棄却の決定は、控訴審の審理が結審した後に下される控訴棄却の判決とは異なり、控訴趣意書が正当な理由なく期限までに提出されなかったため、刑事訴訟法の規定に従って、控訴審を開始せずに裁判を打ち切るという決定である。

これについては、弁護側が裁判引き延ばしのため控訴趣意書を出さないことで裁判所と危険なチキンレースをやって負けたという弁護側批判［web 33］、裁判所のだまし討ちであるという裁判所批判［121］ の両方がある。

弁護団はこの決定に対し、2006年（平成18年）3月30日に東京高等裁判所（白木勇裁判長）へ異議申立てを行ったが、同年5月、棄却が決定された［122］。「裁判所は『精神鑑定の意見が出るまでに提出すれば認める』と明言した」とする弁護団の主張については、「裁判所はその日のうちに見解を訂正した」として退けた［122］。

［source：］麻原彰晃 - Wikipedia https://ja.wikipedia.org/wiki/%E9%BA%BB%E5%8E%9F%E5%BD%B0%E6%99%83#%E7%AC%AC%E4%B8%80%E5%AF%A9%E3%83%BB%E6%9D%B1%E4%BA%AC%E5%9C%B0%E8%A3%81
```

　上記の引用は，同ページの「控訴審・東京高裁」という項目です。ここに仙台の弁護士の名前が出てきましたが，控訴審に安田好弘弁護士の名前はなかったようです。

　安田好弘弁護士といえば，オウム真理教事件の教祖の刑事裁判の控訴審というイメージが強かったのですが，同じ頃には光市母子殺害事件がありました。こちらも岩国市に近い山口県です。

　中西運輸商の4トン長距離で，広島市と山口市辺りの国道2号線というのも，私は何度か走っていました。当時の思い出も重なります。

　「第一審を担当した国選弁護団は終了後に全員が辞任。12人の国選弁護人に支払われた弁護士報酬は計4億5200万円になった[110]。松井武と仙台在住の松下明夫の2人の弁護団が後を引き継いだ。」とのことです。松下明夫という弁護士の名前は少し記憶にありますが，近年は見かけていません。

```
> 弁護団の松井武弁護士は「知っていた...

松井武弁護士は何を考えているのだろう。およそ常識を卓越したハイパーな人権主義者か。松井武弁護士は2004年2月27日に私選弁護人として弁護団に加わった東京二弁所属の人。地裁判決の後、11人いた国選弁護団と私選の安田好弘弁護士が辞任、麻原の家族が松井武弁護士の選任届を出し、私選弁護人に就任した経緯。

［source：］７～８年前までオウム信徒だった弁護士が弁護団に加わる - worldNote https://blog.goo.ne.jp/worldnote/e/bf2edb5613e7e3473db87d08722d7e55
```

　上記の記事によると，オウム真理教事件の麻原彰晃教祖の一審は，安田好弘弁護士が1人，私選弁護人で，他11人が国選弁護人だったとあります。Wikipediaや他の情報では，12人全員が国選弁護人で，その報酬額が総額で４億５２００万円となっています。

　さきほどpythonで計算をしてみたのですが，12人と7年10月で割ると，弁護士一人あたり月に40万円ちょっとの報酬額となっていました。

```
>>> 452000000 / 12
37666666.666666664
>>> 37666666 / ((12 * 7) + 10)
400709.21276595746
```

　安田好弘弁護士の名前は，ネットでほとんど見かけなくなっていますが，再審請求を担当していた和歌山毒カレー殺人事件のことは，えん罪の可能性を指摘する情報を最近も見かけています。その再審請求書は，やがて10年ほど前になりますか，ネットで公開されていたPDFファイルを閲覧しました。

```
「生きる」という権利―麻原彰晃主任弁護人の手記 (日本語) 単行本 – 2005/8/6
安田 好弘  (著)
5つ星のうち3.6    14個の評価
 その他 の形式およびエディションを表示する
単行本
￥700 
￥497 より 14 中古品
￥8,000 より 1 新品
お届け日： 10月20日 - 22日 詳細を見る

［source：］「生きる」という権利―麻原彰晃主任弁護人の手記 | 好弘, 安田 |本 | 通販 | Amazon https://www.amazon.co.jp/%E3%80%8C%E7%94%9F%E3%81%8D%E3%82%8B%E3%80%8D%E3%81%A8%E3%81%84%E3%81%86%E6%A8%A9%E5%88%A9%E2%80%95%E9%BA%BB%E5%8E%9F%E5%BD%B0%E6%99%83%E4%B8%BB%E4%BB%BB%E5%BC%81%E8%AD%B7%E4%BA%BA%E3%81%AE%E6%89%8B%E8%A8%98-%E5%AE%89%E7%94%B0-%E5%A5%BD%E5%BC%98/dp/4062121433
```

　安田好弘弁護士がオウム真理教事件の教祖の裁判の国選弁護人なのか私選弁護人なのか確認しておこうと調べたところ，上記のアマゾンの本のことが検索に出てきました。2005年8月6日という日付が見えます。平成17年ですが，この本のことも今日まで知らずにいたように思います。

```
新宿西口バス放火事件
1980年より、被告人（男性）の弁護人に選任される。死刑が求刑されたが、判決は無期懲役。被告人は1997年に自殺。

［source：］安田好弘 - Wikipedia https://ja.wikipedia.org/wiki/%E5%AE%89%E7%94%B0%E5%A5%BD%E5%BC%98
```

　上記の引用部分に，新宿西口バス放火事件は，安田好弘弁護士が1980人に弁護人に選任され，判決が無期懲役で，被告人は1997年に自殺とあります。いつどこで自殺の話を知ったのか記憶にないですが，被告発人木梨松嗣弁護士の一件記録が福井刑務所に届いたのは，平成6年11月のことで，1994年になります。

```
山谷暴動。新宿駅西口バス放火事件。山梨幼児誘拐殺人事件。名古屋女子大生誘拐殺人事件。宮代町母子殺害事件。北海道連続婦女暴行殺人事件。滝田修、鎌田俊彦、泉水博、丸岡修、坂口弘ら新左翼の闘士たち。
そして、オウム真理教教祖・麻原彰晃。……これらすべての法廷で、弁護人となった男がいた。
いろいろな事件の裁判にかかわって、はっきりと感じることがある。なんらかの形で犯罪に遭遇してしまい、結果として事件の加害者や被害者になるのは、たいていが「弱い人」たちなのである。私は、これまでの弁護士経験の中でそうした「弱い人」たちをたくさんみてきたし、そうした人たちの弁護を請けてきた。それは、私が無条件に「弱い人」たちに共感を覚えるからだ。要するに、肩入れせずにはいられないのだ。——＜まえがきより＞
```

「生きる」という権利―麻原彰晃主任弁護人の手記 | 好弘, 安田 |本 | 通販 | Amazon https://t.co/u4f0AV8doX

　上記の引用は，「「生きる」という権利―麻原彰晃主任弁護人の手記 | 好弘, 安田 |本 | 通販 | Amazon」での書籍の紹介文のようになっています。弁護士鉄道の強力な牽引役だった安田好弘弁護士ですが，被告発人木梨松嗣弁護士にも少なからず，影響を与えたように思えてきました。

* オウム事件で麻原彰晃の国選弁護人を務めていた最中の1998年12月5日、強制執行妨害の容疑で逮捕，その後に私選弁護人になったという安田好弘弁護士
　
```
強制執行妨害事件（安田事件）［編集］
オウム事件で麻原彰晃の国選弁護人を務めていた最中の1998年12月5日、オウム事件とは全く無関係の強制執行妨害の容疑で逮捕。10か月間の拘束で東京地裁は安田を松本被告の国選弁護人から解任、その後も私選弁護人として主任弁護人にとどまったものの、事実上、麻原の弁護活動はできなかった。この事件では、2003年12月に東京地裁は無罪、2審では有罪となり、2011年12月、最高裁で50万円の罰金刑が確定している［3］。

安田は、1993年3月から1996年9月までの間に任意整理を受任した不動産会社「スンーズコーポレーション東京リミテッド」の代表取締役（懲役1年6月執行猶予3年確定）らと共謀し、差押えの強制執行を逃れることを目的として、同社が所有する賃貸ビル2棟のテナントから、賃貸料名目で休眠会社への約2億円の口座振込みを指示して、当然差押え執行がなされるべき財産を隠匿したとする強制執行妨害の被疑事実により逮捕され、約10ヶ月間勾留された後に、右被疑事実を公訴事実として起訴された。この事件は俗に「安田事件」と呼ばれることもある。

この事件は、松本被告の裁判が検察側の主張通りに進まない中で起きたことから、麻原の弁護団（渡辺脩団長）が強く抗議し、土屋公献日弁連会長の呼びかけもあり、1000人以上の弁護団が結成された［3］。安田の逮捕・勾留に際しては、全国から安田の弁護をしようという弁護士が集い、約1200人が弁護人となった。約3000名が抗議デモを行い、日本弁護士連合会やアムネスティ・インターナショナルなどの団体から、警察やマスメディアに対し抗議声明が発表された。

第1審において、安田に対して懲役2年が求刑されたが、2003年12月24日、東京地裁は、検察側の主張を退け、安田の不動産会社への助言に違法性はなかったとし、無罪判決をしたため、検察側は控訴した。

控訴審においては、約2100人の弁護士が弁護人となった。審理において、検察側は、安田は賃料収入を債権者に差押えられぬよう確保することを不動産会社社長と共謀しており、強制執行妨害罪が成立するとして無罪判決の破棄を求めた。これに対し被告人である安田側は、控訴審で検察側は新証拠を一切提出しておらず、安田は違法性のない会社再建構想を示しただけであるから、原審が示した無罪判決は正当であるとして、控訴棄却を求めた。

2008年4月23日、東京高裁（池田耕平裁判長）は、安田の強制執行妨害共謀を認めたが、最終決定は会社側にあり安田は幇助罪にとどまるとし、第1審（東京地裁）の無罪判決を破棄して、罰金50万円の逆転有罪判決を下した。これに対し東京高検の鈴木和宏次席検事は会見を開き、有罪となったことは評価できるものの罰金刑にとどまった点が遺憾であるとの見解を示した。

2011年12月6日、最高裁第3小法廷（那須弘平裁判長）は6日付で検察側、被告側双方の上告を棄却する決定をした。これにより一審無罪判決を破棄し、ほう助罪の成立を認めて罰金50万円の逆転有罪とした二審東京高裁判決が確定した。安田は最高裁の判決後に、自分は無実で検察が証拠を捏造しており、判決は「検察のメンツを立てつつ、私の弁護士資格を奪わない罰金刑で一件落着にするという壮大な妥協」であるとコメントしている［5］。

［source：］安田好弘 - Wikipedia https://ja.wikipedia.org/wiki/%E5%AE%89%E7%94%B0%E5%A5%BD%E5%BC%98
```

　上記の引用部分に，「2008年4月23日、東京高裁（池田耕平裁判長）は、安田の強制執行妨害共謀を認めたが、最終決定は会社側にあり安田は幇助罪にとどまるとし、第1審（東京地裁）の無罪判決を破棄して、罰金50万円の逆転有罪」とあります。最終決定の有無が幇助罪という認定は，参考になりました。

　オウム真理教事件は，平成7年だったと思います。当時私は福井刑務所に服役中でした。確認はしていないものの教祖も地下鉄サリン事件からほどなく逮捕されており，初公判が1年後と仮定しても，そこから7年10ヶ月というのは平成15年辺りに及びそうです。

　1998年12月5日というのは平成10年で，北安江の借家に住んでいた頃，まだ，関係者KYNの配管設備の会社で仕事をしていた頃になります。この12月の月末で，再審請求を諦め配管の仕事に専念することを迫られ，事実上の解雇となりました。

　昨日も記述しておこうと考えていたのですが，Visual C++というWindowsのアプリ開発のソフトを買ったのも，関係者KYNの配管設備の会社を解雇となり，失業した直後のことであったと思います。昼に，八甲田山という映画をテレビでみたことも，同じ頃のこととして強い印象として記憶に残っています。

　7年10月も続いたというオウム真理教事件教祖の刑事裁判の一審ですが，裁判の様子をテレビで見た記憶が少なく，いつごろの裁判だったのかと考えることはありました。当初20年という話がありましたが，本日見た情報では30年という見通しもあったようです。一審に掛かる時間のことです。

　安田好弘弁護士が逮捕されていなければ，主任弁護人だったという安田好弘弁護士の思惑通り，さらに長期化していたとも考えられます。国民の相当数の刑事裁判に対する愛想尽かしが，このオウム真理教事件の麻原彰晃教祖の一審刑事裁判であったとも思われ，弁護士鉄道の転機になったとも考えます。

* 脳機能障害を負った少女の一家から示談不成立と5千万円以上着服した弁護士のニュースに対する、2015年7月22日の深澤諭史弁護士の反応の記録（2020年10月17日）

:CATEGORIES: 深澤諭史弁護士

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-10-17 21:15／2015/08/08 10:31 URL： https://twitter.com/kk_hirono/status/1317439138149199872 https://twitter.com/hirono_hideki/status/629827354567811072  

> ブログ更新： 当時１０代だった一家の長女は平成１８年１月、自転車で帰宅途中、自宅近くの交差点で出合い頭にトラックと衝突。一時は意識不明の重体となり、脳機能障害が残った。 http://t.co/6Xjrr39VkQ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-10-17 21:15／2015/11/30 11:40 URL： https://twitter.com/kk_hirono/status/1317439167714897920 https://twitter.com/hirono_hideki/status/671156922662326272  

> さっきのと同一人物ですか……。開いた口が塞がらないよ……。&amp;#10;脳機能障害を負った少女の一家から着服 「示談不成立」とウソ #ldnews https://t.co/mKQvyPvGDj／（深澤諭史弁護士のリツイート） -... https://t.co/1XexXBFnlJ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-10-17 21:16／2018/01/05 12:05 URL： https://twitter.com/kk_hirono/status/1317439382303825920 https://twitter.com/hirono_hideki/status/949114709990666240  

> 脳機能障害少女家族の弁護士被害に対する、深澤諭史弁護士の反応の記録 - Google フォト https://t.co/MD0TiyBpa5  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-10-17 21:17／2019/06/21 15:02 URL： https://twitter.com/kk_hirono/status/1317439466739437568 https://twitter.com/hirono_hideki/status/1141949567950213121  

> 2019年06月21日14時39分の登録： ％@yukihirosasamo　ささもひょんⁿ@赤腹魔王％さっきのと同一人物ですか……。開いた口が塞がらないよ……。\n脳機能障害を負った少女の一家から着服 「示談不成立」とウソ https://t.co/3E5XOvJ98U  

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「脳機能障害」の検索結果 - Twilog https://t.co/4TPMeGXT1Q

```
(py37_env) ➜  ~ dp -p|grep 2015-07-22
 - 2017年10月09日14時17分の登録： REGEXP：”無邪気”／深澤諭史弁護士（@fukazawas）のツイートの記録（2015-07-22〜2017-02-20／2017年10月09日14時17分・8件） http://hirono2014sk.blogspot.com/2017/10/regexpfukazawas2015-07-222017-02.html
 - 2017年10月09日15時22分の登録： ％@s_hirono　非常上告-最高検察庁御中_ツイッター％2015-07-22-192255_深澤諭史@fukazawas＞ＲＴ自由競争とか，市場原理とか，無邪気にいっている先生，特に佐藤幸治先生とか http://hirono2014sk.blogspot.com/2017/10/shirono-2015-07-22-192255fukazawas.html
 - 2017年10月09日15時24分の登録： ％@s_hirono　非常上告-最高検察庁御中_ツイッター％2015-07-22-192154_自由競争とか，市場原理とか，無邪気にいっている先生，特に佐藤幸治先生 http://hirono2014sk.blogspot.com/2017/10/shirono-2015-07-22-192154.html
 - 2018年05月22日07時16分の登録： TWEET：”2015-07-22 10:39〜2015-07-22 23:19”／深澤諭史（@fukazawas）の検索（2018年05月22日07時16分の記録15件） http://hirono2014sk.blogspot.com/2018/05/tweet2015-07-22-10392015-07-22.html
 - 2019年06月21日14時27分の登録： TWEET：”2015-07-22 10:39〜2015-07-22 23:19”／深澤諭史（@fukazawas）の検索（2019年06月21日14時26分の記録23件） http://hirono2014sk.blogspot.com/2019/06/tweet2015-07-22-10392015-07-22.html
 - 2020年07月01日00時51分の登録： TWEET：”2015-07-22 19:09〜2015-07-22 19:21”／データベース登録済みツイート2020年07月01日00時51分の記録：ユーザ・投稿：1／2件） http://hirono2014sk.blogspot.com/2020/07/tweet2015-07-22-19092015-07-22.html
 - 2020年07月01日00時51分の登録： TWEET：”2015-07-22 10:39〜2015-07-22 23:19”／深澤諭史（@fukazawas）の検索（2020年07月01日00時51分の記録27件） http://hirono2014sk.blogspot.com/2020/07/tweet2015-07-22-10392015-07-22.html
 - 2020年08月18日10時10分の登録： REGEXP：”ウソ”／深澤諭史（@fukazawas）の検索（2015-07-22〜2020-08-16／2020年08月18日10時10分の記録120件） http://hirono2014sk.blogspot.com/2020/08/regexpfukazawas2015-07-222020-08.html
```

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2015/07/22 18:49 URL： https://twitter.com/fukazawas/status/623791961539919873

> ＞ＲＴ  
> 自由競争とか，市場原理とか，無邪気にいっている先生，特に佐藤幸治先生とかには，百回くらい読んで頂きたい記事ですね。  
> (＃･∀･)  

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2015年07月22日 - Twilog https://t.co/8O2uT05Y9i

開いた口が塞がらないよ……。 脳機能障害を負った少女の一家から着服 - Google 検索 https://t.co/LZg97PDpzo

奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: REGEXP：”脳機能障害．＊少女”／データベース登録済みツイート：2018年04月10日02時38分の記録：ユーザ・投稿：5／23件 https://t.co/CPGbejkfwD

▶（01／23） TW yukihirosasamo（ささもたん@赤腹魔王） 日時： 2015-07-23 03:46 URL： <https://twitter.com/yukihirosasamo/status/623791245568012288>
{% tweet 623791245568012288 %}
> さっきのと同一人物ですか……。開いた口が塞がらないよ……。 \n 脳機能障害を負った少女の一家から着服 「示談不成立」とウソ #ldnews http://t.co/BW3bqtjmAW target="_blank">http://t.co/BW3bqtjmAW

▶（02／23） RT fukazawas（深澤諭史）｜yukihirosasamo（ささもたん@赤腹魔王） 日時：2015-07-23 03:48／2015-07-23 03:46 URL： <https://twitter.com/fukazawas/status/623791767637225472> <https://twitter.com/yukihirosasamo/status/623791245568012288>
{% tweet 623791767637225472 %}
> さっきのと同一人物ですか……。開いた口が塞がらないよ……。 \n 脳機能障害を負った少女の一家から着服 「示談不成立」とウソ #ldnews http://t.co/BW3bqtjmAW target="_blank">http://t.co/BW3bqtjmAW

- RT fukazawas（深澤諭史）｜yukihirosasamo（ささもたんⁿ@赤腹魔王） 日時：2015/07/22 18:48／2015/07/22 18:46 URL： https://twitter.com/fukazawas/status/623791767637225472 https://twitter.com/yukihirosasamo/status/623791245568012288

> RT @yukihirosasamo: さっきのと同一人物ですか……。開いた口が塞がらないよ……。  
> 脳機能障害を負った少女の一家から着服 「示談不成立」とウソ #ldnews http://t.co/BW3bqtjmAW  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜yukihirosasamo（ささもたんⁿ@赤腹魔王） 日時：2020-10-17 21:31／2015/07/22 18:46 URL： https://twitter.com/kk_hirono/status/1317443164978835457 https://twitter.com/yukihirosasamo/status/623791245568012288  

> さっきのと同一人物ですか……。開いた口が塞がらないよ……。 脳機能障害を負った少女の一家から着服 「示談不成立」とウソ #ldnews http://t.co/BW3bqtjmAW  

 - 2019年06月21日14時39分の登録： ％@yukihirosasamo　ささもひょんⁿ@赤腹魔王％さっきのと同一人物ですか……。開いた口が塞がらないよ……。\n脳機能障害を負った少女の一家から着服 「示談不成立」とウソ http://hirono2014sk.blogspot.com/2019/06/yukihirosasamon.html

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-17 21:36／2020/10/17 21:35 URL： https://twitter.com/kk_hirono/status/1317444265501360129 https://twitter.com/s_hirono/status/1317444112027504640  

> 2020-10-17-213231_ささもたんⁿ@赤腹魔王@yukihirosasamoさっきのと同一人物ですか……。開いた口が塞がらないよ……。脳機能障害を負った少女の一家か.jpg https://t.co/5x4VU2ELUw  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-17 21:36／2020/10/17 21:35 URL： https://twitter.com/kk_hirono/status/1317444291975815170 https://twitter.com/s_hirono/status/1317444039197683712  

> 2020-10-17-213215_ささもたんⁿ@赤腹魔王@yukihirosasamoさっきのと同一人物ですか……。開いた口が塞がらないよ……。脳機能障害を負った少女の一家か.jpg https://t.co/rLxrpYrNRV  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-17 21:40／2020/10/17 21:39 URL： https://twitter.com/kk_hirono/status/1317445402409328641 https://twitter.com/s_hirono/status/1317445235866177539  

> 2020-10-17-213945_深澤諭史@fukazawas＞ＲＴ自由競争とか，市場原理とか，無邪気にいっている先生，特に佐藤幸治先生とかには，百回くらい読んで頂きたい記事.jpg https://t.co/AC58lwwQf7  

* 




