* 金沢地方検察庁御中: REGEXP：”死刑賛成弁護士．＊（文春新書）”／データベース登録済みツイート：2020年07月27日16時33分の記録：ユーザ・投稿：48／66件
  :LOGBOOK:
  CLOCK: [2020-07-27 月 16:47]
  :END:

:CATEGORIES: 死刑制度,弁護士,犯罪被害者

〉〉〉：Emacs： 2020-07-27（月曜日）16：47　 〉〉〉

　ざっと見たところリツイートが多く，ツイートの数は6,7件ほどかと思いました。本の装丁というかカバーが印象的で，2,3日前にも一度は見ていたと思うのですが，今回はふと，「がきデカ」という漫画のことを思い出しました。たしか「死刑」がギャグになっていたと思います。

　週刊少年チャンピオンの連載で，まだ辺田の浜に住んでいた頃と記憶にあるので，昭和50年4月より前のことになります。小学校の高学年になってから見たとも思うので，昭和50年前後になるかと思うのですが，それより後になるのかもしれません。

```
『がきデカ』は、山上たつひこによる日本の漫画。主人公である日本初の少年警察官と自称するこまわり君と、彼が通う「逆向（さかむけ）小学校」の同級生やその周辺のキャラクター達で展開されるギャグ漫画作品。『週刊少年チャンピオン』（秋田書店）にて、1974年44号から1980年52号まで連載され、単行本の発行部数は3000万部を超える［1］。

1989年にテレビアニメ化、ほぼ同時にOVAも作られているが、双方で制作会社と出演声優が異なる。時期や態勢の異なる再アニメ化は珍しくないが、同時に異なる会社でアニメ化されたケースは当時大変珍しかった。

［source：］がきデカ - Wikipedia https://ja.wikipedia.org/wiki/%E3%81%8C%E3%81%8D%E3%83%87%E3%82%AB
```

　昭和49年の44号からの連載とあります。かなりピンポイントで当たったと思うのですが，昭和55年の52号まで連載が続いていたというのはかなり意外でした。長くて2,3年と思っていました。能都中学校になると週刊少年チャンピオンは，ほとんど読まなかったのかもしれません。

　ちょっと見かけた画像で，記憶にあるより変態っぽい漫画だったのだと思ったのですが，1989年にテレビアニメ化というのは全く知らずにいました。昭和64年から平成元年になった年です。

がきデカ　死刑 - Google 検索 https://t.co/j82zwMVG41

　がきデカという漫画の死刑というギャグが，問題視された記憶は全くなかったのですが，組み合わせで検索をしてみても具体的な情報は見当たりませんでした。昭和40年代も50年代もテレビのニュースやワイドショーで，実際の死刑のニュースや話題を見たのも余り記憶にありません。

　大きな報道を繰り返してテレビでみたと記憶にあるのは，大久保清という連続殺人犯で，死刑になったのではと思います。同じ連続殺人で宮崎勤の事件があってからテレビでよく死刑の問題を見かけるようになったと記憶にあります。

大久保清 - Google 検索 https://t.co/jXiAuimcDv

　Googleの画像検索でいくつか顔写真が出てきたのですが，かすかな記憶にあるのとは，別人のような印象を受けました。ずっと前にも調べたことはあったのですが，当時のGoogle検索では余り写真が出てこなかったのかもしれません。

　警察が被疑者を孤独にさせることで自供させたというのと，被害者の女性に県庁の臨時職員がいたというのが印象的な事件でした。

```
大久保 清（おおくぼ きよし、1935年1月17日 - 1976年1月22日）は、日本の連続殺人犯。1971年（昭和46年）3月から5月までの2か月足らずの間に、路上で自家用車から声をかけて誘った女性8人を相次いで殺害し、逮捕された。1973年に死刑判決を受け、1976年1月22日に刑が執行された。

［source：］大久保清 - Wikipedia https://ja.wikipedia.org/wiki/%E5%A4%A7%E4%B9%85%E4%BF%9D%E6%B8%85
```

　8人も被害者がいたというのは初めて聞いた話のように感じました。昭和48年に死刑判決，昭和51年に死刑執行とあります。被害者の数が多かったのに裁判も長くはなかった様子で，女性8人殺害のすべてが起訴されたのか気になるところです。

大久保清 - Wikipedia https://t.co/5B92SFm6Sp 死刑確定後の1973年4月3日付で身柄を東京拘置所に移送された[67]。同年10月、大久保は獄中から『訣別の章 死刑囚・大久保清獄中手記』（KKロングセラーズ。編集：大島英三郎）を刊行

大久保清 - Wikipedia https://t.co/5B92SFm6Sp 収監先・東京拘置所で死刑囚・大久保清の死刑が執行された（41歳没）[68][62][69]。死刑確定から2年10か月後の執行は当時「一般死刑囚と比較しても速いスピード執行」だった[68][62]。

大久保清 - Wikipedia https://t.co/5B92SFm6Sp 1983年8月29日、筑波昭による同名書籍を原作としたテレビドラマ『昭和四十六年 大久保清の犯罪』（製作：TBS）が放送された。大久保を演じたのはビートたけし、プロデュースは八木康夫。

　ずいぶん警察に反抗し手こずらせたということが書いてありました。昭和46年とありますが，警察が拷問のような取調べをして冤罪になったという話ばかりを聞いてきた時代のように思います。証拠は揃っていたようなので警察も余り無理な取調べは必要なかったとも思えるところはあります。

【昭和】大久保清の深淵【大事件】 - YouTube https://t.co/u5MK2Mjw1Q

【昭和】大久保清の深淵【大事件】 - YouTube https://t.co/u5MK2Mjw1Q 1,108,202 回視聴•2018/12/28 \n ￼

　時刻は18時48分です。上記の動画を視聴していました。終わってから気がついたのですが，再生回数が100万回を越えているようです。以前はたびたび見聞きする機会のあった大事件ですが，インターネットが普及するようになってからは余り情報を見かけていなかった気がします。

　動画のナレーションの始まりに，死体なき殺人事件として捜査は難航を極めた，というような説明があったかと思います。土を掘り返したような跡を見つけた人がいて，それが遺体の発見になったということですが，その発見がなかったら事件化は出来なかったような気もしてきました。

　精神鑑定ではなく心理鑑定というのが出てきて，中田修という人物の映像が出てきました。あると思った場所を探したところ見つからなかったのですが，平成5年当時，母親から差し入れのあった本の著者だったかもしれません。「犯罪精神医学」だったかもしれません。

　たぶん，まだ記憶が新しかった頃のツイートが１つはありそうな気がします。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中） 日時：2020-07-27 19:00／2013/07/17 10:22 URL： https://twitter.com/kk_hirono/status/1287689193913585665 https://twitter.com/kk_hirono/status/357309333505187843  

> 調べたところこの本は現在でもAmazonにあるみたいです。この情報では発売日が1987/10になっていました。→　http://t.co/hEEXK0Lxkh： 犯罪精神医学: 中田 修: 本 http://t.co/6TXJJeYHGk  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中） 日時：2020-07-27 19:00／2013/07/17 10:19 URL： https://twitter.com/kk_hirono/status/1287689291359895554 https://twitter.com/kk_hirono/status/357308518463832065  

> 精神鑑定について、当時拘置所の独居房にいた私には手持ちの辞書で単語を調べるぐらいしか知識がありませんでした。これより後になるのではと思いますが、「犯罪精神医学」という専門書を母親に差し入れてもたったことがあります。今、この本を探したのですが、簡単には見つかりませんでした。  

刑事告発・非常上告＿金沢地方検察庁御中(@kk_hirono)/「犯罪精神医学」の検索結果 - Twilog https://t.co/iKdEWQmRls

　この本には，表紙の裏面だったかに，団藤重光最高裁長官の推薦文のようなものがあって，「面白い」という言葉に，考えさせられることがありました。中田修という人物は，名前とプロフィールしか見たことがなかったと思いますが，体格などが団藤重光氏に似ているような気がしました。

　この動画の中で，被害者が兄が検事だと話したこと，そのあとに検察官と言ったことで，本当の話に間違いがないと思い殺害を決意したという話を思い出しました，しかし，心理鑑定の面接では警察官であるとか他に身内に自衛官の幹部がいると言われなどと，別の話をしたということです。

　心理鑑定を任された中田修氏は，殺害の動機が謎と結論づけたとのことです。殺害しなければ発覚の危険も高まるわけで，自暴自棄になったままいずれは捕まることを覚悟で，強姦を繰り返したような気もします。それでも殺害されなかった被害者も半数ほどいると説明があったように思います。

　余り正確に動画の記憶はしていないのですが，殺害された8人の被害者のうち警察や検事が身内にいると言ったのは7人で，そのうち本当にいたのは3人とのことでした。一番気になった兄が検事という話は事実なのかわかりませんでした。

　以前に逮捕された事件の不満が警察に対する恨みになっていたような話にもなっていました。心理鑑定は180何日となっていましたが，半年間ということなのでしょう。この注目の高さが，警察に緊張感を与え，慎重な捜査になったという気もしました。

　動画はテレビ番組の放送だと思いますが，控訴しなかったという話はなかったようにも思います。死刑判決が出て控訴しなかったという話も余り聞かないですし，判決確定から2年10ヶ月の死刑執行というのは，自ら早期の執行を強く望むことを表明した死刑囚意外に見ていない気がします。

```
宅間は両親に対して、けんかをした際に「ヤクザを使ってお前らの生活滅茶苦茶にしてやる」「死ぬまで苦しめてやる」と語っていた［6］。

宅間には実兄が一人いたが、破綻した実弟の存在に心を病み、起業の失敗と偽って小刀で首を斬って40代前半のときに自殺している［13］。宅間の母親も長期に渡って心を病み、精神病院に数十年以上入院生活し、2016年末に死去している［19］［13］。父親は事件後酒乱となり入院しているが、獄中の宅間によると「宮崎勤の父のように自殺して欲しかった」と語っている。［20］

［source：］附属池田小事件 - Wikipedia https://ja.wikipedia.org/wiki/%E9%99%84%E5%B1%9E%E6%B1%A0%E7%94%B0%E5%B0%8F%E4%BA%8B%E4%BB%B6
```

　死刑判決の確定から執行までの期間を確認しようと調べたところ，初めて知るような情報が出てきたので，上記に引用しました。兄の自殺，母親の精神病，そして「獄中の宅間によると「宮崎勤の父のように自殺して欲しかった」と語っている。」とあります。

```
犠牲者に対する対応［編集］
この事件で死亡した2年生7名は、2006年に同級生と共に特別に卒業証書を授与され、「小学校を卒業」という形になった［注 5］。さらに、2007年にはこれと同様に、死亡した1年生1名に卒業証書が授与された。また小学校を管理する文部科学省は、被害者遺族らに総額4億円の慰謝料や賠償金を支給した。

［source：］附属池田小事件 - Wikipedia https://ja.wikipedia.org/wiki/%E9%99%84%E5%B1%9E%E6%B1%A0%E7%94%B0%E5%B0%8F%E4%BA%8B%E4%BB%B6
```

　また一つ意外な発見がありました。上記に引用しましたが，「また小学校を管理する文部科学省は、被害者遺族らに総額4億円の慰謝料や賠償金を支給した。」とあります。これは裁判でも和解でもなさそうです。村木厚子さんに検察庁が払った賠償以来，知る2件目かもしれません。

　全部は読んでいないのですが，これだけ大きな事件のWikipediaにしては記述量が少ないようにも感じました。父親や母親との関係というのもこれまで全く知らなかったように思います。4回の離婚については以前に読んだことがあると思うのですが，特に触れられていないようです。

　「死刑賛成弁護士」という本と，その本に対する法クラの弁護士らの反応について記述を始めたところ，今回も思わぬ方向で，大久保清元死刑囚のこと，附属池田小事件の宅間守元死刑囚について，今まで知らなかった発見がありました。

　「死刑賛成弁護士」という本のことで思い出し気になったのは，大津園児死傷事故のことです。弁護士が被害者の先頭に立ち，検察官を凌駕する勢いで，被告人の女性を糾弾，断罪しました。余り知られていないとも思うのですが，会っていない男性に対するストーカー事件で有罪となっています。

　「死刑賛成弁護士」という本のタイトルは，想像を超えた次世代の支柱のようなものを感じるところなのですが，さほど反応は大きくない気もします。再度，死刑賛成弁護士だけでTwitterAPIの検索をしてみます。最低10日間は射程にはっていると思うのですが，正確に分かっていません。

　スクリプトの処理過程でツイートの内容をみていると，やはり同じ弁護士として否定的，批判的なツイートが目立つ感じです。私がかなり徹底した記録を行った「大津　控訴」は，TwitterAPIで，検索結果がゼロというありえない現象が起こっていました。

2020年07月27日20時11分の実行記録 \n twitterAPI-search-lawList-mydql-add.rb "死刑賛成弁護士" \n ツイート数：26/1922 リツイート数：57/1922 トータル：267 \n hiron… https://t.co/h2ar1OXlSU

```
2020年07月27日20時11分の実行記録
twitterAPI-search-lawList-mydql-add.rb "死刑賛成弁護士"
ツイート数：26/1922 リツイート数：57/1922 トータル：267
hirono_hideki 4／0件
kk_hirono 4／0件
s_hirono 0／0件
```

　TwitterAPIでは，長いツイートの全文が取得できないので，別に張り付けを行いました。トータルで267件のツイート，リスト登録の1922件のユーザのツイートが26件，リツイートが57件，そのうち私のアカウントのツイートが4件，4件の計8件となっています。

　1922件のリスト登録アカウントのうち，ツイートが26件ですが，私の2つのアカウントの8件のツイートを引くと18件のツイートになります。私のアカウントのリツイートはないので，そのまま57件が1922件のアカウントの中のリツイートとなっています。

奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中: REGEXP：”死刑賛成弁護士”／データベース登録済みツイート：2020年07月27日20時20分の記録：ユーザ・投稿：62／102件 https://t.co/FWinh8dxQx

 - （005／102） TW sho_ya（shoya） 日時： 2020-07-11 13:43:00 +0900 URL： https://twitter.com/sho_ya/status/1281811402999521281

> ご紹介。／
> 文春新書『死刑賛成弁護士』犯罪被害者支援弁護士フォーラム | 新書 - 文藝春秋BOOKS https://t.co/FOFDxQvGRw

 - （034／102） TW FLetlRmdM7gs5vS（ふなざわひろゆき） 日時： 2020-07-19 14:21:00 +0900 URL： https://twitter.com/FLetlRmdM7gs5vS/status/1284720077816750082

> 犯罪被害者支援などで活躍される弁護士さんによる「死刑賛成弁護士」。購入させて頂きました。まだ読めていませんが、もともと、弁護士の手による死刑賛成の立場にたった著書は少なく、また、各章ごとに執筆者が異なるため多面的な死刑賛成論を知る… https://t.co/g2G4swedIf

 - （037／102） TW shiraishilo（白石　資朗） 日時： 2020-07-21 21:37:00 +0900 URL： https://twitter.com/shiraishilo/status/1285554546375225345

> 「死刑賛成弁護士」を読みました。説得力を感じる部分もありますが、法制度の論評としては、もう少し公平さ・公正さに配慮して欲しいと感じました。

 - （041／102） TW 9L1ZTxR8630irXW（法テラ弁） 日時： 2020-07-25 17:17:00 +0900 URL： https://twitter.com/9L1ZTxR8630irXW/status/1286938665634037761

> 「冤罪防止のために日本の刑事手続きは進化しており、冤罪の可能性は低くなっているのです。」死刑賛成弁護士 (文春新書)
>
> そうは思いません。

 - （068／102） TW kouya7977（林宏弥） 日時： 2020-07-26 00:11:00 +0900 URL： https://twitter.com/kouya7977/status/1287042754028007425

> 文春新書の死刑賛成弁護士75頁に記載されている「冤罪防止のために日本の刑事手続きは進化しており、冤罪の可能性は低くなっているのです。」との記載について、私見ですが、筆者が挙げられている「取り調べの可視化、科学的捜査方法などの施策」によりそれがない場合と比べて(続く)

 - （079／102） TW tatsurawoburi（タツ弁（たつらを）） 日時： 2020-07-26 11:46:00 +0900 URL： https://twitter.com/tatsurawoburi/status/1287217702369517574

> 死刑賛成弁護士という書籍が話題になっているが、死刑反対運動もこういう形でやってほしいところ。様々な立場の弁護士がいるのは当然なので、強制加入団体の日弁連が政治声明を出すことはそろそろやめるべき。

 - （084／102） TW tajima38186887（肉弁護士@士業から事業へ） 日時： 2020-07-26 17:26:00 +0900 URL： https://twitter.com/tajima38186887/status/1287303388661612547

> 文春新書から『死刑賛成弁護士』発売されました。
> 執筆者の一人として参加していますので、もしご興味ある方は読んでみてください（kindleもあります）。
>
> https://t.co/uc0wpdjD0S

〈〈〈：Linux Emacs： 2020-07-27（月曜日）21：12 　〈〈〈

