* LinuxのMySQLのデータベースとWindows10のWSL2のMySQLのデータベースを同期（同じ状態）にするため自作したRubyのスクリプト

:CATEGORIES: MySQL,Windows10

>|ruby|
#!/usr/bin/ruby
# coding:utf-8
require "date"
require "open3"
require "fileutils"

date = DateTime.now.strftime("%Y-%m-%d_%H%M")
#@u = "./ubuntu-last-cmd_#{date}.txt"
@u = "./ubuntu-last-cmd.txt"
`rm "#{@u}"`
@w = "./sql-cmd.txt"
`rm "#{@u}"

def db_export(d, t)
    
    db = d
    table = t
    

    db_last_id = `mysql -u hirono-hideki-01  #{db} -e 'select max(id) from #{table};'`.to_s.split(/\n/)[1].to_i
    ucmd = "mysqldump -u hirono-hideki-01  -t #{db} #{table} --where 'id>#{db_last_id}'  > #{db}-#{table}.sql"
        puts ucmd
    File.open(@u, mode = "a"){|f|
    f.write(ucmd + "\n")  # ファイルに書き込む
    }
    
    wcmd =  "mysql -u hirono-hideki-01  -t #{db} < #{db}-#{table}.sql"
    File.open(@w, mode = "a"){|f|
        f.write(wcmd + "\n")  # ファイルに書き込む
    }    
    puts "##{db}-#{table} max_id = #{db_last_id}"
    
end

db_export("benngosi_twitter", "tw_user_tweet")
db_export("benngosi_twitter", "tw_hirono_tweet")
db_export("benngosi_twitter", "tw_user_tweet_MOF")

blog = %w(blogger2016k blogger_hirono2014sk cocolog hatena youtubes blogger_hirono2017kk hatena201912 blogger_hironokk2020)

blog.each do |x|
    db_export("blog", x)
end

db_export("hirono2016k_wpcom", "wp_posts")
#db_export("wp2016s", "wp_posts")
db_export("hirono2016kk_wpcom", "wp_posts")

||<

　Ubuntuの場合は，utowというコマンド名にしています。これを実行するとカレントディレクトリにubuntu-last-cmd.txtというファイルが作成されます。

　次がコマンドを実行し作成したテキストファイルの内容です。これは次回，Windows10の環境でデータベースの変更をした場合に使うものです。

```
(py37_env) ➜  sql cat ubuntu-last-cmd.txt 
mysqldump -u hirono-hideki-01  -t benngosi_twitter tw_user_tweet --where 'id>496155'  > benngosi_twitter-tw_user_tweet.sql
mysqldump -u hirono-hideki-01  -t benngosi_twitter tw_hirono_tweet --where 'id>32719'  > benngosi_twitter-tw_hirono_tweet.sql
mysqldump -u hirono-hideki-01  -t benngosi_twitter tw_user_tweet_MOF --where 'id>611'  > benngosi_twitter-tw_user_tweet_MOF.sql
mysqldump -u hirono-hideki-01  -t blog blogger2016k --where 'id>1165'  > blog-blogger2016k.sql
mysqldump -u hirono-hideki-01  -t blog blogger_hirono2014sk --where 'id>65910'  > blog-blogger_hirono2014sk.sql
mysqldump -u hirono-hideki-01  -t blog cocolog --where 'id>1252'  > blog-cocolog.sql
mysqldump -u hirono-hideki-01  -t blog hatena --where 'id>5799'  > blog-hatena.sql
mysqldump -u hirono-hideki-01  -t blog youtubes --where 'id>1106'  > blog-youtubes.sql
mysqldump -u hirono-hideki-01  -t blog blogger_hirono2017kk --where 'id>756'  > blog-blogger_hirono2017kk.sql
mysqldump -u hirono-hideki-01  -t blog hatena201912 --where 'id>985'  > blog-hatena201912.sql
mysqldump -u hirono-hideki-01  -t blog blogger_hironokk2020 --where 'id>34'  > blog-blogger_hironokk2020.sql
mysqldump -u hirono-hideki-01  -t hirono2016k_wpcom wp_posts --where 'id>5289'  > hirono2016k_wpcom-wp_posts.sql
mysqldump -u hirono-hideki-01  -t hirono2016kk_wpcom wp_posts --where 'id>38'  > hirono2016kk_wpcom-wp_posts.sql
```

　Windows10のWSL2環境では前回に，win-last-cmd.txtというテキストファイルを作成しています。次がファイルの内容ですが，テキストファイルの内容をbashにパイプで渡し，実際にコマンドを実行しデータベースの追加用のsqlファイルを作成します。

```
(py37_env) ➜  sql cat win-last-cmd.txt 
mysqldump -u hirono-hideki-01  -t benngosi_twitter tw_user_tweet --where 'id>494566'  > benngosi_twitter-tw_user_tweet.sql
mysqldump -u hirono-hideki-01  -t benngosi_twitter tw_hirono_tweet --where 'id>31943'  > benngosi_twitter-tw_hirono_tweet.sql
mysqldump -u hirono-hideki-01  -t benngosi_twitter tw_user_tweet_MOF --where 'id>611'  > benngosi_twitter-tw_user_tweet_MOF.sql
mysqldump -u hirono-hideki-01  -t blog blogger2016k --where 'id>1165'  > blog-blogger2016k.sql
mysqldump -u hirono-hideki-01  -t blog blogger_hirono2014sk --where 'id>65910'  > blog-blogger_hirono2014sk.sql
mysqldump -u hirono-hideki-01  -t blog cocolog --where 'id>1252'  > blog-cocolog.sql
mysqldump -u hirono-hideki-01  -t blog hatena --where 'id>5799'  > blog-hatena.sql
mysqldump -u hirono-hideki-01  -t blog youtubes --where 'id>1106'  > blog-youtubes.sql
mysqldump -u hirono-hideki-01  -t blog blogger_hirono2017kk --where 'id>756'  > blog-blogger_hirono2017kk.sql
mysqldump -u hirono-hideki-01  -t blog hatena201912 --where 'id>975'  > blog-hatena201912.sql
mysqldump -u hirono-hideki-01  -t blog blogger_hironokk2020 --where 'id>34'  > blog-blogger_hironokk2020.sql
mysqldump -u hirono-hideki-01  -t hirono2016k_wpcom wp_posts --where 'id>5289'  > hirono2016k_wpcom-wp_posts.sql
mysqldump -u hirono-hideki-01  -t hirono2016kk_wpcom wp_posts --where 'id>38'  > hirono2016kk_wpcom-wp_posts.sql
```

　ipythonコマンドから計算式を実行しましたが，1589件の追加となっていました。

```
In [2]: print('{} - {} = {}'.format(496155, 494566 , 496155 - 494566))
496155 - 494566 = 1589
```

　このあとWindows10に移動して作業を行う予定なので，Windows10のWSL2のMySQLのデータベースを更新するためのsqlのテキストファイルを作成しました。

```
(py37_env) ➜  sql ls
sql-cmd.txt  ubuntu-last-cmd.txt  win-last-cmd.txt
(py37_env) ➜  sql cat win-last-cmd.txt | bash
(py37_env) ➜  sql ls
benngosi_twitter-tw_hirono_tweet.sql    blog-blogger_hirono2014sk.sql  blog-hatena.sql                 hirono2016kk_wpcom-wp_posts.sql
benngosi_twitter-tw_user_tweet.sql      blog-blogger_hirono2017kk.sql  blog-hatena201912.sql           sql-cmd.txt
benngosi_twitter-tw_user_tweet_MOF.sql  blog-blogger_hironokk2020.sql  blog-youtubes.sql               ubuntu-last-cmd.txt
blog-blogger2016k.sql                   blog-cocolog.sql               hirono2016k_wpcom-wp_posts.sql  win-last-cmd.txt
(py37_env) ➜  sql 
```

　benngosi_twitter-tw_hirono_tweet.sqlなどというsql文のテキストファイルが作成されていますが，これらをまとめて，次にWindows10のWSL2のUbuntuにログインしたとき，「cat sql-cmd.txt | bash」というコマンドを実行します。

```
(py37_env) ➜  sql cat sql-cmd.txt 
mysql -u hirono-hideki-01  -t benngosi_twitter < benngosi_twitter-tw_user_tweet.sql
mysql -u hirono-hideki-01  -t benngosi_twitter < benngosi_twitter-tw_hirono_tweet.sql
mysql -u hirono-hideki-01  -t benngosi_twitter < benngosi_twitter-tw_user_tweet_MOF.sql
mysql -u hirono-hideki-01  -t blog < blog-blogger2016k.sql
mysql -u hirono-hideki-01  -t blog < blog-blogger_hirono2014sk.sql
mysql -u hirono-hideki-01  -t blog < blog-cocolog.sql
mysql -u hirono-hideki-01  -t blog < blog-hatena.sql
mysql -u hirono-hideki-01  -t blog < blog-youtubes.sql
mysql -u hirono-hideki-01  -t blog < blog-blogger_hirono2017kk.sql
mysql -u hirono-hideki-01  -t blog < blog-hatena201912.sql
mysql -u hirono-hideki-01  -t blog < blog-blogger_hironokk2020.sql
mysql -u hirono-hideki-01  -t hirono2016k_wpcom < hirono2016k_wpcom-wp_posts.sql
mysql -u hirono-hideki-01  -t hirono2016kk_wpcom < hirono2016kk_wpcom-wp_posts.sql
```

* 《参考資料》「悪口一つでも令状とって強制捜査してくれたりする。一時期のストーカー案件における改善を彷彿とさせるレベル。」という令和2年10月1日の深澤諭史弁護士のツイート

:CATEGORIES: 深澤諭史弁護士,警察,ストーカー,誹謗中傷

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2020/10/01 14:28 URL： https://twitter.com/fukazawas/status/1311538524391317505  

> 最近，ネット上の誹謗中傷等については，警察の動きが明らかに良くなっているな・・。悪口一つでも令状とって強制捜査してくれたりする。一時期のストーカー案件における改善を彷彿とさせるレベル。もっとも，表現の自由の問題もあるし，一 @fukazawas #note https://t.co/Q59RQdzZRO  

　リンクの記事があったことを忘れていたのですが，開いたところnoteの記事ではなく，つぶやきとなっていました。

最近，ネット上の誹謗中傷等については，警察の動きが明らかに良くなっているな・・。悪口一つでも令状とって強制捜査してくれたりする。一時期のストーカー案件における改善を彷彿とさせるレベル。もっとも，表現の自｜深澤諭史｜note https://note.com/fukazawas/n/n507d4ca02da6

　次がnoteのつぶやきの全文になりますが，深澤諭史弁護士のツイートにもある記事のタイトルで途切れているのは，「由の問題もあるし，一般化もできないが・・」という部分です。

```
最近，ネット上の誹謗中傷等については，警察の動きが明らかに良くなっているな・・。悪口一つでも令状とって強制捜査してくれたりする。一時期のストーカー案件における改善を彷彿とさせるレベル。もっとも，表現の自由の問題もあるし，一般化もできないが・・

［source：］最近，ネット上の誹謗中傷等については，警察の動きが明らかに良くなっているな・・。悪口一つでも令状とって強制捜査してくれたりする。一時期のストーカー案件における改善を彷彿とさせるレベル。もっとも，表現の自｜深澤諭史｜note https://note.com/fukazawas/n/n507d4ca02da6
```

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-02 13:04／2020/10/01 19:52 URL： https://twitter.com/kk_hirono/status/1311879682095157248 https://twitter.com/s_hirono/status/1311619981935665152  

> 2020-10-01-194939_深澤諭史@fukazawas·5時間最近，ネット上の誹謗中傷等については，警察の動きが明らかに良くなっているな・・。悪口一つでも令状とって強.jpg https://t.co/2PWucVXxo6  

* 「「この政権、とんでもないところに手を出してきた」　学術会議任命見送られた松宮教授｜政治｜地域のニュース｜京都新聞」という記事から調べた深澤諭史弁護士と共謀罪



** 《参考資料》「「この政権、とんでもないところに手を出してきた」　学術会議任命見送られた松宮教授｜政治｜地域のニュース｜京都新聞」という記事

 :CATEGORIES: 深澤諭史弁護士,共謀罪

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-10-02 13:57／2020/10/02 12:36 URL： https://twitter.com/kk_hirono/status/1311893050587705344 https://twitter.com/hirono_hideki/status/1311872667109081089  

> - 「この政権、とんでもないところに手を出してきた」　学術会議任命見送られた松宮教授｜政治｜地域のニュース｜京都新聞 https://t.co/c7Shz6LALM  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-02 13:58／2020/10/02 13:49 URL： https://twitter.com/kk_hirono/status/1311893198998921216 https://twitter.com/s_hirono/status/1311891125486014464  

> 2020-10-02-124743_個人的な話をすれば、共謀罪の時に「あんなものをつくっては駄目だよ」と、参議院の法務委員会に参考人で呼ばれたので言ったことがある。治安立法とし.jpg https://t.co/j5zBBYECTd  

　Twitterのトレンドから見つけた記事です。記事を見つけたのとトレンドのキーワードが違っているようにも思いますが，同じ問題に関するTwitterのトレンドが次になります。

 - 日本学術会議推薦の6名が菅首相に任命されない異例事態 / Twitter https://twitter.com/i/events/1311639330461417472  

```
　―先生を含めて６人が任命されなかった。

　これがどれだけ重大な問題であるのか、あまり分かっていないのではないか。

　まず、一般公務員の任命と同じだと思ってるようなところがある。菅さんは首相就任の時、「言うことを聞かない者はクビにする」というようなことを言った。学術会議の会員というのは建前上公務員ではあるが、選考基準がはっきり決まっているので、任命権者だからといって自由にクビにするとか任命しないとか、できるわけがない。なぜできないかというと、憲法２３条の学問の自由を保障する必要があるからだ。

　―政権側は、先生を任命しなかった理由についてコメントを避けているが、ご自身はなぜ外されたと考えるか。心当たりは。

　個人的な話をすれば、共謀罪の時に「あんなものをつくっては駄目だよ」と、参議院の法務委員会に参考人で呼ばれたので言ったことがある。治安立法として最悪だということよりも、「そんなものをつくっても多分使えない」と言ったのだ。つくるだけ無駄なもののために政治的空白を大きくするのは、本当に無駄。こんなところにエネルギーを注いだらいけないと言ったのだ。結果、できて３年だが、一度も使われたことがない。政権にとって有益な助言をしてあげたと思っていたのだが、向こうはそう思っていなかったようだ。

　しかし、私個人の問題ではなくて、むしろ学術会議や大学を言うがままに支配したいということの表れだと思っている。何が問題かと言うと、防衛省が多額の研究助成予算で持っている。ところが大学や学術会議は、３年前に確認したが軍事研究はやらないということを言って、あまり応募していない。その代わりに普通の研究経費を上げろと言っているのだが、政府は言うことを聞かない。政府にとってみたら、軍事研究をしろと言っているのに言うことを聞かないのが学者だと思っているはず。ここが多分、本当の問題だと思う。

［source：］「この政権、とんでもないところに手を出してきた」　学術会議任命見送られた松宮教授｜政治｜地域のニュース｜京都新聞(2/3) https://www.kyoto-np.co.jp/articles/-/368847?page=2
```

　立命館大法科大学院の松宮孝明教授，というのは名前を知ったのも初めてかと思いますが，共謀罪に大反対をした学者や弁護士は多数見てきました。立命館大学といえば，あの佐藤博史弁護士も参加する，えん罪を研究する団体にも名を連ねていたと記憶にあります。

立命館大学　えん罪 - Google 検索 https://t.co/kVybNw5HJ3

えん罪救済センター学生ボランティア｜立命館大学 SPORTS&amp;CULTURE https://t.co/XRr5OG62fw

えん罪救済センター https://t.co/1Nre8OAlkI

　名称は記憶になく，記憶にある名称との一致も未確認ですが，Googleで検索をすると「えん罪救済センター」というのが出てきました。

```
設立の目的
「えん罪救済センター」は，刑事事件のえん罪の被害者を支援し救済すること，そしてえん罪事件の再検証を通じて公正・公平な司法を実現することを目指しています。アメリカで1990年代に始まり，全世界に広がりつつある「イノセンス・プロジェクト」の活動を参考にして，司法実務家，法学者，心理学者，情報科学者，一般市民などの有志により，2016年4月1日に設立されました。

　近年，足利事件，布川事件，東電女子社員殺人事件など多くのえん罪事件について再審の結果，無罪が言い渡されてきました。日本の司法制度改革に関する社会的な関心も高まっています。

　えん罪救済センターの活動に，皆様からの幅広いご支援を賜れればと存じます。

2016年4月

えん罪救済センター代表　稲葉光行

［source：］えん罪救済センター http://www.ipjapan.org/
```

　「えん罪救済センター代表　稲葉光行」という人の名前が出てきましたが，これも見覚えはないものです。

```
センターの活動状況
2016年4月1日 えん罪救済センターを設立しました


2016年4月　2日 シンポジウム「志布志事件をくり返すな−冤罪事件の教訓は生かされてきたのか」（＠鹿児島市・県市町村自治会館）において、えん罪救済センターを紹介しました

2016年4月8-9日 イノセンス・ネットワーク・カンファレンス2016の International Organizations Meeting（＠テキサス州サン・アントニオ）でえん罪救済センターを紹介しました

［source：］活動状況 - えん罪救済センター http://www.ipjapan.org/report
```

　活動状況というページに，志布志事件のことが出てきました。大崎事件ほど調べてはいないのですが，一通りの情報は過去に読んでいる志布志事件です。地域における警察と住民，住民と弁護士との関係において深刻に考えさせられる問題性がありそうに思ってきました。

 - 2019年7月 1日「大崎事件」最高裁決定に対する抗議声明 - えん罪救済センター http://www.ipjapan.org/report/-201907-1  

　「えん罪救済センター」というのがすごく目新しく感じるのですが，「市場急配センター」にも似ている文字の並びとなっています。冤罪について再び考えさせられたところですが，ここ1,2日の間にも深澤諭史弁護士のタイムラインで，気になる「えん罪」のツイートがあったように思いました。

 - 構成メンバー - えん罪救済センター http://www.ipjapan.org/home/member  

　このページに，「代　表：稲葉光行（立命館大学　教授）」とあります。下の方を見ていて気が付かなかったのですが，主要メンバーだと思っていた甲南大学の女性教授が副代表ということに，しばらくして気が付きました。「副代表：笹倉香奈（甲南大学　教授）」とあります。

```
松宮 孝明（まつみや たかあき、1958年3月11日 - ）は、日本の法学者。立命館大学法務研究科教授。専門は刑法。博士（法学）。日本刑法学会理事。元民主主義科学者協会法律部会理事［1］。滋賀県出身。

［source：］松宮孝明 - Wikipedia https://ja.wikipedia.org/wiki/%E6%9D%BE%E5%AE%AE%E5%AD%9D%E6%98%8E
```

　深澤諭史弁護士の出身という東京大学法科大学院と東京大学法学部の関係性というのも情報が見当たらず，何もわからなかったのですが，立命館大学に法科大学院があるというのも今日，初めて知ったように思います。

　しかし，Wikipediaでは，「立命館大学法務研究科教授」，「2004年4月 - 立命館大学大学院法務研究科教授」，「2010年4月 - 立命館大学大学院法務研究科研究科長」となっており，法科大学院とは違っているような。再度，記事を確認したのですが，やはり法科大学院となっていました。

```
立命館大法科大学院の松宮孝明教授は１日、京都新聞社の取材に対し、政府が「日本学術会議」会員への自身の任命を見送ったことについて、心境を語った。松宮教授の発言は以下の通り。

［source：］「この政権、とんでもないところに手を出してきた」　学術会議任命見送られた松宮教授｜政治｜地域のニュース｜京都新聞 https://www.kyoto-np.co.jp/articles/-/368847
```

　京都府京都市中京区西ノ京朱雀町1番地が立命館大学法科大学院の住所となっていました。前に立命館大学のキャンパスが滋賀県にあるような情報を見かけていたことを思い出していたのですが，京都弁護士会と同じ京都市内というのは，これも意外な新発見に感じました。

　歌手の倉木麻衣さんが，立命館大学に入学し京都で生活しているという話は，羽咋市に住んでいた頃に知っていたのですが，立命館大学が京都市内にあるとは，知らなかったというか，どこにあるのか余り考えずにいました。

 - 法科大学院　法務研究科　法曹養成専攻 | 立命館大学 http://www.ritsumei.ac.jp/lawschool/  

 - アクセス｜立命館大学 http://www.ritsumei.ac.jp/accessmap/  

```
大学院では、中森喜彦の指導を受けたが、中山研一が佐伯千仭、平場安治などの協力のもとに始めた刑法読書会にも参加しており、相対立する学説を同時に学んだ。過失犯論から研究を始め、著作として、『刑事過失論の研究』（1989年）、『過失犯論の現代的課題』（2004年）がある。中山研一、浅田和茂と共著の『レヴィジオン刑法1 共犯論』（1997年）は共犯論の必読の書。ほかに論文集として『刑事立法と犯罪体系』（2003年）がある。学説は、初期には佐伯千仭説および中山説の影響が強かったが、ボン大学（ライン・フリードリヒ・ヴィルヘルム大学ボン）に留学した折にギュンター・ヤコブス (de：Günther Jakobs) に師事し、その学説の影響も受けており［3］、規範的観点を重視した独自の展開を見せていることが注目される。弟子も多く、影響力の大きな刑法学者である。関東と関西で分断が大きい刑法学であるが、山口厚をはじめ、関東の刑法学者からも注目を集めている。刑事訴訟法分野にも近年興味を持っている。

［source：］松宮孝明 - Wikipedia https://ja.wikipedia.org/wiki/%E6%9D%BE%E5%AE%AE%E5%AD%9D%E6%98%8E
```

　中山研一という刑法学者の名前が出てきました。確認のため少し調べてみます。

```
中山 研一（なかやま けんいち、本名：乾 研一［1］（いぬい けんいち）［2］、1927年1月9日 - 2011年7月31日［2］）は、日本の刑法学者。京都大学名誉教授。

目次
1	来歴
2	人物
3	学説
4	著書
5	訳書
6	共訳書
7	脚注
8	関連項目
9	外部リンク
来歴［編集］
滋賀県出身。虎姫中学、旧制静岡高校を経て、1953年京都大学法学部卒業。1955年助手、助教授を経て、1968年同大教授。1982年、京大名誉教授、大阪市立大学法学部教授。1990年北陸大学法学部教授。1998年退職。退職後も、執筆意欲は衰えを見せなかった。滝川幸辰と佐伯千仭の弟子。

2011年7月31日、肺癌のため大津市の病院で死去。84歳没［2］。

［source：］中山研一 - Wikipedia https://ja.wikipedia.org/wiki/%E4%B8%AD%E5%B1%B1%E7%A0%94%E4%B8%80
```

　「滋賀県出身。虎姫中学」とあります。ついさきほども同じような学歴を目にしていました。「1976年3月 - 滋賀県立虎姫高等学校卒業」とある松宮孝明教授のWikipediaです。

 - 中山研一の刑法学ブログ https://knakayam.exblog.jp/  

　ブログがそのまま残っていたので確認ができました。福井刑務所にいる頃に勉強をした刑法の本に，よく中山説というのを見かけていた刑法学者ですが，本の中で名前だけ見かけていた人物が，ブログで情報発信をしていると知ったときは，時代の移り変わりを感じたものです。

　90歳を越えて亡くなったものと今日まで思っていたのですが，2011年7月31日84歳没とありました。ちょうど昭和11年12月生まれの今の安藤健次郎さんの年齢に近いことになりそうです。

　松宮孝明教授の方は，1958年3月11日生まれということで，昭和33年ですが，昭和39年11月生まれの自分とは，けっこう年が近いのだと思いました。

　「共謀罪の時に「あんなものをつくっては駄目だよ」と、参議院の法務委員会に参考人で呼ばれたので言ったことがある。治安立法として最悪だということよりも、「そんなものをつくっても多分使えない」と言ったのだ。」というのも凄いコメントだと思っていました。

　私はもともと共謀罪について長く考えてきた時期があるのですが，共謀での刑事事件に巻き込まれないためにも必要な法律ではないか，市場急配センターの関係者の刑事責任を考える上でも重要な法律ではないかという考えにいました。

** 
