* 「「どのような取り調べが行われているのか」ってドヤってるけど、可視化しろ、で終わりだし」という井上雄樹弁護士（旭川弁護士会）のツイート

:CATEGORIES: 可視化,取調べ

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜yinoue1975（井上雄樹） 日時：2020-09-13 07:50／2020/08/17 17:23 URL： https://twitter.com/kk_hirono/status/1304915328296611841 https://twitter.com/yinoue1975/status/1295275156701470720  

> 「どのような取り調べが行われているのか」ってドヤってるけど、可視化しろ、で終わりだし https://t.co/b2NkNN5fFt  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜yinoue1975（井上雄樹） 日時：2020-09-13 07:51／2020/08/17 17:21 URL： https://twitter.com/kk_hirono/status/1304915473243336704 https://twitter.com/yinoue1975/status/1295274463987081221  

> https://t.co/FpG57JXKoP この人か、見たみたい気もするが、一昔前の話のようだし、金払う価値はなさそう。  

```
検察官側ではどのような取調べが行われているか
刑事事件における被疑者との接見や相談で、
「検察側ではどのような取り調べが行われているのだろうか」
「この被疑者は自分に対してどの程度本当のことを話しているのだろうか」
などと悩まれることはありませんか？

本講義では、東京地検や大阪地検などの特捜部に在籍し、
20年以上取り調べの第一線で活躍した城祐一郎元検事を講師に迎え、
弁護士が知っておくべき取り調べの真相をお届けします。

講義は全て、城氏が立ち会った事件を題材にしています。
被疑者に真相を語らせる上で、担当検事としていかなる覚悟で挑み、成功させてきたか。
また、複雑な詐欺事案で被疑者がいかにして犯罪を成立させていたかなど、
検事だからこそ知っている真実を、テンポ良く解説していただきます。

検事としての重圧の中で被疑者の口を割ってきた城氏の仕事術は、
刑事事件に関わらない弁護士の先生方にも役立つ要素が満載です。


講義内容（約83分）倍速再生機能付（最大2倍速）
第１　特捜部等において被疑者に真実を供述させる必要性
第２　被疑者から真相を引き出さないと生じる不合理の闘い（その１）
第３　法廷でも維持される自白について
第４　被疑者から真相を引き出さないと生じる不合理の闘い（その２）
第５　被疑者が取引を持ち掛けてきた場合の取調べについて
第６　取調べにおいて叱らなければならない場面について
第７　被疑者が家族のことを想う気持ちについて
付属資料（ダウンロード可能）
・講義レジュメ

［source：］元検察官が語る取り調べの真相 ーなぜ被疑者は取調官に対して真実を語るのかー 講師：城 祐一郎 氏 | 弁護士ドットコムオンラインセミナー https://academia-movie.bengo4.com/set/140
```

　見つけるのに少し時間が掛かったのですが，¥12,800(税込)となっています。井上雄樹弁護士のツイートを見たときは，書籍の紹介だとばかり思っていました。

* 「講師である高野隆氏は、調書への署名拒否や黙秘権の行使などを、大論争を巻き起こしながら日本に根付かせたミランダの会の初代代表を務め、刑事弁護の第一人者」という約400分49,800税込み

:CATEGORIES: 高野隆弁護士

```
刑事弁護人の第一人者 高野隆氏らによる法廷技術をオンラインで学ぶ
講師である高野隆氏は、調書への署名拒否や黙秘権の行使などを、大論争を巻き起こしながら日本に根付かせたミランダの会の初代代表を務め、刑事弁護の第一人者として常に日本の法廷技術をはじめとした刑事弁護実務に大きな影響を与え続けてきました。日本の刑事弁護レベル向上のため、法廷技術をはじめとした法曹教育にも力を入れています。本セミナーではそのエッセンスを余すことなくお伝えします。
弁護人の主張は、裁判官や裁判員に届いているか？
裁判の行く末を左右する、弁護士が持つべき「法廷技術」という道具を、本セミナーで手に入れてください。

東京法廷技術アカデミー設立の辞（高野 隆）
「誘導ばかりの主尋問や行きつ戻りつの要領をえない反対尋問では、事件の真相は何も分からない。複雑な文章を棒読みしたのでは、当事者の訴えはけっして伝わらない。法律家は主尋問によって自分の証人に印象的な物語を語らせなければならない。相手方の証人に対する反対尋問を通じて、その証言が信ずるに足りないことをつぶさに示さなければならない。法律家は、口頭表現によって証拠と理性と正義が自己の勝訴を求めていることを説得的に弁じなければならない。」

一般社団法人東京法廷技術アカデミー（TATA）とは
代表理事・高野隆。法律家の間に法廷技術を普及させ、全国に高度の法廷技術を身につけた刑事弁護人を行き渡らせることを目的として2013年開校。各ワークショップはキャンセル待ちが出るほどの人気。多くの弁護士に法廷技術を研鑽する場を提供している。
http：//www.trialadvocacy.jp/



［source：］刑事弁護「法廷技術」セミナー（約400分）高野隆／東京法廷技術アカデミー（TATA） | 弁護士ドットコムオンラインセミナー https://academia-movie.bengo4.com/set/322?fcid=2
```

　講師に高野隆弁護士の他，我妻路人，高山巌という名前がありますが，初めて見る名前に思いました。もう一人，金杉美和という名前がありますが，金杉美和弁護士としてどこかで見たように思います。

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-13 08:20／2020/01/05 00:10 URL： https://twitter.com/kk_hirono/status/1304922941377794048 https://twitter.com/hirono_hideki/status/1213477928777895937  

> 2020年01月05日00時05分の登録： ＼金杉美和　@KanasugiMiwa＼偉そうな言い方で誠に恐縮ですが、すごくまともな記事。 https://t.co/NObYxZImvm  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-13 08:20／2020/06/18 21:48 URL： https://twitter.com/kk_hirono/status/1304922975523622912 https://twitter.com/hirono_hideki/status/1273598517953490944  

> 2020年06月18日10時23分の登録： ＼かもん弓（鴨志田 祐美）　@kamo629782＼同期の尊敬する刑事弁護人、金杉美和弁護士の講演がオンラインで視聴できます(^-^)v https://t.co/tjIhCvKy0A  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-13 08:21／2020/06/27 10:13 URL： https://twitter.com/kk_hirono/status/1304923160513359872 https://twitter.com/hirono_hideki/status/1276685126978506752  

> 2020年06月27日09時39分の登録： REGEXP：”金杉美和”／データベース登録済みツイート：2020年06月27日09時39分の記録：ユーザ・投稿：5／5件 https://t.co/nU4w8U2HdS  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語） 日時：2020-09-13 08:21／2020/06/27 10:13 URL： https://twitter.com/kk_hirono/status/1304923213399425024 https://twitter.com/hirono_hideki/status/1276685153297788928  

> 2020年06月27日09時45分の登録： ＼金杉美和　@KanasugiMiwa＼犯罪を訴追する組織のナンバー2が、犯罪の構成要件に該当する行為をしたゆーてんのに、懲戒処分すらなされない国ってアリ？いや、ないない https://t.co/xMeigyijlR  

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「金杉美和」の検索結果 - Twilog https://t.co/enrDiCKD14

　1つのリツイートで気がつくことができたのですが，金杉美和弁護士は，京アニ放火殺人事件の弁護人の一人の名前だったと思います。もう一人の弁護士も著名な刑事弁護にんですが，京都の弁護士というイメージが強かったです。最近は名前を見ていないですが，名前もはっきり思い出せません。

　なんとか大輔という名前だったような気がします。実績と評価の高い刑事弁護人という感じでした。

* 情報を見かけていなかった京アニ放火殺人事件の国選弁護人，金杉美和弁護士と遠山大輔弁護士，遠山大輔は過去に舞鶴女子高生殺害事件で無罪判決

:CATEGORIES: 遠山大輔弁護士,金杉美和弁護士,高野隆弁護士

 - 913：2020-09-13_08:29:02 ＊ 「講師である高野隆氏は、調書への署名拒否や黙秘権の行使などを、大論争を巻き起こしながら日本に根付かせたミランダの会の初代代表を務め、刑事弁護の第一人者」という約400分49,800税込み https://hirono-hideki.hatenadiary.jp/entry/2020/09/13/082900

　きっかけは上記の高野隆弁護士に関する記事にありますが，金杉美和弁護士と高野隆弁護士の弁護士に接点があったとは意外でした。まだ所属弁護士会を調べていないのですが，京アニ放火殺人事件で国選弁護人に選任されたという金杉美和弁護士は，京都弁護士会の所属と考えられます。

 - 2020年09月13日07時44分の登録： ＼井上雄樹　@yinoue1975＼「どのような取り調べが行われているのか」ってドヤってるけど、可視化しろ、で終わりだし http://hirono2014sk.blogspot.com/2020/09/yinoue1975.html
 - 2020年09月13日08時27分の登録： REGEXP：”金杉美和”／データベース登録済みツイート：2020年09月13日08時27分の記録：ユーザ・投稿：6／11件 http://hirono2014sk.blogspot.com/2020/09/regexp202009130827611.html
 - 2020年09月13日08時53分の登録： REGEXP：”遠山大輔”／データベース登録済みツイート：2020年09月13日08時52分の記録：ユーザ・投稿：16／46件 http://hirono2014sk.blogspot.com/2020/09/regexp2020091308521646.html

```
2020年9月9日 18時19分

「京都アニメーション」の放火殺人事件で逮捕され、専門家による精神鑑定を受けている、青葉真司容疑者（42）について、京都地方検察庁は刑事責任能力をさらに調べるため、鑑定の期間をことし12月まで3か月延長しました。

去年7月、「京都アニメーション」のスタジオが放火され、社員36人が死亡、33人が重軽傷を負った事件では、青葉真司容疑者が殺人などの疑いでことし5月に逮捕されました。

［source：］「京アニ」放火事件 青葉容疑者の鑑定留置を延長 京都地検 | NHKニュース https://www3.nhk.or.jp/news/html/20200909/k10012609431000.html
```

```
京都市右京区太秦で出生。3歳から富山県で育つ

1993年3月
富山県立高岡高校卒業
1993年4月
大阪大学文学部入学
大学時代は体育会航空部の活動に明け暮れる

1999年3月
2年留年の後、大阪大学文学部文学科を卒業
フリーター生活をしていた2000年11月、一念発起して司法試験に挑戦
受験時代は京都の受験予備校（伊藤塾）に通う

2002年11月
司法試験合格
1年間の実務修習を京都で経験
2004年10月
京都法律事務所　入所
2005年、2010年にそれぞれ男の子を出産し、現在2児の母
弁護士会委員会所属

【京都弁護士会】
刑事委員会副委員長
司法修習委員
死刑制度調査検討委員会
法相センター運営委員
検察審査会PT

【日本弁護士連合会】
刑事弁護センター幹事
法廷技術小委員会・元委員長

［source：］金杉美和 http://www.kyotolaw.jp/introduction/furukawa/
```

　ページタイトルには含まれていないですが，京都法律事務所とあります。前に見たことのあるページにも思いましたが，3歳から富山県で育ち，1993年3月富山県立高岡高校卒業という経歴は初めて知りました。卒業高校の情報も珍しく年度まであります。

```
京都法律事務所 (2017年4月15日 16：50)
今年は桜が長いですね。花が咲き始めたら長雨で、その後も晴れたり振ったり。

もっか、明日の天気が心配なワタクシ。なぜなら、明日は円山野外音楽堂で、京都弁護士会主催の共謀罪の制定を阻止する市民集会in京都　が開催されるからです！

私は例によって司会担当。変わり映えしない配役ですみません・・・。

［source：］明日、共謀罪に反対する弁護士会集会＠円山公園です！ - 金杉美和 http://www.kyotolaw.jp/introduction/furukawa/2017/04/post-77.html
```

　共謀罪はずいぶん前に成立したように思ったのですが，2017年4月15日という記事でした。

 - 京都で弁護士をお探しなら京都法律事務所 http://www.kyotolaw.jp/  

　あまり見覚えのない京都法律事務所と思ったのですが，福山和人弁護士の名前がありました。2,3ヶ月ほど前になるのか，京都市長選に立候補し，落選していたと記憶にありますが，知名度が高そうな弁護士で，Twitterのアカウントもあったと思います。最近ツイートは見かけていないです。

```
また高齢化が進む一方、核家族化も進み、身近に頼れる人がいない高齢者の方も増えています。老後の人生を安らかに過ごすために、自分に万一のことが起こったり、認知症等になったときのために転ばぬ先の杖として専門家に相談しながら準備しておきたいという方も増えています。

一昔前なら、どこの町内にも「横町のご隠居さん」といった身近な相談役の方がいましたが、地域の結びつきが希薄になってる今は、そういう方もなかなかおられず、また社会が複雑化する中、専門家抜きで対応することも難しくなっています。

そんなときに頼りになるのが、「かかりつけ弁護士」です。
これは弁護士事務所に会員登録し、皆さんのお困り事や心配事のよろず相談を弁護士に無料で相談にのってもらうものです。
相談の内容に一切制限はありません。「こんなこと弁護士さんにきいていいのかな？」と思われるような相談でも構いません。人生相談でも結構です。何気ない一言に実は大事な問題が隠されていたということもあります。雑談でもしに来るおつもりで、どうぞ気軽にご相談下さい。
また「もうちょっと早めに相談してもらえたら」と思うこともよくあります。あまり肩肘張らずに早め早めにご相談下さい。

私たち京都法律事務所は、1979年の創設時から、「敷居は低く、志は高く」をモットーに、京都のマチ弁として、債務や消費者被害、相続、遺言、離婚、交通事故、借地借家等の一般的事件から、医療や労働・労災、建築、行政など専門性の高い分野まで、市民のみなさんの幅広いニーズにお応えしてきました。私どもでは、かかりつけ弁護士のメニューとして以下の二つをご用意していす。ご希望に応じてご利用頂ければと思います。

［source：］かかりつけ弁護士のススメ - 福山和人 http://www.kyotolaw.jp/introduction/hukuyama/2020/08/post-28.html
```

* 「名古屋高裁が再鑑定許可　名張毒ぶどう酒事件」という日本経済新聞の記事，弁護団は「「真犯人が別の場所で毒物を入れ、貼り直した証拠だ」と主張した」という

:CATEGORIES: 再審請求

```
三重県名張市で1961年、懇親会でぶどう酒を飲んだ女性5人が死亡するなどした名張毒ぶどう酒事件の第10次再審請求の異議審で、名古屋高裁が、ぶどう酒の王冠と瓶をつなぐように貼られた封かん紙の紙片の再鑑定を許可していたことが11日、分かった。奥西勝元死刑囚の弁護団が明らかにした。

弁護団は8月から再鑑定を始めており、終了し次第、新たな証拠として提出する方針。

封かん紙を巡っては、弁護団は第10次再審請求中の2016年1月の鑑定で、製造時と異なるのりの成分が付着していたとして「真犯人が別の場所で毒物を入れ、貼り直した証拠だ」と主張したが、高裁はこれを否定し、17年12月に請求を棄却した。

弁護団によると、当時の鑑定は名古屋高裁に特殊な機器を持ち込み、封かん紙の損傷を避けるため本来より低い圧力で実施されていた。今回は通常の鑑定に近い高圧力をかけることで、明確に成分を検出できるという。

奥西元死刑囚は15年10月に収監先の八王子医療刑務所（東京都八王子市）で病死。代わって妹の岡美代子さん（90）が第10次再審請求し、棄却に対し異議を申し立てた。

［source：］名古屋高裁が再鑑定許可　名張毒ぶどう酒事件　　：日本経済新聞 https://www.nikkei.com/article/DGXMZO63738240R10C20A9000000/
```

　2020/9/11 17:27となっています。深澤諭史弁護士のタイムラインで見かけたニュースです。

RT fukazawas（深澤諭史）｜ryouheitakaki（弁護士 高木良平） 日時：2020-09-13 11:19／2020-09-13 10:56 URL： https://twitter.com/fukazawas/status/1304968023044796417 https://twitter.com/ryouheitakaki/status/1304962046316802049
> 悪名高き名古屋高裁にしては珍しい判断だ…
> 
> 名古屋高裁が再鑑定許可　名張毒ぶどう酒事件: 日本経済新聞 https://t.co/PJGYaitrO1

　これが死刑と無罪の分かれ目になるのかというのも驚いた話で，さらに本人は長い獄中生活の上，獄死しています。弁護士の視点が別にあれば，無実であれば，無実が証明されたのかとも想像します。

* ついに「弁護士消滅」という言葉が頭に浮かんだ，弁護士フィールドをさらに加速化させた最終進化系，深澤諭史弁護士@fukazawasのタイムライン

:CATEGORIES: 深澤諭史弁護士,岩田圭只弁護士

　間接的な記録も交じるかと思いますが，本日のこれまでの記録です。午前中は，白山神社の秋季大祭の神事に出席し，時計の忘れ物があったことで，宇出津新港まで買い物に行き，もどってから直会の弁当を食べました。ある意味，神がかった憑依現象とも思える深澤諭史弁護士の弁護士フィールドです。

 - 2020年09月13日07時20分の登録： REGEXP：”総本山”／データベース登録済みツイートの検索：2020-09-12〜2020-09-12／2020年09月13日07時20分の記録：ユーザ・投稿：4／4件 http://hirono2014sk.blogspot.com/2020/09/regexp2020-09-122020-09-1220200913072044.html

 - 2020年09月13日07時22分の登録： ツイートの記録資料：＼法務検察・石川県警察宛＼／深澤諭史（@fukazawas）／”2020年09月12日”：53件 http://hirono2014sk.blogspot.com/2020/09/fukazawas2020091253.html

 - 2020年09月13日07時24分の登録： 2020-09-12の投稿一覧＼検察・石川県警察宛記録資料＼奉納＼危険生物・弁護士脳汚染除去装置＼金沢地方検察庁御中：24件 http://hirono2014sk.blogspot.com/2020/09/2020-09-1224.html

 - 2020年09月13日07時24分の登録： ＼すか?　@suka_t＼弁護士業界もいいかげんあたまを刷新していただかないと困りますね。 http://hirono2014sk.blogspot.com/2020/09/sukat.html

 - 2020年09月13日07時29分の登録： ＼喜久山大貴　@kikuyamahiroki＼弁護人がペットの生存確認を任されるパターンもあります。 http://hirono2014sk.blogspot.com/2020/09/kikuyamahiroki_13.html

 - 2020年09月13日07時44分の登録： ＼井上雄樹　@yinoue1975＼「どのような取り調べが行われているのか」ってドヤってるけど、可視化しろ、で終わりだし http://hirono2014sk.blogspot.com/2020/09/yinoue1975.html

 - 2020年09月13日08時27分の登録： REGEXP：”金杉美和”／データベース登録済みツイート：2020年09月13日08時27分の記録：ユーザ・投稿：6／11件 http://hirono2014sk.blogspot.com/2020/09/regexp202009130827611.html

 - 2020年09月13日08時53分の登録： REGEXP：”遠山大輔”／データベース登録済みツイート：2020年09月13日08時52分の記録：ユーザ・投稿：16／46件 http://hirono2014sk.blogspot.com/2020/09/regexp2020091308521646.html

 - 2020年09月13日12時42分の登録： ＼深澤諭史　@fukazawas＼（・∀・）医学部の先生方は「医師は成仏出来ればいいだろｗ」「研修医の給料は大反対！」「新人医師の就職難でメシウマｗ」「新人医師がもっとも http://hirono2014sk.blogspot.com/2020/09/fukazawas_96.html

 - 2020年09月13日12時48分の登録： ＼Document35　@document35＼ロー入学者激減の上、予備合格者を制限してるからで、参入規制の加担者も良いところで、業界の守り神なのに、それでも批判されると http://hirono2014sk.blogspot.com/2020/09/document35document35_13.html

 - 2020年09月13日13時01分の登録： ＼米田龍玄　@YonedaRyogen＼ある弁護士が「冤罪は起きない方がいいが、起きても仕方ない、死刑のメリットと冤罪リスクのバランス」と言ったそう。  いやいや￼個人の http://hirono2014sk.blogspot.com/2020/09/yonedaryogen.html

 - 2020年09月13日13時05分の登録： ＼ぎたべん　@guitar_ben＼「真犯人を無罪放免する」という「悪」を許容している以上、被害者側のみに清廉性を求めるのは不均衡だと考えるからです。 ですので、先生や他 http://hirono2014sk.blogspot.com/2020/09/guitarben_13.html

 - 2020年09月13日13時06分の登録： ＼ぎたべん　@guitar_ben＼でなければ「死刑により無実の人を殺すかもしれない」ことを許容してることを頑なに認めないのは理解できない。殺人者である「アイツ」と「同じ http://hirono2014sk.blogspot.com/2020/09/guitarben_46.html

 - 2020年09月13日13時08分の登録： ＼深澤諭史　@fukazawas＼（；・∀・）業務拡大と非弁業者の排除の一挙両得だったんですけれどもねぇ・・。 （；＾ω＾）なお，理由は「まずいですよ」でしたお・・・。 http://hirono2014sk.blogspot.com/2020/09/fukazawas_65.html

 - 2020年09月13日13時11分の登録： ＼深澤諭史　@fukazawas＼（・∀・）私も、以前、ＡＤＲの時に思い知りました。弁護士の仕事増やしたのになあ、、、、。 http://hirono2014sk.blogspot.com/2020/09/fukazawas_74.html

 - 2020年09月13日13時12分の登録： ＼『信仰の』ノースライム　@noooooooorth＼弁護士会(の一部)って、実は職域の拡大に興味ないというか妨害したいのではないか疑惑。弁護士が職域を拡大することよりも http://hirono2014sk.blogspot.com/2020/09/noooooooorth.html

 - 2020年09月13日13時12分の登録： ＼motoryu　@mototakiryu＼単位会にも日弁にも弁護士業務委員会というのがあって、職域拡大に日々努力されている先生は多くいます。業務改革シンポは出られたこと http://hirono2014sk.blogspot.com/2020/09/motoryumototakiryu.html

 - 2020年09月13日13時21分の登録： ＼深澤諭史　@fukazawas＼（＃＾ω＾）直接見聞きしたわけでもなく，具体的にどういう問題があるかわからないけれども，予備校教育を受けた人は，資質に重大な問題があるん http://hirono2014sk.blogspot.com/2020/09/fukazawas_71.html

 - 2020年09月13日13時23分の登録： ＼いわぽん　@yiwapon＼あの頃に予備校を散々敵視していた連中は伊藤真に詫びを入れてくるべきだと思いますよ。予備校が絶対にいいと言うつもりはありませんが。 http://hirono2014sk.blogspot.com/2020/09/yiwapon.html

 - 2020年09月13日13時24分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼ファンを大事にする裁判官「傍聴席～～！見えてるよーー！せり上がってるかーい！？」 http://hirono2014sk.blogspot.com/2020/09/ksawmen_13.html

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 13:51／2020/09/13 13:51 URL： https://twitter.com/kk_hirono/status/1305006248899747840 https://twitter.com/s_hirono/status/1305006200434470912  

> 2020-09-13-125657_深澤諭史さんがリツイート￼ぎたべん@guitar_ben·13時間米田先生の下記ツイートからも、やはり遺族に憎っくき「アイツ」と同じになると.jpg https://t.co/HU3Ml6DBb9  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 13:51／2020/09/13 13:51 URL： https://twitter.com/kk_hirono/status/1305006289492221952 https://twitter.com/s_hirono/status/1305006127432650753  

> 2020-09-13-124138_深澤諭史@fukazawas·1時間（・∀・）医学部の先生方は「医師は成仏出来ればいいだろｗ」「研修医の給料は大反対！」「新人医師の就職難で.jpg https://t.co/oDPFw8LknU  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 13:52／2020/09/13 13:51 URL： https://twitter.com/kk_hirono/status/1305006308395950081 https://twitter.com/s_hirono/status/1305006054812442624  

> 2020-09-13-123503_再審法改正をめざす市民の会　第4回WEBセミナーが開催.jpg https://t.co/AWMK9LEclm  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 13:52／2020/09/13 13:50 URL： https://twitter.com/kk_hirono/status/1305006329904291840 https://twitter.com/s_hirono/status/1305005982276222979  

> 2020-09-13-123105_「真犯人が別の場所で毒物を入れ、貼り直した証拠だ」と主張したが、高裁はこれを否定し、17年12月に請求を棄却した。.jpg https://t.co/HOOoZs17sw  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 13:52／2020/09/13 13:50 URL： https://twitter.com/kk_hirono/status/1305006344504655874 https://twitter.com/s_hirono/status/1305005909584654339  

> 2020-09-13-075205_元検察官が語る取り調べの真相　ーなぜ被疑者は取調官に対して真実を語るのかー　講師：城　祐一郎　氏（全4本）.jpg https://t.co/p7YjC4HhJu  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 13:52／2020/09/13 13:50 URL： https://twitter.com/kk_hirono/status/1305006369997688833 https://twitter.com/s_hirono/status/1305005836889071616  

> 2020-09-12-162805_深澤諭史@fukazawas·2時間法曹養成関係の政府の委員会に呼ばれたら（・∀・）そんなに地方やら眠れる需要やらが本当にあるというなら，真.jpg https://t.co/Sr5QoYMOKM  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜dreamartworld17（ドリームアートワールド公式） 日時：2020-09-13 13:52／2020/08/19 13:10 URL： https://twitter.com/kk_hirono/status/1305006390017056768 https://twitter.com/dreamartworld17/status/1295936249744637952  

> ドリームアートワールド(入場無料/絵画展示販売会)を石川・富山で開催。 ◆WEB予約×来場で、選べるオリジナルグッズをプレゼント！◆  ディズニー公認アーティストが描く魅力的な作品が満載！ 長年受け継がれ変わらないディズニーの想いにぜひ会いに来て下さい。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 13:52／2020/09/13 13:49 URL： https://twitter.com/kk_hirono/status/1305006407595376640 https://twitter.com/s_hirono/status/1305005763832627201  

> 2020-09-12-162625_深澤諭史@fukazawas·1時間あと，弁護士委員が「地方に需要」とか「法テラスの拡大」とかいったら，（・∀・）先生は，今，どこにいらっし.jpg https://t.co/CSTRRPBp9c  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 13:52／2020/09/13 13:49 URL： https://twitter.com/kk_hirono/status/1305006425870016512 https://twitter.com/s_hirono/status/1305005691241865216  

> 2020-09-12-162349_深澤諭史さんがリツイート深澤諭史@fukazawas2016年2月1日「隗より始めよ」といったら，学者の先生からクソだの，淘汰されてしまえだ.jpg https://t.co/X2C1bnDfxw  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 13:52／2020/09/13 13:49 URL： https://twitter.com/kk_hirono/status/1305006454521307137 https://twitter.com/s_hirono/status/1305005618630066178  

> 2020-09-12-135433_深澤諭史@fukazawasそれと，会社によっては，「当社は交通事故を扱う弁護士から非常に評判が悪い，鼻つまみ者となっております。ついては，.jpg https://t.co/SX0aitPITP  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 13:52／2020/09/13 13:49 URL： https://twitter.com/kk_hirono/status/1305006470149275648 https://twitter.com/s_hirono/status/1305005545204543489  

> 2020-09-12-134943_深澤諭史さんがリツイート￼しゃいん@shine_sann·2月11日バズっても何も宣伝するものありませんが（ここまでテンプレ）、尊敬する先生.jpg https://t.co/lNfi6NHapa  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 13:52／2020/09/13 13:48 URL： https://twitter.com/kk_hirono/status/1305006502474780677 https://twitter.com/s_hirono/status/1305005472584327168  

> 2020-09-12-134911_深澤諭史さんがリツイート￼okumuraosaka@okumuraosaka·17時間弁護士ドットコムの電話代行のセールスの電話があった。「.jpg https://t.co/S3tVIclxA4  

@fukazawas ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@fukazawas）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW fukazawas（深澤諭史） 日時：2020/09/13 11:25 URL： https://twitter.com/fukazawas/status/1304969528946769921  

> 旧試験受験生から，受験資格を奪ったとき，一つの命令が来たぞ・・・！！  
> 「予備試験も食い尽くせ！！」  
> #司法獣  

- TW fukazawas（深澤諭史） 日時： 2020/09/13 11:19 URL： https://twitter.com/fukazawas/status/1304967910624907265  

> （・∀・）医学部の先生方は「医師は成仏出来ればいいだろｗ」「研修医の給料は大反対！」「新人医師の就職難でメシウマｗ」「新人医師がもっともっと困窮するようにがんばってるぞｗ」「就職難と借金でお前ら追い詰められてるなｗｗ新たな何かを開いてみろよｗ」とか，いいませんからねぇ・・。 https://t.co/BAVOeZgTY1  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜galaxy_idol02（レーティア） 日時：2020-09-13 13:55／2020/09/13 11:15 URL： https://twitter.com/kk_hirono/status/1305007084203724804 https://twitter.com/galaxy_idol02/status/1304966997533364230  

> 医学部が関所商法しても特段何か言われないけど、ローが問題視されるの国試の合格率と旧試験制度との差からかな  

- TW fukazawas（深澤諭史） 日時： 2020/09/13 11:12 URL： https://twitter.com/fukazawas/status/1304966032637874177  

> 大学の誰かが，ふと思った。  
> 大学の特定の課程を修了しないと司法試験を受けられないようにすれば，学生を獲得できるのではないか。  
> 大学の誰かが，ふと思った。  
> そういう学校を作れば，補助金やポストが増えるのではないか。  
> 大学の誰かが，ふと思った。  
> ワシらの利権と面子を守らねば…。  
> #司法獣  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜document35（Document35） 日時：2020-09-13 13:56／2020/09/13 11:06 URL： https://twitter.com/kk_hirono/status/1305007458067165184 https://twitter.com/document35/status/1304964744235814912  

> 昔、ローがあるから合格者減らせないという意味で、弁護士のロー批判は自己利益のためとか言われたんですよね。 いまや、合格者増やせないのは、ロー入学者激減の上、予備合格者を制限してるからで、参入規制の加担者も良いところで、業界の守り神なのに、それでも批判されるというポンコツ制度ぶり。  

@guitar_ben ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@guitar_ben）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW guitar_ben（ぎたべん） 日時：2020/09/12 23:16 URL： https://twitter.com/guitar_ben/status/1304785839935741954  

> 米田先生の下記ツイートからも、やはり遺族に憎っくき「アイツ」と同じになるとは言えないとの感覚からではないかと思う。 https://t.co/WKyKB3fLWf  

- TW guitar_ben（ぎたべん） 日時： 2020/09/12 22:53 URL： https://twitter.com/guitar_ben/status/1304780211083333632  

> 死刑制度は、やはりどこかで「アイツ（死刑囚）と私達とは違う存在」との感覚を前提としているのではないかと思う。でなければ「死刑により無実の人を殺すかもしれない」ことを許容してることを頑なに認めないのは理解できない。殺人者である「アイツ」と「同じ」になる事を認められないのではないか。  

- TW fukazawas（深澤諭史） 日時： 2020/09/13 11:04 URL： https://twitter.com/fukazawas/status/1304964091388129280  

> （；・∀・）業務拡大と非弁業者の排除の一挙両得だったんですけれどもねぇ・・。  
> （；＾ω＾）なお，理由は「まずいですよ」でしたお・・・。 https://t.co/JyQF51wugK  

- TW fukazawas（深澤諭史） 日時： 2020/09/13 10:33 URL： https://twitter.com/fukazawas/status/1304956295867318272  

> そういや，すごい！っておもったのは，とある超高名な民法学者の大先生が  
> 「ロー制度ができあがれば，相当な利権が生まれる。批判すると，その利権に預かれなくなる。だから，批判して損をすることはあっても，得をすることはない。」  
> って指摘していて，すげーって思いました。  

- TW fukazawas（深澤諭史） 日時： 2020/09/13 10:32 URL： https://twitter.com/fukazawas/status/1304956002249261057  

> （＃＾ω＾）直接見聞きしたわけでもなく，具体的にどういう問題があるかわからないけれども，予備校教育を受けた人は，資質に重大な問題があるんだお！！  
> （；・∀・）本当に，こういうこと言っていましたからね・・。恐るべき思い上がりと，恥ずべき逆恨みの悪魔合体でできあがった制度でした・・。 https://t.co/9oyM1HOAGy  

@yiwapon ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@yiwapon）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW yiwapon（いわぽん） 日時：2020/09/13 10:29 URL： https://twitter.com/yiwapon/status/1304955227775221762  

> 関所設けて資格商法やってるのが根本的な問題なんで予備校が絶対に優れているというつもりはクソほどもないんですよ。ただ文科省は問題の根っこには絶対に触らないので碩学が揃ったところでアレな議論になって結論もアレになってしまうんでしょうね。 https://t.co/W12oSVWuSw  

- TW yiwapon（いわぽん） 日時： 2020/09/12 00:03 URL： https://twitter.com/yiwapon/status/1304435507229646853  

> 本当に、この特別委員会は延々と議論した挙句に出てくるものがこんなものしかないというのだったら、あの頃に予備校を散々敵視していた連中は伊藤真に詫びを入れてくるべきだと思いますよ。予備校が絶対にいいと言うつもりはありませんが。 https://t.co/NDjYJMPWxL  

@k_sawmen ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@k_sawmen）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW k_sawmen（泥濘大魔王サイケ） 日時：2020/09/13 10:17 URL： https://twitter.com/k_sawmen/status/1304952322372452352  

> ファンを大事にする裁判官「傍聴席～～！見えてるよーー！せり上がってるかーい！？」  

- TW fukazawas（深澤諭史） 日時： 2020/09/13 10:14 URL： https://twitter.com/fukazawas/status/1304951551711035397  

> （・∀・）私も、以前、ＡＤＲの時に思い知りました。弁護士の仕事増やしたのになあ、、、、。 https://t.co/Tpt13pA0Nz  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜noooooooorth（『信仰の』ノースライム） 日時：2020-09-13 14:01／2020/09/13 09:57 URL： https://twitter.com/kk_hirono/status/1305008642412879874 https://twitter.com/noooooooorth/status/1304947181485350913  

> 弁護士会(の一部)って、実は職域の拡大に興味ないというか妨害したいのではないか疑惑。弁護士が職域を拡大することよりも個々の弁護士が勝手に新しいことをやるのを止めさせたい欲求の方が強いように見える。構成員の弁護士の行動をコントロールしたい欲求というか。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜document35（Document35） 日時：2020-09-13 14:01／2020/09/12 17:53 URL： https://twitter.com/kk_hirono/status/1305008786260647938 https://twitter.com/document35/status/1304704722121580544  

> 私は、ロースクールの教育が予備校に劣るとは思っていない。 ただ、司法試験合格に最も重要なのは本人の資質と努力で、ロースクールで教育を受けなければ合格できなかったという人は少ないと思っている。 教育の質が悪いというより、有料で受験生の時間を奪って自学自習の邪魔をする点がタチ悪い。  

@guitar_ben ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@guitar_ben）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW guitar_ben（ぎたべん） 日時：2020/09/12 22:23 URL： https://twitter.com/guitar_ben/status/1304772504007786497  

> 本気でそう思うなら、遺族に「死刑も無期懲役も処罰されるのは同じだから廃止で良いか」と聞いて肯定されると思うのだろうか。されるわけがないだろう。当事者にとっては「違う」からこだわってるのだから。  

@guitar_ben ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@guitar_ben）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW guitar_ben（ぎたべん） 日時：2020/09/12 22:21 URL： https://twitter.com/guitar_ben/status/1304772245697359872  

> 「死刑も無期懲役も冤罪はあってはならないのは変わらないから、冤罪死刑を理由に死刑廃止はおかしい」というのは詭弁の極致だろう。当事者にしてみれば、同じはずはないのだから。死刑から生還した冤罪被害者でこれを肯定する者が居ると思うのだろうか。  

 - 2020年09月13日14時05分の登録： ＼ふて寝べん　@hirune_b＼死刑を維持した上で冤罪による死刑を一切許さないと主張するのであれば、死刑囚は冤罪ではあり得ないというフィクションを置くしかなくなると思う http://hirono2014sk.blogspot.com/2020/09/hiruneb_13.html

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜harrier0516osk（向原総合法律事務所　弁護士向原） 日時：2020-09-13 14:08／2020/09/12 22:04 URL： https://twitter.com/kk_hirono/status/1305010539031011328 https://twitter.com/harrier0516osk/status/1304767731690926081  

> 同感ですね 当然、弁護士会からの補助など必要があろうはずもなく、瞬く間に、四大に匹敵する事務所になるはずですよね  そうならんとわかってるから、会員を巻き込んで労働力をうまいこと搾取しようとしてるのが透けて見えるのですよね。 https://t.co/3VfB9exnXO  

- TW fukazawas（深澤諭史） 日時： 2020/09/12 14:24 URL： https://twitter.com/fukazawas/status/1304652041365544961  

> 法曹養成関係の政府の委員会に呼ばれたら  
> （・∀・）そんなに地方やら眠れる需要やらが本当にあるというなら，真っ先に法曹増員派の先生方で「弁護士法人 法の光」でも設立して，真っ先に地方で開業し，あるいは広告でもして眠れる需要を掘り起こしてはいかがでしょうか。  
> って言ってみたい。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 14:10／2020/09/13 14:09 URL： https://twitter.com/kk_hirono/status/1305010897027346432 https://twitter.com/s_hirono/status/1305010626507415553  

> 2020-09-13-140723_￼深澤諭史@fukazawas·16時間誹謗中傷の被害者の方々へ　-　弁護士　深澤諭史のブログ.jpg https://t.co/M42674IXDr  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 14:10／2020/09/13 14:08 URL： https://twitter.com/kk_hirono/status/1305010915834646529 https://twitter.com/s_hirono/status/1305010553845293056  

> 2020-09-13-140700_深澤諭史さんがリツイート￼向原総合法律事務所　弁護士向原@harrier0516osk·16時間同感ですね当然、弁護士会からの補助など必要が.jpg https://t.co/RPpmG4lG5F  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 14:10／2020/09/13 14:08 URL： https://twitter.com/kk_hirono/status/1305010931559067648 https://twitter.com/s_hirono/status/1305010480952479746  

> 2020-09-13-140628_深澤諭史さんがリツイート￼ぎたべん@guitar_ben·17時間統計的な話をしてるのに個別事例持ち出して反論した気になる人が出るの、ロー擁.jpg https://t.co/KM351eqypN  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 14:10／2020/09/13 14:08 URL： https://twitter.com/kk_hirono/status/1305010949183610882 https://twitter.com/s_hirono/status/1305010408420376578  

> 2020-09-13-140456_深澤諭史さんがリツイート￼ふて寝べん@hirune_b·15時間死刑を維持した上で冤罪による死刑を一切許さないと主張するのであれば、死刑囚は.jpg https://t.co/8BJqznGEVY  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 14:10／2020/09/13 14:08 URL： https://twitter.com/kk_hirono/status/1305010965918838785 https://twitter.com/s_hirono/status/1305010335728820229  

> 2020-09-13-140338_深澤諭史さんがリツイート￼ぎたべん@guitar_ben·15時間本気でそう思うなら、遺族に「死刑も無期懲役も処罰されるのは同じだから廃止で.jpg https://t.co/Lkwcp9yu4D  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 14:10／2020/09/13 14:07 URL： https://twitter.com/kk_hirono/status/1305010982641479681 https://twitter.com/s_hirono/status/1305010263054118912  

> 2020-09-13-140232_深澤諭史さんがリツイート￼Document35@document35·20時間私は、ロースクールの教育が予備校に劣るとは思っていない。ただ、.jpg https://t.co/jrizyNO2gD  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 14:10／2020/09/13 13:53 URL： https://twitter.com/kk_hirono/status/1305010998839971841 https://twitter.com/s_hirono/status/1305006783425966080  

> 2020-09-13-132324_深澤諭史さんがリツイート￼いわぽん@yiwapon·9月12日本当に、この特別委員会は延々と議論した挙句に出てくるものがこんなものしかないと.jpg https://t.co/iaquhI9e62  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 14:10／2020/09/13 13:53 URL： https://twitter.com/kk_hirono/status/1305011015352893441 https://twitter.com/s_hirono/status/1305006709857894400  

> 2020-09-13-132115_深澤諭史@fukazawas（＃＾ω＾）直接見聞きしたわけでもなく，具体的にどういう問題があるかわからないけれども，予備校教育を受けた人は，.jpg https://t.co/fFlMM5yMUV  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 14:10／2020/09/13 13:53 URL： https://twitter.com/kk_hirono/status/1305011028598509568 https://twitter.com/s_hirono/status/1305006636826726401  

> 2020-09-13-131127_@noooooooorth弁護士北周士。東京弁護士会所属。法律事務所アルシエン。コインチェック被害対策弁護団。不当懲戒請求被害回復原告団。弁.jpg https://t.co/5bmXAL6SGQ  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 14:10／2020/09/13 13:53 URL： https://twitter.com/kk_hirono/status/1305011045942009856 https://twitter.com/s_hirono/status/1305006564013518849  

> 2020-09-13-131021_深澤諭史@fukazawas（・∀・）私も、以前、ＡＤＲの時に思い知りました。弁護士の仕事増やしたのになあ、、、、。.jpg https://t.co/VMMYiwzlAO  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 14:10／2020/09/13 13:52 URL： https://twitter.com/kk_hirono/status/1305011058550005761 https://twitter.com/s_hirono/status/1305006491334713344  

> 2020-09-13-130614_深澤諭史さんがリツイート￼ぎたべん@guitar_ben·14時間死刑制度は、やはりどこかで「アイツ（死刑囚）と私達とは違う存在」との感覚を.jpg https://t.co/OlKYmN810j  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 14:11／2020/09/13 13:52 URL： https://twitter.com/kk_hirono/status/1305011072093495296 https://twitter.com/s_hirono/status/1305006418630565889  

> 2020-09-13-130423_ぎたべん@guitar_ben返信先：　@guitar_benさん,　@YonedaRyogenさんそもそも無罪推定や利益原則は「真犯人を無.jpg https://t.co/cEjWJxnfoC  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 14:11／2020/09/13 13:52 URL： https://twitter.com/kk_hirono/status/1305011086245068800 https://twitter.com/s_hirono/status/1305006345960079361  

> 2020-09-13-130032_米田龍玄@YonedaRyogen返信先：　@guitar_benさんいや、だって、遺族は、生命の尊さを誰よりも分かってるから。冤罪で、罪の.jpg https://t.co/zkwdokvYcP  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-09-13 14:11／2020/09/13 13:51 URL： https://twitter.com/kk_hirono/status/1305011098249166848 https://twitter.com/s_hirono/status/1305006273239212032  

> 2020-09-13-125933_真の犯人・加害者に、適切な罰を受けてもらいたいと思っているのであって、誤判の死刑なんて、耐えられないですよ￼それは弁護士としても同じ事です。.jpg https://t.co/JelaRtOJyL  

* 





