* 深澤諭史弁護士のタイムラインでちょくちょくリツイートをみかけてきた「ぽぽひと（@popohito）という匿名弁護士のTwitterアカウントの全記録（2020年10月14日時点）

:CATEGORIES: 深澤諭史弁護士

　全部で393件ありますが多すぎるので，1件ずつ確認しながら，これはというものを再捜査要請書＿警察庁・石川県警察御中（@kk_hirono）にツイートします。

```
dp -p |grep popohito |cat -n |sed 's/$/\n/'| sed -e 's/^   //'|xsel -b

  1	 - 2017年10月06日00時29分の登録： ％@popohito　ぽぽひと@死して屍動けばゾンビ％なお、私は個人的には死刑に否定的ですし、仮に明日の会の主張のような決議を人権大会で採択したらやっぱり反対します http://hirono2014sk.blogspot.com/2017/10/popohito.html

  2	 - 2017年10月06日00時32分の登録： ％@popohito　ぽぽひと@死して屍動けばゾンビ％今年の人権大会の犯罪被害者支援関係でも、会内で意見が大きく割れて激しい議論が巻き起こりそうなセンシティブな決議が出る予定なんですか http://hirono2014sk.blogspot.com/2017/10/popohito_6.html

  3	 - 2017年10月09日09時56分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼弁護士費用１０万円を渋った翌日に出会い系サイトに１００万円を突っ込む相談者に頭抱え http://hirono2014sk.blogspot.com/2017/10/popohito_9.html

  4	 - 2017年10月14日20時06分の登録： ％@popohito　ぽぽひと@死して屍動けばゾンビ％訴訟の勝ち負けは弁護士の腕よりは事件の筋によって決まるのだが、弁護士が早期に介入や助言をすれば事件の筋自体が変わる http://hirono2014sk.blogspot.com/2017/10/popohito_14.html

  5	 - 2017年10月14日20時09分の登録： ＼深澤諭史　@fukazawas　RT：　@popohito＼訴訟の勝ち負けは弁護士の腕よりは事件の筋によって決まるのだが、弁護士が早期に介入や助言をすれば事件の筋自体が変わる http://hirono2014sk.blogspot.com/2017/10/fukazawasrtpopohito.html

  6	 - 2017年10月14日23時03分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼当地のアディーレ支店の入ってるビル、新聞沙汰になるような事件が起きたら退去せにゃならんという条項が賃貸借契約に入ってるそうな http://hirono2014sk.blogspot.com/2017/10/popohito_19.html

  7	 - 2017年10月14日23時07分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼アディーレって着手金無料や激安が多く、着手金を返還してもそれほどダメージなさそうな印象なんだけど http://hirono2014sk.blogspot.com/2017/10/popohito_23.html

  8	 - 2017年10月16日00時29分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼弁護士が違法行為をするのは重いってのなら、事務員に昼休み中に電話応対させてる事務所は軒並み業務停止にするか http://hirono2014sk.blogspot.com/2017/10/popohito_16.html

  9	 - 2017年10月18日00時28分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼なにより、水戸黄門の印籠のような効果は実際のところないですからねえ http://hirono2014sk.blogspot.com/2017/10/popohito_18.html

 10	 - 2017年10月19日11時37分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼アディーレは審査請求して執行停止を申し立てろって文句つける人の感覚、マジで理解不能 http://hirono2014sk.blogspot.com/2017/10/popohito_10.html

 11	 - 2017年10月20日11時04分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼\n http://hirono2014sk.blogspot.com/2017/10/popohito_20.html

 12	 - 2017年10月24日22時22分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼依頼者がどうでといい話をしているときは眠気が襲ってくるけれども、法律上重要な点に話題が移った瞬間に http://hirono2014sk.blogspot.com/2017/10/popohito_24.html

 13	 - 2017年11月03日17時11分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼金に目が眩んで法テラスに関わらないようになったのは当職です http://hirono2014sk.blogspot.com/2017/11/popohito.html

 14	 - 2017年11月04日21時03分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼最高裁がこんなことしてたら、モリカケの文書隠匿も司法からは文句言えないわなあ。 http://hirono2014sk.blogspot.com/2017/11/popohito_4.html

 15	 - 2017年11月06日21時38分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼そもそも捜査当局が捜査情報を漏洩しなけりゃいいだけじゃね？ http://hirono2014sk.blogspot.com/2017/11/popohito_6.html

 16	 - 2017年11月06日23時05分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼所属組織にチクるのではなく所属組織に損害賠償請求をするのが法クラ流 http://hirono2014sk.blogspot.com/2017/11/popohito_57.html

 17	 - 2017年11月06日23時29分の登録： ＼モトケン　@motoken_tw　RT：　@popohito＼そもそも捜査当局が捜査情報を漏洩しなけりゃいいだけじゃね？ http://hirono2014sk.blogspot.com/2017/11/motokentwrtpopohito.html

 18	 - 2017年11月07日00時08分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼組合による本人訴訟支援って非弁にはならないのだろうか。\n例のアカウントに限らず、合同労組のやってるやつとかさ。 http://hirono2014sk.blogspot.com/2017/11/popohito_7.html

 19	 - 2017年11月09日17時37分の登録： ＼井上雄樹　@yinoue1975　RT：　@popohito＼そもそも捜査当局が捜査情報を漏洩しなけりゃいいだけじゃね？ http://hirono2014sk.blogspot.com/2017/11/yinoue1975rtpopohito.html

 20	 - 2017年11月11日00時22分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito　RT：　@lawkus＼本気で殺人事件を防止したいなら家族を禁止しろと何度言えばわかるのか。政府はちゃんと仕事しろ。 http://hirono2014sk.blogspot.com/2017/11/popohitortlawkus.html

 21	 - 2017年11月17日11時31分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼なのに弁護士保険をさらに進めて行くって息巻いてる総本山って何考えてんの？ http://hirono2014sk.blogspot.com/2017/11/popohito_17.html

 22	 - 2017年11月17日11時36分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼法クラのみなさんは色々ネタがあるのではなかろうか。\n\n#クソテラスオブザイヤー http://hirono2014sk.blogspot.com/2017/11/popohito_12.html

 23	 - 2017年11月18日04時53分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼だからさー、価格決定権を第三者に明け渡したら絶対あかんのよ。\nなのに弁護士保険をさらに進めて行くって息巻いてる総本山 http://hirono2014sk.blogspot.com/2017/11/popohito_18.html

 24	 - 2017年12月03日22時32分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼弁護士って相手方の嘘を見抜くスペシャリストであると同時に依頼者に騙されるスペシャリストでもあると思う。 http://hirono2014sk.blogspot.com/2017/12/popohito.html

 25	 - 2017年12月05日17時26分の登録： ％@popohito　ぽぽひと@死して屍動けばゾンビ％座間の事件、普通に弁護方針立てるなら捜査段階は完黙一択だと思うので、捜査情報リークは相当疑わしい。 http://hirono2014sk.blogspot.com/2017/12/popohito_5.html

 26	 - 2017年12月13日11時28分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼ベテラン法曹がこういう修習時代の武勇伝を自慢げに語るのを耳にする度に、そりゃ修習期間が短縮されたり貸与制になったりす http://hirono2014sk.blogspot.com/2017/12/popohito_13.html

 27	 - 2017年12月13日14時58分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼刑務所の受刑者って歯痛を訴えてから歯科医師に見てもらえるのに一年半かかってその間に歯がボロボロになるとかあるんだぜ。 http://hirono2014sk.blogspot.com/2017/12/popohito_40.html

 28	 - 2017年12月19日21時02分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼童貞弄りの批判に苦しい弁解をして再炎上をするはあちゅう氏と公式アカウントに鍵をかけて沈黙を貫く電通、炎上対策スキルが http://hirono2014sk.blogspot.com/2017/12/popohito_19.html

 29	 - 2017年12月20日13時14分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼今までのように安い弁護士費用でも仕事があるだけありがたいと受任する弁護士は減ってくる。 法テラスはいつまでも今のよう http://hirono2014sk.blogspot.com/2017/12/popohito_20.html

 30	 - 2018年01月19日15時55分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼あと、めちゃくちゃ広範な規制の網をかけておいて、それを処分するかどうかは懲戒委員会の裁量に任せてるという点にかなりの http://hirono2014sk.blogspot.com/2018/01/popohito.html

 31	 - 2018年01月20日09時54分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼弁護士会の懲戒って、外部からの干渉を防いで弁護士自治を守る目的で厳しくしてるんだろうけど、無駄に厳しくしたせいで弁護 http://hirono2014sk.blogspot.com/2018/01/popohito_20.html

 32	 - 2018年01月22日21時20分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼「弁護士会に文句があるなら常議員や執行部になれ」って理屈、窮状を訴えた女子高生に対して「政治に文句があるなら政治家に http://hirono2014sk.blogspot.com/2018/01/popohito_22.html

 33	 - 2018年01月25日11時54分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼弁護士会が政治活動しても全く問題ないって考えの人って、仮に総本山が日本会議に乗っ取られて日本会議系の会長声明を出しま http://hirono2014sk.blogspot.com/2018/01/popohito_25.html

 34	 - 2018年01月30日10時52分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼行政や裁判所に懲戒処分権を渡したら濫用的な懲戒処分が必然的になされるっていうなら、弁護士会が懲戒処分権を持っていても http://hirono2014sk.blogspot.com/2018/01/popohito_30.html

 35	 - 2018年02月17日20時56分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼この規定を悪用した非弁の傍聴を許可するのはやめて欲しい。 http://hirono2014sk.blogspot.com/2018/02/popohito.html

 36	 - 2018年02月20日21時42分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼新規登録した新人弁護士が初めて出席した総会にて「（新人弁護士が）ゴミ虫みたいに増えやがって」 なお、重鎮弁護士の発言 http://hirono2014sk.blogspot.com/2018/02/popohito_20.html

 37	 - 2018年02月21日15時06分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼うちの事務所の事務員の一人が元医療事務なんだが、医療職からすると生活保護の不正受給者が世の中にめちゃくちゃたくさんい http://hirono2014sk.blogspot.com/2018/02/popohito_21.html

 38	 - 2018年02月23日13時22分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼過払い全盛時、ニューウェーブ系は訴訟提起すれば満額回収できる案件でも交渉で少額和解をして数をこなしてたなあ。 http://hirono2014sk.blogspot.com/2018/02/popohito_23.html

 39	 - 2018年03月08日02時57分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼法律相談のとき、とりあえず相談者に思いの丈をめいいっぱい語ってもらってその後に必要な事項を軽くヒアリングするってスタ http://hirono2014sk.blogspot.com/2018/03/popohito.html

 40	 - 2018年03月18日12時19分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼一番怖いのは、最初は好人物のように近づいてきて受任後に豹変するタイプ。 こういうのを避けるには、本人のぱっと見の人柄 http://hirono2014sk.blogspot.com/2018/03/popohito_18.html

 41	 - 2018年03月30日23時25分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼民進党と希望の党の合流、元々希望の党ができた経緯が、前原が衆議院選で民進党から公認を出さないという謎行動を取ったから http://hirono2014sk.blogspot.com/2018/03/popohito_30.html

 42	 - 2018年04月01日21時32分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼成仏しそうです #エイプリルフールなので嘘か本当か分からないことを言う http://hirono2014sk.blogspot.com/2018/04/popohito.html

 43	 - 2018年04月14日18時33分の登録： ％@popohito　ぽぽひと@死して屍動けばゾンビ％事務員やイソ弁の新規雇用を考えている弁護士は雇用助成金の申請を検討した方がいいよ。 雇用してからじゃ遅いよ。 http://hirono2014sk.blogspot.com/2018/04/popohito_14.html

 44	 - 2018年04月16日17時09分の登録： ＞@fukazawas　深澤諭史＞RT　@popohito：　医療職からすると生活保護の不正受給者が世の中にめちゃくちゃたくさんいると感じるらしい。全身ブランド品で固めた生活保護受給者をしょっちゅう見かけたとか。 http://hirono2014sk.blogspot.com/2018/04/fukazawasrtpopohito.html

 45	 - 2018年04月17日09時57分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼\n\n石破が右でも別にいいのよ。嘘をつかない、質問されたときにはぐらかさずにまともに答える、それをやってくれたら左右で http://hirono2014sk.blogspot.com/2018/04/popohito_17.html

 46	 - 2018年04月18日15時55分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼実務に出たらそういう主張をしないといけないこともあるんです。。。 http://hirono2014sk.blogspot.com/2018/04/popohito_18.html

 47	 - 2018年04月24日09時27分の登録： ＃ぽぽひと@死して屍動けばゾンビ　@popohito＃のツイート／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年04月24日09時27分 http://hirono2014sk.blogspot.com/2018/04/popohito201804240927.html

 48	 - 2018年04月25日04時49分の登録： ％@popohito　ぽぽひと@死して屍動けばゾンビ％国選報酬を私選弁護相場の七掛けくらいまで引き上げたら、担い手不足は一気に解消されると思います。 現状では私選弁護の相場の三分の一以下ですからね。 まさに経済の原理そのものですね。 http://hirono2014sk.blogspot.com/2018/04/popohito_25.html

 49	 - 2018年05月08日00時18分の登録： ＃ぽぽひと@死して屍動けばゾンビ　@popohito＃のツイート／2018-05-06_1423〜2018-05-07_2352／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年05月08日00時18分 http://hirono2014sk.blogspot.com/2018/05/popohito2018-05-0614232018-05.html

 50	 - 2018年05月08日22時45分の登録： ＃ぽぽひと@死して屍動けばゾンビ　@popohito＃のツイート／2018-05-07_0845〜2018-05-08_2243／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年05月08日22時45分 http://hirono2014sk.blogspot.com/2018/05/popohito2018-05-0708452018-05.html

 51	 - 2018年05月12日22時36分の登録： ＃ぽぽひと@死して屍動けばゾンビ　@popohito＃のツイート／2018-05-11_1417〜2018-05-12_1951／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年05月12日22時36分 http://hirono2014sk.blogspot.com/2018/05/popohito2018-05-1114172018-05.html

 52	 - 2018年05月13日19時03分の登録： ＃ぽぽひと@死して屍動けばゾンビ　@popohito＃のツイート／2018-05-12_1344〜2018-05-13_1815／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年05月13日19時03分 http://hirono2014sk.blogspot.com/2018/05/popohito2018-05-1213442018-05.html

 53	 - 2018年05月18日02時14分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼不当懲戒請求騒動、北先生と佐々木先生が動いていたときには無邪気に両先生を応援していただけなんだが、神原弁護士に高島弁 http://hirono2014sk.blogspot.com/2018/05/popohito.html

 54	 - 2018年05月27日16時31分の登録： ＃ぽぽひと@死して屍動けばゾンビ　@popohito＃のツイート／2018-05-26_0946〜2018-05-27_1516／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年05月27日16時31分 http://hirono2014sk.blogspot.com/2018/05/popohito2018-05-2609462018-05.html

 55	 - 2018年06月06日01時04分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼もうさ、刑事事件の検察官請求証拠は全部「改竄された可能性がある」で不同意にしようぜ。 検察官は公文書を改竄しても罪に http://hirono2014sk.blogspot.com/2018/06/popohito.html

 56	 - 2018年06月06日01時04分の登録： ＃ぽぽひと@死して屍動けばゾンビ　@popohito＃のツイート／2018-06-04_0731〜2018-06-06_0055／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年06月06日01時04分 http://hirono2014sk.blogspot.com/2018/06/popohito2018-06-0407312018-06.html

 57	 - 2018年06月17日14時54分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼同じ問題は弁特、ＬＡＣにも言える。総本山がドヤ顔で成果だと語っていたＬＡＣと弁特はあっという間に交通事故弁の報酬を削 http://hirono2014sk.blogspot.com/2018/06/popohito_17.html

 58	 - 2018年06月17日14時54分の登録： ＃ぽぽひと@死して屍動けばゾンビ　@popohito＃のツイート／2018-06-16_1037〜2018-06-17_1254／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年06月17日14時54分 http://hirono2014sk.blogspot.com/2018/06/popohito2018-06-1610372018-06.html

 59	 - 2018年06月25日22時34分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼発達障害系弁護士はスイッチが入るまでは腰が重いけどスイッチが入れば早い。打ち合わせをすることで入ったスイッチを切るこ http://hirono2014sk.blogspot.com/2018/06/popohito_25.html

 60	 - 2018年06月25日22時34分の登録： ＃ぽぽひと@死して屍動けばゾンビ　@popohito＃のツイート／2018-06-24_0545〜2018-06-25_2126／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年06月25日22時34分 http://hirono2014sk.blogspot.com/2018/06/popohito2018-06-2405452018-06.html

 61	 - 2018年07月01日13時46分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼チェック式の勾留請求に対してチェック式の準抗告を申し立てたらチェック式の準抗告却下決定が出るようになったりして。 http://hirono2014sk.blogspot.com/2018/07/popohito.html

 62	 - 2018年07月01日13時46分の登録： ＃ぽぽひと@死して屍動けばゾンビ　@popohito＃のツイート／2018-06-30_1216〜2018-07-01_1248／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年07月01日13時46分 http://hirono2014sk.blogspot.com/2018/07/popohito2018-06-3012162018-07.html

 63	 - 2018年07月04日18時44分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼国選に関しては親に出す義務はないんでしょうがないかと。 むしろ本人に金があるのに国選という問題の方が。。。 http://hirono2014sk.blogspot.com/2018/07/popohito_4.html

 64	 - 2018年07月04日18時44分の登録： ＃ぽぽひと@死して屍動けばゾンビ　@popohito＃のツイート／2018-07-03_1012〜2018-07-04_1841／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年07月04日18時44分 http://hirono2014sk.blogspot.com/2018/07/popohito2018-07-0310122018-07.html

 65	 - 2018年07月31日10時10分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼今の悪あがきは法曹養成制度をよりよくしようという意識が微塵も感じられず法科大学制度維持が自己目的化してるとしか思えな http://hirono2014sk.blogspot.com/2018/07/popohito_31.html

 66	 - 2018年07月31日10時11分の登録： ＃ぽぽひと@死して屍動けばゾンビ　@popohito＃のツイート／2018-07-30_0639〜2018-07-31_1005／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年07月31日10時11分 http://hirono2014sk.blogspot.com/2018/07/popohito2018-07-3006392018-07.html

 67	 - 2018年08月06日19時27分の登録： ＼ぽぽひと@死して屍動けばゾンビ　@popohito＼モラハラやってる感がプンプンする相談者に対して、事案としてはそれほど難しくないけど依頼を受けたらあなたとトラブりそう http://hirono2014sk.blogspot.com/2018/08/popohito.html

 68	 - 2018年08月06日19時27分の登録： ＃ぽぽひと@死して屍動けばゾンビ　@popohito＃のツイート／2018-08-05_0609〜2018-08-06_1922／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年08月06日19時27分 http://hirono2014sk.blogspot.com/2018/08/popohito2018-08-0506092018-08.html

 69	 - 2018年09月30日23時00分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼村木事務次官の事件で当時ロースクールに実務家教員として来ていた検察官が「あれは捜査をミスっただけで絶対クロだ」っ http://hirono2014sk.blogspot.com/2018/09/popohito.html

 70	 - 2018年09月30日23時00分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2018-09-30_0910〜2018-09-30_2255／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年09月30日23時00分 http://hirono2014sk.blogspot.com/2018/09/popohito2018-09-3009102018-09.html

 71	 - 2018年10月02日22時02分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼しかし、未来の検事総長候補とまで言われた４４期の元超エリート検事がこれから法務大臣として安倍内閣の面白閣議決定に http://hirono2014sk.blogspot.com/2018/10/popohito.html

 72	 - 2018年10月02日22時02分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2018-10-01_1203〜2018-10-02_1803／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年10月02日22時02分 http://hirono2014sk.blogspot.com/2018/10/popohito2018-10-0112032018-10.html

 73	 - 2018年10月11日18時08分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼世間の耳目を集めるような画期的判決を何件も取っていて業界のカリスマなんだけど、画期的判決の陰で敗訴判決が死屍累々 http://hirono2014sk.blogspot.com/2018/10/popohito_11.html

 74	 - 2018年10月11日18時08分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2018-10-10_1050〜2018-10-11_1756／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年10月11日18時08分 http://hirono2014sk.blogspot.com/2018/10/popohito2018-10-1010502018-10.html

 75	 - 2018年10月28日16時03分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼あんま変な職務基本規定が通った場合には、規定によっては無視した上で懲戒されても憲法違反で争う覚悟がある。 http://hirono2014sk.blogspot.com/2018/10/popohito_28.html

 76	 - 2018年10月28日16時03分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2018-10-27_1359〜2018-10-28_1602／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年10月28日16時03分 http://hirono2014sk.blogspot.com/2018/10/popohito2018-10-2713592018-10.html

 77	 - 2018年10月30日07時36分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼憲法で認められた国民の権利だと言って何の躊躇もなくカジュアルに訴訟提起するのが弁護士という民族だぞ。 http://hirono2014sk.blogspot.com/2018/10/popohito_30.html

 78	 - 2018年10月30日07時36分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2018-10-28_2007〜2018-10-30_0711／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年10月30日07時36分 http://hirono2014sk.blogspot.com/2018/10/popohito2018-10-2820072018-10.html

 79	 - 2018年10月31日21時14分の登録： ％@popohito　ぽぽひと@常時発動型煽りスキル持ち％印紙代２１８万円をドブに捨てたのか。リッチだなあ。 http://hirono2014sk.blogspot.com/2018/10/popohito_31.html

 80	 - 2018年10月31日21時14分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2018-10-30_1336〜2018-10-31_2050／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年10月31日21時14分 http://hirono2014sk.blogspot.com/2018/10/popohito2018-10-3013362018-10.html

 81	 - 2018年11月01日18時12分の登録： ％@popohito　ぽぽひと@常時発動型煽りスキル持ち％余命側からの７億２０００万円請求訴訟、訴訟のプロである法クラでビビっている人が誰一人おらず、関心が①印紙代が２１ http://hirono2014sk.blogspot.com/2018/11/popohito.html

 82	 - 2018年11月01日18時12分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2018-10-31_1344〜2018-11-01_1703／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年11月01日18時12分 http://hirono2014sk.blogspot.com/2018/11/popohito2018-10-3113442018-11.html

 83	 - 2018年11月05日21時46分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼証人の証言は具体的で迫真性があり記憶にない点は正直に記憶にないと述べており信用性がある http://hirono2014sk.blogspot.com/2018/11/popohito_5.html

 84	 - 2018年11月05日21時46分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2018-11-04_0939〜2018-11-05_2134／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年11月05日21時46分 http://hirono2014sk.blogspot.com/2018/11/popohito2018-11-0409392018-11.html

 85	 - 2018年11月09日17時56分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼遺言執行者の利益相反規制、厳し過ぎないか。 総本山は会員の首を絞めているように思える。 http://hirono2014sk.blogspot.com/2018/11/popohito_9.html

 86	 - 2018年11月09日17時57分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2018-11-08_1306〜2018-11-09_1754／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年11月09日17時57分 http://hirono2014sk.blogspot.com/2018/11/popohito2018-11-0813062018-11.html

 87	 - 2018年11月25日00時28分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼過去に自国の人間が間違いをした事実を伝えられたって別に自国のことを嫌いにはならないが、その事実を認められない同国 http://hirono2014sk.blogspot.com/2018/11/popohito_25.html

 88	 - 2018年11月25日00時28分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2018-11-23_1732〜2018-11-24_2024／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年11月25日00時28分 http://hirono2014sk.blogspot.com/2018/11/popohito2018-11-2317322018-11.html

 89	 - 2018年11月26日20時21分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼元弁護士としてお勧めの事務所を紹介しますとあったら読者は（元）弁護士の目から見て実力よある事務所にリンクを貼って http://hirono2014sk.blogspot.com/2018/11/popohito_26.html

 90	 - 2018年11月26日20時21分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2018-11-25_1034〜2018-11-26_1957／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年11月26日20時21分 http://hirono2014sk.blogspot.com/2018/11/popohito2018-11-2510342018-11.html

 91	 - 2018年12月21日22時47分の登録： ％@popohito　ぽぽひと@常時発動型煽りスキル持ち％医療過誤訴訟における医師の被害妄想でありがちなんだけど、実際は医療事故で医療側が敗訴するケースの何倍ものケースで http://hirono2014sk.blogspot.com/2018/12/popohito.html

 92	 - 2018年12月21日22時48分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2018-12-20_2207〜2018-12-21_1835／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月21日22時48分 http://hirono2014sk.blogspot.com/2018/12/popohito2018-12-2022072018-12.html

 93	 - 2018年12月28日01時13分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼受け手が嫌だと思わなければセクハラは成立しないんだぜ。 http://hirono2014sk.blogspot.com/2018/12/popohito_28.html

 94	 - 2018年12月28日01時13分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2018-12-25_1436〜2018-12-27_1901／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月28日01時13分 http://hirono2014sk.blogspot.com/2018/12/popohito2018-12-2514362018-12.html

 95	 - 2019年01月11日23時14分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼裁判やったらどう考えても相談者の勝訴になるのに相談者がやたら不安がってる場合でも「絶対勝てる」と弁護士は相談に言 http://hirono2014sk.blogspot.com/2019/01/popohito.html

 96	 - 2019年01月11日23時14分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2019-01-09_1703〜2019-01-11_2247／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年01月11日23時14分 http://hirono2014sk.blogspot.com/2019/01/popohito2019-01-0917032019-01.html

 97	 - 2019年01月30日02時50分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼探偵費用って基本タイムチャージなんで、ピンポイントで調査を依頼すれば十数万円程度で済みますが、あてもなく調査をさ http://hirono2014sk.blogspot.com/2019/01/popohito_30.html

 98	 - 2019年01月30日02時51分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2019-01-28_0245〜2019-01-29_2323／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年01月30日02時51分 http://hirono2014sk.blogspot.com/2019/01/popohito2019-01-2802452019-01.html

 99	 - 2019年02月03日09時38分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2019-02-01_0907〜2019-02-02_2116／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月03日09時38分 http://hirono2014sk.blogspot.com/2019/02/popohito2019-02-0109072019-02.html

100	 - 2019年02月03日09時38分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼それを狙うにしても安保法制辺りで政権ヨイショをしてりゃいいだけなのに、なんで親権沼に突っ込んで来るんですかね。。 http://hirono2014sk.blogspot.com/2019/02/popohito.html

101	 - 2019年02月05日20時18分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2019-02-03_1542〜2019-02-05_1827／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月05日20時18分 http://hirono2014sk.blogspot.com/2019/02/popohito2019-02-0315422019-02.html

102	 - 2019年02月05日20時19分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼深澤諭史さんがリツイート＞　矢部善朗（弁護士）‏（@yoshi_yabe）：　ツイッターで弁護士の刑事弁護関係の http://hirono2014sk.blogspot.com/2019/02/popohitoyoshiyabe.html

103	 - 2019年02月07日20時06分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2019-02-05_1608〜2019-02-07_1608／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月07日20時06分 http://hirono2014sk.blogspot.com/2019/02/popohito2019-02-0516082019-02.html

104	 - 2019年02月10日23時20分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2019-02-08_1257〜2019-02-10_2008／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月10日23時20分 http://hirono2014sk.blogspot.com/2019/02/popohito2019-02-0812572019-02.html

105	 - 2019年02月10日23時20分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼イソ弁の採用で偽装請負をやめてちゃんと雇用契約を締結して雇用保険に加入させれば、女性弁護士はかなり働きやすくなる http://hirono2014sk.blogspot.com/2019/02/popohito_10.html

106	 - 2019年02月11日00時39分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2019-02-08_1257〜2019-02-10_2008／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月11日00時39分 http://hirono2014sk.blogspot.com/2019/02/popohito2019-02-0812572019-02_11.html

107	 - 2019年02月11日00時39分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼ＤＶ加害者が被害者に干渉する手段として面会交流を利用したり共同親権を求めたりするのはよーくある話。 http://hirono2014sk.blogspot.com/2019/02/popohito_11.html

108	 - 2019年02月11日12時19分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2019-02-09_1437〜2019-02-11_1213／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月11日12時19分 http://hirono2014sk.blogspot.com/2019/02/popohito2019-02-0914372019-02.html

109	 - 2019年02月11日12時19分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼そんなしょうもないことよりも刑事裁判で弁護人の証拠調べ請求を問答無用で却下しまくることの方が百万倍公正らしさを失 http://hirono2014sk.blogspot.com/2019/02/popohito_92.html

110	 - 2019年02月17日23時26分の登録： ＼弁護士　野田隼人　@nodahayato＼ 返信先: @popohitoさん\n\nあとは、弁護士の役割とプレゼンスの向上に資するものならライドできますが、死刑とか憲法とか http://hirono2014sk.blogspot.com/2019/02/nodahayato-popohito.html

111	 - 2019年02月18日00時45分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2019-02-17_0952〜2019-02-18_0022／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月18日00時45分 http://hirono2014sk.blogspot.com/2019/02/popohito2019-02-1709522019-02.html

112	 - 2019年02月18日00時46分の登録： ％@popohito　ぽぽひと@常時発動型煽りスキル持ち％キャッチフレーズなんぞ聞くまでもなく裁判官なら誰でもこの二人の業績を知ってる。 http://hirono2014sk.blogspot.com/2019/02/popohito_18.html

113	 - 2019年02月19日22時39分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2019-02-18_0119〜2019-02-19_1933／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月19日22時39分 http://hirono2014sk.blogspot.com/2019/02/popohito2019-02-1801192019-02.html

114	 - 2019年02月19日22時40分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼ほんとさ、結論ありきで論理めちゃくちゃの最高裁判例がまかり通っているのに、ロースクールで適正試験やったり刑法短答 http://hirono2014sk.blogspot.com/2019/02/popohito_19.html

115	 - 2019年02月19日23時16分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2019-02-18_0119〜2019-02-19_1933／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月19日23時16分 http://hirono2014sk.blogspot.com/2019/02/popohito2019-02-1801192019-02_19.html

116	 - 2019年02月19日23時16分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼ほんとさ、結論ありきで論理めちゃくちゃの最高裁判例がまかり通っているのに、ロースクールで適正試験やったり刑法短答 http://hirono2014sk.blogspot.com/2019/02/popohito_70.html

117	 - 2019年02月25日20時08分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2019-02-24_1209〜2019-02-25_2007／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月25日20時08分 http://hirono2014sk.blogspot.com/2019/02/popohito2019-02-2412092019-02.html

118	 - 2019年02月25日20時09分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼関東の面会交流事案でＦＰＩＣの利用を検討することになったが、当地の第三者機関よりもずっと安くて人的資源も豊富だな http://hirono2014sk.blogspot.com/2019/02/popohito_25.html

119	 - 2019年02月26日23時52分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2019-02-25_0919〜2019-02-26_2247／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月26日23時52分 http://hirono2014sk.blogspot.com/2019/02/popohito2019-02-2509192019-02.html

120	 - 2019年02月26日23時52分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼これを偏頗弁済といいます。 http://hirono2014sk.blogspot.com/2019/02/popohito_26.html

121	 - 2019年02月28日12時04分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2019-02-27_1011〜2019-02-28_1203／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月28日12時04分 http://hirono2014sk.blogspot.com/2019/02/popohito2019-02-2710112019-02.html

122	 - 2019年02月28日12時04分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼総理の国会答弁って、裁判の反対尋問だったら、質問事項から露骨に逃げた回答ばっかりして裁判官から注意され、さらには http://hirono2014sk.blogspot.com/2019/02/popohito_28.html

123	 - 2019年03月05日20時51分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼カルロスゴーンですら最初は弘中弁護士や高野弁護士に辿り着けなかった、弘中弁護士や高野弁護士ですら最初からカルロス http://hirono2014sk.blogspot.com/2019/03/popohito.html

124	 - 2019年03月05日20時55分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼保釈や準抗告って弁護人の力量が現れるよなあ。\n無罪に関しては無罪になる事件に当たってないって言い訳ができるけど、 http://hirono2014sk.blogspot.com/2019/03/popohito_5.html

125	 - 2019年03月07日02時29分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼元ツイートは「苦しい生活をしてみろ。そうすれば今の政策のおかしさがわかるから。」って趣旨であって、単に歳費を削れ http://hirono2014sk.blogspot.com/2019/03/popohito_7.html

126	 - 2019年03月08日12時38分の登録： ％@popohito　ぽぽひと@常時発動型煽りスキル持ち％岡口Ｊ、分限裁判のときはかなり舐めてた感じだったけど、弾劾裁判はかなり脅威に感じてるっぽいなあ。\nたしかに弾劾 http://hirono2014sk.blogspot.com/2019/03/popohiton.html

127	 - 2019年03月08日22時07分の登録： ％@popohito　ぽぽひと@常時発動型煽りスキル持ち％法クラが修習中の司法解剖見学体験を語っていて若干不謹慎に感じる人もいるかもしれないが、司法解剖は本当に色んなこと http://hirono2014sk.blogspot.com/2019/03/popohito_8.html

128	 - 2019年03月10日11時50分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼事案によるけど、相手方が無職とか日雇い労働者で養育費の回収が困難とか、養育費請求を要求した際の相手方からの難癖に http://hirono2014sk.blogspot.com/2019/03/popohito_10.html

129	 - 2019年03月13日19時01分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼判決文を見ないで批判するのはおかしいって理屈、法曹としては基本的には同意したいんだけど、その理屈を推し進めていく http://hirono2014sk.blogspot.com/2019/03/popohito_13.html

130	 - 2019年03月15日08時25分の登録： ％@popohito　ぽぽひと@常時発動型煽りスキル持ち％受任率を上げたかったら法律相談のときにとりあえず頷け、とりあえず首を縦に振っておけという、身もふたもない話を聞いたことがある。 http://hirono2014sk.blogspot.com/2019/03/popohito_15.html

131	 - 2019年03月15日20時28分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼山口組の綱領もいいこと書いてあるから、毎日唱和してはいかがでしょう？ http://hirono2014sk.blogspot.com/2019/03/popohito_51.html

132	 - 2019年03月16日22時26分の登録： ％@popohito　ぽぽひと@常時発動型煽りスキル持ち％うん、落ちてる。\n司法記事のクオリティはマジで酷い。司法記事がもう少しマシだったら、それを踏まえた「専門家でない人間」の意見ももう少し合理的になるだろうに。 http://hirono2014sk.blogspot.com/2019/03/popohiton_16.html

133	 - 2019年03月18日18時39分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼「依頼する」と言わずに「雇う」と言うと、弁護士は微妙にイラっとする。 民事事件で「弁護」と言われると弁護士はモヤ http://hirono2014sk.blogspot.com/2019/03/popohito_18.html

134	 - 2019年03月18日20時51分の登録： ％@popohito　ぽぽひと@常時発動型煽りスキル持ち％弁護士に依頼する前に不利な事実（自分から金を借りたとか、不倫をしたとか）を認めていた相手方が、裁判になっても当該事実を認めるとは限らない。 http://hirono2014sk.blogspot.com/2019/03/popohito_53.html

135	 - 2019年03月19日10時02分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼は？弁護士からの支援がメインに決まってるじゃん。 http://hirono2014sk.blogspot.com/2019/03/popohito_19.html

136	 - 2019年03月19日12時51分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼高野隆弁護士と宮崎駿監督\n\n #一番似ている二人をアップした人が優勝 http://hirono2014sk.blogspot.com/2019/03/popohito_57.html

137	 - 2019年03月22日11時38分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼こういうのって懲戒の対象にならんのかな。\nまあ、懲戒って街弁に厳しく企業法務事務所に甘いから、懲戒されないんだろ http://hirono2014sk.blogspot.com/2019/03/popohito_22.html

138	 - 2019年03月23日12時56分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼もはや弁護士の信頼を下げる業務とすら言えるんじゃないの、これ。 http://hirono2014sk.blogspot.com/2019/03/popohito_23.html

139	 - 2019年03月25日10時49分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼そもそもクラウドファンディングに出資してる人のほとんどは破産者じゃなくて弁護士だっての。 http://hirono2014sk.blogspot.com/2019/03/popohito_25.html

140	 - 2019年03月28日18時32分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼公正証書を作成する際にこちらが費用を負担するって提示したら、相手方代理人が、自分の日当も負担してくれと言ってきた http://hirono2014sk.blogspot.com/2019/03/popohito_28.html

141	 - 2019年03月29日10時17分の登録： ＼村松 謙　@kmuramatsu＼https://twitter.com/popohito/status/1111263682799919109 http://hirono2014sk.blogspot.com/2019/03/kmuramatsuhttpstwittercompopohitostatus.html

142	 - 2019年03月29日10時18分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼「政治家になることが目的の人」と「やりたいことがあるからその手段として政治家を選択した人」の差を感じます。誰と比 http://hirono2014sk.blogspot.com/2019/03/popohito_29.html

143	 - 2019年04月03日14時07分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼二件というと\n①政治家になりたかった先生\n②神先生\n③５０倍先生\n④国際弁護士ＣＥＯ先生\nのどれが該当してどれが http://hirono2014sk.blogspot.com/2019/04/popohito.html

144	 - 2019年04月04日08時46分の登録： ＼こぶとりポン太89.8　@ponta_kobutori＼返信先: @popohitoさん\n①はちょっとネタになるレベルを超えてる気がしますわ。 http://hirono2014sk.blogspot.com/2019/04/898pontakobutori-popohito.html

145	 - 2019年04月04日11時36分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼どうせなら保釈直後にやってジャパニーズ人質司法の真髄を世界に発信して欲しかった。\n\nゴーン被告を４回目逮捕へ　東 http://hirono2014sk.blogspot.com/2019/04/popohito_4.html

146	 - 2019年04月05日01時37分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼カルロスゴーン、再逮捕までは「さすがジャパニーズ人質司法」くらいの想定範囲内だったが、裁判資料の押収はさすがにド http://hirono2014sk.blogspot.com/2019/04/popohito_5.html

147	 - 2019年04月06日12時37分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼総本山はよく「市民の理解がー」って言うけど、昨今の性犯罪無罪判決に対する市民様のご意見を拝聴したら、弁護士の活動 http://hirono2014sk.blogspot.com/2019/04/popohito_6.html

148	 - 2019年04月07日20時00分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼三輪先生がよい仕事をしたことを確認できた。 http://hirono2014sk.blogspot.com/2019/04/popohito_7.html

149	 - 2019年04月11日10時50分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼好意的に考えたら、弁護士会の刑事委員会が志願兵の中から選りすぐりを派遣してくれる可能性も微粒子レベルでは存在する http://hirono2014sk.blogspot.com/2019/04/popohito_11.html

150	 - 2019年04月11日10時50分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼いや、普通に弁護士会で登録している名簿順で打診が来るよ。\n\n元経済ヤクザが解説「ゴーン氏が犯した4つの致命的悪手 http://hirono2014sk.blogspot.com/2019/04/popohito-4.html

151	 - 2019年04月13日09時46分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼まずめちゃくちゃラフな報道が出ただけでろくに判決文も検討しないで吹き上がるという時点で、無罪推定を否定していると http://hirono2014sk.blogspot.com/2019/04/popohito_13.html

152	 - 2019年04月16日23時54分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼本当に核戦争で文明が滅びてわずかな人類が生き残りを図ろうとしたら、最大の脅威は狂犬病に冒された野犬の群れで、人間 http://hirono2014sk.blogspot.com/2019/04/popohito_16.html

153	 - 2019年04月19日18時40分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼さすがにちょっと酷いのでツイ消しで逃亡されないようにスクショ保存。 http://hirono2014sk.blogspot.com/2019/04/popohito_19.html

154	 - 2019年04月20日09時19分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼もちろんそれを知った上での、むしろ知っているからこその敢えての指摘です。「民衆の意見＝絶対正義」ではないという点 http://hirono2014sk.blogspot.com/2019/04/popohito_20.html

155	 - 2019年04月22日21時14分の登録： ＼メガバヤシ・ギガバヤシ・テラバヤシ＠永遠の5歳　@terabayashi0620＼返信先: @popohitoさん\nいつもと違って？感情的なツイートですよね、この前のツ http://hirono2014sk.blogspot.com/2019/04/5terabayashi0620-popohito.html

156	 - 2019年04月25日09時26分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼うーん、過激派刑弁スピリッツ系弁護士の中には、刑事弁護人は被告人の利益だけをひたすら追求すればよい、むしろするべ http://hirono2014sk.blogspot.com/2019/04/popohito_25.html

157	 - 2019年04月25日20時26分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼だから、性犯罪無罪判決批判の動きが危険だって多くの弁護士アカウントが警鐘を鳴らしていたのは、すぐにこんなふうに拡 http://hirono2014sk.blogspot.com/2019/04/popohito_32.html

158	 - 2019年04月28日09時17分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼供述調書をわざわざカラーコピーしてて草 http://hirono2014sk.blogspot.com/2019/04/popohito_28.html

159	 - 2019年04月28日09時27分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼私が修習生だったときは検察教官がはっきりと「法律事務所の内定も取れないようなやつは検察に必要ない」って言っていま http://hirono2014sk.blogspot.com/2019/04/popohito_17.html

160	 - 2019年04月29日21時23分の登録： ＼モトケン　@motoken_tw＼返信先: @popohitoさん\nツイート消したみたいだけど、ついでにアカウントも消せばいいのに。 http://hirono2014sk.blogspot.com/2019/04/motokentw-popohito.html

161	 - 2019年04月29日21時26分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼１９９７年に弁護士登録をしたロースクール弁がいると聞いて http://hirono2014sk.blogspot.com/2019/04/popohito_29.html

162	 - 2019年05月01日20時19分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼判例ガン無視学説オンリーで検討して出題者の問題意識に触れることすらできない答案が続出してしまった。\n下位ローだっ http://hirono2014sk.blogspot.com/2019/05/popohito.html

163	 - 2019年05月03日22時46分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼なんかもう、「そういうところだぞ」という感想しか持てないな。 http://hirono2014sk.blogspot.com/2019/05/popohito_3.html

164	 - 2019年05月04日15時16分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼地域によって運用に差が出ていますね。\n当地だと名簿で順繰りに回すので、平日だといつ当番が回ってくるのかわからんの http://hirono2014sk.blogspot.com/2019/05/popohito_4.html

165	 - 2019年05月04日15時17分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼当番、休日のときは要請が来たらすぐに出動って出来るけど、平日だったら午前中に要請が来ても期日が入ってたりして出動 http://hirono2014sk.blogspot.com/2019/05/popohito_39.html

166	 - 2019年05月05日09時14分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼知人に県下一の大地主の一人息子で金は唸るほどあるけれども、キモメンなので全くモテないというレアな非モテがいる。 http://hirono2014sk.blogspot.com/2019/05/popohito_5.html

167	 - 2019年05月05日21時27分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2019-05-05_0932〜2019-05-05_2026／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年05月05日21時27分 http://hirono2014sk.blogspot.com/2019/05/popohito2019-05-0509322019-05.html

168	 - 2019年05月06日09時13分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼方針転換したのはいいけど、私が前に言っていたことは間違いでしたごめんなさいって表明すべきだと思う。\nでないと、そ http://hirono2014sk.blogspot.com/2019/05/popohito_6.html

169	 - 2019年05月07日00時26分の登録： ％@popohito　ぽぽひと@常時発動型煽りスキル持ち％これ、よく言われるけど、弁護士以外のことについて需要者はどこまで品質の良し悪しを判断できるんだろうか。\n\n少 http://hirono2014sk.blogspot.com/2019/05/popohitonn.html

170	 - 2019年05月07日00時35分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼弁護人請求証拠を着払いで送ろう運動、一斉に起こしたら面白いかもしれない。 http://hirono2014sk.blogspot.com/2019/05/popohito_7.html

171	 - 2019年05月10日00時27分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼岡崎支部の判決、ＡＰＳが作文だった問題はあるけど、無罪になったポイントはＶの抗拒不能の評価なんだから、ＡＰＳを適 http://hirono2014sk.blogspot.com/2019/05/popohito_10.html

172	 - 2019年05月11日17時10分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼街弁の仕事をする上で、パソコンのメモリはどれくらいあるのが望ましいんだろう？ http://hirono2014sk.blogspot.com/2019/05/popohito_11.html

173	 - 2019年05月12日18時45分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼#フラワーデモ\nに関与している弁護士たち、「悪いタイミングで判決が公開され始めたな」って内心思ってそう。 http://hirono2014sk.blogspot.com/2019/05/popohito_12.html

174	 - 2019年05月13日13時18分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼地方だとそもそも代理人同士顔見知りで名刺交換をする必要がない→名刺交換の文化が生まれない→初対面の代理人とも名刺 http://hirono2014sk.blogspot.com/2019/05/popohito_13.html

175	 - 2019年05月13日22時50分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼某支部庁舎のロビーで少額訴訟の説明VTRが延々と流れていたのだが、事案が６０万円の物損事故で過失割合に争いがある http://hirono2014sk.blogspot.com/2019/05/popohitovtr.html

176	 - 2019年05月16日21時58分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼普通の人は、不合理な有罪判決はしょっちゅう出るけど不合理な無罪判決はまず出ないという刑事裁判の特殊性を知らないで http://hirono2014sk.blogspot.com/2019/05/popohito_16.html

177	 - 2019年05月17日13時31分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼クロ現、BPO案件になり得るかな。 http://hirono2014sk.blogspot.com/2019/05/popohitobpo.html

178	 - 2019年05月18日09時51分の登録： モトケン（@motoken_tw）／「@popohito」の検索結果　-　Twilog：2019年05月18日09時51分　83件 http://hirono2014sk.blogspot.com/2019/05/motokentwpopohito-twilog20190518095183.html

179	 - 2019年05月22日19時55分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼＼カール・レーフラー@過食　@juntaba1＼毒入りのイメージしかない・・・\n http://hirono2014sk.blogspot.com/2019/05/popohitojuntaba1.html

180	 - 2019年05月22日19時57分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼書類上は地検支部や区検が存在することになっているけれども公判請求するときは全件本庁で起訴。 http://hirono2014sk.blogspot.com/2019/05/popohito_22.html

181	 - 2019年05月25日11時28分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼離婚で金儲けをしている弁護士ですが、家庭を壊して金を儲けているんじゃなくて壊れた家庭の解体撤去作業をして金を儲け http://hirono2014sk.blogspot.com/2019/05/popohito_25.html

182	 - 2019年05月28日04時19分の登録： ％@popohito　ぽぽひと@常時発動型煽りスキル持ち％無罪判決を出すヒラメ裁判官って初めて聞くわ。 http://hirono2014sk.blogspot.com/2019/05/popohito_28.html

183	 - 2019年05月28日18時33分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼せいこうほうしうの請求書作成はもっと楽しいですよ http://hirono2014sk.blogspot.com/2019/05/popohito_50.html

184	 - 2019年05月31日22時56分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼\n‏\n \n@popohito\n 4時間4時間前\n￼ その他\n依頼者「相手方（ＤＶ夫が怒らないでしょうか？」\n当職 http://hirono2014sk.blogspot.com/2019/05/popohito-popohito-44.html

185	 - 2019年06月01日22時34分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼ついに行政書士からの内容証明郵便がキターーー！ http://hirono2014sk.blogspot.com/2019/06/popohito.html

186	 - 2019年06月04日07時48分の登録： REGEXP：”@popohito”／データベース登録済みツイート：2019年06月04日07時42分の記録：ユーザ・投稿：158／631件 http://hirono2014sk.blogspot.com/2019/06/regexppopohito201906040742158631.html

187	 - 2019年06月05日23時49分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼イソ弁時代、ボスがやってた事件で、接見禁止がついているのでボスを通して被告人と恋人がラブラブバカップルな手紙のや http://hirono2014sk.blogspot.com/2019/06/popohito_5.html

188	 - 2019年06月05日23時58分の登録： REGEXP：”@popohito”／データベース登録済みツイートの検索：2019-06-03〜2019-06-05／2019年06月05日23時57分の記録：ユーザ・投稿：13／20件 http://hirono2014sk.blogspot.com/2019/06/regexppopohito2019-06-032019-06.html

189	 - 2019年06月07日11時16分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼択一合格率が高過ぎるって言ってる法曹がちらほら見かけるけど、昔と違って予備試験を通るかローを卒業した人しか受験で http://hirono2014sk.blogspot.com/2019/06/popohito_7.html

190	 - 2019年06月07日21時07分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼べんごしは しんけんについてつぶやいた。\n\nそういうところだぞが  あらわれた！\n\n #法クラクエスト http://hirono2014sk.blogspot.com/2019/06/popohito_72.html

191	 - 2019年06月16日00時48分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼被疑者国選弁護で頑張って勾留されている被疑者の身柄を早期に釈放させたら、弁護士報酬が下がる。 http://hirono2014sk.blogspot.com/2019/06/popohito_16.html

192	 - 2019年06月17日00時40分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼市民から司法アクセスを奪ったってのは疑問。\n司法改革以前よりははるかに市民が司法にアクセスしやすくなっている。法 http://hirono2014sk.blogspot.com/2019/06/popohito_17.html

193	 - 2019年06月17日00時42分の登録： ＼橋本太地（弁護士・あなたのみかた法律事務所）　@kojin_syugi＼返信先: @popohitoさん\n被疑者国選が人権活動かと言うと、感覚的ですが、何か違うようにも http://hirono2014sk.blogspot.com/2019/06/kojinsyugi-popohito.html

194	 - 2019年06月17日00時43分の登録： ＼橋本太地（弁護士・あなたのみかた法律事務所）　@kojin_syugi＼返信先: @popohitoさん\n以前より弁護士の経済的余裕がなくなり、手弁当での人権活動ができ http://hirono2014sk.blogspot.com/2019/06/kojinsyugi-popohito_17.html

195	 - 2019年06月18日17時13分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼おお、ついに当職の時代が来たか！\n\nってその前に１０００万円の弁護士費用を払えるだけの資力のある依頼者を屏風から http://hirono2014sk.blogspot.com/2019/06/popohito_18.html

196	 - 2019年06月18日17時42分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼この一連のツイートを読んで、このアカの代理人弁護士の言っていることに問題がないと思ってしまう弁護士は、離婚事件や http://hirono2014sk.blogspot.com/2019/06/popohito_89.html

197	 - 2019年06月19日01時17分の登録： ％@popohito　ぽぽひと@常時発動型煽りスキル持ち％基本的にＤＶ案件って手間と労力がかかるは弁護士報酬が少ないはで、やりたがらない弁護士ばっかりなんで、金目当てで煽る弁護士なんてまずいないですよ。 http://hirono2014sk.blogspot.com/2019/06/popohito_19.html

198	 - 2019年06月19日01時18分の登録： ％@popohito　ぽぽひと@常時発動型煽りスキル持ち％ＤＶ加害者がＤＶを否定するのは極めて普通なことですよ。というか、素直にＤＶを認める加害者の方が圧倒的な少数派です。 http://hirono2014sk.blogspot.com/2019/06/popohito_76.html

199	 - 2019年06月19日01時18分の登録： ％@popohito　ぽぽひと@常時発動型煽りスキル持ち％普通ですね。少なくとも弁護士に持ち込まれる案件に関していうと。私は離婚案件を多数扱っていますが、事実の存否につい http://hirono2014sk.blogspot.com/2019/06/popohito_6.html

200	 - 2019年06月19日09時36分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼だいたい弁護士がアレなものがほとんどだが、\n\n「年収額が 500 万円を超えたため、賃上げが止まりました。 しか http://hirono2014sk.blogspot.com/2019/06/popohito-500.html

201	 - 2019年06月20日23時06分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼憲法ポエムで懲りてないのかよ・・・。 http://hirono2014sk.blogspot.com/2019/06/popohito_20.html

202	 - 2019年06月20日23時19分の登録： ＼弁護士　野田隼人　@nodahayato＼返信先: @wata_nabekyo_koさん、@popohitoさん\n首かな…。 http://hirono2014sk.blogspot.com/2019/06/nodahayato-watanabekyokopopohito.html

203	 - 2019年06月20日23時20分の登録： ＼なべきょう＠過眠症　@wata_nabekyo_ko＼返信先: @nodahayatoさん、@popohitoさん\n脳みその「その部分」だけスイカスプーンでくりぬければ http://hirono2014sk.blogspot.com/2019/06/watanabekyoko-nodahayatopopohito.html

204	 - 2019年06月20日23時20分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼返信先: @wata_nabekyo_koさん、@nodahayatoさん\nそれなんてロボトミー手術。。。 http://hirono2014sk.blogspot.com/2019/06/popohito-watanabekyokonodahayato.html

205	 - 2019年06月21日17時57分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2019-06-20_1952〜2019-06-21_1756／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年06月21日17時57分 http://hirono2014sk.blogspot.com/2019/06/popohito2019-06-2019522019-06.html

206	 - 2019年06月21日18時14分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito　RT：　@uwaaaa＼RT @uwaaaa: 弁護人役を高野隆先生，検察官役を後藤貞人先生が務めるという「季刊 http://hirono2014sk.blogspot.com/2019/06/popohitortuwaaaart-uwaaaa.html

207	 - 2019年06月21日22時42分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼他の士業の商品を売りたかったら他の士業の資格を取れとしか。 http://hirono2014sk.blogspot.com/2019/06/popohito_21.html

208	 - 2019年06月22日11時43分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼そもそも日本の民事裁判の事実認定において「◯◯が公的に認められる」って意味は基本的にないです。\n民事裁判に証拠の http://hirono2014sk.blogspot.com/2019/06/popohito_22.html

209	 - 2019年06月22日11時43分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼そうではないです。\n例えば名誉毀損などの不法行為だと\n①違法な行為（ネット上の名誉毀損行為など）\n②それによって http://hirono2014sk.blogspot.com/2019/06/popohito_86.html

210	 - 2019年06月22日11時44分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼いや、別に昔から第三者の発言も証拠として扱われてるし。\n名誉毀損の損害立証なんか、不特定多数のインターネット上の http://hirono2014sk.blogspot.com/2019/06/popohito_12.html

211	 - 2019年06月22日11時44分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼いや、別に歴史に残るもツイートが裁判の証拠に使われるなんてむっちゃ普通のことなんだが。\n\nツイートだけじゃなく２ http://hirono2014sk.blogspot.com/2019/06/popohito_13.html

212	 - 2019年06月22日22時17分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼何かの目的があってその手段として無料法律事務所を思いついたんじゃなくて、無料法律事務所という手法ありきで目的を後 http://hirono2014sk.blogspot.com/2019/06/popohito_45.html

213	 - 2019年06月25日12時41分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼吉本興業は、ＮＧＴの第三者委員会をやった弁護士に第三者委員会の調査報告を依頼すればいいんじゃねーの？？ http://hirono2014sk.blogspot.com/2019/06/popohito_25.html

214	 - 2019年06月26日15時25分の登録： ＃ぽぽひと@常時発動型煽りスキル持ち　@popohito＃のツイート／2019-06-24_2124〜2019-06-26_1505／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年06月26日15時25分 http://hirono2014sk.blogspot.com/2019/06/popohito2019-06-2421242019-06.html

215	 - 2019年06月27日17時27分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼これが通ったら月刊懲戒で優良先生が特定できてしまう。。。 http://hirono2014sk.blogspot.com/2019/06/popohito_27.html

216	 - 2019年06月28日22時36分の登録： ＼ぽぽひと@常時発動型煽りスキル持ち　@popohito＼誰も「裁判官を批判するな」なんて言ってないよ。「判決文も読まずに事実関係も知らずに裁判官を批判するな」って言って http://hirono2014sk.blogspot.com/2019/06/popohito_28.html

217	 - 2019年07月01日23時18分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼当職がマッチョ刑弁族認定しているツイッター上のアカウントはたった２つしかいない。\nそのうち１つはつい最近アカウント消去した http://hirono2014sk.blogspot.com/2019/07/popohito.html

218	 - 2019年07月02日12時19分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼弁護士なんて基本負けず嫌いの集団なんだから、リソースが許すなら刑弁教的な戦い方をやりまくりたいって思っている人少なくないと http://hirono2014sk.blogspot.com/2019/07/popohito_2.html

219	 - 2019年07月03日00時39分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼返信先: @jcp_ccさん\n――強制性交等罪の「暴行・脅迫要件」の撤廃と同意要件の新設をはじめ、性暴力の根絶につながる刑 http://hirono2014sk.blogspot.com/2019/07/popohito-jcpcc.html

220	 - 2019年07月05日14時24分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼当会で民事裁判のIT化検討を扱う委員会が、パソコンをろくに使えない重鎮弁護士だらけという情報に接して驚愕している。 http://hirono2014sk.blogspot.com/2019/07/popohitoit.html

221	 - 2019年07月06日16時35分の登録： ＃ぽぽひと@内閣調査室所属　@popohito＃のツイート／2019-07-05_2241〜2019-07-06_1602／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年07月06日16時34分 http://hirono2014sk.blogspot.com/2019/07/popohito2019-07-0522412019-07.html

222	 - 2019年07月11日19時49分の登録： ＃ぽぽひと@内閣調査室所属　@popohito＃のツイート／2019-07-10_1320〜2019-07-11_1941／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年07月11日19時49分 http://hirono2014sk.blogspot.com/2019/07/popohito2019-07-1013202019-07.html

223	 - 2019年07月14日01時02分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼これ、別の人が裁判を起こしたときは全力で争うって宣言だよな。 http://hirono2014sk.blogspot.com/2019/07/popohito_14.html

224	 - 2019年07月16日11時25分の登録： ＃ぽぽひと@内閣調査室所属　@popohito＃のツイート／2019-07-15_0819〜2019-07-16_1124／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年07月16日11時25分 http://hirono2014sk.blogspot.com/2019/07/popohito2019-07-1508192019-07.html

225	 - 2019年07月18日21時12分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼総本山って職域拡大のチャンスで会員にボランティアさせて会員を潰していくよね。 http://hirono2014sk.blogspot.com/2019/07/popohito_18.html

226	 - 2019年07月21日12時31分の登録： ＃ぽぽひと@内閣調査室所属　@popohito＃のツイート／2019-07-20_1725〜2019-07-21_1230／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年07月21日12時31分 http://hirono2014sk.blogspot.com/2019/07/popohito2019-07-2017252019-07.html

227	 - 2019年07月21日12時33分の登録： ＃ぽぽひと@内閣調査室所属　@popohito＃のツイート／2019-07-20_1736〜2019-07-21_1233／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年07月21日12時33分 http://hirono2014sk.blogspot.com/2019/07/popohito2019-07-2017362019-07.html

228	 - 2019年07月21日20時41分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼立憲民主党から公認を外された某弁護士が法クラからどんな目で見られていたかを思い出していただければと思います。 http://hirono2014sk.blogspot.com/2019/07/popohito_21.html

229	 - 2019年07月23日11時44分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼のむしうがまともなことを言っている。\n\nまるで軍事の話になると正気に戻る田母神さんみたいだ。 http://hirono2014sk.blogspot.com/2019/07/popohito_23.html

230	 - 2019年07月23日16時02分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼そんだけもらえるなら記者会見で火だるまになっても構わないって思いました。 http://hirono2014sk.blogspot.com/2019/07/popohito_70.html

231	 - 2019年07月23日16時03分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼クソサイトが吉本のインハウスの年収を５０００万〜８０００万と推測していて、さすがクソサイトだなという感想を持たせてくれた。 http://hirono2014sk.blogspot.com/2019/07/popohito_44.html

232	 - 2019年07月23日19時41分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼さすがいつも体制に擦り寄る芸人、インハウス弁護士（not顧問弁護士）に全責任を押し付けることで会長社長松本に忠誠を誓う姿勢 http://hirono2014sk.blogspot.com/2019/07/popohitonot.html

233	 - 2019年07月24日13時22分の登録： ＼弁護士 遠藤温子　@Atsuko_law＼返信先: \n@okuboka\n さん、 \n@popohito\nさん\n使うことを学ぼうとすらしない弁護士は切り捨てて父のでは？ http://hirono2014sk.blogspot.com/2019/07/atsukolaw-okuboka-popohito.html

234	 - 2019年07月26日02時09分の登録： ％@popohito　ぽぽひと@内閣調査室所属％ツイッタランドに生息している弁護士たちを観察したらあいつら危険生物だってことくらいわかるだろうという趣旨なのか。 http://hirono2014sk.blogspot.com/2019/07/popohito_26.html

235	 - 2019年07月26日02時13分の登録： ＃ぽぽひと@内閣調査室所属　@popohito＃のツイート／2019-07-25_0749〜2019-07-25_2247／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年07月26日02時13分 http://hirono2014sk.blogspot.com/2019/07/popohito2019-07-2507492019-07.html

236	 - 2019年07月26日09時01分の登録： ＃ぽぽひと@内閣調査室所属　@popohito＃のツイート／2019-07-25_1302〜2019-07-26_0855／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年07月26日09時01分 http://hirono2014sk.blogspot.com/2019/07/popohito2019-07-2513022019-07.html

237	 - 2019年07月28日01時24分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼相手方本人から文書で回答もらえたらめっちゃ嬉しい。\nだいたい、訴訟でこちらが有利に使えそうなことが書いてあるから。 http://hirono2014sk.blogspot.com/2019/07/popohito_28.html

238	 - 2019年07月30日03時11分の登録： ％@popohito　ぽぽひと@内閣調査室所属％ゲハオはよりによってなんでこんなに攻撃力の高い弁護士をわざわざターゲットに選んでしまったのかとつくづく思う者 http://hirono2014sk.blogspot.com/2019/07/popohito_30.html

239	 - 2019年08月06日01時52分の登録： ％@popohito　ぽぽひと@内閣調査室所属％だってガソリン持っていくってファックス送るみたいな露骨で痕跡も残る脅迫に対して、警察がピクリとも動かないとか想定できないでしょ。 http://hirono2014sk.blogspot.com/2019/08/popohito.html

240	 - 2019年08月06日16時28分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼最大多数派は弁護士であることの気配を消してただの議員として活動する自公の議員。 http://hirono2014sk.blogspot.com/2019/08/popohito_6.html

241	 - 2019年08月06日18時38分の登録： ％@popohito　ぽぽひと@内閣調査室所属％寿司振る舞い先生という異名が奪われそうになっている件について。 http://hirono2014sk.blogspot.com/2019/08/popohito_33.html

242	 - 2019年08月09日10時06分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼一番固そうな展開\n\n①被害届提出\n↓\n②担当の警察官が適当なことを言って門前払い\n↓\n③津田氏が上記事情をツイート\n↓\n④ http://hirono2014sk.blogspot.com/2019/08/popohito_9.html

243	 - 2019年08月11日09時45分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼ほんと、身柄を早期に解放させたら弁護士費用が下がるシステム、法務省が身柄拘束の邪魔されたくないからとしか思えないな。 http://hirono2014sk.blogspot.com/2019/08/popohito_11.html

244	 - 2019年08月11日22時37分の登録： ＼モトケン　@motoken_tw＼返信先: \n@popohito\nさん\n警察官は警察の上司の命令に従うので、公判検事がいくら不自然だろと言っても言うことを聞かない。 http://hirono2014sk.blogspot.com/2019/08/motokentw-popohito.html

245	 - 2019年08月11日22時38分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼ある公務執行妨害事件で、３人の警察官が主要部分について一言一句同じ内容のコピペの供述調書を出してきた。\n http://hirono2014sk.blogspot.com/2019/08/popohito_38.html

246	 - 2019年08月11日23時12分の登録： ＃ぽぽひと@内閣調査室所属　@popohito＃のツイート／2019-08-11_0608〜2019-08-11_2231／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年08月11日23時12分 http://hirono2014sk.blogspot.com/2019/08/popohito2019-08-1106082019-08.html

247	 - 2019年08月19日00時08分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼なお、今の弁護士会の懲戒は信用していないが、現政権下で行政の監督下に懲戒権が置かれたらもっとヤバいことになりそうなので、消 http://hirono2014sk.blogspot.com/2019/08/popohito_19.html

248	 - 2019年08月20日18時11分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼金田一少年「謎が全て解けたわけじゃないけどこれくらいの証拠が揃ったら逮捕状は出ると思う。」\n剣持警部「わかった。後は連日連 http://hirono2014sk.blogspot.com/2019/08/popohito_20.html

249	 - 2019年08月24日23時33分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼「何をしたら」というよりも余計なことをしなきゃいいだけかと。\n\nわざわざ殊更に大日本帝国の所業を正当化する発言をしてたら、 http://hirono2014sk.blogspot.com/2019/08/popohito_24.html

250	 - 2019年08月28日22時36分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼法テラスの報酬上げろという怪ファックスが届いてた。\n今まで見た怪ファックスの中で一番説得力を感じた。 http://hirono2014sk.blogspot.com/2019/08/popohito_28.html

251	 - 2019年09月01日19時35分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼もっとも、児童買春って量刑の幅が広いので、買春した大人の不利な量刑事情としておもくそ考慮される可能性あるけどな。 http://hirono2014sk.blogspot.com/2019/09/popohito.html

252	 - 2019年09月06日14時36分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼https://twitter.com/popohito/status/1169788422434611202 http://hirono2014sk.blogspot.com/2019/09/popohitohttpstwittercompopohitostatus11.html

253	 - 2019年09月06日14時40分の登録： ＼深澤諭史　@fukazawas　RT：　@popohito＼真相に迫りたいなら地裁の判事していた方がいいのでは。\n最高裁にもとめられるのは理論の構築だろ。\n\n最高裁判事 http://hirono2014sk.blogspot.com/2019/09/fukazawasrtpopohito.html

254	 - 2019年09月22日10時58分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼安倍首相が千葉の被災地入りしないことについて首相は災害現地に行く必要はないって支持者が一生懸命擁護しているけど、じゃあ熊本 http://hirono2014sk.blogspot.com/2019/09/popohito_22.html

255	 - 2019年09月25日20時40分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼殺人事件や傷害致死事件の量刑相場を引き上げていったら、こうなっちゃうのよな。\n昔みたいに特段の事情のない被害者１人の殺人事 http://hirono2014sk.blogspot.com/2019/09/popohito_25.html

256	 - 2019年09月25日20時53分の登録： ％@popohito　ぽぽひと@内閣調査室所属％民事訴訟における被告の所在調査のときに集合住宅の郵便受けを開けて被告宛の郵便物が届いているか確認する行為は http://hirono2014sk.blogspot.com/2019/09/popohito_21.html

257	 - 2019年09月27日19時30分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼相手方代理人、別にこちらの依頼者が不貞行為したこと争っているわけじゃないのに、受任通知と一緒にこちらの依頼者のハメ撮り写真 http://hirono2014sk.blogspot.com/2019/09/popohito_27.html

258	 - 2019年10月03日16時18分の登録： ％@popohito　ぽぽひと@内閣調査室所属％ある程度離婚事件を扱っている弁護士に相談しろの一択でいいのでは。\n\nＤＶ・モラハラで攻撃の矛先が自分に向けられるなんて日常茶飯事だからな。 http://hirono2014sk.blogspot.com/2019/10/popohitonn.html

259	 - 2019年10月04日10時40分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼弁護士費用ケチるからだよって感想しか出てこない。 http://hirono2014sk.blogspot.com/2019/10/popohito.html

260	 - 2019年10月04日14時39分の登録： REGEXP：”@popohito”／データベース登録済みツイートの検索：2019-09-27〜2019-10-04／2019年10月04日14時38分の記録：ユーザ・投稿：33／53件 http://hirono2014sk.blogspot.com/2019/10/regexppopohito2019-09-272019-10.html

261	 - 2019年10月09日10時30分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼今の◯◯弁護士がちゃんとやってくれないから弁護士を変えたいという依頼があり、◯◯弁護士ってそんなおかしい弁護士じゃないよな http://hirono2014sk.blogspot.com/2019/10/popohito_9.html

262	 - 2019年10月12日00時35分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼いや待て、そもそもなんでこんな企画を考えたんだ？ http://hirono2014sk.blogspot.com/2019/10/popohito_12.html

263	 - 2019年10月12日21時17分の登録： ％@popohito　ぽぽひと@内閣調査室所属％卵万引きで実刑ってのは、累犯者だからだろうな。\n万引きは一発目は微罪処分で送検すらされず、二発目は起訴猶予、三発目は略式 http://hirono2014sk.blogspot.com/2019/10/popohiton.html

264	 - 2019年10月15日16時50分の登録： REGEXP：”@popohito”／モトケン（@motoken_tw）の検索（2016-03-06〜2019-10-08／2019年10月15日16時50分の記録75件） http://hirono2014sk.blogspot.com/2019/10/regexppopohitomotokentw2016-03-062019.html

265	 - 2019年10月15日17時12分の登録： REGEXP：”@popohito”／データベース登録済みツイート：2019年10月15日17時04分の記録：ユーザ・投稿：211／975件 http://hirono2014sk.blogspot.com/2019/10/regexppopohito201910151704211975.html

266	 - 2019年10月15日17時31分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼弁護士登録抹消した元弁護士が未だに司法試験の合格率について語ってるの、いいから自分の人生歩めよって思ってしまう。\n\n#なに http://hirono2014sk.blogspot.com/2019/10/popohito_15.html

267	 - 2019年10月18日09時35分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼税金からの給料で食っているスタ弁が全ての弁護士は赤字案件もやるべきってご高説垂れてるの、面白いな。\n\nまずは独立して事務所 http://hirono2014sk.blogspot.com/2019/10/popohito_18.html

268	 - 2019年10月19日16時38分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼日本で警察が携行するカメラで録画をいつもしてたら、法的にアウトな職務質問や任意取調べの動画がいっぱい保存されて面白くなりそ http://hirono2014sk.blogspot.com/2019/10/popohito_19.html

269	 - 2019年10月22日13時26分の登録： ＼ぽぽひと@内閣調査室所属　@popohito＼憲法のことわかっていないのに改憲したがる人間もいるんだし、そんなもんでしょ。 http://hirono2014sk.blogspot.com/2019/10/popohito_22.html

270	 - 2019年10月24日22時34分の登録： ％@popohito　ぽぽひと@内閣調査室所属％あの人、リベラルじゃなくて正義の味方だから。 http://hirono2014sk.blogspot.com/2019/10/popohito_24.html

271	 - 2019年10月25日20時17分の登録： ％@popohito　ぽぽひと@内閣調査室所属％ツイッター上の法クラの書き込みに対してリプライや引用リツイートはおろかエアリプすらせず、顔本のグループで引っ張って批判して http://hirono2014sk.blogspot.com/2019/10/popohito_25.html

272	 - 2019年10月31日12時27分の登録： ＼ぽぽひと@ひとりじゃないよ。　@popohito＼自分は起訴したかったけど決済が通らず忸怩たる思いをしたってのならわかるけど、これを笑い話にできる感性の人間に法律家の肩 http://hirono2014sk.blogspot.com/2019/10/popohito_31.html

273	 - 2019年10月31日12時28分の登録： ＼ぽぽひと@ひとりじゃないよ。　@popohito＼ぽぽひと@ひとりじゃないよ。\n@popohito\n·\n1h\n検察庁が公訴権を恣意的に運用しているのがとってもよーくわか http://hirono2014sk.blogspot.com/2019/10/popohito-popohito-1h.html

274	 - 2019年11月01日07時28分の登録： ＼ぽぽひと@ひとりじゃないよ。　@popohito＼返信先: \n@sato__michiko\nさん\nブロックされている人どうぞ http://hirono2014sk.blogspot.com/2019/11/popohito-satomichiko.html

275	 - 2019年11月05日15時14分の登録： ＼ぽぽひと@ひとりじゃないよ。　@popohito＼ラーメン発見伝で、少数の常連の口出しに影響を受け過ぎて、売り上げの多数を占めていたライトな客層に逃げられて低迷したラー http://hirono2014sk.blogspot.com/2019/11/popohito.html

276	 - 2019年11月06日10時07分の登録： ＜2019年11月06日(水) 10時07分08秒にTwitterAPIで取得したpopohito（ぽぽひと@ひとりじゃないよ。）のプロフィール情報＞\n離婚事件をメインに http://hirono2014sk.blogspot.com/2019/11/20191106-100708twitterapipopohito.html

277	 - 2019年11月13日22時05分の登録： ＼ぽぽひと@ひとりじゃないよ。　@popohito＼交通事故案件はあまり扱っていないけど、法クラのＴＬ情報を総合すると損保の評判は\n\n東京海上>（大正義の壁）>三井住友・ http://hirono2014sk.blogspot.com/2019/11/popohito_13.html

278	 - 2019年11月13日22時07分の登録： ＼亀石　@kame_ishi＼返信先: \n@popohito\nさん\nJAも一番下でもいいような。担当者の質… http://hirono2014sk.blogspot.com/2019/11/kameishi-popohito-ja.html

279	 - 2019年11月13日22時07分の登録： ＼意識低い系弁護士　@hatarakedo1988＼返信先: \n@popohito\nさん\nＪＡは最下位でいいと思います http://hirono2014sk.blogspot.com/2019/11/hatarakedo1988-popohito.html

280	 - 2019年11月13日22時08分の登録： ＼カイト　@kaitoshima＼返信先: \n@popohito\nさん\n交通事故は数百件扱いましたが、JA・全労済・SBIが同列という印象です。ソニーはそこまで悪い印象で http://hirono2014sk.blogspot.com/2019/11/kaitoshima-popohito-jasbi.html

281	 - 2019年11月13日22時08分の登録： ＼弁護士　野田隼人　@nodahayato＼返信先: \n@popohito\nさん\nソニーももう一段下なんじゃないか…。 http://hirono2014sk.blogspot.com/2019/11/nodahayato-popohito.html

282	 - 2019年11月14日14時00分の登録： ＼ぽぽひと@ひとりじゃないよ。　@popohito＼「貴殿は私の訴訟に耐えられるかな？」というパワーワード。\nこれは流行る。 http://hirono2014sk.blogspot.com/2019/11/popohito_14.html

283	 - 2019年11月23日15時59分の登録： ＼ぽぽひと@睡眠重視　@popohito＼５年３割なんか取ったことないなあ。\nそんだけもらってまらうちの事務所もっと儲かるんだけどなあ。\n\n基本は２年の１０〜１２%、養育 http://hirono2014sk.blogspot.com/2019/11/popohito_23.html

284	 - 2019年11月23日21時42分の登録： ＼ぽぽひと@睡眠重視　@popohito＼共同親権界隈が養育費に弁護士報酬が発生するのはおかしいって主張してるの、離婚事件で弁護士の介入によりそれまでのように思い通りいか http://hirono2014sk.blogspot.com/2019/11/popohito_48.html

285	 - 2019年11月29日15時31分の登録： ＼ぽぽひと@睡眠重視　@popohito＼これ、概念が勘違いされて広まっているけど、負の性欲って「性欲を向けられることへの拒否」ではなく「性欲を向けられることを拒否するこ http://hirono2014sk.blogspot.com/2019/11/popohito_29.html

286	 - 2019年11月30日14時59分の登録： ＼ぽぽひと@睡眠重視　@popohito＼非法曹の考える「人権」ってこんなレベルなんだよなと暗澹たる気持ちになった。 http://hirono2014sk.blogspot.com/2019/11/popohito_30.html

287	 - 2019年12月02日21時46分の登録： ＼ぽぽひと@睡眠重視　@popohito＼弁護士の仕事って、手間と時間がかかればかかるほど弁護士のコストは増大するけど、依頼者の利益は減少するっていう面がある。\n報酬をコ http://hirono2014sk.blogspot.com/2019/12/popohito.html

288	 - 2019年12月05日10時21分の登録： ＼ぽぽひと@睡眠重視　@popohito＼弁護士の最大の武器は交渉が決裂しても法的手段を取れるという点なので、法的手段で達成できること以上の成果を交渉で挙げてこいと言われ http://hirono2014sk.blogspot.com/2019/12/popohito_5.html

289	 - 2019年12月10日20時56分の登録： ＼ぽぽひと@睡眠重視　@popohito＼このタイミングでこういうチラシが来て草  http://hirono2014sk.blogspot.com/2019/12/popohito_10.html

290	 - 2019年12月12日12時32分の登録： ＼ぽぽひと@睡眠重視　@popohito＼契約書とかメールとかは残っていないけど、◯◯があったことは相手方も認めていますから大丈夫です。 \n  #弁護士が信じない依頼者 http://hirono2014sk.blogspot.com/2019/12/popohito-n.html

291	 - 2019年12月12日19時29分の登録： ＼ぽぽひと@睡眠重視　@popohito＼依頼者が言うなら、「異性と一緒にラブホに入ったけど周りの目を避けて相談をするためであって、性交渉はしていません。」って話も信じま http://hirono2014sk.blogspot.com/2019/12/popohito_12.html

292	 - 2019年12月15日09時05分の登録： ＼ぽぽひと@睡眠重視　@popohito＼深澤諭史さんがリツイート　　ぽぽひと@睡眠重視　　15時間　　反省文を書かせるってモラハラ加害者がよくやるムーブよな。 http://hirono2014sk.blogspot.com/2019/12/popohito15.html

293	 - 2019年12月16日16時14分の登録： ＃ぽぽひと@睡眠重視　@popohito＃のツイート／2019-12-15_0847〜2019-12-16_1554／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年12月16日16時14分 http://hirono2014sk.blogspot.com/2019/12/popohito2019-12-1508472019-12.html

294	 - 2019年12月18日21時25分の登録： ＼ぽぽひと@睡眠重視　@popohito＼メーリングリストに.jtdファイルを添付したメールを流してはいけない\n #新人弁護士に言いたいこと http://hirono2014sk.blogspot.com/2019/12/popohitojtd.html

295	 - 2019年12月24日14時33分の登録： ＼ぽぽひと@睡眠重視　@popohito＼ 山口敬之の「あの」代理人ですら、男と一緒に飲んで泥酔したらレイプされても仕方がないみたいなエクストリーム抗弁はさすがに裁判で主 http://hirono2014sk.blogspot.com/2019/12/popohito_24.html

296	 - 2019年12月28日18時41分の登録： ＼ぽぽひと@睡眠重視　@popohito＼医師の離婚問題に詳しい行政書士？？？？ http://hirono2014sk.blogspot.com/2019/12/popohito_28.html

297	 - 2019年12月29日10時49分の登録： ＼ぽぽひと@睡眠重視　@popohito＼さて問題です。\n天下りは文科省だけではなく財務省も経産省も厚労省もやりまくっていますし前川元次官が退官した後に文科省の天下りがな http://hirono2014sk.blogspot.com/2019/12/popohito_29.html

298	 - 2019年12月31日12時42分の登録： ＼ぽぽひと@睡眠重視　@popohito＼時価２４０円相当（これでも高く見積もられた方）の野菜を菜園から盗んだ刑事事件の被疑者国選をやったことあるけど、示談をまとめてなん http://hirono2014sk.blogspot.com/2019/12/popohito_31.html

299	 - 2020年01月01日20時07分の登録： ＼ぽぽひと@睡眠重視　@popohito＼ほとんどの弁護士の飯の種は刑事弁護じゃなくて民事の代理ですが？ http://hirono2014sk.blogspot.com/2020/01/popohito.html

300	 - 2020年01月03日04時24分の登録： ＃ぽぽひと@睡眠重視　@popohito＃のツイート／2020-01-02_1027〜2020-01-03_0316／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2020年01月03日04時24分 http://hirono2014sk.blogspot.com/2020/01/popohito2020-01-0210272020-01.html

301	 - 2020年01月03日04時26分の登録： @popohito（ぽぽひと@睡眠重視）のツイート　”．＊”　3194／3194：2019-12-09_0920〜2020-01-03_0316　2020年01月03日04時26分の記録 http://hirono2014sk.blogspot.com/2020/01/popohito319431942019-12-0909202020-01.html

302	 - 2020年01月06日11時07分の登録： ＼ぽぽひと@睡眠重視　@popohito＼日本の弁護士が刑事事件において『日本の弁護士が、「公正な裁判は期待できない。」とか言っちゃうのは少なくとも自分には理解できない。 http://hirono2014sk.blogspot.com/2020/01/popohito_6.html

303	 - 2020年01月06日21時16分の登録： ＃ぽぽひと@睡眠重視　@popohito＃のツイート／2020-01-05_1401〜2020-01-06_1834／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2020年01月06日21時16分 http://hirono2014sk.blogspot.com/2020/01/popohito2020-01-0514012020-01.html

304	 - 2020年01月09日14時32分の登録： ＼ぽぽひと@睡眠重視　@popohito＼ピロシ先生が天下ったモリハマが予備試験組ばかり採用しているのは業が深い http://hirono2014sk.blogspot.com/2020/01/popohito_9.html

305	 - 2020年01月11日16時55分の登録： ＼ぽぽひと@睡眠重視　@popohito＼深澤諭史さんがリツイート\n￼\nぽぽひと@睡眠重視\n@popohito\n·\n2時間\n凶悪事件の被疑者被告人の刑事事件と、そういうと http://hirono2014sk.blogspot.com/2020/01/popohito-popohito-2.html

306	 - 2020年01月12日12時17分の登録： ＼ぽぽひと@睡眠重視　@popohito＼配偶者に非道なことをする人って、結婚前は非道なことをしないのが多いんですよね。\n\n最初から非道なことしたら逃げられて結婚できない http://hirono2014sk.blogspot.com/2020/01/popohito_12.html

307	 - 2020年01月25日21時12分の登録： ％@popohito　ぽぽひと@睡眠重視％最近、イソ弁に強制執行を振るとき、訴訟費用額確定処分までさせている。\n\nうちには、付郵便送達に強い弁護士が既にいるが、それに加えて訴訟費用確定処分に強い弁護士も生まれつつある。 http://hirono2014sk.blogspot.com/2020/01/popohitonn.html

308	 - 2020年01月31日23時53分の登録： ＼ぽぽひと@睡眠重視　@popohito＼あれ？\nアメリカのポルノって強姦系は御法度で、女優がノリノリのオーイェー系じゃなきゃダメなんじゃなかったっけ？？ http://hirono2014sk.blogspot.com/2020/01/popohito_31.html

309	 - 2020年02月02日20時35分の登録： ％@popohito　ぽぽひと@睡眠重視％いくら犯罪抑止が目的だからって、弁護士の肩書で量刑相場についてメディアで明らかな嘘をつくことが正当化できるとはとても思えないんだ http://hirono2014sk.blogspot.com/2020/02/popohito.html

310	 - 2020年02月03日20時13分の登録： ＃ぽぽひと@睡眠重視　@popohito＃のツイート／2020-02-03_0923〜2020-02-03_1954／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2020年02月03日20時13分 http://hirono2014sk.blogspot.com/2020/02/popohito2020-02-0309232020-02.html

311	 - 2020年02月07日10時32分の登録： ＼ぽぽひと@睡眠重視　@popohito＼弁護人、高野先生か。\n\n男性医師は女性患者の胸を舐めたのか、それとも“せん妄”による幻覚だったのか | 文春オンライン http://hirono2014sk.blogspot.com/2020/02/popohito_7.html

312	 - 2020年02月08日10時11分の登録： ＼ぽぽひと@睡眠重視　@popohito＼裁判官が理系だからわからないのではたく、裁判官が弁護人の主張立証に全く耳を傾けないからこういう判決が出たのだと思う。\n\n科学技術 http://hirono2014sk.blogspot.com/2020/02/popohito_8.html

313	 - 2020年02月10日08時50分の登録： ％@popohito　ぽぽひと@睡眠重視％弁護士会費の方が高くて草 http://hirono2014sk.blogspot.com/2020/02/popohito_10.html

314	 - 2020年02月13日21時17分の登録： ＼ぽぽひと@睡眠重視　@popohito＼この動画を見て涙を流す小さい子供を持つ親はそれなりにいると思った。 http://hirono2014sk.blogspot.com/2020/02/popohito_13.html

315	 - 2020年02月13日21時25分の登録： ＼ぽぽひと@睡眠重視　@popohito＼＜使用容疑ではないので、2年前の容疑での逮捕は珍しくない。＞\n\n刑事事件あんまやらないから知らないけど、そういうもんなの？？？\n http://hirono2014sk.blogspot.com/2020/02/popohito2.html

316	 - 2020年02月13日21時36分の登録： ＼ぽぽひと@睡眠重視　@popohito＼最近聞かなくなったけど司法試験合格者減少論が活発だったときは、「弁護士人口増加により弁護士の収入が減りプロボノができなくなった。 http://hirono2014sk.blogspot.com/2020/02/popohito_42.html

317	 - 2020年02月13日21時36分の登録： ＼ぽぽひと@睡眠重視　@popohito＼日本では排除法則がほとんど適用されずに違法捜査やり放題ったのが現状だからなあ。\n排除しまくっても違法捜査がやまないってなったら別 http://hirono2014sk.blogspot.com/2020/02/popohito_52.html

318	 - 2020年02月19日01時24分の登録： ＼ぽぽひと@睡眠重視　@popohito＼むしろ実名アカウントの中には、意図的に誤った情報を発信して、その情報に騙された人を顧客にしようとしているのではと疑われる弁護士が http://hirono2014sk.blogspot.com/2020/02/popohito_19.html

319	 - 2020年02月21日13時05分の登録： ＼ぽぽひと@睡眠重視　@popohito＼二回相談をドタキャンした人から、訴訟を起こされたので早急に相談したいという問い合わせが来たので、おまいは二回ドタキャンしやがった http://hirono2014sk.blogspot.com/2020/02/popohito_21.html

320	 - 2020年02月27日10時33分の登録： ＼ぽぽひと@睡眠重視　@popohito＼新型コロナの対応や検査体制、諸外国と比較して日本だけ明らかに独自路線を突っ走ってるんだけど、日本政府のやり方は間違ってないとなる http://hirono2014sk.blogspot.com/2020/02/popohito_27.html

321	 - 2020年02月28日09時30分の登録： ＼ぽぽひと@睡眠重視　@popohito＼返信先: \n@fukazawas\nさん\n法テラスの苦い経験よりもＬＡＣの苦い経験の方が大きいと思います。\nＬＡＣができたころは、 http://hirono2014sk.blogspot.com/2020/02/popohito-fukazawas.html

322	 - 2020年02月28日13時23分の登録： ＼ぽぽひと@睡眠重視　@popohito＼依頼者と揉めて決裂したとき、依頼者は弁護士の悪口を言いふらし放題なのに、弁護士が依頼者のクソさを語ったら守秘義務違反になるの、し http://hirono2014sk.blogspot.com/2020/02/popohito_28.html

323	 - 2020年02月28日20時46分の登録： ＼ぽぽひと@睡眠重視　@popohito＼コロナ事業者破産はマジで来そうなので、倒産村の弁護士は申立代理人側も破産管財人側もアップしておいた方がいいと思う。 http://hirono2014sk.blogspot.com/2020/02/popohito_43.html

324	 - 2020年03月01日22時09分の登録： ＃ぽぽひと@睡眠重視　@popohito＃のツイート／2020-02-29_1458〜2020-03-01_2106／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2020年03月01日22時09分 http://hirono2014sk.blogspot.com/2020/03/popohito2020-02-2914582020-03.html

325	 - 2020年03月07日02時01分の登録： ＼ぽぽひと@睡眠重視　@popohito＼言い返しましたよ。\nいつ電話するかはこっちが決めるって。 http://hirono2014sk.blogspot.com/2020/03/popohito.html

326	 - 2020年03月08日13時14分の登録： ＼鳩屋　@haya_rt＼返信先: \n@popohito\nさん\n結局モラ夫なので弁護士にもモラ夫ぶりを発揮してくる感じですかね？ http://hirono2014sk.blogspot.com/2020/03/hayart-popohito.html

327	 - 2020年03月08日13時20分の登録： ＼ぽぽひと@睡眠重視　@popohito＼モラ夫の依頼を高額着手金で何回か受任してみたことがあるが、さんざん労力かけさせられた挙句に着手金叩き返して辞任ということが続いた http://hirono2014sk.blogspot.com/2020/03/popohito_8.html

328	 - 2020年03月08日13時49分の登録： ＼ぽぽひと@睡眠重視　@popohito＼音楽用語。「狂詩曲」のこと。叙事的，英雄的，あるいは民族的な色彩をもち，自由なファンタジー風の楽曲をいう http://hirono2014sk.blogspot.com/2020/03/popohito_93.html

329	 - 2020年03月11日16時04分の登録： ＼ぽぽひと@睡眠重視　@popohito＼イソ弁氏が「これ、依頼者がダメ元で希望しているんですけど、無理ですよね～。」と当職に相談してきた事案、調べたらそれなりにやってみ http://hirono2014sk.blogspot.com/2020/03/popohito_11.html

330	 - 2020年03月11日17時17分の登録： ＼ぽぽひと@睡眠重視　@popohito＼地方会対東京大阪の構図ではないという主張が、最も皮肉な形で実証されたような気がする。\n\n#日弁連会長選挙\n引用ツイート\n http://hirono2014sk.blogspot.com/2020/03/popohito_53.html

331	 - 2020年03月11日17時21分の登録： ＼ぽぽひと@睡眠重視　@popohito＼ツイッターだと山岸先生支持者の勢力の方が圧倒的にあったのに、実際の投票結果は荒先生の方が上っぽいの、色々と興味深い。\n\nやっぱ、 http://hirono2014sk.blogspot.com/2020/03/popohito_67.html

332	 - 2020年03月12日09時11分の登録： ＼ぽぽひと@睡眠重視　@popohito＼第１回目の公開質問状だと荒先生は職務基本規定改正を進める感じだったし山岸先生もなんか歯切れ悪い感じだったのに、第２回目の公開質問 http://hirono2014sk.blogspot.com/2020/03/popohito_12.html

333	 - 2020年03月17日02時00分の登録： ＼ぽぽひと@睡眠重視　@popohito＼さいたまの市役所前で人が刺されたって情報と県庁前で人が刺されたって情報と地裁前で人が刺されたって情報があるんだが、多分密集してる http://hirono2014sk.blogspot.com/2020/03/popohito_17.html

334	 - 2020年03月18日22時00分の登録： ＼ぽぽひと@睡眠重視　@popohito＼どれもこれも金にならない案件ばかりで草 http://hirono2014sk.blogspot.com/2020/03/popohito_18.html

335	 - 2020年03月20日20時04分の登録： ＼ぽぽひと@睡眠重視　@popohito＼そういえば、新司法試験に批判的な政治家だったからというだけの理由で、この人を持てはやす弁護士がちらほらいたような記憶がある。\n\n http://hirono2014sk.blogspot.com/2020/03/popohito_20.html

336	 - 2020年03月25日17時23分の登録： ＼ぽぽひと@睡眠重視　@popohito＼割とマジで、新型コロナウイルスによる事業者の倒産処理のために、弁護士費用クーポンを国が出したら、結果的に経済のダメージは小さくな http://hirono2014sk.blogspot.com/2020/03/popohito_25.html

337	 - 2020年03月26日11時23分の登録： ＼ぽぽひと@睡眠重視　@popohito＼あまりに予想通りで草。\n予言者と呼んでくれ。 http://hirono2014sk.blogspot.com/2020/03/popohito_26.html

338	 - 2020年03月27日14時09分の登録： ＼ぽぽひと@睡眠重視　@popohito＼かわいそうな依頼者を人質に取られているからです。\n\n当職のような冷血感は別れています。 http://hirono2014sk.blogspot.com/2020/03/popohito_27.html

339	 - 2020年03月30日23時07分の登録： ＼ぽぽひと@睡眠重視　@popohito＼宇都宮会長時代に日弁連のコンピューター委員会が潰されたとして、それから一体何年経ってんのよ。潰したのは宇都宮会長の責任でも、未だ http://hirono2014sk.blogspot.com/2020/03/popohito_30.html

340	 - 2020年04月02日09時14分の登録： ＼ぽぽひと@睡眠重視　@popohito＼しかしマスクを配ることはできるのであった。 http://hirono2014sk.blogspot.com/2020/04/popohito.html

341	 - 2020年04月07日13時24分の登録： ＼ぽぽひと@睡眠重視　@popohito＼権力からの自由と権力への自由が矛盾すると思ってるのかな？\n弁護士バッジつける前にもう少し憲法の勉強をした方がいいと思う。\n引用ツ http://hirono2014sk.blogspot.com/2020/04/popohito_7.html

342	 - 2020年04月08日12時05分の登録： ＼ぽぽひと@睡眠重視　@popohito＼「PCR検査は無意味、有害！」って叫び続けていた医クラが政府の方針転換に合わせて自身の主張も変遷させていくのを見ると、医者って他 http://hirono2014sk.blogspot.com/2020/04/popohitopcr.html

343	 - 2020年04月08日12時05分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼返信先: \n@popohito\nさん\nツイッターの法クラ（の特に声の大きい人たち）が弁護士全体を代表しないのと同様、ネットででかい http://hirono2014sk.blogspot.com/2020/04/ksawmen-popohito.html

344	 - 2020年04月10日15時58分の登録： ＼ぽぽひと@睡眠重視　@popohito＼正義中毒と悪不感症は両立するで。\n\n権力者の巨悪をスルーして芸能人の不倫叩きに精を出すみたいに。 http://hirono2014sk.blogspot.com/2020/04/popohito_10.html

345	 - 2020年04月12日16時49分の登録： ％@popohito　ぽぽひと@睡眠重視％ピロシ先生が天下ったモリハマが予備試験組ばかり採用しているのは業が深い。 http://hirono2014sk.blogspot.com/2020/04/popohito_12.html

346	 - 2020年04月21日10時32分の登録： ＼ぽぽひと@睡眠重視　@popohito＼性暴力被害者から加害者への未回収債権や養育費の未回収債権があるから（いずれも債務名義取得済み）、差し押さえたるかな。 http://hirono2014sk.blogspot.com/2020/04/popohito_21.html

347	 - 2020年05月08日20時09分の登録： ＼ぽぽひと@睡眠重視　@popohito＼業務委託契約のイソ弁の報酬を１ヶ月だけ削って持続化給付金を請求させ、差額をボスが召し上げるというスキームを思いついたけど、そんな http://hirono2014sk.blogspot.com/2020/05/popohito.html

348	 - 2020年05月13日22時06分の登録： ＼ぽぽひと@睡眠重視　@popohito＼森法務大臣って中途半端に法曹としての誠実さが残っているから色々と支離滅裂な対応になっちゃうんだと思う。 これが菅官房長官や加藤厚 http://hirono2014sk.blogspot.com/2020/05/popohito_13.html

349	 - 2020年05月18日19時30分の登録： ％@popohito　ぽぽひと@睡眠重視％弁護士会ばかり政治的中立性が問題視されるけど、他の士業団体って弁政連より遥かに高い加入率の政治連盟を持っていて、単位会の総会と政 http://hirono2014sk.blogspot.com/2020/05/popohito_18.html

350	 - 2020年05月21日10時41分の登録： ＼ぽぽひと@睡眠重視　@popohito＼野村修習行ってない也先生というワードは、元々本人が弁護士の肩書をつけながら修習に行って実務に触れていたら絶対に間違えないであろう http://hirono2014sk.blogspot.com/2020/05/popohito_21.html

351	 - 2020年05月22日14時29分の登録： ＼ぽぽひと@睡眠重視　@popohito＼黒川検事長、終局処分をどうするかはさておき、常習性や収賄、国家公務員法違反の疑いを調査するためにガサしてスマホを差押えたり、口裏 http://hirono2014sk.blogspot.com/2020/05/popohito_22.html

352	 - 2020年05月27日15時55分の登録： ＼ぽぽひと@睡眠重視　@popohito＼代理人による刑事告発が認められないって、これ弁護士会や日弁連が抗議声明出さなきゃならない話じゃないか？  不受理にするにしてもも http://hirono2014sk.blogspot.com/2020/05/popohito_27.html

353	 - 2020年05月28日23時09分の登録： ＼ぽぽひと@睡眠重視　@popohito＼このシーン、法曹資格持ちの原作者は庁舎内での会話を指定したのに作画担当が勝手に居酒屋での会話に変えたのではないかと疑ってしまうく http://hirono2014sk.blogspot.com/2020/05/popohito_28.html

354	 - 2020年06月02日00時53分の登録： ＼山崎靖子　@pEjEoaqB03qNfkX＼返信先:  @popohito さん,  @fukazawas さん 一発で懲戒ですね。業務停止レベルの。 http://hirono2014sk.blogspot.com/2020/06/pejeoaqb03qnfkx-popohito-fukazawas.html

355	 - 2020年06月03日17時34分の登録： ＼ぽぽひと@睡眠重視　@popohito＼余程の著名人でない限り，数十名が特定個人に関心を持って強力な誹謗中傷を行うというのは発生しにくいですね。 引用ツイート http://hirono2014sk.blogspot.com/2020/06/popohito.html

356	 - 2020年06月13日19時59分の登録： ＼ぽぽひと@睡眠重視　@popohito＼なんで旅行業界や飲食業界はクーポンもらえて、弁護士は法テラス拡大なんだよ。  他の業界と同じように弁護士費用クーポン出せよ。 http://hirono2014sk.blogspot.com/2020/06/popohito_13.html

357	 - 2020年06月16日01時39分の登録： ＼ぽぽひと@睡眠重視　@popohito＼自称日弁連の人じゃなくて副会長と事務局次長が来たんだから、マジモンの日弁連の人では？ http://hirono2014sk.blogspot.com/2020/06/popohito_16.html

358	 - 2020年06月22日20時03分の登録： ＼ぽぽひと@睡眠重視　@popohito＼宇都宮先生がサラ金相手に成果を出したのって、単に一弁護士としての能力が高かったからってわけじゃなくて、日本中の弁護士が参加する一 http://hirono2014sk.blogspot.com/2020/06/popohito_22.html

359	 - 2020年06月25日15時53分の登録： ＼ぽぽひと@睡眠重視　@popohito＼実は、サラ金にとどめを刺した最高裁H18.1.13判決を出した事件の代理人は宇都宮弁護士ではないんだよね。 だから「一人で打ち砕 http://hirono2014sk.blogspot.com/2020/06/popohitoh18113.html

360	 - 2020年07月02日20時30分の登録： ＼ぽぽひと@睡眠重視　@popohito＼ヒャッハーの世界でも無免許運転はしないのが偉い http://hirono2014sk.blogspot.com/2020/07/popohito.html

361	 - 2020年07月14日01時01分の登録： ＼ぽぽひと@睡眠重視　@popohito＼刑弁畑の弁護士は公判をイメージして有罪認定がザル，被害者の供述信用し過ぎって感じる一方で，被害者支援畑の弁護士は捜査段階をイメー http://hirono2014sk.blogspot.com/2020/07/popohito_14.html

362	 - 2020年07月14日02時06分の登録： ＼ぽぽひと@睡眠重視　@popohito＼そう考えるならお医者様にはもっと日本の刑事司法に対して関心を持って欲しいものだ。 お医者様だけが特別に厳しい扱いをされているので http://hirono2014sk.blogspot.com/2020/07/popohito_36.html

363	 - 2020年07月14日14時37分の登録： ＼ぽぽひと@睡眠重視　@popohito＼最近は依頼者にイソ弁が新規相談対応から受任した依頼者に難あり案件がちらほらあるので，これをチェックしてケアするのが意外と重要な仕 http://hirono2014sk.blogspot.com/2020/07/popohito_5.html

364	 - 2020年07月14日15時08分の登録： ＼ぽぽひと@睡眠重視　@popohito＼興味があったけど，損保会社から全くお呼びがかからなかった者。  イソ弁時代は多少損保案件あったし，そのときは正直元ボスよりいい仕 http://hirono2014sk.blogspot.com/2020/07/popohito_24.html

365	 - 2020年07月16日13時02分の登録： ＼ぽぽひと@睡眠重視　@popohito＼竹野内豊が月9主演へ。漫画『イチケイのカラス』が実写ドラマ化、来年放送作品に出演報道。 – 今日の最新芸能ゴシップニュースサイト http://hirono2014sk.blogspot.com/2020/07/popohito9.html

366	 - 2020年07月19日22時28分の登録： ＼ぽぽひと@睡眠重視　@popohito＼女性議員が少ない最大の原因って議員の最大勢力である世襲議員に女性が極端に少ないからだと思う。  国会議員だと小渕優子くらいしか思 http://hirono2014sk.blogspot.com/2020/07/popohito_19.html

367	 - 2020年07月19日22時29分の登録： ＼ぽぽひと@睡眠重視　@popohito＼私が既婚者と一緒にラブホテルに行ったのは人目を避けて相談をするためです。セックスはしていません。 http://hirono2014sk.blogspot.com/2020/07/popohito_82.html

368	 - 2020年07月20日21時58分の登録： ＼ぽぽひと@睡眠重視　@popohito＼依頼者に地雷臭を感じたイソ弁氏の担当案件，いろいろとイソ弁氏に対して忠告や指示を出していたら依頼者の方から他事務所の弁護士に替え http://hirono2014sk.blogspot.com/2020/07/popohito_20.html

369	 - 2020年07月30日15時44分の登録： ＼ぽぽひと@睡眠重視　@popohito＼これ、「人を一人殺したら命で償うのが当たり前」なまでに量刑相場が上がっていて、「死刑が確定したら法務大臣は速やかに執行しろ」って http://hirono2014sk.blogspot.com/2020/07/popohito_30.html

370	 - 2020年07月30日18時30分の登録： ＼ぽぽひと@睡眠重視　@popohito＼通常の離婚事件の３倍は弁護士費用が欲しい。旧日弁連基準でね。 http://hirono2014sk.blogspot.com/2020/07/popohito_72.html

371	 - 2020年07月30日18時31分の登録： ＼ぽぽひと@睡眠重視　@popohito＼当職は金の味方なので、そういうところだぞの方々からの依頼を受けることで儲かるならいくらでも依頼を受けますよ。  でも、残念ながら http://hirono2014sk.blogspot.com/2020/07/popohito_74.html

372	 - 2020年08月13日22時08分の登録： ＼ぽぽひと@睡眠重視　@popohito＼弁護士がクライアントファーストを標榜すると真っ先に犠牲になるのは家庭。その次が事務局とイソ弁。 \n というか、普通に仕事してい http://hirono2014sk.blogspot.com/2020/08/popohito-n.html

373	 - 2020年08月13日22時29分の登録： ＼ぽぽひと@睡眠重視　@popohito＼弁護士がクライアントファーストを標榜すると真っ先に犠牲になるのは家庭。その次が事務局とイソ弁。 というか、普通に仕事していたら無 http://hirono2014sk.blogspot.com/2020/08/popohito.html

374	 - 2020年08月16日21時03分の登録： ＼ぽぽひと@睡眠重視　@popohito＼当時の公文書、ガンガン廃棄されたからね。  今も廃棄しまくりだけど。 http://hirono2014sk.blogspot.com/2020/08/popohito_16.html

375	 - 2020年08月24日03時22分の登録： ＼ぽぽひと@睡眠重視　@popohito＼元警察官の人が実体的真実の観点からは真犯人であっても訴訟上の観点で無罪になることがあるって指摘するの、それ自体はそんなにおかしい http://hirono2014sk.blogspot.com/2020/08/popohito_24.html

376	 - 2020年08月29日15時09分の登録： ＼ぽぽひと@睡眠重視　@popohito＼会社を潰す勢いのポンコツ経営を繰り返す社長が病気で退陣したら、社員は理由はなんであれ社長が変わってよかったって考えるんじゃないか http://hirono2014sk.blogspot.com/2020/08/popohito_29.html

377	 - 2020年09月04日22時30分の登録： ＼ぽぽひと@ゆ・３３４　@popohito＼しかし、日頃は反安倍批判を馬鹿にしているアカウントが日弁連定期総会における執行部の態度を強く批判しているのを見ると、なんだかな http://hirono2014sk.blogspot.com/2020/09/popohito.html

378	 - 2020年09月11日12時01分の登録： ＼ぽぽひと＠wordタケノコ粒あん党　@popohito＼死刑を破棄したのは最高裁の山口厚じゃなくて高裁裁判官だって。  あの山口厚がそんな面倒なことするわけないだろ。 http://hirono2014sk.blogspot.com/2020/09/wordpopohito.html

379	 - 2020年09月16日19時42分の登録： ＼ぽぽひと＠wordタケノコ粒あん党　@popohito＼論文問題で今の国会答弁みたいな回答を書いたら大変なことになるのでは。 http://hirono2014sk.blogspot.com/2020/09/wordpopohito_16.html

380	 - 2020年09月16日22時03分の登録： ＼めしだ＠法教育おじさん　@r_messy＼返信先:  @popohito さん 認められる、と言わざるを得ません。 刑事弁護系と被害者支援系が衝突するのと同様に、労働系 http://hirono2014sk.blogspot.com/2020/09/rmessy-popohito.html

381	 - 2020年09月20日20時12分の登録： ％@popohito　ぽぽひと＠wordタケノコ粒あん党％こういうことをする人って、金銭的な対価を支払わずにサービスを得ることで自分が他の客とは違う特別な存在になりたいと http://kk2020-09.blogspot.com/2020/09/popohitoword.html

382	 - 2020年09月23日09時32分の登録： ＼ぽぽひと＠wordタケノコ粒あん党　@popohito＼「執行部はダメだけど弁護士自治放棄はもっとダメ」が執行部を腐らせているのではないか。下手したら弁護士自治を失うく http://kk2020-09.blogspot.com/2020/09/wordpopohito_23.html

383	 - 2020年09月25日21時26分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼返信先: @popohitoさんそれはそうなんですよね。。。ただ、現状では書面投票やWeb投票への反対がものすごく強くて、、、 http://kk2020-09.blogspot.com/2020/09/ksawmen-popohitoweb.html

384	 - 2020年09月25日21時27分の登録： ＼ぽぽひと＠wordタケノコ粒あん党　@popohito＼委任状の緩和は無関心層を執行部賛成票に転換させる効力が強すぎるので、事前の書面投票やWeb投票を充実させる方がい http://kk2020-09.blogspot.com/2020/09/wordpopohitoweb.html

385	 - 2020年09月27日11時42分の登録： ％@popohito　ぽぽひと＠wordタケノコ粒あん党％これは別ツイートでも言及したんですが、労働問題や消費者問題だと死刑廃止論における被害者支援系弁護士ほど企業系弁護 http://kk2020-09.blogspot.com/2020/09/popohitoword_27.html

386	 - 2020年10月01日19時45分の登録： ＼ぽぽひと＠wordタケノコ粒あん党　@popohito＼公正世界仮説って現実には幻想なんだけど、フィクションの世界では基本的に守られていないと話が面白くないのよな。ちゃ http://kk2020-09.blogspot.com/2020/10/wordpopohito.html

387	 - 2020年10月01日19時48分の登録： ＼ぽぽひと＠wordタケノコ粒あん党　@popohito＼「自由刑で冤罪が発生してしまうのと同様に死刑で冤罪が発生してしまってもしょうがないんでねーの。冤罪で殺されてしま http://kk2020-09.blogspot.com/2020/10/wordpopohito_1.html

388	 - 2020年10月04日01時14分の登録： ＼ぽぽひと＠wordタケノコ粒あん党　@popohito＼あと、依頼者がモラハラ被害を訴えているってだけじゃなくて、モラハラ夫本人と直接やり取りして「そういうところだぞ」 http://kk2020-09.blogspot.com/2020/10/wordpopohito_4.html

389	 - 2020年10月04日14時43分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼返信先: @popohitoさん死刑になるような重大犯罪の被告人が金持ちのことあんまないでしょうしね…… http://kk2020-09.blogspot.com/2020/10/ksawmen-popohito.html

390	 - 2020年10月04日19時34分の登録： ＼ぽぽひと＠wordタケノコ粒あん党　@popohito＼こういうふうに、何が正しくて何が間違っているかを頭を使って考えることなくただひたすら左翼の逆張りをし続けるのが、 http://kk2020-09.blogspot.com/2020/10/wordpopohito_83.html

391	 - 2020年10月08日09時28分の登録： ＞@popohito　ぽぽひと＠wordタケノコ粒あん党＞RT　@fukazawas：　試験委員の誰かがふと思った。 \n まるで娘のような気持ちに・・。…\n http://kk2020-09.blogspot.com/2020/10/popohitowordrtfukazawas-n-n.html

392	 - 2020年10月08日21時53分の登録： ＼ぽぽひと＠wordタケノコ粒あん党　@popohito＼弁護士自治なんかもういらねーよと言いたくなくくらいのクソムーブを総本山執行部がしたかと思ったら、それをさらに越え http://kk2020-09.blogspot.com/2020/10/wordpopohito_8.html

393	 - 2020年10月14日08時45分の登録： ＼ぽぽひと＠wordタケノコ粒あん党　@popohito＼国選弁護や民事法律扶助でも責任は同じとされている弁護士のみなさーん！ http://kk2020-09.blogspot.com/2020/10/wordpopohito_14.html

```

* 「国選弁護や民事法律扶助でも責任は同じとされている弁護士のみなさーん！」という深澤諭史弁護士のリツイート

:CATEGORIES: 深澤諭史弁護士,国選弁護

- RT fukazawas（深澤諭史）｜popohito（ぽぽひと＠wordタケノコ粒あん党） 日時：2020/10/14 07:17／2020/10/14 07:15 URL： https://twitter.com/fukazawas/status/1316140976365170689 https://twitter.com/popohito/status/1316140593462927360

> RT @popohito: 国選弁護や民事法律扶助でも責任は同じとされている弁護士のみなさーん！ https://t.co/EYVkTA1oP6  

@popohito ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@popohito）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW popohito（ぽぽひと＠wordタケノコ粒あん党） 日時：2020/10/14 07:15 URL： https://twitter.com/popohito/status/1316140593462927360  

> 国選弁護や民事法律扶助でも責任は同じとされている弁護士のみなさーん！ https://t.co/EYVkTA1oP6  

 - 2020年10月14日08時45分の登録： ＼ぽぽひと＠wordタケノコ粒あん党　@popohito＼国選弁護や民事法律扶助でも責任は同じとされている弁護士のみなさーん！ http://kk2020-09.blogspot.com/2020/10/wordpopohito_14.html

 - 2020年10月14日10時31分の登録： ＼深澤諭史　@fukazawas　RT：　@popohito＼国選弁護や民事法律扶助でも責任は同じとされている弁護士のみなさーん！ http://kk2020-09.blogspot.com/2020/10/fukazawasrtpopohito.html

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-14 10:52／2020/10/14 08:49 URL： https://twitter.com/kk_hirono/status/1316195060933775360 https://twitter.com/s_hirono/status/1316164278336974848  

> 2020-10-14-084446_深澤諭史さんがリツイート￼ぽぽひと＠wordタケノコ粒あん党@popohito·1時間国選弁護や民事法律扶助でも責任は同じとされている弁護士.jpg https://t.co/jgVfrYt93L  

* 「「行政が違法なことをやっても、飯の話でもしてやれば庶民は騙くらかせる」って意味だぞこれ。」という泥濘大魔王サイケのツイート，深澤諭史弁護士のリツイート

:CATEGORIES: 深澤諭史弁護士,泥濘大魔王サイケ

@k_sawmen ===> You have been blocked from retweeting this user's tweets at their request.  
▷▷▷　次のツイートのアカウント（@k_sawmen）は，@kk_hironoをブロックしています。リツイートできませんでした。 ▷▷▷  

- TW k_sawmen（泥濘大魔王サイケ） 日時：2020/10/14 08:25 URL： https://twitter.com/k_sawmen/status/1316158240359546880  

> これに「そうだそうだ」って言ってる庶民、馬鹿にされてることに気づいてなくて笑える https://t.co/5gFh227X9e  

- RT fukazawas（深澤諭史）｜k_sawmen（泥濘大魔王サイケ） 日時：2020/10/14 08:55／2020/10/14 08:27 URL： https://twitter.com/fukazawas/status/1316165704639414272 https://twitter.com/k_sawmen/status/1316158553674018816

> RT @k_sawmen: 「行政が違法なことをやっても、飯の話でもしてやれば庶民は騙くらかせる」って意味だぞこれ。  

▶▶▶　kk_hironoのリツイート　▶▶▶  

- RT kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2020-10-14 10:58／2020/10/14 10:35 URL： https://twitter.com/kk_hirono/status/1316196735715209216 https://twitter.com/s_hirono/status/1316190750799847425  

> 2020-10-14-103400_深澤諭史さんがリツイート￼泥濘大魔王サイケ@k_sawmen·2時間「行政が違法なことをやっても、飯の話でもしてやれば庶民は騙くらかせる」っ.jpg https://t.co/uHyobg7OuE  

* 深澤諭史弁護士のタイムラインでリツイートとして見かけることの多い，@k_sawmen（泥濘大魔王サイケ）という匿名弁護士アカウント関連のツイートの全記録（2020年10月14日時点）

:CATEGORIES: 深澤諭史弁護士,泥濘大魔王サイケ

dp -p |grep k_sawmen |cat -n |sed 's/$/\n/'| sed -e 's/^   //'|xsel -b

```
  1	 - 2017年09月25日17時17分の登録： ＼泥濘大魔王サイケ‏ @k_sawmen＼あぁ……電通過労死で罰金50万円なら、通常の殺人罪も罰金50万円でいいですよね http://hirono2014sk.blogspot.com/2017/09/ksawmen5050.html

  2	 - 2017年09月26日10時09分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼弁護士会が民主的に運営されつつ人権活動をやるためには、こういう意見もきちっと聞かないといかんよな http://hirono2014sk.blogspot.com/2017/09/ksawmen.html

  3	 - 2017年09月29日09時18分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼弁護士会が民主的に運営されつつ人権活動をやるためには、こういう意見もきちっと聞かないといかんよな http://hirono2014sk.blogspot.com/2017/09/ksawmen_29.html

  4	 - 2017年09月30日15時44分の登録： ＞@fukazawas　深澤諭史＞RT　@k_sawmen：　あまねく全ての人権や権利を弁護士会が守れるなら、そりゃあそれが一番いいだろうけど、現実問題そうはいかんからな http://hirono2014sk.blogspot.com/2017/09/fukazawasrtksawmen.html

  5	 - 2017年10月10日20時56分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「自分だけ被害者面するな」、「自分も差別されている」と言うなら、まず自分が被害を訴えましょう。自分はただ差別に対して黙ってるだけなのに、 http://hirono2014sk.blogspot.com/2017/10/ksawmen.html

  6	 - 2017年10月17日00時23分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼イカとヒーローと人類滅亡の話しかしない弁護士の倫理観is最高 http://hirono2014sk.blogspot.com/2017/10/ksawmenis.html

  7	 - 2017年10月23日14時55分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼セーフティーネットは仕事じゃないっておま　セーフティーネットなめすぎだろ http://hirono2014sk.blogspot.com/2017/10/ksawmen_23.html

  8	 - 2017年10月28日11時11分の登録： ％@k_sawmen　泥濘大魔王サイケ％１０年後になれば稼げるかもしれないから直近の労働条件なんて気にするな！１０年後には若さは亡く、 http://hirono2014sk.blogspot.com/2017/10/ksawmen_28.html

  9	 - 2017年10月28日21時13分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼気持ち的には「これだけ会務で尽くしてきたのに？刑訴法の重大論点になりうる部分の訴訟なのに？なんで軽んじられるの！？」ってなるのは普 http://hirono2014sk.blogspot.com/2017/10/ksawmen_98.html

 10	 - 2017年10月29日11時44分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「発達障害は甘え」とか言っちゃう人は、「甘え」という言葉の便利さに甘えすぎだ http://hirono2014sk.blogspot.com/2017/10/ksawmen_29.html

 11	 - 2017年11月01日20時07分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼人間の子供苦手なんだけど、油断すると会務で法教育降ってくる http://hirono2014sk.blogspot.com/2017/11/ksawmen.html

 12	 - 2017年11月01日20時10分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼弁護士は人間じゃありませんから http://hirono2014sk.blogspot.com/2017/11/ksawmen_1.html

 13	 - 2017年11月12日20時08分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼他方、被害者のために弁護士が活動する場合、そのようなシステムはありません。\n代わりにあるのが、日弁連がお金を出す「委託援助」です。 http://hirono2014sk.blogspot.com/2017/11/ksawmen_12.html

 14	 - 2017年11月12日20時19分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼被告が本人訴訟だと答弁書が２通出てくるとか普通にあります http://hirono2014sk.blogspot.com/2017/11/ksawmen_26.html

 15	 - 2017年11月15日20時09分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼刑事弁護やってて「さすが国の作った制度！合理的だなぁ」なんて思ったこと一度でもあんのかよ http://hirono2014sk.blogspot.com/2017/11/ksawmen_15.html

 16	 - 2017年11月18日04時25分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼弁護士会、ITに関しては想像を絶するレベルでバカなんじゃねぇかと思い始めた\n2件の返信 4件のリツイート 12 いいね\n￼ http://hirono2014sk.blogspot.com/2017/11/ksawmenit-2-4-12.html

 17	 - 2017年11月21日09時17分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼事務所に居るだけで仕事が降ってくるんだからやめらんねぇよな　早独とか俺には考えられないわ http://hirono2014sk.blogspot.com/2017/11/ksawmen_21.html

 18	 - 2017年11月23日19時04分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼当職の弁護力は５３万である。しかし、もちろんフルパワーで本件訴訟を戦うつもりはないので、安心されたい。　#準備書面で使えない表現集 http://hirono2014sk.blogspot.com/2017/11/ksawmen_23.html

 19	 - 2017年12月03日13時23分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「感情の問題なのに法律を持ち出すな！」っていう人は、感情の問題で殺されても構わんってことなのかな http://hirono2014sk.blogspot.com/2017/12/ksawmen.html

 20	 - 2017年12月05日11時07分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「感情の問題なのに法律を持ち出すな！」っていう人は、感情の問題で殺されても構わんってことなのかな http://hirono2014sk.blogspot.com/2017/12/ksawmen_5.html

 21	 - 2017年12月10日17時26分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼おくたばり損なわれた妖怪ご老人の皆さまこそ票田であるため、そこに予算は突っ込まれる http://hirono2014sk.blogspot.com/2017/12/ksawmen_10.html

 22	 - 2017年12月16日15時36分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼某MLに早くも70期が加入している http://hirono2014sk.blogspot.com/2017/12/ksawmenml70.html

 23	 - 2017年12月16日15時53分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼今日から弁護士になった皆さん、おめでとうございます。これまでの、勉強して試験を受け、勉強して試験を受けての繰り返しの期間は長かった http://hirono2014sk.blogspot.com/2017/12/ksawmen_16.html

 24	 - 2017年12月19日20時03分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼これは本当に法曹界、ひいては日本社会に蔓延する病理だと思う。本来なら、労基法違反をやらかすような法律事務所など、代表は退会勧告され http://hirono2014sk.blogspot.com/2017/12/ksawmen_19.html

 25	 - 2017年12月20日13時18分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼今、日弁連が弁護士職務基本規程を改正しようとしていて、その中に、組織内弁護士以外にも「適正対応義務」を課すというものがある。すなわ http://hirono2014sk.blogspot.com/2017/12/ksawmen_20.html

 26	 - 2017年12月29日23時08分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼法テラス取扱の弁護士の質が低いっていう話。「それは事実か？」と言われたら「事実ではない。法テラス取扱の優秀な弁護士を何人も何人も知 http://hirono2014sk.blogspot.com/2017/12/ksawmen_29.html

 27	 - 2017年12月30日12時38分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼角界のイメージというのがおそらく、「無法地帯のイメージ」を指しているのでしょうね。傷害事件があろうと警察権力の介入を許さない世紀末 http://hirono2014sk.blogspot.com/2017/12/ksawmen_30.html

 28	 - 2018年01月02日19時44分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼俺がせっかく「法テラスだからサービスの質が下がるということはない」と強調しつつ「消費者としてはそういう心配をするのも無理からぬ部分 http://hirono2014sk.blogspot.com/2018/01/ksawmen.html

 29	 - 2018年01月02日19時45分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「最新パソコン、一万円です」って書いてあったら、「よほど質の悪い、バグとエラーだらけの欠陥品なのだろう」って思うでしょ？「法テラス http://hirono2014sk.blogspot.com/2018/01/ksawmen_2.html

 30	 - 2018年01月02日19時47分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼会費滞納してて、かつ会から連絡つかなくなっちゃってる先生とか、いらっしゃいますからね……懲戒制度の趣旨とは別のところで、退会の必要 http://hirono2014sk.blogspot.com/2018/01/ksawmen_52.html

 31	 - 2018年01月02日19時49分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼角界のイメージというのがおそらく、「無法地帯のイメージ」を指しているのでしょうね。傷害事件があろうと警察権力の介入を許さない世紀末 http://hirono2014sk.blogspot.com/2018/01/ksawmen_68.html

 32	 - 2018年01月02日19時51分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼弁護士会の会費は地域によりばらつきはあるものの相当程度馬鹿にならない額であること等を考えると、会費滞納のサンクションが横領より重い http://hirono2014sk.blogspot.com/2018/01/ksawmen_48.html

 33	 - 2018年01月24日23時37分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼魅力に限定したのは間違いでした。すみません。\n歴史や意義でもいいんです。\n今の弁護士会に興味を持てない若手たちに、弁護士会の在り方 http://hirono2014sk.blogspot.com/2018/01/ksawmen_24.html

 34	 - 2018年01月24日23時38分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼（こた先生に、ではなく、全弁護士に　ですね。失礼）期待してたんです。特にこた先生は会務に熱心で弁護士会の魅力に明るい方だから、その http://hirono2014sk.blogspot.com/2018/01/ksawmen_50.html

 35	 - 2018年01月24日23時39分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼弁護士なら、邪魔者扱いするくらいなら修習生受け入れなければいいですよね……\n公務員なら、修習生の育成も仕事のうちですよね…… http://hirono2014sk.blogspot.com/2018/01/ksawmen_55.html

 36	 - 2018年01月25日17時38分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼毎年1500人新人が入ってきて、その8割か9割が弁護士会に興味持ってない状況じゃあ、権力と戦う力を持ち続けられないよ http://hirono2014sk.blogspot.com/2018/01/ksawmen150089.html

 37	 - 2018年01月27日00時22分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼極端な話、今の弁護士会、日弁連に必要なのはアナーキーだとさえ思っている。アナーキーが既存の制度を破壊し、みんなが「やべぇ」と思って http://hirono2014sk.blogspot.com/2018/01/ksawmen_27.html

 38	 - 2018年02月01日11時25分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼かりんせ６５期だったんすか　もっと上かと（失礼） http://hirono2014sk.blogspot.com/2018/02/ksawmen.html

 39	 - 2018年02月05日21時35分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「働き方改革」は「残業代2倍」でうまくいく 「残業代ゼロ」制度や「裁量労働制」は逆効果 http://hirono2014sk.blogspot.com/2018/02/ksawmen2.html

 40	 - 2018年02月07日13時03分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼国選って、普通に接見して普通に保釈請求して普通に公判やったら、絶対にペイしない料金体系なんだよな。「やりがい搾取」という言葉がよく http://hirono2014sk.blogspot.com/2018/02/ksawmen_7.html

 41	 - 2018年02月10日01時04分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼日弁から送られてきた死刑廃止のパンフレット、「人は変わり得るという寛容が云々」ってのと「仮釈放のない終身刑で足りるはず」ってのが混 http://hirono2014sk.blogspot.com/2018/02/ksawmen_10.html

 42	 - 2018年02月10日11時45分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼深澤先生またつれてってください http://hirono2014sk.blogspot.com/2018/02/ksawmen_71.html

 43	 - 2018年02月12日13時54分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼デビルマンcrybabyすぎる http://hirono2014sk.blogspot.com/2018/02/ksawmencrybaby.html

 44	 - 2018年02月16日20時18分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼そんなくだんねぇこと議論してねぇで法科大学院の統廃合を進めろアホ http://hirono2014sk.blogspot.com/2018/02/ksawmen_16.html

 45	 - 2018年02月16日20時19分の登録： ＼深澤諭史　@fukazawas　RT：　@k_sawmen＼そんなくだんねぇこと議論してねぇで法科大学院の統廃合を進めろアホ http://hirono2014sk.blogspot.com/2018/02/fukazawasrtksawmen.html

 46	 - 2018年02月21日15時05分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼友人の薬剤師が「生活保護受給者は無駄にめちゃくちゃ薬をもらっていく。無料だからだ。絶対転売してる」などと主張していました。 「それ http://hirono2014sk.blogspot.com/2018/02/ksawmen_21.html

 47	 - 2018年03月08日19時09分の登録： ＼泥濘大魔王ジャイホー！バーフバリ！　@k_sawmen＼よくもまぁこんなに都合良く歴史を創作できますねぇ……しかも表現の自由まで特攻で守られたことにしちゃうし笑　明治憲 http://hirono2014sk.blogspot.com/2018/03/ksawmen.html

 48	 - 2018年03月15日20時01分の登録： ＼泥濘大魔王サイケ・オブ・ウォーター　@k_sawmen＼日弁連委託援助とか、金のない人々や国家により迫害されてる人々のために自腹切るのは弁護士会・日弁連の得意技じゃない http://hirono2014sk.blogspot.com/2018/03/ksawmen_15.html

 49	 - 2018年04月09日02時25分の登録： ＼泥濘大魔王サイケ・オブ・ウォーター　@k_sawmen＼弁護士「悔しいっ……けど……横領しちゃうっ……」ﾋﾞｸﾝﾋﾞｸﾝ 弁護士会「んほおおおお見舞金出ちゃうぅぅううう http://hirono2014sk.blogspot.com/2018/04/ksawmen.html

 50	 - 2018年04月13日05時10分の登録： ＼泥濘大魔王サイケ・オブ・ウォーター　@k_sawmen＼甲○号証○頁○行目「～」とあるのは、「～」の誤記である。これは、書類作成時にいたずら者の妖精さんが作成者の手元を http://hirono2014sk.blogspot.com/2018/04/ksawmen_13.html

 51	 - 2018年04月13日21時15分の登録： ＼泥濘大魔王サイケ・オブ・ウォーター　@k_sawmen＼俺たちは、政府から「シネ」って言われてるんだよ。 http://hirono2014sk.blogspot.com/2018/04/ksawmen_16.html

 52	 - 2018年04月16日15時33分の登録： ＼泥濘大魔王サイケ:アップライジング　@k_sawmen＼ストーカー関連の事件、まだ一件しかやってないんですけど、警察さんすごくちゃんと対応してくれました。気持ちよく協働 http://hirono2014sk.blogspot.com/2018/04/ksawmen_29.html

 53	 - 2018年04月18日15時50分の登録： ％@k_sawmen　泥濘大魔王サイケ:アップライジング％めつわか（人類滅亡を企む悪の若手弁護士の会：Society of Supervillain Young Lawy http://hirono2014sk.blogspot.com/2018/04/ksawmensociety-of-supervillain-young.html

 54	 - 2018年04月18日15時51分の登録： ＼泥濘大魔王サイケ:アップライジング　@k_sawmen＼青ヤギさんたら女生徒食べた 仕方がないから問題漏らした さっきの行為の対価はなぁに http://hirono2014sk.blogspot.com/2018/04/ksawmen_18.html

 55	 - 2018年04月18日15時52分の登録： ＼泥濘大魔王サイケ:アップライジング　@k_sawmen＼「火垂るの墓」につき、「戦災孤児は甘え」との意見を持つ人もいるのだなぁ。……貴様それでも人間か？ http://hirono2014sk.blogspot.com/2018/04/ksawmen_36.html

 56	 - 2018年04月18日15時54分の登録： ＼泥濘大魔王サイケ:アップライジング　@k_sawmen＼人間関係のトラブルのほとんどは、ククリナイフで解決できる http://hirono2014sk.blogspot.com/2018/04/ksawmen_53.html

 57	 - 2018年04月18日15時57分の登録： ＼泥濘大魔王サイケ:アップライジング　@k_sawmen＼「声をあげる女性の勇気を讃えること」と、「声をあげていない女性に声をあげろと要求すること」との間の一兆光年の距離 http://hirono2014sk.blogspot.com/2018/04/ksawmen_75.html

 58	 - 2018年04月21日17時25分の登録： ％@k_sawmen　泥濘大魔王サイケ:アップライジング％ 返信先: @motoken_twさん、@fukazawasさん\n\nなるほど、そうなんですね。ご教示ありがとうございます！\n http://hirono2014sk.blogspot.com/2018/04/ksawmen-motokentwfukazawasnnn.html

 59	 - 2018年04月23日16時16分の登録： ＃泥濘大魔王サイケ:アップライジング　@k_sawmen＃のツイート／記録作成措置実行日時：2018年04月23日16時16分 http://hirono2014sk.blogspot.com/2018/04/ksawmen201804231616.html

 60	 - 2018年04月24日03時21分の登録： ＼泥濘大魔王サイケ:アップライジング　@k_sawmen＼弁護そのものの質は国選と私選で変わるはずがないよね。国選の北パブと私選のブティックだったら絶対前者のほうが弁護の http://hirono2014sk.blogspot.com/2018/04/ksawmen_24.html

 61	 - 2018年04月24日10時47分の登録： ＃泥濘大魔王サイケ:アップライジング　@k_sawmen＃のツイート／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年04月24日10時47分 http://hirono2014sk.blogspot.com/2018/04/ksawmen201804241047.html

 62	 - 2018年04月25日10時56分の登録： ＃泥濘大魔王サイケ:アップライジング　@k_sawmen＃のツイート／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年04月25日10時56分 http://hirono2014sk.blogspot.com/2018/04/ksawmen201804251056.html

 63	 - 2018年05月07日14時51分の登録： ＃泥濘大魔王サイケ:アップライジング　@k_sawmen＃のツイート／2018-04-29_2041〜2018-05-07_1339／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年05月07日14時50分 http://hirono2014sk.blogspot.com/2018/05/ksawmen2018-04-2920412018-05.html

 64	 - 2018年05月10日13時02分の登録： ＃泥濘大魔王サイケ:アップライジング　@k_sawmen＃のツイート／2018-04-30_0329〜2018-05-10_1301／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年05月10日13時01分 http://hirono2014sk.blogspot.com/2018/05/ksawmen2018-04-3003292018-05.html

 65	 - 2018年05月17日21時07分の登録： ＃泥濘大魔王サイケ:アップライジング　@k_sawmen＃のツイート／2018-05-10_1745〜2018-05-17_2036／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年05月17日21時07分 http://hirono2014sk.blogspot.com/2018/05/ksawmen2018-05-1017452018-05.html

 66	 - 2018年05月23日00時20分の登録： ＃宇宙超泥濘サイケギドラ　@k_sawmen＃のツイート／2018-05-17_1755〜2018-05-22_2338／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年05月23日00時19分 http://hirono2014sk.blogspot.com/2018/05/ksawmen2018-05-1717552018-05.html

 67	 - 2018年05月24日22時42分の登録： ＃宇宙超泥濘サイケギドラ　@k_sawmen＃のツイート／2018-05-20_1319〜2018-05-24_2223／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年05月24日22時42分 http://hirono2014sk.blogspot.com/2018/05/ksawmen2018-05-2013192018-05.html

 68	 - 2018年05月28日20時59分の登録： ＃宇宙超泥濘サイケギドラ　@k_sawmen＃のツイート／2018-05-24_1204〜2018-05-28_1945／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年05月28日20時59分 http://hirono2014sk.blogspot.com/2018/05/ksawmen2018-05-2412042018-05.html

 69	 - 2018年05月31日21時06分の登録： ＃宇宙超泥濘サイケギドラ　@k_sawmen＃のツイート／2018-05-28_1727〜2018-05-31_2105／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年05月31日21時06分 http://hirono2014sk.blogspot.com/2018/05/ksawmen2018-05-2817272018-05.html

 70	 - 2018年06月03日15時13分の登録： ＼宇宙超泥濘サイケギドラ　@k_sawmen＼  おお……神よ……まさか哺乳類の中に、「精神的に追いつめられて自殺するのは自殺する奴の責任」なんて暴論を振りかざす者が居る http://hirono2014sk.blogspot.com/2018/06/ksawmen.html

 71	 - 2018年06月06日11時39分の登録： ＼宇宙超泥濘サイケギドラ　@k_sawmen＼人材が欲しければ待遇を上げる。きょうび中学生でもわかる対策があるぞ日経さんよ。 http://hirono2014sk.blogspot.com/2018/06/ksawmen_6.html

 72	 - 2018年06月06日11時39分の登録： ＃宇宙超泥濘サイケギドラ　@k_sawmen＃のツイート／2018-06-01_1227〜2018-06-06_0954／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年06月06日11時39分 http://hirono2014sk.blogspot.com/2018/06/ksawmen2018-06-0112272018-06.html

 73	 - 2018年06月08日17時03分の登録： ＼宇宙超泥濘サイケギドラ　@k_sawmen＼「キレる高裁判事」……クロ現あたりが特集しませんかね http://hirono2014sk.blogspot.com/2018/06/ksawmen_8.html

 74	 - 2018年06月08日17時03分の登録： ＃宇宙超泥濘サイケギドラ　@k_sawmen＃のツイート／2018-06-03_1613〜2018-06-08_1701／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年06月08日17時03分 http://hirono2014sk.blogspot.com/2018/06/ksawmen2018-06-0316132018-06.html

 75	 - 2018年06月10日22時43分の登録： ＼宇宙超泥濘サイケギドラ　@k_sawmen＼脱法行為とみなされた？疑われた？ — たぶんそういうことじゃなく、単に原告代理人の調査不足か検討不足かなんかなんでしょうね http://hirono2014sk.blogspot.com/2018/06/ksawmen_10.html

 76	 - 2018年06月10日22時43分の登録： ＃宇宙超泥濘サイケギドラ　@k_sawmen＃のツイート／2018-06-06_0848〜2018-06-10_2204／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年06月10日22時43分 http://hirono2014sk.blogspot.com/2018/06/ksawmen2018-06-0608482018-06.html

 77	 - 2018年06月11日22時49分の登録： ＼宇宙超泥濘サイケギドラ　@k_sawmen＼弁護士がオフに見るべきなのは、パシフィック・リムとか、ランペイジ巨獣大乱闘とか、デッドプールとか、そういう実務に役立つ格式高 http://hirono2014sk.blogspot.com/2018/06/ksawmen_11.html

 78	 - 2018年06月11日22時50分の登録： ＃宇宙超泥濘サイケギドラ　@k_sawmen＃のツイート／2018-06-07_0910〜2018-06-11_1941／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年06月11日22時50分 http://hirono2014sk.blogspot.com/2018/06/ksawmen2018-06-0709102018-06.html

 79	 - 2018年06月12日05時15分の登録： ＼宇宙超泥濘サイケギドラ　@k_sawmen＼在宅の被疑者に対して「ポリ公がサボってやがるのであんたの事件は全然進行してません」って伝える報告書、なかなか書きぶりが難しい http://hirono2014sk.blogspot.com/2018/06/ksawmen_12.html

 80	 - 2018年06月12日05時15分の登録： ＃宇宙超泥濘サイケギドラ　@k_sawmen＃のツイート／2018-06-07_0910〜2018-06-11_1941／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年06月12日05時15分 http://hirono2014sk.blogspot.com/2018/06/ksawmen2018-06-0709102018-06_12.html

 81	 - 2018年06月20日19時08分の登録： ＼宇宙超泥濘サイケギドラ　@k_sawmen＼相手方本人「俺には弁護士の知り合いがいるんだ」 俺「私も結構いますよ」 http://hirono2014sk.blogspot.com/2018/06/ksawmen_20.html

 82	 - 2018年06月20日19時08分の登録： ＃宇宙超泥濘サイケギドラ　@k_sawmen＃のツイート／2018-06-13_1609〜2018-06-20_1821／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年06月20日19時08分 http://hirono2014sk.blogspot.com/2018/06/ksawmen2018-06-1316092018-06.html

 83	 - 2018年07月03日13時58分の登録： ＼宇宙超泥濘サイケギドラ　@k_sawmen＼たばこもそう。「この草を燃やして吸うといい気分になる。ただし毒性が強いからフィルターで薄める。でも周りには毒性の強いままの煙 http://hirono2014sk.blogspot.com/2018/07/ksawmen.html

 84	 - 2018年07月03日13時59分の登録： ＃宇宙超泥濘サイケギドラ　@k_sawmen＃のツイート／2018-06-25_0132〜2018-07-03_1340／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年07月03日13時58分 http://hirono2014sk.blogspot.com/2018/07/ksawmen2018-06-2501322018-07.html

 85	 - 2018年07月24日05時34分の登録： ＼泥濘大魔王サイカク　@k_sawmen＼いろいろな言説が流れているが、俺の考えとしては ①人間の価値を生産性で見積もること自体が邪悪 ②生殖のみで人間の生産性を見積もる http://hirono2014sk.blogspot.com/2018/07/ksawmen_24.html

 86	 - 2018年07月24日05時34分の登録： ＃泥濘大魔王サイカク　@k_sawmen＃のツイート／2018-07-18_0020〜2018-07-24_0222／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年07月24日05時34分 http://hirono2014sk.blogspot.com/2018/07/ksawmen2018-07-1800202018-07.html

 87	 - 2018年08月23日02時08分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼某四大の先生が、「労働審判の最低着手金は○00万円」って仰ってたのを聞いたときに飛び出た目玉が今も行方不明です http://hirono2014sk.blogspot.com/2018/08/ksawmen00.html

 88	 - 2018年08月23日02時08分の登録： ＃泥濘大魔王サイケ　@k_sawmen＃のツイート／2018-08-16_1523〜2018-08-22_2316／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年08月23日02時08分 http://hirono2014sk.blogspot.com/2018/08/ksawmen2018-08-1615232018-08.html

 89	 - 2018年09月12日21時06分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼・弁護士向け あなたは、被疑者国選で受任している被疑者について、担当検察官から「先生が釈放後の示談交渉継続を約束してくれるなら処分 http://hirono2014sk.blogspot.com/2018/09/ksawmen.html

 90	 - 2018年09月12日21時07分の登録： ＃泥濘大魔王サイケ　@k_sawmen＃のツイート／2018-09-06_1026〜2018-09-12_2100／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年09月12日21時07分 http://hirono2014sk.blogspot.com/2018/09/ksawmen2018-09-0610262018-09.html

 91	 - 2018年09月15日14時52分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼検察官って、勾留請求をしたりする立場で、ある意味弁護士以上に人権を直接取扱う仕事なのよね。 司法試験も通らず「とりあえず勾留請求し http://hirono2014sk.blogspot.com/2018/09/ksawmen_15.html

 92	 - 2018年09月15日14時53分の登録： ＃泥濘大魔王サイケ　@k_sawmen＃のツイート／2018-09-07_2308〜2018-09-15_0939／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年09月15日14時52分 http://hirono2014sk.blogspot.com/2018/09/ksawmen2018-09-0723082018-09.html

 93	 - 2018年10月01日01時38分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼弁護団会議に間に合わずにネット経由で参加したら、ちょっと聞き取りにくいしこっちの声通ってるのかよくわからんしなんだか発言しにくかっ http://hirono2014sk.blogspot.com/2018/10/ksawmen.html

 94	 - 2018年10月01日01時38分の登録： ＃泥濘大魔王サイケ　@k_sawmen＃のツイート／2018-09-14_1958〜2018-09-30_2205／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年10月01日01時38分 http://hirono2014sk.blogspot.com/2018/10/ksawmen2018-09-1419582018-09.html

 95	 - 2018年10月04日19時22分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼人類滅亡を企む悪の若手弁護士の会（めつわか）と思想に一定の親和性が見られるので、めつわかに加入してもらうか検討してる http://hirono2014sk.blogspot.com/2018/10/ksawmen_4.html

 96	 - 2018年10月04日19時22分の登録： ＃泥濘大魔王サイケ　@k_sawmen＃のツイート／2018-09-19_1139〜2018-10-04_1818／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年10月04日19時22分 http://hirono2014sk.blogspot.com/2018/10/ksawmen2018-09-1911392018-10.html

 97	 - 2018年10月19日14時26分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「横領の証拠はない」から尋問が不当って……尋問って証拠を作るためのもんじゃないの http://hirono2014sk.blogspot.com/2018/10/ksawmen_19.html

 98	 - 2018年10月19日14時26分の登録： ＃泥濘大魔王サイケ　@k_sawmen＃のツイート／2018-09-27_1742〜2018-10-19_1400／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年10月19日14時26分 http://hirono2014sk.blogspot.com/2018/10/ksawmen2018-09-2717422018-10.html

 99	 - 2018年11月28日00時37分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼えらいひとの言う「弁護士への信頼」とは、「報酬を踏み倒しても法的手続はとらないだろうという信頼」を含むんですね http://hirono2014sk.blogspot.com/2018/11/ksawmen.html

100	 - 2018年11月28日00時38分の登録： ＃泥濘大魔王サイケ　@k_sawmen＃のツイート／2018-11-01_1314〜2018-11-27_1854／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年11月28日00時38分 http://hirono2014sk.blogspot.com/2018/11/ksawmen2018-11-0113142018-11.html

101	 - 2018年11月28日00時38分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼今のところ、刑事事件は被疑者被告人側：被害者側をだいたい５：５くらいで扱っている気がする。わりと理想的なバランスだと思うので、今後 http://hirono2014sk.blogspot.com/2018/11/ksawmen_28.html

102	 - 2018年11月30日11時37分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼生活保護って、受給が終わった後に任意に返還できる制度とかあったりしないのかな。「生活保護受けたらどうですか」っていうと嫌な顔する人 http://hirono2014sk.blogspot.com/2018/11/ksawmen_30.html

103	 - 2018年11月30日11時37分の登録： ＃泥濘大魔王サイケ　@k_sawmen＃のツイート／2018-11-02_1531〜2018-11-30_1034／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年11月30日11時37分 http://hirono2014sk.blogspot.com/2018/11/ksawmen2018-11-0215312018-11.html

104	 - 2018年12月27日14時16分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼そりゃあ、「通るように主張する」技術を大学四年、ロースクール二年、司法修習一年、プラス実務経験年数だけ学んできてるプロと無手の素人 http://hirono2014sk.blogspot.com/2018/12/ksawmen.html

105	 - 2018年12月27日14時16分の登録： ＃泥濘大魔王サイケ　@k_sawmen＃のツイート／2018-12-12_2035〜2018-12-27_1300／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2018年12月27日14時16分 http://hirono2014sk.blogspot.com/2018/12/ksawmen2018-12-1220352018-12.html

106	 - 2019年02月02日22時24分の登録： ＃泥濘大魔王サイケ　@k_sawmen＃のツイート／2019-01-18_1658〜2019-02-02_2205／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月02日22時24分 http://hirono2014sk.blogspot.com/2019/02/ksawmen2019-01-1816582019-02.html

107	 - 2019年02月02日22時24分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「好きな人と結婚する権利」は、相手との間に合意があれば、重婚等の婚姻障害に該当しない限りすべての人に保障されます……LGBTを除い http://hirono2014sk.blogspot.com/2019/02/ksawmenlgbt.html

108	 - 2019年02月04日21時47分の登録： ＃泥濘大魔王サイケ　@k_sawmen＃のツイート／2019-01-24_1353〜2019-02-04_2102／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月04日21時47分 http://hirono2014sk.blogspot.com/2019/02/ksawmen2019-01-2413532019-02.html

109	 - 2019年02月04日21時48分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼深澤諭史さんがリツイート＞　泥濘大魔王サイケ‏（@k_sawmen）：　新人が営業の電話に出ているのを聞いてて、なんかすごいハラハ http://hirono2014sk.blogspot.com/2019/02/ksawmenksawmen.html

110	 - 2019年02月06日19時42分の登録： ＃泥濘大魔王サイケ　@k_sawmen＃のツイート／2019-01-31_0950〜2019-02-06_1801／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月06日19時42分 http://hirono2014sk.blogspot.com/2019/02/ksawmen2019-01-3109502019-02.html

111	 - 2019年02月06日19時42分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼修習生がいることを事前に伝えているのに、器物損壊事件を配点してくる弁護士会　無能＆無能　勾留請求されず、勾留の争いを修習生に見せら http://hirono2014sk.blogspot.com/2019/02/ksawmen.html

112	 - 2019年02月15日10時49分の登録： ＃泥濘大魔王サイケ　@k_sawmen＃のツイート／2019-02-05_0859〜2019-02-15_1029／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年02月15日10時49分 http://hirono2014sk.blogspot.com/2019/02/ksawmen2019-02-0508592019-02.html

113	 - 2019年02月15日10時49分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼翻し方すごいですね……皿の裏を見ようとしてちゃぶ台の下に回ったような感じですね。\nセカンドオピニオンをとることを否定する趣旨ではな http://hirono2014sk.blogspot.com/2019/02/ksawmen_15.html

114	 - 2019年03月07日21時22分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼中大ローの商法学者さんは個性の強めな方が多くていらっしゃるのかしらねぇ http://hirono2014sk.blogspot.com/2019/03/ksawmen.html

115	 - 2019年04月05日01時20分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼マジで……日本の検察、控えめに言っても、アッタマおかしいんじゃねぇのか。日本の刑事司法、マジ中生代だな。 http://hirono2014sk.blogspot.com/2019/04/ksawmen.html

116	 - 2019年04月06日11時42分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼これ、本当だとすれば、裁判所を愚弄しすぎじゃないか。特捜ごとき（あえて「ごとき」という言葉を使う）が、裁判所の保釈条件をなんで反故 http://hirono2014sk.blogspot.com/2019/04/ksawmen_6.html

117	 - 2019年04月06日11時42分の登録： ＼venomy　@idleness_venomy＼＼泥濘大魔王サイケ　@k_sawmen＼これ、本当だとすれば、裁判所を愚弄しすぎじゃないか。特捜ごとき（あえて「ごとき」 http://hirono2014sk.blogspot.com/2019/04/venomyidlenessvenomyksawmen.html

118	 - 2019年04月09日10時20分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼ふーん、証拠や法律を検討したうえで「無罪判決はおかしい」と仰っていたんですか。それは存じませんで失礼しました。 http://hirono2014sk.blogspot.com/2019/04/ksawmen_9.html

119	 - 2019年04月12日08時48分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼見落としがちだが、一般の方は「刑事事件で加害者が無罪になったら、もはや被害者への救済は一切閉ざされる」と認識している可能性も高いの http://hirono2014sk.blogspot.com/2019/04/ksawmen_12.html

120	 - 2019年04月13日10時26分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「あれ？この人、思考から『被害者の気持ち』が抜けてないか？」っていう瞬間がある。認めの事件なら医療に繋いでいく案件だと思う。 http://hirono2014sk.blogspot.com/2019/04/ksawmen_13.html

121	 - 2019年04月13日11時42分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼というか、今回の不当懲戒請求は差別を原動力として弁護士自治を悪用して業務を妨害するものなので、きちっと最大限の責任を追及したほうが http://hirono2014sk.blogspot.com/2019/04/ksawmen_42.html

122	 - 2019年04月13日11時43分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼不当懲戒請求受けた人はどんどん訴訟したらいいと思う。先駆者たちに勝訴判決が出たんだし乗っかったらいいと思う。「勝ち馬に乗るのはださ http://hirono2014sk.blogspot.com/2019/04/ksawmen_46.html

123	 - 2019年04月15日20時02分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「弁護士同士なら名を名乗れ」っていうけど、弁護士に意見するためにTwitter上で名を名乗ったら、今後公権力を批判するときに匿名性 http://hirono2014sk.blogspot.com/2019/04/ksawmentwitter.html

124	 - 2019年04月16日23時53分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼とてもよいツリーですご査収ください http://hirono2014sk.blogspot.com/2019/04/ksawmen_16.html

125	 - 2019年04月18日21時38分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼ご自身で探した弁護士に、弁護士費用特約を使ってやってもらうこともできますよ。 http://hirono2014sk.blogspot.com/2019/04/ksawmen_18.html

126	 - 2019年04月18日21時38分の登録： ％@ponta_kobutori　こぶとりポン太90.6％＼泥濘大魔王サイケ　@k_sawmen＼ご自身で探した弁護士に、弁護士費用特約を使ってやってもらうこともできますよ。\n http://hirono2014sk.blogspot.com/2019/04/pontakobutori906ksawmenn.html

127	 - 2019年04月19日14時08分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼冤罪弁護で成果を挙げてない弁護士は黙れってよ。無罪推定についても冤罪についても語っちゃイカンらしいぜ。弁護士法1条の使命も忘れなよ http://hirono2014sk.blogspot.com/2019/04/ksawmen1.html

128	 - 2019年04月19日14時10分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼レッテル貼りで対立を煽るのが成果を挙げている弁護士のやり方なのでしょうか？ええ、ええ、私のこのツイートも疑問を呈しただけです。 http://hirono2014sk.blogspot.com/2019/04/ksawmen_19.html

129	 - 2019年04月20日14時38分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼ナプキン確認とか意味わからんです。単純に人権侵害。男子がずるいとかではなく、教師が完全に狂ってます。学校を訴えるレベルです。 http://hirono2014sk.blogspot.com/2019/04/ksawmen_20.html

130	 - 2019年04月25日22時05分の登録： ＼うるとら泥濘大魔王サイケ　@k_sawmen＼「弁護士資格と専門知識のぶん時間あたりの給与が高く設定されている従業員に、弁護士資格や専門知識と関係のない業務を割り振るの http://hirono2014sk.blogspot.com/2019/04/ksawmen_25.html

131	 - 2019年05月02日18時41分の登録： ＼うるとら泥濘大魔王サイケ　@k_sawmen＼法クラって好戦的だよなぁ　俺みたいな平和主義者は少ない http://hirono2014sk.blogspot.com/2019/05/ksawmen.html

132	 - 2019年05月03日19時56分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼ペットの餌やりとかですか……？ http://hirono2014sk.blogspot.com/2019/05/ksawmen_3.html

133	 - 2019年05月05日21時32分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼夜間や土日祝日の準抗告は蛇蝎のごとく嫌われるようで、「先生、暇人ですね」とか「嫌がらせですか？」とか言われることも、まれにあります http://hirono2014sk.blogspot.com/2019/05/ksawmen_5.html

134	 - 2019年05月05日21時33分の登録： ＼優良にゃん?　@jmtpjmgmt＼＼泥濘大魔王サイケ　@k_sawmen＼夜間や土日祝日の準抗告は蛇蝎のごとく嫌われるようで、「先生、暇人ですね」とか「嫌がらせですか http://hirono2014sk.blogspot.com/2019/05/jmtpjmgmtksawmen.html

135	 - 2019年05月07日17時20分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼スレイ http://hirono2014sk.blogspot.com/2019/05/ksawmen_7.html

136	 - 2019年05月08日18時46分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼原告側も支援傍聴とかしたほうがいいのかしら。期日と期日の間とかに聞きに行ってみようかしらん。 http://hirono2014sk.blogspot.com/2019/05/ksawmen_8.html

137	 - 2019年05月11日00時50分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼無罪の理由と関係ない（無罪の理由はあくまで客観的構成要件の不充足で、作文は故意の問題）ので特に指摘しませんでした。 http://hirono2014sk.blogspot.com/2019/05/ksawmen_11.html

138	 - 2019年05月12日13時33分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼さすがに「お願いされたら断れない人」や「裁判員制度に意義を感じる人」を全く想定しないのは…… http://hirono2014sk.blogspot.com/2019/05/ksawmen_12.html

139	 - 2019年05月13日21時02分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼法テラスから初級者向け説明会とかいうのの案内が届いた。法テラス初級者で……居たかった……なぁ……（ｶﾞｸｯ http://hirono2014sk.blogspot.com/2019/05/ksawmen_13.html

140	 - 2019年05月16日10時53分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼そりゃ、社名くらい明らかにして質問しなさいよ。表現の自由ってのは発言に対する責任を一切負わないことじゃない。 http://hirono2014sk.blogspot.com/2019/05/ksawmen_16.html

141	 - 2019年05月16日18時36分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼返信先: @jmtpjmgmtさん\nすげぇええええ……法律学んだ人誰もが一度は考えるけど決してやらないもんと思ってました……でもま http://hirono2014sk.blogspot.com/2019/05/ksawmen-jmtpjmgmt.html

142	 - 2019年05月16日18時36分の登録： ＼優良にゃん?　@jmtpjmgmt＼返信先: @k_sawmenさん\nおまわりもPも立件に超絶消極的でした。不思議なものです。 http://hirono2014sk.blogspot.com/2019/05/jmtpjmgmt-ksawmen-p.html

143	 - 2019年05月24日22時18分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼どうも、非弁取締の趣旨を弁護士の「業界保護」と勘違いしている方のようですね。 http://hirono2014sk.blogspot.com/2019/05/ksawmen_24.html

144	 - 2019年05月30日18時59分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼部屋にテレビとゲーム機　岩崎容疑者の自宅 - FNNプライムオンライン https://www.fnn.jp/posts/0041 http://hirono2014sk.blogspot.com/2019/05/ksawmen-fnn-httpswwwfnnjpposts0041.html

145	 - 2019年06月02日17時28分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「もう一度」もなにも、コイツはおそらく今まで一度も個人の尊厳について考えたことないでしょうね http://hirono2014sk.blogspot.com/2019/06/ksawmen.html

146	 - 2019年06月04日01時29分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼強制的夫婦同姓のコストが全面的に各個人に転嫁されてるの、どちゃくそ理不尽だよな…… http://hirono2014sk.blogspot.com/2019/06/ksawmen_4.html

147	 - 2019年06月07日20時40分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼家族への連絡、弁護人の義務だとしても最初の一報（身柄拘束場所が変わった際はそれも）だけでいいですよね。。。\nていうか、そもそも捜査 http://hirono2014sk.blogspot.com/2019/06/ksawmen_7.html

148	 - 2019年06月07日20時59分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼これ、単に「顔面でひとを～」ってのに加えて、「そもそも結婚＝子どもっていう考え方」、「（未来の）子どもまで顔面でDisる」、「子ど http://hirono2014sk.blogspot.com/2019/06/ksawmendis.html

149	 - 2019年06月07日20時59分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼某医師の某芸人と某女優が結婚したことに対する某「不細工いじり」、単なる不細工いじりであればここまで燃えなかっただろうけど、「生まれ http://hirono2014sk.blogspot.com/2019/06/ksawmen_83.html

150	 - 2019年06月11日12時26分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「性犯罪に遭った人に限定配布！」てアホかよ……なんで薬を渡すかどうかを患者が道徳的に正しいかどうかで選別しとるの？ってーか、安いゴ http://hirono2014sk.blogspot.com/2019/06/ksawmen_11.html

151	 - 2019年06月11日22時04分の登録： ＼小笠原 淳　@ogasawarajun＼深澤諭史さんがリツイート\n￼\n泥濘大魔王サイケ\n‏\n \n@k_sawmen\n 1日1日前\n￼ その他\n裁判官さんwwwww素人の http://hirono2014sk.blogspot.com/2019/06/ogasawarajun-ksawmen-11-wwwww.html

152	 - 2019年06月14日12時46分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼平均的な同期より50倍弁護士会の活動に参加している弁護士 http://hirono2014sk.blogspot.com/2019/06/ksawmen50.html

153	 - 2019年06月14日19時35分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼命の大切さを説いてる人だってたいてい、自国内で子どもが死んだニュースには大きく反応するけれど、発展途上国で毎日何人子どもが死んでて http://hirono2014sk.blogspot.com/2019/06/ksawmen_14.html

154	 - 2019年06月16日09時01分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼生活保護制度がないと、こういう「生きるため盗むのさ　仕方がないだろ」が増えていくわけですね http://hirono2014sk.blogspot.com/2019/06/ksawmen_16.html

155	 - 2019年06月18日13時17分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼杉田水脈ってやつは邪悪なうえに馬鹿なんだな。政治家としてこれ以上不適格な奴いるのかね。 http://hirono2014sk.blogspot.com/2019/06/ksawmen_18.html

156	 - 2019年06月18日13時18分の登録： ＼まゆこ　@mayukotaniguchi＼返信先: @k_sawmenさん、@jmtpjmgmtさん\nしかも私の地元の大学出身なので泣けてきます。 http://hirono2014sk.blogspot.com/2019/06/mayukotaniguchi-ksawmenjmtpjmgmt.html

157	 - 2019年06月18日20時00分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼返信先: @himaben1stさん\nこういう説諭してるとき裁判官絶対勃起してると思ってます http://hirono2014sk.blogspot.com/2019/06/ksawmen-himaben1st.html

158	 - 2019年06月18日20時01分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼返信先: @hirune_bさん、@himaben1stさん\nコカインくらいで10分も説教するネタがあるのは凄いですよね http://hirono2014sk.blogspot.com/2019/06/ksawmen-hirunebhimaben1st-10.html

159	 - 2019年06月18日20時01分の登録： ＼ひる寝べん　@hirune_b＼返信先: @k_sawmenさん、@himaben1stさん\nマスコミが傍聴きているから気合入っちゃったんでしょうかね。 http://hirono2014sk.blogspot.com/2019/06/hiruneb-ksawmenhimaben1st.html

160	 - 2019年06月19日22時23分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼裁判官が説諭で笑わせようとしてスベッたけど引っ込みつかずに１０分間説諭を続けたみたいな印象操作やめろ！！！ http://hirono2014sk.blogspot.com/2019/06/ksawmen_19.html

161	 - 2019年06月22日20時44分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「子の連れ去り」問題、たしかに現行制度だと別居親が会えるまでに時間かかりすぎとか色々問題はあるんだけど、DV受けて子ども連れずに別 http://hirono2014sk.blogspot.com/2019/06/ksawmendv.html

162	 - 2019年06月23日16時43分の登録： ％@k_sawmen　泥濘大魔王サイケ％あれ？こたんせ先生消えた？ http://hirono2014sk.blogspot.com/2019/06/ksawmen_23.html

163	 - 2019年06月29日22時34分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼刑事弁護は懲戒リスクをギリギリで回避する身のこなしと福祉との架け橋を作れるスキルと飽くなき情熱を併せ持つスーパー弁護士だけがやって http://hirono2014sk.blogspot.com/2019/06/ksawmen_29.html

164	 - 2019年06月29日22時35分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「まともな国選・民事法律扶助報酬を目指す会」とか作ってそこの代表が日弁連会長選挙に出たら当選するのではないか http://hirono2014sk.blogspot.com/2019/06/ksawmen_10.html

165	 - 2019年06月29日22時35分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼珍しく深澤先生がシビルウォーの当事者になろうとしている http://hirono2014sk.blogspot.com/2019/06/ksawmen_41.html

166	 - 2019年06月30日19時28分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「被害者支援弁護士がつくと刑事弁護がやりにくくなる」というのは、おそらく多くの刑事弁護人に共感される感覚ではないのではなかろうか。 http://hirono2014sk.blogspot.com/2019/06/ksawmen_30.html

167	 - 2019年06月30日22時13分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼これは本当にそう思う。せめて銀行預金の引き出しくらい、ポリ公が代理してやれよ。てめーらの都合で閉じこめてんだろうが http://hirono2014sk.blogspot.com/2019/06/ksawmen_76.html

168	 - 2019年07月01日22時42分の登録： ％@k_sawmen　泥濘大魔王サイケ％今、日弁連が弁護士職務基本規程を改正しようとしていて、その中に、組織内弁護士以外にも「適正対応義務」を課すというものがある。すなわ http://hirono2014sk.blogspot.com/2019/07/ksawmen.html

169	 - 2019年07月03日10時45分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼私は性犯罪の処罰範囲拡大には賛成の立場だけど、その方法論は慎重に検討しなくてはいけないと思う。「不同意性交」だと運用に委ねられる部 http://hirono2014sk.blogspot.com/2019/07/ksawmen_3.html

170	 - 2019年07月04日14時13分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼そもそも刑事裁判において「被告人に立証責任を負わせる」っていう発想が近代以降の刑事法的にイレギュラー中のイレギュラーなんですよ。 http://hirono2014sk.blogspot.com/2019/07/ksawmen_4.html

171	 - 2019年07月05日09時19分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼中さんが書かれているとおり、「後から訴えてくるかもしれない相手と、念書もなしにセックスした」から不同意性交罪に問われるという事例が http://hirono2014sk.blogspot.com/2019/07/ksawmen_5.html

172	 - 2019年07月05日09時20分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼を処罰する」法律になっちゃうんですよ。 http://hirono2014sk.blogspot.com/2019/07/ksawmen_53.html

173	 - 2019年07月05日23時43分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼場所はどちらでしたっけ（もし近場で弁護団組むなら参加したい） http://hirono2014sk.blogspot.com/2019/07/ksawmen_90.html

174	 - 2019年07月10日08時39分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼非弁提携してる弁護士も抹殺すべきだけど、業際非弁も抹殺すべきだよな…… http://hirono2014sk.blogspot.com/2019/07/ksawmen_10.html

175	 - 2019年07月10日20時57分の登録： ％@k_sawmen　泥濘大魔王サイケ％返信先: @kyoshimineさん\nや、ちゃいます。そうではなく、その先の「じゃあどういう規定ぶりなら、規制すべきウイルスの作 http://hirono2014sk.blogspot.com/2019/07/ksawmen-kyoshiminen.html

176	 - 2019年07月10日20時57分の登録： ％@k_sawmen　泥濘大魔王サイケ％この点、吉峰先生のご見解伺いたいです。恥ずかしながらプログラミングについては素人で、マイニングとかもざっくりと「前ブロックのハッシ http://hirono2014sk.blogspot.com/2019/07/ksawmen_58.html

177	 - 2019年07月10日20時58分の登録： ％@k_sawmen　泥濘大魔王サイケ％閲覧者のPCでバックグラウンド実行してコインを得てたのがコインハイブ事件だと思うのですが、これを法文上どうやってウイルスと区別しうるでしょう……素人感覚だとそこの想像がつかないのです。 http://hirono2014sk.blogspot.com/2019/07/ksawmenpc.html

178	 - 2019年07月11日02時41分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼不当懲戒請求の件、弁護士費用が認められない意味がわからんよな。大工が家を壊されて損害賠償請求したら「原告は大工だから自分で建て直せ http://hirono2014sk.blogspot.com/2019/07/ksawmen_11.html

179	 - 2019年07月16日11時11分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼私が刑事弁護で説教をするのは、被疑者・被告人が反省の基礎材料を持ってないとき（言うまでもないが自白事件前提）だな。たとえば痴漢事件 http://hirono2014sk.blogspot.com/2019/07/ksawmen_16.html

180	 - 2019年07月16日11時23分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼みんな逮捕された弁護士を優良先生と誤認しすぎ。優良誤認。 http://hirono2014sk.blogspot.com/2019/07/ksawmen_35.html

181	 - 2019年07月16日11時26分の登録： ＼弁護士　野田隼人　@nodahayato＼返信先: @k_sawmenさん\n嗜虐性からくる性犯罪の場合，被害者の感情の追体験はかえって犯罪を誘発する危険があるという論文 http://hirono2014sk.blogspot.com/2019/07/nodahayato-ksawmen.html

182	 - 2019年07月17日19時09分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼警察が批判されてるときに「この法律が～」って持ち出した素人が専門家に反論されて「でもマナーが」って言いよどんじゃうの、警察がマナー http://hirono2014sk.blogspot.com/2019/07/ksawmen_17.html

183	 - 2019年07月21日12時47分の登録： ＃泥濘大魔王サイケ　@k_sawmen＃のツイート／2019-07-18_2314〜2019-07-20_2353／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年07月21日12時46分 http://hirono2014sk.blogspot.com/2019/07/ksawmen2019-07-1823142019-07.html

184	 - 2019年07月22日17時55分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼要するに、「日常困っていることから距離のある」「政治的お念仏」ってのは、「少数者の権利など、念仏に過ぎない」、「少数者が困っていて http://hirono2014sk.blogspot.com/2019/07/ksawmen_22.html

185	 - 2019年07月25日00時16分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼マイノリティの権利を実現しようって話に「マジョリティの顔色を窺おう」って返すのはセンスがないんですよね http://hirono2014sk.blogspot.com/2019/07/ksawmen_25.html

186	 - 2019年07月25日13時56分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼日本弁護士連合会：同性婚に関する法整備を求める人権救済申立事件（意見書）  http://hirono2014sk.blogspot.com/2019/07/ksawmen_96.html

187	 - 2019年07月25日23時23分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼政治権力にヘコヘコすり寄ってる商法学者の話はしたくない気分です http://hirono2014sk.blogspot.com/2019/07/ksawmen_7.html

188	 - 2019年07月26日17時02分の登録： ＼深澤諭史　@fukazawas＼返信先: \n@k_sawmen\n さん、 \n@un_co_the2nd\nさん\n（；・∀・）弁護士から報酬決定の自由、経済的自由を奪い取っ http://hirono2014sk.blogspot.com/2019/07/fukazawas-ksawmen-uncothe2nd.html

189	 - 2019年07月28日01時25分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼とてもありがたいです。全部証拠が残る。 http://hirono2014sk.blogspot.com/2019/07/ksawmen_28.html

190	 - 2019年08月03日11時02分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼重大事件の被害者の実名公表が事件から時間経ってて「きわめて異例」とかいうけど、そもそも被害者の実名公表する必要性ないだろ。お前ら単 http://hirono2014sk.blogspot.com/2019/08/ksawmen.html

191	 - 2019年08月08日16時39分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼俺が弁護団に入るとなぜか同じ弁護団に入る後輩がいるのだが、そいつは俺より優秀なので、俺は弁護団に入ってそいつが入るのを待ってれば弁 http://hirono2014sk.blogspot.com/2019/08/ksawmen_8.html

192	 - 2019年08月19日19時44分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼リプ欄がさらに義務教育の敗北って感じですね http://hirono2014sk.blogspot.com/2019/08/ksawmen_19.html

193	 - 2019年08月22日11時10分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「事件報道の真実性担保」は一見もっともらしいが、これもなぁ。マスコミなら事件の発生自体くらいは取材で調べられるだろうし（例の件もマ http://hirono2014sk.blogspot.com/2019/08/ksawmen_22.html

194	 - 2019年08月28日13時14分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼さらっと司法改革の闇をぶちまけるスタイル素敵です http://hirono2014sk.blogspot.com/2019/08/ksawmen_28.html

195	 - 2019年09月04日21時03分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼事務所に入った若手が一年以内に離職する率○○○%を誇るうちのクラスの刑弁教官の話はやめてください！！ http://hirono2014sk.blogspot.com/2019/09/ksawmen.html

196	 - 2019年10月02日13時19分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼深澤諭史さんがリツイート泥濘大魔王サイケ@k_sawmen·2h副検事・簡裁判事、本当に意味不明の制度だしマジで百害あって一利なし http://hirono2014sk.blogspot.com/2019/10/ksawmenksawmen2h.html

197	 - 2019年10月06日09時26分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼人権大会、地方でやってオンライン中継とかオンライン参加とか認めないあたり、「人権活動は暇な金持ちの道楽ないし特権」っていう感覚を醸 http://hirono2014sk.blogspot.com/2019/10/ksawmen.html

198	 - 2019年10月08日08時52分の登録： ％@k_sawmen　泥濘大魔王サイケ％いちおう、弁護士法一条二項には、弁護士はその使命に基づき「社会秩序の維持及び法律制度の改善に努力しなければならない」と規定されてますね http://hirono2014sk.blogspot.com/2019/10/ksawmen_8.html

199	 - 2019年10月08日19時51分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼法クラが怖いのは、この事実調査能力も一因ですよね。普段からいろんな証拠集めをやってるので、暇つぶしにささっと検索するだけでも人の黒 http://hirono2014sk.blogspot.com/2019/10/ksawmen_72.html

200	 - 2019年10月10日19時23分の登録： ＼モトケン　@motoken_tw＼返信先: \n@k_sawmen\nさん\n一件程度では甘く見られてるみたいですね。\n神戸は市長が味方になりますから、どんどん告訴してほしい http://hirono2014sk.blogspot.com/2019/10/motokentw-ksawmen.html

201	 - 2019年10月10日19時25分の登録： ＼モトケン　@motoken_tw＼返信先: \n@k_sawmen\nさん\n事故発生のニュースだけじゃなくて、教員が刑事責任を問われたというニュースが一件でもあれば、びびり http://hirono2014sk.blogspot.com/2019/10/motokentw-ksawmen_10.html

202	 - 2019年10月10日19時26分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼組体操で重大な事故が発生したニュースを集め、まとめて学校に提出したら、びびって組体操やめる学校けっこうあるんじゃねぇのかしら http://hirono2014sk.blogspot.com/2019/10/ksawmen_10.html

203	 - 2019年10月10日19時27分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼返信先: \n@motoken_tw\nさん\n今ぱっと調べたら、1990年に相模原市で中学生が組体操中に亡くなって保健体育の教員が書類 http://hirono2014sk.blogspot.com/2019/10/ksawmen-motokentw-1990.html

204	 - 2019年10月10日20時57分の登録： ＼ystk　@lawkus＼返信先: \n@battamon_black\n さん、 \n@k_sawmen\nさん\nその場合、裁判所としては独断で口頭のみの告知で済ませるのでは http://hirono2014sk.blogspot.com/2019/10/ystklawkus-battamonblack-ksawmen.html

205	 - 2019年10月19日16時36分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼東京オリンピック招致を批判する人もいるけど、オリンピック招致の段階で、夏場の東京が暑すぎて競技に適しないとか、東京湾が汚すぎて競技 http://hirono2014sk.blogspot.com/2019/10/ksawmen_19.html

206	 - 2019年10月23日18時37分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼返信先: \n@fukazawas\nさん\n20億円くらいあげたらいいのにと思いますね http://hirono2014sk.blogspot.com/2019/10/ksawmen-fukazawas-20.html

207	 - 2019年10月25日14時07分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼たしかに。東京であのキャラの濃さに対抗できそうなのは優良先生くらいかしら。 http://hirono2014sk.blogspot.com/2019/10/ksawmen_25.html

208	 - 2019年10月30日20時13分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「税金がー財源がー」って言うけど、国庫に全くカネがないわけじゃないんだから、「今現在それにかかる予算を超える税金を投入しているすべ http://hirono2014sk.blogspot.com/2019/10/ksawmen_30.html

209	 - 2019年11月01日17時16分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼前に高名な刑事弁護人の先生が、強制性交等罪の暴行脅迫要件について、実務上は空文化してるようなこと言ってたけど……被害者側をやらない http://hirono2014sk.blogspot.com/2019/11/ksawmen.html

210	 - 2019年11月01日21時52分の登録： ＼弁護士　野田隼人　@nodahayato＼返信先: \n@k_sawmen\nさん\nなかなか立件しない反面、立件すると無理から有罪に振るというピーキーな仕様。 http://hirono2014sk.blogspot.com/2019/11/nodahayato-ksawmen.html

211	 - 2019年11月03日14時30分の登録： ％@fukazawas　深澤諭史％@k_sawmen\n \n@to7shi1ki7\n \nたぶん，関係者が，Ｔｗｉｔｔｅｒのログを司法研修所に送ったのだろう。\n（・∀・） http://hirono2014sk.blogspot.com/2019/11/fukazawasksawmenn-nto7shi1ki7n-nn.html

212	 - 2019年11月09日00時32分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼まあ、私も（ちょい古めの？）少年漫画では性犯罪被害の扱われ方が軽いよなぁとは思いますけどね。例えば男性が女性の意に反して性的な接触 http://hirono2014sk.blogspot.com/2019/11/ksawmen_9.html

213	 - 2019年11月09日00時34分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼お師さん……また……温もりを…… http://hirono2014sk.blogspot.com/2019/11/ksawmen_86.html

214	 - 2019年11月11日08時02分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「この属性の奴が人を殺した。だからこの属性の奴らは悪だ」っていうド直球差別を煽る報道をした連中とそれに飛びついた連中も、恨まれて当 http://hirono2014sk.blogspot.com/2019/11/ksawmen_11.html

215	 - 2019年11月17日21時08分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「権力者の不正を見逃せ」という理由付けのために被災者を持ち出す卑怯者。それでもウルトラマンか。 http://hirono2014sk.blogspot.com/2019/11/ksawmen_17.html

216	 - 2019年11月24日11時33分の登録： ＃泥濘大魔王サイケ　@k_sawmen＃のツイート／2019-11-15_1011〜2019-11-24_0950／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2019年11月24日11時33分 http://hirono2014sk.blogspot.com/2019/11/ksawmen2019-11-1510112019-11.html

217	 - 2019年11月24日11時46分の登録： REGEXP：”@k_sawmen”／データベース登録済みツイート：2019年11月24日11時42分の記録：ユーザ・投稿：110／890件 http://hirono2014sk.blogspot.com/2019/11/regexpksawmen201911241142110890.html

218	 - 2019年11月24日11時49分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼当然だけど、弁護士全員が俺みたいに人格円満温厚穏和清廉潔白公明正大ってわけじゃないんだよね http://hirono2014sk.blogspot.com/2019/11/ksawmen_24.html

219	 - 2019年12月12日17時38分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼法クラ流行語大賞、ここにきて「神は常に最上ですよ」とかいう有力候補出現 http://hirono2014sk.blogspot.com/2019/12/ksawmen.html

220	 - 2019年12月12日18時30分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼普段は冤罪に全く気を払っておらず逮捕報道とかを有罪前提で論じちゃう人が痴漢についてだけ冤罪冤罪言ってるのはクソ寒いが、だからといっ http://hirono2014sk.blogspot.com/2019/12/ksawmen_12.html

221	 - 2019年12月20日13時22分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼来年も事務所に修習生が来るので、年末はあまり先回りしての起案をしないようにと兄弁からやんわり注意を受けた http://hirono2014sk.blogspot.com/2019/12/ksawmen_20.html

222	 - 2020年01月01日14時19分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼美空ひばりとか世代じゃないから名前しか知らないし、生命倫理とかにも疎いのだが、「故人をAIで復活させて歌を歌わせました」ってのはな http://hirono2014sk.blogspot.com/2020/01/ksawmenai.html

223	 - 2020年01月01日20時09分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼これまで弁護士・弁護士会がどれだけ人質司法と戦ったのか、その歴史の断片でも知ってれば出てこない台詞。まちがったらすなおにごめんなさ http://hirono2014sk.blogspot.com/2020/01/ksawmen.html

224	 - 2020年01月01日20時11分の登録： ＼鳩屋　@haya_rt＼返信先: \n@k_sawmen\nさん\n接見交通の問題で弁護士が警察署に接見に行ったら警察官に暴行されたと言うのを見た時は戦慄しました。 http://hirono2014sk.blogspot.com/2020/01/hayart-ksawmen.html

225	 - 2020年01月01日22時36分の登録： ＃泥濘大魔王サイケ　@k_sawmen＃のツイート／2019-12-27_0807〜2020-01-01_2207／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2020年01月01日22時36分 http://hirono2014sk.blogspot.com/2020/01/ksawmen2019-12-2708072020-01.html

226	 - 2020年01月07日19時13分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼東京地検、ゴーン氏の妻の身柄取るの？マジで？このタイミングで？本気？ http://hirono2014sk.blogspot.com/2020/01/ksawmen_7.html

227	 - 2020年01月07日19時14分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼ゴーン被告の妻 キャロル容疑者に逮捕状 偽証の疑い | NHKニュース http://hirono2014sk.blogspot.com/2020/01/ksawmen-nhk.html

228	 - 2020年01月22日17時20分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼刑事弁護関係は簡単に荒れる。熱心に考えている人が多いから。 http://hirono2014sk.blogspot.com/2020/01/ksawmen_22.html

229	 - 2020年01月22日19時57分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼さらっと冒頭に書いてますが、「逃亡請負人」ってこれ名誉棄損では？弘中先生がゴーンの”逃亡に”手を貸したって言ってるわけですよね。 http://hirono2014sk.blogspot.com/2020/01/ksawmen_33.html

230	 - 2020年02月03日09時12分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼異性カップルが必ず子どもを産むと思ってるのか？安倍晋三って知ってるか？\n引用ツイート\n http://hirono2014sk.blogspot.com/2020/02/ksawmen.html

231	 - 2020年02月03日20時13分の登録： ＃泥濘大魔王サイケ　@k_sawmen＃のツイート／2020-01-31_1028〜2020-02-03_1918／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2020年02月03日20時13分 http://hirono2014sk.blogspot.com/2020/02/ksawmen2020-01-3110282020-02.html

232	 - 2020年02月07日11時14分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼会長選投票後、本を見てたらオッサンに「先生、国民年金基金入ってますか？！」と言われた。この俺様をネズミ講なんぞに誘うつもりか塵芥が http://hirono2014sk.blogspot.com/2020/02/ksawmen_7.html

233	 - 2020年02月08日20時37分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼昭和天皇の顔写真を燃やす→表現の自由\nマッドサイエンティストキャラに「丸太」と名付ける→表現の自由\n上記「丸太」を批判する→表現の http://hirono2014sk.blogspot.com/2020/02/ksawmen_8.html

234	 - 2020年02月10日18時05分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼人類滅亡に向けた具体的な政策と努力です http://hirono2014sk.blogspot.com/2020/02/ksawmen_10.html

235	 - 2020年02月15日13時19分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼泥濘大魔王サイケ@k_sawmen·33分最近モトケン先生とおぐりん先生のケンカ見てない気がする\n http://hirono2014sk.blogspot.com/2020/02/ksawmenksawmen33.html

236	 - 2020年02月21日21時33分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼非弁対策に明るい弁護士（といっても、私の知ってる範囲って非常に狭くて、深澤先生含めて数名だけど）はわりと山岸候補陣営にいますね。 http://hirono2014sk.blogspot.com/2020/02/ksawmen_21.html

237	 - 2020年02月26日23時33分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼証拠のねつ造で有罪判決受けた元検察官を弁護士会が登録拒否した件、難しいよなぁ。\nそりゃ一般論としては、犯罪者も贖罪後の再起を妨げら http://hirono2014sk.blogspot.com/2020/02/ksawmen_26.html

238	 - 2020年03月03日19時25分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼その程度の学生しか入学させられない、魅力のない法科大学院は、市場原理に従って淘汰されるべきなのでは？ http://hirono2014sk.blogspot.com/2020/03/ksawmen.html

239	 - 2020年03月07日02時02分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼個々の裁判官の頑張りで解決するよりは、ちゃんと裁判所の建物拡張して裁判官を増やし、裁判官一人あたりの手持ち事件数を減らして解決した http://hirono2014sk.blogspot.com/2020/03/ksawmen_7.html

240	 - 2020年03月09日12時03分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼深澤諭史さんがリツイート\n￼\n泥濘大魔王サイケ\n@k_sawmen\n·\n19分\nどうせ誰が会長になっても谷間世代は負債を背負い続け http://hirono2014sk.blogspot.com/2020/03/ksawmen-ksawmen-19.html

241	 - 2020年03月09日18時55分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼受刑者であってもパートナーとの性交渉を含む面会を認めても差し支えないはず http://hirono2014sk.blogspot.com/2020/03/ksawmen_9.html

242	 - 2020年03月11日17時58分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼アラチュウが当選なのか。 http://hirono2014sk.blogspot.com/2020/03/ksawmen_11.html

243	 - 2020年03月11日23時20分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼たま市マジ頭おかしいのか。ガキの健康人質にとって言うこと聞かせようってか？ヤクザか？ http://hirono2014sk.blogspot.com/2020/03/ksawmen_66.html

244	 - 2020年03月25日19時19分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼米がないなら和牛を食べればいいじゃない http://hirono2014sk.blogspot.com/2020/03/ksawmen_25.html

245	 - 2020年03月31日14時15分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼日本では増えていないのだろうか。捕捉されていないだけではないだろうか。外出が制限されたストレスが家庭内で弱者に向かう構図は日本でも http://hirono2014sk.blogspot.com/2020/03/ksawmen_31.html

246	 - 2020年04月04日16時18分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼政治家の風刺をすると今まで築き上げてきた物が一気に崩れるって……北の将軍様かよ。ネトウヨども、日本を馬鹿にするのも大概にせえよ http://hirono2014sk.blogspot.com/2020/04/ksawmen.html

247	 - 2020年04月07日23時03分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼老人に向けて思い切り咳をしましょう。老人が泣くまでしましょう http://hirono2014sk.blogspot.com/2020/04/ksawmen_7.html

248	 - 2020年04月08日12時05分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼返信先: \n@popohito\nさん\nツイッターの法クラ（の特に声の大きい人たち）が弁護士全体を代表しないのと同様、ネットででかい http://hirono2014sk.blogspot.com/2020/04/ksawmen-popohito.html

249	 - 2020年04月08日19時51分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼なんでドラッグストアにやるんだ　官邸でやれ官邸で http://hirono2014sk.blogspot.com/2020/04/ksawmen_8.html

250	 - 2020年04月08日20時01分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼？？「私や妻が関わっていたら辞職」\n引用ツイート\n http://hirono2014sk.blogspot.com/2020/04/ksawmen_46.html

251	 - 2020年04月10日13時13分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼普段から弁護士をマトモに尊重していたら、「こんな事態だから仕方ない。みんなで法テラスを支えよう」ってなりますよ。 http://hirono2014sk.blogspot.com/2020/04/ksawmen_10.html

252	 - 2020年04月15日16時53分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼多摩地域の若手弁護士が有志で、多摩の高齢者・障害者の法律相談をしているそうです。電話相談は30分無料、ご家族・支援者の方からのご相 http://hirono2014sk.blogspot.com/2020/04/ksawmen30.html

253	 - 2020年04月20日12時33分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼何かきれいな「目的」さえあれば、法律の定めも何もかもすっ飛ばして、権力がその思うとおりに振る舞える……そういう状態が一番危険だとい http://hirono2014sk.blogspot.com/2020/04/ksawmen_20.html

254	 - 2020年04月30日20時40分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼税金、8割くらい抑えられたのでは……？って思うよね。\n要するに466億円のうち8割の370億円は、安倍友に配ったんでしょ……？ http://hirono2014sk.blogspot.com/2020/04/ksawmen8-4668370.html

255	 - 2020年04月30日20時41分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼いや、あれは下ネタだから炎上したのではなくて、「他人が貧困に陥って、ある事を嫌々やらざるを得なくなるのが楽しみ」っていう悪性に、よ http://hirono2014sk.blogspot.com/2020/04/ksawmen_30.html

256	 - 2020年05月08日19時14分の登録： ％@k_sawmen　泥濘大魔王サイケ％主要な法クラであり大魔王です。よろしくお願いします。\n引用ツイート\n http://hirono2014sk.blogspot.com/2020/05/ksawmennn.html

257	 - 2020年05月10日17時07分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼シン・ゴジラは凄いよなぁ……基本ヒューマンドラマなんだけど、恋愛要素はほとんど徹底的に排除してひたすら戦略と精神力で魅せてくる。ゴ http://hirono2014sk.blogspot.com/2020/05/ksawmen.html

258	 - 2020年05月12日14時57分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼それでは聞いてください。「ヘドラをやっつけろ」 ♪光るヘドラの熱戦銃　走るゴジラの放射能 がんばれがんばれ僕らのゴジラ がんばれが http://hirono2014sk.blogspot.com/2020/05/ksawmen_12.html

259	 - 2020年05月12日18時48分の登録： TWEET：”2014-05-11 14:42〜2020-05-09 15:02”／泥濘大魔王サイケ（@k_sawmen）の検索（2020年05月12日18時47分の記録1614件） http://hirono2014sk.blogspot.com/2020/05/tweet2014-05-11-14422020-05-09.html

260	 - 2020年06月12日19時35分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼下限が三年の自由刑な犯罪って刑法だと ・内乱謀議参与、群衆指揮（禁錮３～） ・現住建造物等浸害（懲役３～死） ・現に人がいる汽車・ http://hirono2014sk.blogspot.com/2020/06/ksawmen.html

261	 - 2020年06月24日12時27分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼ちぇんちぇーは法学らなくて医学が専門なのよさ http://hirono2014sk.blogspot.com/2020/06/ksawmen_24.html

262	 - 2020年07月14日20時51分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼GoToトラベル、「いまさら止められない」はマジウケるな。太平洋戦争かよ http://hirono2014sk.blogspot.com/2020/07/ksawmengoto.html

263	 - 2020年07月16日20時03分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼Go　To事業は東京除外し22日から実施 | 2020/7/16 - 共同通信 http://hirono2014sk.blogspot.com/2020/07/ksawmengoto22-2020716.html

264	 - 2020年07月19日23時34分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼内容の真実性とおもしろさにあまり相関を感じない者 http://hirono2014sk.blogspot.com/2020/07/ksawmen.html

265	 - 2020年07月21日11時22分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「ドーモ、非弁業者=サン、非弁スレイヤーです。非弁殺すべし！殺す前にインタビューをする。正直に答えればカイシャクしてやる」 http://hirono2014sk.blogspot.com/2020/07/ksawmen_21.html

266	 - 2020年07月23日20時52分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼公務員だからわかんないのは仕方ないけど、わかんないくせに上から物言って、指摘されたら機嫌損ねるとか、クソガキ裁判官ですねぇ http://hirono2014sk.blogspot.com/2020/07/ksawmen_23.html

267	 - 2020年07月24日16時26分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼最近の深澤先生、寄生獣の最初のナレーションにハマってるな笑 http://hirono2014sk.blogspot.com/2020/07/ksawmen_24.html

268	 - 2020年08月10日12時55分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼Gotoで全国に感染の輪が広がっていったの、和をもって尊しとなすって感じでとても日本的。 http://hirono2014sk.blogspot.com/2020/08/ksawmengoto.html

269	 - 2020年08月12日21時39分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼周庭氏保釈の件で弁護士がざわついてるのをネトウヨっぽい人が「なに言ってるんだ他のところで中国は人権後進国！弁護士頭おかしい」みたい http://hirono2014sk.blogspot.com/2020/08/ksawmen.html

270	 - 2020年08月15日22時31分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼戦没者に感謝って意味わからんよな。飢え死にしてくれてありがとうって？ http://hirono2014sk.blogspot.com/2020/08/ksawmen_15.html

271	 - 2020年08月16日13時43分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼見なされるわけねぇだろふざけんな http://hirono2014sk.blogspot.com/2020/08/ksawmen_16.html

272	 - 2020年08月18日12時33分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼四大の若手ってけっこう、その辺の町弁よりずっと人権活動やってたりするよね。「あなたの体と家族のほうが大事では？」って思ったりもする http://hirono2014sk.blogspot.com/2020/08/ksawmen_18.html

273	 - 2020年08月22日01時34分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼事理弁識能力がグチャミソになってる弁護士、弁護士会でどうにか処理する方法作らないとダメでしょこれ…… http://hirono2014sk.blogspot.com/2020/08/ksawmen_22.html

274	 - 2020年08月23日01時13分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「本当はやっているのに無罪になった場合」って、たいていは警察・検察が証拠収集の過程で重大な違法を犯した場合ですね。 http://hirono2014sk.blogspot.com/2020/08/ksawmen_23.html

275	 - 2020年08月23日08時48分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「本当はやっているのに無罪になった場合」って、たいていは警察・検察が証拠収集の過程で重大な違法を犯した場合ですね。 http://hirono2014sk.blogspot.com/2020/08/ksawmen_66.html

276	 - 2020年08月26日21時11分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼仮に検察官が準抗告してたとして、面会拒む理由になるんですかね？ http://hirono2014sk.blogspot.com/2020/08/ksawmen_26.html

277	 - 2020年08月28日14時04分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「私は黒人ですって、日本人じゃないの？」とか言ってた皆さんのおかげで、BBCに「大坂選手は日本で人種差別の標的にされている」と報道 http://hirono2014sk.blogspot.com/2020/08/ksawmenbbc.html

278	 - 2020年09月01日12時10分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼ユーミンが安倍支持を表明してバッシング受けてる件、芸能人が政治的思想を表明したらそりゃ賛否両論出てはくるだろう。脅迫に至るような言 http://hirono2014sk.blogspot.com/2020/09/ksawmen.html

279	 - 2020年09月03日09時10分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「ナンパしてセックスに誘ったらとくに拒否しなかったのでOKと思った」みたいな主張が、「どんなバカ男でもきょうびそれを合意とは思いま http://hirono2014sk.blogspot.com/2020/09/ksawmenok.html

280	 - 2020年09月04日12時25分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼仙台弁護士会にさよならバイバイ 俺はこいつと　選挙出る 「アラチュウ！」 http://hirono2014sk.blogspot.com/2020/09/ksawmen_4.html

281	 - 2020年09月06日20時59分の登録： ＼なべきょう＠過眠症　@wata_nabekyo_ko＼返信先:  @k_sawmen さん,  @nyamu624 さん 集めた票で　勝ちまくり 仲間を増やして　つぎの http://hirono2014sk.blogspot.com/2020/09/watanabekyoko-ksawmen-nyamu624.html

282	 - 2020年09月13日13時24分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼ファンを大事にする裁判官「傍聴席～～！見えてるよーー！せり上がってるかーい！？」 http://hirono2014sk.blogspot.com/2020/09/ksawmen_13.html

283	 - 2020年09月13日23時21分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼次の選挙は及川先生がでるなら及川先生に入れよう。他にどんなに良さそうな候補がいても、及川先生に入れよう。 http://hirono2014sk.blogspot.com/2020/09/ksawmen_6.html

284	 - 2020年09月16日19時55分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼司法試験問題を漏洩した元教授は「娘のような気持ち」と言うが、あきらかにムスコを突っ込んでいるんじゃ http://hirono2014sk.blogspot.com/2020/09/ksawmen_16.html

285	 - 2020年09月16日19時55分の登録： ＼鉄ヲタ検察官ですが何か?　@judgeman246＼返信先:  @k_sawmen さん 娘に息子が惚れたから、つい接近(意味深)したのでは、、、 http://hirono2014sk.blogspot.com/2020/09/judgeman246-ksawmen.html

286	 - 2020年09月17日19時20分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼その状況でそんなこと言われたら「はぁ～～～～（クソデカため息）、あなたは弁護士の仕事についてご存じないみたいなので教えてあげますが http://hirono2014sk.blogspot.com/2020/09/ksawmen_17.html

287	 - 2020年09月21日00時48分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼#freeporygon #冤罪 #ポケモン界の袴田事件 #無罪判決引用ツイート http://kk2020-09.blogspot.com/2020/09/ksawmenfreeporygon.html

288	 - 2020年09月21日00時49分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼他の期はみんな一年間先輩にたらふく奢ってもらってるのに、なんで自分たちだけ……と思うのはわからんでもないし、かわいそうだと思う。た http://kk2020-09.blogspot.com/2020/09/ksawmen.html

289	 - 2020年09月21日00時51分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼冤罪が晴らされた！！！！！！！我々弁護団も感涙です！！！！！！！！ http://kk2020-09.blogspot.com/2020/09/ksawmen_21.html

290	 - 2020年09月21日11時47分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼懲戒されるようなことやってる自覚がなかったら、同じ名前の弁護士法人を東京三会ぜんぶに作ろうとはあんまり思わない気はしますよね http://kk2020-09.blogspot.com/2020/09/ksawmen_56.html

291	 - 2020年09月22日09時19分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼文系の、というか、自然科学？に属さない議論は結局最後には価値観に行き着きますもんね。 http://kk2020-09.blogspot.com/2020/09/ksawmen_22.html

292	 - 2020年09月24日20時32分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼米田先生からの「この決議が公表されたとき、被害者遺族はどう感じると思うか？」との質問に、理事者は「回答は差し控える」との回答。 http://kk2020-09.blogspot.com/2020/09/ksawmen_24.html

293	 - 2020年09月24日20時33分の登録： ＼Goshi弁太郎　@mackckckck＼返信先: @k_sawmenさん議論すらせずに数の力で押し進める。悲しすぎるぜ。 http://kk2020-09.blogspot.com/2020/09/goshimackckckck-ksawmen.html

294	 - 2020年09月24日20時33分の登録： ＼すけ　@EdF26D4CYaQctX1＼返信先: @k_sawmenさんやはり熟れたトマト祭りを開催すべきなのかもしれませんね。。。 http://kk2020-09.blogspot.com/2020/09/edf26d4cyaqctx1-ksawmen.html

295	 - 2020年09月25日21時26分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼返信先: @popohitoさんそれはそうなんですよね。。。ただ、現状では書面投票やWeb投票への反対がものすごく強くて、、、 http://kk2020-09.blogspot.com/2020/09/ksawmen-popohitoweb.html

296	 - 2020年10月03日20時58分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼うーむ、依頼者自死はともかく、相手方自死は別になんとも思わんな…… http://kk2020-09.blogspot.com/2020/10/ksawmen.html

297	 - 2020年10月03日21時00分の登録： ＼ぺっぺ丸　@piyorinchi＼返信先: @k_sawmenさん心が痛むというより、驚くのと、なにかやりすぎたのか？って最初の時は思いました。 http://kk2020-09.blogspot.com/2020/10/piyorinchi-ksawmen.html

298	 - 2020年10月03日21時01分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼返信先: @piyorinchiさんなんか本当に事案によるんですが、事案によっては事件解決の喜びしかなくて…… http://kk2020-09.blogspot.com/2020/10/ksawmen-piyorinchi.html

299	 - 2020年10月04日14時43分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼返信先: @popohitoさん死刑になるような重大犯罪の被告人が金持ちのことあんまないでしょうしね…… http://kk2020-09.blogspot.com/2020/10/ksawmen-popohito.html

300	 - 2020年10月05日07時16分の登録： ＃泥濘大魔王サイケ　@k_sawmen＃のツイート／2020-10-02_0858〜2020-10-05_0210／法務検察・石川県警察宛参考資料／記録作成措置実行日時：2020年10月05日07時16分 http://kk2020-09.blogspot.com/2020/10/ksawmen2020-10-0208582020-10.html

301	 - 2020年10月05日20時04分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼・相談だけ受けたうえで・「類型的に儲からないから自分はやらない」と・相談者本人に向かって言う……そんな弁護士いるかな。いないとまで http://kk2020-09.blogspot.com/2020/10/ksawmen_5.html

302	 - 2020年10月05日20時12分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼これは憲法に明文で書かないといけないですね。・この憲法は破棄できない・この憲法は破壊できない・この憲法は抹消できない・この憲法は消 http://kk2020-09.blogspot.com/2020/10/ksawmen_89.html

303	 - 2020年10月14日10時33分の登録： ＼泥濘大魔王サイケ　@k_sawmen＼「行政が違法なことをやっても、飯の話でもしてやれば庶民は騙くらかせる」って意味だぞこれ。 http://kk2020-09.blogspot.com/2020/10/ksawmen_14.html

304	 - 2020年10月14日10時33分の登録： ＼深澤諭史　@fukazawas　RT：　@k_sawmen＼「行政が違法なことをやっても、飯の話でもしてやれば庶民は騙くらかせる」って意味だぞこれ。 http://kk2020-09.blogspot.com/2020/10/fukazawasrtksawmen.html






* 
