#+TITLE: 告発状
#+AUTHOR: 廣野秀樹
#+STARTUP: indent
#+STARTUP: hidestars
#+STARTUP: content
#+OPTIONS:  H:5  num:t  toc:t  \n:nil  @:t  ::t  |:t  ^:t  *:nil  TeX:t LaTeX:t
#+TODO: [TODO](t) [EDIT](e) | [DONE](d)

告発状

〒920-0912金沢市大手町6番15号

金沢地方検察庁御中

    被告発人 金沢弁護士会所属 木梨松嗣弁護士

    被告発人 金沢弁護士会所属 岡田進弁護士

    被告発人 金沢弁護士会所属 長谷川紘之弁護士

    被告発人 金沢弁護士会所属 若杉幸平弁護士

    被告発人 元名古屋高裁金沢支部裁判長 小島裕史

    被告発人 元金沢地方裁判所裁判官 古川龍一

    被告発人 松平日出男

    被告発人 池田宏美

    被告発人 梅野博之

    被告発人 安田繁克

    被告発人 安田敏

    被告発人 東渡好信

    被告発人 多田敏明

    被告発人 浜口卓也

    被告発人 大網健二

被告発人らの所為は､市場急配ｾﾝﾀｰ（所在地: 〒920-0025 石川県金沢市駅西本町5丁目10−20）における殺人未遂の共謀共同正犯として法的評価すべきもの,また,弁護士､裁判官らの立場と職権で隠ぺいした幇助犯であると思料するので､犯情甚だ悪質につき､無期懲役刑として処罰することを求め､ここに告発に及びます｡

    告発人

    〒927-0431 石川県鳳珠郡能登町宇出津山分10-3

    廣野秀樹

令和2年○月○日

記

* 告発に至る経緯


** はじめに

*** 告発状本文の作成開始

*** 準備の完了と今後の予定

　8月4日となりましたが，いろいろと準備が完了し，いよいよ本件告訴状の本文作成に取りかかります。今月中を目途と考えておりますが，ぶっつけ本番というのが実際のところとなるので，成り行き次第，適宜変更をすることになると思います。

　準備というのは告発状の書面作成を行うパソコン環境の整備と，使用するアプリの選択でした。これがことのほか時間が掛かったのですが，最終的に選択したのはWindows10でのワープロソフト一太郎2019になります。

　告発状の本文と参考資料を分けるのも基本方針で，この参考資料の作成においては，Linuxのパソコン環境で主にテキストエディタEmacsを使って作業を行います。参考資料は本文の膨大化を避けるのが主目的になります。

*** 予定する本件告発状の作成範囲と証拠資料

*** 現在の記憶のみを基本とする記述

　参考資料には，Twitterのツイートや記事の引用が多いのですが，本件告発状は事件の道筋とアウトラインを示すことを優先事項とするので，やや日時の特定にも不正確なところが出てくるかもしれないですが，現在の記憶での記述をベースにします。

　過去の記事やTwilogから調べるという方法もあり，これまでよくやってきたことですが，当面をそれを控えることで，要点を絞った簡略化を行いたいと考えます。

*** 基礎とする証拠資料（名古屋高等裁判所金沢支部平成5年9月7日付判決）

- アルバム アーカイブ -
平成5年9月7日付控訴審判決（名古屋高裁金沢支部・小島裕史裁判長）（写真 5
枚）
https://get.google.com/albumarchive/114099790846205945578/album/AF1QipNKvU2fMq7VGmIcdquGo7cGzk5Jq4JOOBjj4AtI?feat=embedwebsite

　今のところこの「2011/11/17 •
一般公開」とある判決書の写真をメインの証拠資料にしたいと考えております。一般公開とありますが，これは私が設定を勘違いしていて，3週間ぐらいかまえに一般公開に設定し直したものかもしれません。

　他にもインターネット上には公開済みの判決書の写真があると思うのですが，前に軽く調べたときに見つかったのはこれだけだったと思います。Windows10のパソコン環境ではやりづらいことなのですが，後で調べ直し，参考資料としてご紹介したいと思います。

*** その他の証拠資料

　現在手元には，被告発人長谷川紘之弁護士が代理人となった損害賠償裁判の被告発人古川龍一裁判官の判決書があります。これもインターネット上に公開済みのものがあると思うので，そちらを資料として理由をご説明する予定です。

　今回，除外を決定したわけではないですが，市場急配センターの関係者の平成4年金沢西警察署作成の供述調書については，取り扱いの優先順位を下げて参照したいと考えています。

　私自身，何年も目を通していないもので，読めば書きたくなることもいっぱい出てきて想定している全体のバランスが崩れるという危惧があります。

　同様のものに平成5年11月28日付の手書きの書面があります。

　今，スマホの通話履歴で確認したところ6月4日となっているのですが，金沢地方検察庁の男性検察事務官から電話があり，今のところ最後となっている金沢西警察署刑事課強行主任からもあった日になります。

　ちょうどその頃，平成5年11月28日付の手書きの書面の一部を読んでいました。金沢西警察署刑事課強行主任の最後の電話があってからは，考えていることも変わり，読まなくなっていたと思います。

　微に入り細を穿つことになるのですが，全体像やアウトラインを優先させたためです。読むのも時間が掛かりますし，それにこだわっていると前に進める距離が短くなってしまいます。一方で，これは精緻な事実の記録という価値はあります。

*** 平成5年11月28日付の手書きの書面について

　これだけは御庁つまり金沢地方検察庁に提出されていない書面になるかもしれません。福井刑務所の受刑中，平成6年の11月になりますが，母親経由で被告発人被告発人木梨松嗣（金沢弁護士会）から郵送された一件記録の一部になります。

　たしか25日間の，懲罰が明けたのは平成5年の10月の中頃になると思います。書面に11月28日付けとなっているので，その間に作成し上告審での私選弁護人を依頼するつもりでいた被告発人被告発人木梨松嗣（金沢弁護士会）に郵送したものになります。

　被告発人木梨松嗣（金沢弁護士会）には，通常の便せんで手紙を送ることも多く，たぶん超過枚数の許可ももらっていたと思うのですが，拘置所の決まりでは免業日以外に一日2通，1通あたり便せん7枚となっていました。

　上告審で判決が確定する間際だったとも思うのですが，被告発人大網健二に48枚ぐらいの手紙を超過枚数の許可で発信した憶えがあります。

　たぶんそれを含めてですが，福井刑務所の出所後，早い時期に被告発人大網健二から特に説明もなく返され，それを金沢地方裁判所の再審請求の資料として提出したような憶えがあります。

　平成5年11月28日付の手書きの書面は，裁判所に提出した上申書と同じく，B4の罫紙で作成したもので大型封筒で郵送しています。認書の作成と大型封筒使用の許可を得る願箋を出しました。許可が出ないと作成も郵送もできません。

　被告発人木梨松嗣（金沢弁護士会）が私選弁護人となった控訴審の判決は，その平成5年の9月7日で，だいたい一月ぐらい，2，3週間前とも思えるのですが，郵送された書面で判決期日の指定がありました。

　私は，被告発人小島裕史裁判長の名古屋高等裁判所金沢支部に提出する上申書を作成中で，作成しながらできた書面を小分けに郵送をしていたと思います。

　時系列の事実経過で書き進めまだ平成4年の1月中だったと思うのですが，そこでいきなり判決期日の通知が書面で送られてきたのです。被告発人木梨松嗣（金沢弁護士会）からの説明はなく，何度手紙や電報を送っても連絡はありませんでした。

　そして判決のあった平成5年9月7日に問題を起こし，たぶん25日間，の懲罰の間は，筆記用具も私本も取り上げられ，書くことも読むこともできない状態でした。読むことができたのは，備え付けの「所内生活の手引き」ぐらいのものです。

　10月の中頃になると思うのですが，懲罰が明けたことで未決囚として普通に生活ができるようになり，控訴審の上申書でまだ書いていなかった時期以降を重点的に記述した書面になります。

*** 殺人未遂事件を隠蔽，社会的に抹殺した被告発人らの犯罪性

　表面的，外形的な事実と金沢西警察署の未確認，不十分な捜査もしくは市場急配センターの関係者（被告発人数名を含む）に担がれ利用された不手際を刑事裁判の判決として確定させたのも弁護士，裁判官としての地位の悪用になります。

　比較的関与が薄く見える被告発人岡田進弁護士ですが，早い段階で刑事裁判の流れを決定づけており，あとに控訴審の私選弁護人となった被告発人木梨松嗣（金沢弁護士会）との通謀，結託も視野に被疑事実の全貌の解明が不可欠です。

*** 被害者安藤文さんに対する殺人未遂と評価するべき事実

　真意はともかく，金沢西警察署刑事課強行主任によってブログのタイトルに殺人未遂事件と市場急配センターを結びつけることは厳禁とされております。

　御庁つまり金沢地方検察庁に殺人未遂の告発事件として受理されてもなお，ブログのタイトルに殺人未遂事件と市場急配センターを結びつけることが許されないことなのか否かは，受理された段階で確認することも考えております。

　「被害者安藤文さんに対する殺人未遂と評価するべき事実」はもちろん市場急配センターにおける事実関係が中心で，平成4年4月1日の結果発生を基準点とした共謀共同正犯になります。

　ここには公訴時効の問題があるのですが，殺人未遂の幇助犯として告発する弁護士・裁判官の被告発人らは，不正に不当な判決を確定させたもので，非常上告の手続きにより，破棄されるべき法律行為になります。ここに公訴時効の起算点はありません。

　上告審は書面審理でいわゆる三下り半の決定でした。事実を検討し直した形跡もありません。事実審の終局が名古屋高等裁判所金沢支部であって，その判決を出したのが被告発人小島裕史裁判長になります。

　この確定判決の事実認定と，被告発人の弁護士・裁判官らが完全に無視し切り捨てた事実，その内容がこれから記述する「被害者安藤文さんに対する殺人未遂と評価するべき事実」となります。

** 関係機関

*** 金沢地方検察庁

*** 金沢地方裁判所

*** [EDIT] 警察庁
*** 社会問題としての弁護士，本件告発事件の本質と関わり
**** うの字（うのじ，とも。神奈川県横浜市で神奈川県弁護士会所属の弁護士として活動している可能性のあるTwitterアカウント）
***** 深澤諭史弁護士のTLで見た「日本の警察は、今年3月から防犯カメラやSNSの画像を顔認証システムで照合していた 」に「画像提供する民間側が損害賠償のリスク背負ってないからじゃねーかな」というツイート



*** 金沢中警察署

*** 金沢西警察署

*** 金沢弁護士会

```

```
* 告発の事実
==========

** 殺人未遂事件を隠蔽した弁護士らの関与
----

*** 被告発人岡田進弁護士

*** 被告発人被告発人木梨松嗣

*** 被告発人小島裕史裁判長

*** 被告発人長谷川紘之弁護士

*** 被告発人古川龍一裁判官

*** 被告発人若杉幸平弁護士

市場急配センター

** 殺人未遂事件の

*** 被告発人松平日出男

*** 被告発人池田宏美

**** 被害者安藤文さんの家に電話を掛けるなと言った被告発人池田宏美

やはり，これが津幡町能瀬からの電話だったと思います。いや，ちがうかもしれません。津幡町能瀬からの電話では被害者安藤文さん本人が電話に出ており，被告訴人池田宏美の話は，今考えると側に本人がいたとは考えにくいものです。

「広野さん，あの子の家，電話掛けとるやる。絶対やめときなさい。」と被告発人池田宏美は言いました。「あの子，彼氏おるんやし」とも言ったように思います。

「どうしても電話掛けたいんやったら，わたしんとこ掛けてきなさい。」とも言ったように思いますし，「さみしいんやったら」とも言っていたように思います。

なんとなく思い出すのは，最初に被告発人梅野博之が電話に出で，被害者安藤文さんを出そうとしなかったので，私がいくらか強く彼女を電話に出すように言ったところ，被告発人池田宏美が代わって電話口に出たような状況です。

**** 被害者安藤文さんのことで，「可哀想な子や，可哀想な子やと思っときなさい」と言った被告発人池田宏美

　七尾市で荷物を積んで出発した後，小杉インターから北陸自動車道に乗り，すぐ先にある呉羽パーキングエリアからの電話です。時刻はだいたい17時30分頃と思いますが，外はすっかりと暗くなって夜と同じでした。

　余りはっきりとは思い出せないですが，被告発人池田宏美の場合，17時30分頃はだいたい会社にいたように思います。18時頃までいることもさほど珍しくはなかったと思いますが，19時以降というのはほとんど見たことがなかったと思います。

　これは昼に掛けた津幡町能瀬からの電話の続きのような内容です。これも記憶がはっきりしませんが，現在の中能登町鹿島の辺りからも会社に電話を掛け，被告発人池田宏美と話をしていたかもしれません。

　「広野さん，あの子にかまわんときなさい。今あの子に会社やめられたらほんと困るげんてぇ。」というようなことを言われたのですが，津幡町能瀬からの電話だとすると，被害者安藤文さんが電話に出ているので，側で被告発人池田宏美の悲痛な声を聞いていたことになります。

　そういう被告発人池田宏美の声を聞いていたような被害者安藤文さんの態度ではなかったので，やはり別に機会の電話になると思います。本当は全く別の日とも考えたのですが，呉羽パーキングエリアからの電話での，被告発人池田宏美の発言と整合があるのはこの日のことです。

　先月，8月の初めになると思いますが，車で金沢への買い物に連れて行ってもらい，富山県小矢部市のアウトレットに買い物に行ったのですが，そこから雨晴海岸で写真撮影などしたあと，氷見市を通って七尾市に向かいました。

　氷見市からは氷見警察署の前を通った後，いくらか引き返すかたちでインターの乗り口を探し，のと里山街道につながる自動車専用道路に乗りました。インターは途中で降りて，七尾城趾の見晴台まで行ったのですが，高岡市から七尾市までずいぶんと距離があると感じました。

　途中までが高岡市から七尾市まで通じる国道160号線ですが，昼に通ったのは平成4年3月以来のことになります。一度，平成10年辺りに，宇出津の実家に何かを取りに行く用事の帰り，夜中に国道160号線で高岡市から金沢市に戻ったことがありました。

　国道160号線はのんびり走れる道路で，七尾市内から北陸自動車道の小杉インターまでも割合早かったという印象がありました。能登木材と林ベニアのいずれかの荷物でしたが，市場急配センターでは11月辺りから一番多い仕事のパターンだったと思います。

　呉羽パーキングエリアから電話を掛けると，被告発人池田宏美は機嫌の良い声で，被害者安藤文さんが納得をして帰ったという趣旨のことを言っていました。納得と言うよりは安心あるいは安堵がそれに近かったと思います。

　被告発人池田宏美は口も達者でしたが，抑揚の表現力もあり，まるで劇団の役者のようでした。今が4回目の結婚とかで，初めの頃は四国の徳島などに住んでいたと話すことがありました。まだ私が金沢市場輸送にいた頃に聞いた話だったかもしれません。

　基本は金沢弁でしたが，ときおり他の地方の言葉が混じっていると感じることがありました。長距離トラック運転手の仕事をしていたので，いろいろな地方の言葉は聞いていましたが，地域を特定できるように感じることはなく，個人的な話し言葉の癖なのかとも考えることはありました。

　「あの子，わかったって帰った。」というような言い方だったと思います。優しく安心感を与える話しぶりでした。しかし，そのあとに続けた被告発人池田宏美の話が，どうなっているのかと混乱を招かせるものでした。

　「可哀想な子や，可哀想な子やと思っときなさい広野さん。あの子，会社でしおらしいしとるやろ，でも友達との電話の話とか聞いとったら，がんこなこといっとるわ。」ってな話でした。

「しおらしい」という言葉は，その場で余りはっきりと聞き取れなかったのですが，他に，「なんもわかっとらんげんて，あの子」ということも言っていたと思います。被告発人池田宏美の声と話しぶりは，これも熟練の役者のような聞き取りやすさがありました。

　金沢市場輸送にいる頃から，被告発人池田宏美のことは，話し上手だけど余り信用のおけない要注意の人物と思っていました。女の直感という言葉を聞くことがあった時代ですが，私の妻が，「あの人，怖い感じする。」と言ったのも印象的でした。

　被告発人池田宏美については，要領が良く利発という印象もありましたが，時に私の方で，警戒しすぎて偏見があるのかもしれないと考えさせられることもありました。言うときはズバッと言うタイプだったので，迫力や威圧感のあっただろうと思います。

　そういえば書いているうちに思い出すことがありました。

*** 被告発人梅野博之

**** 平成3年12月13日の金曜日の夕方

　この日の夕方，私は初めて被害者安藤文さんに声を掛けようと思い，裏駐車場に駐めた自分の軽四の中で彼女を待ちました。裏駐車場でも入って右手の一番手前の方になります。彼女の車の横に駐めていたと思います。

　長くて18時頃まで待ったと思いますが，彼女が出てこないので諦めて帰りました。その間，2回，あるいは3回だったと思いますが，私の車の横を被告発人梅野博之が歩いて通りました。まるで私を警戒した見回りのようでもあり，被害者安藤文さんに気を遣い様子を見に来た感じでした。

　被害者安藤文さんの裏駐車場の行動が始まって初めての対応でした。彼女の望みや要求に応えたつもりだったのですが，このときも被告発人池田宏美や被告発人梅野博之が彼女によからぬことを吹き込み，不安にさせた可能性が大です。

　しかし，それでも当時は，その日が13日の金曜日だったということで，彼女がその日に会うことを忌避したとも考えました。当時，かなり若者に影響を与えていたと思われるホラー映画のことです。私自身は気にしていなかったですが，彼女の年頃だと気にすることもあるのかと考えました。

**** 河北郡津幡町能瀬からの電話に出た被告発人梅野博之

　近くに能瀬という地名の標識か看板がありました。ずいぶん古い繊維工場の跡地のような印象が残っているのですが，そこにある小型の電話機をアクリル板で囲っただけのような電話ボックスから会社に電話を掛けたと記憶にあります。

　これも余りよく思い出せないのですが，電話に被告発人梅野博之が出て，優しく被害者安藤文さんをかばうような素振りを見せていました。他に被告発人池田宏美も出たように思うのですが，何度かかけ直した電話に被害者安藤文さん本人が出ました。

　言葉で表現するのは難しいのですが，このときの被告発人梅野博之の態度は，なんともいえない微妙なものがあり，強く印象に残っています。

　倉庫移動という会社の指示で行った北陸ハイミールで会社から電話が入り，急遽，七尾市に向かったときでした。ああいうことは後にも先にも他になかったですが，計算されたものがあったと思います。被害者安藤文さんとの関係も微妙な時期でした。

　そのあとのことは，現在の中能登町鹿島の広くなった道路で，七尾市に向かって左側に中西運輸商の大型トラックが駐められているのを見たことが，けっこう印象に残っています。

　七尾市での荷積みの作業などは記憶にないのですが，次に記憶にあるのが，別に記載する被告発人池田宏美の電話対応になります。

　確認には至らないのですが，このときの運行の行き先は，山梨県だったと思います。これもけっこう印象に残る運行でした。2カ所降ろしだったと思います。

　国道20号線から静岡市に向かう国道52号線に入って，しばらく走り，右手に入った集落と記憶にあるのですが，Googleマップで見ると，その辺りは現在，南アルプス市となっていて，見覚えのある地名は見当たりませんでした。

　山梨県内は，国道20号線と中央自動車道の通過ではよく通っていましたが，荷物の積み下ろしをしたのは初めてだったのでそれも印象的に憶えているのですが，集落の雰囲気も独特なものを感じたと記憶にあります。

　これははっきりしている記憶ですが，山梨で七尾市からの荷物を荷下ろしした後は，東京に向かいました。どの時点で決まったのか記憶にないですが，東京に向かう時点で，翌日の池袋の三越デパートからの展示会の引き上げの仕事が決まり，指示を受けていたはずです。

*** 被告発人安田繁克

**** 松浦さんの愛人の息子として入社した被告発人安田繁克（平成元年9月？）

**** 被告発人安田繁克と被告発人大網健二との接点（平成2年春か秋）

***** 中古のBMW

　余り具体的な話として聞いていなかったと思うのですが，後に被告発人大網健二は，被告発人安田繁克と思われる男が，中古車販売の話し合いをする喫茶店に彼女を同伴させていたと私に話しました。その車というのが中古のBMWになります。

　私は1,2回，金沢市場輸送の駐車場でそれらしいBMWをみています。洗車機の横辺りと思いますが，駐車場でも奥の方に他の車と横に並んで駐車されていました。スポーツタイプに見えたBMWですが，ずいぶん古いもので，遠目にもかなりのポンコツに見えました。

　私が小学校6年生の頃になると思いますが，スーパーカーブームというのがありました。その1,2年後になるのかもしれないですが，週刊少年ジャンプに「サーキットの狼」という漫画の連載がありました。ちょうどその頃に玩具屋のプラモデルでみたBMWの型になります。

- 907：2020-09-10_13:35:30 ＊
《参考資料》昭和50年代初めのスーパーカーブームと週刊少年ジャンプの連載「サーキットの狼」，その当時のBMW
https://hirono-hideki.hatenadiary.jp/entry/2020/09/10/133528

　被告発人安田繁克の名前を知ったのは，平成3年6月22日頃になるかと思います。被告発人安田敏と同じ名前と知ったのも，市場急配センターに掛けた電話で，電話口に出た被害者安藤文さんが「どちらの安田ですか？」と聞き返したからです。

　なお，この電話の少し前に私は被告発人安田繁克と会って話をしており，そのとき被告発人安田繁克は市場急配センターをやめており，フリーで仕事を請け負っているなどと話していました。ただ，その話をした場所が，今思い出せなくなっています。

　中古のBMWの売買の話は，これも被告発人大網健二から聞いていて，直接名前など聞いていなかったはずですが，私は被告発人安田繁克のことに間違いがないと思いながら話を聞いていました。

　あとで考えると芝居じみた不自然な点も感じられるのですが，似たような話で不自然さが際立ったのが，別の項目として取り上げる，笹田君のことです。これには被告発人安田繁克と親しくしていた可能性もあるS藤も絡んできます。

***** ほぼ同じ頃に入社した西口君と名古屋の元暴力団員S藤

/告発の事実/市場急配センター/被告発人安田繁克/松浦さんの愛人の息子として入社した被告発人安田繁克（平成元年9月？）/ほぼ同じ頃に入社した西口君と名古屋の元暴力団員S藤

　西口君は，金沢市場輸送の古参運転手，山田さんの娘婿あるいは婚約者として，被告発人安田繁克は堂野さんの愛人の息子として，ほぼ同時の入社となり，盛り上がった話題となっていました。平成元年の9月頃と思うのですが，あるいは昭和63年かもしれません。

　秋口というのか9月頃というのはなんとなく憶えています。名古屋の元暴力団員S藤も同じ頃と思うのですが，同じ頃だとすると昭和63年になると思います。これは被告発人松平日出男の登場とも近い時期でした。

　同じ頃に，被告発人松平日出男とは中古車購入の話をし，被告発人松平日出男が金沢市場輸送に新型車のカリーナを私に試乗させるために持ってきたことがあり，同じ頃，S藤とは，彼が乗っていた400CCクラスのオートバイの話をしたと記憶にあります。

　私はかなり長い間，被告発人安田繁克の母親の愛人を堂野さんと思い込んでいました。なので松浦さんが母親の愛人と知ったときは，かなり驚き，自分の勘違いを恥辱のように思っていたのですが，最近では勘違いではなく，そのように吹き込まれていた可能性を考えるようになっています。

　堂野さんの場合も金沢市場輸送や市場急配センターの社員ではなかった可能性があるのですが，イワシのシーズンも終わりに近づいた頃に，イワシ運搬のダンプの持ち込み運転手として仕事をするようになりました。

　これは私の2度目のイワシの運搬だったので，2月頃というのは平成2年になります。これだと被告発人安田繁克の入社も平成2年になります。堂野さんが先に仕事をするようになっていたことが前提になるからです。

　堂野さんの愛人の息子と聞いた被告発人安田繁克ですが，これも主に金沢市場輸送の輪島の運転手に聞いたと印象にあります。一人を除き，大型保冷車の運転手で主に鮮魚を運んでいました。仕事上の接点は考えられないのですが，夕方に麻雀を堂野さんがしていたのが，知り合うきっかけとは考えられます。

　私の知る範囲で，堂野さんが鮮魚の仕事をしたことはなかったのですが，配車係の本恒夫社長が無理な配車をして，たびたび自分で運行に出ていると聞いており，堂野さんにも頼んだことがあったのかもしれません。

　頼むとすれば東北便ですが，鮮魚だけではなく練り製品など扱う種類が多く，慣れないと出来る仕事ではなかったと思います。可能性として輪島の運転手に堂野さんの協力を頼んだとは考えられ，それで親しくなったとは考えられます。

　実際に聞いた話ではないですが，東北便の荷物だけを堂野さんに運んでもらい，金沢中央卸売市場に待機した輪島の運転手が，率先して荷降ろしの手伝いをし，荷降ろしの完了後には，堂野さんのおごりで酒を飲んだことも想定は出来るところです。

　私としては堂野さんとは一緒に食事をしたこともなかったと思いますが，松浦さんには食事に連れて行ってもらい，おごってもらうこともありました。一つ強く印象に残っているのが，金石のバスターミナルで，廃車になったバスが焼き鳥屋になっていたと思います。夜遅くに行きました。

　そのときに見た，松浦さんの指輪も印象に残るもので，銀色で大きな平面上の指輪でした。それと同じような指輪を平成3年3月に被害者安藤文さんがつけているのを見たのですが，3月5日は細い指輪で，清水市行きのミールを積んだ日が，その指輪だったと思います。

　記録には記憶も清明な状態で繰り返し記述していると思いますが，イワシの運搬は昭和63年12月から始まった1回目と，平成元年12月から始まった2回目でメンバーががらりと変わっていました。同じだったのは松浦さんと私だけだったと思います。

　繰り返しますが，堂野さんの愛人が入社する，あるいは入社したという話を聞いた頃，一度，被告発人安田繁克の姿を近くで見ているはずなのですが，その後，会社で姿をみることは少なかったと思います。

　特に，一番，運転手の集まる夕方の時間帯に被告発人安田繁克の姿を見たという記憶がない気がします。笹田君と峰田君は，割とちょくちょく，仕事が終わった後も金沢市場輸送の運転手の休憩室で，ぶらぶらとしていました。テレビを見ることもあったかもしれません。

　被告発人安田繁克のことではっきり印象にあり，直接，言葉を交わしたのが2月頃のことでした。たぶん平成3年になると思うのですが，これもまだ記憶が清明だったときに記述したものがあると思います。

　午前中，金沢市場輸送の駐車場には雪が積もっていて，市内配達の2トン車だったと思いますが，被告発人安田繁克がスリップをさせて動けなくしていたので，運転を代わり，雪の轍から出したということがありました。

　ワンデフの大型車は雪道に弱く，新潟や東北の豪雪地帯もよく走るので，こつのようなものはつかめていました。上り坂の雪道でいったん停車すると，そのまま発進できないことも普通にあったので，乗用車の運転とは比較にならず難しいものがありました。

　西口君は，当初より新車の4トン保冷車の持ち込み運転手となっていましたが，やはり山田さんの存在が大きいという話でした。山田さんは途中で名前が山田さんに変わったのですが，古参といっても昭和59年の10月にはいなかった運転手で，昭和61年の8月にはいたはずです。

　西口君の4トン保冷車は新車で，それもフルモデルチェンジをして間もない頃の日野のトラックだったと思います。運転手の間で話題になることはなかったですが，日野の4トン車はモデルチェンジ前の昭和59年当時の車種も同じで，英語でレンジャーという名前があったと思います。

　平成3年には1月と10月に2回，日野の大型車の新車に乗務をしていますが，その当時のことは記憶にないものの，昭和59年当時の金沢市場輸送の新車の日野の大型車が，ドルフィンという名前であったことはよく憶えています。平成3年10月もフルモデルチェンジにはなっていませんでした。

- 908：2020-09-10_14:59:57 ＊
《参考資料》日野レンジャー　4代目（1989年〜2001年）
https://hirono-hideki.hatenadiary.jp/entry/2020/09/10/145955

　「1989年7月登場」とありました。平成元年7月です。西口君とも会う機会は少なかったと思うのですが，その4トン保冷車で仕事をする姿は見かけていました。早い段階で話もしていると思うのですが，同じ能都町の瑞穂の出身で，金沢市の尾山台高校を卒業したと聞きました。

　この西口君も平成3年の秋から私の前に姿をあらわすようになり，被告発人多田敏明とともに工作活動っぽいことをやった形跡があり，私に被害者安藤文さんに関する偽りの情報を吹き込んだ可能性もあります。

　S藤ですが，最初に姿を見た頃にバイクの話などして，それから長い間，姿を見かけずにいました。市内配達の仕事をしているとは聞いていましたが，仕事をする姿を見ることはなかったような気がします。そして久しぶりに姿を見たのが，平成元年12月のことでした。

　これが被告発人大網健二と笹田君の車の売買を巡るトラブルになります。

***** 長く勘違いしていた，入社のきっかけとなった被告発人安田繁克の母親の愛人

　すでに書いていることですが，私は長い間，被告発人安田繁克のことを堂野さんの愛人の息子だと思っていました。実際は，堂野さんを金沢市場輸送のイワシの運搬の仕事に紹介した松浦さんの愛人の息子だったのですが，この間違いにいつ気がついたのか現在思い出せなくなっています。

　繰り返し愛人と聞いていたのですが，松浦さんは金沢市場輸送で仕事を初めてすぐの頃，若い妻が家出をしたという話でした。それでも1度は，その妻という女性の姿を金沢港のイワシの仕事の現場で見かけています。髪が長く，顔ははっきりわからなかったのか，印象に残っていません。

　離婚をしたとは聞いていなかったので，新たに入籍も出来ず愛人となっていたのかもしれません。近年は愛人という言葉自体を見かけなくなっていますが，平成の前後にはテレサテンの「愛人」というヒット曲もあり，身近によく聞くような言葉ではありました。

　当時，松浦さんは45歳ぐらいと聞いていたように思いますが，妻は若く，20歳過ぎかあるいは10代と聞いていたかもしれません。子供が二人いてどちらも男の子ですが，上の子は昭和61年生まれの私の長男より1つほど年上と聞いていました。下の子は，まだ満足に話が出来ない年頃でした。

　私が市場急配センターで市内配達の仕事を始めたのは，平成3年の6月23日になります。私の記憶では5月だったのですが，金沢市場輸送の運行表に6月分の運行記録がありました。

　母親を通じて金沢刑務所の拘置所に差し入れられた一部だったのか，頼んでいなかったはずの，金沢市場輸送の運行表があり，疑問に思いました。あるいは，斐川雅文弁護士から郵送で差し入れがあった一部になります。

　感覚的に一月ほど先に被告発人安田敏は金沢市場輸送で市内配達の仕事を始めていましたが，すっかり打ち解けた様子でした。すぐに繰り返し聞かされたのが，大野君のことです。被告発人安田敏は私に，当時16歳という大野君のことを堂野さんの愛人の息子だと話していました。

　当時はそれほど深く考えなかったと思うのですが，被告発人安田敏は堂野さんのことをよく知る人物のような口ぶりでした。堂野さんは金沢市場輸送の社員運転手ではなかったはずで，会社に来ることも少なかったと思うのですが，考えられるのが金沢市場輸送での夕方以降の麻雀です。

　しかし，朝早く夕方早めの時間に仕事が終わる市場急配センターの市内配達の仕事をしていた被告発人安田敏が，夕方に金沢市場輸送の事務所に行くとは考えられず，被告発人安田敏が麻雀の話をすることもなかったと思います。

　私が見たのは一度だけだったと思いますが，群馬県の中国化薬に，堂野さんが金沢市場輸送の大型トラックで荷物を運んできていました。ウィング車だったと思うのですが，なぜか平ボディ車を見たような記憶になっています。荷物が爆弾か魚雷だけに，シートを掛ける平ボディ車とは考えにくいのですが。

　他にも金沢市場輸送の長距離の仕事をしているような感じでしたが，ミールやダンベを運ぶのも見たことがなかったと思います。持ち込みのダンプも，一般の土砂積みのダンプに比べかなり小型に見えました。

　古い型の三菱ふそうの大型車だったと思います。色がバイクの塗装のようなワインレッドで，色の具合で小さく見えるとは考えていましたが，普通の大型車のキャビンには見えなかったと思います。

　10トン車と6トン車の間に別の大きさの車種はなかったと思うのですが，そもそも何を運んでいたのか不思議なダンプでした。土砂積み禁止のダンプになっていたと思いますが，通常，土砂積み禁止のダンプは木材チップなど軽くてかさばるものを運ぶので，車体は大きくなる傾向がありました。

　大野君は大人しく無口でしたが，体の大きな少年でした。仕事中もヘッドフォンをつけて曲など聴いている様子でした。何度か市内配達で同乗させたことがあるのですが，話しかけると割合，普通に話していました。

　夏休みになると高校生の大野君の友人も，市内配達のアルバイトをするようになり，彼も同乗させることがありました。名前は今も憶えていますし，なんとなく姿や顔も記憶にあるのですが，細身で割と背が高く，大人しく素直な少年でした。

　被告発人安田敏がやたらと積極的に，私にこの堂野さんの愛人の息子という大野君の話をしていたのですが，堂野君の家は，金沢市内の涌波だと言い，安田敏が住む花里のすぐ近くになります。アルバイトの少年も家が近くと聞いていましたが，どの辺りに家があるのかは，聞かなかったように思います。

　この涌波には，ウェルマートというスーパーがあり，近年出来たスーパーで，私の知る範囲で他に，保古店と，玉鉾店があったと思います。保古店には，東力2丁目のアパートから買い物に行くこともありました。ただ，平成9年頃には全滅をしていたと思います。

　他に，七尾市に本部を置く，昭成会という暴力団の組事務所がありました。大通り沿いで周囲はほとんどが住宅地だったと思いますが，特に問題になっているとは聞いていませんでした。珠洲市のKという被告発人安田敏の友達が所属したのもこの事務所だったと思います。

　珠洲市のKに最初に会ったのは昭和58年の秋頃のことでしたが，昭和61年の12月に被告発人安田敏が私のアパートに訪ねてくるようになった頃は，暴力団員になったといい，被告発人安田敏はそのKから借りてきたというカマロという大型のアメリカ車に乗ってくることもありました。

　たぶん，その後も付き合いはあったと思うのですが，平成3年には珠洲市のKの話を，被告発人安田敏がすることはたぶんなかったと思います。珠洲市のKと被告発人安田敏の間には，他にもいくつか接点があったのですが，その辺りも記録には洗いざらい徹底した記述してあります。

　被告発人安田敏の花里のアパートについても，Googleマップで場所を確認しておこうと思いながらやっていませんでした。前に官舎があったので，たぶん今でも場所の特定はできそうに思います。

- 909：2020-09-10_16:38:39 ＊
《参考資料》被告発人安田敏の平成3年当時の花里のアパートと，金沢市涌波周辺
https://hirono-hideki.hatenadiary.jp/entry/2020/09/10/163837

　堂野さんの愛人のことですが，大野君の話を聞く前に，母親とは会っていました。大同生命だったと思いますが，生命保険の勧誘で，堂野さんが引き合わせたのが，その女性だったからです。時期は春か秋だったと思います。

　堂野さんが勧誘をする前に，生命保険外交員の女性から私の妻に接触があった様子でもありました。東力のアパートの駐車場に堂野さんが車を停め，車の中で待っていた様子が記憶にあります。女性が一人でアパートの中に入り，契約の手続きをしたように思います。

　妻から何度かその女性の名前は聞いていたのですが，余り話をしなかったと思います。生命保険の加入も不本意でした。たぶん同じ頃になると思うのですが，堂野さんに頼まれて，寺中町まで車で送ったことがありました。涌波とはかなり離れた場所です。これもマイマップに追加しておこうと思います。

- 910：2020-09-10_17:17:00 ＊
《参考資料》堂野さんを送った寺中町の大体の場所と，同じ寺中町の中西運輸商の事務所，それと近くの金沢西警察署
https://hirono-hideki.hatenadiary.jp/entry/2020/09/10/171658

　堂野さんの乗用車というのは見た記憶がなく，東力のアパートに来たときも，保険外交員の女性の車を運転しているような感じでした。堂野さんについては，どこに住んでいるのか，また，家族のことも話を聞くことはなかったように思います。妻子がいるような話も聞いていなかったと思います。

　堂野さんを金沢市場輸送に引き入れた松浦さんですが，元暴力団員で，いかにもそれらしい雰囲気で，昭和の時代の仁義なき戦いの映画の感じでした。一度，本当にその時代の映画に出てくるような，古いポンコツのベンツに乗って，乱暴な運転をする様子を目の当たりにしたことがありました。

　大野という女性の名前は聞いていたと思いますが，保険の契約をした当時，堂野さんの愛人とは聞いていなかったかもしれません。ただ，堂野さんの妻と考えることはなく，それは大野という違った名前を聞いていたからだと思います。

　堂野さんと最初に会ってから，生命保険の契約まで半年ぐらい間があったように思います。暑くもなく寒くもなく過ごしやすい季節だったと記憶にあるので，やはり平成2年の秋になりそうです。その後，大野という女性に会うことはなかったと思いますが，どこかで一度，顔を合わせたような気もします。

***** 被害者安藤文さんを市場急配センターに紹介したともされる，笹田君と峰田君

　この二人は，私の判断で実名としますが，事案解明の鍵を握るかもしれない人物であります。ほぼ同時期の入社でいつも一緒に行動をしていた二人です。入社の時期ははっきりしませんが，金沢市場輸送の事務所が西念町リの１にあったとき，事務所が一つだけの頃はまだいなかったと思います。

　高田さんが市内配達の責任者で，金沢市場輸送以外にも石川日通，小林運送などが市内配達をしていた頃のことです。高田さんが竹沢俊寿社長を激怒させるかたちで失踪し，それからまもなくだったと思いますが，同じテナントビルの並びにもう一部屋賃貸したらしく，市内配達の社員がそちらに移りました。

　被告発人梅野博之が代行の責任者をやっているという話も聞きましたが，余り姿を見かけることはなかったと思います。興味本位に部屋を覗くと，決まって女子事務員が一人いました。名前を出すつもりはないですが，ちょっと思い出せなくなりました。半年ほど前には憶えていたはずです。

　大西真さんのおごりで片町に飲みに行ったとき，被告発人池田宏美と一緒にいた女性です。２０代後半と聞いていましたが，ずいぶんと落ち着いていて，かなり年上に感じていました。

　金沢市場輸送の事務所が二口町に移ってからもしばらくはいたと思いますが，姿をみなくなったあと，社員運転手Tさんとの不倫関係で首にされたという話を聞きました。二口町に移ったのは昭和６３年の７月の初めと記憶しています。なぜか７月の初めということをしっかり憶えています。

　それから金沢市場輸送の長距離と市内配達が，また同じ事務所と運転手の休憩室となったわけです。これは平成２年の春，市場急配センターの新事務所が出来るまで続きました。

　笹田君と峰田君の姿を見るようになったのも，その二口町の事務所に移ってからだと思います。そういえば，少し思い出したのですが，大久保くんの場合は，逆に二口町に事務所が移ってから姿を見なくなったかもしれません。

　大久保という名前もはっきりとは憶えていないのですが，ありふれた名前ですし，一応そうしておきます。石川日通の運転手だった，こちらも名前が思い出せないですが，確か私の一つか２つ年下で家が小立野にあると聞いていましたが，その運転手の後輩として金沢市場輸送に入ったような話を聞きました。

　その大久保君が笹田君や峰田君と彼女の交換をしていたという話を被告発人多田敏明から吹き込まれたと思うのですが，被告発人多田敏明というのは，金沢市場輸送と市場急配センターが同じ事務所だった頃には姿を見ていなかった運転手なので，なぜ大久保君の名前をしっているのか不思議でした。

　そして同じ頃，被告発人多田敏明に，被害者安藤文さんを市場急配センターに紹介したのが笹田君か峰田君と聞かされたのです。どちらかはっきりしないのは，私の記憶がはっきりしないためです。たぶん峰田君と聞いていたと思うのですが，確信は持てません。

　笹田君と峰田君の年を19歳と聞いていた記憶があるのですが，それは平成4年の2年ほど前のことで，被害者安藤文さんと同じ年と聞いたように思います。被害者安藤文さんは8月生まれで，平成4年の誕生日を迎えるまでは21歳でした。昭和45年生まれです。

　とにかく笹田君と峰田君は会社にいるときいつも一緒にいました。何度か直接会話をしたことがあったのですが，二人とも家は金石と話していたように思います。金石は金沢港の近くでもありますが，犀川の河口に金石港があります。大野とも隣接していますが，北前船などの古い歴史があるところです。

　といっても金石は広く，金沢西警察署に近い辺りほど住宅地が多い感じでした。昭和56年当時は，暴走族が多いとも聞いた金石ですが，平成4年当時は，金石海岸がナンパのスポットともなっていて，金沢西警察署の警察官も「ちゃんかい」と読んでいました。方言を直すと「セックス街道」のようなものです。

　昭和58年当時，「ちゃんぺ街道」のような露骨な表現はなかったですが，ナンパのスポットは繁華街の片町から少し離れた香林坊から南町でした。夜にその辺りを若い女性が歩いていると，ナンパされるのを目的にしているとみなされ，声を掛けられていたものです。

　被告発人安田繁克は暴走族のリーダーだったとも聞いていましたが，2月1日の夜にグループ名を尋ねると，「狂走恋命」だと言っていました。昭和56年頃にも暴走族の落書きとして見かけていたものですが，具体的な暴走族のグループ名としては聞くことがありませんでした。

　被告発人多田敏明も暴走族に入っていると話していました。平成4年に入ってからではと思いますが，新聞に暴走族の死亡事故のニュースがあり，当日だったと思いますが，昨夜の死亡事故は自分も参加した集団暴走と話していました。金沢東インターの近くで福久が事故現場になっていたと思います。

　仲間が事故を起こしたのを置き去りしたという話もありました。トラックの仕事で夜に運転をすることも多かったですが，平成3,4年頃には，暴走族は余りみなかったと思います。長距離も同じでしたが，昭和57年の9月から12月に名古屋の港区にいるときは，逆走する大きな集団暴走を見ていました。

　なお，被告発人安田繁克も被害者安藤文さんと同じ21歳で，そのとき被告発人多田敏明は19歳でした。2つ年下になります。被告発人安田繁克は，被害者安藤文さんが泉中で，自分が高中だったので，話をしていたとも言っていました。高中は，高岡中学校のことです。

金沢市立高岡中学校 - Wikipedia https://t.co/pcjdTjyjXC
石川県金沢市新神田1丁目10番1号

　被告発人安田繁克の家が東力，被告発人多田敏明が間明と聞いていました。供述調書で被告発人安田繁克の住所を見たのだと思いますが，その後の大型書店が出来た駐車場の前辺りに家があったようです。入江の交差点の近くにもなりますが，平成4年当時は何があったのかよく憶えていません。

　笹田君と峰田君に関しては，他にも話を聞いたことがありました。守田水産輸送の古参の運転手で松ちゃんと呼ばれていた人ですが，同じトラックの中で話をしていたとき，二人とも自分の息子の親しい友達だと話していました。

　ただ息子といる家は，金石ではなく金沢港の近くと話していたように思います。金沢港でも戸水町の辺りと聞いたように思います。これも記録には記述したことがあると思います。

　少し思い出したのですが，大久保君や笹田君と峰田くんが彼女の交換をしていたという話は，被告発人多田敏明ではなく，被告発人梅野博之の口から出た話かもしれません。あまりはっきりとは思い出せないのですが，これも記録には，しっかりした記憶で記述したものがあるはずです。

　なお，被告発人梅野博之の入社は昭和61年12月頃になると思います。被告発人池田宏美と同時期でしたが，被告発人梅野博之は，けっこう長い間，目立たぬ存在でした。平和町の県営住宅に住んでいるような話を聞いていて，供述調書にもその住所がありました。

　笹田君と峰田君は，平成3年の2月頃，姫のNさん，珠洲市大谷町出身のYSさんが，竹沢俊寿会長に不義理をするかたちで市場急配センターを去ったとき，一緒に行動したとも聞きました。宇出津のK村さんもそうだと思います。

ひまわりチェーン - Google 検索 https://t.co/VjHrS21sZU

　意外に思ったのですが，ひまわりチェーンというのは今も金沢市に存在するようです。ただ店舗数は少なそうです。平成3年当時は，金沢市内のあちこちで店舗を見かけていました。いずれもスーパーというよりは，食料品店に近い感じでした。

加盟店情報 | 全日本食品株式会社（全日食チェーン）
https://t.co/WpxGbZWFsE

　ひまわりチェーンは，「全日本食品株式会社（全日食チェーン）」の加盟店のような情報を見かけました。全日食チェーンというのは，平成4年より前にもどこかで見かけていたような気がしますが，ひまわりチェーンとは関係がないものと思っていました。

飛騨運輸 金沢支店 - Google マップ https://t.co/muLEZuqYjV

　住所は金沢市湊4丁目となっていますが，この飛騨運輸金沢支店の場所の辺りに，ひまわりチェーンの配送センターのような倉庫があったと思います。けっこう新しい建物でした。近くには糧食，カナカンと大きな，似たような商品を扱う倉庫があって，北都運輸の市内配達をしているときの配達先でした。

　たぶん，ひまわりチェーンだったと思うのですが，会社の内容が変わっているとも考えられます。平成3年の春，被告発人大網健二の引っ越しの手伝いで，2トントラックを返しに行ったのも，その金沢港に近いひまわりチェーンの倉庫でした。

　詳しい話は聞かなかったですが，宇出津のK村さんらは，市場急配センターを見限るかたちで，ひまわりチェーンの仕事を始めたようです。

　市場急配センターでの市内配達中，笹田君か峰田君，たぶんその両方と，他の能登の顔見知りの市場急配センターの仕事をしていた運転手とも同じ場所で顔を合わせたことがありました。ひまわりチェーンの店舗だったと思います。ややこしい場所でしたが，だいたいの場所は記憶にあります。

長土塀 - Google マップ https://t.co/svRWwcU64R

　ちょっと意外には感じたのですが，住所は金沢市長土塀になりそうです。被告発人大網健二兄弟とも縁のあった豊蔵組の会社がありますが，その並びの道路からやや斜めで古い商店街に入る道路がありました。その奥の方にひまわりチェーンがあったと思いますが，道路が折れ曲がっていたとも思います。

　自分の受け持ちだった小立野・片町コースの受け持ちのようでしたが，余り配達に行く店ではありませんでした。ずいぶん久しぶりに姿を見たとも思ったのですが，そこで笹田君や峰田君と出会ったのです。忙しそうに真剣に仕事をしていたので声を掛けることはなかったかもしれません。

　笹田君と峰田くんとは，その後にも一度会っております。同じ焼肉店で食事をしたのですが，その場には被告発人浜口卓也，被告発人多田敏明，西口君がいましたし，被告発人多田敏明が手引きをしたような成り行きで，被告発人浜口卓也のアパートに行った後のことです。平成3年の年末です。

***** 宇出津のK村さんと姫のNさんという被告発人大網健二と市場急配センターの接点

　よく考えてみると，金沢市場輸送で被告発人松平日出男を見るより，宇出津のK村さんと姫のNさんを金沢市場輸送でみたのが少し早かったかもしれません。被告発人松平日出男に関しては8月の終わりか9月の初めと記憶にあります。金沢市場輸送の事務所が移転した昭和63年のことです。

　宇出津のK村さんと姫のNさんは，8月の20日過ぎに姿を見ていたようにも思います。見かけただけではなく，その場で話もしているはずかと思います。もともとK村さんのことは知りませんでした。今も被告発人大網健二から聞いていた話以外に，K村さんの話を聞くことはありません。

　前後がはっきりしないのですが，宇出津のK村さんと姫のNさんについて，被告発人大網健二から魚の移動販売の仕事をしていると聞かされました。姫のNさんとは，昭和56年の12月から昭和58年とよく顔を合わせ，一緒に行動することがありました。昭和60年にも会っています。

　その後，姫のNさんとは会うこともなく，話を聞くことも余りなかったと思います。少し聞いたのは野々市の運送会社のことでした。昭和59年の10月に私が金沢市場輸送をやめた後，すぐに金沢市場輸送に入社して，けっこう長く4t車で長距離の仕事をしていたとも聞いていました。

　これもはっきりした時期は憶えていないですが，最初に金沢市場輸送で宇出津のK村さんと姫のNさんの姿を見かけてから，1,2ヶ月後，だったと思いますが，魚の移動販売に使っていたというトラックを，金沢市場輸送の給油機の前の駐車場に停めて，話をしたこともありました。

　二人はかなりポンコツの青い色の2トントラックで市内配達の仕事をしていたと記憶にあります。そのままスクラップ工場に置いてあるような中古車でした。その持ち込みのトラックが古かったことも印象的でしたが，金沢市場輸送での2t車の持ち込みはK村さんとNさんの二人が初めてだったと思います。

　K村さんについて，被告発人大網健二は昔からよく知っている話しぶりでした。宇出津のどの辺りに家があるとか，話を聞いたようにも思うのですが，ほとんど記憶に残っていません。ただ，消去法を交えて，宇出津の「いわいまち」とは聞いたような気がします。

　「いわいまち」というのは口伝なので，発音にも個人差があり，最近は聞かないのですが，宇出津の町内の下岩屋と上岩屋を合わせて，「いわいまち」と中学生の頃に聞いていました。近年，祭礼委員の関係で知ったことですが，川原町も下岩屋と上岩屋と同じ区分になるようです。

　新村三町内というのは，その前から聞いていたのですが，近年，これも祭礼委員の関係で，新町三町内というのも聞きました。もともと宇出津の新町といえば，上町と中町ということは知っていたのですが，大橋組を合わせて新町三町内とのことです。被告発人大網健二が住んでいたのは，この大橋組でした。

　大橋組は川原町とも隣接し，川原町は新村と隣接しています。この宇出津の町内は地図の住所にはないものになります。小さい町内は十数戸，大きい町内は100戸を超えます。この区割りや数は，祭礼委員の仕事をすることでよくわかったのですが，地元でも他の町内のことは知らないことが多いと思います。

　今，手元にある「のと町テレホンガイド」で調べたのですが，K村という漢字の名前は宇出津にありませんでした。たぶん平成16年4月発行のものです。表紙にはないのですが，中にそれらしい記載がありました。2,3日前に必要があって引っ張り出したのですが，住宅地図入りの電話帳です。

　たぶん平成9年ですが，その頃にはK村という漢字の名前が宇出津にあり，私の母親の当時の知り合いにもそれらしい名前がありました。漢字の異なるK村は今でもけっこう宇出津にあるのですが，私は早い段階で，母親から漢字のことを含めて知らされていたと思うのです。K村さんのこととは無関係に。

　疑って掛かるわけではないですが，当初，K村さんのことは余り意識せずにいました。ちょっと事情が違うように感じたのは，平成11年の2月頃のことで，金沢市役所で被告発人大網健二が，私とK村さんを引き合わせたことでした。ただK村さんとはその場で，言葉を交わすこともありませんでした。

　商工会の融資のような話だと被告発人大網健二は私に説明をしていましたが，余り実態のありそうな話には思えませんでした。それでもK村さんは，思い悩んだ様子で，被告発人大網健二を頼りにしていると映りました。しかし，今考えても電話で済みそうな話です。

　印象的だったのは，その時，K村さんが乗ってきたという車の話で，車体が大きすぎて金沢市役所の駐車場には駐車が出来ず，石川県庁の駐車場に停めてきたというような話をしていました。ベンツとは聞かなかったですが，ヨーロッパの外車の大型車のようでした。

　この宇出津のK村さんと姫のNさんは，被告発人松平日出男と前後して金沢市場輸送で市内配達の仕事をトラックの持ち込みで始めたことになります。そもそも被告発人松平日出男というのは，市内配達のトラック運転手の仕事などは知識も経験も皆無の様子で，右も左もわからなかったはずなのです。

　被告発人大網健二の話では，K村さんは以前に，車のブローカーをやっていたという経歴がありました。

　これが被告発人松平日出男との共通する接点になりそうとは考えたのですが，被告発人松平日出男がK村さんと話をする様子は，余り見た覚えがなく，そもそも被告発人松平日出男の姿は麻雀以外に見かけずにいました。

　金沢市場輸送の事務所に被告発人松平日出男の机というのはなかったと思います。昭和63年の9月から平成2年の4月頃までの間のことです。2年以上の間ですが，思い返しても，被告発人松平日出男が机を前に椅子に座って何かをしているというのは見た憶えがありません。

　被告発人松平日出男がどんな車に乗っているのかもわからなかったのですが，平成3年には竹沢俊寿会長が乗っていたベンツに乗るようになっていました。竹沢俊寿会長がシルバーの2枚ドアのジャガーに乗るようになったあとのことと思いますが，けっこう前にベンツから乗り換えていたはずです。

　平成3年の春頃には，ほとんど車の運転をしなくなっていたと思う竹沢俊寿会長です。夫人のエスティマで送り迎えをされている様子でした。会社に顔を出すこと自体，少なくなっていたかもしれません。あのエスティマも一番初期の頃のモデルだったと思います。

トヨタ・エスティマ - Wikipedia https://t.co/CekszsCCo5
それから約半年後の1990年5月12日に市販化され、その卵をイメージさせる未来的なスタイルで「高性能ニューコンセプトサルーン」として注目を集めた。

　わかりやすい時期のことが書いてありました。平成2年5月12日に市販化されたとあります。そういえば，昨日辺りに被告発人安田繁克と雪のスリップのことを書きましたが，ちょうど同じ頃に，金沢市場輸送の事務所前で，同じく積雪の状態でベンツを移動させたことがありました。

　ギアを高めに発進させたのですが，さすがにすごいパワーだと思いました。それから少しして，雪が降らなくなった時期に，ジャガーにかわったとも思います。ジャガーもけっこう長い間，金沢市場輸送で見かけていた印象があります。おそらく見かけなくなったのは，竹沢俊寿会長の体調悪化なのでしょう。

　もっとも竹沢俊寿会長の健康状態に関しては，ずいぶん前から詐病の疑いもありました。糖尿病で石川県立中央病院に通院していたことは事実のようですが，主治医でもないと実際の健康状態のことはわからなかったと思われますし，疑いの目で見る人もけっこう周りにいた感じでした。

　まだ金沢市場輸送で長崎県の長与農協にミカンを積みに行っていた時期で，昭和63年の正月前後になるかと思いますが，だいたいその時期のことで，金沢市場輸送の運転手の武田さんが，竹沢俊寿社長の還暦祝いに赤いチャンチャンコを贈るような話をしていました。

　昭和63年に60歳だとすると，平成3年の秋には63,4歳と推定されますが，杖をつきやっと歩いている状態となっていました。12月には夫人が介添をするようになっていました。今より糖尿病に関しては，目が見えなくなるとか色々と深刻な話を聞く時代ではありました。

　最後に竹沢俊寿会長と話をしたのは，電話でしたが，平成9年の2月頃のことになります。弁護士を紹介してやるといい，しきりに私に会いたがっていました。電話の声を聞いた感じでは，平成4年当時と変わりがなかったと思います。

　最後に竹沢俊寿会長と会ったのも，はっきりとは思い出せないですが，夕方，外が暗くなった時間に，夫人と二人で食事に誘われたことがあり，そのあとにも1回ぐらいは姿を見たような気がします。

　食事に誘われる少し前には，被告発人東渡好信と浜上さんが，子供のいない竹沢俊寿会長夫妻が，私を養子に迎えて会社を継がせたいと考えている，というような話を私にしたことがありました。真偽はともかく，私より被害者安藤文さんに影響を与えそうな話だとは思いました。

　竹沢俊寿会長夫妻に食事に誘われた数日後とも思うのですが，同じような時間に，被告発人松平日出男の誘いで食事に行くことになりました。被告発人東渡好信と浜上さんもいたと思います。他のメンバーは今思い出せないですが，全部で6,8人だったように思います。

　最初に中橋の陸橋の下の焼き鳥屋のような店に行ったのですが，満席で断られたように思います。車の中に乗ったままでいました。そのあと金沢駅の西口に行き，そこで食事をしたと思います。開発されたばかりの金沢駅西口でした。これも調べれば情報が見つかりそうです。

金沢百番街 - Wikipedia https://t.co/mCRe0qKQY6
合計で100店舗を超えるテナントが集積している。JR西日本の子会社である金沢ターミナル開発が1991年（平成3年）3月20日に開業させた。

　「JR金沢駅西口ビル（あんと
西）」とあるので間違いはなさそうですが，金沢百番街という聞いたことのある名称が，西口とは結びつきがありませんでした。平成3年3月20日開業とあります。

　平成16年か17年に，電話で被告発人梅野博之が意味ありげに，宇出津のNという名前の話を始めました。姫のNさんと同じ苗字ですが，電話帳で調べたところ，同じ小棚木の町内に家があったので，直接，その家を訪ねて，市場急配センターとの関係を確認したということもありました。

　被告発人浜口卓也の場合も，姫に隣接した集落の真脇でしたが，金沢では宇出津の出身と話していたようです。

　インターネットも普及していなかった平成4年以前は，能登の宇出津だと言っても通じないことがありましたが，当時の鳳至郡能都町で役場もあったのが宇出津なので，宇出津と説明をしていても不思議はない話です。

　ただそのときの被告発人梅野博之の口ぶりが，かなりあざとく感じられるもので，気になって調べておくことにしたのです。

　まだ金沢市場輸送にいた頃，そのときも給油機の前辺りでしたが，見慣れない人に声を掛けられ，しばらく話をしたのですが，持ち込みの市内配達をしているといい，松任市で宇出津のK村さんや姫のNさんと同じアパートの部屋に住んでいて，紹介で仕事をするようになったと話していたと思います。

　全体的に記憶の方が薄れているので断定は出来ないのですが，少なくとも姫のNさんと同じアパートの部屋に住んでいるという話で，宇出津のK村さんも一緒のようにも聞こえました。どちらかの名前を出し，「ら」という複数形にしていたのかもしれません。

　ずいぶん変わった名前だったので，今でもよく覚えているのですが，今年の春辺りに名前を検索で調べたところ，七尾市の近くによくある名前のようでした。簡単にはみつからなかったのですが，歴史遺産にもなっているような旧家の名前のようです。

　市場急配センターに移ってからも，裏駐車場で一度は顔を合わせているのですが，その後は姿を見なかったように思います。平成4年の1月4日だったと思いますが，市場急配センターの2階事務所で新年の顔合わせがあり，意外ほど大勢の運転手が一同に集まっていましたが，姿は見なかった気がします。

　持ち込み運転手の場合は特に，用事以外に市場急配センターの会社に姿を見せない運転手がいる様子でした。2t車なので，乗用車と同じ通勤にも使っているので，なおさら顔を合わす機会が少なかったのだと思います。金沢中央卸売市場の仕事もけっこう時間にばらつきのあるものでした。

　姫のNさんが松任市に住んでいることは，最初に被告発人大網健二から魚の移動販売の仕事の話を聞いた頃から聞いていたと思います。松任市としていますが，会話では，「まっとう」とだけ呼んでいました。現在は白山市の一部になって白山市全体の範囲が大きく広がっています。

　平成15年の1月，関係者KYNの会社事務所で彼と話をしたとき，話の最後に彼が姫のNさんとの付き合いを語りだしたのはずいぶん意外でしたが，そこには大きなものが秘められていると感じ，姫のNさんや宇出津のK村さんに対する注目度を大きく高めたことは確かです。

　松波のAKさんとも会うことがなく，どこに住んでいるのかも聞かなかったことも大きな意味があると感じていました。いしかわ動物園のアザラシ館の水槽の基礎工事で，松波のAKさんらしき人の姿を見ていたことも記憶には記述があると思います。人形のように黙って座り，目を動かさなかったのも異様でした。

　色の濃い眼鏡かサングラスを掛けていたので表情は読み取れず，横に3人ほど並んで座り，おばさんも一人いたと思います。少なくとも3人はいましたが，同じような行動なのが演目を演じているようにも感じられました。とても松波のAKさんに似ているとは思いましたが，確信にまでは至りませんでした。

　その人たちは型枠大工のようでしたが，その少し前には松波のAKさんが，被告発人大網健二の兄関係者OSNの鳶職の会社をやめ，型枠大工の仕事をしていると聞かされていました。被告発人大網健二に聞いたとも思いますが，そういう話はしたのに，どこに住んでいるのか話さなかったのが気になりました。

　松波のAKさんの妻とは，平成3年12月21日の夜，片町のオーロラ会館の5階ぐらいの飲み屋で会っています。被告発人浜口卓也に連れられて入った店でした。これも記録には繰り返し詳細に記述してある事実のはずです。

　金沢駅の近くに全日空のビルがありますが，松波のAKさんが被告発人大網健二の兄関係者OSNの鳶職の会社で仕事をしている頃，高い階層から足場組立の材料を大量に落下させる事故があったと被告発人大網健二に話を聞き，別かもしれないですが，太ももに鉄パイプが突き刺さったような話も聞きました。

　金沢市場輸送で姫のNさんと顔を合わすようになってからもほとんど会話をした記憶はありません。不思議なほど寡黙でした。他の誰かと会話をしているのも見たことがないのですが，夕方近くに金沢市場輸送の運転手の休憩室の机で，真剣に伝票の整理をする姿は何度か見かけていました。

　少し言葉を交わしたのは，一度，金沢市南新保の被告発人浜口卓也のアパートで会ったときです。被告発人安田敏も一緒にいました。たぶん被告発人浜口卓也に誘われてアパートに行き，しばらくして姫のNさんが来たように思います。言葉は少なかったですが，ずいぶんと穏やかで思慮深く感じられました。

　これは市場急配センターで市内配達の仕事をしている頃のことで，夕方だったと思いますが，早い時間で16時台だったように思います。それより前に，被告発人浜口卓也のアパートに行ったことは，今のところ思い出せません。そこで姫のNさんに出会ったのは，偶然とばかり考えてきました。

　ここでは特定を避けるため曖昧にしておきますが，共通の友人・知人にKという女性がいて，被告発人安田敏とも関わりのあるTさんと結婚していたのですが，平成元年の1月，そのTさんが松波港で新車の赤い軽四で海に飛び込み自殺をしました。

　平成3年の9月，20日頃だったと思いますが，共通の友人・知人にKという女性が再婚したとか再婚するという話を聞き，再婚相手も金沢市大場町東の被告発人大網健二の家で会いました。そのときも松任市と聞いていたように思います。

　その後，2億とも聞いた保険金の話がありました。億の単位でしたが1億ではなく端数はなかったように思いますが，だいぶん前から正確な金額が思い出せずにいます。3億ではなかったと思うので，2億円の可能性が最も高い気がします。端数のことも完全には否定できないです。

　松任市で重機を扱う会社というような話も聞いていました。保険金の話はある場所で，ある人から聞いていますが，それ以外には一切耳にしたことのない話です。これも知っていることのすべては記録に記述があるはずです。今でも名前は憶えています。

　松波港で新車の赤い軽四で海に飛び込み自殺をしたTさんは，高校卒業後に金沢市場輸送で長距離の運転手をしていたとも昭和59年より前に聞いていましたが，昭和61年の12月頃には免許取り消し中でしたが，再度，金沢市場輸送に入社し，ミールの倉庫移動など一緒に仕事をしていました。

***** 笹田君と被告発人大網健二の中古車販売を巡るトラブル

　記憶が薄れていますが，この笹田君と被告発人大網健二との車のトラブルは，中橋陸橋の下の商店街のような場所のことが強く印象に残っていて，そこで昼に被告発人大網健二と会っていたように思うのです。

　このあと《参考資料》としてGoogleで調べたいと考えているのですが，今記憶のまま書いておきます。六枚の交差点から金石方面に向かうとすぐに中橋の陸橋がありましたが，被告発人松平日出男に食事に誘われ最初に向かったのは，陸橋手前の右側でした。

　被告発人大網健二と会ったように思うのが，六枚の交差点から金石方面に向かう方向で，陸橋の右手の奥になります。そこに本当に商店街があったのかも定かではないのですが，滅多に行くような場所ではなく，行ったのもほんの数回だったと思います。

　今考えると，時期的に北都運輸の市内配達の仕事をしていた時かもしれません。北都運輸の市内配達ではずっと金沢市場輸送の古い4トン保冷車でした。車番は6526のような感じだったと思います。昭和59年当時にも乗務していたトラックでした。このナンバーは「石」になります。

　北都運輸の市内配達は，業務用のマヨネーズ，ドレッシング，ジャムなどが主な荷物でしたが，ほぼ金沢市内全域が受け持ちのコースになっていたと思います。それでもだいたいの範囲は決まっていて，配達の最後が金沢港の周辺であったようにも記憶にあります。

　戦災を受けていない金沢市内は，狭い路地が多いという特徴もあるのですが，4トン保冷車での市内配達でもそれほど難儀したという記憶はありません。卯辰山の上り口，天神橋を渡った先のカーブで，無理なUターンをしていたことは，よく憶えています。

- 911：2020-09-12_10:38:19 ＊
《参考資料》金沢市内，中橋陸橋付近と，大和町
https://hirono-hideki.hatenadiary.jp/entry/2020/09/12/103818

　平成元年当時とは町並みも変わっていると思いますが，まじまじと中橋陸橋周辺の地図を見たのは今回が初めてかもしれません。中橋町とありますが，これも初めて目にするような金沢市内の住所です。

　今回，Googleマップを見て，六枚の交差点から中橋陸橋を渡った先の，初めの大きな交差点の名前が中橋の交差点ということをずいぶんと久々に思い出しました。

　中橋の交差点で金石街道と交差するのは，Googleマップで県道60号線と見えますが，大豆田大橋方面が「まめだ大通り」，諸江方面が「もろえ通り」ともなっています。どちらも余り聞いたことのない道路の名前ですが，よく通行する道路でした。

　中橋陸橋は，金沢駅から最も近い陸橋になると思いますが，昭和55年当時からあったと思います。金沢駅から歩いて，被告発人大網健二が住んでいた大和町のアパートに行った記憶があり，六枚の交差点から中橋陸橋が見えたような記憶もあって，その風景は平成に入ってからも変わらぬものでした。

　金沢駅に近いだけあって賑わいは感じられましたが，店などはほとんどなかったと思います。入ったことはなかったですが，中橋の陸橋の下の道路には飲食店がありそうな雰囲気でした。六枚の交差点から増泉の方に向かうと，右手に婦人会館のビル，左手に職業安定所がありました。

　職業安定所の住所は芳斉だったと思います。Googleマップで確認すると前の道路が昭和大通りとなっていました。これは聞いたことのあるような道路の名前です。よく婦人会館と聞いていた建物は石川県女性センターとなっています。

　少し手前に金沢中央郵便局とありますが，平成4年には出来ていた新しい建物で，市場急配センターの仕事で行ったことがありました。イヨカンを積み込んだような気もするのですが，それを金沢中央卸売市場で降ろした時かもしれません。

　石川丸果の課長という人物がいて，被害者安藤文さんとよく似た年頃の娘と思われる人を連れていました。この課長については他にも話を聞いたのですが，被告発人松平日出男と昵懇でよろしくやっているという話でした。

　この告発状の本文には書いていないかもしれないですが，平成3,4年当時，市場急配センターの事務所の横の空き地に，いつも郵便局の大型トラックが駐車していました。いつも2台いたような気がします。金沢中央卸売市場との間になる空き地です。

　その空き地はずいぶん前から市場急配センターの給油所になっていて，Googleマップで確認が出来ると思います。平成3,4年当時はただの空き地ではなく，草が生えた放棄地のような空き地で，舗装などもされていなかったと思います。不思議と郵便局のトラックの出入りは見たことがありませんでした。

　金沢中央卸売市場やその周辺で，郵便局の大型車が仕事をするのも見たことがなかった気がします。新車のような新しいトラックで，いつもピカピカに洗車されているような状態だったのも印象に残っています。ときどき不思議に思っていたのですが，余り話題になることはなかったと思います。

　一度誰かに，郵便局大型トラックの疑問をぶつけ，何か話を聞いたような気もするのですが，忘れてしまったのか思い出せません。あの土地の所有というのも不可解でした。角地になりますが，そこを残して，賃貸か売買かはわかりませんが，市場急配センターが事務所と駐車場を作ったことになります。

▶▶▶　kk_hironoのリツイート　▶▶▶

- RT
kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター）
日時：2020-09-12 11:25／2020/09/12 11:24 URL：
https://twitter.com/kk_hirono/status/1304606916518191109
https://twitter.com/s_hirono/status/1304606795097276416


2020-09-12-112109_平成4年当時の市場急配センターの事務所と給油所になった空き地の場所.jpg
https://t.co/Ukr7ZkWlO8

　スクリーンショットを作成しましたが，あらためてGoogleマップで給油所となった空き地を見ると，平成4年当時の記憶より倍ほどにも感じるほどの広さがあります。金沢中央卸売市場横の道路の角地ですが，すぐ近くに金沢中央卸売市場の立体駐車場の出入り口があります。

　ストリートビューでみると金沢中央卸売市場の建物は4階建てですが，売り場のある1階が，そのまま2階分ぐらいの高さとなっています。2階には一部事務所があって，用事で行ったこともある記憶ですが，他の階などはデパートによくある立体の駐車場となっていました。

　大きな駐車場で，何度か行ったことがあるのですが，広く大きな駐車場だったわりには，車の出入りを見かけることが少なかった気がします。市場急配センターの裏駐車場の横がその出入り口になりますが，特に夕方から夜は，車の出入りを見ることがなかった気がします。

　中橋陸橋の話に戻します。商店街があるようにも，あったようにも見えないのですが，当然ながら陸橋を渡らずに，向こう側には行けず，踏切りがあったという記憶もありません。割と広い道路で，それが一直線に長くなっていたとも記憶にあります。

　中橋の陸橋周辺ではなかったと思えてきたのですが，他にそれらしい場所というのも思い当たるものがありません。なぜ中橋陸橋の周辺として記憶していたのかもわからないのですが，かなり衝撃的に焼き付いた記憶となっています。

　なぜその場所で被告発人大網健二と出合ったのかも不思議でした。それだけではなく，いきなりの興奮状態で私にまくしたてたのは，笹谷君に対する不満でした。同じ金沢市場輸送の会社だから知っていて当然という思いが彼にあったことは否定できないですが，私の立場ではずいぶんと意外でした。

　何度か言葉を交わしたというのもたぶん笹田君ではなく峰田君だったと思います。いつも二人でぴたりと一緒にいたので，どちらとも話をしている感覚ではありました。女子ではよく見かけた仲良さですが，男では他に今まで見たことがない気がします。思い当たる人物がありません。

　背格好も似ていたと思いますが，峰田君の方が細身であったような気がします。笹田君は中肉中背だったと思いますが，どちらかといえば小柄であったような印象があります。

　笹田君も峰田君も他の社員とは，余り話をするのを見たという記憶がありません。今考えると，何か時間をつぶす必要があって夕方に割と遅めの時間まで金沢市場輸送の運転手休憩室に残っていたのかもしれません。他の運転手には見られない行動でもあったので，余計に印象に残っています。

　なぜ被告発人大網健二があそこまで感情をむき出しにして怒っていたのか，今考えられる結論は演技です。当時もおかしいとは思い頭をひねっていたのですが，思い当たることがないまま漠然としていました。

　これまで重要視する事実関係の1つとしながら深くは考えてこなかったのですが，被告発人大網健二と出合った場所が思い出せません。当然ながら携帯電話など普及していなかった時代で，ポケットベルというものはありましたが，持ったことも使ったこともありませんでした。

　昭和58年の春にポケットベルをもたされたことはあったかもしれないですが，私個人ではなく二人以上はいて従という立場だったと思います。

　松元組という暴力団の組員で，北友会の幹部と聞いていました。当時の石川県の暴力団の多くは，山口組一会の傘下に北友会があって，北友会の事務所は中央通りにありました。事務所に入ったこともあったのですが，片町の繁華街のすぐ側で，まるで警察の交番のような雰囲気があったと記憶にあります。

　秋田県の能代の浜に死体で上がり，入れ墨で身元が判明したような話を聞いたのも，最後に会ってから1〜3年後のことだったと思います。白菊町のFNさんのアパートでよく会ったのですが，姫のNさんに対して本気で怒っていたことが印象的でした。理由は聞いていません。

　被告発人浜口卓也も同じ松元組の元組員だったのですが，不思議とそのMUという暴力団員と接点のある話は耳にしませんでした。私はそのMUという人物のつてで，金沢市松村町のダクトの会社で仕事をするようになったのですが，先にMUという人に紹介されたDDさんの紹介だったのかもしれません。

　ダクトというのは空調設備のことですが，仕事をしたのは長くて2ヶ月ぐらいだったと思います。そしてその会社をやめたすぐ後に，金沢市場輸送に入社しています。昭和59年1月のことです。やはりMUさんの直接の紹介ではなかったと思います。MUさんに最後に会ったのは遅くても夏のことだと思います。

　DDさんですが，昭和58年の8月の終わり，宇出津のDDさんの家で，被告発人安田敏に会ったことがきっかけで，被告発人安田敏の金沢市観音堂のアパートに居候することになりました。居候は11月の10日頃まで続き，その後に出雲町の運送会社とダクトの会社で仕事をしたように思います。

　出雲町の運送会社では，社長に，他の社員に無事，正月を迎えさせたいので辞めてくれと言われ首になりました。だいぶん普通ではなかったのですが，これはその後の金沢市場輸送でも問題児扱いされることになります。

　昭和59年の1月から10月まで金沢市場輸送にいて問題を起こし問題児扱いされたことは確かなのですが，そのギャップが大きかったことで，昭和61年8月の入社以降は，自分でいうのもなんですが，大きな信頼と実績を残すようになりました。とりわけ評価してくれたのが竹沢俊寿会長夫妻になります。

　出雲町の運送会社にいたことを考えると，ダクトの会社にいたのは一月より短い間だったのかもしれません。和倉温泉の美湾荘に仕事に行ったことと，民宿での泊りがけで富山県黒部市のYKK吉田工業の大きな工場の現場に行ったことが印象に残っており，富山に通ったのは雪の降る時期でした。

　夜になっていましたが，金沢に帰る北陸自動車道で，ちょうど有磯海サービスエリアの出口からの側道が交わる辺りのカーブで，北海道の地図を象った模様と，札幌と書いてあったと思いますが，高速で雪を巻き上げて走る姿に感銘を受け，長距離トラックの運転手になりたいと思ったのです。

　平成元年ですが，北都運輸の市内配達の仕事を始めたのは5月か6月だったと思います。金沢市場輸送の給料の締切日と給料日が思い出せないのですが，25日締めの翌月5日払いという市場急配センターの給料日とは，違っていたような気がします。考えられるのは月末締めですが，確信は持てません。

　いずれにせよ，北都運輸の仕事は11月一杯となっていたと思います。私にとって続けて2回目のイワシのシーズンでしたが，前年は12月21日辺りに出発した運行を大型保冷車での長距離の運行の最後としました。YTを同乗させ，宮城県石巻市のハローマックに向かった運行です。

　到着した石巻での冷房のこともあるので，ハローマックに間違いはないと思うのですが，この行きの荷物は富山県高岡市の古くて大きな倉庫のような場所で夕方暗くなった時間に積み込んだような記憶があります。

　ハローマックの仕事は他に，高知県高知市と宮城県岩沼市あるいは名取市が記憶にあるのですが，いずれも金沢市内の浅野本町の辺りで荷物を積み込んだ記憶があります。金沢駅から鳴和に向かうと右手でした。道路の名前は東大通りとなっていましが，右手に1本か2本入った通り沿いでした。

　当時，テレビCMがよく流れていた子供向けの人形の会社だったと思います。端午の節句の人形などです。荷物は箱詰めされ中身はわからなかったと思いますが，ハローマックは全国展開する玩具店で，金沢にも八日市辺りに店舗がありました。

　1年目は，そもそもイワシを運搬する水槽が出来るのに，シーズン開始を過ぎていたかもしれません。ほぼ同時に5台の大型平ボディ車が納車されました。いすゞは2台で，三菱ふそうが3台だったと思います。

　5台ともそうだったのかは記憶にないですが，トラックの運転席と助手席のドアの横には，社名を入れることが決まりになっていると聞いたのですが，そこには金沢市場輸送ではなく「両合物産」となっていました。

　蛸島の浜田漁業の関連会社の社名です。おそらくは税金対策ですが，関連はよくわかっていません。浜田漁業は，濱田が正確なのかもしれません。トラックは浜田になっていたと思うのですが，濱田という社名もどこかで見ていたように思います。

　なにか行政処分のようなものを受け，新車の納入が出来ず，それで両合物産の名前を借りたと聞きました。原因は北陸自動車道の新潟県，糸魚川インターでの重量オーバーの摘発でした。運転手が会社の指示で嫌々積んだような話をしたため，大事になったと話を聞きました。竹林から聞いたように思います。

　イワシの水槽は竹沢俊寿会長が調べ上げて業者に発注をしたという話で，和歌山県田辺市の工場でした。一回だけだったと思いますが，水槽を載せたトラックを，これから水槽を載せるトラックに乗って引き取りに行ったのです。たぶん1月の年明けだったように思います。

　しかし，それをイワシの運搬のスタートと考えると，12月21日頃に大型保冷車での最後の運行をした意味がなくなります。大型の平ボディ車の新車もまだ秋のような季節，11月中に入っていたような記憶もあります。工事中で通り抜けできない道路に，その平ボディ車を駐車していました。

　石7599号での最後の運行は，とりわけ印象に残るものだったので大体の日付もよく憶えています。たぶん出発が12月21日ですが，20日という可能性もあるかもしれません。

　2年目のイワシの運搬の仕事の始まりは，日付が特定しづらいのですが，ずっと前から12月の15日頃という記憶になっています。まだ正月やクリスマスが近づいたというあわただしさもなかったという感覚が残っています。

石川県（漁協） 金沢港支所 - Google マップ https://t.co/YRT10LUhsL

〒920-0331 石川県大野町４丁目イ - Google マップ https://t.co/WR3zEIUr5G

　Googleマップで見ると，「４丁目イ」となっていますが，たぶん1年目のイワシのシーズンは，ずっとこの場所でイワシの船の水揚げから運搬をしていたと思います。

　割と最近になってGoogleマップで気がついたのですが，橋があってずっと川だと思っていたものが海の通り道で，大野の地域自体が出島のような地形になっているのだと知りました。起訴状などでは大野埠頭となっていたかもしれません。

　Googleマップでは「石川県（漁協）
金沢港支所」ですが，運転手の間では県魚連と呼んでいたように思います。魚市場のようなものですが，Googleマップには市場とは書かれていないようです。近くにもう一つ魚市場があって，そちらは南浦と呼ばれていたように思います。地名とは関係なさそうです。

石川県漁業協同組合かなざわ総合市場 - Google マップ
https://t.co/xrWpIA3NET

　Googleマップでは，これも聞いたことのない名前になっていました。県魚連の市場の方が荷物も多かったですが，だいぶん前から建物の一部が海産物の直売所になっている話はテレビで聞いていました。Googleマップでは次の名称となっています。

金沢港いきいき魚市 （株）新田商店 - Google マップ
https://t.co/vhlJViXzMb

　そういえば，新田商店は昭和59年当時，河北郡七塚町に会社があると聞いていました。被告発人松平日出男の出身地と聞いたのも同じ七塚町ですし，今考えると年齢もだいたい同じぐらいになりそうです。昭和59年当時は4トン保冷車が4台で，白ナンバーでした。

　昭和59年当時，金沢市場輸送は丸中水産の仕事で，金沢港からスルメイカを積んでいたのですが，それとは別に2,3度，茨城県の今の鹿嶋市行きのあさり貝を積み込んだことがあり，それが新田商店の仕事でした。

　金沢市場輸送は昭和59年当時，丸中水産で新潟の定期便をしていたのですが，昭和61年の8月に私が二度目の入社をした頃にはなくなっていて，代わりに守田水産輸送がするようになっていました。もともと丸中水産は金沢市場輸送と手を切りたかったという話です。

　昭和59年当時の丸中水産は若社長で，先代から引き継いだばかりとも聞いたように思います。まだ20代という感じだったので，今だと9歳前後になるのかもしれません。これまで余り考えたことがなかったですが，当時の金沢市場輸送や竹沢俊寿社長の実像をよく知る人物となるのかもしれません。

　もともと腐れ縁で，金沢市場輸送が丸中水産の仕事をしているという話もありました。金沢市場輸送は朝から人足を出して魚の積み込みを手伝わせていたのに，なぜそこまで悪く見られるのか不思議でもありました。大きなミスや悪さを運転手がしたという話もなかったように思います。

　昭和59年当時の金沢市場輸送は，大型運転手は別かもしれないですが，朝8時か8時半の出社で，決まって金沢中央卸売市場の鮮魚の売り場に行き，丸中水産の新潟便の積み込みを手伝わされたのです。気楽な面も大きかったですが，この辺りはしっかりと徹底したものが規律のようになっていました。

　夜中に長距離を走ることを前提とした朝8時か8時半の出社でした。それで給料が固定で20万円。まだ不景気という時代でもありましたが，市場急配センターの市内配達でも固定給で20万円と聞く時代に，数年後には変わったことになります。

　Googleマップに「石川県（漁協）
金沢港支所」とある場所ですが，今のGoogleマップには見当たらないものの以前は「無量寺埠頭」となっていたように思います。人工的に作られたと思われる埠頭ですが，この奥に向かって中央から右端辺りが，もう一つの別のイワシの水揚げ場所となりました。

　1回目のイワシのシーズンに1回もなかったとは断言できないですが，2回目のシーズンから始まったとすると，その初日だったと思います。水揚げ場所が増えたのは，北陸ハイミールの仕事が増えたからで，イワシを捕獲し水揚げをする船団も浜田漁業お抱えの蛸島丸に，輪島丸が加わりました。

　余りはっきりとは憶えていないものの浜田漁業金沢工場のイワシの処理は一日で600トンと聞いていたように思います。北陸ハイミールはそれが1600トンで日本海側最大という話でした。北陸ハイミールは北海道の釧路の会社らしく，愛国運輸もイワシの運搬に加わりました。

　3週間か4週間ほど前，テレビで大阪府の岸和田市の辺りでしたが，イワシ漁の紹介をしていました。大きな網で漁をしていましたが，はっきりとは記憶していないものの，運搬船の大きさなど2,30トンという話であったように思います。浜田漁業の運搬船は大きなもので400トンでした。

　浜田漁業の運搬船は4隻ぐらいだったと思います。輪島丸の方が少し多かったような気もしますが，小型でした。

　12月の金沢は17時半になるとすっかり夜の暗さになっていたと思いますが，19時から21時の間の時間だったと思います。ちょうど決められた集合時間頃だったとも思うのですが，トラックの運転席にいたところ，下から声が掛かりました。大型車の運転席なのでけっこう高いです。

　これもいきなりの興奮状態で，受け取り次第では喧嘩腰にも思える勢いがあったのですが，突然にわけのわからないような話を始めたのが笹田君でした。たぶんすぐには誰なのかわからなかったと思いますし，普段は無口で大人しいだけに，まるで別人のようでもありました。

　すぐに被告発人大網健二の名前が出たので，だいたいの用件というのは理解ができましたが，一緒にいた若者がチンピラヤクザ丸出しで，短いパンチパーマでした。

　本物のヤクザというか暴力団員を連れてきたものと思ったのですが，しばらくしてそれがS藤だとわかったときは驚きました。前は長髪だったので見た目もずいぶん違っていました。

　二人が乗ってきた車は笹田君の車で，トヨタのレビンかトレノだったと思います。どちらも確かカローラの仲間で，テールランプの形状など外観の少しの違いがあるだけだったと思います。新車のようでしたが，新車と聞いたかもしれません。

ファミリーマート 金沢みなと店 - Google マップ https://t.co/lDMrw0j1QW 石川県金沢市大野町４丁目ヲ３１−１

　上記の「ファミリーマート
金沢みなと店」となっている場所には，かなり遅くまでやっている今のコンビニのような酒店がありました。どこに行ったのか思い出せないのですが，笹田君の車に乗って，その店の前辺りを走行していた記憶があるのですが，たぶんその店に買い物に行ったのだと思います。

　いくらか前の時期の話に戻りますが，11月一杯で北都運輸の市内配達の仕事をやめたとして，そのあとイワシの運搬の仕事が始まるまで，どんな仕事をしていたのか思い出せないのです。12月の20日頃までは，イワシの水揚げが，量と回数ともに少なく，仕事は回転も早いダンプが優先となっていました。

　被告発人大網健二から話を聞いたのが先だったのは間違いないと思いますが，笹田君が私に被告発人大網健二に対する苦情をぶちまけにくるまで，どれぐらいの日数があったのか，今は思い出せなくなっています。そもそも私に何かを言って解決するような話ではなかったはずです。

　今は，笹田君が何を言葉にしていたのか思い出せないですが，「いったい，あの人（あるいは，あの男），どうなるがけ！」というような感じだったとは思います。怒りと驚きが入り混じったような様子でした。普段大人しい人ほど，怒ったときに爆発するとは聞いていましたが，尋常ではなかったです。

　特段とりなしたり，なだめたつもりもないのですが，これも何を話したのか記憶にないものの，受け答えをすると笹田君はすぐに落ち着いたように思います。要するに注意をしてくれという話であったと思いますが，具体的に何をしてくれという話はなかったはずです。

　ちょうど同じ頃，被告発人大網健二のアパートに遊びに行きました。たぶん初めて行ったときだと思います。そこで笹田君の話をした記憶はないのですが，終始穏やかで上機嫌だったような印象が残っています。ようやく神戸から戻ってきた金沢での生活が落ち着いたという，安堵感も感じられました。

　S藤は，見た目とは異なり，最初から大人しい感じでした。笹田君が話す，被告発人大網健二とのトラブルも理解しているようには思えず，不思議そうにもしているとも感じられました。

　その場で，市場急配センターを辞めたような話は聞いた憶えがないのですが，ずいぶん長く顔を見ていなかったので，辞めていたと考えられます。ただ，最初に続けて何度か会った後は，ずっと会うことがなかったと思うので，他の運転手とは違った生活スタイルの仕事をしているようにも思えました。

　金沢市場輸送の仕事で昼に金沢中央卸売市場に入ることは滅多になかったということもありますが，このS藤や被告発人安田繁克が市内配達の仕事をする様子というのも見たことがなかったように思います。

　金沢市場輸送の仕事で昼に金沢中央卸売市場に入るのは，筍の仕事ぐらいで，それも長くて2,3週間だったような記憶です。ちょくちょく行ったのは，魚箱の発泡スチロールを捨て場所から拾ってくる用事で，これは鮮魚の積み込みをするとき，隙間に入れて固定するために必須のものでした。

　一番，市場急配センターの運転手と顔を合わせる機会が多かったのは，金沢市場輸送に一台だけあった給油機かもしれません。給油機には鍵があって，最初のうちは金沢市場輸送の事務所で，女子事務員に借りていたようにも思います。

　金沢市場輸送と市場急配センターは給油機の鍵が別になっていたのですが，9月には被害者安藤文さんが預かるようになっていました。8月中にも一度，二階の窓から落としてもらったような記憶があるのですが，それは市場急配センターにある洗車機の鍵だったかもしれません。

　この金沢市場輸送の給油機の鍵というのも，私と被害者安藤文さんと接近するきっかけの１つとなっていました。おそらくは仕組まれたものです。この給油機の鍵のことだけでも色々とあったのですが，今は全体がぼやけわずかに思い出せる程度となっています。

　12月中にも金沢市場輸送で給油をしていた記憶があるのですが，市場急配センターから鍵を持っていった記憶はなく，金沢市場輸送の女子事務員の預かりとなっていたような気がします。年が明け平成4年となると，今度は金沢市場輸送に給油に行ったという記憶自体がなくなってきます。

　なにか指示を受けたという記憶はないのですが，かなり面倒に思いながら津幡町の太陽鉱油まで行って給油をしたことは，何度か記憶にあります。往復だと30分以上は時間が無駄にかかったと思います。こういう無駄な走行というのは，かなり苦痛に感じていました。

　被告発人大網健二と笹田君の間でトラブルになったという車は，アルトワークスでした。軽四でしたがツインカムターボのマニュアル車でした。これも時期がはっきり思い出せないのですが，4月か5月だったと思います。その笹田君が乗っていたというアルトワークスを私が買うことになったのです。

　きっかけは，それまで乗っていたホンダのプレリュードの故障でした。春と記憶にあるのですが，いきなりギアがおかしくなり，どこかの自動車工場でみてもらうと，ミッションの載せ替えで，ずいぶんと修理代が掛かるようなことを言われました。このプレリュードもマニュアル車です。

　ちょうど同じ頃に，被告発人大網健二は別の人とのトラブルめいた話を私にします。はっきりした記憶ではないのですが，私が査定０の下取りに出したプレリュードの転売が，その原因と聞いたような気もします。相手ははっきりしています。

```

第58回

1974年

昭和49年 石川水産（石川）

［source：］歴代優勝校・優勝者｜高等学校相撲金沢大会
https://hk-event.jp/sumou/winner/

```

歴代優勝校・優勝者｜高等学校相撲金沢大会 https://t.co/4Zz0Zb42BO 
第58回  1974年  昭和49年石川水産（石川）

　高等学校相撲金沢大会とありますが，卯辰山の相撲大会として知られています。昭和49年に石川水産が優勝していますが，この大会の関係者として，ずっと前から何度か名前は聞いたことのある人でした。全国優勝と考えるとずいぶん小柄にも思え，勘違いがあるのかと考えもしました。

　被告発人大網健二からもはっきりした話は聞いていなかったと思うのですが，被告発人大網健二からその人の話を聞く前に，私はその人と出会って，直接，会話をしていました。会話の内容も話をした場所も思い出せないのですが，たぶん守田水産輸送の大型保冷車の運転席だったと思います。

　重なる時期ではなく，たぶん前だったと思いますが，同じ守田水産輸送の大型保冷車の運転手として，宇出津の小棚木のNさんとも出会っています。被告発人東渡好信の知人として市場急配センターに来ていたことを，すでにこの告発状本文に記述済みと思います。

　宇出津の小棚木のNさんの場合は，宮城県の石巻港の魚市場の前で，駐車した守田水産輸送のトラックで話をしたという記憶が，割合はっきりと残っています。同じような状況で話をしたのが，息子が笹田君，峰田君の友人という松ちゃんと呼ばれる運転手で，その人とは複数回似たことがあったと思います。

　笹田君のときほど猛々しいことはなかったと思いますが，負けないぐらい強い調子で，その人に対する不満を被告発人大網健二は私に話していました。たぶんですが，守田水産輸送には長くいなかったと思われ，その後，姿を見ることもありませんでした。

　何月ごろから始まったのか思い出せないですが，ちょうど丸一年ぐらい，守田水産輸送の青森定期便の仕事が続きました。守田水産輸送の自社便とは一日交代でしたが，青森の運送会社に帰り荷として仕事を出すこともあったようです。漢字が思い出せないですが，「しんせい運輸」だと思い出しました。

青森 新生運輸 - Google 検索 https://t.co/1acmNg8mGM

　昭和60年代に見ていたのと同じような青森の新生運輸の大型トラックの写真がぞろぞろと出てきましたが，後ろの扉に大きな赤い文字で港とあるのは，ちょっと見た記憶がないです。

　守田水産輸送は，金沢で三人兄弟がそれぞれ別の運送会社を経営しているとも聞いていましたが，大型保冷車の数は少なく，その割に長距離の運行が長いと聞いていました。同じ保冷車でも他の会社は冷凍食品など運んでいるという話でした。

　金沢から青森まで鮮魚を運ぶと，青森から帆立貝を積んで九州に行き，九州から荷物を積んで金沢に戻るのが，一運行のパターンだと聞きました。ただ，その割に九州方面で守田水産輸送のトラックを見たことはなかったか，少なかったと思います。対向車としてすれ違うこともなかったです。

　被告発人大網健二から売ってもらったアルトワークスの値段は50万円でした。笹田君からの買取価格と同じ値段と被告発人大網健二は言っていましたが，カーステレオのコンポなどを取り外したなどと言っていました。けっこういいのが付いていたような口ぶりでした。

　被告発人大網健二はそれを当然のことのように話し，それでも不満があるいう口ぶりでした。一方の笹田君ですがお金に関する不満は言っていなかったように思います。だからなおさら理解に苦しむ話だったのですが，いきさつはともかく笹田君も新しい車を買ったことで満足をしているようにも見えました。

　被告発人大網健二が神戸から戻った時期というのもすぐに思い出せないのですが，昭和63年のお盆には神戸から帰省していました。神戸から戻って最初の頃，車のブローカーをしているような話をし，福田自動車という名刺をくれたと思います。会社の住所は，金沢市高畠か，少なくともその周辺でした。

　その辺りを車で通りかかって，それらしい車を見たような気もするのですが，私としては余り関心もなく，自分から内容を尋ねることもなかったと思います。

　もともと車のトラブルであれば，被告発人松平日出男が出てこないのも気になっていました。笹田君として頼みづらいか頼みたくはない事情でもあるのかとは想像しましたが，それ以上のことはわかりませんでした。被告発人松平日出男が社員に車の売買をしたという話も聞くことはなかったように思います。

　平成3年12月28日頃，諸江の焼肉店で，笹田君もいたと思うのですが，峰田君のことしか印象に残っていません。笹田君の姿がなければ，なにかあったのかともっと印象に残っていたという気はします。峰田君は割合，社交的で，笹田君の方はいくらか内向的だったとも思います。仲はとても良さそうでした。

　平成3年12月28日頃ではと思ったのですが，この日は市場急配センターの仕事納めの可能性があり，だとすれば，違うような気もします。その日は，強い風で車のドアが歪んだこと，夕方にパチンコオークラに被告発人安田敏を探しに行ったことを憶えています。

**** 平成3年6月，被害者安藤文さんに電話で言われた，どちらの安田

**** 平成4年2月1日の夜，自分で接近しておきながら，金沢西警察署の供述調書で私に発見されたような話にした被告発人安田繁克

***** 被告発人多田敏明が山三青果に行き，23時頃に戻るという話

　午前中であったように記憶にあるのですが，それも11時ぐらいです。被告発人東渡好信だったと思いますが，私に聞かせるような感じで，被告発人多田敏明を山三青果に行かせた，今夜23時頃に戻る，というような話をしていました。対面の会話ではなく電話口だった気がします。

　細かいことは思い出せないですが，23時というのは荷下ろしが終わる時間だと思いました。実際に被告発人多田敏明が会社に戻ったのは23時30分ぐらいだった気がします。その間に私は，被告発人安田繁克と諸江に買い物に行っていたと思います。

　今考えると，この運行も不審に思えるのですが，28年も経っているので確認は難しいでしょう。というのも4トン車一台で，山三青果の荷物が積めたのか疑わしいのです。荷物のほとんどは白菜やレタスでかさばります。大型車でも荷物の少ないときはあったのですが，無理に詰め込めばおろすのも大変です。

　山三青果の仕事は富山，高岡，金沢，福井と決まっていました。荷物の多いときは大型車2台，それにプラス4トン車ということもありました。23時に金沢にいるということは，夕市がなかったことも意味します。

　山三青果の夕市についてはすでにご説明を記述しておりますが，夕市で2台以上ということは一度もなく，必ず4カ所積みでしたが，それでも荷物は少なめでした。

　私もその感覚で23時頃にはちょうど仕事が終わると考えていたのですが，それは福井中継を出しての前提です。今まで気がつかなかったのですが，いつも中継に使っている4トン車で，別に中継に出したとは考えにくいところです。仮にあるとすれば2トン車でしょう。

　福井の市場までは往復で考えると荷下ろしを含め3時間は掛かるのではと思います。23時30分に会社に戻るとなると，3時間前の20時30分には金沢中央卸売市場で荷下ろしを終え，出発していることになります。

　市内配達と同じぐらいの荷物と考えれば，違うような気もしますが，富山から高岡の市場に行くのも，高速道路から離れているためけっこう時間が掛かるのです。高岡の市場から金沢も同じです。

　それに4トン車だとある程度荷物を積めば，大型車ほど安定した走行はできなかったと思います。特に急がなくても21時前に，金沢中央卸売市場に着くことはなかった気がしますし，早くても20時台だった気がします。この時間は夕市で古河市を出発するような時間でもあります。

　被告発人多田敏明の乗務していた4トンウィング車は，箱の大きさの割にタイヤが小さく見え，通常の4トン保冷車に比較すると，ずいぶん安定性が悪そうでした。高速道路でスピードは出せなかったと思います。

　なお，被告発人多田敏明は市場急配センターの1階休憩室に10分から長くて30分ほどいて，家に帰ると言って帰って行ったように思います。機嫌が悪そうにはみえなかったですが，いつもと違う感じの無口さがありました。

***** 珍しく22時頃まで会社に残っていた社員運転手

　21時ぐらいなら他にもあったと思うのですが，その日は22時から23時近くまで運転手が集まり，雑談をしていました。

　はっきり憶えているのは，被告発人東渡好信，浜上さん，七尾のMさんですが，これだと私を含めて4人になります。5人はいたと思うのですが，6人かもしれません。他にいたと考えられるのは河野さんになります。大分前からですが，この河野さんのことが不鮮明になっています。

　数年間はばっちり記憶をしていたので，平成5年11月28日付の手書きの書面にははっきりしたことが記述されていると思うのですが，すでに述べているとおり，今のところ調べて確認はしない方針でいます。

　よくそれだけ長い時間，集まって会話が続いたと思うのですが，17時から18時の間には集まって話が始まっていたはずです。16時頃から始まることも普通にありました。

　今思い出して気になったのは，七尾のMさんのことです。今でも名前を覚えていて，間違っていないと思うのですが総合的な判断で名前は伏せておきます。1月に入り，片山津温泉の新年会が終わった後の入社であったと思います。

　その前は七尾市の共栄運輸にいたという話でした。七尾市で鮮魚を運ぶ運送会社は，共栄運輸ぐらいで，他にあっても小さい会社だったと思います。保冷車の数では小林運送が多かったと思いますが，スギヨの専属で練り製品を運んでいました。

　全部のトラックではなかったかもしれないですが，共栄運輸のトラックは箱の後ろに，お祭りの太鼓の紋章がありました。それで目立ったということもありますが，よく見かけていたので台数も多かったのではと思います。

　七尾のMさんは，何度か1階休憩室の畳の部屋で泊まっているのを見ています。部屋といっても戸や襖のない部屋でした。広くて6畳だったと思います。小型テレビが置いてありましたが，あまりついていることはなく。テレビを見たとはっきり記憶にあるのは4月1日の星陵対堀越学園戦ぐらいです。

　そういえば，この平成4年2月1日は土曜日でした。土曜日なので遅い時間まで集まっていたのかわからないですが，さきほどから気になっていた謎が解けました。

　畳の部屋に泊まっているのを見かけたのは，被告発人東渡好信と七尾のMさんの二人だけです。輪島市の浜上さんも泊まっていたはずですが，はっきり見たという記憶はありません。2月頃にはアパートを探していて，見つかったというような話も，平成5年11月28日付の手書きの書面にありました。

　そういえば浜上さんの乗用車というのが思い出せないのですが，乗務しているトラックで輪島まで帰っていた可能性はあります。被告発人東渡好信も乗用車を見かけるようになったのは，2月か3月に入ってのことだったと思います。

　金沢から七尾と輪島では倍ぐらい距離があると思います。穴水町からだと輪島と宇出津は同じぐらいだったと思います。30キロほどです。金沢から七尾は看板に60キロというのを見かけていました。

　Googleマップで経路を調べてみると，金沢中央卸売市場から宇出津まで121キロ，金沢中央卸売市場から輪島市までが111キロとなっていました。七尾市だと66キロと68キロの経路がありました。

***** 偶然とは思えない裏駐車場での動き，被告発人安田繁克の車の通過

　解散する少し前でしたが，裏駐車場の奥の方から会社の建物まで5人ぐらいで歩いていました。これもはっきり憶えているのは，被告発人東渡好信，浜上さん，七尾のMと私の4人だけです。直前に1人帰っていた可能性もあるかと思います。

　その場の成り行きで特に疑問を持つことなくその場を歩いていたと記憶にあります。会話の流れでその場所にいたのですが，裏駐車場から外に出ることはなかったと思います。

　用があって行くとすれば，金沢中央卸売市場の正面ですが，数人で集まって歩いていったようなことは一度もありません。市場前は早い店で22時には開いていたかもしれません。食事をする店です。ただ市場で荷下ろしが終わるのは早くて23時過ぎだったので，22時はないかもしれません。

　22時から23時というのは金沢中央卸売市場で仕事が始まるような時間でした。午前中は人も多いですが，食事の店がやっているのも14時ぐらいまでで，そのあとは明るい時間でも真夜中のような人通りでした。

　この市場急配センターの裏駐車場というのは，他にも重要な事実関係が詰まっています。今，夜に行くことはないですが，街灯のようなものは見当たらず，現在でも平成4年当時と，余り変わりはなさそうか感じです。

　裏駐車場の一番奥から1階休憩室の裏口のドアまで中ほどを歩いているときだったと思います。市場急配センターの会社前の入り口の方から一台の車が入ってきて，ゆっくりと通過していきました。車高が高かったこともありますが，ヘッドライトがとてもまぶしくて，車の形ぐらいしかわかりませんでした。

　これが後でわかる被告発人安田繁克の車だったのですが，驚いた様子を表情にみせたのは七尾のMさんだけでした。被告発人東渡好信と浜上さんは，うつむきがちでしたが，何も見ていない，なにごともなかったような様子で歩いていました。

　裏口のドアから1階休憩室に入った場面が記憶に残っていますが，それからすぐに解散になったと思います。一斉の解散でした。なお，1階休憩室の前は休憩室と同じぐらいの空きのスペースで，外はシャッターになっていました。鍵などなく24時間，誰でも出入りができていました。

　シャッターは3枚になっていて，夜や休日は1枚だけ，それも半分ぐらいの高さで開いていました。それも人がいるときで，誰もいないときはシャッターが降りていたと思います。夜中に仕事に来る人もいたようたようなので，夜は降りていなかったかもしれません。

***** 金石街道に出る交差点の信号待ちで声を掛けてきた被告発人安田繁克

▶▶▶　kk_hironoのリツイート　▶▶▶

- RT
kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター）
日時：2020-08-10 07:50／2020/08/10 07:48 URL：
https://twitter.com/kk_hirono/status/1292594123799580673
https://twitter.com/s_hirono/status/1292593615361867776


2020-08-10-073646\_.Googleマップ　市場急配センターから若宮交差点jpg.jpg
https://t.co/31CKkOakgT

〒920-0025 石川県金沢市駅西本町４丁目２ から 〒920-0025
石川県金沢市駅西本町 - Google マップ https://t.co/yGSvoBYkF7 
北安江出雲線経由　4分　300ｍ 
北安江出雲線経由と金石街道／県道17号経由　5分　350ｍ

　Googleマップでは若宮交差点となっていました。十字路の交差点で北安江出雲線となっていますが，平成4年当時は金石街道が突き当たりになる交差点でした。それでも数年前にできたばかりの新しい道路でした。

　若宮という地名も平成4年当時は余り見覚えのないもので，平成9年当時は少し離れた場所に若宮大橋ができていて，その手前にノートパソコンとディスクトップパソコンを買ったパソコンの館という店がありました。その前の道路も新しくできた道路です。

　その時間帯にしては珍しく，私の車の前にも1，2台信号待ちの車が停車していたと記憶にあるのですが，後ろに停車した車から人が降りてきて，合図をし声を掛けてきたのです。それが被告発人安田繁克でした。

　金沢西警察署の被告発人安田繁克の供述調書では，彼が信号待ちをしていたところに，私がけんか腰で声を掛けてきたことになっているのですが，乗っている車を知らなかったので声を掛けること自体があり得ないことです。

　被告発人安田繁克は被告発人多田敏明を探していると言いました。被告発人多田敏明が会社に戻る時間を聞いていたこともありますが，私の方から市場急配センターの会社に行って話そうと言いました。

　Twilogで調べたのですが，被告発人安田繁克の車の車種に関する情報は見つかりませんでした。タイヤの大きな大型車でしたが，車の車高そのものは普通の高さで，2枚ドアの後ろが荷台になっていたと思います。トヨタの車だと思います。

***** 市場急配センター1階休憩室で酒を飲もうと言い出した被告発人安田繁克

　市場急配センターの会社に着いてすぐだったと思います。被告発人安田繁克が酒を飲もうと言い出しました。

　諸江の24時間やっているコンビニのような酒屋に行って，酒やつまみを買ってきました。当時，金沢市内では，コンビニもまだ普及していなかったと思います。少し出始めていたような気もしますが，金沢中央卸売市場の周辺にはありませんでした。

　けっこうな量の買い物をしてきたのですが，すべて被告発人安田繁克が支払いをしていたと思います。二人で飲み食いをする量には思えませんでした。食べきることはなかったと思いますが，残ったのをどうしたのか憶えていません。

　二階の事務所には冷蔵庫があったと思いますが，冷蔵庫を使うようなことはなく，夜中に勝手に事務所に入ることもなかったので，鍵が掛かっていたのかもわからないですが。鍵を掛ける戸締まりの様子も見たことはなかったと思います。

　被告発人安田繁克は黒の作業服で，暴走族の特攻服のような衣装でしたが，腕に縦書きの大きな刺繍で「松浦商店」と入れていたのが印象的でした。実在する店とは考えなかったのですが，彼の母親の愛人で，金沢市場輸送で最初にイワシのダンプに乗務したのが松浦さんでした。

▶▶▶　kk_hironoのリツイート　▶▶▶

- RT
kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜s_hirono（非常上告-最高検察庁御中_ツイッター）
日時：2020-08-10 08:26／2020/08/10 08:25 URL：
https://twitter.com/kk_hirono/status/1292603080857407488
https://twitter.com/s_hirono/status/1292602856147582979

2020-08-10-082403_市場急配センターホームページ　代表者　堂野俊一.jpg https://t.co/chz0kgIagp

　今，確認しスクリーンショットの記録を行ったのが，市場急配センターのホームページにある「代表者　堂野俊一」で，確実に特定はできないですが，堂野さんで平成10年11月当時，自ら労務の担当者となのっていたのが，松浦さんの紹介でイワシの仕事を始めた人物です。

　堂野さんが市場急配センターの社長になったという話は，直接聞いていないかもしれません。被告発人安田敏との最後の会話で憶えているのは，竹沢俊寿会長について，とっくの昔に死んでおる，というような話し方をしていたことです。

　被告発人安田敏は堂野の親父というような言い方をしていたと思いますが，私がホームページで告発などの情報公開をしていることに，いつでも訴えられると言っていたと話していました。そのことについてもホームページで公開をしたと思います。

　たぶんその次に被告発人安田敏に会ったときだと思いますが，堂野さんについて，市場急配センターの従業員というような，そんな感じの言い方をしていました。

　従業員ではっきり憶えているのは，一度だけ金沢刑務所に面会に来た被告発人松平日出男で，パンツと何かを差し入れていったのですが，指印を押すのに帳簿を見ると，職業を会社従業員としていました。供述調書では，代表取締役社長となっていたと思います。

***** 山三青果の運行から戻りしばらく1階休憩室にいた被告発人多田敏明

　被告発人安田繁克と諸江の酒店から会社に戻り，少しすると被告発人多田敏明が休憩室に入ってきました。午後11時から11時半の間だったと記憶にあります。被告発人多田敏明はおとなしく無口で，被告発人安田繁克との間にも会話はほとんどなかったと思います。

　もともと被告発人多田敏明を探しているというのが被告発人安田繁克が私に接近してきた口実だったのですが，用事があるようなそぶりは全く見せておらず，少しすると，帰ると言い出した被告発人多田敏明を引き留めることもありませんでした。

　28年前の記憶で，それらしい記載の書面も読んでいないのですが，強く印象に残るのは，被告発人安田繁克が酒屋で買ってきた商品の量でした。それを机の上に並べていたはずです。後から入ってきた被告発人多田敏明もそれを見ているはずになるのですが，無反応で疲れた様子にも見えました。

　この2月1日の夜のこともけっこう長い間，鮮明によく憶えていたと思います。知る限りのことを詳細に記述しているはずです。ただ，最初の頃は，この2月1日を全く違った時期と取り違え，後になって自分の記憶違いに驚いたようなことを憶えています。

　この2月1日は特定がしやすい日でした。この土曜日に福岡行きのミールを積み込み，会社の指示のままよく考えずに，月曜日に出社をしてから福岡に出発しました。夕方のフェリーに乗るのに向かったのは神戸市の魚崎だったと思います。

***** 被告発人安田繁克が話し始めた被害者安藤文さんとの関係，交際を否定

　28年前の記憶になりますが，この平成4年2月1日の夜，深夜の2時頃まで市場急配センターの1階休憩室で被告発人安田繁克と話をしていました。2時に被告発人安田繁克と別れた後のことは，現在思い出すことがなく，2月2日の昼と夜のことも同様です。

　たぶん今は思い出せないこともあるのかと思いますが，思い出せる範囲で被告発人安田繁克は私に次ぎのようなことを話していました。

a. 被害者安藤文さんとの交際を否定。

b. 用事があって一度，被害者安藤文さんの自宅に電話を掛けたことがある。

c. 被害者安藤文さんの母親は塾の先生。

d. 被害者安藤文さんの父親は，議員か代議士。

e. 人間不信になった（被害者安藤文さんに関わっていた頃）。

f. 殴りたくなるような女とは付き合わない。

　他のもあったような気がしますが，とりあえず思い出せるのはこの辺りかと思います。あとで思い出せることがあれば，項目を追加します。初めてなると思いますが，見出しレベルの6を使って箇条書きとしました。

　けっこう寒い夜だったことも印象にあります。この日に限らないのですが，市場急配センターの1階休憩室には，大きな石油ストーブがあり，アパートに帰っても寒かったので，アパートに帰らずに時間をつぶすこともよくありました。

　弁当のことも私の方から訊いたように思います。ほかに直接，被告発人安田繁克に答えをきく機械はなかったので，やはりこのときになると思います。「冗談で言ったら作ってきた。」という趣旨の返事でした。この弁当のことは1月21日の夜に，被告発人浜口卓也から聞いていました。

　被告発人安田繁克と被害者安藤文さんとの交際というのも，その1月21日の夜に初めて聞いた話でした。この交際自体が作り上げられた架空の事実である可能性が高く，示し合わせた計画性をうかがせるものとなっています。

*** 被告発人安田敏

**** 金沢市場輸送のストライキ中，被告発人安田敏からの電話連絡（平成3年4月）

**** 被告発人安田敏の妻の不審な行動（平成3年）

　被告発人安田敏から連絡があったのが平成3年4月の終わり頃として記憶にあるのですが，ゴールデンウィークの連休に入る前だったとも思います。輪島屋鮮冷の運転手として金沢市場輸送での荷物の積み替えのこともあったのですが，たぶん連休前です。

　金沢市場輸送での被告発人安田敏の面接があったのが4月の終わりとも思えるのですが，5月の連休明けから被告発人安田敏が仕事を始めたという記憶はなく，あるのは，すぐに市場急配センターで市内配達の仕事を始めたと聞いたことです。

　まるでとんとん拍子に進んだのですが，金沢市花里の被告発人安田敏のアパートに行ったのは，被告発人安田敏が市内配達の仕事を始めてからではなかったかと思います。

　一方で，入社を決める条件とした50万円の前借りですが，入社が決まる前に，被告発人安田敏のアパートに行って，その場に被告発人安田敏の妻となる彼女がいたような記憶もかすかに残っています。

　はっきりしていて異様に思ったのは，その後も含め一切，被告発人安田敏の妻となる彼女からお礼の言葉はなかったことです。迷惑そうですらあったのですが，そのあたりも自然な成り行きとは思えないところでした。

　一応，アパートとしましたが，実際は工務店の倉庫の二階のような部屋でした。1DKでしたが，他に賃貸の部屋はないという変わった物件でした。交際を始めてから被告発人安田敏が転がり込んで住むようになったという話です。

　前の年つまり平成2年に被告発人安田敏と会ったときは，被告発人安田敏は片町の近くに住んでいて，それも通常のアパートではない借家の二階だけというような変わった物件でした。人が出入りしているようには感じなかったのですが，色々と物が多く，雑貨類の店舗のような印象も残っています。

- 十三間町中丁 - Google マップ https://t.co/KlKh6AvEtD

　たぶん住所は，上記のGoogleマップにある十三間町中丁になると思います。この中丁というのは見覚えがなかったのですが，十三間町の方が犀川に近く，ある程度，犀川から離れていた記憶があります。

　やはり秋だったと思うのですが，その季節としては暖かい日で，夜の気温を気にかけながら薄着で出かけたような憶えがあります。神田の陸橋の手前，ジョーシンという家電店の前のバス停からバスに乗ったことも憶えています。

　ほぼ8月いっぱいまで一緒に市内配達をしていた頃は，ちょくちょくと花里の被告発人安田敏のアパートに遊びに行っていました。仕事が終わった後の夕方です。暗い時間までいたり，一緒に食事をした憶えはありません。

　小立野で餃子を食べたことはありました。当時話題となっていた人気のお店で，第八餃子というような店名でした。被告発人安田敏に案内してもらうようなかたちで店に入ったのです。

　赤坂プラザに入ったこともありました。百貨店に近い商業施設になります。被告発人安田敏のアパートに向かったのは，だいたいが，場所が全然違う大徳自動車学校から向かったという記憶があり，藤江のバイパス沿いのゲームセンターでゲームをすることもありました。

　何回ぐらい被告発人安田敏の花里のアパートに遊びに行ったのか，今は思い出せないですが，以前には詳細に記述した書面もあるかと思います。そちらの方が記憶も正確です。

　被告発人安田敏とは，市場急配センターで市内配達の仕事を始めてから何度か金沢港の五郎島にセイゴ釣りに行ったこともありました。金石の釣具店で太い青虫を買ってから向かっていたとも記憶にあります。その店の青虫が特別太いものでした。

　9月に入ってからも被告発人安田敏と金沢港の五郎島にセイゴ釣りに行くことはありました。被害者安藤文さんのことで何か話したようなこともかすかに記憶にあるのですが，今は思い出せなくなっています。

　被告発人安田敏の花里のアパートに行くより，一緒に五郎島にセイゴ釣り行くことが多かったとも思います。決まってセイゴは釣れましたが，持って帰ることはほとんどなく，一度だけ例外がありました。

　60センチぐらいありそうなセイゴが釣れて，それを市場急配センターの二階事務所にある冷凍庫に入れ，まさやんと呼ばれた津幡の運転手にあげたことをよく憶えています。まさやんも持ち込み運転手だったと思います。

　そのまさやんが被害者安藤文さんに，遊びすぎたら鼻が落ちるぞ，などと言ったのも印象的でした。もともと冗談を言うようなタイプではなかったのですが，今考えると事実でないことを吹き込まれ，誤解をしていた可能性もありそうです。

　もう一人，細身で背が高い人がいたのですが，名前が思い出せなくなっていて，しばらく前から気になっていました。ふと中山という名前だったような気がしたのですが，記憶に自信はありません。彼も被告発人梅野博之と同じぐらいの年頃で，入社の時期も近かったような気がします。

　市場急配センターは10代から20代の運転手が多かったのですが，被害者安藤文さんは話しかけられてもあまり喋らず，その中山さんなど40代から50代の運転手や社員とは，積極的に会話をしているとも聞いていました。

　被告発人安田敏の妻となる彼女ですが，車というのも彼女の車一台だけで，それでよく被告発人安田敏の送り迎えにも来ていました。ほとんど変装に近いような格好で，顔はほとんどわかりませんでした。

　当時の車で，ミラージュやファミリアのような車種でした。小型車になります。それがかなりのポンコツで，そのままスクラップ工場にありそうな，代車のような車で，土建会社が現場で使っているような車でもあったのですが，若い女性の車とはにわかに信じられませんでした。

　帽子とマスクとサングラスだったと思いますが，そのポンコツの車との組み合わせが，テレビドラマ以上の不審者ぶりを印象づけていました。声や話し方にも特徴があって，赤ちゃん言葉に近いものがありました。

　花里のアパートは，ダイニングキッチンの奥に同じぐらいの広さの部屋があったのですが，たぶん8畳間と思います。奥に大きなベッドがありました。ダブルベッドではなくセミダブルだったような気もするのですが，部屋の半分近くを占めていました。

　彼女がいないこともあったように思いますが，いるときは必ずベッドで寝ていて，タオルケットを頭からかぶり，絶対に顔を見せようとはしませんでした。思い当たるきっかけはなかったのですが，最初から敵対的な姿勢に近いものがありました。

　これとよく似た経験は前にもあったのですが，金沢港でイワシの現場監督のような仕事をやっていたKKさんの妻ことです。家に行くとあからさまな攻撃姿勢で追い返されるようなかたちとなりました。聞こえたのは声だけです。

　幼稚園か小学校の低学年ぐらいの子供が2人いる姿を少し離れて見た記憶はあり，そばに妻がいたような気がするのですが，顔や表情は全く見えなかったと記憶にあります。KKさんの車というのも記憶にないのですが，歩いて通える場所でした。

- Google マップ https://t.co/qNkYyAzf9O

　周辺の道路が変わりすぎていてわかりづらいのですが，上記のGoogleマップに長田二丁目という交差点があります。金石街道から斜めに入ったと思うのですが，交差点の右角にスーパーがあったと思います。

　今は周辺にいくつも新しい道路ができているのですが，少なくとも平成4年頃までは主要な道路でした。交差点を右折すると8号線バイパスに向かう道路があり，8号線バイパスの方から来る方が多かったとも思います。

　裏道として使うことが少なくなかったのですが，その長田二丁目という交差点を金石街道から来て右折すると，しばらく先，右手に小学校があったと思います。その小学校のもう少し先を左に入る道路があり，少し入ったところに広場がありました。

　時代劇に出てくる長屋を連想させる独特の雰囲気で，そこにある家の一つがKKさんの家でした。潜水服と酸素ボンベを見せにもらいに行ったときかもしれません。行ったのは一度だけでした。

　最高裁判事の息子と聞いていたKKさんのことです。石川県警察で白バイに乗っていたという話もしていました。社会勉強で金沢に来て，最高裁判事の父親の友人だった竹沢俊寿社長の世話になったという話を私は信じていました。

　今考えると，住んでいる家に余りに不満があったので，私を連れてきたことに妻は激怒し，あのような態度になったのかもしれません。KKさんは群馬県の渋川市の辺りに実家があり，大きな梅園があるとも話していました。

　物腰は柔らかくこざっぱりとしていましたが，KKさんは体型が東京の上野のあると聞く，西郷隆盛の銅像に似ていたと思います。以前はよくテレビで目にする機会があった銅像ですが，実際に見たことはありません。

　体型はそうでしたが，大柄ではなく，たぶん身長も170センチはなかったような気がします。最高裁判事の息子という話も信じがたいのですが，元警察官と話していたのも半信半疑になります。

　気になるのは，その後にも似たようなことがあって，次は，被害者安藤文さんの父親が弁護士という話でした。これを私に吹き込んだのは被告発人多田敏明です。

　KKさんとは最後に群馬県の前橋市内国道50号線の交差点で会っています。足利方面に向かっているとき信号待ちで，大型のバイクに乗っている彼に声をかけられました。たぶん古河市の山三青果に向かっているときです。

　熊本県の八代市で荷物をおろし，翌日に鹿児島市内の市場から長野市の市場行きの白菜を積みました。長野の市場で夜中に荷物をおろし，朝まで仮眠をしたあとのことになります。

　金沢市場輸送で山三青果の仕事が始まったのは平成2年の12月に入ってからだと記憶にあります。同じ古河市の青果市場には，昭和62年の4月頃にも一度行っているのですが，その間に行くことはなかったと思います。

　乗務していたのは保冷車だと思いますが，平成3年の1月17日からは新車で納入されたウィング車に乗務するようになりました。ナンバーは石川2315だったと思います。同じ平成3年の10月12日は市場急配センターでも新車に乗りましたが，そちらは石川3068でした。

　ただよく考えてみると，平成2年に金沢市場輸送で乗務していた保冷車は冷凍機付きで，箱が昭和59年当時の新車のもので載せ替えとなっており，他の保冷車より箱の中が低く小さく感じるものでした。それにかさばる白菜を積んだのかとなると，ちょっと疑問もあります。

**** 平成3年12月22日の夜，顔を見せた出産直前の被告発人安田敏の妻

　平成3年は12月21日が土曜日，22日が日曜日です。この21日の土曜日に被害者安藤文さんとの間で，ティファニーのネックレスのことがあり，夜に被告発人浜口卓也のアパートに行ったものの用件を切り出すことができず，次の夜に被告発人安田敏に頼みに行ったのです。

　8号線バイパスの藤江陸橋の側道で，走行中の車内から投げ捨てたネックレスのプレゼントでした。21日の夕方，暗くなっていたので19時は過ぎていたと思いますが，捨てたものを拾いに行き，そのまま南新保の被告発人浜口卓也のアパートに行きました。

　いきなりの訪問だったと思いますが，訪問してしばらくした頃，被告発人浜口卓也が電話で被告発人大網健二と話をしていました。どちらが掛けた電話だったのか今は思い出せないですが，偶然とは思えない電話で，電話の用件もよくわからないものでした。

　12月22日の日曜日は昼に被告発人大網健二と会っていました。パチンコオークラの横にあった花屋で配達を頼んだことを今数年ぶりに思い出した気分です。バイパスの県立中央病院の近くの大きな喫茶店に入ったこと，森本と津幡の間のゴルフの打ちっぱなしに行ったことなどありました。

　印象に残っているのは，河北潟の広い場所に行ったことです。そこでよくゴルフの練習をしていると被告発人大網健二は話していました。天狗中田ハム才田工場の間の道路で突き当たりに少し左に行った辺りかと思います。

　いずれ取り上げる予定なのですが，一月ほど前，宇出津の図書館に行き，平成4年2月と3月の北國新聞縮小版を閲覧しました。2月で調べたかったのは関越トンネルの通行止めの日にちだったのですが記事は見つかりませんでした。

　たぶんその2月の方だったと思いますが，目にして思い出す事件があって，金沢市の東山となっていましたが，妻が夫を殺害し河北潟に埋めたという事件がありました。

　金沢ではその数年前にも何度もニュースになる殺人事件があって，事件の内容は憶えていないですが，金沢競馬場の関係者でした。被告発人大網健二が平成3年2月頃から住んでいた金沢市大場町東は，競馬場との間に田んぼが広く距離がありますが，競馬場の関係者が多く住んでいると彼は話していました。

　小さな家でしたが中古物件で購入したと被告発人大網健二は話していました。4月だったと記憶にあるのですが，金沢港の近くの無量寺のアパートから引っ越しを手伝いました。その頃はまだストライキの問題が起こっていなかったような気がします。

　2トントラックを借りて，金沢港の近くの，ひまわりチェーン配送センターのようなところに被告発人大網健二と二人で返しに行ったこともよく憶えています。そこにはカナカン，糧食と大きな倉庫が3つほどあり，北都運輸の市内配達でよく行っていた場所です。

　夕方，少し薄暗くなりかけた時間まで被告発人大網健二と一緒にいたと思うのですが，12月22日なので冬至に近く日が暮れるのが最も早い時期です。17時にはかなり暗くなっていたかもしれません。

　たぶん東力2丁目の自宅アパートに戻ってから被告発人安田敏に電話を掛けたように思います。公衆電話を使ったような記憶はないからです。19時から20時の間ぐらいに花里の被告発人安田敏のアパートに着いたように思うのですが，帰る時間はけっこう遅くなっていたように思います。

　やたらと部屋が明るかったと記憶にあるのですが，部屋に被告発人安田敏の姿はなく，キッチンにいたのだと思います。何か料理を振る舞われたような気もするのですが，今ははっきり思い出せません。

　漫画のコマで言えば，3，4コマの場面しか記憶にないのですが，それが強烈に脳裏に焼き付いています。被告発人安田敏の妻は，それまでとは別人のようなふるまいで，普通に顔を見せ，テーブルの前に座っていました。

　被告発人安田敏は自分の誕生日を12月25日と言っていたと思いますが，同じ日の出産になるかもしれないと話していました。その日が出産予定日であれば3日前だったことになります。

　普通，妊婦の女の人はお腹が目立たないマタニティドレスのようなものを着て人前に現れると思うのですが，そのときの被告発人安田敏の妻は，下がジャージで上がぴっちりフィットするシャツという姿でした。ちょうど部活の女子生徒という感じです。それに薄着であることも気になりました。

　上着を羽織ることもなかったのですが，どう考えても尋常ではない行動で，ものすごく穏やかでやさしそうな態度ふるまいでした。大きなお腹はずいぶんと目立っていました。出産を控え不安な気持ちからおとなしくなっていたとは考えられますが，前の顔見せ拒否とは余りにかけ離れていました。

　この12月22日の夜は，被告発人安田敏の花里のアパートで，他にも偶然とは思えない出来事がありました。

**** 平成3年12月22日の夜，被告発人安田敏の花里のアパートに掛かってきた，会社からの運行指示という電話

　以前は，他に色々ありすぎて，さほど重視する問題とは考えていなかったのですが，今改めて思い出しながら考えてみると，不可解な点が大きく感じられます。

　電話があった時刻は22時から23時の間だったと思います。その日の被告発人安田敏は普段とは別人のように上機嫌でした。妻の出産を間近にしているという喜びもあったのかもしれません。

　被告発人安田敏のアパートの電話は当時珍しい特徴があって，昭和40年代に普通であったダイヤル式の黒電話でした。その何年も前から一度も見たことがなかったので，とても珍しいものでした。

　その電話機の特徴もあるのですが，気になったのは近くにいるのに電話口の声がまったく聞こえなかったことです。被告発人安田敏が一人芝居で何かやっているようにも思えたぐらいです。それでも電話のベルが鳴ったことは間違いのないことでした。

　被告発人安田敏は電話口で，相づちをうつようにほとんど一方的に相手の話を聞いている様子でした。とても素直な様子でもありました。

　10月か11月頃には，被告発人安田敏の出社が遅く，自宅に電話をしても電話線を抜いて出ないと，被告発人松平日出男と被告発人東渡好信が口を揃えて苦情を言っていました。一度だったと思いますが，実際，花里まで被告発人安田敏を呼びに行かされたこともありました。

　金沢市場輸送の仕事は，行き荷で雑貨の定期便が多かったのですが，市場急配センターではなかったと思います。日本通運，トナミ運輸，中越運送の定期便を金沢市場輸送ではやっていました。仙台，福岡，千葉などです。

　11月だとまだ七尾市の能登木材，林ベニアの仕事が始まっていなかったと思います。金沢中央卸売市場の裏側の倉庫から馬鈴薯を積む仕事が多い時期でした。北海道から船のコンテナで金沢港に運ばれてくると聞いたことがありました。

　他は雑貨の貸し切りの仕事があったと思いますが，被告発人松平日出男らが問題にしていたのは被告発人安田敏の午後1時ぐらいの出社で，連絡がとれないと運行の指示に支障が出るという話でした。

　午後の1時から2時の間に会社を出発すれば，それで十分，荷物の積み込みに間に合う仕事しか経験がなかったので，それもおかしな話とは思っていました。早い時間に積みに来いという指示を受けた経験はなかったからです。

　電話の線抜きと同じ頃に，被告発人松平日出男と被告発人東渡好信が口を揃えて問題にしたのは，他に被告発人安田敏が危険な運転をしているという話もありました。スピードを出しているという話でしたが，具体的な話ではないように感じていました。

　雪が降るようになってから被告発人安田敏と話をしたことはあったのですが，関越道の湯沢インターと長岡市の間で，かなりの積雪や吹雪の中，被告発人安田敏がゆっくり走ったというので，何キロかと聞いてみると，80キロだと話していました。普通は50キロぐらい落とす状況下だと思います。

　今思い出せるのは，工事現場突入の件，茨城県土浦市の話と，東名高速豊橋インターでの白菜散乱の話，清水倉庫でのタイヤ爆発の件ぐらいですが，被告発人安田敏がいろいろと問題を起こしていたことは事実で，会社の対応が甘すぎて不自然には思えていました。

　被告発人安田敏には他に50万円の前借りのこともあったのですが，被告発人安田敏の非常識な振る舞いを，被告発人松平日出男は私に自分の責任のように思わせていました。これは被害者安藤文さんの関係とも共通するところがあります。

　電話を終えた被告発人安田敏は，今から豊橋に行くことになったと話しました。愛知県の豊橋市です。これは小林運送の仕事で，私も平成4年2月中に2回やりましたが，豊橋の仕事のことを聞いたのもこれが初めてだったかもしれません。

　被告発人安田敏の話では，津幡のYTの仕事で，津幡から金沢方面に向かっているとき，金沢東インターの手前で，国道8号線バイパスが大きくカーブしているところと聞きました。ちょうど道路の上には北陸自動車道があって，下をくぐるような場所とも思い浮かべました。

　そこで津幡のYSが他の車とトラブルになり，車の外でケンカとなって，道路に頭をぶつけしばらく気を失っていたという話を，今の電話で聞いた話として被告発人安田敏は私に説明をしていました。

　怪我の程度はよくわからなかったですが，数日後に津幡のYTと会ったときは何事もなさそうな様子でした。怪我の話を聞くようなこともなく，他にその話をする者もいなかったと思います。

　誰からの電話だったのかと被告発人安田敏に尋ねたはずですが，被告発人安田敏の返事が思い出せなくなっています。被告発人松平日出男か被告発人東渡好信のどちらかでした。あるいは曖昧な返答だったかもしれません。

　さきほど考えたのですが，会社が開いていない夜中の仕事が多い長距離トラックの仕事で，何かあったときの連絡先として，被告発人松平日出男の自宅の電話番号も聞いていませんでした。

　実際，金沢市場輸送のときは配車係だった本恒夫の自宅に，仕事のことで夜中に電話をしたことがありました。夜中に電話で次の朝の仕事の指示を受けるようなこともあったのですが，携帯電話などない時代のことです。

　実際は，平成4年の2月頃かに市場急配センターに携帯電話が一台入ったのですが，被告発人東渡好信が北陸ハイミールの倉庫でフォークリフトの運転をしながら独り占めで使っているような話でした。その電話番号というのも知らされることはなかったです。

　被告発人東渡好信が持っている携帯電話を北陸ハイミールの倉庫で見ることもあったのですが，大きなラジオカセットを肩からぶら下げているような感じでした。

　被告発人安田敏は少しも不満なそぶりはみせず，上機嫌のままこれから豊橋に向かうと話し，私も東力2丁目の自宅アパートに戻りました。東力ストアの前で追突事故に遭ったのは，そのときではなかった気がするのですが，被告発人安田敏のアパートから戻ったときだったとは思います。

　夜に被告発人安田敏の花里の被告発人安田敏のアパートに行ったのは，その12月22日だけだったとも思います。その後，被告発人安田敏のアパートに行ったのも，たぶん一度だけで，年明けの1月になっていたはずです。

　そういえば1つ思い出したのですが，ショートケーキを手土産に被告発人安田敏の花里のアパートに行ったことがありました。

　平成4年1月に入って，被告発人安田敏の花里のアパートに行ったときは，昼で，被告発人安田敏の買い物に付き合い，レンタルという話だったような気もするのですが，生まれたばかりの子供のための加湿器だと被告発人安田敏は話していました。

　湿度の高い北陸で，除湿機というのは見たこともあったのですが，加湿器というのは他に聞いたこともなく必要なものなのか疑問もあってよく憶えています。

**** 被告発人安田敏に頼んだ被害者安藤文さんへのクリスマスプレゼントの受け渡し

　「[[平成3年12月24日，クリスマスイブの夜]{.ul}](\l)」にある通り，12月24日の夜，まだ日付が変わる前の時間に山三青果の仕事を終えました。翌日が25日ですが，たぶんこの日も関東に向け運行に出発していると思います。

　市場急配センターの仕事の関東便で泊まりとなったのは2回だけだったと思います。平成4年1月の終わり頃の池袋の三越デパートからの展示会の引き上げと，同年3月20日頃，当時の静岡県清水市から古河市に向かった運行です。

　金沢市場輸送でも関東便での泊まりというのはほとんどなく，帰り荷が見つからないと空車で帰ることが何度かありました。泊まりが多かったのは宮城県の塩釜・石巻で，福岡では連泊することもありました。この泊まりに嫌気がさしたというのも金沢市場輸送をやめた理由です。

　例えば本日の8日に七尾市でベニアを積んで出発すると，関東の目的地には夜中の2時から4時ぐらいに到着し，朝一番で荷下ろしして茨城県古河市の山三青果に向かいます。だいたい午前中11時頃までには着いていた気がします。

　夕市とも呼ばれていたような気がしますが，その夕方の競りがないと早い時間，午後1時頃には出発が出てきていたように思います。まだ明るい時間に，富山の市場に入ることもありました。それでも最終的に荷下ろしが終わるのは22時頃になっていたと思います。

　夕方の競りがあると出発が20時から遅いときで21時になっていました。市場急配センターではなかったと思いますが，金沢市場輸送では4カ所卸で福井から戻ると，朝の7時近くになることもありました。早朝は市場が混み合って荷下ろしに時間も掛かっていたと思います。

　市場急配センターではそれほど遅い時間になったという記憶は残っていないのですが，夜中の2時頃に荷下ろしが終われば早い方だったかもしれません。

　先ほどの例で，8日に七尾で積んだ荷物を9日の朝におろすと，同日に古河市を出発して，荷下ろしが翌日の10日なります。しかし，実際は9日の夜の間に仕事が終わることが少なくないというのが市場の仕事の特徴になります。

　荷物をおろした当日に別の荷物を積んで次の運行に出発することを「着発」と呼んでいました。当日の出発がないと，トラックの洗車や修理，他の運転手の積み込みの手伝いなどして17時まで会社にいることになっていましたが，これを「あがり」と呼んでいました。

　平成4年当時は，銀行や役所は土日休みの週休二日制になっていたかと思いますが，他の会社や工場で土曜日に休みというのはなかったと思います。よくあるのが土曜日に荷物を積み込んだ月曜日おろしになり，日曜日に出発するので土曜日は「積みおき」と呼ばれていました。

　金沢市場輸送の場合は，他に「三角運行」と呼ばれるパターンもあって，九州行きの荷物で九州に行き，帰り荷が九州から関東になって，関東から荷物を積んで北陸に帰るという運行でした。これは市場急配センターではなかったパターンです。

　この運行の組み合わせというのはちょうどパズルのピースのようになり，当てはめていくことで日付の特定ができたり，事実関係が変化のある物語のような経過となりました。

　被告発人安田敏にプレゼントの受け渡しを実行してくれと頼んだのは12月24日でした。それからしばらく被告発人安田敏とは連絡がつかず，ようやく被告発人安田敏が自宅の電話に出たのは，私が栃木県足利市の太陽鉱油のガソリンスタンドから電話をしたときでした。

　なにか私が事前に頼んでいたのとは違った方法でやったと被告発人安田敏は説明をしました。被害者安藤文さんを外に呼び出して無理強いしないで渡してくれと頼んだのを，仕事中の彼女に，「これ秀樹やもろてくれと」と言ったようです。絶対がついていたかもしれません。

　ほとんどの場合，被害者安藤文さんは市場急配センターの二階事務所で，向き合った机で被告発人池田宏美と二人で事務の仕事をしていました。被告発人安田敏によると，「あやちゃん，どうしたん？　顔真っ赤かやじい」と被告発人池田宏美が話しかけということです。

　被告発人池田宏美の供述調書では違った話になっていて，被害者安藤文さんはものすごく嫌そうな顔をし，机の上に渡されたものを置いたままで，机の中に入れておくように話しかけたというような供述になっていたかと思います。もう何年もその供述調書を読んでいませんが。

　そのとき被告発人安田敏は，仕事が終わって自宅に戻ってきたところだと言い，当日は茨城県からレンコンを積んでいたと言い，土浦市内で民家の屋根に大型トラックの後部を引っかけてきたような話を軽い調子で話していました。

　このとき無事，子供が産まれたという話もしていたと思います。出産の数日前に入院していたと話していたと思いますが，12月22日の夜に入院日は聞いていたのかもしれません。金沢市の寺町で，入院費用が高そうな名前の病院でした。

鈴木ホスピタル - Google 検索 https://t.co/1GyENqbX89

鈴木レディスホスピタル：産科・婦人科／外科・消化器内科／小児科／不妊専門外来
https://t.co/QSqlwiSt4s

　あまり記憶に自信はなかったのですが，全国的に他にもありそうだと思っていた病院名が，トップに金沢市寺町を住所にする病院名だったのでこれに間違いはないと思います。

　Googleマップとストリートビューで鈴木レディスホスピタルの場所と建物を見ていたのですが，金沢市内でこれより大きな産婦人科の病院を見たという記憶はありません。

　出産の費用などお金の心配をしているように見えなかったのも気になるところでした。そもそもお金に困っているので50万円の前借りを条件に金沢市場輸送に入社した被告発人安田敏です。ただ翌日から市場急配センターで市内配達の仕事を始めたらしいので金沢市場輸送では仕事をしていないはずです。

**** 被告発人安田敏の妻と，平成14年当時の被告発人安田敏の生活ぶり

　被告発人安田敏は，私に妻の話をしていましたが，名前を柳瀬と言っていたように思います。市場急配センターの市内配達に似たような名前の若者がいたので，余計に印象に残っているのですが，綾瀬だったのかちょっと違っているような気もしてきました。

　金沢市内の諸江に住んでいたとも話していましたが，諸江は国道8号線バイパスにまたがる地域で，金沢市内中心部よりバイパスの向こう側だと言っていたと思います。

　父親と二人暮らしで，その父親がガンで亡くなり，天涯孤独になったような話をしていました。花里のアパートでは，ダブルベッドの足元に同じぐらいの高さの台があったのだと思いますが，その台の上に父親の遺影のような写真がありました。

　厳格そうな父親の写真でしたが，被告発人安田敏は父親が亡くなる前，病院で会って話をしたとも言っていました。私の方から細かいことは聞かなかったのですが，前に小立野の飲み屋の前で別れた後では，そこまで生活が変化する期間があったのかという疑問はありました。

　小立野の飲み屋の前でへたりこみ，私にタクシー代をくれたように思うのですが，かなりすさんだ生活ぶりにも思えました。その飲み屋のマスターのことも過去の書面には記述があるはずです。

　その小立野の飲み屋のマスターと二人で，東京の池袋のサンシャインビルをバックで撮影した写真など，被告発人安田敏は私にいろいろ写真を見せてくれました。

　そのなかには被告発人安田敏の妻となる彼女の写真もあって，職場で数人で写ったものでした。5，6人であったかもしれません。そのうちの一人が知られた曲の歌手と被告発人安田敏は説明をしていたと思います。演歌系です。

　それというのも被告発人安田敏の妻となる彼女の職場が，有線という話でした。有線放送という音楽関係の仕事かと思います。詳しくは知らないですが当時は喫茶店などで，その有線放送の音楽を流していると聞いたことがありました。

　前に同じ有線の仕事をしていると聞いた人がいて，それが配車係から金沢市場輸送の社長になった本恒夫の妻でした。会ったことはないし，顔も記憶にないのですが，本恒夫より年上か，年上に見えるという話を聞いたことがありました。

　実は一度，顔を見ているかもしれない可能性があるのですが，見たかもしれない本恒夫の娘の顔を含め記憶には残っていません。入り江の回転寿司で輪島の運転手が，「なんちゅう食べるおなごかい」と言ったので，隣の席をみると，本恒夫の家族が食事をしていたのです。

　この本恒夫についても過去の提出書面には知る限りのことを記述していますが，竹沢俊寿会長とも特別な関係があり，福井刑務所では暴力団員だったという話も聞いています。富山市内で飲み屋を経営，静岡ではサラ金をやっていたと言います。

　被告発人東渡好信を金沢市場輸送に招いた人物でもあり，被告発人安田敏が金沢市場輸送の入社から市場急配センターで仕事をするようになった経緯にも絡んでいて，以前は，被告発人，被告訴人に加えていたこともありました。

　自分の記憶の衰えもあって，竹沢俊寿会長と本恒夫は被告訴人，被告発人から外したのですが，事件の真相解明には不可欠の人物と当時は考えていました。あのストライキも被告発人東渡好信との出来レースだった可能性があります。

　被告発人安田敏の見せた写真は，石けんでも入っていたような箱に入れたもので，よくある薄い小さなアルバムに入った写真もあったと思いますが，無造作に詰め込んであったような印象も残っています。

　写真の数が多い割には，意図的な選別がされているような印象がありました。私にみせるために用意した写真という感じです。それほど注意深く写真をみていたわけでもなく，あとになってじわじわと気になるようになったという感じでした。

　被告発人安田敏は妻との入籍の時期についても私に話していたかもしれないですが，それも記憶にはありません。ただ子供が産まれてから入籍をするとは考えられず，早産の可能性もあるので，早めの入籍はあったものと考えています。

　被告発人安田敏の妻は，私と初対面の頃から身構えたような様子があり，気迫のようなものが伝わりました。最初に会ったのが平成3年の4月の終わりか5月の初めで，12月22日の夜になるまで，徹底的に顔を隠していました。

　有線で仕事をしていたと被告発人安田敏に話を聞きましたが，出会うようになってから少なくとも毎日は仕事に出かけている様子はなく，一台しかない車で被告発人安田敏の送り迎えなどもしていました。

　私は平成13年12月31日に金沢刑務所を満期出所しました。被告発人安田敏に会ったのは翌年の4月の初めだったと思います。私が近くの電子部品の工場で仕事を始めたのが4月の10日過ぎだったので，その少し前だと思います。

　被告発人安田敏の鵜川の実家の方に電話をすると，七見の町営住宅に住んでいることと電話番号がわかりました。それで電話で最初は話したのだと思いますが，午後に宇出津の私の家に来てもらって直接話をしました。

　偶然なのだと思いますが，その翌日ぐらいに宇出津新港の職業安定所で被告発人安田敏に会いました。高岡市の方に面接に行くとかあるいはそこに仕事が決まって行くことになったと話していました。

　ショッピングタウンともいうアルプの駐車場であったと思うのですが，そこでも被告発人安田敏に会ったように思います。狭い職業安定所の駐車場ではなかったと思うのですが，その日，二度，妻が運転する車を見ていたような気もします。

　かなり古い大型車でした。型式も古く正確なことはわからないですが，これがランドクルーザーという車なのかと思いました。戦車のような大型車で，ずいぶんと燃費が悪そうでした。ちょっと聞いた話ですが，この手の車種は2020年の現在でもずいぶん燃費が悪いようです。

　2，3年前，比較的最近になって知ったのですが，同じ団地のような場所で，住所は鵜川と七見に分かれるようです。その辺りは桜木という町名も昭和の時代から聞いていました。

字七見 - Google マップ https://t.co/5iiShi3reV

　Googleマップで再確認しましたが，住宅地の真ん中辺りで鵜川と七見に分かれています。町営住宅と聞いたこともあるのですが，被告発人安田敏は自分の自宅の住所を七見だと言っていたと思います。告訴か告発をするので，住所を教えてくれと言うと教えてくれました。

　告訴と言ったのか告発と言ったのか私自身がよく憶えていないという意味です。これはどちらもやったと思いますし，どのときどちらにしたのかよく憶えていません。

　被告発人安田敏との会話はそのほとんどをボイスレコーダーに録音し，録音した音声ファイルを再審請求をしていた金沢地方裁判所に提出しています。インターネットでも情報公開をしていました。

　最初は，七見のパーキングに駐車した車内で録音をしたように思います。平成15年の正月前後，年末で正月休みの初めだったかもしれません。ボイスレコーダーはそのしばらく前に購入していました。12月に入ってからだと思います。

　被告発人安田敏は仕事が長続きせず転職を繰り返していたようです。その場その場で条件のよい職場を探していたようですが，これは昭和60年に始まった岐阜県海津町の出稼ぎに始まっているようで，失業保険などの受給とセットにしていました。その生活スタイルが続いていたようです。

　宇出津新港のどこかの駐車場，たぶんアルプの駐車場ですが，離れたところに被告発人安田敏の妻が運転をするランドクルーザーのような大型車がありました。何か強い警戒心と注目が伝わってきたのですが，昨年の秋，二子山でイノシシの親子に遭遇したときの気配に似ていました。

　直接，被告発人安田敏の七見の住宅にも行ったのですが，家の中から妻の声が聞こえ話をしたものの姿は見えなかったように思います。電話でも話をしましたが，警察に相談するようなことを言われ，ずいぶんと警戒した様子でした。

　平成3年の12月に産まれたという子供は女の子でした。そのあと弟が産まれたようですが，この男の子は，七見の被告発人安田敏の家に行ったとき，少し姿を見たような憶えがあります。おとなしそうな男の子でした。

　電話で被告発人安田敏の家の子供と話をしたこともあったのですが，しっかりした感じの声を聞きながら男の子だと思い，時折，坊やと呼びかけながら話をしていたところ，あとで名前を聞くと聞いたことのある長女の名前でした。

　七見の被告発人安田敏の家は，丘の上のような場所の平屋の住宅地で，町営住宅だと思います。かなり古い建物になっていました。生活や豊かに見えなかったですが，あのものすごく燃費の悪そうな車のことは気掛かりでした。

　もっとも平成15年当時は最もガソリンの値段が下がった時期だったかもしれません。金沢市内のガソリンスタンドでは1リッターが80円台になっていましたが，昔も今の奥能登では，それよりかなり割高です。これは灯油も同じで，金沢でポリタンクにまとめて買ってくる人もいます。

　ずいぶんと古い大型車だったので，リッター辺りよく走って3，4キロぐらいという感じでした。鵜川から金沢までは100キロ以上あります。少なめに100キロ，リッター4としても片道25リッターになり，当時の消費税のことはわかりませんが，リッター100円として2500円になります。

　ガソリンが安い時代であったので，それほど負担にならなかったのかもしれないですが，節約とは真逆です。被告発人安田敏は妻が鵜川の角田ストアーでレジのアルバイトをしているか，していたという話もしていました。

　私はその鵜川の角田ストアーの場所を長い間，勘違いしていたのですが，3年ほど前の夕方に店の前にバイクで通りかかったときは，明るい時間でしたが営業していませんでした。たまたま定休日だったのか不明です。

　今，2014年の1月3日から更新がなさそうな宇出津の角田ストアーのFacebookを見たのですが，ついでに安田敏でFacebookの検索をしたところ，4件のアカウントが出てきましたが，被告発人安田敏のアカウントは消えているようです。

　もう3，4年Facebookで被告発人安田敏のアカウントを確認していなかったのですが，それまでは顔写真があったり，矢沢永吉のコンサートの情報がありました。鵜川のにわか祭りの太鼓の写真か動画もあったと思います。

**** 平成5年11月28日付の手書きの書面で見つけて思い出した，被告発人安田敏の追突事故の被告発人東渡好信の口利き

　5月中だと思い込んでいた金沢西警察署刑事課強行主任からの最後の電話ですが，電話があったのが6月4日と，この前，確認して驚いたのです。平成5年11月28日付の手書きの書面を読み出したのもその2，3日前と思います。

　被告発人東渡好信については，平成3年の2，3月になるとほとんど会社で姿を見かけなくなっていたという印象が強く残っていて，何を考えているのかわからない様子で，精神異常者を装う素振りも感じられました。

　そんな被告発人東渡好信を浜上さんが心配をしていたのですが，余り会社に来なくなって，別に仕事を始めるようなことも話していたようです。ある程度，具体性のある仕事内容だったと思いますが，これも今は思い出せない状態です。

　3月のいつ頃かは憶えていないものの，被告発人安田敏が追突事故に遭ったという話をし，示談金をせしめるようなことも話していたと思います。私がその場で，「首を切り落としたら直るぞ」と被告発人安田敏に言ったようなことも少し憶えています。市場急配センターの一階，休憩室でのことでした。

　そういえば，平成5年11月28日付の手書きの書面を読むと，その追突事故の示談金のようなもので，被告発人安田敏が新車を買ったとなっていました。この新車のことはずっと忘れることなく憶えていました。車種も特徴のあった車です。

　この被告発人安田敏の新車のことは，3月でも初めの方だと記憶にあります。150万円で購入したという話でしたが，私に前借りした50万円も満足に返済せず，2月14日の午後には，私が叩き返すような感じで，20万円あるいは25万円を完済したのです。

　もしかすると30万円かもしれないのですが，20万円から30万円の間であったことは確かです。その場で北國銀行中央市場支店に行き，ATMだと思いますが引き下ろしてきました。そして，市場急配センターで被告発人池田宏美に渡したと思うのですが，その場面は余り記憶に残っていません。

　追突事故の相手は女性とも被告発人安田敏は話していたように思います。30歳ぐらいの女性で，ちょうど被告発人安田敏の妻と同じ年頃の女性を想像していました。その妻の年齢も聞いていたと思うのですが，同級生か，それともいくつか年上と聞いたように思います。

　平成4年の3月頃私は27歳だったので，二つ年上で12月生まれという被告発人安田敏は29歳ということになります。そういえば供述調書にも29歳と記載があったように思います。30歳というのが当時の記憶にあるので，妻の年を30歳と聞いていたのかもしれません。

　ただ被告発人安田敏が追突事故でもらったというお金は，30万円か多くて50万円と聞いたように思います。怪我をしている様子などなく仕事をしていたので，100万円など請求すれば，恐喝で警察に相談されていた可能性，リスクもありそうな気がします。

　被告発人安田敏は平成3年の5月から市場急配センターで仕事をしていたはずですが，50万円の前借りをようやく支払うようになったのが12月でした。これは被告発人池田宏美が，心配そうに私に話してきたことで，2階事務所，被害者安藤文さんもその場にいました。

　被告発人安田敏の不可解な言動は，被害者安藤文さんに対しても欺罔の手段として最大限利用されていたはずです。

　市場急配センターの長距離，大型運転手の給料は，固定給で月50万円となっていました。ただ，手取りで40万はもらったことがなかったとも記憶にあり，金沢市場輸送では手取りで43万円もらったことがありました。離婚していたので引かれる税金の額が違っていたことは確かです。

　被告発人安田敏が市場急配センターで本格的に大型車の長距離の仕事を始めたのは10月になると思います。9月中は似たようなこともやっていたはずですが，たぶん長距離に出る回数も少なかったと思います。

　市場急配センターの給料は25日締めの翌月5日払いとなっていたと思います。支払日はよりはっきり憶えているものです。50万円もらえなかったと被告発人安田敏が不満を言っているという話を聞いた憶えがありますが，本人の言い分などは余り憶えていません。

　5月に50万円の前借りをして12月まで全く支払いをしなかったという話ですが，見かねた被告発人池田宏美が被告発人安田敏を説得し，いくらか給料から天引きで返済に充てるという話でした。当時は余り気にしていなかったのですが，会社がそこまで猶予しているのも疑問でした。

　平成4年というのはすでにバブル景気が終わって不景気になったという情報もネットで見かけるのですが，少なくとも石川県の金沢では，景気の後退で仕事が減るような話を聞くことはなかったと思います。

　そのバブル景気ということで，運送の仕事はいくらでもあると言われていたのが平成2年のことですが，同時に運転手不足が深刻で，運送会社の間で運転手の取り合いにもなっており，協定が必要と竹沢俊寿会長が言っていました。月に6休と聞いたのも同じ頃と思います。

　金沢市場輸送では，荷物を積んで運んだ距離数だけだった歩合が，売り上げも計算に入れたものに給料計算の変更がありました。はっきりいってまるっきりわけのわけらないような給料明細になったと思っていました。

　市場急配センターも同じですが，長距離には運行費という食事代が支給され，税金の対象にもならないという話でした。名古屋，大阪の記憶はないですが，関東便だと4千円でした。

　名古屋でも2千円は出ていたような気がしますが，夕方6時か7時に出発をして，夜中の2時頃には空車で戻ることが多かったので，まるまる小遣いのようなものでした。

　運転手の確保ということで被告発人安田敏が甘やかされている可能性も考えていましたが，50万円の固定給というのは条件がよかったので，募集すれば運転手はいつでも充当できそうでした。仕事内容も，他よりだいぶん楽だったと思います。

　名古屋からの空車のときも全線で高速代が出ていました。これはカード払いになるので現金の支払いはありません。有料道路は立替払いでした。金沢市場輸送でも首都高や阪神高速は使用に制限がなかったですが，他の運送会社ではそうでもないという話でした。

　ただ，市場の仕事と言うことで敬遠されがちだったということはあるかと思います。それでも金沢市場輸送の鮮魚のようなことはなく，青果物で市場の仕事をする運送会社は金沢でも普通にありました。

　ただ，私が50万円の前借りの保証人になったことで，被告発人安田敏に支払いをせかすようなことを言わなかったのは，昭和58年の9月の初めから11月10日頃まで，金沢市の観音堂のアパートで世話になったからで，よく食事も食べさせてもらっていました。

　平成5年11月28日付の手書きの書面には，平成4年の3月，市場急配センターの新入運転手の名前が出てくるのですが，名前のことは思い出したものの，どうな人物だったのか思い浮かんで来ないのです。和田君のアパートにも一緒に行ったような話になっていました。

***** 首にギプスのような包帯を巻いていた被告発人安田敏

　追補になりますが，追突事故の話を聞いたとき，被告発人安田敏は首にギプスのような包帯を巻いていました。しかしただの包帯にも包帯にも見えるもので大げさなものではなかったし，本当の首のギプスなら仕事には来ていないと思います。

　そのギプスのような包帯を首に巻いた被告発人安田敏の姿を見たのもたぶん一度だけだったと思います。たぶん会社の階段前で被告発人安田敏が私にベルトを渡そうとしたときより前のことになると思いますし，ベルトのときは首に巻くものはなかったと思います。

　おそらく診断書をとるために病院に行ったのだと思いますが，どこの病院に行ったのか聞いていなかった気がします。

***** 昭和58年，被告発人安田敏が入院していた金沢西病院

　市場急配センターの会社の近くの病院ということで思い出したのですが，国道8号線バイパス藤江陸橋の側に金沢西病院がありました。今年の3月金沢に行ったとき，病院の前を歩いたのですが，建物は新しくなっていました。

　昭和58年当時はかなり古く見える建物の病院でした。目立つ場所にあったので憶えていますが，病院の中に入ったことはありませんし，他に病院の話を聞くこともなかったと思います。

　被告発人安田敏と再会したのは宇出津の先輩の家で，8月の終わりだったと思います。そのときに金沢のアパートに遊びに来るように誘われ，9月に入ってすぐに遊びに行き，そのまま居候のような生活をすることになりました。それが金沢市観音堂のアパートです。

　当時，観音堂には運転免許センターがあり，多くの若者が集まる場所でもありました。金石街道から入ると，左手に運転免許センターがあり，そのまま道沿いに行くと，T字路に突き当たったと思います。

　そのT字路を左折するのも右折するのもよく通った裏道だったのですが，右折すると高畠から金石に行く犀川沿いの道路がちょうど犀川を渡った辺りに出たと思います。そこを右折してすぐの辺りではなかったかと思います。被告発人安田敏には板金屋と聞いたように思います。

　その前を通りかかったと頃に被告発人安田敏が話をしていたのですが，前に仕事をしていた職場で，そこで指を切断するという怪我をし，金沢西病院に入院していたという話でした。指に肉をつけるためお腹に縫合していたとも話していました。

　その大怪我でまとまったお金が入ったらしく，100万円ぐらいと聞いたようにも思います。そのまとまったお金が入ったことで，仕事をせず毎日遊び回っていたところに，私が転がり込むことになったわけです。

　私は大怪我でお金をもらったという経験がないのでよくわからないのですが，この保険金のようなものが被告発人安田敏の成功体験になった可能性はあるかもしれません。岐阜へ出稼ぎに行った後の失業保険についても似たような話をしていました。出稼ぎだと降りるのが早いとか。

*** 被告発人東渡好信

**** 被告発人東渡好信の金沢市場輸送への入社

**** 被告発人東渡好信が主導した金沢市場輸送のストライキ

**** 平成4年3月当時の被告発人東渡好信の不可解な言動

　市場急配センターをやめるという話にもなっていましたが，平成4年4月1日の午後にも市場急配センターの一階で，被告発人東渡好信の姿を見たように思います。

　その数日前の休日にも，市場急配センターの会社の前で，自分の乗用車の洗車をしている姿を見たのですが，なんというのか物思いにふけり，自分の世界に入り込んでいるような様子のおかしさがありました。たぶん演技で打算があったものと考えられます。

　七尾市の丸一運送に行ったときも，会社のだいぶん上のような立場の人に，被告発人東渡好信のことについて心配そうに尋ねられたことがありました。丸一運送は七尾市内の目立たない場所にありましたが，かなり大きな運送会社でした。

七尾・能登を中心に荷物や貨物の配送、貸し倉庫なら丸一運輸！
https://t.co/5mdDRFzXiN

　丸一運送ではなく丸一運輸でした。ホームページの主要取引先に，カナカンと能登ヤクルト販売があるのは以外でした。この2つは食品や飲料を扱う会社にかるからです。3つあるもう一つが林ベニアで，市場急配センターでやった仕事になります。

　七尾市はロシアからの木材の輸入が多いと聞いたことがありますが，木材や製材の取り扱いが多い港というイメージがあって，市場急配センターでは林ベニアの他に能登木材の仕事をしていました。

　Googleマップでは林ベニアの近くに七尾魚市場がみえましたが，七尾市の魚市場というのは仕事に行った憶えがなく，青果物は割と運んだのですが，たぶん魚市場とある場所と同じで，同じ敷地になるのではと考えています。

　七尾市公設卸売市場とは隣接して，別の敷地に魚市場があるらしいとGoogleマップで確認しましたが，小さく見える魚市場で，海の岸壁から離れているのも珍しく思いました。どんたくミートセンターの方が岸壁に近い場所にあります。

　Googleマップをみると，七尾市公設卸売市場に隣接して奥の方に林ベニアがあるのですが，これも意外な初めての発見に感じました。七尾市公設卸売市場は夜中にしか行くことがなかったので気がつかなかったのかもしれません。

　市場急配センターで平成3年の11月の20日頃から和歌山県のかつらぎ農協からミカン，イヨカンを運んだ仕事も丸一運輸の請負でした。必ず七尾おろしで，ほとんどが小松市の市場との2カ所おろしだったと思います。

　私は一度もやることがなかったのですが，愛知県の碧南市から瓦を積んでくる仕事がよくあったらしく，今考えると，それも丸一運輸の仕事だったのかもしれません。

　私はずっと前，たぶん中西運輸商の4トン車だったと思うのですが，七尾市の和倉温泉の近くから赤いレンガのようなものを積んだことがありました。数年前，石崎奉燈祭を見に行ったとき，たぶんその工場の前を通りかかったのですが，イソライトとか書いてあったと思います。

イソライト工業 七尾工場 - Google マップ https://t.co/aksie16eum

　Googleマップでみてもかなり大きな工場です。どこの運送会社が荷物を運んでいるのか気になるところですが，珪藻土資料館というのも見えました。レンガと瓦は同じ原材料ではと考えていたのですが，珪藻土は七輪が有名で珠洲市がよくテレビに出ています。

会社概要 | イソライト工業株式会社 https://t.co/bDO6mXoBqt

　本社が大阪となっていて，「工場
音羽(愛知）・七尾(石川）」とあります。音羽蒲郡というのをどこかで見かけていたように思い出しました。調べると東名高速のインターでしたが，住所が豊川市となっていました。

　「瓦　碧南」とGoogle検索すると，地図にたくさんの工場や会社が出てきました。瓦について調べると日本三大産地が出てきて，その1つが愛知県の西三河地方となっていました。

　市場急配センターでの最後の仕事は，愛知県小牧市からアサヒビールの缶ビールを運んだのですが，前日に碧南市から瓦を積むと指示を受けていて，朝方，碧南市の近くまで行ってから仮眠をとっていました。

　28年も前なので丸一運輸の仕事内容にも変化があるのかもしれず，被告発人東渡好信の知り合いが会社に残っているとも考えにくいところです。平成4年当時で，43か44歳と聞いたことがあったと思うのですが，それなら現在は71，2歳になりそうです。

　被告発人安田敏はトラックで，七尾市のパチンコ店の前まで被告発人東渡好信を迎えに行ったことがあるとも話していました。丸一運輸の会社の近くには国道沿いにパチンコ店があったように思っていたので，その近所に住んでいるのかと考えていました。

　調べたところ，現在七尾市の丸一運輸の付近にパチンコ店はありませんでした。被告発人多田敏明の場合は，家に招かれ食事をしたとも話していましたが，七尾市のどの辺りかは聞いておらず，金沢育ちなので，聞いてもわからないだろうと思っていました。

　他にはっきり憶えているのは，夕方に市場急配センターの一階休憩室に，宇出津のNさんが来て，被告発人東渡好信と浜上さんと親しそうに話をしていたことです。まだ薄明るい時間で，城山運輸のトレーラーが止まっていたと思います。

　その宇出津のNさんとは，金沢市場輸送が1年ほど，守田水産輸送の青森定期便を一日交代でやっていた頃，守田水産輸送の新入運転手として，石巻で一緒になり話をしたことがあったのです。同じ小棚木の町内で，他に知り合いもいる名前で，親戚と聞いたとも思います。

　調べたところ城山運輸は，七尾市大田町の運送会社でした。金沢で見かけることが多く，七尾では余り見かけた憶えがなかったので，金沢の運送会社とも考えていたのですが，城山というのは七尾市でよく聞くような言葉です。宇出津でも遠島山公園のことを城山と呼びます。

　金沢にも城山運輸の支店か営業所があるのかと思ったのですが，検索結果をみるとなさそうです。七尾市の大田は火力発電所で知られた住所ですが，会社はGoogleマップに七尾市公設卸売市場の横となっていました。

　金沢港も湊という住所の辺りが木材の多い場所になります。河北潟の水路が木材の仕事と関連した歴史がありそうです。ちょうど金沢港から河北潟近くのミール工場にイワシを運搬する道路沿いでもあり，木材を積むトラックはよく見かけていました。

　被告発人東渡好信も浜上さんも以前はトレーラーで木材を運んでいたと話していました。和田君も一緒だったと聞きましたが，たぶん金沢の方の運送会社なのだろうと思っていました。

　金沢港で木材を運ぶ運送会社として記憶にあるのは，星崎運輸になるのですが，本社が名古屋の会社で，金沢市場輸送で帰り荷の仕事をしたこともあったと思います。大きな会社に行った憶えがあります。

　金沢市場輸送でイワシの運搬をしていた頃，金沢港のあたりで出会った宇出津のTSさんは，星崎運輸のトレーラーではなく大型車に乗務していたと思います。昭和59年に金沢市場輸送の大型保冷車に乗務していたTSさんです。

　金沢で見た木材を運ぶトレーラーで，会社名をはっきり憶えているのは星崎運輸と城山運輸ぐらいだったように思います。中には個人の持ち込みでやっているような運転手もいたのかもしれないですが，そのあたりはよくわかりません。

　しかし今回，城山運輸が七尾市の運送会社ということがわかったことで，被告発人東渡好信の実態に少し迫れたような気がします。浜上さんや和田君には「さんちゃん」とよく呼ばれていました。

　東渡というのは誰もが呼んでいた名前ですが，東渡好信というフルネームは，市場急配センターの一階休憩室に，火元責任者の札として見ていた名前になります。浜上さんは，さんちゃんと呼ぶ理由を尋ねたが答えてくれませんでした。

　宇出津のNさんを見たのも3月の前半か，あるいは2月の後半かもしれません。そのときも被告発人東渡好信はしっかりした様子で落ち着いていました。

　もう一つ，これも同じ頃の似た状況なのですが，小木港の遠洋漁船の漁師だったという人が，同じような時間，市場急配センターの一階で，被告発人東渡好信と浜上さんと話をしていました。

　その人は前に何度か見たことがあったのですが，いずれも金沢市場輸送に麻雀をしに来ているのを見たものです。被告発人東渡好信を下っ端扱いにするような言動があったので，そのことも気になっていました。年も被告発人東渡好信と同じぐらいです。

　そういえば先ほど書き忘れがあったと思いますが，宇出津のNさんも以前は小木運送で仕事をしていたと話していました。宇出津の漁運会輸送と同じで，普通の社員運転手のシステムではないという話でした。

　珠洲市の若山といっていたSさんは，金沢市場輸送の傭車として小木運送の大型保冷車でよく仕事をしていました。本恒夫社長との関係が強かったようです。しょっちゅう来ていったので，話もしましたが，本恒夫社長の不満を口にすることもなく，いつのニコニコしていました。

　宇出津の漁運会輸送も以前はたくさんのトラックが宇出津の魚市場の周辺にあったのですが，小木運送のトラックもよく見かけていました。余り小木港に行かなくなり，特に組合の辺りには行かなくなったということもありますが，ずいぶん長く小木運送のトラックを見ていない気がします。

　「石川県漁業協同組合　小木支所」のことで，北朝鮮の大和碓違法操業のニュースで建物を見ることも多いのですが，小木の地元では組合と呼ばれているようです。

　その小木港の組合で船凍イカの水揚げがおこなわれるのですが，小木運送のトラックもその駐車場によくとまっていました。もう8年ほど前ですが，アジングでよく西堤防の方に行っていた頃は，そこに七尾市の共栄運輸の保冷車も見かけていました。

　金沢市場輸送に麻雀に来ていた小木の元漁師という人は，運転手をするようには見えなかったのですが，金沢港でイワシの運搬をやっており，被告発人安田繁克に手鉤で追いかけ回されたと話していました。

　そこで被告発人東渡好信と浜上さんがやさしく相づちを打つ感じで，年なのだから若い者にはかなわないなどとなだめていました。しかし理由もきかず，少しも驚かなかったので，これはおかしな話ではないかと思いました。

　被告発人安田繁克が人間関係で上を立てるタイプと思う一方，相手の小木の元漁師が金沢市場輸送で被告発人東渡好信を小馬鹿にしたような態度をとったことも目にしていたので，礼を欠き怒らせることがあったのかと考えるところもありました。

　3月の10日頃だったと思いますが，金沢市場輸送の駐車場で，被告発人安田繁克の車が駐車されているのを見かけたことがありました。車は見かけたのですが姿が見えず，他の誰かの車かトラックに同乗して出かけたのかもしれないとは考えていました。これも工作なのかと思う一方。

　この被告発人安田繁克の車は，当時ずいぶんと珍しい感じの車で特徴があり，前に時間を掛けて車種を調べたことがあったのですが，ようやく見つけたような情報のことも忘れてしまいました。昔のダットサンのような車で，タイヤが大きく車高が高い仕様です。

　その車を初めて見たのは平成4年2月1日の夜なのですが，被告発人安田繁克は，平成3年中にも何度か私の前に姿を見せ，工作活動と思われるような行動をしているのですが，乗ってきた車を見た記憶がありません。

*** 被告発人多田敏明

**** 平成3年12月24日，クリスマスイブの夜の被告発人多田敏明の仕事

　23時から0時の間だったと思います。茨城県古河市の山三青果の荷物の福井中継を被告発人多田敏明が乗務する4トンウィング車に積み替えました。そのときの被告発人多田敏明の表情がとても明るく上機嫌だったのが印象的でした。

　遊び盛りで交友関係も広いという被告発人多田敏明が，クリスマスイブの夜に仕事をさせられて，うれしそうにしているのはとても不自然に思えました。日頃，不機嫌で楽しそうに仕事をする姿など見たことがなかった被告発人多田敏明のことです。

　被告発人多田敏明とは，4トンウィング車に荷物を積み替えることなく，そのまま大型ウィング車に同乗させて，福井の市場におろしに行くことの方が多かったかもしれません。そのときは私の方でも珍しく，さっさと荷物を積み替えて自宅に戻りました。

*** 被告発人浜口卓也

*** 被告発人大網健二

**** 被告発人浜口卓也との関係

***** 浜口邸新築工事のWordファイル

　正確な時期は過去の書面に記載があると思いますが，平成9年の秋頃のことで，冬に近かったかもしれないですが，陽光穏やかな午後のことでした。被告発人大網健二が何か理由をつけ，私に自分が仕事で使っているノートパソコンをあずけたのです。

　彼のノートパソコンのメーカーは忘れてしまいましたが，メビウスというシリーズだったと思います。CDとフロッピーディスクを機器の着脱で使い分けるという仕組みになっていていました。35万円ぐらいで買ったように聞いたと思います。

　ファイルの整理のようなことを頼まれたと思いますが，余り要領を得ない頼みごとでした。当時のパソコンはWindows98ではなかったかと思います。あるいはまだWindows95だったかもしれません。

　ファイルは一般的なドキュメントフォルダの中に保存されていたとも思いますが。仕事で使っている割にはファイルの数が少なすぎると感じました。特定のファイルを目立たせ，私に気づかせるのが目的だったと考えられます。

　その被告発人大網健二が目的にしたと考えられるのが，浜口邸新築工事などとしたファイル名のファイルで，Word文書になっていたと思います。ファイルの中身は見積書のようなものでした。ページ数で長くて2,3枚だったと思います。1ページだったかもしれません。

　大雑把にしか記憶にないですが，全部で4千万円ほどの見積もりで，頭金が1千万円ほどになっていました。場所は金沢市粟崎です。当時，地図で場所を確認することはなかったですが，河北郡内灘町と隣接している一部に海沿いを含む一帯という感覚でした。

　今は記憶が薄れていて正確なことは過去の書面に記述があると思いますが，この時点で，被告発人大網健二とは浜口邸新築工事について会話はしていないかもしれません。被告発人大網健二の方で被告発人浜口卓也にふれる話題は避けていたとも考えられます。

- 877：2020-09-05_11:12:24 ＊ 金沢市粟崎町について
https://hirono-hideki.hatenadiary.jp/entry/2020/09/05/111222

***** 何度も前を通っているのに被告発人大網健二がずっと黙っていた浜口商運のトラック駐車場

　こちらは参考資料の作成から始めたいと思います。住所はぎりぎり金沢市西念町になるのかと思いますが，この金沢市西念も西念と西念町があったり，かなりややこしくなります。

〒920-0024 石川県金沢市西念３丁目１２－２１ - Google マップ
https://t.co/dStaFqdSw2

　建物の情報が出てこないのですが，この場所の駐車場の位置になると思います。記憶よりは側道の道幅が広く感じられます。メインの道路が北安江出雲線となっていますが，ちょうどこのあたりで，諸江方面から金沢中央卸売市場に向い，右折する側道で，信号機はなかったと思います。

　Googleマップでは，すぐ近くに現在も双葉湯がありますが，これが平成11年当時，平成元年当時に共通した場所の目安となります。松浦さんと愛知県瀬戸市のカワムラさんと3人で入浴したのも平成元年の初めになるのではと思います。二人とも入れ墨が体に一杯でした。

双葉湯 - Google マップ https://t.co/4fuYgQIMuw 〒920-0027
石川県金沢市駅西新町１丁目１４－２４

　この双葉湯のすぐ後ろの方には，飛鳥という食堂が平成10年当時もあったはずですが，同じ場所だったのか不明のもののリニューアルされた店舗は，昭和59年当時とほぼ同じ場所だったと思います。ただ，周辺の状況が大きく変わっており，当時の記憶というのも微かに残っているだけです。

　Googleマップでは北安江出雲線とありますが，他に諸江方面から金沢中央卸売市場に向い右折する道路はあったものの，被告発人大網健二は，よくそこを右折していました。右折した左手に更地のような駐車場があり，4ｔ車と2ｔ車のトラックがいつも数台駐車されていました。

　工場出荷時というのか塗装をしないトラックで，これは被告発人浜口卓也が最初に市場急配センターで持ち込みを始めた新車の2ｔ車と同じでした。色は白というよりクリーム色に近かったと思います。通りかかるたびにトラックが数台駐車されているので，多少気にはなっていました。

　その駐車場に駐車されたトラックが，被告発人浜口卓也の浜口商運のトラックだと，被告発人大網健二に聞かされたのはだいぶんあとのことだったと思います。なぜそのタイミングで被告発人大網健二が私に告白のような知らせをやったのか，そのことも気にはなっていました。

　これも過去の記録の書面には，具体的に特定できる時期の記述があるはずですが，今は思い出せなくなっており，関係者KYNの配管工事の現場の辰口庁舎で，被告発人大網健二の兄である関係者OSNと顔を合わすようになったころかとも思います。

　被告発人大網健二はしばらく私の前に姿を見せなかったので，たぶん平成10年11月以降にもなりそうです。このあたりのことも過去の記録の書面には，詳細に記述があるはずです。

　簡単に言って，被告発人大網健二と関係者KYNは，私を精神的にも経済的にも弱らせた状態で，被告発人浜口卓也との関わりや橋渡し役を試みた形跡があります。結果として私はいっさい応じませんでした。

被害者安藤文さんとの関係

*** 私が金沢市場輸送にいた頃

*** 被害者安藤文さんの市場急配センターへの入社時期

　平成2年の4月頃になると思います。金沢市場輸送の事務所で午前中のだいたい決まった時間だけ姿を見かけるようになりました。コンピューターの入力操作に来ているらしく，初めのうちは金沢中央卸売市場の仲買か金沢中央卸売市場の石川丸果の社員と思っていました。

　金沢中央卸売市場の水産部門はウロコ水産と石川中央魚市の2つ売り場がありましたが，青果物の部門は石川丸果の売り場だけでした。その売り場の奥には仲買の店舗がかなりの数ありました。

　水産の鮮魚にも仲買がありましたが，金沢市場輸送や市場急配センターで仕事をすることはほとんどなかったと思います。それに対して，青果物の仲買は，市場急配センターが午前と午後の2便で小口の市内配達をやっていました。

　古い記録には記憶も新しかった当時の詳しい記述があると思いますが，もともとは昭和60年ぐらいに金沢市場輸送，小林運送，石川日通などが運転手とトラックを出しながら始めたもので，金沢市場輸送のトラックと運転手の数が多く，現場の監督者だったのも高田さんでした。

　平成元年の秋だと思いますが，それまで同じ事務所と休憩室だった金沢市場輸送の長距離と市内配達が，市内配達の部門が独立するかたちでできたのが市場急配センターになります。しかししばらくは以前と同様に同じ事務所と休憩室でした。

　平成2年になってからとも思うのですが，あとに市場急配センターの事務所ができる場所は，すべて金沢市場輸送の駐車場で，使わない大型平ボディ車などのトラックが駐車されていました。

　記憶が定かではないですが，イワシの運搬で大型平ボディ車が仕事をしていたのは2月いっぱいとも3月に入っても他の仕事と掛け持ちしながらだらだら続けていたとも思われます。それがいよいよなくなったところで，大型平ボディ車をその駐車場にとめにいきました。

　車での送り迎えがあったと思うのですが，いちおう事務所で配車係をしていたYTと藤田さんの2人がいて私と3人でした。そのときに藤田さんではなかったかと思うのですが，駐車場の一部を中継場にするらしいと言い出したのです。

　いちおう事務所で配車係としたのは，本恒夫社長が配車の仕事を独占し，2人にほとんどなにもさせなかったり，運転手の荷物の積み込みの手伝いなど雑用をさせていたことです。2人は会うたびに本恒夫社長に対する強い不満を口にしていました。

　給料の支払いはあったようで，その給料の不満というのは聞いたことがなかったと思うのですが，中でもよく憶えているのは，YTと藤田さんの2人を同乗させて，七尾市の港の近くにあるスギヨの工場に荷物を積みに行ったことです。

　また別のところに記述をしたいと思いますが，YTは被告発人安田繁克とも関わりがあり，藤田さんは仕事で被告発人松平日出男とも関わりがあったようです。YTが都商事，藤田さんが津幡町の協共運送になります。

　3人で駐車場に行ってから短い間だったと思います。次に同じ場所を通りかかると，その駐車場に事務所の建物ができていたのです。これは金沢市場輸送と市場急配センターの上層部が，堅く秘密を守る情報統制に長けていたことをうかがわせるところと思います。

　おそらくこの市場急配センターの新社屋の完成に合わせて事務員として採用され働き始めたのが被害者安藤文さんになると思います。それまで日中を通して彼女が金沢市場輸送の事務所にいるのを見たことがなかったからです。

　彼女の金沢市場輸送の事務所でのコンピューターのデータ入力は，その後も続きました。ただ，3月に入ってからだと思いますが，出かける時間に変化があって，午前午後を問わず，私が会社にいる時間は，市場急配センターにいて，私が出かけるときに金沢市場輸送に行くようになったようです。

　七尾市に関東行きの荷物を積みに行くのは14時頃だったと思いますが，出発するときに彼女も出かけていくようになりました。これも会社の指示があったのことだと思います。

　金沢市場輸送で被害者安藤文さんの姿を見るようになったのは，もう雪が降ることはないだろうという時期でした。昭和の時代に比べると雪は少なくなっていましたが，それでも4月に入って雪が降ることも一度くらいは普通にありました。

*** 金沢市場輸送で被害者安藤文さんを見かけるようになったのと，入れ替わるように静かにいなくなった元石川県警察の警察官というKKさん

　いなくなる少し前，私には家業を継ぐことになり群馬に帰ることになったとKKさんは話していました。群馬に広大な梅園があって，その管理のような話にも聞こえましたが，父親の健康状態の悪化もありそうな話しぶりだったように思います。

　イワシの運搬の仕事が少なくなってからは，午後に時間を持て余し，KKさんと一緒にバラック小屋のようなラーメン店によく行っていました。そこで昼から焼酎を飲んでご機嫌だったと思うのですが，元警察官で白バイ隊員の行動としては疑問でした。他にも昼から酒を飲む運転手はいなかったと思います。

　細かいことなのでこれまで記述することはなかったかもしれないのですが，そのバラック小屋のようなラーメン店では，下から上の方に太くなる紙コップの形状で，割と大きめ，それが銅でできているような入れ物でKKさんは焼酎を飲んでいました。他に同じような入れ物は見たことがなかったと思います。

　熱燗のように温めたものを飲んでいるのかと思っていたのですが，尋ねるようなことはなく，湯気が出たり，火傷を気にするような飲み方もしていなかったように思います。おばさんにしては若そうな女の人がその店の切り盛りをしていました。

Googleで調べると，焼酎用ロックグラスというのがあるらしく「ステンレスや銅、錫といった金属製のロックグラス」とありました。金沢中央卸売市場の周辺の店は14時前には閉店となるので，金沢市場輸送の頃からそのラーメン店には行っていました。

　客のほとんどがとなりのパチンコオークラの客であったとも思われます。ただ広い道沿いで，後ろのパチンコ店までは少し離れていました。店の前が広くなっていたのか車も駐車がしやすかったように思います。店の名前は見ていないようにも思います。赤いラーメンののれんがあるだけでした。

　そのラーメン店でKKさんは，被告発人松平日出男に対する不満も口にしていました。とにかく酒が入ると明るくなる性格だったので，深刻さは伝わらず，愚痴を言っているだけにも聞こえたのですが，折り合いはよくない感じでした。

　そもそもKKさんは早い段階で金沢市場輸送の大型平ボディ車の運転手から市場急配センターの社員になっていたのですが，被告発人松平日出男と話す姿はほとんど見ていなかったように思います。もっとも被告発人松平日出男が金沢市場輸送の事務所にいることも少なかったです。

　金沢市場輸送の事務所の机で被告発人松平日出男が仕事をしているような姿は見たことがなく，たぶん机もなかったのだと思います。姿を見かけたのは，夕方以降で，休憩室での麻雀が始まる前の集合か，始まってからのことです。

　金沢中央卸売市場での現場のことは被告発人梅野博之に任せているようでもありました。被告発人松平日出男は運転手の経験もなさそうだったので，仕事の内容は右も左も分からなったのかもしれません。

　普通なら会社にいないということは，他に仕事に出ているか，仕事に出てきていないことになるかと思いますが，金沢市場輸送の青果部門の場合は，石川丸果の売り場が現場のようにもなっていたので，そちらにいた可能性は出てくるわけです。

　もっとも運転手が自主的にできる仕事で，私自身，その場で上から指示を受けたという記憶は余りありません。たまに臨時の仕事で荷物を運んでくれということはありました。被告発人梅野博之の場合は，臨時で長距離に出ることもあったようです。

　KKさんですが，最初に北國銀行中央市場支店の前辺りで，大型バイクの話をしたことをよく憶えています。昭和61年の秋とも，昭和62年の春とも思うのですが，年末の忘年会にはその姿を見ていなかったように思います。

　金沢市の繁華街片町で，昭和56年当時，バナナなんとかというディスコがあったビルになります。金沢で初のディスコということで話題にもなっていました。相撲茶屋輪島もあったと思います。食事をしたのが，その後釜の居酒屋になるのかもしれません。一時，大問題になったお店です。

　ディスコはバナナビーチだったかと思います。その左隣のビルとも思うのですが，上の方の階のスナックにも行きました。いわゆる2次会だったのかと思います。Hさんに連れて行かれたように思います。何年か前，少し変わった名前の同姓同名の人が，割と大きな薬物事件の逮捕者に含まれていました。

　Hさんも当時，大型平ボディ車に乗務し，日通カラーの一台で，ダブルマフラーというのをつけていました。同じトラックでもエンジンがV8でないと無意味ともいわれたダブルマフラーになります。トラック野郎の映画でもおなじみの音です。

　KKさんの姿を見るようになった頃にはHさんはいなくなったとも思いますし，KKさんがローカルの仕事をしていると話していたのも，日通カラーの大型平ボディ車の一台だったと思います。高柳の北陸通運の仕事をよくやっているとも話していたような気もします。

　KKさんはあとにダンベで長距離の仕事もしていましたが，長距離にも鮮魚にも抵抗はなさそうでした。新鮮なイワシを運ぶこともありましたが，腐ってヘドロになりつつあるようなイワシを運ぶこともあり，ミールの製品には鮮度はまったく無関係という話でした。

　これはイワシが死んでからの時間と言うよりは，船で運ばれてくる時間に揺られ，水槽内に圧が掛かりイワシが潰れるという話でした。時期が冬場だったので，真夏の鮮魚の仕事よりは，ましに思えることもあった気がします。保冷車の中をきれいにしておかないとけっこうきついことになりました。

　魚の汚れた仕事には抵抗がなさそうでしたが，いつも新品のようなパリッとした作業服を着ているのが印象的でした。市場急配センターの作業服になります。青の深い色に，折り返しのような部分がえんじ色になっていました。被害者安藤文さんも着ているのを見たことがありました。

　金沢市場輸送の事務所で，KKさんと被害者安藤文さんが一緒にいるのは見た憶えがなく，イワシの運搬の仕事が少なくなった頃には，KKさんがコンピューターのデータ入力をろくな手当もなくやらされていると，これもラーメン屋でくだを巻いていたように思います。

　他にできる者がいないともKKさんは私に話していたのですが，誰も扱えないコンピューターを会社の事務所に導入し，KKさんに片手間にやらせていたというのも，今考えると変な話です。身近なものではなかったのではっきりしたことはわからないですが，まだパソコンという言葉はなかったと思います。

　マイコンという言葉はあったかもしれません。50メートル道路沿いにマイコンピルといのがありました。いつ頃できたのか憶えはないですが，平成15年から18年年頃にはよく店に立ち寄って，パソコン関係の買い物をすることもありました。

　KKさんもコンピューターと呼んでいたように思うのですが，画面が小さく黒地に緑色の文字を見たような憶えが少し残っています。まさに電子計算機という感じでした。難易度もさっぱりわからなかったのですが，それなりの教育を受けていないとできそうにはなかったです。

PC-8000シリーズ - Wikipedia https://t.co/sirty99q2j 
種別パーソナルコンピュータ  発売日1979年9月（40年前）[1] 
標準価格168,000円  販売終了日1983年1月[2]  売上台数25万台[2]

　少し調べたのですが，上記のPC-8000シリーズという写真が，モニターのかたちはほぼ記憶通りでした。キーボードはだいぶん違っていると思います。平成9年にパソコンを触るようになったときも，余り変わっていないキーボードの形状だと思いました。

　当時最新のコンピューターだとなんとなく思っていたのですが，今考えると数年前の中古品だったのかもしれません。標準価格168,000円というのもずいぶん安く思えたのですが，Windows95が出てからのパソコンが極端に高くなったのかもしれません。

　そういえば，昭和59年当時，西念町の金沢市場輸送の事務所では，竹沢俊寿社長の夫人が，いつも算盤を弾き続けていました。どうしてもコンピューターを使う必要はなく，気が向いて買ったものを事務所に置いていたのかもしれず，KKさんも遊びの延長のような話しぶりでした。

　どうも当時のコンピューターは高価で，金沢市場輸送が必要性に迫られて買ったという見立てが強すぎたのかもしれません。

　同じ頃になると思いますが，私はPCエンジンというゲーム機に，後でCDロムを合体させるようなゲーム機を5万円台後半で買ったのですが，デザインも斬新なものとなっており，ゲームの性能も高く感じていました。

　KKさんがいなくなって，次にYTと藤田さんが一緒にやめていなくなったのですが，6月の片山津温泉ホテルながやまでの一泊の慰安会には参加をしていました。これはスルメイカの仕事のこともあるので，6月でも下旬になると思われます。

　被害者安藤文さんの参加はなかったですが，その頃には，被害者安藤文さんが市場急配センターの事務員らしいと知っていたと思います。誰に聞いたのか思い出せないですが，少なくとも金沢市場輸送の運転手の間で，被害者安藤文さんが話題になることはなかったです。

　また，その片山津温泉ホテルながやまでの一泊の慰安会の時点では，まだ被告発人浜口卓也が市場急配センターに来ていませんでした。その1，2週間後ぐらいだったと思います。社員ではなく，2トン車の持ち込み運転手としての仕事でした。

*** 市場急配センターへの移転，市内配達の仕事
*** 平成3年9月

**** 平成3年9月中頃，被害者安藤文さんが手伝ってくれた車のフィルム貼り

***** 数日前，被害者安藤文さんの軽四が大倉さんの4トン車にぶつけられた

　大倉さんも金沢市場輸送での麻雀の常連メンバーだったと思います。被告発人安田敏に聞いた話では，群馬県高崎市の国道で事故死したということでした。国道17号線と聞いたように思いますが，高崎市だと国道18号線の可能性もありそうです。

　大倉さんは市場急配センターの社員ではなく，4トン車の持ち込み運転手でした。けっこう箱の大きな4トン車で，家具でも運んでいたようなトラックでした。かなり古く，塗装などはされていなかったように思います。

　被害者安藤文さんの車の後部がぶつけられていたと思います。会社前の駐車場で，駐車スペースは，事務所の建物に向かって右端，これは裏駐車場に入る通路の境になります。

　バックでトラックの後ろをぶつけていましたが，考えられるのは，事務所前での方向転換になります。ぶつけようと思って運転をする人は少ないですが，今考えるとかなり不自然な事故であったとも思えます。昼間で，天候も良かったです。

　大倉さんはぶつけてすぐに，2階の事務所から降りてきたと思う被害者安藤文さんに，「直してやる」といったことを一言言ったように思いますが，不機嫌な感じでした。

　他にも何人か，ぶつけられた被害者安藤文さんの車の後ろの方に集まっていましたが，今は顔ぶれも思い出さなくなっています。後ろのガラスが割れていたように思いますが，大きなへこみのようなものは記憶にありません。

　彼女の車は，軽四のホンダトゥデイで，それが最初のモデルだったと思いますが，新型車を見かける頃に彼女の車も金沢市場輸送の駐車場で見かけるようになったと記憶にあります。平成2年春のことです。

- ホンダ・トゥデイ (自動車) - Wikipedia https://t.co/ETLXXgQOSt
1990年2月23日に、軽自動車の規格変更に合わせマイナーチェンジが行なわれた。全長が100mm延ばされ、合わせてデザインも変更される。エンジンは660ccのE07A型が搭載される。

　ホンダトゥデイについて調べてみました。マイナーチェンジとありますが，「JA2型（1990年-1993年」として，上記のWikipediaのページに写真があるのが，被害者安藤文さんの所有と同型車だったと思われます。

　色は黒で，横の下の方に青色のラインが入っていたと記憶にあります。その場で聞いたような気もするのですが，松任市のホンダで買ったと彼女は話していました。松任市のホンダというのがよくわからなかったのですが，野々市町の明治乳業の前辺りをイメージしていたと記憶にあります。

　今でこそ，Googleマップがありますが，金沢市，石川郡野々市町，松任市の境というのは，車で走っていて，ずいぶんとややこしく感じるものでした。野々市町の向こうが金沢市内になったりします。馬替などです。

- 明治 北陸工場 業務係 - Google マップ https://t.co/taTjlODE0z
〒921-8844 石川県野々市市堀内４丁目１７２

- 新潟運輸 金沢支店 - Google マップ https://t.co/WP5lrJgQuQ 〒921-8842
石川県野々市市徳用１丁目４０

　国道8号線バイパスの松任駅側も一部，野々市市となっていました。新潟運輸の住所を野々市市と確認しました。松任駅に向かう道路の左手に新潟運輸がありますが，昭和63年当時の私の記憶では，反対側の道路右手にありました。

　松任市内でも松任駅周辺というのは余り縁がなくて，仕事以外で行くことはほとんどなかったと思います。ただ，一度，YTの妻と，前妻に頼まれて，待ち合わせか送迎をしたようなことはあったように記憶します。

- Honda Cars 石川 金沢古府店 - Google マップ https://t.co/JmEprwaMiD
〒920-0362 石川県金沢市古府２丁目１２５−１

　ホンダのディラーの名前が思い出せないですが，国道8号線バイパスの松島交差点の近く，野田専光寺線の上記の場所にあったのが，ホンダトゥデイの取扱店で，トゥデイの看板が出ていたと記憶にあります。

- Honda Cars 石川西 白山店 - Google マップ https://t.co/6CDX1SoB3K
〒924-0803 石川県白山市乾町３８−１

　同じ「Honda
Cars」として，白山市内に店舗があります。国道8号線バイパス沿いのようですが，平成4年前の間に，その場所にホンダの店舗があったという記憶はありません。

　気になって松任市内のホンダを調べてみたのも，当初私は，被害者安藤文さんの自宅を松任市内と考えていたからです。遅くとも10月5日の電話では，彼女に質問し，金沢市内の住所を確認しています。

　私の方から横にいた被害者安藤文さんに話しかけたのですが，前から関心のあったスモークフィルムのことでした。彼女は，友達と一緒に貼ったと答えていました。

***** 被告発人多田敏明と津幡のYTの目撃から始まる被害者安藤文さんのフィルム貼りの手伝い

　当日は水曜日で，金沢中央卸売市場が休みとなっていました。盆と正月，そして日曜日以外の休みというのは，そのときが初だったかもしれません。そういうふうに聞いていましたし，7，8月中に水曜日が市場の休みになることはなかったと思います。新制度の始まりです。

　calコマンドでみると，平成3年9月は，11日と18日が水曜日です。今はどちらなのか特定が困難ですが，まだ1階休憩室の建築工事中だったことははっきりしています。一週間か長くて10日ほどの工事だったと思います。

　市場急配センターの市内配達の仕事は朝6時頃からが多かったと思いますが，16時から16時半頃には終わっていたようです。たまに18時頃まで，1階休憩室に残っている社員運転手もいましたが，その1階休憩室もまだできる前のことです。

　ほぼ8月いっぱいまで市内配達の仕事をしていた頃は，やはり16時頃に会社に戻ることが多かったと思いますが，どういう時間差なのかわからないものの，他の運転手の姿をみることは少なく，多数が集まるのは見た憶えがありません。

　まだ金沢市場輸送の休憩室に市場急配センターの市内配達の運転手がいた頃も，帳簿の束を机に置いて，けっこう長い時間，作業日報の作成をしている姿を見かけたものですが，市場急配センターに来てからは余り見かけなかった気がします。

　私自身も同じような受取伝票の帳簿の束を手に作業日報の作成をするようになったのですが，割と単純な作業で時間も掛からなかったと思います。夕方には，そういう会社に人の少ない時間帯がありました。

　当日は朝からそんな夕方の人の少ない時間帯のような状況で，2階の事務所は被告発人池田宏美と被害者安藤文さんの二人だけという様子でした。少し前まで2階の事務所にいて，何か用意をしていたような場面も記憶にあります。

　たしか前日に東京で積み込んできた外果の荷物を荷下ろしして会社に戻りました。直接，被告発人松平日出男に指示を受けたとも記憶にあるのですが，夕方に金沢中央卸売市場まで運ぶ梨の仕事をするように言われました。金沢市内の外れになる舘山です。

- 舘山町 - Google マップ https://t.co/ekrNsh6arY 石川県金沢市

　一度，東力のアパートに戻ったような気がしないでもないのですが，車のスモークフィルムは，数日前に購入済みだったと思います。夕方まで自由な時間ができたので，休日にするつもりだったフィルム貼りを会社ですることにしました。

　たぶん，1階休憩室の工事の関係で，事務所前の駐車場に会社の車は駐車されていなかったのだと思います。工事の業者も仕事には来ていなかったと思います。建築資材が前に置かれ，シートがかぶせてあったような状況は，ぼんやりと記憶に残っています。

　2階の事務所から階段を降りた出入り口の左前で，フィルム貼りを始めました。水道のホースの水を使うのに都合の良い場所であったとも思うのですが，周囲には余裕がありました。

　だいぶん記憶が劣化していると思います。たぶんになりますが，被告発人多田敏明と津幡のYTの2人が2階の事務所から降りてきて，会社前の道路に横付けした4トンウィング車に戻る前に，私に話しかけ，横に座って，少しフィルム貼りの手伝いを始めました。泡のような空気を抜く作業になります。

　けっこう手間と時間の掛かる作業でした。被告発人多田敏明と津幡のYTが横に座ってすぐだったと思いますが，2階の事務所から被害者安藤文さんが降りてきて，黙ったまま横に座って，フィルム貼りの手伝いを始めたのです。

　被告発人多田敏明と津幡YTの2人は，驚いた様子でしたが表情に出すこともなく，それほどではありませんでした。今から大阪府の高槻市の市場に馬鈴薯を運ぶと言っていたので，少しするとトラックに乗り込み出発してきました。

***** 被害者安藤文さんがフィルム貼りの手伝いをしながら交わした会話

　被告発人多田敏明と津幡YTの2人が出発すると，市場急配センターの会社前は，私と被害者安藤文さんの二人だけになりました。彼女は黙ったまま，うつむいて刷毛でフィルムの空気を押し出すような作業をしていましたが，黙っているわけにもいかないので，私から声を掛けました。

　前に何をしていたのかと最初に尋ねたと思います。彼女は，県庁で臨時職員をしていたと答えましたが，初めて知る話ではなかったように思います。

　たぶん，被告発人安田敏から聞いていた話で，そのほとんどを彼は，免停中で，高松コースの市内配達に同乗させていた被告発人多田敏明から聞いていたようです。ほとんどの場合，トッチという前置きがありました。被告発人多田敏明の呼び名です。

　実際の時間がわからないのですが，長く感じる時間でした。目撃者が出たのは，いずれも二回目で，今考えると，午後になっていたような気もします。

　一方で，午後には1階休憩室の工事が始まっていたような記憶もあるのですが，彼女がフィルム貼りを手伝っているときに工事はなかったと思います。

　2回かあるいは3回に分けて，彼女は2階事務所から降りてきて，フィルム貼りを手伝ってくれました。「親のコネや」とも彼女は話していたように思いますが，他の会話の内容がほとんど思い出せなくなっています。

***** 竹沢俊寿会長の目撃

　これはやはり午後になっていたように思うのですが，被害者安藤文さんがフィルム貼りの手伝いをしていたところに，裏駐車場の方から竹沢俊寿会長が一人で歩いてきました。体調が良くないという話もあって，やっと歩いているという感じでした。

　竹沢俊寿会長は，私と被害者安藤文さんが一緒にいるのを見て，ずいぶん驚いた様子でしたが，糖尿病で目が悪くなっているという話もあって，いつも色の濃いサングラスをかけていました。そのまま2階の事務所に上がっていったと思いますが，来た時間帯といい，かなり珍しく感じました。

　他にも竹沢俊寿会長が市場急配センターの二階事務所に来ることはありましたが，夫人が同伴をしていたと思います。12月の中頃にそういうことが1度あって，それとは別に1月中と思いますが，夕方の遅い時間に，1階休憩室にいるところを食事に誘われるようなことがありました。

　会社の建物の横側を竹沢俊寿会長が歩いていたような記憶があります。これは，次のカベヤも同じでした。フィルム貼りの場所を変更した憶えはないですが，マルモ整備のパンチパーマの整備工のときは，2階の事務所に上る階段の出入り口付近でした。

***** 被告発人松平日出男の友人，通称カベヤ（たぶん松岡という名前）の目的と，お前ら夫婦やったんか発言

　被告発人松平日出男の姿を見かけた憶えはないのですが，いつも被告発人松平日出男と二人で行動するカベヤという人物が，一人で市場急配センターに来て，2階の事務所の方に向かっていったのも珍しいことでした。

　カベヤという人物は，いつも細長い鞄のようなものを手に持って，集金に回っているように見えたものです。内装工事の会社の社長で，壁の仕事なのでカベヤと呼ばれているとも聞いていました。被告発人松平日出男とは相当仲が良かったらしく，いつも一緒に行動をしていました。

　そのカベヤも金沢市場輸送での麻雀のメンバーだったと思います。ただ実際に麻雀をする姿というのは余り見ておらず，横で眺めていることが多かったような気もします。誰から聞いたのか憶えていないですが，松岡という名前だと聞いたとも記憶に残っています。

　カベヤという人物は，1月11日の片山津温泉せきや，での新年会にも参加し，宿泊をしていました。

　落ち着いた様子にも感じましたが，私と被害者安藤文さんが二人きりでフィルム貼りをする姿を見て，カベヤという人物は，「お前ら，夫婦やったんか」などと言いました。彼女は，「そんなん見えるけ」とだけ答えていました。

　カベヤという人物も私に妻子がいることは知っていたはずと思うのです。ちょうど被告発人松平日出男とカベヤが金沢市場輸送に麻雀に来る時間帯，私はよく金沢市場輸送の事務所の前で，車に乗ったままの妻子を長い時間待たせていました。

***** マルモ整備のパンチパーマの整備工の目撃

　一番，驚いた表情を見せたのが，このマルモ整備のパンチパーマの整備工になります。それこそ顔が引きつったようにも見えました。金沢市場輸送でもずいぶん長く会っていなかったと思うのですが，市場急配センターに用事があったようです。2階の事務所に上がる様子でした。

　当時は金沢市内と思っていたのですが，今Googleマップで確認すると野々市市二日市町になりそうです。そこに小さな整備工場がありました。簡単な修理とオイル交換を，金沢市場輸送ではマルモ設備でやっていました。

　しかし，金沢市場輸送の物置にドラム缶を置いて，運転手が各自でオイル交換をするようになってからは，ほとんどマルモ設備に行くことはなかったと思います。オイル交換は1万キロで，月に1回半ぐらいの頻度でした。

*** 平成3年10月

**** 平成3年10月12日，無言電話がきっかけで，夜遅く，初めて被害者安藤文さんの自宅に掛けた電話

***** 新車の大型ウィング車3068号の納車

　午後に納車があったと思いますが早めの時間でした。会社からは，当時の石川県石川郡鶴来町（白山市）にある白山比咩神社にお祓いに行くように言われたのですが，近くで済まそうと考えた私は，地図で場所を確認するなどし，石川護国神社に行きました。

　昭和62年4月，金沢市場輸送で新車の大型保冷車7599号に乗務したときは，竹沢俊寿社長夫人に言われ，白山比咩神社にお祓いに行きました。保冷車の後ろの扉の下の方には，白山比咩神社のステッカーを貼っていたと思います。

***** 夕方の暗い時間，2階の事務所から降りてきて，「広野さん，今日どっか走るが？」とたずねた被害者安藤文さん

　10月12日というのは，まだ日の長い時期と思いますが，外はすっかり暗くなっていました。そんな時間まで被害者安藤文さんが会社にいたのも珍しいことです。

　18時半頃かもしれません。会社前の道路に新車の大型ウィング車3068号を横付けした状況で，会社前で私は被告発人安田敏と話をしていました。そこに被害者安藤文さんが2階事務所から降りてきて，私に声をかけたのです。

　明るく弾むような声にも感じたのですが，彼女は私に，「広野さん，今日，どっか走るが？」と尋ねてきました。

　2階事務所は電気がついていましたが，その時間としては珍しいことです。何人か人が残っている様子でした。以前は，そのとき誰がいたのか憶えていたかもしれません。

***** 東力の自宅アパートへの無言電話

　無言電話があったのは，22時頃ではなかったかと思います。間違い電話というのも記憶にないのですが，ほかに無言電話というのはなかったと思います。

　最初に疑ったのは前妻でしたが，その前妻から会社に電話があって，被害者安藤文さんが応対したことも考えられました。

　「広野さん，今日，どっか走るが？」と被害者安藤文さんが私に尋ねてきた真意，目的も気になってきました。被害者安藤文さんの性格から無言電話をすることはないと考えましたが，それもあり得ないことではないのかもしれないという考えももたげてきました。

***** 遅い時間，たぶん22時半頃に掛けた，初めての被害者安藤文さんの自宅への電話

　まず，被害者安藤文さんの家の電話番号を調べたのですが，電話の番号案内で尋ねると，彼女の家の住所に安藤という名前の家は1軒だけだったので，すぐにわかりました。電話番号がわかると，すぐだったと思いますが，思い切って電話を掛けました。

　ちょうど一週間前になる10月5日は，プライベートで初めての被害者安藤文さんとの電話でしたが，私の自宅アパートに掛けてもらった電話でした。自分から彼女の自宅に電話をしたのは，この10月12日が初めてになります。

　22時半より早い時間だったかもしれないですが，22時頃にはなっていたと思います。こんな時間に電話をするのは非常識という思いはありましたが，無言電話のことと，夕方の彼女からの質問のことが頭から離れなかったので，電話をすることに決めました。

　電話口に出たのは被害者安藤文さんの母親でした。明るい感じの応対で，男から娘に電話があったのをとても珍しく感じているような反応が感じられました。驚いた様子だったのは，電話に出た被害者安藤文さんでした。何か手短に一言言うと，階段を駆け上がるような物音が聞こえました。

　けっこう大げさな演技のようにも感じたのですが，物音がやんだ後，ひと呼吸を置く様子で，おもむろに，「はい」などと，私の電話の用件を聞く準備ができたと伝える感じでした。それで夕方の質問のことを尋ねたのですが，会社の誰かに聞いてくるようにいわれた，などと言っていたように思います。

　それが誰なのかも以前は憶えていたと思いますが，運転手の配車をするのは事務所の配車係で，運転手である私本人に確認するのは，もともとおかしな話だったのです。それも普通は，出発しているか，馬鈴薯ならば，そろそろ出発するかという時間帯でのことでした。

　余り憶えてはいないのですが，馬鈴薯のときも，大阪・名古屋方面に向かうのに，遠回りになる金沢東インターから北陸自動車道に乗っていたように思います。福井方面に向かう金沢西インターには台貫場があって，重量オーバーで摘発されるリスクがあったからです。

　用件はすぐに終わったのですが，なにか被害者安藤文さんの方から話しかけがあって，しばらく会話が続いたように思います。23時を過ぎるまで電話の会話が続いたような記憶もあるのですが，これも記憶が鮮明だった時期の記述が正確です。

　無言電話のことも話し，会社に私のことで電話がなかったのか，そのことも尋ねて確認をしたように思います。そういうことは全くないという返事があったと思います。

***** 被害者安藤文さんへの自宅への電話を終えて，すぐに掛かってきた前妻からの電話

　平成3年8月の初めで，1日か2日とずっと思ってきたのですが，今calコマンドで確認すると，その8月の最初の月曜日は8月5日となっていました。

　月曜日の朝には東力のアパートには前妻と子供二人がいて，夕方仕事から戻るといなくなっていたという場面が記憶に残っています。今まで調べて確認しなかったのも不思議ではあるのですが，パソコンでUNIXのcalコマンドが使えなければ，容易に調べることはできなかったと思います。

　前妻からはその後，11月になって2，3度電話があったと記憶にあるのですが，10月中，それも比較的早い段階の10月12日の夜に電話があったことは，無言電話のことで連鎖的に思い出すまで，すっかり忘れていたような気もします。

　まだ23時台だったと思いますが，仕事が終わった後と前妻は言いながら，それまでにも普通に連絡を取り合っていたような感じで話をしていました。日付が変わる0時過ぎまで話をしていたような気もしますが，会話の内容というのも今は思い出せなくなっています。

　記憶に残っているのは，いずれも11月中の電話になると思います。神戸市の湊川神社の話などです。また，11月中にも被害者安藤文さんとの電話と前妻からの電話が，同じ夜にあったような記憶が，今もかすかに残っています。

　偶然の重なりではなかった可能性があるのですが，だとすると手回しをした可能性が高いのが，前妻が電話で相談をしていた可能性も考えられる被告発人大網健二になります。

*** 平成3年11月

**** 10月12日の夜より後，被害者安藤文さんの自宅に掛けた電話

***** 前妻からの電話

　10月の後半というのは余り記憶にないのですが，11月に入って2，3回，前妻からの電話がありました。中でもよく憶えているのは，神戸市の港島に行った運行で，戻った日の夜か，その次の夜に前妻から電話があり，神戸市内に住んでいると話していました。

calコマンドで調べたところ，平成3年11月は13日が第二水曜日になるようです。行きの荷物は大阪府の高槻市の市場行きの馬鈴薯でした。夕方，早めの時間に会社から出発するとき，被告発人東渡好信が被告発人池田宏美の車に乗り込むような場面がありました。

　それまで被告発人松平日出男なども会社に集まっていたのですが，何かただならぬ雰囲気があったものの，今は思い出せなくなっています。水曜日で金沢中央卸売市場の休日でした。たぶん第二水曜日ではなかったかと思います。

　神戸市の港島はポートアイランドとも呼ばれ，昭和59年，金沢市場輸送の4トン保冷車の仕事でちょくちょくと行っていました。「エルヨン」と呼ばれた倉庫で，外果を積み込んでいました。行った先がそのエルヨンだったと思います。

　エルヨンで外果を積んで，たぶんオレンジやレモンだったと思いますが，翌日の午前中に富山県高岡市の市場で荷下ろしをしました。国道8号線で金沢に戻り，金沢東インター近くにあるトラックステーションにトラックを駐め，被告発人大網健二に迎えに来てもらったと思います。

　たぶん，被告発人大網健二に来るまで迎えに来てもらって，彼の自宅の大場町東に行ったと思うのですが，そのあと何をしたのか思い出せなくなっています。一度，彼の自宅に泊まったことがあったのですが，それは2月頃だったように思います。

　前妻からの電話が3回ほど続き，最後に掛かってきた電話で，私はもう電話を掛けてくるなと言いました。かなりショックを受けた様子でしたが，そのあと1月20日まで電話が掛かることはありませんでした。

***** 被害者安藤文さんの自宅に掛けた電話

　10月12日の夜の電話のあと，11月25日までというのは，特に記憶の劣化を感じる期間となっています。その都度，被害者安藤文さんとの間で，思い詰めるところがあって，彼女の自宅に電話をしていたのですが，そのたびに，「あきらめる，気にするな。」と言っていたとも思います。

　いずれも11月に入ってからの電話とも考えていたのですが，10月の後半にも一度，電話を掛けたと，書面に記載していたようなことを少し思い出しました。

　彼女には電話で，「あきらめるので気にしないでくれ。」ということを伝えていたと思います。会社で彼女の気遣いが感じられたからと思います。具体的な事実，出来事が連日のようにありました。やはり根本にあったのは，最初に交際を断れたときの衝撃と不信感が大きなものとなっていました。

***** 別々に振り込んだという銀行の通帳

　これは久しぶりに思い出したように思います。完全に眠っていた記憶ではないですが，とりたてて思い出すことがなかった感じです。たぶん30万円と3万円になっていたと思います。

　しかし，これは平成9年の秋に，北國銀行中央市場支店に直接出向き，調べるなどしたのですが，通帳にそのような記載はなく，納得のいかない思いをしたことがありました。

　私はもともと北國銀行の通帳を持っていて，平成3年の秋に，それとは別に金沢信用金庫の通帳を作った憶えがあり，なぜ何のために作ったのか思い出せないのですが，金石街道沿いのジャスコ若宮店の近くに店舗があって，そこには何度か行った記憶があります。

　ちょうどその頃になるのか，市場急配センターで私の給料を銀行振り込みにするという話があり，それを被告発人池田宏美に頼んだところ，後日，被告発人池田宏美が，「あの子，なんか別々に振り込んだらしいよ」などと私に言ってきたのです。

　給料の銀行振り込みというのは，それまで経験がなかったのですが，時間も掛かり，何度か同じようなことを被告発人池田宏美に言われ，いくらなんでも手間が掛かりすぎではないかといぶかしんだことがありました。

***** 会社での被害者安藤文さん，被告発人池田宏美の「このケーキ，広野さんが文ちゃんのために買ってきてくれてんよ」という発言

　苦手意識もあった銀行の用事を被告発人池田宏美や被害者安藤文さんにやってもらったということもあり，チーズケーキだったと思いますが，買ってきて渡したことがありました。

　16時頃過ぎと思いますが，二階事務所で被告発人池田宏美と二人でいたところ，外から被害者安藤文さんが戻ってきました。すると，被告発人池田宏美が，「これ広野さんが文ちゃんのために買ってきてくれてんよ」などと言い出したのです。

　被害者安藤文さんは，少しはにかみながら満足そうに笑っていて，このときの彼女の表情が，11月25日の夜に，被害者安藤文さんの自宅に電話を掛ける動機形成となりました。

**** 11月25日夜に被害者安藤文さんの自宅に掛けた電話

***** 「広野さん，いくつのとき結婚したん？・・・・今まだいいけど，あと2，3年したら焦るぞいね。」

　このとき初めてだったと思いますが，気後れなく被害者安藤文さんの自宅に電話を掛けることができました。それまでも電話をすると，彼女の方から，「今日どこも走らんかったん？」などと会話をを振ってくれていたのですが，この時は，いきなり思いがけない質問がありました。

　「広野さん，いくつんとき結婚したん？」という質問で，私は，21歳，今の文ちゃんと同じ年と答えたと思います。彼女は，ふーんと前置きをした感じで，「私，早く結婚したいぞいね。いま，まだいいけど後2，3年したら焦るぞいね。」と言いました。

***** 「（好きな人）ダメになったかもしれん。・・・これからはやさしくしてあげようと思っとるげん。」

***** 好意を持たれ迷惑ではないことを確認，この次も自宅に掛けた電話を掛けることの了承


```
**** 11月26日の夕方，遅い時間まで会社2階の事務所に残っていた被害者安藤文さん

***** 午後の割と早い時間からずっと1階休憩室にいた被告発人多田敏明と浜上さん

***** 夕方の，たぶん遅い時間になって，1階休憩室に顔を出した西口君

***** 名古屋・関西方面に出発，南条サービスエリアで落ち合う

```

*** 平成3年12月
*** 平成4年1月

**** 平成4年1月21日の夕方，大型ウィング車3016号での，被害者安藤文さんとの会見

　まず，概要です。1月に入ってからすでに2，3回，裏駐車場で被害者安藤文さんに声を掛け，駐車していた大型ウィング車の助手席に乗ってもらいました。彼女が退社するときのことです。

　私としてはその日と約束したつもりでいました。前回の時，彼女は，「私，今から美容室行かないかん。」と言い，翌日には，それまで見たことのないショートカットヘアーとなっていました。髪が長いのも彼女の特徴で，金沢市場輸送で見かけていた頃は，ポニーテールが多かったと思います。

　彼女の市場急配センターでの退社時間は17時だったと思います。一度だけ5分か10分前に，うつむきながら泣いた様子で，一階休憩室の前を小走りに通り抜けたことがありました。1月25日ことかと思います。

　17時10分頃に帰って行くことが多かったと思いますが，仕事では遅くて17時30分頃までいることがありました。仕事以外では2度ほど，19時を過ぎた時間まで二階事務所にいました。11月26日がその1つです。もう1回は，2月か3月中だったように思いますが，思い出せません。

　19時過ぎまで彼女が市場急配センターの二階事務所にいたのは，金沢市諸江に住むという高校の時からの女友達が迎えに来るのを待つときで，そのまま諸江のKさんの家にお泊まりに行っていたようです。被告発人多田敏明が外泊と言っていたように思います。

　ここでは概要を述べるのでした。当日と約束したつもりでいたのですが，退社の時間が近づくと被害者安藤文さんが渋るようになっていました。この変化は，4月1日の事件当日と同じで，被告発人池田宏美と被告発人梅野博之がよからぬことを吹き込み，彼女を不安にさせたようです。

　この1月21日のことは，被害者安藤文さんから話も聞いておらず，被告発人池田宏美や被告発人梅野博之の関与を確認できないですが，4月1日は金沢西警察署の供述調書があって，確か，注意という言葉で，被害者安藤文さんが私に会うのを引き留めたなどとしております。

　17時を過ぎて外はすっかり暗くなっていました。裏駐車場の方から，市場急配センターの二階事務所の台所の入り口で，電気が明るい窓越しに，そこに鏡があるとは気がつかなかったのですが，鏡があるらしく，その前に立って，櫛で何度もいらだつように髪をすく彼女の姿がありました。

　前日の1月20日に前妻から連絡があり，東力のアパートまで来て，会うことがありました。会うと言っても短い時間で，残した荷物を取りに来るように私が言ったことで，前にタクシーを止めたままタクシーには二人の子供が乗っているとも聞いていました。

　前妻もなにか思い詰めている様子がありました。それが夕方の被害者安藤文さんの態度とも関係しているように思え，私も焦りが出ていたのです。前妻が市場急配センターに電話を掛け，被害者安藤文さんが対応したことは十分に考えられる可能性でした。

　しぶる被害者安藤文さんをやや強引に大型ウィング車3068号の助手席に乗せたのは，早い時間で17時30分頃だと思います。もう少し遅かった気はしますが，18時という時間には近づいていなかったと思います。

　このあと個別に詳細を記述しますが，トラックを発車させ，金沢東インターから北陸自動車道に乗って，一区間先の金沢西インターで降りて，裏道で桜田町の辺りから長田の辺りに出て，市場急配センターの会社に戻りました。

　そういえば，家には当時の金沢市内の地図があったと思うので，道路が確認できるかと思います。その辺りは，新しい道路がいくつもできすぎて，どこがどう変わったのかわからなくなっています。

　実際に走行してみないと時間はわからないのですが，1時間以上とは考えられないので，18時半頃には戻って，被害者安藤文さんと別れたことになります。

　このあと別の項目として取り上げておく予定の被告発人浜口卓也のアパートのことは，会社に戻った後のことになり，裏駐車場に着いてから，30分ほど後には被告発人浜口卓也のアパートに着いていたと思います。

　それから夜中の1時半頃まで，被告発人浜口卓也のアパートにいて，ずっと話をしていたとは考えにくいのです。19時に着いたとすると，6時間半もの間，会話を続けていたことになるからです。一緒にテレビを観ていたようなこともなかったです。

　この辺りの謎も，平成5年11月28日付の手書きの書面を読めばわかることかと思いますが，今はそれをやっていません。現在の記憶のままに書いています。そしてそのあと，次のブログ記事にした，夜中2時頃の電話のことがありました。

- 806：2020-08-19_13:48:57 ア.
平成4年1月21日の夜中2時頃に被害者安藤文さんの自宅に掛けた電話
https://hirono-hideki.hatenadiary.jp/entry/2020/08/19/134847

- 807：2020-08-19_13:54:53 (ア).
夜中2時頃の電話の目撃者は，被告発人東渡好信の紹介で入社した七尾のMさん
https://hirono-hideki.hatenadiary.jp/entry/2020/08/19/135443

- 808：2020-08-19_15:15:10 (イ).
夜中2時頃の電話に，すぐに出た被害者安藤文さん，「殺せ，明日会社行ったら殺されてやるわ
い」と返す https://hirono-hideki.hatenadiary.jp/entry/2020/08/19/151500

- 809：2020-08-19_15:15:47 (ウ).
平成4年1月22日，手に大きなハサミを持つ私に，二階の窓からにらみつけ，呼んだらすぐに降りてくる勢いをみせた被害者安藤文さん
https://hirono-hideki.hatenadiary.jp/entry/2020/08/19/151537

**** 平成4年1月21日の夜中2時頃に被害者安藤文さんの自宅に掛けた電話

　2日ほど前，深澤諭史弁護士のツイートを読んだことで思い出すことがあったのですが，完全に忘れていたわけでもなく，他のことより重視をしていなかったということがあったように思います。

- 794：2020-08-15_17:39:44 ア.
被害者安藤文さんの市場急配センターへの入社時期
https://hirono-hideki.hatenadiary.jp/entry/2020/08/15/173942

- 795：2020-08-15_17:40:28 イ.
金沢市場輸送で被害者安藤文さんを見かけるようになったのと，入れ替わるように静かにいなくなった元石川県警察の警察官というKKさん
https://hirono-hideki.hatenadiary.jp/entry/2020/08/15/174025

　告発状の作成は，上記のブログエントリーを投稿した8月15日依頼になります。このエントリーの辺りで，七尾のMさんについて記述をしていると思います。2月1日の夜のことです。この七尾のMさんのことで，最も印象に残るのが，この1月21日の深夜のことになります。

　夜中の2時頃のこととしてずっと記憶にあるので，正確には1月22日未明となるのですが，1月21日の夜の出来事の続きになるので，1月21日の夜中のこととしておきます。場所は市場急配センターの1階休憩室です。

***** 夜中2時頃の電話の目撃者は，被告発人東渡好信の紹介で入社した七尾のMさん

　七尾のMさんの入社時期は，前に書いていると思います。七尾の共栄運輸にいたという話です。私の知る限りですが，共栄運輸は保冷車ばかりで，鮮魚や小木港の船凍イカなど冷凍物を運んでいたようです。

　七尾のMさんは，おとなしく気さくな感じの人でしたが，会う機会も少なく，仕事では一度も一緒になったことがなかったので，たぶん個人的に会話をしたことはなかったように思います。体は比較的小柄であったように思います。長距離トラック運転手で，よくいそうなタイプの人でした。

　七尾のMさんは1月に入ってからの入社のように思うのですが，4月1日まで仕事が一度も一緒にならなかったのは，今考えると不自然な気もします。被告発人東渡好信とは特に親しそうには見えませんでした。

　古い記録に記述があると思いますが，共栄運輸の運転手が一人，市場急配センターの二階事務所で話をしていたことがありました。3月中だったと思います。話の内容は憶えていませんが，記録に記述をした当時は，憶えていることもあったように思います。

　ちょうど，被告発人松平日出男が，2階の事務所で，私と，被害者安藤文さんと被告発人池田宏美に出前のうどんを振る舞った頃のことです。全部で3回はあったと思います。私はいつも，稲荷うどん」を注文していました。

　うどんを注文したのは，被告発人池田宏美と被害者安藤文さんに合わせたからです。高速道路のパーキングエリア以外で，うどんを食べることは滅多になく，高速道路では天玉うどん，福岡県や山口県のパーキングエリアでは，肉玉うどんがほとんどでした。

　山口県では，湯田パーキングエリアと，下関市の近くの王司パーキングエリアによく入りました。中西運輸商では，佐川急便の仕事で，広島県の七塚原サービスエリアと，王司パーキングエリアが，途中連絡の場所に指定されていました。

　出前は，たぶん「加登長」だったと思います。金沢市内にいくつかある食堂で，他に店を見かけることはあったのですが，市場急配センターの会社の近くには見たことがなく，どこの店から出前を届けているのか気になっていました。岡持に名前を見たのだと思います。

　七尾のMさんは，よく一階休憩室に泊まっているようでしたが，見かけた回数は多くなく2，3回か3，4回だと思います。市場急配センターは長距離でも運行が短いので，夜中に会社に戻ることは多くありました。

　金沢市場輸送だと同じ会社の運転手同士でも半年ぐらい顔を合わせないことがあるといわれることがあったぐらいなので，市場急配センターだと一日おき以上に夜中に会社に戻っているような感覚もありました。名古屋に馬鈴薯だとほとんどが日帰りでした。夕方に出て夜中に戻る。

　市場急配センターの長距離では，運転手の間で仕事内容にずいぶん違いがあったようです。それも金沢市場輸送とは違い，他の運転手の仕事が確認できないものでした。

　金沢市場輸送の場合は，表になった黒板に，すべての運転手の運行がチョークで書かれていました。市場急配センターではそれがなかったのですが，一度，二階事務所で，大きな紙に書いたものを見せられたことはありました。

　市場急配センターでは3，4人ほどの運転手が強く仕事の選り好みをしていたようです。誰とは書かないですが，被告発人東渡好信もその一人だったようです。11月中には運転手をしなくなった被告発人東渡好信ですが，その後は配車係やミールの積み込みをやっていたようです。

　ちょうど電話を終える頃のタイミングだったと思いますが，少し離れた間隔で七尾のMさんが電話をする私の横を歩いて行きました。戻ってきたタイミングとは考えにくいので，中から外に出たのだと思います。驚いた様子と言うより，笑った感じでしたが，微笑ましい感じでした。

***** 夜中2時頃の電話に，すぐに出た被害者安藤文さん，「殺せ，明日会社行ったら殺されてやるわい」と返す

　それは，金沢市南新保の被告発人浜口卓也のアパートから戻った後の電話でした。古い記録の書面などでは，午前1時半頃と記述をしていたようにも思います。今考えると，そんな遅い時間まで被告発人浜口卓也のアパートにいたのが不思議なのですが，30分以上の間はなかったと思います。

　今では記憶が薄れてしまっているので前後の憶えている範囲からの推測になるのですが，大型トラックのなかで寝ようとしたところ寝付けず，電話を掛けることを思いついたのだと思います。はっきりしていることは，被害者安藤文さんが出るとは思わず，両親が出て，両親と話すつもりでの電話でした。

　それまでに何度も掛けていた被害者安藤文さん宅への電話ですが，彼女の母親が彼女に電話を取り次ぐとき，彼女が電話に出るまでけっこう時間の掛かることがあり，電話口から聞こえる物音を含めてのことですが，けっこう広い家なのかと考えることがありました。

　彼女の方で，私から電話が掛かるとは思っていなかったと思うのですが，2コールぐらいで出たように思います。それもずいぶん落ち着いていました。ずいぶん思い悩んでいる様子でもありました。彼女が電話に出たとき，何か言ったのか，言った言葉も今は思い出せません。

　何か一言，彼女の言葉があったのかもしれないですが，私はすぐに，「お前，人おちょくるがもいい加減にしとけや，しまいにゃたった殺すぞ」というようなことを，叩きつけるように大きな声を言いました。

　それに対して彼女が返した言葉が，「殺せ，明日会社行ったら殺されてやるわい」になります。そのあとに私が何を言ったのか，思い出せないですが，何か一言言って，すぐに電話を切ったと思います。

　言葉選びや表現が難しいのですが，彼女は思い詰めたような腹をくくったような様子で，これはその夜，裏駐車場で私のトラックから降りた彼女の別れ際の様子によく似ていました。

***** 平成4年1月22日，手に大きなハサミを持つ私に，二階の窓からにらみつけ，呼んだらすぐに降りてくる勢いをみせた被害者安藤文さん

　このハサミのことで思い出したのですが，東京の池袋の三越デパートで，大型ウィング車の最後尾上部のシートを少し破ったのは，1月13日月曜日になるようです。夜に引っ掛けたという記憶だったので，1月終わり頃の展示会の引き上げの時と思っていました。

　しかし，前から思っていたのですが，1月13日から1月29日辺りまでの物産展の展示会というのは期間が長すぎるように思えてなりません。持って行くのと引き上げるのが一緒になった展示会は，他にも少しありましたが，長くて一週間か10日ぐらいだったと思います。

　この池袋の三越デパートの運行は，どちらもとても印象に残る運行で，憶えていることが多いです。1月13日の方が日付ははっきりしていて，1月12日土曜日，片山津温泉のせきや，での一泊の新年会の翌日でした。

　池袋の三越デパートで1月13日に荷下ろしをした状況は記憶にないのですが，広い道路をしばらく走り，見つけた公衆電話から会社に電話を掛けたことをよく憶えています。被害者安藤文さんが出て，安堵するような会話でした。朝でも早い時間だったと印象にあります。

　夜中の比較的早い時間に池袋に着いた頃は，それまでトラックの中でTHE BLUE
HEARTSの「心の救急車」という曲をそのときの気分で繰り返し聴いていました。

　やはり夜に，シートを引っ掛けたと記憶にあります。三越デパートの建物の横の駐車場のようなところで，料金所のゲートのようなものがあり，ギリギリ少し引っ掛けたような感じだったのです。少し嫌な気はしたのですが，確認することはなかったと思います。

　そもそも大型ウィング車の屋根の上に，シートの部分があるとは知らなかったように思います。1，2日か2，3日して，少し雨漏りがしたことで，シートが少し破けていたことに気がついたのです。

　なお，いつもくぐれている高さでも，荷物の重量が荷台の前の方に偏ると，後ろが跳ね上がるかたちで高くなってしまいます。前の方は，余裕をもってくぐれても，後ろが危ないことになります。

　トラックの高さは車検で3.8メートルが上限です。市場急配センターもウィング車も上限の3.8メートルではなかったと思いますが，3.7ぐらいはあったと思います。

　破れを発見した当日ではなかったと思いますが，次の運行から戻った辺りで，当時は河北郡津幡町と金沢市森本の境辺り，国道157号線沿いにあった日野自動車にトラックを持って行き，修理を頼んだと記憶にあります。

　そのときかどうかはっきりしませんが，その頃，日野自動車の前の公衆電話から会社に電話を掛け，被害者安藤文さんを食事に誘ったことがありました。あえてラーメンと言ったのですが，彼女は，「いける，いけるけど，今日はいけん」と答えていました。

　金沢弁になると思いますが，「行ってもいいけど，今日はいけない」という意味になります。ちなみに，能登でも宇出津の辺りだと，「行かれるけど，今日は行かれん」になるかと思います。

　1月21日も22日も雨や雪は降っていなかったと思います。あるいはウィング車の荷台の中から小さな穴で外が見えたことで，シートに破れに気がついたのかもしれません。荷物が濡れたという記憶はなく，その可能性が高そうに思います。

　私は，市場急配センターの事務所の二階の窓に，トラックの後ろをギリギリにつけ，二階の窓からウィング車の箱の上に降りて作業をしたような憶えがあり，それだと事務所前になります。

　私の記憶にある場面は，事務所の後ろ側です。被害者安藤文さんも事務所の後ろ側の窓から顔を見せていました。私はその下にいて，手に大きなハサミを持っていました。応急処置で，ハサミで切った何かを，破れたシートに貼り付けようとしていたのです。これはトラックの上の高い位置ではありません。

　そういえば，思い出したのですが，その直前に，二階事務所を出るとき，ドアを軽く蹴ったつもりが，つま先が鉄板の安全靴だったため，軽くへこむか穴が開くことがあったのです。そのまま下に降りて，事務所の裏側に行ったところ，被害者安藤文さんが窓から顔を出していたのです。

　裏駐車場に駐車したトラックの中にハサミで切って使う材料があって，二階事務所で大きなハサミを借りて，トラックに戻るタイミングだったのだと思います。

　なお，安全靴は，12月の10日頃，羽咋市の平鍛造に山形県天童市ではなかったかと思いますが，その山形行きの荷物を積みに行くときに，安全靴が必須ということで，津幡町辺りの城西運輸の事務所に立ち寄って借りたものでした。

　被告発人松平日出男が返さなくていい，と行ったのでそのまま履いていたのですが，その城西運輸のたぶん配車係とはずいぶん親しそうな関係でした。建築現場でのクレーン車も多い城西運輸ですが，建設関係の運送業では，金沢では独占状態にも思えるような大きな会社でした。

**** 1月25日の夜に被害者安藤文さんの家に掛けた電話と，翌日か翌々日辺りの津幡町能瀬からの電話

***** 1月25日の夕方，小走りで涙を拭う仕草で退社

　この1月25日のことは夕方16時ぐらいからのことしか記憶にないのですが，珍しく早めの時間から暇を持て余し，被告発人安田敏が2階事務所のコピー機で1万円札をコピーしていたのを憶えています。

　被害者安藤文さんの退社時刻は17時でしたが，だいたい17時10分頃の退社が多かったように思います。定時前に彼女が退社する姿を見たのは，その1月25日だけでした。

　17時の定時の5分か10分前でした。彼女が涙を流す様子で，うつむきながら小走りに1階休憩室の前を通り抜けて行きました。手で涙を拭うような姿もあったように思うのですが，あるいは勘違いかもしれません。

　1月22日に，大きなハサミのことがありましたが，それから25日の午後まで，ぶっ通しのような仕事になって，市場急配センターの会社には顔を出していなかったと思います。ミールを積んで三重県の四日市市に2,3往復するという運行もありました。

　1月25日，被害者安藤文さんはいつもと違った服装でした。セーターを着ていたように思いますし，色は黒だったように思います。首にネックレスが掛かっていたのですが，私がクリスマスに贈ったものとは，長さが違うように感じました。

　このネックレスのことは，谷内孝志警部補が作成した供述調書で，読んだ憶えがあるのですが，母親が被害者安藤文さんにせがまれて買い与えた，というような話になっていました。

　谷内孝志警部補は，このネックレスのことをけっこう重視している様子でした。交際が嫌だから受け取らなかった，というような解釈です。ここで思い出したことがあります。3月5日の電話で，ネックレスのことを直接，彼女に尋ねました。

　ネックレスは金色で，私が贈ったものと同じ色でしたが，黒い服にずいぶんと目立っていました。彼女が身につけていたものが長めだったかもしれません。買ったとき，この長さで首に巻けるのかと，不思議に思ったような記憶があります。

　被害者安藤文さんが私のことで会社で泣き出したという話は，他にも聞くことがありましたが，しばらく前，2階事務所でネックレスと一緒に姿を見たときは，割合，落ち着いて見えました。

***** 1月25日の夜，被害者安藤文さんの自宅に掛けた電話

　これも前に別のところで記述をしていると思いますが，時系列でまとめておきます。退社する時の思い詰めた彼女の様子が気になり，自宅に電話をしました。1月12日以来になると思いますが，その時は彼女本人が電話に出ました。

　1月に入ってからも初めの頃に彼女の自宅に電話を掛けたと思います。本当は年内に彼女との関係のけりをつけたいという思いがあり，年末の方にいくらか集中して電話を掛けたのですが，これは出る気がなさそうだと思いました。

　年末年始ともに母親が電話に出ました。母親以外が電話に出たのは，兄が1,2回，父親が2回になります。兄が出た電話というのは思い出せなくなっていますが，一度目は12月中であったように思います。

　年末年始の電話は，不思議なほど母親の対応が普通でした。いくらか好意的だったとも思います。12月24日の夜には，赤いバラの花を10本，自宅に届けているので，母親もそれを知っている可能性が高いと思っていたからです。

　しかし，一度だけ，母親が電話口で警戒感を示すような対応をしたことがあり，それが，この1月25日の夜の電話だったと思うのです。そのあと2月の半ば過ぎにも彼女の自宅に電話を掛けたと記憶にあるのですが，父親が2回目に電話に出ました。

***** 被害者安藤文さんと少し話をした津幡町能瀬からの電話

　被告発人梅野博之と被告発人池田宏美が邪魔をしてなかなか電話に出てくれなかった被害者安藤文さんだと思うのですが，ようやく電話に出たときも，不機嫌というのか，私に対して強い不満がありそうな態度でした。

　例えば，「はあ～ん」ってな感じで，強い不満を表現した被害者安藤文さんでしたが，具体的な言葉は今，思い出せないでいます。その態度もあり，私は反射的に次のように彼女に申し向けました。

　「俺，田舎もんやし，文ちゃん，何考えとるかわからんし，これ以上かかわっとったら文ちゃん傷つけてしまいそうやし，諦めるわ」というようなことを言いました。それに対する被害者安藤文さんの反応も，今現在思い出せないところですが，わざとらしいような怒り方でした。

*** 平成4年2月

*** 平成4年3月

**** 平成4年3月23日の夜，被害者安藤文さんの自宅に掛けた電話

***** 最初に被害者安藤文さんの方から掛けてもらった電話

　この夜の電話のことを，私はずっと夜の22時台で遅い時間だったと考えていたと思うのですが，最初に被害者安藤文さんの方から掛けてもらったことを考えると，私の方で時間指定をしていて20時の可能性が高いと思えてきました。

　この3月23日は，午後だったように思いますが，金石街道沿いの喫茶店で，被告発人松平日出男と被害者安藤文さんの3人で話をしています。その場で，夜に電話を掛けてくれるように頼んだとも思います。

　6月の初めになると思いますが，平成5年11月28日付の手書きの書面を部分的に読んでいたところ，3月23日の夜の電話と，3月5日の夜の電話で，記憶が混同しているように思われる箇所がありました。

　3月5日の夜の電話は，長い通話時間ではなかったと思いますが，現在憶えていることも少なくなっています。

　市場急配センターの会社にいる被害者安藤文さんに電話を掛け，夜に私の自宅アパートに電話を掛けてもらったのは3回だったと思います。10月5日，3月5日，そして3月23日ですが，前述の通り，喫茶店で彼女に口頭で伝えた可能性もあります。

　喫茶店にいるときの彼女は，うなずくような返事以外に言葉はなかったと思いますが，感情を抑えているようにも見えました。電話に出た被害者安藤文さんは，そこ堰が切れたかのように，勢いよく次のように話し出しました。

　「私，広野さんに私の気持ち伝わっとるとばっかり思うとった。」

　それに対して私は，ちょっとふざけたような声で，「なんやそれ？」と言い返しました。逆上というほどではなかったですが，やや感情を高ぶらせ，彼女は次のように言いました。

　「私，広野さんとつきあう気持ちないってこと。好きな人おるって，付きあっとる人おるってこととおんなじことやろ」

　あとで冷静に考えれば，違った解釈というか受け取り方もできたと思うのですが，そのあとの私の言葉で，彼女はすすり泣きを始めることになります。

　ただ，これは私がかけ直した後の会話になると思います。そのまましばらく時間が過ぎ，一度，彼女の母親が電話口に出る感じで，「いつまで話とるが」と軽く注意をするようなことを言い，私の方から電話を切るまで通話が続いたはずです。

　彼女の家の電話は，当時最新に近い電話機で，ワイヤレスの子機があったようです。直接見ていないので想像と推測になりますが，10月12日の電話では，彼女が電話機をもったまま会談を駆け上るような物音が聞こえていました。

***** 出先の金沢市久安から掛けているという被害者安藤文さん，両親と話をするつもりで自宅に掛け直すと，すぐに彼女が出た

　昭和の時代のバラエティのようなテレビドラマで，夜に屋根の物干し台のような場面が決まって出てきたと記憶にあったのですが，車が通過する物音も聞こえていたので，彼女はベランダのような物干し台で，外から電話を掛けている様子が感じられていました。

　車が通行する音から外には間違いないと思ったので，どこにいるのかと彼女に確認しました。彼女は久安にいると，答えたと思います。彼女の自宅があると聞く住所から比較的近くには思いましたが，信号待ちもあるので車で5分程度はありそうに思いました。

　彼女が自宅ではなく外にいるということを知ったので，この機会に彼女の自宅に電話を掛け，両親に彼女の不可解な言動について説明し，親としての指導監督を促すつもりでした。

　平成5年11月28日付の手書きの書面では，この久安のことを3月5日の出来事のように書いてあったと思うのです。外にいるはずの彼女が自宅の電話に出たのは驚きでしたが，先日記述を済ませたところの，1月21日深夜の電話でも，午前2時頃に彼女が出ました。

***** 3月28日夜の電話で印象的なのは，電話口に時代劇のテレビドラマの音声が聞こえていたこと

　まだ一月は経っていないと思いますが，宇出津の図書館で平成4年3月の北國新聞縮小版のテレビ欄を調べてきました。今確認はしていないので，やや記憶が不確かともなっているのですが，20時からの放送ということはよく憶えていて，ドラマは「大岡越前」だったと思います。

　ずっと長い間，22時台の電話で，22時台に放送のテレビの時代劇という感覚でいました。今では年に数回しか見かけることがなくなった時代劇ですが，平成4年当時はまだ数が多かったと思います。

　平成4年当時より少し前の年代になるかもしれないですが，たぶん日曜夜10台の放送として，印象深く記憶にあるのが，「必殺仕事人」になります。2ヶ月ほど前になるのか，今年は夏に近い時期に年に一度と思われる放送をみました。「必殺仕事人2020」となっていたと思います。

***** 3月23日の夜の電話，のんきのも思えた被害者安藤文さんの母親の声

　さきほど考えていたのですが，他の電話機からの割り込みの声であったように思えます。被害者安藤文さんは，ずっとすすり泣く様子で，ほとんど話しませんでした。

　「彼氏おるんやったら，彼氏だけにしておけや，ほんでいいやろ」などと，私は何度も彼女に確認を求めていたのですが，彼女は答えることなく，その繰り返しのときに母親の声が聞こえたと思います。そして，もう一度ぐらい同じ問いを繰り返し，返事がなかったので電話を切りました。

　当時の最新の電話機の機能は，よくわからないのですが，市場急配センターの会社の電話も新しいもので，2階の事務所と1階休憩室の間の電話機で通話ができました。専用のダイヤルがあったとも思います。

　2階の事務所は電話機が少なくとも被告発人池田宏美，被害者安藤文さんの机にあって，たぶん被告発人松平日出男の机にもあって，被告発人梅野博之の机にもあったと思うのですが，電話番号は1つだけでした。

　その割に話し中というのが余り記憶になく，1つの電話番号で一度に複数の通話ができたのか不明です。1階休憩室の電話は，余り鳴ることがなかったとも思います。

　その1階休憩室の電話で，唯一外部からの電話で，電話を取ったと記憶にあるのは，3月の最後の日曜日の午前中，被告発人安田敏に掛かってきた女性の電話でした。顔を合わせても話はしていなかったと思いますが，その場で被告発人安田敏と二人だけで居合わせたのも気になる偶然です。

　電話口で娘がすすり泣いているのに，母親が側にいて動揺しないというのもおかしなことと思っていました。すでにその前の電話で，彼女の母親が私に対して，警戒感を示す態度を見せることがありました。1月25日かと思います。

　2月の半ば過ぎにも一度，被害者安藤文さんの自宅に電話をしていると思うのですが，そのときは1月21日の夜以来，2度目に父親が出て，このときは被害者安藤文さんに対して，怪訝を向けた様子で，電話に出るのか確認をしている様子が伝わりました。

　平成5年の5月か6月と思う，控訴審で，判決前最後となった審理で，被害者安藤文さんの母親と思われる女性の姿をみました。出入り口前の一番後ろの席で，安藤健次郎さんと一緒に座り，ずっとうつむいたまま泣き続けている様子でした。

　たぶん，被告発人小島裕史裁判長は，その審理の公判で結審をする腹づもりだったとも考えられるのですが，次回判決という告知はありませんでした。

　その3月23日の夜の電話は，それほど長くなっていなかったと思うのですが，11月25日の夜の電話か，10月12日の電話がかなりの長電話となっていました。やはり10月12日だと思います。それも遅い時間に掛けた電話でした。私の自宅アパートに掛かった無言電話がきっかけです。

　彼女の母親の声は，「いつまで話とるがぁ」でしたが，不満をぶつけたものの優しい声でした。なにか他に電話が掛かるとか，そういう用事があったのかもしれません。

　そういえば，一度，彼女の自宅の電話で，会話中に他から電話が掛かり，切り替えをするような話が出たかもしれません。これはずっと眠っていた記憶で，それも曖昧模糊としています。

***** 今から東力2丁目の自宅アパートに来るようにいうと，「行ける，行けるけど，今日は行けん」と答え，理由を問い詰めると「怖い」と答えた

　彼女の生活ぶりというのは，実際よくわかっていなかったのですが，2月中に，小杉インターと富山インターの間にある呉羽パーキングエリアから掛けた電話での，彼女の二面性を強く印象づける言葉が大きくありました。

　彼女の反応を試すという目的で，「お前，今から俺のアパートに来い。一発やらせるか，土下座をせい」などと申し向けたのです。これも繰り返し問いただしたのだと思いますが，時間が経ってから「行ける，行けるけど，今日は行けん」と彼女は答えました。

　そして理由をたずねると，これも時間をおいて「怖い」と答えました。私は，「怖くさせたん，お前やろ，怖けりゃこんでいいわい。彼氏おるんやったら彼氏だけにしておけや。彼氏かわいそうやろ。」などと説教をする感じでいいました。

　私は彼女と関わることで，危機感を募らせるようになっていました。一方で，私がこの電話で終わりにするという趣旨の「ほんでいいやろ」という確認に対して，彼女は最後まで返事をしなかったことで，やはり彼女のいう彼氏が，最初から自分のことなのかとも考えました。

**** 平成4年3月23日の夜の電話を終えてから同年4月1日の傷害・準強姦の日を迎えるまでの状況

　3月24日から3月31日になりますが，4月1日の午前中までは，彼女との関係がそれまでになく良好で穏やかだったと思います。3月23日の喫茶店でも，彼女は何か反省をしたような様子でした。紺色で地味目のよそ行きの高そうな服を着ていたことも印象的でした。

　平成5年11月28日付の手書きの書面を見れば細かく確認できることもあるのですが，今は自分の記憶のまま，わかる範囲のことを記述していきます。この間に運行は3回あったと思います。

　3月29日が日曜日だとcalコマンドで確認しました。土曜日の夜は関係者KYNの黒田二丁目のマンションに遊びに行き，そのまま朝まで寝ていました。起きたとき仕事に出たと聞いたので，すぐに出て自宅アパートに戻りました。

　calコマンドのカレンダーをみると，24日から26日の運行，26日から28日の土曜日までの運行，休み明けの30日から4月1日までの運行があったものとわかります。

　26日の運行というのが，今ひとつ記憶がはっきりしないのですが，浜上さんと高岡市の中越パルプ工業で荷物を積み込み，昼の明るい時間に有磯海サービスエリアで一緒に食事をしたのが，この運行の時になるのかと思われます。

　とりわけ印象に残るのが，24日に出発したと思われる加賀市から宇都宮市への運行でした。

　3月30日に出発した市場急配センターで最後となった運行は，行きの荷物の記憶はないものの，茨城県古河市の山三青果に着いてからのことは，割合鮮明に記憶に残っています。そこで4月1日に，夕方仕事が終わってから会うという約束を電話でしました。

***** 加賀市大聖寺の大同工業から栃木県宇都宮市に荷物を運んだ運行

　大同工業はオートバイのチェーンで有名なメーカーでしたが，最初に加賀市の会社だと知ったのも驚きでした。昭和60年に中西運輸商の仕事で初めて行き，熊本県の阿蘇山の麓のような場所まで荷物を運んだのも印象的によく憶えています。

　前にネットで調べたところ，正確には大聖寺ではなく，加賀市熊坂が住所になるのかもしれません。ただ，私の記憶では大聖寺の町中にありました。

　加賀温泉郷の片山津温泉，山中温泉，山城温泉に比べ，知名度は低そうですが，市役所もある加賀市の中心部が大聖寺と聞きます。大聖寺藩という藩政の歴史もあるようです。

　昭和20年代，戦争中の軍事工場のように見えたのも印象的な大きな工場でした。古い建物に見えたので，実際に軍事工場として使われた歴史もあったのかもしれません。石川製作所では，爆弾や魚雷の荷物を金沢市場輸送に続き，市場急配センターでも運んでいました。

　この運行の時は珍しく，市場急配センターの会社に立ち寄らないで，そのまま宇都宮市に向かったと思います。会社では事前に運行費をもらうのがいつものことだったと思います。加賀市に荷物を積みに行くときにもらっていたのかもしれません。

　宇都宮市でのこともいくつか少し記憶に残っています。会社の名前が政治団体のようだったので印象に残っていたというのもあります。平成5年11月28日付の手書きの書面でもその会社名が出てきて，少し驚いたのですが，そのしばらく前にネットの検索で社名は探し出していました。

　昼に宇都宮市内の書店に立ち寄り，恋愛の本を手に取って少し読んだことはよく憶えていたのですが，平成5年11月28日付の手書きの書面には，ほとんど思い出せないようなことが書いてありました。

　市場急配センターで加賀市の大同工業に行ったのは，一度しか記憶になかったのですが，平成5年11月28日付の手書きの書面によると，往復の荷物だったというのです。帰りに運んだのが空タックなどとなっていました。それ以前の記憶でも荷物はホイールだったと思っていました。

　ホイールと聞いていましたが，乗用車やトラックのホイールではなかったとも思います。ラックに載せて運ぶホイールだったのでしょう。なんとなくは憶えていますが，特殊そうなものに見えたと思います。

　平成5年11月28日付の手書きの書面では，さらに驚くことが記述されていて，同じ宇都宮市行きの仕事を前にもやって3月24日の運行は2度目だったというのです。私は3月24日を間違って2月24日としていることも，最初は考えていました。

　けっこう細かく事実が書いてありましたが，それでも隙間のようなものがあって，思い出すこともできずもどかしさを感じていました。前にも同じ仕事で宇都宮市に行っているとすると，2月24日の可能性があるようにも思えてきました。

　たぶん2月24日というのは，運行上は，愛媛県の松山市の近くで積み込んだイヨカンの荷物を，新潟でおろしたことになっているはずですが，夜中に新潟で荷下ろしをして，夜中の2時か3時頃には金沢に戻っていました。

　このときも諸江の24時間営業のような酒屋のコンビニのような店で買い物をし，市場急配センターの会社に戻ってから1時間ぐらいは，大型トラックの運転席で，被告発人多田敏明と話をしていたはずです。新潟への運行に彼を同乗させていました。

　今，業務日報で確認したところ，2月24日から26日は，確かに協共でホイル，宇都宮となり，帰り荷が石灰で，丸一が荷主，栃木から七尾となっていました。小杉インターで降りた領収書が8,400円となっています。

　ちょうどその頃に，栃木県内で石灰を積んで七尾市に向かったとき，関越トンネルで通行止めに遭遇し，大渋滞で七尾市に着いたのが夕方近くということがありました。

　午後になっていたと思いますが，大渋滞から抜け出し，関越道に乗ったのは，はっきり思い出せないですが，越後川口インターの辺りだったと思います。今，Googleマップで場所をみると，小千谷市の近くでした。

　小千谷市の次が，北陸自動車道との分岐点にもなる長岡市になります。余り思い出せないのですが，これを見ても関越トンネルだけの通行止めではなく，湯沢インターから次に通行止め解除に関越道のインターに乗るまで，早朝から午後まで時間が掛かったように思います。

　他の領収書をみていると，2月13日に富山インターで降りたのが10,800円となっていました。山三青果の仕事なので，この時期なら群馬県の高崎インターから乗っていた可能性が高いと思います。

　栃木から七尾市に向かったときは，富山インターの一つ先の小杉インターで降りています。その料金が8,400円だと，通行止めに遭い新潟県内の関越道のインターから乗っていた可能性も出てきそうです。これはいずれも大型車の料金になります。

　以前，この2月下旬とも3月上旬の運行とも考えていた，我孫子警察署で大型車の通行許可証をもらった運行が，運行日報の記録で，2月13日付の通行許可申請書を確認しています。午前2時から午前10時までともなっています。

　2月12日付として花園インターで降りた領収書が11,050円となっています。日付が変わる前に降りていたようですが，当時の高速道路の領収書に時間の刻印はありません。これもどこのインターから乗ったのか気になっています。

　ふと，給油の領収書を見たところ，3月1日付で，「R-8カナザワSS」となっていて，時刻は13時30分となっています。今頃気がついたのですが，太陽鉱油のカードは，市場急配センターではなく金沢市場輸送のようです。「カナザワイチバ　ユソ」となっています。

　運行が2月28日から3月1日となっていたので，これもcalコマンドで確認したところ平成4年は2月が29日までありました。太陽鉱油の領収書は国道8号金沢という意味の記載でしたが，場所はほとんど河北郡津幡町で，検問所の近くだったと思います。

　13時30分に津幡で給油となると，高岡市の中越パルプに荷積みに向かっていた可能性があります。道も混む昼に津幡に給油に行ったことは少なく，一度だけ，急に入った仕事で北陸ハイミールから七尾市に向かうときに，立ち寄り給油をしました。能瀬からの電話の時です。

　市場急配センターの業務日報と領収書ですが，被告発人松平日出男は見つからないといって3月分は渡してくれませんでした。

　2月28日から3月1日の業務日報には，荷主が「北都ん」となっています。運行指示書にも同じ「北都ん」とあるのでまねたのかもしれないですが，おかしな書き方です。それに北都運輸ならば，前年7月の7月頃には，倒産したと新聞に出ていました。

　積み荷と思われる「品名」の項目が，「B脂」とあり，小松市からの積み込みとなっていますが，これはよく憶えている仕事でした。食肉の工場に皮を剥いだ大きな牛が上からぶら下げられていました。けっこう衝撃の光景でした。

　運行指示書には大宮，業務日報には埼玉県大利根とありますが，この多分牛脂の荷物の卸先は，東北自動車道を走行中に見える工場であったように思います。たしか地名が羽生などとなっていたように思います。

　そもそも大宮というのが，東北自動車道からは離れているのではないかと思います。大利根というのは聞いたことがありますが，調べてみないと場所がわかりません。

　Googleマップで検索しても大利根という地名は見当たらないものの，情報が加須市に集中しています。その加須市の左上には羽生市が見えました。

　国道125号線が，栗橋で国道4号線にぶつかっていますが，その辺りもよく通行する道路でした。馬鈴薯を運んだ東京の大田市場から古河市に向かうときも，栗橋で国道125線から国道4号線に出ていました。

　加賀市の大同工業で荷物を積み出発してからは，国道8号線沿いの北陸食堂で食事をしたように平成5年11月28日付の手書きの書面には書いてありましたが，被告発人多田敏明を連れて，岐阜県大垣市から石灰を積んできた帰りも，北陸食堂に立ち寄ったようなことが記述されていました。

　ざっと2月の業務日報に目を通したところ，2月14日に大阪の本場市場に行き，空荷で戻っていたのも意外でしたが，その次の運行の出発が2月17日となっていました。

　その2月17日の業務日報には，小林運送の仕事で，豊橋から小松・金沢となっていますが，渥美と書いてあったところに訂正線が入り，下に豊橋と書き込んであります。空荷で向かった運行になりそうですが，名北の市場で馬鈴薯をおろしたあとに向かったものと考えていました。

　平成5年11月28日付の手書きの書面では，栃木県での石灰の積み込み先を，葛生町と鍋山に分けていました。今，Googleマップで確認すると鍋山が栃木市だったのは納得したのですが，葛生町が佐野市になっているのは，ちょっと驚きでした。当時は郡部だったような気もします。

　そういえば阿蘇に似た漢字の郡部があったことを思い出しました。調べたところ「安蘇郡」とあります。読み方まで熊本県の阿蘇と同じ「あそ」ぐんのようです。

　宇都宮市内から石灰を積みに向かうのに，どの道を通ったのかも気になるところですが，余り記憶にはないものの一度だけ，佐野市内とは，逆方向から向かったような記憶は漠然ですが，あったような気もします。

***** 協共運送の仕事だった加賀市の大同工業から栃木県宇都宮市への運行

　業務日報にも荷主が「協共」とあるのですが，協共運送のことだと思います。あるいは協共運輸かもしれないのですが，河北郡津幡町の国道沿いにある運送会社でした，立ち寄ったことはなかったですが，広い道路で会社の前を通過したことはありました。

　金沢市場輸送の藤田さんが再就職先としたと聞いていた運送会社になります。平成5年11月28日付の手書きの書面に協共運送の仕事で宇都宮市という記述を見たとき，ちょっと驚いたように思います。

　協共運送のことで強く記憶にあるのは2月の初めの九州，福岡市への運行でした。九州に協共運送の営業所があるらしく，九州自動車道から何度か電話を掛けさせられていました。

　福岡県の福岡市と久留米市の間で佐賀県になる鳥栖市は，九州の交通の大きな分岐点となり，長距離トラックのガソリンスタンドが多く，トラックステーションもある場所でした。中西運輸商でも帰りの荷物待ちで，よく連絡待ちで待機をさせられていた場所になります。

　それだけに思い出の場所でもありましたが，一晩泊まるといたたまれなくなり，私は被告発人松平日出男に空車で帰ると言って，九州自動車道に乗ったのです。鳥栖インターから太宰府インターがあって，その先が福岡インターだったと思います。

　その太宰府インターと福岡インターの間の辺りに，パーキングエリアがあって，被告発人松平日出男の強めの指示で，そこから協共運送に電話を掛けさせられていたのですが，中西運輸商のとき一緒だった運転手が，代わる代わる電話口に出ました。

　一人は口髭と顎髭がつながった人で，よくある名前の人でしたが，福岡県大牟田市に家があると聞いていました。もう一人は，九州出身なのか憶えておらず，関西弁だったと思うTさんでした。

　当時の石川郡野々市町に大きな立派なマンションがあって，飲み屋のママらしい女性と同棲をしていて，一度遊びに行ったことがありました。女性とあったのもその場が初めてだったと思います。

　そのあと平成2年か，あるいは平成3年の春先になるのか，一度，国道8号線沿いから少しだけ離れた小さな工業団地のような場所，当時の能美郡，現在の能美市になる川北町と思います。そこに仕事に行ったとき，行った先の工場で，Tさんに出会い，驚いたことがありました。

　同じ工場か確認できませんが，ちょうど同じ工業団地にある工場が，オウム真理教の教団に買収され，アジトのようになっていたと，何かの情報で知りました。

オカムラ鉄工乗っ取り事件 - Wikipedia https://t.co/qpW4aHqD04
社長は教団の在家信者で、教祖の麻原彰晃に相談したことから、

教団が経営に関与することになった。麻原は「2ヶ月で無借金経営にする」と豪語し、1992年（平成4年）9月14日に自らが社長に就任
した。

　社長がオウム真理教の在家信者という情報は初めて見たように思います。穴水町に別荘地があって，国道249号線からは離れているので，滅多に通る場所ではないのですが，そこもオウム真理教で死刑を免れた主犯格の医師の潜伏先だったという情報を見かけています。

　オカムラ鉄工は，川北町ではなく寺井町とありました。そもそも川北町には工業団地がないのかもしれず，工業団地という名称は記憶にないのですが，国道8号線が間近に見える場所に，工場がいくつかあって，工業団地らしい感じにはなっていました。

1 麻原を石川県で見た！ オカムラ鉄工 岐部哲也、林郁雄逮捕 松本剛 -
YouTube https://t.co/RBnBhmOZTq

　今，Googleマップで寺井町を調べてみると，驚くほど狭い範囲でした。昭和61年には，朝のマルエーの鮮魚の配達で，松任店，美川店，そしてこの寺井店が毎日の配達先でした。手取川から小松市側になるようですが，手取フィッシュランドの住所も能美市粟生町となっています。

　今は白山市となっている松任市ですが，松任市と小松市の間には，海にも面した美川町と，国道8号線から山側の寺井町が，知名度の高い地名としてよく見聞きしていたものです。道路の標識にも美川と寺井がよくありました。

　中西運輸商でメインの仕事だったのは佐川急便の広島・九州便で，福岡市内には福岡店と，東福岡店がありました。九州のコードは01から09だったと思いますが，東福岡店は014などとなっていたように思います。

　福岡店は太宰府インターで降りて，福岡市内に戻るかっこうで，国道3号線沿いの右手にありました。金沢市場輸送で多かったトナミ運輸の福岡便も，その先になりますが，福岡市内に入った頃の左手に，九州西武運輸の会社があり，そこで荷下ろしをしていました。

　佐川急便の福岡店は，九州全域の荷物の中継点となっていて，東福岡店は福岡市内の配達を拠点としているようでした。中西運輸商で，帰り荷として荷物を積んだのは，東福岡店になります。住所は思い出深くもある箱崎になっていたかもしれないですが，国道3号線よりは山側でした。

　もともと中西運輸商で一緒だったYTと藤田さんは，中西運輸商がやっていた広島・九州便を奪い取り，自分らが配車をするという目的を明らかにし，そこで選んだ運送会社が，なじみでもある私が運転手をしていた金沢市場輸送になります。

　金沢市場輸送を退社したあとの，再就職先が，YTは守田水産輸送の子会社であった金沢市示野に事務所があるという都商事，藤田さんが河北郡津幡町の協共運送という違いはありました。

　この話は，もともとあのワンマン社長の中西運輸商から仕事を奪うという点で引っ掛かりがあったのですが，平成2年2月の初めに福岡の協共運送の営業所に電話をさせられた時点では，目的を達成したのかと思える状況でした。

　なお，私は一度だけ，金沢市場輸送の保冷車7599号で，中西運輸商の下請けとして，佐川急便の九州便をやったのですが，当時，戦前の軍隊のような教育が徹底していた佐川急便では，会う佐川急便の社員すべてに挨拶をするという決まりで，金沢市場輸送の運転手は端から相手にしていませんでした。

　今では全く情報を見かけないので，知らない人が多そうですが，当時の佐川急便というのは，軍隊式の過酷な労働で有名を馳せていました。私が長距離の仕事をしていた昭和60年は，ちょうどその分岐点で，山口支店にも査察が入り，しばらく待機するように指示を受けたことがあります。

　もう少しあとには，大きな政治問題となった佐川急便で，当時の創始者でカリスマ的存在とされた佐川急便のトップが，金沢市内の女友達を車で送迎した病院で，裁判所の追及を阻止していたことは，金沢刑務所の拘置所にいるときに，ニュースで見たという記憶もあります。

　時刻は21時41分になります。台所で午後に冷蔵庫に入れ，半解凍状態となっていたキンキを焼いて食べたのですが，思い以上の期待外れで，まるで赤魚でした。アメリカ産となっていたので，余り期待はしていなかったのですが，250ｇぐらいはあったので，いくらかの期待はありました。

　事前にネットで調べたところ，アメリカ産というキンキは，アラスカ産の可能性がありそうです。キンキはロシア産の冷凍もあるという情報でした。アジやサバもそうですが，近年は脂の落ちた魚が目立っているとも感じるところで，地球規模の環境の変化になるのかもしれません。

　今日もどんたく宇出津店では，銀ダラの弁当が半額で1つだけ残っていて，最初に手に取ったのですが，あとにはコンブ巻きのサバの寿司に寿司に交換しました。値段も半分ぐらいだったと思います。鮮魚には石川県産の鱈の切り身も目立ったので，確認をしたのですが，やはり銀ダラとなっていました。

　YTが私に金沢市場輸送で中西運輸商の広島・九州便を引き継ぐため配車係をしたいと連絡を寄越した頃，一度，彼の自宅に行ったのですが，それも松任市の外れで川北町に近い，オレンジ団地という振興の住宅地の集合住宅でした。

　以前の検索では情報が出てきたのですが，今，Googleマップでオレンジ団地を検索すると，情報が見つかりませんなどと出てきました。

　Googleで「松任市　オレンジ団地」，「石川県　オレンジ団地」と検索をしても情報が見つからなくなっているようです。Twilogには情報が残っていると思います。

▶▶▶　kk_hironoのリツイート　▶▶▶

- RT
kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）
日時：2020-08-23 21:56／2018/12/04 16:11 URL：
https://twitter.com/kk_hirono/status/1297518192407924736
https://twitter.com/kk_hirono/status/1069851697789382661


団地といっても、大きなところではなく、公設の住宅とも聞いてはいなかったように思うのですが、名称が変わっていたので、よく憶えています。まだ調べたことはないのですが、「オレンジ団地」と聞いていました。あるいは平仮名で「おれんじ団地」とも考えられます。

▶▶▶　kk_hironoのリツイート　▶▶▶

- RT
kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）
日時：2020-08-23 21:57／2018/12/04 16:13 URL：
https://twitter.com/kk_hirono/status/1297518219960283137
https://twitter.com/kk_hirono/status/1069852186966802432


Googleマップでは、「オレンジ団地」としても「おれんじ団地」としても該当はありませんでした。全国的に見れば、ありそうに思っていたのですが、思っていた以上に珍しい名称だったようです。

▶▶▶　kk_hironoのリツイート　▶▶▶

- RT
kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）
日時：2020-08-23 21:57／2018/12/04 16:18 URL：
https://twitter.com/kk_hirono/status/1297518277241925633
https://twitter.com/kk_hirono/status/1069853461003423744


Googleで、オレンジ団地や白山市、松任市との組み合わせで調べましたが、それらしい情報は見つかりませんでした。当時の松任市の最果てのような場所で、新しい建物だったことも記憶に残っています。

▶▶▶　kk_hironoのリツイート　▶▶▶

- RT
kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）
日時：2020-08-23 21:57／2018/12/04 16:27 URL：
https://twitter.com/kk_hirono/status/1297518350671568897
https://twitter.com/kk_hirono/status/1069855629924171777


Googleマップでそれらしい場所を見ていると、先ほどの検索結果で少し見かけていた「信開ウェラコートオレンジ」というのが出てきました。ただの建物の名称だと思っていたのですが、新開オレンジマンション、A棟、B棟が隣接しています。通称がオレンジ団地だったのかもしれません。

▶▶▶　kk_hironoのリツイート　▶▶▶

- RT
kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）｜kk_hirono（刑事告発・非常上告＿金沢地方検察庁御中）
日時：2020-08-23 21:57／2018/12/04 16:30 URL：
https://twitter.com/kk_hirono/status/1297518417218400256
https://twitter.com/kk_hirono/status/1069856452947263488


YTが金沢市黒田に住むようになったのは、そのあとだったのかもしれません。オレンジ団地の住所は源兵島町になるのかもしれません。聞いたことはない地名ですが、道路標識としては見かけていたような気もします。

刑事告発・非常上告＿金沢地方検察庁御中(\@kk_hirono)/「オレンジ団地」の検索結果
- Twilog https://t.co/pogz84nhto

奉納＼さらば弁護士鉄道・泥棒神社の物語(\@hirono_hideki)/「オレンジ団地」の検索結果
- Twilog https://t.co/XosVt14JWg ツイ ートが見つかりませんでした

　もう8年ほど前になると思いますが，昼に宇出津新港の堤防の先端近くの曲がり角付近で魚釣りをしている人と，会話をしていたところ，YTの運送会社で運転手をしたいたという話を聞きました。余り記憶に残っていませんが，釣り道具の小物がとても多かったことが印象に残っています。

　記憶が薄れているものの，YTが経営する運送会社は，金沢市内でも木越の近くと聞いたようにも思います。木越というのは金沢東インターの近くで，その後に瑞樹団地という住宅地もできていますが，佐川急便の近くでもありました。

　被告発人安田敏が私に，金沢市場輸送の山田さんがその後に始めた運送会社で，しばらく働いていたというのも，場所が木越という話でした。運送会社があるような場所として考えられたのは，木越でも河北郡内灘町との間で，ちょうどその辺りには被告発人浜口卓也の浜口商運の会社がありました。

浜口商運 - Google 検索 https://t.co/f0pI29A2q9 https://t.co/f0pI29A2q9

　数年ぶりに浜口商運で検索をしてみると，以前と同じような求人募集の情報だけが集中して出てきましたが，代表者の名前は見当たらず，以前と同じような建物の写真は見当たりました。もう何年前かと思いますが，当時と変わらぬGoogle検索の結果になります。

大網商事 - Google 検索 https://t.co/iHU3nsnA9l

　大網商事でも同様に検索をしてみたところ，2件ほど以前と同じような求人募集の情報が出てきましたが，2015年11月辺りの情報で止まっているようです。被告発人大網健二の兄，関係者OSNの鳶職の有限会社になります。

　2月3日に出発した市場急配センターでの九州福岡市へのミールを運んだ運行は，事前の2月1日に被告発人安田繁克が不自然な参上をしたこと，当日の2月3日に，被害者安藤文さんが裏駐車場の駐車をやめたことなどでも，私に大きな影響を与え，綿密に練られた計画性を窺わせる重大な事実です。

　はっきり指摘をしておきますが，中西運輸商で私に掛けられた保険金が目的で，一連の被害者安藤文さんを被害者に巻き込んだ私こと廣野秀樹に対する保険金目的殺害の計画性がありうるところであり，徹底した捜査は，もうずっと昔に御庁つまり金沢地方検察庁にもお願いをしたいたはずです。

　YTについては，被告発人安田敏とも私の東力のアパートで直接出会った面識がありましたが，その後に聞いた話では，被告発人浜口卓也とも商売関係での付き合いがあり，一緒に飲みに行ったというような話も聞いていました。

　この殺人計画が仮に事実であるとすれば，悪質の極みであり，関係者全員を無期懲役刑に処するべきだと，前にも書いたように思いますが，改めて申し添えをしておきます。重ねておきますが，二度と社会に戻ることのない無期懲役刑になります。

　ことの重大さに比較し，確証を持てないのでYTのことは，仮名としてきました。確証が持てず，被疑者だと決めつけられないのも事実になります。被告発人安田繁克のことなど接点はありますが，間接的な関与になるので，重ねておきますが，殺人計画の共犯者とは，はるかに断定ができません。

　明らかに虚偽の事実を私に吹き込んだと思われる被告発人浜口卓也とは事情も違います。被害者安藤文さんが被告発人安田繁克と交際していたという事実ではない可能性の高い話を，弁当の具体的事実を交え，私に最初に吹き込んだのが被告発人浜口卓也になります。1月21日の夜のことです。

　何のためにありもしない事実をでっち上げたのかという疑惑から始まる問題になりますが，本件殺人未遂事件としての真相解明には欠かすことのできないのが被告発人とした被告発人浜口卓也のことで，これは被告発人大網健二との関わりも大きなものとなります。

　その後の関係は全く確認をしていませんが，被告発人大網健二は，ちょうど一年ほど前の昭和59年4月頃の金沢市場輸送の入社と同じく，少し期間は短く6月頃までだったと思いますが，私の紹介で中西運輸商に入社し，4トン車で長距離運転手の仕事をしていました。

　金沢市場輸送の竹沢俊寿社長は，私に中西運輸商の社長の窮地をお金で救ってやったと私に何度か話したことがあり，その中西運輸商の社長，中西富も私に対して，金沢市場輸送の竹沢俊寿の話題で，意味ありげな苦笑いの表情を見せたことがありました。七尾市石崎町出身という中西の社長になります。

　中西運輸商では生命の危険を感じる運行が普通にありました。当時は若気の至りというのか，あえてその今で言うブラック企業性に飛び込んでいた私ですが，事故死で保険金が入る可能性が高いとして，会社で保険金を掛けられていた可能性はあると思います。警察，検察では確認済みのこととも思います。

　中西運輸商はそのブラック企業性と事故の多さで，佐川急便の広島・九州便から切られたと聞いていました。九州の運転手が大半以上だった中西運輸商ですが，終わりの頃は，今で言うブラック企業性で，大きな暴力団から脅しを掛けられていたという話もありました。

　身内思いで近親愛が強いとも感じた七尾市石崎町出身の中西運輸商の社長，中西冨になりますが，稼げるときに思いっきり稼いで，その後は稼いだ金で悠々自適の生活をするという人生設計が，当時は社会経験が乏しかった私にもうかがえるところの公明正大な露骨さがありました。

　一枚かんだのは後発の被告発人松平日出男だった可能性もありそうに思えるところがあります。被告発人松平日出男も中古車販売の経営の経験とともに，車の保険に関しても精通していたらしく金沢市場輸送の保険の問題も一手に担当していた様子です。能生町と北九州の事故のことがありました。

　これも過去の記録では再三指摘してきたところと思います。中西運輸商の延長上に保険金目的の私に対する殺人計画があり，それに被害者安藤文さんが巻き込まれた可能性というのは，徹底した捜査と事実であれば苛烈を極める無期懲役刑の処罰が金沢地方検察庁に求められる公益性になります。

*** 平成4年4月1日の傷害・準強姦事件

* [EDIT] 本件告発状の作成及び公開について

** 作成

*** Linux（Ubuntu）

**** Wordファイルの告発状をEmacsのorg-modeのorg形式に変換し再編集（2020年9月18日）


