*** 被告発人浜口卓也との関係

**** 浜口邸新築工事のWordファイル
   　正確な時期は過去の書面に記載があると思いますが，平成9年の秋頃のことで，冬に近かったかもしれないですが，陽光穏やかな午後のことでした。被告発人大網健二が何か理由をつけ，私に自分が仕事で使っているノートパソコンをあずけたのです。

   　彼のノートパソコンのメーカーは忘れてしまいましたが，メビウスというシリーズだったと思います。CDとフロッピーディスクを機器の着脱で使い分けるという仕組みになっていていました。35万円ぐらいで買ったように聞いたと思います。

   　ファイルの整理のようなことを頼まれたと思いますが，余り要領を得ない頼みごとでした。当時のパソコ
   ンはWindows98ではなかったかと思います。あるいはまだWindows95だったかもしれません。

   　ファイルは一般的なドキュメントフォルダの中に保存されていたとも思いますが。仕事で使っている割にはファイルの数が少なすぎると感じました。特定のファイルを目立たせ，私に気づかせるのが目的だったと考えられます。

   　その被告発人大網健二が目的にしたと考えられるのが，浜口邸新築工事などとしたファイル名のファイルで，Word文書になっていたと思います。ファイルの中身は見積書のようなものでした。ページ数で長くて2,3枚だったと思います。1ページだったかもしれません。

   　大雑把にしか記憶にないですが，全部で4千万円ほどの見積もりで，頭金が1千万円ほどになっていました。場所は金沢市粟崎です。当時，地図で場所を確認することはなかったですが，河北郡内灘町と隣接している一部に海沿いを含む一帯という感覚でした。

   　今は記憶が薄れていて正確なことは過去の書面に記述があると思いますが，この時点で，被告発人大網健二とは浜口邸新築工事について会話はしていないかもしれません。被告発人大網健二の方で被告発人浜口卓也にふれる話題は避けていたとも考えられます。

   - 877：2020-09-05_11:12:24 ＊ 金沢市粟崎町について https://hirono-hideki.hatenadiary.jp/entry/2020/09/05/111222

**** 何度も前を通っているのに被告発人大網健二がずっと黙っていた浜口商運のトラック駐車場
　こちらは参考資料の作成から始めたいと思います。住所はぎりぎり金沢市西念町になるのかと思いますが，この金沢市西念も西念と西念町があったり，かなりややこしくなります。






